<?php
/**
 * Republic of Austria states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'AT' => [
		'EIST' => __( 'Eisenstadt Stadt', 'ry-wc-city-select' ),
		'EI' => __( 'Eisenstadt-Umgebung', 'ry-wc-city-select' ),
		'GRST' => __( 'Graz Stadt', 'ry-wc-city-select' ),
		'INST' => __( 'Innsbruck Stadt', 'ry-wc-city-select' ),
		'KLWO' => __( 'Klagenfurt am Woerthersee', 'ry-wc-city-select' ),
		'KRDEDOST' => __( 'Krems an der Donau Stadt', 'ry-wc-city-select' ),
		'LIST' => __( 'Linz Stadt', 'ry-wc-city-select' ),
		'POBEAM' => __( 'Politischer Bezirk Amstetten', 'ry-wc-city-select' ),
		'POBEBA' => __( 'Politischer Bezirk Baden', 'ry-wc-city-select' ),
		'POBEBL' => __( 'Politischer Bezirk Bludenz', 'ry-wc-city-select' ),
		'POBEBRIN' => __( 'Politischer Bezirk Braunau am Inn', 'ry-wc-city-select' ),
		'POBEBR' => __( 'Politischer Bezirk Bregenz', 'ry-wc-city-select' ),
		'POBEBRDELE' => __( 'Politischer Bezirk Bruck an der Leitha', 'ry-wc-city-select' ),
		'POBEBR2' => __( 'Politischer Bezirk Bruck-Muerzzuschlag', 'ry-wc-city-select' ),
		'POBEDE' => __( 'Politischer Bezirk Deutschlandsberg', 'ry-wc-city-select' ),
		'POBEDO' => __( 'Politischer Bezirk Dornbirn', 'ry-wc-city-select' ),
		'POBEEF' => __( 'Politischer Bezirk Eferding', 'ry-wc-city-select' ),
		'POBEFE' => __( 'Politischer Bezirk Feldkirch', 'ry-wc-city-select' ),
		'POBEFE2' => __( 'Politischer Bezirk Feldkirchen', 'ry-wc-city-select' ),
		'POBEFR' => __( 'Politischer Bezirk Freistadt', 'ry-wc-city-select' ),
		'POBEGA' => __( 'Politischer Bezirk Gaenserndorf', 'ry-wc-city-select' ),
		'POBEGM' => __( 'Politischer Bezirk Gmuend', 'ry-wc-city-select' ),
		'POBEGM2' => __( 'Politischer Bezirk Gmunden', 'ry-wc-city-select' ),
		'POBEGR' => __( 'Politischer Bezirk Graz-Umgebung', 'ry-wc-city-select' ),
		'POBEGR2' => __( 'Politischer Bezirk Grieskirchen', 'ry-wc-city-select' ),
		'POBEGU' => __( 'Politischer Bezirk Guessing', 'ry-wc-city-select' ),
		'POBEHA' => __( 'Politischer Bezirk Hallein', 'ry-wc-city-select' ),
		'POBEHA2' => __( 'Politischer Bezirk Hartberg-Fuerstenfeld', 'ry-wc-city-select' ),
		'POBEHE' => __( 'Politischer Bezirk Hermagor', 'ry-wc-city-select' ),
		'POBEHO' => __( 'Politischer Bezirk Hollabrunn', 'ry-wc-city-select' ),
		'POBEHO2' => __( 'Politischer Bezirk Horn', 'ry-wc-city-select' ),
		'POBEIM' => __( 'Politischer Bezirk Imst', 'ry-wc-city-select' ),
		'POBEINLA' => __( 'Politischer Bezirk Innsbruck Land', 'ry-wc-city-select' ),
		'POBEJE' => __( 'Politischer Bezirk Jennersdorf', 'ry-wc-city-select' ),
		'POBEKIDEKR' => __( 'Politischer Bezirk Kirchdorf an der Krem', 'ry-wc-city-select' ),
		'POBEKI' => __( 'Politischer Bezirk Kitzbuehel', 'ry-wc-city-select' ),
		'POBEKLLA' => __( 'Politischer Bezirk Klagenfurt Land', 'ry-wc-city-select' ),
		'POBEKO' => __( 'Politischer Bezirk Korneuburg', 'ry-wc-city-select' ),
		'POBEKR' => __( 'Politischer Bezirk Krems', 'ry-wc-city-select' ),
		'POBEKU' => __( 'Politischer Bezirk Kufstein', 'ry-wc-city-select' ),
		'POBELA' => __( 'Politischer Bezirk Landeck', 'ry-wc-city-select' ),
		'POBELE' => __( 'Politischer Bezirk Leibnitz', 'ry-wc-city-select' ),
		'POBELE2' => __( 'Politischer Bezirk Leoben', 'ry-wc-city-select' ),
		'POBELI' => __( 'Politischer Bezirk Lienz', 'ry-wc-city-select' ),
		'POBELI2' => __( 'Politischer Bezirk Liezen', 'ry-wc-city-select' ),
		'POBELI3' => __( 'Politischer Bezirk Lilienfeld', 'ry-wc-city-select' ),
		'POBELI4' => __( 'Politischer Bezirk Linz-Land', 'ry-wc-city-select' ),
		'POBEMA' => __( 'Politischer Bezirk Mattersburg', 'ry-wc-city-select' ),
		'POBEME' => __( 'Politischer Bezirk Melk', 'ry-wc-city-select' ),
		'POBEMI' => __( 'Politischer Bezirk Mistelbach', 'ry-wc-city-select' ),
		'POBEMO' => __( 'Politischer Bezirk Moedling', 'ry-wc-city-select' ),
		'POBEMU' => __( 'Politischer Bezirk Murau', 'ry-wc-city-select' ),
		'POBEMU2' => __( 'Politischer Bezirk Murtal', 'ry-wc-city-select' ),
		'POBENE' => __( 'Politischer Bezirk Neunkirchen', 'ry-wc-city-select' ),
		'POBENESE' => __( 'Politischer Bezirk Neusiedl am See', 'ry-wc-city-select' ),
		'POBEOB' => __( 'Politischer Bezirk Oberpullendorf', 'ry-wc-city-select' ),
		'POBEOB2' => __( 'Politischer Bezirk Oberwart', 'ry-wc-city-select' ),
		'POBEPE' => __( 'Politischer Bezirk Perg', 'ry-wc-city-select' ),
		'POBERE' => __( 'Politischer Bezirk Reutte', 'ry-wc-city-select' ),
		'POBERIIN' => __( 'Politischer Bezirk Ried im Innkreis', 'ry-wc-city-select' ),
		'POBERO' => __( 'Politischer Bezirk Rohrbach', 'ry-wc-city-select' ),
		'POBESA' => __( 'Politischer Bezirk Salzburg-Umgebung', 'ry-wc-city-select' ),
		'POBESAJOPO' => __( 'Politischer Bezirk Sankt Johann im Ponga', 'ry-wc-city-select' ),
		'POBESAPO' => __( 'Politischer Bezirk Sankt Poelten', 'ry-wc-city-select' ),
		'POBESAVEDEGL' => __( 'Politischer Bezirk Sankt Veit an der Gla', 'ry-wc-city-select' ),
		'POBESC' => __( 'Politischer Bezirk Schaerding', 'ry-wc-city-select' ),
		'POBESC2' => __( 'Politischer Bezirk Scheibbs', 'ry-wc-city-select' ),
		'POBESC3' => __( 'Politischer Bezirk Schwaz', 'ry-wc-city-select' ),
		'POBESPDEDR' => __( 'Politischer Bezirk Spittal an der Drau', 'ry-wc-city-select' ),
		'POBEST' => __( 'Politischer Bezirk Steyr-Land', 'ry-wc-city-select' ),
		'POBESU' => __( 'Politischer Bezirk Suedoststeiermark', 'ry-wc-city-select' ),
		'POBETA' => __( 'Politischer Bezirk Tamsweg', 'ry-wc-city-select' ),
		'POBETU' => __( 'Politischer Bezirk Tulln', 'ry-wc-city-select' ),
		'POBEUR' => __( 'Politischer Bezirk Urfahr-Umgebung', 'ry-wc-city-select' ),
		'POBEVILA' => __( 'Politischer Bezirk Villach Land', 'ry-wc-city-select' ),
		'POBEVO' => __( 'Politischer Bezirk Voecklabruck', 'ry-wc-city-select' ),
		'POBEVO2' => __( 'Politischer Bezirk Voelkermarkt', 'ry-wc-city-select' ),
		'POBEVO3' => __( 'Politischer Bezirk Voitsberg', 'ry-wc-city-select' ),
		'POBEWADETH' => __( 'Politischer Bezirk Waidhofen an der Thay', 'ry-wc-city-select' ),
		'POBEWE' => __( 'Politischer Bezirk Weiz', 'ry-wc-city-select' ),
		'POBEWINE' => __( 'Politischer Bezirk Wiener Neustadt', 'ry-wc-city-select' ),
		'POBEWO' => __( 'Politischer Bezirk Wolfsberg', 'ry-wc-city-select' ),
		'POBEZESE' => __( 'Politischer Bezirk Zell am See', 'ry-wc-city-select' ),
		'POBEZW' => __( 'Politischer Bezirk Zwettl', 'ry-wc-city-select' ),
		'RUST' => __( 'Rust Stadt', 'ry-wc-city-select' ),
		'SAST' => __( 'Salzburg Stadt', 'ry-wc-city-select' ),
		'SAPOST' => __( 'Sankt Poelten Stadt', 'ry-wc-city-select' ),
		'STST' => __( 'Steyr Stadt', 'ry-wc-city-select' ),
		'VIST' => __( 'Villach Stadt', 'ry-wc-city-select' ),
		'WADEYBST' => __( 'Waidhofen an der Ybbs Stadt', 'ry-wc-city-select' ),
		'WEST' => __( 'Wels Stadt', 'ry-wc-city-select' ),
		'WE' => __( 'Wels-Land', 'ry-wc-city-select' ),
		'WIST' => __( 'Wien Stadt', 'ry-wc-city-select' ),
		'WINEST' => __( 'Wiener Neustadt Stadt', 'ry-wc-city-select' ),
		'BU' => __( 'Burgenland', 'ry-wc-city-select' ),
		'KA' => __( 'Kaernten', 'ry-wc-city-select' ),
		'NI' => __( 'Niederoesterreich', 'ry-wc-city-select' ),
		'OB' => __( 'Oberoesterreich', 'ry-wc-city-select' ),
		'SA' => __( 'Salzburg', 'ry-wc-city-select' ),
		'ST' => __( 'Steiermark', 'ry-wc-city-select' ),
		'TI' => __( 'Tirol', 'ry-wc-city-select' ),
		'VO' => __( 'Vorarlberg', 'ry-wc-city-select' ),
		'WI' => __( 'Wien', 'ry-wc-city-select' ),
	]
];