<?php
/**
 * Republic of Azerbaijan states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'AZ' => [
		'ABRA' => __( 'Absheron Rayon', 'ry-wc-city-select' ),
		'BACI' => __( 'Baku City', 'ry-wc-city-select' ),
		'GORA' => __( 'Goranboy Rayon', 'ry-wc-city-select' ),
		'NAAURE' => __( 'Nakhchivan Autonomous Republic', 'ry-wc-city-select' ),
		'TARA' => __( 'Tartar Rayon', 'ry-wc-city-select' ),
		'AGRA' => __( 'Aghdam Rayon', 'ry-wc-city-select' ),
		'AGRA2' => __( 'Aghdash Rayon', 'ry-wc-city-select' ),
		'AGRA3' => __( 'Aghjabadi Rayon', 'ry-wc-city-select' ),
		'AGRA4' => __( 'Aghstafa Rayon', 'ry-wc-city-select' ),
		'AGRA5' => __( 'Aghsu Rayon', 'ry-wc-city-select' ),
		'ASDI' => __( 'Astara District', 'ry-wc-city-select' ),
		'BARA' => __( 'Balakan Rayon', 'ry-wc-city-select' ),
		'BARA2' => __( 'Barda Rayon', 'ry-wc-city-select' ),
		'BERA' => __( 'Beylagan Rayon', 'ry-wc-city-select' ),
		'BIRA' => __( 'Bilasuvar Rayon', 'ry-wc-city-select' ),
		'DARA' => __( 'Dashkasan Rayon', 'ry-wc-city-select' ),
		'FIRA' => __( 'Fizuli Rayon', 'ry-wc-city-select' ),
		'GARA' => __( 'Gadabay Rayon', 'ry-wc-city-select' ),
		'GACI' => __( 'Ganja City', 'ry-wc-city-select' ),
		'GORA2' => __( 'Gobustan Rayon', 'ry-wc-city-select' ),
		'GORA3' => __( 'Goychay Rayon', 'ry-wc-city-select' ),
		'GORA4' => __( 'Goygol Rayon', 'ry-wc-city-select' ),
		'HARA' => __( 'Hajigabul Rayon', 'ry-wc-city-select' ),
		'IMRA' => __( 'Imishli Rayon', 'ry-wc-city-select' ),
		'ISRA' => __( 'Ismayilli Rayon', 'ry-wc-city-select' ),
		'JADI' => __( 'Jabrayil District', 'ry-wc-city-select' ),
		'JA' => __( 'Jalilabad', 'ry-wc-city-select' ),
		'KADI' => __( 'Kalbajar District', 'ry-wc-city-select' ),
		'KHRA' => __( 'Khachmaz Rayon', 'ry-wc-city-select' ),
		'KHRA2' => __( 'Khizi Rayon', 'ry-wc-city-select' ),
		'KHDI' => __( 'Khojavend District', 'ry-wc-city-select' ),
		'KURA' => __( 'Kurdamir Rayon', 'ry-wc-city-select' ),
		'LARA' => __( 'Lacin Rayonu', 'ry-wc-city-select' ),
		'LARA2' => __( 'Lankaran Rayon', 'ry-wc-city-select' ),
		'LASA' => __( 'Lankaran Sahari', 'ry-wc-city-select' ),
		'LERA' => __( 'Lerik Rayon', 'ry-wc-city-select' ),
		'MADI' => __( 'Masally District', 'ry-wc-city-select' ),
		'MICI' => __( 'Mingacevir City', 'ry-wc-city-select' ),
		'NACI' => __( 'Naftalan City', 'ry-wc-city-select' ),
		'NERA' => __( 'Neftchala Rayon', 'ry-wc-city-select' ),
		'OGRA' => __( 'Oghuz Rayon', 'ry-wc-city-select' ),
		'QARA' => __( 'Qabala Rayon', 'ry-wc-city-select' ),
		'QARA2' => __( 'Qakh Rayon', 'ry-wc-city-select' ),
		'QARA3' => __( 'Qazakh Rayon', 'ry-wc-city-select' ),
		'QURA' => __( 'Quba Rayon', 'ry-wc-city-select' ),
		'QURA2' => __( 'Qubadli Rayon', 'ry-wc-city-select' ),
		'QURA3' => __( 'Qusar Rayon', 'ry-wc-city-select' ),
		'SARA' => __( 'Saatly Rayon', 'ry-wc-city-select' ),
		'SARA2' => __( 'Sabirabad Rayon', 'ry-wc-city-select' ),
		'SARA3' => __( 'Salyan Rayon', 'ry-wc-city-select' ),
		'SARA4' => __( 'Samukh Rayon', 'ry-wc-city-select' ),
		'SHRA' => __( 'Shabran Rayon', 'ry-wc-city-select' ),
		'SHRA2' => __( 'Shaki Rayon', 'ry-wc-city-select' ),
		'SHCI' => __( 'Shaki city', 'ry-wc-city-select' ),
		'SHRA3' => __( 'Shamakhi Rayon', 'ry-wc-city-select' ),
		'SHRA4' => __( 'Shamkir Rayon', 'ry-wc-city-select' ),
		'SH' => __( 'Shirvan', 'ry-wc-city-select' ),
		'SH2' => __( 'Shusha', 'ry-wc-city-select' ),
		'SIRA' => __( 'Siazan Rayon', 'ry-wc-city-select' ),
		'SUCI' => __( 'Sumqayit City', 'ry-wc-city-select' ),
		'SURA' => __( 'Susa Rayonu', 'ry-wc-city-select' ),
		'TORA' => __( 'Tovuz Rayon', 'ry-wc-city-select' ),
		'UJRA' => __( 'Ujar Rayon', 'ry-wc-city-select' ),
		'XASA' => __( 'Xankandi Sahari', 'ry-wc-city-select' ),
		'XORA' => __( 'Xocali Rayonu', 'ry-wc-city-select' ),
		'YARA' => __( 'Yardymli Rayon', 'ry-wc-city-select' ),
		'YECI' => __( 'Yevlakh City', 'ry-wc-city-select' ),
		'YERA' => __( 'Yevlakh Rayon', 'ry-wc-city-select' ),
		'ZARA' => __( 'Zangilan Rayon', 'ry-wc-city-select' ),
		'ZARA2' => __( 'Zaqatala Rayon', 'ry-wc-city-select' ),
		'ZARA3' => __( 'Zardab Rayon', 'ry-wc-city-select' ),
	]
];