<?php
/**
 * Bangladesh states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'BD' => [
		'BA' => __( 'Bagerhat', 'ry-wc-city-select' ),
		'BA2' => __( 'Bandarban', 'ry-wc-city-select' ),
		'BA3' => __( 'Barguna', 'ry-wc-city-select' ),
		'BA4' => __( 'Barisal', 'ry-wc-city-select' ),
		'BH' => __( 'Bhola', 'ry-wc-city-select' ),
		'BO' => __( 'Bogra', 'ry-wc-city-select' ),
		'BR' => __( 'Brahmanbaria', 'ry-wc-city-select' ),
		'CH' => __( 'Chandpur', 'ry-wc-city-select' ),
		'CHNA' => __( 'Chapai Nababganj', 'ry-wc-city-select' ),
		'CH2' => __( 'Chittagong', 'ry-wc-city-select' ),
		'CH3' => __( 'Chuadanga', 'ry-wc-city-select' ),
		'CO' => __( 'Comilla', 'ry-wc-city-select' ),
		'COBA' => __( 'Coxs Bazar', 'ry-wc-city-select' ),
		'DH' => __( 'Dhaka', 'ry-wc-city-select' ),
		'DI' => __( 'Dinajpur', 'ry-wc-city-select' ),
		'FA' => __( 'Faridpur', 'ry-wc-city-select' ),
		'FE' => __( 'Feni', 'ry-wc-city-select' ),
		'GA' => __( 'Gaibandha', 'ry-wc-city-select' ),
		'GA2' => __( 'Gazipur', 'ry-wc-city-select' ),
		'GO' => __( 'Gopalganj', 'ry-wc-city-select' ),
		'HA' => __( 'Habiganj', 'ry-wc-city-select' ),
		'JA' => __( 'Jamalpur', 'ry-wc-city-select' ),
		'JE' => __( 'Jessore', 'ry-wc-city-select' ),
		'JH' => __( 'Jhalokati', 'ry-wc-city-select' ),
		'JH2' => __( 'Jhenaidah', 'ry-wc-city-select' ),
		'JO' => __( 'Joypurhat', 'ry-wc-city-select' ),
		'KH' => __( 'Khagrachhari', 'ry-wc-city-select' ),
		'KH2' => __( 'Khulna', 'ry-wc-city-select' ),
		'KI' => __( 'Kishoregonj', 'ry-wc-city-select' ),
		'KU' => __( 'Kurigram', 'ry-wc-city-select' ),
		'KU2' => __( 'Kushtia', 'ry-wc-city-select' ),
		'LA' => __( 'Lakshmipur', 'ry-wc-city-select' ),
		'LADI' => __( 'Lalmonirhat District', 'ry-wc-city-select' ),
		'MA' => __( 'Madaripur', 'ry-wc-city-select' ),
		'MA2' => __( 'Magura', 'ry-wc-city-select' ),
		'MA3' => __( 'Manikganj', 'ry-wc-city-select' ),
		'MA4' => __( 'Maulvibazar', 'ry-wc-city-select' ),
		'ME' => __( 'Meherpur', 'ry-wc-city-select' ),
		'MU' => __( 'Munshiganj', 'ry-wc-city-select' ),
		'MY' => __( 'Mymensingh', 'ry-wc-city-select' ),
		'NA' => __( 'Naogaon', 'ry-wc-city-select' ),
		'NA2' => __( 'Narail', 'ry-wc-city-select' ),
		'NA3' => __( 'Narayanganj', 'ry-wc-city-select' ),
		'NA4' => __( 'Narsingdi', 'ry-wc-city-select' ),
		'NA5' => __( 'Natore', 'ry-wc-city-select' ),
		'NE' => __( 'Netrakona', 'ry-wc-city-select' ),
		'NIZI' => __( 'Nilphamari Zila', 'ry-wc-city-select' ),
		'NO' => __( 'Noakhali', 'ry-wc-city-select' ),
		'PA' => __( 'Pabna', 'ry-wc-city-select' ),
		'PA2' => __( 'Panchagarh', 'ry-wc-city-select' ),
		'PA3' => __( 'Patuakhali', 'ry-wc-city-select' ),
		'PI' => __( 'Pirojpur', 'ry-wc-city-select' ),
		'RA' => __( 'Rajbari', 'ry-wc-city-select' ),
		'RA2' => __( 'Rajshahi', 'ry-wc-city-select' ),
		'RA3' => __( 'Rangamati', 'ry-wc-city-select' ),
		'RA4' => __( 'Rangpur', 'ry-wc-city-select' ),
		'SA' => __( 'Satkhira', 'ry-wc-city-select' ),
		'SH' => __( 'Shariatpur', 'ry-wc-city-select' ),
		'SH2' => __( 'Sherpur', 'ry-wc-city-select' ),
		'SI' => __( 'Sirajganj', 'ry-wc-city-select' ),
		'SU' => __( 'Sunamganj', 'ry-wc-city-select' ),
		'SY' => __( 'Sylhet', 'ry-wc-city-select' ),
		'TA' => __( 'Tangail', 'ry-wc-city-select' ),
		'TH' => __( 'Thakurgaon', 'ry-wc-city-select' ),
		'BADI' => __( 'Barisal Division', 'ry-wc-city-select' ),
		'DHDI' => __( 'Dhaka Division', 'ry-wc-city-select' ),
		'KHDI' => __( 'Khulna Division', 'ry-wc-city-select' ),
		'MYDI' => __( 'Mymensingh Division', 'ry-wc-city-select' ),
		'RADI' => __( 'Rajshahi Division', 'ry-wc-city-select' ),
		'RADI2' => __( 'Rangpur Division', 'ry-wc-city-select' ),
		'SYDI' => __( 'Sylhet Division', 'ry-wc-city-select' ),
	]
];