<?php
/**
 * Republic of Benin states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'BJ' => [
		'AD' => __( 'Adjaouere', 'ry-wc-city-select' ),
		'AD2' => __( 'Adjara', 'ry-wc-city-select' ),
		'AG' => __( 'Aguegues', 'ry-wc-city-select' ),
		'AK' => __( 'Akpro-Misserete', 'ry-wc-city-select' ),
		'AP' => __( 'Aplahoue', 'ry-wc-city-select' ),
		'AV' => __( 'Avrankou', 'ry-wc-city-select' ),
		'BA' => __( 'Bassila', 'ry-wc-city-select' ),
		'BE' => __( 'Bembereke', 'ry-wc-city-select' ),
		'BO' => __( 'Bonou', 'ry-wc-city-select' ),
		'BO2' => __( 'Boukoumbe', 'ry-wc-city-select' ),
		'CO' => __( 'Cobly', 'ry-wc-city-select' ),
		'CO2' => __( 'Come', 'ry-wc-city-select' ),
		'COAB' => __( 'Commune of Abomey', 'ry-wc-city-select' ),
		'COAB2' => __( 'Commune of Abomey-Calavi', 'ry-wc-city-select' ),
		'COAD' => __( 'Commune of Adjohoun', 'ry-wc-city-select' ),
		'COAG' => __( 'Commune of Agbangnizoun', 'ry-wc-city-select' ),
		'COAL' => __( 'Commune of Allada', 'ry-wc-city-select' ),
		'COAT' => __( 'Commune of Athieme', 'ry-wc-city-select' ),
		'COBA' => __( 'Commune of Banikoara', 'ry-wc-city-select' ),
		'COBA2' => __( 'Commune of Bante', 'ry-wc-city-select' ),
		'COBO' => __( 'Commune of Bohicon', 'ry-wc-city-select' ),
		'COBO2' => __( 'Commune of Bopa', 'ry-wc-city-select' ),
		'COCO' => __( 'Commune of Cove', 'ry-wc-city-select' ),
		'CODA' => __( 'Commune of Dassa-Zoume', 'ry-wc-city-select' ),
		'CODJ' => __( 'Commune of Djidja', 'ry-wc-city-select' ),
		'CODJ2' => __( 'Commune of Djougou', 'ry-wc-city-select' ),
		'COGL' => __( 'Commune of Glazoue', 'ry-wc-city-select' ),
		'COHO' => __( 'Commune of Houeyogbe', 'ry-wc-city-select' ),
		'COKE' => __( 'Commune of Ketou', 'ry-wc-city-select' ),
		'COKP' => __( 'Commune of Kpomasse', 'ry-wc-city-select' ),
		'COOU' => __( 'Commune of Ouesse', 'ry-wc-city-select' ),
		'COOU2' => __( 'Commune of Ouidah', 'ry-wc-city-select' ),
		'COOU3' => __( 'Commune of Ouinhi', 'ry-wc-city-select' ),
		'COPA' => __( 'Commune of Parakou', 'ry-wc-city-select' ),
		'COPO' => __( 'Commune of Pobe', 'ry-wc-city-select' ),
		'COSA' => __( 'Commune of Sakete', 'ry-wc-city-select' ),
		'COSA2' => __( 'Commune of Savalou', 'ry-wc-city-select' ),
		'COSA3' => __( 'Commune of Save', 'ry-wc-city-select' ),
		'COSO' => __( 'Commune of So-Ava', 'ry-wc-city-select' ),
		'COTC' => __( 'Commune of Tchaourou', 'ry-wc-city-select' ),
		'COTO' => __( 'Commune of Toffo', 'ry-wc-city-select' ),
		'COTO2' => __( 'Commune of Tori-Bossito', 'ry-wc-city-select' ),
		'COZA' => __( 'Commune of Za-Kpota', 'ry-wc-city-select' ),
		'COZA2' => __( 'Commune of Zangnanado', 'ry-wc-city-select' ),
		'CO3' => __( 'Commune of Ze', 'ry-wc-city-select' ),
		'COZO' => __( 'Commune of Zogbodome', 'ry-wc-city-select' ),
		'CO4' => __( 'Copargo', 'ry-wc-city-select' ),
		'CO5' => __( 'Cotonou', 'ry-wc-city-select' ),
		'DA' => __( 'Dangbo', 'ry-wc-city-select' ),
		'DJ' => __( 'Djakotomey', 'ry-wc-city-select' ),
		'DOTO' => __( 'Dogbo Tota', 'ry-wc-city-select' ),
		'GO' => __( 'Gogounou', 'ry-wc-city-select' ),
		'GR' => __( 'Grand-Popo', 'ry-wc-city-select' ),
		'IF' => __( 'Ifangni', 'ry-wc-city-select' ),
		'KA' => __( 'Kalale', 'ry-wc-city-select' ),
		'KA2' => __( 'Kandi', 'ry-wc-city-select' ),
		'KA3' => __( 'Karimama', 'ry-wc-city-select' ),
		'KE' => __( 'Kerou', 'ry-wc-city-select' ),
		'KL' => __( 'Klouekanme', 'ry-wc-city-select' ),
		'KO' => __( 'Kouande', 'ry-wc-city-select' ),
		'LA' => __( 'Lalo', 'ry-wc-city-select' ),
		'LO' => __( 'Lokossa', 'ry-wc-city-select' ),
		'MA' => __( 'Malanville', 'ry-wc-city-select' ),
		'MA2' => __( 'Materi', 'ry-wc-city-select' ),
		'NA' => __( 'Natitingou', 'ry-wc-city-select' ),
		'ND' => __( 'Ndali', 'ry-wc-city-select' ),
		'NI' => __( 'Nikki', 'ry-wc-city-select' ),
		'OU' => __( 'Ouake', 'ry-wc-city-select' ),
		'PE' => __( 'Pehonko', 'ry-wc-city-select' ),
		'PE2' => __( 'Perere', 'ry-wc-city-select' ),
		'PO' => __( 'Porto-Novo', 'ry-wc-city-select' ),
		'SE' => __( 'Segbana', 'ry-wc-city-select' ),
		'SE2' => __( 'Seme-Kpodji', 'ry-wc-city-select' ),
		'SI' => __( 'Sinende', 'ry-wc-city-select' ),
		'TA' => __( 'Tanguieta', 'ry-wc-city-select' ),
		'TO' => __( 'Toukountouna', 'ry-wc-city-select' ),
		'TO2' => __( 'Toviklin', 'ry-wc-city-select' ),
		'AL' => __( 'Alibori', 'ry-wc-city-select' ),
		'ATDE' => __( 'Atakora Department', 'ry-wc-city-select' ),
		'ATDE2' => __( 'Atlantique Department', 'ry-wc-city-select' ),
		'BODE' => __( 'Borgou Department', 'ry-wc-city-select' ),
		'CODE' => __( 'Collines Department', 'ry-wc-city-select' ),
		'DELO' => __( 'Departement de lOueme', 'ry-wc-city-select' ),
		'DO' => __( 'Donga', 'ry-wc-city-select' ),
		'KODE' => __( 'Kouffo Department', 'ry-wc-city-select' ),
		'LI' => __( 'Littoral', 'ry-wc-city-select' ),
		'MO' => __( 'Mono', 'ry-wc-city-select' ),
		'PLDE' => __( 'Plateau Department', 'ry-wc-city-select' ),
		'ZODE' => __( 'Zou Department', 'ry-wc-city-select' ),
	]
];