<?php
/**
 * Canada states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CA' => [
		'AB' => __( 'Abitibi-Temiscamingue', 'ry-wc-city-select' ),
		'AL' => __( 'Algoma', 'ry-wc-city-select' ),
		'BA' => __( 'Bas-Saint-Laurent', 'ry-wc-city-select' ),
		'BRCO' => __( 'Bruce County', 'ry-wc-city-select' ),
		'CABRCO' => __( 'Cape Breton County', 'ry-wc-city-select' ),
		'CAREDI' => __( 'Capital Regional District', 'ry-wc-city-select' ),
		'CA' => __( 'Capitale-Nationale', 'ry-wc-city-select' ),
		'CAREDI2' => __( 'Cariboo Regional District', 'ry-wc-city-select' ),
		'CE' => __( 'Centre-du-Quebec', 'ry-wc-city-select' ),
		'CH' => __( 'Chaudiere-Appalaches', 'ry-wc-city-select' ),
		'CODI' => __( 'Cochrane District', 'ry-wc-city-select' ),
		'COREDI' => __( 'Columbia-Shuswap Regional District', 'ry-wc-city-select' ),
		'COVAREDI' => __( 'Comox Valley Regional District', 'ry-wc-city-select' ),
		'COUNPRRU' => __( 'Comtes unis de Prescott et Russell', 'ry-wc-city-select' ),
		'CO' => __( 'Cote-Nord', 'ry-wc-city-select' ),
		'COVAREDI2' => __( 'Cowichan Valley Regional District', 'ry-wc-city-select' ),
		'DERE' => __( 'Dehcho Region', 'ry-wc-city-select' ),
		'DIMUMU' => __( 'District Municipality of Muskoka', 'ry-wc-city-select' ),
		'DUCO' => __( 'Dufferin County', 'ry-wc-city-select' ),
		'DU' => __( 'Durham', 'ry-wc-city-select' ),
		'ELCO' => __( 'Elgin County', 'ry-wc-city-select' ),
		'ESCO' => __( 'Essex County', 'ry-wc-city-select' ),
		'ES' => __( 'Estrie', 'ry-wc-city-select' ),
		'FRVAREDI' => __( 'Fraser Valley Regional District', 'ry-wc-city-select' ),
		'FRCO' => __( 'Frontenac County', 'ry-wc-city-select' ),
		'GA' => __( 'Gaspesie-Iles-de-la-Madeleine', 'ry-wc-city-select' ),
		'GRCO' => __( 'Grey County', 'ry-wc-city-select' ),
		'HACO' => __( 'Haliburton County', 'ry-wc-city-select' ),
		'HACO2' => __( 'Hastings County', 'ry-wc-city-select' ),
		'HUCO' => __( 'Huron County', 'ry-wc-city-select' ),
		'INRE' => __( 'Inuvik Region', 'ry-wc-city-select' ),
		'KEDI' => __( 'Kenora District', 'ry-wc-city-select' ),
		'LACO' => __( 'Lambton County', 'ry-wc-city-select' ),
		'LACO2' => __( 'Lanark County', 'ry-wc-city-select' ),
		'LA' => __( 'Lanaudiere', 'ry-wc-city-select' ),
		'LA2' => __( 'Laurentides', 'ry-wc-city-select' ),
		'LEANADCO' => __( 'Lennox and Addington County', 'ry-wc-city-select' ),
		'MADI' => __( 'Manitoulin District', 'ry-wc-city-select' ),
		'MA' => __( 'Mauricie', 'ry-wc-city-select' ),
		'MEVAREDI' => __( 'Metro Vancouver Regional District', 'ry-wc-city-select' ),
		'MICO' => __( 'Middlesex County', 'ry-wc-city-select' ),
		'MO' => __( 'Monteregie', 'ry-wc-city-select' ),
		'MO2' => __( 'Montreal', 'ry-wc-city-select' ),
		'NIDI' => __( 'Nipissing District', 'ry-wc-city-select' ),
		'NO' => __( 'Nord-du-Quebec', 'ry-wc-city-select' ),
		'NOSLRE' => __( 'North Slave Region', 'ry-wc-city-select' ),
		'NOROREMU' => __( 'Northern Rockies Regional Municipality', 'ry-wc-city-select' ),
		'NOCO' => __( 'Northumberland County', 'ry-wc-city-select' ),
		'OT' => __( 'Ottawa', 'ry-wc-city-select' ),
		'OU' => __( 'Outaouais', 'ry-wc-city-select' ),
		'OXCO' => __( 'Oxford County', 'ry-wc-city-select' ),
		'PASODI' => __( 'Parry Sound District', 'ry-wc-city-select' ),
		'PERIREDI' => __( 'Peace River Regional District', 'ry-wc-city-select' ),
		'PECO' => __( 'Perth County', 'ry-wc-city-select' ),
		'PECO2' => __( 'Peterborough County', 'ry-wc-city-select' ),
		'PORIREDI' => __( 'Powell River Regional District', 'ry-wc-city-select' ),
		'RARIDI' => __( 'Rainy River District', 'ry-wc-city-select' ),
		'REDIAL' => __( 'Regional District of Alberni-Clayoquot', 'ry-wc-city-select' ),
		'REDIBU' => __( 'Regional District of Bulkley-Nechako', 'ry-wc-city-select' ),
		'REDICEKO' => __( 'Regional District of Central Kootenay', 'ry-wc-city-select' ),
		'REDICEOK' => __( 'Regional District of Central Okanagan', 'ry-wc-city-select' ),
		'REDIEAKO' => __( 'Regional District of East Kootenay', 'ry-wc-city-select' ),
		'REDIFRGE' => __( 'Regional District of Fraser-Fort George', 'ry-wc-city-select' ),
		'REDIKI' => __( 'Regional District of Kitimat-Stikine', 'ry-wc-city-select' ),
		'REDIKO' => __( 'Regional District of Kootenay-Boundary', 'ry-wc-city-select' ),
		'REDIMOWA' => __( 'Regional District of Mount Waddington', 'ry-wc-city-select' ),
		'REDINA' => __( 'Regional District of Nanaimo', 'ry-wc-city-select' ),
		'REDINOOK' => __( 'Regional District of North Okanagan', 'ry-wc-city-select' ),
		'REDIOK' => __( 'Regional District of Okanagan-Similkamee', 'ry-wc-city-select' ),
		'REMUNI' => __( 'Regional Municipality of Niagara', 'ry-wc-city-select' ),
		'REMUWA' => __( 'Regional Municipality of Waterloo', 'ry-wc-city-select' ),
		'RECO' => __( 'Renfrew County', 'ry-wc-city-select' ),
		'SA' => __( 'Saguenay/Lac-Saint-Jean', 'ry-wc-city-select' ),
		'SARE' => __( 'Sahtu Region', 'ry-wc-city-select' ),
		'SICO' => __( 'Simcoe County', 'ry-wc-city-select' ),
		'SKCHREDI' => __( 'Skeena-Queen Charlotte Regional District', 'ry-wc-city-select' ),
		'SOSLRE' => __( 'South Slave Region', 'ry-wc-city-select' ),
		'SQREDI' => __( 'Squamish-Lillooet Regional District', 'ry-wc-city-select' ),
		'STRE' => __( 'Stikine Region', 'ry-wc-city-select' ),
		'STREDI' => __( 'Strathcona Regional District', 'ry-wc-city-select' ),
		'SU' => __( 'Sudbury', 'ry-wc-city-select' ),
		'SUCOREDI' => __( 'Sunshine Coast Regional District', 'ry-wc-city-select' ),
		'THREDI' => __( 'Thompson-Nicola Regional District', 'ry-wc-city-select' ),
		'THBADI' => __( 'Thunder Bay District', 'ry-wc-city-select' ),
		'TIDI' => __( 'Timiskaming District', 'ry-wc-city-select' ),
		'UNCOLEANGR' => __( 'United Counties of Leeds and Grenville', 'ry-wc-city-select' ),
		'UNCOSTDUAN' => __( 'United Counties of Stormont, Dundas and', 'ry-wc-city-select' ),
		'WECO' => __( 'Wellington County', 'ry-wc-city-select' ),
		'YO' => __( 'York', 'ry-wc-city-select' ),
		'AL2' => __( 'Alberta', 'ry-wc-city-select' ),
		'BRCO2' => __( 'British Columbia', 'ry-wc-city-select' ),
		'MA2' => __( 'Manitoba', 'ry-wc-city-select' ),
		'NEBR' => __( 'New Brunswick/Nouveau-Brunswick', 'ry-wc-city-select' ),
		'NOSC' => __( 'Nova Scotia', 'ry-wc-city-select' ),
		'ON' => __( 'Ontario', 'ry-wc-city-select' ),
		'PREDIS' => __( 'Prince Edward Island', 'ry-wc-city-select' ),
		'QU' => __( 'Quebec', 'ry-wc-city-select' ),
		'SA2' => __( 'Saskatchewan', 'ry-wc-city-select' ),
		'NEANLA' => __( 'Newfoundland and Labrador', 'ry-wc-city-select' ),
		'NOTE' => __( 'Northwest Territories', 'ry-wc-city-select' ),
		'NU' => __( 'Nunavut', 'ry-wc-city-select' ),
		'YU' => __( 'Yukon', 'ry-wc-city-select' ),
	]
];