<?php
/**
 * Republic of Chile states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CL' => [
		'PEPR' => __( 'Petorca Province', 'ry-wc-city-select' ),
		'PRANCH' => __( 'Provincia Antartica Chilena', 'ry-wc-city-select' ),
		'PRCAPR' => __( 'Provincia Capitan Prat', 'ry-wc-city-select' ),
		'PRGECA' => __( 'Provincia General Carrera', 'ry-wc-city-select' ),
		'PRAI' => __( 'Provincia de Aisen', 'ry-wc-city-select' ),
		'PRAN' => __( 'Provincia de Antofagasta', 'ry-wc-city-select' ),
		'PRAR' => __( 'Provincia de Arauco', 'ry-wc-city-select' ),
		'PRAR2' => __( 'Provincia de Arica', 'ry-wc-city-select' ),
		'PRBI' => __( 'Provincia de Biobio', 'ry-wc-city-select' ),
		'PRCA' => __( 'Provincia de Cachapoal', 'ry-wc-city-select' ),
		'PRCACA' => __( 'Provincia de Cardenal Caro', 'ry-wc-city-select' ),
		'PRCA2' => __( 'Provincia de Cauquenes', 'ry-wc-city-select' ),
		'PRCA3' => __( 'Provincia de Cautin', 'ry-wc-city-select' ),
		'PRCH' => __( 'Provincia de Chacabuco', 'ry-wc-city-select' ),
		'PRCH2' => __( 'Provincia de Chanaral', 'ry-wc-city-select' ),
		'PRCH3' => __( 'Provincia de Chiloe', 'ry-wc-city-select' ),
		'PRCH4' => __( 'Provincia de Choapa', 'ry-wc-city-select' ),
		'PRCO' => __( 'Provincia de Colchagua', 'ry-wc-city-select' ),
		'PRCO2' => __( 'Provincia de Concepcion', 'ry-wc-city-select' ),
		'PRCO3' => __( 'Provincia de Copiapo', 'ry-wc-city-select' ),
		'PRCO4' => __( 'Provincia de Cordillera', 'ry-wc-city-select' ),
		'PRCO5' => __( 'Provincia de Coyhaique', 'ry-wc-city-select' ),
		'PRCU' => __( 'Provincia de Curico', 'ry-wc-city-select' ),
		'PRDI' => __( 'Provincia de Diguillin', 'ry-wc-city-select' ),
		'PRLO' => __( 'Provincia de El Loa', 'ry-wc-city-select' ),
		'PREL' => __( 'Provincia de Elqui', 'ry-wc-city-select' ),
		'PRHU' => __( 'Provincia de Huasco', 'ry-wc-city-select' ),
		'PRIQ' => __( 'Provincia de Iquique', 'ry-wc-city-select' ),
		'PRISPA' => __( 'Provincia de Isla de Pascua', 'ry-wc-city-select' ),
		'PRIT' => __( 'Provincia de Itata', 'ry-wc-city-select' ),
		'PRLI' => __( 'Provincia de Limari', 'ry-wc-city-select' ),
		'PRLI2' => __( 'Provincia de Linares', 'ry-wc-city-select' ),
		'PRLL' => __( 'Provincia de Llanquihue', 'ry-wc-city-select' ),
		'PRLOAN' => __( 'Provincia de Los Andes', 'ry-wc-city-select' ),
		'PRMA' => __( 'Provincia de Magallanes', 'ry-wc-city-select' ),
		'PRMA2' => __( 'Provincia de Maipo', 'ry-wc-city-select' ),
		'PRMA3' => __( 'Provincia de Malleco', 'ry-wc-city-select' ),
		'PRMAMA' => __( 'Provincia de Marga Marga', 'ry-wc-city-select' ),
		'PRME' => __( 'Provincia de Melipilla', 'ry-wc-city-select' ),
		'PROS' => __( 'Provincia de Osorno', 'ry-wc-city-select' ),
		'PRPA' => __( 'Provincia de Palena', 'ry-wc-city-select' ),
		'PRPA2' => __( 'Provincia de Parinacota', 'ry-wc-city-select' ),
		'PRPU' => __( 'Provincia de Punilla', 'ry-wc-city-select' ),
		'PRQU' => __( 'Provincia de Quillota', 'ry-wc-city-select' ),
		'PRSAFEAC' => __( 'Provincia de San Felipe de Aconcagua', 'ry-wc-city-select' ),
		'PRSA' => __( 'Provincia de Santiago', 'ry-wc-city-select' ),
		'PRTA' => __( 'Provincia de Talagante', 'ry-wc-city-select' ),
		'PRTA2' => __( 'Provincia de Talca', 'ry-wc-city-select' ),
		'PRTIDEFU' => __( 'Provincia de Tierra del Fuego', 'ry-wc-city-select' ),
		'PRTO' => __( 'Provincia de Tocopilla', 'ry-wc-city-select' ),
		'PRULES' => __( 'Provincia de Ultima Esperanza', 'ry-wc-city-select' ),
		'PRVA' => __( 'Provincia de Valdivia', 'ry-wc-city-select' ),
		'PRVA2' => __( 'Provincia de Valparaiso', 'ry-wc-city-select' ),
		'PRDERA' => __( 'Provincia del Ranco', 'ry-wc-city-select' ),
		'PRDETA' => __( 'Provincia del Tamarugal', 'ry-wc-city-select' ),
		'SAANPR' => __( 'San Antonio Province', 'ry-wc-city-select' ),
		'REAY' => __( 'Region Aysen', 'ry-wc-city-select' ),
		'REME' => __( 'Region Metropolitana', 'ry-wc-city-select' ),
		'REAN' => __( 'Region de Antofagasta', 'ry-wc-city-select' ),
		'REARPA' => __( 'Region de Arica y Parinacota', 'ry-wc-city-select' ),
		'REAT' => __( 'Region de Atacama', 'ry-wc-city-select' ),
		'RECO' => __( 'Region de Coquimbo', 'ry-wc-city-select' ),
		'REMAANCH' => __( 'Region de Magallanes y Antartica Chilena', 'ry-wc-city-select' ),
		'RENU' => __( 'Region de Nuble', 'ry-wc-city-select' ),
		'RETA' => __( 'Region de Tarapaca', 'ry-wc-city-select' ),
		'REVA' => __( 'Region de Valparaiso', 'ry-wc-city-select' ),
		'REAR' => __( 'Region de la Araucania', 'ry-wc-city-select' ),
		'RELOLA' => __( 'Region de los Lagos', 'ry-wc-city-select' ),
		'RELORI' => __( 'Region de los Rios', 'ry-wc-city-select' ),
		'REDEBI' => __( 'Region del Biobio', 'ry-wc-city-select' ),
		'REDELIGEBE' => __( 'Region del Libertador General Bernardo O', 'ry-wc-city-select' ),
		'REDEMA' => __( 'Region del Maule', 'ry-wc-city-select' ),
	]
];