<?php
/**
 * Republic of Costa Rica states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CR' => [
		'AB' => __( 'Abangares', 'ry-wc-city-select' ),
		'AC' => __( 'Acosta', 'ry-wc-city-select' ),
		'AL' => __( 'Alajuela', 'ry-wc-city-select' ),
		'AL2' => __( 'Alajuelita', 'ry-wc-city-select' ),
		'AL3' => __( 'Alvarado', 'ry-wc-city-select' ),
		'AS' => __( 'Aserri', 'ry-wc-city-select' ),
		'AT' => __( 'Atenas', 'ry-wc-city-select' ),
		'BA' => __( 'Bagaces', 'ry-wc-city-select' ),
		'BA2' => __( 'Barva', 'ry-wc-city-select' ),
		'BE' => __( 'Belen', 'ry-wc-city-select' ),
		'BUAI' => __( 'Buenos Aires', 'ry-wc-city-select' ),
		'CA' => __( 'Canas', 'ry-wc-city-select' ),
		'CA2' => __( 'Carrillo', 'ry-wc-city-select' ),
		'CA3' => __( 'Cartago', 'ry-wc-city-select' ),
		'CO' => __( 'Corredores', 'ry-wc-city-select' ),
		'COBR' => __( 'Coto Brus', 'ry-wc-city-select' ),
		'CU' => __( 'Curridabat', 'ry-wc-city-select' ),
		'DE' => __( 'Desamparados', 'ry-wc-city-select' ),
		'DO' => __( 'Dota', 'ry-wc-city-select' ),
		'GU' => __( 'El Guarco', 'ry-wc-city-select' ),
		'ES' => __( 'Escazu', 'ry-wc-city-select' ),
		'ES2' => __( 'Esparza', 'ry-wc-city-select' ),
		'FL' => __( 'Flores', 'ry-wc-city-select' ),
		'GA' => __( 'Garabito', 'ry-wc-city-select' ),
		'GO' => __( 'Goicoechea', 'ry-wc-city-select' ),
		'GO2' => __( 'Golfito', 'ry-wc-city-select' ),
		'GR' => __( 'Grecia', 'ry-wc-city-select' ),
		'GU2' => __( 'Guacimo', 'ry-wc-city-select' ),
		'GU3' => __( 'Guatuso', 'ry-wc-city-select' ),
		'HE' => __( 'Heredia', 'ry-wc-city-select' ),
		'HO' => __( 'Hojancha', 'ry-wc-city-select' ),
		'JI' => __( 'Jimenez', 'ry-wc-city-select' ),
		'CR' => __( 'La Cruz', 'ry-wc-city-select' ),
		'UN' => __( 'La Union', 'ry-wc-city-select' ),
		'LECO' => __( 'Leon Cortes', 'ry-wc-city-select' ),
		'LI' => __( 'Liberia', 'ry-wc-city-select' ),
		'LI2' => __( 'Limon', 'ry-wc-city-select' ),
		'LOCH' => __( 'Los Chiles', 'ry-wc-city-select' ),
		'MA' => __( 'Matina', 'ry-wc-city-select' ),
		'MOOC' => __( 'Montes de Oca', 'ry-wc-city-select' ),
		'MOOR' => __( 'Montes de Oro', 'ry-wc-city-select' ),
		'MO' => __( 'Mora', 'ry-wc-city-select' ),
		'MO2' => __( 'Moravia', 'ry-wc-city-select' ),
		'NA' => __( 'Nandayure', 'ry-wc-city-select' ),
		'NA2' => __( 'Naranjo', 'ry-wc-city-select' ),
		'NI' => __( 'Nicoya', 'ry-wc-city-select' ),
		'OR' => __( 'Oreamuno', 'ry-wc-city-select' ),
		'OR2' => __( 'Orotina', 'ry-wc-city-select' ),
		'OS' => __( 'Osa', 'ry-wc-city-select' ),
		'PA' => __( 'Palmares', 'ry-wc-city-select' ),
		'PA2' => __( 'Paraiso', 'ry-wc-city-select' ),
		'PA3' => __( 'Parrita', 'ry-wc-city-select' ),
		'PEZE' => __( 'Perez Zeledon', 'ry-wc-city-select' ),
		'PO' => __( 'Poas', 'ry-wc-city-select' ),
		'PO2' => __( 'Pococi', 'ry-wc-city-select' ),
		'PU' => __( 'Puntarenas', 'ry-wc-city-select' ),
		'PU2' => __( 'Puriscal', 'ry-wc-city-select' ),
		'QU' => __( 'Quepos', 'ry-wc-city-select' ),
		'RICU' => __( 'Rio Cuarto', 'ry-wc-city-select' ),
		'SACA' => __( 'San Carlos', 'ry-wc-city-select' ),
		'SAIS' => __( 'San Isidro', 'ry-wc-city-select' ),
		'SAJO' => __( 'San Jose', 'ry-wc-city-select' ),
		'SAMA' => __( 'San Mateo', 'ry-wc-city-select' ),
		'SAPA' => __( 'San Pablo', 'ry-wc-city-select' ),
		'SARA' => __( 'San Rafael', 'ry-wc-city-select' ),
		'SARA2' => __( 'San Ramon', 'ry-wc-city-select' ),
		'SAAN' => __( 'Santa Ana', 'ry-wc-city-select' ),
		'SABA' => __( 'Santa Barbara', 'ry-wc-city-select' ),
		'SACR' => __( 'Santa Cruz', 'ry-wc-city-select' ),
		'SADO' => __( 'Santo Domingo', 'ry-wc-city-select' ),
		'SA' => __( 'Sarapiqui', 'ry-wc-city-select' ),
		'SI' => __( 'Siquirres', 'ry-wc-city-select' ),
		'TA' => __( 'Talamanca', 'ry-wc-city-select' ),
		'TA2' => __( 'Tarrazu', 'ry-wc-city-select' ),
		'TI' => __( 'Tibas', 'ry-wc-city-select' ),
		'TI2' => __( 'Tilaran', 'ry-wc-city-select' ),
		'TU' => __( 'Turrialba', 'ry-wc-city-select' ),
		'TU2' => __( 'Turrubares', 'ry-wc-city-select' ),
		'UP' => __( 'Upala', 'ry-wc-city-select' ),
		'VAVE' => __( 'Valverde Vega', 'ry-wc-city-select' ),
		'VACO' => __( 'Vazquez de Coronado', 'ry-wc-city-select' ),
		'ZA' => __( 'Zarcero', 'ry-wc-city-select' ),
		'PRAL' => __( 'Provincia de Alajuela', 'ry-wc-city-select' ),
		'PRCA' => __( 'Provincia de Cartago', 'ry-wc-city-select' ),
		'PRGU' => __( 'Provincia de Guanacaste', 'ry-wc-city-select' ),
		'PRHE' => __( 'Provincia de Heredia', 'ry-wc-city-select' ),
		'PRLI' => __( 'Provincia de Limon', 'ry-wc-city-select' ),
		'PRPU' => __( 'Provincia de Puntarenas', 'ry-wc-city-select' ),
		'PRSAJO' => __( 'Provincia de San Jose', 'ry-wc-city-select' ),
	]
];