<?php
/**
 * Czechia states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CZ' => [
		'MEBR' => __( 'Mesto Brno', 'ry-wc-city-select' ),
		'OKBE' => __( 'Okres Benesov', 'ry-wc-city-select' ),
		'OKBE2' => __( 'Okres Beroun', 'ry-wc-city-select' ),
		'OKBL' => __( 'Okres Blansko', 'ry-wc-city-select' ),
		'OKBR' => __( 'Okres Breclav', 'ry-wc-city-select' ),
		'OKBR2' => __( 'Okres Brno-venkov', 'ry-wc-city-select' ),
		'OKBR3' => __( 'Okres Bruntal', 'ry-wc-city-select' ),
		'OKCELI' => __( 'Okres Ceska Lipa', 'ry-wc-city-select' ),
		'OKCEBU' => __( 'Okres Ceske Budejovice', 'ry-wc-city-select' ),
		'OKCEKR' => __( 'Okres Cesky Krumlov', 'ry-wc-city-select' ),
		'OKCH' => __( 'Okres Cheb', 'ry-wc-city-select' ),
		'OKCH2' => __( 'Okres Chomutov', 'ry-wc-city-select' ),
		'OKCH3' => __( 'Okres Chrudim', 'ry-wc-city-select' ),
		'OKDE' => __( 'Okres Decin', 'ry-wc-city-select' ),
		'OKDO' => __( 'Okres Domazlice', 'ry-wc-city-select' ),
		'OKFR' => __( 'Okres Frydek-Mistek', 'ry-wc-city-select' ),
		'OKHABR' => __( 'Okres Havlickuv Brod', 'ry-wc-city-select' ),
		'OKHO' => __( 'Okres Hodonin', 'ry-wc-city-select' ),
		'OKHRKR' => __( 'Okres Hradec Kralove', 'ry-wc-city-select' ),
		'OKJANANI' => __( 'Okres Jablonec nad Nisou', 'ry-wc-city-select' ),
		'OKJE' => __( 'Okres Jesenik', 'ry-wc-city-select' ),
		'OKJI' => __( 'Okres Jicin', 'ry-wc-city-select' ),
		'OKJI2' => __( 'Okres Jihlava', 'ry-wc-city-select' ),
		'OKJIHR' => __( 'Okres Jindrichuv Hradec', 'ry-wc-city-select' ),
		'OKKAVA' => __( 'Okres Karlovy Vary', 'ry-wc-city-select' ),
		'OKKA' => __( 'Okres Karvina', 'ry-wc-city-select' ),
		'OKKL' => __( 'Okres Kladno', 'ry-wc-city-select' ),
		'OKKL2' => __( 'Okres Klatovy', 'ry-wc-city-select' ),
		'OKKO' => __( 'Okres Kolin', 'ry-wc-city-select' ),
		'OKKR' => __( 'Okres Kromeriz', 'ry-wc-city-select' ),
		'OKKUHO' => __( 'Okres Kutna Hora', 'ry-wc-city-select' ),
		'OKLI' => __( 'Okres Liberec', 'ry-wc-city-select' ),
		'OKLI2' => __( 'Okres Litomerice', 'ry-wc-city-select' ),
		'OKLO' => __( 'Okres Louny', 'ry-wc-city-select' ),
		'OKME' => __( 'Okres Melnik', 'ry-wc-city-select' ),
		'OKMLBO' => __( 'Okres Mlada Boleslav', 'ry-wc-city-select' ),
		'OKMO' => __( 'Okres Most', 'ry-wc-city-select' ),
		'OKNA' => __( 'Okres Nachod', 'ry-wc-city-select' ),
		'OKNOJI' => __( 'Okres Novy Jicin', 'ry-wc-city-select' ),
		'OKNY' => __( 'Okres Nymburk', 'ry-wc-city-select' ),
		'OKOL' => __( 'Okres Olomouc', 'ry-wc-city-select' ),
		'OKOP' => __( 'Okres Opava', 'ry-wc-city-select' ),
		'OKOS' => __( 'Okres Ostrava-mesto', 'ry-wc-city-select' ),
		'OKPA' => __( 'Okres Pardubice', 'ry-wc-city-select' ),
		'OKPE' => __( 'Okres Pelhrimov', 'ry-wc-city-select' ),
		'OKPI' => __( 'Okres Pisek', 'ry-wc-city-select' ),
		'OKPL' => __( 'Okres Plzen-jih', 'ry-wc-city-select' ),
		'OKPL2' => __( 'Okres Plzen-mesto', 'ry-wc-city-select' ),
		'OKPL3' => __( 'Okres Plzen-sever', 'ry-wc-city-select' ),
		'OKPR' => __( 'Okres Prachatice', 'ry-wc-city-select' ),
		'OKPR2' => __( 'Okres Praha-vychod', 'ry-wc-city-select' ),
		'OKPR3' => __( 'Okres Praha-zapad', 'ry-wc-city-select' ),
		'OKPR4' => __( 'Okres Prerov', 'ry-wc-city-select' ),
		'OKPR5' => __( 'Okres Pribram', 'ry-wc-city-select' ),
		'OKPR6' => __( 'Okres Prostejov', 'ry-wc-city-select' ),
		'OKRA' => __( 'Okres Rakovnik', 'ry-wc-city-select' ),
		'OKRO' => __( 'Okres Rokycany', 'ry-wc-city-select' ),
		'OKRYNAKN' => __( 'Okres Rychnov nad Kneznou', 'ry-wc-city-select' ),
		'OKSE' => __( 'Okres Semily', 'ry-wc-city-select' ),
		'OKSO' => __( 'Okres Sokolov', 'ry-wc-city-select' ),
		'OKST' => __( 'Okres Strakonice', 'ry-wc-city-select' ),
		'OKSU' => __( 'Okres Sumperk', 'ry-wc-city-select' ),
		'OKSV' => __( 'Okres Svitavy', 'ry-wc-city-select' ),
		'OKTA' => __( 'Okres Tabor', 'ry-wc-city-select' ),
		'OKTA2' => __( 'Okres Tachov', 'ry-wc-city-select' ),
		'OKTE' => __( 'Okres Teplice', 'ry-wc-city-select' ),
		'OKTR' => __( 'Okres Trebic', 'ry-wc-city-select' ),
		'OKTR2' => __( 'Okres Trutnov', 'ry-wc-city-select' ),
		'OKUHHR' => __( 'Okres Uherske Hradiste', 'ry-wc-city-select' ),
		'OKUSNALA' => __( 'Okres Usti nad Labem', 'ry-wc-city-select' ),
		'OKUSNAOR' => __( 'Okres Usti nad Orlici', 'ry-wc-city-select' ),
		'OKVS' => __( 'Okres Vsetin', 'ry-wc-city-select' ),
		'OKVY' => __( 'Okres Vyskov', 'ry-wc-city-select' ),
		'OKZGNASA' => __( 'Okres Zgar nad Sazavou', 'ry-wc-city-select' ),
		'OKZL' => __( 'Okres Zlin', 'ry-wc-city-select' ),
		'OKZN' => __( 'Okres Znojmo', 'ry-wc-city-select' ),
		'PR' => __( 'Praha 1', 'ry-wc-city-select' ),
		'PR2' => __( 'Praha 10', 'ry-wc-city-select' ),
		'PR3' => __( 'Praha 11', 'ry-wc-city-select' ),
		'PR4' => __( 'Praha 12', 'ry-wc-city-select' ),
		'PR5' => __( 'Praha 13', 'ry-wc-city-select' ),
		'PR6' => __( 'Praha 14', 'ry-wc-city-select' ),
		'PR7' => __( 'Praha 15', 'ry-wc-city-select' ),
		'PR8' => __( 'Praha 16', 'ry-wc-city-select' ),
		'PR9' => __( 'Praha 17', 'ry-wc-city-select' ),
		'PR10' => __( 'Praha 18', 'ry-wc-city-select' ),
		'PR11' => __( 'Praha 19', 'ry-wc-city-select' ),
		'PR12' => __( 'Praha 2', 'ry-wc-city-select' ),
		'PR13' => __( 'Praha 20', 'ry-wc-city-select' ),
		'PR14' => __( 'Praha 21', 'ry-wc-city-select' ),
		'PR15' => __( 'Praha 22', 'ry-wc-city-select' ),
		'PR16' => __( 'Praha 3', 'ry-wc-city-select' ),
		'PR17' => __( 'Praha 4', 'ry-wc-city-select' ),
		'PR18' => __( 'Praha 5', 'ry-wc-city-select' ),
		'PR19' => __( 'Praha 6', 'ry-wc-city-select' ),
		'PR20' => __( 'Praha 7', 'ry-wc-city-select' ),
		'PR21' => __( 'Praha 8', 'ry-wc-city-select' ),
		'PR22' => __( 'Praha 9', 'ry-wc-city-select' ),
		'HLMEPR' => __( 'Hlavni mesto Praha', 'ry-wc-city-select' ),
		'JIKR' => __( 'Jihocesky kraj', 'ry-wc-city-select' ),
		'JIKR2' => __( 'Jihomoravsky kraj', 'ry-wc-city-select' ),
		'KAKR' => __( 'Karlovarsky kraj', 'ry-wc-city-select' ),
		'KRVY' => __( 'Kraj Vysocina', 'ry-wc-city-select' ),
		'KRKR' => __( 'Kralovehradecky kraj', 'ry-wc-city-select' ),
		'LIKR' => __( 'Liberecky kraj', 'ry-wc-city-select' ),
		'MOKR' => __( 'Moravskoslezsky kraj', 'ry-wc-city-select' ),
		'OLKR' => __( 'Olomoucky kraj', 'ry-wc-city-select' ),
		'PAKR' => __( 'Pardubicky kraj', 'ry-wc-city-select' ),
		'PLKR' => __( 'Plzensky kraj', 'ry-wc-city-select' ),
		'STKR' => __( 'Stredocesky kraj', 'ry-wc-city-select' ),
		'USKR' => __( 'Ustecky kraj', 'ry-wc-city-select' ),
		'ZLKR' => __( 'Zlinsky kraj', 'ry-wc-city-select' ),
	]
];