<?php
/**
 * Republic of Estonia states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'EE' => [
		'ALVA' => __( 'Alutaguse vald', 'ry-wc-city-select' ),
		'ANVA' => __( 'Anija vald', 'ry-wc-city-select' ),
		'ANVA2' => __( 'Antsla vald', 'ry-wc-city-select' ),
		'ELVA' => __( 'Elva vald', 'ry-wc-city-select' ),
		'HALI' => __( 'Haapsalu linn', 'ry-wc-city-select' ),
		'HAVA' => __( 'Haeaedemeeste vald', 'ry-wc-city-select' ),
		'HAVA2' => __( 'Haljala vald', 'ry-wc-city-select' ),
		'HAVA3' => __( 'Harku vald', 'ry-wc-city-select' ),
		'HIVA' => __( 'Hiiumaa vald', 'ry-wc-city-select' ),
		'JAVA' => __( 'Jaerva vald', 'ry-wc-city-select' ),
		'JOVA' => __( 'Joelaehtme vald', 'ry-wc-city-select' ),
		'JOVA2' => __( 'Jogeva vald', 'ry-wc-city-select' ),
		'JOVA3' => __( 'Johvi vald', 'ry-wc-city-select' ),
		'KAVA' => __( 'Kadrina vald', 'ry-wc-city-select' ),
		'KAVA2' => __( 'Kambja vald', 'ry-wc-city-select' ),
		'KAVA3' => __( 'Kanepi vald', 'ry-wc-city-select' ),
		'KAVA4' => __( 'Kastre vald', 'ry-wc-city-select' ),
		'KEVA' => __( 'Kehtna vald', 'ry-wc-city-select' ),
		'KIVA' => __( 'Kihnu vald', 'ry-wc-city-select' ),
		'KIVA2' => __( 'Kiili vald', 'ry-wc-city-select' ),
		'KOVA' => __( 'Kohila vald', 'ry-wc-city-select' ),
		'KOLI' => __( 'Kohtla-Jaerve linn', 'ry-wc-city-select' ),
		'KOVA2' => __( 'Kose vald', 'ry-wc-city-select' ),
		'KUVA' => __( 'Kuusalu vald', 'ry-wc-city-select' ),
		'LAVA' => __( 'Laeaene-Harju vald', 'ry-wc-city-select' ),
		'LAVA2' => __( 'Laeaene-Nigula vald', 'ry-wc-city-select' ),
		'LAVA3' => __( 'Laeaeneranna vald', 'ry-wc-city-select' ),
		'LUVA' => __( 'Lueganuse vald', 'ry-wc-city-select' ),
		'LUVA2' => __( 'Luunja vald', 'ry-wc-city-select' ),
		'MAVA' => __( 'Maerjamaa vald', 'ry-wc-city-select' ),
		'MUVA' => __( 'Muhu vald', 'ry-wc-city-select' ),
		'MUVA2' => __( 'Mulgi vald', 'ry-wc-city-select' ),
		'MUVA3' => __( 'Mustvee vald', 'ry-wc-city-select' ),
		'NALI' => __( 'Narva-Joesuu linn', 'ry-wc-city-select' ),
		'NOVA' => __( 'Noo vald', 'ry-wc-city-select' ),
		'OTVA' => __( 'Otepaeae vald', 'ry-wc-city-select' ),
		'PALI' => __( 'Paernu linn', 'ry-wc-city-select' ),
		'PALI2' => __( 'Paide linn', 'ry-wc-city-select' ),
		'PEVA' => __( 'Peipsiaeaere vald', 'ry-wc-city-select' ),
		'POVA' => __( 'Pohja-Paernumaa vald', 'ry-wc-city-select' ),
		'POVA2' => __( 'Pohja-Sakala vald', 'ry-wc-city-select' ),
		'POVA3' => __( 'Poltsamaa vald', 'ry-wc-city-select' ),
		'POVA4' => __( 'Polva vald', 'ry-wc-city-select' ),
		'RAVA' => __( 'Raasiku vald', 'ry-wc-city-select' ),
		'RAVA2' => __( 'Rae vald', 'ry-wc-city-select' ),
		'RAVA3' => __( 'Raepina vald', 'ry-wc-city-select' ),
		'RAVA4' => __( 'Rakvere vald', 'ry-wc-city-select' ),
		'RAVA5' => __( 'Rapla vald', 'ry-wc-city-select' ),
		'ROVA' => __( 'Rouge vald', 'ry-wc-city-select' ),
		'RUVA' => __( 'Ruhnu vald', 'ry-wc-city-select' ),
		'SAVA' => __( 'Saarde vald', 'ry-wc-city-select' ),
		'SAVA2' => __( 'Saaremaa vald', 'ry-wc-city-select' ),
		'SAVA3' => __( 'Saku vald', 'ry-wc-city-select' ),
		'SAVA4' => __( 'Saue vald', 'ry-wc-city-select' ),
		'SEVA' => __( 'Setomaa vald', 'ry-wc-city-select' ),
		'TA' => __( 'Tallinn', 'ry-wc-city-select' ),
		'TAVA' => __( 'Tapa vald', 'ry-wc-city-select' ),
		'TALI' => __( 'Tartu linn', 'ry-wc-city-select' ),
		'TAVA2' => __( 'Tartu vald', 'ry-wc-city-select' ),
		'TOVA' => __( 'Toila vald', 'ry-wc-city-select' ),
		'TOVA2' => __( 'Tori vald', 'ry-wc-city-select' ),
		'TOVA3' => __( 'Torva vald', 'ry-wc-city-select' ),
		'TUVA' => __( 'Tueri vald', 'ry-wc-city-select' ),
		'VAVA' => __( 'Vaeike-Maarja vald', 'ry-wc-city-select' ),
		'VAVA2' => __( 'Valga vald', 'ry-wc-city-select' ),
		'VIVA' => __( 'Viimsi vald', 'ry-wc-city-select' ),
		'VIVA2' => __( 'Viljandi vald', 'ry-wc-city-select' ),
		'VIVA3' => __( 'Vinni vald', 'ry-wc-city-select' ),
		'VIVA4' => __( 'Viru-Nigula vald', 'ry-wc-city-select' ),
		'VOVA' => __( 'Vormsi vald', 'ry-wc-city-select' ),
		'VOVA2' => __( 'Voru vald', 'ry-wc-city-select' ),
		'HA' => __( 'Harjumaa', 'ry-wc-city-select' ),
		'ID' => __( 'Ida-Virumaa', 'ry-wc-city-select' ),
		'LA' => __( 'Laane-Virumaa', 'ry-wc-city-select' ),
		'VI' => __( 'Viljandimaa', 'ry-wc-city-select' ),
		'VO' => __( 'Vorumaa', 'ry-wc-city-select' ),
		'HI' => __( 'Hiiumaa', 'ry-wc-city-select' ),
		'JA' => __( 'Jarvamaa', 'ry-wc-city-select' ),
		'JO' => __( 'Jogevamaa', 'ry-wc-city-select' ),
		'LA2' => __( 'Laeaenemaa', 'ry-wc-city-select' ),
		'PA' => __( 'Paernumaa', 'ry-wc-city-select' ),
		'PO' => __( 'Polvamaa', 'ry-wc-city-select' ),
		'RA' => __( 'Raplamaa', 'ry-wc-city-select' ),
		'SA' => __( 'Saaremaa', 'ry-wc-city-select' ),
		'TA2' => __( 'Tartumaa', 'ry-wc-city-select' ),
		'VA' => __( 'Valgamaa', 'ry-wc-city-select' ),
	]
];