<?php
/**
 * Kingdom of Spain states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'ES' => [
		'AL' => __( 'Almeria', 'ry-wc-city-select' ),
		'BI' => __( 'Bizkaia', 'ry-wc-city-select' ),
		'CE' => __( 'Ceuta', 'ry-wc-city-select' ),
		'ILBA' => __( 'Illes Balears', 'ry-wc-city-select' ),
		'ME' => __( 'Melilla', 'ry-wc-city-select' ),
		'MU' => __( 'Murcia', 'ry-wc-city-select' ),
		'PRAS' => __( 'Province of Asturias', 'ry-wc-city-select' ),
		'PRCO' => __( 'Province of Cordoba', 'ry-wc-city-select' ),
		'PRTO' => __( 'Province of Toledo', 'ry-wc-city-select' ),
		'PRCO2' => __( 'Provincia da Coruna', 'ry-wc-city-select' ),
		'PRAL' => __( 'Provincia de Alava', 'ry-wc-city-select' ),
		'PRAL2' => __( 'Provincia de Albacete', 'ry-wc-city-select' ),
		'PRAL3' => __( 'Provincia de Alicante', 'ry-wc-city-select' ),
		'PRAV' => __( 'Provincia de Avila', 'ry-wc-city-select' ),
		'PRBA' => __( 'Provincia de Badajoz', 'ry-wc-city-select' ),
		'PRBA2' => __( 'Provincia de Barcelona', 'ry-wc-city-select' ),
		'PRBU' => __( 'Provincia de Burgos', 'ry-wc-city-select' ),
		'PRCA' => __( 'Provincia de Caceres', 'ry-wc-city-select' ),
		'PRCA2' => __( 'Provincia de Cadiz', 'ry-wc-city-select' ),
		'PRCA3' => __( 'Provincia de Cantabria', 'ry-wc-city-select' ),
		'PRCA4' => __( 'Provincia de Castello', 'ry-wc-city-select' ),
		'PRCIRE' => __( 'Provincia de Ciudad Real', 'ry-wc-city-select' ),
		'PRCU' => __( 'Provincia de Cuenca', 'ry-wc-city-select' ),
		'PRGI' => __( 'Provincia de Girona', 'ry-wc-city-select' ),
		'PRGR' => __( 'Provincia de Granada', 'ry-wc-city-select' ),
		'PRGU' => __( 'Provincia de Guadalajara', 'ry-wc-city-select' ),
		'PRGU2' => __( 'Provincia de Guipuzcoa', 'ry-wc-city-select' ),
		'PRHU' => __( 'Provincia de Huelva', 'ry-wc-city-select' ),
		'PRHU2' => __( 'Provincia de Huesca', 'ry-wc-city-select' ),
		'PRJA' => __( 'Provincia de Jaen', 'ry-wc-city-select' ),
		'PRRI' => __( 'Provincia de La Rioja', 'ry-wc-city-select' ),
		'PRLAPA' => __( 'Provincia de Las Palmas', 'ry-wc-city-select' ),
		'PRLE' => __( 'Provincia de Leon', 'ry-wc-city-select' ),
		'PRLL' => __( 'Provincia de Lleida', 'ry-wc-city-select' ),
		'PRLU' => __( 'Provincia de Lugo', 'ry-wc-city-select' ),
		'PRMA' => __( 'Provincia de Madrid', 'ry-wc-city-select' ),
		'PRMA2' => __( 'Provincia de Malaga', 'ry-wc-city-select' ),
		'PRNA' => __( 'Provincia de Navarra', 'ry-wc-city-select' ),
		'PROU' => __( 'Provincia de Ourense', 'ry-wc-city-select' ),
		'PRPA' => __( 'Provincia de Palencia', 'ry-wc-city-select' ),
		'PRPO' => __( 'Provincia de Pontevedra', 'ry-wc-city-select' ),
		'PRSA' => __( 'Provincia de Salamanca', 'ry-wc-city-select' ),
		'PRSACRTE' => __( 'Provincia de Santa Cruz de Tenerife', 'ry-wc-city-select' ),
		'PRSE' => __( 'Provincia de Segovia', 'ry-wc-city-select' ),
		'PRSE2' => __( 'Provincia de Sevilla', 'ry-wc-city-select' ),
		'PRSO' => __( 'Provincia de Soria', 'ry-wc-city-select' ),
		'PRTA' => __( 'Provincia de Tarragona', 'ry-wc-city-select' ),
		'PRTE' => __( 'Provincia de Teruel', 'ry-wc-city-select' ),
		'PRVA' => __( 'Provincia de Valencia', 'ry-wc-city-select' ),
		'PRVA2' => __( 'Provincia de Valladolid', 'ry-wc-city-select' ),
		'PRZA' => __( 'Provincia de Zamora', 'ry-wc-city-select' ),
		'PRZA2' => __( 'Provincia de Zaragoza', 'ry-wc-city-select' ),
		'AN' => __( 'Andalusia', 'ry-wc-city-select' ),
		'AR' => __( 'Aragon', 'ry-wc-city-select' ),
		'CAIS' => __( 'Canary Islands', 'ry-wc-city-select' ),
		'CA' => __( 'Cantabria', 'ry-wc-city-select' ),
		'CALE' => __( 'Castilla y Leon', 'ry-wc-city-select' ),
		'CAMA' => __( 'Castilla-La Mancha', 'ry-wc-city-select' ),
		'CA2' => __( 'Catalunya', 'ry-wc-city-select' ),
		'COMA' => __( 'Comunidad de Madrid', 'ry-wc-city-select' ),
		'COAULEILBA' => __( 'Comunitat Autonoma de les Illes Balears', 'ry-wc-city-select' ),
		'COVA' => __( 'Comunitat Valenciana', 'ry-wc-city-select' ),
		'EUAUER' => __( 'Euskal Autonomia Erkidegoa', 'ry-wc-city-select' ),
		'EX' => __( 'Extremadura', 'ry-wc-city-select' ),
		'GA' => __( 'Galicia', 'ry-wc-city-select' ),
		'RI' => __( 'La Rioja', 'ry-wc-city-select' ),
		'NA' => __( 'Navarra', 'ry-wc-city-select' ),
		'PRAS2' => __( 'Principality of Asturias', 'ry-wc-city-select' ),
		'REMU' => __( 'Region de Murcia', 'ry-wc-city-select' ),
	]
];