<?php
/**
 * Federal Democratic Republic of Ethiopia states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'ET' => [
		'ADABZO' => __( 'Addis Ababa Zone 3', 'ry-wc-city-select' ),
		'ADZO' => __( 'Administrative Zone 1', 'ry-wc-city-select' ),
		'ADZO2' => __( 'Administrative Zone 3', 'ry-wc-city-select' ),
		'ADZO3' => __( 'Administrative Zone 4', 'ry-wc-city-select' ),
		'ADZO4' => __( 'Administrative Zone 5', 'ry-wc-city-select' ),
		'ARZO' => __( 'Arsi Zone', 'ry-wc-city-select' ),
		'AS' => __( 'Asosa', 'ry-wc-city-select' ),
		'AW' => __( 'Awi', 'ry-wc-city-select' ),
		'BA' => __( 'Bale', 'ry-wc-city-select' ),
		'BASPWO' => __( 'Basketo Special Woreda', 'ry-wc-city-select' ),
		'BEMAZO' => __( 'Bench Maji Zone', 'ry-wc-city-select' ),
		'BOZO' => __( 'Borena Zone', 'ry-wc-city-select' ),
		'CETIZO' => __( 'Central Tigray Zone', 'ry-wc-city-select' ),
		'DA' => __( 'Dawuro', 'ry-wc-city-select' ),
		'EAGOZO' => __( 'East Gojjam Zone', 'ry-wc-city-select' ),
		'EAHAZO' => __( 'East Harerghe Zone', 'ry-wc-city-select' ),
		'EAWEZO' => __( 'East Wellega Zone', 'ry-wc-city-select' ),
		'EATIZO' => __( 'Eastern Tigray Zone', 'ry-wc-city-select' ),
		'FA' => __( 'Fafan', 'ry-wc-city-select' ),
		'GAGOZO' => __( 'Gamo Gofa Zone', 'ry-wc-city-select' ),
		'GEZO' => __( 'Gedeo Zone', 'ry-wc-city-select' ),
		'GOZO' => __( 'Gode Zone', 'ry-wc-city-select' ),
		'GUZO' => __( 'Guji Zone', 'ry-wc-city-select' ),
		'GUZO2' => __( 'Guraghe Zone', 'ry-wc-city-select' ),
		'HAZO' => __( 'Hadiya Zone', 'ry-wc-city-select' ),
		'JIZO' => __( 'Jimma Zone', 'ry-wc-city-select' ),
		'KAZO' => __( 'Kaffa Zone', 'ry-wc-city-select' ),
		'KEALTEZO' => __( 'Kembata Alaba Tembaro Zone', 'ry-wc-city-select' ),
		'LIZO' => __( 'Liben zone', 'ry-wc-city-select' ),
		'MEAW' => __( 'Metekel Awraja', 'ry-wc-city-select' ),
		'MISH' => __( 'Misraq Shewa', 'ry-wc-city-select' ),
		'NOGOZO' => __( 'North Gondar Zone', 'ry-wc-city-select' ),
		'NOSHZO' => __( 'North Shewa Zone', 'ry-wc-city-select' ),
		'NOWETI' => __( 'North Western Tigray', 'ry-wc-city-select' ),
		'NOWOZO' => __( 'North Wollo Zone', 'ry-wc-city-select' ),
		'ORZO' => __( 'Oromia Zone', 'ry-wc-city-select' ),
		'SHZO' => __( 'Shinile Zone', 'ry-wc-city-select' ),
		'SIZO' => __( 'Sidama Zone', 'ry-wc-city-select' ),
		'SIZO2' => __( 'Siltie Zone', 'ry-wc-city-select' ),
		'SOGOZO' => __( 'South Gondar Zone', 'ry-wc-city-select' ),
		'SOOMZO' => __( 'South Omo Zone', 'ry-wc-city-select' ),
		'SOWESH' => __( 'South West Shewa', 'ry-wc-city-select' ),
		'SOWOZO' => __( 'South Wollo Zone', 'ry-wc-city-select' ),
		'SOTIZO' => __( 'Southeastern Tigray Zone', 'ry-wc-city-select' ),
		'SOTIZO2' => __( 'Southern Tigray Zone', 'ry-wc-city-select' ),
		'WAHEZO' => __( 'Wag Hemra Zone', 'ry-wc-city-select' ),
		'WEGOZO' => __( 'West Gojjam Zone', 'ry-wc-city-select' ),
		'WEHAZO' => __( 'West Harerghe Zone', 'ry-wc-city-select' ),
		'WESHZO' => __( 'West Shewa Zone', 'ry-wc-city-select' ),
		'WEWEZO' => __( 'West Wellega Zone', 'ry-wc-city-select' ),
		'WOZO' => __( 'Wolayita Zone', 'ry-wc-city-select' ),
		'ADABAS' => __( 'Adis Abeba Astedader', 'ry-wc-city-select' ),
		'AFRE' => __( 'Afar Region', 'ry-wc-city-select' ),
		'AMRE' => __( 'Amhara Region', 'ry-wc-city-select' ),
		'BERE' => __( 'Benishangul-Gumuz Region', 'ry-wc-city-select' ),
		'GARE' => __( 'Gambela Region', 'ry-wc-city-select' ),
		'HARE' => __( 'Harari Region', 'ry-wc-city-select' ),
		'ORRE' => __( 'Oromiya Region', 'ry-wc-city-select' ),
		'SORE' => __( 'Somali Region', 'ry-wc-city-select' ),
		'SONANAANPE' => __( 'Southern Nations, Nationalities, and Peo', 'ry-wc-city-select' ),
		'TIRE' => __( 'Tigray Region', 'ry-wc-city-select' ),
		'DIDARE' => __( 'Dire Dawa Region', 'ry-wc-city-select' ),
	]
];