<?php
/**
 * Republic of Finland states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'FI' => [
		'AE' => __( 'AEaenekoski', 'ry-wc-city-select' ),
		'AB' => __( 'Aboland-Turunmaa', 'ry-wc-city-select' ),
		'ET' => __( 'Etelae-Pirkanmaa', 'ry-wc-city-select' ),
		'FO' => __( 'Forssa', 'ry-wc-city-select' ),
		'HA' => __( 'Haapavesi-Siikalatva', 'ry-wc-city-select' ),
		'HA2' => __( 'Haemeenlinna', 'ry-wc-city-select' ),
		'HE' => __( 'Helsinki', 'ry-wc-city-select' ),
		'IM' => __( 'Imatra', 'ry-wc-city-select' ),
		'IT' => __( 'Itae-Lappi', 'ry-wc-city-select' ),
		'JA' => __( 'Jaemsae', 'ry-wc-city-select' ),
		'JA2' => __( 'Jaerviseutu', 'ry-wc-city-select' ),
		'JA3' => __( 'Jakobstadsregionen', 'ry-wc-city-select' ),
		'JO' => __( 'Joensuu', 'ry-wc-city-select' ),
		'JO2' => __( 'Joutsa', 'ry-wc-city-select' ),
		'JY' => __( 'Jyvaeskylae', 'ry-wc-city-select' ),
		'KA' => __( 'Kajaani', 'ry-wc-city-select' ),
		'KA2' => __( 'Kaustinen', 'ry-wc-city-select' ),
		'KE' => __( 'Kehys-Kainuu', 'ry-wc-city-select' ),
		'KE2' => __( 'Kemi-Tornio', 'ry-wc-city-select' ),
		'KE3' => __( 'Keski-Karjala', 'ry-wc-city-select' ),
		'KE4' => __( 'Keuruu', 'ry-wc-city-select' ),
		'KO' => __( 'Koillis-Savo', 'ry-wc-city-select' ),
		'KO2' => __( 'Koillismaa', 'ry-wc-city-select' ),
		'KO3' => __( 'Kokkola', 'ry-wc-city-select' ),
		'KO4' => __( 'Kotka-Hamina', 'ry-wc-city-select' ),
		'KO5' => __( 'Kouvola', 'ry-wc-city-select' ),
		'KU' => __( 'Kuopio', 'ry-wc-city-select' ),
		'KU2' => __( 'Kuusiokunnat', 'ry-wc-city-select' ),
		'KY' => __( 'Kyroenmaa', 'ry-wc-city-select' ),
		'LA' => __( 'Lahti', 'ry-wc-city-select' ),
		'LA2' => __( 'Lappeenranta', 'ry-wc-city-select' ),
		'LO' => __( 'Loimaa', 'ry-wc-city-select' ),
		'LO2' => __( 'Lounais-Pirkanmaa', 'ry-wc-city-select' ),
		'LO3' => __( 'Loviisa', 'ry-wc-city-select' ),
		'LU' => __( 'Luoteis-Pirkanmaa', 'ry-wc-city-select' ),
		'MI' => __( 'Mikkeli', 'ry-wc-city-select' ),
		'NI' => __( 'Nivala-Haapajaervi', 'ry-wc-city-select' ),
		'OU' => __( 'Oulu', 'ry-wc-city-select' ),
		'OU2' => __( 'Oulunkaari', 'ry-wc-city-select' ),
		'PI' => __( 'Pieksaemaeki', 'ry-wc-city-select' ),
		'PIKA' => __( 'Pielisen Karjala', 'ry-wc-city-select' ),
		'PO' => __( 'Pohjois-Lappi', 'ry-wc-city-select' ),
		'PO2' => __( 'Pohjois-Satakunta', 'ry-wc-city-select' ),
		'PO3' => __( 'Pori', 'ry-wc-city-select' ),
		'PO4' => __( 'Porvoo', 'ry-wc-city-select' ),
		'RA' => __( 'Raahe', 'ry-wc-city-select' ),
		'RA2' => __( 'Raaseporin', 'ry-wc-city-select' ),
		'RA3' => __( 'Rauma', 'ry-wc-city-select' ),
		'RI' => __( 'Riihimaeki', 'ry-wc-city-select' ),
		'RO' => __( 'Rovaniemi', 'ry-wc-city-select' ),
		'SA' => __( 'Saarijaervi-Viitasaari', 'ry-wc-city-select' ),
		'SA2' => __( 'Salo', 'ry-wc-city-select' ),
		'SA3' => __( 'Savonlinna', 'ry-wc-city-select' ),
		'SE' => __( 'Seinaejoki', 'ry-wc-city-select' ),
		'SI' => __( 'Sisae-Savo', 'ry-wc-city-select' ),
		'SU' => __( 'Suupohja', 'ry-wc-city-select' ),
		'SY' => __( 'Sydosterbotten', 'ry-wc-city-select' ),
		'TA' => __( 'Tampere', 'ry-wc-city-select' ),
		'TO' => __( 'Torniolaakso', 'ry-wc-city-select' ),
		'TU' => __( 'Tunturi-Lappi', 'ry-wc-city-select' ),
		'TU2' => __( 'Turku', 'ry-wc-city-select' ),
		'VA' => __( 'Vaasa', 'ry-wc-city-select' ),
		'VA2' => __( 'Vakka-Suomi', 'ry-wc-city-select' ),
		'VA3' => __( 'Varkaus', 'ry-wc-city-select' ),
		'YL' => __( 'Ylae-Pirkanmaa', 'ry-wc-city-select' ),
		'YL2' => __( 'Ylae-Savo', 'ry-wc-city-select' ),
		'YL3' => __( 'Ylivieska', 'ry-wc-city-select' ),
		'ET2' => __( 'Etela-Pohjanmaa', 'ry-wc-city-select' ),
		'ET3' => __( 'Etelae-Karjala', 'ry-wc-city-select' ),
		'KA3' => __( 'Kainuu', 'ry-wc-city-select' ),
		'KA4' => __( 'Kanta-Haeme', 'ry-wc-city-select' ),
		'KE5' => __( 'Keski-Pohjanmaa', 'ry-wc-city-select' ),
		'KY2' => __( 'Kymenlaakso', 'ry-wc-city-select' ),
		'LA3' => __( 'Lapland', 'ry-wc-city-select' ),
		'MEFI' => __( 'Mellersta Finland', 'ry-wc-city-select' ),
		'PA' => __( 'Paijanne-Tavastland', 'ry-wc-city-select' ),
		'PI2' => __( 'Pirkanmaa', 'ry-wc-city-select' ),
		'PO5' => __( 'Pohjanmaa', 'ry-wc-city-select' ),
		'PO6' => __( 'Pohjois-Karjala', 'ry-wc-city-select' ),
		'PO7' => __( 'Pohjois-Pohjanmaa', 'ry-wc-city-select' ),
		'PO8' => __( 'Pohjois-Savo', 'ry-wc-city-select' ),
		'SA4' => __( 'Satakunta', 'ry-wc-city-select' ),
		'SOSA' => __( 'Southern Savonia', 'ry-wc-city-select' ),
		'UU' => __( 'Uusimaa', 'ry-wc-city-select' ),
		'VA4' => __( 'Varsinais-Suomi', 'ry-wc-city-select' ),
	]
];