<?php
/**
 * Republic of France states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'FR' => [
		'AI' => __( 'Ain', 'ry-wc-city-select' ),
		'AI2' => __( 'Aisne', 'ry-wc-city-select' ),
		'AL' => __( 'Allier', 'ry-wc-city-select' ),
		'AL2' => __( 'Alpes-Maritimes', 'ry-wc-city-select' ),
		'AL3' => __( 'Alpes-de-Haute-Provence', 'ry-wc-city-select' ),
		'AR' => __( 'Ardeche', 'ry-wc-city-select' ),
		'AR2' => __( 'Ardennes', 'ry-wc-city-select' ),
		'AR3' => __( 'Ariege', 'ry-wc-city-select' ),
		'AU' => __( 'Aube', 'ry-wc-city-select' ),
		'AU2' => __( 'Aude', 'ry-wc-city-select' ),
		'AV' => __( 'Aveyron', 'ry-wc-city-select' ),
		'BA' => __( 'Bas-Rhin', 'ry-wc-city-select' ),
		'BO' => __( 'Bouches-du-Rhone', 'ry-wc-city-select' ),
		'CA' => __( 'Calvados', 'ry-wc-city-select' ),
		'CA2' => __( 'Cantal', 'ry-wc-city-select' ),
		'CH' => __( 'Charente', 'ry-wc-city-select' ),
		'CH2' => __( 'Charente-Maritime', 'ry-wc-city-select' ),
		'CH3' => __( 'Cher', 'ry-wc-city-select' ),
		'CO' => __( 'Correze', 'ry-wc-city-select' ),
		'CODO' => __( 'Cote dOr', 'ry-wc-city-select' ),
		'CO2' => __( 'Cotes-dArmor', 'ry-wc-city-select' ),
		'CR' => __( 'Creuse', 'ry-wc-city-select' ),
		'DE' => __( 'Deux-Sevres', 'ry-wc-city-select' ),
		'DO' => __( 'Dordogne', 'ry-wc-city-select' ),
		'DO2' => __( 'Doubs', 'ry-wc-city-select' ),
		'DR' => __( 'Drome', 'ry-wc-city-select' ),
		'ES' => __( 'Essonne', 'ry-wc-city-select' ),
		'EU' => __( 'Eure', 'ry-wc-city-select' ),
		'EU2' => __( 'Eure-et-Loir', 'ry-wc-city-select' ),
		'FI' => __( 'Finistere', 'ry-wc-city-select' ),
		'GA' => __( 'Gard', 'ry-wc-city-select' ),
		'GE' => __( 'Gers', 'ry-wc-city-select' ),
		'GI' => __( 'Gironde', 'ry-wc-city-select' ),
		'HA' => __( 'Haut-Rhin', 'ry-wc-city-select' ),
		'HA2' => __( 'Haute-Loire', 'ry-wc-city-select' ),
		'HA3' => __( 'Haute-Marne', 'ry-wc-city-select' ),
		'HA4' => __( 'Haute-Saone', 'ry-wc-city-select' ),
		'HA5' => __( 'Haute-Savoie', 'ry-wc-city-select' ),
		'HA6' => __( 'Haute-Vienne', 'ry-wc-city-select' ),
		'HA7' => __( 'Hautes-Alpes', 'ry-wc-city-select' ),
		'HA8' => __( 'Hautes-Pyrenees', 'ry-wc-city-select' ),
		'HA9' => __( 'Hauts-de-Seine', 'ry-wc-city-select' ),
		'HE' => __( 'Herault', 'ry-wc-city-select' ),
		'IL' => __( 'Ille-et-Vilaine', 'ry-wc-city-select' ),
		'IN' => __( 'Indre', 'ry-wc-city-select' ),
		'IN2' => __( 'Indre-et-Loire', 'ry-wc-city-select' ),
		'IS' => __( 'Isere', 'ry-wc-city-select' ),
		'JU' => __( 'Jura', 'ry-wc-city-select' ),
		'LA' => __( 'Landes', 'ry-wc-city-select' ),
		'LO' => __( 'Loir-et-Cher', 'ry-wc-city-select' ),
		'LO2' => __( 'Loire', 'ry-wc-city-select' ),
		'LO3' => __( 'Loire-Atlantique', 'ry-wc-city-select' ),
		'LO4' => __( 'Loiret', 'ry-wc-city-select' ),
		'LO5' => __( 'Lot', 'ry-wc-city-select' ),
		'LO6' => __( 'Lot-et-Garonne', 'ry-wc-city-select' ),
		'LO7' => __( 'Lozere', 'ry-wc-city-select' ),
		'MA' => __( 'Maine-et-Loire', 'ry-wc-city-select' ),
		'MA2' => __( 'Manche', 'ry-wc-city-select' ),
		'MA3' => __( 'Marne', 'ry-wc-city-select' ),
		'MA4' => __( 'Mayenne', 'ry-wc-city-select' ),
		'MEMO' => __( 'Meurthe et Moselle', 'ry-wc-city-select' ),
		'ME' => __( 'Meuse', 'ry-wc-city-select' ),
		'MO' => __( 'Morbihan', 'ry-wc-city-select' ),
		'MO2' => __( 'Moselle', 'ry-wc-city-select' ),
		'NI' => __( 'Nievre', 'ry-wc-city-select' ),
		'NO' => __( 'North', 'ry-wc-city-select' ),
		'OI' => __( 'Oise', 'ry-wc-city-select' ),
		'OR' => __( 'Orne', 'ry-wc-city-select' ),
		'PA' => __( 'Paris', 'ry-wc-city-select' ),
		'PA2' => __( 'Pas-de-Calais', 'ry-wc-city-select' ),
		'PU' => __( 'Puy-de-Dome', 'ry-wc-city-select' ),
		'PY' => __( 'Pyrenees-Atlantiques', 'ry-wc-city-select' ),
		'PY2' => __( 'Pyrenees-Orientales', 'ry-wc-city-select' ),
		'RH' => __( 'Rhone', 'ry-wc-city-select' ),
		'SA' => __( 'Saone-et-Loire', 'ry-wc-city-select' ),
		'SA2' => __( 'Sarthe', 'ry-wc-city-select' ),
		'SA3' => __( 'Savoy', 'ry-wc-city-select' ),
		'SE' => __( 'Seine-Maritime', 'ry-wc-city-select' ),
		'SE2' => __( 'Seine-Saint-Denis', 'ry-wc-city-select' ),
		'SE3' => __( 'Seine-et-Marne', 'ry-wc-city-select' ),
		'SO' => __( 'Somme', 'ry-wc-city-select' ),
		'SOCO' => __( 'South Corsica', 'ry-wc-city-select' ),
		'TA' => __( 'Tarn', 'ry-wc-city-select' ),
		'TA2' => __( 'Tarn-et-Garonne', 'ry-wc-city-select' ),
		'TEBE' => __( 'Territoire de Belfort', 'ry-wc-city-select' ),
		'UPCO' => __( 'Upper Corsica', 'ry-wc-city-select' ),
		'UPGA' => __( 'Upper Garonne', 'ry-wc-city-select' ),
		'VADO' => __( 'Val dOise', 'ry-wc-city-select' ),
		'VA' => __( 'Val-de-Marne', 'ry-wc-city-select' ),
		'VA2' => __( 'Var', 'ry-wc-city-select' ),
		'VA3' => __( 'Vaucluse', 'ry-wc-city-select' ),
		'VE' => __( 'Vendee', 'ry-wc-city-select' ),
		'VI' => __( 'Vienne', 'ry-wc-city-select' ),
		'VO' => __( 'Vosges', 'ry-wc-city-select' ),
		'YO' => __( 'Yonne', 'ry-wc-city-select' ),
		'YV' => __( 'Yvelines', 'ry-wc-city-select' ),
		'AU3' => __( 'Auvergne-Rhone-Alpes', 'ry-wc-city-select' ),
		'BO2' => __( 'Bourgogne-Franche-Comte', 'ry-wc-city-select' ),
		'BR' => __( 'Bretagne', 'ry-wc-city-select' ),
		'CELO' => __( 'Centre-Val de Loire', 'ry-wc-city-select' ),
		'CO3' => __( 'Corse', 'ry-wc-city-select' ),
		'GRES' => __( 'Grand Est', 'ry-wc-city-select' ),
		'HA10' => __( 'Hauts-de-France', 'ry-wc-city-select' ),
		'IL2' => __( 'Ile-de-France', 'ry-wc-city-select' ),
		'NO2' => __( 'Normandie', 'ry-wc-city-select' ),
		'NO3' => __( 'Nouvelle-Aquitaine', 'ry-wc-city-select' ),
		'OC' => __( 'Occitanie', 'ry-wc-city-select' ),
		'PALO' => __( 'Pays de la Loire', 'ry-wc-city-select' ),
		'PRDA' => __( 'Provence-Alpes-Cote dAzur', 'ry-wc-city-select' ),
	]
];