<?php
/**
 * Hellenic Republic states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'GR' => [
		'CH' => __( 'Chios', 'ry-wc-city-select' ),
		'DO' => __( 'Dodecanese', 'ry-wc-city-select' ),
		'LE' => __( 'Lefkada', 'ry-wc-city-select' ),
		'LE2' => __( 'Lesbos', 'ry-wc-city-select' ),
		'NOANAT' => __( 'Nomarchia Anatolikis Attikis', 'ry-wc-city-select' ),
		'NOAT' => __( 'Nomarchia Athinas', 'ry-wc-city-select' ),
		'NOAC' => __( 'Nomos Achaias', 'ry-wc-city-select' ),
		'NOAIKAAK' => __( 'Nomos Aitolias kai Akarnanias', 'ry-wc-city-select' ),
		'NOAR' => __( 'Nomos Argolidos', 'ry-wc-city-select' ),
		'NOAR2' => __( 'Nomos Arkadias', 'ry-wc-city-select' ),
		'NOAR3' => __( 'Nomos Artas', 'ry-wc-city-select' ),
		'NOAT2' => __( 'Nomos Attikis', 'ry-wc-city-select' ),
		'NOCH' => __( 'Nomos Chalkidikis', 'ry-wc-city-select' ),
		'NOCH2' => __( 'Nomos Chanias', 'ry-wc-city-select' ),
		'NODR' => __( 'Nomos Dramas', 'ry-wc-city-select' ),
		'NOEV' => __( 'Nomos Evrou', 'ry-wc-city-select' ),
		'NOEV2' => __( 'Nomos Evrytanias', 'ry-wc-city-select' ),
		'NOEV3' => __( 'Nomos Evvoias', 'ry-wc-city-select' ),
		'NOFL' => __( 'Nomos Florinis', 'ry-wc-city-select' ),
		'NOFO' => __( 'Nomos Fokidos', 'ry-wc-city-select' ),
		'NOFT' => __( 'Nomos Fthiotidos', 'ry-wc-city-select' ),
		'NOGR' => __( 'Nomos Grevenon', 'ry-wc-city-select' ),
		'NOIL' => __( 'Nomos Ileias', 'ry-wc-city-select' ),
		'NOIM' => __( 'Nomos Imathias', 'ry-wc-city-select' ),
		'NOIO' => __( 'Nomos Ioanninon', 'ry-wc-city-select' ),
		'NOIR' => __( 'Nomos Irakleiou', 'ry-wc-city-select' ),
		'NOKA' => __( 'Nomos Kardhitsas', 'ry-wc-city-select' ),
		'NOKA2' => __( 'Nomos Kastorias', 'ry-wc-city-select' ),
		'NOKA3' => __( 'Nomos Kavalas', 'ry-wc-city-select' ),
		'NOKE' => __( 'Nomos Kefallinias', 'ry-wc-city-select' ),
		'NOKE2' => __( 'Nomos Kerkyras', 'ry-wc-city-select' ),
		'NOKI' => __( 'Nomos Kilkis', 'ry-wc-city-select' ),
		'NOKO' => __( 'Nomos Korinthias', 'ry-wc-city-select' ),
		'NOKO2' => __( 'Nomos Kozanis', 'ry-wc-city-select' ),
		'NOKY' => __( 'Nomos Kykladon', 'ry-wc-city-select' ),
		'NOLA' => __( 'Nomos Lakonias', 'ry-wc-city-select' ),
		'NOLA2' => __( 'Nomos Larisis', 'ry-wc-city-select' ),
		'NOLA3' => __( 'Nomos Lasithiou', 'ry-wc-city-select' ),
		'NOMA' => __( 'Nomos Magnisias', 'ry-wc-city-select' ),
		'NOME' => __( 'Nomos Messinias', 'ry-wc-city-select' ),
		'NOPE' => __( 'Nomos Pellis', 'ry-wc-city-select' ),
		'NOPI' => __( 'Nomos Pierias', 'ry-wc-city-select' ),
		'NOPI2' => __( 'Nomos Piraios', 'ry-wc-city-select' ),
		'NOPR' => __( 'Nomos Prevezis', 'ry-wc-city-select' ),
		'NORE' => __( 'Nomos Rethymnis', 'ry-wc-city-select' ),
		'NORO' => __( 'Nomos Rodopis', 'ry-wc-city-select' ),
		'NOSA' => __( 'Nomos Samou', 'ry-wc-city-select' ),
		'NOSE' => __( 'Nomos Serron', 'ry-wc-city-select' ),
		'NOTH' => __( 'Nomos Thesprotias', 'ry-wc-city-select' ),
		'NOTH2' => __( 'Nomos Thessalonikis', 'ry-wc-city-select' ),
		'NOVO' => __( 'Nomos Voiotias', 'ry-wc-city-select' ),
		'NOXA' => __( 'Nomos Xanthis', 'ry-wc-city-select' ),
		'NOZA' => __( 'Nomos Zakynthou', 'ry-wc-city-select' ),
		'TR' => __( 'Trikala', 'ry-wc-city-select' ),
		'AT' => __( 'Attica', 'ry-wc-city-select' ),
		'CEGR' => __( 'Central Greece', 'ry-wc-city-select' ),
		'CEMA' => __( 'Central Macedonia', 'ry-wc-city-select' ),
		'CR' => __( 'Crete', 'ry-wc-city-select' ),
		'EAMAANTH' => __( 'Eastern Macedonia and Thrace', 'ry-wc-city-select' ),
		'EP' => __( 'Epirus', 'ry-wc-city-select' ),
		'IOIS' => __( 'Ionian Islands', 'ry-wc-city-select' ),
		'MOAT' => __( 'Mount Athos', 'ry-wc-city-select' ),
		'NOAE' => __( 'North Aegean', 'ry-wc-city-select' ),
		'PE' => __( 'Peloponnese', 'ry-wc-city-select' ),
		'SOAE' => __( 'South Aegean', 'ry-wc-city-select' ),
		'TH' => __( 'Thessaly', 'ry-wc-city-select' ),
		'WEGR' => __( 'Western Greece', 'ry-wc-city-select' ),
		'WEMA' => __( 'Western Macedonia', 'ry-wc-city-select' ),
	]
];