<?php
/**
 * Republic of Indonesia states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'ID' => [
		'EAHARE' => __( 'East Halmahera Regency', 'ry-wc-city-select' ),
		'KAACBADA' => __( 'Kabupaten Aceh Barat Daya', 'ry-wc-city-select' ),
		'KABA' => __( 'Kabupaten Badung', 'ry-wc-city-select' ),
		'KABA2' => __( 'Kabupaten Banggai', 'ry-wc-city-select' ),
		'KABAKE' => __( 'Kabupaten Banggai Kepulauan', 'ry-wc-city-select' ),
		'KABALA' => __( 'Kabupaten Banggai Laut', 'ry-wc-city-select' ),
		'KABEME' => __( 'Kabupaten Bener Meriah', 'ry-wc-city-select' ),
		'KABI' => __( 'Kabupaten Bima', 'ry-wc-city-select' ),
		'KABU' => __( 'Kabupaten Buleleng', 'ry-wc-city-select' ),
		'KABU2' => __( 'Kabupaten Buol', 'ry-wc-city-select' ),
		'KACI' => __( 'Kabupaten Cirebon', 'ry-wc-city-select' ),
		'KADO' => __( 'Kabupaten Donggala', 'ry-wc-city-select' ),
		'KAFLTI' => __( 'Kabupaten Flores Timur', 'ry-wc-city-select' ),
		'KAHABA' => __( 'Kabupaten Halmahera Barat', 'ry-wc-city-select' ),
		'KAKA' => __( 'Kabupaten Karawang', 'ry-wc-city-select' ),
		'KAKUPR' => __( 'Kabupaten Kulon Progo', 'ry-wc-city-select' ),
		'KALOBA' => __( 'Kabupaten Lombok Barat', 'ry-wc-city-select' ),
		'KALOTE' => __( 'Kabupaten Lombok Tengah', 'ry-wc-city-select' ),
		'KALOUT' => __( 'Kabupaten Lombok Utara', 'ry-wc-city-select' ),
		'KAMABA' => __( 'Kabupaten Manggarai Barat', 'ry-wc-city-select' ),
		'KAMOUT' => __( 'Kabupaten Morowali Utara', 'ry-wc-city-select' ),
		'KANU' => __( 'Kabupaten Nunukan', 'ry-wc-city-select' ),
		'KAPAMO' => __( 'Kabupaten Parigi Moutong', 'ry-wc-city-select' ),
		'KAPA' => __( 'Kabupaten Pasuruan', 'ry-wc-city-select' ),
		'KAPEBI' => __( 'Kabupaten Pegunungan Bintang', 'ry-wc-city-select' ),
		'KAPE' => __( 'Kabupaten Pemalang', 'ry-wc-city-select' ),
		'KAPOMA' => __( 'Kabupaten Polewali Mandar', 'ry-wc-city-select' ),
		'KAPO' => __( 'Kabupaten Poso', 'ry-wc-city-select' ),
		'KAPU' => __( 'Kabupaten Purbalingga', 'ry-wc-city-select' ),
		'KASI' => __( 'Kabupaten Sigi', 'ry-wc-city-select' ),
		'KASUBA' => __( 'Kabupaten Sumbawa Barat', 'ry-wc-city-select' ),
		'KASU' => __( 'Kabupaten Sumedang', 'ry-wc-city-select' ),
		'KATO' => __( 'Kabupaten Toli-Toli', 'ry-wc-city-select' ),
		'KOBA' => __( 'Kota Batam', 'ry-wc-city-select' ),
		'KOBI' => __( 'Kota Bima', 'ry-wc-city-select' ),
		'KODE' => __( 'Kota Denpasar', 'ry-wc-city-select' ),
		'KOPA' => __( 'Kota Palu', 'ry-wc-city-select' ),
		'LARE' => __( 'Lahat Regency', 'ry-wc-city-select' ),
		'MORE' => __( 'Morowali Regency', 'ry-wc-city-select' ),
		'TOUNRE' => __( 'Tojo Una-Una Regency', 'ry-wc-city-select' ),
		'WARE' => __( 'Wakatobi Regency', 'ry-wc-city-select' ),
		'BA' => __( 'Banten', 'ry-wc-city-select' ),
		'DAISYO' => __( 'Daerah Istimewa Yogyakarta', 'ry-wc-city-select' ),
		'DAKHIBJA' => __( 'Daerah Khusus Ibukota Jakarta', 'ry-wc-city-select' ),
		'EANUTE' => __( 'East Nusa Tenggara', 'ry-wc-city-select' ),
		'JABA' => __( 'Jawa Barat', 'ry-wc-city-select' ),
		'JATI' => __( 'Jawa Timur', 'ry-wc-city-select' ),
		'KEBABE' => __( 'Kepulauan Bangka Belitung', 'ry-wc-city-select' ),
		'NAACDAPR' => __( 'Nanggroe Aceh Darussalam Province', 'ry-wc-city-select' ),
		'NOKA' => __( 'North Kalimantan', 'ry-wc-city-select' ),
		'NOMA' => __( 'North Maluku', 'ry-wc-city-select' ),
		'NOSU' => __( 'North Sumatra', 'ry-wc-city-select' ),
		'PRBE' => __( 'Propinsi Bengkulu', 'ry-wc-city-select' ),
		'PRBA' => __( 'Provinsi Bali', 'ry-wc-city-select' ),
		'PRGO' => __( 'Provinsi Gorontalo', 'ry-wc-city-select' ),
		'PRJA' => __( 'Provinsi Jambi', 'ry-wc-city-select' ),
		'PRJATE' => __( 'Provinsi Jawa Tengah', 'ry-wc-city-select' ),
		'PRKABA' => __( 'Provinsi Kalimantan Barat', 'ry-wc-city-select' ),
		'PRKASE' => __( 'Provinsi Kalimantan Selatan', 'ry-wc-city-select' ),
		'PRKATE' => __( 'Provinsi Kalimantan Tengah', 'ry-wc-city-select' ),
		'PRKATI' => __( 'Provinsi Kalimantan Timur', 'ry-wc-city-select' ),
		'PRKERI' => __( 'Provinsi Kepulauan Riau', 'ry-wc-city-select' ),
		'PRLA' => __( 'Provinsi Lampung', 'ry-wc-city-select' ),
		'PRMA' => __( 'Provinsi Maluku', 'ry-wc-city-select' ),
		'PRPA' => __( 'Provinsi Papua', 'ry-wc-city-select' ),
		'PRPABA' => __( 'Provinsi Papua Barat', 'ry-wc-city-select' ),
		'PRRI' => __( 'Provinsi Riau', 'ry-wc-city-select' ),
		'PRSUBA' => __( 'Provinsi Sulawesi Barat', 'ry-wc-city-select' ),
		'PRSUSE' => __( 'Provinsi Sulawesi Selatan', 'ry-wc-city-select' ),
		'PRSUBA2' => __( 'Provinsi Sumatera Barat', 'ry-wc-city-select' ),
		'SUTE' => __( 'Sulawesi Tenggara', 'ry-wc-city-select' ),
		'SUUT' => __( 'Sulawesi Utara', 'ry-wc-city-select' ),
		'SUSE' => __( 'Sumatera Selatan', 'ry-wc-city-select' ),
		'WENUTE' => __( 'West Nusa Tenggara', 'ry-wc-city-select' ),
		'SUTE2' => __( 'Sulawesi Tengah', 'ry-wc-city-select' ),
	]
];