<?php
/**
 * Republic of India states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'IN' => [
		'BA' => __( 'Bagalkot', 'ry-wc-city-select' ),
		'BA2' => __( 'Ballari', 'ry-wc-city-select' ),
		'BARU' => __( 'Bangalore Rural', 'ry-wc-city-select' ),
		'BAUR' => __( 'Bangalore Urban', 'ry-wc-city-select' ),
		'BE' => __( 'Belgaum', 'ry-wc-city-select' ),
		'BI' => __( 'Bidar', 'ry-wc-city-select' ),
		'BI2' => __( 'Bijapur', 'ry-wc-city-select' ),
		'CH' => __( 'Chamrajnagar', 'ry-wc-city-select' ),
		'CH2' => __( 'Chikkaballapur', 'ry-wc-city-select' ),
		'CH3' => __( 'Chikmagalur', 'ry-wc-city-select' ),
		'CH4' => __( 'Chitradurga', 'ry-wc-city-select' ),
		'DAKA' => __( 'Dakshina Kannada', 'ry-wc-city-select' ),
		'DA' => __( 'Davanagere', 'ry-wc-city-select' ),
		'DH' => __( 'Dharwad', 'ry-wc-city-select' ),
		'GA' => __( 'Gadag', 'ry-wc-city-select' ),
		'GU' => __( 'Gulbarga', 'ry-wc-city-select' ),
		'HA' => __( 'Hassan', 'ry-wc-city-select' ),
		'HA2' => __( 'Haveri', 'ry-wc-city-select' ),
		'KO' => __( 'Kodagu', 'ry-wc-city-select' ),
		'KO2' => __( 'Kolar', 'ry-wc-city-select' ),
		'KO3' => __( 'Koppal', 'ry-wc-city-select' ),
		'MA' => __( 'Mandya', 'ry-wc-city-select' ),
		'MY' => __( 'Mysore', 'ry-wc-city-select' ),
		'RA' => __( 'Raichur', 'ry-wc-city-select' ),
		'RA2' => __( 'Ramanagara', 'ry-wc-city-select' ),
		'SH' => __( 'Shimoga', 'ry-wc-city-select' ),
		'TH' => __( 'Thiruvananthapuram', 'ry-wc-city-select' ),
		'TU' => __( 'Tumkur', 'ry-wc-city-select' ),
		'UD' => __( 'Udupi', 'ry-wc-city-select' ),
		'UTKA' => __( 'Uttar Kannada', 'ry-wc-city-select' ),
		'WETR' => __( 'West Tripura', 'ry-wc-city-select' ),
		'YA' => __( 'Yadgir', 'ry-wc-city-select' ),
		'AS' => __( 'Assam', 'ry-wc-city-select' ),
		'GO' => __( 'Goa', 'ry-wc-city-select' ),
		'LA' => __( 'Ladakh', 'ry-wc-city-select' ),
		'MAPR' => __( 'Madhya Pradesh', 'ry-wc-city-select' ),
		'MA2' => __( 'Manipur', 'ry-wc-city-select' ),
		'ME' => __( 'Meghalaya', 'ry-wc-city-select' ),
		'MI' => __( 'Mizoram', 'ry-wc-city-select' ),
		'NACATEDE' => __( 'National Capital Territory of Delhi', 'ry-wc-city-select' ),
		'SI' => __( 'Sikkim', 'ry-wc-city-select' ),
		'STANPR' => __( 'State of Andhra Pradesh', 'ry-wc-city-select' ),
		'STARPR' => __( 'State of Arunachal Pradesh', 'ry-wc-city-select' ),
		'STBI' => __( 'State of Bihar', 'ry-wc-city-select' ),
		'STCH' => __( 'State of Chhattisgarh', 'ry-wc-city-select' ),
		'STGU' => __( 'State of Gujarat', 'ry-wc-city-select' ),
		'STHA' => __( 'State of Haryana', 'ry-wc-city-select' ),
		'STHIPR' => __( 'State of Himachal Pradesh', 'ry-wc-city-select' ),
		'STJAANKA' => __( 'State of Jammu and Kashmir', 'ry-wc-city-select' ),
		'STJH' => __( 'State of Jharkhand', 'ry-wc-city-select' ),
		'STKE' => __( 'State of Kerala', 'ry-wc-city-select' ),
		'STMA' => __( 'State of Maharashtra', 'ry-wc-city-select' ),
		'STNA' => __( 'State of Nagaland', 'ry-wc-city-select' ),
		'STOD' => __( 'State of Odisha', 'ry-wc-city-select' ),
		'STPU' => __( 'State of Punjab', 'ry-wc-city-select' ),
		'STRA' => __( 'State of Rajasthan', 'ry-wc-city-select' ),
		'STTANA' => __( 'State of Tamil Nadu', 'ry-wc-city-select' ),
		'STUT' => __( 'State of Uttarakhand', 'ry-wc-city-select' ),
		'TE' => __( 'Telangana', 'ry-wc-city-select' ),
		'TR' => __( 'Tripura', 'ry-wc-city-select' ),
		'UNTEANANNI' => __( 'Union Territory of Andaman and Nicobar I', 'ry-wc-city-select' ),
		'UNTECH' => __( 'Union Territory of Chandigarh', 'ry-wc-city-select' ),
		'UNTEDAANNAHA' => __( 'Union Territory of Dadra and Nagar Havel', 'ry-wc-city-select' ),
		'UNTEDAANDI' => __( 'Union Territory of Daman and Diu', 'ry-wc-city-select' ),
		'UNTELA' => __( 'Union Territory of Lakshadweep', 'ry-wc-city-select' ),
		'UNTEPU' => __( 'Union Territory of Puducherry', 'ry-wc-city-select' ),
		'UTPR' => __( 'Uttar Pradesh', 'ry-wc-city-select' ),
		'WEBE' => __( 'West Bengal', 'ry-wc-city-select' ),
		'STKA' => __( 'State of Karnataka', 'ry-wc-city-select' ),
	]
];