<?php
/**
 * Republic of Latvia states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'LV' => [
		'ADNO' => __( 'Adazu Novads', 'ry-wc-city-select' ),
		'AGNO' => __( 'Aglonas Novads', 'ry-wc-city-select' ),
		'AINO' => __( 'Aizkraukles novads', 'ry-wc-city-select' ),
		'AINO2' => __( 'Aizputes Novads', 'ry-wc-city-select' ),
		'AKNO' => __( 'Aknistes Novads', 'ry-wc-city-select' ),
		'ALNO' => __( 'Alojas Novads', 'ry-wc-city-select' ),
		'ALNO2' => __( 'Alsungas Novads', 'ry-wc-city-select' ),
		'ALNO3' => __( 'Aluksnes Novads', 'ry-wc-city-select' ),
		'AMNO' => __( 'Amatas Novads', 'ry-wc-city-select' ),
		'APNO' => __( 'Apes Novads', 'ry-wc-city-select' ),
		'AUNO' => __( 'Auces Novads', 'ry-wc-city-select' ),
		'BANO' => __( 'Babites Novads', 'ry-wc-city-select' ),
		'BANO2' => __( 'Baldones Novads', 'ry-wc-city-select' ),
		'BANO3' => __( 'Baltinavas Novads', 'ry-wc-city-select' ),
		'BANO4' => __( 'Balvu Novads', 'ry-wc-city-select' ),
		'BANO5' => __( 'Bauskas Novads', 'ry-wc-city-select' ),
		'BENO' => __( 'Beverinas Novads', 'ry-wc-city-select' ),
		'BRNO' => __( 'Brocenu Novads', 'ry-wc-city-select' ),
		'BUNO' => __( 'Burtnieku Novads', 'ry-wc-city-select' ),
		'CANO' => __( 'Carnikavas Novads', 'ry-wc-city-select' ),
		'CENO' => __( 'Cesu Novads', 'ry-wc-city-select' ),
		'CENO2' => __( 'Cesvaines Novads', 'ry-wc-city-select' ),
		'CINO' => __( 'Ciblas Novads', 'ry-wc-city-select' ),
		'DANO' => __( 'Dagdas Novads', 'ry-wc-city-select' ),
		'DA' => __( 'Daugavpils', 'ry-wc-city-select' ),
		'DAMU' => __( 'Daugavpils municipality', 'ry-wc-city-select' ),
		'DONO' => __( 'Dobeles novads', 'ry-wc-city-select' ),
		'DUNO' => __( 'Dundagas Novads', 'ry-wc-city-select' ),
		'DUNO2' => __( 'Durbes Novads', 'ry-wc-city-select' ),
		'ENNO' => __( 'Engures Novads', 'ry-wc-city-select' ),
		'ERNO' => __( 'Erglu Novads', 'ry-wc-city-select' ),
		'GAMU' => __( 'Garkalne Municipality', 'ry-wc-city-select' ),
		'GRNO' => __( 'Grobinas Novads', 'ry-wc-city-select' ),
		'GUNO' => __( 'Gulbenes novads', 'ry-wc-city-select' ),
		'IENO' => __( 'Iecavas Novads', 'ry-wc-city-select' ),
		'IKNO' => __( 'Ikskiles Novads', 'ry-wc-city-select' ),
		'ILNO' => __( 'Ilukstes Novads', 'ry-wc-city-select' ),
		'INNO' => __( 'Incukalna Novads', 'ry-wc-city-select' ),
		'JANO' => __( 'Jaunjelgavas Novads', 'ry-wc-city-select' ),
		'JANO2' => __( 'Jaunpiebalgas Novads', 'ry-wc-city-select' ),
		'JANO3' => __( 'Jaunpils Novads', 'ry-wc-city-select' ),
		'JE' => __( 'Jekabpils', 'ry-wc-city-select' ),
		'JEMU' => __( 'Jekabpils Municipality', 'ry-wc-city-select' ),
		'JE2' => __( 'Jelgava', 'ry-wc-city-select' ),
		'JENO' => __( 'Jelgavas novads', 'ry-wc-city-select' ),
		'JU' => __( 'Jurmala', 'ry-wc-city-select' ),
		'KANO' => __( 'Kandavas Novads', 'ry-wc-city-select' ),
		'KANO2' => __( 'Karsavas Novads', 'ry-wc-city-select' ),
		'KENO' => __( 'Keguma Novads', 'ry-wc-city-select' ),
		'KENO2' => __( 'Kekavas Novads', 'ry-wc-city-select' ),
		'KONO' => __( 'Kocenu Novads', 'ry-wc-city-select' ),
		'KONO2' => __( 'Kokneses Novads', 'ry-wc-city-select' ),
		'KRNO' => __( 'Kraslavas novads', 'ry-wc-city-select' ),
		'KRNO2' => __( 'Krimuldas Novads', 'ry-wc-city-select' ),
		'KRNO3' => __( 'Krustpils Novads', 'ry-wc-city-select' ),
		'KUNO' => __( 'Kuldigas novads', 'ry-wc-city-select' ),
		'LINO' => __( 'Lielvardes Novads', 'ry-wc-city-select' ),
		'LI' => __( 'Liepaja', 'ry-wc-city-select' ),
		'LINO2' => __( 'Ligatnes Novads', 'ry-wc-city-select' ),
		'LINO3' => __( 'Limbazu novads', 'ry-wc-city-select' ),
		'LINO4' => __( 'Livanu Novads', 'ry-wc-city-select' ),
		'LUNO' => __( 'Lubanas Novads', 'ry-wc-city-select' ),
		'LUNO2' => __( 'Ludzas novads', 'ry-wc-city-select' ),
		'MAMU' => __( 'Madona Municipality', 'ry-wc-city-select' ),
		'MANO' => __( 'Malpils Novads', 'ry-wc-city-select' ),
		'MANO2' => __( 'Marupes Novads', 'ry-wc-city-select' ),
		'MANO3' => __( 'Mazsalacas Novads', 'ry-wc-city-select' ),
		'MENO' => __( 'Mersraga Novads', 'ry-wc-city-select' ),
		'NANO' => __( 'Nauksenu Novads', 'ry-wc-city-select' ),
		'NENO' => __( 'Neretas Novads', 'ry-wc-city-select' ),
		'NINO' => __( 'Nicas Novads', 'ry-wc-city-select' ),
		'OGNO' => __( 'Ogres novads', 'ry-wc-city-select' ),
		'OLNO' => __( 'Olaines Novads', 'ry-wc-city-select' ),
		'OZNO' => __( 'Ozolnieku Novads', 'ry-wc-city-select' ),
		'PANO' => __( 'Pargaujas Novads', 'ry-wc-city-select' ),
		'PANO2' => __( 'Pavilostas Novads', 'ry-wc-city-select' ),
		'PLNO' => __( 'Plavinu Novads', 'ry-wc-city-select' ),
		'PRMU' => __( 'Preili Municipality', 'ry-wc-city-select' ),
		'PRNO' => __( 'Priekules Novads', 'ry-wc-city-select' ),
		'PRMU2' => __( 'Priekuli Municipality', 'ry-wc-city-select' ),
		'RANO' => __( 'Raunas Novads', 'ry-wc-city-select' ),
		'RE' => __( 'Rezekne', 'ry-wc-city-select' ),
		'RENO' => __( 'Rezeknes Novads', 'ry-wc-city-select' ),
		'RINO' => __( 'Riebinu Novads', 'ry-wc-city-select' ),
		'RI' => __( 'Riga', 'ry-wc-city-select' ),
		'RONO' => __( 'Rojas Novads', 'ry-wc-city-select' ),
		'RONO2' => __( 'Ropazu Novads', 'ry-wc-city-select' ),
		'RUNO' => __( 'Rucavas Novads', 'ry-wc-city-select' ),
		'RUNO2' => __( 'Rugaju Novads', 'ry-wc-city-select' ),
		'RUNO3' => __( 'Rujienas Novads', 'ry-wc-city-select' ),
		'RUNO4' => __( 'Rundales Novads', 'ry-wc-city-select' ),
		'SANO' => __( 'Salacgrivas Novads', 'ry-wc-city-select' ),
		'SANO2' => __( 'Salas Novads', 'ry-wc-city-select' ),
		'SANO3' => __( 'Salaspils Novads', 'ry-wc-city-select' ),
		'SAMU' => __( 'Saldus Municipality', 'ry-wc-city-select' ),
		'SANO4' => __( 'Saulkrastu Novads', 'ry-wc-city-select' ),
		'SENO' => __( 'Sejas Novads', 'ry-wc-city-select' ),
		'SINO' => __( 'Siguldas Novads', 'ry-wc-city-select' ),
		'SKNO' => __( 'Skriveru Novads', 'ry-wc-city-select' ),
		'SKNO2' => __( 'Skrundas Novads', 'ry-wc-city-select' ),
		'SMNO' => __( 'Smiltenes Novads', 'ry-wc-city-select' ),
		'STNO' => __( 'Stopinu Novads', 'ry-wc-city-select' ),
		'STNO2' => __( 'Strencu Novads', 'ry-wc-city-select' ),
		'TAMU' => __( 'Talsi Municipality', 'ry-wc-city-select' ),
		'TENO' => __( 'Tervetes Novads', 'ry-wc-city-select' ),
		'TUNO' => __( 'Tukuma novads', 'ry-wc-city-select' ),
		'VANO' => __( 'Vainodes Novads', 'ry-wc-city-select' ),
		'VAMU' => __( 'Valka Municipality', 'ry-wc-city-select' ),
		'VA' => __( 'Valmiera', 'ry-wc-city-select' ),
		'VANO2' => __( 'Varaklanu Novads', 'ry-wc-city-select' ),
		'VANO3' => __( 'Varkavas Novads', 'ry-wc-city-select' ),
		'VENO' => __( 'Vecpiebalgas Novads', 'ry-wc-city-select' ),
		'VENO2' => __( 'Vecumnieku Novads', 'ry-wc-city-select' ),
		'VE' => __( 'Ventspils', 'ry-wc-city-select' ),
		'VEMU' => __( 'Ventspils Municipality', 'ry-wc-city-select' ),
		'VINO' => __( 'Viesites Novads', 'ry-wc-city-select' ),
		'VINO2' => __( 'Vilakas Novads', 'ry-wc-city-select' ),
		'VINO3' => __( 'Vilanu Novads', 'ry-wc-city-select' ),
		'ZINO' => __( 'Zilupes Novads', 'ry-wc-city-select' ),
	]
];