<?php
/**
 * Kingdom of Morocco states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MA' => [
		'AG' => __( 'Agadir-Ida-ou-Tnan', 'ry-wc-city-select' ),
		'AL' => __( 'Al-Haouz', 'ry-wc-city-select' ),
		'AL2' => __( 'Al-Hoceima', 'ry-wc-city-select' ),
		'AO' => __( 'Aousserd', 'ry-wc-city-select' ),
		'AS' => __( 'Assa-Zag', 'ry-wc-city-select' ),
		'AZPR' => __( 'Azilal Province', 'ry-wc-city-select' ),
		'BE' => __( 'Beni-Mellal', 'ry-wc-city-select' ),
		'BE2' => __( 'Benslimane', 'ry-wc-city-select' ),
		'BE3' => __( 'Berkane', 'ry-wc-city-select' ),
		'BO' => __( 'Boujdour', 'ry-wc-city-select' ),
		'BO2' => __( 'Boulemane', 'ry-wc-city-select' ),
		'CA' => __( 'Casablanca', 'ry-wc-city-select' ),
		'CHPR' => __( 'Chefchaouen Province', 'ry-wc-city-select' ),
		'CH' => __( 'Chichaoua', 'ry-wc-city-select' ),
		'CH2' => __( 'Chtouka-Ait-Baha', 'ry-wc-city-select' ),
		'EL' => __( 'El-Hajeb', 'ry-wc-city-select' ),
		'EL2' => __( 'El-Jadida', 'ry-wc-city-select' ),
		'ER' => __( 'Errachidia', 'ry-wc-city-select' ),
		'ES' => __( 'Es-Semara', 'ry-wc-city-select' ),
		'ES2' => __( 'Essaouira', 'ry-wc-city-select' ),
		'FA' => __( 'Fahs-Anjra', 'ry-wc-city-select' ),
		'FE' => __( 'Fes', 'ry-wc-city-select' ),
		'FI' => __( 'Figuig', 'ry-wc-city-select' ),
		'FQBESAPR' => __( 'Fquih Ben Salah Province', 'ry-wc-city-select' ),
		'GU' => __( 'Guelmim', 'ry-wc-city-select' ),
		'IF' => __( 'Ifrane', 'ry-wc-city-select' ),
		'INME' => __( 'Inezgane-Ait Melloul', 'ry-wc-city-select' ),
		'JE' => __( 'Jerada', 'ry-wc-city-select' ),
		'KE' => __( 'Kelaa-Des-Sraghna', 'ry-wc-city-select' ),
		'KEPR' => __( 'Kenitra Province', 'ry-wc-city-select' ),
		'KH' => __( 'Khemisset', 'ry-wc-city-select' ),
		'KH2' => __( 'Khenifra', 'ry-wc-city-select' ),
		'KHPR' => __( 'Khouribga Province', 'ry-wc-city-select' ),
		'LA' => __( 'Laayoune', 'ry-wc-city-select' ),
		'LA2' => __( 'Larache', 'ry-wc-city-select' ),
		'MD' => __( 'MDiq-Fnideq', 'ry-wc-city-select' ),
		'MA' => __( 'Marrakech', 'ry-wc-city-select' ),
		'ME' => __( 'Mediouna', 'ry-wc-city-select' ),
		'ME2' => __( 'Meknes', 'ry-wc-city-select' ),
		'MO' => __( 'Mohammedia', 'ry-wc-city-select' ),
		'MO2' => __( 'Moulay-Yacoub', 'ry-wc-city-select' ),
		'NA' => __( 'Nador', 'ry-wc-city-select' ),
		'NO' => __( 'Nouaceur', 'ry-wc-city-select' ),
		'OU' => __( 'Ouarzazate', 'ry-wc-city-select' ),
		'OU2' => __( 'Oued-Ed-Dahab', 'ry-wc-city-select' ),
		'OUPR' => __( 'Ouezzane Province', 'ry-wc-city-select' ),
		'OU3' => __( 'Oujda-Angad', 'ry-wc-city-select' ),
		'RA' => __( 'Rabat', 'ry-wc-city-select' ),
		'SA' => __( 'Safi', 'ry-wc-city-select' ),
		'SA2' => __( 'Sale', 'ry-wc-city-select' ),
		'SE' => __( 'Sefrou', 'ry-wc-city-select' ),
		'SEPR' => __( 'Settat Province', 'ry-wc-city-select' ),
		'SISL' => __( 'Sidi Slimane', 'ry-wc-city-select' ),
		'SI' => __( 'Sidi-Kacem', 'ry-wc-city-select' ),
		'SK' => __( 'Skhirate-Temara', 'ry-wc-city-select' ),
		'TA' => __( 'Tan-Tan', 'ry-wc-city-select' ),
		'TA2' => __( 'Tanger-Assilah', 'ry-wc-city-select' ),
		'TA3' => __( 'Taounate', 'ry-wc-city-select' ),
		'TA4' => __( 'Taourirt', 'ry-wc-city-select' ),
		'TA5' => __( 'Taroudannt', 'ry-wc-city-select' ),
		'TA6' => __( 'Tata', 'ry-wc-city-select' ),
		'TA7' => __( 'Taza', 'ry-wc-city-select' ),
		'TE' => __( 'Tetouan', 'ry-wc-city-select' ),
		'TIPR' => __( 'Tinghir Province', 'ry-wc-city-select' ),
		'TI' => __( 'Tiznit', 'ry-wc-city-select' ),
		'ZA' => __( 'Zagora', 'ry-wc-city-select' ),
		'CA2' => __( 'Casablanca-Settat', 'ry-wc-city-select' ),
		'DR' => __( 'Draa-Tafilalet', 'ry-wc-city-select' ),
		'GUNO' => __( 'Guelmim-Oued Noun', 'ry-wc-city-select' ),
		'LAHA' => __( 'Laayoune-Sakia El Hamra', 'ry-wc-city-select' ),
		'MA2' => __( 'Marrakesh-Safi', 'ry-wc-city-select' ),
		'OR' => __( 'Oriental', 'ry-wc-city-select' ),
		'BEME' => __( 'Beni Mellal-Khenifra', 'ry-wc-city-select' ),
		'DAED' => __( 'Dakhla-Oued Ed-Dahab', 'ry-wc-city-select' ),
		'FE2' => __( 'Fes-Meknes', 'ry-wc-city-select' ),
		'RA2' => __( 'Rabat-Sale-Kenitra', 'ry-wc-city-select' ),
		'SO' => __( 'Souss-Massa', 'ry-wc-city-select' ),
		'TAHO' => __( 'Tanger-Tetouan-Al Hoceima', 'ry-wc-city-select' ),
	]
];