<?php
/**
 * Union of Burma states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MM' => [
		'BADI' => __( 'Bago District', 'ry-wc-city-select' ),
		'BADI2' => __( 'Bawlakhe District', 'ry-wc-city-select' ),
		'BHDI' => __( 'Bhamo District', 'ry-wc-city-select' ),
		'DADI' => __( 'Dawei District', 'ry-wc-city-select' ),
		'FA' => __( 'Falam', 'ry-wc-city-select' ),
		'GADI' => __( 'Gangaw District', 'ry-wc-city-select' ),
		'HA' => __( 'Hakha', 'ry-wc-city-select' ),
		'HIDI' => __( 'Hinthada District', 'ry-wc-city-select' ),
		'HKDI' => __( 'Hkamti District', 'ry-wc-city-select' ),
		'HO' => __( 'Hopang', 'ry-wc-city-select' ),
		'HPDI' => __( 'Hpa-an District', 'ry-wc-city-select' ),
		'HP' => __( 'Hpapun', 'ry-wc-city-select' ),
		'KADI' => __( 'Kale District', 'ry-wc-city-select' ),
		'KADI2' => __( 'Katha District', 'ry-wc-city-select' ),
		'KADI3' => __( 'Kawkareik District', 'ry-wc-city-select' ),
		'KADI4' => __( 'Kawthaung District', 'ry-wc-city-select' ),
		'KEDI' => __( 'Kengtung District', 'ry-wc-city-select' ),
		'KYDI' => __( 'Kyaukme District', 'ry-wc-city-select' ),
		'KYDI2' => __( 'Kyaukse District', 'ry-wc-city-select' ),
		'KYDI3' => __( 'Kyaunkpyu District', 'ry-wc-city-select' ),
		'LADI' => __( 'Labutta District', 'ry-wc-city-select' ),
		'LADI2' => __( 'Langhko District', 'ry-wc-city-select' ),
		'LADI3' => __( 'Lashio District', 'ry-wc-city-select' ),
		'LA' => __( 'Laukkaing', 'ry-wc-city-select' ),
		'LODI' => __( 'Loikaw District', 'ry-wc-city-select' ),
		'LODI2' => __( 'Loilem District', 'ry-wc-city-select' ),
		'MADI' => __( 'Ma-ubin District', 'ry-wc-city-select' ),
		'MADI2' => __( 'Magway District', 'ry-wc-city-select' ),
		'MADI3' => __( 'Mandalay District', 'ry-wc-city-select' ),
		'MA' => __( 'Matman', 'ry-wc-city-select' ),
		'MADI4' => __( 'Maungdaw District', 'ry-wc-city-select' ),
		'MADI5' => __( 'Mawlaik District', 'ry-wc-city-select' ),
		'MADI6' => __( 'Mawlamyine District', 'ry-wc-city-select' ),
		'MEDI' => __( 'Meiktila District', 'ry-wc-city-select' ),
		'MIDI' => __( 'Minbu District', 'ry-wc-city-select' ),
		'MI' => __( 'Mindat', 'ry-wc-city-select' ),
		'MODI' => __( 'Mohnyin District', 'ry-wc-city-select' ),
		'MOHSDI' => __( 'Mong Hsat District', 'ry-wc-city-select' ),
		'MO' => __( 'Mongmit', 'ry-wc-city-select' ),
		'MO2' => __( 'Monywa', 'ry-wc-city-select' ),
		'MR' => __( 'Mrauk-U', 'ry-wc-city-select' ),
		'DI' => __( 'Mu Se District', 'ry-wc-city-select' ),
		'MYDI' => __( 'Myaungmya District', 'ry-wc-city-select' ),
		'MYDI2' => __( 'Myawaddy District', 'ry-wc-city-select' ),
		'MYDI3' => __( 'Myeik District', 'ry-wc-city-select' ),
		'MYDI4' => __( 'Myingyan District', 'ry-wc-city-select' ),
		'MYDI5' => __( 'Myitkyina District', 'ry-wc-city-select' ),
		'NAPYTA(N' => __( 'Nay Pyi Taw (North)', 'ry-wc-city-select' ),
		'NAPYTA(S' => __( 'Nay Pyi Taw (South)', 'ry-wc-city-select' ),
		'NYDI' => __( 'Nyaung-U District', 'ry-wc-city-select' ),
		'PADI' => __( 'Pakokku District', 'ry-wc-city-select' ),
		'PADI2' => __( 'Pathein District', 'ry-wc-city-select' ),
		'PUDI' => __( 'Putao District', 'ry-wc-city-select' ),
		'PYDI' => __( 'Pyapon District', 'ry-wc-city-select' ),
		'PYDI2' => __( 'Pyay District', 'ry-wc-city-select' ),
		'PYLWDI' => __( 'Pyin Oo Lwin District', 'ry-wc-city-select' ),
		'SADI' => __( 'Sagaing District', 'ry-wc-city-select' ),
		'SHDI' => __( 'Shwebo District', 'ry-wc-city-select' ),
		'SIDI' => __( 'Sittwe District', 'ry-wc-city-select' ),
		'TADI' => __( 'Tachileik District', 'ry-wc-city-select' ),
		'TADI2' => __( 'Tamu District', 'ry-wc-city-select' ),
		'TADI3' => __( 'Taunggyi District', 'ry-wc-city-select' ),
		'TADI4' => __( 'Taungoo District', 'ry-wc-city-select' ),
		'THDI' => __( 'Thandwe District', 'ry-wc-city-select' ),
		'THDI2' => __( 'Thaton District', 'ry-wc-city-select' ),
		'THDI3' => __( 'Thayarwady District', 'ry-wc-city-select' ),
		'THDI4' => __( 'Thayet District', 'ry-wc-city-select' ),
		'YADI' => __( 'Yamethin District', 'ry-wc-city-select' ),
		'YA(E' => __( 'Yangon (East)', 'ry-wc-city-select' ),
		'YA(N' => __( 'Yangon (North)', 'ry-wc-city-select' ),
		'YAEADI' => __( 'Yangon East District', 'ry-wc-city-select' ),
		'YASODI' => __( 'Yangon South District', 'ry-wc-city-select' ),
		'YI' => __( 'Yinmabin', 'ry-wc-city-select' ),
		'AYRE' => __( 'Ayeyarwady Region', 'ry-wc-city-select' ),
		'BARE' => __( 'Bago Region', 'ry-wc-city-select' ),
		'CHST' => __( 'Chin State', 'ry-wc-city-select' ),
		'KAST' => __( 'Kachin State', 'ry-wc-city-select' ),
		'KAST2' => __( 'Kayah State', 'ry-wc-city-select' ),
		'KAST3' => __( 'Kayin State', 'ry-wc-city-select' ),
		'MARE' => __( 'Magway Region', 'ry-wc-city-select' ),
		'MARE2' => __( 'Mandalay Region', 'ry-wc-city-select' ),
		'MOST' => __( 'Mon State', 'ry-wc-city-select' ),
		'NAPYTA' => __( 'Nay Pyi Taw', 'ry-wc-city-select' ),
		'RAST' => __( 'Rakhine State', 'ry-wc-city-select' ),
		'SARE' => __( 'Sagaing Region', 'ry-wc-city-select' ),
		'SHST' => __( 'Shan State', 'ry-wc-city-select' ),
		'TARE' => __( 'Tanintharyi Region', 'ry-wc-city-select' ),
		'YARE' => __( 'Yangon Region', 'ry-wc-city-select' ),
	]
];