<?php
/**
 * Republic of Malta states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MT' => [
		'AT' => __( 'Attard', 'ry-wc-city-select' ),
		'BA' => __( 'Balzan', 'ry-wc-city-select' ),
		'BI' => __( 'Birkirkara', 'ry-wc-city-select' ),
		'BI2' => __( 'Birzebbuga', 'ry-wc-city-select' ),
		'BO' => __( 'Bormla', 'ry-wc-city-select' ),
		'DI' => __( 'Dingli', 'ry-wc-city-select' ),
		'GH' => __( 'Ghajnsielem', 'ry-wc-city-select' ),
		'HAGH' => __( 'Hal Gharghur', 'ry-wc-city-select' ),
		'HAGH2' => __( 'Hal Ghaxaq', 'ry-wc-city-select' ),
		'HA' => __( 'Haz-Zabbar', 'ry-wc-city-select' ),
		'HA2' => __( 'Haz-Zebbug', 'ry-wc-city-select' ),
		'IL' => __( 'Il-Birgu', 'ry-wc-city-select' ),
		'IL2' => __( 'Il-Fgura', 'ry-wc-city-select' ),
		'IL3' => __( 'Il-Fontana', 'ry-wc-city-select' ),
		'IL4' => __( 'Il-Furjana', 'ry-wc-city-select' ),
		'IL5' => __( 'Il-Gudja', 'ry-wc-city-select' ),
		'IL6' => __( 'Il-Gzira', 'ry-wc-city-select' ),
		'IL7' => __( 'Il-Hamrun', 'ry-wc-city-select' ),
		'IL8' => __( 'Il-Kalkara', 'ry-wc-city-select' ),
		'IL9' => __( 'Il-Marsa', 'ry-wc-city-select' ),
		'IL10' => __( 'Il-Mellieha', 'ry-wc-city-select' ),
		'IL11' => __( 'Il-Mosta', 'ry-wc-city-select' ),
		'IL12' => __( 'Il-Munxar', 'ry-wc-city-select' ),
		'IL13' => __( 'Il-Qala', 'ry-wc-city-select' ),
		'IL14' => __( 'Il-Qrendi', 'ry-wc-city-select' ),
		'IN' => __( 'In-Nadur', 'ry-wc-city-select' ),
		'IN2' => __( 'In-Naxxar', 'ry-wc-city-select' ),
		'IR' => __( 'Ir-Rabat', 'ry-wc-city-select' ),
		'IS' => __( 'Is-Siggiewi', 'ry-wc-city-select' ),
		'IS2' => __( 'Is-Swieqi', 'ry-wc-city-select' ),
		'IX' => __( 'Ix-Xaghra', 'ry-wc-city-select' ),
		'IX2' => __( 'Ix-Xewkija', 'ry-wc-city-select' ),
		'IX3' => __( 'Ix-Xghajra', 'ry-wc-city-select' ),
		'IZ' => __( 'Iz-Zebbug', 'ry-wc-city-select' ),
		'IZ2' => __( 'Iz-Zejtun', 'ry-wc-city-select' ),
		'IZ3' => __( 'Iz-Zurrieq', 'ry-wc-city-select' ),
		'KI' => __( 'Kirkop', 'ry-wc-city-select' ),
		'L-' => __( 'L-Gharb', 'ry-wc-city-select' ),
		'L-2' => __( 'L-Ghasri', 'ry-wc-city-select' ),
		'L-3' => __( 'L-Iklin', 'ry-wc-city-select' ),
		'L-4' => __( 'L-Imdina', 'ry-wc-city-select' ),
		'L-5' => __( 'L-Imgarr', 'ry-wc-city-select' ),
		'L-6' => __( 'L-Imqabba', 'ry-wc-city-select' ),
		'L-7' => __( 'L-Imsida', 'ry-wc-city-select' ),
		'L-8' => __( 'L-Imtarfa', 'ry-wc-city-select' ),
		'L-9' => __( 'L-Isla', 'ry-wc-city-select' ),
		'LI' => __( 'Lija', 'ry-wc-city-select' ),
		'LU' => __( 'Luqa', 'ry-wc-city-select' ),
		'MA' => __( 'Marsaskala', 'ry-wc-city-select' ),
		'MA2' => __( 'Marsaxlokk', 'ry-wc-city-select' ),
		'PA' => __( 'Paola', 'ry-wc-city-select' ),
		'PE' => __( 'Pembroke', 'ry-wc-city-select' ),
		'QO' => __( 'Qormi', 'ry-wc-city-select' ),
		'SA' => __( 'Safi', 'ry-wc-city-select' ),
		'SAJO' => __( 'Saint John', 'ry-wc-city-select' ),
		'SAJU' => __( 'Saint Julians', 'ry-wc-city-select' ),
		'SALA' => __( 'Saint Lawrence', 'ry-wc-city-select' ),
		'SALU' => __( 'Saint Lucia', 'ry-wc-city-select' ),
		'SAPABA' => __( 'Saint Pauls Bay', 'ry-wc-city-select' ),
		'SAVE' => __( 'Saint Venera', 'ry-wc-city-select' ),
		'SA2' => __( 'Sannat', 'ry-wc-city-select' ),
		'KE' => __( 'Ta Kercem', 'ry-wc-city-select' ),
		'XB' => __( 'Ta Xbiex', 'ry-wc-city-select' ),
		'TA' => __( 'Tal-Pieta', 'ry-wc-city-select' ),
		'TA2' => __( 'Tarxien', 'ry-wc-city-select' ),
		'TA3' => __( 'Tas-Sliema', 'ry-wc-city-select' ),
		'VA' => __( 'Valletta', 'ry-wc-city-select' ),
		'VI' => __( 'Victoria', 'ry-wc-city-select' ),
	]
];