<?php
/**
 * Federal Democratic Republic of Nepal states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'NP' => [
		'AC' => __( 'Achham', 'ry-wc-city-select' ),
		'AR' => __( 'Arghakhanchi', 'ry-wc-city-select' ),
		'BA' => __( 'Baglung', 'ry-wc-city-select' ),
		'BA2' => __( 'Baitadi', 'ry-wc-city-select' ),
		'BA3' => __( 'Bajhang', 'ry-wc-city-select' ),
		'BA4' => __( 'Bajura', 'ry-wc-city-select' ),
		'BA5' => __( 'Banke', 'ry-wc-city-select' ),
		'BA6' => __( 'Bara', 'ry-wc-city-select' ),
		'BA7' => __( 'Bardiya', 'ry-wc-city-select' ),
		'BH' => __( 'Bhaktapur', 'ry-wc-city-select' ),
		'BH2' => __( 'Bhojpur', 'ry-wc-city-select' ),
		'CH' => __( 'Chitwan', 'ry-wc-city-select' ),
		'DA' => __( 'Dadeldhura', 'ry-wc-city-select' ),
		'DA2' => __( 'Dailekh', 'ry-wc-city-select' ),
		'DA3' => __( 'Dang', 'ry-wc-city-select' ),
		'DA4' => __( 'Darchula', 'ry-wc-city-select' ),
		'DH' => __( 'Dhading', 'ry-wc-city-select' ),
		'DH2' => __( 'Dhankuta', 'ry-wc-city-select' ),
		'DH3' => __( 'Dhanusa', 'ry-wc-city-select' ),
		'DO' => __( 'Dolakha', 'ry-wc-city-select' ),
		'DO2' => __( 'Dolpa', 'ry-wc-city-select' ),
		'DO3' => __( 'Doti', 'ry-wc-city-select' ),
		'GO' => __( 'Gorkha', 'ry-wc-city-select' ),
		'GU' => __( 'Gulmi', 'ry-wc-city-select' ),
		'HU' => __( 'Humla', 'ry-wc-city-select' ),
		'IL' => __( 'Ilam', 'ry-wc-city-select' ),
		'JA' => __( 'Jajarkot', 'ry-wc-city-select' ),
		'JH' => __( 'Jhapa', 'ry-wc-city-select' ),
		'JU' => __( 'Jumla', 'ry-wc-city-select' ),
		'KA' => __( 'Kailali', 'ry-wc-city-select' ),
		'KA2' => __( 'Kalikot', 'ry-wc-city-select' ),
		'KA3' => __( 'Kanchanpur', 'ry-wc-city-select' ),
		'KA4' => __( 'Kapilbastu', 'ry-wc-city-select' ),
		'KA5' => __( 'Kaski', 'ry-wc-city-select' ),
		'KA6' => __( 'Kathmandu', 'ry-wc-city-select' ),
		'KA7' => __( 'Kavrepalanchok', 'ry-wc-city-select' ),
		'KH' => __( 'Khotang', 'ry-wc-city-select' ),
		'LA' => __( 'Lalitpur', 'ry-wc-city-select' ),
		'LA2' => __( 'Lamjung', 'ry-wc-city-select' ),
		'MA' => __( 'Mahottari', 'ry-wc-city-select' ),
		'MA2' => __( 'Makwanpur', 'ry-wc-city-select' ),
		'MA3' => __( 'Manag', 'ry-wc-city-select' ),
		'MO' => __( 'Morang', 'ry-wc-city-select' ),
		'MU' => __( 'Mugu', 'ry-wc-city-select' ),
		'MU2' => __( 'Mustang', 'ry-wc-city-select' ),
		'MY' => __( 'Myagdi', 'ry-wc-city-select' ),
		'NA' => __( 'Nawalparasi', 'ry-wc-city-select' ),
		'NU' => __( 'Nuwakot', 'ry-wc-city-select' ),
		'OK' => __( 'Okhaldhunga', 'ry-wc-city-select' ),
		'PA' => __( 'Palpa', 'ry-wc-city-select' ),
		'PA2' => __( 'Panchthar', 'ry-wc-city-select' ),
		'PA3' => __( 'Parbat', 'ry-wc-city-select' ),
		'PA4' => __( 'Parsa', 'ry-wc-city-select' ),
		'PY' => __( 'Pyuthan', 'ry-wc-city-select' ),
		'RA' => __( 'Ramechhap', 'ry-wc-city-select' ),
		'RA2' => __( 'Rasuwa', 'ry-wc-city-select' ),
		'RA3' => __( 'Rautahat', 'ry-wc-city-select' ),
		'RO' => __( 'Rolpa', 'ry-wc-city-select' ),
		'RU' => __( 'Rukum', 'ry-wc-city-select' ),
		'RU2' => __( 'Rupandehi', 'ry-wc-city-select' ),
		'SA' => __( 'Salyan', 'ry-wc-city-select' ),
		'SA2' => __( 'Sankhuwasabha', 'ry-wc-city-select' ),
		'SA3' => __( 'Saptari', 'ry-wc-city-select' ),
		'SA4' => __( 'Sarlahi', 'ry-wc-city-select' ),
		'SI' => __( 'Sindhuli', 'ry-wc-city-select' ),
		'SI2' => __( 'Sindhupalchowk', 'ry-wc-city-select' ),
		'SI3' => __( 'Siraha', 'ry-wc-city-select' ),
		'SO' => __( 'Solukhumbu', 'ry-wc-city-select' ),
		'SU' => __( 'Sunsari', 'ry-wc-city-select' ),
		'SU2' => __( 'Surkhet', 'ry-wc-city-select' ),
		'SY' => __( 'Syangja', 'ry-wc-city-select' ),
		'TA' => __( 'Tanahun', 'ry-wc-city-select' ),
		'TA2' => __( 'Taplejung', 'ry-wc-city-select' ),
		'TE' => __( 'Terathum', 'ry-wc-city-select' ),
		'UD' => __( 'Udayapur', 'ry-wc-city-select' ),
		'GAPR' => __( 'Gandaki Pradesh', 'ry-wc-city-select' ),
		'PR' => __( 'Province 1', 'ry-wc-city-select' ),
		'PR2' => __( 'Province 2', 'ry-wc-city-select' ),
		'PR3' => __( 'Province 3', 'ry-wc-city-select' ),
		'PR4' => __( 'Province 5', 'ry-wc-city-select' ),
		'PR5' => __( 'Province 6', 'ry-wc-city-select' ),
		'SUPR' => __( 'Sudurpashchim Pradesh', 'ry-wc-city-select' ),
	]
];