<?php
/**
 * Republic of Panama states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'PA' => [
		'BE' => __( 'Besiko', 'ry-wc-city-select' ),
		'CE' => __( 'Cemaco', 'ry-wc-city-select' ),
		'DIAR' => __( 'Distrito Arraijan', 'ry-wc-city-select' ),
		'DICHGR' => __( 'Distrito Chiriqui Grande', 'ry-wc-city-select' ),
		'DIPE' => __( 'Distrito Penonome', 'ry-wc-city-select' ),
		'DISAMI' => __( 'Distrito San Miguelito', 'ry-wc-city-select' ),
		'DIAG' => __( 'Distrito de Aguadulce', 'ry-wc-city-select' ),
		'DIAL' => __( 'Distrito de Alanje', 'ry-wc-city-select' ),
		'DIAN' => __( 'Distrito de Anton', 'ry-wc-city-select' ),
		'DIAT' => __( 'Distrito de Atalaya', 'ry-wc-city-select' ),
		'DIBA' => __( 'Distrito de Balboa', 'ry-wc-city-select' ),
		'DIBA2' => __( 'Distrito de Baru', 'ry-wc-city-select' ),
		'DIBODETO' => __( 'Distrito de Bocas del Toro', 'ry-wc-city-select' ),
		'DIBO' => __( 'Distrito de Boqueron', 'ry-wc-city-select' ),
		'DIBO2' => __( 'Distrito de Boquete', 'ry-wc-city-select' ),
		'DIBU' => __( 'Distrito de Bugaba', 'ry-wc-city-select' ),
		'DICA' => __( 'Distrito de Calobre', 'ry-wc-city-select' ),
		'DICA2' => __( 'Distrito de Canazas', 'ry-wc-city-select' ),
		'DICA3' => __( 'Distrito de Capira', 'ry-wc-city-select' ),
		'DICH' => __( 'Distrito de Chagres', 'ry-wc-city-select' ),
		'DICH2' => __( 'Distrito de Chame', 'ry-wc-city-select' ),
		'DICH3' => __( 'Distrito de Changuinola', 'ry-wc-city-select' ),
		'DICH4' => __( 'Distrito de Chepigana', 'ry-wc-city-select' ),
		'DICH5' => __( 'Distrito de Chepo', 'ry-wc-city-select' ),
		'DICH6' => __( 'Distrito de Chiman', 'ry-wc-city-select' ),
		'DICH7' => __( 'Distrito de Chitre', 'ry-wc-city-select' ),
		'DICO' => __( 'Distrito de Colon', 'ry-wc-city-select' ),
		'DIDA' => __( 'Distrito de David', 'ry-wc-city-select' ),
		'DIDO' => __( 'Distrito de Dolega', 'ry-wc-city-select' ),
		'DIDO2' => __( 'Distrito de Donoso', 'ry-wc-city-select' ),
		'DIGU' => __( 'Distrito de Gualaca', 'ry-wc-city-select' ),
		'DIGU2' => __( 'Distrito de Guarare', 'ry-wc-city-select' ),
		'DICH8' => __( 'Distrito de La Chorrera', 'ry-wc-city-select' ),
		'DIME' => __( 'Distrito de La Mesa', 'ry-wc-city-select' ),
		'DIPI' => __( 'Distrito de La Pintada', 'ry-wc-city-select' ),
		'DILAMI' => __( 'Distrito de Las Minas', 'ry-wc-city-select' ),
		'DILAPA' => __( 'Distrito de Las Palmas', 'ry-wc-city-select' ),
		'DILATA' => __( 'Distrito de Las Tablas', 'ry-wc-city-select' ),
		'DILOPO' => __( 'Distrito de Los Pozos', 'ry-wc-city-select' ),
		'DILOSA' => __( 'Distrito de Los Santos', 'ry-wc-city-select' ),
		'DIMA' => __( 'Distrito de Macaracas', 'ry-wc-city-select' ),
		'DIMO' => __( 'Distrito de Montijo', 'ry-wc-city-select' ),
		'DINA' => __( 'Distrito de Nata', 'ry-wc-city-select' ),
		'DIOC' => __( 'Distrito de Ocu', 'ry-wc-city-select' ),
		'DIOL' => __( 'Distrito de Ola', 'ry-wc-city-select' ),
		'DIPA' => __( 'Distrito de Panama', 'ry-wc-city-select' ),
		'DIPA2' => __( 'Distrito de Parita', 'ry-wc-city-select' ),
		'DIPE2' => __( 'Distrito de Pedasi', 'ry-wc-city-select' ),
		'DIPE3' => __( 'Distrito de Pese', 'ry-wc-city-select' ),
		'DIPI2' => __( 'Distrito de Pinogana', 'ry-wc-city-select' ),
		'DIPO' => __( 'Distrito de Pocri', 'ry-wc-city-select' ),
		'DIPO2' => __( 'Distrito de Portobelo', 'ry-wc-city-select' ),
		'DIRE' => __( 'Distrito de Remedios', 'ry-wc-city-select' ),
		'DIRE2' => __( 'Distrito de Renacimiento', 'ry-wc-city-select' ),
		'DIRIJE' => __( 'Distrito de Rio de Jesus', 'ry-wc-city-select' ),
		'DISACA' => __( 'Distrito de San Carlos', 'ry-wc-city-select' ),
		'DISAFE' => __( 'Distrito de San Felix', 'ry-wc-city-select' ),
		'DISAFR' => __( 'Distrito de San Francisco', 'ry-wc-city-select' ),
		'DISALO' => __( 'Distrito de San Lorenzo', 'ry-wc-city-select' ),
		'DISA' => __( 'Distrito de Santa Fe', 'ry-wc-city-select' ),
		'DISAIS' => __( 'Distrito de Santa Isabel', 'ry-wc-city-select' ),
		'DISAMA' => __( 'Distrito de Santa Maria', 'ry-wc-city-select' ),
		'DISA2' => __( 'Distrito de Santiago', 'ry-wc-city-select' ),
		'DISO' => __( 'Distrito de Sona', 'ry-wc-city-select' ),
		'DITA' => __( 'Distrito de Taboga', 'ry-wc-city-select' ),
		'DITO' => __( 'Distrito de Tole', 'ry-wc-city-select' ),
		'DITO2' => __( 'Distrito de Tonosi', 'ry-wc-city-select' ),
		'PO' => __( 'El Porvenir', 'ry-wc-city-select' ),
		'KA' => __( 'Kankintu', 'ry-wc-city-select' ),
		'KU' => __( 'Kusapin', 'ry-wc-city-select' ),
		'MADI' => __( 'Mariato District', 'ry-wc-city-select' ),
		'MI' => __( 'Mirono', 'ry-wc-city-select' ),
		'MU' => __( 'Muena', 'ry-wc-city-select' ),
		'NODU' => __( 'Nole Dueima', 'ry-wc-city-select' ),
		'NU' => __( 'Nurun', 'ry-wc-city-select' ),
		'SA' => __( 'Sambu', 'ry-wc-city-select' ),
		'EM' => __( 'Embera-Wounaan', 'ry-wc-city-select' ),
		'GUYA' => __( 'Guna Yala', 'ry-wc-city-select' ),
		'NG' => __( 'Ngoebe-Bugle', 'ry-wc-city-select' ),
		'PAOE' => __( 'Panama Oeste', 'ry-wc-city-select' ),
		'PRBODETO' => __( 'Provincia de Bocas del Toro', 'ry-wc-city-select' ),
		'PRCH' => __( 'Provincia de Chiriqui', 'ry-wc-city-select' ),
		'PRCO' => __( 'Provincia de Cocle', 'ry-wc-city-select' ),
		'PRCO2' => __( 'Provincia de Colon', 'ry-wc-city-select' ),
		'PRHE' => __( 'Provincia de Herrera', 'ry-wc-city-select' ),
		'PRLOSA' => __( 'Provincia de Los Santos', 'ry-wc-city-select' ),
		'PRPA' => __( 'Provincia de Panama', 'ry-wc-city-select' ),
		'PRVE' => __( 'Provincia de Veraguas', 'ry-wc-city-select' ),
		'PRDEDA' => __( 'Provincia del Darien', 'ry-wc-city-select' ),
	]
];