<?php
/**
 * Republic of the Philippines states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'PH' => [
		'AP' => __( 'Apayao', 'ry-wc-city-select' ),
		'BI' => __( 'Biliran', 'ry-wc-city-select' ),
		'BO' => __( 'Bohol', 'ry-wc-city-select' ),
		'CADI' => __( 'Capital District', 'ry-wc-city-select' ),
		'COVA' => __( 'Compostela Valley', 'ry-wc-city-select' ),
		'DAOC' => __( 'Davao Occidental', 'ry-wc-city-select' ),
		'DIIS' => __( 'Dinagat Islands', 'ry-wc-city-select' ),
		'EAMADI' => __( 'Eastern Manila District', 'ry-wc-city-select' ),
		'KA' => __( 'Kalinga', 'ry-wc-city-select' ),
		'MOPR' => __( 'Mountain Province', 'ry-wc-city-select' ),
		'NOMADI' => __( 'Northern Manila District', 'ry-wc-city-select' ),
		'PRZADESU' => __( 'Province of  Zamboanga del Sur', 'ry-wc-city-select' ),
		'PRAB' => __( 'Province of Abra', 'ry-wc-city-select' ),
		'PRAGDENO' => __( 'Province of Agusan del Norte', 'ry-wc-city-select' ),
		'PRAGDESU' => __( 'Province of Agusan del Sur', 'ry-wc-city-select' ),
		'PRAK' => __( 'Province of Aklan', 'ry-wc-city-select' ),
		'PRAL' => __( 'Province of Albay', 'ry-wc-city-select' ),
		'PRAN' => __( 'Province of Antique', 'ry-wc-city-select' ),
		'PRAU' => __( 'Province of Aurora', 'ry-wc-city-select' ),
		'PRBA' => __( 'Province of Basilan', 'ry-wc-city-select' ),
		'PRBA2' => __( 'Province of Bataan', 'ry-wc-city-select' ),
		'PRBA3' => __( 'Province of Batanes', 'ry-wc-city-select' ),
		'PRBA4' => __( 'Province of Batangas', 'ry-wc-city-select' ),
		'PRBE' => __( 'Province of Benguet', 'ry-wc-city-select' ),
		'PRBU' => __( 'Province of Bukidnon', 'ry-wc-city-select' ),
		'PRBU2' => __( 'Province of Bulacan', 'ry-wc-city-select' ),
		'PRCA' => __( 'Province of Cagayan', 'ry-wc-city-select' ),
		'PRCANO' => __( 'Province of Camarines Norte', 'ry-wc-city-select' ),
		'PRCASU' => __( 'Province of Camarines Sur', 'ry-wc-city-select' ),
		'PRCA2' => __( 'Province of Camiguin', 'ry-wc-city-select' ),
		'PRCA3' => __( 'Province of Capiz', 'ry-wc-city-select' ),
		'PRCA4' => __( 'Province of Catanduanes', 'ry-wc-city-select' ),
		'PRCA5' => __( 'Province of Cavite', 'ry-wc-city-select' ),
		'PRCE' => __( 'Province of Cebu', 'ry-wc-city-select' ),
		'PRCO' => __( 'Province of Cotabato', 'ry-wc-city-select' ),
		'PRDAOR' => __( 'Province of Davao Oriental', 'ry-wc-city-select' ),
		'PRDADENO' => __( 'Province of Davao del Norte', 'ry-wc-city-select' ),
		'PRDADESU' => __( 'Province of Davao del Sur', 'ry-wc-city-select' ),
		'PREASA' => __( 'Province of Eastern Samar', 'ry-wc-city-select' ),
		'PRGU' => __( 'Province of Guimaras', 'ry-wc-city-select' ),
		'PRIF' => __( 'Province of Ifugao', 'ry-wc-city-select' ),
		'PRILNO' => __( 'Province of Ilocos Norte', 'ry-wc-city-select' ),
		'PRILSU' => __( 'Province of Ilocos Sur', 'ry-wc-city-select' ),
		'PRIL' => __( 'Province of Iloilo', 'ry-wc-city-select' ),
		'PRIS' => __( 'Province of Isabela', 'ry-wc-city-select' ),
		'PRUN' => __( 'Province of La Union', 'ry-wc-city-select' ),
		'PRLA' => __( 'Province of Laguna', 'ry-wc-city-select' ),
		'PRLADENO' => __( 'Province of Lanao del Norte', 'ry-wc-city-select' ),
		'PRLADESU' => __( 'Province of Lanao del Sur', 'ry-wc-city-select' ),
		'PRLE' => __( 'Province of Leyte', 'ry-wc-city-select' ),
		'PRMA' => __( 'Province of Maguindanao', 'ry-wc-city-select' ),
		'PRMA2' => __( 'Province of Marinduque', 'ry-wc-city-select' ),
		'PRMA3' => __( 'Province of Masbate', 'ry-wc-city-select' ),
		'PRMIOC' => __( 'Province of Mindoro Occidental', 'ry-wc-city-select' ),
		'PRMIOR' => __( 'Province of Mindoro Oriental', 'ry-wc-city-select' ),
		'PRMIOC2' => __( 'Province of Misamis Occidental', 'ry-wc-city-select' ),
		'PRMIOR2' => __( 'Province of Misamis Oriental', 'ry-wc-city-select' ),
		'PRNEOC' => __( 'Province of Negros Occidental', 'ry-wc-city-select' ),
		'PRNEOR' => __( 'Province of Negros Oriental', 'ry-wc-city-select' ),
		'PRNOSA' => __( 'Province of Northern Samar', 'ry-wc-city-select' ),
		'PRNUEC' => __( 'Province of Nueva Ecija', 'ry-wc-city-select' ),
		'PRNUVI' => __( 'Province of Nueva Vizcaya', 'ry-wc-city-select' ),
		'PRPA' => __( 'Province of Palawan', 'ry-wc-city-select' ),
		'PRPA2' => __( 'Province of Pampanga', 'ry-wc-city-select' ),
		'PRPA3' => __( 'Province of Pangasinan', 'ry-wc-city-select' ),
		'PRQU' => __( 'Province of Quezon', 'ry-wc-city-select' ),
		'PRQU2' => __( 'Province of Quirino', 'ry-wc-city-select' ),
		'PRRI' => __( 'Province of Rizal', 'ry-wc-city-select' ),
		'PRRO' => __( 'Province of Romblon', 'ry-wc-city-select' ),
		'PRSA' => __( 'Province of Samar', 'ry-wc-city-select' ),
		'PRSA2' => __( 'Province of Sarangani', 'ry-wc-city-select' ),
		'PRSI' => __( 'Province of Siquijor', 'ry-wc-city-select' ),
		'PRSO' => __( 'Province of Sorsogon', 'ry-wc-city-select' ),
		'PRSOCO' => __( 'Province of South Cotabato', 'ry-wc-city-select' ),
		'PRSOLE' => __( 'Province of Southern Leyte', 'ry-wc-city-select' ),
		'PRSUKU' => __( 'Province of Sultan Kudarat', 'ry-wc-city-select' ),
		'PRSU' => __( 'Province of Sulu', 'ry-wc-city-select' ),
		'PRSUDENO' => __( 'Province of Surigao del Norte', 'ry-wc-city-select' ),
		'PRSUDESU' => __( 'Province of Surigao del Sur', 'ry-wc-city-select' ),
		'PRTA' => __( 'Province of Tarlac', 'ry-wc-city-select' ),
		'PRTA2' => __( 'Province of Tawi-Tawi', 'ry-wc-city-select' ),
		'PRZA' => __( 'Province of Zambales', 'ry-wc-city-select' ),
		'PRZASI' => __( 'Province of Zamboanga Sibugay', 'ry-wc-city-select' ),
		'PRZADENO' => __( 'Province of Zamboanga del Norte', 'ry-wc-city-select' ),
		'SOMADI' => __( 'Southern Manila District', 'ry-wc-city-select' ),
		'SO' => __( 'Soccsksargen', 'ry-wc-city-select' ),
		'AUREMUMI' => __( 'Autonomous Region in Muslim Mindanao', 'ry-wc-city-select' ),
		'BI2' => __( 'Bicol', 'ry-wc-city-select' ),
		'CAVA' => __( 'Cagayan Valley', 'ry-wc-city-select' ),
		'CA' => __( 'Calabarzon', 'ry-wc-city-select' ),
		'CA2' => __( 'Caraga', 'ry-wc-city-select' ),
		'CELU' => __( 'Central Luzon', 'ry-wc-city-select' ),
		'CEVI' => __( 'Central Visayas', 'ry-wc-city-select' ),
		'COADRE' => __( 'Cordillera Administrative Region', 'ry-wc-city-select' ),
		'DA' => __( 'Davao', 'ry-wc-city-select' ),
		'EAVI' => __( 'Eastern Visayas', 'ry-wc-city-select' ),
		'IL' => __( 'Ilocos', 'ry-wc-city-select' ),
		'MI' => __( 'Mimaropa', 'ry-wc-city-select' ),
		'NACARE' => __( 'National Capital Region', 'ry-wc-city-select' ),
		'NOMI' => __( 'Northern Mindanao', 'ry-wc-city-select' ),
		'WEVI' => __( 'Western Visayas', 'ry-wc-city-select' ),
		'ZAPE' => __( 'Zamboanga Peninsula', 'ry-wc-city-select' ),
	]
];