<?php
/**
 * Russian Federation states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'RU' => [
		'AGBUOK' => __( 'Aginskiy Buryatskiy Okrug', 'ry-wc-city-select' ),
		'BAUROK' => __( 'Barnaul Urban Okrug', 'ry-wc-city-select' ),
		'EAADOK' => __( 'Eastern Administrative Okrug', 'ry-wc-city-select' ),
		'GOAS' => __( 'Gorod Astrakhan', 'ry-wc-city-select' ),
		'GOKA' => __( 'Gorod Kazan', 'ry-wc-city-select' ),
		'GONACH' => __( 'Gorod Naberezhnyye Chelny', 'ry-wc-city-select' ),
		'GRUROK' => __( 'Grozny Urban Okrug', 'ry-wc-city-select' ),
		'NINOUROK' => __( 'Nizhny Novgorod Urban Okrug', 'ry-wc-city-select' ),
		'NORA' => __( 'Novosibirskiy Rayon', 'ry-wc-city-select' ),
		'SEADOK' => __( 'Severnyy Administrativnyy Okrug', 'ry-wc-city-select' ),
		'SEADOK2' => __( 'Severo-Vostochnyy Administrativnyy Okrug', 'ry-wc-city-select' ),
		'SEADOK3' => __( 'Severo-Zapadnyy Administrativnyy Okrug', 'ry-wc-city-select' ),
		'TSADOK' => __( 'Tsentralnyy Administrativnyy Okrug', 'ry-wc-city-select' ),
		'TURA' => __( 'Tukayevskiy Rayon', 'ry-wc-city-select' ),
		'YUADOK' => __( 'Yugo-Vostochnyy Administrativnyy Okrug', 'ry-wc-city-select' ),
		'YUADOK2' => __( 'Yugo-Zapadnyy Administrativnyy Okrug', 'ry-wc-city-select' ),
		'YUADOK3' => __( 'Yuzhnyy Administrativnyy Okrug', 'ry-wc-city-select' ),
		'ZAADOK' => __( 'Zapadnyy Administrativnyy Okrug', 'ry-wc-city-select' ),
		'ZEADOK' => __( 'Zelenogradsky Administrative Okrug', 'ry-wc-city-select' ),
		'ALKR' => __( 'Altayskiy Kray', 'ry-wc-city-select' ),
		'AMOB' => __( 'Amurskaya Oblast', 'ry-wc-city-select' ),
		'AROB' => __( 'Arkhangelskaya Oblast', 'ry-wc-city-select' ),
		'ASOB' => __( 'Astrakhanskaya Oblast', 'ry-wc-city-select' ),
		'BA' => __( 'Bashkortostan', 'ry-wc-city-select' ),
		'BEOB' => __( 'Belgorodskaya Oblast', 'ry-wc-city-select' ),
		'BROB' => __( 'Bryanskaya Oblast', 'ry-wc-city-select' ),
		'CHRE' => __( 'Chechenskaya Respublika', 'ry-wc-city-select' ),
		'CHOB' => __( 'Chelyabinskaya Oblast', 'ry-wc-city-select' ),
		'CHAVOK' => __( 'Chukotskiy Avtonomnyy Okrug', 'ry-wc-city-select' ),
		'CHRE2' => __( 'Chuvashskaya Respublika', 'ry-wc-city-select' ),
		'DA' => __( 'Dagestan', 'ry-wc-city-select' ),
		'IROB' => __( 'Irkutskaya Oblast', 'ry-wc-city-select' ),
		'IVOB' => __( 'Ivanovskaya Oblast', 'ry-wc-city-select' ),
		'KARE' => __( 'Kabardino-Balkarskaya Respublika', 'ry-wc-city-select' ),
		'KAOB' => __( 'Kaliningradskaya Oblast', 'ry-wc-city-select' ),
		'KA' => __( 'Kalmykiya', 'ry-wc-city-select' ),
		'KAOB2' => __( 'Kaluzhskaya Oblast', 'ry-wc-city-select' ),
		'KAKR' => __( 'Kamchatka Krai', 'ry-wc-city-select' ),
		'KA2' => __( 'Karachayevo-Cherkesiya', 'ry-wc-city-select' ),
		'KEOB' => __( 'Kemerovskaya Oblast', 'ry-wc-city-select' ),
		'KHKR' => __( 'Khabarovskiy Kray', 'ry-wc-city-select' ),
		'KIOB' => __( 'Kirovskaya Oblast', 'ry-wc-city-select' ),
		'KO' => __( 'Komi', 'ry-wc-city-select' ),
		'KOOB' => __( 'Kostromskaya Oblast', 'ry-wc-city-select' ),
		'KRKR' => __( 'Krasnodarskiy Kray', 'ry-wc-city-select' ),
		'KRKR2' => __( 'Krasnoyarskiy Kray', 'ry-wc-city-select' ),
		'KUOB' => __( 'Kurganskaya Oblast', 'ry-wc-city-select' ),
		'KUOB2' => __( 'Kurskaya Oblast', 'ry-wc-city-select' ),
		'LEOB' => __( 'Leningradskaya Oblast', 'ry-wc-city-select' ),
		'LIOB' => __( 'Lipetskaya Oblast', 'ry-wc-city-select' ),
		'MAOB' => __( 'Magadanskaya Oblast', 'ry-wc-city-select' ),
		'MOOB' => __( 'Moscow Oblast', 'ry-wc-city-select' ),
		'MO' => __( 'Moskva', 'ry-wc-city-select' ),
		'MUOB' => __( 'Murmanskaya Oblast', 'ry-wc-city-select' ),
		'NIOB' => __( 'Nizhegorodskaya Oblast', 'ry-wc-city-select' ),
		'NOOS' => __( 'North Ossetia', 'ry-wc-city-select' ),
		'NOOB' => __( 'Novgorodskaya Oblast', 'ry-wc-city-select' ),
		'NOOB2' => __( 'Novosibirskaya Oblast', 'ry-wc-city-select' ),
		'OMOB' => __( 'Omskaya Oblast', 'ry-wc-city-select' ),
		'OROB' => __( 'Orenburgskaya Oblast', 'ry-wc-city-select' ),
		'OROB2' => __( 'Orlovskaya Oblast', 'ry-wc-city-select' ),
		'PEOB' => __( 'Penzenskaya Oblast', 'ry-wc-city-select' ),
		'PEKR' => __( 'Perm Krai', 'ry-wc-city-select' ),
		'PRKR' => __( 'Primorskiy Kray', 'ry-wc-city-select' ),
		'PSOB' => __( 'Pskovskaya Oblast', 'ry-wc-city-select' ),
		'READ' => __( 'Respublika Adygeya', 'ry-wc-city-select' ),
		'REAL' => __( 'Respublika Altay', 'ry-wc-city-select' ),
		'REBU' => __( 'Respublika Buryatiya', 'ry-wc-city-select' ),
		'REIN' => __( 'Respublika Ingushetiya', 'ry-wc-city-select' ),
		'REKA' => __( 'Respublika Kareliya', 'ry-wc-city-select' ),
		'REKH' => __( 'Respublika Khakasiya', 'ry-wc-city-select' ),
		'REMA' => __( 'Respublika Mariy-El', 'ry-wc-city-select' ),
		'REMO' => __( 'Respublika Mordoviya', 'ry-wc-city-select' ),
		'RESA(Y' => __( 'Respublika Sakha (Yakutiya)', 'ry-wc-city-select' ),
		'RETY' => __( 'Respublika Tyva', 'ry-wc-city-select' ),
		'ROOB' => __( 'Rostovskaya Oblast', 'ry-wc-city-select' ),
		'RYOB' => __( 'Ryazanskaya Oblast', 'ry-wc-city-select' ),
		'SAOB' => __( 'Sakhalinskaya Oblast', 'ry-wc-city-select' ),
		'SAOB2' => __( 'Samarskaya Oblast', 'ry-wc-city-select' ),
		'SA' => __( 'Sankt-Peterburg', 'ry-wc-city-select' ),
		'SAOB3' => __( 'Saratovskaya Oblast', 'ry-wc-city-select' ),
		'SMOB' => __( 'Smolenskaya Oblast', 'ry-wc-city-select' ),
		'STKR' => __( 'Stavropolskiy Kray', 'ry-wc-city-select' ),
		'SVOB' => __( 'Sverdlovskaya Oblast', 'ry-wc-city-select' ),
		'TAOB' => __( 'Tambovskaya Oblast', 'ry-wc-city-select' ),
		'TA' => __( 'Tatarstan', 'ry-wc-city-select' ),
		'TOOB' => __( 'Tomskaya Oblast', 'ry-wc-city-select' ),
		'TUOB' => __( 'Tulskaya Oblast', 'ry-wc-city-select' ),
		'TVOB' => __( 'Tverskaya Oblast', 'ry-wc-city-select' ),
		'TYOB' => __( 'Tyumenskaya Oblast', 'ry-wc-city-select' ),
		'UDRE' => __( 'Udmurtskaya Respublika', 'ry-wc-city-select' ),
		'ULOB' => __( 'Ulyanovsk Oblast', 'ry-wc-city-select' ),
		'VLOB' => __( 'Vladimirskaya Oblast', 'ry-wc-city-select' ),
		'VOOB' => __( 'Volgogradskaya Oblast', 'ry-wc-city-select' ),
		'VOOB2' => __( 'Vologodskaya Oblast', 'ry-wc-city-select' ),
		'VOOB3' => __( 'Voronezhskaya Oblast', 'ry-wc-city-select' ),
		'YAAVOK' => __( 'Yamalo-Nenetskiy Avtonomnyy Okrug', 'ry-wc-city-select' ),
		'YAOB' => __( 'Yaroslavskaya Oblast', 'ry-wc-city-select' ),
		'YEAVOB' => __( 'Yevreyskaya Avtonomnaya Oblast', 'ry-wc-city-select' ),
		'ZAKR' => __( 'Zabaykalskiy Kray', 'ry-wc-city-select' ),
		'KHAVOK' => __( 'Khanty-Mansiyskiy Avtonomnyy Okrug-Yugra', 'ry-wc-city-select' ),
		'NEAVOK' => __( 'Nenetskiy Avtonomnyy Okrug', 'ry-wc-city-select' ),
	]
];