<?php
/**
 * Slovak Republic states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'SK' => [
		'KO' => __( 'Kosice I', 'ry-wc-city-select' ),
		'KO2' => __( 'Kosice II', 'ry-wc-city-select' ),
		'KOII' => __( 'Kosice III', 'ry-wc-city-select' ),
		'KO3' => __( 'Kosice IV', 'ry-wc-city-select' ),
		'OKBANABE' => __( 'Okres Banovce nad Bebravou', 'ry-wc-city-select' ),
		'OKBABY' => __( 'Okres Banska Bystrica', 'ry-wc-city-select' ),
		'OKBAST' => __( 'Okres Banska Stiavnica', 'ry-wc-city-select' ),
		'OKBA' => __( 'Okres Bardejov', 'ry-wc-city-select' ),
		'OKBR' => __( 'Okres Bratislava I', 'ry-wc-city-select' ),
		'OKBR2' => __( 'Okres Bratislava II', 'ry-wc-city-select' ),
		'OKBRII' => __( 'Okres Bratislava III', 'ry-wc-city-select' ),
		'OKBR3' => __( 'Okres Bratislava IV', 'ry-wc-city-select' ),
		'OKBR4' => __( 'Okres Bratislava V', 'ry-wc-city-select' ),
		'OKBR5' => __( 'Okres Brezno', 'ry-wc-city-select' ),
		'OKBY' => __( 'Okres Bytca', 'ry-wc-city-select' ),
		'OKCA' => __( 'Okres Cadca', 'ry-wc-city-select' ),
		'OKDE' => __( 'Okres Detva', 'ry-wc-city-select' ),
		'OKDOKU' => __( 'Okres Dolny Kubin', 'ry-wc-city-select' ),
		'OKDUST' => __( 'Okres Dunajska Streda', 'ry-wc-city-select' ),
		'OKGA' => __( 'Okres Galanta', 'ry-wc-city-select' ),
		'OKGE' => __( 'Okres Gelnica', 'ry-wc-city-select' ),
		'OKHL' => __( 'Okres Hlohovec', 'ry-wc-city-select' ),
		'OKHU' => __( 'Okres Humenne', 'ry-wc-city-select' ),
		'OKIL' => __( 'Okres Ilava', 'ry-wc-city-select' ),
		'OKKE' => __( 'Okres Kezmarok', 'ry-wc-city-select' ),
		'OKKO' => __( 'Okres Komarno', 'ry-wc-city-select' ),
		'OKKO2' => __( 'Okres Kosice-okolie', 'ry-wc-city-select' ),
		'OKKR' => __( 'Okres Krupina', 'ry-wc-city-select' ),
		'OKKYNOME' => __( 'Okres Kysucke Nove Mesto', 'ry-wc-city-select' ),
		'OKLE' => __( 'Okres Levice', 'ry-wc-city-select' ),
		'OKLE2' => __( 'Okres Levoca', 'ry-wc-city-select' ),
		'OKLIMI' => __( 'Okres Liptovsky Mikulas', 'ry-wc-city-select' ),
		'OKLU' => __( 'Okres Lucenec', 'ry-wc-city-select' ),
		'OKMA' => __( 'Okres Malacky', 'ry-wc-city-select' ),
		'OKMA2' => __( 'Okres Martin', 'ry-wc-city-select' ),
		'OKME' => __( 'Okres Medzilaborce', 'ry-wc-city-select' ),
		'OKMI' => __( 'Okres Michalovce', 'ry-wc-city-select' ),
		'OKMY' => __( 'Okres Myjava', 'ry-wc-city-select' ),
		'OKNA' => __( 'Okres Namestovo', 'ry-wc-city-select' ),
		'OKNI' => __( 'Okres Nitra', 'ry-wc-city-select' ),
		'OKNOMENAVA' => __( 'Okres Nove Mesto nad Vahom', 'ry-wc-city-select' ),
		'OKNOZA' => __( 'Okres Nove Zamky', 'ry-wc-city-select' ),
		'OKPA' => __( 'Okres Partizanske', 'ry-wc-city-select' ),
		'OKPE' => __( 'Okres Pezinok', 'ry-wc-city-select' ),
		'OKPI' => __( 'Okres Piestany', 'ry-wc-city-select' ),
		'OKPO' => __( 'Okres Poltar', 'ry-wc-city-select' ),
		'OKPO2' => __( 'Okres Poprad', 'ry-wc-city-select' ),
		'OKPOBY' => __( 'Okres Povazska Bystrica', 'ry-wc-city-select' ),
		'OKPR' => __( 'Okres Presov', 'ry-wc-city-select' ),
		'OKPR2' => __( 'Okres Prievidza', 'ry-wc-city-select' ),
		'OKPU' => __( 'Okres Puchov', 'ry-wc-city-select' ),
		'OKRE' => __( 'Okres Revuca', 'ry-wc-city-select' ),
		'OKRISO' => __( 'Okres Rimavska Sobota', 'ry-wc-city-select' ),
		'OKRO' => __( 'Okres Roznava', 'ry-wc-city-select' ),
		'OKRU' => __( 'Okres Ruzomberok', 'ry-wc-city-select' ),
		'OKSA' => __( 'Okres Sabinov', 'ry-wc-city-select' ),
		'OKSA2' => __( 'Okres Sala', 'ry-wc-city-select' ),
		'OKSE' => __( 'Okres Senec', 'ry-wc-city-select' ),
		'OKSE2' => __( 'Okres Senica', 'ry-wc-city-select' ),
		'OKSK' => __( 'Okres Skalica', 'ry-wc-city-select' ),
		'OKSN' => __( 'Okres Snina', 'ry-wc-city-select' ),
		'OKSO' => __( 'Okres Sobrance', 'ry-wc-city-select' ),
		'OKSPNOVE' => __( 'Okres Spisska Nova Ves', 'ry-wc-city-select' ),
		'OKSTLU' => __( 'Okres Stara Lubovna', 'ry-wc-city-select' ),
		'OKST' => __( 'Okres Stropkov', 'ry-wc-city-select' ),
		'OKSV' => __( 'Okres Svidnik', 'ry-wc-city-select' ),
		'OKTO' => __( 'Okres Topolcany', 'ry-wc-city-select' ),
		'OKTR' => __( 'Okres Trebisov', 'ry-wc-city-select' ),
		'OKTR2' => __( 'Okres Trencin', 'ry-wc-city-select' ),
		'OKTR3' => __( 'Okres Trnava', 'ry-wc-city-select' ),
		'OKTUTE' => __( 'Okres Turcianske Teplice', 'ry-wc-city-select' ),
		'OKTV' => __( 'Okres Tvrdosin', 'ry-wc-city-select' ),
		'OKVEKR' => __( 'Okres Velky Krtis', 'ry-wc-city-select' ),
		'OKVRNATO' => __( 'Okres Vranov nad Toplou', 'ry-wc-city-select' ),
		'OKZA' => __( 'Okres Zarnovica', 'ry-wc-city-select' ),
		'OKZINAHR' => __( 'Okres Ziar nad Hronom', 'ry-wc-city-select' ),
		'OKZI' => __( 'Okres Zilina', 'ry-wc-city-select' ),
		'OKZLMO' => __( 'Okres Zlate Moravce', 'ry-wc-city-select' ),
		'OKZV' => __( 'Okres Zvolen', 'ry-wc-city-select' ),
		'BABY' => __( 'Banska Bystrica', 'ry-wc-city-select' ),
		'BR' => __( 'Bratislava', 'ry-wc-city-select' ),
		'KO4' => __( 'Kosice', 'ry-wc-city-select' ),
		'NI' => __( 'Nitra', 'ry-wc-city-select' ),
		'PR' => __( 'Presov', 'ry-wc-city-select' ),
		'TR' => __( 'Trencin', 'ry-wc-city-select' ),
		'TR2' => __( 'Trnava', 'ry-wc-city-select' ),
		'ZI' => __( 'Zilina', 'ry-wc-city-select' ),
	]
];