<?php
/**
 * Kingdom of Thailand states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'TH' => [
		'AMBAKR' => __( 'Amphoe Bang Kruai', 'ry-wc-city-select' ),
		'AMBAYA' => __( 'Amphoe Bang Yai', 'ry-wc-city-select' ),
		'AMMASA' => __( 'Amphoe Mae Sariang', 'ry-wc-city-select' ),
		'AMMUNO' => __( 'Amphoe Mueang Nonthaburi', 'ry-wc-city-select' ),
		'AMPA' => __( 'Amphoe Pai', 'ry-wc-city-select' ),
		'AMPAKR' => __( 'Amphoe Pak Kret', 'ry-wc-city-select' ),
		'AMTH' => __( 'Amphoe Thanyaburi', 'ry-wc-city-select' ),
		'BAPH' => __( 'Bang Phlat', 'ry-wc-city-select' ),
		'DOMU' => __( 'Don Mueang', 'ry-wc-city-select' ),
		'KHSA' => __( 'Khlong Sam Wa', 'ry-wc-city-select' ),
		'LA' => __( 'Lak Si', 'ry-wc-city-select' ),
		'BA' => __( 'Bangkok', 'ry-wc-city-select' ),
		'CHAMCH' => __( 'Changwat Amnat Charoen', 'ry-wc-city-select' ),
		'CHANTH' => __( 'Changwat Ang Thong', 'ry-wc-city-select' ),
		'CHBUKA' => __( 'Changwat Bueng Kan', 'ry-wc-city-select' ),
		'CHBURA' => __( 'Changwat Buri Ram', 'ry-wc-city-select' ),
		'CHCH' => __( 'Changwat Chachoengsao', 'ry-wc-city-select' ),
		'CHCHNA' => __( 'Changwat Chai Nat', 'ry-wc-city-select' ),
		'CHCH2' => __( 'Changwat Chaiyaphum', 'ry-wc-city-select' ),
		'CHCH3' => __( 'Changwat Chanthaburi', 'ry-wc-city-select' ),
		'CHCHRA' => __( 'Changwat Chiang Rai', 'ry-wc-city-select' ),
		'CHCHBU' => __( 'Changwat Chon Buri', 'ry-wc-city-select' ),
		'CHCH4' => __( 'Changwat Chumphon', 'ry-wc-city-select' ),
		'CHKA' => __( 'Changwat Kalasin', 'ry-wc-city-select' ),
		'CHKAPH' => __( 'Changwat Kamphaeng Phet', 'ry-wc-city-select' ),
		'CHKA2' => __( 'Changwat Kanchanaburi', 'ry-wc-city-select' ),
		'CHKHKA' => __( 'Changwat Khon Kaen', 'ry-wc-city-select' ),
		'CHKR' => __( 'Changwat Krabi', 'ry-wc-city-select' ),
		'CHLA' => __( 'Changwat Lampang', 'ry-wc-city-select' ),
		'CHLA2' => __( 'Changwat Lamphun', 'ry-wc-city-select' ),
		'CHLO' => __( 'Changwat Loei', 'ry-wc-city-select' ),
		'CHLOBU' => __( 'Changwat Lop Buri', 'ry-wc-city-select' ),
		'CHMAHOSO' => __( 'Changwat Mae Hong Son', 'ry-wc-city-select' ),
		'CHMASA' => __( 'Changwat Maha Sarakham', 'ry-wc-city-select' ),
		'CHMU' => __( 'Changwat Mukdahan', 'ry-wc-city-select' ),
		'CHNANA' => __( 'Changwat Nakhon Nayok', 'ry-wc-city-select' ),
		'CHNAPA' => __( 'Changwat Nakhon Pathom', 'ry-wc-city-select' ),
		'CHNAPH' => __( 'Changwat Nakhon Phanom', 'ry-wc-city-select' ),
		'CHNARA' => __( 'Changwat Nakhon Ratchasima', 'ry-wc-city-select' ),
		'CHNASA' => __( 'Changwat Nakhon Sawan', 'ry-wc-city-select' ),
		'CHNATH' => __( 'Changwat Nakhon Si Thammarat', 'ry-wc-city-select' ),
		'CHNA' => __( 'Changwat Nan', 'ry-wc-city-select' ),
		'CHNA2' => __( 'Changwat Narathiwat', 'ry-wc-city-select' ),
		'CHNOBULA' => __( 'Changwat Nong Bua Lamphu', 'ry-wc-city-select' ),
		'CHNOKH' => __( 'Changwat Nong Khai', 'ry-wc-city-select' ),
		'CHNO' => __( 'Changwat Nonthaburi', 'ry-wc-city-select' ),
		'CHPATH' => __( 'Changwat Pathum Thani', 'ry-wc-city-select' ),
		'CHPA' => __( 'Changwat Pattani', 'ry-wc-city-select' ),
		'CHPH' => __( 'Changwat Phangnga', 'ry-wc-city-select' ),
		'CHPH2' => __( 'Changwat Phatthalung', 'ry-wc-city-select' ),
		'CHPH3' => __( 'Changwat Phayao', 'ry-wc-city-select' ),
		'CHPH4' => __( 'Changwat Phetchabun', 'ry-wc-city-select' ),
		'CHPH5' => __( 'Changwat Phetchaburi', 'ry-wc-city-select' ),
		'CHPH6' => __( 'Changwat Phichit', 'ry-wc-city-select' ),
		'CHPH7' => __( 'Changwat Phitsanulok', 'ry-wc-city-select' ),
		'CHPH8' => __( 'Changwat Phrae', 'ry-wc-city-select' ),
		'CHPRBU' => __( 'Changwat Prachin Buri', 'ry-wc-city-select' ),
		'CHPRKHKH' => __( 'Changwat Prachuap Khiri Khan', 'ry-wc-city-select' ),
		'CHRA' => __( 'Changwat Ranong', 'ry-wc-city-select' ),
		'CHRA2' => __( 'Changwat Ratchaburi', 'ry-wc-city-select' ),
		'CHRA3' => __( 'Changwat Rayong', 'ry-wc-city-select' ),
		'CHRO' => __( 'Changwat Roi Et', 'ry-wc-city-select' ),
		'CHKA3' => __( 'Changwat Sa Kaeo', 'ry-wc-city-select' ),
		'CHSANA' => __( 'Changwat Sakon Nakhon', 'ry-wc-city-select' ),
		'CHSAPR' => __( 'Changwat Samut Prakan', 'ry-wc-city-select' ),
		'CHSASA' => __( 'Changwat Samut Sakhon', 'ry-wc-city-select' ),
		'CHSASO' => __( 'Changwat Samut Songkhram', 'ry-wc-city-select' ),
		'CHSA' => __( 'Changwat Saraburi', 'ry-wc-city-select' ),
		'CHSA2' => __( 'Changwat Satun', 'ry-wc-city-select' ),
		'CHKE' => __( 'Changwat Si Sa Ket', 'ry-wc-city-select' ),
		'CHSIBU' => __( 'Changwat Sing Buri', 'ry-wc-city-select' ),
		'CHSO' => __( 'Changwat Songkhla', 'ry-wc-city-select' ),
		'CHSU' => __( 'Changwat Sukhothai', 'ry-wc-city-select' ),
		'CHSUBU' => __( 'Changwat Suphan Buri', 'ry-wc-city-select' ),
		'CHSUTH' => __( 'Changwat Surat Thani', 'ry-wc-city-select' ),
		'CHSU2' => __( 'Changwat Surin', 'ry-wc-city-select' ),
		'CHTA' => __( 'Changwat Tak', 'ry-wc-city-select' ),
		'CHTR' => __( 'Changwat Trang', 'ry-wc-city-select' ),
		'CHTR2' => __( 'Changwat Trat', 'ry-wc-city-select' ),
		'CHUBRA' => __( 'Changwat Ubon Ratchathani', 'ry-wc-city-select' ),
		'CHUDTH' => __( 'Changwat Udon Thani', 'ry-wc-city-select' ),
		'CHUTTH' => __( 'Changwat Uthai Thani', 'ry-wc-city-select' ),
		'CHUT' => __( 'Changwat Uttaradit', 'ry-wc-city-select' ),
		'CHYA' => __( 'Changwat Yala', 'ry-wc-city-select' ),
		'CHYA2' => __( 'Changwat Yasothon', 'ry-wc-city-select' ),
		'CHMAPR' => __( 'Chiang Mai Province', 'ry-wc-city-select' ),
		'PHNAAY' => __( 'Phra Nakhon Si Ayutthaya', 'ry-wc-city-select' ),
		'PHPR' => __( 'Phuket Province', 'ry-wc-city-select' ),
	]
];