<?php
/**
 * Democratic Republic of Timor-Leste states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'TL' => [
		'AIVI' => __( 'Aileu Villa', 'ry-wc-city-select' ),
		'AI' => __( 'Ainaro', 'ry-wc-city-select' ),
		'AL' => __( 'Alas', 'ry-wc-city-select' ),
		'AT' => __( 'Atabae', 'ry-wc-city-select' ),
		'ATIS' => __( 'Atauro Island', 'ry-wc-city-select' ),
		'AT2' => __( 'Atsabe', 'ry-wc-city-select' ),
		'BA' => __( 'Baguia', 'ry-wc-city-select' ),
		'BA2' => __( 'Balibo', 'ry-wc-city-select' ),
		'BA3' => __( 'Barique', 'ry-wc-city-select' ),
		'BA4' => __( 'Baucau', 'ry-wc-city-select' ),
		'BA5' => __( 'Bazartete', 'ry-wc-city-select' ),
		'BO' => __( 'Bobonaro', 'ry-wc-city-select' ),
		'CA' => __( 'Cailaco', 'ry-wc-city-select' ),
		'CRRE' => __( 'Cristo Rei', 'ry-wc-city-select' ),
		'DOAL' => __( 'Dom Aleixo', 'ry-wc-city-select' ),
		'ERVI' => __( 'Ermera Villa', 'ry-wc-city-select' ),
		'FA' => __( 'Fatuberliu', 'ry-wc-city-select' ),
		'FA2' => __( 'Fatululik', 'ry-wc-city-select' ),
		'FA3' => __( 'Fatumean', 'ry-wc-city-select' ),
		'FO' => __( 'Fohorem', 'ry-wc-city-select' ),
		'HA' => __( 'Hato-Udo', 'ry-wc-city-select' ),
		'HA2' => __( 'Hatobuilico', 'ry-wc-city-select' ),
		'HA3' => __( 'Hatulia', 'ry-wc-city-select' ),
		'IL' => __( 'Iliomar', 'ry-wc-city-select' ),
		'LA' => __( 'Laclo', 'ry-wc-city-select' ),
		'LA2' => __( 'Laclubar', 'ry-wc-city-select' ),
		'LA3' => __( 'Lacluta', 'ry-wc-city-select' ),
		'LA4' => __( 'Laga', 'ry-wc-city-select' ),
		'LA5' => __( 'Laleia', 'ry-wc-city-select' ),
		'LA6' => __( 'Laulara', 'ry-wc-city-select' ),
		'LA7' => __( 'Lautem', 'ry-wc-city-select' ),
		'LE' => __( 'Lequidoe', 'ry-wc-city-select' ),
		'LE2' => __( 'Letefoho', 'ry-wc-city-select' ),
		'LI' => __( 'Liquica', 'ry-wc-city-select' ),
		'LO' => __( 'Lolotoe', 'ry-wc-city-select' ),
		'LO2' => __( 'Lospalos', 'ry-wc-city-select' ),
		'LU' => __( 'Luro', 'ry-wc-city-select' ),
		'MA' => __( 'Maliana', 'ry-wc-city-select' ),
		'MA2' => __( 'Manatuto', 'ry-wc-city-select' ),
		'MA3' => __( 'Maubara', 'ry-wc-city-select' ),
		'MA4' => __( 'Maubisse', 'ry-wc-city-select' ),
		'MA5' => __( 'Maucatar', 'ry-wc-city-select' ),
		'ME' => __( 'Metinaro', 'ry-wc-city-select' ),
		'NAFE' => __( 'Nain Feto', 'ry-wc-city-select' ),
		'NI' => __( 'Nitibe', 'ry-wc-city-select' ),
		'OE' => __( 'Oesilo', 'ry-wc-city-select' ),
		'OS' => __( 'Ossu', 'ry-wc-city-select' ),
		'PAMA' => __( 'Pante Makasar', 'ry-wc-city-select' ),
		'PA' => __( 'Passabe', 'ry-wc-city-select' ),
		'QU' => __( 'Quelicai', 'ry-wc-city-select' ),
		'RA' => __( 'Railaco', 'ry-wc-city-select' ),
		'RE' => __( 'Remexio', 'ry-wc-city-select' ),
		'SA' => __( 'Same', 'ry-wc-city-select' ),
		'SO' => __( 'Soibada', 'ry-wc-city-select' ),
		'SU' => __( 'Suai', 'ry-wc-city-select' ),
		'TI' => __( 'Tilomar', 'ry-wc-city-select' ),
		'TU' => __( 'Turiscai', 'ry-wc-city-select' ),
		'TU2' => __( 'Tutuala', 'ry-wc-city-select' ),
		'UA' => __( 'Uatocarabau', 'ry-wc-city-select' ),
		'UA2' => __( 'Uatolari', 'ry-wc-city-select' ),
		'VE' => __( 'Vemasse', 'ry-wc-city-select' ),
		'VE2' => __( 'Venilale', 'ry-wc-city-select' ),
		'VECR' => __( 'Vera Cruz', 'ry-wc-city-select' ),
		'VI' => __( 'Viqueque', 'ry-wc-city-select' ),
		'ZU' => __( 'Zumalai', 'ry-wc-city-select' ),
		'AI2' => __( 'Aileu', 'ry-wc-city-select' ),
		'DI' => __( 'Dili', 'ry-wc-city-select' ),
		'ER' => __( 'Ermera', 'ry-wc-city-select' ),
		'KO' => __( 'Kovalima', 'ry-wc-city-select' ),
		'LA8' => __( 'Lautein', 'ry-wc-city-select' ),
		'MA6' => __( 'Manufahi', 'ry-wc-city-select' ),
		'OE2' => __( 'Oecusse', 'ry-wc-city-select' ),
	]
];