<?php
/**
 * Republic of Turkey states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'TR' => [
		'MIIL' => __( 'Milas Ilcesi', 'ry-wc-city-select' ),
		'SUIL' => __( 'Sultanhisar Ilcesi', 'ry-wc-city-select' ),
		'AD' => __( 'Adana', 'ry-wc-city-select' ),
		'AD2' => __( 'Adiyaman', 'ry-wc-city-select' ),
		'AF' => __( 'Afyonkarahisar', 'ry-wc-city-select' ),
		'AG' => __( 'Agri', 'ry-wc-city-select' ),
		'AK' => __( 'Aksaray', 'ry-wc-city-select' ),
		'AM' => __( 'Amasya', 'ry-wc-city-select' ),
		'AN' => __( 'Ankara', 'ry-wc-city-select' ),
		'AN2' => __( 'Antalya', 'ry-wc-city-select' ),
		'AR' => __( 'Ardahan', 'ry-wc-city-select' ),
		'AR2' => __( 'Artvin', 'ry-wc-city-select' ),
		'AY' => __( 'Aydin', 'ry-wc-city-select' ),
		'BA' => __( 'Balikesir', 'ry-wc-city-select' ),
		'BA2' => __( 'Bartin', 'ry-wc-city-select' ),
		'BA3' => __( 'Batman', 'ry-wc-city-select' ),
		'BA4' => __( 'Bayburt', 'ry-wc-city-select' ),
		'BI' => __( 'Bilecik', 'ry-wc-city-select' ),
		'BI2' => __( 'Bingoel', 'ry-wc-city-select' ),
		'BI3' => __( 'Bitlis', 'ry-wc-city-select' ),
		'BO' => __( 'Bolu', 'ry-wc-city-select' ),
		'BU' => __( 'Burdur', 'ry-wc-city-select' ),
		'BU2' => __( 'Bursa', 'ry-wc-city-select' ),
		'CA' => __( 'Canakkale', 'ry-wc-city-select' ),
		'CA2' => __( 'Cankiri', 'ry-wc-city-select' ),
		'CO' => __( 'Corum', 'ry-wc-city-select' ),
		'DE' => __( 'Denizli', 'ry-wc-city-select' ),
		'DI' => __( 'Diyarbakir', 'ry-wc-city-select' ),
		'DU' => __( 'Duezce', 'ry-wc-city-select' ),
		'ED' => __( 'Edirne', 'ry-wc-city-select' ),
		'EL' => __( 'Elazig', 'ry-wc-city-select' ),
		'ER' => __( 'Erzincan', 'ry-wc-city-select' ),
		'ER2' => __( 'Erzurum', 'ry-wc-city-select' ),
		'ES' => __( 'Eskisehir', 'ry-wc-city-select' ),
		'GA' => __( 'Gaziantep', 'ry-wc-city-select' ),
		'GI' => __( 'Giresun', 'ry-wc-city-select' ),
		'GU' => __( 'Guemueshane', 'ry-wc-city-select' ),
		'HA' => __( 'Hakkari', 'ry-wc-city-select' ),
		'HA2' => __( 'Hatay', 'ry-wc-city-select' ),
		'IG' => __( 'Igdir', 'ry-wc-city-select' ),
		'IS' => __( 'Isparta', 'ry-wc-city-select' ),
		'IS2' => __( 'Istanbul', 'ry-wc-city-select' ),
		'IZ' => __( 'Izmir', 'ry-wc-city-select' ),
		'KA' => __( 'Kahramanmaras', 'ry-wc-city-select' ),
		'KA2' => __( 'Karabuek', 'ry-wc-city-select' ),
		'KA3' => __( 'Karaman', 'ry-wc-city-select' ),
		'KA4' => __( 'Kars', 'ry-wc-city-select' ),
		'KA5' => __( 'Kastamonu', 'ry-wc-city-select' ),
		'KA6' => __( 'Kayseri', 'ry-wc-city-select' ),
		'KI' => __( 'Kilis', 'ry-wc-city-select' ),
		'KI2' => __( 'Kirikkale', 'ry-wc-city-select' ),
		'KI3' => __( 'Kirklareli', 'ry-wc-city-select' ),
		'KI4' => __( 'Kirsehir', 'ry-wc-city-select' ),
		'KO' => __( 'Kocaeli', 'ry-wc-city-select' ),
		'KO2' => __( 'Konya', 'ry-wc-city-select' ),
		'KU' => __( 'Kuetahya', 'ry-wc-city-select' ),
		'MA' => __( 'Malatya', 'ry-wc-city-select' ),
		'MA2' => __( 'Manisa', 'ry-wc-city-select' ),
		'MA3' => __( 'Mardin', 'ry-wc-city-select' ),
		'ME' => __( 'Mersin', 'ry-wc-city-select' ),
		'MU' => __( 'Mugla', 'ry-wc-city-select' ),
		'MU2' => __( 'Mus', 'ry-wc-city-select' ),
		'NE' => __( 'Nevsehir', 'ry-wc-city-select' ),
		'NI' => __( 'Nigde', 'ry-wc-city-select' ),
		'OR' => __( 'Ordu', 'ry-wc-city-select' ),
		'OS' => __( 'Osmaniye', 'ry-wc-city-select' ),
		'RI' => __( 'Rize', 'ry-wc-city-select' ),
		'SA' => __( 'Sakarya', 'ry-wc-city-select' ),
		'SA2' => __( 'Samsun', 'ry-wc-city-select' ),
		'SA3' => __( 'Sanliurfa', 'ry-wc-city-select' ),
		'SI' => __( 'Siirt', 'ry-wc-city-select' ),
		'SI2' => __( 'Sinop', 'ry-wc-city-select' ),
		'SI3' => __( 'Sirnak', 'ry-wc-city-select' ),
		'SI4' => __( 'Sivas', 'ry-wc-city-select' ),
		'TE' => __( 'Tekirdag', 'ry-wc-city-select' ),
		'TO' => __( 'Tokat', 'ry-wc-city-select' ),
		'TR' => __( 'Trabzon', 'ry-wc-city-select' ),
		'TU' => __( 'Tunceli', 'ry-wc-city-select' ),
		'US' => __( 'Usak', 'ry-wc-city-select' ),
		'VA' => __( 'Van', 'ry-wc-city-select' ),
		'YA' => __( 'Yalova', 'ry-wc-city-select' ),
		'YO' => __( 'Yozgat', 'ry-wc-city-select' ),
		'ZO' => __( 'Zonguldak', 'ry-wc-city-select' ),
	]
];