<?php
/**
 * Ukraine states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'UA' => [
		'BARA' => __( 'Bakhchysarai Raion', 'ry-wc-city-select' ),
		'BADI' => __( 'Balaklava District', 'ry-wc-city-select' ),
		'BARA2' => __( 'Baranivka Raion', 'ry-wc-city-select' ),
		'BERA' => __( 'Belogorskiy rayon', 'ry-wc-city-select' ),
		'BIRA' => __( 'Bilhorod-Dnistrovskyy Raion', 'ry-wc-city-select' ),
		'CHRA' => __( 'Chernihivka Raion', 'ry-wc-city-select' ),
		'CHMU' => __( 'Chernivtsi Municipality', 'ry-wc-city-select' ),
		'CHRA2' => __( 'Chernomorskiy rayon', 'ry-wc-city-select' ),
		'CHRA3' => __( 'Chudniv Raion', 'ry-wc-city-select' ),
		'DNMIRA' => __( 'Dniprovska Miska Rada', 'ry-wc-city-select' ),
		'DOMI' => __( 'Donetska Miskrada', 'ry-wc-city-select' ),
		'DZRA' => __( 'Dzhankoyskiy rayon', 'ry-wc-city-select' ),
		'HADI' => __( 'Haharinskyi District', 'ry-wc-city-select' ),
		'HORA' => __( 'Holosiiv Raion', 'ry-wc-city-select' ),
		'KAMU' => __( 'Kamianske Municipality', 'ry-wc-city-select' ),
		'KHMI' => __( 'Khersonska Miskrada', 'ry-wc-city-select' ),
		'KHRA' => __( 'Khoroshiv Raion', 'ry-wc-city-select' ),
		'KIRA' => __( 'Kirovske Raion', 'ry-wc-city-select' ),
		'KRRA' => __( 'Krasnohvardiiske Raion', 'ry-wc-city-select' ),
		'KRRA2' => __( 'Krasnoperekopsk Raion', 'ry-wc-city-select' ),
		'LEDI' => __( 'Lenin District', 'ry-wc-city-select' ),
		'LERA' => __( 'Lenine Raion', 'ry-wc-city-select' ),
		'LURA' => __( 'Luhyny Raion', 'ry-wc-city-select' ),
		'LYAMTECO' => __( 'Lyman Amalgated Territorial Community', 'ry-wc-city-select' ),
		'MAMI' => __( 'Makiyivska Miskrada', 'ry-wc-city-select' ),
		'MARA' => __( 'Malyn Raion', 'ry-wc-city-select' ),
		'NARA' => __( 'Nakhimovskiy rayon', 'ry-wc-city-select' ),
		'NARA2' => __( 'Narodychi Raion', 'ry-wc-city-select' ),
		'NIRA' => __( 'Nizhnegorskiy rayon', 'ry-wc-city-select' ),
		'PERA' => __( 'Pervomayskiy rayon', 'ry-wc-city-select' ),
		'PORA' => __( 'Popilnia Raion', 'ry-wc-city-select' ),
		'PRRA' => __( 'Pryazovske Raion', 'ry-wc-city-select' ),
		'PRRA2' => __( 'Prymorsk Raion', 'ry-wc-city-select' ),
		'RARA' => __( 'Radomyshl Raion', 'ry-wc-city-select' ),
		'RARA2' => __( 'Razdolnenskiy rayon', 'ry-wc-city-select' ),
		'SARA' => __( 'Sakskiy rayon', 'ry-wc-city-select' ),
		'SIRA' => __( 'Simferopol Raion', 'ry-wc-city-select' ),
		'SORA' => __( 'Solomianka Rayon', 'ry-wc-city-select' ),
		'SORA2' => __( 'Sovietskyi Raion', 'ry-wc-city-select' ),
		'TORA' => __( 'Tokmak Raion', 'ry-wc-city-select' ),
		'VIMI' => __( 'Vinnytska Miskrada', 'ry-wc-city-select' ),
		'VORA' => __( 'Volochysk Raion', 'ry-wc-city-select' ),
		'YARA' => __( 'Yakymivka Raion', 'ry-wc-city-select' ),
		'AURECR' => __( 'Autonomous Republic of Crimea', 'ry-wc-city-select' ),
		'CHOB' => __( 'Cherkaska Oblast', 'ry-wc-city-select' ),
		'CHOB2' => __( 'Chernihivska Oblast', 'ry-wc-city-select' ),
		'CHOB3' => __( 'Chernivtsi Oblast', 'ry-wc-city-select' ),
		'DNOB' => __( 'Dnipropetrovska Oblast', 'ry-wc-city-select' ),
		'DOOB' => __( 'Donetska Oblast', 'ry-wc-city-select' ),
		'IVOB' => __( 'Ivano-Frankivska Oblast', 'ry-wc-city-select' ),
		'KHOB' => __( 'Kharkivska Oblast', 'ry-wc-city-select' ),
		'KHOB2' => __( 'Khersonska Oblast', 'ry-wc-city-select' ),
		'KHOB3' => __( 'Khmelnytska Oblast', 'ry-wc-city-select' ),
		'KIOB' => __( 'Kirovohradska Oblast', 'ry-wc-city-select' ),
		'KYOB' => __( 'Kyiv Oblast', 'ry-wc-city-select' ),
		'LVOB' => __( 'Lvivska Oblast', 'ry-wc-city-select' ),
		'LUOB' => __( 'Luhanska Oblast', 'ry-wc-city-select' ),
		'MIKY' => __( 'Misto Kyyiv', 'ry-wc-city-select' ),
		'MYOB' => __( 'Mykolayivska Oblast', 'ry-wc-city-select' ),
		'ODOB' => __( 'Odeska Oblast', 'ry-wc-city-select' ),
		'POOB' => __( 'Poltavska Oblast', 'ry-wc-city-select' ),
		'RIOB' => __( 'Rivnenska Oblast', 'ry-wc-city-select' ),
		'SUOB' => __( 'Sumska Oblast', 'ry-wc-city-select' ),
		'TEOB' => __( 'Ternopilska Oblast', 'ry-wc-city-select' ),
		'VIOB' => __( 'Vinnytska Oblast', 'ry-wc-city-select' ),
		'VOOB' => __( 'Volynska Oblast', 'ry-wc-city-select' ),
		'ZAOB' => __( 'Zakarpattia Oblast', 'ry-wc-city-select' ),
		'ZAOB2' => __( 'Zaporizka Oblast', 'ry-wc-city-select' ),
		'ZHOB' => __( 'Zhytomyrska Oblast', 'ry-wc-city-select' ),
		'SECI' => __( 'Sebastopol City', 'ry-wc-city-select' ),
	]
];