<?php
/**
 * Republic of Uganda states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'UG' => [
		'ABDI' => __( 'Abim District', 'ry-wc-city-select' ),
		'ADDI' => __( 'Adjumani District', 'ry-wc-city-select' ),
		'AGDI' => __( 'Agago District', 'ry-wc-city-select' ),
		'ALDI' => __( 'Alebtong District', 'ry-wc-city-select' ),
		'AMDI' => __( 'Amolatar District', 'ry-wc-city-select' ),
		'AMDI2' => __( 'Amudat District', 'ry-wc-city-select' ),
		'AMDI3' => __( 'Amuria District', 'ry-wc-city-select' ),
		'AMDI4' => __( 'Amuru District', 'ry-wc-city-select' ),
		'APDI' => __( 'Apac District', 'ry-wc-city-select' ),
		'ARDI' => __( 'Arua District', 'ry-wc-city-select' ),
		'BUDI' => __( 'Budaka District', 'ry-wc-city-select' ),
		'BUDI2' => __( 'Bududa District', 'ry-wc-city-select' ),
		'BUDI3' => __( 'Buhweju District', 'ry-wc-city-select' ),
		'BUDI4' => __( 'Buikwe District', 'ry-wc-city-select' ),
		'BUDI5' => __( 'Bukedea District', 'ry-wc-city-select' ),
		'BUDI6' => __( 'Bukomansimbi District', 'ry-wc-city-select' ),
		'BUDI7' => __( 'Bukwa District', 'ry-wc-city-select' ),
		'BUDI8' => __( 'Bulambuli District', 'ry-wc-city-select' ),
		'BUDI9' => __( 'Bulisa District', 'ry-wc-city-select' ),
		'BUDI10' => __( 'Bundibugyo District', 'ry-wc-city-select' ),
		'BU' => __( 'Bunyangabu', 'ry-wc-city-select' ),
		'BUDI11' => __( 'Bushenyi District', 'ry-wc-city-select' ),
		'BUDI12' => __( 'Busia District', 'ry-wc-city-select' ),
		'BUDI13' => __( 'Butaleja District', 'ry-wc-city-select' ),
		'BUDI14' => __( 'Butambala District', 'ry-wc-city-select' ),
		'BU2' => __( 'Butebo', 'ry-wc-city-select' ),
		'BUDI15' => __( 'Buvuma District', 'ry-wc-city-select' ),
		'BUDI16' => __( 'Buyende District', 'ry-wc-city-select' ),
		'DODI' => __( 'Dokolo District', 'ry-wc-city-select' ),
		'GODI' => __( 'Gomba District', 'ry-wc-city-select' ),
		'GUDI' => __( 'Gulu District', 'ry-wc-city-select' ),
		'HODI' => __( 'Hoima District', 'ry-wc-city-select' ),
		'IBDI' => __( 'Ibanda District', 'ry-wc-city-select' ),
		'IGDI' => __( 'Iganga District', 'ry-wc-city-select' ),
		'ISDI' => __( 'Isingiro District', 'ry-wc-city-select' ),
		'JIDI' => __( 'Jinja District', 'ry-wc-city-select' ),
		'KADI' => __( 'Kaabong District', 'ry-wc-city-select' ),
		'KADI2' => __( 'Kabale District', 'ry-wc-city-select' ),
		'KADI3' => __( 'Kabarole District', 'ry-wc-city-select' ),
		'KADI4' => __( 'Kaberamaido District', 'ry-wc-city-select' ),
		'KA' => __( 'Kagadi', 'ry-wc-city-select' ),
		'KA2' => __( 'Kakumiro', 'ry-wc-city-select' ),
		'KADI5' => __( 'Kalangala District', 'ry-wc-city-select' ),
		'KADI6' => __( 'Kaliro District', 'ry-wc-city-select' ),
		'KADI7' => __( 'Kalungu District', 'ry-wc-city-select' ),
		'KADI8' => __( 'Kampala District', 'ry-wc-city-select' ),
		'KADI9' => __( 'Kamuli District', 'ry-wc-city-select' ),
		'KADI10' => __( 'Kamwenge District', 'ry-wc-city-select' ),
		'KADI11' => __( 'Kanungu District', 'ry-wc-city-select' ),
		'KADI12' => __( 'Kapchorwa District', 'ry-wc-city-select' ),
		'KADI13' => __( 'Kasese District', 'ry-wc-city-select' ),
		'KADI14' => __( 'Katakwi District', 'ry-wc-city-select' ),
		'KADI15' => __( 'Kayunga District', 'ry-wc-city-select' ),
		'KIDI' => __( 'Kibale District', 'ry-wc-city-select' ),
		'KIDI2' => __( 'Kiboga District', 'ry-wc-city-select' ),
		'KIDI3' => __( 'Kibuku District', 'ry-wc-city-select' ),
		'KIDI4' => __( 'Kiruhura District', 'ry-wc-city-select' ),
		'KIDI5' => __( 'Kiryandongo District', 'ry-wc-city-select' ),
		'KIDI6' => __( 'Kisoro District', 'ry-wc-city-select' ),
		'KIDI7' => __( 'Kitgum District', 'ry-wc-city-select' ),
		'KODI' => __( 'Koboko District', 'ry-wc-city-select' ),
		'KODI2' => __( 'Kole District', 'ry-wc-city-select' ),
		'KODI3' => __( 'Kotido District', 'ry-wc-city-select' ),
		'KUDI' => __( 'Kumi District', 'ry-wc-city-select' ),
		'KWDI' => __( 'Kween District', 'ry-wc-city-select' ),
		'KYDI' => __( 'Kyegegwa District', 'ry-wc-city-select' ),
		'KYDI2' => __( 'Kyenjojo District', 'ry-wc-city-select' ),
		'KY' => __( 'Kyotera', 'ry-wc-city-select' ),
		'LADI' => __( 'Lamwo District', 'ry-wc-city-select' ),
		'LIDI' => __( 'Lira District', 'ry-wc-city-select' ),
		'LUDI' => __( 'Luuka District', 'ry-wc-city-select' ),
		'LUDI2' => __( 'Luwero District', 'ry-wc-city-select' ),
		'LWDI' => __( 'Lwengo District', 'ry-wc-city-select' ),
		'LYDI' => __( 'Lyantonde District', 'ry-wc-city-select' ),
		'MADI' => __( 'Manafwa District', 'ry-wc-city-select' ),
		'MADI2' => __( 'Maracha District', 'ry-wc-city-select' ),
		'MADI3' => __( 'Masaka District', 'ry-wc-city-select' ),
		'MADI4' => __( 'Masindi District', 'ry-wc-city-select' ),
		'MADI5' => __( 'Mayuge District', 'ry-wc-city-select' ),
		'MBDI' => __( 'Mbale District', 'ry-wc-city-select' ),
		'MBDI2' => __( 'Mbarara District', 'ry-wc-city-select' ),
		'MIDI' => __( 'Mitoma District', 'ry-wc-city-select' ),
		'MIDI2' => __( 'Mityana District', 'ry-wc-city-select' ),
		'MODI' => __( 'Moroto District', 'ry-wc-city-select' ),
		'MODI2' => __( 'Moyo District', 'ry-wc-city-select' ),
		'MPDI' => __( 'Mpigi District', 'ry-wc-city-select' ),
		'MUDI' => __( 'Mubende District', 'ry-wc-city-select' ),
		'MUDI2' => __( 'Mukono District', 'ry-wc-city-select' ),
		'NADI' => __( 'Nakapiripirit District', 'ry-wc-city-select' ),
		'NADI2' => __( 'Nakaseke District', 'ry-wc-city-select' ),
		'NADI3' => __( 'Nakasongola District', 'ry-wc-city-select' ),
		'NADI4' => __( 'Namayingo District', 'ry-wc-city-select' ),
		'NA' => __( 'Namisindwa', 'ry-wc-city-select' ),
		'NADI5' => __( 'Namutumba District', 'ry-wc-city-select' ),
		'NADI6' => __( 'Napak District', 'ry-wc-city-select' ),
		'NEDI' => __( 'Nebbi District', 'ry-wc-city-select' ),
		'NGDI' => __( 'Ngora District', 'ry-wc-city-select' ),
		'NTDI' => __( 'Ntoroko District', 'ry-wc-city-select' ),
		'NTDI2' => __( 'Ntungamo District', 'ry-wc-city-select' ),
		'NWDI' => __( 'Nwoya District', 'ry-wc-city-select' ),
		'OM' => __( 'Omoro', 'ry-wc-city-select' ),
		'OTDI' => __( 'Otuke District', 'ry-wc-city-select' ),
		'OYDI' => __( 'Oyam District', 'ry-wc-city-select' ),
		'PADI' => __( 'Pader District', 'ry-wc-city-select' ),
		'PA' => __( 'Pakwach', 'ry-wc-city-select' ),
		'PADI2' => __( 'Pallisa District', 'ry-wc-city-select' ),
		'RADI' => __( 'Rakai District', 'ry-wc-city-select' ),
		'RU' => __( 'Rubanda', 'ry-wc-city-select' ),
		'RUDI' => __( 'Rubirizi District', 'ry-wc-city-select' ),
		'RU2' => __( 'Rukiga', 'ry-wc-city-select' ),
		'RUDI2' => __( 'Rukungiri District', 'ry-wc-city-select' ),
		'SEDI' => __( 'Sembabule District', 'ry-wc-city-select' ),
		'SEDI2' => __( 'Serere District', 'ry-wc-city-select' ),
		'SHDI' => __( 'Sheema District', 'ry-wc-city-select' ),
		'SIDI' => __( 'Sironko District', 'ry-wc-city-select' ),
		'SODI' => __( 'Soroti District', 'ry-wc-city-select' ),
		'TODI' => __( 'Tororo District', 'ry-wc-city-select' ),
		'WADI' => __( 'Wakiso District', 'ry-wc-city-select' ),
		'YUDI' => __( 'Yumbe District', 'ry-wc-city-select' ),
		'ZODI' => __( 'Zombo District', 'ry-wc-city-select' ),
		'CERE' => __( 'Central Region', 'ry-wc-city-select' ),
		'EARE' => __( 'Eastern Region', 'ry-wc-city-select' ),
		'NORE' => __( 'Northern Region', 'ry-wc-city-select' ),
		'WERE' => __( 'Western Region', 'ry-wc-city-select' ),
	]
];