<?php
/**
 * Republic of South Africa states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'ZA' => [
		'ALNZDIMU' => __( 'Alfred Nzo District Municipality', 'ry-wc-city-select' ),
		'AMDIMU' => __( 'Amajuba District Municipality', 'ry-wc-city-select' ),
		'AMDIMU2' => __( 'Amathole District Municipality', 'ry-wc-city-select' ),
		'BOPLDIMU' => __( 'Bojanala Platinum District Municipality', 'ry-wc-city-select' ),
		'BUCIMEMU' => __( 'Buffalo City Metropolitan Municipality', 'ry-wc-city-select' ),
		'CAWIDIMU' => __( 'Cape Winelands District Municipality', 'ry-wc-city-select' ),
		'CADIMU' => __( 'Capricorn District Municipality', 'ry-wc-city-select' ),
		'CEKADIMU' => __( 'Central Karoo District Municipality', 'ry-wc-city-select' ),
		'CHHADIMU' => __( 'Chris Hani District Municipality', 'ry-wc-city-select' ),
		'CICATO' => __( 'City of Cape Town', 'ry-wc-city-select' ),
		'CIJOMEMU' => __( 'City of Johannesburg Metropolitan Munici', 'ry-wc-city-select' ),
		'CITSMEMU' => __( 'City of Tshwane Metropolitan Municipalit', 'ry-wc-city-select' ),
		'KEKADIMU' => __( 'Dr Kenneth Kaunda District Municipality', 'ry-wc-city-select' ),
		'RUSEMODIMU' => __( 'Dr Ruth Segomotsi Mompati District Munic', 'ry-wc-city-select' ),
		'EDDIMU' => __( 'Eden District Municipality', 'ry-wc-city-select' ),
		'EHDI' => __( 'Ehlanzeni District', 'ry-wc-city-select' ),
		'EKMEMU' => __( 'Ekurhuleni Metropolitan Municipality', 'ry-wc-city-select' ),
		'FEDADIMU' => __( 'Fezile Dabi District Municipality', 'ry-wc-city-select' ),
		'FRBADIMU' => __( 'Frances Baard District Municipality', 'ry-wc-city-select' ),
		'GESIDIMU' => __( 'Gert Sibande District Municipality', 'ry-wc-city-select' ),
		'JOGQDIMU' => __( 'Joe Gqabi District Municipality', 'ry-wc-city-select' ),
		'JOTAGADIMU' => __( 'John Taolo Gaetsewe District Municipalit', 'ry-wc-city-select' ),
		'LEDIMU' => __( 'Lejweleputswa District Municipality', 'ry-wc-city-select' ),
		'MAMEMU' => __( 'Mangaung Metropolitan Municipality', 'ry-wc-city-select' ),
		'MODIMU' => __( 'Mopani District Municipality', 'ry-wc-city-select' ),
		'NADIMU' => __( 'Namakwa District Municipality', 'ry-wc-city-select' ),
		'NEMABAMEMU' => __( 'Nelson Mandela Bay Metropolitan Municipa', 'ry-wc-city-select' ),
		'NGMOMODIMU' => __( 'Ngaka Modiri Molema District Municipalit', 'ry-wc-city-select' ),
		'NKDIMU' => __( 'Nkangala District Municipality', 'ry-wc-city-select' ),
		'TADIMU' => __( 'OR Tambo District Municipality', 'ry-wc-city-select' ),
		'OVDIMU' => __( 'Overberg District Municipality', 'ry-wc-city-select' ),
		'PISEDIMU' => __( 'Pixley ka Seme District Municipality', 'ry-wc-city-select' ),
		'SABADIMU' => __( 'Sarah Baartman District Municipality', 'ry-wc-city-select' ),
		'SEDIMU' => __( 'Sedibeng District Municipality', 'ry-wc-city-select' ),
		'SEDIMU2' => __( 'Sekhukhune District Municipality', 'ry-wc-city-select' ),
		'SIDIMU' => __( 'Sisonke District Municipality', 'ry-wc-city-select' ),
		'SIDIMU2' => __( 'Siyanda District Municipality', 'ry-wc-city-select' ),
		'THMODIMU' => __( 'Thabo Mofutsanyana District Municipality', 'ry-wc-city-select' ),
		'UGDIMU' => __( 'Ugu District Municipality', 'ry-wc-city-select' ),
		'VHDIMU' => __( 'Vhembe District Municipality', 'ry-wc-city-select' ),
		'WADIMU' => __( 'Waterberg District Municipality', 'ry-wc-city-select' ),
		'WECODIMU' => __( 'West Coast District Municipality', 'ry-wc-city-select' ),
		'WERADIMU' => __( 'West Rand District Municipality', 'ry-wc-city-select' ),
		'XHDIMU' => __( 'Xhariep District Municipality', 'ry-wc-city-select' ),
		'ZUDIMU' => __( 'Zululand District Municipality', 'ry-wc-city-select' ),
		'ETMEMU' => __( 'eThekwini Metropolitan Municipality', 'ry-wc-city-select' ),
		'ILDIMU' => __( 'iLembe District Municipality', 'ry-wc-city-select' ),
		'UMDIMU' => __( 'uMgungundlovu District Municipality', 'ry-wc-city-select' ),
		'UMDIMU2' => __( 'uMkhanyakude District Municipality', 'ry-wc-city-select' ),
		'UMDIMU3' => __( 'uMzinyathi District Municipality', 'ry-wc-city-select' ),
		'UTDIMU' => __( 'uThukela District Municipality', 'ry-wc-city-select' ),
		'UTDIMU2' => __( 'uThungulu District Municipality', 'ry-wc-city-select' ),
		'EACA' => __( 'Eastern Cape', 'ry-wc-city-select' ),
		'FRST' => __( 'Free State', 'ry-wc-city-select' ),
		'GA' => __( 'Gauteng', 'ry-wc-city-select' ),
		'KW' => __( 'KwaZulu-Natal', 'ry-wc-city-select' ),
		'LI' => __( 'Limpopo', 'ry-wc-city-select' ),
		'MP' => __( 'Mpumalanga', 'ry-wc-city-select' ),
		'NOWE' => __( 'North West', 'ry-wc-city-select' ),
		'NOCA' => __( 'Northern Cape', 'ry-wc-city-select' ),
		'WECA' => __( 'Western Cape', 'ry-wc-city-select' ),
	]
];