<?php
/**
 * Islamic Republic of Afghanistan places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'AF' => [
	'BA' => [
		_x('Arghanj Khwah', 'BA', 'ry-wc-city-select'),
		_x('Argo', 'BA', 'ry-wc-city-select'),
		_x('Baharak', 'BA', 'ry-wc-city-select'),
		_x('Darayim', 'BA', 'ry-wc-city-select'),
		_x('Darwaz-e Bala', 'BA', 'ry-wc-city-select'),
		_x('Darwaz-e Pain', 'BA', 'ry-wc-city-select'),
		_x('Faizabad', 'BA', 'ry-wc-city-select'),
		_x('Ishkashim', 'BA', 'ry-wc-city-select'),
		_x('Jurm', 'BA', 'ry-wc-city-select'),
		_x('Khash', 'BA', 'ry-wc-city-select'),
		_x('Khwahan', 'BA', 'ry-wc-city-select'),
		_x('Kishim', 'BA', 'ry-wc-city-select'),
		_x('Kohistan', 'BA', 'ry-wc-city-select'),
		_x('Kuf Ab', 'BA', 'ry-wc-city-select'),
		_x('Kuran Wa Munjan', 'BA', 'ry-wc-city-select'),
		_x('Raghistan', 'BA', 'ry-wc-city-select'),
		_x('Shahr-e Buzurg', 'BA', 'ry-wc-city-select'),
		_x('Shighnan District', 'BA', 'ry-wc-city-select'),
		_x('Shiki', 'BA', 'ry-wc-city-select'),
		_x('Shuhada', 'BA', 'ry-wc-city-select'),
		_x('Tagab', 'BA', 'ry-wc-city-select'),
		_x('Tashkan', 'BA', 'ry-wc-city-select'),
		_x('Wakhan', 'BA', 'ry-wc-city-select'),
		_x('Warduj', 'BA', 'ry-wc-city-select'),
		_x('Yaftal-e Sufla', 'BA', 'ry-wc-city-select'),
		_x('Yamgan', 'BA', 'ry-wc-city-select'),
		_x('Yawan', 'BA', 'ry-wc-city-select'),
		_x('Zaybak', 'BA', 'ry-wc-city-select'),
	],
	'BA2' => [
		_x('Ab-e Kamari', 'BA2', 'ry-wc-city-select'),
		_x('Ghormach', 'BA2', 'ry-wc-city-select'),
		_x('Jowand', 'BA2', 'ry-wc-city-select'),
		_x('Muqur', 'BA2', 'ry-wc-city-select'),
		_x('Murghab', 'BA2', 'ry-wc-city-select'),
		_x('Qadis', 'BA2', 'ry-wc-city-select'),
		_x('Qalah-ye Now', 'BA2', 'ry-wc-city-select'),
	],
	'BA3' => [
		_x('Balkh District', 'BA3', 'ry-wc-city-select'),
		_x('Chahar Bolak', 'BA3', 'ry-wc-city-select'),
		_x('Chahar Kent', 'BA3', 'ry-wc-city-select'),
		_x('Chimtal', 'BA3', 'ry-wc-city-select'),
		_x('Dehdadi', 'BA3', 'ry-wc-city-select'),
		_x('Dowlatabad', 'BA3', 'ry-wc-city-select'),
		_x('Kaldar', 'BA3', 'ry-wc-city-select'),
		_x('Khulm', 'BA3', 'ry-wc-city-select'),
		_x('Kishindeh', 'BA3', 'ry-wc-city-select'),
		_x('Marmul', 'BA3', 'ry-wc-city-select'),
		_x('Mazar-e Sharif', 'BA3', 'ry-wc-city-select'),
		_x('Nahri Shahi', 'BA3', 'ry-wc-city-select'),
		_x('Sholgara', 'BA3', 'ry-wc-city-select'),
		_x('Shor Tepah', 'BA3', 'ry-wc-city-select'),
		_x('Zari', 'BA3', 'ry-wc-city-select'),
	],
	'DAPR' => [
		_x('Gayti', 'DAPR', 'ry-wc-city-select'),
		_x('Gizab', 'DAPR', 'ry-wc-city-select'),
		_x('Ishtarlay', 'DAPR', 'ry-wc-city-select'),
		_x('Kajran', 'DAPR', 'ry-wc-city-select'),
		_x('Khadir', 'DAPR', 'ry-wc-city-select'),
		_x('Mir Amor', 'DAPR', 'ry-wc-city-select'),
		_x('Nili', 'DAPR', 'ry-wc-city-select'),
		_x('Sang-e Takht', 'DAPR', 'ry-wc-city-select'),
		_x('Shahristan', 'DAPR', 'ry-wc-city-select'),
	],
	'FA' => [
		_x('Anar Darah', 'FA', 'ry-wc-city-select'),
		_x('Bakwah', 'FA', 'ry-wc-city-select'),
		_x('Bala Buluk', 'FA', 'ry-wc-city-select'),
		_x('Farah', 'FA', 'ry-wc-city-select'),
		_x('Gulistan', 'FA', 'ry-wc-city-select'),
		_x('Khak-e Safed', 'FA', 'ry-wc-city-select'),
		_x('Lash-e Juwayn', 'FA', 'ry-wc-city-select'),
		_x('Pur Chaman', 'FA', 'ry-wc-city-select'),
		_x('Pusht-e Rod', 'FA', 'ry-wc-city-select'),
		_x('Qalah-ye Kah', 'FA', 'ry-wc-city-select'),
		_x('Shayb Koh', 'FA', 'ry-wc-city-select'),
	],
	'FAPR' => [
		_x('Almar', 'FAPR', 'ry-wc-city-select'),
		_x('Andkhoy', 'FAPR', 'ry-wc-city-select'),
		_x('Bal Chiragh', 'FAPR', 'ry-wc-city-select'),
		_x('Dowlatabad', 'FAPR', 'ry-wc-city-select'),
		_x('Gurziwan', 'FAPR', 'ry-wc-city-select'),
		_x('Khan-e Chahar Bagh', 'FAPR', 'ry-wc-city-select'),
		_x('Khwajah Sabz Posh', 'FAPR', 'ry-wc-city-select'),
		_x('Kohistan', 'FAPR', 'ry-wc-city-select'),
		_x('Maimanah', 'FAPR', 'ry-wc-city-select'),
		_x('Pashtun Kot', 'FAPR', 'ry-wc-city-select'),
		_x('Qaisar', 'FAPR', 'ry-wc-city-select'),
		_x('Qaram Qol', 'FAPR', 'ry-wc-city-select'),
		_x('Qurghan', 'FAPR', 'ry-wc-city-select'),
		_x('Shirin Tagab', 'FAPR', 'ry-wc-city-select'),
	],
	'HE' => [
		_x('Baghran', 'HE', 'ry-wc-city-select'),
		_x('Dishu', 'HE', 'ry-wc-city-select'),
		_x('Garmsir', 'HE', 'ry-wc-city-select'),
		_x('Kajaki', 'HE', 'ry-wc-city-select'),
		_x('Lashkar Gah', 'HE', 'ry-wc-city-select'),
		_x('Musa Qalah', 'HE', 'ry-wc-city-select'),
		_x('Nad Ali', 'HE', 'ry-wc-city-select'),
		_x('Nahr-e Saraj', 'HE', 'ry-wc-city-select'),
		_x('Naw Zad', 'HE', 'ry-wc-city-select'),
		_x('Nawah-ye Barakzai', 'HE', 'ry-wc-city-select'),
		_x('Reg-e Khan Neshin', 'HE', 'ry-wc-city-select'),
		_x('Sangin', 'HE', 'ry-wc-city-select'),
		_x('Washer', 'HE', 'ry-wc-city-select'),
	],
	'HE2' => [
		_x('Adraskan', 'HE2', 'ry-wc-city-select'),
		_x('Chisht-e Sharif', 'HE2', 'ry-wc-city-select'),
		_x('Farsi', 'HE2', 'ry-wc-city-select'),
		_x('Ghoriyan', 'HE2', 'ry-wc-city-select'),
		_x('Gulran', 'HE2', 'ry-wc-city-select'),
		_x('Guzarah', 'HE2', 'ry-wc-city-select'),
		_x('Herat District', 'HE2', 'ry-wc-city-select'),
		_x('Injil', 'HE2', 'ry-wc-city-select'),
		_x('Karukh', 'HE2', 'ry-wc-city-select'),
		_x('Kuhsan', 'HE2', 'ry-wc-city-select'),
		_x('Kushk', 'HE2', 'ry-wc-city-select'),
		_x('Kushk-e Kuhnah', 'HE2', 'ry-wc-city-select'),
		_x('Obeh', 'HE2', 'ry-wc-city-select'),
		_x('Pashtun Zarghun', 'HE2', 'ry-wc-city-select'),
		_x('Shindand', 'HE2', 'ry-wc-city-select'),
		_x('Zindah Jan', 'HE2', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Arghandab', 'KA', 'ry-wc-city-select'),
		_x('Arghistan', 'KA', 'ry-wc-city-select'),
		_x('Daman', 'KA', 'ry-wc-city-select'),
		_x('Ghorak', 'KA', 'ry-wc-city-select'),
		_x('Kandahar District', 'KA', 'ry-wc-city-select'),
		_x('Khakrez', 'KA', 'ry-wc-city-select'),
		_x('Maruf', 'KA', 'ry-wc-city-select'),
		_x('Maywand', 'KA', 'ry-wc-city-select'),
		_x('Mya Neshin', 'KA', 'ry-wc-city-select'),
		_x('Nesh', 'KA', 'ry-wc-city-select'),
		_x('Panjwai', 'KA', 'ry-wc-city-select'),
		_x('Registan', 'KA', 'ry-wc-city-select'),
		_x('Shah Wali Kot', 'KA', 'ry-wc-city-select'),
		_x('Shorabak', 'KA', 'ry-wc-city-select'),
		_x('Spin Boldak', 'KA', 'ry-wc-city-select'),
		_x('Zharey', 'KA', 'ry-wc-city-select'),
	],
	'KU' => [
		_x('Aliabad', 'KU', 'ry-wc-city-select'),
		_x('Chahar Dara', 'KU', 'ry-wc-city-select'),
		_x('Dasht-e Archi', 'KU', 'ry-wc-city-select'),
		_x('Imam Sahib', 'KU', 'ry-wc-city-select'),
		_x('Khanabad', 'KU', 'ry-wc-city-select'),
		_x('Kunduz', 'KU', 'ry-wc-city-select'),
		_x('Qalah-ye Zal', 'KU', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Achin', 'NA', 'ry-wc-city-select'),
		_x('Bati Kot', 'NA', 'ry-wc-city-select'),
		_x('Bihsud', 'NA', 'ry-wc-city-select'),
		_x('Chaparhar', 'NA', 'ry-wc-city-select'),
		_x('Darah-ye Nur', 'NA', 'ry-wc-city-select'),
		_x('Deh Bala', 'NA', 'ry-wc-city-select'),
		_x('Dur Baba', 'NA', 'ry-wc-city-select'),
		_x('Goshtah', 'NA', 'ry-wc-city-select'),
		_x('Hisarak', 'NA', 'ry-wc-city-select'),
		_x('Jalalabad', 'NA', 'ry-wc-city-select'),
		_x('Kamah', 'NA', 'ry-wc-city-select'),
		_x('Khugyani', 'NA', 'ry-wc-city-select'),
		_x('Kot', 'NA', 'ry-wc-city-select'),
		_x('Kuz Kunar', 'NA', 'ry-wc-city-select'),
		_x('Lalpur', 'NA', 'ry-wc-city-select'),
		_x('Mohmand Darah', 'NA', 'ry-wc-city-select'),
		_x('Naziyan', 'NA', 'ry-wc-city-select'),
		_x('Pachir wa Agam', 'NA', 'ry-wc-city-select'),
		_x('Rodat', 'NA', 'ry-wc-city-select'),
		_x('Sherzad', 'NA', 'ry-wc-city-select'),
		_x('Shinwar', 'NA', 'ry-wc-city-select'),
		_x('Surkh Rod', 'NA', 'ry-wc-city-select'),
	],
	'PA' => [
		_x('Unabah', 'PA', 'ry-wc-city-select'),
		_x('Bazarak', 'PA', 'ry-wc-city-select'),
		_x('Darah', 'PA', 'ry-wc-city-select'),
		_x('Khinj', 'PA', 'ry-wc-city-select'),
		_x('Parian', 'PA', 'ry-wc-city-select'),
		_x('Rukhah', 'PA', 'ry-wc-city-select'),
		_x('Shutul', 'PA', 'ry-wc-city-select'),
	],
	'PA2' => [
		_x('Bagram', 'PA2', 'ry-wc-city-select'),
		_x('Charikar', 'PA2', 'ry-wc-city-select'),
		_x('Jabal us Saraj', 'PA2', 'ry-wc-city-select'),
		_x('Koh-e Safi', 'PA2', 'ry-wc-city-select'),
		_x('Salang', 'PA2', 'ry-wc-city-select'),
		_x('Sayyid Khel', 'PA2', 'ry-wc-city-select'),
		_x('Shaykh Ali', 'PA2', 'ry-wc-city-select'),
		_x('Shinwari', 'PA2', 'ry-wc-city-select'),
		_x('Siyahgird Ghorband', 'PA2', 'ry-wc-city-select'),
		_x('Surkhi Parsa', 'PA2', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Aibak', 'SA', 'ry-wc-city-select'),
		_x('Darah-ye Suf-e Bala', 'SA', 'ry-wc-city-select'),
		_x('Darah-ye Suf-e Pain', 'SA', 'ry-wc-city-select'),
		_x('Fayroz Nakhchir', 'SA', 'ry-wc-city-select'),
		_x('Hazrat-e Sultan', 'SA', 'ry-wc-city-select'),
		_x('Khuram wa Sar Bagh', 'SA', 'ry-wc-city-select'),
		_x('Ruy Duab', 'SA', 'ry-wc-city-select'),
	],
	'SAPU' => [
		_x('Balkhab', 'SAPU', 'ry-wc-city-select'),
		_x('Gosfandi', 'SAPU', 'ry-wc-city-select'),
		_x('Kohistanat', 'SAPU', 'ry-wc-city-select'),
		_x('Sangcharak', 'SAPU', 'ry-wc-city-select'),
		_x('Sar-e Pul', 'SAPU', 'ry-wc-city-select'),
		_x('Sayad', 'SAPU', 'ry-wc-city-select'),
		_x('Sozmah Qalah', 'SAPU', 'ry-wc-city-select'),
	],
	'UR' => [
		_x('Chorah', 'UR', 'ry-wc-city-select'),
		_x('Deh Rawud', 'UR', 'ry-wc-city-select'),
		_x('Khas Uruzgan', 'UR', 'ry-wc-city-select'),
		_x('Shahid-e Hasas', 'UR', 'ry-wc-city-select'),
		_x('Tarin Kot', 'UR', 'ry-wc-city-select'),
	],
	'VEKH' => [
		_x('Bak', 'VEKH', 'ry-wc-city-select'),
		_x('Gurbuz', 'VEKH', 'ry-wc-city-select'),
		_x('Jaji Maidan', 'VEKH', 'ry-wc-city-select'),
		_x('Khost', 'VEKH', 'ry-wc-city-select'),
		_x('Manduzai', 'VEKH', 'ry-wc-city-select'),
		_x('Musa Khel', 'VEKH', 'ry-wc-city-select'),
		_x('Nadir Shah Kot', 'VEKH', 'ry-wc-city-select'),
		_x('Qalandar', 'VEKH', 'ry-wc-city-select'),
		_x('Sabari', 'VEKH', 'ry-wc-city-select'),
		_x('Shamul', 'VEKH', 'ry-wc-city-select'),
		_x('Sperah', 'VEKH', 'ry-wc-city-select'),
		_x('Tani', 'VEKH', 'ry-wc-city-select'),
		_x('Terayzai', 'VEKH', 'ry-wc-city-select'),
	],
	'VENU' => [
		_x('Barg-e Matal', 'VENU', 'ry-wc-city-select'),
		_x('Du Ab', 'VENU', 'ry-wc-city-select'),
		_x('Kamdesh', 'VENU', 'ry-wc-city-select'),
		_x('Mandol', 'VENU', 'ry-wc-city-select'),
		_x('Nurgaram', 'VENU', 'ry-wc-city-select'),
		_x('Parun', 'VENU', 'ry-wc-city-select'),
		_x('Wama', 'VENU', 'ry-wc-city-select'),
		_x('Waygal', 'VENU', 'ry-wc-city-select'),
	],
	'WA' => [
		_x('Chak-e Wardak', 'WA', 'ry-wc-city-select'),
		_x('Day Mirdad', 'WA', 'ry-wc-city-select'),
		_x('Hisah-ye Awal-e Bihsud', 'WA', 'ry-wc-city-select'),
		_x('Jaghatu', 'WA', 'ry-wc-city-select'),
		_x('Jalrayz', 'WA', 'ry-wc-city-select'),
		_x('Maidan Shahr', 'WA', 'ry-wc-city-select'),
		_x('Markazi Bihsud', 'WA', 'ry-wc-city-select'),
		_x('Nirkh', 'WA', 'ry-wc-city-select'),
		_x('Sayyidabad', 'WA', 'ry-wc-city-select'),
	],
	'WIBA' => [
		_x('Andarab', 'WIBA', 'ry-wc-city-select'),
		_x('Baghlan-e Jadid', 'WIBA', 'ry-wc-city-select'),
		_x('Burkah', 'WIBA', 'ry-wc-city-select'),
		_x('Dahanah-ye Ghori', 'WIBA', 'ry-wc-city-select'),
		_x('Deh-e Salah', 'WIBA', 'ry-wc-city-select'),
		_x('Doshi', 'WIBA', 'ry-wc-city-select'),
		_x('Firing wa Gharu', 'WIBA', 'ry-wc-city-select'),
		_x('Guzargah-e Nur', 'WIBA', 'ry-wc-city-select'),
		_x('Khinjan', 'WIBA', 'ry-wc-city-select'),
		_x('Khost wa Firing', 'WIBA', 'ry-wc-city-select'),
		_x('Khwajah Hijran', 'WIBA', 'ry-wc-city-select'),
		_x('Nahrin', 'WIBA', 'ry-wc-city-select'),
		_x('Pul-e Hisar', 'WIBA', 'ry-wc-city-select'),
		_x('Puli Khumri', 'WIBA', 'ry-wc-city-select'),
		_x('Talah wa Barfak', 'WIBA', 'ry-wc-city-select'),
	],
	'WIBA2' => [
		_x('Bamyan', 'WIBA2', 'ry-wc-city-select'),
		_x('Kahmard', 'WIBA2', 'ry-wc-city-select'),
		_x('Panjab', 'WIBA2', 'ry-wc-city-select'),
		_x('Sayghan', 'WIBA2', 'ry-wc-city-select'),
		_x('Shibar', 'WIBA2', 'ry-wc-city-select'),
		_x('Waras', 'WIBA2', 'ry-wc-city-select'),
		_x('Yakawlang', 'WIBA2', 'ry-wc-city-select'),
	],
	'WIGH' => [
		_x('Ab Band', 'WIGH', 'ry-wc-city-select'),
		_x('Ajristan', 'WIGH', 'ry-wc-city-select'),
		_x('Andar', 'WIGH', 'ry-wc-city-select'),
		_x('Bahram-e Shahid', 'WIGH', 'ry-wc-city-select'),
		_x('Deh Yak', 'WIGH', 'ry-wc-city-select'),
		_x('Gelan', 'WIGH', 'ry-wc-city-select'),
		_x('Ghazni', 'WIGH', 'ry-wc-city-select'),
		_x('Giro', 'WIGH', 'ry-wc-city-select'),
		_x('Jaghuri', 'WIGH', 'ry-wc-city-select'),
		_x('Khwajah Omari', 'WIGH', 'ry-wc-city-select'),
		_x('Malistan', 'WIGH', 'ry-wc-city-select'),
		_x('Muqer', 'WIGH', 'ry-wc-city-select'),
		_x('Nawah', 'WIGH', 'ry-wc-city-select'),
		_x('Nawur', 'WIGH', 'ry-wc-city-select'),
		_x('Qarah Bagh', 'WIGH', 'ry-wc-city-select'),
		_x('Rashidan', 'WIGH', 'ry-wc-city-select'),
		_x('Waghaz', 'WIGH', 'ry-wc-city-select'),
		_x('Wali Muhammad Shahid Khugyani', 'WIGH', 'ry-wc-city-select'),
		_x('Zanakhan', 'WIGH', 'ry-wc-city-select'),
	],
	'WIGH2' => [
		_x('Chaghcharan', 'WIGH2', 'ry-wc-city-select'),
		_x('Chahar Sadah', 'WIGH2', 'ry-wc-city-select'),
		_x('Dowlatyar', 'WIGH2', 'ry-wc-city-select'),
		_x('Du Lainah', 'WIGH2', 'ry-wc-city-select'),
		_x('Lal wa Sar Jangal', 'WIGH2', 'ry-wc-city-select'),
		_x('Pasaband', 'WIGH2', 'ry-wc-city-select'),
		_x('Saghar', 'WIGH2', 'ry-wc-city-select'),
		_x('Shahrak', 'WIGH2', 'ry-wc-city-select'),
		_x('Taywarah', 'WIGH2', 'ry-wc-city-select'),
		_x('Tulak', 'WIGH2', 'ry-wc-city-select'),
	],
	'WIJO' => [
		_x('Aqchah', 'WIJO', 'ry-wc-city-select'),
		_x('Darzab', 'WIJO', 'ry-wc-city-select'),
		_x('Faizabad', 'WIJO', 'ry-wc-city-select'),
		_x('Khamyab', 'WIJO', 'ry-wc-city-select'),
		_x('Khanaqah', 'WIJO', 'ry-wc-city-select'),
		_x('Khwajah Du Koh', 'WIJO', 'ry-wc-city-select'),
		_x('Mardian', 'WIJO', 'ry-wc-city-select'),
		_x('Mingajik', 'WIJO', 'ry-wc-city-select'),
		_x('Qarqin', 'WIJO', 'ry-wc-city-select'),
		_x('Qush Tepah', 'WIJO', 'ry-wc-city-select'),
		_x('Shibirghan', 'WIJO', 'ry-wc-city-select'),
	],
	'WIKA' => [
		_x('Bagrami', 'WIKA', 'ry-wc-city-select'),
		_x('Chahar Asyab', 'WIKA', 'ry-wc-city-select'),
		_x('Deh-e Sabz', 'WIKA', 'ry-wc-city-select'),
		_x('Farzah', 'WIKA', 'ry-wc-city-select'),
		_x('Gul Darah', 'WIKA', 'ry-wc-city-select'),
		_x('Istalif', 'WIKA', 'ry-wc-city-select'),
		_x('Kabul', 'WIKA', 'ry-wc-city-select'),
		_x('Kalakan', 'WIKA', 'ry-wc-city-select'),
		_x('Khak-e Jabar', 'WIKA', 'ry-wc-city-select'),
		_x('Mir Bachah Kot', 'WIKA', 'ry-wc-city-select'),
		_x('Musahi', 'WIKA', 'ry-wc-city-select'),
		_x('Paghman', 'WIKA', 'ry-wc-city-select'),
		_x('Qarah Bagh', 'WIKA', 'ry-wc-city-select'),
		_x('Shakar Darah', 'WIKA', 'ry-wc-city-select'),
		_x('Surobi', 'WIKA', 'ry-wc-city-select'),
	],
	'WIKA2' => [
		_x('Alah Say', 'WIKA2', 'ry-wc-city-select'),
		_x('Hisah-ye Awal-e Kohistan', 'WIKA2', 'ry-wc-city-select'),
		_x('Hisah-ye Duwum-e Kohistan', 'WIKA2', 'ry-wc-city-select'),
		_x('Koh Band', 'WIKA2', 'ry-wc-city-select'),
		_x('Mahmud-e Raqi', 'WIKA2', 'ry-wc-city-select'),
		_x('Nijrab', 'WIKA2', 'ry-wc-city-select'),
		_x('Tagab', 'WIKA2', 'ry-wc-city-select'),
	],
	'WIKU' => [
		_x('Asadabad', 'WIKU', 'ry-wc-city-select'),
		_x('Bar Kunar', 'WIKU', 'ry-wc-city-select'),
		_x('Chapah Darah', 'WIKU', 'ry-wc-city-select'),
		_x('Dangam', 'WIKU', 'ry-wc-city-select'),
		_x('Darah-ye Pech', 'WIKU', 'ry-wc-city-select'),
		_x('Ghaziabad', 'WIKU', 'ry-wc-city-select'),
		_x('Khas Kunar', 'WIKU', 'ry-wc-city-select'),
		_x('Marawarah', 'WIKU', 'ry-wc-city-select'),
		_x('Narang', 'WIKU', 'ry-wc-city-select'),
		_x('Naray', 'WIKU', 'ry-wc-city-select'),
		_x('Nurgal', 'WIKU', 'ry-wc-city-select'),
		_x('Shigal wa Sheltan', 'WIKU', 'ry-wc-city-select'),
		_x('Sirkanay', 'WIKU', 'ry-wc-city-select'),
		_x('Tsowkey', 'WIKU', 'ry-wc-city-select'),
		_x('Wutahpur', 'WIKU', 'ry-wc-city-select'),
	],
	'WILA' => [
		_x('Alingar', 'WILA', 'ry-wc-city-select'),
		_x('Alisheng', 'WILA', 'ry-wc-city-select'),
		_x('Dowlat Shah', 'WILA', 'ry-wc-city-select'),
		_x('Mehtar Lam', 'WILA', 'ry-wc-city-select'),
		_x('Qarghahi', 'WILA', 'ry-wc-city-select'),
	],
	'WILO' => [
		_x('Azrah', 'WILO', 'ry-wc-city-select'),
		_x('Baraki Barak', 'WILO', 'ry-wc-city-select'),
		_x('Charkh', 'WILO', 'ry-wc-city-select'),
		_x('Kharwar', 'WILO', 'ry-wc-city-select'),
		_x('Khoshi', 'WILO', 'ry-wc-city-select'),
		_x('Muhammad Aghah', 'WILO', 'ry-wc-city-select'),
		_x('Pul-e Alam', 'WILO', 'ry-wc-city-select'),
	],
	'WINI' => [
		_x('Chahar Burjak', 'WINI', 'ry-wc-city-select'),
		_x('Chakhansur', 'WINI', 'ry-wc-city-select'),
		_x('Kang', 'WINI', 'ry-wc-city-select'),
		_x('Khash Rod', 'WINI', 'ry-wc-city-select'),
		_x('Zaranj', 'WINI', 'ry-wc-city-select'),
	],
	'WIPA' => [
		_x('Bermal', 'WIPA', 'ry-wc-city-select'),
		_x('Dilah', 'WIPA', 'ry-wc-city-select'),
		_x('Giyan', 'WIPA', 'ry-wc-city-select'),
		_x('Gomal', 'WIPA', 'ry-wc-city-select'),
		_x('Jani Khel', 'WIPA', 'ry-wc-city-select'),
		_x('Muta Khan', 'WIPA', 'ry-wc-city-select'),
		_x('Nikeh', 'WIPA', 'ry-wc-city-select'),
		_x('Omnah', 'WIPA', 'ry-wc-city-select'),
		_x('Sar Rowzah', 'WIPA', 'ry-wc-city-select'),
		_x('Sarobi', 'WIPA', 'ry-wc-city-select'),
		_x('Sharan', 'WIPA', 'ry-wc-city-select'),
		_x('Terwo', 'WIPA', 'ry-wc-city-select'),
		_x('Urgun District', 'WIPA', 'ry-wc-city-select'),
		_x('Wazah Khwah', 'WIPA', 'ry-wc-city-select'),
		_x('Wur Mamay', 'WIPA', 'ry-wc-city-select'),
		_x('Yahya Khel', 'WIPA', 'ry-wc-city-select'),
		_x('Yosuf Khel', 'WIPA', 'ry-wc-city-select'),
		_x('Zarghun Shahr', 'WIPA', 'ry-wc-city-select'),
		_x('Ziruk', 'WIPA', 'ry-wc-city-select'),
	],
	'WIPA2' => [
		_x('Ahmadabad', 'WIPA2', 'ry-wc-city-select'),
		_x('Dand Patan', 'WIPA2', 'ry-wc-city-select'),
		_x('Dzadran', 'WIPA2', 'ry-wc-city-select'),
		_x('Gardez', 'WIPA2', 'ry-wc-city-select'),
		_x('Jaji', 'WIPA2', 'ry-wc-city-select'),
		_x('Jani Khel', 'WIPA2', 'ry-wc-city-select'),
		_x('Lajah Ahmad Khel', 'WIPA2', 'ry-wc-city-select'),
		_x('Sayyid Karam', 'WIPA2', 'ry-wc-city-select'),
		_x('Shwak', 'WIPA2', 'ry-wc-city-select'),
		_x('Tsamkani', 'WIPA2', 'ry-wc-city-select'),
		_x('Zurmat', 'WIPA2', 'ry-wc-city-select'),
	],
	'WITA' => [
		_x('Baharak', 'WITA', 'ry-wc-city-select'),
		_x('Bangi', 'WITA', 'ry-wc-city-select'),
		_x('Chah Ab', 'WITA', 'ry-wc-city-select'),
		_x('Chal', 'WITA', 'ry-wc-city-select'),
		_x('Darqad', 'WITA', 'ry-wc-city-select'),
		_x('Dasht-e Qalah', 'WITA', 'ry-wc-city-select'),
		_x('Farkhar', 'WITA', 'ry-wc-city-select'),
		_x('Hazar Sumuch', 'WITA', 'ry-wc-city-select'),
		_x('Ishkamish', 'WITA', 'ry-wc-city-select'),
		_x('Kalafgan', 'WITA', 'ry-wc-city-select'),
		_x('Khwajah Bahawuddin', 'WITA', 'ry-wc-city-select'),
		_x('Khwajah Ghar', 'WITA', 'ry-wc-city-select'),
		_x('Namak Ab', 'WITA', 'ry-wc-city-select'),
		_x('Rustaq', 'WITA', 'ry-wc-city-select'),
		_x('Taluqan', 'WITA', 'ry-wc-city-select'),
		_x('Warsaj', 'WITA', 'ry-wc-city-select'),
		_x('Yangi Qalah', 'WITA', 'ry-wc-city-select'),
	],
	'WIZA' => [
		_x('Arghandab', 'WIZA', 'ry-wc-city-select'),
		_x('Atghar', 'WIZA', 'ry-wc-city-select'),
		_x('Daychopan', 'WIZA', 'ry-wc-city-select'),
		_x('Kakar', 'WIZA', 'ry-wc-city-select'),
		_x('Mizan', 'WIZA', 'ry-wc-city-select'),
		_x('Now Bahar', 'WIZA', 'ry-wc-city-select'),
		_x('Qalat', 'WIZA', 'ry-wc-city-select'),
		_x('Shah Joy', 'WIZA', 'ry-wc-city-select'),
		_x('Shamulzai', 'WIZA', 'ry-wc-city-select'),
		_x('Shinkai', 'WIZA', 'ry-wc-city-select'),
		_x('Tarnek wa Jaldak', 'WIZA', 'ry-wc-city-select'),
	],
	]
];