<?php
/**
 * Republic of Albania places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'AL' => [
	'RREL' => [
		_x('Komuna e Gracenit', 'RREL', 'ry-wc-city-select'),
	],
	'RRTR' => [
		_x('Ara e Rexhep Mals', 'RRTR', 'ry-wc-city-select'),
		_x('Bajram Curri', 'RRTR', 'ry-wc-city-select'),
		_x('Begaj', 'RRTR', 'ry-wc-city-select'),
		_x('Corraj', 'RRTR', 'ry-wc-city-select'),
		_x('Demaliaj', 'RRTR', 'ry-wc-city-select'),
		_x('Gosturan', 'RRTR', 'ry-wc-city-select'),
		_x('Hoxhaj', 'RRTR', 'ry-wc-city-select'),
		_x('Kocanaj', 'RRTR', 'ry-wc-city-select'),
		_x('Komuna e Llugajt', 'RRTR', 'ry-wc-city-select'),
		_x('Komuna e Margegaje', 'RRTR', 'ry-wc-city-select'),
		_x('Komuna e Tropojes', 'RRTR', 'ry-wc-city-select'),
		_x('Lagjia e Imeraje', 'RRTR', 'ry-wc-city-select'),
		_x('Markaj', 'RRTR', 'ry-wc-city-select'),
		_x('Mejdan', 'RRTR', 'ry-wc-city-select'),
		_x('Myhejan', 'RRTR', 'ry-wc-city-select'),
		_x('Pac', 'RRTR', 'ry-wc-city-select'),
		_x('Shkolla e Margegaja', 'RRTR', 'ry-wc-city-select'),
		_x('Shoshan', 'RRTR', 'ry-wc-city-select'),
		_x('Sinanaj', 'RRTR', 'ry-wc-city-select'),
		_x('Spitali i Pacit', 'RRTR', 'ry-wc-city-select'),
		_x('Ura e Baram Uks', 'RRTR', 'ry-wc-city-select'),
		_x('Vlad', 'RRTR', 'ry-wc-city-select'),
		_x('Zherke', 'RRTR', 'ry-wc-city-select'),
	],
	'QABE' => [
		_x('Bashkia Berat', 'QABE', 'ry-wc-city-select'),
		_x('Bashkia Kucove', 'QABE', 'ry-wc-city-select'),
		_x('Bashkia Polican', 'QABE', 'ry-wc-city-select'),
		_x('Bashkia Skrapar', 'QABE', 'ry-wc-city-select'),
		_x('Bashkia Ura Vajgurore', 'QABE', 'ry-wc-city-select'),
		_x('Rrethi i Beratit', 'QABE', 'ry-wc-city-select'),
		_x('Rrethi i Kucoves', 'QABE', 'ry-wc-city-select'),
		_x('Rrethi i Skraparit', 'QABE', 'ry-wc-city-select'),
	],
	'QADI' => [
		_x('Bashkia Bulqize', 'QADI', 'ry-wc-city-select'),
		_x('Bashkia Diber', 'QADI', 'ry-wc-city-select'),
		_x('Bashkia Klos', 'QADI', 'ry-wc-city-select'),
		_x('Bashkia Mat', 'QADI', 'ry-wc-city-select'),
		_x('Rrethi i Bulqizes', 'QADI', 'ry-wc-city-select'),
		_x('Rrethi i Dibres', 'QADI', 'ry-wc-city-select'),
		_x('Rrethi i Matit', 'QADI', 'ry-wc-city-select'),
	],
	'QADU' => [
		_x('Bashkia Durres', 'QADU', 'ry-wc-city-select'),
		_x('Bashkia Kruje', 'QADU', 'ry-wc-city-select'),
		_x('Bashkia Shijak', 'QADU', 'ry-wc-city-select'),
		_x('Durres District', 'QADU', 'ry-wc-city-select'),
		_x('Rrethi i Krujes', 'QADU', 'ry-wc-city-select'),
	],
	'QAEL' => [
		_x('Bashkia Belsh', 'QAEL', 'ry-wc-city-select'),
		_x('Bashkia Cerrik', 'QAEL', 'ry-wc-city-select'),
		_x('Bashkia Elbasan', 'QAEL', 'ry-wc-city-select'),
		_x('Bashkia Gramsh', 'QAEL', 'ry-wc-city-select'),
		_x('Bashkia Librazhd', 'QAEL', 'ry-wc-city-select'),
		_x('Bashkia Peqin', 'QAEL', 'ry-wc-city-select'),
		_x('Bashkia Prrenjas', 'QAEL', 'ry-wc-city-select'),
		_x('Rrethi i Gramshit', 'QAEL', 'ry-wc-city-select'),
		_x('Rrethi i Librazhdit', 'QAEL', 'ry-wc-city-select'),
		_x('Rrethi i Peqinit', 'QAEL', 'ry-wc-city-select'),
	],
	'QAFI' => [
		_x('Bashkia Divjake', 'QAFI', 'ry-wc-city-select'),
		_x('Bashkia Fier', 'QAFI', 'ry-wc-city-select'),
		_x('Bashkia Mallakaster', 'QAFI', 'ry-wc-city-select'),
		_x('Bashkia Patos', 'QAFI', 'ry-wc-city-select'),
		_x('Bashkia Roskovec', 'QAFI', 'ry-wc-city-select'),
		_x('Fier', 'QAFI', 'ry-wc-city-select'),
		_x('Rrethi i Lushnjes', 'QAFI', 'ry-wc-city-select'),
		_x('Rrethi i Mallakastres', 'QAFI', 'ry-wc-city-select'),
	],
	'QAGJ' => [
		_x('Bashkia Dropull', 'QAGJ', 'ry-wc-city-select'),
		_x('Bashkia Gjirokaster', 'QAGJ', 'ry-wc-city-select'),
		_x('Bashkia Kelcyre', 'QAGJ', 'ry-wc-city-select'),
		_x('Bashkia Libohove', 'QAGJ', 'ry-wc-city-select'),
		_x('Bashkia Memaliaj', 'QAGJ', 'ry-wc-city-select'),
		_x('Bashkia Permet', 'QAGJ', 'ry-wc-city-select'),
		_x('Bashkia Tepelene', 'QAGJ', 'ry-wc-city-select'),
		_x('Rrethi i Gjirokastres', 'QAGJ', 'ry-wc-city-select'),
		_x('Rrethi i Permetit', 'QAGJ', 'ry-wc-city-select'),
		_x('Rrethi i Tepelenes', 'QAGJ', 'ry-wc-city-select'),
	],
	'QAKO' => [
		_x('Bashkia Devoll', 'QAKO', 'ry-wc-city-select'),
		_x('Bashkia Kolonje', 'QAKO', 'ry-wc-city-select'),
		_x('Bashkia Korce', 'QAKO', 'ry-wc-city-select'),
		_x('Bashkia Maliq', 'QAKO', 'ry-wc-city-select'),
		_x('Bashkia Pogradec', 'QAKO', 'ry-wc-city-select'),
		_x('Bashkia Pustec', 'QAKO', 'ry-wc-city-select'),
		_x('Rrethi i Devollit', 'QAKO', 'ry-wc-city-select'),
		_x('Rrethi i Kolonjes', 'QAKO', 'ry-wc-city-select'),
		_x('Rrethi i Korces', 'QAKO', 'ry-wc-city-select'),
		_x('Rrethi i Pogradecit', 'QAKO', 'ry-wc-city-select'),
	],
	'QAKU' => [
		_x('Bashkia Has', 'QAKU', 'ry-wc-city-select'),
		_x('Bashkia Kukes', 'QAKU', 'ry-wc-city-select'),
		_x('Bashkia Tropoje', 'QAKU', 'ry-wc-city-select'),
		_x('Rrethi i Hasit', 'QAKU', 'ry-wc-city-select'),
		_x('Rrethi i Kukesit', 'QAKU', 'ry-wc-city-select'),
	],
	'QALE' => [
		_x('Bashkia Kurbin', 'QALE', 'ry-wc-city-select'),
		_x('Bashkia Lezhe', 'QALE', 'ry-wc-city-select'),
		_x('Bashkia Mirdite', 'QALE', 'ry-wc-city-select'),
		_x('Lezhe', 'QALE', 'ry-wc-city-select'),
		_x('Rrethi i Kurbinit', 'QALE', 'ry-wc-city-select'),
		_x('Rrethi i Mirdites', 'QALE', 'ry-wc-city-select'),
	],
	'QASH' => [
		_x('Bashkia Fushe Arres', 'QASH', 'ry-wc-city-select'),
		_x('Bashkia Malesi e Madhe', 'QASH', 'ry-wc-city-select'),
		_x('Bashkia Puke', 'QASH', 'ry-wc-city-select'),
		_x('Bashkia Shkoder', 'QASH', 'ry-wc-city-select'),
		_x('Bashkia Vau i Dejes', 'QASH', 'ry-wc-city-select'),
		_x('Rrethi i Malesia e Madhe', 'QASH', 'ry-wc-city-select'),
		_x('Rrethi i Pukes', 'QASH', 'ry-wc-city-select'),
		_x('Rrethi i Shkodres', 'QASH', 'ry-wc-city-select'),
	],
	'QATI' => [
		_x('Bashkia Kamez', 'QATI', 'ry-wc-city-select'),
		_x('Bashkia Kavaje', 'QATI', 'ry-wc-city-select'),
		_x('Bashkia Rrogozhine', 'QATI', 'ry-wc-city-select'),
		_x('Bashkia Tirane', 'QATI', 'ry-wc-city-select'),
		_x('Bashkia Vore', 'QATI', 'ry-wc-city-select'),
		_x('Rrethi i Kavajes', 'QATI', 'ry-wc-city-select'),
		_x('Rrethi i Tiranes', 'QATI', 'ry-wc-city-select'),
	],
	'QAVL' => [
		_x('Bashkia Delvine', 'QAVL', 'ry-wc-city-select'),
		_x('Bashkia Finiq', 'QAVL', 'ry-wc-city-select'),
		_x('Bashkia Himare', 'QAVL', 'ry-wc-city-select'),
		_x('Bashkia Konispol', 'QAVL', 'ry-wc-city-select'),
		_x('Bashkia Sarande', 'QAVL', 'ry-wc-city-select'),
		_x('Bashkia Selenice', 'QAVL', 'ry-wc-city-select'),
		_x('Bashkia Vlore', 'QAVL', 'ry-wc-city-select'),
		_x('Rrethi i Delvines', 'QAVL', 'ry-wc-city-select'),
		_x('Rrethi i Sarandes', 'QAVL', 'ry-wc-city-select'),
		_x('Rrethi i Vlores', 'QAVL', 'ry-wc-city-select'),
	],
	]
];