<?php
/**
 * Republic of Angola places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'AO' => [
	'BEPR' => [
		_x('Ambriz', 'BEPR', 'ry-wc-city-select'),
		_x('Bula Atumba', 'BEPR', 'ry-wc-city-select'),
		_x('Dande Municipality', 'BEPR', 'ry-wc-city-select'),
		_x('Dembos', 'BEPR', 'ry-wc-city-select'),
		_x('Municipio Pango Aluquem', 'BEPR', 'ry-wc-city-select'),
		_x('Nambuangongo Municipality', 'BEPR', 'ry-wc-city-select'),
	],
	'BE' => [
		_x('Baia Farta', 'BE', 'ry-wc-city-select'),
		_x('Benguela', 'BE', 'ry-wc-city-select'),
		_x('Bocoio', 'BE', 'ry-wc-city-select'),
		_x('Caimbambo', 'BE', 'ry-wc-city-select'),
		_x('Catumbela', 'BE', 'ry-wc-city-select'),
		_x('Chongoroi', 'BE', 'ry-wc-city-select'),
		_x('Cubal', 'BE', 'ry-wc-city-select'),
		_x('Ganda', 'BE', 'ry-wc-city-select'),
		_x('Lobito', 'BE', 'ry-wc-city-select'),
		_x('Municipio Balombo', 'BE', 'ry-wc-city-select'),
	],
	'CA' => [
		_x('Belize', 'CA', 'ry-wc-city-select'),
		_x('Buco Zau', 'CA', 'ry-wc-city-select'),
		_x('Cabinda', 'CA', 'ry-wc-city-select'),
		_x('Cacongo', 'CA', 'ry-wc-city-select'),
	],
	'CUNOPR' => [
		_x('Ambaca', 'CUNOPR', 'ry-wc-city-select'),
		_x('Banga', 'CUNOPR', 'ry-wc-city-select'),
		_x('Bolongongo', 'CUNOPR', 'ry-wc-city-select'),
		_x('Cambambe', 'CUNOPR', 'ry-wc-city-select'),
		_x('Cazengo Municipality', 'CUNOPR', 'ry-wc-city-select'),
		_x('Golungo Alto', 'CUNOPR', 'ry-wc-city-select'),
		_x('Lucala', 'CUNOPR', 'ry-wc-city-select'),
		_x('Ngonguembo', 'CUNOPR', 'ry-wc-city-select'),
		_x('Quiculungo', 'CUNOPR', 'ry-wc-city-select'),
		_x('Samba Caju', 'CUNOPR', 'ry-wc-city-select'),
	],
	'CUPR' => [
		_x('Cahama', 'CUPR', 'ry-wc-city-select'),
		_x('Cuanhama', 'CUPR', 'ry-wc-city-select'),
		_x('Curoca', 'CUPR', 'ry-wc-city-select'),
		_x('Cuvelai', 'CUPR', 'ry-wc-city-select'),
		_x('Namacunde', 'CUPR', 'ry-wc-city-select'),
		_x('Ombadja', 'CUPR', 'ry-wc-city-select'),
	],
	'HU' => [
		_x('Bailundo', 'HU', 'ry-wc-city-select'),
		_x('Caala', 'HU', 'ry-wc-city-select'),
		_x('Cachiungo', 'HU', 'ry-wc-city-select'),
		_x('Chicala Cholohanga', 'HU', 'ry-wc-city-select'),
		_x('Chinjenje', 'HU', 'ry-wc-city-select'),
		_x('Ecunha', 'HU', 'ry-wc-city-select'),
		_x('Huambo', 'HU', 'ry-wc-city-select'),
		_x('Londuimbali', 'HU', 'ry-wc-city-select'),
		_x('Longonjo', 'HU', 'ry-wc-city-select'),
		_x('Mungo', 'HU', 'ry-wc-city-select'),
		_x('Ucuma', 'HU', 'ry-wc-city-select'),
	],
	'HUPR' => [
		_x('Caconda', 'HUPR', 'ry-wc-city-select'),
		_x('Cacula', 'HUPR', 'ry-wc-city-select'),
		_x('Caluquembe', 'HUPR', 'ry-wc-city-select'),
		_x('Chibia', 'HUPR', 'ry-wc-city-select'),
		_x('Chicomba', 'HUPR', 'ry-wc-city-select'),
		_x('Chipindo', 'HUPR', 'ry-wc-city-select'),
		_x('Cuvango', 'HUPR', 'ry-wc-city-select'),
		_x('Gambos', 'HUPR', 'ry-wc-city-select'),
		_x('Humpata', 'HUPR', 'ry-wc-city-select'),
		_x('Jamba', 'HUPR', 'ry-wc-city-select'),
		_x('Lubango', 'HUPR', 'ry-wc-city-select'),
		_x('Matala', 'HUPR', 'ry-wc-city-select'),
		_x('Quilengues', 'HUPR', 'ry-wc-city-select'),
		_x('Quipungo', 'HUPR', 'ry-wc-city-select'),
	],
	'KUKU' => [
		_x('Calai', 'KUKU', 'ry-wc-city-select'),
		_x('Cuangar', 'KUKU', 'ry-wc-city-select'),
		_x('Cuchi', 'KUKU', 'ry-wc-city-select'),
		_x('Cuito Cuanavale', 'KUKU', 'ry-wc-city-select'),
		_x('Dirico', 'KUKU', 'ry-wc-city-select'),
		_x('Mavinga', 'KUKU', 'ry-wc-city-select'),
		_x('Menongue', 'KUKU', 'ry-wc-city-select'),
		_x('Nancova', 'KUKU', 'ry-wc-city-select'),
		_x('Rivungo', 'KUKU', 'ry-wc-city-select'),
	],
	'KWSU' => [
		_x('Amboim', 'KWSU', 'ry-wc-city-select'),
		_x('Cassongue', 'KWSU', 'ry-wc-city-select'),
		_x('Cela', 'KWSU', 'ry-wc-city-select'),
		_x('Conda', 'KWSU', 'ry-wc-city-select'),
		_x('Ebo', 'KWSU', 'ry-wc-city-select'),
		_x('Libolo', 'KWSU', 'ry-wc-city-select'),
		_x('Mussende', 'KWSU', 'ry-wc-city-select'),
		_x('Porto Amboim', 'KWSU', 'ry-wc-city-select'),
		_x('Quibala', 'KWSU', 'ry-wc-city-select'),
		_x('Quilenda', 'KWSU', 'ry-wc-city-select'),
		_x('Seles', 'KWSU', 'ry-wc-city-select'),
		_x('Sumbe', 'KWSU', 'ry-wc-city-select'),
	],
	'LUPR' => [
		_x('Belas', 'LUPR', 'ry-wc-city-select'),
		_x('Cacuaco Municipality', 'LUPR', 'ry-wc-city-select'),
		_x('Icolo e Bengo', 'LUPR', 'ry-wc-city-select'),
		_x('Luanda Municipality', 'LUPR', 'ry-wc-city-select'),
		_x('Municipio Cazenga', 'LUPR', 'ry-wc-city-select'),
		_x('Quissama', 'LUPR', 'ry-wc-city-select'),
		_x('Viana', 'LUPR', 'ry-wc-city-select'),
	],
	'LUNOPR' => [
		_x('Cambulo', 'LUNOPR', 'ry-wc-city-select'),
		_x('Capenda Camulemba', 'LUNOPR', 'ry-wc-city-select'),
		_x('Caungula', 'LUNOPR', 'ry-wc-city-select'),
		_x('Chitato', 'LUNOPR', 'ry-wc-city-select'),
		_x('Cuango', 'LUNOPR', 'ry-wc-city-select'),
		_x('Cuilo', 'LUNOPR', 'ry-wc-city-select'),
		_x('Lubalo', 'LUNOPR', 'ry-wc-city-select'),
		_x('Lucapa', 'LUNOPR', 'ry-wc-city-select'),
		_x('Xa-Muteba', 'LUNOPR', 'ry-wc-city-select'),
	],
	'LUSU' => [
		_x('Cacolo', 'LUSU', 'ry-wc-city-select'),
		_x('Dala', 'LUSU', 'ry-wc-city-select'),
		_x('Muconda', 'LUSU', 'ry-wc-city-select'),
		_x('Saurimo', 'LUSU', 'ry-wc-city-select'),
	],
	'MAPR' => [
		_x('Caculama', 'MAPR', 'ry-wc-city-select'),
		_x('Cacuso', 'MAPR', 'ry-wc-city-select'),
		_x('Cahombo', 'MAPR', 'ry-wc-city-select'),
		_x('Calandula', 'MAPR', 'ry-wc-city-select'),
		_x('Cambundi-Catembo', 'MAPR', 'ry-wc-city-select'),
		_x('Cangandala', 'MAPR', 'ry-wc-city-select'),
		_x('Cunda-Dia-Baze', 'MAPR', 'ry-wc-city-select'),
		_x('Kiwaba Nzoji', 'MAPR', 'ry-wc-city-select'),
		_x('Kiwaba Nzoji', 'MAPR', 'ry-wc-city-select'),
		_x('Luquembo', 'MAPR', 'ry-wc-city-select'),
		_x('Malanje Municipality', 'MAPR', 'ry-wc-city-select'),
		_x('Marimba', 'MAPR', 'ry-wc-city-select'),
		_x('Massango', 'MAPR', 'ry-wc-city-select'),
		_x('Quela', 'MAPR', 'ry-wc-city-select'),
		_x('Quirima', 'MAPR', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Alto Zambeze', 'MO', 'ry-wc-city-select'),
		_x('Bundas', 'MO', 'ry-wc-city-select'),
		_x('Camanongue', 'MO', 'ry-wc-city-select'),
		_x('Cameia', 'MO', 'ry-wc-city-select'),
		_x('Leua', 'MO', 'ry-wc-city-select'),
		_x('Luacano', 'MO', 'ry-wc-city-select'),
		_x('Luau', 'MO', 'ry-wc-city-select'),
		_x('Luchazes', 'MO', 'ry-wc-city-select'),
		_x('Luena', 'MO', 'ry-wc-city-select'),
	],
	'NAPR' => [
		_x('Bibala', 'NAPR', 'ry-wc-city-select'),
		_x('Camucuio', 'NAPR', 'ry-wc-city-select'),
		_x('Namibe', 'NAPR', 'ry-wc-city-select'),
		_x('Tombwa', 'NAPR', 'ry-wc-city-select'),
		_x('Virei', 'NAPR', 'ry-wc-city-select'),
	],
	'PRBI' => [
		_x('Andulo', 'PRBI', 'ry-wc-city-select'),
		_x('Barkeol', 'PRBI', 'ry-wc-city-select'),
		_x('Camacupa', 'PRBI', 'ry-wc-city-select'),
		_x('Catabola', 'PRBI', 'ry-wc-city-select'),
		_x('Chinguar', 'PRBI', 'ry-wc-city-select'),
		_x('Chitembo', 'PRBI', 'ry-wc-city-select'),
		_x('Cuemba', 'PRBI', 'ry-wc-city-select'),
		_x('Cuito', 'PRBI', 'ry-wc-city-select'),
		_x('Cunhinga', 'PRBI', 'ry-wc-city-select'),
		_x('Municipio Camacupa', 'PRBI', 'ry-wc-city-select'),
		_x('Nharea', 'PRBI', 'ry-wc-city-select'),
	],
	'PRUI' => [
		_x('Ambuila Municipality', 'PRUI', 'ry-wc-city-select'),
		_x('Bembe', 'PRUI', 'ry-wc-city-select'),
		_x('Buengas', 'PRUI', 'ry-wc-city-select'),
		_x('Bungo', 'PRUI', 'ry-wc-city-select'),
		_x('Cangola', 'PRUI', 'ry-wc-city-select'),
		_x('Damba', 'PRUI', 'ry-wc-city-select'),
		_x('Maquela do Zombo', 'PRUI', 'ry-wc-city-select'),
		_x('Mucaba', 'PRUI', 'ry-wc-city-select'),
		_x('Municipio Bembe', 'PRUI', 'ry-wc-city-select'),
		_x('Negage Municipality', 'PRUI', 'ry-wc-city-select'),
		_x('Puri', 'PRUI', 'ry-wc-city-select'),
		_x('Quimbele', 'PRUI', 'ry-wc-city-select'),
		_x('Quitexe Municipality', 'PRUI', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRUI', 'ry-wc-city-select'),
		_x('Sanza Pombo', 'PRUI', 'ry-wc-city-select'),
		_x('Songo', 'PRUI', 'ry-wc-city-select'),
		_x('Uige Municipality', 'PRUI', 'ry-wc-city-select'),
	],
	'ZA' => [
		_x('Cuimba', 'ZA', 'ry-wc-city-select'),
		_x('Mbanza Congo', 'ZA', 'ry-wc-city-select'),
		_x('Noqui', 'ZA', 'ry-wc-city-select'),
		_x('Nzeto', 'ZA', 'ry-wc-city-select'),
		_x('Soyo', 'ZA', 'ry-wc-city-select'),
		_x('Tomboco', 'ZA', 'ry-wc-city-select'),
	],
	]
];