<?php
/**
 * Argentine Republic places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'AR' => [
	'CO' => [
		_x('Constitucion', 'CO', 'ry-wc-city-select'),
		_x('Monserrat', 'CO', 'ry-wc-city-select'),
		_x('Puerto Madero', 'CO', 'ry-wc-city-select'),
		_x('Retiro', 'CO', 'ry-wc-city-select'),
		_x('San Nicolas', 'CO', 'ry-wc-city-select'),
		_x('San Telmo', 'CO', 'ry-wc-city-select'),
	],
	'CO2' => [
		_x('Floresta', 'CO2', 'ry-wc-city-select'),
		_x('Monte Castro', 'CO2', 'ry-wc-city-select'),
		_x('Velez Sarsfield', 'CO2', 'ry-wc-city-select'),
		_x('Versalles', 'CO2', 'ry-wc-city-select'),
		_x('Villa Luro', 'CO2', 'ry-wc-city-select'),
		_x('Villa Real', 'CO2', 'ry-wc-city-select'),
	],
	'CO3' => [
		_x('Villa Del Parque', 'CO3', 'ry-wc-city-select'),
		_x('Villa Devoto', 'CO3', 'ry-wc-city-select'),
		_x('Villa Gral. Mitre', 'CO3', 'ry-wc-city-select'),
		_x('Villa Santa Rita', 'CO3', 'ry-wc-city-select'),
	],
	'CO4' => [
		_x('Coghlan', 'CO4', 'ry-wc-city-select'),
		_x('Saavedra', 'CO4', 'ry-wc-city-select'),
		_x('Villa Pueyrredon', 'CO4', 'ry-wc-city-select'),
		_x('Villa Urquiza', 'CO4', 'ry-wc-city-select'),
	],
	'CO5' => [
		_x('Belgrano', 'CO5', 'ry-wc-city-select'),
		_x('Colegiales', 'CO5', 'ry-wc-city-select'),
		_x('Nunez', 'CO5', 'ry-wc-city-select'),
	],
	'CO6' => [
		_x('Palermo', 'CO6', 'ry-wc-city-select'),
	],
	'CO7' => [
		_x('Agronomia', 'CO7', 'ry-wc-city-select'),
		_x('Chacarita', 'CO7', 'ry-wc-city-select'),
		_x('Parque Chas', 'CO7', 'ry-wc-city-select'),
		_x('Paternal', 'CO7', 'ry-wc-city-select'),
		_x('Villa Crespo', 'CO7', 'ry-wc-city-select'),
		_x('Villa Ortuzar', 'CO7', 'ry-wc-city-select'),
	],
	'CO8' => [
		_x('Recoleta', 'CO8', 'ry-wc-city-select'),
	],
	'CO9' => [
		_x('Balvanera', 'CO9', 'ry-wc-city-select'),
		_x('San Cristobal', 'CO9', 'ry-wc-city-select'),
	],
	'CO10' => [
		_x('Barracas', 'CO10', 'ry-wc-city-select'),
		_x('Boca', 'CO10', 'ry-wc-city-select'),
		_x('Nueva Pompeya', 'CO10', 'ry-wc-city-select'),
		_x('Parque Patricios', 'CO10', 'ry-wc-city-select'),
	],
	'CO11' => [
		_x('Almagro', 'CO11', 'ry-wc-city-select'),
		_x('Boedo', 'CO11', 'ry-wc-city-select'),
	],
	'CO12' => [
		_x('Caballito', 'CO12', 'ry-wc-city-select'),
	],
	'CO13' => [
		_x('Flores', 'CO13', 'ry-wc-city-select'),
		_x('Parque Chacabuco', 'CO13', 'ry-wc-city-select'),
	],
	'CO14' => [
		_x('Villa Lugano', 'CO14', 'ry-wc-city-select'),
		_x('Villa Riachuelo', 'CO14', 'ry-wc-city-select'),
		_x('Villa Soldati', 'CO14', 'ry-wc-city-select'),
	],
	'CO15' => [
		_x('Liniers', 'CO15', 'ry-wc-city-select'),
		_x('Mataderos', 'CO15', 'ry-wc-city-select'),
		_x('Parque Avellaneda', 'CO15', 'ry-wc-city-select'),
	],
	'DEBA' => [
		_x('San Carlos de Bariloche', 'DEBA', 'ry-wc-city-select'),
	],
	'DECO' => [
		_x('San Jose (Entre Rios)', 'DECO', 'ry-wc-city-select'),
	],
	'DENO' => [
		_x('Caviahue-Copahue', 'DENO', 'ry-wc-city-select'),
	],
	'RODE' => [
		_x('Centro Municipal De Distrito Norte Vill', 'RODE', 'ry-wc-city-select'),
	],
	'BUAI' => [
		_x('Partido de Adolfo Alsina', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Adolfo Gonzalez Chaves', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Alberti', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Almirante Brown', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Arrecifes', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Avellaneda', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Ayacucho', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Azul', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Bahia Blanca', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Balcarce', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Baradero', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Benito Juarez', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Berazategui', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Berisso', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Bolivar', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Bragado', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Brandsen', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Campana', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Canuelas', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Capitan Sarmiento', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Carlos Casares', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Carlos Tejedor', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Carmen de Areco', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Castelli', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Chacabuco', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Chascomus', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Chivilcoy', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Colon', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Coronel Dorrego', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Coronel Pringles', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Coronel Rosales', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Coronel Suarez', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Daireaux', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Dolores', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Ensenada', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Escobar', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Esteban Echeverria', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Exaltacion de la Cruz', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Ezeiza', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Florencio Varela', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Florentino Ameghino', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Alvarado', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Alvear', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Arenales', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Belgrano', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Guido', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General La Madrid', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Las Heras', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Lavalle', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Madariaga', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Paz', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Pinto', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Pueyrredon', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Rodriguez', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General San Martin', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Viamonte', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de General Villegas', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Guamini', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Hipolito Yrigoyen', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Hurlingham', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Ituzaingo', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Jose C. Paz', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Junin', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de La Costa', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de La Matanza', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de La Plata', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Lanus', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Laprida', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Las Flores', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Leandro N. Alem', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Lezama', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Lincoln', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Loberia', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Lobos', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Lomas de Zamora', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Lujan', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Magdalena', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Maipu', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Malvinas Argentinas', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Mar Chiquita', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Marcos Paz', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Mercedes', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Merlo', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Monte', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Monte Hermoso', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Moreno', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Moron', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Navarro', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Necochea', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Nueve de Julio', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Olavarria', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Patagones', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Pehuajo', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Pellegrini', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Pergamino', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Pila', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Pilar', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Pinamar', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Presidente Peron', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Puan', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Punta Indio', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Quilmes', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Ramallo', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Rauch', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Rivadavia', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Rojas', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Roque Perez', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Saavedra', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Saladillo', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Salliquelo', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Salto', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de San Andres de Giles', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de San Cayetano', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de San Fernando', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de San Isidro', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de San Miguel', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de San Nicolas', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de San Pedro', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de San Vicente', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Suipacha', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Tandil', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Tapalque', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Tigre', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Tordillo', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Tornquist', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Trenque Lauquen', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Tres Arroyos', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Tres Lomas', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Tres de Febrero', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Veinticinco de Mayo', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Vicente Lopez', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Villa Gesell', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Villarino', 'BUAI', 'ry-wc-city-select'),
		_x('Partido de Zarate', 'BUAI', 'ry-wc-city-select'),
		_x('San Antonio de Areco', 'BUAI', 'ry-wc-city-select'),
	],
	'CAPR' => [
		_x('Departamento de Ambato', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Ancasti', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Andalgala', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Antofagasta de la Sierra', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Belen', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Capayan', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de El Alto', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Fray Mamerto Esquiu', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de La Paz', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Paclin', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Poman', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Santa Maria', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Santa Rosa', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Tinogasta', 'CAPR', 'ry-wc-city-select'),
		_x('Departamento de Valle Viejo', 'CAPR', 'ry-wc-city-select'),
	],
	'CHPR' => [
		_x('Chacabuco', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Almirante Brown', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Bermejo', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Comandante Fernandez', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Doce de Octubre', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Dos de Abril', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de General Belgrano', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de General Donovan', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de General Gueemes', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Independencia', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Libertad', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Libertador General San M', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Maipu', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Mayor Luis J. Fontana', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Nueve de Julio', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de OHiggins', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Presidencia de la Plaza', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Quitilipi', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de San Fernando', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de San Lorenzo', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Sargento Cabral', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento de Tapenaga', 'CHPR', 'ry-wc-city-select'),
		_x('Departamento del Primero de Mayo', 'CHPR', 'ry-wc-city-select'),
		_x('Fray Justo Santa Maria de Oro', 'CHPR', 'ry-wc-city-select'),
		_x('Veinticinco de Mayo', 'CHPR', 'ry-wc-city-select'),
	],
	'CHPR2' => [
		_x('Departamento de Biedma', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Cushamen', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Escalante', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Florentino Ameghino', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Futaleufu', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Gaiman', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Gastre', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Languineo', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Martires', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Paso de Indios', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Rawson', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Rio Senguerr', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Sarmiento', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Tehuelches', 'CHPR2', 'ry-wc-city-select'),
		_x('Departamento de Telsen', 'CHPR2', 'ry-wc-city-select'),
	],
	'COPR' => [
		_x('Departamento de Calamuchita', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Colon', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Cruz del Eje', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de General Roca', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de General San Martin', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Ischilin', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Juarez Celman', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Marcos Juarez', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Minas', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Pocho', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Presidente Roque Saenz P', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Punilla', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Rio Cuarto', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Rio Primero', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Rio Seco', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Rio Segundo', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de San Alberto', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de San Javier', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de San Justo', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Santa Maria', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Sobremonte', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Tercero Arriba', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Totoral', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Tulumba', 'COPR', 'ry-wc-city-select'),
		_x('Departamento de Union', 'COPR', 'ry-wc-city-select'),
	],
	'COPR2' => [
		_x('Departamento de Bella Vista', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Beron de Astrada', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Concepcion', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Curuzu Cuatia', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Empedrado', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Esquina', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de General Alvear', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de General Paz', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Goya', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Itati', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Ituzaingo', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Lavalle', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Mburucuya', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Mercedes', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Monte Caseros', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Paso de los Libres', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Saladas', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de San Cosme', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de San Luis del Palmar', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de San Martin', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de San Miguel', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de San Roque', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Santo Tome', 'COPR2', 'ry-wc-city-select'),
		_x('Departamento de Sauce', 'COPR2', 'ry-wc-city-select'),
	],
	'ENRIPR' => [
		_x('Departamento de Concordia', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Diamante', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Federacion', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Federal', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Feliciano', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Gualeguay', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Gualeguaychu', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Islas del Ibicuy', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de La Paz', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Nogoya', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Parana', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de San Salvador', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Tala', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Uruguay', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Victoria', 'ENRIPR', 'ry-wc-city-select'),
		_x('Departamento de Villaguay', 'ENRIPR', 'ry-wc-city-select'),
	],
	'FOPR' => [
		_x('Departamento de Bermejo', 'FOPR', 'ry-wc-city-select'),
		_x('Departamento de Formosa', 'FOPR', 'ry-wc-city-select'),
		_x('Departamento de Laishi', 'FOPR', 'ry-wc-city-select'),
		_x('Departamento de Matacos', 'FOPR', 'ry-wc-city-select'),
		_x('Departamento de Patino', 'FOPR', 'ry-wc-city-select'),
		_x('Departamento de Pilagas', 'FOPR', 'ry-wc-city-select'),
		_x('Departamento de Pilcomayo', 'FOPR', 'ry-wc-city-select'),
		_x('Departamento de Pirane', 'FOPR', 'ry-wc-city-select'),
		_x('Departamento de Ramon Lista', 'FOPR', 'ry-wc-city-select'),
	],
	'JUPR' => [
		_x('Departamento de Cochinoca', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Doctor Manuel Belgrano', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de El Carmen', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Humahuaca', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Ledesma', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Palpala', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Rinconada', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de San Antonio', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de San Pedro', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Santa Barbara', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Santa Catalina', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Susques', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Tilcara', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Tumbaya', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Valle Grande', 'JUPR', 'ry-wc-city-select'),
		_x('Departamento de Yavi', 'JUPR', 'ry-wc-city-select'),
	],
	'PAPR' => [
		_x('Departamento de Atreuco', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Caleu-Caleu', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Catrilo', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Chalileo', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Chapaleufu', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Chical-Co', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Conhelo', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Curaco', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Guatrache', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Hucal', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Lihuel-Calel', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Limay Mahuida', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Loventue', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Maraco', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Puelen', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Quemu Quemu', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Rancul', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Realico', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Toay', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Trenel', 'PAPR', 'ry-wc-city-select'),
		_x('Departamento de Utracan', 'PAPR', 'ry-wc-city-select'),
	],
	'RIPR' => [
		_x('Departamento de Arauco', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Castro Barros', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Chamical', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Chilecito', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Coronel Felipe Varela', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Famatina', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de General Angel Penaloza', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de General Belgrano', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de General Juan F. Quiroga', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de General Lamadrid', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de General Ocampo', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de General San Martin', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Independencia', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Rosario Vera Penaloza', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de San Blas de los Sauces', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Sanagasta', 'RIPR', 'ry-wc-city-select'),
		_x('Departamento de Vinchina', 'RIPR', 'ry-wc-city-select'),
	],
	'MEPR' => [
		_x('Departamento de Capital', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de General Alvear', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Godoy Cruz', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Guaymallen', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Junin', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de La Paz', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Las Heras', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Lavalle', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Lujan', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Maipu', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Malarguee', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Rivadavia', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de San Carlos', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de San Martin', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de San Rafael', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Santa Rosa', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Tunuyan', 'MEPR', 'ry-wc-city-select'),
		_x('Departamento de Tupungato', 'MEPR', 'ry-wc-city-select'),
	],
	'MIPR' => [
		_x('Departamento de Apostoles', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Cainguas', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Candelaria', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Concepcion de la Sierra', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Eldorado', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de General Manuel Belgrano', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Guarani', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Iguazu', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Leandro N. Alem', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Libertador General San M', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Montecarlo', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Obera', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de San Ignacio', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de San Javier', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de San Pedro', 'MIPR', 'ry-wc-city-select'),
		_x('Departamento de Veinticinco de Mayo', 'MIPR', 'ry-wc-city-select'),
	],
	'NEPR' => [
		_x('Departamento de Alumine', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Anelo', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Catan-Lil', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Chos-Malal', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Collon-Cura', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Confluencia', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Huiliches', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Lacar', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Loncopue', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Los Lagos', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Minas', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Pehuenches', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Picun Leufu', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Picunches', 'NEPR', 'ry-wc-city-select'),
		_x('Departamento de Zapala', 'NEPR', 'ry-wc-city-select'),
	],
	'RINEPR' => [
		_x('Departamento de Adolfo Alsina', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de Avellaneda', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de Conesa', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de El Cuy', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de General Roca', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de Norquinco', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de Nueve de Julio', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de Pichi Mahuida', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de Pilcaniyeu', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de San Antonio', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de Valcheta', 'RINEPR', 'ry-wc-city-select'),
		_x('Departamento de Veinticinco de Mayo', 'RINEPR', 'ry-wc-city-select'),
	],
	'SAPR' => [
		_x('Cafayate', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento Capital', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Anta', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Cachi', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Cerrillos', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Chicoana', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de General Gueemes', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de General Jose de San Mart', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Guachipas', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Iruya', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de La Poma', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de La Vina', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Los Andes', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Metan', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Molinos', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Oran', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Rivadavia', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Rosario de Lerma', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Rosario de la Frontera', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de San Carlos', 'SAPR', 'ry-wc-city-select'),
		_x('Departamento de Santa Victoria', 'SAPR', 'ry-wc-city-select'),
		_x('La Caldera', 'SAPR', 'ry-wc-city-select'),
		_x('La Candelaria', 'SAPR', 'ry-wc-city-select'),
	],
	'SAJUPR' => [
		_x('Departamento de Albardon', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Angaco', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Calingasta', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Caucete', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Chimbas', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Iglesia', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Jachal', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Nueve de Julio', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Pocito', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Rawson', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Rivadavia', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de San Martin', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Santa Lucia', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Sarmiento', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Ullum', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Valle Fertil', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Veinticinco de Mayo', 'SAJUPR', 'ry-wc-city-select'),
		_x('Departamento de Zonda', 'SAJUPR', 'ry-wc-city-select'),
	],
	'SALUPR' => [
		_x('Coronel Pringles', 'SALUPR', 'ry-wc-city-select'),
		_x('Departamento de Ayacucho', 'SALUPR', 'ry-wc-city-select'),
		_x('Departamento de Belgrano', 'SALUPR', 'ry-wc-city-select'),
		_x('Departamento de Chacabuco', 'SALUPR', 'ry-wc-city-select'),
		_x('Departamento de General Pedernera', 'SALUPR', 'ry-wc-city-select'),
		_x('Departamento de Gobernador Vicente Dupuy', 'SALUPR', 'ry-wc-city-select'),
		_x('Departamento de Junin', 'SALUPR', 'ry-wc-city-select'),
		_x('Departamento de Libertador General San M', 'SALUPR', 'ry-wc-city-select'),
		_x('Juan Martin de Pueyrredon', 'SALUPR', 'ry-wc-city-select'),
	],
	'SACRPR' => [
		_x('Departamento de Corpen Aike', 'SACRPR', 'ry-wc-city-select'),
		_x('Departamento de Deseado', 'SACRPR', 'ry-wc-city-select'),
		_x('Departamento de Gueer Aike', 'SACRPR', 'ry-wc-city-select'),
		_x('Departamento de Lago Argentino', 'SACRPR', 'ry-wc-city-select'),
		_x('Departamento de Lago Buenos Aires', 'SACRPR', 'ry-wc-city-select'),
		_x('Departamento de Magallanes', 'SACRPR', 'ry-wc-city-select'),
		_x('Departamento de Rio Chico', 'SACRPR', 'ry-wc-city-select'),
	],
	'SAPR2' => [
		_x('Departamento de Belgrano', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de Caseros', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de Castellanos', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de Constitucion', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de La Capital', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de Nueve de Julio', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de San Cristobal', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de San Javier', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de San Justo', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de San Lorenzo', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de San Martin', 'SAPR2', 'ry-wc-city-select'),
		_x('Departamento de Vera', 'SAPR2', 'ry-wc-city-select'),
		_x('Garay Department', 'SAPR2', 'ry-wc-city-select'),
		_x('General Lopez Department', 'SAPR2', 'ry-wc-city-select'),
		_x('General Obligado Department', 'SAPR2', 'ry-wc-city-select'),
		_x('Iriondo Department', 'SAPR2', 'ry-wc-city-select'),
		_x('Las Colonias Department', 'SAPR2', 'ry-wc-city-select'),
		_x('San Jeronimo Department', 'SAPR2', 'ry-wc-city-select'),
	],
	'SADEESPR' => [
		_x('Departamento de Aguirre', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Alberdi', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Atamisqui', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Avellaneda', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Banda', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Belgrano', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Choya', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Copo', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Figueroa', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de General Taboada', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Guasayan', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Jimenez', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Juan F. Ibarra', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Loreto', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Mitre', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Moreno', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Ojo de Agua', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Pellegrini', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Quebrachos', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Rio Hondo', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Rivadavia', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Robles', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Salavina', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de San Martin', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Sarmiento', 'SADEESPR', 'ry-wc-city-select'),
		_x('Departamento de Silipica', 'SADEESPR', 'ry-wc-city-select'),
	],
	'TIDEFUPR' => [
		_x('Antartida Argentina', 'TIDEFUPR', 'ry-wc-city-select'),
		_x('Departamento de Rio Grande', 'TIDEFUPR', 'ry-wc-city-select'),
		_x('Departamento de Ushuaia', 'TIDEFUPR', 'ry-wc-city-select'),
		_x('Islas del Atlantico Sur', 'TIDEFUPR', 'ry-wc-city-select'),
		_x('Tolhuin', 'TIDEFUPR', 'ry-wc-city-select'),
	],
	'TUPR' => [
		_x('Departamento de Burruyacu', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Capital', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Chicligasta', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Cruz Alta', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Famailla', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Graneros', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Juan B. Alberdi', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de La Cocha', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Leales', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Lules', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Monteros', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Rio Chico', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Simoca', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Tafi Viejo', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Tafi del Valle', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Trancas', 'TUPR', 'ry-wc-city-select'),
		_x('Departamento de Yerba Buena', 'TUPR', 'ry-wc-city-select'),
	],
	]
];