<?php
/**
 * Commonwealth of Australia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'AU' => [
	'NOTE' => [
		_x('Alice Springs', 'NOTE', 'ry-wc-city-select'),
		_x('Barkly', 'NOTE', 'ry-wc-city-select'),
		_x('Belyuen', 'NOTE', 'ry-wc-city-select'),
		_x('Central Desert', 'NOTE', 'ry-wc-city-select'),
		_x('Coomalie', 'NOTE', 'ry-wc-city-select'),
		_x('Darwin', 'NOTE', 'ry-wc-city-select'),
		_x('East Arnhem', 'NOTE', 'ry-wc-city-select'),
		_x('Katherine', 'NOTE', 'ry-wc-city-select'),
		_x('Litchfield', 'NOTE', 'ry-wc-city-select'),
		_x('MacDonnell', 'NOTE', 'ry-wc-city-select'),
		_x('Palmerston', 'NOTE', 'ry-wc-city-select'),
		_x('Roper Gulf', 'NOTE', 'ry-wc-city-select'),
		_x('Tiwi Islands', 'NOTE', 'ry-wc-city-select'),
		_x('Victoria Daly', 'NOTE', 'ry-wc-city-select'),
		_x('Wagait', 'NOTE', 'ry-wc-city-select'),
		_x('West Arnhem', 'NOTE', 'ry-wc-city-select'),
		_x('West Daly', 'NOTE', 'ry-wc-city-select'),
	],
	'STNESOWA' => [
		_x('Albury Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Armidale Regional', 'STNESOWA', 'ry-wc-city-select'),
		_x('Ballina', 'STNESOWA', 'ry-wc-city-select'),
		_x('Balranald', 'STNESOWA', 'ry-wc-city-select'),
		_x('Bathurst Regional', 'STNESOWA', 'ry-wc-city-select'),
		_x('Bega Valley', 'STNESOWA', 'ry-wc-city-select'),
		_x('Bellingen', 'STNESOWA', 'ry-wc-city-select'),
		_x('Berrigan', 'STNESOWA', 'ry-wc-city-select'),
		_x('Blacktown', 'STNESOWA', 'ry-wc-city-select'),
		_x('Bland', 'STNESOWA', 'ry-wc-city-select'),
		_x('Blayney', 'STNESOWA', 'ry-wc-city-select'),
		_x('Blue Mountains Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Bogan', 'STNESOWA', 'ry-wc-city-select'),
		_x('Botany Bay', 'STNESOWA', 'ry-wc-city-select'),
		_x('Bourke', 'STNESOWA', 'ry-wc-city-select'),
		_x('Brewarrina', 'STNESOWA', 'ry-wc-city-select'),
		_x('Broken Hill Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Burwood', 'STNESOWA', 'ry-wc-city-select'),
		_x('Byron Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Cabonne', 'STNESOWA', 'ry-wc-city-select'),
		_x('Camden', 'STNESOWA', 'ry-wc-city-select'),
		_x('Campbelltown Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Canada Bay', 'STNESOWA', 'ry-wc-city-select'),
		_x('Canterbury-Bankstown', 'STNESOWA', 'ry-wc-city-select'),
		_x('Carrathool', 'STNESOWA', 'ry-wc-city-select'),
		_x('Central Coast', 'STNESOWA', 'ry-wc-city-select'),
		_x('Central Darling', 'STNESOWA', 'ry-wc-city-select'),
		_x('Cessnock', 'STNESOWA', 'ry-wc-city-select'),
		_x('City of Sydney', 'STNESOWA', 'ry-wc-city-select'),
		_x('Clarence Valley', 'STNESOWA', 'ry-wc-city-select'),
		_x('Cobar', 'STNESOWA', 'ry-wc-city-select'),
		_x('Coffs Harbour', 'STNESOWA', 'ry-wc-city-select'),
		_x('Coolamon', 'STNESOWA', 'ry-wc-city-select'),
		_x('Coonamble', 'STNESOWA', 'ry-wc-city-select'),
		_x('Cowra', 'STNESOWA', 'ry-wc-city-select'),
		_x('Cumberland', 'STNESOWA', 'ry-wc-city-select'),
		_x('Dungog', 'STNESOWA', 'ry-wc-city-select'),
		_x('Edward River', 'STNESOWA', 'ry-wc-city-select'),
		_x('Eurobodalla', 'STNESOWA', 'ry-wc-city-select'),
		_x('Fairfield', 'STNESOWA', 'ry-wc-city-select'),
		_x('Federation', 'STNESOWA', 'ry-wc-city-select'),
		_x('Forbes', 'STNESOWA', 'ry-wc-city-select'),
		_x('Georges River', 'STNESOWA', 'ry-wc-city-select'),
		_x('Gilgandra', 'STNESOWA', 'ry-wc-city-select'),
		_x('Glen Innes Severn', 'STNESOWA', 'ry-wc-city-select'),
		_x('Goulburn Mulwaree', 'STNESOWA', 'ry-wc-city-select'),
		_x('Greater Hume Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Griffith', 'STNESOWA', 'ry-wc-city-select'),
		_x('Gundagai', 'STNESOWA', 'ry-wc-city-select'),
		_x('Gunnedah', 'STNESOWA', 'ry-wc-city-select'),
		_x('Gwydir', 'STNESOWA', 'ry-wc-city-select'),
		_x('Hawkesbury', 'STNESOWA', 'ry-wc-city-select'),
		_x('Hay', 'STNESOWA', 'ry-wc-city-select'),
		_x('Hilltops', 'STNESOWA', 'ry-wc-city-select'),
		_x('Hornsby Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Hunters Hill', 'STNESOWA', 'ry-wc-city-select'),
		_x('Inner West', 'STNESOWA', 'ry-wc-city-select'),
		_x('Inverell', 'STNESOWA', 'ry-wc-city-select'),
		_x('Junee', 'STNESOWA', 'ry-wc-city-select'),
		_x('Kempsey', 'STNESOWA', 'ry-wc-city-select'),
		_x('Kiama', 'STNESOWA', 'ry-wc-city-select'),
		_x('Ku-ring-gai', 'STNESOWA', 'ry-wc-city-select'),
		_x('Kyogle', 'STNESOWA', 'ry-wc-city-select'),
		_x('Lachlan', 'STNESOWA', 'ry-wc-city-select'),
		_x('Lake Macquarie Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Lane Cove', 'STNESOWA', 'ry-wc-city-select'),
		_x('Leeton', 'STNESOWA', 'ry-wc-city-select'),
		_x('Lismore Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Lithgow', 'STNESOWA', 'ry-wc-city-select'),
		_x('Liverpool', 'STNESOWA', 'ry-wc-city-select'),
		_x('Liverpool Plains', 'STNESOWA', 'ry-wc-city-select'),
		_x('Lockhart', 'STNESOWA', 'ry-wc-city-select'),
		_x('Maitland Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Mid-Coast', 'STNESOWA', 'ry-wc-city-select'),
		_x('Mid-Western Regional', 'STNESOWA', 'ry-wc-city-select'),
		_x('Moree Plains', 'STNESOWA', 'ry-wc-city-select'),
		_x('Mosman', 'STNESOWA', 'ry-wc-city-select'),
		_x('Murray River', 'STNESOWA', 'ry-wc-city-select'),
		_x('Murrumbidgee', 'STNESOWA', 'ry-wc-city-select'),
		_x('Muswellbrook', 'STNESOWA', 'ry-wc-city-select'),
		_x('Nambucca Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Narrabri', 'STNESOWA', 'ry-wc-city-select'),
		_x('Narrandera', 'STNESOWA', 'ry-wc-city-select'),
		_x('Narromine', 'STNESOWA', 'ry-wc-city-select'),
		_x('Newcastle', 'STNESOWA', 'ry-wc-city-select'),
		_x('North Sydney', 'STNESOWA', 'ry-wc-city-select'),
		_x('Northern Beaches', 'STNESOWA', 'ry-wc-city-select'),
		_x('Oberon', 'STNESOWA', 'ry-wc-city-select'),
		_x('Orange Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Parkes', 'STNESOWA', 'ry-wc-city-select'),
		_x('Parramatta', 'STNESOWA', 'ry-wc-city-select'),
		_x('Penrith Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Port Macquarie-Hastings', 'STNESOWA', 'ry-wc-city-select'),
		_x('Port Stephens Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Queanbeyan-Palerang Regional', 'STNESOWA', 'ry-wc-city-select'),
		_x('Randwick', 'STNESOWA', 'ry-wc-city-select'),
		_x('Richmond Valley', 'STNESOWA', 'ry-wc-city-select'),
		_x('Rockdale', 'STNESOWA', 'ry-wc-city-select'),
		_x('Ryde', 'STNESOWA', 'ry-wc-city-select'),
		_x('Shellharbour', 'STNESOWA', 'ry-wc-city-select'),
		_x('Shoalhaven Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Singleton', 'STNESOWA', 'ry-wc-city-select'),
		_x('Snowy Monaro Regional', 'STNESOWA', 'ry-wc-city-select'),
		_x('Snowy Valleys', 'STNESOWA', 'ry-wc-city-select'),
		_x('Strathfield', 'STNESOWA', 'ry-wc-city-select'),
		_x('Sutherland Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Tamworth Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Temora Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('Tenterfield Municipality', 'STNESOWA', 'ry-wc-city-select'),
		_x('The Hills Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Tweed', 'STNESOWA', 'ry-wc-city-select'),
		_x('Upper Hunter Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Upper Lachlan Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Uralla', 'STNESOWA', 'ry-wc-city-select'),
		_x('Wagga Wagga', 'STNESOWA', 'ry-wc-city-select'),
		_x('Walcha', 'STNESOWA', 'ry-wc-city-select'),
		_x('Walgett', 'STNESOWA', 'ry-wc-city-select'),
		_x('Warren Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Warrumbungle Shire', 'STNESOWA', 'ry-wc-city-select'),
		_x('Waverley', 'STNESOWA', 'ry-wc-city-select'),
		_x('Weddin', 'STNESOWA', 'ry-wc-city-select'),
		_x('Wentworth', 'STNESOWA', 'ry-wc-city-select'),
		_x('Western Plains Regional', 'STNESOWA', 'ry-wc-city-select'),
		_x('Willoughby', 'STNESOWA', 'ry-wc-city-select'),
		_x('Wingecarribee', 'STNESOWA', 'ry-wc-city-select'),
		_x('Wollondilly', 'STNESOWA', 'ry-wc-city-select'),
		_x('Wollongong', 'STNESOWA', 'ry-wc-city-select'),
		_x('Woollahra', 'STNESOWA', 'ry-wc-city-select'),
		_x('Yass Valley', 'STNESOWA', 'ry-wc-city-select'),
	],
	'STQU' => [
		_x('Aurukun', 'STQU', 'ry-wc-city-select'),
		_x('Balonne Shire', 'STQU', 'ry-wc-city-select'),
		_x('Banana', 'STQU', 'ry-wc-city-select'),
		_x('Barcaldine', 'STQU', 'ry-wc-city-select'),
		_x('Barcoo', 'STQU', 'ry-wc-city-select'),
		_x('Blackall Tambo', 'STQU', 'ry-wc-city-select'),
		_x('Boulia', 'STQU', 'ry-wc-city-select'),
		_x('Brisbane', 'STQU', 'ry-wc-city-select'),
		_x('Bulloo', 'STQU', 'ry-wc-city-select'),
		_x('Bundaberg', 'STQU', 'ry-wc-city-select'),
		_x('Burdekin', 'STQU', 'ry-wc-city-select'),
		_x('Burke', 'STQU', 'ry-wc-city-select'),
		_x('Cairns', 'STQU', 'ry-wc-city-select'),
		_x('Carpentaria', 'STQU', 'ry-wc-city-select'),
		_x('Cassowary Coast', 'STQU', 'ry-wc-city-select'),
		_x('Central Highlands', 'STQU', 'ry-wc-city-select'),
		_x('Charters Towers', 'STQU', 'ry-wc-city-select'),
		_x('Cherbourg', 'STQU', 'ry-wc-city-select'),
		_x('Cloncurry', 'STQU', 'ry-wc-city-select'),
		_x('Cook Shire', 'STQU', 'ry-wc-city-select'),
		_x('Croydon', 'STQU', 'ry-wc-city-select'),
		_x('Diamantina', 'STQU', 'ry-wc-city-select'),
		_x('Doomadgee', 'STQU', 'ry-wc-city-select'),
		_x('Douglas', 'STQU', 'ry-wc-city-select'),
		_x('Etheridge', 'STQU', 'ry-wc-city-select'),
		_x('Flinders', 'STQU', 'ry-wc-city-select'),
		_x('Fraser Coast', 'STQU', 'ry-wc-city-select'),
		_x('Gladstone', 'STQU', 'ry-wc-city-select'),
		_x('Gold Coast', 'STQU', 'ry-wc-city-select'),
		_x('Goondiwindi', 'STQU', 'ry-wc-city-select'),
		_x('Gympie Regional Council', 'STQU', 'ry-wc-city-select'),
		_x('Hinchinbrook', 'STQU', 'ry-wc-city-select'),
		_x('Hope Vale', 'STQU', 'ry-wc-city-select'),
		_x('Ipswich', 'STQU', 'ry-wc-city-select'),
		_x('Isaac', 'STQU', 'ry-wc-city-select'),
		_x('Kowanyama', 'STQU', 'ry-wc-city-select'),
		_x('Livingstone', 'STQU', 'ry-wc-city-select'),
		_x('Lockhart River', 'STQU', 'ry-wc-city-select'),
		_x('Lockyer Valley', 'STQU', 'ry-wc-city-select'),
		_x('Logan', 'STQU', 'ry-wc-city-select'),
		_x('Longreach', 'STQU', 'ry-wc-city-select'),
		_x('Mackay', 'STQU', 'ry-wc-city-select'),
		_x('Mapoon', 'STQU', 'ry-wc-city-select'),
		_x('Maranoa', 'STQU', 'ry-wc-city-select'),
		_x('Mareeba', 'STQU', 'ry-wc-city-select'),
		_x('McKinlay', 'STQU', 'ry-wc-city-select'),
		_x('Moreton Bay', 'STQU', 'ry-wc-city-select'),
		_x('Mornington', 'STQU', 'ry-wc-city-select'),
		_x('Mount Isa', 'STQU', 'ry-wc-city-select'),
		_x('Murweh', 'STQU', 'ry-wc-city-select'),
		_x('Napranum', 'STQU', 'ry-wc-city-select'),
		_x('Noosa', 'STQU', 'ry-wc-city-select'),
		_x('North Burnett', 'STQU', 'ry-wc-city-select'),
		_x('Northern Peninsula Area', 'STQU', 'ry-wc-city-select'),
		_x('Palm Island', 'STQU', 'ry-wc-city-select'),
		_x('Paroo', 'STQU', 'ry-wc-city-select'),
		_x('Pormpuraaw', 'STQU', 'ry-wc-city-select'),
		_x('Quilpie', 'STQU', 'ry-wc-city-select'),
		_x('Redland', 'STQU', 'ry-wc-city-select'),
		_x('Richmond', 'STQU', 'ry-wc-city-select'),
		_x('Rockhampton', 'STQU', 'ry-wc-city-select'),
		_x('Scenic Rim', 'STQU', 'ry-wc-city-select'),
		_x('Somerset', 'STQU', 'ry-wc-city-select'),
		_x('South Burnett', 'STQU', 'ry-wc-city-select'),
		_x('Southern Downs', 'STQU', 'ry-wc-city-select'),
		_x('Sunshine Coast', 'STQU', 'ry-wc-city-select'),
		_x('Tablelands', 'STQU', 'ry-wc-city-select'),
		_x('Toowoomba', 'STQU', 'ry-wc-city-select'),
		_x('Torres', 'STQU', 'ry-wc-city-select'),
		_x('Torres Strait Island Region', 'STQU', 'ry-wc-city-select'),
		_x('Townsville', 'STQU', 'ry-wc-city-select'),
		_x('Weipa', 'STQU', 'ry-wc-city-select'),
		_x('Western Downs', 'STQU', 'ry-wc-city-select'),
		_x('Whitsunday', 'STQU', 'ry-wc-city-select'),
		_x('Winton', 'STQU', 'ry-wc-city-select'),
		_x('Woorabinda', 'STQU', 'ry-wc-city-select'),
		_x('Wujal Wujal', 'STQU', 'ry-wc-city-select'),
		_x('Yarrabah', 'STQU', 'ry-wc-city-select'),
	],
	'STSOAU' => [
		_x('Adelaide', 'STSOAU', 'ry-wc-city-select'),
		_x('Adelaide Hills', 'STSOAU', 'ry-wc-city-select'),
		_x('Alexandrina', 'STSOAU', 'ry-wc-city-select'),
		_x('Anangu Pitjantjatjara', 'STSOAU', 'ry-wc-city-select'),
		_x('Barossa', 'STSOAU', 'ry-wc-city-select'),
		_x('Barunga West', 'STSOAU', 'ry-wc-city-select'),
		_x('Berri and Barmera', 'STSOAU', 'ry-wc-city-select'),
		_x('Burnside', 'STSOAU', 'ry-wc-city-select'),
		_x('Campbelltown', 'STSOAU', 'ry-wc-city-select'),
		_x('Ceduna', 'STSOAU', 'ry-wc-city-select'),
		_x('Charles Sturt', 'STSOAU', 'ry-wc-city-select'),
		_x('City of West Torrens', 'STSOAU', 'ry-wc-city-select'),
		_x('Clare and Gilbert Valleys', 'STSOAU', 'ry-wc-city-select'),
		_x('Cleve', 'STSOAU', 'ry-wc-city-select'),
		_x('Coober Pedy', 'STSOAU', 'ry-wc-city-select'),
		_x('Copper Coast', 'STSOAU', 'ry-wc-city-select'),
		_x('Elliston', 'STSOAU', 'ry-wc-city-select'),
		_x('Flinders Ranges', 'STSOAU', 'ry-wc-city-select'),
		_x('Franklin Harbour', 'STSOAU', 'ry-wc-city-select'),
		_x('Gawler', 'STSOAU', 'ry-wc-city-select'),
		_x('Goyder', 'STSOAU', 'ry-wc-city-select'),
		_x('Grant', 'STSOAU', 'ry-wc-city-select'),
		_x('Holdfast Bay', 'STSOAU', 'ry-wc-city-select'),
		_x('Kangaroo Island', 'STSOAU', 'ry-wc-city-select'),
		_x('Karoonda East Murray', 'STSOAU', 'ry-wc-city-select'),
		_x('Kimba', 'STSOAU', 'ry-wc-city-select'),
		_x('Kingston', 'STSOAU', 'ry-wc-city-select'),
		_x('Light', 'STSOAU', 'ry-wc-city-select'),
		_x('Lower Eyre Peninsula', 'STSOAU', 'ry-wc-city-select'),
		_x('Loxton Waikerie', 'STSOAU', 'ry-wc-city-select'),
		_x('Mallala', 'STSOAU', 'ry-wc-city-select'),
		_x('Maralinga Tjarutja', 'STSOAU', 'ry-wc-city-select'),
		_x('Marion', 'STSOAU', 'ry-wc-city-select'),
		_x('Mid Murray', 'STSOAU', 'ry-wc-city-select'),
		_x('Mitcham', 'STSOAU', 'ry-wc-city-select'),
		_x('Mount Barker', 'STSOAU', 'ry-wc-city-select'),
		_x('Mount Gambier', 'STSOAU', 'ry-wc-city-select'),
		_x('Mount Remarkable', 'STSOAU', 'ry-wc-city-select'),
		_x('Murray Bridge', 'STSOAU', 'ry-wc-city-select'),
		_x('Naracoorte and Lucindale', 'STSOAU', 'ry-wc-city-select'),
		_x('Northern Areas', 'STSOAU', 'ry-wc-city-select'),
		_x('Norwood Payneham St Peters', 'STSOAU', 'ry-wc-city-select'),
		_x('Onkaparinga', 'STSOAU', 'ry-wc-city-select'),
		_x('Orroroo/Carrieton', 'STSOAU', 'ry-wc-city-select'),
		_x('Peterborough', 'STSOAU', 'ry-wc-city-select'),
		_x('Playford', 'STSOAU', 'ry-wc-city-select'),
		_x('Port Adelaide Enfield', 'STSOAU', 'ry-wc-city-select'),
		_x('Port Augusta', 'STSOAU', 'ry-wc-city-select'),
		_x('Port Lincoln', 'STSOAU', 'ry-wc-city-select'),
		_x('Port Pirie City and Dists', 'STSOAU', 'ry-wc-city-select'),
		_x('Prospect', 'STSOAU', 'ry-wc-city-select'),
		_x('Renmark Paringa', 'STSOAU', 'ry-wc-city-select'),
		_x('Robe', 'STSOAU', 'ry-wc-city-select'),
		_x('Roxby Downs', 'STSOAU', 'ry-wc-city-select'),
		_x('Salisbury', 'STSOAU', 'ry-wc-city-select'),
		_x('Southern Mallee', 'STSOAU', 'ry-wc-city-select'),
		_x('Streaky Bay', 'STSOAU', 'ry-wc-city-select'),
		_x('Tatiara', 'STSOAU', 'ry-wc-city-select'),
		_x('Tea Tree Gully', 'STSOAU', 'ry-wc-city-select'),
		_x('The Coorong', 'STSOAU', 'ry-wc-city-select'),
		_x('Tumby Bay', 'STSOAU', 'ry-wc-city-select'),
		_x('Unley', 'STSOAU', 'ry-wc-city-select'),
		_x('Victor Harbor', 'STSOAU', 'ry-wc-city-select'),
		_x('Wakefield', 'STSOAU', 'ry-wc-city-select'),
		_x('Walkerville', 'STSOAU', 'ry-wc-city-select'),
		_x('Wattle Range', 'STSOAU', 'ry-wc-city-select'),
		_x('Whyalla', 'STSOAU', 'ry-wc-city-select'),
		_x('Wudinna', 'STSOAU', 'ry-wc-city-select'),
		_x('Yankalilla', 'STSOAU', 'ry-wc-city-select'),
		_x('Yorke Peninsula', 'STSOAU', 'ry-wc-city-select'),
	],
	'STTA' => [
		_x('Break ODay', 'STTA', 'ry-wc-city-select'),
		_x('Brighton', 'STTA', 'ry-wc-city-select'),
		_x('Burnie', 'STTA', 'ry-wc-city-select'),
		_x('Central Coast', 'STTA', 'ry-wc-city-select'),
		_x('Central Highlands', 'STTA', 'ry-wc-city-select'),
		_x('Circular Head', 'STTA', 'ry-wc-city-select'),
		_x('Clarence', 'STTA', 'ry-wc-city-select'),
		_x('Derwent Valley', 'STTA', 'ry-wc-city-select'),
		_x('Devonport', 'STTA', 'ry-wc-city-select'),
		_x('Dorset', 'STTA', 'ry-wc-city-select'),
		_x('Flinders', 'STTA', 'ry-wc-city-select'),
		_x('George Town', 'STTA', 'ry-wc-city-select'),
		_x('Glamorgan/Spring Bay', 'STTA', 'ry-wc-city-select'),
		_x('Glenorchy', 'STTA', 'ry-wc-city-select'),
		_x('Hobart', 'STTA', 'ry-wc-city-select'),
		_x('Huon Valley', 'STTA', 'ry-wc-city-select'),
		_x('Kentish', 'STTA', 'ry-wc-city-select'),
		_x('King Island', 'STTA', 'ry-wc-city-select'),
		_x('Kingborough', 'STTA', 'ry-wc-city-select'),
		_x('Latrobe', 'STTA', 'ry-wc-city-select'),
		_x('Launceston', 'STTA', 'ry-wc-city-select'),
		_x('Meander Valley', 'STTA', 'ry-wc-city-select'),
		_x('Northern Midlands', 'STTA', 'ry-wc-city-select'),
		_x('Sorell', 'STTA', 'ry-wc-city-select'),
		_x('Southern Midlands', 'STTA', 'ry-wc-city-select'),
		_x('Tasman Peninsula', 'STTA', 'ry-wc-city-select'),
		_x('Waratah/Wynyard', 'STTA', 'ry-wc-city-select'),
		_x('West Coast', 'STTA', 'ry-wc-city-select'),
		_x('West Tamar', 'STTA', 'ry-wc-city-select'),
	],
	'STVI' => [
		_x('Alpine', 'STVI', 'ry-wc-city-select'),
		_x('Ararat', 'STVI', 'ry-wc-city-select'),
		_x('Ballarat', 'STVI', 'ry-wc-city-select'),
		_x('Banyule', 'STVI', 'ry-wc-city-select'),
		_x('Bass Coast', 'STVI', 'ry-wc-city-select'),
		_x('Baw Baw', 'STVI', 'ry-wc-city-select'),
		_x('Bayside', 'STVI', 'ry-wc-city-select'),
		_x('Benalla', 'STVI', 'ry-wc-city-select'),
		_x('Boroondara', 'STVI', 'ry-wc-city-select'),
		_x('Brimbank', 'STVI', 'ry-wc-city-select'),
		_x('Buloke', 'STVI', 'ry-wc-city-select'),
		_x('Campaspe', 'STVI', 'ry-wc-city-select'),
		_x('Cardinia', 'STVI', 'ry-wc-city-select'),
		_x('Casey', 'STVI', 'ry-wc-city-select'),
		_x('Central Goldfields', 'STVI', 'ry-wc-city-select'),
		_x('Colac Otway', 'STVI', 'ry-wc-city-select'),
		_x('Corangamite', 'STVI', 'ry-wc-city-select'),
		_x('Darebin', 'STVI', 'ry-wc-city-select'),
		_x('East Gippsland', 'STVI', 'ry-wc-city-select'),
		_x('Frankston', 'STVI', 'ry-wc-city-select'),
		_x('Gannawarra', 'STVI', 'ry-wc-city-select'),
		_x('Glen Eira', 'STVI', 'ry-wc-city-select'),
		_x('Glenelg', 'STVI', 'ry-wc-city-select'),
		_x('Golden Plains', 'STVI', 'ry-wc-city-select'),
		_x('Greater Bendigo', 'STVI', 'ry-wc-city-select'),
		_x('Greater Dandenong', 'STVI', 'ry-wc-city-select'),
		_x('Greater Geelong', 'STVI', 'ry-wc-city-select'),
		_x('Greater Shepparton', 'STVI', 'ry-wc-city-select'),
		_x('Hepburn', 'STVI', 'ry-wc-city-select'),
		_x('Hindmarsh', 'STVI', 'ry-wc-city-select'),
		_x('Hobsons Bay', 'STVI', 'ry-wc-city-select'),
		_x('Horsham', 'STVI', 'ry-wc-city-select'),
		_x('Hume', 'STVI', 'ry-wc-city-select'),
		_x('Indigo', 'STVI', 'ry-wc-city-select'),
		_x('Kingston', 'STVI', 'ry-wc-city-select'),
		_x('Knox', 'STVI', 'ry-wc-city-select'),
		_x('Latrobe', 'STVI', 'ry-wc-city-select'),
		_x('Loddon', 'STVI', 'ry-wc-city-select'),
		_x('Macedon Ranges', 'STVI', 'ry-wc-city-select'),
		_x('Manningham', 'STVI', 'ry-wc-city-select'),
		_x('Mansfield', 'STVI', 'ry-wc-city-select'),
		_x('Maribyrnong', 'STVI', 'ry-wc-city-select'),
		_x('Maroondah', 'STVI', 'ry-wc-city-select'),
		_x('Melbourne', 'STVI', 'ry-wc-city-select'),
		_x('Melton', 'STVI', 'ry-wc-city-select'),
		_x('Mildura', 'STVI', 'ry-wc-city-select'),
		_x('Mitchell', 'STVI', 'ry-wc-city-select'),
		_x('Moira', 'STVI', 'ry-wc-city-select'),
		_x('Monash', 'STVI', 'ry-wc-city-select'),
		_x('Moonee Valley', 'STVI', 'ry-wc-city-select'),
		_x('Moorabool', 'STVI', 'ry-wc-city-select'),
		_x('Moreland', 'STVI', 'ry-wc-city-select'),
		_x('Mornington Peninsula', 'STVI', 'ry-wc-city-select'),
		_x('Mount Alexander', 'STVI', 'ry-wc-city-select'),
		_x('Moyne', 'STVI', 'ry-wc-city-select'),
		_x('Murrindindi', 'STVI', 'ry-wc-city-select'),
		_x('Nillumbik', 'STVI', 'ry-wc-city-select'),
		_x('Northern Grampians', 'STVI', 'ry-wc-city-select'),
		_x('Port Phillip', 'STVI', 'ry-wc-city-select'),
		_x('Pyrenees', 'STVI', 'ry-wc-city-select'),
		_x('Queenscliffe', 'STVI', 'ry-wc-city-select'),
		_x('South Gippsland', 'STVI', 'ry-wc-city-select'),
		_x('Southern Grampians', 'STVI', 'ry-wc-city-select'),
		_x('Stonnington', 'STVI', 'ry-wc-city-select'),
		_x('Strathbogie', 'STVI', 'ry-wc-city-select'),
		_x('Surf Coast', 'STVI', 'ry-wc-city-select'),
		_x('Swan Hill', 'STVI', 'ry-wc-city-select'),
		_x('Towong', 'STVI', 'ry-wc-city-select'),
		_x('Wangaratta', 'STVI', 'ry-wc-city-select'),
		_x('Warrnambool', 'STVI', 'ry-wc-city-select'),
		_x('Wellington', 'STVI', 'ry-wc-city-select'),
		_x('West Wimmera', 'STVI', 'ry-wc-city-select'),
		_x('Whitehorse', 'STVI', 'ry-wc-city-select'),
		_x('Whittlesea', 'STVI', 'ry-wc-city-select'),
		_x('Wodonga', 'STVI', 'ry-wc-city-select'),
		_x('Wyndham', 'STVI', 'ry-wc-city-select'),
		_x('Yarra', 'STVI', 'ry-wc-city-select'),
		_x('Yarra Ranges', 'STVI', 'ry-wc-city-select'),
		_x('Yarriambiack', 'STVI', 'ry-wc-city-select'),
	],
	'STWEAU' => [
		_x('Albany', 'STWEAU', 'ry-wc-city-select'),
		_x('Armadale', 'STWEAU', 'ry-wc-city-select'),
		_x('Ashburton', 'STWEAU', 'ry-wc-city-select'),
		_x('Augusta-Margaret River Shire', 'STWEAU', 'ry-wc-city-select'),
		_x('Bassendean', 'STWEAU', 'ry-wc-city-select'),
		_x('Bayswater', 'STWEAU', 'ry-wc-city-select'),
		_x('Belmont', 'STWEAU', 'ry-wc-city-select'),
		_x('Beverley', 'STWEAU', 'ry-wc-city-select'),
		_x('Boddington', 'STWEAU', 'ry-wc-city-select'),
		_x('Boyup Brook', 'STWEAU', 'ry-wc-city-select'),
		_x('Bridgetown-Greenbushes', 'STWEAU', 'ry-wc-city-select'),
		_x('Brookton', 'STWEAU', 'ry-wc-city-select'),
		_x('Broome', 'STWEAU', 'ry-wc-city-select'),
		_x('Broomehill-Tambellup', 'STWEAU', 'ry-wc-city-select'),
		_x('Bruce Rock', 'STWEAU', 'ry-wc-city-select'),
		_x('Bunbury', 'STWEAU', 'ry-wc-city-select'),
		_x('Busselton', 'STWEAU', 'ry-wc-city-select'),
		_x('Cambridge', 'STWEAU', 'ry-wc-city-select'),
		_x('Canning', 'STWEAU', 'ry-wc-city-select'),
		_x('Capel', 'STWEAU', 'ry-wc-city-select'),
		_x('Carnamah', 'STWEAU', 'ry-wc-city-select'),
		_x('Carnarvon', 'STWEAU', 'ry-wc-city-select'),
		_x('Chapman Valley', 'STWEAU', 'ry-wc-city-select'),
		_x('Chittering', 'STWEAU', 'ry-wc-city-select'),
		_x('City of Cockburn', 'STWEAU', 'ry-wc-city-select'),
		_x('City of Perth', 'STWEAU', 'ry-wc-city-select'),
		_x('Claremont', 'STWEAU', 'ry-wc-city-select'),
		_x('Collie', 'STWEAU', 'ry-wc-city-select'),
		_x('Coolgardie', 'STWEAU', 'ry-wc-city-select'),
		_x('Coorow', 'STWEAU', 'ry-wc-city-select'),
		_x('Corrigin', 'STWEAU', 'ry-wc-city-select'),
		_x('Cottesloe', 'STWEAU', 'ry-wc-city-select'),
		_x('Cranbrook', 'STWEAU', 'ry-wc-city-select'),
		_x('Cuballing', 'STWEAU', 'ry-wc-city-select'),
		_x('Cue', 'STWEAU', 'ry-wc-city-select'),
		_x('Cunderdin', 'STWEAU', 'ry-wc-city-select'),
		_x('Dalwallinu', 'STWEAU', 'ry-wc-city-select'),
		_x('Dandaragan', 'STWEAU', 'ry-wc-city-select'),
		_x('Dardanup', 'STWEAU', 'ry-wc-city-select'),
		_x('Denmark', 'STWEAU', 'ry-wc-city-select'),
		_x('Derby-West Kimberley', 'STWEAU', 'ry-wc-city-select'),
		_x('Donnybrook-Balingup', 'STWEAU', 'ry-wc-city-select'),
		_x('Dowerin', 'STWEAU', 'ry-wc-city-select'),
		_x('Dumbleyung Shire', 'STWEAU', 'ry-wc-city-select'),
		_x('Dundas', 'STWEAU', 'ry-wc-city-select'),
		_x('East Fremantle', 'STWEAU', 'ry-wc-city-select'),
		_x('East Pilbara', 'STWEAU', 'ry-wc-city-select'),
		_x('Esperance Shire', 'STWEAU', 'ry-wc-city-select'),
		_x('Exmouth', 'STWEAU', 'ry-wc-city-select'),
		_x('Fremantle', 'STWEAU', 'ry-wc-city-select'),
		_x('Gingin', 'STWEAU', 'ry-wc-city-select'),
		_x('Gnowangerup', 'STWEAU', 'ry-wc-city-select'),
		_x('Goomalling', 'STWEAU', 'ry-wc-city-select'),
		_x('Gosnells', 'STWEAU', 'ry-wc-city-select'),
		_x('Greater Geraldton', 'STWEAU', 'ry-wc-city-select'),
		_x('Halls Creek', 'STWEAU', 'ry-wc-city-select'),
		_x('Harvey', 'STWEAU', 'ry-wc-city-select'),
		_x('Irwin', 'STWEAU', 'ry-wc-city-select'),
		_x('Jerramungup', 'STWEAU', 'ry-wc-city-select'),
		_x('Joondalup', 'STWEAU', 'ry-wc-city-select'),
		_x('Kalamunda', 'STWEAU', 'ry-wc-city-select'),
		_x('Kalgoorlie/Boulder', 'STWEAU', 'ry-wc-city-select'),
		_x('Karratha', 'STWEAU', 'ry-wc-city-select'),
		_x('Katanning', 'STWEAU', 'ry-wc-city-select'),
		_x('Kellerberrin', 'STWEAU', 'ry-wc-city-select'),
		_x('Kent Shire', 'STWEAU', 'ry-wc-city-select'),
		_x('Kojonup', 'STWEAU', 'ry-wc-city-select'),
		_x('Kondinin', 'STWEAU', 'ry-wc-city-select'),
		_x('Koorda', 'STWEAU', 'ry-wc-city-select'),
		_x('Kulin', 'STWEAU', 'ry-wc-city-select'),
		_x('Kwinana', 'STWEAU', 'ry-wc-city-select'),
		_x('Lake Grace', 'STWEAU', 'ry-wc-city-select'),
		_x('Laverton', 'STWEAU', 'ry-wc-city-select'),
		_x('Leonora', 'STWEAU', 'ry-wc-city-select'),
		_x('Mandurah', 'STWEAU', 'ry-wc-city-select'),
		_x('Manjimup', 'STWEAU', 'ry-wc-city-select'),
		_x('Meekatharra', 'STWEAU', 'ry-wc-city-select'),
		_x('Melville', 'STWEAU', 'ry-wc-city-select'),
		_x('Menzies', 'STWEAU', 'ry-wc-city-select'),
		_x('Merredin', 'STWEAU', 'ry-wc-city-select'),
		_x('Mingenew', 'STWEAU', 'ry-wc-city-select'),
		_x('Moora', 'STWEAU', 'ry-wc-city-select'),
		_x('Morawa', 'STWEAU', 'ry-wc-city-select'),
		_x('Mosman Park', 'STWEAU', 'ry-wc-city-select'),
		_x('Mount Magnet', 'STWEAU', 'ry-wc-city-select'),
		_x('Mount Marshall', 'STWEAU', 'ry-wc-city-select'),
		_x('Mukinbudin', 'STWEAU', 'ry-wc-city-select'),
		_x('Mundaring', 'STWEAU', 'ry-wc-city-select'),
		_x('Murchison', 'STWEAU', 'ry-wc-city-select'),
		_x('Murray', 'STWEAU', 'ry-wc-city-select'),
		_x('Nannup', 'STWEAU', 'ry-wc-city-select'),
		_x('Narembeen', 'STWEAU', 'ry-wc-city-select'),
		_x('Narrogin', 'STWEAU', 'ry-wc-city-select'),
		_x('Nedlands', 'STWEAU', 'ry-wc-city-select'),
		_x('Ngaanyatjarraku', 'STWEAU', 'ry-wc-city-select'),
		_x('Northam', 'STWEAU', 'ry-wc-city-select'),
		_x('Northampton Shire', 'STWEAU', 'ry-wc-city-select'),
		_x('Nungarin', 'STWEAU', 'ry-wc-city-select'),
		_x('Peppermint Grove', 'STWEAU', 'ry-wc-city-select'),
		_x('Perenjori', 'STWEAU', 'ry-wc-city-select'),
		_x('Pingelly', 'STWEAU', 'ry-wc-city-select'),
		_x('Plantagenet Shire', 'STWEAU', 'ry-wc-city-select'),
		_x('Port Hedland', 'STWEAU', 'ry-wc-city-select'),
		_x('Quairading', 'STWEAU', 'ry-wc-city-select'),
		_x('Ravensthorpe', 'STWEAU', 'ry-wc-city-select'),
		_x('Rockingham', 'STWEAU', 'ry-wc-city-select'),
		_x('Sandstone', 'STWEAU', 'ry-wc-city-select'),
		_x('Serpentine-Jarrahdale', 'STWEAU', 'ry-wc-city-select'),
		_x('Shark Bay', 'STWEAU', 'ry-wc-city-select'),
		_x('South Perth', 'STWEAU', 'ry-wc-city-select'),
		_x('Stirling', 'STWEAU', 'ry-wc-city-select'),
		_x('Subiaco', 'STWEAU', 'ry-wc-city-select'),
		_x('Swan', 'STWEAU', 'ry-wc-city-select'),
		_x('Tammin', 'STWEAU', 'ry-wc-city-select'),
		_x('Three Springs', 'STWEAU', 'ry-wc-city-select'),
		_x('Toodyay', 'STWEAU', 'ry-wc-city-select'),
		_x('Trayning', 'STWEAU', 'ry-wc-city-select'),
		_x('Upper Gascoyne', 'STWEAU', 'ry-wc-city-select'),
		_x('Victoria Park', 'STWEAU', 'ry-wc-city-select'),
		_x('Victoria Plains', 'STWEAU', 'ry-wc-city-select'),
		_x('Vincent', 'STWEAU', 'ry-wc-city-select'),
		_x('Wagin', 'STWEAU', 'ry-wc-city-select'),
		_x('Wandering', 'STWEAU', 'ry-wc-city-select'),
		_x('Wanneroo', 'STWEAU', 'ry-wc-city-select'),
		_x('Waroona', 'STWEAU', 'ry-wc-city-select'),
		_x('West Arthur', 'STWEAU', 'ry-wc-city-select'),
		_x('Westonia', 'STWEAU', 'ry-wc-city-select'),
		_x('Wickepin', 'STWEAU', 'ry-wc-city-select'),
		_x('Williams', 'STWEAU', 'ry-wc-city-select'),
		_x('Wiluna', 'STWEAU', 'ry-wc-city-select'),
		_x('Wongan-Ballidu', 'STWEAU', 'ry-wc-city-select'),
		_x('Woodanilling', 'STWEAU', 'ry-wc-city-select'),
		_x('Wyalkatchem', 'STWEAU', 'ry-wc-city-select'),
		_x('Wyndham-East Kimberley', 'STWEAU', 'ry-wc-city-select'),
		_x('Yalgoo', 'STWEAU', 'ry-wc-city-select'),
		_x('Yilgarn', 'STWEAU', 'ry-wc-city-select'),
		_x('York', 'STWEAU', 'ry-wc-city-select'),
	],
	]
];