<?php
/**
 * Bosnia and Herzegovina places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'BA' => [
	'BOKAGO' => [
		_x('Foca-Ustikolina', 'BOKAGO', 'ry-wc-city-select'),
		_x('Pale-Praca', 'BOKAGO', 'ry-wc-city-select'),
	],
	'POKA' => [
		_x('Vukosavlje', 'POKA', 'ry-wc-city-select'),
	],
	'TUKA' => [
		_x('Kalesija', 'TUKA', 'ry-wc-city-select'),
	],
	'ZEKA' => [
		_x('Kakanj', 'ZEKA', 'ry-wc-city-select'),
	],
	'FEBOANHE' => [
		_x('Hercegovacko-Neretvanski Kanton', 'FEBOANHE', 'ry-wc-city-select'),
		_x('Kanton 10', 'FEBOANHE', 'ry-wc-city-select'),
		_x('Kanton Sarajevo', 'FEBOANHE', 'ry-wc-city-select'),
		_x('Neretvljanski', 'FEBOANHE', 'ry-wc-city-select'),
		_x('Srednjobosanski Kanton', 'FEBOANHE', 'ry-wc-city-select'),
		_x('Unsko-Sanski Kanton', 'FEBOANHE', 'ry-wc-city-select'),
		_x('Zapadnohercegovacki Kanton', 'FEBOANHE', 'ry-wc-city-select'),
	],
	'RESR' => [
		_x('Banja Luka', 'RESR', 'ry-wc-city-select'),
		_x('Bijeljina', 'RESR', 'ry-wc-city-select'),
		_x('Bratunac', 'RESR', 'ry-wc-city-select'),
		_x('Derventa', 'RESR', 'ry-wc-city-select'),
		_x('Doboj', 'RESR', 'ry-wc-city-select'),
		_x('Foca', 'RESR', 'ry-wc-city-select'),
		_x('Gacko', 'RESR', 'ry-wc-city-select'),
		_x('Grad Istocno Sarajevo', 'RESR', 'ry-wc-city-select'),
		_x('Han Pijesak', 'RESR', 'ry-wc-city-select'),
		_x('Istocna Ilidza', 'RESR', 'ry-wc-city-select'),
		_x('Istocni Drvar', 'RESR', 'ry-wc-city-select'),
		_x('Istocni Mostar', 'RESR', 'ry-wc-city-select'),
		_x('Istocni Stari Grad', 'RESR', 'ry-wc-city-select'),
		_x('Istocno Novo Sarajevo', 'RESR', 'ry-wc-city-select'),
		_x('Jezero', 'RESR', 'ry-wc-city-select'),
		_x('Kalinovik', 'RESR', 'ry-wc-city-select'),
		_x('Kostajnica', 'RESR', 'ry-wc-city-select'),
		_x('Ljubinje', 'RESR', 'ry-wc-city-select'),
		_x('Lopare', 'RESR', 'ry-wc-city-select'),
		_x('Modrica', 'RESR', 'ry-wc-city-select'),
		_x('Mrkonjic Grad Jug Opcina', 'RESR', 'ry-wc-city-select'),
		_x('Novo Gorazde', 'RESR', 'ry-wc-city-select'),
		_x('Opcina Donji Zabar', 'RESR', 'ry-wc-city-select'),
		_x('Opcina Knezevo', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Berkovici', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Bileca', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Brod', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Cajnice', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Celinac', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Gradiska', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Kotor Varos', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Kozarska Dubica', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Krupa na Uni', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Kupres', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Laktasi', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Milici', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Modrica', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Mrkonjic Grad', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Nevesinje', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Novi Grad', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Osmaci', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Ostra Luka', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Pale', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Pelagicevo', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Petrovac', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Petrovo', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Ribnik', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Samac', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Sekovici', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Sipovo', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Sokolac', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Teslic', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Trnovo', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Ugljevik', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Visegrad', 'RESR', 'ry-wc-city-select'),
		_x('Opstina Vukosavlje', 'RESR', 'ry-wc-city-select'),
		_x('Prijedor', 'RESR', 'ry-wc-city-select'),
		_x('Prnjavor', 'RESR', 'ry-wc-city-select'),
		_x('Rogatica', 'RESR', 'ry-wc-city-select'),
		_x('Rudo', 'RESR', 'ry-wc-city-select'),
		_x('Skelani Opstina', 'RESR', 'ry-wc-city-select'),
		_x('Srbac', 'RESR', 'ry-wc-city-select'),
		_x('Srebrenica', 'RESR', 'ry-wc-city-select'),
		_x('Stanari', 'RESR', 'ry-wc-city-select'),
		_x('Trebinje', 'RESR', 'ry-wc-city-select'),
		_x('Vlasenica', 'RESR', 'ry-wc-city-select'),
		_x('Zvornik', 'RESR', 'ry-wc-city-select'),
	],
	]
];