<?php
/**
 * Bangladesh places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'BD' => [
	'BA' => [
		_x('Bagerhat S.', 'BA', 'ry-wc-city-select'),
		_x('Chitalmari', 'BA', 'ry-wc-city-select'),
		_x('Fakirhat', 'BA', 'ry-wc-city-select'),
		_x('Kachua', 'BA', 'ry-wc-city-select'),
		_x('Mollahat', 'BA', 'ry-wc-city-select'),
		_x('Mongla Upazila', 'BA', 'ry-wc-city-select'),
		_x('Morrelganj', 'BA', 'ry-wc-city-select'),
		_x('Rampal', 'BA', 'ry-wc-city-select'),
		_x('Sarankhola', 'BA', 'ry-wc-city-select'),
	],
	'BA2' => [
		_x('Alikadam', 'BA2', 'ry-wc-city-select'),
		_x('Bandarban Sadar', 'BA2', 'ry-wc-city-select'),
		_x('Lama', 'BA2', 'ry-wc-city-select'),
		_x('Naikhongchhari', 'BA2', 'ry-wc-city-select'),
		_x('Rowangghhari', 'BA2', 'ry-wc-city-select'),
		_x('Ruma', 'BA2', 'ry-wc-city-select'),
		_x('Thanchi', 'BA2', 'ry-wc-city-select'),
	],
	'BA3' => [
		_x('Amtali', 'BA3', 'ry-wc-city-select'),
		_x('Bamna Upazila', 'BA3', 'ry-wc-city-select'),
		_x('Barguna S.', 'BA3', 'ry-wc-city-select'),
		_x('Betagi Upazila', 'BA3', 'ry-wc-city-select'),
		_x('Patharghata Upazila', 'BA3', 'ry-wc-city-select'),
	],
	'BA4' => [
		_x('Agailjhara', 'BA4', 'ry-wc-city-select'),
		_x('Babuganj Upazila', 'BA4', 'ry-wc-city-select'),
		_x('Bakerganj Upazila', 'BA4', 'ry-wc-city-select'),
		_x('Banaripara Upazila', 'BA4', 'ry-wc-city-select'),
		_x('Barisal Sadar Upazila', 'BA4', 'ry-wc-city-select'),
		_x('Gaurnadi Upazila', 'BA4', 'ry-wc-city-select'),
		_x('Hizla Upazila', 'BA4', 'ry-wc-city-select'),
		_x('Mehendiganj Upazila', 'BA4', 'ry-wc-city-select'),
		_x('Muladi Upazila', 'BA4', 'ry-wc-city-select'),
		_x('Wazirpur', 'BA4', 'ry-wc-city-select'),
	],
	'BH' => [
		_x('Bhola Sadar Upazila', 'BH', 'ry-wc-city-select'),
		_x('Burhanuddin', 'BH', 'ry-wc-city-select'),
		_x('Charfasson', 'BH', 'ry-wc-city-select'),
		_x('Daulatkhan', 'BH', 'ry-wc-city-select'),
		_x('Lalmohan', 'BH', 'ry-wc-city-select'),
		_x('Manpura', 'BH', 'ry-wc-city-select'),
		_x('Tazumuddin', 'BH', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Adamdighi', 'BO', 'ry-wc-city-select'),
		_x('Bogra', 'BO', 'ry-wc-city-select'),
		_x('Dhunot', 'BO', 'ry-wc-city-select'),
		_x('Dhupchanchia', 'BO', 'ry-wc-city-select'),
		_x('Gabtali', 'BO', 'ry-wc-city-select'),
		_x('Kahaloo', 'BO', 'ry-wc-city-select'),
		_x('Nandigram', 'BO', 'ry-wc-city-select'),
		_x('Saraikandi', 'BO', 'ry-wc-city-select'),
		_x('Shajahanpur', 'BO', 'ry-wc-city-select'),
		_x('Sherpur', 'BO', 'ry-wc-city-select'),
		_x('Shibganj', 'BO', 'ry-wc-city-select'),
		_x('Sonatala', 'BO', 'ry-wc-city-select'),
	],
	'BR' => [
		_x('Akhaura', 'BR', 'ry-wc-city-select'),
		_x('Ashuganj Upazila', 'BR', 'ry-wc-city-select'),
		_x('Bancharampur Upazila', 'BR', 'ry-wc-city-select'),
		_x('Brahmanbaria S.', 'BR', 'ry-wc-city-select'),
		_x('Kasba', 'BR', 'ry-wc-city-select'),
		_x('Nabinagar', 'BR', 'ry-wc-city-select'),
		_x('Nasirnagar', 'BR', 'ry-wc-city-select'),
		_x('Sarail', 'BR', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Chandpur S.', 'CH', 'ry-wc-city-select'),
		_x('Faridganj', 'CH', 'ry-wc-city-select'),
		_x('Haimchar', 'CH', 'ry-wc-city-select'),
		_x('Haziganj', 'CH', 'ry-wc-city-select'),
		_x('Kachua', 'CH', 'ry-wc-city-select'),
		_x('Matlab Dakshin Upazila', 'CH', 'ry-wc-city-select'),
		_x('Matlab Uttar Upazila', 'CH', 'ry-wc-city-select'),
		_x('Shahrasti', 'CH', 'ry-wc-city-select'),
	],
	'CHNA' => [
		_x('Bholahat', 'CHNA', 'ry-wc-city-select'),
		_x('Gomastapur', 'CHNA', 'ry-wc-city-select'),
		_x('Nachole', 'CHNA', 'ry-wc-city-select'),
		_x('Nawabganj Sadar Upazila', 'CHNA', 'ry-wc-city-select'),
		_x('Shibganj', 'CHNA', 'ry-wc-city-select'),
	],
	'CH3' => [
		_x('Alamdanga', 'CH3', 'ry-wc-city-select'),
		_x('Chuadanga Sadar Upazila', 'CH3', 'ry-wc-city-select'),
		_x('Damurhuda Upazila', 'CH3', 'ry-wc-city-select'),
		_x('Jibannagar Upazila', 'CH3', 'ry-wc-city-select'),
	],
	'CO' => [
		_x('Barura', 'CO', 'ry-wc-city-select'),
		_x('Brahmanpara', 'CO', 'ry-wc-city-select'),
		_x('Burichang', 'CO', 'ry-wc-city-select'),
		_x('Chandhina', 'CO', 'ry-wc-city-select'),
		_x('Chauddagram', 'CO', 'ry-wc-city-select'),
		_x('Comilla S.', 'CO', 'ry-wc-city-select'),
		_x('Comilla Sadar Dakshin Upazila', 'CO', 'ry-wc-city-select'),
		_x('Daudkandi Upazila', 'CO', 'ry-wc-city-select'),
		_x('Debidwar', 'CO', 'ry-wc-city-select'),
		_x('Homna', 'CO', 'ry-wc-city-select'),
		_x('Laksam Upazila', 'CO', 'ry-wc-city-select'),
		_x('Meghna', 'CO', 'ry-wc-city-select'),
		_x('Monoharganj', 'CO', 'ry-wc-city-select'),
		_x('Muradnagar', 'CO', 'ry-wc-city-select'),
		_x('Nangalkot', 'CO', 'ry-wc-city-select'),
		_x('Titas Upazila', 'CO', 'ry-wc-city-select'),
	],
	'COBA' => [
		_x('Chakaria Upazila', 'COBA', 'ry-wc-city-select'),
		_x('Coxs Bazar Sadar Upazila', 'COBA', 'ry-wc-city-select'),
		_x('Kutubdia', 'COBA', 'ry-wc-city-select'),
		_x('Maheshkhali', 'COBA', 'ry-wc-city-select'),
		_x('Pekua Upazila', 'COBA', 'ry-wc-city-select'),
		_x('Ramu', 'COBA', 'ry-wc-city-select'),
		_x('Teknaf', 'COBA', 'ry-wc-city-select'),
		_x('Ukhia', 'COBA', 'ry-wc-city-select'),
	],
	'DH' => [
		_x('DCC (Kotwali)', 'DH', 'ry-wc-city-select'),
		_x('Dhamrai', 'DH', 'ry-wc-city-select'),
		_x('Dohar', 'DH', 'ry-wc-city-select'),
		_x('Keraniganj', 'DH', 'ry-wc-city-select'),
		_x('Nawabganj', 'DH', 'ry-wc-city-select'),
		_x('Savar', 'DH', 'ry-wc-city-select'),
	],
	'DI' => [
		_x('Biral', 'DI', 'ry-wc-city-select'),
		_x('Birampur', 'DI', 'ry-wc-city-select'),
		_x('Birganj', 'DI', 'ry-wc-city-select'),
		_x('Bochaganj', 'DI', 'ry-wc-city-select'),
		_x('Chirirbandar Upazila', 'DI', 'ry-wc-city-select'),
		_x('Dinajpur Sadar', 'DI', 'ry-wc-city-select'),
		_x('Ghoraghat', 'DI', 'ry-wc-city-select'),
		_x('Hakimpur', 'DI', 'ry-wc-city-select'),
		_x('Kaharole', 'DI', 'ry-wc-city-select'),
		_x('Khansama', 'DI', 'ry-wc-city-select'),
		_x('Nawabgonj', 'DI', 'ry-wc-city-select'),
		_x('Parbatipur', 'DI', 'ry-wc-city-select'),
		_x('Phulbari', 'DI', 'ry-wc-city-select'),
	],
	'FA' => [
		_x('Alfadanga', 'FA', 'ry-wc-city-select'),
		_x('Bhanga', 'FA', 'ry-wc-city-select'),
		_x('Boalmari', 'FA', 'ry-wc-city-select'),
		_x('Char Bhadrasan', 'FA', 'ry-wc-city-select'),
		_x('Faridpur Sadar Upazila', 'FA', 'ry-wc-city-select'),
		_x('Madhukhali', 'FA', 'ry-wc-city-select'),
		_x('Nagarkanda', 'FA', 'ry-wc-city-select'),
		_x('Sadarpur', 'FA', 'ry-wc-city-select'),
	],
	'FE' => [
		_x('Chhagalnaiya', 'FE', 'ry-wc-city-select'),
		_x('Daganbhuiyan', 'FE', 'ry-wc-city-select'),
		_x('Feni Sadar Upazila', 'FE', 'ry-wc-city-select'),
		_x('Fulgazi', 'FE', 'ry-wc-city-select'),
		_x('Parshuram', 'FE', 'ry-wc-city-select'),
		_x('Sonagazi Upazila', 'FE', 'ry-wc-city-select'),
	],
	'GA' => [
		_x('Gaibandha S.', 'GA', 'ry-wc-city-select'),
		_x('Gobindaganj', 'GA', 'ry-wc-city-select'),
		_x('Palashbari Upazila', 'GA', 'ry-wc-city-select'),
		_x('Phulchhari', 'GA', 'ry-wc-city-select'),
		_x('Sadullapur', 'GA', 'ry-wc-city-select'),
		_x('Saghata', 'GA', 'ry-wc-city-select'),
		_x('Sundarganj', 'GA', 'ry-wc-city-select'),
	],
	'GA2' => [
		_x('Gazipur S.', 'GA2', 'ry-wc-city-select'),
		_x('Kaliakair', 'GA2', 'ry-wc-city-select'),
		_x('Kaliganj', 'GA2', 'ry-wc-city-select'),
		_x('Kapasia', 'GA2', 'ry-wc-city-select'),
		_x('Sreepur', 'GA2', 'ry-wc-city-select'),
	],
	'GO' => [
		_x('Gopalganj S.', 'GO', 'ry-wc-city-select'),
		_x('Kashiani', 'GO', 'ry-wc-city-select'),
		_x('Kotalipara Upazila', 'GO', 'ry-wc-city-select'),
		_x('Muksudpur', 'GO', 'ry-wc-city-select'),
		_x('Tungipara', 'GO', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Ajmiriganj', 'HA', 'ry-wc-city-select'),
		_x('Bahubal', 'HA', 'ry-wc-city-select'),
		_x('Baniachong', 'HA', 'ry-wc-city-select'),
		_x('Chunarughat Upazila', 'HA', 'ry-wc-city-select'),
		_x('Habiganj Sadar Upazila', 'HA', 'ry-wc-city-select'),
		_x('Lakhai', 'HA', 'ry-wc-city-select'),
		_x('Madhabpur Upazila', 'HA', 'ry-wc-city-select'),
		_x('Nabiganj', 'HA', 'ry-wc-city-select'),
	],
	'JA' => [
		_x('Baksiganj', 'JA', 'ry-wc-city-select'),
		_x('Dewanganj', 'JA', 'ry-wc-city-select'),
		_x('Islampur', 'JA', 'ry-wc-city-select'),
		_x('Jamalpur Upazila', 'JA', 'ry-wc-city-select'),
		_x('Madarganj', 'JA', 'ry-wc-city-select'),
		_x('Melandaha', 'JA', 'ry-wc-city-select'),
		_x('Sarishabari', 'JA', 'ry-wc-city-select'),
	],
	'JE' => [
		_x('Abhaynagar Upazila', 'JE', 'ry-wc-city-select'),
		_x('Bagherpara Upazila', 'JE', 'ry-wc-city-select'),
		_x('Chaugachha', 'JE', 'ry-wc-city-select'),
		_x('Jessore Sadar', 'JE', 'ry-wc-city-select'),
		_x('Jhikargachha Upazila', 'JE', 'ry-wc-city-select'),
		_x('Keshabpur Upazila', 'JE', 'ry-wc-city-select'),
		_x('Manirampur Upazila', 'JE', 'ry-wc-city-select'),
		_x('Sharsha', 'JE', 'ry-wc-city-select'),
	],
	'JH' => [
		_x('Jhalokati Sadar', 'JH', 'ry-wc-city-select'),
		_x('Kathalia', 'JH', 'ry-wc-city-select'),
		_x('Nalchity', 'JH', 'ry-wc-city-select'),
		_x('Rajapur', 'JH', 'ry-wc-city-select'),
	],
	'JH2' => [
		_x('Harinakunda', 'JH2', 'ry-wc-city-select'),
		_x('Jhenaidah Sadar Upazila', 'JH2', 'ry-wc-city-select'),
		_x('Kaliganj Upazila', 'JH2', 'ry-wc-city-select'),
		_x('Kotchandpur Upazila', 'JH2', 'ry-wc-city-select'),
		_x('Maheshpur', 'JH2', 'ry-wc-city-select'),
		_x('Shailkupa', 'JH2', 'ry-wc-city-select'),
	],
	'JO' => [
		_x('Akkelpur', 'JO', 'ry-wc-city-select'),
		_x('Joypurhat Sadar', 'JO', 'ry-wc-city-select'),
		_x('Kalai', 'JO', 'ry-wc-city-select'),
		_x('Khetlal', 'JO', 'ry-wc-city-select'),
		_x('Panchbibi', 'JO', 'ry-wc-city-select'),
	],
	'KH' => [
		_x('Dighinala', 'KH', 'ry-wc-city-select'),
		_x('Khagrachhari', 'KH', 'ry-wc-city-select'),
		_x('Lakshmichhari', 'KH', 'ry-wc-city-select'),
		_x('Mahalchhari', 'KH', 'ry-wc-city-select'),
		_x('Manikchhari', 'KH', 'ry-wc-city-select'),
		_x('Matiranga', 'KH', 'ry-wc-city-select'),
		_x('Panchhari', 'KH', 'ry-wc-city-select'),
		_x('Ramgarh', 'KH', 'ry-wc-city-select'),
	],
	'KH2' => [
		_x('Batiaghata Upazila', 'KH2', 'ry-wc-city-select'),
		_x('Dacope Upazila', 'KH2', 'ry-wc-city-select'),
		_x('Dighalia Upazila', 'KH2', 'ry-wc-city-select'),
		_x('Dumuria Upazila', 'KH2', 'ry-wc-city-select'),
		_x('KCC (Daulatpur)', 'KH2', 'ry-wc-city-select'),
		_x('KCC (Khalishpur)', 'KH2', 'ry-wc-city-select'),
		_x('KCC (Sonadanga)', 'KH2', 'ry-wc-city-select'),
		_x('Khan Jahan Ali', 'KH2', 'ry-wc-city-select'),
		_x('Kotwali', 'KH2', 'ry-wc-city-select'),
		_x('Koyra', 'KH2', 'ry-wc-city-select'),
		_x('Paikgachha', 'KH2', 'ry-wc-city-select'),
		_x('Phultala Upazila', 'KH2', 'ry-wc-city-select'),
		_x('Rupsa', 'KH2', 'ry-wc-city-select'),
		_x('Terokhada', 'KH2', 'ry-wc-city-select'),
	],
	'KI' => [
		_x('Astagram Upazila', 'KI', 'ry-wc-city-select'),
		_x('Bajitpur', 'KI', 'ry-wc-city-select'),
		_x('Bhairab Upazila', 'KI', 'ry-wc-city-select'),
		_x('Hossainpur', 'KI', 'ry-wc-city-select'),
		_x('Itna Upazila', 'KI', 'ry-wc-city-select'),
		_x('Karimganj', 'KI', 'ry-wc-city-select'),
		_x('Katiadi', 'KI', 'ry-wc-city-select'),
		_x('Kishoreganj Sadar Upazila', 'KI', 'ry-wc-city-select'),
		_x('Kuliarchar Upazila', 'KI', 'ry-wc-city-select'),
		_x('Mithamain Upazila', 'KI', 'ry-wc-city-select'),
		_x('Nikli', 'KI', 'ry-wc-city-select'),
		_x('Pakundia', 'KI', 'ry-wc-city-select'),
		_x('Tarail', 'KI', 'ry-wc-city-select'),
	],
	'KU' => [
		_x('Bhurungamari Upazila', 'KU', 'ry-wc-city-select'),
		_x('Char Rajibpur', 'KU', 'ry-wc-city-select'),
		_x('Chilmari', 'KU', 'ry-wc-city-select'),
		_x('Kurigram S.', 'KU', 'ry-wc-city-select'),
		_x('Nageshwari', 'KU', 'ry-wc-city-select'),
		_x('Phulbari Upazila', 'KU', 'ry-wc-city-select'),
		_x('Rajarhat', 'KU', 'ry-wc-city-select'),
		_x('Raomari Upazila', 'KU', 'ry-wc-city-select'),
		_x('Ulipur', 'KU', 'ry-wc-city-select'),
	],
	'KU2' => [
		_x('Bheramara', 'KU2', 'ry-wc-city-select'),
		_x('Daulatpur', 'KU2', 'ry-wc-city-select'),
		_x('Khoksa Upazila', 'KU2', 'ry-wc-city-select'),
		_x('Kumarkhali Upazila', 'KU2', 'ry-wc-city-select'),
		_x('Kushtia Sadar Upazila', 'KU2', 'ry-wc-city-select'),
		_x('Mirpur', 'KU2', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Lakshmipur Sadar Upazila', 'LA', 'ry-wc-city-select'),
		_x('Raipur', 'LA', 'ry-wc-city-select'),
		_x('Ramganj Upazila', 'LA', 'ry-wc-city-select'),
		_x('Ramgati', 'LA', 'ry-wc-city-select'),
	],
	'LADI' => [
		_x('Aditmari', 'LADI', 'ry-wc-city-select'),
		_x('Hatibandha', 'LADI', 'ry-wc-city-select'),
		_x('Kaliganj Upazila', 'LADI', 'ry-wc-city-select'),
		_x('Lalmonirhat Sadar Upazila', 'LADI', 'ry-wc-city-select'),
		_x('Patgram Upazila', 'LADI', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Kalkini', 'MA', 'ry-wc-city-select'),
		_x('Madaripur S.', 'MA', 'ry-wc-city-select'),
		_x('Rajoir', 'MA', 'ry-wc-city-select'),
		_x('Shibchar', 'MA', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('Magura Sadar Upazila', 'MA2', 'ry-wc-city-select'),
		_x('Mohammadpur', 'MA2', 'ry-wc-city-select'),
		_x('Shalikha', 'MA2', 'ry-wc-city-select'),
		_x('Sreepur', 'MA2', 'ry-wc-city-select'),
	],
	'MA3' => [
		_x('Dawlatpur', 'MA3', 'ry-wc-city-select'),
		_x('Ghior', 'MA3', 'ry-wc-city-select'),
		_x('Harirampur', 'MA3', 'ry-wc-city-select'),
		_x('Manikgonj Sadar Upazila', 'MA3', 'ry-wc-city-select'),
		_x('Saturia', 'MA3', 'ry-wc-city-select'),
		_x('Shivalaya', 'MA3', 'ry-wc-city-select'),
		_x('Singair', 'MA3', 'ry-wc-city-select'),
	],
	'MA4' => [
		_x('Barlekha', 'MA4', 'ry-wc-city-select'),
		_x('Juri Upazila', 'MA4', 'ry-wc-city-select'),
		_x('Kamalganj', 'MA4', 'ry-wc-city-select'),
		_x('Kulaura', 'MA4', 'ry-wc-city-select'),
		_x('Moulvibazar Sadar Upazila', 'MA4', 'ry-wc-city-select'),
		_x('Rajnagar', 'MA4', 'ry-wc-city-select'),
		_x('Sreemangal', 'MA4', 'ry-wc-city-select'),
	],
	'ME' => [
		_x('Gangni', 'ME', 'ry-wc-city-select'),
		_x('Meherpur Sadar Upazila', 'ME', 'ry-wc-city-select'),
		_x('Mujibnagar', 'ME', 'ry-wc-city-select'),
	],
	'MU' => [
		_x('Gazaria', 'MU', 'ry-wc-city-select'),
		_x('Lohajang', 'MU', 'ry-wc-city-select'),
		_x('Munshiganj S.', 'MU', 'ry-wc-city-select'),
		_x('Sirajdikhan', 'MU', 'ry-wc-city-select'),
		_x('Sreenagar', 'MU', 'ry-wc-city-select'),
		_x('Tongibari', 'MU', 'ry-wc-city-select'),
	],
	'MY' => [
		_x('Bhaluka Upazila', 'MY', 'ry-wc-city-select'),
		_x('Dhobaura', 'MY', 'ry-wc-city-select'),
		_x('Fulbaria Upazila', 'MY', 'ry-wc-city-select'),
		_x('Gaffargaon', 'MY', 'ry-wc-city-select'),
		_x('Gauripur', 'MY', 'ry-wc-city-select'),
		_x('Haluaghat', 'MY', 'ry-wc-city-select'),
		_x('Ishwarganj', 'MY', 'ry-wc-city-select'),
		_x('Muktagacha Upazila', 'MY', 'ry-wc-city-select'),
		_x('Mymensingh S.', 'MY', 'ry-wc-city-select'),
		_x('Nandail Upazila', 'MY', 'ry-wc-city-select'),
		_x('Phulpur Upazila', 'MY', 'ry-wc-city-select'),
		_x('Trishal', 'MY', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Atrai', 'NA', 'ry-wc-city-select'),
		_x('Badalgachhi', 'NA', 'ry-wc-city-select'),
		_x('Dhamoirhat', 'NA', 'ry-wc-city-select'),
		_x('Manda', 'NA', 'ry-wc-city-select'),
		_x('Mohadevpur', 'NA', 'ry-wc-city-select'),
		_x('Naogaon S.', 'NA', 'ry-wc-city-select'),
		_x('Niamatpur', 'NA', 'ry-wc-city-select'),
		_x('Patnitala', 'NA', 'ry-wc-city-select'),
		_x('Porsha', 'NA', 'ry-wc-city-select'),
		_x('Raninagar', 'NA', 'ry-wc-city-select'),
		_x('Sapahar', 'NA', 'ry-wc-city-select'),
	],
	'NA2' => [
		_x('Kalia Upazila', 'NA2', 'ry-wc-city-select'),
		_x('Lohagara', 'NA2', 'ry-wc-city-select'),
		_x('Narail S.', 'NA2', 'ry-wc-city-select'),
	],
	'NA3' => [
		_x('Araihazar', 'NA3', 'ry-wc-city-select'),
		_x('Bandar', 'NA3', 'ry-wc-city-select'),
		_x('Narayanganj S.', 'NA3', 'ry-wc-city-select'),
		_x('Rupganj', 'NA3', 'ry-wc-city-select'),
		_x('Sonargaon', 'NA3', 'ry-wc-city-select'),
	],
	'NA4' => [
		_x('Belabo', 'NA4', 'ry-wc-city-select'),
		_x('Monohardi Upazila', 'NA4', 'ry-wc-city-select'),
		_x('Narsingdi S.', 'NA4', 'ry-wc-city-select'),
		_x('Palash Upazila', 'NA4', 'ry-wc-city-select'),
		_x('Raipura Upazila', 'NA4', 'ry-wc-city-select'),
		_x('Shibpur Upazila', 'NA4', 'ry-wc-city-select'),
	],
	'NA5' => [
		_x('Bagatipara', 'NA5', 'ry-wc-city-select'),
		_x('Baraigram', 'NA5', 'ry-wc-city-select'),
		_x('Gurudaspur', 'NA5', 'ry-wc-city-select'),
		_x('Lalpur', 'NA5', 'ry-wc-city-select'),
		_x('Natore S.', 'NA5', 'ry-wc-city-select'),
		_x('Singra', 'NA5', 'ry-wc-city-select'),
	],
	'NE' => [
		_x('Atpara Upazila', 'NE', 'ry-wc-city-select'),
		_x('Barhatta Upazila', 'NE', 'ry-wc-city-select'),
		_x('Durgapur', 'NE', 'ry-wc-city-select'),
		_x('Kalmakanda', 'NE', 'ry-wc-city-select'),
		_x('Kendua Upazila', 'NE', 'ry-wc-city-select'),
		_x('Khaliajuri', 'NE', 'ry-wc-city-select'),
		_x('Madan Upazila', 'NE', 'ry-wc-city-select'),
		_x('Mohanganj Upazila', 'NE', 'ry-wc-city-select'),
		_x('Netrokona Sadar Upazila', 'NE', 'ry-wc-city-select'),
		_x('Purbadhala Upazila', 'NE', 'ry-wc-city-select'),
	],
	'NIZI' => [
		_x('Dimla', 'NIZI', 'ry-wc-city-select'),
		_x('Domar', 'NIZI', 'ry-wc-city-select'),
		_x('Jaldhaka', 'NIZI', 'ry-wc-city-select'),
		_x('Kishoreganj Upazila', 'NIZI', 'ry-wc-city-select'),
		_x('Nilphamari Sadar Upazila', 'NIZI', 'ry-wc-city-select'),
		_x('Saidpur', 'NIZI', 'ry-wc-city-select'),
	],
	'NO' => [
		_x('Begumganj', 'NO', 'ry-wc-city-select'),
		_x('Chatkhil Upazila', 'NO', 'ry-wc-city-select'),
		_x('Companiganj', 'NO', 'ry-wc-city-select'),
		_x('Hatiya', 'NO', 'ry-wc-city-select'),
		_x('Kabirhat Upazila', 'NO', 'ry-wc-city-select'),
		_x('Noakhali S.', 'NO', 'ry-wc-city-select'),
		_x('Senbagh', 'NO', 'ry-wc-city-select'),
		_x('Sonaimuri', 'NO', 'ry-wc-city-select'),
		_x('Subarnachar Upazila', 'NO', 'ry-wc-city-select'),
	],
	'PA' => [
		_x('Atgharia Upazila', 'PA', 'ry-wc-city-select'),
		_x('Bera Upazila', 'PA', 'ry-wc-city-select'),
		_x('Bhangura', 'PA', 'ry-wc-city-select'),
		_x('Chatmohar', 'PA', 'ry-wc-city-select'),
		_x('Faridpur U', 'PA', 'ry-wc-city-select'),
		_x('Ishwardi Upazila', 'PA', 'ry-wc-city-select'),
		_x('Pabna S.', 'PA', 'ry-wc-city-select'),
		_x('Santhia', 'PA', 'ry-wc-city-select'),
		_x('Sujanagar', 'PA', 'ry-wc-city-select'),
	],
	'PA2' => [
		_x('Atwari', 'PA2', 'ry-wc-city-select'),
		_x('Boda Upazila', 'PA2', 'ry-wc-city-select'),
		_x('Debiganj', 'PA2', 'ry-wc-city-select'),
		_x('Panchagarh Sadar', 'PA2', 'ry-wc-city-select'),
		_x('Tetulia Upazila', 'PA2', 'ry-wc-city-select'),
	],
	'PA3' => [
		_x('Bauphal', 'PA3', 'ry-wc-city-select'),
		_x('Dashmina Upazila', 'PA3', 'ry-wc-city-select'),
		_x('Dumki', 'PA3', 'ry-wc-city-select'),
		_x('Dumki Upazila', 'PA3', 'ry-wc-city-select'),
		_x('Galachipa', 'PA3', 'ry-wc-city-select'),
		_x('Kalapara', 'PA3', 'ry-wc-city-select'),
		_x('Mirzaganj', 'PA3', 'ry-wc-city-select'),
		_x('Rangabali Upazila', 'PA3', 'ry-wc-city-select'),
	],
	'PI' => [
		_x('Bhandaria Upazila', 'PI', 'ry-wc-city-select'),
		_x('Kawkhali Upazila', 'PI', 'ry-wc-city-select'),
		_x('Mathbaria Upazila', 'PI', 'ry-wc-city-select'),
		_x('Nazirpur', 'PI', 'ry-wc-city-select'),
		_x('Nesarabad Upazila', 'PI', 'ry-wc-city-select'),
		_x('Pirojpur S.', 'PI', 'ry-wc-city-select'),
		_x('Zianagar Upazila', 'PI', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Baliakandi', 'RA', 'ry-wc-city-select'),
		_x('Goalandaghat Upazila', 'RA', 'ry-wc-city-select'),
		_x('Pangsha', 'RA', 'ry-wc-city-select'),
		_x('Rajbari Sadar Upazila', 'RA', 'ry-wc-city-select'),
	],
	'RA2' => [
		_x('Bagha', 'RA2', 'ry-wc-city-select'),
		_x('Bagmara', 'RA2', 'ry-wc-city-select'),
		_x('Boalia Upazila', 'RA2', 'ry-wc-city-select'),
		_x('Charghat Upazila', 'RA2', 'ry-wc-city-select'),
		_x('Durgapur', 'RA2', 'ry-wc-city-select'),
		_x('Godagari', 'RA2', 'ry-wc-city-select'),
		_x('Mohanpur', 'RA2', 'ry-wc-city-select'),
		_x('Paba Upazila', 'RA2', 'ry-wc-city-select'),
		_x('Puthia Upazila', 'RA2', 'ry-wc-city-select'),
		_x('RCC (Motihar)', 'RA2', 'ry-wc-city-select'),
		_x('RCC (Rajpara)', 'RA2', 'ry-wc-city-select'),
		_x('RCC (Shahmokhdum)', 'RA2', 'ry-wc-city-select'),
		_x('Tanore', 'RA2', 'ry-wc-city-select'),
	],
	'RA3' => [
		_x('Bagaichhari', 'RA3', 'ry-wc-city-select'),
		_x('Barkal', 'RA3', 'ry-wc-city-select'),
		_x('Belaichhari', 'RA3', 'ry-wc-city-select'),
		_x('Juraichhari', 'RA3', 'ry-wc-city-select'),
		_x('Kaptai', 'RA3', 'ry-wc-city-select'),
		_x('Kawkhali', 'RA3', 'ry-wc-city-select'),
		_x('Langadu', 'RA3', 'ry-wc-city-select'),
		_x('Nannerchar', 'RA3', 'ry-wc-city-select'),
		_x('Rajasthali', 'RA3', 'ry-wc-city-select'),
		_x('Rangamati Sadar Upazila', 'RA3', 'ry-wc-city-select'),
	],
	'RA4' => [
		_x('Badarganj Upazila', 'RA4', 'ry-wc-city-select'),
		_x('Gangachhara', 'RA4', 'ry-wc-city-select'),
		_x('Kaunia', 'RA4', 'ry-wc-city-select'),
		_x('Mithapukur Upazila', 'RA4', 'ry-wc-city-select'),
		_x('Pirgachha', 'RA4', 'ry-wc-city-select'),
		_x('Pirganj', 'RA4', 'ry-wc-city-select'),
		_x('Rangpur Sadar', 'RA4', 'ry-wc-city-select'),
		_x('Taraganj', 'RA4', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Assasuni', 'SA', 'ry-wc-city-select'),
		_x('Debhata', 'SA', 'ry-wc-city-select'),
		_x('Kalaroa', 'SA', 'ry-wc-city-select'),
		_x('Kaliganj', 'SA', 'ry-wc-city-select'),
		_x('Satkhira S.', 'SA', 'ry-wc-city-select'),
		_x('Shyamnagar Upazila', 'SA', 'ry-wc-city-select'),
		_x('Tala', 'SA', 'ry-wc-city-select'),
	],
	'SH' => [
		_x('Bhedarganj', 'SH', 'ry-wc-city-select'),
		_x('Damudya Upazila', 'SH', 'ry-wc-city-select'),
		_x('Gosairhat', 'SH', 'ry-wc-city-select'),
		_x('Naria Upazila', 'SH', 'ry-wc-city-select'),
		_x('Palong', 'SH', 'ry-wc-city-select'),
		_x('Zanjira', 'SH', 'ry-wc-city-select'),
	],
	'SH2' => [
		_x('Jhenaigati', 'SH2', 'ry-wc-city-select'),
		_x('Nakla', 'SH2', 'ry-wc-city-select'),
		_x('Nalitabari Upazila', 'SH2', 'ry-wc-city-select'),
		_x('Sherpur Sadar Upazila', 'SH2', 'ry-wc-city-select'),
		_x('Sreebardi', 'SH2', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Belkuchi', 'SI', 'ry-wc-city-select'),
		_x('Chauhali Upazila', 'SI', 'ry-wc-city-select'),
		_x('Kamarkhanda', 'SI', 'ry-wc-city-select'),
		_x('Kazipur', 'SI', 'ry-wc-city-select'),
		_x('Raiganj', 'SI', 'ry-wc-city-select'),
		_x('Shahjadpur', 'SI', 'ry-wc-city-select'),
		_x('Sirajganj Sadar', 'SI', 'ry-wc-city-select'),
		_x('Tarash', 'SI', 'ry-wc-city-select'),
		_x('Ullahpara', 'SI', 'ry-wc-city-select'),
	],
	'SU' => [
		_x('Bishwamvarpur', 'SU', 'ry-wc-city-select'),
		_x('Chhatak', 'SU', 'ry-wc-city-select'),
		_x('Derai', 'SU', 'ry-wc-city-select'),
		_x('Dharampasha', 'SU', 'ry-wc-city-select'),
		_x('Dowarabazar', 'SU', 'ry-wc-city-select'),
		_x('Jagannathpur', 'SU', 'ry-wc-city-select'),
		_x('Jamalganj', 'SU', 'ry-wc-city-select'),
		_x('Sullah Upazila', 'SU', 'ry-wc-city-select'),
		_x('Sunamganj', 'SU', 'ry-wc-city-select'),
		_x('Sunamganj S.', 'SU', 'ry-wc-city-select'),
		_x('Tahirpur', 'SU', 'ry-wc-city-select'),
	],
	'SY' => [
		_x('Balaganj', 'SY', 'ry-wc-city-select'),
		_x('Beanibazar', 'SY', 'ry-wc-city-select'),
		_x('Bishwanath', 'SY', 'ry-wc-city-select'),
		_x('Companiganj', 'SY', 'ry-wc-city-select'),
		_x('Fenchuganj Upazila', 'SY', 'ry-wc-city-select'),
		_x('Golabganj', 'SY', 'ry-wc-city-select'),
		_x('Gowainghat', 'SY', 'ry-wc-city-select'),
		_x('Jaintiapur', 'SY', 'ry-wc-city-select'),
		_x('Kanaighat', 'SY', 'ry-wc-city-select'),
		_x('South Surma', 'SY', 'ry-wc-city-select'),
		_x('Sylhet S.', 'SY', 'ry-wc-city-select'),
		_x('Zakiganj', 'SY', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Basail', 'TA', 'ry-wc-city-select'),
		_x('Bhuapur', 'TA', 'ry-wc-city-select'),
		_x('Delduar', 'TA', 'ry-wc-city-select'),
		_x('Dhanbari', 'TA', 'ry-wc-city-select'),
		_x('Ghatail Upazila', 'TA', 'ry-wc-city-select'),
		_x('Gopalpur', 'TA', 'ry-wc-city-select'),
		_x('Kalihati', 'TA', 'ry-wc-city-select'),
		_x('Madhupur Upazila', 'TA', 'ry-wc-city-select'),
		_x('Mirzapur', 'TA', 'ry-wc-city-select'),
		_x('Nagarpur Upazila', 'TA', 'ry-wc-city-select'),
		_x('Sakhipur Upazila', 'TA', 'ry-wc-city-select'),
		_x('Tangail Sadar', 'TA', 'ry-wc-city-select'),
	],
	'TH' => [
		_x('Baliadangi', 'TH', 'ry-wc-city-select'),
		_x('Haripur', 'TH', 'ry-wc-city-select'),
		_x('Pirganj Upazila', 'TH', 'ry-wc-city-select'),
		_x('Ranisankail Upazila', 'TH', 'ry-wc-city-select'),
		_x('Thakurgaon S.', 'TH', 'ry-wc-city-select'),
	],
	]
];