<?php
/**
 * Republic of Benin places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'BJ' => [
	'AD' => [
		_x('Adja-Ouere', 'AD', 'ry-wc-city-select'),
		_x('Ikpinle', 'AD', 'ry-wc-city-select'),
		_x('Kpoulou', 'AD', 'ry-wc-city-select'),
		_x('Masse', 'AD', 'ry-wc-city-select'),
		_x('Oko-Akare', 'AD', 'ry-wc-city-select'),
		_x('Totonnoukon', 'AD', 'ry-wc-city-select'),
	],
	'AD2' => [
		_x('Adjarra I', 'AD2', 'ry-wc-city-select'),
		_x('Adjarra II', 'AD2', 'ry-wc-city-select'),
		_x('Aglogbe', 'AD2', 'ry-wc-city-select'),
		_x('Honvie', 'AD2', 'ry-wc-city-select'),
		_x('Malanhoui', 'AD2', 'ry-wc-city-select'),
		_x('Mededjonou', 'AD2', 'ry-wc-city-select'),
	],
	'AG' => [
		_x('Avagbodji', 'AG', 'ry-wc-city-select'),
		_x('Houedome', 'AG', 'ry-wc-city-select'),
		_x('Zoungame', 'AG', 'ry-wc-city-select'),
	],
	'AK' => [
		_x('Akpro-Misserete', 'AK', 'ry-wc-city-select'),
		_x('Gome-Sota', 'AK', 'ry-wc-city-select'),
		_x('Katagon', 'AK', 'ry-wc-city-select'),
		_x('Vakon', 'AK', 'ry-wc-city-select'),
		_x('Zoungbome', 'AK', 'ry-wc-city-select'),
	],
	'AP' => [
		_x('Aplahoue', 'AP', 'ry-wc-city-select'),
		_x('Atome', 'AP', 'ry-wc-city-select'),
		_x('Azove', 'AP', 'ry-wc-city-select'),
		_x('Dekpo', 'AP', 'ry-wc-city-select'),
		_x('Godohou', 'AP', 'ry-wc-city-select'),
		_x('Kissamey', 'AP', 'ry-wc-city-select'),
		_x('Lonkly', 'AP', 'ry-wc-city-select'),
	],
	'AV' => [
		_x('Atchoukpa', 'AV', 'ry-wc-city-select'),
		_x('Avrankou', 'AV', 'ry-wc-city-select'),
		_x('Djomon', 'AV', 'ry-wc-city-select'),
		_x('Gbozounme', 'AV', 'ry-wc-city-select'),
		_x('Kouty', 'AV', 'ry-wc-city-select'),
		_x('Ouanho', 'AV', 'ry-wc-city-select'),
		_x('Sado', 'AV', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Bassila', 'BA', 'ry-wc-city-select'),
		_x('Manigri', 'BA', 'ry-wc-city-select'),
		_x('Penessoulou', 'BA', 'ry-wc-city-select'),
	],
	'BE' => [
		_x('Bembereke', 'BE', 'ry-wc-city-select'),
		_x('Beroubouay', 'BE', 'ry-wc-city-select'),
		_x('Bouanri', 'BE', 'ry-wc-city-select'),
		_x('Gomia', 'BE', 'ry-wc-city-select'),
		_x('Ina', 'BE', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Affame', 'BO', 'ry-wc-city-select'),
		_x('Atchonsa', 'BO', 'ry-wc-city-select'),
		_x('Bonou', 'BO', 'ry-wc-city-select'),
		_x('Dame-Wogon', 'BO', 'ry-wc-city-select'),
		_x('Houinvigue', 'BO', 'ry-wc-city-select'),
	],
	'BO2' => [
		_x('Dipoli', 'BO2', 'ry-wc-city-select'),
		_x('Korontiere', 'BO2', 'ry-wc-city-select'),
		_x('Kossoucoingou', 'BO2', 'ry-wc-city-select'),
		_x('Manta', 'BO2', 'ry-wc-city-select'),
		_x('Natta', 'BO2', 'ry-wc-city-select'),
		_x('Tabota', 'BO2', 'ry-wc-city-select'),
	],
	'CO' => [
		_x('Cobly', 'CO', 'ry-wc-city-select'),
		_x('Datori', 'CO', 'ry-wc-city-select'),
		_x('Kountori', 'CO', 'ry-wc-city-select'),
		_x('Tapoga', 'CO', 'ry-wc-city-select'),
	],
	'CO2' => [
		_x('Agatogbo', 'CO2', 'ry-wc-city-select'),
		_x('Akodeha', 'CO2', 'ry-wc-city-select'),
		_x('Come', 'CO2', 'ry-wc-city-select'),
		_x('Ouedeme-Pedah', 'CO2', 'ry-wc-city-select'),
		_x('Oumako', 'CO2', 'ry-wc-city-select'),
	],
	'COAB' => [
		_x('Agbokpa', 'COAB', 'ry-wc-city-select'),
		_x('Detohou', 'COAB', 'ry-wc-city-select'),
		_x('Djegbe', 'COAB', 'ry-wc-city-select'),
		_x('Hounli', 'COAB', 'ry-wc-city-select'),
		_x('Sehoun', 'COAB', 'ry-wc-city-select'),
		_x('Vidole', 'COAB', 'ry-wc-city-select'),
		_x('Zounzounme', 'COAB', 'ry-wc-city-select'),
	],
	'COAB2' => [
		_x('Abomey-Calavi', 'COAB2', 'ry-wc-city-select'),
		_x('Akassato', 'COAB2', 'ry-wc-city-select'),
		_x('Glo-Djigbe', 'COAB2', 'ry-wc-city-select'),
		_x('Godomey', 'COAB2', 'ry-wc-city-select'),
		_x('Hevie', 'COAB2', 'ry-wc-city-select'),
		_x('Kpanroun', 'COAB2', 'ry-wc-city-select'),
		_x('Ouedo', 'COAB2', 'ry-wc-city-select'),
		_x('Togba', 'COAB2', 'ry-wc-city-select'),
		_x('Zinvie', 'COAB2', 'ry-wc-city-select'),
	],
	'COAD' => [
		_x('Adjohoun', 'COAD', 'ry-wc-city-select'),
		_x('Akpadanou', 'COAD', 'ry-wc-city-select'),
		_x('Awonou', 'COAD', 'ry-wc-city-select'),
		_x('Azowlisse', 'COAD', 'ry-wc-city-select'),
		_x('Deme', 'COAD', 'ry-wc-city-select'),
		_x('Gangban', 'COAD', 'ry-wc-city-select'),
		_x('Kode', 'COAD', 'ry-wc-city-select'),
		_x('Togbota', 'COAD', 'ry-wc-city-select'),
	],
	'COAG' => [
		_x('Adahondjigon', 'COAG', 'ry-wc-city-select'),
		_x('Adingningon', 'COAG', 'ry-wc-city-select'),
		_x('Agbangnizoun', 'COAG', 'ry-wc-city-select'),
		_x('Kinta', 'COAG', 'ry-wc-city-select'),
		_x('Kpota', 'COAG', 'ry-wc-city-select'),
		_x('Lissazounme', 'COAG', 'ry-wc-city-select'),
		_x('Sahe', 'COAG', 'ry-wc-city-select'),
		_x('Siwe', 'COAG', 'ry-wc-city-select'),
		_x('Tanve', 'COAG', 'ry-wc-city-select'),
		_x('Zoungoudo', 'COAG', 'ry-wc-city-select'),
	],
	'COAL' => [
		_x('Agbanou', 'COAL', 'ry-wc-city-select'),
		_x('Ahouannonzoun', 'COAL', 'ry-wc-city-select'),
		_x('Allada', 'COAL', 'ry-wc-city-select'),
		_x('Attogon', 'COAL', 'ry-wc-city-select'),
		_x('Avakpa', 'COAL', 'ry-wc-city-select'),
		_x('Ayou', 'COAL', 'ry-wc-city-select'),
		_x('Hinvi', 'COAL', 'ry-wc-city-select'),
		_x('Lissegazoun', 'COAL', 'ry-wc-city-select'),
		_x('Lon-Agonmey', 'COAL', 'ry-wc-city-select'),
		_x('Sekou', 'COAL', 'ry-wc-city-select'),
		_x('Togoudo', 'COAL', 'ry-wc-city-select'),
		_x('Tokpa-Avagoudo', 'COAL', 'ry-wc-city-select'),
	],
	'COAT' => [
		_x('Adohoun', 'COAT', 'ry-wc-city-select'),
		_x('Atchannou', 'COAT', 'ry-wc-city-select'),
		_x('Athieme', 'COAT', 'ry-wc-city-select'),
		_x('Dedekpoe', 'COAT', 'ry-wc-city-select'),
		_x('Kpinnou', 'COAT', 'ry-wc-city-select'),
	],
	'COBA' => [
		_x('Banikoara', 'COBA', 'ry-wc-city-select'),
		_x('Founougo', 'COBA', 'ry-wc-city-select'),
		_x('Gomparou', 'COBA', 'ry-wc-city-select'),
		_x('Goumori', 'COBA', 'ry-wc-city-select'),
		_x('Kokey', 'COBA', 'ry-wc-city-select'),
		_x('Kokiborou', 'COBA', 'ry-wc-city-select'),
		_x('Ounet', 'COBA', 'ry-wc-city-select'),
		_x('Somperekou', 'COBA', 'ry-wc-city-select'),
		_x('Soroko', 'COBA', 'ry-wc-city-select'),
		_x('Toura', 'COBA', 'ry-wc-city-select'),
	],
	'COBA2' => [
		_x('Agoua', 'COBA2', 'ry-wc-city-select'),
		_x('Akpassi', 'COBA2', 'ry-wc-city-select'),
		_x('Atokoligbe', 'COBA2', 'ry-wc-city-select'),
		_x('Bante', 'COBA2', 'ry-wc-city-select'),
		_x('Bobe', 'COBA2', 'ry-wc-city-select'),
		_x('Gouka', 'COBA2', 'ry-wc-city-select'),
		_x('Koko', 'COBA2', 'ry-wc-city-select'),
		_x('Lougba', 'COBA2', 'ry-wc-city-select'),
		_x('Pira', 'COBA2', 'ry-wc-city-select'),
	],
	'COBO' => [
		_x('Agongointo', 'COBO', 'ry-wc-city-select'),
		_x('Avogbana', 'COBO', 'ry-wc-city-select'),
		_x('Bohicon I', 'COBO', 'ry-wc-city-select'),
		_x('Bohicon II', 'COBO', 'ry-wc-city-select'),
		_x('Gnidjazoun', 'COBO', 'ry-wc-city-select'),
		_x('Lissezoun', 'COBO', 'ry-wc-city-select'),
		_x('Ouassaho', 'COBO', 'ry-wc-city-select'),
		_x('Passagon', 'COBO', 'ry-wc-city-select'),
		_x('Saclo', 'COBO', 'ry-wc-city-select'),
		_x('Sodohome', 'COBO', 'ry-wc-city-select'),
	],
	'COBO2' => [
		_x('Agbodji', 'COBO2', 'ry-wc-city-select'),
		_x('Badazoui', 'COBO2', 'ry-wc-city-select'),
		_x('Bopa', 'COBO2', 'ry-wc-city-select'),
		_x('Gbakpodji', 'COBO2', 'ry-wc-city-select'),
		_x('Lobogo', 'COBO2', 'ry-wc-city-select'),
		_x('Possotome', 'COBO2', 'ry-wc-city-select'),
		_x('Yegodoe', 'COBO2', 'ry-wc-city-select'),
	],
	'COCO' => [
		_x('Adogbe', 'COCO', 'ry-wc-city-select'),
		_x('Gounli', 'COCO', 'ry-wc-city-select'),
		_x('Houeko', 'COCO', 'ry-wc-city-select'),
		_x('Houen-Hounso', 'COCO', 'ry-wc-city-select'),
		_x('Lainta-Cogbe', 'COCO', 'ry-wc-city-select'),
		_x('Naogon', 'COCO', 'ry-wc-city-select'),
		_x('Soli', 'COCO', 'ry-wc-city-select'),
		_x('Zogba', 'COCO', 'ry-wc-city-select'),
	],
	'CODA' => [
		_x('Akofodjoule', 'CODA', 'ry-wc-city-select'),
		_x('Dassa I', 'CODA', 'ry-wc-city-select'),
		_x('Dassa II', 'CODA', 'ry-wc-city-select'),
		_x('Gbaffo', 'CODA', 'ry-wc-city-select'),
		_x('Kere', 'CODA', 'ry-wc-city-select'),
		_x('Kpingni', 'CODA', 'ry-wc-city-select'),
		_x('Lema', 'CODA', 'ry-wc-city-select'),
		_x('Paouingnan', 'CODA', 'ry-wc-city-select'),
		_x('Soclogbo', 'CODA', 'ry-wc-city-select'),
		_x('Tre', 'CODA', 'ry-wc-city-select'),
	],
	'CODJ' => [
		_x('Agondji', 'CODJ', 'ry-wc-city-select'),
		_x('Agouna', 'CODJ', 'ry-wc-city-select'),
		_x('Dan', 'CODJ', 'ry-wc-city-select'),
		_x('Djidja', 'CODJ', 'ry-wc-city-select'),
		_x('Dohouime', 'CODJ', 'ry-wc-city-select'),
		_x('Gobe', 'CODJ', 'ry-wc-city-select'),
		_x('Monsourou', 'CODJ', 'ry-wc-city-select'),
		_x('Mougnon', 'CODJ', 'ry-wc-city-select'),
		_x('Oungbegame', 'CODJ', 'ry-wc-city-select'),
		_x('Outo', 'CODJ', 'ry-wc-city-select'),
		_x('Setto', 'CODJ', 'ry-wc-city-select'),
	],
	'CODJ2' => [
		_x('Barei', 'CODJ2', 'ry-wc-city-select'),
		_x('Barienou', 'CODJ2', 'ry-wc-city-select'),
		_x('Bellefoungou', 'CODJ2', 'ry-wc-city-select'),
		_x('Bougou', 'CODJ2', 'ry-wc-city-select'),
		_x('Djougou I', 'CODJ2', 'ry-wc-city-select'),
		_x('Djougou II', 'CODJ2', 'ry-wc-city-select'),
		_x('Djougou III', 'CODJ2', 'ry-wc-city-select'),
		_x('Kolokonde', 'CODJ2', 'ry-wc-city-select'),
		_x('Onklou', 'CODJ2', 'ry-wc-city-select'),
		_x('Patargo', 'CODJ2', 'ry-wc-city-select'),
		_x('Pelebina', 'CODJ2', 'ry-wc-city-select'),
		_x('Serou', 'CODJ2', 'ry-wc-city-select'),
	],
	'COGL' => [
		_x('Aklankpa', 'COGL', 'ry-wc-city-select'),
		_x('Assante', 'COGL', 'ry-wc-city-select'),
		_x('Glazoue', 'COGL', 'ry-wc-city-select'),
		_x('Gome', 'COGL', 'ry-wc-city-select'),
		_x('Kpakpaza', 'COGL', 'ry-wc-city-select'),
		_x('Magoumi', 'COGL', 'ry-wc-city-select'),
		_x('Ouedeme', 'COGL', 'ry-wc-city-select'),
		_x('Sokponta', 'COGL', 'ry-wc-city-select'),
		_x('Thio', 'COGL', 'ry-wc-city-select'),
		_x('Zaffe', 'COGL', 'ry-wc-city-select'),
	],
	'COHO' => [
		_x('Dahe', 'COHO', 'ry-wc-city-select'),
		_x('Doutou', 'COHO', 'ry-wc-city-select'),
		_x('Honhoue', 'COHO', 'ry-wc-city-select'),
		_x('Houeyogbe', 'COHO', 'ry-wc-city-select'),
		_x('Se', 'COHO', 'ry-wc-city-select'),
		_x('Zoungbonou', 'COHO', 'ry-wc-city-select'),
	],
	'COKE' => [
		_x('Adakplame', 'COKE', 'ry-wc-city-select'),
		_x('Idigny', 'COKE', 'ry-wc-city-select'),
		_x('Ketou', 'COKE', 'ry-wc-city-select'),
		_x('Kpankou', 'COKE', 'ry-wc-city-select'),
		_x('Odometa', 'COKE', 'ry-wc-city-select'),
		_x('Okpometa', 'COKE', 'ry-wc-city-select'),
	],
	'COKP' => [
		_x('Aganmalome', 'COKP', 'ry-wc-city-select'),
		_x('Agbanto', 'COKP', 'ry-wc-city-select'),
		_x('Agonkanme', 'COKP', 'ry-wc-city-select'),
		_x('Dedome', 'COKP', 'ry-wc-city-select'),
		_x('Dekanme', 'COKP', 'ry-wc-city-select'),
		_x('Kpomasse', 'COKP', 'ry-wc-city-select'),
		_x('Segbeya', 'COKP', 'ry-wc-city-select'),
		_x('Segbohoue', 'COKP', 'ry-wc-city-select'),
		_x('Tokpa-Dome', 'COKP', 'ry-wc-city-select'),
	],
	'COOU' => [
		_x('Challa-Ogoi', 'COOU', 'ry-wc-city-select'),
		_x('Djegbe', 'COOU', 'ry-wc-city-select'),
		_x('Gbanlin', 'COOU', 'ry-wc-city-select'),
		_x('Kemon', 'COOU', 'ry-wc-city-select'),
		_x('Kilibo', 'COOU', 'ry-wc-city-select'),
		_x('Laminou', 'COOU', 'ry-wc-city-select'),
		_x('Odougba', 'COOU', 'ry-wc-city-select'),
		_x('Ouesse', 'COOU', 'ry-wc-city-select'),
		_x('Toui', 'COOU', 'ry-wc-city-select'),
	],
	'COOU2' => [
		_x('Avlekete', 'COOU2', 'ry-wc-city-select'),
		_x('Djegbadji', 'COOU2', 'ry-wc-city-select'),
		_x('Gakpe', 'COOU2', 'ry-wc-city-select'),
		_x('Ouakpe-Daho', 'COOU2', 'ry-wc-city-select'),
		_x('Ouidah I', 'COOU2', 'ry-wc-city-select'),
		_x('Ouidah II', 'COOU2', 'ry-wc-city-select'),
		_x('Ouidah III', 'COOU2', 'ry-wc-city-select'),
		_x('Ouidah IV', 'COOU2', 'ry-wc-city-select'),
		_x('Pahou', 'COOU2', 'ry-wc-city-select'),
		_x('Savi', 'COOU2', 'ry-wc-city-select'),
	],
	'COOU3' => [
		_x('Dasso', 'COOU3', 'ry-wc-city-select'),
		_x('Ouinhi', 'COOU3', 'ry-wc-city-select'),
		_x('Sagon', 'COOU3', 'ry-wc-city-select'),
		_x('Tohoue', 'COOU3', 'ry-wc-city-select'),
	],
	'COPA' => [
		_x('1er Arrondissement', 'COPA', 'ry-wc-city-select'),
		_x('2eme Arrondissement', 'COPA', 'ry-wc-city-select'),
		_x('3eme Arrondissement', 'COPA', 'ry-wc-city-select'),
	],
	'COPO' => [
		_x('Ahoyeye', 'COPO', 'ry-wc-city-select'),
		_x('Igana', 'COPO', 'ry-wc-city-select'),
		_x('Issaba', 'COPO', 'ry-wc-city-select'),
		_x('Pobe', 'COPO', 'ry-wc-city-select'),
		_x('Towe', 'COPO', 'ry-wc-city-select'),
	],
	'COSA' => [
		_x('Aguidi', 'COSA', 'ry-wc-city-select'),
		_x('Ita-Djebou', 'COSA', 'ry-wc-city-select'),
		_x('Sakete I', 'COSA', 'ry-wc-city-select'),
		_x('Sakete II', 'COSA', 'ry-wc-city-select'),
		_x('Takon', 'COSA', 'ry-wc-city-select'),
		_x('Yoko', 'COSA', 'ry-wc-city-select'),
	],
	'COSA2' => [
		_x('Djaloukou', 'COSA2', 'ry-wc-city-select'),
		_x('Doume', 'COSA2', 'ry-wc-city-select'),
		_x('Gobada', 'COSA2', 'ry-wc-city-select'),
		_x('Kpataba', 'COSA2', 'ry-wc-city-select'),
		_x('Lahotan', 'COSA2', 'ry-wc-city-select'),
		_x('Lema', 'COSA2', 'ry-wc-city-select'),
		_x('Logozohoue', 'COSA2', 'ry-wc-city-select'),
		_x('Monkpa', 'COSA2', 'ry-wc-city-select'),
		_x('Ottola', 'COSA2', 'ry-wc-city-select'),
		_x('Savalou-Aga', 'COSA2', 'ry-wc-city-select'),
		_x('Savalou-Agbado', 'COSA2', 'ry-wc-city-select'),
		_x('Savalou-Attake', 'COSA2', 'ry-wc-city-select'),
		_x('Tchetti', 'COSA2', 'ry-wc-city-select'),
	],
	'COSA3' => [
		_x('Adido', 'COSA3', 'ry-wc-city-select'),
		_x('Besse', 'COSA3', 'ry-wc-city-select'),
		_x('Boni', 'COSA3', 'ry-wc-city-select'),
		_x('Kaboua', 'COSA3', 'ry-wc-city-select'),
		_x('Ofe', 'COSA3', 'ry-wc-city-select'),
		_x('Okpara', 'COSA3', 'ry-wc-city-select'),
		_x('Plateau', 'COSA3', 'ry-wc-city-select'),
		_x('Sakin', 'COSA3', 'ry-wc-city-select'),
	],
	'COSO' => [
		_x('Ahomey-Lokpo', 'COSO', 'ry-wc-city-select'),
		_x('Dekanmey', 'COSO', 'ry-wc-city-select'),
		_x('Ganvie I', 'COSO', 'ry-wc-city-select'),
		_x('Ganvie II', 'COSO', 'ry-wc-city-select'),
		_x('Houedo-Aguekon', 'COSO', 'ry-wc-city-select'),
		_x('So-Ava', 'COSO', 'ry-wc-city-select'),
		_x('Vekky', 'COSO', 'ry-wc-city-select'),
	],
	'COTC' => [
		_x('Alafiarou', 'COTC', 'ry-wc-city-select'),
		_x('Beterou', 'COTC', 'ry-wc-city-select'),
		_x('Goro', 'COTC', 'ry-wc-city-select'),
		_x('Kika', 'COTC', 'ry-wc-city-select'),
		_x('Sanson', 'COTC', 'ry-wc-city-select'),
		_x('Tchaourou', 'COTC', 'ry-wc-city-select'),
		_x('Tchatchou', 'COTC', 'ry-wc-city-select'),
	],
	'COTO' => [
		_x('Ague', 'COTO', 'ry-wc-city-select'),
		_x('Colli-Agbame', 'COTO', 'ry-wc-city-select'),
		_x('Coussi', 'COTO', 'ry-wc-city-select'),
		_x('Dame', 'COTO', 'ry-wc-city-select'),
		_x('Djanglanme', 'COTO', 'ry-wc-city-select'),
		_x('Houegbo', 'COTO', 'ry-wc-city-select'),
		_x('Kpome', 'COTO', 'ry-wc-city-select'),
		_x('Se', 'COTO', 'ry-wc-city-select'),
		_x('Sehoue', 'COTO', 'ry-wc-city-select'),
		_x('Toffo-Ague', 'COTO', 'ry-wc-city-select'),
	],
	'COTO2' => [
		_x('Avame', 'COTO2', 'ry-wc-city-select'),
		_x('Azohoue-Aliho', 'COTO2', 'ry-wc-city-select'),
		_x('Azohoue-Cada', 'COTO2', 'ry-wc-city-select'),
		_x('Tori-Bossito', 'COTO2', 'ry-wc-city-select'),
		_x('Tori-Cada', 'COTO2', 'ry-wc-city-select'),
		_x('Tori-Gare', 'COTO2', 'ry-wc-city-select'),
	],
	'COZA' => [
		_x('Allahe', 'COZA', 'ry-wc-city-select'),
		_x('Assalin', 'COZA', 'ry-wc-city-select'),
		_x('Houngomey', 'COZA', 'ry-wc-city-select'),
		_x('Kpakpame', 'COZA', 'ry-wc-city-select'),
		_x('Kpozoun', 'COZA', 'ry-wc-city-select'),
		_x('Za-Kpota', 'COZA', 'ry-wc-city-select'),
		_x('Za-Tanta', 'COZA', 'ry-wc-city-select'),
		_x('Zeko', 'COZA', 'ry-wc-city-select'),
	],
	'COZA2' => [
		_x('Agonli-Houegbo', 'COZA2', 'ry-wc-city-select'),
		_x('Baname', 'COZA2', 'ry-wc-city-select'),
		_x('Dovi', 'COZA2', 'ry-wc-city-select'),
		_x('Kpedekpo', 'COZA2', 'ry-wc-city-select'),
		_x('N-Tan (Don Tan)', 'COZA2', 'ry-wc-city-select'),
		_x('Zagnanado', 'COZA2', 'ry-wc-city-select'),
	],
	'CO3' => [
		_x('Adjan', 'CO3', 'ry-wc-city-select'),
		_x('Dawe', 'CO3', 'ry-wc-city-select'),
		_x('Djigbe', 'CO3', 'ry-wc-city-select'),
		_x('Dodji-Bata', 'CO3', 'ry-wc-city-select'),
		_x('Hekanme', 'CO3', 'ry-wc-city-select'),
		_x('Koundokpoe', 'CO3', 'ry-wc-city-select'),
		_x('Sedje-Denou', 'CO3', 'ry-wc-city-select'),
		_x('Sedje-Houegoudo', 'CO3', 'ry-wc-city-select'),
		_x('Tangbo-Djevie', 'CO3', 'ry-wc-city-select'),
		_x('Yokpo', 'CO3', 'ry-wc-city-select'),
	],
	'COZO' => [
		_x('Akiza', 'COZO', 'ry-wc-city-select'),
		_x('Avlame', 'COZO', 'ry-wc-city-select'),
		_x('Cana I', 'COZO', 'ry-wc-city-select'),
		_x('Cana II', 'COZO', 'ry-wc-city-select'),
		_x('Dome', 'COZO', 'ry-wc-city-select'),
		_x('Koussoukpa', 'COZO', 'ry-wc-city-select'),
		_x('Kpokissa', 'COZO', 'ry-wc-city-select'),
		_x('Massi', 'COZO', 'ry-wc-city-select'),
		_x('Tanwe-Hessou', 'COZO', 'ry-wc-city-select'),
		_x('Zogbodomey', 'COZO', 'ry-wc-city-select'),
		_x('Zoukou', 'COZO', 'ry-wc-city-select'),
	],
	'CO4' => [
		_x('Anandana', 'CO4', 'ry-wc-city-select'),
		_x('Kopargo', 'CO4', 'ry-wc-city-select'),
		_x('Pabegou', 'CO4', 'ry-wc-city-select'),
		_x('Singre', 'CO4', 'ry-wc-city-select'),
	],
	'CO5' => [
		_x('13th  Arrondissement', 'CO5', 'ry-wc-city-select'),
		_x('1st Arrondissement', 'CO5', 'ry-wc-city-select'),
		_x('2nd Arrondissement', 'CO5', 'ry-wc-city-select'),
		_x('3rd Arrondissement', 'CO5', 'ry-wc-city-select'),
		_x('7th Arrondissement', 'CO5', 'ry-wc-city-select'),
		_x('8th Arrondissement', 'CO5', 'ry-wc-city-select'),
		_x('9th Arrondissement', 'CO5', 'ry-wc-city-select'),
	],
	'DA' => [
		_x('Dangbo', 'DA', 'ry-wc-city-select'),
		_x('Dekin', 'DA', 'ry-wc-city-select'),
		_x('Gbeko', 'DA', 'ry-wc-city-select'),
		_x('Houedomey', 'DA', 'ry-wc-city-select'),
		_x('Hozin', 'DA', 'ry-wc-city-select'),
		_x('Kessounou', 'DA', 'ry-wc-city-select'),
		_x('Zoungue', 'DA', 'ry-wc-city-select'),
	],
	'DJ' => [
		_x('Adjintimey', 'DJ', 'ry-wc-city-select'),
		_x('Betoumey', 'DJ', 'ry-wc-city-select'),
		_x('Djakotomey I', 'DJ', 'ry-wc-city-select'),
		_x('Djakotomey II', 'DJ', 'ry-wc-city-select'),
		_x('Gohomey', 'DJ', 'ry-wc-city-select'),
		_x('Houegamey', 'DJ', 'ry-wc-city-select'),
		_x('Kinkinhoue', 'DJ', 'ry-wc-city-select'),
		_x('Kokohoue', 'DJ', 'ry-wc-city-select'),
		_x('Kpoba', 'DJ', 'ry-wc-city-select'),
		_x('Sokouhoue', 'DJ', 'ry-wc-city-select'),
	],
	'DOTO' => [
		_x('Deve', 'DOTO', 'ry-wc-city-select'),
		_x('Honton', 'DOTO', 'ry-wc-city-select'),
		_x('Lokogohoue', 'DOTO', 'ry-wc-city-select'),
		_x('Madjre', 'DOTO', 'ry-wc-city-select'),
		_x('Tota', 'DOTO', 'ry-wc-city-select'),
		_x('Totchagni', 'DOTO', 'ry-wc-city-select'),
	],
	'GO' => [
		_x('Bagou', 'GO', 'ry-wc-city-select'),
		_x('Gogounou', 'GO', 'ry-wc-city-select'),
		_x('Gounarou', 'GO', 'ry-wc-city-select'),
		_x('Ouara', 'GO', 'ry-wc-city-select'),
		_x('Sori', 'GO', 'ry-wc-city-select'),
		_x('Zoungou-Pantrossi', 'GO', 'ry-wc-city-select'),
	],
	'GR' => [
		_x('Adjaha', 'GR', 'ry-wc-city-select'),
		_x('Agoue', 'GR', 'ry-wc-city-select'),
		_x('Avloh', 'GR', 'ry-wc-city-select'),
		_x('Djanglanmey', 'GR', 'ry-wc-city-select'),
		_x('Gbehoue', 'GR', 'ry-wc-city-select'),
		_x('Grand-Popo', 'GR', 'ry-wc-city-select'),
		_x('Sazoue', 'GR', 'ry-wc-city-select'),
	],
	'IF' => [
		_x('Banigbe', 'IF', 'ry-wc-city-select'),
		_x('Daagbe', 'IF', 'ry-wc-city-select'),
		_x('Ifangni', 'IF', 'ry-wc-city-select'),
		_x('Ko-Koumolou', 'IF', 'ry-wc-city-select'),
		_x('Lagbe', 'IF', 'ry-wc-city-select'),
		_x('Tchaada', 'IF', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Basso', 'KA', 'ry-wc-city-select'),
		_x('Bouka', 'KA', 'ry-wc-city-select'),
		_x('Derassi', 'KA', 'ry-wc-city-select'),
		_x('Dunkassa', 'KA', 'ry-wc-city-select'),
		_x('Kalale', 'KA', 'ry-wc-city-select'),
		_x('Peonga', 'KA', 'ry-wc-city-select'),
	],
	'KA2' => [
		_x('Angaradebou', 'KA2', 'ry-wc-city-select'),
		_x('Bensekou', 'KA2', 'ry-wc-city-select'),
		_x('Donwari', 'KA2', 'ry-wc-city-select'),
		_x('Kandi I', 'KA2', 'ry-wc-city-select'),
		_x('Kandi II', 'KA2', 'ry-wc-city-select'),
		_x('Kandi III', 'KA2', 'ry-wc-city-select'),
		_x('Kassakou', 'KA2', 'ry-wc-city-select'),
		_x('Saah', 'KA2', 'ry-wc-city-select'),
		_x('Sam Arrondissement', 'KA2', 'ry-wc-city-select'),
		_x('Sonsoro', 'KA2', 'ry-wc-city-select'),
	],
	'KA3' => [
		_x('Bogo-Bogo', 'KA3', 'ry-wc-city-select'),
		_x('Karimama', 'KA3', 'ry-wc-city-select'),
		_x('Kompa', 'KA3', 'ry-wc-city-select'),
		_x('Monsey', 'KA3', 'ry-wc-city-select'),
	],
	'KE' => [
		_x('Brignamaro', 'KE', 'ry-wc-city-select'),
		_x('Firou', 'KE', 'ry-wc-city-select'),
		_x('Kerou', 'KE', 'ry-wc-city-select'),
		_x('Koabagou', 'KE', 'ry-wc-city-select'),
	],
	'KL' => [
		_x('Adjanhonme', 'KL', 'ry-wc-city-select'),
		_x('Ahogbeya', 'KL', 'ry-wc-city-select'),
		_x('Aya-Hohoue', 'KL', 'ry-wc-city-select'),
		_x('Djotto', 'KL', 'ry-wc-city-select'),
		_x('Hondji', 'KL', 'ry-wc-city-select'),
		_x('Klouekanme', 'KL', 'ry-wc-city-select'),
		_x('Lanta', 'KL', 'ry-wc-city-select'),
		_x('Tchikpe', 'KL', 'ry-wc-city-select'),
	],
	'KO' => [
		_x('Birni', 'KO', 'ry-wc-city-select'),
		_x('Chabi-Couma', 'KO', 'ry-wc-city-select'),
		_x('Fo-Tance', 'KO', 'ry-wc-city-select'),
		_x('Guilmaro', 'KO', 'ry-wc-city-select'),
		_x('Kouande', 'KO', 'ry-wc-city-select'),
		_x('Ourokayo', 'KO', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Adoukandji', 'LA', 'ry-wc-city-select'),
		_x('Ahomadegbe', 'LA', 'ry-wc-city-select'),
		_x('Ahondjinnako', 'LA', 'ry-wc-city-select'),
		_x('Banigbe', 'LA', 'ry-wc-city-select'),
		_x('Gnizounme', 'LA', 'ry-wc-city-select'),
		_x('Hlassame', 'LA', 'ry-wc-city-select'),
		_x('Lalo', 'LA', 'ry-wc-city-select'),
		_x('Lokogba', 'LA', 'ry-wc-city-select'),
		_x('Tchito', 'LA', 'ry-wc-city-select'),
		_x('Tohou', 'LA', 'ry-wc-city-select'),
		_x('Zalli', 'LA', 'ry-wc-city-select'),
	],
	'LO' => [
		_x('Agame', 'LO', 'ry-wc-city-select'),
		_x('Houedeme-Adja', 'LO', 'ry-wc-city-select'),
		_x('Houin', 'LO', 'ry-wc-city-select'),
		_x('Koudo', 'LO', 'ry-wc-city-select'),
		_x('Lokossa', 'LO', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Garou', 'MA', 'ry-wc-city-select'),
		_x('Guene', 'MA', 'ry-wc-city-select'),
		_x('Malanville', 'MA', 'ry-wc-city-select'),
		_x('Mandecali', 'MA', 'ry-wc-city-select'),
		_x('Tomboutou', 'MA', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('Dassari', 'MA2', 'ry-wc-city-select'),
		_x('Gouande', 'MA2', 'ry-wc-city-select'),
		_x('Materi', 'MA2', 'ry-wc-city-select'),
		_x('Nodi', 'MA2', 'ry-wc-city-select'),
		_x('Tantega', 'MA2', 'ry-wc-city-select'),
		_x('Tchianhoun-Cossi', 'MA2', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Kotapounga', 'NA', 'ry-wc-city-select'),
		_x('Kouaba', 'NA', 'ry-wc-city-select'),
		_x('Koundata', 'NA', 'ry-wc-city-select'),
		_x('Natitingou I', 'NA', 'ry-wc-city-select'),
		_x('Natitingou II', 'NA', 'ry-wc-city-select'),
		_x('Natitingou III', 'NA', 'ry-wc-city-select'),
		_x('Natitingou IV', 'NA', 'ry-wc-city-select'),
		_x('Perma', 'NA', 'ry-wc-city-select'),
		_x('Tchoumi-Tchoumi', 'NA', 'ry-wc-city-select'),
	],
	'ND' => [
		_x('Bori', 'ND', 'ry-wc-city-select'),
		_x('Gbegourou', 'ND', 'ry-wc-city-select'),
		_x('NDali', 'ND', 'ry-wc-city-select'),
		_x('Ouenou', 'ND', 'ry-wc-city-select'),
		_x('Sirarou', 'ND', 'ry-wc-city-select'),
	],
	'NI' => [
		_x('Biro', 'NI', 'ry-wc-city-select'),
		_x('Gnonkourakali', 'NI', 'ry-wc-city-select'),
		_x('Nikki', 'NI', 'ry-wc-city-select'),
		_x('Serekale', 'NI', 'ry-wc-city-select'),
		_x('Suya', 'NI', 'ry-wc-city-select'),
		_x('Tasso', 'NI', 'ry-wc-city-select'),
	],
	'OU' => [
		_x('Badjoude', 'OU', 'ry-wc-city-select'),
		_x('Konde', 'OU', 'ry-wc-city-select'),
		_x('Ouake', 'OU', 'ry-wc-city-select'),
		_x('Semere I', 'OU', 'ry-wc-city-select'),
		_x('Semere II', 'OU', 'ry-wc-city-select'),
		_x('Tchalinga', 'OU', 'ry-wc-city-select'),
	],
	'PE' => [
		_x('Gnemasson', 'PE', 'ry-wc-city-select'),
		_x('Tobre', 'PE', 'ry-wc-city-select'),
	],
	'PE2' => [
		_x('Gninsy', 'PE2', 'ry-wc-city-select'),
		_x('Guinagourou', 'PE2', 'ry-wc-city-select'),
		_x('Kpane', 'PE2', 'ry-wc-city-select'),
		_x('Pebie', 'PE2', 'ry-wc-city-select'),
		_x('Perere', 'PE2', 'ry-wc-city-select'),
		_x('Sontou', 'PE2', 'ry-wc-city-select'),
	],
	'PO' => [
		_x('1st arrondissement of Porto-Novo', 'PO', 'ry-wc-city-select'),
		_x('2eme Arrondissement', 'PO', 'ry-wc-city-select'),
		_x('3eme Arrondissement', 'PO', 'ry-wc-city-select'),
		_x('4eme Arrondissement', 'PO', 'ry-wc-city-select'),
		_x('5eme Arrondissement', 'PO', 'ry-wc-city-select'),
	],
	'SE' => [
		_x('Libante', 'SE', 'ry-wc-city-select'),
		_x('Liboussou', 'SE', 'ry-wc-city-select'),
		_x('Lougou', 'SE', 'ry-wc-city-select'),
		_x('Segbana', 'SE', 'ry-wc-city-select'),
		_x('Sokotindji', 'SE', 'ry-wc-city-select'),
	],
	'SE2' => [
		_x('Agblangandan', 'SE2', 'ry-wc-city-select'),
		_x('Aholouyeme', 'SE2', 'ry-wc-city-select'),
		_x('Djregbe', 'SE2', 'ry-wc-city-select'),
		_x('Ekpe', 'SE2', 'ry-wc-city-select'),
		_x('Seme-Kpodji', 'SE2', 'ry-wc-city-select'),
		_x('Tohoue', 'SE2', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Fo-Boure', 'SI', 'ry-wc-city-select'),
		_x('Sekere', 'SI', 'ry-wc-city-select'),
		_x('Sikki', 'SI', 'ry-wc-city-select'),
		_x('Sinende', 'SI', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Cotiakou', 'TA', 'ry-wc-city-select'),
		_x('NDahonta', 'TA', 'ry-wc-city-select'),
		_x('Taiakou', 'TA', 'ry-wc-city-select'),
		_x('Tanguieta', 'TA', 'ry-wc-city-select'),
		_x('Tanongou', 'TA', 'ry-wc-city-select'),
	],
	'TO' => [
		_x('Kouarfa', 'TO', 'ry-wc-city-select'),
		_x('Tampegre', 'TO', 'ry-wc-city-select'),
	],
	'TO2' => [
		_x('Adjido', 'TO2', 'ry-wc-city-select'),
		_x('Avedjin', 'TO2', 'ry-wc-city-select'),
		_x('Doko', 'TO2', 'ry-wc-city-select'),
		_x('Houedogli', 'TO2', 'ry-wc-city-select'),
		_x('Missinko', 'TO2', 'ry-wc-city-select'),
		_x('Tannou-Gola', 'TO2', 'ry-wc-city-select'),
		_x('Toviklin', 'TO2', 'ry-wc-city-select'),
	],
	]
];