<?php
/**
 * Republic of Belarus places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'BY' => [
	'BROB' => [
		_x('Baranovichskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Brestski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Byarozawski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Drahichynski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Hantsavitski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Horad Baranavichy', 'BROB', 'ry-wc-city-select'),
		_x('Horad Brest', 'BROB', 'ry-wc-city-select'),
		_x('Ivanawski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Ivatsevitski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Kamyanyetski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Kobrynski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Luninyetski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Lyakhavitski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Malarytski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Pinski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Pruzhanski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Stolinski Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Zhabinkawski Rayon', 'BROB', 'ry-wc-city-select'),
	],
	'GROB' => [
		_x('Ashmyanski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Astravyetski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Byerastavitski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Dzyatlawski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Grodnenskiy Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Horad Hrodna', 'GROB', 'ry-wc-city-select'),
		_x('Horad Lida', 'GROB', 'ry-wc-city-select'),
		_x('Horad Navahrudak', 'GROB', 'ry-wc-city-select'),
		_x('Horad Slonim', 'GROB', 'ry-wc-city-select'),
		_x('Horad Smarhon', 'GROB', 'ry-wc-city-select'),
		_x('Horad Vawkavysk', 'GROB', 'ry-wc-city-select'),
		_x('Iwyewski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Karelitski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Lidski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Mastowski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Novogrudskiy Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Shchuchynski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Slonimskiy Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Smarhonski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Svislatski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Vawkavyski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Voranawski Rayon', 'GROB', 'ry-wc-city-select'),
		_x('Zelvenskiy Rayon', 'GROB', 'ry-wc-city-select'),
	],
	'HOVO' => [
		_x('Aktsyabrski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Brahinski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Buda-Kashalyowski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Chacherski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Dobrushski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Homyelski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Horad Dobrush', 'HOVO', 'ry-wc-city-select'),
		_x('Horad Homyel', 'HOVO', 'ry-wc-city-select'),
		_x('Horad Kalinkavichy', 'HOVO', 'ry-wc-city-select'),
		_x('Horad Mazyr', 'HOVO', 'ry-wc-city-select'),
		_x('Horad Rahachow', 'HOVO', 'ry-wc-city-select'),
		_x('Horad Svyetlahorsk', 'HOVO', 'ry-wc-city-select'),
		_x('Horad Zhlobin', 'HOVO', 'ry-wc-city-select'),
		_x('Kalinkavitski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Karmyanski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Khoynitski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Loyewski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Lyelchytski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Mazyrski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Narawlyanski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Pyetrykawski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Rahachowski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Rechytski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Svyetlahorski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Uvarovichskiy Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Vyetkawski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Yelski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Zhlobinski Rayon', 'HOVO', 'ry-wc-city-select'),
		_x('Zhytkavitski Rayon', 'HOVO', 'ry-wc-city-select'),
	],
	'HOMI' => [
		_x('Frunzyenski Rayon', 'HOMI', 'ry-wc-city-select'),
		_x('Kastrychnitski Rayon', 'HOMI', 'ry-wc-city-select'),
		_x('Lyeninski Rayon', 'HOMI', 'ry-wc-city-select'),
		_x('Maskowski Rayon', 'HOMI', 'ry-wc-city-select'),
		_x('Partyzanski Rayon', 'HOMI', 'ry-wc-city-select'),
		_x('Pyershamayski Rayon', 'HOMI', 'ry-wc-city-select'),
		_x('Savyetski Rayon', 'HOMI', 'ry-wc-city-select'),
		_x('Tsentralny Rayon', 'HOMI', 'ry-wc-city-select'),
		_x('Zavodski Rayon', 'HOMI', 'ry-wc-city-select'),
	],
	'MIOB' => [
		_x('Barysaw', 'MIOB', 'ry-wc-city-select'),
		_x('Barysawski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Byarezinski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Chervyenski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Dzyarzhynski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Horad Dzyarzhynsk', 'MIOB', 'ry-wc-city-select'),
		_x('Horad Maladzyechna', 'MIOB', 'ry-wc-city-select'),
		_x('Horad Salihorsk', 'MIOB', 'ry-wc-city-select'),
		_x('Horad Slutsk', 'MIOB', 'ry-wc-city-select'),
		_x('Horad Vilyeyka', 'MIOB', 'ry-wc-city-select'),
		_x('Horad Zaslawye', 'MIOB', 'ry-wc-city-select'),
		_x('Kapylski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Klyetski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Krupski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Lahoyski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Lyubanski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Maladzyechanski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Minski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Molodechnenskij Rajon', 'MIOB', 'ry-wc-city-select'),
		_x('Myadzyelski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Nyasvizhski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Pukhavichy Raion', 'MIOB', 'ry-wc-city-select'),
		_x('Salihorski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Slutski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Smalyavitski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Staradarozhski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Stawbtsowski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Uzdzyenski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Valozhynski Rayon', 'MIOB', 'ry-wc-city-select'),
		_x('Vilyeyski Rayon', 'MIOB', 'ry-wc-city-select'),
	],
	'MOOB' => [
		_x('Asipovitski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Babruyski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Byalynitski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Bykhawski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Chavuski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Cherykawski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Drybinski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Hluski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Horad Asipovichy', 'MOOB', 'ry-wc-city-select'),
		_x('Horatski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Kastsyukovitski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Khotsimski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Kirawsk', 'MOOB', 'ry-wc-city-select'),
		_x('Kirawski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Klichawski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Klimavitski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Krasnapolski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Kruhlyanski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Krychawski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Mahilyow', 'MOOB', 'ry-wc-city-select'),
		_x('Mahilyowski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Mstsislawski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Shklowski Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Slawharadski Rayon', 'MOOB', 'ry-wc-city-select'),
	],
	'VIOB' => [
		_x('Arshanski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Braslawski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Byeshankovitski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Chashnitski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Dokshytski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Dubrovyenski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Haradotski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Hlybotski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Horad Lyepyel', 'VIOB', 'ry-wc-city-select'),
		_x('Horad Navapolatsk', 'VIOB', 'ry-wc-city-select'),
		_x('Horad Polatsk', 'VIOB', 'ry-wc-city-select'),
		_x('Horad Vitsyebsk', 'VIOB', 'ry-wc-city-select'),
		_x('Lyepyelski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Lyoznyenski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Myorski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Pastawski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Polatski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Rasonski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Sharkawshchynski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Shumilinski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Syennyenski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Talachynski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Ushatski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Vitsyebski Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Vyerkhnyadzvinski Rayon', 'VIOB', 'ry-wc-city-select'),
	],
	]
];