<?php
/**
 * Republic of Chile places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CL' => [
	'PEPR' => [
		_x('Cabildo', 'PEPR', 'ry-wc-city-select'),
		_x('La Ligua', 'PEPR', 'ry-wc-city-select'),
		_x('Papudo', 'PEPR', 'ry-wc-city-select'),
		_x('Petorca', 'PEPR', 'ry-wc-city-select'),
		_x('Zapallar', 'PEPR', 'ry-wc-city-select'),
	],
	'PRANCH' => [
		_x('Cabo de Hornos', 'PRANCH', 'ry-wc-city-select'),
		_x('Chilean Antarctic Territory', 'PRANCH', 'ry-wc-city-select'),
	],
	'PRCAPR' => [
		_x('Cochrane', 'PRCAPR', 'ry-wc-city-select'),
		_x('O Higgins', 'PRCAPR', 'ry-wc-city-select'),
		_x('Tortel', 'PRCAPR', 'ry-wc-city-select'),
	],
	'PRGECA' => [
		_x('Chile Chico', 'PRGECA', 'ry-wc-city-select'),
		_x('Rio Ibanez', 'PRGECA', 'ry-wc-city-select'),
	],
	'PRAI' => [
		_x('Aisen', 'PRAI', 'ry-wc-city-select'),
		_x('Cisnes', 'PRAI', 'ry-wc-city-select'),
		_x('Guaitecas', 'PRAI', 'ry-wc-city-select'),
	],
	'PRAN' => [
		_x('Antofagasta', 'PRAN', 'ry-wc-city-select'),
		_x('Mejillones', 'PRAN', 'ry-wc-city-select'),
		_x('Sierra Gorda', 'PRAN', 'ry-wc-city-select'),
		_x('Taltal', 'PRAN', 'ry-wc-city-select'),
	],
	'PRAR' => [
		_x('Arauco', 'PRAR', 'ry-wc-city-select'),
		_x('Canete', 'PRAR', 'ry-wc-city-select'),
		_x('Contulmo', 'PRAR', 'ry-wc-city-select'),
		_x('Curanilahue', 'PRAR', 'ry-wc-city-select'),
		_x('Lebu', 'PRAR', 'ry-wc-city-select'),
		_x('Los Alamos', 'PRAR', 'ry-wc-city-select'),
		_x('Tirua', 'PRAR', 'ry-wc-city-select'),
	],
	'PRAR2' => [
		_x('Arica', 'PRAR2', 'ry-wc-city-select'),
		_x('Camarones', 'PRAR2', 'ry-wc-city-select'),
	],
	'PRBI' => [
		_x('Alto Biobio', 'PRBI', 'ry-wc-city-select'),
		_x('Antuco', 'PRBI', 'ry-wc-city-select'),
		_x('Cabrero', 'PRBI', 'ry-wc-city-select'),
		_x('Laja', 'PRBI', 'ry-wc-city-select'),
		_x('Los Angeles', 'PRBI', 'ry-wc-city-select'),
		_x('Mulchen', 'PRBI', 'ry-wc-city-select'),
		_x('Nacimiento', 'PRBI', 'ry-wc-city-select'),
		_x('Negrete', 'PRBI', 'ry-wc-city-select'),
		_x('Quilaco', 'PRBI', 'ry-wc-city-select'),
		_x('Quilleco', 'PRBI', 'ry-wc-city-select'),
		_x('San Rosendo', 'PRBI', 'ry-wc-city-select'),
		_x('Santa Barbara', 'PRBI', 'ry-wc-city-select'),
		_x('Tucapel', 'PRBI', 'ry-wc-city-select'),
		_x('Yumbel', 'PRBI', 'ry-wc-city-select'),
	],
	'PRCA' => [
		_x('Codegua', 'PRCA', 'ry-wc-city-select'),
		_x('Coinco', 'PRCA', 'ry-wc-city-select'),
		_x('Coltauco', 'PRCA', 'ry-wc-city-select'),
		_x('Donihue', 'PRCA', 'ry-wc-city-select'),
		_x('Graneros', 'PRCA', 'ry-wc-city-select'),
		_x('Las Cabras', 'PRCA', 'ry-wc-city-select'),
		_x('Machali', 'PRCA', 'ry-wc-city-select'),
		_x('Malloa', 'PRCA', 'ry-wc-city-select'),
		_x('Mostazal', 'PRCA', 'ry-wc-city-select'),
		_x('Olivar', 'PRCA', 'ry-wc-city-select'),
		_x('Peumo', 'PRCA', 'ry-wc-city-select'),
		_x('Pichidegua', 'PRCA', 'ry-wc-city-select'),
		_x('Quinta de Tilcoco', 'PRCA', 'ry-wc-city-select'),
		_x('Rancagua', 'PRCA', 'ry-wc-city-select'),
		_x('Rengo', 'PRCA', 'ry-wc-city-select'),
		_x('Requinoa', 'PRCA', 'ry-wc-city-select'),
		_x('San Vicente', 'PRCA', 'ry-wc-city-select'),
	],
	'PRCACA' => [
		_x('La Estrella', 'PRCACA', 'ry-wc-city-select'),
		_x('Litueche', 'PRCACA', 'ry-wc-city-select'),
		_x('Marchihue', 'PRCACA', 'ry-wc-city-select'),
		_x('Navidad', 'PRCACA', 'ry-wc-city-select'),
		_x('Paredones', 'PRCACA', 'ry-wc-city-select'),
		_x('Pichilemu', 'PRCACA', 'ry-wc-city-select'),
	],
	'PRCA2' => [
		_x('Cauquenes', 'PRCA2', 'ry-wc-city-select'),
		_x('Chanco', 'PRCA2', 'ry-wc-city-select'),
		_x('Pelluhue', 'PRCA2', 'ry-wc-city-select'),
	],
	'PRCA3' => [
		_x('Carahue', 'PRCA3', 'ry-wc-city-select'),
		_x('Cholchol', 'PRCA3', 'ry-wc-city-select'),
		_x('Cunco', 'PRCA3', 'ry-wc-city-select'),
		_x('Curarrehue', 'PRCA3', 'ry-wc-city-select'),
		_x('Freire', 'PRCA3', 'ry-wc-city-select'),
		_x('Galvarino', 'PRCA3', 'ry-wc-city-select'),
		_x('Gorbea', 'PRCA3', 'ry-wc-city-select'),
		_x('Lautaro', 'PRCA3', 'ry-wc-city-select'),
		_x('Loncoche', 'PRCA3', 'ry-wc-city-select'),
		_x('Melipeuco', 'PRCA3', 'ry-wc-city-select'),
		_x('Nueva Imperial', 'PRCA3', 'ry-wc-city-select'),
		_x('Padre Las Casas', 'PRCA3', 'ry-wc-city-select'),
		_x('Perquenco', 'PRCA3', 'ry-wc-city-select'),
		_x('Pitrufquen', 'PRCA3', 'ry-wc-city-select'),
		_x('Pucon', 'PRCA3', 'ry-wc-city-select'),
		_x('Saavedra', 'PRCA3', 'ry-wc-city-select'),
		_x('Temuco', 'PRCA3', 'ry-wc-city-select'),
		_x('Teodoro Schmidt', 'PRCA3', 'ry-wc-city-select'),
		_x('Tolten', 'PRCA3', 'ry-wc-city-select'),
		_x('Vilcun', 'PRCA3', 'ry-wc-city-select'),
		_x('Villarrica', 'PRCA3', 'ry-wc-city-select'),
	],
	'PRCH' => [
		_x('Colina', 'PRCH', 'ry-wc-city-select'),
		_x('Lampa', 'PRCH', 'ry-wc-city-select'),
		_x('Tiltil', 'PRCH', 'ry-wc-city-select'),
	],
	'PRCH2' => [
		_x('Chanaral', 'PRCH2', 'ry-wc-city-select'),
		_x('Diego de Almagro', 'PRCH2', 'ry-wc-city-select'),
	],
	'PRCH3' => [
		_x('Ancud', 'PRCH3', 'ry-wc-city-select'),
		_x('Castro', 'PRCH3', 'ry-wc-city-select'),
		_x('Chonchi', 'PRCH3', 'ry-wc-city-select'),
		_x('Curaco de Velez', 'PRCH3', 'ry-wc-city-select'),
		_x('Dalcahue', 'PRCH3', 'ry-wc-city-select'),
		_x('Puqueldon', 'PRCH3', 'ry-wc-city-select'),
		_x('Queilen', 'PRCH3', 'ry-wc-city-select'),
		_x('Quellon', 'PRCH3', 'ry-wc-city-select'),
		_x('Quemchi', 'PRCH3', 'ry-wc-city-select'),
		_x('Quinchao', 'PRCH3', 'ry-wc-city-select'),
	],
	'PRCH4' => [
		_x('Canela', 'PRCH4', 'ry-wc-city-select'),
		_x('Illapel', 'PRCH4', 'ry-wc-city-select'),
		_x('Los Vilos', 'PRCH4', 'ry-wc-city-select'),
		_x('Salamanca', 'PRCH4', 'ry-wc-city-select'),
	],
	'PRCO' => [
		_x('Chepica', 'PRCO', 'ry-wc-city-select'),
		_x('Chimbarongo', 'PRCO', 'ry-wc-city-select'),
		_x('Lolol', 'PRCO', 'ry-wc-city-select'),
		_x('Nancagua', 'PRCO', 'ry-wc-city-select'),
		_x('Palmilla', 'PRCO', 'ry-wc-city-select'),
		_x('Peralillo', 'PRCO', 'ry-wc-city-select'),
		_x('Placilla', 'PRCO', 'ry-wc-city-select'),
		_x('Pumanque', 'PRCO', 'ry-wc-city-select'),
		_x('San Fernando', 'PRCO', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRCO', 'ry-wc-city-select'),
	],
	'PRCO2' => [
		_x('Chiguayante', 'PRCO2', 'ry-wc-city-select'),
		_x('Comuna de Concepcion', 'PRCO2', 'ry-wc-city-select'),
		_x('Comuna de Hualpen', 'PRCO2', 'ry-wc-city-select'),
		_x('Comuna de San Pedro de la Paz', 'PRCO2', 'ry-wc-city-select'),
		_x('Comuna de Talcahuano', 'PRCO2', 'ry-wc-city-select'),
		_x('Coronel', 'PRCO2', 'ry-wc-city-select'),
		_x('Florida', 'PRCO2', 'ry-wc-city-select'),
		_x('Hualqui', 'PRCO2', 'ry-wc-city-select'),
		_x('Lota', 'PRCO2', 'ry-wc-city-select'),
		_x('Penco', 'PRCO2', 'ry-wc-city-select'),
		_x('Santa Juana', 'PRCO2', 'ry-wc-city-select'),
		_x('Tome', 'PRCO2', 'ry-wc-city-select'),
	],
	'PRCO3' => [
		_x('Caldera', 'PRCO3', 'ry-wc-city-select'),
		_x('Copiapo', 'PRCO3', 'ry-wc-city-select'),
		_x('Tierra Amarilla', 'PRCO3', 'ry-wc-city-select'),
	],
	'PRCO4' => [
		_x('Pirque', 'PRCO4', 'ry-wc-city-select'),
		_x('Puente Alto', 'PRCO4', 'ry-wc-city-select'),
		_x('San Jose de Maipo', 'PRCO4', 'ry-wc-city-select'),
	],
	'PRCO5' => [
		_x('Coyhaique', 'PRCO5', 'ry-wc-city-select'),
		_x('Lago Verde', 'PRCO5', 'ry-wc-city-select'),
	],
	'PRCU' => [
		_x('Curico', 'PRCU', 'ry-wc-city-select'),
		_x('Hualane', 'PRCU', 'ry-wc-city-select'),
		_x('Licanten', 'PRCU', 'ry-wc-city-select'),
		_x('Molina', 'PRCU', 'ry-wc-city-select'),
		_x('Rauco', 'PRCU', 'ry-wc-city-select'),
		_x('Romeral', 'PRCU', 'ry-wc-city-select'),
		_x('Sagrada Familia', 'PRCU', 'ry-wc-city-select'),
		_x('Teno', 'PRCU', 'ry-wc-city-select'),
		_x('Vichuquen', 'PRCU', 'ry-wc-city-select'),
	],
	'PRDI' => [
		_x('Bulnes', 'PRDI', 'ry-wc-city-select'),
		_x('Chillan', 'PRDI', 'ry-wc-city-select'),
		_x('Chillan Viejo', 'PRDI', 'ry-wc-city-select'),
		_x('El Carmen', 'PRDI', 'ry-wc-city-select'),
		_x('Pemuco', 'PRDI', 'ry-wc-city-select'),
		_x('Pinto', 'PRDI', 'ry-wc-city-select'),
		_x('Quillon', 'PRDI', 'ry-wc-city-select'),
		_x('San Ignacio', 'PRDI', 'ry-wc-city-select'),
		_x('Yungay', 'PRDI', 'ry-wc-city-select'),
	],
	'PRLO' => [
		_x('Calama', 'PRLO', 'ry-wc-city-select'),
		_x('Ollague', 'PRLO', 'ry-wc-city-select'),
		_x('San Pedro de Atacama', 'PRLO', 'ry-wc-city-select'),
	],
	'PREL' => [
		_x('Andacollo', 'PREL', 'ry-wc-city-select'),
		_x('Coquimbo', 'PREL', 'ry-wc-city-select'),
		_x('La Higuera', 'PREL', 'ry-wc-city-select'),
		_x('La Serena', 'PREL', 'ry-wc-city-select'),
		_x('Paihuano', 'PREL', 'ry-wc-city-select'),
		_x('Vicuna', 'PREL', 'ry-wc-city-select'),
	],
	'PRHU' => [
		_x('Alto del Carmen', 'PRHU', 'ry-wc-city-select'),
		_x('Freirina', 'PRHU', 'ry-wc-city-select'),
		_x('Huasco', 'PRHU', 'ry-wc-city-select'),
		_x('Vallenar', 'PRHU', 'ry-wc-city-select'),
	],
	'PRIQ' => [
		_x('Alto Hospicio', 'PRIQ', 'ry-wc-city-select'),
		_x('Iquique', 'PRIQ', 'ry-wc-city-select'),
	],
	'PRISPA' => [
		_x('Isla de Pascua', 'PRISPA', 'ry-wc-city-select'),
	],
	'PRIT' => [
		_x('Cobquecura', 'PRIT', 'ry-wc-city-select'),
		_x('Coelemu', 'PRIT', 'ry-wc-city-select'),
		_x('Ninhue', 'PRIT', 'ry-wc-city-select'),
		_x('Portezuelo', 'PRIT', 'ry-wc-city-select'),
		_x('Quirihue', 'PRIT', 'ry-wc-city-select'),
		_x('Ranquil', 'PRIT', 'ry-wc-city-select'),
		_x('Treguaco', 'PRIT', 'ry-wc-city-select'),
	],
	'PRLI' => [
		_x('Combarbala', 'PRLI', 'ry-wc-city-select'),
		_x('Monte Patria', 'PRLI', 'ry-wc-city-select'),
		_x('Ovalle', 'PRLI', 'ry-wc-city-select'),
		_x('Punitaqui', 'PRLI', 'ry-wc-city-select'),
		_x('Rio Hurtado', 'PRLI', 'ry-wc-city-select'),
	],
	'PRLI2' => [
		_x('Colbun', 'PRLI2', 'ry-wc-city-select'),
		_x('Linares', 'PRLI2', 'ry-wc-city-select'),
		_x('Longavi', 'PRLI2', 'ry-wc-city-select'),
		_x('Parral', 'PRLI2', 'ry-wc-city-select'),
		_x('Retiro', 'PRLI2', 'ry-wc-city-select'),
		_x('San Javier', 'PRLI2', 'ry-wc-city-select'),
		_x('Villa Alegre', 'PRLI2', 'ry-wc-city-select'),
		_x('Yerbas Buenas', 'PRLI2', 'ry-wc-city-select'),
	],
	'PRLL' => [
		_x('Calbuco', 'PRLL', 'ry-wc-city-select'),
		_x('Cochamo', 'PRLL', 'ry-wc-city-select'),
		_x('Fresia', 'PRLL', 'ry-wc-city-select'),
		_x('Frutillar', 'PRLL', 'ry-wc-city-select'),
		_x('Llanquihue', 'PRLL', 'ry-wc-city-select'),
		_x('Los Muermos', 'PRLL', 'ry-wc-city-select'),
		_x('Maulln', 'PRLL', 'ry-wc-city-select'),
		_x('Puerto Montt', 'PRLL', 'ry-wc-city-select'),
		_x('Puerto Varas', 'PRLL', 'ry-wc-city-select'),
	],
	'PRLOAN' => [
		_x('Calle Larga', 'PRLOAN', 'ry-wc-city-select'),
		_x('Los Andes', 'PRLOAN', 'ry-wc-city-select'),
		_x('Rinconada', 'PRLOAN', 'ry-wc-city-select'),
		_x('San Esteban', 'PRLOAN', 'ry-wc-city-select'),
	],
	'PRMA' => [
		_x('Laguna Blanca', 'PRMA', 'ry-wc-city-select'),
		_x('Punta Arenas', 'PRMA', 'ry-wc-city-select'),
		_x('Rio Verde', 'PRMA', 'ry-wc-city-select'),
		_x('San Gregorio', 'PRMA', 'ry-wc-city-select'),
	],
	'PRMA2' => [
		_x('Buin', 'PRMA2', 'ry-wc-city-select'),
		_x('Calera de Tango', 'PRMA2', 'ry-wc-city-select'),
		_x('Paine', 'PRMA2', 'ry-wc-city-select'),
		_x('San Bernardo', 'PRMA2', 'ry-wc-city-select'),
	],
	'PRMA3' => [
		_x('Angol', 'PRMA3', 'ry-wc-city-select'),
		_x('Collipulli', 'PRMA3', 'ry-wc-city-select'),
		_x('Curacautin', 'PRMA3', 'ry-wc-city-select'),
		_x('Ercilla', 'PRMA3', 'ry-wc-city-select'),
		_x('Lonquimay', 'PRMA3', 'ry-wc-city-select'),
		_x('Los Sauces', 'PRMA3', 'ry-wc-city-select'),
		_x('Lumaco', 'PRMA3', 'ry-wc-city-select'),
		_x('Puren', 'PRMA3', 'ry-wc-city-select'),
		_x('Renaico', 'PRMA3', 'ry-wc-city-select'),
		_x('Traiguen', 'PRMA3', 'ry-wc-city-select'),
		_x('Victoria', 'PRMA3', 'ry-wc-city-select'),
	],
	'PRMAMA' => [
		_x('Limache', 'PRMAMA', 'ry-wc-city-select'),
		_x('Olmue', 'PRMAMA', 'ry-wc-city-select'),
		_x('Quilpue', 'PRMAMA', 'ry-wc-city-select'),
		_x('Villa Alemana', 'PRMAMA', 'ry-wc-city-select'),
	],
	'PRME' => [
		_x('Alhue', 'PRME', 'ry-wc-city-select'),
		_x('Curacavi', 'PRME', 'ry-wc-city-select'),
		_x('Maria Pinto', 'PRME', 'ry-wc-city-select'),
		_x('Melipilla', 'PRME', 'ry-wc-city-select'),
		_x('San Pedro', 'PRME', 'ry-wc-city-select'),
	],
	'PROS' => [
		_x('Osorno', 'PROS', 'ry-wc-city-select'),
		_x('Puerto Octay', 'PROS', 'ry-wc-city-select'),
		_x('Purranque', 'PROS', 'ry-wc-city-select'),
		_x('Puyehue', 'PROS', 'ry-wc-city-select'),
		_x('Rio Negro', 'PROS', 'ry-wc-city-select'),
		_x('San Juan de la Costa', 'PROS', 'ry-wc-city-select'),
		_x('San Pablo', 'PROS', 'ry-wc-city-select'),
	],
	'PRPA' => [
		_x('Chaiten', 'PRPA', 'ry-wc-city-select'),
		_x('Futaleufu', 'PRPA', 'ry-wc-city-select'),
		_x('Huailaihue', 'PRPA', 'ry-wc-city-select'),
		_x('Palena', 'PRPA', 'ry-wc-city-select'),
	],
	'PRPA2' => [
		_x('General Lagos', 'PRPA2', 'ry-wc-city-select'),
		_x('Putre', 'PRPA2', 'ry-wc-city-select'),
	],
	'PRPU' => [
		_x('Coihueco', 'PRPU', 'ry-wc-city-select'),
		_x('Niquen', 'PRPU', 'ry-wc-city-select'),
		_x('San Carlos', 'PRPU', 'ry-wc-city-select'),
		_x('San Fabian', 'PRPU', 'ry-wc-city-select'),
		_x('San Nicolas', 'PRPU', 'ry-wc-city-select'),
	],
	'PRQU' => [
		_x('Calera', 'PRQU', 'ry-wc-city-select'),
		_x('Hijuelas', 'PRQU', 'ry-wc-city-select'),
		_x('La Cruz', 'PRQU', 'ry-wc-city-select'),
		_x('Nogales', 'PRQU', 'ry-wc-city-select'),
		_x('Quillota', 'PRQU', 'ry-wc-city-select'),
	],
	'PRSAFEAC' => [
		_x('Catemu', 'PRSAFEAC', 'ry-wc-city-select'),
		_x('Llaillay', 'PRSAFEAC', 'ry-wc-city-select'),
		_x('Panquehue', 'PRSAFEAC', 'ry-wc-city-select'),
		_x('Putaendo', 'PRSAFEAC', 'ry-wc-city-select'),
		_x('San Felipe', 'PRSAFEAC', 'ry-wc-city-select'),
		_x('Santa Maria', 'PRSAFEAC', 'ry-wc-city-select'),
	],
	'PRSA' => [
		_x('Cerrillos', 'PRSA', 'ry-wc-city-select'),
		_x('Cerro Navia', 'PRSA', 'ry-wc-city-select'),
		_x('Conchali', 'PRSA', 'ry-wc-city-select'),
		_x('El Bosque', 'PRSA', 'ry-wc-city-select'),
		_x('Estacion Central', 'PRSA', 'ry-wc-city-select'),
		_x('Huechuraba', 'PRSA', 'ry-wc-city-select'),
		_x('Independencia', 'PRSA', 'ry-wc-city-select'),
		_x('La Cisterna', 'PRSA', 'ry-wc-city-select'),
		_x('La Florida', 'PRSA', 'ry-wc-city-select'),
		_x('La Granja', 'PRSA', 'ry-wc-city-select'),
		_x('La Pintana', 'PRSA', 'ry-wc-city-select'),
		_x('La Reina', 'PRSA', 'ry-wc-city-select'),
		_x('Las Condes', 'PRSA', 'ry-wc-city-select'),
		_x('Lo Barnechea', 'PRSA', 'ry-wc-city-select'),
		_x('Lo Espejo', 'PRSA', 'ry-wc-city-select'),
		_x('Lo Prado', 'PRSA', 'ry-wc-city-select'),
		_x('Macul', 'PRSA', 'ry-wc-city-select'),
		_x('Maipu', 'PRSA', 'ry-wc-city-select'),
		_x('Nunoa', 'PRSA', 'ry-wc-city-select'),
		_x('Pedro Aguirre Cerda', 'PRSA', 'ry-wc-city-select'),
		_x('Penalolen', 'PRSA', 'ry-wc-city-select'),
		_x('Providencia', 'PRSA', 'ry-wc-city-select'),
		_x('Pudahuel', 'PRSA', 'ry-wc-city-select'),
		_x('Quilicura', 'PRSA', 'ry-wc-city-select'),
		_x('Quinta Normal', 'PRSA', 'ry-wc-city-select'),
		_x('Recoleta', 'PRSA', 'ry-wc-city-select'),
		_x('Renca', 'PRSA', 'ry-wc-city-select'),
		_x('San Joaquin', 'PRSA', 'ry-wc-city-select'),
		_x('San Miguel', 'PRSA', 'ry-wc-city-select'),
		_x('San Ramon', 'PRSA', 'ry-wc-city-select'),
		_x('Santiago', 'PRSA', 'ry-wc-city-select'),
		_x('Vitacura', 'PRSA', 'ry-wc-city-select'),
	],
	'PRTA' => [
		_x('El Monte', 'PRTA', 'ry-wc-city-select'),
		_x('Isla de Maipo', 'PRTA', 'ry-wc-city-select'),
		_x('Padre Hurtado', 'PRTA', 'ry-wc-city-select'),
		_x('Penaflor', 'PRTA', 'ry-wc-city-select'),
		_x('Talagante', 'PRTA', 'ry-wc-city-select'),
	],
	'PRTA2' => [
		_x('Constitucion', 'PRTA2', 'ry-wc-city-select'),
		_x('Curepto', 'PRTA2', 'ry-wc-city-select'),
		_x('Empedrado', 'PRTA2', 'ry-wc-city-select'),
		_x('Maule', 'PRTA2', 'ry-wc-city-select'),
		_x('Pelarco', 'PRTA2', 'ry-wc-city-select'),
		_x('Pencahue', 'PRTA2', 'ry-wc-city-select'),
		_x('Rio Claro', 'PRTA2', 'ry-wc-city-select'),
		_x('San Clemente', 'PRTA2', 'ry-wc-city-select'),
		_x('San Rafael', 'PRTA2', 'ry-wc-city-select'),
		_x('Talca', 'PRTA2', 'ry-wc-city-select'),
	],
	'PRTIDEFU' => [
		_x('Porvenir', 'PRTIDEFU', 'ry-wc-city-select'),
		_x('Primavera', 'PRTIDEFU', 'ry-wc-city-select'),
		_x('Timaukel', 'PRTIDEFU', 'ry-wc-city-select'),
	],
	'PRTO' => [
		_x('Maria Elena', 'PRTO', 'ry-wc-city-select'),
		_x('Tocopilla', 'PRTO', 'ry-wc-city-select'),
	],
	'PRULES' => [
		_x('Natales', 'PRULES', 'ry-wc-city-select'),
		_x('Torres del Paine', 'PRULES', 'ry-wc-city-select'),
	],
	'PRVA' => [
		_x('Corral', 'PRVA', 'ry-wc-city-select'),
		_x('Lanco', 'PRVA', 'ry-wc-city-select'),
		_x('Los Lagos', 'PRVA', 'ry-wc-city-select'),
		_x('Mafil', 'PRVA', 'ry-wc-city-select'),
		_x('Mariquina', 'PRVA', 'ry-wc-city-select'),
		_x('Paillaco', 'PRVA', 'ry-wc-city-select'),
		_x('Panguipulli', 'PRVA', 'ry-wc-city-select'),
		_x('Valdivia', 'PRVA', 'ry-wc-city-select'),
	],
	'PRVA2' => [
		_x('Casablanca', 'PRVA2', 'ry-wc-city-select'),
		_x('Concon', 'PRVA2', 'ry-wc-city-select'),
		_x('Juan Fernandez', 'PRVA2', 'ry-wc-city-select'),
		_x('Puchuncavi', 'PRVA2', 'ry-wc-city-select'),
		_x('Quintero', 'PRVA2', 'ry-wc-city-select'),
		_x('Valparaiso', 'PRVA2', 'ry-wc-city-select'),
		_x('Vina del Mar', 'PRVA2', 'ry-wc-city-select'),
	],
	'PRDERA' => [
		_x('Futrono', 'PRDERA', 'ry-wc-city-select'),
		_x('La Union', 'PRDERA', 'ry-wc-city-select'),
		_x('Lago Ranco', 'PRDERA', 'ry-wc-city-select'),
		_x('Rio Bueno', 'PRDERA', 'ry-wc-city-select'),
	],
	'PRDETA' => [
		_x('Camina', 'PRDETA', 'ry-wc-city-select'),
		_x('Colchane', 'PRDETA', 'ry-wc-city-select'),
		_x('Huara', 'PRDETA', 'ry-wc-city-select'),
		_x('Pica', 'PRDETA', 'ry-wc-city-select'),
		_x('Pozo Almonte', 'PRDETA', 'ry-wc-city-select'),
	],
	'SAANPR' => [
		_x('Algarrobo', 'SAANPR', 'ry-wc-city-select'),
		_x('Cartagena', 'SAANPR', 'ry-wc-city-select'),
		_x('El Quisco', 'SAANPR', 'ry-wc-city-select'),
		_x('El Tabo', 'SAANPR', 'ry-wc-city-select'),
		_x('San Antonio', 'SAANPR', 'ry-wc-city-select'),
		_x('Santo Domingo', 'SAANPR', 'ry-wc-city-select'),
	],
	]
];