<?php
/**
 * Republic of Colombia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CO' => [
	'BOD.' => [
		_x('Antonio Narino', 'BOD.', 'ry-wc-city-select'),
		_x('Barrios Unidos', 'BOD.', 'ry-wc-city-select'),
		_x('Bosa', 'BOD.', 'ry-wc-city-select'),
		_x('Candelaria', 'BOD.', 'ry-wc-city-select'),
		_x('Ciudad Bolivar', 'BOD.', 'ry-wc-city-select'),
		_x('Engativa', 'BOD.', 'ry-wc-city-select'),
		_x('Fontibon', 'BOD.', 'ry-wc-city-select'),
		_x('Kennedy', 'BOD.', 'ry-wc-city-select'),
		_x('Los Martires', 'BOD.', 'ry-wc-city-select'),
		_x('Puente Aranda', 'BOD.', 'ry-wc-city-select'),
		_x('Rafael Uribe Uribe', 'BOD.', 'ry-wc-city-select'),
		_x('Santa Fe', 'BOD.', 'ry-wc-city-select'),
		_x('Suba', 'BOD.', 'ry-wc-city-select'),
		_x('Teusaquillo', 'BOD.', 'ry-wc-city-select'),
		_x('Usaquen', 'BOD.', 'ry-wc-city-select'),
		_x('Usme', 'BOD.', 'ry-wc-city-select'),
	],
	'ME' => [
		_x('Aranjuez', 'ME', 'ry-wc-city-select'),
		_x('Belen', 'ME', 'ry-wc-city-select'),
		_x('Buenos Aires', 'ME', 'ry-wc-city-select'),
		_x('Castilla', 'ME', 'ry-wc-city-select'),
		_x('Doce de Octubre', 'ME', 'ry-wc-city-select'),
		_x('El Poblado', 'ME', 'ry-wc-city-select'),
		_x('Guayabal', 'ME', 'ry-wc-city-select'),
		_x('La America', 'ME', 'ry-wc-city-select'),
		_x('La Candelaria', 'ME', 'ry-wc-city-select'),
		_x('Laureles Estadio', 'ME', 'ry-wc-city-select'),
		_x('Manrique', 'ME', 'ry-wc-city-select'),
		_x('Popular', 'ME', 'ry-wc-city-select'),
		_x('Robledo', 'ME', 'ry-wc-city-select'),
		_x('San Javier', 'ME', 'ry-wc-city-select'),
		_x('Santa Cruz', 'ME', 'ry-wc-city-select'),
		_x('Villa Hermosa', 'ME', 'ry-wc-city-select'),
	],
	'AM' => [
		_x('El Encanto', 'AM', 'ry-wc-city-select'),
		_x('La Chorrera', 'AM', 'ry-wc-city-select'),
		_x('La Pedrera', 'AM', 'ry-wc-city-select'),
		_x('La Victoria', 'AM', 'ry-wc-city-select'),
		_x('Leticia', 'AM', 'ry-wc-city-select'),
		_x('Miriti - Parana', 'AM', 'ry-wc-city-select'),
		_x('Puerto Alegria', 'AM', 'ry-wc-city-select'),
		_x('Puerto Arica', 'AM', 'ry-wc-city-select'),
		_x('Puerto Narino', 'AM', 'ry-wc-city-select'),
		_x('Puerto Santander', 'AM', 'ry-wc-city-select'),
		_x('Tarapaca', 'AM', 'ry-wc-city-select'),
	],
	'DEAN' => [
		_x('Abejorral', 'DEAN', 'ry-wc-city-select'),
		_x('Abriaqui', 'DEAN', 'ry-wc-city-select'),
		_x('Alejandria', 'DEAN', 'ry-wc-city-select'),
		_x('Amaga', 'DEAN', 'ry-wc-city-select'),
		_x('Amalfi', 'DEAN', 'ry-wc-city-select'),
		_x('Andes', 'DEAN', 'ry-wc-city-select'),
		_x('Angelopolis', 'DEAN', 'ry-wc-city-select'),
		_x('Angostura', 'DEAN', 'ry-wc-city-select'),
		_x('Anori', 'DEAN', 'ry-wc-city-select'),
		_x('Anza', 'DEAN', 'ry-wc-city-select'),
		_x('Apartado', 'DEAN', 'ry-wc-city-select'),
		_x('Arboletes', 'DEAN', 'ry-wc-city-select'),
		_x('Argelia', 'DEAN', 'ry-wc-city-select'),
		_x('Armenia', 'DEAN', 'ry-wc-city-select'),
		_x('Barbosa', 'DEAN', 'ry-wc-city-select'),
		_x('Bello', 'DEAN', 'ry-wc-city-select'),
		_x('Belmira', 'DEAN', 'ry-wc-city-select'),
		_x('Betania', 'DEAN', 'ry-wc-city-select'),
		_x('Betulia', 'DEAN', 'ry-wc-city-select'),
		_x('Briceno', 'DEAN', 'ry-wc-city-select'),
		_x('Buritica', 'DEAN', 'ry-wc-city-select'),
		_x('Caceres', 'DEAN', 'ry-wc-city-select'),
		_x('Caicedo', 'DEAN', 'ry-wc-city-select'),
		_x('Caldas', 'DEAN', 'ry-wc-city-select'),
		_x('Campamento', 'DEAN', 'ry-wc-city-select'),
		_x('Canasgordas', 'DEAN', 'ry-wc-city-select'),
		_x('Caracoli', 'DEAN', 'ry-wc-city-select'),
		_x('Caramanta', 'DEAN', 'ry-wc-city-select'),
		_x('Carepa', 'DEAN', 'ry-wc-city-select'),
		_x('Carolina', 'DEAN', 'ry-wc-city-select'),
		_x('Caucasia', 'DEAN', 'ry-wc-city-select'),
		_x('Chigorodo', 'DEAN', 'ry-wc-city-select'),
		_x('Cisneros', 'DEAN', 'ry-wc-city-select'),
		_x('Ciudad Bolivar', 'DEAN', 'ry-wc-city-select'),
		_x('Cocorna', 'DEAN', 'ry-wc-city-select'),
		_x('Concepcion', 'DEAN', 'ry-wc-city-select'),
		_x('Concordia', 'DEAN', 'ry-wc-city-select'),
		_x('Copacabana', 'DEAN', 'ry-wc-city-select'),
		_x('Dabeiba', 'DEAN', 'ry-wc-city-select'),
		_x('Don Matias', 'DEAN', 'ry-wc-city-select'),
		_x('Ebejico', 'DEAN', 'ry-wc-city-select'),
		_x('El Bagre', 'DEAN', 'ry-wc-city-select'),
		_x('El Carmen de Viboral', 'DEAN', 'ry-wc-city-select'),
		_x('El Santuario', 'DEAN', 'ry-wc-city-select'),
		_x('Entrerrios', 'DEAN', 'ry-wc-city-select'),
		_x('Envigado', 'DEAN', 'ry-wc-city-select'),
		_x('Fredonia', 'DEAN', 'ry-wc-city-select'),
		_x('Frontino', 'DEAN', 'ry-wc-city-select'),
		_x('Giraldo', 'DEAN', 'ry-wc-city-select'),
		_x('Girardota', 'DEAN', 'ry-wc-city-select'),
		_x('Gomez Plata', 'DEAN', 'ry-wc-city-select'),
		_x('Granada', 'DEAN', 'ry-wc-city-select'),
		_x('Guadalupe', 'DEAN', 'ry-wc-city-select'),
		_x('Guarne', 'DEAN', 'ry-wc-city-select'),
		_x('Guatape', 'DEAN', 'ry-wc-city-select'),
		_x('Heliconia', 'DEAN', 'ry-wc-city-select'),
		_x('Hispania', 'DEAN', 'ry-wc-city-select'),
		_x('Itagui', 'DEAN', 'ry-wc-city-select'),
		_x('Ituango', 'DEAN', 'ry-wc-city-select'),
		_x('Jardin', 'DEAN', 'ry-wc-city-select'),
		_x('Jerico', 'DEAN', 'ry-wc-city-select'),
		_x('La Ceja', 'DEAN', 'ry-wc-city-select'),
		_x('La Estrella', 'DEAN', 'ry-wc-city-select'),
		_x('La Pintada', 'DEAN', 'ry-wc-city-select'),
		_x('La Union', 'DEAN', 'ry-wc-city-select'),
		_x('Liborina', 'DEAN', 'ry-wc-city-select'),
		_x('Maceo', 'DEAN', 'ry-wc-city-select'),
		_x('Marinilla', 'DEAN', 'ry-wc-city-select'),
		_x('Montebello', 'DEAN', 'ry-wc-city-select'),
		_x('Municipio de San Pedro de los Milagros', 'DEAN', 'ry-wc-city-select'),
		_x('Murindo', 'DEAN', 'ry-wc-city-select'),
		_x('Mutata', 'DEAN', 'ry-wc-city-select'),
		_x('Narino', 'DEAN', 'ry-wc-city-select'),
		_x('Nechi', 'DEAN', 'ry-wc-city-select'),
		_x('Necocli', 'DEAN', 'ry-wc-city-select'),
		_x('Olaya', 'DEAN', 'ry-wc-city-select'),
		_x('Penol', 'DEAN', 'ry-wc-city-select'),
		_x('Peque', 'DEAN', 'ry-wc-city-select'),
		_x('Pueblorrico', 'DEAN', 'ry-wc-city-select'),
		_x('Puerto Berrio', 'DEAN', 'ry-wc-city-select'),
		_x('Puerto Nare', 'DEAN', 'ry-wc-city-select'),
		_x('Puerto Triunfo', 'DEAN', 'ry-wc-city-select'),
		_x('Remedios', 'DEAN', 'ry-wc-city-select'),
		_x('Retiro', 'DEAN', 'ry-wc-city-select'),
		_x('Rionegro', 'DEAN', 'ry-wc-city-select'),
		_x('Sabanalarga', 'DEAN', 'ry-wc-city-select'),
		_x('Sabaneta', 'DEAN', 'ry-wc-city-select'),
		_x('Salgar', 'DEAN', 'ry-wc-city-select'),
		_x('San Andres de Cuerquia', 'DEAN', 'ry-wc-city-select'),
		_x('San Carlos', 'DEAN', 'ry-wc-city-select'),
		_x('San Francisco', 'DEAN', 'ry-wc-city-select'),
		_x('San Jeronimo', 'DEAN', 'ry-wc-city-select'),
		_x('San Jose de La Montana', 'DEAN', 'ry-wc-city-select'),
		_x('San Juan de Uraba', 'DEAN', 'ry-wc-city-select'),
		_x('San Luis', 'DEAN', 'ry-wc-city-select'),
		_x('San Pedro de Uraba', 'DEAN', 'ry-wc-city-select'),
		_x('San Rafael', 'DEAN', 'ry-wc-city-select'),
		_x('San Roque', 'DEAN', 'ry-wc-city-select'),
		_x('San Vicente Ferrer', 'DEAN', 'ry-wc-city-select'),
		_x('Santa Barbara', 'DEAN', 'ry-wc-city-select'),
		_x('Santa Rosa de Osos', 'DEAN', 'ry-wc-city-select'),
		_x('Santafe de Antioquia', 'DEAN', 'ry-wc-city-select'),
		_x('Santo Domingo', 'DEAN', 'ry-wc-city-select'),
		_x('Segovia', 'DEAN', 'ry-wc-city-select'),
		_x('Sonson', 'DEAN', 'ry-wc-city-select'),
		_x('Sopetran', 'DEAN', 'ry-wc-city-select'),
		_x('Tamesis', 'DEAN', 'ry-wc-city-select'),
		_x('Taraza', 'DEAN', 'ry-wc-city-select'),
		_x('Tarso', 'DEAN', 'ry-wc-city-select'),
		_x('Titiribi', 'DEAN', 'ry-wc-city-select'),
		_x('Toledo', 'DEAN', 'ry-wc-city-select'),
		_x('Turbo', 'DEAN', 'ry-wc-city-select'),
		_x('Uramita', 'DEAN', 'ry-wc-city-select'),
		_x('Urrao', 'DEAN', 'ry-wc-city-select'),
		_x('Valdivia', 'DEAN', 'ry-wc-city-select'),
		_x('Valparaiso', 'DEAN', 'ry-wc-city-select'),
		_x('Vegachi', 'DEAN', 'ry-wc-city-select'),
		_x('Venecia', 'DEAN', 'ry-wc-city-select'),
		_x('Vigia del Fuerte', 'DEAN', 'ry-wc-city-select'),
		_x('Yali', 'DEAN', 'ry-wc-city-select'),
		_x('Yarumal', 'DEAN', 'ry-wc-city-select'),
		_x('Yolombo', 'DEAN', 'ry-wc-city-select'),
		_x('Yondo', 'DEAN', 'ry-wc-city-select'),
		_x('Zaragoza', 'DEAN', 'ry-wc-city-select'),
	],
	'DEAR' => [
		_x('Arauca', 'DEAR', 'ry-wc-city-select'),
		_x('Arauquita', 'DEAR', 'ry-wc-city-select'),
		_x('Cravo Norte', 'DEAR', 'ry-wc-city-select'),
		_x('Fortul', 'DEAR', 'ry-wc-city-select'),
		_x('Puerto Rondon', 'DEAR', 'ry-wc-city-select'),
		_x('Saravena', 'DEAR', 'ry-wc-city-select'),
		_x('Tame', 'DEAR', 'ry-wc-city-select'),
	],
	'DEBO' => [
		_x('Achi', 'DEBO', 'ry-wc-city-select'),
		_x('Altos del Rosario', 'DEBO', 'ry-wc-city-select'),
		_x('Arenal', 'DEBO', 'ry-wc-city-select'),
		_x('Arjona', 'DEBO', 'ry-wc-city-select'),
		_x('Arroyohondo', 'DEBO', 'ry-wc-city-select'),
		_x('Barranco de Loba', 'DEBO', 'ry-wc-city-select'),
		_x('Calamar', 'DEBO', 'ry-wc-city-select'),
		_x('Cantagallo', 'DEBO', 'ry-wc-city-select'),
		_x('Cicuco', 'DEBO', 'ry-wc-city-select'),
		_x('Clemencia', 'DEBO', 'ry-wc-city-select'),
		_x('Cordoba', 'DEBO', 'ry-wc-city-select'),
		_x('El Carmen de Bolivar', 'DEBO', 'ry-wc-city-select'),
		_x('El Guamo', 'DEBO', 'ry-wc-city-select'),
		_x('El Penon', 'DEBO', 'ry-wc-city-select'),
		_x('Hatillo de Loba', 'DEBO', 'ry-wc-city-select'),
		_x('Magangue', 'DEBO', 'ry-wc-city-select'),
		_x('Mahates', 'DEBO', 'ry-wc-city-select'),
		_x('Margarita', 'DEBO', 'ry-wc-city-select'),
		_x('Mompos', 'DEBO', 'ry-wc-city-select'),
		_x('Montecristo', 'DEBO', 'ry-wc-city-select'),
		_x('Morales', 'DEBO', 'ry-wc-city-select'),
		_x('Municipio de Cartagena de Indias', 'DEBO', 'ry-wc-city-select'),
		_x('Municipio de Maria la Baja', 'DEBO', 'ry-wc-city-select'),
		_x('Norosi', 'DEBO', 'ry-wc-city-select'),
		_x('Pinillos', 'DEBO', 'ry-wc-city-select'),
		_x('Regidor', 'DEBO', 'ry-wc-city-select'),
		_x('Rio Viejo', 'DEBO', 'ry-wc-city-select'),
		_x('San Cristobal', 'DEBO', 'ry-wc-city-select'),
		_x('San Estanislao', 'DEBO', 'ry-wc-city-select'),
		_x('San Fernando', 'DEBO', 'ry-wc-city-select'),
		_x('San Jacinto', 'DEBO', 'ry-wc-city-select'),
		_x('San Jacinto del Cauca', 'DEBO', 'ry-wc-city-select'),
		_x('San Juan Nepomuceno', 'DEBO', 'ry-wc-city-select'),
		_x('San Martin de Loba', 'DEBO', 'ry-wc-city-select'),
		_x('San Pablo', 'DEBO', 'ry-wc-city-select'),
		_x('Santa Catalina', 'DEBO', 'ry-wc-city-select'),
		_x('Santa Rosa', 'DEBO', 'ry-wc-city-select'),
		_x('Santa Rosa del Sur', 'DEBO', 'ry-wc-city-select'),
		_x('Simiti', 'DEBO', 'ry-wc-city-select'),
		_x('Soplaviento', 'DEBO', 'ry-wc-city-select'),
		_x('Talaigua Nuevo', 'DEBO', 'ry-wc-city-select'),
		_x('Tiquisio', 'DEBO', 'ry-wc-city-select'),
		_x('Turbaco', 'DEBO', 'ry-wc-city-select'),
		_x('Turbana', 'DEBO', 'ry-wc-city-select'),
		_x('Villanueva', 'DEBO', 'ry-wc-city-select'),
		_x('Zambrano', 'DEBO', 'ry-wc-city-select'),
	],
	'DEBO2' => [
		_x('Almeida', 'DEBO2', 'ry-wc-city-select'),
		_x('Aquitania', 'DEBO2', 'ry-wc-city-select'),
		_x('Arcabuco', 'DEBO2', 'ry-wc-city-select'),
		_x('Belen', 'DEBO2', 'ry-wc-city-select'),
		_x('Berbeo', 'DEBO2', 'ry-wc-city-select'),
		_x('Beteitiva', 'DEBO2', 'ry-wc-city-select'),
		_x('Boavita', 'DEBO2', 'ry-wc-city-select'),
		_x('Boyaca', 'DEBO2', 'ry-wc-city-select'),
		_x('Briceno', 'DEBO2', 'ry-wc-city-select'),
		_x('Buenavista', 'DEBO2', 'ry-wc-city-select'),
		_x('Busbanza', 'DEBO2', 'ry-wc-city-select'),
		_x('Caldas', 'DEBO2', 'ry-wc-city-select'),
		_x('Campohermoso', 'DEBO2', 'ry-wc-city-select'),
		_x('Cerinza', 'DEBO2', 'ry-wc-city-select'),
		_x('Chinavita', 'DEBO2', 'ry-wc-city-select'),
		_x('Chiquinquira', 'DEBO2', 'ry-wc-city-select'),
		_x('Chiquiza', 'DEBO2', 'ry-wc-city-select'),
		_x('Chiscas', 'DEBO2', 'ry-wc-city-select'),
		_x('Chita', 'DEBO2', 'ry-wc-city-select'),
		_x('Chitaraque', 'DEBO2', 'ry-wc-city-select'),
		_x('Chivata', 'DEBO2', 'ry-wc-city-select'),
		_x('Chivor', 'DEBO2', 'ry-wc-city-select'),
		_x('Cienega', 'DEBO2', 'ry-wc-city-select'),
		_x('Combita', 'DEBO2', 'ry-wc-city-select'),
		_x('Coper', 'DEBO2', 'ry-wc-city-select'),
		_x('Corrales', 'DEBO2', 'ry-wc-city-select'),
		_x('Covarachia', 'DEBO2', 'ry-wc-city-select'),
		_x('Cubara', 'DEBO2', 'ry-wc-city-select'),
		_x('Cucaita', 'DEBO2', 'ry-wc-city-select'),
		_x('Cuitiva', 'DEBO2', 'ry-wc-city-select'),
		_x('Duitama', 'DEBO2', 'ry-wc-city-select'),
		_x('El Cocuy', 'DEBO2', 'ry-wc-city-select'),
		_x('El Espino', 'DEBO2', 'ry-wc-city-select'),
		_x('Firavitoba', 'DEBO2', 'ry-wc-city-select'),
		_x('Floresta', 'DEBO2', 'ry-wc-city-select'),
		_x('Gachantiva', 'DEBO2', 'ry-wc-city-select'),
		_x('Gameza', 'DEBO2', 'ry-wc-city-select'),
		_x('Garagoa', 'DEBO2', 'ry-wc-city-select'),
		_x('Guacamayas', 'DEBO2', 'ry-wc-city-select'),
		_x('Guateque', 'DEBO2', 'ry-wc-city-select'),
		_x('Guayata', 'DEBO2', 'ry-wc-city-select'),
		_x('Gueican', 'DEBO2', 'ry-wc-city-select'),
		_x('Iza', 'DEBO2', 'ry-wc-city-select'),
		_x('Jenesano', 'DEBO2', 'ry-wc-city-select'),
		_x('Jerico', 'DEBO2', 'ry-wc-city-select'),
		_x('La Capilla', 'DEBO2', 'ry-wc-city-select'),
		_x('La Uvita', 'DEBO2', 'ry-wc-city-select'),
		_x('La Victoria', 'DEBO2', 'ry-wc-city-select'),
		_x('Labranzagrande', 'DEBO2', 'ry-wc-city-select'),
		_x('Macanal', 'DEBO2', 'ry-wc-city-select'),
		_x('Maripi', 'DEBO2', 'ry-wc-city-select'),
		_x('Miraflores', 'DEBO2', 'ry-wc-city-select'),
		_x('Mongua', 'DEBO2', 'ry-wc-city-select'),
		_x('Mongui', 'DEBO2', 'ry-wc-city-select'),
		_x('Moniquira', 'DEBO2', 'ry-wc-city-select'),
		_x('Motavita', 'DEBO2', 'ry-wc-city-select'),
		_x('Muzo', 'DEBO2', 'ry-wc-city-select'),
		_x('Nobsa', 'DEBO2', 'ry-wc-city-select'),
		_x('Nuevo Colon', 'DEBO2', 'ry-wc-city-select'),
		_x('Oicata', 'DEBO2', 'ry-wc-city-select'),
		_x('Otanche', 'DEBO2', 'ry-wc-city-select'),
		_x('Pachavita', 'DEBO2', 'ry-wc-city-select'),
		_x('Paez', 'DEBO2', 'ry-wc-city-select'),
		_x('Paipa', 'DEBO2', 'ry-wc-city-select'),
		_x('Pajarito', 'DEBO2', 'ry-wc-city-select'),
		_x('Panqueba', 'DEBO2', 'ry-wc-city-select'),
		_x('Pauna', 'DEBO2', 'ry-wc-city-select'),
		_x('Paya', 'DEBO2', 'ry-wc-city-select'),
		_x('Paz de Rio', 'DEBO2', 'ry-wc-city-select'),
		_x('Pesca', 'DEBO2', 'ry-wc-city-select'),
		_x('Pisba', 'DEBO2', 'ry-wc-city-select'),
		_x('Puerto Boyaca', 'DEBO2', 'ry-wc-city-select'),
		_x('Quipama', 'DEBO2', 'ry-wc-city-select'),
		_x('Ramiriqui', 'DEBO2', 'ry-wc-city-select'),
		_x('Raquira', 'DEBO2', 'ry-wc-city-select'),
		_x('Rondon', 'DEBO2', 'ry-wc-city-select'),
		_x('Saboya', 'DEBO2', 'ry-wc-city-select'),
		_x('Sachica', 'DEBO2', 'ry-wc-city-select'),
		_x('Samaca', 'DEBO2', 'ry-wc-city-select'),
		_x('San Eduardo', 'DEBO2', 'ry-wc-city-select'),
		_x('San Jose de Pare', 'DEBO2', 'ry-wc-city-select'),
		_x('San Luis de Gaceno', 'DEBO2', 'ry-wc-city-select'),
		_x('San Mateo', 'DEBO2', 'ry-wc-city-select'),
		_x('San Miguel de Sema', 'DEBO2', 'ry-wc-city-select'),
		_x('San Pablo de Borbur', 'DEBO2', 'ry-wc-city-select'),
		_x('Santa Maria', 'DEBO2', 'ry-wc-city-select'),
		_x('Santa Rosa de Viterbo', 'DEBO2', 'ry-wc-city-select'),
		_x('Santa Sofia', 'DEBO2', 'ry-wc-city-select'),
		_x('Santana', 'DEBO2', 'ry-wc-city-select'),
		_x('Sativanorte', 'DEBO2', 'ry-wc-city-select'),
		_x('Sativasur', 'DEBO2', 'ry-wc-city-select'),
		_x('Siachoque', 'DEBO2', 'ry-wc-city-select'),
		_x('Soata', 'DEBO2', 'ry-wc-city-select'),
		_x('Socha', 'DEBO2', 'ry-wc-city-select'),
		_x('Socota', 'DEBO2', 'ry-wc-city-select'),
		_x('Sogamoso', 'DEBO2', 'ry-wc-city-select'),
		_x('Somondoco', 'DEBO2', 'ry-wc-city-select'),
		_x('Sora', 'DEBO2', 'ry-wc-city-select'),
		_x('Soraca', 'DEBO2', 'ry-wc-city-select'),
		_x('Sotaquira', 'DEBO2', 'ry-wc-city-select'),
		_x('Susacon', 'DEBO2', 'ry-wc-city-select'),
		_x('Sutamarchan', 'DEBO2', 'ry-wc-city-select'),
		_x('Sutatenza', 'DEBO2', 'ry-wc-city-select'),
		_x('Tasco', 'DEBO2', 'ry-wc-city-select'),
		_x('Tenza', 'DEBO2', 'ry-wc-city-select'),
		_x('Tibana', 'DEBO2', 'ry-wc-city-select'),
		_x('Tibasosa', 'DEBO2', 'ry-wc-city-select'),
		_x('Tinjaca', 'DEBO2', 'ry-wc-city-select'),
		_x('Tipacoque', 'DEBO2', 'ry-wc-city-select'),
		_x('Toca', 'DEBO2', 'ry-wc-city-select'),
		_x('Toguei', 'DEBO2', 'ry-wc-city-select'),
		_x('Topaga', 'DEBO2', 'ry-wc-city-select'),
		_x('Tota', 'DEBO2', 'ry-wc-city-select'),
		_x('Tunja', 'DEBO2', 'ry-wc-city-select'),
		_x('Tunungua', 'DEBO2', 'ry-wc-city-select'),
		_x('Turmeque', 'DEBO2', 'ry-wc-city-select'),
		_x('Tuta', 'DEBO2', 'ry-wc-city-select'),
		_x('Tutaza', 'DEBO2', 'ry-wc-city-select'),
		_x('Umbita', 'DEBO2', 'ry-wc-city-select'),
		_x('Ventaquemada', 'DEBO2', 'ry-wc-city-select'),
		_x('Villa de Leyva', 'DEBO2', 'ry-wc-city-select'),
		_x('Viracacha', 'DEBO2', 'ry-wc-city-select'),
		_x('Zetaquira', 'DEBO2', 'ry-wc-city-select'),
	],
	'DECA' => [
		_x('Aguadas', 'DECA', 'ry-wc-city-select'),
		_x('Anserma', 'DECA', 'ry-wc-city-select'),
		_x('Aranzazu', 'DECA', 'ry-wc-city-select'),
		_x('Belalcazar', 'DECA', 'ry-wc-city-select'),
		_x('Chinchina', 'DECA', 'ry-wc-city-select'),
		_x('Filadelfia', 'DECA', 'ry-wc-city-select'),
		_x('La Dorada', 'DECA', 'ry-wc-city-select'),
		_x('La Merced', 'DECA', 'ry-wc-city-select'),
		_x('Manizales', 'DECA', 'ry-wc-city-select'),
		_x('Manzanares', 'DECA', 'ry-wc-city-select'),
		_x('Marmato', 'DECA', 'ry-wc-city-select'),
		_x('Marquetalia', 'DECA', 'ry-wc-city-select'),
		_x('Marulanda', 'DECA', 'ry-wc-city-select'),
		_x('Neira', 'DECA', 'ry-wc-city-select'),
		_x('Norcasia', 'DECA', 'ry-wc-city-select'),
		_x('Pacora', 'DECA', 'ry-wc-city-select'),
		_x('Palestina', 'DECA', 'ry-wc-city-select'),
		_x('Pensilvania', 'DECA', 'ry-wc-city-select'),
		_x('Riosucio', 'DECA', 'ry-wc-city-select'),
		_x('Risaralda', 'DECA', 'ry-wc-city-select'),
		_x('Salamina', 'DECA', 'ry-wc-city-select'),
		_x('Samana', 'DECA', 'ry-wc-city-select'),
		_x('San Jose', 'DECA', 'ry-wc-city-select'),
		_x('Supia', 'DECA', 'ry-wc-city-select'),
		_x('Victoria', 'DECA', 'ry-wc-city-select'),
		_x('Villamaria', 'DECA', 'ry-wc-city-select'),
		_x('Viterbo', 'DECA', 'ry-wc-city-select'),
	],
	'DECA2' => [
		_x('Aguazul', 'DECA2', 'ry-wc-city-select'),
		_x('Chameza', 'DECA2', 'ry-wc-city-select'),
		_x('Hato Corozal', 'DECA2', 'ry-wc-city-select'),
		_x('La Salina', 'DECA2', 'ry-wc-city-select'),
		_x('Mani', 'DECA2', 'ry-wc-city-select'),
		_x('Monterrey', 'DECA2', 'ry-wc-city-select'),
		_x('Nunchia', 'DECA2', 'ry-wc-city-select'),
		_x('Orocue', 'DECA2', 'ry-wc-city-select'),
		_x('Paz de Ariporo', 'DECA2', 'ry-wc-city-select'),
		_x('Pore', 'DECA2', 'ry-wc-city-select'),
		_x('Recetor', 'DECA2', 'ry-wc-city-select'),
		_x('Sabanalarga', 'DECA2', 'ry-wc-city-select'),
		_x('Sacama', 'DECA2', 'ry-wc-city-select'),
		_x('San Luis de Palenque', 'DECA2', 'ry-wc-city-select'),
		_x('Tamara', 'DECA2', 'ry-wc-city-select'),
		_x('Tauramena', 'DECA2', 'ry-wc-city-select'),
		_x('Trinidad', 'DECA2', 'ry-wc-city-select'),
		_x('Villanueva', 'DECA2', 'ry-wc-city-select'),
		_x('Yopal', 'DECA2', 'ry-wc-city-select'),
	],
	'DECO' => [
		_x('Ayapel', 'DECO', 'ry-wc-city-select'),
		_x('Buenavista', 'DECO', 'ry-wc-city-select'),
		_x('Canalete', 'DECO', 'ry-wc-city-select'),
		_x('Cerete', 'DECO', 'ry-wc-city-select'),
		_x('Chima', 'DECO', 'ry-wc-city-select'),
		_x('Chinu', 'DECO', 'ry-wc-city-select'),
		_x('Cienaga de Oro', 'DECO', 'ry-wc-city-select'),
		_x('Cotorra', 'DECO', 'ry-wc-city-select'),
		_x('La Apartada', 'DECO', 'ry-wc-city-select'),
		_x('Lorica', 'DECO', 'ry-wc-city-select'),
		_x('Los Cordobas', 'DECO', 'ry-wc-city-select'),
		_x('Momil', 'DECO', 'ry-wc-city-select'),
		_x('Monitos', 'DECO', 'ry-wc-city-select'),
		_x('Montelibano', 'DECO', 'ry-wc-city-select'),
		_x('Monteria', 'DECO', 'ry-wc-city-select'),
		_x('Planeta Rica', 'DECO', 'ry-wc-city-select'),
		_x('Pueblo Nuevo', 'DECO', 'ry-wc-city-select'),
		_x('Puerto Escondido', 'DECO', 'ry-wc-city-select'),
		_x('Puerto Libertador', 'DECO', 'ry-wc-city-select'),
		_x('Purisima', 'DECO', 'ry-wc-city-select'),
		_x('Sahagun', 'DECO', 'ry-wc-city-select'),
		_x('San Andres Sotavento', 'DECO', 'ry-wc-city-select'),
		_x('San Antero', 'DECO', 'ry-wc-city-select'),
		_x('San Bernardo del Viento', 'DECO', 'ry-wc-city-select'),
		_x('San Carlos', 'DECO', 'ry-wc-city-select'),
		_x('San Jose De Ure', 'DECO', 'ry-wc-city-select'),
		_x('San Pelayo', 'DECO', 'ry-wc-city-select'),
		_x('Tierralta', 'DECO', 'ry-wc-city-select'),
		_x('Tuchin', 'DECO', 'ry-wc-city-select'),
		_x('Valencia', 'DECO', 'ry-wc-city-select'),
	],
	'DECU' => [
		_x('Agua de Dios', 'DECU', 'ry-wc-city-select'),
		_x('Alban', 'DECU', 'ry-wc-city-select'),
		_x('Anapoima', 'DECU', 'ry-wc-city-select'),
		_x('Anolaima', 'DECU', 'ry-wc-city-select'),
		_x('Apulo', 'DECU', 'ry-wc-city-select'),
		_x('Arbelaez', 'DECU', 'ry-wc-city-select'),
		_x('Beltran', 'DECU', 'ry-wc-city-select'),
		_x('Bituima', 'DECU', 'ry-wc-city-select'),
		_x('Bojaca', 'DECU', 'ry-wc-city-select'),
		_x('Cabrera', 'DECU', 'ry-wc-city-select'),
		_x('Cachipay', 'DECU', 'ry-wc-city-select'),
		_x('Cajica', 'DECU', 'ry-wc-city-select'),
		_x('Caparrapi', 'DECU', 'ry-wc-city-select'),
		_x('Caqueza', 'DECU', 'ry-wc-city-select'),
		_x('Carmen de Carupa', 'DECU', 'ry-wc-city-select'),
		_x('Chaguani', 'DECU', 'ry-wc-city-select'),
		_x('Chia', 'DECU', 'ry-wc-city-select'),
		_x('Chipaque', 'DECU', 'ry-wc-city-select'),
		_x('Choachi', 'DECU', 'ry-wc-city-select'),
		_x('Choconta', 'DECU', 'ry-wc-city-select'),
		_x('Cogua', 'DECU', 'ry-wc-city-select'),
		_x('Cota', 'DECU', 'ry-wc-city-select'),
		_x('Cucunuba', 'DECU', 'ry-wc-city-select'),
		_x('El Colegio', 'DECU', 'ry-wc-city-select'),
		_x('El Penon', 'DECU', 'ry-wc-city-select'),
		_x('El Rosal', 'DECU', 'ry-wc-city-select'),
		_x('Facatativa', 'DECU', 'ry-wc-city-select'),
		_x('Fomeque', 'DECU', 'ry-wc-city-select'),
		_x('Fosca', 'DECU', 'ry-wc-city-select'),
		_x('Funza', 'DECU', 'ry-wc-city-select'),
		_x('Fuquene', 'DECU', 'ry-wc-city-select'),
		_x('Fusagasuga', 'DECU', 'ry-wc-city-select'),
		_x('Gachala', 'DECU', 'ry-wc-city-select'),
		_x('Gachancipa', 'DECU', 'ry-wc-city-select'),
		_x('Gacheta', 'DECU', 'ry-wc-city-select'),
		_x('Gama', 'DECU', 'ry-wc-city-select'),
		_x('Girardot', 'DECU', 'ry-wc-city-select'),
		_x('Granada', 'DECU', 'ry-wc-city-select'),
		_x('Guacheta', 'DECU', 'ry-wc-city-select'),
		_x('Guaduas', 'DECU', 'ry-wc-city-select'),
		_x('Guasca', 'DECU', 'ry-wc-city-select'),
		_x('Guataqui', 'DECU', 'ry-wc-city-select'),
		_x('Guatavita', 'DECU', 'ry-wc-city-select'),
		_x('Guayabal de Siquima', 'DECU', 'ry-wc-city-select'),
		_x('Guayabetal', 'DECU', 'ry-wc-city-select'),
		_x('Gutierrez', 'DECU', 'ry-wc-city-select'),
		_x('Jerusalen', 'DECU', 'ry-wc-city-select'),
		_x('Junin', 'DECU', 'ry-wc-city-select'),
		_x('La Calera', 'DECU', 'ry-wc-city-select'),
		_x('La Mesa', 'DECU', 'ry-wc-city-select'),
		_x('La Palma', 'DECU', 'ry-wc-city-select'),
		_x('La Pena', 'DECU', 'ry-wc-city-select'),
		_x('La Vega', 'DECU', 'ry-wc-city-select'),
		_x('Lenguazaque', 'DECU', 'ry-wc-city-select'),
		_x('Macheta', 'DECU', 'ry-wc-city-select'),
		_x('Madrid', 'DECU', 'ry-wc-city-select'),
		_x('Manta', 'DECU', 'ry-wc-city-select'),
		_x('Medina', 'DECU', 'ry-wc-city-select'),
		_x('Mosquera', 'DECU', 'ry-wc-city-select'),
		_x('Narino', 'DECU', 'ry-wc-city-select'),
		_x('Nemocon', 'DECU', 'ry-wc-city-select'),
		_x('Nilo', 'DECU', 'ry-wc-city-select'),
		_x('Nimaima', 'DECU', 'ry-wc-city-select'),
		_x('Nocaima', 'DECU', 'ry-wc-city-select'),
		_x('Pacho', 'DECU', 'ry-wc-city-select'),
		_x('Paime', 'DECU', 'ry-wc-city-select'),
		_x('Pandi', 'DECU', 'ry-wc-city-select'),
		_x('Paratebueno', 'DECU', 'ry-wc-city-select'),
		_x('Pasca', 'DECU', 'ry-wc-city-select'),
		_x('Puerto Salgar', 'DECU', 'ry-wc-city-select'),
		_x('Puli', 'DECU', 'ry-wc-city-select'),
		_x('Quebradanegra', 'DECU', 'ry-wc-city-select'),
		_x('Quetame', 'DECU', 'ry-wc-city-select'),
		_x('Quipile', 'DECU', 'ry-wc-city-select'),
		_x('Ricaurte', 'DECU', 'ry-wc-city-select'),
		_x('San Antonio del Tequendama', 'DECU', 'ry-wc-city-select'),
		_x('San Bernardo', 'DECU', 'ry-wc-city-select'),
		_x('San Cayetano', 'DECU', 'ry-wc-city-select'),
		_x('San Francisco', 'DECU', 'ry-wc-city-select'),
		_x('San Juan de Rio Seco', 'DECU', 'ry-wc-city-select'),
		_x('Sasaima', 'DECU', 'ry-wc-city-select'),
		_x('Sesquile', 'DECU', 'ry-wc-city-select'),
		_x('Sibate', 'DECU', 'ry-wc-city-select'),
		_x('Silvania', 'DECU', 'ry-wc-city-select'),
		_x('Simijaca', 'DECU', 'ry-wc-city-select'),
		_x('Soacha', 'DECU', 'ry-wc-city-select'),
		_x('Sopo', 'DECU', 'ry-wc-city-select'),
		_x('Subachoque', 'DECU', 'ry-wc-city-select'),
		_x('Suesca', 'DECU', 'ry-wc-city-select'),
		_x('Supata', 'DECU', 'ry-wc-city-select'),
		_x('Susa', 'DECU', 'ry-wc-city-select'),
		_x('Sutatausa', 'DECU', 'ry-wc-city-select'),
		_x('Tabio', 'DECU', 'ry-wc-city-select'),
		_x('Tausa', 'DECU', 'ry-wc-city-select'),
		_x('Tena', 'DECU', 'ry-wc-city-select'),
		_x('Tenjo', 'DECU', 'ry-wc-city-select'),
		_x('Tibacuy', 'DECU', 'ry-wc-city-select'),
		_x('Tibirita', 'DECU', 'ry-wc-city-select'),
		_x('Tocaima', 'DECU', 'ry-wc-city-select'),
		_x('Tocancipa', 'DECU', 'ry-wc-city-select'),
		_x('Topaipi', 'DECU', 'ry-wc-city-select'),
		_x('Ubala', 'DECU', 'ry-wc-city-select'),
		_x('Ubaque', 'DECU', 'ry-wc-city-select'),
		_x('Une', 'DECU', 'ry-wc-city-select'),
		_x('Utica', 'DECU', 'ry-wc-city-select'),
		_x('Venecia', 'DECU', 'ry-wc-city-select'),
		_x('Vergara', 'DECU', 'ry-wc-city-select'),
		_x('Viani', 'DECU', 'ry-wc-city-select'),
		_x('Villa de San Diego de Ubate', 'DECU', 'ry-wc-city-select'),
		_x('Villagomez', 'DECU', 'ry-wc-city-select'),
		_x('Villapinzon', 'DECU', 'ry-wc-city-select'),
		_x('Villeta', 'DECU', 'ry-wc-city-select'),
		_x('Viota', 'DECU', 'ry-wc-city-select'),
		_x('Yacopi', 'DECU', 'ry-wc-city-select'),
		_x('Zipacon', 'DECU', 'ry-wc-city-select'),
		_x('Zipaquira', 'DECU', 'ry-wc-city-select'),
	],
	'DEGU' => [
		_x('Albania', 'DEGU', 'ry-wc-city-select'),
		_x('Barrancas', 'DEGU', 'ry-wc-city-select'),
		_x('Dibulla', 'DEGU', 'ry-wc-city-select'),
		_x('Distraccion', 'DEGU', 'ry-wc-city-select'),
		_x('El Molino', 'DEGU', 'ry-wc-city-select'),
		_x('Fonseca', 'DEGU', 'ry-wc-city-select'),
		_x('Hatonuevo', 'DEGU', 'ry-wc-city-select'),
		_x('La Jagua del Pilar', 'DEGU', 'ry-wc-city-select'),
		_x('Maicao', 'DEGU', 'ry-wc-city-select'),
		_x('Manaure', 'DEGU', 'ry-wc-city-select'),
		_x('Riohacha', 'DEGU', 'ry-wc-city-select'),
		_x('San Juan del Cesar', 'DEGU', 'ry-wc-city-select'),
		_x('Uribia', 'DEGU', 'ry-wc-city-select'),
		_x('Urumita', 'DEGU', 'ry-wc-city-select'),
		_x('Villanueva', 'DEGU', 'ry-wc-city-select'),
	],
	'DENA' => [
		_x('Alban', 'DENA', 'ry-wc-city-select'),
		_x('Aldana', 'DENA', 'ry-wc-city-select'),
		_x('Ancuya', 'DENA', 'ry-wc-city-select'),
		_x('Arboleda', 'DENA', 'ry-wc-city-select'),
		_x('Barbacoas', 'DENA', 'ry-wc-city-select'),
		_x('Belen', 'DENA', 'ry-wc-city-select'),
		_x('Buesaco', 'DENA', 'ry-wc-city-select'),
		_x('Chachaguei', 'DENA', 'ry-wc-city-select'),
		_x('Colon', 'DENA', 'ry-wc-city-select'),
		_x('Consaca', 'DENA', 'ry-wc-city-select'),
		_x('Contadero', 'DENA', 'ry-wc-city-select'),
		_x('Cordoba', 'DENA', 'ry-wc-city-select'),
		_x('Cuaspud', 'DENA', 'ry-wc-city-select'),
		_x('Cumbal', 'DENA', 'ry-wc-city-select'),
		_x('Cumbitara', 'DENA', 'ry-wc-city-select'),
		_x('El Charco', 'DENA', 'ry-wc-city-select'),
		_x('El Penol', 'DENA', 'ry-wc-city-select'),
		_x('El Rosario', 'DENA', 'ry-wc-city-select'),
		_x('El Tablon de Gomez', 'DENA', 'ry-wc-city-select'),
		_x('El Tambo', 'DENA', 'ry-wc-city-select'),
		_x('Francisco Pizarro', 'DENA', 'ry-wc-city-select'),
		_x('Funes', 'DENA', 'ry-wc-city-select'),
		_x('Guachucal', 'DENA', 'ry-wc-city-select'),
		_x('Guaitarilla', 'DENA', 'ry-wc-city-select'),
		_x('Gualmatan', 'DENA', 'ry-wc-city-select'),
		_x('Iles', 'DENA', 'ry-wc-city-select'),
		_x('Imues', 'DENA', 'ry-wc-city-select'),
		_x('Ipiales', 'DENA', 'ry-wc-city-select'),
		_x('La Cruz', 'DENA', 'ry-wc-city-select'),
		_x('La Florida', 'DENA', 'ry-wc-city-select'),
		_x('La Llanada', 'DENA', 'ry-wc-city-select'),
		_x('La Tola', 'DENA', 'ry-wc-city-select'),
		_x('La Union', 'DENA', 'ry-wc-city-select'),
		_x('Leiva', 'DENA', 'ry-wc-city-select'),
		_x('Linares', 'DENA', 'ry-wc-city-select'),
		_x('Los Andes', 'DENA', 'ry-wc-city-select'),
		_x('Maguei', 'DENA', 'ry-wc-city-select'),
		_x('Mallama', 'DENA', 'ry-wc-city-select'),
		_x('Mosquera', 'DENA', 'ry-wc-city-select'),
		_x('Narino', 'DENA', 'ry-wc-city-select'),
		_x('Olaya Herrera', 'DENA', 'ry-wc-city-select'),
		_x('Ospina', 'DENA', 'ry-wc-city-select'),
		_x('Pasto', 'DENA', 'ry-wc-city-select'),
		_x('Policarpa', 'DENA', 'ry-wc-city-select'),
		_x('Potosi', 'DENA', 'ry-wc-city-select'),
		_x('Providencia', 'DENA', 'ry-wc-city-select'),
		_x('Puerres', 'DENA', 'ry-wc-city-select'),
		_x('Pupiales', 'DENA', 'ry-wc-city-select'),
		_x('Ricaurte', 'DENA', 'ry-wc-city-select'),
		_x('Roberto Payan', 'DENA', 'ry-wc-city-select'),
		_x('Samaniego', 'DENA', 'ry-wc-city-select'),
		_x('San Andres de Tumaco', 'DENA', 'ry-wc-city-select'),
		_x('San Bernardo', 'DENA', 'ry-wc-city-select'),
		_x('San Lorenzo', 'DENA', 'ry-wc-city-select'),
		_x('San Pablo', 'DENA', 'ry-wc-city-select'),
		_x('San Pedro de Cartago', 'DENA', 'ry-wc-city-select'),
		_x('Sandona', 'DENA', 'ry-wc-city-select'),
		_x('Santa Barbara', 'DENA', 'ry-wc-city-select'),
		_x('Santacruz', 'DENA', 'ry-wc-city-select'),
		_x('Sapuyes', 'DENA', 'ry-wc-city-select'),
		_x('Taminango', 'DENA', 'ry-wc-city-select'),
		_x('Tangua', 'DENA', 'ry-wc-city-select'),
		_x('Tuquerres', 'DENA', 'ry-wc-city-select'),
		_x('Yacuanquer', 'DENA', 'ry-wc-city-select'),
	],
	'DENOSA' => [
		_x('Abrego', 'DENOSA', 'ry-wc-city-select'),
		_x('Arboledas', 'DENOSA', 'ry-wc-city-select'),
		_x('Bochalema', 'DENOSA', 'ry-wc-city-select'),
		_x('Bucarasica', 'DENOSA', 'ry-wc-city-select'),
		_x('Cachira', 'DENOSA', 'ry-wc-city-select'),
		_x('Cacota', 'DENOSA', 'ry-wc-city-select'),
		_x('Chinacota', 'DENOSA', 'ry-wc-city-select'),
		_x('Chitaga', 'DENOSA', 'ry-wc-city-select'),
		_x('Convencion', 'DENOSA', 'ry-wc-city-select'),
		_x('Cucuta', 'DENOSA', 'ry-wc-city-select'),
		_x('Cucutilla', 'DENOSA', 'ry-wc-city-select'),
		_x('Durania', 'DENOSA', 'ry-wc-city-select'),
		_x('El Carmen', 'DENOSA', 'ry-wc-city-select'),
		_x('El Tarra', 'DENOSA', 'ry-wc-city-select'),
		_x('El Zulia', 'DENOSA', 'ry-wc-city-select'),
		_x('Gramalote', 'DENOSA', 'ry-wc-city-select'),
		_x('Hacari', 'DENOSA', 'ry-wc-city-select'),
		_x('Herran', 'DENOSA', 'ry-wc-city-select'),
		_x('La Esperanza', 'DENOSA', 'ry-wc-city-select'),
		_x('La Playa', 'DENOSA', 'ry-wc-city-select'),
		_x('Labateca', 'DENOSA', 'ry-wc-city-select'),
		_x('Los Patios', 'DENOSA', 'ry-wc-city-select'),
		_x('Lourdes', 'DENOSA', 'ry-wc-city-select'),
		_x('Mutiscua', 'DENOSA', 'ry-wc-city-select'),
		_x('Ocana', 'DENOSA', 'ry-wc-city-select'),
		_x('Pamplona', 'DENOSA', 'ry-wc-city-select'),
		_x('Pamplonita', 'DENOSA', 'ry-wc-city-select'),
		_x('Puerto Santander', 'DENOSA', 'ry-wc-city-select'),
		_x('Ragonvalia', 'DENOSA', 'ry-wc-city-select'),
		_x('Salazar', 'DENOSA', 'ry-wc-city-select'),
		_x('San Calixto', 'DENOSA', 'ry-wc-city-select'),
		_x('San Cayetano', 'DENOSA', 'ry-wc-city-select'),
		_x('Santiago', 'DENOSA', 'ry-wc-city-select'),
		_x('Sardinata', 'DENOSA', 'ry-wc-city-select'),
		_x('Silos', 'DENOSA', 'ry-wc-city-select'),
		_x('Teorama', 'DENOSA', 'ry-wc-city-select'),
		_x('Tibu', 'DENOSA', 'ry-wc-city-select'),
		_x('Toledo', 'DENOSA', 'ry-wc-city-select'),
		_x('Villa Caro', 'DENOSA', 'ry-wc-city-select'),
		_x('Villa del Rosario', 'DENOSA', 'ry-wc-city-select'),
	],
	'DERI' => [
		_x('Apia', 'DERI', 'ry-wc-city-select'),
		_x('Balboa', 'DERI', 'ry-wc-city-select'),
		_x('Belen de Umbria', 'DERI', 'ry-wc-city-select'),
		_x('Dosquebradas', 'DERI', 'ry-wc-city-select'),
		_x('Guatica', 'DERI', 'ry-wc-city-select'),
		_x('La Celia', 'DERI', 'ry-wc-city-select'),
		_x('La Virginia', 'DERI', 'ry-wc-city-select'),
		_x('Marsella', 'DERI', 'ry-wc-city-select'),
		_x('Mistrato', 'DERI', 'ry-wc-city-select'),
		_x('Pereira', 'DERI', 'ry-wc-city-select'),
		_x('Pueblo Rico', 'DERI', 'ry-wc-city-select'),
		_x('Quinchia', 'DERI', 'ry-wc-city-select'),
		_x('Santa Rosa de Cabal', 'DERI', 'ry-wc-city-select'),
		_x('Santuario', 'DERI', 'ry-wc-city-select'),
	],
	'DESA' => [
		_x('Aguada', 'DESA', 'ry-wc-city-select'),
		_x('Albania', 'DESA', 'ry-wc-city-select'),
		_x('Aratoca', 'DESA', 'ry-wc-city-select'),
		_x('Barbosa', 'DESA', 'ry-wc-city-select'),
		_x('Barichara', 'DESA', 'ry-wc-city-select'),
		_x('Barrancabermeja', 'DESA', 'ry-wc-city-select'),
		_x('Betulia', 'DESA', 'ry-wc-city-select'),
		_x('Bolivar', 'DESA', 'ry-wc-city-select'),
		_x('Bucaramanga', 'DESA', 'ry-wc-city-select'),
		_x('Cabrera', 'DESA', 'ry-wc-city-select'),
		_x('California', 'DESA', 'ry-wc-city-select'),
		_x('Capitanejo', 'DESA', 'ry-wc-city-select'),
		_x('Carcasi', 'DESA', 'ry-wc-city-select'),
		_x('Cepita', 'DESA', 'ry-wc-city-select'),
		_x('Cerrito', 'DESA', 'ry-wc-city-select'),
		_x('Charala', 'DESA', 'ry-wc-city-select'),
		_x('Charta', 'DESA', 'ry-wc-city-select'),
		_x('Chima', 'DESA', 'ry-wc-city-select'),
		_x('Chipata', 'DESA', 'ry-wc-city-select'),
		_x('Cimitarra', 'DESA', 'ry-wc-city-select'),
		_x('Concepcion', 'DESA', 'ry-wc-city-select'),
		_x('Confines', 'DESA', 'ry-wc-city-select'),
		_x('Contratacion', 'DESA', 'ry-wc-city-select'),
		_x('Coromoro', 'DESA', 'ry-wc-city-select'),
		_x('Curiti', 'DESA', 'ry-wc-city-select'),
		_x('El Carmen de Chucuri', 'DESA', 'ry-wc-city-select'),
		_x('El Guacamayo', 'DESA', 'ry-wc-city-select'),
		_x('El Penon', 'DESA', 'ry-wc-city-select'),
		_x('El Playon', 'DESA', 'ry-wc-city-select'),
		_x('Encino', 'DESA', 'ry-wc-city-select'),
		_x('Enciso', 'DESA', 'ry-wc-city-select'),
		_x('Florian', 'DESA', 'ry-wc-city-select'),
		_x('Floridablanca', 'DESA', 'ry-wc-city-select'),
		_x('Galan', 'DESA', 'ry-wc-city-select'),
		_x('Gambita', 'DESA', 'ry-wc-city-select'),
		_x('Giron', 'DESA', 'ry-wc-city-select'),
		_x('Guaca', 'DESA', 'ry-wc-city-select'),
		_x('Guadalupe', 'DESA', 'ry-wc-city-select'),
		_x('Guapota', 'DESA', 'ry-wc-city-select'),
		_x('Guavata', 'DESA', 'ry-wc-city-select'),
		_x('Gueepsa', 'DESA', 'ry-wc-city-select'),
		_x('Hato', 'DESA', 'ry-wc-city-select'),
		_x('Jesus Maria', 'DESA', 'ry-wc-city-select'),
		_x('Jordan', 'DESA', 'ry-wc-city-select'),
		_x('La Belleza', 'DESA', 'ry-wc-city-select'),
		_x('La Paz', 'DESA', 'ry-wc-city-select'),
		_x('Landazuri', 'DESA', 'ry-wc-city-select'),
		_x('Lebrija', 'DESA', 'ry-wc-city-select'),
		_x('Los Santos', 'DESA', 'ry-wc-city-select'),
		_x('Macaravita', 'DESA', 'ry-wc-city-select'),
		_x('Malaga', 'DESA', 'ry-wc-city-select'),
		_x('Matanza', 'DESA', 'ry-wc-city-select'),
		_x('Mogotes', 'DESA', 'ry-wc-city-select'),
		_x('Molagavita', 'DESA', 'ry-wc-city-select'),
		_x('Ocamonte', 'DESA', 'ry-wc-city-select'),
		_x('Oiba', 'DESA', 'ry-wc-city-select'),
		_x('Onzaga', 'DESA', 'ry-wc-city-select'),
		_x('Palmar', 'DESA', 'ry-wc-city-select'),
		_x('Palmas del Socorro', 'DESA', 'ry-wc-city-select'),
		_x('Paramo', 'DESA', 'ry-wc-city-select'),
		_x('Piedecuesta', 'DESA', 'ry-wc-city-select'),
		_x('Pinchote', 'DESA', 'ry-wc-city-select'),
		_x('Puente Nacional', 'DESA', 'ry-wc-city-select'),
		_x('Puerto Parra', 'DESA', 'ry-wc-city-select'),
		_x('Puerto Wilches', 'DESA', 'ry-wc-city-select'),
		_x('Rionegro', 'DESA', 'ry-wc-city-select'),
		_x('Sabana de Torres', 'DESA', 'ry-wc-city-select'),
		_x('San Andres', 'DESA', 'ry-wc-city-select'),
		_x('San Benito', 'DESA', 'ry-wc-city-select'),
		_x('San Gil', 'DESA', 'ry-wc-city-select'),
		_x('San Joaquin', 'DESA', 'ry-wc-city-select'),
		_x('San Jose de Miranda', 'DESA', 'ry-wc-city-select'),
		_x('San Miguel', 'DESA', 'ry-wc-city-select'),
		_x('San Vicente de Chucuri', 'DESA', 'ry-wc-city-select'),
		_x('Santa Barbara', 'DESA', 'ry-wc-city-select'),
		_x('Santa Helena del Opon', 'DESA', 'ry-wc-city-select'),
		_x('Simacota', 'DESA', 'ry-wc-city-select'),
		_x('Socorro', 'DESA', 'ry-wc-city-select'),
		_x('Suaita', 'DESA', 'ry-wc-city-select'),
		_x('Sucre', 'DESA', 'ry-wc-city-select'),
		_x('Surata', 'DESA', 'ry-wc-city-select'),
		_x('Tona', 'DESA', 'ry-wc-city-select'),
		_x('Valle de San Jose', 'DESA', 'ry-wc-city-select'),
		_x('Velez', 'DESA', 'ry-wc-city-select'),
		_x('Vetas', 'DESA', 'ry-wc-city-select'),
		_x('Villanueva', 'DESA', 'ry-wc-city-select'),
		_x('Zapatoca', 'DESA', 'ry-wc-city-select'),
	],
	'DESU' => [
		_x('Buenavista', 'DESU', 'ry-wc-city-select'),
		_x('Caimito', 'DESU', 'ry-wc-city-select'),
		_x('Chalan', 'DESU', 'ry-wc-city-select'),
		_x('Coloso', 'DESU', 'ry-wc-city-select'),
		_x('Corozal', 'DESU', 'ry-wc-city-select'),
		_x('Covenas', 'DESU', 'ry-wc-city-select'),
		_x('El Roble', 'DESU', 'ry-wc-city-select'),
		_x('Galeras', 'DESU', 'ry-wc-city-select'),
		_x('Guaranda', 'DESU', 'ry-wc-city-select'),
		_x('La Union', 'DESU', 'ry-wc-city-select'),
		_x('Los Palmitos', 'DESU', 'ry-wc-city-select'),
		_x('Majagual', 'DESU', 'ry-wc-city-select'),
		_x('Morroa', 'DESU', 'ry-wc-city-select'),
		_x('Ovejas', 'DESU', 'ry-wc-city-select'),
		_x('Palmito', 'DESU', 'ry-wc-city-select'),
		_x('Sampues', 'DESU', 'ry-wc-city-select'),
		_x('San Benito Abad', 'DESU', 'ry-wc-city-select'),
		_x('San Juan de Betulia', 'DESU', 'ry-wc-city-select'),
		_x('San Luis de Since', 'DESU', 'ry-wc-city-select'),
		_x('San Marcos', 'DESU', 'ry-wc-city-select'),
		_x('San Onofre', 'DESU', 'ry-wc-city-select'),
		_x('San Pedro', 'DESU', 'ry-wc-city-select'),
		_x('Santiago de Tolu', 'DESU', 'ry-wc-city-select'),
		_x('Sincelejo', 'DESU', 'ry-wc-city-select'),
		_x('Sucre', 'DESU', 'ry-wc-city-select'),
		_x('Tolu Viejo', 'DESU', 'ry-wc-city-select'),
	],
	'DETO' => [
		_x('Alpujarra', 'DETO', 'ry-wc-city-select'),
		_x('Alvarado', 'DETO', 'ry-wc-city-select'),
		_x('Ambalema', 'DETO', 'ry-wc-city-select'),
		_x('Anzoategui', 'DETO', 'ry-wc-city-select'),
		_x('Armero', 'DETO', 'ry-wc-city-select'),
		_x('Ataco', 'DETO', 'ry-wc-city-select'),
		_x('Cajamarca', 'DETO', 'ry-wc-city-select'),
		_x('Carmen de Apicala', 'DETO', 'ry-wc-city-select'),
		_x('Casabianca', 'DETO', 'ry-wc-city-select'),
		_x('Chaparral', 'DETO', 'ry-wc-city-select'),
		_x('Coello', 'DETO', 'ry-wc-city-select'),
		_x('Coyaima', 'DETO', 'ry-wc-city-select'),
		_x('Cunday', 'DETO', 'ry-wc-city-select'),
		_x('Dolores', 'DETO', 'ry-wc-city-select'),
		_x('Espinal', 'DETO', 'ry-wc-city-select'),
		_x('Falan', 'DETO', 'ry-wc-city-select'),
		_x('Flandes', 'DETO', 'ry-wc-city-select'),
		_x('Fresno', 'DETO', 'ry-wc-city-select'),
		_x('Guamo', 'DETO', 'ry-wc-city-select'),
		_x('Herveo', 'DETO', 'ry-wc-city-select'),
		_x('Honda', 'DETO', 'ry-wc-city-select'),
		_x('Ibague', 'DETO', 'ry-wc-city-select'),
		_x('Icononzo', 'DETO', 'ry-wc-city-select'),
		_x('Lerida', 'DETO', 'ry-wc-city-select'),
		_x('Libano', 'DETO', 'ry-wc-city-select'),
		_x('Melgar', 'DETO', 'ry-wc-city-select'),
		_x('Municipio de San Sebastian de Mariquita', 'DETO', 'ry-wc-city-select'),
		_x('Murillo', 'DETO', 'ry-wc-city-select'),
		_x('Natagaima', 'DETO', 'ry-wc-city-select'),
		_x('Ortega', 'DETO', 'ry-wc-city-select'),
		_x('Palocabildo', 'DETO', 'ry-wc-city-select'),
		_x('Piedras', 'DETO', 'ry-wc-city-select'),
		_x('Planadas', 'DETO', 'ry-wc-city-select'),
		_x('Prado', 'DETO', 'ry-wc-city-select'),
		_x('Purificacion', 'DETO', 'ry-wc-city-select'),
		_x('Rioblanco', 'DETO', 'ry-wc-city-select'),
		_x('Roncesvalles', 'DETO', 'ry-wc-city-select'),
		_x('Rovira', 'DETO', 'ry-wc-city-select'),
		_x('Saldana', 'DETO', 'ry-wc-city-select'),
		_x('San Antonio', 'DETO', 'ry-wc-city-select'),
		_x('San Luis', 'DETO', 'ry-wc-city-select'),
		_x('Santa Isabel', 'DETO', 'ry-wc-city-select'),
		_x('Suarez', 'DETO', 'ry-wc-city-select'),
		_x('Valle de San Juan', 'DETO', 'ry-wc-city-select'),
		_x('Venadillo', 'DETO', 'ry-wc-city-select'),
		_x('Villahermosa', 'DETO', 'ry-wc-city-select'),
		_x('Villarrica', 'DETO', 'ry-wc-city-select'),
	],
	'DEDEAT' => [
		_x('Baranoa', 'DEDEAT', 'ry-wc-city-select'),
		_x('Barranquilla', 'DEDEAT', 'ry-wc-city-select'),
		_x('Campo de La Cruz', 'DEDEAT', 'ry-wc-city-select'),
		_x('Candelaria', 'DEDEAT', 'ry-wc-city-select'),
		_x('Galapa', 'DEDEAT', 'ry-wc-city-select'),
		_x('Juan de Acosta', 'DEDEAT', 'ry-wc-city-select'),
		_x('Luruaco', 'DEDEAT', 'ry-wc-city-select'),
		_x('Malambo', 'DEDEAT', 'ry-wc-city-select'),
		_x('Manati', 'DEDEAT', 'ry-wc-city-select'),
		_x('Palmar de Varela', 'DEDEAT', 'ry-wc-city-select'),
		_x('Piojo', 'DEDEAT', 'ry-wc-city-select'),
		_x('Polonuevo', 'DEDEAT', 'ry-wc-city-select'),
		_x('Ponedera', 'DEDEAT', 'ry-wc-city-select'),
		_x('Puerto Colombia', 'DEDEAT', 'ry-wc-city-select'),
		_x('Repelon', 'DEDEAT', 'ry-wc-city-select'),
		_x('Sabanagrande', 'DEDEAT', 'ry-wc-city-select'),
		_x('Sabanalarga', 'DEDEAT', 'ry-wc-city-select'),
		_x('Santa Lucia', 'DEDEAT', 'ry-wc-city-select'),
		_x('Santo Tomas', 'DEDEAT', 'ry-wc-city-select'),
		_x('Soledad', 'DEDEAT', 'ry-wc-city-select'),
		_x('Suan', 'DEDEAT', 'ry-wc-city-select'),
		_x('Tubara', 'DEDEAT', 'ry-wc-city-select'),
		_x('Usiacuri', 'DEDEAT', 'ry-wc-city-select'),
	],
	'DEDECA' => [
		_x('Albania', 'DEDECA', 'ry-wc-city-select'),
		_x('Belen de Los Andaquies', 'DEDECA', 'ry-wc-city-select'),
		_x('Cartagena del Chaira', 'DEDECA', 'ry-wc-city-select'),
		_x('Curillo', 'DEDECA', 'ry-wc-city-select'),
		_x('El Doncello', 'DEDECA', 'ry-wc-city-select'),
		_x('El Paujil', 'DEDECA', 'ry-wc-city-select'),
		_x('Florencia', 'DEDECA', 'ry-wc-city-select'),
		_x('La Montanita', 'DEDECA', 'ry-wc-city-select'),
		_x('Milan', 'DEDECA', 'ry-wc-city-select'),
		_x('Morelia', 'DEDECA', 'ry-wc-city-select'),
		_x('Puerto Rico', 'DEDECA', 'ry-wc-city-select'),
		_x('San Jose del Fragua', 'DEDECA', 'ry-wc-city-select'),
		_x('San Vicente del Caguan', 'DEDECA', 'ry-wc-city-select'),
		_x('Solano', 'DEDECA', 'ry-wc-city-select'),
		_x('Solita', 'DEDECA', 'ry-wc-city-select'),
		_x('Valparaiso', 'DEDECA', 'ry-wc-city-select'),
	],
	'DEDECA2' => [
		_x('Almaguer', 'DEDECA2', 'ry-wc-city-select'),
		_x('Argelia', 'DEDECA2', 'ry-wc-city-select'),
		_x('Balboa', 'DEDECA2', 'ry-wc-city-select'),
		_x('Bolivar', 'DEDECA2', 'ry-wc-city-select'),
		_x('Buenos Aires', 'DEDECA2', 'ry-wc-city-select'),
		_x('Cajibio', 'DEDECA2', 'ry-wc-city-select'),
		_x('Caldono', 'DEDECA2', 'ry-wc-city-select'),
		_x('Caloto', 'DEDECA2', 'ry-wc-city-select'),
		_x('Corinto', 'DEDECA2', 'ry-wc-city-select'),
		_x('El Tambo', 'DEDECA2', 'ry-wc-city-select'),
		_x('Florencia', 'DEDECA2', 'ry-wc-city-select'),
		_x('Guachene', 'DEDECA2', 'ry-wc-city-select'),
		_x('Guapi', 'DEDECA2', 'ry-wc-city-select'),
		_x('Inza', 'DEDECA2', 'ry-wc-city-select'),
		_x('Jambalo', 'DEDECA2', 'ry-wc-city-select'),
		_x('La Sierra', 'DEDECA2', 'ry-wc-city-select'),
		_x('La Vega', 'DEDECA2', 'ry-wc-city-select'),
		_x('Mercaderes', 'DEDECA2', 'ry-wc-city-select'),
		_x('Miranda', 'DEDECA2', 'ry-wc-city-select'),
		_x('Morales', 'DEDECA2', 'ry-wc-city-select'),
		_x('Municipio de Lopez de Micay', 'DEDECA2', 'ry-wc-city-select'),
		_x('Padilla', 'DEDECA2', 'ry-wc-city-select'),
		_x('Paez', 'DEDECA2', 'ry-wc-city-select'),
		_x('Patia', 'DEDECA2', 'ry-wc-city-select'),
		_x('Piamonte', 'DEDECA2', 'ry-wc-city-select'),
		_x('Piendamo', 'DEDECA2', 'ry-wc-city-select'),
		_x('Popayan', 'DEDECA2', 'ry-wc-city-select'),
		_x('Puerto Tejada', 'DEDECA2', 'ry-wc-city-select'),
		_x('Purace', 'DEDECA2', 'ry-wc-city-select'),
		_x('Rosas', 'DEDECA2', 'ry-wc-city-select'),
		_x('San Sebastian', 'DEDECA2', 'ry-wc-city-select'),
		_x('Santa Rosa', 'DEDECA2', 'ry-wc-city-select'),
		_x('Santander de Quilichao', 'DEDECA2', 'ry-wc-city-select'),
		_x('Silvia', 'DEDECA2', 'ry-wc-city-select'),
		_x('Sotara', 'DEDECA2', 'ry-wc-city-select'),
		_x('Suarez', 'DEDECA2', 'ry-wc-city-select'),
		_x('Sucre', 'DEDECA2', 'ry-wc-city-select'),
		_x('Timbio', 'DEDECA2', 'ry-wc-city-select'),
		_x('Timbiqui', 'DEDECA2', 'ry-wc-city-select'),
		_x('Toribio', 'DEDECA2', 'ry-wc-city-select'),
		_x('Totoro', 'DEDECA2', 'ry-wc-city-select'),
		_x('Villa Rica', 'DEDECA2', 'ry-wc-city-select'),
	],
	'DEDECE' => [
		_x('Aguachica', 'DEDECE', 'ry-wc-city-select'),
		_x('Agustin Codazzi', 'DEDECE', 'ry-wc-city-select'),
		_x('Astrea', 'DEDECE', 'ry-wc-city-select'),
		_x('Becerril', 'DEDECE', 'ry-wc-city-select'),
		_x('Bosconia', 'DEDECE', 'ry-wc-city-select'),
		_x('Chimichagua', 'DEDECE', 'ry-wc-city-select'),
		_x('Chiriguana', 'DEDECE', 'ry-wc-city-select'),
		_x('Curumani', 'DEDECE', 'ry-wc-city-select'),
		_x('El Copey', 'DEDECE', 'ry-wc-city-select'),
		_x('El Paso', 'DEDECE', 'ry-wc-city-select'),
		_x('Gamarra', 'DEDECE', 'ry-wc-city-select'),
		_x('Gonzalez', 'DEDECE', 'ry-wc-city-select'),
		_x('La Gloria', 'DEDECE', 'ry-wc-city-select'),
		_x('La Jagua de Ibirico', 'DEDECE', 'ry-wc-city-select'),
		_x('La Paz', 'DEDECE', 'ry-wc-city-select'),
		_x('Manaure', 'DEDECE', 'ry-wc-city-select'),
		_x('Pailitas', 'DEDECE', 'ry-wc-city-select'),
		_x('Pelaya', 'DEDECE', 'ry-wc-city-select'),
		_x('Pueblo Bello', 'DEDECE', 'ry-wc-city-select'),
		_x('Rio de Oro', 'DEDECE', 'ry-wc-city-select'),
		_x('San Alberto', 'DEDECE', 'ry-wc-city-select'),
		_x('San Diego', 'DEDECE', 'ry-wc-city-select'),
		_x('San Martin', 'DEDECE', 'ry-wc-city-select'),
		_x('Tamalameque', 'DEDECE', 'ry-wc-city-select'),
		_x('Valledupar', 'DEDECE', 'ry-wc-city-select'),
	],
	'DEDECH' => [
		_x('Acandi', 'DEDECH', 'ry-wc-city-select'),
		_x('Alto Baudo', 'DEDECH', 'ry-wc-city-select'),
		_x('Atrato', 'DEDECH', 'ry-wc-city-select'),
		_x('Bagado', 'DEDECH', 'ry-wc-city-select'),
		_x('Bahia Solano', 'DEDECH', 'ry-wc-city-select'),
		_x('Bajo Baudo', 'DEDECH', 'ry-wc-city-select'),
		_x('Bojaya', 'DEDECH', 'ry-wc-city-select'),
		_x('Carmen del Darien', 'DEDECH', 'ry-wc-city-select'),
		_x('Certegui', 'DEDECH', 'ry-wc-city-select'),
		_x('Condoto', 'DEDECH', 'ry-wc-city-select'),
		_x('El Canton del San Pablo', 'DEDECH', 'ry-wc-city-select'),
		_x('El Carmen de Atrato', 'DEDECH', 'ry-wc-city-select'),
		_x('El Litoral del San Juan', 'DEDECH', 'ry-wc-city-select'),
		_x('Istmina', 'DEDECH', 'ry-wc-city-select'),
		_x('Jurado', 'DEDECH', 'ry-wc-city-select'),
		_x('Lloro', 'DEDECH', 'ry-wc-city-select'),
		_x('Medio Atrato', 'DEDECH', 'ry-wc-city-select'),
		_x('Medio Baudo', 'DEDECH', 'ry-wc-city-select'),
		_x('Medio San Juan', 'DEDECH', 'ry-wc-city-select'),
		_x('Novita', 'DEDECH', 'ry-wc-city-select'),
		_x('Nuqui', 'DEDECH', 'ry-wc-city-select'),
		_x('Quibdo', 'DEDECH', 'ry-wc-city-select'),
		_x('Rio Iro', 'DEDECH', 'ry-wc-city-select'),
		_x('Rio Quito', 'DEDECH', 'ry-wc-city-select'),
		_x('Riosucio', 'DEDECH', 'ry-wc-city-select'),
		_x('San Jose del Palmar', 'DEDECH', 'ry-wc-city-select'),
		_x('Sipi', 'DEDECH', 'ry-wc-city-select'),
		_x('Tado', 'DEDECH', 'ry-wc-city-select'),
		_x('Unguia', 'DEDECH', 'ry-wc-city-select'),
		_x('Union Panamericana', 'DEDECH', 'ry-wc-city-select'),
	],
	'DEDEGU' => [
		_x('Barranco Minas', 'DEDEGU', 'ry-wc-city-select'),
		_x('Cacahual', 'DEDEGU', 'ry-wc-city-select'),
		_x('Inirida', 'DEDEGU', 'ry-wc-city-select'),
		_x('La Guadalupe', 'DEDEGU', 'ry-wc-city-select'),
		_x('Mapiripana', 'DEDEGU', 'ry-wc-city-select'),
		_x('Morichal', 'DEDEGU', 'ry-wc-city-select'),
		_x('Pana Pana', 'DEDEGU', 'ry-wc-city-select'),
		_x('Puerto Colombia', 'DEDEGU', 'ry-wc-city-select'),
		_x('San Felipe', 'DEDEGU', 'ry-wc-city-select'),
	],
	'DEDEGU2' => [
		_x('Calamar', 'DEDEGU2', 'ry-wc-city-select'),
		_x('El Retorno', 'DEDEGU2', 'ry-wc-city-select'),
		_x('Miraflores', 'DEDEGU2', 'ry-wc-city-select'),
		_x('San Jose del Guaviare', 'DEDEGU2', 'ry-wc-city-select'),
	],
	'DEDEHU' => [
		_x('Acevedo', 'DEDEHU', 'ry-wc-city-select'),
		_x('Agrado', 'DEDEHU', 'ry-wc-city-select'),
		_x('Aipe', 'DEDEHU', 'ry-wc-city-select'),
		_x('Algeciras', 'DEDEHU', 'ry-wc-city-select'),
		_x('Altamira', 'DEDEHU', 'ry-wc-city-select'),
		_x('Baraya', 'DEDEHU', 'ry-wc-city-select'),
		_x('Campoalegre', 'DEDEHU', 'ry-wc-city-select'),
		_x('Colombia', 'DEDEHU', 'ry-wc-city-select'),
		_x('Elias', 'DEDEHU', 'ry-wc-city-select'),
		_x('Garzon', 'DEDEHU', 'ry-wc-city-select'),
		_x('Gigante', 'DEDEHU', 'ry-wc-city-select'),
		_x('Guadalupe', 'DEDEHU', 'ry-wc-city-select'),
		_x('Hobo', 'DEDEHU', 'ry-wc-city-select'),
		_x('Isnos', 'DEDEHU', 'ry-wc-city-select'),
		_x('La Argentina', 'DEDEHU', 'ry-wc-city-select'),
		_x('La Plata', 'DEDEHU', 'ry-wc-city-select'),
		_x('Municipio de Iquira', 'DEDEHU', 'ry-wc-city-select'),
		_x('Nataga', 'DEDEHU', 'ry-wc-city-select'),
		_x('Neiva', 'DEDEHU', 'ry-wc-city-select'),
		_x('Oporapa', 'DEDEHU', 'ry-wc-city-select'),
		_x('Paicol', 'DEDEHU', 'ry-wc-city-select'),
		_x('Palermo', 'DEDEHU', 'ry-wc-city-select'),
		_x('Palestina', 'DEDEHU', 'ry-wc-city-select'),
		_x('Pital', 'DEDEHU', 'ry-wc-city-select'),
		_x('Pitalito', 'DEDEHU', 'ry-wc-city-select'),
		_x('Rivera', 'DEDEHU', 'ry-wc-city-select'),
		_x('Saladoblanco', 'DEDEHU', 'ry-wc-city-select'),
		_x('San Agustin', 'DEDEHU', 'ry-wc-city-select'),
		_x('Santa Maria', 'DEDEHU', 'ry-wc-city-select'),
		_x('Suaza', 'DEDEHU', 'ry-wc-city-select'),
		_x('Tarqui', 'DEDEHU', 'ry-wc-city-select'),
		_x('Tello', 'DEDEHU', 'ry-wc-city-select'),
		_x('Teruel', 'DEDEHU', 'ry-wc-city-select'),
		_x('Tesalia', 'DEDEHU', 'ry-wc-city-select'),
		_x('Timana', 'DEDEHU', 'ry-wc-city-select'),
		_x('Villavieja', 'DEDEHU', 'ry-wc-city-select'),
		_x('Yaguara', 'DEDEHU', 'ry-wc-city-select'),
	],
	'DEDEMA' => [
		_x('Algarrobo', 'DEDEMA', 'ry-wc-city-select'),
		_x('Aracataca', 'DEDEMA', 'ry-wc-city-select'),
		_x('Ariguani', 'DEDEMA', 'ry-wc-city-select'),
		_x('Cerro San Antonio', 'DEDEMA', 'ry-wc-city-select'),
		_x('Chibolo', 'DEDEMA', 'ry-wc-city-select'),
		_x('Cienaga', 'DEDEMA', 'ry-wc-city-select'),
		_x('Concordia', 'DEDEMA', 'ry-wc-city-select'),
		_x('El Banco', 'DEDEMA', 'ry-wc-city-select'),
		_x('El Pinon', 'DEDEMA', 'ry-wc-city-select'),
		_x('El Reten', 'DEDEMA', 'ry-wc-city-select'),
		_x('Fundacion', 'DEDEMA', 'ry-wc-city-select'),
		_x('Guamal', 'DEDEMA', 'ry-wc-city-select'),
		_x('Nueva Granada', 'DEDEMA', 'ry-wc-city-select'),
		_x('Pedraza', 'DEDEMA', 'ry-wc-city-select'),
		_x('Pijino del Carmen', 'DEDEMA', 'ry-wc-city-select'),
		_x('Pivijay', 'DEDEMA', 'ry-wc-city-select'),
		_x('Plato', 'DEDEMA', 'ry-wc-city-select'),
		_x('Puebloviejo', 'DEDEMA', 'ry-wc-city-select'),
		_x('Remolino', 'DEDEMA', 'ry-wc-city-select'),
		_x('Sabanas de San Angel', 'DEDEMA', 'ry-wc-city-select'),
		_x('Salamina', 'DEDEMA', 'ry-wc-city-select'),
		_x('San Sebastian de Buenavista', 'DEDEMA', 'ry-wc-city-select'),
		_x('San Zenon', 'DEDEMA', 'ry-wc-city-select'),
		_x('Santa Ana', 'DEDEMA', 'ry-wc-city-select'),
		_x('Santa Barbara de Pinto', 'DEDEMA', 'ry-wc-city-select'),
		_x('Santa Marta', 'DEDEMA', 'ry-wc-city-select'),
		_x('Sitionuevo', 'DEDEMA', 'ry-wc-city-select'),
		_x('Tenerife', 'DEDEMA', 'ry-wc-city-select'),
		_x('Zapayan', 'DEDEMA', 'ry-wc-city-select'),
		_x('Zona Bananera', 'DEDEMA', 'ry-wc-city-select'),
	],
	'DEDEME' => [
		_x('Acacias', 'DEDEME', 'ry-wc-city-select'),
		_x('Barranca de Upia', 'DEDEME', 'ry-wc-city-select'),
		_x('Cabuyaro', 'DEDEME', 'ry-wc-city-select'),
		_x('Castilla la Nueva', 'DEDEME', 'ry-wc-city-select'),
		_x('Cubarral', 'DEDEME', 'ry-wc-city-select'),
		_x('Cumaral', 'DEDEME', 'ry-wc-city-select'),
		_x('El Calvario', 'DEDEME', 'ry-wc-city-select'),
		_x('El Castillo', 'DEDEME', 'ry-wc-city-select'),
		_x('El Dorado', 'DEDEME', 'ry-wc-city-select'),
		_x('Fuente de Oro', 'DEDEME', 'ry-wc-city-select'),
		_x('Granada', 'DEDEME', 'ry-wc-city-select'),
		_x('Guamal', 'DEDEME', 'ry-wc-city-select'),
		_x('La Macarena', 'DEDEME', 'ry-wc-city-select'),
		_x('Lejanias', 'DEDEME', 'ry-wc-city-select'),
		_x('Mapiripan', 'DEDEME', 'ry-wc-city-select'),
		_x('Mesetas', 'DEDEME', 'ry-wc-city-select'),
		_x('Puerto Concordia', 'DEDEME', 'ry-wc-city-select'),
		_x('Puerto Gaitan', 'DEDEME', 'ry-wc-city-select'),
		_x('Puerto Lleras', 'DEDEME', 'ry-wc-city-select'),
		_x('Puerto Lopez', 'DEDEME', 'ry-wc-city-select'),
		_x('Puerto Rico', 'DEDEME', 'ry-wc-city-select'),
		_x('Restrepo', 'DEDEME', 'ry-wc-city-select'),
		_x('San Carlos de Guaroa', 'DEDEME', 'ry-wc-city-select'),
		_x('San Juan de Arama', 'DEDEME', 'ry-wc-city-select'),
		_x('San Juanito', 'DEDEME', 'ry-wc-city-select'),
		_x('San Martin', 'DEDEME', 'ry-wc-city-select'),
		_x('Uribe', 'DEDEME', 'ry-wc-city-select'),
		_x('Villavicencio', 'DEDEME', 'ry-wc-city-select'),
		_x('Vistahermosa', 'DEDEME', 'ry-wc-city-select'),
	],
	'DEDEPU' => [
		_x('Colon', 'DEDEPU', 'ry-wc-city-select'),
		_x('Leguizamo', 'DEDEPU', 'ry-wc-city-select'),
		_x('Mocoa', 'DEDEPU', 'ry-wc-city-select'),
		_x('Orito', 'DEDEPU', 'ry-wc-city-select'),
		_x('Puerto Asis', 'DEDEPU', 'ry-wc-city-select'),
		_x('Puerto Caicedo', 'DEDEPU', 'ry-wc-city-select'),
		_x('Puerto Guzman', 'DEDEPU', 'ry-wc-city-select'),
		_x('San Francisco', 'DEDEPU', 'ry-wc-city-select'),
		_x('San Miguel', 'DEDEPU', 'ry-wc-city-select'),
		_x('Santiago', 'DEDEPU', 'ry-wc-city-select'),
		_x('Sibundoy', 'DEDEPU', 'ry-wc-city-select'),
		_x('Valle del Guamuez', 'DEDEPU', 'ry-wc-city-select'),
		_x('Villagarzon', 'DEDEPU', 'ry-wc-city-select'),
	],
	'DEDEVADECA' => [
		_x('Alcala', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Andalucia', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Ansermanuevo', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Argelia', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Bolivar', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Buenaventura', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Bugalagrande', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Caicedonia', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Cali', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Calima', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Candelaria', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Cartago', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Dagua', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('El Aguila', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('El Cairo', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('El Cerrito', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('El Dovio', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Florida', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Ginebra', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Guacari', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Guadalajara de Buga', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Jamundi', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('La Cumbre', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('La Union', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('La Victoria', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Obando', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Palmira', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Pradera', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Restrepo', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Riofrio', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Roldanillo', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('San Pedro', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Sevilla', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Toro', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Trujillo', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Tulua', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Ulloa', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Versalles', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Vijes', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Yotoco', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Yumbo', 'DEDEVADECA', 'ry-wc-city-select'),
		_x('Zarzal', 'DEDEVADECA', 'ry-wc-city-select'),
	],
	'DEDEVA' => [
		_x('Caruru', 'DEDEVA', 'ry-wc-city-select'),
		_x('Mitu', 'DEDEVA', 'ry-wc-city-select'),
		_x('Pacoa', 'DEDEVA', 'ry-wc-city-select'),
		_x('Papunaua', 'DEDEVA', 'ry-wc-city-select'),
		_x('Taraira', 'DEDEVA', 'ry-wc-city-select'),
		_x('Yavarate', 'DEDEVA', 'ry-wc-city-select'),
	],
	'DEDEVI' => [
		_x('Cumaribo', 'DEDEVI', 'ry-wc-city-select'),
		_x('La Primavera', 'DEDEVI', 'ry-wc-city-select'),
		_x('Puerto Carreno', 'DEDEVI', 'ry-wc-city-select'),
		_x('Santa Rosalia', 'DEDEVI', 'ry-wc-city-select'),
	],
	'PRSACADE' => [
		_x('Providencia', 'PRSACADE', 'ry-wc-city-select'),
		_x('San Andres', 'PRSACADE', 'ry-wc-city-select'),
	],
	'QUDE' => [
		_x('Armenia', 'QUDE', 'ry-wc-city-select'),
		_x('Buenavista', 'QUDE', 'ry-wc-city-select'),
		_x('Calarca', 'QUDE', 'ry-wc-city-select'),
		_x('Circasia', 'QUDE', 'ry-wc-city-select'),
		_x('Cordoba', 'QUDE', 'ry-wc-city-select'),
		_x('Filandia', 'QUDE', 'ry-wc-city-select'),
		_x('Genova', 'QUDE', 'ry-wc-city-select'),
		_x('La Tebaida', 'QUDE', 'ry-wc-city-select'),
		_x('Montenegro', 'QUDE', 'ry-wc-city-select'),
		_x('Pijao', 'QUDE', 'ry-wc-city-select'),
		_x('Quimbaya', 'QUDE', 'ry-wc-city-select'),
		_x('Salento', 'QUDE', 'ry-wc-city-select'),
	],
	]
];