<?php
/**
 * Republic of Costa Rica places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CR' => [
	'AB' => [
		_x('Colorado', 'AB', 'ry-wc-city-select'),
		_x('Las Juntas', 'AB', 'ry-wc-city-select'),
		_x('San Juan', 'AB', 'ry-wc-city-select'),
		_x('Sierra', 'AB', 'ry-wc-city-select'),
	],
	'AC' => [
		_x('Cangrejal', 'AC', 'ry-wc-city-select'),
		_x('Guaitil', 'AC', 'ry-wc-city-select'),
		_x('Palmichal', 'AC', 'ry-wc-city-select'),
		_x('Sabanillas', 'AC', 'ry-wc-city-select'),
		_x('San Ignacio', 'AC', 'ry-wc-city-select'),
	],
	'AL' => [
		_x('Alajuela', 'AL', 'ry-wc-city-select'),
		_x('Carrizal', 'AL', 'ry-wc-city-select'),
		_x('Desamparados', 'AL', 'ry-wc-city-select'),
		_x('Garita', 'AL', 'ry-wc-city-select'),
		_x('Guacima', 'AL', 'ry-wc-city-select'),
		_x('Rio Segundo', 'AL', 'ry-wc-city-select'),
		_x('Sabanilla', 'AL', 'ry-wc-city-select'),
		_x('San Antonio', 'AL', 'ry-wc-city-select'),
		_x('San Isidro', 'AL', 'ry-wc-city-select'),
		_x('San Jose', 'AL', 'ry-wc-city-select'),
		_x('San Rafael', 'AL', 'ry-wc-city-select'),
		_x('Sarapiqui', 'AL', 'ry-wc-city-select'),
		_x('Tambor', 'AL', 'ry-wc-city-select'),
		_x('Turrucares', 'AL', 'ry-wc-city-select'),
	],
	'AL2' => [
		_x('Alajuelita', 'AL2', 'ry-wc-city-select'),
		_x('Concepcion', 'AL2', 'ry-wc-city-select'),
		_x('San Antonio', 'AL2', 'ry-wc-city-select'),
		_x('San Felipe', 'AL2', 'ry-wc-city-select'),
		_x('San Josecito', 'AL2', 'ry-wc-city-select'),
	],
	'AL3' => [
		_x('Capellades', 'AL3', 'ry-wc-city-select'),
		_x('Cervantes', 'AL3', 'ry-wc-city-select'),
		_x('Pacayas', 'AL3', 'ry-wc-city-select'),
	],
	'AS' => [
		_x('Aserri', 'AS', 'ry-wc-city-select'),
		_x('Legua', 'AS', 'ry-wc-city-select'),
		_x('Monterrey', 'AS', 'ry-wc-city-select'),
		_x('Salitrillos', 'AS', 'ry-wc-city-select'),
		_x('San Gabriel', 'AS', 'ry-wc-city-select'),
		_x('Tarbaca', 'AS', 'ry-wc-city-select'),
		_x('Vuelta de Jorco', 'AS', 'ry-wc-city-select'),
	],
	'AT' => [
		_x('Atenas', 'AT', 'ry-wc-city-select'),
		_x('Concepcion', 'AT', 'ry-wc-city-select'),
		_x('Escobal', 'AT', 'ry-wc-city-select'),
		_x('Jesus', 'AT', 'ry-wc-city-select'),
		_x('Mercedes', 'AT', 'ry-wc-city-select'),
		_x('San Isidro', 'AT', 'ry-wc-city-select'),
		_x('San Jose', 'AT', 'ry-wc-city-select'),
		_x('Santa Eulalia', 'AT', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Bagaces', 'BA', 'ry-wc-city-select'),
		_x('La Fortuna', 'BA', 'ry-wc-city-select'),
		_x('Mogote', 'BA', 'ry-wc-city-select'),
		_x('Rio Naranjo', 'BA', 'ry-wc-city-select'),
	],
	'BA2' => [
		_x('Barva', 'BA2', 'ry-wc-city-select'),
		_x('San Jose de la Montana', 'BA2', 'ry-wc-city-select'),
		_x('San Pablo', 'BA2', 'ry-wc-city-select'),
		_x('San Pedro', 'BA2', 'ry-wc-city-select'),
		_x('San Roque', 'BA2', 'ry-wc-city-select'),
		_x('Santa Lucia', 'BA2', 'ry-wc-city-select'),
	],
	'BE' => [
		_x('La Asuncion', 'BE', 'ry-wc-city-select'),
		_x('La Ribera', 'BE', 'ry-wc-city-select'),
		_x('San Antonio', 'BE', 'ry-wc-city-select'),
	],
	'BUAI' => [
		_x('Biolley', 'BUAI', 'ry-wc-city-select'),
		_x('Boruca', 'BUAI', 'ry-wc-city-select'),
		_x('Brunka', 'BUAI', 'ry-wc-city-select'),
		_x('Buenos Aires', 'BUAI', 'ry-wc-city-select'),
		_x('Changuena', 'BUAI', 'ry-wc-city-select'),
		_x('Colinas', 'BUAI', 'ry-wc-city-select'),
		_x('Pilas', 'BUAI', 'ry-wc-city-select'),
		_x('Potrero Grande', 'BUAI', 'ry-wc-city-select'),
		_x('Volcan', 'BUAI', 'ry-wc-city-select'),
	],
	'CA' => [
		_x('Bebedero', 'CA', 'ry-wc-city-select'),
		_x('Canas', 'CA', 'ry-wc-city-select'),
		_x('Palmira', 'CA', 'ry-wc-city-select'),
		_x('Porozal', 'CA', 'ry-wc-city-select'),
		_x('San Miguel', 'CA', 'ry-wc-city-select'),
	],
	'CA2' => [
		_x('Belen', 'CA2', 'ry-wc-city-select'),
		_x('Filadelfia', 'CA2', 'ry-wc-city-select'),
		_x('Palmira', 'CA2', 'ry-wc-city-select'),
		_x('Sardinal', 'CA2', 'ry-wc-city-select'),
	],
	'CA3' => [
		_x('Aguacaliente o San Francisco', 'CA3', 'ry-wc-city-select'),
		_x('Carmen', 'CA3', 'ry-wc-city-select'),
		_x('Corralillo', 'CA3', 'ry-wc-city-select'),
		_x('Dulce Nombre', 'CA3', 'ry-wc-city-select'),
		_x('Guadalupe o Arenilla', 'CA3', 'ry-wc-city-select'),
		_x('Llano Grande', 'CA3', 'ry-wc-city-select'),
		_x('Occidental', 'CA3', 'ry-wc-city-select'),
		_x('Oriental', 'CA3', 'ry-wc-city-select'),
		_x('Quebradilla', 'CA3', 'ry-wc-city-select'),
		_x('San Nicolas', 'CA3', 'ry-wc-city-select'),
		_x('Tierra Blanca', 'CA3', 'ry-wc-city-select'),
	],
	'CO' => [
		_x('Canoas', 'CO', 'ry-wc-city-select'),
		_x('Corredor', 'CO', 'ry-wc-city-select'),
		_x('La Cuesta', 'CO', 'ry-wc-city-select'),
		_x('Laurel', 'CO', 'ry-wc-city-select'),
	],
	'COBR' => [
		_x('Aguabuena', 'COBR', 'ry-wc-city-select'),
		_x('Limoncito', 'COBR', 'ry-wc-city-select'),
		_x('Pittier', 'COBR', 'ry-wc-city-select'),
		_x('Sabalito', 'COBR', 'ry-wc-city-select'),
		_x('San Vito', 'COBR', 'ry-wc-city-select'),
	],
	'CU' => [
		_x('Curridabat', 'CU', 'ry-wc-city-select'),
		_x('Granadilla', 'CU', 'ry-wc-city-select'),
		_x('Sanchez', 'CU', 'ry-wc-city-select'),
		_x('Tirrases', 'CU', 'ry-wc-city-select'),
	],
	'DE' => [
		_x('Damas', 'DE', 'ry-wc-city-select'),
		_x('Desamparados', 'DE', 'ry-wc-city-select'),
		_x('Frailes', 'DE', 'ry-wc-city-select'),
		_x('Gravilias', 'DE', 'ry-wc-city-select'),
		_x('Los Guido', 'DE', 'ry-wc-city-select'),
		_x('Patarra', 'DE', 'ry-wc-city-select'),
		_x('Rosario', 'DE', 'ry-wc-city-select'),
		_x('San Antonio', 'DE', 'ry-wc-city-select'),
		_x('San Cristobal', 'DE', 'ry-wc-city-select'),
		_x('San Juan de Dios', 'DE', 'ry-wc-city-select'),
		_x('San Miguel', 'DE', 'ry-wc-city-select'),
		_x('San Rafael Abajo', 'DE', 'ry-wc-city-select'),
		_x('San Rafael Arriba', 'DE', 'ry-wc-city-select'),
	],
	'DO' => [
		_x('Copey', 'DO', 'ry-wc-city-select'),
		_x('Jardin', 'DO', 'ry-wc-city-select'),
		_x('Santa Maria', 'DO', 'ry-wc-city-select'),
	],
	'GU' => [
		_x('El Tejar', 'GU', 'ry-wc-city-select'),
		_x('Patio de Agua', 'GU', 'ry-wc-city-select'),
		_x('San Isidro', 'GU', 'ry-wc-city-select'),
		_x('Tobosi', 'GU', 'ry-wc-city-select'),
	],
	'ES' => [
		_x('Escazu', 'ES', 'ry-wc-city-select'),
		_x('San Antonio', 'ES', 'ry-wc-city-select'),
		_x('San Rafael', 'ES', 'ry-wc-city-select'),
	],
	'ES2' => [
		_x('Espiritu Santo', 'ES2', 'ry-wc-city-select'),
		_x('Macacona', 'ES2', 'ry-wc-city-select'),
		_x('San Jeronimo', 'ES2', 'ry-wc-city-select'),
		_x('San Juan Grande', 'ES2', 'ry-wc-city-select'),
		_x('San Rafael', 'ES2', 'ry-wc-city-select'),
	],
	'FL' => [
		_x('Barrantes', 'FL', 'ry-wc-city-select'),
		_x('Llorente', 'FL', 'ry-wc-city-select'),
		_x('San Joaquin', 'FL', 'ry-wc-city-select'),
	],
	'GA' => [
		_x('Jaco', 'GA', 'ry-wc-city-select'),
		_x('Tarcoles', 'GA', 'ry-wc-city-select'),
	],
	'GO' => [
		_x('Calle Blancos', 'GO', 'ry-wc-city-select'),
		_x('Guadalupe', 'GO', 'ry-wc-city-select'),
		_x('Ipis', 'GO', 'ry-wc-city-select'),
		_x('Mata de Platano', 'GO', 'ry-wc-city-select'),
		_x('Purral', 'GO', 'ry-wc-city-select'),
		_x('Rancho Redondo', 'GO', 'ry-wc-city-select'),
		_x('San Francisco', 'GO', 'ry-wc-city-select'),
	],
	'GO2' => [
		_x('Golfito', 'GO2', 'ry-wc-city-select'),
		_x('Guaycara', 'GO2', 'ry-wc-city-select'),
		_x('Pavon', 'GO2', 'ry-wc-city-select'),
		_x('Puerto Jimenez', 'GO2', 'ry-wc-city-select'),
	],
	'GR' => [
		_x('Bolivar', 'GR', 'ry-wc-city-select'),
		_x('Grecia', 'GR', 'ry-wc-city-select'),
		_x('Puente de Piedra', 'GR', 'ry-wc-city-select'),
		_x('San Isidro', 'GR', 'ry-wc-city-select'),
		_x('San Jose', 'GR', 'ry-wc-city-select'),
		_x('San Roque', 'GR', 'ry-wc-city-select'),
		_x('Tacares', 'GR', 'ry-wc-city-select'),
	],
	'GU2' => [
		_x('Duacari', 'GU2', 'ry-wc-city-select'),
		_x('Guacimo', 'GU2', 'ry-wc-city-select'),
		_x('Mercedes', 'GU2', 'ry-wc-city-select'),
		_x('Pocora', 'GU2', 'ry-wc-city-select'),
		_x('Rio Jimenez', 'GU2', 'ry-wc-city-select'),
	],
	'GU3' => [
		_x('Buenavista', 'GU3', 'ry-wc-city-select'),
		_x('Cote', 'GU3', 'ry-wc-city-select'),
		_x('Katira', 'GU3', 'ry-wc-city-select'),
		_x('San Rafael', 'GU3', 'ry-wc-city-select'),
	],
	'HE' => [
		_x('Heredia', 'HE', 'ry-wc-city-select'),
		_x('Mercedes', 'HE', 'ry-wc-city-select'),
		_x('San Francisco', 'HE', 'ry-wc-city-select'),
		_x('Ulloa', 'HE', 'ry-wc-city-select'),
		_x('Varablanca', 'HE', 'ry-wc-city-select'),
	],
	'HO' => [
		_x('Hojancha', 'HO', 'ry-wc-city-select'),
		_x('Huacas', 'HO', 'ry-wc-city-select'),
		_x('Monte Romo', 'HO', 'ry-wc-city-select'),
		_x('Puerto Carrillo', 'HO', 'ry-wc-city-select'),
	],
	'JI' => [
		_x('Juan Vinas', 'JI', 'ry-wc-city-select'),
		_x('Pejibaye', 'JI', 'ry-wc-city-select'),
		_x('Tucurrique', 'JI', 'ry-wc-city-select'),
	],
	'CR' => [
		_x('La Cruz', 'CR', 'ry-wc-city-select'),
		_x('La Garita', 'CR', 'ry-wc-city-select'),
		_x('Santa Cecilia', 'CR', 'ry-wc-city-select'),
		_x('Santa Elena', 'CR', 'ry-wc-city-select'),
	],
	'UN' => [
		_x('Concepcion', 'UN', 'ry-wc-city-select'),
		_x('Dulce Nombre', 'UN', 'ry-wc-city-select'),
		_x('Rio Azul', 'UN', 'ry-wc-city-select'),
		_x('San Diego', 'UN', 'ry-wc-city-select'),
		_x('San Juan', 'UN', 'ry-wc-city-select'),
		_x('San Rafael', 'UN', 'ry-wc-city-select'),
		_x('San Ramon', 'UN', 'ry-wc-city-select'),
		_x('Tres Rios', 'UN', 'ry-wc-city-select'),
	],
	'LECO' => [
		_x('Llano Bonito', 'LECO', 'ry-wc-city-select'),
		_x('San Andres', 'LECO', 'ry-wc-city-select'),
		_x('San Antonio', 'LECO', 'ry-wc-city-select'),
		_x('San Isidro', 'LECO', 'ry-wc-city-select'),
		_x('San Pablo', 'LECO', 'ry-wc-city-select'),
		_x('Santa Cruz', 'LECO', 'ry-wc-city-select'),
	],
	'LI' => [
		_x('Canas Dulces', 'LI', 'ry-wc-city-select'),
		_x('Curubande', 'LI', 'ry-wc-city-select'),
		_x('Liberia', 'LI', 'ry-wc-city-select'),
		_x('Mayorga', 'LI', 'ry-wc-city-select'),
		_x('Nacascolo', 'LI', 'ry-wc-city-select'),
	],
	'LI2' => [
		_x('Limon', 'LI2', 'ry-wc-city-select'),
		_x('Matama', 'LI2', 'ry-wc-city-select'),
		_x('Rio Blanco', 'LI2', 'ry-wc-city-select'),
		_x('Valle La Estrella', 'LI2', 'ry-wc-city-select'),
	],
	'LOCH' => [
		_x('Cano Negro', 'LOCH', 'ry-wc-city-select'),
		_x('El Amparo', 'LOCH', 'ry-wc-city-select'),
		_x('Los Chiles', 'LOCH', 'ry-wc-city-select'),
		_x('San Jorge', 'LOCH', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Batan', 'MA', 'ry-wc-city-select'),
		_x('Carrandi', 'MA', 'ry-wc-city-select'),
		_x('Matina', 'MA', 'ry-wc-city-select'),
	],
	'MOOC' => [
		_x('Mercedes', 'MOOC', 'ry-wc-city-select'),
		_x('Sabanilla', 'MOOC', 'ry-wc-city-select'),
		_x('San Pedro', 'MOOC', 'ry-wc-city-select'),
		_x('San Rafael', 'MOOC', 'ry-wc-city-select'),
	],
	'MOOR' => [
		_x('La Union', 'MOOR', 'ry-wc-city-select'),
		_x('Miramar', 'MOOR', 'ry-wc-city-select'),
		_x('San Isidro', 'MOOR', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Colon', 'MO', 'ry-wc-city-select'),
		_x('Guayabo', 'MO', 'ry-wc-city-select'),
		_x('Picagres', 'MO', 'ry-wc-city-select'),
		_x('Piedras Negras', 'MO', 'ry-wc-city-select'),
		_x('Tabarcia', 'MO', 'ry-wc-city-select'),
	],
	'MO2' => [
		_x('La Trinidad', 'MO2', 'ry-wc-city-select'),
		_x('San Jeronimo', 'MO2', 'ry-wc-city-select'),
		_x('San Vicente', 'MO2', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Bejuco', 'NA', 'ry-wc-city-select'),
		_x('Carmona', 'NA', 'ry-wc-city-select'),
		_x('Porvenir', 'NA', 'ry-wc-city-select'),
		_x('San Pablo', 'NA', 'ry-wc-city-select'),
		_x('Santa Rita', 'NA', 'ry-wc-city-select'),
		_x('Zapotal', 'NA', 'ry-wc-city-select'),
	],
	'NA2' => [
		_x('Cirri Sur', 'NA2', 'ry-wc-city-select'),
		_x('El Rosario', 'NA2', 'ry-wc-city-select'),
		_x('Naranjo', 'NA2', 'ry-wc-city-select'),
		_x('Palmitos', 'NA2', 'ry-wc-city-select'),
		_x('San Jeronimo', 'NA2', 'ry-wc-city-select'),
		_x('San Jose', 'NA2', 'ry-wc-city-select'),
		_x('San Juan', 'NA2', 'ry-wc-city-select'),
		_x('San Miguel', 'NA2', 'ry-wc-city-select'),
	],
	'NI' => [
		_x('Belen de Nosarita', 'NI', 'ry-wc-city-select'),
		_x('Mansion', 'NI', 'ry-wc-city-select'),
		_x('Nicoya', 'NI', 'ry-wc-city-select'),
		_x('Nosara', 'NI', 'ry-wc-city-select'),
		_x('Quebrada Honda', 'NI', 'ry-wc-city-select'),
		_x('Samara', 'NI', 'ry-wc-city-select'),
		_x('San Antonio', 'NI', 'ry-wc-city-select'),
	],
	'OR' => [
		_x('Cipreses', 'OR', 'ry-wc-city-select'),
		_x('Cot', 'OR', 'ry-wc-city-select'),
		_x('Potrero Cerrado', 'OR', 'ry-wc-city-select'),
		_x('San Rafael', 'OR', 'ry-wc-city-select'),
		_x('Santa Rosa', 'OR', 'ry-wc-city-select'),
	],
	'OR2' => [
		_x('Coyolar', 'OR2', 'ry-wc-city-select'),
		_x('El Mastate', 'OR2', 'ry-wc-city-select'),
		_x('Hacienda Vieja', 'OR2', 'ry-wc-city-select'),
		_x('La Ceiba', 'OR2', 'ry-wc-city-select'),
		_x('Orotina', 'OR2', 'ry-wc-city-select'),
	],
	'OS' => [
		_x('Bahia Ballena', 'OS', 'ry-wc-city-select'),
		_x('Palmar', 'OS', 'ry-wc-city-select'),
		_x('Piedras Blancas', 'OS', 'ry-wc-city-select'),
		_x('Puerto Cortes', 'OS', 'ry-wc-city-select'),
		_x('Sierpe', 'OS', 'ry-wc-city-select'),
	],
	'PA' => [
		_x('Buenos Aires', 'PA', 'ry-wc-city-select'),
		_x('Candelaria', 'PA', 'ry-wc-city-select'),
		_x('Esquipulas', 'PA', 'ry-wc-city-select'),
		_x('La Granja', 'PA', 'ry-wc-city-select'),
		_x('Palmares', 'PA', 'ry-wc-city-select'),
		_x('Santiago', 'PA', 'ry-wc-city-select'),
		_x('Zaragoza', 'PA', 'ry-wc-city-select'),
	],
	'PA2' => [
		_x('Cachi', 'PA2', 'ry-wc-city-select'),
		_x('Llanos de Santa Lucia', 'PA2', 'ry-wc-city-select'),
		_x('Orosi', 'PA2', 'ry-wc-city-select'),
		_x('Paraiso', 'PA2', 'ry-wc-city-select'),
		_x('Santiago', 'PA2', 'ry-wc-city-select'),
	],
	'PA3' => [
		_x('Parrita', 'PA3', 'ry-wc-city-select'),
	],
	'PEZE' => [
		_x('Baru', 'PEZE', 'ry-wc-city-select'),
		_x('Cajon', 'PEZE', 'ry-wc-city-select'),
		_x('Daniel Flores', 'PEZE', 'ry-wc-city-select'),
		_x('El General', 'PEZE', 'ry-wc-city-select'),
		_x('Paramo', 'PEZE', 'ry-wc-city-select'),
		_x('Pejibaye', 'PEZE', 'ry-wc-city-select'),
		_x('Platanares', 'PEZE', 'ry-wc-city-select'),
		_x('Rio Nuevo', 'PEZE', 'ry-wc-city-select'),
		_x('Rivas', 'PEZE', 'ry-wc-city-select'),
		_x('San Isidro de El General', 'PEZE', 'ry-wc-city-select'),
		_x('San Pedro', 'PEZE', 'ry-wc-city-select'),
	],
	'PO' => [
		_x('Carrillos', 'PO', 'ry-wc-city-select'),
		_x('Sabana Redonda', 'PO', 'ry-wc-city-select'),
		_x('San Juan', 'PO', 'ry-wc-city-select'),
		_x('San Pedro', 'PO', 'ry-wc-city-select'),
		_x('San Rafael', 'PO', 'ry-wc-city-select'),
	],
	'PO2' => [
		_x('Cariari', 'PO2', 'ry-wc-city-select'),
		_x('Colorado', 'PO2', 'ry-wc-city-select'),
		_x('Guapiles', 'PO2', 'ry-wc-city-select'),
		_x('Jimenez', 'PO2', 'ry-wc-city-select'),
		_x('Rita', 'PO2', 'ry-wc-city-select'),
		_x('Roxana', 'PO2', 'ry-wc-city-select'),
	],
	'PU' => [
		_x('Acapulco', 'PU', 'ry-wc-city-select'),
		_x('Arancibia', 'PU', 'ry-wc-city-select'),
		_x('Barranca', 'PU', 'ry-wc-city-select'),
		_x('Chacarita', 'PU', 'ry-wc-city-select'),
		_x('Chira', 'PU', 'ry-wc-city-select'),
		_x('Chomes', 'PU', 'ry-wc-city-select'),
		_x('Cobano', 'PU', 'ry-wc-city-select'),
		_x('El Roble', 'PU', 'ry-wc-city-select'),
		_x('Guacimal', 'PU', 'ry-wc-city-select'),
		_x('Isla Del Coco', 'PU', 'ry-wc-city-select'),
		_x('Lepanto', 'PU', 'ry-wc-city-select'),
		_x('Manzanillo', 'PU', 'ry-wc-city-select'),
		_x('Monte Verde', 'PU', 'ry-wc-city-select'),
		_x('Paquera', 'PU', 'ry-wc-city-select'),
		_x('Pitahaya', 'PU', 'ry-wc-city-select'),
		_x('Puntarenas', 'PU', 'ry-wc-city-select'),
	],
	'PU2' => [
		_x('Barbacoas', 'PU2', 'ry-wc-city-select'),
		_x('Candelarita', 'PU2', 'ry-wc-city-select'),
		_x('Chires', 'PU2', 'ry-wc-city-select'),
		_x('Desamparaditos', 'PU2', 'ry-wc-city-select'),
		_x('Grifo Alto', 'PU2', 'ry-wc-city-select'),
		_x('Mercedes Sur', 'PU2', 'ry-wc-city-select'),
		_x('San Antonio', 'PU2', 'ry-wc-city-select'),
		_x('San Rafael', 'PU2', 'ry-wc-city-select'),
		_x('Santiago', 'PU2', 'ry-wc-city-select'),
	],
	'QU' => [
		_x('Naranjito', 'QU', 'ry-wc-city-select'),
		_x('Quepos', 'QU', 'ry-wc-city-select'),
		_x('Savegre', 'QU', 'ry-wc-city-select'),
	],
	'RICU' => [
		_x('Rio Cuarto', 'RICU', 'ry-wc-city-select'),
	],
	'SACA' => [
		_x('Aguas Zarcas', 'SACA', 'ry-wc-city-select'),
		_x('Buenavista', 'SACA', 'ry-wc-city-select'),
		_x('Cutris', 'SACA', 'ry-wc-city-select'),
		_x('Florencia', 'SACA', 'ry-wc-city-select'),
		_x('La Fortuna', 'SACA', 'ry-wc-city-select'),
		_x('La Palmera', 'SACA', 'ry-wc-city-select'),
		_x('La Tigra', 'SACA', 'ry-wc-city-select'),
		_x('Monterrey', 'SACA', 'ry-wc-city-select'),
		_x('Pital', 'SACA', 'ry-wc-city-select'),
		_x('Pocosol', 'SACA', 'ry-wc-city-select'),
		_x('Quesada', 'SACA', 'ry-wc-city-select'),
		_x('Venado', 'SACA', 'ry-wc-city-select'),
		_x('Venecia', 'SACA', 'ry-wc-city-select'),
	],
	'SAIS' => [
		_x('Concepcion', 'SAIS', 'ry-wc-city-select'),
		_x('San Francisco', 'SAIS', 'ry-wc-city-select'),
		_x('San Isidro', 'SAIS', 'ry-wc-city-select'),
		_x('San Jose', 'SAIS', 'ry-wc-city-select'),
	],
	'SAJO' => [
		_x('Carmen', 'SAJO', 'ry-wc-city-select'),
		_x('Catedral', 'SAJO', 'ry-wc-city-select'),
		_x('Hatillo', 'SAJO', 'ry-wc-city-select'),
		_x('Hospital', 'SAJO', 'ry-wc-city-select'),
		_x('Mata Redonda', 'SAJO', 'ry-wc-city-select'),
		_x('Merced', 'SAJO', 'ry-wc-city-select'),
		_x('Pavas', 'SAJO', 'ry-wc-city-select'),
		_x('San Francisco de Dos Rios', 'SAJO', 'ry-wc-city-select'),
		_x('San Sebastian', 'SAJO', 'ry-wc-city-select'),
		_x('Uruca', 'SAJO', 'ry-wc-city-select'),
		_x('Zapote', 'SAJO', 'ry-wc-city-select'),
	],
	'SAMA' => [
		_x('Desmonte', 'SAMA', 'ry-wc-city-select'),
		_x('Jesus Maria', 'SAMA', 'ry-wc-city-select'),
		_x('San Mateo', 'SAMA', 'ry-wc-city-select'),
	],
	'SAPA' => [
		_x('Rincon de Sabanilla', 'SAPA', 'ry-wc-city-select'),
		_x('San Pablo', 'SAPA', 'ry-wc-city-select'),
	],
	'SARA' => [
		_x('Angeles', 'SARA', 'ry-wc-city-select'),
		_x('Concepcion', 'SARA', 'ry-wc-city-select'),
		_x('San Josecito', 'SARA', 'ry-wc-city-select'),
		_x('San Rafael', 'SARA', 'ry-wc-city-select'),
		_x('Santiago', 'SARA', 'ry-wc-city-select'),
	],
	'SARA2' => [
		_x('Alfaro', 'SARA2', 'ry-wc-city-select'),
		_x('Angeles', 'SARA2', 'ry-wc-city-select'),
		_x('Concepcion', 'SARA2', 'ry-wc-city-select'),
		_x('Penas Blancas', 'SARA2', 'ry-wc-city-select'),
		_x('Piedades Norte', 'SARA2', 'ry-wc-city-select'),
		_x('Piedades Sur', 'SARA2', 'ry-wc-city-select'),
		_x('San Isidro', 'SARA2', 'ry-wc-city-select'),
		_x('San Juan', 'SARA2', 'ry-wc-city-select'),
		_x('San Rafael', 'SARA2', 'ry-wc-city-select'),
		_x('San Ramon', 'SARA2', 'ry-wc-city-select'),
		_x('Santiago', 'SARA2', 'ry-wc-city-select'),
		_x('Volio', 'SARA2', 'ry-wc-city-select'),
		_x('Zapotal', 'SARA2', 'ry-wc-city-select'),
	],
	'SAAN' => [
		_x('Brasil', 'SAAN', 'ry-wc-city-select'),
		_x('Piedades', 'SAAN', 'ry-wc-city-select'),
		_x('Pozos', 'SAAN', 'ry-wc-city-select'),
		_x('Salitral', 'SAAN', 'ry-wc-city-select'),
		_x('Santa Ana', 'SAAN', 'ry-wc-city-select'),
		_x('Uruca', 'SAAN', 'ry-wc-city-select'),
	],
	'SABA' => [
		_x('Jesus', 'SABA', 'ry-wc-city-select'),
		_x('Puraba', 'SABA', 'ry-wc-city-select'),
		_x('San Juan', 'SABA', 'ry-wc-city-select'),
		_x('San Pedro', 'SABA', 'ry-wc-city-select'),
		_x('Santa Barbara', 'SABA', 'ry-wc-city-select'),
		_x('Santo Domingo', 'SABA', 'ry-wc-city-select'),
	],
	'SACR' => [
		_x('Bolson', 'SACR', 'ry-wc-city-select'),
		_x('Cabo Velas', 'SACR', 'ry-wc-city-select'),
		_x('Cartagena', 'SACR', 'ry-wc-city-select'),
		_x('Cuajiniquil', 'SACR', 'ry-wc-city-select'),
		_x('Diria', 'SACR', 'ry-wc-city-select'),
		_x('Santa Cruz', 'SACR', 'ry-wc-city-select'),
		_x('Tamarindo', 'SACR', 'ry-wc-city-select'),
		_x('Tempate', 'SACR', 'ry-wc-city-select'),
		_x('Veintisiete de Abril', 'SACR', 'ry-wc-city-select'),
	],
	'SADO' => [
		_x('Para', 'SADO', 'ry-wc-city-select'),
		_x('Paracito', 'SADO', 'ry-wc-city-select'),
		_x('San Miguel', 'SADO', 'ry-wc-city-select'),
		_x('San Vicente', 'SADO', 'ry-wc-city-select'),
		_x('Santa Rosa', 'SADO', 'ry-wc-city-select'),
		_x('Santo Domingo', 'SADO', 'ry-wc-city-select'),
		_x('Santo Tomas', 'SADO', 'ry-wc-city-select'),
		_x('Tures', 'SADO', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Curena', 'SA', 'ry-wc-city-select'),
		_x('La Virgen', 'SA', 'ry-wc-city-select'),
		_x('Las Horquetas', 'SA', 'ry-wc-city-select'),
		_x('Llanuras del Gaspar', 'SA', 'ry-wc-city-select'),
		_x('Puerto Viejo', 'SA', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Alegria', 'SI', 'ry-wc-city-select'),
		_x('El Cairo', 'SI', 'ry-wc-city-select'),
		_x('Florida', 'SI', 'ry-wc-city-select'),
		_x('Germania', 'SI', 'ry-wc-city-select'),
		_x('Pacuarito', 'SI', 'ry-wc-city-select'),
		_x('Siquirres', 'SI', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Bratsi', 'TA', 'ry-wc-city-select'),
		_x('Cahuita', 'TA', 'ry-wc-city-select'),
		_x('Sixaola', 'TA', 'ry-wc-city-select'),
		_x('Telire', 'TA', 'ry-wc-city-select'),
	],
	'TA2' => [
		_x('San Carlos', 'TA2', 'ry-wc-city-select'),
		_x('San Lorenzo', 'TA2', 'ry-wc-city-select'),
		_x('San Marcos', 'TA2', 'ry-wc-city-select'),
	],
	'TI' => [
		_x('Anselmo Llorente', 'TI', 'ry-wc-city-select'),
		_x('Cinco Esquinas', 'TI', 'ry-wc-city-select'),
		_x('Colima', 'TI', 'ry-wc-city-select'),
		_x('Leon XIII', 'TI', 'ry-wc-city-select'),
		_x('San Juan', 'TI', 'ry-wc-city-select'),
	],
	'TI2' => [
		_x('Arenal', 'TI2', 'ry-wc-city-select'),
		_x('Libano', 'TI2', 'ry-wc-city-select'),
		_x('Quebrada Grande', 'TI2', 'ry-wc-city-select'),
		_x('Santa Rosa', 'TI2', 'ry-wc-city-select'),
		_x('Tierras Morenas', 'TI2', 'ry-wc-city-select'),
		_x('Tilaran', 'TI2', 'ry-wc-city-select'),
		_x('Tronadora', 'TI2', 'ry-wc-city-select'),
	],
	'TU' => [
		_x('Chirripo', 'TU', 'ry-wc-city-select'),
		_x('La Isabel', 'TU', 'ry-wc-city-select'),
		_x('La Suiza', 'TU', 'ry-wc-city-select'),
		_x('Pavones', 'TU', 'ry-wc-city-select'),
		_x('Peralta', 'TU', 'ry-wc-city-select'),
		_x('Santa Cruz', 'TU', 'ry-wc-city-select'),
		_x('Santa Rosa', 'TU', 'ry-wc-city-select'),
		_x('Santa Teresita', 'TU', 'ry-wc-city-select'),
		_x('Tayutic', 'TU', 'ry-wc-city-select'),
		_x('Tres Equis', 'TU', 'ry-wc-city-select'),
		_x('Tuis', 'TU', 'ry-wc-city-select'),
		_x('Turrialba', 'TU', 'ry-wc-city-select'),
	],
	'TU2' => [
		_x('Carara', 'TU2', 'ry-wc-city-select'),
		_x('San Juan de Mata', 'TU2', 'ry-wc-city-select'),
		_x('San Luis', 'TU2', 'ry-wc-city-select'),
		_x('San Pablo', 'TU2', 'ry-wc-city-select'),
		_x('San Pedro', 'TU2', 'ry-wc-city-select'),
	],
	'UP' => [
		_x('Aguas Claras', 'UP', 'ry-wc-city-select'),
		_x('Bijagua', 'UP', 'ry-wc-city-select'),
		_x('Delicias', 'UP', 'ry-wc-city-select'),
		_x('Dos Rios', 'UP', 'ry-wc-city-select'),
		_x('San Jose o Pizote', 'UP', 'ry-wc-city-select'),
		_x('Upala', 'UP', 'ry-wc-city-select'),
		_x('Yolillal', 'UP', 'ry-wc-city-select'),
	],
	'VAVE' => [
		_x('Rodriguez', 'VAVE', 'ry-wc-city-select'),
		_x('San Pedro', 'VAVE', 'ry-wc-city-select'),
		_x('Sarchi Norte', 'VAVE', 'ry-wc-city-select'),
		_x('Sarchi Sur', 'VAVE', 'ry-wc-city-select'),
		_x('Toro Amarillo', 'VAVE', 'ry-wc-city-select'),
	],
	'VACO' => [
		_x('Cascajal', 'VACO', 'ry-wc-city-select'),
		_x('Dulce Nombre de Jesus', 'VACO', 'ry-wc-city-select'),
		_x('Patalillo', 'VACO', 'ry-wc-city-select'),
		_x('San Isidro', 'VACO', 'ry-wc-city-select'),
		_x('San Rafael', 'VACO', 'ry-wc-city-select'),
	],
	'ZA' => [
		_x('Brisas', 'ZA', 'ry-wc-city-select'),
		_x('Guadalupe', 'ZA', 'ry-wc-city-select'),
		_x('Laguna', 'ZA', 'ry-wc-city-select'),
		_x('Palmira', 'ZA', 'ry-wc-city-select'),
		_x('Tapesco', 'ZA', 'ry-wc-city-select'),
		_x('Zapote', 'ZA', 'ry-wc-city-select'),
		_x('Zarcero', 'ZA', 'ry-wc-city-select'),
	],
	]
];