<?php
/**
 * Republic of Cuba places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CU' => [
	'BO' => [
		_x('Santiago de las Vegas', 'BO', 'ry-wc-city-select'),
	],
	'CO' => [
		_x('Santa Maria del Rosario', 'CO', 'ry-wc-city-select'),
	],
	'AR' => [
		_x('Bahia Honda', 'AR', 'ry-wc-city-select'),
		_x('Municipio de Alquizar', 'AR', 'ry-wc-city-select'),
		_x('Municipio de Artemisa', 'AR', 'ry-wc-city-select'),
		_x('Municipio de Bauta', 'AR', 'ry-wc-city-select'),
		_x('Municipio de Caimito', 'AR', 'ry-wc-city-select'),
		_x('Municipio de Candelaria', 'AR', 'ry-wc-city-select'),
		_x('Municipio de Guanajay', 'AR', 'ry-wc-city-select'),
		_x('Municipio de Gueira de Melena', 'AR', 'ry-wc-city-select'),
		_x('Municipio de Mariel', 'AR', 'ry-wc-city-select'),
		_x('Municipio de San Antonio de los Banos', 'AR', 'ry-wc-city-select'),
		_x('Municipio de San Cristobal', 'AR', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Arroyo Naranjo', 'HA', 'ry-wc-city-select'),
		_x('Centro Habana', 'HA', 'ry-wc-city-select'),
		_x('Cerro', 'HA', 'ry-wc-city-select'),
		_x('Diez De Octubre', 'HA', 'ry-wc-city-select'),
		_x('La Habana Del Este', 'HA', 'ry-wc-city-select'),
		_x('La Habana Vieja', 'HA', 'ry-wc-city-select'),
		_x('La Lisa', 'HA', 'ry-wc-city-select'),
		_x('Municipio de Guanabacoa', 'HA', 'ry-wc-city-select'),
		_x('Municipio de Marianao', 'HA', 'ry-wc-city-select'),
		_x('Municipio de Regla', 'HA', 'ry-wc-city-select'),
		_x('Playa', 'HA', 'ry-wc-city-select'),
		_x('Plaza De La Revolucion', 'HA', 'ry-wc-city-select'),
		_x('San Miguel Del Padron', 'HA', 'ry-wc-city-select'),
	],
	'LATU' => [
		_x('Amancio', 'LATU', 'ry-wc-city-select'),
		_x('Colombia', 'LATU', 'ry-wc-city-select'),
		_x('Majibacoa', 'LATU', 'ry-wc-city-select'),
		_x('Municipio de Jesus Menendez', 'LATU', 'ry-wc-city-select'),
		_x('Municipio de Jobabo', 'LATU', 'ry-wc-city-select'),
		_x('Municipio de Las Tunas', 'LATU', 'ry-wc-city-select'),
		_x('Municipio de Manati', 'LATU', 'ry-wc-city-select'),
		_x('Municipio de Puerto Padre', 'LATU', 'ry-wc-city-select'),
	],
	'PRGR' => [
		_x('Bartolome Maso', 'PRGR', 'ry-wc-city-select'),
		_x('Buey Arriba', 'PRGR', 'ry-wc-city-select'),
		_x('Cauto Cristo', 'PRGR', 'ry-wc-city-select'),
		_x('Guisa', 'PRGR', 'ry-wc-city-select'),
		_x('Media Luna', 'PRGR', 'ry-wc-city-select'),
		_x('Municipio de Bayamo', 'PRGR', 'ry-wc-city-select'),
		_x('Municipio de Campechuela', 'PRGR', 'ry-wc-city-select'),
		_x('Municipio de Jiguani', 'PRGR', 'ry-wc-city-select'),
		_x('Municipio de Manzanillo', 'PRGR', 'ry-wc-city-select'),
		_x('Municipio de Niquero', 'PRGR', 'ry-wc-city-select'),
		_x('Municipio de Rio Cauto', 'PRGR', 'ry-wc-city-select'),
		_x('Pilon', 'PRGR', 'ry-wc-city-select'),
		_x('Yara', 'PRGR', 'ry-wc-city-select'),
	],
	'PRMA' => [
		_x('Municipio de Batabano', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de Bejucal', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de Gueines', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de Jaruco', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de Madruga', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de Melena del Sur', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de Nueva Paz', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de Quivican', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de San Jose de las Lajas', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de San Nicolas', 'PRMA', 'ry-wc-city-select'),
		_x('Municipio de Santa Cruz del Norte', 'PRMA', 'ry-wc-city-select'),
	],
	'PRCA' => [
		_x('Carlos Manuel De Cespedes', 'PRCA', 'ry-wc-city-select'),
		_x('Jimaguayu', 'PRCA', 'ry-wc-city-select'),
		_x('Minas', 'PRCA', 'ry-wc-city-select'),
		_x('Municipio de Camagueey', 'PRCA', 'ry-wc-city-select'),
		_x('Municipio de Esmeralda', 'PRCA', 'ry-wc-city-select'),
		_x('Municipio de Florida', 'PRCA', 'ry-wc-city-select'),
		_x('Municipio de Guaimaro', 'PRCA', 'ry-wc-city-select'),
		_x('Municipio de Nuevitas', 'PRCA', 'ry-wc-city-select'),
		_x('Municipio de Santa Cruz del Sur', 'PRCA', 'ry-wc-city-select'),
		_x('Najasa', 'PRCA', 'ry-wc-city-select'),
		_x('Sibanicu', 'PRCA', 'ry-wc-city-select'),
		_x('Sierra De Cubitas', 'PRCA', 'ry-wc-city-select'),
		_x('Vertientes', 'PRCA', 'ry-wc-city-select'),
	],
	'PRCIAV' => [
		_x('Bolivia', 'PRCIAV', 'ry-wc-city-select'),
		_x('Florencia', 'PRCIAV', 'ry-wc-city-select'),
		_x('Majagua', 'PRCIAV', 'ry-wc-city-select'),
		_x('Municipio de Baragua', 'PRCIAV', 'ry-wc-city-select'),
		_x('Municipio de Chambas', 'PRCIAV', 'ry-wc-city-select'),
		_x('Municipio de Ciego de Avila', 'PRCIAV', 'ry-wc-city-select'),
		_x('Municipio de Ciro Redondo', 'PRCIAV', 'ry-wc-city-select'),
		_x('Municipio de Moron', 'PRCIAV', 'ry-wc-city-select'),
		_x('Primero De Enero', 'PRCIAV', 'ry-wc-city-select'),
		_x('Venezuela', 'PRCIAV', 'ry-wc-city-select'),
	],
	'PRCI' => [
		_x('Cumanayagua', 'PRCI', 'ry-wc-city-select'),
		_x('Municipio de Abreus', 'PRCI', 'ry-wc-city-select'),
		_x('Municipio de Aguada de Pasajeros', 'PRCI', 'ry-wc-city-select'),
		_x('Municipio de Cienfuegos', 'PRCI', 'ry-wc-city-select'),
		_x('Municipio de Cruces', 'PRCI', 'ry-wc-city-select'),
		_x('Municipio de Palmira', 'PRCI', 'ry-wc-city-select'),
		_x('Municipio de Rodas', 'PRCI', 'ry-wc-city-select'),
		_x('Municipio de Santa Isabel de las Lajas', 'PRCI', 'ry-wc-city-select'),
	],
	'PRGU' => [
		_x('Caimanera', 'PRGU', 'ry-wc-city-select'),
		_x('El Salvador', 'PRGU', 'ry-wc-city-select'),
		_x('Imias', 'PRGU', 'ry-wc-city-select'),
		_x('Maisi', 'PRGU', 'ry-wc-city-select'),
		_x('Manuel Tames', 'PRGU', 'ry-wc-city-select'),
		_x('Municipio de Baracoa', 'PRGU', 'ry-wc-city-select'),
		_x('Municipio de Guantanamo', 'PRGU', 'ry-wc-city-select'),
		_x('Municipio de Yateras', 'PRGU', 'ry-wc-city-select'),
		_x('Niceto Perez', 'PRGU', 'ry-wc-city-select'),
		_x('San Antonio Del Sur', 'PRGU', 'ry-wc-city-select'),
	],
	'PRHO' => [
		_x('Baguanos', 'PRHO', 'ry-wc-city-select'),
		_x('Cacocum', 'PRHO', 'ry-wc-city-select'),
		_x('Cueto', 'PRHO', 'ry-wc-city-select'),
		_x('Frank Pais', 'PRHO', 'ry-wc-city-select'),
		_x('Moa', 'PRHO', 'ry-wc-city-select'),
		_x('Municipio de Antilla', 'PRHO', 'ry-wc-city-select'),
		_x('Municipio de Banes', 'PRHO', 'ry-wc-city-select'),
		_x('Municipio de Calixto Garcia', 'PRHO', 'ry-wc-city-select'),
		_x('Municipio de Gibara', 'PRHO', 'ry-wc-city-select'),
		_x('Municipio de Holguin', 'PRHO', 'ry-wc-city-select'),
		_x('Municipio de Mayari', 'PRHO', 'ry-wc-city-select'),
		_x('Municipio de Sagua de Tanamo', 'PRHO', 'ry-wc-city-select'),
		_x('Rafael Freyre', 'PRHO', 'ry-wc-city-select'),
		_x('Urbano Noris', 'PRHO', 'ry-wc-city-select'),
	],
	'PRMA2' => [
		_x('Calimete', 'PRMA2', 'ry-wc-city-select'),
		_x('Cienaga De Zapata', 'PRMA2', 'ry-wc-city-select'),
		_x('Limonar', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Cardenas', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Colon', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Jagueey Grande', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Jovellanos', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Los Arabos', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Marti', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Matanzas', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Pedro Betancourt', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Perico', 'PRMA2', 'ry-wc-city-select'),
		_x('Municipio de Union de Reyes', 'PRMA2', 'ry-wc-city-select'),
	],
	'PRPIDERI' => [
		_x('Minas De Matahambre', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de Consolacion del Sur', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de Guane', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de La Palma', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de Los Palacios', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de Mantua', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de Pinar del Rio', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de San Juan y Martinez', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de San Luis', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Municipio de Vinales', 'PRPIDERI', 'ry-wc-city-select'),
		_x('Sandino', 'PRPIDERI', 'ry-wc-city-select'),
	],
	'PRSASP' => [
		_x('La Sierpe', 'PRSASP', 'ry-wc-city-select'),
		_x('Municipio de Cabaiguan', 'PRSASP', 'ry-wc-city-select'),
		_x('Municipio de Fomento', 'PRSASP', 'ry-wc-city-select'),
		_x('Municipio de Jatibonico', 'PRSASP', 'ry-wc-city-select'),
		_x('Municipio de Sancti Spiritus', 'PRSASP', 'ry-wc-city-select'),
		_x('Municipio de Trinidad', 'PRSASP', 'ry-wc-city-select'),
		_x('Municipio de Yaguajay', 'PRSASP', 'ry-wc-city-select'),
		_x('Taguasco', 'PRSASP', 'ry-wc-city-select'),
	],
	'PRSACU' => [
		_x('Contramaestre', 'PRSACU', 'ry-wc-city-select'),
		_x('Guama', 'PRSACU', 'ry-wc-city-select'),
		_x('Mella', 'PRSACU', 'ry-wc-city-select'),
		_x('Municipio de Palma Soriano', 'PRSACU', 'ry-wc-city-select'),
		_x('Municipio de San Luis', 'PRSACU', 'ry-wc-city-select'),
		_x('Municipio de Santiago de Cuba', 'PRSACU', 'ry-wc-city-select'),
		_x('Segundo Frente', 'PRSACU', 'ry-wc-city-select'),
		_x('Songo - La Maya', 'PRSACU', 'ry-wc-city-select'),
		_x('Tercer Frente', 'PRSACU', 'ry-wc-city-select'),
	],
	'PRVICL' => [
		_x('Manicaragua', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Caibarien', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Camajuani', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Cifuentes', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Corralillo', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Encrucijada', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Placetas', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Quemado de Gueines', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Ranchuelo', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Sagua la Grande', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Santa Clara', 'PRVICL', 'ry-wc-city-select'),
		_x('Municipio de Santo Domingo', 'PRVICL', 'ry-wc-city-select'),
		_x('Remedios', 'PRVICL', 'ry-wc-city-select'),
	],
	]
];