<?php
/**
 * Republic of Cyprus places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'CY' => [
	'LE' => [
		_x('Saint Spyridonas', 'LE', 'ry-wc-city-select'),
	],
	'EPAM' => [
		_x('Acheritou', 'EPAM', 'ry-wc-city-select'),
		_x('Achna', 'EPAM', 'ry-wc-city-select'),
		_x('Afanteia', 'EPAM', 'ry-wc-city-select'),
		_x('Agia Napa', 'EPAM', 'ry-wc-city-select'),
		_x('Agia Trias', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Andronikos', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Andronikos', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Chariton', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Efstathios', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Georgios', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Iakovos', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Ilias', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Nikolaos', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Sergios', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Symeon', 'EPAM', 'ry-wc-city-select'),
		_x('Agios Theodoros', 'EPAM', 'ry-wc-city-select'),
		_x('Aigialousa', 'EPAM', 'ry-wc-city-select'),
		_x('Akanthou', 'EPAM', 'ry-wc-city-select'),
		_x('Aloda', 'EPAM', 'ry-wc-city-select'),
		_x('Ammochostos', 'EPAM', 'ry-wc-city-select'),
		_x('Ammochostos Municipality', 'EPAM', 'ry-wc-city-select'),
		_x('Angastina', 'EPAM', 'ry-wc-city-select'),
		_x('Ardana', 'EPAM', 'ry-wc-city-select'),
		_x('Arnadi', 'EPAM', 'ry-wc-city-select'),
		_x('Artemi', 'EPAM', 'ry-wc-city-select'),
		_x('Askeia', 'EPAM', 'ry-wc-city-select'),
		_x('Avgolida', 'EPAM', 'ry-wc-city-select'),
		_x('Avgorou', 'EPAM', 'ry-wc-city-select'),
		_x('Bogazi', 'EPAM', 'ry-wc-city-select'),
		_x('Davlos', 'EPAM', 'ry-wc-city-select'),
		_x('Deryneia', 'EPAM', 'ry-wc-city-select'),
		_x('Egkomi', 'EPAM', 'ry-wc-city-select'),
		_x('Eptakomi', 'EPAM', 'ry-wc-city-select'),
		_x('Flamoudi', 'EPAM', 'ry-wc-city-select'),
		_x('Frenaros', 'EPAM', 'ry-wc-city-select'),
		_x('Gaidouras', 'EPAM', 'ry-wc-city-select'),
		_x('Galateia', 'EPAM', 'ry-wc-city-select'),
		_x('Galinoporni', 'EPAM', 'ry-wc-city-select'),
		_x('Gastria', 'EPAM', 'ry-wc-city-select'),
		_x('Genagra', 'EPAM', 'ry-wc-city-select'),
		_x('Gerani', 'EPAM', 'ry-wc-city-select'),
		_x('Goufes', 'EPAM', 'ry-wc-city-select'),
		_x('Gypsou', 'EPAM', 'ry-wc-city-select'),
		_x('Kalopsida', 'EPAM', 'ry-wc-city-select'),
		_x('Kiados', 'EPAM', 'ry-wc-city-select'),
		_x('Knodara', 'EPAM', 'ry-wc-city-select'),
		_x('Koilanemos', 'EPAM', 'ry-wc-city-select'),
		_x('Koma tou Gialou', 'EPAM', 'ry-wc-city-select'),
		_x('Komi', 'EPAM', 'ry-wc-city-select'),
		_x('Kontea', 'EPAM', 'ry-wc-city-select'),
		_x('Kornokipos', 'EPAM', 'ry-wc-city-select'),
		_x('Koroveia', 'EPAM', 'ry-wc-city-select'),
		_x('Kouklia', 'EPAM', 'ry-wc-city-select'),
		_x('Krideia', 'EPAM', 'ry-wc-city-select'),
		_x('Lapathos', 'EPAM', 'ry-wc-city-select'),
		_x('Lefkonoiko', 'EPAM', 'ry-wc-city-select'),
		_x('Leonarisso', 'EPAM', 'ry-wc-city-select'),
		_x('Limnia', 'EPAM', 'ry-wc-city-select'),
		_x('Liopetri', 'EPAM', 'ry-wc-city-select'),
		_x('Livadia', 'EPAM', 'ry-wc-city-select'),
		_x('Lysi', 'EPAM', 'ry-wc-city-select'),
		_x('Lythragkomi', 'EPAM', 'ry-wc-city-select'),
		_x('Makrasyka', 'EPAM', 'ry-wc-city-select'),
		_x('Mandres', 'EPAM', 'ry-wc-city-select'),
		_x('Maratha', 'EPAM', 'ry-wc-city-select'),
		_x('Marathovounos', 'EPAM', 'ry-wc-city-select'),
		_x('Melanarga', 'EPAM', 'ry-wc-city-select'),
		_x('Melounta', 'EPAM', 'ry-wc-city-select'),
		_x('Milia', 'EPAM', 'ry-wc-city-select'),
		_x('Monarga', 'EPAM', 'ry-wc-city-select'),
		_x('Mousoulita', 'EPAM', 'ry-wc-city-select'),
		_x('Neta', 'EPAM', 'ry-wc-city-select'),
		_x('Ovgoros', 'EPAM', 'ry-wc-city-select'),
		_x('Paralimni', 'EPAM', 'ry-wc-city-select'),
		_x('Patriki', 'EPAM', 'ry-wc-city-select'),
		_x('Peristerona', 'EPAM', 'ry-wc-city-select'),
		_x('Perivolia', 'EPAM', 'ry-wc-city-select'),
		_x('Pigi', 'EPAM', 'ry-wc-city-select'),
		_x('Platani', 'EPAM', 'ry-wc-city-select'),
		_x('Platanissos', 'EPAM', 'ry-wc-city-select'),
		_x('Prastio', 'EPAM', 'ry-wc-city-select'),
		_x('Psyllatos', 'EPAM', 'ry-wc-city-select'),
		_x('Pyrga', 'EPAM', 'ry-wc-city-select'),
		_x('Rizokarpaso', 'EPAM', 'ry-wc-city-select'),
		_x('Santalaris', 'EPAM', 'ry-wc-city-select'),
		_x('Sinta', 'EPAM', 'ry-wc-city-select'),
		_x('Sotira', 'EPAM', 'ry-wc-city-select'),
		_x('Spathariko', 'EPAM', 'ry-wc-city-select'),
		_x('Strongylos', 'EPAM', 'ry-wc-city-select'),
		_x('Stylloi', 'EPAM', 'ry-wc-city-select'),
		_x('Sygkrasi', 'EPAM', 'ry-wc-city-select'),
		_x('Tavrou', 'EPAM', 'ry-wc-city-select'),
		_x('Trikomo', 'EPAM', 'ry-wc-city-select'),
		_x('Trypimeni', 'EPAM', 'ry-wc-city-select'),
		_x('Vasili', 'EPAM', 'ry-wc-city-select'),
		_x('Vatili', 'EPAM', 'ry-wc-city-select'),
		_x('Vitsada', 'EPAM', 'ry-wc-city-select'),
		_x('Vokolida', 'EPAM', 'ry-wc-city-select'),
		_x('Vothylakas', 'EPAM', 'ry-wc-city-select'),
	],
	'EPKE' => [
		_x('Agia Eirini', 'EPKE', 'ry-wc-city-select'),
		_x('Agios Amvrosios', 'EPKE', 'ry-wc-city-select'),
		_x('Agios Epiktitos', 'EPKE', 'ry-wc-city-select'),
		_x('Agios Ermolaos', 'EPKE', 'ry-wc-city-select'),
		_x('Agios Georgios', 'EPKE', 'ry-wc-city-select'),
		_x('Agirda', 'EPKE', 'ry-wc-city-select'),
		_x('Agridaki', 'EPKE', 'ry-wc-city-select'),
		_x('Asomatos', 'EPKE', 'ry-wc-city-select'),
		_x('Belapais', 'EPKE', 'ry-wc-city-select'),
		_x('Charkeia', 'EPKE', 'ry-wc-city-select'),
		_x('Diorios', 'EPKE', 'ry-wc-city-select'),
		_x('Elia', 'EPKE', 'ry-wc-city-select'),
		_x('Fota', 'EPKE', 'ry-wc-city-select'),
		_x('Ftericha', 'EPKE', 'ry-wc-city-select'),
		_x('Kalograia', 'EPKE', 'ry-wc-city-select'),
		_x('Kampyli', 'EPKE', 'ry-wc-city-select'),
		_x('Karakoumi', 'EPKE', 'ry-wc-city-select'),
		_x('Karavas', 'EPKE', 'ry-wc-city-select'),
		_x('Karmi', 'EPKE', 'ry-wc-city-select'),
		_x('Karpaseia', 'EPKE', 'ry-wc-city-select'),
		_x('Kato Dikomo', 'EPKE', 'ry-wc-city-select'),
		_x('Kazafani', 'EPKE', 'ry-wc-city-select'),
		_x('Keryneia', 'EPKE', 'ry-wc-city-select'),
		_x('Kiomourtzou', 'EPKE', 'ry-wc-city-select'),
		_x('Klepini', 'EPKE', 'ry-wc-city-select'),
		_x('Kontemenos', 'EPKE', 'ry-wc-city-select'),
		_x('Kormakitis', 'EPKE', 'ry-wc-city-select'),
		_x('Koutsoventis', 'EPKE', 'ry-wc-city-select'),
		_x('Krini', 'EPKE', 'ry-wc-city-select'),
		_x('Kyrenia Municipality', 'EPKE', 'ry-wc-city-select'),
		_x('Lapithos', 'EPKE', 'ry-wc-city-select'),
		_x('Larnakas Lapithou', 'EPKE', 'ry-wc-city-select'),
		_x('Livera', 'EPKE', 'ry-wc-city-select'),
		_x('Motides', 'EPKE', 'ry-wc-city-select'),
		_x('Myrtou', 'EPKE', 'ry-wc-city-select'),
		_x('Orga', 'EPKE', 'ry-wc-city-select'),
		_x('Palaiosofos', 'EPKE', 'ry-wc-city-select'),
		_x('Panagra', 'EPKE', 'ry-wc-city-select'),
		_x('Pano Dikomo', 'EPKE', 'ry-wc-city-select'),
		_x('Pileri', 'EPKE', 'ry-wc-city-select'),
		_x('Sichari', 'EPKE', 'ry-wc-city-select'),
		_x('Sysklipos', 'EPKE', 'ry-wc-city-select'),
		_x('Templos', 'EPKE', 'ry-wc-city-select'),
		_x('Thermeia', 'EPKE', 'ry-wc-city-select'),
		_x('Trapeza', 'EPKE', 'ry-wc-city-select'),
		_x('Trimithi', 'EPKE', 'ry-wc-city-select'),
		_x('Vasileia', 'EPKE', 'ry-wc-city-select'),
		_x('Vouno', 'EPKE', 'ry-wc-city-select'),
	],
	'EPLA' => [
		_x('Agia Anna', 'EPLA', 'ry-wc-city-select'),
		_x('Agioi Vavatsinias', 'EPLA', 'ry-wc-city-select'),
		_x('Alaminos', 'EPLA', 'ry-wc-city-select'),
		_x('Alethriko', 'EPLA', 'ry-wc-city-select'),
		_x('Anafotida', 'EPLA', 'ry-wc-city-select'),
		_x('Anglisides', 'EPLA', 'ry-wc-city-select'),
		_x('Aplanta', 'EPLA', 'ry-wc-city-select'),
		_x('Aradippou', 'EPLA', 'ry-wc-city-select'),
		_x('Arsos', 'EPLA', 'ry-wc-city-select'),
		_x('Athienou', 'EPLA', 'ry-wc-city-select'),
		_x('Avdellero', 'EPLA', 'ry-wc-city-select'),
		_x('Choirokoitia', 'EPLA', 'ry-wc-city-select'),
		_x('Delikipos', 'EPLA', 'ry-wc-city-select'),
		_x('Dromolaxia', 'EPLA', 'ry-wc-city-select'),
		_x('Kalavasos', 'EPLA', 'ry-wc-city-select'),
		_x('Kato Drys', 'EPLA', 'ry-wc-city-select'),
		_x('Kato Lefkara', 'EPLA', 'ry-wc-city-select'),
		_x('Kellia', 'EPLA', 'ry-wc-city-select'),
		_x('Kiti', 'EPLA', 'ry-wc-city-select'),
		_x('Kivisili', 'EPLA', 'ry-wc-city-select'),
		_x('Klavdia', 'EPLA', 'ry-wc-city-select'),
		_x('Kochi', 'EPLA', 'ry-wc-city-select'),
		_x('Kofinou', 'EPLA', 'ry-wc-city-select'),
		_x('Kornos', 'EPLA', 'ry-wc-city-select'),
		_x('Lageia', 'EPLA', 'ry-wc-city-select'),
		_x('Larnaka', 'EPLA', 'ry-wc-city-select'),
		_x('Mari', 'EPLA', 'ry-wc-city-select'),
		_x('Maroni', 'EPLA', 'ry-wc-city-select'),
		_x('Mazotos', 'EPLA', 'ry-wc-city-select'),
		_x('Melini', 'EPLA', 'ry-wc-city-select'),
		_x('Melouseia', 'EPLA', 'ry-wc-city-select'),
		_x('Meneou', 'EPLA', 'ry-wc-city-select'),
		_x('Menogeia', 'EPLA', 'ry-wc-city-select'),
		_x('Mosfiloti', 'EPLA', 'ry-wc-city-select'),
		_x('Odou', 'EPLA', 'ry-wc-city-select'),
		_x('Ora', 'EPLA', 'ry-wc-city-select'),
		_x('Ormideia', 'EPLA', 'ry-wc-city-select'),
		_x('Pano Lefkara', 'EPLA', 'ry-wc-city-select'),
		_x('Pergamos', 'EPLA', 'ry-wc-city-select'),
		_x('Petrofani', 'EPLA', 'ry-wc-city-select'),
		_x('Psematismenos', 'EPLA', 'ry-wc-city-select'),
		_x('Psevdas', 'EPLA', 'ry-wc-city-select'),
		_x('Pyla', 'EPLA', 'ry-wc-city-select'),
		_x('Skarinou', 'EPLA', 'ry-wc-city-select'),
		_x('Softades', 'EPLA', 'ry-wc-city-select'),
		_x('Tersefanou', 'EPLA', 'ry-wc-city-select'),
		_x('Tochni', 'EPLA', 'ry-wc-city-select'),
		_x('Tremetousia', 'EPLA', 'ry-wc-city-select'),
		_x('Troulloi', 'EPLA', 'ry-wc-city-select'),
		_x('Vavatsinia', 'EPLA', 'ry-wc-city-select'),
		_x('Vavla', 'EPLA', 'ry-wc-city-select'),
		_x('Voroklini', 'EPLA', 'ry-wc-city-select'),
		_x('Xylofagou', 'EPLA', 'ry-wc-city-select'),
		_x('Xylotymvou', 'EPLA', 'ry-wc-city-select'),
		_x('Zygi', 'EPLA', 'ry-wc-city-select'),
	],
	'EPLE' => [
		_x('Agia', 'EPLE', 'ry-wc-city-select'),
		_x('Agia Eirini', 'EPLE', 'ry-wc-city-select'),
		_x('Agia Marina', 'EPLE', 'ry-wc-city-select'),
		_x('Agia Marina', 'EPLE', 'ry-wc-city-select'),
		_x('Agia Varvara', 'EPLE', 'ry-wc-city-select'),
		_x('Agioi Iliofotoi', 'EPLE', 'ry-wc-city-select'),
		_x('Agioi Trimithias', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Dometios', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Epifanios', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Epifanios', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Georgios', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Georgios', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Ioannis', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Ioannis Selemani', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Nikolaos', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Sozomenos', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Theodoros', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Theodoros', 'EPLE', 'ry-wc-city-select'),
		_x('Agios Vasileios', 'EPLE', 'ry-wc-city-select'),
		_x('Aglantzia', 'EPLE', 'ry-wc-city-select'),
		_x('Agrokipia', 'EPLE', 'ry-wc-city-select'),
		_x('Akaki', 'EPLE', 'ry-wc-city-select'),
		_x('Alampra', 'EPLE', 'ry-wc-city-select'),
		_x('Alevga', 'EPLE', 'ry-wc-city-select'),
		_x('Alithinou', 'EPLE', 'ry-wc-city-select'),
		_x('Alona', 'EPLE', 'ry-wc-city-select'),
		_x('Ammadies', 'EPLE', 'ry-wc-city-select'),
		_x('Ampelikou', 'EPLE', 'ry-wc-city-select'),
		_x('Anageia', 'EPLE', 'ry-wc-city-select'),
		_x('Analiontas', 'EPLE', 'ry-wc-city-select'),
		_x('Angolemi', 'EPLE', 'ry-wc-city-select'),
		_x('Apliki', 'EPLE', 'ry-wc-city-select'),
		_x('Arediou', 'EPLE', 'ry-wc-city-select'),
		_x('Argaki', 'EPLE', 'ry-wc-city-select'),
		_x('Askas', 'EPLE', 'ry-wc-city-select'),
		_x('Astromeritis', 'EPLE', 'ry-wc-city-select'),
		_x('Avlona', 'EPLE', 'ry-wc-city-select'),
		_x('Beikioi', 'EPLE', 'ry-wc-city-select'),
		_x('Dali', 'EPLE', 'ry-wc-city-select'),
		_x('Deneia', 'EPLE', 'ry-wc-city-select'),
		_x('Dyo Potamoi', 'EPLE', 'ry-wc-city-select'),
		_x('Egkomi', 'EPLE', 'ry-wc-city-select'),
		_x('Elia', 'EPLE', 'ry-wc-city-select'),
		_x('Epicho', 'EPLE', 'ry-wc-city-select'),
		_x('Episkopeio', 'EPLE', 'ry-wc-city-select'),
		_x('Ergates', 'EPLE', 'ry-wc-city-select'),
		_x('Evrychou', 'EPLE', 'ry-wc-city-select'),
		_x('Exo Metochi', 'EPLE', 'ry-wc-city-select'),
		_x('Farmakas', 'EPLE', 'ry-wc-city-select'),
		_x('Fikardou', 'EPLE', 'ry-wc-city-select'),
		_x('Flasou', 'EPLE', 'ry-wc-city-select'),
		_x('Frodisia', 'EPLE', 'ry-wc-city-select'),
		_x('Fterikoudi', 'EPLE', 'ry-wc-city-select'),
		_x('Fyllia', 'EPLE', 'ry-wc-city-select'),
		_x('Galata', 'EPLE', 'ry-wc-city-select'),
		_x('Galini', 'EPLE', 'ry-wc-city-select'),
		_x('Gerakies', 'EPLE', 'ry-wc-city-select'),
		_x('Geri', 'EPLE', 'ry-wc-city-select'),
		_x('Gerolakkos', 'EPLE', 'ry-wc-city-select'),
		_x('Gourri', 'EPLE', 'ry-wc-city-select'),
		_x('Kakopetria', 'EPLE', 'ry-wc-city-select'),
		_x('Kaliana', 'EPLE', 'ry-wc-city-select'),
		_x('Kalo Chorio', 'EPLE', 'ry-wc-city-select'),
		_x('Kalo Chorio', 'EPLE', 'ry-wc-city-select'),
		_x('Kalo Chorio Kapouti', 'EPLE', 'ry-wc-city-select'),
		_x('Kalopanagiotis', 'EPLE', 'ry-wc-city-select'),
		_x('Kalyvakia', 'EPLE', 'ry-wc-city-select'),
		_x('Kampi', 'EPLE', 'ry-wc-city-select'),
		_x('Kampia', 'EPLE', 'ry-wc-city-select'),
		_x('Kampos', 'EPLE', 'ry-wc-city-select'),
		_x('Kanli', 'EPLE', 'ry-wc-city-select'),
		_x('Kannavia', 'EPLE', 'ry-wc-city-select'),
		_x('Kapedes', 'EPLE', 'ry-wc-city-select'),
		_x('Karavostasi', 'EPLE', 'ry-wc-city-select'),
		_x('Kataliontas', 'EPLE', 'ry-wc-city-select'),
		_x('Kato Deftera', 'EPLE', 'ry-wc-city-select'),
		_x('Kato Koutrafas', 'EPLE', 'ry-wc-city-select'),
		_x('Kato Moni', 'EPLE', 'ry-wc-city-select'),
		_x('Kato Pyrgos', 'EPLE', 'ry-wc-city-select'),
		_x('Kato Zodeia', 'EPLE', 'ry-wc-city-select'),
		_x('Katokopia', 'EPLE', 'ry-wc-city-select'),
		_x('Katydata', 'EPLE', 'ry-wc-city-select'),
		_x('Kazivera', 'EPLE', 'ry-wc-city-select'),
		_x('Kioneli', 'EPLE', 'ry-wc-city-select'),
		_x('Klirou', 'EPLE', 'ry-wc-city-select'),
		_x('Kokkina', 'EPLE', 'ry-wc-city-select'),
		_x('Kokkinotrimithia', 'EPLE', 'ry-wc-city-select'),
		_x('Korakou', 'EPLE', 'ry-wc-city-select'),
		_x('Kotsiatis', 'EPLE', 'ry-wc-city-select'),
		_x('Kourou Monastiri', 'EPLE', 'ry-wc-city-select'),
		_x('Kyra', 'EPLE', 'ry-wc-city-select'),
		_x('Kythrea', 'EPLE', 'ry-wc-city-select'),
		_x('Lagoudera', 'EPLE', 'ry-wc-city-select'),
		_x('Lakatamia', 'EPLE', 'ry-wc-city-select'),
		_x('Latsia', 'EPLE', 'ry-wc-city-select'),
		_x('Lazanias', 'EPLE', 'ry-wc-city-select'),
		_x('Lefka', 'EPLE', 'ry-wc-city-select'),
		_x('Lefkosia', 'EPLE', 'ry-wc-city-select'),
		_x('Linou', 'EPLE', 'ry-wc-city-select'),
		_x('Livadia', 'EPLE', 'ry-wc-city-select'),
		_x('Louroukina', 'EPLE', 'ry-wc-city-select'),
		_x('Loutros', 'EPLE', 'ry-wc-city-select'),
		_x('Lympia', 'EPLE', 'ry-wc-city-select'),
		_x('Lythrodontas', 'EPLE', 'ry-wc-city-select'),
		_x('Malounta', 'EPLE', 'ry-wc-city-select'),
		_x('Mammari', 'EPLE', 'ry-wc-city-select'),
		_x('Mandres', 'EPLE', 'ry-wc-city-select'),
		_x('Mansoura', 'EPLE', 'ry-wc-city-select'),
		_x('Margi', 'EPLE', 'ry-wc-city-select'),
		_x('Margo', 'EPLE', 'ry-wc-city-select'),
		_x('Masari', 'EPLE', 'ry-wc-city-select'),
		_x('Mathiatis', 'EPLE', 'ry-wc-city-select'),
		_x('Meniko', 'EPLE', 'ry-wc-city-select'),
		_x('Mia Milia', 'EPLE', 'ry-wc-city-select'),
		_x('Mitsero', 'EPLE', 'ry-wc-city-select'),
		_x('Mora', 'EPLE', 'ry-wc-city-select'),
		_x('Morfou', 'EPLE', 'ry-wc-city-select'),
		_x('Mosfili', 'EPLE', 'ry-wc-city-select'),
		_x('Moutoutllas', 'EPLE', 'ry-wc-city-select'),
		_x('Mylikouri', 'EPLE', 'ry-wc-city-select'),
		_x('Neo Chorio', 'EPLE', 'ry-wc-city-select'),
		_x('Nicosia Municipality', 'EPLE', 'ry-wc-city-select'),
		_x('Nikitari', 'EPLE', 'ry-wc-city-select'),
		_x('Nikitas', 'EPLE', 'ry-wc-city-select'),
		_x('Nisou', 'EPLE', 'ry-wc-city-select'),
		_x('Oikos', 'EPLE', 'ry-wc-city-select'),
		_x('Orounta', 'EPLE', 'ry-wc-city-select'),
		_x('Ortakioi', 'EPLE', 'ry-wc-city-select'),
		_x('Pachyammos', 'EPLE', 'ry-wc-city-select'),
		_x('Palaichori', 'EPLE', 'ry-wc-city-select'),
		_x('Palaichori Morfou', 'EPLE', 'ry-wc-city-select'),
		_x('Palaikythro', 'EPLE', 'ry-wc-city-select'),
		_x('Palaiometocho', 'EPLE', 'ry-wc-city-select'),
		_x('Pano Deftera', 'EPLE', 'ry-wc-city-select'),
		_x('Pano Koutrafas', 'EPLE', 'ry-wc-city-select'),
		_x('Pano Pyrgos', 'EPLE', 'ry-wc-city-select'),
		_x('Pano Zodeia', 'EPLE', 'ry-wc-city-select'),
		_x('Pedoulas', 'EPLE', 'ry-wc-city-select'),
		_x('Pentageia', 'EPLE', 'ry-wc-city-select'),
		_x('Pera', 'EPLE', 'ry-wc-city-select'),
		_x('Pera Chorio', 'EPLE', 'ry-wc-city-select'),
		_x('Peristerona', 'EPLE', 'ry-wc-city-select'),
		_x('Peristeronari', 'EPLE', 'ry-wc-city-select'),
		_x('Petra', 'EPLE', 'ry-wc-city-select'),
		_x('Petra tou Digeni', 'EPLE', 'ry-wc-city-select'),
		_x('Pigenia', 'EPLE', 'ry-wc-city-select'),
		_x('Platanistasa', 'EPLE', 'ry-wc-city-select'),
		_x('Politiko', 'EPLE', 'ry-wc-city-select'),
		_x('Polystypos', 'EPLE', 'ry-wc-city-select'),
		_x('Potami', 'EPLE', 'ry-wc-city-select'),
		_x('Potamia', 'EPLE', 'ry-wc-city-select'),
		_x('Prastio', 'EPLE', 'ry-wc-city-select'),
		_x('Psimolofou', 'EPLE', 'ry-wc-city-select'),
		_x('Pyrogi', 'EPLE', 'ry-wc-city-select'),
		_x('Saranti', 'EPLE', 'ry-wc-city-select'),
		_x('Selladi tou Appi kai Agio Georgoudi', 'EPLE', 'ry-wc-city-select'),
		_x('Sia', 'EPLE', 'ry-wc-city-select'),
		_x('Sinaoros', 'EPLE', 'ry-wc-city-select'),
		_x('Skouriotissa', 'EPLE', 'ry-wc-city-select'),
		_x('Skylloura', 'EPLE', 'ry-wc-city-select'),
		_x('Spilia', 'EPLE', 'ry-wc-city-select'),
		_x('Strovolos', 'EPLE', 'ry-wc-city-select'),
		_x('Synoikismos Anthoupolis', 'EPLE', 'ry-wc-city-select'),
		_x('Syrianochori', 'EPLE', 'ry-wc-city-select'),
		_x('Temvria', 'EPLE', 'ry-wc-city-select'),
		_x('Trachonas', 'EPLE', 'ry-wc-city-select'),
		_x('Trachoni', 'EPLE', 'ry-wc-city-select'),
		_x('Tsakistra', 'EPLE', 'ry-wc-city-select'),
		_x('Tseri', 'EPLE', 'ry-wc-city-select'),
		_x('Tymvou', 'EPLE', 'ry-wc-city-select'),
		_x('Variseia', 'EPLE', 'ry-wc-city-select'),
		_x('Voni', 'EPLE', 'ry-wc-city-select'),
		_x('Vyzakia', 'EPLE', 'ry-wc-city-select'),
		_x('Xerovounos', 'EPLE', 'ry-wc-city-select'),
		_x('Xyliatos', 'EPLE', 'ry-wc-city-select'),
	],
	'EPLE2' => [
		_x('Agios Athanasios', 'EPLE2', 'ry-wc-city-select'),
		_x('Agios Dimitrios', 'EPLE2', 'ry-wc-city-select'),
		_x('Agios Konstantinos', 'EPLE2', 'ry-wc-city-select'),
		_x('Agios Mamas', 'EPLE2', 'ry-wc-city-select'),
		_x('Agios Pavlos', 'EPLE2', 'ry-wc-city-select'),
		_x('Agios Therapon', 'EPLE2', 'ry-wc-city-select'),
		_x('Agios Tomas', 'EPLE2', 'ry-wc-city-select'),
		_x('Agios Tychon', 'EPLE2', 'ry-wc-city-select'),
		_x('Agridia', 'EPLE2', 'ry-wc-city-select'),
		_x('Agros', 'EPLE2', 'ry-wc-city-select'),
		_x('Akapnou', 'EPLE2', 'ry-wc-city-select'),
		_x('Akrotiri', 'EPLE2', 'ry-wc-city-select'),
		_x('Akrounta', 'EPLE2', 'ry-wc-city-select'),
		_x('Alassa', 'EPLE2', 'ry-wc-city-select'),
		_x('Alektora', 'EPLE2', 'ry-wc-city-select'),
		_x('Amiantos', 'EPLE2', 'ry-wc-city-select'),
		_x('Anogyra', 'EPLE2', 'ry-wc-city-select'),
		_x('Apesia', 'EPLE2', 'ry-wc-city-select'),
		_x('Apsiou', 'EPLE2', 'ry-wc-city-select'),
		_x('Arakapas', 'EPLE2', 'ry-wc-city-select'),
		_x('Armenochori', 'EPLE2', 'ry-wc-city-select'),
		_x('Arsos', 'EPLE2', 'ry-wc-city-select'),
		_x('Asgata', 'EPLE2', 'ry-wc-city-select'),
		_x('Avdimou', 'EPLE2', 'ry-wc-city-select'),
		_x('Chandria', 'EPLE2', 'ry-wc-city-select'),
		_x('Dierona', 'EPLE2', 'ry-wc-city-select'),
		_x('Dora', 'EPLE2', 'ry-wc-city-select'),
		_x('Doros', 'EPLE2', 'ry-wc-city-select'),
		_x('Dymes', 'EPLE2', 'ry-wc-city-select'),
		_x('Episkopi', 'EPLE2', 'ry-wc-city-select'),
		_x('Eptagoneia', 'EPLE2', 'ry-wc-city-select'),
		_x('Erimi', 'EPLE2', 'ry-wc-city-select'),
		_x('Fasoula', 'EPLE2', 'ry-wc-city-select'),
		_x('Foini', 'EPLE2', 'ry-wc-city-select'),
		_x('Foinikaria', 'EPLE2', 'ry-wc-city-select'),
		_x('Gerasa', 'EPLE2', 'ry-wc-city-select'),
		_x('Germasogeia', 'EPLE2', 'ry-wc-city-select'),
		_x('Gerovasa', 'EPLE2', 'ry-wc-city-select'),
		_x('Kaminaria', 'EPLE2', 'ry-wc-city-select'),
		_x('Kantou', 'EPLE2', 'ry-wc-city-select'),
		_x('Kapileio', 'EPLE2', 'ry-wc-city-select'),
		_x('Kato Kivides', 'EPLE2', 'ry-wc-city-select'),
		_x('Kato Mylos', 'EPLE2', 'ry-wc-city-select'),
		_x('Kato Platres', 'EPLE2', 'ry-wc-city-select'),
		_x('Kato Polemidia', 'EPLE2', 'ry-wc-city-select'),
		_x('Kellaki', 'EPLE2', 'ry-wc-city-select'),
		_x('Kissousa', 'EPLE2', 'ry-wc-city-select'),
		_x('Klonari', 'EPLE2', 'ry-wc-city-select'),
		_x('Koilani', 'EPLE2', 'ry-wc-city-select'),
		_x('Kolossi', 'EPLE2', 'ry-wc-city-select'),
		_x('Korfi', 'EPLE2', 'ry-wc-city-select'),
		_x('Kouka', 'EPLE2', 'ry-wc-city-select'),
		_x('Kyperounta', 'EPLE2', 'ry-wc-city-select'),
		_x('Laneia', 'EPLE2', 'ry-wc-city-select'),
		_x('Lemithou', 'EPLE2', 'ry-wc-city-select'),
		_x('Limnatis', 'EPLE2', 'ry-wc-city-select'),
		_x('Lofou', 'EPLE2', 'ry-wc-city-select'),
		_x('Louvaras', 'EPLE2', 'ry-wc-city-select'),
		_x('Malia', 'EPLE2', 'ry-wc-city-select'),
		_x('Mandria', 'EPLE2', 'ry-wc-city-select'),
		_x('Mathikoloni', 'EPLE2', 'ry-wc-city-select'),
		_x('Mesa Geitonia', 'EPLE2', 'ry-wc-city-select'),
		_x('Monagri', 'EPLE2', 'ry-wc-city-select'),
		_x('Monagroulli', 'EPLE2', 'ry-wc-city-select'),
		_x('Moniatis', 'EPLE2', 'ry-wc-city-select'),
		_x('Mouttagiaka', 'EPLE2', 'ry-wc-city-select'),
		_x('Omodos', 'EPLE2', 'ry-wc-city-select'),
		_x('Pachna', 'EPLE2', 'ry-wc-city-select'),
		_x('Palaiomylos', 'EPLE2', 'ry-wc-city-select'),
		_x('Palodeia', 'EPLE2', 'ry-wc-city-select'),
		_x('Pano Kivides', 'EPLE2', 'ry-wc-city-select'),
		_x('Pano Platres', 'EPLE2', 'ry-wc-city-select'),
		_x('Pano Polemidia', 'EPLE2', 'ry-wc-city-select'),
		_x('Paramali', 'EPLE2', 'ry-wc-city-select'),
		_x('Paramytha', 'EPLE2', 'ry-wc-city-select'),
		_x('Parekklisia', 'EPLE2', 'ry-wc-city-select'),
		_x('Pelendri', 'EPLE2', 'ry-wc-city-select'),
		_x('Pentakomo', 'EPLE2', 'ry-wc-city-select'),
		_x('Pera Pedi', 'EPLE2', 'ry-wc-city-select'),
		_x('Pissouri', 'EPLE2', 'ry-wc-city-select'),
		_x('Platanisteia', 'EPLE2', 'ry-wc-city-select'),
		_x('Potamiou', 'EPLE2', 'ry-wc-city-select'),
		_x('Potamitissa', 'EPLE2', 'ry-wc-city-select'),
		_x('Prodromos', 'EPLE2', 'ry-wc-city-select'),
		_x('Sanida', 'EPLE2', 'ry-wc-city-select'),
		_x('Silikou', 'EPLE2', 'ry-wc-city-select'),
		_x('Sotira', 'EPLE2', 'ry-wc-city-select'),
		_x('Souni-Zanakia', 'EPLE2', 'ry-wc-city-select'),
		_x('Spitali', 'EPLE2', 'ry-wc-city-select'),
		_x('Sykopetra', 'EPLE2', 'ry-wc-city-select'),
		_x('Treis Elies', 'EPLE2', 'ry-wc-city-select'),
		_x('Trimiklini', 'EPLE2', 'ry-wc-city-select'),
		_x('Tserkezoi', 'EPLE2', 'ry-wc-city-select'),
		_x('Vasa', 'EPLE2', 'ry-wc-city-select'),
		_x('Vasa', 'EPLE2', 'ry-wc-city-select'),
		_x('Vikla', 'EPLE2', 'ry-wc-city-select'),
		_x('Vouni', 'EPLE2', 'ry-wc-city-select'),
		_x('Ypsonas', 'EPLE2', 'ry-wc-city-select'),
		_x('Zoopigi', 'EPLE2', 'ry-wc-city-select'),
	],
	'EPPA' => [
		_x('Acheleia', 'EPPA', 'ry-wc-city-select'),
		_x('Agia Marinouda', 'EPPA', 'ry-wc-city-select'),
		_x('Agios Dimitrianos', 'EPPA', 'ry-wc-city-select'),
		_x('Agios Isidoros', 'EPPA', 'ry-wc-city-select'),
		_x('Akoursos', 'EPPA', 'ry-wc-city-select'),
		_x('Amargeti', 'EPPA', 'ry-wc-city-select'),
		_x('Anadiou', 'EPPA', 'ry-wc-city-select'),
		_x('Anarita', 'EPPA', 'ry-wc-city-select'),
		_x('Androlikou', 'EPPA', 'ry-wc-city-select'),
		_x('Argaka', 'EPPA', 'ry-wc-city-select'),
		_x('Arminou', 'EPPA', 'ry-wc-city-select'),
		_x('Armou', 'EPPA', 'ry-wc-city-select'),
		_x('Asprogia', 'EPPA', 'ry-wc-city-select'),
		_x('Axylou', 'EPPA', 'ry-wc-city-select'),
		_x('Chlorakas', 'EPPA', 'ry-wc-city-select'),
		_x('Choletria', 'EPPA', 'ry-wc-city-select'),
		_x('Choli', 'EPPA', 'ry-wc-city-select'),
		_x('Choulou', 'EPPA', 'ry-wc-city-select'),
		_x('Chrysochou', 'EPPA', 'ry-wc-city-select'),
		_x('Drouseia', 'EPPA', 'ry-wc-city-select'),
		_x('Drymou', 'EPPA', 'ry-wc-city-select'),
		_x('Eledio', 'EPPA', 'ry-wc-city-select'),
		_x('Empa', 'EPPA', 'ry-wc-city-select'),
		_x('Episkopi', 'EPPA', 'ry-wc-city-select'),
		_x('Evretou', 'EPPA', 'ry-wc-city-select'),
		_x('Faleia', 'EPPA', 'ry-wc-city-select'),
		_x('Fasli', 'EPPA', 'ry-wc-city-select'),
		_x('Fasoula', 'EPPA', 'ry-wc-city-select'),
		_x('Filousa', 'EPPA', 'ry-wc-city-select'),
		_x('Filousa', 'EPPA', 'ry-wc-city-select'),
		_x('Foinikas', 'EPPA', 'ry-wc-city-select'),
		_x('Fyti', 'EPPA', 'ry-wc-city-select'),
		_x('Galataria', 'EPPA', 'ry-wc-city-select'),
		_x('Geroskipou Municipality', 'EPPA', 'ry-wc-city-select'),
		_x('Gialia', 'EPPA', 'ry-wc-city-select'),
		_x('Giolou', 'EPPA', 'ry-wc-city-select'),
		_x('Goudi', 'EPPA', 'ry-wc-city-select'),
		_x('Ineia', 'EPPA', 'ry-wc-city-select'),
		_x('Kallepeia', 'EPPA', 'ry-wc-city-select'),
		_x('Kannaviou-Melamiou', 'EPPA', 'ry-wc-city-select'),
		_x('Karamoullides', 'EPPA', 'ry-wc-city-select'),
		_x('Kathikas', 'EPPA', 'ry-wc-city-select'),
		_x('Kato Akourdaleia', 'EPPA', 'ry-wc-city-select'),
		_x('Kato Arodes', 'EPPA', 'ry-wc-city-select'),
		_x('Kedares', 'EPPA', 'ry-wc-city-select'),
		_x('Kelokedara', 'EPPA', 'ry-wc-city-select'),
		_x('Kidasi', 'EPPA', 'ry-wc-city-select'),
		_x('Kios', 'EPPA', 'ry-wc-city-select'),
		_x('Kissonerga', 'EPPA', 'ry-wc-city-select'),
		_x('Koili', 'EPPA', 'ry-wc-city-select'),
		_x('Koilineia', 'EPPA', 'ry-wc-city-select'),
		_x('Konia', 'EPPA', 'ry-wc-city-select'),
		_x('Kouklia', 'EPPA', 'ry-wc-city-select'),
		_x('Kourdaka', 'EPPA', 'ry-wc-city-select'),
		_x('Kritou Marottou', 'EPPA', 'ry-wc-city-select'),
		_x('Kritou Tera', 'EPPA', 'ry-wc-city-select'),
		_x('Kynousa', 'EPPA', 'ry-wc-city-select'),
		_x('Lapithiou', 'EPPA', 'ry-wc-city-select'),
		_x('Lasa', 'EPPA', 'ry-wc-city-select'),
		_x('Lemona', 'EPPA', 'ry-wc-city-select'),
		_x('Lempa', 'EPPA', 'ry-wc-city-select'),
		_x('Letymvou', 'EPPA', 'ry-wc-city-select'),
		_x('Livadi', 'EPPA', 'ry-wc-city-select'),
		_x('Loukrounou', 'EPPA', 'ry-wc-city-select'),
		_x('Lysos', 'EPPA', 'ry-wc-city-select'),
		_x('Makounta', 'EPPA', 'ry-wc-city-select'),
		_x('Mamonia', 'EPPA', 'ry-wc-city-select'),
		_x('Mamountali', 'EPPA', 'ry-wc-city-select'),
		_x('Mandria', 'EPPA', 'ry-wc-city-select'),
		_x('Marathounta', 'EPPA', 'ry-wc-city-select'),
		_x('Maronas', 'EPPA', 'ry-wc-city-select'),
		_x('Meladeia', 'EPPA', 'ry-wc-city-select'),
		_x('Melandra', 'EPPA', 'ry-wc-city-select'),
		_x('Mesa Chorio', 'EPPA', 'ry-wc-city-select'),
		_x('Mesana', 'EPPA', 'ry-wc-city-select'),
		_x('Mesogi', 'EPPA', 'ry-wc-city-select'),
		_x('Miliou', 'EPPA', 'ry-wc-city-select'),
		_x('Mousere', 'EPPA', 'ry-wc-city-select'),
		_x('Nata', 'EPPA', 'ry-wc-city-select'),
		_x('Nea Dimmata', 'EPPA', 'ry-wc-city-select'),
		_x('Neo Chorio', 'EPPA', 'ry-wc-city-select'),
		_x('Nikokleia', 'EPPA', 'ry-wc-city-select'),
		_x('Pafos', 'EPPA', 'ry-wc-city-select'),
		_x('Pano Akourdaleia', 'EPPA', 'ry-wc-city-select'),
		_x('Pano Archimandrita', 'EPPA', 'ry-wc-city-select'),
		_x('Pano Arodes', 'EPPA', 'ry-wc-city-select'),
		_x('Pano Panagia', 'EPPA', 'ry-wc-city-select'),
		_x('Pegeia', 'EPPA', 'ry-wc-city-select'),
		_x('Pelathousa', 'EPPA', 'ry-wc-city-select'),
		_x('Pentalia', 'EPPA', 'ry-wc-city-select'),
		_x('Pitargou', 'EPPA', 'ry-wc-city-select'),
		_x('Polemi', 'EPPA', 'ry-wc-city-select'),
		_x('Polis', 'EPPA', 'ry-wc-city-select'),
		_x('Pomos', 'EPPA', 'ry-wc-city-select'),
		_x('Praitori', 'EPPA', 'ry-wc-city-select'),
		_x('Psathi', 'EPPA', 'ry-wc-city-select'),
		_x('Salamiou', 'EPPA', 'ry-wc-city-select'),
		_x('Sarama', 'EPPA', 'ry-wc-city-select'),
		_x('Simou', 'EPPA', 'ry-wc-city-select'),
		_x('Skoulli', 'EPPA', 'ry-wc-city-select'),
		_x('Souskiou', 'EPPA', 'ry-wc-city-select'),
		_x('Statos-Agios Fotios', 'EPPA', 'ry-wc-city-select'),
		_x('Stavrokonnou', 'EPPA', 'ry-wc-city-select'),
		_x('Steni', 'EPPA', 'ry-wc-city-select'),
		_x('Stroumpi', 'EPPA', 'ry-wc-city-select'),
		_x('Tala', 'EPPA', 'ry-wc-city-select'),
		_x('Tera', 'EPPA', 'ry-wc-city-select'),
		_x('Theletra', 'EPPA', 'ry-wc-city-select'),
		_x('Thrinia', 'EPPA', 'ry-wc-city-select'),
		_x('Timi', 'EPPA', 'ry-wc-city-select'),
		_x('Trachypedoula', 'EPPA', 'ry-wc-city-select'),
		_x('Tremithousa', 'EPPA', 'ry-wc-city-select'),
		_x('Trimithousa', 'EPPA', 'ry-wc-city-select'),
		_x('Tsada', 'EPPA', 'ry-wc-city-select'),
		_x('Vretsia', 'EPPA', 'ry-wc-city-select'),
		_x('Zacharia', 'EPPA', 'ry-wc-city-select'),
	],
	]
];