<?php
/**
 * Federal Republic of Germany places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'DE' => [
	'DUDI' => [
		_x('Kreis Kleve', 'DUDI', 'ry-wc-city-select'),
		_x('Kreis Mettmann', 'DUDI', 'ry-wc-city-select'),
		_x('Kreis Viersen', 'DUDI', 'ry-wc-city-select'),
		_x('Kreis Wesel', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Duesseldorf', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Duisburg', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Essen', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Krefeld', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Moenchengladbach', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Muelheim an der Ruhr', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Oberhausen', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Remscheid', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Solingen', 'DUDI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Wuppertal', 'DUDI', 'ry-wc-city-select'),
		_x('Rhein-Kreis Neuss', 'DUDI', 'ry-wc-city-select'),
	],
	'FRRE' => [
		_x('Landkreis Breisgau-Hochschwarzwald', 'FRRE', 'ry-wc-city-select'),
		_x('Landkreis Emmendingen', 'FRRE', 'ry-wc-city-select'),
		_x('Landkreis Konstanz', 'FRRE', 'ry-wc-city-select'),
		_x('Landkreis Loerrach', 'FRRE', 'ry-wc-city-select'),
		_x('Landkreis Rottweil', 'FRRE', 'ry-wc-city-select'),
		_x('Landkreis Tuttlingen', 'FRRE', 'ry-wc-city-select'),
		_x('Landkreis Waldshut', 'FRRE', 'ry-wc-city-select'),
		_x('Ortenaukreis', 'FRRE', 'ry-wc-city-select'),
		_x('Schwarzwald-Baar-Kreis', 'FRRE', 'ry-wc-city-select'),
		_x('Stadtkreis Freiburg im Breisgau', 'FRRE', 'ry-wc-city-select'),
	],
	'KARE' => [
		_x('Enzkreis', 'KARE', 'ry-wc-city-select'),
		_x('Landkreis Calw', 'KARE', 'ry-wc-city-select'),
		_x('Landkreis Freudenstadt', 'KARE', 'ry-wc-city-select'),
		_x('Landkreis Karlsruhe', 'KARE', 'ry-wc-city-select'),
		_x('Landkreis Rastatt', 'KARE', 'ry-wc-city-select'),
		_x('Neckar-Odenwald-Kreis', 'KARE', 'ry-wc-city-select'),
		_x('Rhein-Neckar-Kreis', 'KARE', 'ry-wc-city-select'),
		_x('Stadtkreis Baden-Baden', 'KARE', 'ry-wc-city-select'),
		_x('Stadtkreis Heidelberg', 'KARE', 'ry-wc-city-select'),
		_x('Stadtkreis Karlsruhe', 'KARE', 'ry-wc-city-select'),
		_x('Stadtkreis Mannheim', 'KARE', 'ry-wc-city-select'),
		_x('Stadtkreis Pforzheim', 'KARE', 'ry-wc-city-select'),
	],
	'LOBA' => [
		_x('Kreisfreie Stadt Landshut', 'LOBA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Passau', 'LOBA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Straubing', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Deggendorf', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Dingolfing-Landau', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Freyung-Grafenau', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Kelheim', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Landshut', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Passau', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Regen', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Rottal-Inn', 'LOBA', 'ry-wc-city-select'),
		_x('Landkreis Straubing-Bogen', 'LOBA', 'ry-wc-city-select'),
	],
	'REAR' => [
		_x('Ennepe-Ruhr-Kreis', 'REAR', 'ry-wc-city-select'),
		_x('Hochsauerlandkreis', 'REAR', 'ry-wc-city-select'),
		_x('Kreis Olpe', 'REAR', 'ry-wc-city-select'),
		_x('Kreis Siegen-Wittgenstein', 'REAR', 'ry-wc-city-select'),
		_x('Kreis Soest', 'REAR', 'ry-wc-city-select'),
		_x('Kreis Unna', 'REAR', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Bochum', 'REAR', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Dortmund', 'REAR', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Hagen', 'REAR', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Hamm', 'REAR', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Herne', 'REAR', 'ry-wc-city-select'),
		_x('Maerkischer Kreis', 'REAR', 'ry-wc-city-select'),
	],
	'REDA' => [
		_x('Frankfurt am Main', 'REDA', 'ry-wc-city-select'),
		_x('Hochtaunuskreis', 'REDA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Darmstadt', 'REDA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Offenbach am Main', 'REDA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Wiesbaden', 'REDA', 'ry-wc-city-select'),
		_x('Landkreis Bergstrasse', 'REDA', 'ry-wc-city-select'),
		_x('Landkreis Darmstadt-Dieburg', 'REDA', 'ry-wc-city-select'),
		_x('Landkreis Gross-Gerau', 'REDA', 'ry-wc-city-select'),
		_x('Landkreis Offenbach', 'REDA', 'ry-wc-city-select'),
		_x('Main-Kinzig-Kreis', 'REDA', 'ry-wc-city-select'),
		_x('Main-Taunus-Kreis', 'REDA', 'ry-wc-city-select'),
		_x('Odenwaldkreis', 'REDA', 'ry-wc-city-select'),
		_x('Rheingau-Taunus-Kreis', 'REDA', 'ry-wc-city-select'),
		_x('Wetteraukreis', 'REDA', 'ry-wc-city-select'),
	],
	'REDE' => [
		_x('Kreis Guetersloh', 'REDE', 'ry-wc-city-select'),
		_x('Kreis Herford', 'REDE', 'ry-wc-city-select'),
		_x('Kreis Hoexter', 'REDE', 'ry-wc-city-select'),
		_x('Kreis Lippe', 'REDE', 'ry-wc-city-select'),
		_x('Kreis Minden-Luebbecke', 'REDE', 'ry-wc-city-select'),
		_x('Kreis Paderborn', 'REDE', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Bielefeld', 'REDE', 'ry-wc-city-select'),
	],
	'REGI' => [
		_x('Lahn-Dill-Kreis', 'REGI', 'ry-wc-city-select'),
		_x('Landkreis Giessen', 'REGI', 'ry-wc-city-select'),
		_x('Landkreis Limburg-Weilburg', 'REGI', 'ry-wc-city-select'),
		_x('Landkreis Marburg-Biedenkopf', 'REGI', 'ry-wc-city-select'),
		_x('Vogelsbergkreis', 'REGI', 'ry-wc-city-select'),
	],
	'REKA' => [
		_x('Kreisfreie Stadt Kassel', 'REKA', 'ry-wc-city-select'),
		_x('Landkreis Fulda', 'REKA', 'ry-wc-city-select'),
		_x('Landkreis Hersfeld-Rotenburg', 'REKA', 'ry-wc-city-select'),
		_x('Landkreis Kassel', 'REKA', 'ry-wc-city-select'),
		_x('Landkreis Waldeck-Frankenberg', 'REKA', 'ry-wc-city-select'),
		_x('Schwalm-Eder-Kreis', 'REKA', 'ry-wc-city-select'),
		_x('Werra-Meissner-Kreis', 'REKA', 'ry-wc-city-select'),
	],
	'REKO' => [
		_x('Kreis Dueren', 'REKO', 'ry-wc-city-select'),
		_x('Kreis Euskirchen', 'REKO', 'ry-wc-city-select'),
		_x('Kreis Heinsberg', 'REKO', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Bonn', 'REKO', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Koeln', 'REKO', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Leverkusen', 'REKO', 'ry-wc-city-select'),
		_x('Oberbergischer Kreis', 'REKO', 'ry-wc-city-select'),
		_x('Rhein-Erft-Kreis', 'REKO', 'ry-wc-city-select'),
		_x('Rhein-Sieg-Kreis', 'REKO', 'ry-wc-city-select'),
		_x('Rheinisch-Bergischer Kreis', 'REKO', 'ry-wc-city-select'),
		_x('Staedteregion Aachen', 'REKO', 'ry-wc-city-select'),
	],
	'REMI' => [
		_x('Kreisfreie Stadt Ansbach', 'REMI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Erlangen', 'REMI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Fuerth', 'REMI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Nuernberg', 'REMI', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Schwabach', 'REMI', 'ry-wc-city-select'),
		_x('Landkreis Ansbach', 'REMI', 'ry-wc-city-select'),
		_x('Landkreis Erlangen-Hoechstadt', 'REMI', 'ry-wc-city-select'),
		_x('Landkreis Fuerth', 'REMI', 'ry-wc-city-select'),
		_x('Landkreis Neustadt an der Aisch-Bad Wind', 'REMI', 'ry-wc-city-select'),
		_x('Landkreis Roth', 'REMI', 'ry-wc-city-select'),
		_x('Landkreis Weissenburg-Gunzenhausen', 'REMI', 'ry-wc-city-select'),
		_x('Nuernberger Land', 'REMI', 'ry-wc-city-select'),
	],
	'REMU' => [
		_x('Kreis Borken', 'REMU', 'ry-wc-city-select'),
		_x('Kreis Coesfeld', 'REMU', 'ry-wc-city-select'),
		_x('Kreis Recklinghausen', 'REMU', 'ry-wc-city-select'),
		_x('Kreis Steinfurt', 'REMU', 'ry-wc-city-select'),
		_x('Kreis Warendorf', 'REMU', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Bottrop', 'REMU', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Gelsenkirchen', 'REMU', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Muenster', 'REMU', 'ry-wc-city-select'),
	],
	'REST' => [
		_x('Hohenlohekreis', 'REST', 'ry-wc-city-select'),
		_x('Landkreis Boeblingen', 'REST', 'ry-wc-city-select'),
		_x('Landkreis Esslingen', 'REST', 'ry-wc-city-select'),
		_x('Landkreis Goeppingen', 'REST', 'ry-wc-city-select'),
		_x('Landkreis Heidenheim', 'REST', 'ry-wc-city-select'),
		_x('Landkreis Heilbronn', 'REST', 'ry-wc-city-select'),
		_x('Landkreis Ludwigsburg', 'REST', 'ry-wc-city-select'),
		_x('Landkreis Schwaebisch Hall', 'REST', 'ry-wc-city-select'),
		_x('Main-Tauber-Kreis', 'REST', 'ry-wc-city-select'),
		_x('Ostalbkreis', 'REST', 'ry-wc-city-select'),
		_x('Rems-Murr-Kreis', 'REST', 'ry-wc-city-select'),
		_x('Stadtkreis Heilbronn', 'REST', 'ry-wc-city-select'),
		_x('Stadtkreis Stuttgart', 'REST', 'ry-wc-city-select'),
	],
	'REUN' => [
		_x('Kreisfreie Stadt Aschaffenburg', 'REUN', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Schweinfurt', 'REUN', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Wuerzburg', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Aschaffenburg', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Bad Kissingen', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Hassberge', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Kitzingen', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Main-Spessart', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Miltenberg', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Rhoen-Grabfeld', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Schweinfurt', 'REUN', 'ry-wc-city-select'),
		_x('Landkreis Wuerzburg', 'REUN', 'ry-wc-city-select'),
	],
	'SW' => [
		_x('Kreisfreie Stadt Augsburg', 'SW', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Kaufbeuren', 'SW', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Kempten', 'SW', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Memmingen', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Aichach-Friedberg', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Augsburg', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Dillingen an der Donau', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Donau-Ries', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Guenzburg', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Lindau', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Neu-Ulm', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Oberallgaeu', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Ostallgaeu', 'SW', 'ry-wc-city-select'),
		_x('Landkreis Unterallgaeu', 'SW', 'ry-wc-city-select'),
	],
	'TURE' => [
		_x('Alb-Donau-Kreis', 'TURE', 'ry-wc-city-select'),
		_x('Bodenseekreis', 'TURE', 'ry-wc-city-select'),
		_x('Landkreis Biberach', 'TURE', 'ry-wc-city-select'),
		_x('Landkreis Ravensburg', 'TURE', 'ry-wc-city-select'),
		_x('Landkreis Reutlingen', 'TURE', 'ry-wc-city-select'),
		_x('Landkreis Sigmaringen', 'TURE', 'ry-wc-city-select'),
		_x('Landkreis Tuebingen', 'TURE', 'ry-wc-city-select'),
		_x('Stadtkreis Ulm', 'TURE', 'ry-wc-city-select'),
		_x('Zollernalbkreis', 'TURE', 'ry-wc-city-select'),
	],
	'UPBA' => [
		_x('Berchtesgadener Land', 'UPBA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Ingolstadt', 'UPBA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Muenchen', 'UPBA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Rosenheim', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Altoetting', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Bad Toelz-Wolfratshausen', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Dachau', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Ebersberg', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Eichstaett', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Erding', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Freising', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Fuerstenfeldbruck', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Garmisch-Partenkirchen', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Landsberg am Lech', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Miesbach', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Muehldorf am Inn', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Muenchen', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Neuburg-Schrobenhausen', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Pfaffenhofen an der Ilm', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Rosenheim', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Starnberg', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Traunstein', 'UPBA', 'ry-wc-city-select'),
		_x('Landkreis Weilheim-Schongau', 'UPBA', 'ry-wc-city-select'),
	],
	'UPFR' => [
		_x('Kreisfreie Stadt Bamberg', 'UPFR', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Bayreuth', 'UPFR', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Coburg', 'UPFR', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Hof', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Bamberg', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Bayreuth', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Coburg', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Forchheim', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Hof', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Kronach', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Kulmbach', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Lichtenfels', 'UPFR', 'ry-wc-city-select'),
		_x('Landkreis Wunsiedel im Fichtelgebirge', 'UPFR', 'ry-wc-city-select'),
	],
	'UPPA' => [
		_x('Kreisfreie Stadt Amberg', 'UPPA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Regensburg', 'UPPA', 'ry-wc-city-select'),
		_x('Kreisfreie Stadt Weiden in der Oberpfalz', 'UPPA', 'ry-wc-city-select'),
		_x('Landkreis Amberg-Sulzbach', 'UPPA', 'ry-wc-city-select'),
		_x('Landkreis Cham', 'UPPA', 'ry-wc-city-select'),
		_x('Landkreis Neumarkt in der Oberpfalz', 'UPPA', 'ry-wc-city-select'),
		_x('Landkreis Neustadt an der Waldnaab', 'UPPA', 'ry-wc-city-select'),
		_x('Landkreis Regensburg', 'UPPA', 'ry-wc-city-select'),
		_x('Landkreis Schwandorf', 'UPPA', 'ry-wc-city-select'),
		_x('Landkreis Tirschenreuth', 'UPPA', 'ry-wc-city-select'),
	],
	]
];