<?php
/**
 * Kingdom of Denmark places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'DK' => [
	'NODERE' => [
		_x('Alborg Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Bronderslev Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Frederikshavn Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Hjorring Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Jammerbugt Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Laeso Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Mariagerfjord Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Morso Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Rebild Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Thisted Kommune', 'NODERE', 'ry-wc-city-select'),
		_x('Vesthimmerland Kommune', 'NODERE', 'ry-wc-city-select'),
	],
	'REHO' => [
		_x('Albertslund Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Allerod Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Ballerup Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Bornholm Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Brondby Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Christianso', 'REHO', 'ry-wc-city-select'),
		_x('Dragor Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Egedal Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Fredensborg Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Frederiksberg Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Frederikssund Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Fureso Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Gentofte Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Gladsaxe Municipality', 'REHO', 'ry-wc-city-select'),
		_x('Glostrup Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Gribskov Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Halsnaes Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Helsingor Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Herlev Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Hillerod Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Hoje-Taastrup Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Horsholm Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Hvidovre Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Ishoj Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Kobenhavn', 'REHO', 'ry-wc-city-select'),
		_x('Lyngby-Tarbaek Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Rodovre Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Rudersdal Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Tarnby Kommune', 'REHO', 'ry-wc-city-select'),
		_x('Vallensbaek Kommune', 'REHO', 'ry-wc-city-select'),
	],
	'REMI' => [
		_x('Arhus Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Favrskov Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Hedensted Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Herning Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Holstebro Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Horsens Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Ikast-Brande Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Lemvig Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Norddjurs Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Odder Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Randers Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Ringkobing-Skjern Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Samso Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Silkeborg Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Skanderborg Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Skive Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Struer Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Syddjurs Kommune', 'REMI', 'ry-wc-city-select'),
		_x('Viborg Kommune', 'REMI', 'ry-wc-city-select'),
	],
	'RESJ' => [
		_x('Faxe Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Greve Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Guldborgsund Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Holbaek Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Kalundborg Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Koge Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Lejre Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Lolland Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Naestved Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Odsherred Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Ringsted Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Roskilde Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Slagelse Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Solrod Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Soro Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Stevns Kommune', 'RESJ', 'ry-wc-city-select'),
		_x('Vordingborg Kommune', 'RESJ', 'ry-wc-city-select'),
	],
	'RESY' => [
		_x('AEro Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Aabenraa Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Assens Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Billund Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Esbjerg Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Faaborg-Midtfyn Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Fano Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Fredericia Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Haderslev Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Kerteminde Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Kolding Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Langeland Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Middelfart Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Nordfyns Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Nyborg Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Odense Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Sonderborg Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Svendborg Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Tonder Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Varde Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Vejen Kommune', 'RESY', 'ry-wc-city-select'),
		_x('Vejle Kommune', 'RESY', 'ry-wc-city-select'),
	],
	]
];