<?php
/**
 * Republic of Ecuador places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'EC' => [
	'ALBAMO(J' => [
		_x('Alfredo Baquerizo Moreno (Jujan)', 'ALBAMO(J', 'ry-wc-city-select'),
	],
	'AR' => [
		_x('Arajuno', 'AR', 'ry-wc-city-select'),
		_x('Curaray', 'AR', 'ry-wc-city-select'),
	],
	'AT' => [
		_x('Atacames', 'AT', 'ry-wc-city-select'),
		_x('La Union', 'AT', 'ry-wc-city-select'),
		_x('Sua (Cab. En La Bocana)', 'AT', 'ry-wc-city-select'),
		_x('Tonchigue', 'AT', 'ry-wc-city-select'),
		_x('Tonsupa', 'AT', 'ry-wc-city-select'),
	],
	'AT2' => [
		_x('Ayapamba', 'AT2', 'ry-wc-city-select'),
		_x('Cordoncillo', 'AT2', 'ry-wc-city-select'),
		_x('Milagro', 'AT2', 'ry-wc-city-select'),
		_x('Paccha', 'AT2', 'ry-wc-city-select'),
		_x('San Jose', 'AT2', 'ry-wc-city-select'),
		_x('San Juan De Cerro Azul', 'AT2', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Balao', 'BA', 'ry-wc-city-select'),
	],
	'BA2' => [
		_x('Balsas', 'BA2', 'ry-wc-city-select'),
		_x('Bellamaria', 'BA2', 'ry-wc-city-select'),
	],
	'CAPOEN' => [
		_x('Camilo Ponce Enriquez', 'CAPOEN', 'ry-wc-city-select'),
		_x('El Carmen De Pijili', 'CAPOEN', 'ry-wc-city-select'),
	],
	'CAAG' => [
		_x('Capitan Augusto Rivadeneyra', 'CAAG', 'ry-wc-city-select'),
		_x('Cononaco', 'CAAG', 'ry-wc-city-select'),
		_x('Nuevo Rocafuerte', 'CAAG', 'ry-wc-city-select'),
		_x('Santa Maria De Huiririma', 'CAAG', 'ry-wc-city-select'),
		_x('Tiputini', 'CAAG', 'ry-wc-city-select'),
		_x('Yasuni', 'CAAG', 'ry-wc-city-select'),
	],
	'CAAL' => [
		_x('Achupallas', 'CAAL', 'ry-wc-city-select'),
		_x('Alausi', 'CAAL', 'ry-wc-city-select'),
		_x('Guasuntos', 'CAAL', 'ry-wc-city-select'),
		_x('Huigra', 'CAAL', 'ry-wc-city-select'),
		_x('Multitud', 'CAAL', 'ry-wc-city-select'),
		_x('Pistishi (Nariz Del Diablo)', 'CAAL', 'ry-wc-city-select'),
		_x('Pumallacta', 'CAAL', 'ry-wc-city-select'),
		_x('Sevilla', 'CAAL', 'ry-wc-city-select'),
		_x('Sibambe', 'CAAL', 'ry-wc-city-select'),
		_x('Tixan', 'CAAL', 'ry-wc-city-select'),
	],
	'CAAM' => [
		_x('Ambatillo', 'CAAM', 'ry-wc-city-select'),
		_x('Ambato', 'CAAM', 'ry-wc-city-select'),
		_x('Atahualpa (Chisalata)', 'CAAM', 'ry-wc-city-select'),
		_x('Augusto N. Martinez (Mundugleo)', 'CAAM', 'ry-wc-city-select'),
		_x('Constantino Fernandez (Cab. En Cullitahu', 'CAAM', 'ry-wc-city-select'),
		_x('Cunchibamba', 'CAAM', 'ry-wc-city-select'),
		_x('Huachi Grande', 'CAAM', 'ry-wc-city-select'),
		_x('Izamba', 'CAAM', 'ry-wc-city-select'),
		_x('Juan Benigno Vela', 'CAAM', 'ry-wc-city-select'),
		_x('Montalvo', 'CAAM', 'ry-wc-city-select'),
		_x('Pasa', 'CAAM', 'ry-wc-city-select'),
		_x('Picaigua', 'CAAM', 'ry-wc-city-select'),
		_x('Pilaguin (Pilahuin)', 'CAAM', 'ry-wc-city-select'),
		_x('Quisapincha (Quizapincha)', 'CAAM', 'ry-wc-city-select'),
		_x('San Bartolome De Pinllog', 'CAAM', 'ry-wc-city-select'),
		_x('San Fernando (Pasa San Fernando)', 'CAAM', 'ry-wc-city-select'),
		_x('Santa Rosa', 'CAAM', 'ry-wc-city-select'),
		_x('Totoras', 'CAAM', 'ry-wc-city-select'),
		_x('Unamuncho', 'CAAM', 'ry-wc-city-select'),
	],
	'CAANAN' => [
		_x('Atuntaqui', 'CAANAN', 'ry-wc-city-select'),
		_x('Imbaya (San Luis De Cobuendo)', 'CAANAN', 'ry-wc-city-select'),
		_x('San Fco. De Natabuela', 'CAANAN', 'ry-wc-city-select'),
		_x('San Jose De Chaltura', 'CAANAN', 'ry-wc-city-select'),
		_x('San Roque', 'CAANAN', 'ry-wc-city-select'),
	],
	'CAAR' => [
		_x('Archidona', 'CAAR', 'ry-wc-city-select'),
		_x('Cotundo', 'CAAR', 'ry-wc-city-select'),
		_x('Hatun Sumaku', 'CAAR', 'ry-wc-city-select'),
		_x('San Pablo De Ushpayacu', 'CAAR', 'ry-wc-city-select'),
	],
	'CAAR2' => [
		_x('Arenillas', 'CAAR2', 'ry-wc-city-select'),
		_x('Carcabon', 'CAAR2', 'ry-wc-city-select'),
		_x('Chacras', 'CAAR2', 'ry-wc-city-select'),
		_x('Palmales', 'CAAR2', 'ry-wc-city-select'),
	],
	'CAAZ' => [
		_x('Azogues', 'CAAZ', 'ry-wc-city-select'),
		_x('Cojitambo', 'CAAZ', 'ry-wc-city-select'),
		_x('Guapan', 'CAAZ', 'ry-wc-city-select'),
		_x('Javier Loyola (Chuquipata)', 'CAAZ', 'ry-wc-city-select'),
		_x('Luis Cordero', 'CAAZ', 'ry-wc-city-select'),
		_x('Pindilig', 'CAAZ', 'ry-wc-city-select'),
		_x('Rivera', 'CAAZ', 'ry-wc-city-select'),
		_x('San Miguel', 'CAAZ', 'ry-wc-city-select'),
		_x('Taday', 'CAAZ', 'ry-wc-city-select'),
	],
	'CABA' => [
		_x('Baba', 'CABA', 'ry-wc-city-select'),
		_x('Guare', 'CABA', 'ry-wc-city-select'),
		_x('Isla De Bejucal', 'CABA', 'ry-wc-city-select'),
	],
	'CABA2' => [
		_x('Babahoyo', 'CABA2', 'ry-wc-city-select'),
		_x('Caracol', 'CABA2', 'ry-wc-city-select'),
		_x('Febres Cordero (Las Juntas)', 'CABA2', 'ry-wc-city-select'),
		_x('La Union', 'CABA2', 'ry-wc-city-select'),
		_x('Pimocha', 'CABA2', 'ry-wc-city-select'),
	],
	'CABA3' => [
		_x('Balzar', 'CABA3', 'ry-wc-city-select'),
	],
	'CABA4' => [
		_x('Banos De Agua Santa', 'CABA4', 'ry-wc-city-select'),
		_x('Lligua', 'CABA4', 'ry-wc-city-select'),
		_x('Rio Negro', 'CABA4', 'ry-wc-city-select'),
		_x('Rio Verde', 'CABA4', 'ry-wc-city-select'),
		_x('Ulba', 'CABA4', 'ry-wc-city-select'),
	],
	'CABI' => [
		_x('Biblian', 'CABI', 'ry-wc-city-select'),
		_x('Jerusalen', 'CABI', 'ry-wc-city-select'),
		_x('Nazon (Cab. En Pampa De Dominguez)', 'CABI', 'ry-wc-city-select'),
		_x('San Francisco De Sageo', 'CABI', 'ry-wc-city-select'),
		_x('Turupamba', 'CABI', 'ry-wc-city-select'),
	],
	'CABO' => [
		_x('Calceta', 'CABO', 'ry-wc-city-select'),
		_x('Membrillo', 'CABO', 'ry-wc-city-select'),
		_x('Quiroga', 'CABO', 'ry-wc-city-select'),
	],
	'CABU' => [
		_x('Patricia Pilar', 'CABU', 'ry-wc-city-select'),
		_x('San Jacinto De Buena Fe', 'CABU', 'ry-wc-city-select'),
	],
	'CACA' => [
		_x('Caluma', 'CACA', 'ry-wc-city-select'),
	],
	'CACA2' => [
		_x('Cariamanga', 'CACA2', 'ry-wc-city-select'),
		_x('Colaisaca', 'CACA2', 'ry-wc-city-select'),
		_x('El Lucero', 'CACA2', 'ry-wc-city-select'),
		_x('Sanguillin', 'CACA2', 'ry-wc-city-select'),
		_x('Utuana', 'CACA2', 'ry-wc-city-select'),
	],
	'CACA3' => [
		_x('Canar', 'CACA3', 'ry-wc-city-select'),
		_x('Chontamarca', 'CACA3', 'ry-wc-city-select'),
		_x('Chorocopte', 'CACA3', 'ry-wc-city-select'),
		_x('Ducur', 'CACA3', 'ry-wc-city-select'),
		_x('General Morales (Socarte)', 'CACA3', 'ry-wc-city-select'),
		_x('Gualleturo', 'CACA3', 'ry-wc-city-select'),
		_x('Honorato Vasquez (Tambo Viejo)', 'CACA3', 'ry-wc-city-select'),
		_x('Ingapirca', 'CACA3', 'ry-wc-city-select'),
		_x('Juncal', 'CACA3', 'ry-wc-city-select'),
		_x('San Antonio', 'CACA3', 'ry-wc-city-select'),
		_x('Ventura', 'CACA3', 'ry-wc-city-select'),
		_x('Zhud', 'CACA3', 'ry-wc-city-select'),
	],
	'CACA4' => [
		_x('Catamayo (La Toma)', 'CACA4', 'ry-wc-city-select'),
		_x('El Tambo', 'CACA4', 'ry-wc-city-select'),
		_x('Guayquichuma', 'CACA4', 'ry-wc-city-select'),
		_x('San Pedro De La Bendita', 'CACA4', 'ry-wc-city-select'),
		_x('Zambi', 'CACA4', 'ry-wc-city-select'),
	],
	'CACA5' => [
		_x('Ascazubi', 'CACA5', 'ry-wc-city-select'),
		_x('Cangahua', 'CACA5', 'ry-wc-city-select'),
		_x('Cayambe', 'CACA5', 'ry-wc-city-select'),
		_x('Olmedo (Pesillo)', 'CACA5', 'ry-wc-city-select'),
		_x('Oton', 'CACA5', 'ry-wc-city-select'),
		_x('San Jose De Ayora', 'CACA5', 'ry-wc-city-select'),
		_x('Santa Rosa De Cuzubamba', 'CACA5', 'ry-wc-city-select'),
	],
	'CACE' => [
		_x('Celica', 'CACE', 'ry-wc-city-select'),
		_x('Cruzpamba (Cab En Carlos Bustamante)', 'CACE', 'ry-wc-city-select'),
		_x('Pozul (San Juan De Pozul)', 'CACE', 'ry-wc-city-select'),
		_x('Sabanilla', 'CACE', 'ry-wc-city-select'),
		_x('Tnte. Maximiliano Rodriguez Loaiza', 'CACE', 'ry-wc-city-select'),
	],
	'CACH' => [
		_x('El Chaco', 'CACH', 'ry-wc-city-select'),
		_x('Gonzalo Diaz De Pineda (El Bombon)', 'CACH', 'ry-wc-city-select'),
		_x('Linares', 'CACH', 'ry-wc-city-select'),
		_x('Oyacachi', 'CACH', 'ry-wc-city-select'),
		_x('Santa Rosa', 'CACH', 'ry-wc-city-select'),
		_x('Sardinas', 'CACH', 'ry-wc-city-select'),
	],
	'CACH2' => [
		_x('Chillanes', 'CACH2', 'ry-wc-city-select'),
		_x('San Jose Del Tambo (Tambopamba)', 'CACH2', 'ry-wc-city-select'),
	],
	'CACH3' => [
		_x('Asuncion (Asancoto)', 'CACH3', 'ry-wc-city-select'),
		_x('Magdalena (Chapacoto)', 'CACH3', 'ry-wc-city-select'),
		_x('San Jose De Chimbo', 'CACH3', 'ry-wc-city-select'),
		_x('San Sebastian', 'CACH3', 'ry-wc-city-select'),
		_x('Telimbela', 'CACH3', 'ry-wc-city-select'),
	],
	'CACH4' => [
		_x('Chito', 'CACH4', 'ry-wc-city-select'),
		_x('El Chorro', 'CACH4', 'ry-wc-city-select'),
		_x('La Chonta', 'CACH4', 'ry-wc-city-select'),
		_x('Pucapamba', 'CACH4', 'ry-wc-city-select'),
		_x('San Andres', 'CACH4', 'ry-wc-city-select'),
		_x('Zumba', 'CACH4', 'ry-wc-city-select'),
	],
	'CACH5' => [
		_x('Boyaca', 'CACH5', 'ry-wc-city-select'),
		_x('Canuto', 'CACH5', 'ry-wc-city-select'),
		_x('Chibunga', 'CACH5', 'ry-wc-city-select'),
		_x('Chone', 'CACH5', 'ry-wc-city-select'),
		_x('Convento', 'CACH5', 'ry-wc-city-select'),
		_x('Eloy Alfaro', 'CACH5', 'ry-wc-city-select'),
		_x('Ricaurte', 'CACH5', 'ry-wc-city-select'),
		_x('San Antonio', 'CACH5', 'ry-wc-city-select'),
	],
	'CACH6' => [
		_x('Capzol', 'CACH6', 'ry-wc-city-select'),
		_x('Chunchi', 'CACH6', 'ry-wc-city-select'),
		_x('Compud', 'CACH6', 'ry-wc-city-select'),
		_x('Gonzol', 'CACH6', 'ry-wc-city-select'),
		_x('Llagos', 'CACH6', 'ry-wc-city-select'),
	],
	'CACO' => [
		_x('Colimes', 'CACO', 'ry-wc-city-select'),
		_x('San Jacinto', 'CACO', 'ry-wc-city-select'),
	],
	'CACO2' => [
		_x('Cani', 'CACO2', 'ry-wc-city-select'),
		_x('Columbe', 'CACO2', 'ry-wc-city-select'),
		_x('Juan De Velasco (Pangor)', 'CACO2', 'ry-wc-city-select'),
		_x('Santiago De Quito (Cab. En San Antonio D', 'CACO2', 'ry-wc-city-select'),
		_x('Villa La Union (Cajabamba)', 'CACO2', 'ry-wc-city-select'),
	],
	'CACO3' => [
		_x('6 De Julio De Cuellaje (Cab. En Cuellaje', 'CACO3', 'ry-wc-city-select'),
		_x('Apuela', 'CACO3', 'ry-wc-city-select'),
		_x('Cotacachi', 'CACO3', 'ry-wc-city-select'),
		_x('Garcia Moreno (Llurimagua)', 'CACO3', 'ry-wc-city-select'),
		_x('Imantag', 'CACO3', 'ry-wc-city-select'),
		_x('Penaherrera', 'CACO3', 'ry-wc-city-select'),
		_x('Plaza Gutierrez (Calvario)', 'CACO3', 'ry-wc-city-select'),
		_x('Quiroga', 'CACO3', 'ry-wc-city-select'),
		_x('Vacas Galindo (El Churo) (Cab. En San Mi', 'CACO3', 'ry-wc-city-select'),
	],
	'CACU' => [
		_x('Banos', 'CACU', 'ry-wc-city-select'),
		_x('Chaucha', 'CACU', 'ry-wc-city-select'),
		_x('Checa (Jidcay)', 'CACU', 'ry-wc-city-select'),
		_x('Chiquintad', 'CACU', 'ry-wc-city-select'),
		_x('Cuenca', 'CACU', 'ry-wc-city-select'),
		_x('Cumbe', 'CACU', 'ry-wc-city-select'),
		_x('Llacao', 'CACU', 'ry-wc-city-select'),
		_x('Molleturo', 'CACU', 'ry-wc-city-select'),
		_x('Nulti', 'CACU', 'ry-wc-city-select'),
		_x('Octavio Cordero Palacios (Sta. Rosa)', 'CACU', 'ry-wc-city-select'),
		_x('Paccha', 'CACU', 'ry-wc-city-select'),
		_x('Quingeo', 'CACU', 'ry-wc-city-select'),
		_x('Ricaurte', 'CACU', 'ry-wc-city-select'),
		_x('San Joaquin', 'CACU', 'ry-wc-city-select'),
		_x('Santa Ana', 'CACU', 'ry-wc-city-select'),
		_x('Sayausi', 'CACU', 'ry-wc-city-select'),
		_x('Sidcay', 'CACU', 'ry-wc-city-select'),
		_x('Sinincay', 'CACU', 'ry-wc-city-select'),
		_x('Tarqui', 'CACU', 'ry-wc-city-select'),
		_x('Turi', 'CACU', 'ry-wc-city-select'),
		_x('Valle', 'CACU', 'ry-wc-city-select'),
		_x('Victoria Del Portete (Irquis)', 'CACU', 'ry-wc-city-select'),
	],
	'CADA' => [
		_x('Daule', 'CADA', 'ry-wc-city-select'),
		_x('Juan Bautista Aguirre (Los Tintos)', 'CADA', 'ry-wc-city-select'),
		_x('Laurel', 'CADA', 'ry-wc-city-select'),
		_x('Limonal', 'CADA', 'ry-wc-city-select'),
		_x('Los Lojas (Enrique Baquerizo Moreno)', 'CADA', 'ry-wc-city-select'),
	],
	'CAEC' => [
		_x('Echeandia', 'CAEC', 'ry-wc-city-select'),
	],
	'CACA6' => [
		_x('El Carmen', 'CACA6', 'ry-wc-city-select'),
		_x('San Pedro De Suma', 'CACA6', 'ry-wc-city-select'),
		_x('Wilfrido Loor Moreira (Maicito)', 'CACA6', 'ry-wc-city-select'),
	],
	'CAEM' => [
		_x('El Rosario', 'CAEM', 'ry-wc-city-select'),
		_x('Guayas (Pueblo Nuevo)', 'CAEM', 'ry-wc-city-select'),
		_x('Velasco Ibarra (Cab. El Empalme)', 'CAEM', 'ry-wc-city-select'),
	],
	'CATA' => [
		_x('El Tambo', 'CATA', 'ry-wc-city-select'),
	],
	'CAELAL' => [
		_x('Anchayacu', 'CAELAL', 'ry-wc-city-select'),
		_x('Atahualpa (Cab. En Camarones)', 'CAELAL', 'ry-wc-city-select'),
		_x('Borbon', 'CAELAL', 'ry-wc-city-select'),
		_x('Colon Eloy Del Maria', 'CAELAL', 'ry-wc-city-select'),
		_x('La Tola', 'CAELAL', 'ry-wc-city-select'),
		_x('Luis Vargas Torres (Cab. En Playa De Oro', 'CAELAL', 'ry-wc-city-select'),
		_x('Maldonado', 'CAELAL', 'ry-wc-city-select'),
		_x('Pampanal De Bolivar', 'CAELAL', 'ry-wc-city-select'),
		_x('San Francisco De Onzole', 'CAELAL', 'ry-wc-city-select'),
		_x('San Jose De Cayapas', 'CAELAL', 'ry-wc-city-select'),
		_x('Santa Lucia De Las Penas', 'CAELAL', 'ry-wc-city-select'),
		_x('Santo Domingo De Onzole', 'CAELAL', 'ry-wc-city-select'),
		_x('Selva Alegre', 'CAELAL', 'ry-wc-city-select'),
		_x('Telembi', 'CAELAL', 'ry-wc-city-select'),
		_x('Timbire', 'CAELAL', 'ry-wc-city-select'),
		_x('Valdez (Limones)', 'CAELAL', 'ry-wc-city-select'),
	],
	'CAES' => [
		_x('Camarones (Cab. En San Vicente)', 'CAES', 'ry-wc-city-select'),
		_x('Chinca', 'CAES', 'ry-wc-city-select'),
		_x('Crnel. Carlos Concha Torres (Cab. En Hue', 'CAES', 'ry-wc-city-select'),
		_x('Esmeraldas', 'CAES', 'ry-wc-city-select'),
		_x('Majua', 'CAES', 'ry-wc-city-select'),
		_x('San Mateo', 'CAES', 'ry-wc-city-select'),
		_x('Tabiazo', 'CAES', 'ry-wc-city-select'),
		_x('Tachina', 'CAES', 'ry-wc-city-select'),
		_x('Vuelta Larga', 'CAES', 'ry-wc-city-select'),
	],
	'CAES2' => [
		_x('El Angel', 'CAES2', 'ry-wc-city-select'),
		_x('El Goaltal', 'CAES2', 'ry-wc-city-select'),
		_x('La Libertad (Alizo)', 'CAES2', 'ry-wc-city-select'),
		_x('San Isidro', 'CAES2', 'ry-wc-city-select'),
	],
	'CAES3' => [
		_x('27 De Abril (Cab. En La Naranja)', 'CAES3', 'ry-wc-city-select'),
		_x('Amaluza', 'CAES3', 'ry-wc-city-select'),
		_x('Bellavista', 'CAES3', 'ry-wc-city-select'),
		_x('El Airo', 'CAES3', 'ry-wc-city-select'),
		_x('El Ingenio', 'CAES3', 'ry-wc-city-select'),
		_x('Jimbura', 'CAES3', 'ry-wc-city-select'),
		_x('Santa Teresita', 'CAES3', 'ry-wc-city-select'),
	],
	'CAGI' => [
		_x('Asuncion', 'CAGI', 'ry-wc-city-select'),
		_x('Giron', 'CAGI', 'ry-wc-city-select'),
		_x('San Gerardo', 'CAGI', 'ry-wc-city-select'),
	],
	'CAGO' => [
		_x('Changaimina (La Libertad)', 'CAGO', 'ry-wc-city-select'),
		_x('Gonzanama', 'CAGO', 'ry-wc-city-select'),
		_x('Nambacola', 'CAGO', 'ry-wc-city-select'),
		_x('Purunuma (Eguiguren)', 'CAGO', 'ry-wc-city-select'),
		_x('Sacapalca', 'CAGO', 'ry-wc-city-select'),
	],
	'CAGU' => [
		_x('Barbones (Sucre)', 'CAGU', 'ry-wc-city-select'),
		_x('El Guabo', 'CAGU', 'ry-wc-city-select'),
		_x('La Iberia', 'CAGU', 'ry-wc-city-select'),
		_x('Rio Bonito', 'CAGU', 'ry-wc-city-select'),
		_x('Tendales (Cab. En Puerto Tendales)', 'CAGU', 'ry-wc-city-select'),
	],
	'CAGU2' => [
		_x('Daniel Cordova Toral (El Oriente)', 'CAGU2', 'ry-wc-city-select'),
		_x('Gualaceo', 'CAGU2', 'ry-wc-city-select'),
		_x('Jadan', 'CAGU2', 'ry-wc-city-select'),
		_x('Luis Cordero Vega', 'CAGU2', 'ry-wc-city-select'),
		_x('Mariano Moreno', 'CAGU2', 'ry-wc-city-select'),
		_x('Remigio Crespo Toral (Gulag)', 'CAGU2', 'ry-wc-city-select'),
		_x('San Juan', 'CAGU2', 'ry-wc-city-select'),
		_x('Simon Bolivar (Cab. En Gananzol)', 'CAGU2', 'ry-wc-city-select'),
		_x('Zhidmad', 'CAGU2', 'ry-wc-city-select'),
	],
	'CAGU3' => [
		_x('Amazonas (Rosario De Cuyes)', 'CAGU3', 'ry-wc-city-select'),
		_x('Bermejos', 'CAGU3', 'ry-wc-city-select'),
		_x('Bomboiza', 'CAGU3', 'ry-wc-city-select'),
		_x('Chiguinda', 'CAGU3', 'ry-wc-city-select'),
		_x('El Ideal', 'CAGU3', 'ry-wc-city-select'),
		_x('El Rosario', 'CAGU3', 'ry-wc-city-select'),
		_x('Gualaquiza', 'CAGU3', 'ry-wc-city-select'),
		_x('Nueva Tarqui', 'CAGU3', 'ry-wc-city-select'),
		_x('San Miguel De Cuyes', 'CAGU3', 'ry-wc-city-select'),
	],
	'CAGU4' => [
		_x('Cebadas', 'CAGU4', 'ry-wc-city-select'),
		_x('Guamote', 'CAGU4', 'ry-wc-city-select'),
		_x('Palmira', 'CAGU4', 'ry-wc-city-select'),
	],
	'CAGU5' => [
		_x('Guanando', 'CAGU5', 'ry-wc-city-select'),
		_x('Guano', 'CAGU5', 'ry-wc-city-select'),
		_x('Ilapo', 'CAGU5', 'ry-wc-city-select'),
		_x('La Providencia', 'CAGU5', 'ry-wc-city-select'),
		_x('San Andres', 'CAGU5', 'ry-wc-city-select'),
		_x('San Gerardo De Pacaicaguan', 'CAGU5', 'ry-wc-city-select'),
		_x('San Isidro De Patulu', 'CAGU5', 'ry-wc-city-select'),
		_x('San Jose Del Chazo', 'CAGU5', 'ry-wc-city-select'),
		_x('Santa Fe De Galan', 'CAGU5', 'ry-wc-city-select'),
		_x('Valparaiso', 'CAGU5', 'ry-wc-city-select'),
	],
	'CAGU6' => [
		_x('Facundo Vela', 'CAGU6', 'ry-wc-city-select'),
		_x('Guaranda', 'CAGU6', 'ry-wc-city-select'),
		_x('Julio E. Moreno (Catanahuan Grande)', 'CAGU6', 'ry-wc-city-select'),
		_x('Salinas', 'CAGU6', 'ry-wc-city-select'),
		_x('San Lorenzo', 'CAGU6', 'ry-wc-city-select'),
		_x('San Luis De Pambil', 'CAGU6', 'ry-wc-city-select'),
		_x('San Simon (Yacoto)', 'CAGU6', 'ry-wc-city-select'),
		_x('Santa Fe (Santa Fe)', 'CAGU6', 'ry-wc-city-select'),
		_x('Simiatug', 'CAGU6', 'ry-wc-city-select'),
	],
	'CAGU7' => [
		_x('Guayaquil', 'CAGU7', 'ry-wc-city-select'),
		_x('Juan Gomez Rendon (Progreso)', 'CAGU7', 'ry-wc-city-select'),
		_x('Morro', 'CAGU7', 'ry-wc-city-select'),
		_x('Posorja', 'CAGU7', 'ry-wc-city-select'),
		_x('Puna', 'CAGU7', 'ry-wc-city-select'),
		_x('Tenguel', 'CAGU7', 'ry-wc-city-select'),
	],
	'CAHU' => [
		_x('Huaquillas', 'CAHU', 'ry-wc-city-select'),
	],
	'CAIS' => [
		_x('Puerto Villamil', 'CAIS', 'ry-wc-city-select'),
		_x('Tomas De Berlanga (Santo Tomas)', 'CAIS', 'ry-wc-city-select'),
	],
	'CAJI' => [
		_x('America', 'CAJI', 'ry-wc-city-select'),
		_x('El Anegado (Cab. En Eloy Alfaro)', 'CAJI', 'ry-wc-city-select'),
		_x('Jipijapa', 'CAJI', 'ry-wc-city-select'),
		_x('Julcuy', 'CAJI', 'ry-wc-city-select'),
		_x('La Union', 'CAJI', 'ry-wc-city-select'),
		_x('Membrillal', 'CAJI', 'ry-wc-city-select'),
		_x('Pedro Pablo Gomez', 'CAJI', 'ry-wc-city-select'),
		_x('Puerto De Cayo', 'CAJI', 'ry-wc-city-select'),
	],
	'CAJU' => [
		_x('Junin', 'CAJU', 'ry-wc-city-select'),
	],
	'CALAAG' => [
		_x('10 De Agosto', 'CALAAG', 'ry-wc-city-select'),
		_x('Dureno', 'CALAAG', 'ry-wc-city-select'),
		_x('El Eno', 'CALAAG', 'ry-wc-city-select'),
		_x('General Farfan', 'CALAAG', 'ry-wc-city-select'),
		_x('Jambeli', 'CALAAG', 'ry-wc-city-select'),
		_x('Nueva Loja', 'CALAAG', 'ry-wc-city-select'),
		_x('Pacayacu', 'CALAAG', 'ry-wc-city-select'),
		_x('Santa Cecilia', 'CALAAG', 'ry-wc-city-select'),
	],
	'CALANA' => [
		_x('Las Naves', 'CALANA', 'ry-wc-city-select'),
	],
	'CALA' => [
		_x('11 De Noviembre (Ilinchisi)', 'CALA', 'ry-wc-city-select'),
		_x('Alaques (Alaquez)', 'CALA', 'ry-wc-city-select'),
		_x('Belisario Quevedo (Guanailin)', 'CALA', 'ry-wc-city-select'),
		_x('Guaitacama (Guaytacama)', 'CALA', 'ry-wc-city-select'),
		_x('Joseguango Bajo', 'CALA', 'ry-wc-city-select'),
		_x('Latacunga', 'CALA', 'ry-wc-city-select'),
		_x('Mulalo', 'CALA', 'ry-wc-city-select'),
		_x('Poalo', 'CALA', 'ry-wc-city-select'),
		_x('San Juan De Pastocalle', 'CALA', 'ry-wc-city-select'),
		_x('Tanicuchi', 'CALA', 'ry-wc-city-select'),
		_x('Toacaso', 'CALA', 'ry-wc-city-select'),
	],
	'CALIIN' => [
		_x('Gral. Leonidas Plaza Gutierrez', 'CALIIN', 'ry-wc-city-select'),
		_x('Indanza', 'CALIIN', 'ry-wc-city-select'),
		_x('San Antonio (Cab En San Antonio Centro)', 'CALIIN', 'ry-wc-city-select'),
		_x('San Miguel De Conchay', 'CALIIN', 'ry-wc-city-select'),
		_x('Sta Susana De Chiviaza (Cab En Chiviaza)', 'CALIIN', 'ry-wc-city-select'),
		_x('Yunganza (Cab En El Rosario)', 'CALIIN', 'ry-wc-city-select'),
	],
	'CALO' => [
		_x('Chantaco', 'CALO', 'ry-wc-city-select'),
		_x('Chuquiribamba', 'CALO', 'ry-wc-city-select'),
		_x('El Cisne', 'CALO', 'ry-wc-city-select'),
		_x('Gualel', 'CALO', 'ry-wc-city-select'),
		_x('Jimbilla', 'CALO', 'ry-wc-city-select'),
		_x('Loja', 'CALO', 'ry-wc-city-select'),
		_x('Malacatos (Valladolid)', 'CALO', 'ry-wc-city-select'),
		_x('Quinara', 'CALO', 'ry-wc-city-select'),
		_x('San Lucas', 'CALO', 'ry-wc-city-select'),
		_x('San Pedro De Vilcabamba', 'CALO', 'ry-wc-city-select'),
		_x('Santiago', 'CALO', 'ry-wc-city-select'),
		_x('Taquil (Miguel Riofrio)', 'CALO', 'ry-wc-city-select'),
		_x('Vilcabamba (Victoria)', 'CALO', 'ry-wc-city-select'),
		_x('Yangana (Arsenio Castillo)', 'CALO', 'ry-wc-city-select'),
	],
	'CAMA' => [
		_x('La Victoria', 'CAMA', 'ry-wc-city-select'),
		_x('Larama', 'CAMA', 'ry-wc-city-select'),
		_x('Macara', 'CAMA', 'ry-wc-city-select'),
		_x('Sabiango (La Capilla)', 'CAMA', 'ry-wc-city-select'),
	],
	'CAMA2' => [
		_x('El Retiro', 'CAMA2', 'ry-wc-city-select'),
		_x('Machala', 'CAMA2', 'ry-wc-city-select'),
	],
	'CAMA3' => [
		_x('Manta', 'CAMA3', 'ry-wc-city-select'),
		_x('San Lorenzo', 'CAMA3', 'ry-wc-city-select'),
		_x('Santa Marianita (Boca De Pacoche)', 'CAMA3', 'ry-wc-city-select'),
	],
	'CAME' => [
		_x('Aloag', 'CAME', 'ry-wc-city-select'),
		_x('Aloasi', 'CAME', 'ry-wc-city-select'),
		_x('Cutuglahua', 'CAME', 'ry-wc-city-select'),
		_x('El Chaupi', 'CAME', 'ry-wc-city-select'),
		_x('Machachi', 'CAME', 'ry-wc-city-select'),
		_x('Manuel Cornejo Astorga (Tandapi)', 'CAME', 'ry-wc-city-select'),
		_x('Tambillo', 'CAME', 'ry-wc-city-select'),
		_x('Uyumbicho', 'CAME', 'ry-wc-city-select'),
	],
	'CAME2' => [
		_x('Madre Tierra', 'CAME2', 'ry-wc-city-select'),
		_x('Mera', 'CAME2', 'ry-wc-city-select'),
		_x('Shell', 'CAME2', 'ry-wc-city-select'),
	],
	'CAMI' => [
		_x('Chobo', 'CAMI', 'ry-wc-city-select'),
		_x('Mariscal Sucre (Huaques)', 'CAMI', 'ry-wc-city-select'),
		_x('Milagro', 'CAMI', 'ry-wc-city-select'),
		_x('Roberto Astudillo (Cab. En Cruce De Vene', 'CAMI', 'ry-wc-city-select'),
	],
	'CAMI2' => [
		_x('Concepcion', 'CAMI2', 'ry-wc-city-select'),
		_x('Jijon Y Caamano (Cab. En Rio Blanco)', 'CAMI2', 'ry-wc-city-select'),
		_x('Juan Montalvo (San Ignacio De Quil)', 'CAMI2', 'ry-wc-city-select'),
		_x('Mira (Chontahuasi)', 'CAMI2', 'ry-wc-city-select'),
	],
	'CAMO' => [
		_x('La Pila', 'CAMO', 'ry-wc-city-select'),
		_x('Montecristi', 'CAMO', 'ry-wc-city-select'),
	],
	'CAMO2' => [
		_x('Chitan De Navarrete', 'CAMO2', 'ry-wc-city-select'),
		_x('Cristobal Colon', 'CAMO2', 'ry-wc-city-select'),
		_x('Fernandez Salvador', 'CAMO2', 'ry-wc-city-select'),
		_x('La Paz', 'CAMO2', 'ry-wc-city-select'),
		_x('Piartal', 'CAMO2', 'ry-wc-city-select'),
		_x('San Gabriel', 'CAMO2', 'ry-wc-city-select'),
	],
	'CAMO3' => [
		_x('Alshi (Cab En 9 De Octubre)', 'CAMO3', 'ry-wc-city-select'),
		_x('Cuchaentza', 'CAMO3', 'ry-wc-city-select'),
		_x('General Proano', 'CAMO3', 'ry-wc-city-select'),
		_x('Macas', 'CAMO3', 'ry-wc-city-select'),
		_x('Rio Blanco', 'CAMO3', 'ry-wc-city-select'),
		_x('San Isidro', 'CAMO3', 'ry-wc-city-select'),
		_x('Sevilla Don Bosco', 'CAMO3', 'ry-wc-city-select'),
		_x('Sinai', 'CAMO3', 'ry-wc-city-select'),
		_x('Zuna (Zunac)', 'CAMO3', 'ry-wc-city-select'),
	],
	'CAMU' => [
		_x('Bolivar', 'CAMU', 'ry-wc-city-select'),
		_x('Daule', 'CAMU', 'ry-wc-city-select'),
		_x('Galera', 'CAMU', 'ry-wc-city-select'),
		_x('Muisne', 'CAMU', 'ry-wc-city-select'),
		_x('Quingue (Olmedo Perdomo Franco)', 'CAMU', 'ry-wc-city-select'),
		_x('Salima', 'CAMU', 'ry-wc-city-select'),
		_x('San Francisco', 'CAMU', 'ry-wc-city-select'),
		_x('San Gregorio', 'CAMU', 'ry-wc-city-select'),
		_x('San Jose De Chamanga', 'CAMU', 'ry-wc-city-select'),
	],
	'CANA' => [
		_x('Cochapata', 'CANA', 'ry-wc-city-select'),
		_x('El Progreso (Cab. En Zhota)', 'CANA', 'ry-wc-city-select'),
		_x('Las Nieves (Chaya)', 'CANA', 'ry-wc-city-select'),
		_x('Nabon', 'CANA', 'ry-wc-city-select'),
	],
	'CANA2' => [
		_x('Jesus Maria', 'CANA2', 'ry-wc-city-select'),
		_x('Naranjal', 'CANA2', 'ry-wc-city-select'),
		_x('San Carlos', 'CANA2', 'ry-wc-city-select'),
		_x('Santa Rosa De Flandes', 'CANA2', 'ry-wc-city-select'),
		_x('Taura', 'CANA2', 'ry-wc-city-select'),
	],
	'CANA3' => [
		_x('Naranjito', 'CANA3', 'ry-wc-city-select'),
	],
	'CAOT' => [
		_x('Doctor Miguel Egas Cabezas (Peguche)', 'CAOT', 'ry-wc-city-select'),
		_x('Eugenio Espejo (Calpaqui)', 'CAOT', 'ry-wc-city-select'),
		_x('Gonzalez Suarez', 'CAOT', 'ry-wc-city-select'),
		_x('Otavalo', 'CAOT', 'ry-wc-city-select'),
		_x('Pataqui', 'CAOT', 'ry-wc-city-select'),
		_x('San Jose De Quichinche', 'CAOT', 'ry-wc-city-select'),
		_x('San Juan De Iluman', 'CAOT', 'ry-wc-city-select'),
		_x('San Pablo', 'CAOT', 'ry-wc-city-select'),
		_x('San Rafael', 'CAOT', 'ry-wc-city-select'),
		_x('Selva Alegre (Cab. En San Miguel De Pamp', 'CAOT', 'ry-wc-city-select'),
	],
	'CAPA' => [
		_x('Campozano (La Palma De Pajan)', 'CAPA', 'ry-wc-city-select'),
		_x('Cascol', 'CAPA', 'ry-wc-city-select'),
		_x('Guale', 'CAPA', 'ry-wc-city-select'),
		_x('Lascano', 'CAPA', 'ry-wc-city-select'),
		_x('Pajan', 'CAPA', 'ry-wc-city-select'),
	],
	'CAPA2' => [
		_x('16 De Agosto', 'CAPA2', 'ry-wc-city-select'),
		_x('Arapicos', 'CAPA2', 'ry-wc-city-select'),
		_x('Cumanda (Cab En Colonia Agricola Sevilla', 'CAPA2', 'ry-wc-city-select'),
		_x('Palora (Metzera)', 'CAPA2', 'ry-wc-city-select'),
		_x('Sangay (Cab En Nayamanaca)', 'CAPA2', 'ry-wc-city-select'),
	],
	'CAPA3' => [
		_x('Cangonama', 'CAPA3', 'ry-wc-city-select'),
		_x('Casanga', 'CAPA3', 'ry-wc-city-select'),
		_x('Catacocha', 'CAPA3', 'ry-wc-city-select'),
		_x('Guachanama', 'CAPA3', 'ry-wc-city-select'),
		_x('Lauro Guerrero', 'CAPA3', 'ry-wc-city-select'),
		_x('Orianga', 'CAPA3', 'ry-wc-city-select'),
		_x('San Antonio', 'CAPA3', 'ry-wc-city-select'),
		_x('Yamana', 'CAPA3', 'ry-wc-city-select'),
	],
	'CAPA4' => [
		_x('El Corazon', 'CAPA4', 'ry-wc-city-select'),
		_x('Moraspungo', 'CAPA4', 'ry-wc-city-select'),
		_x('Pinllopata', 'CAPA4', 'ry-wc-city-select'),
		_x('Ramon Campana', 'CAPA4', 'ry-wc-city-select'),
	],
	'CAPA5' => [
		_x('Buenavista', 'CAPA5', 'ry-wc-city-select'),
		_x('Canaquemada', 'CAPA5', 'ry-wc-city-select'),
		_x('Casacay', 'CAPA5', 'ry-wc-city-select'),
		_x('La Peana', 'CAPA5', 'ry-wc-city-select'),
		_x('Pasaje', 'CAPA5', 'ry-wc-city-select'),
		_x('Progreso', 'CAPA5', 'ry-wc-city-select'),
		_x('Uzhcurrumi', 'CAPA5', 'ry-wc-city-select'),
	],
	'CAPA6' => [
		_x('Canelos', 'CAPA6', 'ry-wc-city-select'),
		_x('Diez De Agosto', 'CAPA6', 'ry-wc-city-select'),
		_x('El Triunfo', 'CAPA6', 'ry-wc-city-select'),
		_x('Fatima', 'CAPA6', 'ry-wc-city-select'),
		_x('Montalvo (Andoas)', 'CAPA6', 'ry-wc-city-select'),
		_x('Pomona', 'CAPA6', 'ry-wc-city-select'),
		_x('Puyo', 'CAPA6', 'ry-wc-city-select'),
		_x('Rio Corrientes', 'CAPA6', 'ry-wc-city-select'),
		_x('Rio Tigre', 'CAPA6', 'ry-wc-city-select'),
		_x('Sarayacu', 'CAPA6', 'ry-wc-city-select'),
		_x('Simon Bolivar (Cab. En Mushullacta)', 'CAPA6', 'ry-wc-city-select'),
		_x('Tarqui', 'CAPA6', 'ry-wc-city-select'),
		_x('Teniente Hugo Ortiz', 'CAPA6', 'ry-wc-city-select'),
		_x('Veracruz (Indillama) (Cab. En Indillama)', 'CAPA6', 'ry-wc-city-select'),
	],
	'CAPA7' => [
		_x('El Triunfo', 'CAPA7', 'ry-wc-city-select'),
		_x('Los Andes (Cab. En Poatug)', 'CAPA7', 'ry-wc-city-select'),
		_x('Patate', 'CAPA7', 'ry-wc-city-select'),
		_x('Sucre (Cab. En Sucre-Patate Urcu)', 'CAPA7', 'ry-wc-city-select'),
	],
	'CAPA8' => [
		_x('Bulan (Jose Victor Izquierdo)', 'CAPA8', 'ry-wc-city-select'),
		_x('Chican (Guillermo Ortega)', 'CAPA8', 'ry-wc-city-select'),
		_x('Dug Dug', 'CAPA8', 'ry-wc-city-select'),
		_x('El Cabo', 'CAPA8', 'ry-wc-city-select'),
		_x('Guarainag', 'CAPA8', 'ry-wc-city-select'),
		_x('Paute', 'CAPA8', 'ry-wc-city-select'),
		_x('San Cristobal (Carlos Ordonez Lazo)', 'CAPA8', 'ry-wc-city-select'),
		_x('Tomebamba', 'CAPA8', 'ry-wc-city-select'),
	],
	'CAPE' => [
		_x('10 De Agosto', 'CAPE', 'ry-wc-city-select'),
		_x('Atahualpa', 'CAPE', 'ry-wc-city-select'),
		_x('Cojimies', 'CAPE', 'ry-wc-city-select'),
		_x('Pedernales', 'CAPE', 'ry-wc-city-select'),
	],
	'CAPEMO' => [
		_x('La Esperanza', 'CAPEMO', 'ry-wc-city-select'),
		_x('Malchingui', 'CAPEMO', 'ry-wc-city-select'),
		_x('Tabacundo', 'CAPEMO', 'ry-wc-city-select'),
		_x('Tocachi', 'CAPEMO', 'ry-wc-city-select'),
		_x('Tupigachi', 'CAPEMO', 'ry-wc-city-select'),
	],
	'CAPEVIMA' => [
		_x('Pedro Vicente Maldonado', 'CAPEVIMA', 'ry-wc-city-select'),
	],
	'CAPE2' => [
		_x('Benitez (Pachanlica)', 'CAPE2', 'ry-wc-city-select'),
		_x('Bolivar', 'CAPE2', 'ry-wc-city-select'),
		_x('Chiquicha (Cab. En Chiquicha Grande)', 'CAPE2', 'ry-wc-city-select'),
		_x('Cotalo', 'CAPE2', 'ry-wc-city-select'),
		_x('El Rosario (Rumichaca)', 'CAPE2', 'ry-wc-city-select'),
		_x('Garcia Moreno (Chumaqui)', 'CAPE2', 'ry-wc-city-select'),
		_x('Guambalo (Huambalo)', 'CAPE2', 'ry-wc-city-select'),
		_x('Pelileo', 'CAPE2', 'ry-wc-city-select'),
		_x('Salasaca', 'CAPE2', 'ry-wc-city-select'),
	],
	'CAPI' => [
		_x('Baquerizo Moreno', 'CAPI', 'ry-wc-city-select'),
		_x('Emilio Maria Teran (Rumipamba)', 'CAPI', 'ry-wc-city-select'),
		_x('Marcos Espinel (Chacata)', 'CAPI', 'ry-wc-city-select'),
		_x('Pillaro', 'CAPI', 'ry-wc-city-select'),
		_x('Presidente Urbina (Chagrapamba -Patzucul', 'CAPI', 'ry-wc-city-select'),
		_x('San Andres', 'CAPI', 'ry-wc-city-select'),
		_x('San Jose De Poalo', 'CAPI', 'ry-wc-city-select'),
		_x('San Miguelito', 'CAPI', 'ry-wc-city-select'),
	],
	'CAPI2' => [
		_x('Chuga', 'CAPI2', 'ry-wc-city-select'),
		_x('Mariano Acosta', 'CAPI2', 'ry-wc-city-select'),
		_x('Pimampiro', 'CAPI2', 'ry-wc-city-select'),
		_x('San  Fco. De Sigsipamba', 'CAPI2', 'ry-wc-city-select'),
	],
	'CAPI3' => [
		_x('Capiro (Cab. En La Capilla De Capiro)', 'CAPI3', 'ry-wc-city-select'),
		_x('La Bocana', 'CAPI3', 'ry-wc-city-select'),
		_x('Moromoro (Cab. En El Vado)', 'CAPI3', 'ry-wc-city-select'),
		_x('Piedras', 'CAPI3', 'ry-wc-city-select'),
		_x('Pinas', 'CAPI3', 'ry-wc-city-select'),
		_x('San Roque (Ambrosio Maldonado)', 'CAPI3', 'ry-wc-city-select'),
		_x('Saracay', 'CAPI3', 'ry-wc-city-select'),
	],
	'CAPO' => [
		_x('Curtincapa', 'CAPO', 'ry-wc-city-select'),
		_x('Morales', 'CAPO', 'ry-wc-city-select'),
		_x('Portovelo', 'CAPO', 'ry-wc-city-select'),
		_x('Salati', 'CAPO', 'ry-wc-city-select'),
	],
	'CAPO2' => [
		_x('Abdon Calderon (San Francisco)', 'CAPO2', 'ry-wc-city-select'),
		_x('Alhajuela (Bajo Grande)', 'CAPO2', 'ry-wc-city-select'),
		_x('Chirijos', 'CAPO2', 'ry-wc-city-select'),
		_x('Crucita', 'CAPO2', 'ry-wc-city-select'),
		_x('Portoviejo', 'CAPO2', 'ry-wc-city-select'),
		_x('Pueblo Nuevo', 'CAPO2', 'ry-wc-city-select'),
		_x('Riochico (Rio Chico)', 'CAPO2', 'ry-wc-city-select'),
		_x('San Placido', 'CAPO2', 'ry-wc-city-select'),
	],
	'CAPU' => [
		_x('Puebloviejo', 'CAPU', 'ry-wc-city-select'),
		_x('Puerto Pechiche', 'CAPU', 'ry-wc-city-select'),
		_x('San Juan', 'CAPU', 'ry-wc-city-select'),
	],
	'CAPU2' => [
		_x('Angamarca', 'CAPU2', 'ry-wc-city-select'),
		_x('Guangaje', 'CAPU2', 'ry-wc-city-select'),
		_x('La Victoria', 'CAPU2', 'ry-wc-city-select'),
		_x('Pilalo', 'CAPU2', 'ry-wc-city-select'),
		_x('Pujili', 'CAPU2', 'ry-wc-city-select'),
		_x('Tingo', 'CAPU2', 'ry-wc-city-select'),
		_x('Zumbahua', 'CAPU2', 'ry-wc-city-select'),
	],
	'CAPU3' => [
		_x('Palma Roja', 'CAPU3', 'ry-wc-city-select'),
		_x('Puerto Bolivar (Puerto Montufar)', 'CAPU3', 'ry-wc-city-select'),
		_x('Puerto El Carmen Del Putumayo', 'CAPU3', 'ry-wc-city-select'),
		_x('Puerto Rodriguez', 'CAPU3', 'ry-wc-city-select'),
		_x('Santa Elena', 'CAPU3', 'ry-wc-city-select'),
	],
	'CAPU4' => [
		_x('Alamor', 'CAPU4', 'ry-wc-city-select'),
		_x('Ciano', 'CAPU4', 'ry-wc-city-select'),
		_x('El Arenal', 'CAPU4', 'ry-wc-city-select'),
		_x('El Limo (Mariana De Jesus)', 'CAPU4', 'ry-wc-city-select'),
		_x('Mercadillo', 'CAPU4', 'ry-wc-city-select'),
		_x('Vicentino', 'CAPU4', 'ry-wc-city-select'),
	],
	'CAQU' => [
		_x('Quero', 'CAQU', 'ry-wc-city-select'),
		_x('Rumipamba', 'CAQU', 'ry-wc-city-select'),
		_x('Yanayacu - Mochapata (Cab. En Yanayacu)', 'CAQU', 'ry-wc-city-select'),
	],
	'CAQU2' => [
		_x('La Esperanza', 'CAQU2', 'ry-wc-city-select'),
		_x('Quevedo', 'CAQU2', 'ry-wc-city-select'),
		_x('San Carlos', 'CAQU2', 'ry-wc-city-select'),
	],
	'CAQU3' => [
		_x('Baeza', 'CAQU3', 'ry-wc-city-select'),
		_x('Cosanga', 'CAQU3', 'ry-wc-city-select'),
		_x('Cuyuja', 'CAQU3', 'ry-wc-city-select'),
		_x('Papallacta', 'CAQU3', 'ry-wc-city-select'),
		_x('San Francisco De Borja (Virgilio Davila)', 'CAQU3', 'ry-wc-city-select'),
		_x('Sumaco', 'CAQU3', 'ry-wc-city-select'),
	],
	'CAQU4' => [
		_x('Chura (Chancama) (Cab. En El Yerbero)', 'CAQU4', 'ry-wc-city-select'),
		_x('Cube', 'CAQU4', 'ry-wc-city-select'),
		_x('La Union', 'CAQU4', 'ry-wc-city-select'),
		_x('Malimpia', 'CAQU4', 'ry-wc-city-select'),
		_x('Rosa Zarate (Quininde)', 'CAQU4', 'ry-wc-city-select'),
		_x('Viche', 'CAQU4', 'ry-wc-city-select'),
	],
	'CAQU5' => [
		_x('Alangasi', 'CAQU5', 'ry-wc-city-select'),
		_x('Amaguana', 'CAQU5', 'ry-wc-city-select'),
		_x('Atahualpa (Habaspamba)', 'CAQU5', 'ry-wc-city-select'),
		_x('Calacali', 'CAQU5', 'ry-wc-city-select'),
		_x('Calderon (Carapungo)', 'CAQU5', 'ry-wc-city-select'),
		_x('Chavezpamba', 'CAQU5', 'ry-wc-city-select'),
		_x('Checa (Chilpa)', 'CAQU5', 'ry-wc-city-select'),
		_x('Conocoto', 'CAQU5', 'ry-wc-city-select'),
		_x('Cumbaya', 'CAQU5', 'ry-wc-city-select'),
		_x('El Quinche', 'CAQU5', 'ry-wc-city-select'),
		_x('Gualea', 'CAQU5', 'ry-wc-city-select'),
		_x('Guangopolo', 'CAQU5', 'ry-wc-city-select'),
		_x('Guayllabamba', 'CAQU5', 'ry-wc-city-select'),
		_x('La Merced', 'CAQU5', 'ry-wc-city-select'),
		_x('Llano Chico', 'CAQU5', 'ry-wc-city-select'),
		_x('Lloa', 'CAQU5', 'ry-wc-city-select'),
		_x('Nanegal', 'CAQU5', 'ry-wc-city-select'),
		_x('Nanegalito', 'CAQU5', 'ry-wc-city-select'),
		_x('Nayon', 'CAQU5', 'ry-wc-city-select'),
		_x('Nono', 'CAQU5', 'ry-wc-city-select'),
		_x('Pacto', 'CAQU5', 'ry-wc-city-select'),
		_x('Perucho', 'CAQU5', 'ry-wc-city-select'),
		_x('Pifo', 'CAQU5', 'ry-wc-city-select'),
		_x('Pintag', 'CAQU5', 'ry-wc-city-select'),
		_x('Pomasqui', 'CAQU5', 'ry-wc-city-select'),
		_x('Puellaro', 'CAQU5', 'ry-wc-city-select'),
		_x('Puembo', 'CAQU5', 'ry-wc-city-select'),
		_x('Quito', 'CAQU5', 'ry-wc-city-select'),
		_x('San Antonio', 'CAQU5', 'ry-wc-city-select'),
		_x('San Jose De Minas', 'CAQU5', 'ry-wc-city-select'),
		_x('Tababela', 'CAQU5', 'ry-wc-city-select'),
		_x('Tumbaco', 'CAQU5', 'ry-wc-city-select'),
		_x('Yaruqui', 'CAQU5', 'ry-wc-city-select'),
		_x('Zambiza', 'CAQU5', 'ry-wc-city-select'),
	],
	'CARI' => [
		_x('Cacha (Cab. En Machangara)', 'CARI', 'ry-wc-city-select'),
		_x('Calpi', 'CARI', 'ry-wc-city-select'),
		_x('Cubijies', 'CARI', 'ry-wc-city-select'),
		_x('Flores', 'CARI', 'ry-wc-city-select'),
		_x('Lican', 'CARI', 'ry-wc-city-select'),
		_x('Licto', 'CARI', 'ry-wc-city-select'),
		_x('Pungala', 'CARI', 'ry-wc-city-select'),
		_x('Punin', 'CARI', 'ry-wc-city-select'),
		_x('Quimiag', 'CARI', 'ry-wc-city-select'),
		_x('Riobamba', 'CARI', 'ry-wc-city-select'),
		_x('San Juan', 'CARI', 'ry-wc-city-select'),
		_x('San Luis', 'CARI', 'ry-wc-city-select'),
	],
	'CARO' => [
		_x('Rocafuerte', 'CARO', 'ry-wc-city-select'),
	],
	'CARU' => [
		_x('Cotogchoa', 'CARU', 'ry-wc-city-select'),
		_x('Rumipamba', 'CARU', 'ry-wc-city-select'),
		_x('Sangolqui', 'CARU', 'ry-wc-city-select'),
	],
	'CASA' => [
		_x('Antonio Jose Holguin (Santa Lucia)', 'CASA', 'ry-wc-city-select'),
		_x('Cusubamba', 'CASA', 'ry-wc-city-select'),
		_x('Mulalillo', 'CASA', 'ry-wc-city-select'),
		_x('Mulliquindil (Santa Ana)', 'CASA', 'ry-wc-city-select'),
		_x('Pansaleo', 'CASA', 'ry-wc-city-select'),
		_x('San Miguel', 'CASA', 'ry-wc-city-select'),
	],
	'CASA2' => [
		_x('Anconcito', 'CASA2', 'ry-wc-city-select'),
		_x('Jose Luis Tamayo (Muey)', 'CASA2', 'ry-wc-city-select'),
		_x('Salinas', 'CASA2', 'ry-wc-city-select'),
	],
	'CASA3' => [
		_x('El Salitre (Las Ramas)', 'CASA3', 'ry-wc-city-select'),
		_x('Gral. Vernaza (Dos Esteros)', 'CASA3', 'ry-wc-city-select'),
		_x('Junquillal', 'CASA3', 'ry-wc-city-select'),
		_x('La Victoria (Nauza)', 'CASA3', 'ry-wc-city-select'),
	],
	'CASA4' => [
		_x('Samborondon', 'CASA4', 'ry-wc-city-select'),
		_x('Tarifa', 'CASA4', 'ry-wc-city-select'),
	],
	'CASACR' => [
		_x('El Progreso', 'CASACR', 'ry-wc-city-select'),
		_x('Isla Santa Maria (Floreana) (Cab. En  Pt', 'CASACR', 'ry-wc-city-select'),
		_x('Puerto Baquerizo Moreno', 'CASACR', 'ry-wc-city-select'),
	],
	'CASAFE' => [
		_x('Chumblin', 'CASAFE', 'ry-wc-city-select'),
		_x('San Fernando', 'CASAFE', 'ry-wc-city-select'),
	],
	'CASALO' => [
		_x('5 De Junio (Cab. En Uimbi)', 'CASALO', 'ry-wc-city-select'),
		_x('Alto Tambo (Cab En Guadual)', 'CASALO', 'ry-wc-city-select'),
		_x('Ancon (Pichangal) (Cab. En Palma Real)', 'CASALO', 'ry-wc-city-select'),
		_x('Calderon', 'CASALO', 'ry-wc-city-select'),
		_x('Carondelet', 'CASALO', 'ry-wc-city-select'),
		_x('Concepcion', 'CASALO', 'ry-wc-city-select'),
		_x('Mataje (Cab. En Santander)', 'CASALO', 'ry-wc-city-select'),
		_x('San Javier De Cachavi (Cab. En San Javie', 'CASALO', 'ry-wc-city-select'),
		_x('San Lorenzo', 'CASALO', 'ry-wc-city-select'),
		_x('Santa Rita', 'CASALO', 'ry-wc-city-select'),
		_x('Tambillo', 'CASALO', 'ry-wc-city-select'),
		_x('Tululbi (Cab. En Ricaurte)', 'CASALO', 'ry-wc-city-select'),
		_x('Urbina', 'CASALO', 'ry-wc-city-select'),
	],
	'CASAMI' => [
		_x('Balsapamba', 'CASAMI', 'ry-wc-city-select'),
		_x('Bilovan', 'CASAMI', 'ry-wc-city-select'),
		_x('Regulo De Mora', 'CASAMI', 'ry-wc-city-select'),
		_x('San Miguel', 'CASAMI', 'ry-wc-city-select'),
		_x('San Pablo (San Pablo De Atenas)', 'CASAMI', 'ry-wc-city-select'),
		_x('San Vicente', 'CASAMI', 'ry-wc-city-select'),
		_x('Santiago', 'CASAMI', 'ry-wc-city-select'),
	],
	'CASAAN' => [
		_x('Ayacucho', 'CASAAN', 'ry-wc-city-select'),
		_x('Honorato Vasquez (Cab En Vasquez)', 'CASAAN', 'ry-wc-city-select'),
		_x('La Union', 'CASAAN', 'ry-wc-city-select'),
		_x('San Pablo (Cab En Pueblo Nuevo)', 'CASAAN', 'ry-wc-city-select'),
		_x('Santa Ana De Vuelta Larga', 'CASAAN', 'ry-wc-city-select'),
	],
	'CASACR2' => [
		_x('Bellavista', 'CASACR2', 'ry-wc-city-select'),
		_x('Puerto Ayora', 'CASACR2', 'ry-wc-city-select'),
		_x('Santa Rosa', 'CASACR2', 'ry-wc-city-select'),
	],
	'CASAEL' => [
		_x('Atahualpa', 'CASAEL', 'ry-wc-city-select'),
		_x('Chanduy', 'CASAEL', 'ry-wc-city-select'),
		_x('Colonche', 'CASAEL', 'ry-wc-city-select'),
		_x('Manglaralto', 'CASAEL', 'ry-wc-city-select'),
		_x('San Jose De Ancon', 'CASAEL', 'ry-wc-city-select'),
		_x('Santa Elena', 'CASAEL', 'ry-wc-city-select'),
		_x('Simon Bolivar (Julio Moreno)', 'CASAEL', 'ry-wc-city-select'),
	],
	'CASAIS' => [
		_x('Abdon Calderon (La Union)', 'CASAIS', 'ry-wc-city-select'),
		_x('San Salvador De Canaribamba', 'CASAIS', 'ry-wc-city-select'),
		_x('Santa Isabel (Chaguarurco)', 'CASAIS', 'ry-wc-city-select'),
		_x('Zhaglli (Shaglli )', 'CASAIS', 'ry-wc-city-select'),
	],
	'CASARO' => [
		_x('Bellamaria', 'CASARO', 'ry-wc-city-select'),
		_x('Bellavista', 'CASARO', 'ry-wc-city-select'),
		_x('Jambeli', 'CASARO', 'ry-wc-city-select'),
		_x('La Avanzada', 'CASARO', 'ry-wc-city-select'),
		_x('San Antonio', 'CASARO', 'ry-wc-city-select'),
		_x('Santa Rosa', 'CASARO', 'ry-wc-city-select'),
		_x('Torata', 'CASARO', 'ry-wc-city-select'),
		_x('Victoria', 'CASARO', 'ry-wc-city-select'),
	],
	'CASADOLOCO' => [
		_x('Alluriquin', 'CASADOLOCO', 'ry-wc-city-select'),
		_x('El Esfuerzo', 'CASADOLOCO', 'ry-wc-city-select'),
		_x('Luz De America', 'CASADOLOCO', 'ry-wc-city-select'),
		_x('Puerto Limon', 'CASADOLOCO', 'ry-wc-city-select'),
		_x('San Jacinto Del Bua', 'CASADOLOCO', 'ry-wc-city-select'),
		_x('Santa Maria Del Toachi', 'CASADOLOCO', 'ry-wc-city-select'),
		_x('Santo Domingo De Los Colorados', 'CASADOLOCO', 'ry-wc-city-select'),
		_x('Valle Hermoso', 'CASADOLOCO', 'ry-wc-city-select'),
	],
	'CASA5' => [
		_x('El Paraiso De Celen', 'CASA5', 'ry-wc-city-select'),
		_x('El Tablon', 'CASA5', 'ry-wc-city-select'),
		_x('Lluzhapa', 'CASA5', 'ry-wc-city-select'),
		_x('Manu', 'CASA5', 'ry-wc-city-select'),
		_x('San Antonio De Qumbe (Cumbe)', 'CASA5', 'ry-wc-city-select'),
		_x('San Pablo De Tenta', 'CASA5', 'ry-wc-city-select'),
		_x('San Sebastian De Yuluc', 'CASA5', 'ry-wc-city-select'),
		_x('Saraguro', 'CASA5', 'ry-wc-city-select'),
		_x('Selva Alegre', 'CASA5', 'ry-wc-city-select'),
		_x('Sumaypamba', 'CASA5', 'ry-wc-city-select'),
		_x('Urdaneta (Paquishapa)', 'CASA5', 'ry-wc-city-select'),
	],
	'CASI' => [
		_x('Chugchillan', 'CASI', 'ry-wc-city-select'),
		_x('Isinlivi', 'CASI', 'ry-wc-city-select'),
		_x('Las Pampas', 'CASI', 'ry-wc-city-select'),
		_x('Palo Quemado', 'CASI', 'ry-wc-city-select'),
		_x('Sigchos', 'CASI', 'ry-wc-city-select'),
	],
	'CASI2' => [
		_x('Cuchil (Cutchil)', 'CASI2', 'ry-wc-city-select'),
		_x('Gima', 'CASI2', 'ry-wc-city-select'),
		_x('Guel', 'CASI2', 'ry-wc-city-select'),
		_x('Ludo', 'CASI2', 'ry-wc-city-select'),
		_x('San Bartolome', 'CASI2', 'ry-wc-city-select'),
		_x('San Jose De Raranga', 'CASI2', 'ry-wc-city-select'),
		_x('Sigsig', 'CASI2', 'ry-wc-city-select'),
	],
	'CASO' => [
		_x('Nueva Fatima', 'CASO', 'ry-wc-city-select'),
		_x('Sozoranga', 'CASO', 'ry-wc-city-select'),
		_x('Tacamoros', 'CASO', 'ry-wc-city-select'),
	],
	'CASU' => [
		_x('Bahia De Caraquez', 'CASU', 'ry-wc-city-select'),
		_x('Charapoto', 'CASU', 'ry-wc-city-select'),
		_x('San Isidro', 'CASU', 'ry-wc-city-select'),
	],
	'CASU2' => [
		_x('Asuncion', 'CASU2', 'ry-wc-city-select'),
		_x('Huambi', 'CASU2', 'ry-wc-city-select'),
		_x('Santa Marianita De Jesus', 'CASU2', 'ry-wc-city-select'),
		_x('Sucua', 'CASU2', 'ry-wc-city-select'),
	],
	'CASU3' => [
		_x('El Playon De San Francisco', 'CASU3', 'ry-wc-city-select'),
		_x('La Bonita', 'CASU3', 'ry-wc-city-select'),
		_x('La Sofia', 'CASU3', 'ry-wc-city-select'),
		_x('Rosa Florida', 'CASU3', 'ry-wc-city-select'),
		_x('Santa Barbara', 'CASU3', 'ry-wc-city-select'),
	],
	'CATE' => [
		_x('Ahuano', 'CATE', 'ry-wc-city-select'),
		_x('Chontapunta', 'CATE', 'ry-wc-city-select'),
		_x('Pano', 'CATE', 'ry-wc-city-select'),
		_x('Puerto Misahualli', 'CATE', 'ry-wc-city-select'),
		_x('Puerto Napo', 'CATE', 'ry-wc-city-select'),
		_x('San Juan De Muyuna', 'CATE', 'ry-wc-city-select'),
		_x('Talag', 'CATE', 'ry-wc-city-select'),
		_x('Tena', 'CATE', 'ry-wc-city-select'),
	],
	'CATU' => [
		_x('El Carmelo (El Pun)', 'CATU', 'ry-wc-city-select'),
		_x('El Chical', 'CATU', 'ry-wc-city-select'),
		_x('Julio Andrade (Orejuela)', 'CATU', 'ry-wc-city-select'),
		_x('Maldonado', 'CATU', 'ry-wc-city-select'),
		_x('Pioter', 'CATU', 'ry-wc-city-select'),
		_x('Santa Martha De Cuba', 'CATU', 'ry-wc-city-select'),
		_x('Tobar Donoso (La Bocana De Camumbi)', 'CATU', 'ry-wc-city-select'),
		_x('Tufino', 'CATU', 'ry-wc-city-select'),
		_x('Tulcan', 'CATU', 'ry-wc-city-select'),
		_x('Urbina (Taya)', 'CATU', 'ry-wc-city-select'),
	],
	'CAUR' => [
		_x('Catarama', 'CAUR', 'ry-wc-city-select'),
		_x('Ricaurte', 'CAUR', 'ry-wc-city-select'),
	],
	'CAVA' => [
		_x('Valencia', 'CAVA', 'ry-wc-city-select'),
	],
	'CAVEMA' => [
		_x('Arq. Sixto Duran Ballen', 'CAVEMA', 'ry-wc-city-select'),
		_x('Bellavista', 'CAVEMA', 'ry-wc-city-select'),
		_x('Noboa', 'CAVEMA', 'ry-wc-city-select'),
		_x('Sucre', 'CAVEMA', 'ry-wc-city-select'),
	],
	'CAVE' => [
		_x('Chacarita', 'CAVE', 'ry-wc-city-select'),
		_x('Los Angeles', 'CAVE', 'ry-wc-city-select'),
		_x('Ventanas', 'CAVE', 'ry-wc-city-select'),
		_x('Zapotal', 'CAVE', 'ry-wc-city-select'),
	],
	'CAVI' => [
		_x('Antonio Sotomayor (Cab. En Playas De Vin', 'CAVI', 'ry-wc-city-select'),
		_x('Vinces', 'CAVI', 'ry-wc-city-select'),
	],
	'CAYA' => [
		_x('28 De Mayo (San Jose De Yacuambi)', 'CAYA', 'ry-wc-city-select'),
		_x('La Paz', 'CAYA', 'ry-wc-city-select'),
		_x('Tutupali', 'CAYA', 'ry-wc-city-select'),
	],
	'CAYA2' => [
		_x('Gral. Pedro J. Montero (Boliche)', 'CAYA2', 'ry-wc-city-select'),
		_x('San Jacinto De Yaguachi', 'CAYA2', 'ry-wc-city-select'),
		_x('Virgen De Fatima', 'CAYA2', 'ry-wc-city-select'),
		_x('Yaguachi Viejo (Cone)', 'CAYA2', 'ry-wc-city-select'),
	],
	'CAYA3' => [
		_x('Chicana', 'CAYA3', 'ry-wc-city-select'),
		_x('Los Encuentros', 'CAYA3', 'ry-wc-city-select'),
		_x('Yantzaza (Yanzatza)', 'CAYA3', 'ry-wc-city-select'),
	],
	'CAZA' => [
		_x('Cumbaratza', 'CAZA', 'ry-wc-city-select'),
		_x('Guadalupe', 'CAZA', 'ry-wc-city-select'),
		_x('Imbana (La Victoria De Imbana)', 'CAZA', 'ry-wc-city-select'),
		_x('Sabanilla', 'CAZA', 'ry-wc-city-select'),
		_x('San Carlos De Las Minas', 'CAZA', 'ry-wc-city-select'),
		_x('Timbara', 'CAZA', 'ry-wc-city-select'),
		_x('Zamora', 'CAZA', 'ry-wc-city-select'),
	],
	'CAZA2' => [
		_x('Abanin', 'CAZA2', 'ry-wc-city-select'),
		_x('Arcapamba', 'CAZA2', 'ry-wc-city-select'),
		_x('Guanazan', 'CAZA2', 'ry-wc-city-select'),
		_x('Guizhaguina', 'CAZA2', 'ry-wc-city-select'),
		_x('Huertas', 'CAZA2', 'ry-wc-city-select'),
		_x('Malvas', 'CAZA2', 'ry-wc-city-select'),
		_x('Muluncay Grande', 'CAZA2', 'ry-wc-city-select'),
		_x('Salvias', 'CAZA2', 'ry-wc-city-select'),
		_x('Sinsao', 'CAZA2', 'ry-wc-city-select'),
		_x('Zaruma', 'CAZA2', 'ry-wc-city-select'),
	],
	'CAJUARTO' => [
		_x('Carlos Julio Arosemena Tola', 'CAJUARTO', 'ry-wc-city-select'),
	],
	'CA' => [
		_x('El Dorado De Cascales', 'CA', 'ry-wc-city-select'),
		_x('Santa Rosa De Sucumbios', 'CA', 'ry-wc-city-select'),
		_x('Sevilla', 'CA', 'ry-wc-city-select'),
	],
	'CEDECO' => [
		_x('Panguintza', 'CEDECO', 'ry-wc-city-select'),
		_x('Triunfo-Dorado', 'CEDECO', 'ry-wc-city-select'),
		_x('Zumbi', 'CEDECO', 'ry-wc-city-select'),
	],
	'CE' => [
		_x('Cevallos', 'CE', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Amarillos', 'CH', 'ry-wc-city-select'),
		_x('Buenavista', 'CH', 'ry-wc-city-select'),
		_x('Chaguarpamba', 'CH', 'ry-wc-city-select'),
		_x('El Rosario', 'CH', 'ry-wc-city-select'),
		_x('Santa Rufina', 'CH', 'ry-wc-city-select'),
	],
	'CH2' => [
		_x('Chambo', 'CH2', 'ry-wc-city-select'),
	],
	'CH3' => [
		_x('Chilla', 'CH3', 'ry-wc-city-select'),
	],
	'CH4' => [
		_x('Chordeleg', 'CH4', 'ry-wc-city-select'),
		_x('La Union', 'CH4', 'ry-wc-city-select'),
		_x('Luis Galarza Orellana (Cab. En Delegsol)', 'CH4', 'ry-wc-city-select'),
		_x('Principal', 'CH4', 'ry-wc-city-select'),
		_x('San Martin De Puzhio', 'CH4', 'ry-wc-city-select'),
	],
	'COMAMA' => [
		_x('Coronel Marcelino Mariduena (San Carlos)', 'COMAMA', 'ry-wc-city-select'),
	],
	'CU' => [
		_x('Cumanda', 'CU', 'ry-wc-city-select'),
	],
	'CU2' => [
		_x('Aguas Negras', 'CU2', 'ry-wc-city-select'),
		_x('Cuyabeno', 'CU2', 'ry-wc-city-select'),
		_x('Tarapoa', 'CU2', 'ry-wc-city-select'),
	],
	'DE' => [
		_x('Deleg', 'DE', 'ry-wc-city-select'),
		_x('Solano', 'DE', 'ry-wc-city-select'),
	],
	'DU' => [
		_x('Eloy Alfaro (Duran)', 'DU', 'ry-wc-city-select'),
	],
	'PA' => [
		_x('El Pan', 'PA', 'ry-wc-city-select'),
		_x('San Vicente', 'PA', 'ry-wc-city-select'),
	],
	'PA2' => [
		_x('El Guisme', 'PA2', 'ry-wc-city-select'),
		_x('El Pangui', 'PA2', 'ry-wc-city-select'),
		_x('Pachicutza', 'PA2', 'ry-wc-city-select'),
		_x('Tundayme', 'PA2', 'ry-wc-city-select'),
	],
	'TR' => [
		_x('El Triunfo', 'TR', 'ry-wc-city-select'),
	],
	'FLAL' => [
		_x('Flavio Alfaro', 'FLAL', 'ry-wc-city-select'),
		_x('San Francisco De Novillo (Cab. En Novill', 'FLAL', 'ry-wc-city-select'),
		_x('Zapallo', 'FLAL', 'ry-wc-city-select'),
	],
	'FRORCA' => [
		_x('Alejandro Labaka', 'FRORCA', 'ry-wc-city-select'),
		_x('Dayuma', 'FRORCA', 'ry-wc-city-select'),
		_x('El Dorado', 'FRORCA', 'ry-wc-city-select'),
		_x('El Eden', 'FRORCA', 'ry-wc-city-select'),
		_x('Garcia Moreno', 'FRORCA', 'ry-wc-city-select'),
		_x('Ines Arango (Cab. En Western)', 'FRORCA', 'ry-wc-city-select'),
		_x('La Belleza', 'FRORCA', 'ry-wc-city-select'),
		_x('Nuevo Paraiso (Cab. En Union )', 'FRORCA', 'ry-wc-city-select'),
		_x('Puerto Francisco De Orellana (El Coca)', 'FRORCA', 'ry-wc-city-select'),
		_x('San Jose De Guayusa', 'FRORCA', 'ry-wc-city-select'),
		_x('San Luis De Armenia', 'FRORCA', 'ry-wc-city-select'),
		_x('Taracoa (Nueva Esperanza: Yuca)', 'FRORCA', 'ry-wc-city-select'),
	],
	'GEANEL' => [
		_x('Gral. Antonio Elizalde (Bucay)', 'GEANEL', 'ry-wc-city-select'),
	],
	'GOPI' => [
		_x('El Reventador', 'GOPI', 'ry-wc-city-select'),
		_x('Gonzalo Pizarro', 'GOPI', 'ry-wc-city-select'),
		_x('Lumbaqui', 'GOPI', 'ry-wc-city-select'),
		_x('Puerto Libre', 'GOPI', 'ry-wc-city-select'),
	],
	'GU' => [
		_x('Guachapala', 'GU', 'ry-wc-city-select'),
	],
	'HU' => [
		_x('Chiguaza', 'HU', 'ry-wc-city-select'),
		_x('Huamboya', 'HU', 'ry-wc-city-select'),
	],
	'IB' => [
		_x('Ambuqui', 'IB', 'ry-wc-city-select'),
		_x('Angochagua', 'IB', 'ry-wc-city-select'),
		_x('Carolina', 'IB', 'ry-wc-city-select'),
		_x('La Esperanza', 'IB', 'ry-wc-city-select'),
		_x('Lita', 'IB', 'ry-wc-city-select'),
		_x('Salinas', 'IB', 'ry-wc-city-select'),
		_x('San Antonio', 'IB', 'ry-wc-city-select'),
		_x('San Miguel De Ibarra', 'IB', 'ry-wc-city-select'),
	],
	'ISAY' => [
		_x('Isidro Ayora', 'ISAY', 'ry-wc-city-select'),
	],
	'JA' => [
		_x('Jama', 'JA', 'ry-wc-city-select'),
	],
	'JA2' => [
		_x('Jaramijo', 'JA2', 'ry-wc-city-select'),
	],
	'CO' => [
		_x('La Concordia', 'CO', 'ry-wc-city-select'),
		_x('La Villegas', 'CO', 'ry-wc-city-select'),
		_x('Monterrey', 'CO', 'ry-wc-city-select'),
		_x('Plan Piloto', 'CO', 'ry-wc-city-select'),
	],
	'JOLOSA' => [
		_x('Enokanqui', 'JOLOSA', 'ry-wc-city-select'),
		_x('La Joya De Los Sachas', 'JOLOSA', 'ry-wc-city-select'),
		_x('Lago San Pedro', 'JOLOSA', 'ry-wc-city-select'),
		_x('Pompeya', 'JOLOSA', 'ry-wc-city-select'),
		_x('Rumipamba', 'JOLOSA', 'ry-wc-city-select'),
		_x('San Carlos', 'JOLOSA', 'ry-wc-city-select'),
		_x('San Sebastian Del Coca', 'JOLOSA', 'ry-wc-city-select'),
		_x('Tres De Noviembre', 'JOLOSA', 'ry-wc-city-select'),
		_x('Union Milagrena', 'JOLOSA', 'ry-wc-city-select'),
	],
	'LI' => [
		_x('La Libertad', 'LI', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Guasaganda (Cab. En Guasaganda Centro)', 'MA', 'ry-wc-city-select'),
		_x('La Mana', 'MA', 'ry-wc-city-select'),
		_x('Pucayacu', 'MA', 'ry-wc-city-select'),
	],
	'TR2' => [
		_x('La Troncal', 'TR2', 'ry-wc-city-select'),
		_x('Manuel J. Calle', 'TR2', 'ry-wc-city-select'),
		_x('Pancho Negro', 'TR2', 'ry-wc-city-select'),
	],
	'LALA' => [
		_x('El Paraiso', 'LALA', 'ry-wc-city-select'),
		_x('La Libertad', 'LALA', 'ry-wc-city-select'),
		_x('La Victoria', 'LALA', 'ry-wc-city-select'),
		_x('San Isidro', 'LALA', 'ry-wc-city-select'),
	],
	'LO' => [
		_x('Logrono', 'LO', 'ry-wc-city-select'),
		_x('Shimpis', 'LO', 'ry-wc-city-select'),
		_x('Yaupi', 'LO', 'ry-wc-city-select'),
	],
	'LOSA' => [
		_x('Lomas De Sargentillo', 'LOSA', 'ry-wc-city-select'),
	],
	'LOCA' => [
		_x('Avila (Cab. En Huiruno)', 'LOCA', 'ry-wc-city-select'),
		_x('Loreto', 'LOCA', 'ry-wc-city-select'),
		_x('Puerto Murialdo', 'LOCA', 'ry-wc-city-select'),
		_x('San Jose De Dahuano', 'LOCA', 'ry-wc-city-select'),
		_x('San Jose De Payamino', 'LOCA', 'ry-wc-city-select'),
		_x('San Vicente De Huaticocha', 'LOCA', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('El Ingenio', 'MA2', 'ry-wc-city-select'),
		_x('Marcabeli', 'MA2', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Mocache', 'MO', 'ry-wc-city-select'),
	],
	'MO2' => [
		_x('Mocha', 'MO2', 'ry-wc-city-select'),
		_x('Pinguili', 'MO2', 'ry-wc-city-select'),
	],
	'MO3' => [
		_x('La Esmeralda', 'MO3', 'ry-wc-city-select'),
		_x('Montalvo', 'MO3', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Guayzimi', 'NA', 'ry-wc-city-select'),
		_x('Nuevo Paraiso', 'NA', 'ry-wc-city-select'),
		_x('Zurmi', 'NA', 'ry-wc-city-select'),
	],
	'NO' => [
		_x('Narcisa De Jesus', 'NO', 'ry-wc-city-select'),
	],
	'OL' => [
		_x('Olmedo', 'OL', 'ry-wc-city-select'),
	],
	'ON' => [
		_x('San Felipe De Ona', 'ON', 'ry-wc-city-select'),
		_x('Susudel', 'ON', 'ry-wc-city-select'),
	],
	'PASE' => [
		_x('Pablo Sexto', 'PASE', 'ry-wc-city-select'),
	],
	'PA3' => [
		_x('El Porvenir Del Carmen', 'PA3', 'ry-wc-city-select'),
		_x('La Canela', 'PA3', 'ry-wc-city-select'),
		_x('Palanda', 'PA3', 'ry-wc-city-select'),
		_x('San Francisco Del Vergel', 'PA3', 'ry-wc-city-select'),
		_x('Valladolid', 'PA3', 'ry-wc-city-select'),
	],
	'PA4' => [
		_x('Palenque', 'PA4', 'ry-wc-city-select'),
	],
	'PA5' => [
		_x('Palestina', 'PA5', 'ry-wc-city-select'),
	],
	'PA6' => [
		_x('Pallatanga', 'PA6', 'ry-wc-city-select'),
	],
	'PA7' => [
		_x('Bellavista', 'PA7', 'ry-wc-city-select'),
		_x('Nuevo Quito', 'PA7', 'ry-wc-city-select'),
		_x('Paquisha', 'PA7', 'ry-wc-city-select'),
	],
	'PECA' => [
		_x('Pedro Carbo', 'PECA', 'ry-wc-city-select'),
		_x('Sabanilla', 'PECA', 'ry-wc-city-select'),
		_x('Valle De La Virgen', 'PECA', 'ry-wc-city-select'),
	],
	'PE' => [
		_x('Bilbao (Cab. En Quilluyacu)', 'PE', 'ry-wc-city-select'),
		_x('El Altar', 'PE', 'ry-wc-city-select'),
		_x('La Candelaria', 'PE', 'ry-wc-city-select'),
		_x('Matus', 'PE', 'ry-wc-city-select'),
		_x('Penipe', 'PE', 'ry-wc-city-select'),
		_x('Puela', 'PE', 'ry-wc-city-select'),
		_x('San Antonio De Bayushig', 'PE', 'ry-wc-city-select'),
	],
	'PI' => [
		_x('Barraganete', 'PI', 'ry-wc-city-select'),
		_x('Pichincha', 'PI', 'ry-wc-city-select'),
		_x('San Sebastian', 'PI', 'ry-wc-city-select'),
	],
	'PI2' => [
		_x('12 De Diciembre (Cab. En Achiotes)', 'PI2', 'ry-wc-city-select'),
		_x('Chaquinal', 'PI2', 'ry-wc-city-select'),
		_x('Milagros', 'PI2', 'ry-wc-city-select'),
		_x('Pindal', 'PI2', 'ry-wc-city-select'),
	],
	'PL' => [
		_x('General Villamil (Playas)', 'PL', 'ry-wc-city-select'),
	],
	'PU' => [
		_x('Pucara', 'PU', 'ry-wc-city-select'),
		_x('San Rafael De Sharug', 'PU', 'ry-wc-city-select'),
	],
	'PULO' => [
		_x('Machalilla', 'PULO', 'ry-wc-city-select'),
		_x('Puerto Lopez', 'PULO', 'ry-wc-city-select'),
		_x('Salango', 'PULO', 'ry-wc-city-select'),
	],
	'PUQU' => [
		_x('Puerto Quito', 'PUQU', 'ry-wc-city-select'),
	],
	'QU' => [
		_x('Fundochamba', 'QU', 'ry-wc-city-select'),
		_x('Quilanga', 'QU', 'ry-wc-city-select'),
		_x('San Antonio De Las Aradas (Cab. En Las A', 'QU', 'ry-wc-city-select'),
	],
	'QU2' => [
		_x('Quinsaloma', 'QU2', 'ry-wc-city-select'),
	],
	'RIVE' => [
		_x('Chontaduro', 'RIVE', 'ry-wc-city-select'),
		_x('Chumunde', 'RIVE', 'ry-wc-city-select'),
		_x('Lagarto', 'RIVE', 'ry-wc-city-select'),
		_x('Montalvo (Cab En Horqueta)', 'RIVE', 'ry-wc-city-select'),
		_x('Rioverde', 'RIVE', 'ry-wc-city-select'),
		_x('Rocafuerte', 'RIVE', 'ry-wc-city-select'),
	],
	'SAJUBO' => [
		_x('Pan De Azucar', 'SAJUBO', 'ry-wc-city-select'),
		_x('San Carlos De Limon', 'SAJUBO', 'ry-wc-city-select'),
		_x('San Jacinto De Wakambeis', 'SAJUBO', 'ry-wc-city-select'),
		_x('San Juan Bosco', 'SAJUBO', 'ry-wc-city-select'),
		_x('Santiago De Pananza', 'SAJUBO', 'ry-wc-city-select'),
	],
	'SAMILOBA' => [
		_x('Mindo', 'SAMILOBA', 'ry-wc-city-select'),
		_x('San Miguel De Los Bancos', 'SAMILOBA', 'ry-wc-city-select'),
	],
	'SAMIURCA' => [
		_x('Cahuasqui', 'SAMIURCA', 'ry-wc-city-select'),
		_x('La Merced De Buenos Aires', 'SAMIURCA', 'ry-wc-city-select'),
		_x('Pablo Arenas', 'SAMIURCA', 'ry-wc-city-select'),
		_x('San Blas', 'SAMIURCA', 'ry-wc-city-select'),
		_x('Tumbabiro', 'SAMIURCA', 'ry-wc-city-select'),
		_x('Urcuqui', 'SAMIURCA', 'ry-wc-city-select'),
	],
	'SAPEHU' => [
		_x('Huaca', 'SAPEHU', 'ry-wc-city-select'),
		_x('Mariscal Sucre', 'SAPEHU', 'ry-wc-city-select'),
	],
	'SAVI' => [
		_x('Canoa', 'SAVI', 'ry-wc-city-select'),
		_x('San Vicente', 'SAVI', 'ry-wc-city-select'),
	],
	'SACL' => [
		_x('San Jose', 'SACL', 'ry-wc-city-select'),
		_x('Santa Clara', 'SACL', 'ry-wc-city-select'),
	],
	'SALU' => [
		_x('Santa Lucia', 'SALU', 'ry-wc-city-select'),
	],
	'SAME' => [
		_x('Chupianza', 'SAME', 'ry-wc-city-select'),
		_x('Copal', 'SAME', 'ry-wc-city-select'),
		_x('Patuca', 'SAME', 'ry-wc-city-select'),
		_x('San Francisco De Chinimbimi', 'SAME', 'ry-wc-city-select'),
		_x('San Luis De El Acho (Cab En El Acho)', 'SAME', 'ry-wc-city-select'),
		_x('Santiago De Mendez', 'SAME', 'ry-wc-city-select'),
		_x('Tayuza', 'SAME', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Canchagua', 'SA', 'ry-wc-city-select'),
		_x('Chantilin', 'SA', 'ry-wc-city-select'),
		_x('Cochapamba', 'SA', 'ry-wc-city-select'),
		_x('Saquisili', 'SA', 'ry-wc-city-select'),
	],
	'SEOR' => [
		_x('Amaluza', 'SEOR', 'ry-wc-city-select'),
		_x('Palmas', 'SEOR', 'ry-wc-city-select'),
		_x('Sevilla De Oro', 'SEOR', 'ry-wc-city-select'),
	],
	'SH' => [
		_x('Limoncocha', 'SH', 'ry-wc-city-select'),
		_x('Panacocha', 'SH', 'ry-wc-city-select'),
		_x('San Pedro De Los Cofanes', 'SH', 'ry-wc-city-select'),
		_x('San Roque (Cab. En San Vicente)', 'SH', 'ry-wc-city-select'),
		_x('Shushufindi', 'SH', 'ry-wc-city-select'),
		_x('Siete De Julio', 'SH', 'ry-wc-city-select'),
	],
	'SIBO' => [
		_x('Crnel. Lorenzo De Garaicoa (Pedregal)', 'SIBO', 'ry-wc-city-select'),
		_x('Simon Bolivar', 'SIBO', 'ry-wc-city-select'),
	],
	'SU' => [
		_x('Suscal', 'SU', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Huasaga (Cab En Wampuik)', 'TA', 'ry-wc-city-select'),
		_x('Macuma', 'TA', 'ry-wc-city-select'),
		_x('Pumpuentsa', 'TA', 'ry-wc-city-select'),
		_x('Taisha', 'TA', 'ry-wc-city-select'),
		_x('Tuutinentza', 'TA', 'ry-wc-city-select'),
	],
	'TI' => [
		_x('Quinchicoto', 'TI', 'ry-wc-city-select'),
		_x('Tisaleo', 'TI', 'ry-wc-city-select'),
	],
	'TI2' => [
		_x('San Jose De Morona', 'TI2', 'ry-wc-city-select'),
		_x('Santiago', 'TI2', 'ry-wc-city-select'),
	],
	'TO' => [
		_x('Angel Pedro Giler (La Estancilla)', 'TO', 'ry-wc-city-select'),
		_x('Bachillero', 'TO', 'ry-wc-city-select'),
		_x('Tosagua', 'TO', 'ry-wc-city-select'),
	],
	'ZA' => [
		_x('Bolaspamba', 'ZA', 'ry-wc-city-select'),
		_x('Cazaderos', 'ZA', 'ry-wc-city-select'),
		_x('Garzareal', 'ZA', 'ry-wc-city-select'),
		_x('Limones', 'ZA', 'ry-wc-city-select'),
		_x('Mangahurco (Cazaderos)', 'ZA', 'ry-wc-city-select'),
		_x('Paletillas', 'ZA', 'ry-wc-city-select'),
		_x('Zapotillo', 'ZA', 'ry-wc-city-select'),
	],
	]
];