<?php
/**
 * Arab Republic of Egypt places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'EG' => [
	'BEGO' => [
		_x('Markaz Abu Hummus', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz Abu al Matamir', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz Damanhur', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz Hawsh `Isa', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz Idku', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz Itay al Barud', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz Kafr ad Dawwar', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz Rashid', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz ad Dilinjat', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz al Mahmudiyah', 'BEGO', 'ry-wc-city-select'),
		_x('Markaz ar Rahmaniyah', 'BEGO', 'ry-wc-city-select'),
	],
	'CAGO' => [
		_x('Al Marj', 'CAGO', 'ry-wc-city-select'),
		_x('Markaz al Khankah', 'CAGO', 'ry-wc-city-select'),
		_x('Markaz as Saff', 'CAGO', 'ry-wc-city-select'),
		_x('Mostafa El Serwy', 'CAGO', 'ry-wc-city-select'),
	],
	'DAGO' => [
		_x('Markaz Fariskur', 'DAGO', 'ry-wc-city-select'),
		_x('Markaz Kafr Sa`d', 'DAGO', 'ry-wc-city-select'),
		_x('Markaz az Zarqa', 'DAGO', 'ry-wc-city-select'),
	],
	'ISGO' => [
		_x('Markaz Fayid', 'ISGO', 'ry-wc-city-select'),
		_x('Markaz al Isma`iliyah', 'ISGO', 'ry-wc-city-select'),
		_x('Markaz al Qantarah Gharb', 'ISGO', 'ry-wc-city-select'),
		_x('Markaz al Qantarah Sharq', 'ISGO', 'ry-wc-city-select'),
	],
	'KAASSH' => [
		_x('Kafr El Sheikh', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz Biyala', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz Disuq', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz Fuwwah', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz Kafr ash Shaykh', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz Mutubas', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz Qallin', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz Sidi Salim', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz al Burullus', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz al Hamul', 'KAASSH', 'ry-wc-city-select'),
		_x('Markaz ar Riyad', 'KAASSH', 'ry-wc-city-select'),
	],
	'MUAS' => [
		_x('Markaz Aswan', 'MUAS', 'ry-wc-city-select'),
		_x('Markaz Idfu', 'MUAS', 'ry-wc-city-select'),
		_x('Markaz `Unaybah', 'MUAS', 'ry-wc-city-select'),
	],
	'MUAS2' => [
		_x('Markaz Abu Tij', 'MUAS2', 'ry-wc-city-select'),
		_x('Markaz Asyut', 'MUAS2', 'ry-wc-city-select'),
		_x('Markaz Dayrut', 'MUAS2', 'ry-wc-city-select'),
		_x('Markaz al Badari', 'MUAS2', 'ry-wc-city-select'),
		_x('Markaz al Fath', 'MUAS2', 'ry-wc-city-select'),
		_x('Markaz al Ghanayim', 'MUAS2', 'ry-wc-city-select'),
		_x('Markaz al Qusiyah', 'MUAS2', 'ry-wc-city-select'),
		_x('Markaz as Sahil', 'MUAS2', 'ry-wc-city-select'),
	],
	'MUBASU' => [
		_x('Markaz Bani Suwayf', 'MUBASU', 'ry-wc-city-select'),
		_x('Markaz Biba', 'MUBASU', 'ry-wc-city-select'),
		_x('Markaz Bush', 'MUBASU', 'ry-wc-city-select'),
		_x('Markaz Ihnasiya al Madinah', 'MUBASU', 'ry-wc-city-select'),
		_x('Markaz Nasir', 'MUBASU', 'ry-wc-city-select'),
		_x('Markaz Sumusta al Waqf', 'MUBASU', 'ry-wc-city-select'),
		_x('Markaz al Fashn', 'MUBASU', 'ry-wc-city-select'),
		_x('Markaz al Wasita', 'MUBASU', 'ry-wc-city-select'),
	],
	'MUMA' => [
		_x('Markaz Matruh', 'MUMA', 'ry-wc-city-select'),
	],
	'MUQI' => [
		_x('Markaz Abu Tisht', 'MUQI', 'ry-wc-city-select'),
		_x('Markaz Armant', 'MUQI', 'ry-wc-city-select'),
		_x('Markaz Dishna', 'MUQI', 'ry-wc-city-select'),
		_x('Markaz Isna', 'MUQI', 'ry-wc-city-select'),
		_x('Markaz Naj Hammadi', 'MUQI', 'ry-wc-city-select'),
		_x('Markaz Qina', 'MUQI', 'ry-wc-city-select'),
	],
	'MUSHSI' => [
		_x('Markaz Bir al `Abd', 'MUSHSI', 'ry-wc-city-select'),
		_x('Markaz Rafah', 'MUSHSI', 'ry-wc-city-select'),
		_x('Markaz al `Arish', 'MUSHSI', 'ry-wc-city-select'),
		_x('Markaz ash Shaykh Zuwayd', 'MUSHSI', 'ry-wc-city-select'),
	],
	'MUSU' => [
		_x('Markaz Akhmim', 'MUSU', 'ry-wc-city-select'),
		_x('Markaz Awlad Tawq Sharq', 'MUSU', 'ry-wc-city-select'),
		_x('Markaz Dar as Salam', 'MUSU', 'ry-wc-city-select'),
		_x('Markaz Jirja', 'MUSU', 'ry-wc-city-select'),
		_x('Markaz Juhaynah al Gharbiyah', 'MUSU', 'ry-wc-city-select'),
		_x('Markaz Suhaj', 'MUSU', 'ry-wc-city-select'),
		_x('Markaz al Balyana', 'MUSU', 'ry-wc-city-select'),
		_x('Markaz al Maraghah', 'MUSU', 'ry-wc-city-select'),
		_x('Markaz al Munshaah', 'MUSU', 'ry-wc-city-select'),
	],
	'MUDA' => [
		_x('Bahr El Bakr', 'MUDA', 'ry-wc-city-select'),
		_x('Markaz Aja', 'MUDA', 'ry-wc-city-select'),
		_x('Markaz Bilqas', 'MUDA', 'ry-wc-city-select'),
		_x('Markaz Dikirnis', 'MUDA', 'ry-wc-city-select'),
		_x('Markaz Minyat An Nasr', 'MUDA', 'ry-wc-city-select'),
		_x('Markaz Mit Ghamr', 'MUDA', 'ry-wc-city-select'),
		_x('Markaz al Mansurah', 'MUDA', 'ry-wc-city-select'),
		_x('Markaz al Manzilah', 'MUDA', 'ry-wc-city-select'),
		_x('Mit Yazid', 'MUDA', 'ry-wc-city-select'),
	],
	'MUFA' => [
		_x('Markaz Ibshaway', 'MUFA', 'ry-wc-city-select'),
		_x('Markaz Itsa', 'MUFA', 'ry-wc-city-select'),
		_x('Markaz Tamiyah', 'MUFA', 'ry-wc-city-select'),
		_x('Markaz al Fayyum', 'MUFA', 'ry-wc-city-select'),
	],
	'MUGH' => [
		_x('Markaz Basyun', 'MUGH', 'ry-wc-city-select'),
		_x('Markaz Qutur', 'MUGH', 'ry-wc-city-select'),
		_x('Markaz Sammanud', 'MUGH', 'ry-wc-city-select'),
		_x('Markaz Tanta', 'MUGH', 'ry-wc-city-select'),
		_x('Markaz Zifta', 'MUGH', 'ry-wc-city-select'),
		_x('Markaz al Mahallah al Kubra', 'MUGH', 'ry-wc-city-select'),
		_x('Markaz as Santah', 'MUGH', 'ry-wc-city-select'),
	],
	'MUIS' => [
		_x('Al Muntazah', 'MUIS', 'ry-wc-city-select'),
		_x('Markaz Maryut', 'MUIS', 'ry-wc-city-select'),
	],
	'MUJI' => [
		_x('Markaz Awsim', 'MUJI', 'ry-wc-city-select'),
		_x('Markaz Imbabah', 'MUJI', 'ry-wc-city-select'),
		_x('Markaz al Badrashayn', 'MUJI', 'ry-wc-city-select'),
		_x('Markaz al Jizah', 'MUJI', 'ry-wc-city-select'),
		_x('Markaz al Wahat al Bahriyah', 'MUJI', 'ry-wc-city-select'),
		_x('Markaz al `Ayyat', 'MUJI', 'ry-wc-city-select'),
		_x('Walikale', 'MUJI', 'ry-wc-city-select'),
	],
	'MUMI' => [
		_x('Markaz Ashmun', 'MUMI', 'ry-wc-city-select'),
		_x('Markaz Birkat as Sab`', 'MUMI', 'ry-wc-city-select'),
		_x('Markaz Quwaysina', 'MUMI', 'ry-wc-city-select'),
		_x('Markaz al Bajur', 'MUMI', 'ry-wc-city-select'),
		_x('Markaz ash Shuhada', 'MUMI', 'ry-wc-city-select'),
	],
	'MUMI2' => [
		_x('Markaz Bani Mazar', 'MUMI2', 'ry-wc-city-select'),
		_x('Markaz Dayr Mawas', 'MUMI2', 'ry-wc-city-select'),
		_x('Markaz Mallawi', 'MUMI2', 'ry-wc-city-select'),
		_x('Markaz Matay', 'MUMI2', 'ry-wc-city-select'),
		_x('Markaz Qurqas', 'MUMI2', 'ry-wc-city-select'),
		_x('Markaz Samalut', 'MUMI2', 'ry-wc-city-select'),
		_x('Markaz al Minya', 'MUMI2', 'ry-wc-city-select'),
		_x('Markaz al `Idwah', 'MUMI2', 'ry-wc-city-select'),
	],
	'MUQA' => [
		_x('Markaz Banha', 'MUQA', 'ry-wc-city-select'),
		_x('Markaz Kafr Shukr', 'MUQA', 'ry-wc-city-select'),
		_x('Markaz Qalyub', 'MUQA', 'ry-wc-city-select'),
		_x('Mostorod', 'MUQA', 'ry-wc-city-select'),
	],
	'MUUQ' => [
		_x('Markaz al Uqsur', 'MUUQ', 'ry-wc-city-select'),
	],
	'MUWAJA' => [
		_x('Baris Shurtah', 'MUWAJA', 'ry-wc-city-select'),
		_x('Markaz al Wahat ad Dakhilah', 'MUWAJA', 'ry-wc-city-select'),
		_x('Markaz al Wahat al Kharijah', 'MUWAJA', 'ry-wc-city-select'),
		_x('Shurtah al-Farafirah', 'MUWAJA', 'ry-wc-city-select'),
	],
	'MUASSH' => [
		_x('Bahr El Bakar', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz Abu Hammad', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz Abu Kabir', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz Bilbays', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz Diyarb Najm', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz Hihya', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz Minya al Qamh', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz al Husayniyah', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz at Tall al Kabir', 'MUASSH', 'ry-wc-city-select'),
		_x('Markaz az Zaqaziq', 'MUASSH', 'ry-wc-city-select'),
	],
	'SOSIGO' => [
		_x('Markaz Atfih', 'SOSIGO', 'ry-wc-city-select'),
	],
	]
];