<?php
/**
 * Republic of Finland places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'FI' => [
	'AE' => [
		_x('Enekoski', 'AE', 'ry-wc-city-select'),
		_x('Konnevesi', 'AE', 'ry-wc-city-select'),
	],
	'AB' => [
		_x('Kimitooen', 'AB', 'ry-wc-city-select'),
		_x('Pargas', 'AB', 'ry-wc-city-select'),
	],
	'ET' => [
		_x('Akaa', 'ET', 'ry-wc-city-select'),
		_x('Urjala', 'ET', 'ry-wc-city-select'),
		_x('Valkeakoski', 'ET', 'ry-wc-city-select'),
	],
	'FO' => [
		_x('Forssa', 'FO', 'ry-wc-city-select'),
		_x('Humppila', 'FO', 'ry-wc-city-select'),
		_x('Jokioinen', 'FO', 'ry-wc-city-select'),
		_x('Tammela', 'FO', 'ry-wc-city-select'),
		_x('Ypaejae', 'FO', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Haapavesi', 'HA', 'ry-wc-city-select'),
		_x('Pyhaentae', 'HA', 'ry-wc-city-select'),
		_x('Siikalatva', 'HA', 'ry-wc-city-select'),
	],
	'HA2' => [
		_x('Haemeenlinna', 'HA2', 'ry-wc-city-select'),
		_x('Hattula', 'HA2', 'ry-wc-city-select'),
		_x('Janakkala', 'HA2', 'ry-wc-city-select'),
	],
	'HE' => [
		_x('Espoo', 'HE', 'ry-wc-city-select'),
		_x('Helsinki', 'HE', 'ry-wc-city-select'),
		_x('Hyvinkaeae', 'HE', 'ry-wc-city-select'),
		_x('Jaervenpaeae', 'HE', 'ry-wc-city-select'),
		_x('Karkkila', 'HE', 'ry-wc-city-select'),
		_x('Kauniainen', 'HE', 'ry-wc-city-select'),
		_x('Kerava', 'HE', 'ry-wc-city-select'),
		_x('Kirkkonummi', 'HE', 'ry-wc-city-select'),
		_x('Lohja', 'HE', 'ry-wc-city-select'),
		_x('Maentsaelae', 'HE', 'ry-wc-city-select'),
		_x('Nurmijaervi', 'HE', 'ry-wc-city-select'),
		_x('Pornainen', 'HE', 'ry-wc-city-select'),
		_x('Sipoo', 'HE', 'ry-wc-city-select'),
		_x('Siuntio', 'HE', 'ry-wc-city-select'),
		_x('Tuusula', 'HE', 'ry-wc-city-select'),
		_x('Vantaa', 'HE', 'ry-wc-city-select'),
		_x('Vihti', 'HE', 'ry-wc-city-select'),
	],
	'IM' => [
		_x('Imatra', 'IM', 'ry-wc-city-select'),
		_x('Parikkala', 'IM', 'ry-wc-city-select'),
		_x('Rautjaervi', 'IM', 'ry-wc-city-select'),
		_x('Ruokolahti', 'IM', 'ry-wc-city-select'),
	],
	'IT' => [
		_x('Kemijaervi', 'IT', 'ry-wc-city-select'),
		_x('Pelkosenniemi', 'IT', 'ry-wc-city-select'),
		_x('Posio', 'IT', 'ry-wc-city-select'),
		_x('Salla', 'IT', 'ry-wc-city-select'),
		_x('Savukoski', 'IT', 'ry-wc-city-select'),
	],
	'JA' => [
		_x('Jaemsae', 'JA', 'ry-wc-city-select'),
		_x('Kuhmoinen', 'JA', 'ry-wc-city-select'),
	],
	'JA2' => [
		_x('Alajaervi', 'JA2', 'ry-wc-city-select'),
		_x('Evijaervi', 'JA2', 'ry-wc-city-select'),
		_x('Lappajaervi', 'JA2', 'ry-wc-city-select'),
		_x('Soini', 'JA2', 'ry-wc-city-select'),
		_x('Vimpeli', 'JA2', 'ry-wc-city-select'),
	],
	'JA3' => [
		_x('Jakobstad', 'JA3', 'ry-wc-city-select'),
		_x('Kronoby', 'JA3', 'ry-wc-city-select'),
		_x('Larsmo', 'JA3', 'ry-wc-city-select'),
		_x('Nykarleby', 'JA3', 'ry-wc-city-select'),
		_x('Pedersoere', 'JA3', 'ry-wc-city-select'),
	],
	'JO' => [
		_x('Ilomantsi', 'JO', 'ry-wc-city-select'),
		_x('Joensuu', 'JO', 'ry-wc-city-select'),
		_x('Juuka', 'JO', 'ry-wc-city-select'),
		_x('Kontiolahti', 'JO', 'ry-wc-city-select'),
		_x('Liperi', 'JO', 'ry-wc-city-select'),
		_x('Outokumpu', 'JO', 'ry-wc-city-select'),
		_x('Polvijaervi', 'JO', 'ry-wc-city-select'),
	],
	'JO2' => [
		_x('Joutsa', 'JO2', 'ry-wc-city-select'),
		_x('Luhanka', 'JO2', 'ry-wc-city-select'),
	],
	'JY' => [
		_x('Hankasalmi', 'JY', 'ry-wc-city-select'),
		_x('Jyvaeskylae', 'JY', 'ry-wc-city-select'),
		_x('Laukaa', 'JY', 'ry-wc-city-select'),
		_x('Muurame', 'JY', 'ry-wc-city-select'),
		_x('Petaejaevesi', 'JY', 'ry-wc-city-select'),
		_x('Toivakka', 'JY', 'ry-wc-city-select'),
		_x('Uurainen', 'JY', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Kajaani', 'KA', 'ry-wc-city-select'),
		_x('Paltamo', 'KA', 'ry-wc-city-select'),
		_x('Ristijaervi', 'KA', 'ry-wc-city-select'),
		_x('Sotkamo', 'KA', 'ry-wc-city-select'),
		_x('Vaala', 'KA', 'ry-wc-city-select'),
	],
	'KA2' => [
		_x('Halsua', 'KA2', 'ry-wc-city-select'),
		_x('Kaustinen', 'KA2', 'ry-wc-city-select'),
		_x('Lestijaervi', 'KA2', 'ry-wc-city-select'),
		_x('Perho', 'KA2', 'ry-wc-city-select'),
		_x('Toholampi', 'KA2', 'ry-wc-city-select'),
		_x('Veteli', 'KA2', 'ry-wc-city-select'),
	],
	'KE' => [
		_x('Hyrynsalmi', 'KE', 'ry-wc-city-select'),
		_x('Kuhmo', 'KE', 'ry-wc-city-select'),
		_x('Puolanka', 'KE', 'ry-wc-city-select'),
		_x('Suomussalmi', 'KE', 'ry-wc-city-select'),
	],
	'KE2' => [
		_x('Kemi', 'KE2', 'ry-wc-city-select'),
		_x('Keminmaa', 'KE2', 'ry-wc-city-select'),
		_x('Simo', 'KE2', 'ry-wc-city-select'),
		_x('Tervola', 'KE2', 'ry-wc-city-select'),
		_x('Tornio', 'KE2', 'ry-wc-city-select'),
	],
	'KE3' => [
		_x('Kitee', 'KE3', 'ry-wc-city-select'),
		_x('Raeaekkylae', 'KE3', 'ry-wc-city-select'),
		_x('Tohmajaervi', 'KE3', 'ry-wc-city-select'),
	],
	'KE4' => [
		_x('Keuruu', 'KE4', 'ry-wc-city-select'),
		_x('Multia', 'KE4', 'ry-wc-city-select'),
	],
	'KO' => [
		_x('Kaavi', 'KO', 'ry-wc-city-select'),
		_x('Rautavaara', 'KO', 'ry-wc-city-select'),
		_x('Tuusniemi', 'KO', 'ry-wc-city-select'),
	],
	'KO2' => [
		_x('Kuusamo', 'KO2', 'ry-wc-city-select'),
		_x('Taivalkoski', 'KO2', 'ry-wc-city-select'),
	],
	'KO3' => [
		_x('Kannus', 'KO3', 'ry-wc-city-select'),
		_x('Kokkola', 'KO3', 'ry-wc-city-select'),
	],
	'KO4' => [
		_x('Hamina', 'KO4', 'ry-wc-city-select'),
		_x('Kotka', 'KO4', 'ry-wc-city-select'),
		_x('Miehikkaelae', 'KO4', 'ry-wc-city-select'),
		_x('Pyttis', 'KO4', 'ry-wc-city-select'),
		_x('Virolahti', 'KO4', 'ry-wc-city-select'),
	],
	'KO5' => [
		_x('Iitti', 'KO5', 'ry-wc-city-select'),
		_x('Kouvola', 'KO5', 'ry-wc-city-select'),
	],
	'KU' => [
		_x('Kuopio', 'KU', 'ry-wc-city-select'),
		_x('Siilinjaervi', 'KU', 'ry-wc-city-select'),
	],
	'KU2' => [
		_x('AEhtaeri', 'KU2', 'ry-wc-city-select'),
		_x('Alavus', 'KU2', 'ry-wc-city-select'),
		_x('Kuortane', 'KU2', 'ry-wc-city-select'),
	],
	'KY' => [
		_x('Isokyroe', 'KY', 'ry-wc-city-select'),
		_x('Laihia', 'KY', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Asikkala', 'LA', 'ry-wc-city-select'),
		_x('Hartola', 'LA', 'ry-wc-city-select'),
		_x('Heinola', 'LA', 'ry-wc-city-select'),
		_x('Hollola', 'LA', 'ry-wc-city-select'),
		_x('Kaerkoelae', 'LA', 'ry-wc-city-select'),
		_x('Lahti', 'LA', 'ry-wc-city-select'),
		_x('Orimattila', 'LA', 'ry-wc-city-select'),
		_x('Padasjoki', 'LA', 'ry-wc-city-select'),
		_x('Sysmae', 'LA', 'ry-wc-city-select'),
	],
	'LA2' => [
		_x('Lappeenranta', 'LA2', 'ry-wc-city-select'),
		_x('Lemi', 'LA2', 'ry-wc-city-select'),
		_x('Luumaeki', 'LA2', 'ry-wc-city-select'),
		_x('Savitaipale', 'LA2', 'ry-wc-city-select'),
		_x('Taipalsaari', 'LA2', 'ry-wc-city-select'),
	],
	'LO' => [
		_x('Aura', 'LO', 'ry-wc-city-select'),
		_x('Koski Tl', 'LO', 'ry-wc-city-select'),
		_x('Loimaa', 'LO', 'ry-wc-city-select'),
		_x('Marttila', 'LO', 'ry-wc-city-select'),
		_x('Oripaeae', 'LO', 'ry-wc-city-select'),
		_x('Poeytyae', 'LO', 'ry-wc-city-select'),
	],
	'LO2' => [
		_x('Punkalaidun', 'LO2', 'ry-wc-city-select'),
		_x('Sastamala', 'LO2', 'ry-wc-city-select'),
	],
	'LO3' => [
		_x('Lapptraesk', 'LO3', 'ry-wc-city-select'),
		_x('Loviisa', 'LO3', 'ry-wc-city-select'),
	],
	'LU' => [
		_x('Ikaalinen', 'LU', 'ry-wc-city-select'),
		_x('Kihnioe', 'LU', 'ry-wc-city-select'),
		_x('Parkano', 'LU', 'ry-wc-city-select'),
	],
	'MI' => [
		_x('Hirvensalmi', 'MI', 'ry-wc-city-select'),
		_x('Kangasniemi', 'MI', 'ry-wc-city-select'),
		_x('Maentyharju', 'MI', 'ry-wc-city-select'),
		_x('Mikkeli', 'MI', 'ry-wc-city-select'),
		_x('Pertunmaa', 'MI', 'ry-wc-city-select'),
		_x('Puumala', 'MI', 'ry-wc-city-select'),
	],
	'NI' => [
		_x('Haapajaervi', 'NI', 'ry-wc-city-select'),
		_x('Kaersaemaeki', 'NI', 'ry-wc-city-select'),
		_x('Nivala', 'NI', 'ry-wc-city-select'),
		_x('Pyhaejaervi', 'NI', 'ry-wc-city-select'),
		_x('Reisjaervi', 'NI', 'ry-wc-city-select'),
	],
	'OU' => [
		_x('Hailuoto', 'OU', 'ry-wc-city-select'),
		_x('Kempele', 'OU', 'ry-wc-city-select'),
		_x('Liminka', 'OU', 'ry-wc-city-select'),
		_x('Lumijoki', 'OU', 'ry-wc-city-select'),
		_x('Muhos', 'OU', 'ry-wc-city-select'),
		_x('Oulu', 'OU', 'ry-wc-city-select'),
		_x('Tyrnaevae', 'OU', 'ry-wc-city-select'),
	],
	'OU2' => [
		_x('Ii', 'OU2', 'ry-wc-city-select'),
		_x('Pudasjaervi', 'OU2', 'ry-wc-city-select'),
		_x('Utajaervi', 'OU2', 'ry-wc-city-select'),
	],
	'PI' => [
		_x('Joroinen', 'PI', 'ry-wc-city-select'),
		_x('Juva', 'PI', 'ry-wc-city-select'),
		_x('Pieksaemaeki', 'PI', 'ry-wc-city-select'),
	],
	'PIKA' => [
		_x('Lieksa', 'PIKA', 'ry-wc-city-select'),
		_x('Nurmes', 'PIKA', 'ry-wc-city-select'),
		_x('Valtimo', 'PIKA', 'ry-wc-city-select'),
	],
	'PO' => [
		_x('Inari', 'PO', 'ry-wc-city-select'),
		_x('Sodankylae', 'PO', 'ry-wc-city-select'),
		_x('Utsjoki', 'PO', 'ry-wc-city-select'),
	],
	'PO2' => [
		_x('Honkajoki', 'PO2', 'ry-wc-city-select'),
		_x('Jaemijaervi', 'PO2', 'ry-wc-city-select'),
		_x('Kankaanpaeae', 'PO2', 'ry-wc-city-select'),
		_x('Karvia', 'PO2', 'ry-wc-city-select'),
		_x('Siikainen', 'PO2', 'ry-wc-city-select'),
	],
	'PO3' => [
		_x('Harjavalta', 'PO3', 'ry-wc-city-select'),
		_x('Huittinen', 'PO3', 'ry-wc-city-select'),
		_x('Kokemaeki', 'PO3', 'ry-wc-city-select'),
		_x('Merikarvia', 'PO3', 'ry-wc-city-select'),
		_x('Nakkila', 'PO3', 'ry-wc-city-select'),
		_x('Pomarkku', 'PO3', 'ry-wc-city-select'),
		_x('Pori', 'PO3', 'ry-wc-city-select'),
		_x('Ulvila', 'PO3', 'ry-wc-city-select'),
	],
	'PO4' => [
		_x('Askola', 'PO4', 'ry-wc-city-select'),
		_x('Moerskom', 'PO4', 'ry-wc-city-select'),
		_x('Porvoo', 'PO4', 'ry-wc-city-select'),
		_x('Pukkila', 'PO4', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Pyhaejoki', 'RA', 'ry-wc-city-select'),
		_x('Raahe', 'RA', 'ry-wc-city-select'),
		_x('Siikajoki', 'RA', 'ry-wc-city-select'),
	],
	'RA2' => [
		_x('Hanko', 'RA2', 'ry-wc-city-select'),
		_x('Inga', 'RA2', 'ry-wc-city-select'),
		_x('Raseborg', 'RA2', 'ry-wc-city-select'),
	],
	'RA3' => [
		_x('Eura', 'RA3', 'ry-wc-city-select'),
		_x('Eurajoki', 'RA3', 'ry-wc-city-select'),
		_x('Rauma', 'RA3', 'ry-wc-city-select'),
		_x('Saekylae', 'RA3', 'ry-wc-city-select'),
	],
	'RI' => [
		_x('Hausjaervi', 'RI', 'ry-wc-city-select'),
		_x('Loppi', 'RI', 'ry-wc-city-select'),
		_x('Riihimaeki', 'RI', 'ry-wc-city-select'),
	],
	'RO' => [
		_x('Ranua', 'RO', 'ry-wc-city-select'),
		_x('Rovaniemi', 'RO', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Kannonkoski', 'SA', 'ry-wc-city-select'),
		_x('Karstula', 'SA', 'ry-wc-city-select'),
		_x('Kinnula', 'SA', 'ry-wc-city-select'),
		_x('Kivijaervi', 'SA', 'ry-wc-city-select'),
		_x('Kyyjaervi', 'SA', 'ry-wc-city-select'),
		_x('Pihtipudas', 'SA', 'ry-wc-city-select'),
		_x('Saarijaervi', 'SA', 'ry-wc-city-select'),
		_x('Viitasaari', 'SA', 'ry-wc-city-select'),
	],
	'SA2' => [
		_x('Salo', 'SA2', 'ry-wc-city-select'),
		_x('Somero', 'SA2', 'ry-wc-city-select'),
	],
	'SA3' => [
		_x('Enonkoski', 'SA3', 'ry-wc-city-select'),
		_x('Heinaevesi', 'SA3', 'ry-wc-city-select'),
		_x('Rantasalmi', 'SA3', 'ry-wc-city-select'),
		_x('Savonlinna', 'SA3', 'ry-wc-city-select'),
		_x('Sulkava', 'SA3', 'ry-wc-city-select'),
	],
	'SE' => [
		_x('Ilmajoki', 'SE', 'ry-wc-city-select'),
		_x('Kauhava', 'SE', 'ry-wc-city-select'),
		_x('Kurikka', 'SE', 'ry-wc-city-select'),
		_x('Lapua', 'SE', 'ry-wc-city-select'),
		_x('Seinaejoki', 'SE', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Rautalampi', 'SI', 'ry-wc-city-select'),
		_x('Suonenjoki', 'SI', 'ry-wc-city-select'),
		_x('Tervo', 'SI', 'ry-wc-city-select'),
		_x('Vesanto', 'SI', 'ry-wc-city-select'),
	],
	'SU' => [
		_x('Isojoki', 'SU', 'ry-wc-city-select'),
		_x('Karijoki', 'SU', 'ry-wc-city-select'),
		_x('Kauhajoki', 'SU', 'ry-wc-city-select'),
		_x('Teuva', 'SU', 'ry-wc-city-select'),
	],
	'SY' => [
		_x('Kaskinen', 'SY', 'ry-wc-city-select'),
		_x('Kristinestad', 'SY', 'ry-wc-city-select'),
		_x('Naerpes', 'SY', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Haemeenkyroe', 'TA', 'ry-wc-city-select'),
		_x('Kangasala', 'TA', 'ry-wc-city-select'),
		_x('Lempaeaelae', 'TA', 'ry-wc-city-select'),
		_x('Nokia', 'TA', 'ry-wc-city-select'),
		_x('Orivesi', 'TA', 'ry-wc-city-select'),
		_x('Paelkaene', 'TA', 'ry-wc-city-select'),
		_x('Pirkkala', 'TA', 'ry-wc-city-select'),
		_x('Tampere', 'TA', 'ry-wc-city-select'),
		_x('Vesilahti', 'TA', 'ry-wc-city-select'),
		_x('Yloejaervi', 'TA', 'ry-wc-city-select'),
	],
	'TO' => [
		_x('Pello', 'TO', 'ry-wc-city-select'),
		_x('Ylitornio', 'TO', 'ry-wc-city-select'),
	],
	'TU' => [
		_x('Enontekioe', 'TU', 'ry-wc-city-select'),
		_x('Kittilae', 'TU', 'ry-wc-city-select'),
		_x('Kolari', 'TU', 'ry-wc-city-select'),
		_x('Muonio', 'TU', 'ry-wc-city-select'),
	],
	'TU2' => [
		_x('Kaarina', 'TU2', 'ry-wc-city-select'),
		_x('Lieto', 'TU2', 'ry-wc-city-select'),
		_x('Masku', 'TU2', 'ry-wc-city-select'),
		_x('Naantali', 'TU2', 'ry-wc-city-select'),
		_x('Nousiainen', 'TU2', 'ry-wc-city-select'),
		_x('Paimio', 'TU2', 'ry-wc-city-select'),
		_x('Raisio', 'TU2', 'ry-wc-city-select'),
		_x('Rusko', 'TU2', 'ry-wc-city-select'),
		_x('Sauvo', 'TU2', 'ry-wc-city-select'),
		_x('Turku', 'TU2', 'ry-wc-city-select'),
		_x('Virmo', 'TU2', 'ry-wc-city-select'),
	],
	'VA' => [
		_x('Korsholm', 'VA', 'ry-wc-city-select'),
		_x('Korsnaes', 'VA', 'ry-wc-city-select'),
		_x('Malax', 'VA', 'ry-wc-city-select'),
		_x('Vaasa', 'VA', 'ry-wc-city-select'),
		_x('Voera', 'VA', 'ry-wc-city-select'),
	],
	'VA2' => [
		_x('Kustavi', 'VA2', 'ry-wc-city-select'),
		_x('Laitila', 'VA2', 'ry-wc-city-select'),
		_x('Pyhaeranta', 'VA2', 'ry-wc-city-select'),
		_x('Taivassalo', 'VA2', 'ry-wc-city-select'),
		_x('Uusikaupunki', 'VA2', 'ry-wc-city-select'),
		_x('Vehmaa', 'VA2', 'ry-wc-city-select'),
	],
	'VA3' => [
		_x('Leppaevirta', 'VA3', 'ry-wc-city-select'),
		_x('Varkaus', 'VA3', 'ry-wc-city-select'),
	],
	'YL' => [
		_x('Juupajoki', 'YL', 'ry-wc-city-select'),
		_x('Maenttae-Vilppula', 'YL', 'ry-wc-city-select'),
		_x('Ruovesi', 'YL', 'ry-wc-city-select'),
		_x('Virrat', 'YL', 'ry-wc-city-select'),
	],
	'YL2' => [
		_x('Iisalmi', 'YL2', 'ry-wc-city-select'),
		_x('Keitele', 'YL2', 'ry-wc-city-select'),
		_x('Kiuruvesi', 'YL2', 'ry-wc-city-select'),
		_x('Lapinlahti', 'YL2', 'ry-wc-city-select'),
		_x('Pielavesi', 'YL2', 'ry-wc-city-select'),
		_x('Sonkajaervi', 'YL2', 'ry-wc-city-select'),
		_x('Vieremae', 'YL2', 'ry-wc-city-select'),
	],
	'YL3' => [
		_x('Alavieska', 'YL3', 'ry-wc-city-select'),
		_x('Kalajoki', 'YL3', 'ry-wc-city-select'),
		_x('Merijaervi', 'YL3', 'ry-wc-city-select'),
		_x('Oulainen', 'YL3', 'ry-wc-city-select'),
		_x('Sievi', 'YL3', 'ry-wc-city-select'),
		_x('Ylivieska', 'YL3', 'ry-wc-city-select'),
	],
	]
];