<?php
/**
 * Georgia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'GE' => [
	'AB' => [
		_x('Gagra District', 'AB', 'ry-wc-city-select'),
		_x('Gali District', 'AB', 'ry-wc-city-select'),
		_x('Gudauta District', 'AB', 'ry-wc-city-select'),
		_x('Gulripshi district', 'AB', 'ry-wc-city-select'),
		_x('Ochamchira District', 'AB', 'ry-wc-city-select'),
		_x('Sukhumi District', 'AB', 'ry-wc-city-select'),
		_x('Tkvarcheli district', 'AB', 'ry-wc-city-select'),
	],
	'AJ' => [
		_x('Batumi', 'AJ', 'ry-wc-city-select'),
		_x('Kobuletis Raioni', 'AJ', 'ry-wc-city-select'),
		_x('Kedis Munitsipaliteti', 'AJ', 'ry-wc-city-select'),
		_x('Khelvachauri Municipality', 'AJ', 'ry-wc-city-select'),
		_x('Kobuletis Munitsipaliteti', 'AJ', 'ry-wc-city-select'),
	],
	'GU' => [
		_x('Chokhatauris Munitsipaliteti', 'GU', 'ry-wc-city-select'),
		_x('Chokhatauri', 'GU', 'ry-wc-city-select'),
		_x('Lanchkhutis Munitsipaliteti', 'GU', 'ry-wc-city-select'),
		_x('Ozurgetis Raioni', 'GU', 'ry-wc-city-select'),
	],
	'IM' => [
		_x('Baghdati', 'IM', 'ry-wc-city-select'),
		_x('Baghdatis Munitsipaliteti', 'IM', 'ry-wc-city-select'),
		_x('Kalaki Chiatura', 'IM', 'ry-wc-city-select'),
		_x('Kalaki Tqibuli', 'IM', 'ry-wc-city-select'),
		_x('Kalaki Kutaisi', 'IM', 'ry-wc-city-select'),
		_x('Kharagaulis Raioni', 'IM', 'ry-wc-city-select'),
		_x('Khoni', 'IM', 'ry-wc-city-select'),
		_x('Khonis Munitsipaliteti', 'IM', 'ry-wc-city-select'),
		_x('Sachkhere', 'IM', 'ry-wc-city-select'),
		_x('Samtredia', 'IM', 'ry-wc-city-select'),
		_x('Terjolis Munitsipaliteti', 'IM', 'ry-wc-city-select'),
		_x('Tsqaltubo', 'IM', 'ry-wc-city-select'),
		_x('Vanis Munitsipaliteti', 'IM', 'ry-wc-city-select'),
		_x('Zestaponis Munitsipaliteti', 'IM', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Akhmetis Munitsipaliteti', 'KA', 'ry-wc-city-select'),
		_x('Dedoplis Tskaro', 'KA', 'ry-wc-city-select'),
		_x('Dedoplistsqaros Munitsipaliteti', 'KA', 'ry-wc-city-select'),
		_x('Gurjaani', 'KA', 'ry-wc-city-select'),
		_x('Gurjaanis Munitsipaliteti', 'KA', 'ry-wc-city-select'),
		_x('Lagodekhi', 'KA', 'ry-wc-city-select'),
		_x('Qvarlis Munitsipaliteti', 'KA', 'ry-wc-city-select'),
		_x('Qvareli', 'KA', 'ry-wc-city-select'),
		_x('Sagarejo', 'KA', 'ry-wc-city-select'),
		_x('Sagarejos Munitsipaliteti', 'KA', 'ry-wc-city-select'),
		_x('Sighnaghi', 'KA', 'ry-wc-city-select'),
		_x('Sighnaghis Munitsipaliteti', 'KA', 'ry-wc-city-select'),
		_x('Telavi', 'KA', 'ry-wc-city-select'),
	],
	'KVKA' => [
		_x('Bolnisis Munitsipaliteti', 'KVKA', 'ry-wc-city-select'),
		_x('Dmanisi', 'KVKA', 'ry-wc-city-select'),
		_x('Dmanisis Munitsipaliteti', 'KVKA', 'ry-wc-city-select'),
		_x('Gardabani', 'KVKA', 'ry-wc-city-select'),
		_x('Gardabnis Munitsipaliteti', 'KVKA', 'ry-wc-city-select'),
		_x('Kalaki Rustavi', 'KVKA', 'ry-wc-city-select'),
		_x('Marneuli', 'KVKA', 'ry-wc-city-select'),
		_x('Marneulis Munitsipaliteti', 'KVKA', 'ry-wc-city-select'),
		_x('Tetri Tsqaro', 'KVKA', 'ry-wc-city-select'),
		_x('Tetritsqalos Munitsipaliteti', 'KVKA', 'ry-wc-city-select'),
		_x('Tsalkis Munitsipaliteti', 'KVKA', 'ry-wc-city-select'),
		_x('Tsalka', 'KVKA', 'ry-wc-city-select'),
	],
	'MT' => [
		_x('Akhalgori', 'MT', 'ry-wc-city-select'),
		_x('Akhalgoris Munitsipaliteti', 'MT', 'ry-wc-city-select'),
		_x('Dusheti', 'MT', 'ry-wc-city-select'),
		_x('Dushetis Munitsipaliteti', 'MT', 'ry-wc-city-select'),
		_x('Kazbegi', 'MT', 'ry-wc-city-select'),
		_x('Mtskheta', 'MT', 'ry-wc-city-select'),
		_x('Mtskhetis Munitsipaliteti', 'MT', 'ry-wc-city-select'),
		_x('Qazbegis Munitsipalitet`i', 'MT', 'ry-wc-city-select'),
		_x('Tianetis Munitsipaliteti', 'MT', 'ry-wc-city-select'),
	],
	'RAANKVSV' => [
		_x('Ambrolauris Munitsipaliteti', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Imeni Dvadtsati Shesti Komissarov Rayon', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Kalininskiy Rayon', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Kirovskiy Rayon', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Lentekhis Munitsipaliteti', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Lentekhi', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Onis Munitsipaliteti', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Ordzhonikidzevskiy Rayon', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Pervomayskiy Rayon', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Tsageri', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Tsageris Munitsipaliteti', 'RAANKVSV', 'ry-wc-city-select'),
		_x('Zavodskoy Rayon', 'RAANKVSV', 'ry-wc-city-select'),
	],
	'SASVMK' => [
		_x('Abasha', 'SASVMK', 'ry-wc-city-select'),
		_x('Chkhorotsqus Munitsipaliteti', 'SASVMK', 'ry-wc-city-select'),
		_x('Chkhorotsqu', 'SASVMK', 'ry-wc-city-select'),
		_x('Kalaki Poti', 'SASVMK', 'ry-wc-city-select'),
		_x('Khobis Munitsipaliteti', 'SASVMK', 'ry-wc-city-select'),
		_x('Martvilis Munitsipaliteti', 'SASVMK', 'ry-wc-city-select'),
		_x('Martvili', 'SASVMK', 'ry-wc-city-select'),
		_x('Mestiis Munitsipaliteti', 'SASVMK', 'ry-wc-city-select'),
		_x('Mestia', 'SASVMK', 'ry-wc-city-select'),
		_x('Poti', 'SASVMK', 'ry-wc-city-select'),
		_x('Senakis Raioni', 'SASVMK', 'ry-wc-city-select'),
		_x('Tsalenjikhis Munitsipaliteti', 'SASVMK', 'ry-wc-city-select'),
		_x('Tsalenjikha', 'SASVMK', 'ry-wc-city-select'),
		_x('Zugdidis Munitsipaliteti', 'SASVMK', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Adigeni Municipality', 'SA', 'ry-wc-city-select'),
		_x('Akhalkalakis Munitsipaliteti', 'SA', 'ry-wc-city-select'),
		_x('Akhaltsikhis Munitsipaliteti', 'SA', 'ry-wc-city-select'),
		_x('Aspindzis Munitsipaliteti', 'SA', 'ry-wc-city-select'),
		_x('Borjomis Munitsipaliteti', 'SA', 'ry-wc-city-select'),
		_x('Ninotsmindis Munitsipaliteti', 'SA', 'ry-wc-city-select'),
		_x('Ninotsminda', 'SA', 'ry-wc-city-select'),
	],
	'SHKA' => [
		_x('Goris Munitsipaliteti', 'SHKA', 'ry-wc-city-select'),
		_x('Javis Munitsipaliteti', 'SHKA', 'ry-wc-city-select'),
		_x('Kareli', 'SHKA', 'ry-wc-city-select'),
		_x('Kaspis Raioni', 'SHKA', 'ry-wc-city-select'),
		_x('Khashuris Raioni', 'SHKA', 'ry-wc-city-select'),
		_x('Tskhinvali District', 'SHKA', 'ry-wc-city-select'),
	],
	]
];