<?php
/**
 * Republic of Ghana places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'GH' => [
	'BAMUDI' => [
		_x('Bawku', 'BAMUDI', 'ry-wc-city-select'),
	],
	'AH' => [
		_x('Asunafo North', 'AH', 'ry-wc-city-select'),
		_x('Asunafo South', 'AH', 'ry-wc-city-select'),
		_x('Asutifi', 'AH', 'ry-wc-city-select'),
		_x('Asutifi South', 'AH', 'ry-wc-city-select'),
		_x('Tano North', 'AH', 'ry-wc-city-select'),
		_x('Tano South', 'AH', 'ry-wc-city-select'),
	],
	'ASRE' => [
		_x('Adansi North', 'ASRE', 'ry-wc-city-select'),
		_x('Adansi South', 'ASRE', 'ry-wc-city-select'),
		_x('Afigya-Kwabre District', 'ASRE', 'ry-wc-city-select'),
		_x('Ahafo Ano North', 'ASRE', 'ry-wc-city-select'),
		_x('Ahafo Ano South', 'ASRE', 'ry-wc-city-select'),
		_x('Amansie Central', 'ASRE', 'ry-wc-city-select'),
		_x('Amansie West', 'ASRE', 'ry-wc-city-select'),
		_x('Asante Akim Central Municipal', 'ASRE', 'ry-wc-city-select'),
		_x('Asante Akim North', 'ASRE', 'ry-wc-city-select'),
		_x('Asante Akim South District', 'ASRE', 'ry-wc-city-select'),
		_x('Asokore Mampong Municipal', 'ASRE', 'ry-wc-city-select'),
		_x('Atwima Kwanwoma', 'ASRE', 'ry-wc-city-select'),
		_x('Atwima Mponua', 'ASRE', 'ry-wc-city-select'),
		_x('Atwima Nwabiagya', 'ASRE', 'ry-wc-city-select'),
		_x('Bekwai', 'ASRE', 'ry-wc-city-select'),
		_x('Bosome Freho', 'ASRE', 'ry-wc-city-select'),
		_x('Bosomtwe', 'ASRE', 'ry-wc-city-select'),
		_x('Ejisu Juaben', 'ASRE', 'ry-wc-city-select'),
		_x('Ejura Sekyedumase', 'ASRE', 'ry-wc-city-select'),
		_x('Kumasi', 'ASRE', 'ry-wc-city-select'),
		_x('Kwabre District', 'ASRE', 'ry-wc-city-select'),
		_x('Mampong', 'ASRE', 'ry-wc-city-select'),
		_x('Obuasi', 'ASRE', 'ry-wc-city-select'),
		_x('Offinso Municipal District', 'ASRE', 'ry-wc-city-select'),
		_x('Offinso North', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere Afram Plains', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere Afram Plains North', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere Central', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere East', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere South', 'ASRE', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Banda', 'BO', 'ry-wc-city-select'),
		_x('Berekum', 'BO', 'ry-wc-city-select'),
		_x('Dormaa', 'BO', 'ry-wc-city-select'),
		_x('Dormaa East', 'BO', 'ry-wc-city-select'),
		_x('Dormaa West', 'BO', 'ry-wc-city-select'),
		_x('Jaman North', 'BO', 'ry-wc-city-select'),
		_x('Jaman South', 'BO', 'ry-wc-city-select'),
		_x('Sunyani', 'BO', 'ry-wc-city-select'),
		_x('Sunyani West', 'BO', 'ry-wc-city-select'),
		_x('Tain', 'BO', 'ry-wc-city-select'),
		_x('Wenchi', 'BO', 'ry-wc-city-select'),
	],
	'BOEA' => [
		_x('Atebubu-Amantin District', 'BOEA', 'ry-wc-city-select'),
		_x('Kintampo North Municipal District', 'BOEA', 'ry-wc-city-select'),
		_x('Kintampo South District', 'BOEA', 'ry-wc-city-select'),
		_x('Nkoranza North District', 'BOEA', 'ry-wc-city-select'),
		_x('Nkoranza South', 'BOEA', 'ry-wc-city-select'),
		_x('Pru', 'BOEA', 'ry-wc-city-select'),
		_x('Sene', 'BOEA', 'ry-wc-city-select'),
		_x('Sene East', 'BOEA', 'ry-wc-city-select'),
		_x('Techiman Municipal', 'BOEA', 'ry-wc-city-select'),
		_x('Techiman Municipal District', 'BOEA', 'ry-wc-city-select'),
	],
	'CERE' => [
		_x('Abura/Asebu/Kwamankese', 'CERE', 'ry-wc-city-select'),
		_x('Agona East', 'CERE', 'ry-wc-city-select'),
		_x('Agona West', 'CERE', 'ry-wc-city-select'),
		_x('Ajumako/Enyan/Essiam', 'CERE', 'ry-wc-city-select'),
		_x('Asikuma/Odoben/Brakwa', 'CERE', 'ry-wc-city-select'),
		_x('Assin North', 'CERE', 'ry-wc-city-select'),
		_x('Assin South', 'CERE', 'ry-wc-city-select'),
		_x('Awutu Senya', 'CERE', 'ry-wc-city-select'),
		_x('Awutu Senya East Municipal', 'CERE', 'ry-wc-city-select'),
		_x('Cape Coast', 'CERE', 'ry-wc-city-select'),
		_x('Effutu', 'CERE', 'ry-wc-city-select'),
		_x('Ekumfi', 'CERE', 'ry-wc-city-select'),
		_x('Gomoa East', 'CERE', 'ry-wc-city-select'),
		_x('Gomoa West', 'CERE', 'ry-wc-city-select'),
		_x('Komenda/Edina/Eguafo/Abirem', 'CERE', 'ry-wc-city-select'),
		_x('Mfatseman', 'CERE', 'ry-wc-city-select'),
		_x('Twifo Ati-Morkwa', 'CERE', 'ry-wc-city-select'),
		_x('Twifo Hemang Lower Denkyira', 'CERE', 'ry-wc-city-select'),
		_x('Upper Denkyira East', 'CERE', 'ry-wc-city-select'),
		_x('Upper Denkyira West', 'CERE', 'ry-wc-city-select'),
	],
	'EARE' => [
		_x('Akuapim North', 'EARE', 'ry-wc-city-select'),
		_x('Akuapim South', 'EARE', 'ry-wc-city-select'),
		_x('Akyemansa', 'EARE', 'ry-wc-city-select'),
		_x('Asuogyaman', 'EARE', 'ry-wc-city-select'),
		_x('Atiwa', 'EARE', 'ry-wc-city-select'),
		_x('Ayensuano', 'EARE', 'ry-wc-city-select'),
		_x('Birim Central', 'EARE', 'ry-wc-city-select'),
		_x('Birim North', 'EARE', 'ry-wc-city-select'),
		_x('Birim South', 'EARE', 'ry-wc-city-select'),
		_x('Denkyembour', 'EARE', 'ry-wc-city-select'),
		_x('East Akim', 'EARE', 'ry-wc-city-select'),
		_x('Fanteakwa', 'EARE', 'ry-wc-city-select'),
		_x('Kwaebibirem', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu Afram Plains South', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu East', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu North', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu South', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu West', 'EARE', 'ry-wc-city-select'),
		_x('Lower Manya Krobo', 'EARE', 'ry-wc-city-select'),
		_x('New Juaben', 'EARE', 'ry-wc-city-select'),
		_x('Nsawam Adoagyiri', 'EARE', 'ry-wc-city-select'),
		_x('Suhum/Kraboa/Coaltar', 'EARE', 'ry-wc-city-select'),
		_x('Upper Manya Krobo', 'EARE', 'ry-wc-city-select'),
		_x('Upper West Akim', 'EARE', 'ry-wc-city-select'),
		_x('West Akim', 'EARE', 'ry-wc-city-select'),
		_x('Yilo Krobo', 'EARE', 'ry-wc-city-select'),
	],
	'GRACRE' => [
		_x('Accra', 'GRACRE', 'ry-wc-city-select'),
		_x('Ada East', 'GRACRE', 'ry-wc-city-select'),
		_x('Ada West', 'GRACRE', 'ry-wc-city-select'),
		_x('Adenta', 'GRACRE', 'ry-wc-city-select'),
		_x('Ashaiman', 'GRACRE', 'ry-wc-city-select'),
		_x('Ga Central Municipal Assembly', 'GRACRE', 'ry-wc-city-select'),
		_x('Ga East', 'GRACRE', 'ry-wc-city-select'),
		_x('Ga South', 'GRACRE', 'ry-wc-city-select'),
		_x('Ga West', 'GRACRE', 'ry-wc-city-select'),
		_x('Kpone Katamanso', 'GRACRE', 'ry-wc-city-select'),
		_x('La Dade Kotopon', 'GRACRE', 'ry-wc-city-select'),
		_x('La Nkwantanang Madina', 'GRACRE', 'ry-wc-city-select'),
		_x('Ledzekuku-Krowor', 'GRACRE', 'ry-wc-city-select'),
		_x('Ningo Prampram', 'GRACRE', 'ry-wc-city-select'),
		_x('Shai Osudoku District', 'GRACRE', 'ry-wc-city-select'),
		_x('Tema Metropolitan District', 'GRACRE', 'ry-wc-city-select'),
	],
	'NOEA' => [
		_x('Bunkpurugu-Yunyoo', 'NOEA', 'ry-wc-city-select'),
		_x('Chereponi', 'NOEA', 'ry-wc-city-select'),
		_x('East Mamprusi', 'NOEA', 'ry-wc-city-select'),
		_x('Mamprugo Moaduri District', 'NOEA', 'ry-wc-city-select'),
		_x('West Mamprusi', 'NOEA', 'ry-wc-city-select'),
	],
	'NORE' => [
		_x('Gushiegu', 'NORE', 'ry-wc-city-select'),
		_x('Karaga', 'NORE', 'ry-wc-city-select'),
		_x('Kpandai', 'NORE', 'ry-wc-city-select'),
		_x('Kumbumgu', 'NORE', 'ry-wc-city-select'),
		_x('Mion', 'NORE', 'ry-wc-city-select'),
		_x('Nanumba North', 'NORE', 'ry-wc-city-select'),
		_x('Nanumba South', 'NORE', 'ry-wc-city-select'),
		_x('Saboba', 'NORE', 'ry-wc-city-select'),
		_x('Sagnerigu', 'NORE', 'ry-wc-city-select'),
		_x('Savelugu/Nanton', 'NORE', 'ry-wc-city-select'),
		_x('Tamale', 'NORE', 'ry-wc-city-select'),
		_x('Tatale', 'NORE', 'ry-wc-city-select'),
		_x('Tolon/Kumbungu', 'NORE', 'ry-wc-city-select'),
		_x('Yendi', 'NORE', 'ry-wc-city-select'),
		_x('Zabzugu/Tatale', 'NORE', 'ry-wc-city-select'),
	],
	'OT' => [
		_x('Biakoye', 'OT', 'ry-wc-city-select'),
		_x('Jasikan', 'OT', 'ry-wc-city-select'),
		_x('Kadjebi', 'OT', 'ry-wc-city-select'),
		_x('Krachi East', 'OT', 'ry-wc-city-select'),
		_x('Krachi Nchumuru', 'OT', 'ry-wc-city-select'),
		_x('Krachi West', 'OT', 'ry-wc-city-select'),
		_x('Nkwanta North', 'OT', 'ry-wc-city-select'),
		_x('Nkwanta South', 'OT', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Bole', 'SA', 'ry-wc-city-select'),
		_x('Central Gonja', 'SA', 'ry-wc-city-select'),
		_x('East Gonja', 'SA', 'ry-wc-city-select'),
		_x('North Gonja', 'SA', 'ry-wc-city-select'),
		_x('Sawla-Tuna-Kalba', 'SA', 'ry-wc-city-select'),
		_x('West Gonja', 'SA', 'ry-wc-city-select'),
	],
	'UPEARE' => [
		_x('Bawku West', 'UPEARE', 'ry-wc-city-select'),
		_x('Binduri District', 'UPEARE', 'ry-wc-city-select'),
		_x('Bolgatanga Municipal District', 'UPEARE', 'ry-wc-city-select'),
		_x('Bongo District', 'UPEARE', 'ry-wc-city-select'),
		_x('Builsa South', 'UPEARE', 'ry-wc-city-select'),
		_x('Garu-Tempane', 'UPEARE', 'ry-wc-city-select'),
		_x('Kassena Nankana', 'UPEARE', 'ry-wc-city-select'),
		_x('Kassena Nankana West', 'UPEARE', 'ry-wc-city-select'),
		_x('Nabdam', 'UPEARE', 'ry-wc-city-select'),
		_x('North Builsa District', 'UPEARE', 'ry-wc-city-select'),
		_x('Pusiga', 'UPEARE', 'ry-wc-city-select'),
		_x('Talensi-Nabdam', 'UPEARE', 'ry-wc-city-select'),
	],
	'UPWERE' => [
		_x('Daffiama Bussie Issa District', 'UPWERE', 'ry-wc-city-select'),
		_x('Jirapa', 'UPWERE', 'ry-wc-city-select'),
		_x('Lambussie Karni', 'UPWERE', 'ry-wc-city-select'),
		_x('Lawra', 'UPWERE', 'ry-wc-city-select'),
		_x('Nadowli', 'UPWERE', 'ry-wc-city-select'),
		_x('Nandom', 'UPWERE', 'ry-wc-city-select'),
		_x('Sissala East', 'UPWERE', 'ry-wc-city-select'),
		_x('Sissala West', 'UPWERE', 'ry-wc-city-select'),
		_x('Wa', 'UPWERE', 'ry-wc-city-select'),
		_x('Wa East', 'UPWERE', 'ry-wc-city-select'),
		_x('Wa West', 'UPWERE', 'ry-wc-city-select'),
	],
	'VORE' => [
		_x('Adaklu', 'VORE', 'ry-wc-city-select'),
		_x('Afadzato South', 'VORE', 'ry-wc-city-select'),
		_x('Agotime Ziope', 'VORE', 'ry-wc-city-select'),
		_x('Akatsi District', 'VORE', 'ry-wc-city-select'),
		_x('Akatsi South', 'VORE', 'ry-wc-city-select'),
		_x('Central Tongu', 'VORE', 'ry-wc-city-select'),
		_x('Ho', 'VORE', 'ry-wc-city-select'),
		_x('Ho West', 'VORE', 'ry-wc-city-select'),
		_x('Hohoe', 'VORE', 'ry-wc-city-select'),
		_x('Keta', 'VORE', 'ry-wc-city-select'),
		_x('Ketu North District', 'VORE', 'ry-wc-city-select'),
		_x('Ketu South District', 'VORE', 'ry-wc-city-select'),
		_x('Kpando', 'VORE', 'ry-wc-city-select'),
		_x('North Dayi', 'VORE', 'ry-wc-city-select'),
		_x('North Tongu', 'VORE', 'ry-wc-city-select'),
		_x('South Dayi', 'VORE', 'ry-wc-city-select'),
		_x('South Tongu District', 'VORE', 'ry-wc-city-select'),
	],
	'WENO' => [
		_x('Aowin/Suaman', 'WENO', 'ry-wc-city-select'),
		_x('Bia', 'WENO', 'ry-wc-city-select'),
		_x('Bia East', 'WENO', 'ry-wc-city-select'),
		_x('Bibiani/Ahwiaso/Bekwai', 'WENO', 'ry-wc-city-select'),
		_x('Bodi', 'WENO', 'ry-wc-city-select'),
		_x('Juaboso', 'WENO', 'ry-wc-city-select'),
		_x('Sefwi Akontobra', 'WENO', 'ry-wc-city-select'),
		_x('Sefwi-Wiawso', 'WENO', 'ry-wc-city-select'),
		_x('Suaman', 'WENO', 'ry-wc-city-select'),
	],
	'WERE' => [
		_x('Ahanta West', 'WERE', 'ry-wc-city-select'),
		_x('Ellembelle', 'WERE', 'ry-wc-city-select'),
		_x('Jomoro', 'WERE', 'ry-wc-city-select'),
		_x('Mpohor', 'WERE', 'ry-wc-city-select'),
		_x('Mpohor/Wassa East', 'WERE', 'ry-wc-city-select'),
		_x('Nzema East', 'WERE', 'ry-wc-city-select'),
		_x('Prestea-Huni Valley', 'WERE', 'ry-wc-city-select'),
		_x('Secondi Takoradi', 'WERE', 'ry-wc-city-select'),
		_x('Shama', 'WERE', 'ry-wc-city-select'),
		_x('Tarkwa Nsuaem', 'WERE', 'ry-wc-city-select'),
		_x('Wassa Amenfi Central', 'WERE', 'ry-wc-city-select'),
		_x('Wassa Amenfi East', 'WERE', 'ry-wc-city-select'),
		_x('Wassa Amenfi West', 'WERE', 'ry-wc-city-select'),
	],
	]
];