<?php
/**
 * Republic of Guinea places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'GN' => [
	'BEPR' => [
		_x('Diara-Guerela', 'BEPR', 'ry-wc-city-select'),
		_x('Diassodou', 'BEPR', 'ry-wc-city-select'),
		_x('Fouala', 'BEPR', 'ry-wc-city-select'),
		_x('Foumbadou Sub-Prefecture', 'BEPR', 'ry-wc-city-select'),
		_x('Gbakedou', 'BEPR', 'ry-wc-city-select'),
		_x('Gbessoba', 'BEPR', 'ry-wc-city-select'),
		_x('Karala', 'BEPR', 'ry-wc-city-select'),
		_x('Koumandou', 'BEPR', 'ry-wc-city-select'),
		_x('Moussadou', 'BEPR', 'ry-wc-city-select'),
		_x('Nionsomoridou', 'BEPR', 'ry-wc-city-select'),
		_x('Samana', 'BEPR', 'ry-wc-city-select'),
		_x('Sinko', 'BEPR', 'ry-wc-city-select'),
		_x('Sokourala', 'BEPR', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Colia', 'BO', 'ry-wc-city-select'),
		_x('Douprou', 'BO', 'ry-wc-city-select'),
		_x('Koba-Tatema', 'BO', 'ry-wc-city-select'),
		_x('Mankountan', 'BO', 'ry-wc-city-select'),
		_x('Tamita', 'BO', 'ry-wc-city-select'),
		_x('Tougnifili', 'BO', 'ry-wc-city-select'),
	],
	'BOPR' => [
		_x('Bintimodiya', 'BOPR', 'ry-wc-city-select'),
		_x('Dabiss', 'BOPR', 'ry-wc-city-select'),
		_x('Kamakoulon', 'BOPR', 'ry-wc-city-select'),
		_x('Kanfarande', 'BOPR', 'ry-wc-city-select'),
		_x('Kolaboui', 'BOPR', 'ry-wc-city-select'),
		_x('Malapouyah', 'BOPR', 'ry-wc-city-select'),
		_x('Sangaredi', 'BOPR', 'ry-wc-city-select'),
		_x('Sansale', 'BOPR', 'ry-wc-city-select'),
		_x('Tanene', 'BOPR', 'ry-wc-city-select'),
	],
	'COSPZO' => [
		_x('Kaloum', 'COSPZO', 'ry-wc-city-select'),
	],
	'DA' => [
		_x('Arfamoussaya', 'DA', 'ry-wc-city-select'),
		_x('Banko', 'DA', 'ry-wc-city-select'),
		_x('Bissikrima', 'DA', 'ry-wc-city-select'),
		_x('Dogomet', 'DA', 'ry-wc-city-select'),
		_x('Kankama', 'DA', 'ry-wc-city-select'),
		_x('Kindoye', 'DA', 'ry-wc-city-select'),
		_x('Konindou', 'DA', 'ry-wc-city-select'),
		_x('NDema', 'DA', 'ry-wc-city-select'),
	],
	'DA2' => [
		_x('Bodie', 'DA2', 'ry-wc-city-select'),
		_x('Dalaba-Centre', 'DA2', 'ry-wc-city-select'),
		_x('Ditinn', 'DA2', 'ry-wc-city-select'),
		_x('Gongore', 'DA2', 'ry-wc-city-select'),
		_x('Kaala', 'DA2', 'ry-wc-city-select'),
		_x('Kankalabe', 'DA2', 'ry-wc-city-select'),
		_x('Kebali', 'DA2', 'ry-wc-city-select'),
		_x('Koba', 'DA2', 'ry-wc-city-select'),
		_x('Mafara', 'DA2', 'ry-wc-city-select'),
		_x('Mitty', 'DA2', 'ry-wc-city-select'),
		_x('Mombeyah', 'DA2', 'ry-wc-city-select'),
	],
	'DIPR' => [
		_x('Banora', 'DIPR', 'ry-wc-city-select'),
		_x('Dialakoro', 'DIPR', 'ry-wc-city-select'),
		_x('Diatifere', 'DIPR', 'ry-wc-city-select'),
		_x('Gagnakali', 'DIPR', 'ry-wc-city-select'),
		_x('Kalinko', 'DIPR', 'ry-wc-city-select'),
		_x('Lansanya', 'DIPR', 'ry-wc-city-select'),
		_x('Selouma', 'DIPR', 'ry-wc-city-select'),
	],
	'FAPR' => [
		_x('Banian', 'FAPR', 'ry-wc-city-select'),
		_x('Beindou', 'FAPR', 'ry-wc-city-select'),
		_x('Gnaleah', 'FAPR', 'ry-wc-city-select'),
		_x('Heremakonon', 'FAPR', 'ry-wc-city-select'),
		_x('Kobikoro', 'FAPR', 'ry-wc-city-select'),
		_x('Marela', 'FAPR', 'ry-wc-city-select'),
		_x('Passayah', 'FAPR', 'ry-wc-city-select'),
		_x('Sandeniah', 'FAPR', 'ry-wc-city-select'),
		_x('Songoyah', 'FAPR', 'ry-wc-city-select'),
		_x('Tiro', 'FAPR', 'ry-wc-city-select'),
	],
	'FR' => [
		_x('Badi', 'FR', 'ry-wc-city-select'),
		_x('Baguinet', 'FR', 'ry-wc-city-select'),
		_x('Sogolon', 'FR', 'ry-wc-city-select'),
		_x('Tormelin', 'FR', 'ry-wc-city-select'),
	],
	'GAPR' => [
		_x('Foulamory', 'GAPR', 'ry-wc-city-select'),
		_x('Kakony', 'GAPR', 'ry-wc-city-select'),
		_x('Kollet', 'GAPR', 'ry-wc-city-select'),
		_x('Koumbia', 'GAPR', 'ry-wc-city-select'),
		_x('Kounsitel', 'GAPR', 'ry-wc-city-select'),
		_x('Lafou', 'GAPR', 'ry-wc-city-select'),
		_x('Malanta', 'GAPR', 'ry-wc-city-select'),
		_x('Touba', 'GAPR', 'ry-wc-city-select'),
		_x('Wendou MBour', 'GAPR', 'ry-wc-city-select'),
	],
	'KAPR' => [
		_x('Balandougou', 'KAPR', 'ry-wc-city-select'),
		_x('Bate-Nafadji', 'KAPR', 'ry-wc-city-select'),
		_x('Boula', 'KAPR', 'ry-wc-city-select'),
		_x('Gberedou-Baranama', 'KAPR', 'ry-wc-city-select'),
		_x('Kanfamoriyah', 'KAPR', 'ry-wc-city-select'),
		_x('Kankan Centre', 'KAPR', 'ry-wc-city-select'),
		_x('Komodou', 'KAPR', 'ry-wc-city-select'),
		_x('Koumban', 'KAPR', 'ry-wc-city-select'),
		_x('Missamana', 'KAPR', 'ry-wc-city-select'),
		_x('Moribayah', 'KAPR', 'ry-wc-city-select'),
		_x('Sabadou-Baranama', 'KAPR', 'ry-wc-city-select'),
		_x('Tinti-Oulen', 'KAPR', 'ry-wc-city-select'),
		_x('Tokounou', 'KAPR', 'ry-wc-city-select'),
	],
	'KEPR' => [
		_x('Banankoro', 'KEPR', 'ry-wc-city-select'),
		_x('Damaro', 'KEPR', 'ry-wc-city-select'),
		_x('Kounsankoro', 'KEPR', 'ry-wc-city-select'),
		_x('Linko', 'KEPR', 'ry-wc-city-select'),
	],
	'KI' => [
		_x('Bangouyah', 'KI', 'ry-wc-city-select'),
		_x('Damankanyah', 'KI', 'ry-wc-city-select'),
		_x('Friguiagbe', 'KI', 'ry-wc-city-select'),
		_x('Kolente', 'KI', 'ry-wc-city-select'),
		_x('Mambia', 'KI', 'ry-wc-city-select'),
		_x('Molota', 'KI', 'ry-wc-city-select'),
		_x('Samayah', 'KI', 'ry-wc-city-select'),
		_x('Sougueta', 'KI', 'ry-wc-city-select'),
	],
	'KI2' => [
		_x('Albadaria', 'KI2', 'ry-wc-city-select'),
		_x('Banama', 'KI2', 'ry-wc-city-select'),
		_x('Bardou', 'KI2', 'ry-wc-city-select'),
		_x('Fermessadou-Pombo', 'KI2', 'ry-wc-city-select'),
		_x('Firawa-Yomadou', 'KI2', 'ry-wc-city-select'),
		_x('Gbangbadou', 'KI2', 'ry-wc-city-select'),
		_x('Kissidougou-Centre', 'KI2', 'ry-wc-city-select'),
		_x('Kondiadou', 'KI2', 'ry-wc-city-select'),
		_x('Mamouroudou', 'KI2', 'ry-wc-city-select'),
		_x('Manfran', 'KI2', 'ry-wc-city-select'),
		_x('Sangarado', 'KI2', 'ry-wc-city-select'),
		_x('Sibiribaro', 'KI2', 'ry-wc-city-select'),
		_x('Soromaya', 'KI2', 'ry-wc-city-select'),
		_x('Yende-Millimou', 'KI2', 'ry-wc-city-select'),
		_x('Yombiro', 'KI2', 'ry-wc-city-select'),
	],
	'KO' => [
		_x('Dionfo', 'KO', 'ry-wc-city-select'),
		_x('Fafaya', 'KO', 'ry-wc-city-select'),
		_x('Missira', 'KO', 'ry-wc-city-select'),
		_x('Pilimini', 'KO', 'ry-wc-city-select'),
	],
	'KOPR' => [
		_x('Guingan', 'KOPR', 'ry-wc-city-select'),
		_x('Kamaby', 'KOPR', 'ry-wc-city-select'),
		_x('Sambailo', 'KOPR', 'ry-wc-city-select'),
		_x('Sareboido', 'KOPR', 'ry-wc-city-select'),
		_x('Termesse', 'KOPR', 'ry-wc-city-select'),
		_x('Youkounkoun', 'KOPR', 'ry-wc-city-select'),
	],
	'KO2' => [
		_x('Babila', 'KO2', 'ry-wc-city-select'),
		_x('Balato', 'KO2', 'ry-wc-city-select'),
		_x('Banfele', 'KO2', 'ry-wc-city-select'),
		_x('Baro', 'KO2', 'ry-wc-city-select'),
		_x('Cissela', 'KO2', 'ry-wc-city-select'),
		_x('Douako', 'KO2', 'ry-wc-city-select'),
		_x('Kiniero', 'KO2', 'ry-wc-city-select'),
		_x('Komola-Koura', 'KO2', 'ry-wc-city-select'),
		_x('Koumana', 'KO2', 'ry-wc-city-select'),
		_x('Sanguiana', 'KO2', 'ry-wc-city-select'),
	],
	'LAPR' => [
		_x('Dalein', 'LAPR', 'ry-wc-city-select'),
		_x('Diari', 'LAPR', 'ry-wc-city-select'),
		_x('Garambe', 'LAPR', 'ry-wc-city-select'),
		_x('Hafia', 'LAPR', 'ry-wc-city-select'),
		_x('Kaalan', 'LAPR', 'ry-wc-city-select'),
		_x('Kouramangui', 'LAPR', 'ry-wc-city-select'),
		_x('Popodara', 'LAPR', 'ry-wc-city-select'),
		_x('Tountouroun', 'LAPR', 'ry-wc-city-select'),
	],
	'LEPR' => [
		_x('Balaya', 'LEPR', 'ry-wc-city-select'),
		_x('Djountou', 'LEPR', 'ry-wc-city-select'),
		_x('Herico', 'LEPR', 'ry-wc-city-select'),
		_x('Korbe', 'LEPR', 'ry-wc-city-select'),
		_x('Manda', 'LEPR', 'ry-wc-city-select'),
		_x('Parawol', 'LEPR', 'ry-wc-city-select'),
		_x('Sagale', 'LEPR', 'ry-wc-city-select'),
		_x('Tyanguel-Bori', 'LEPR', 'ry-wc-city-select'),
	],
	'LO' => [
		_x('Bossou', 'LO', 'ry-wc-city-select'),
		_x('Gama', 'LO', 'ry-wc-city-select'),
		_x('Gueassou', 'LO', 'ry-wc-city-select'),
		_x('Kokota', 'LO', 'ry-wc-city-select'),
		_x('Lain', 'LO', 'ry-wc-city-select'),
		_x('NZoo', 'LO', 'ry-wc-city-select'),
		_x('Tounkarata', 'LO', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Balizia', 'MA', 'ry-wc-city-select'),
		_x('Binikala', 'MA', 'ry-wc-city-select'),
		_x('Bofossou', 'MA', 'ry-wc-city-select'),
		_x('Daro', 'MA', 'ry-wc-city-select'),
		_x('Fassankoni', 'MA', 'ry-wc-city-select'),
		_x('Kouankan', 'MA', 'ry-wc-city-select'),
		_x('Koyamah', 'MA', 'ry-wc-city-select'),
		_x('NZebela', 'MA', 'ry-wc-city-select'),
		_x('Ouremai', 'MA', 'ry-wc-city-select'),
		_x('Panziazou', 'MA', 'ry-wc-city-select'),
		_x('Sengbedou', 'MA', 'ry-wc-city-select'),
		_x('Seredou', 'MA', 'ry-wc-city-select'),
		_x('Vasseredou', 'MA', 'ry-wc-city-select'),
		_x('Watanka', 'MA', 'ry-wc-city-select'),
	],
	'MAPR' => [
		_x('Balaki', 'MAPR', 'ry-wc-city-select'),
		_x('Donghol-Sigon', 'MAPR', 'ry-wc-city-select'),
		_x('Dougountouny', 'MAPR', 'ry-wc-city-select'),
		_x('Fougou', 'MAPR', 'ry-wc-city-select'),
		_x('Gadha-Woundou', 'MAPR', 'ry-wc-city-select'),
		_x('Gayah', 'MAPR', 'ry-wc-city-select'),
		_x('Hidayatou', 'MAPR', 'ry-wc-city-select'),
		_x('Lebekere', 'MAPR', 'ry-wc-city-select'),
		_x('Linsan', 'MAPR', 'ry-wc-city-select'),
		_x('Madina-Wora', 'MAPR', 'ry-wc-city-select'),
		_x('Matakaou', 'MAPR', 'ry-wc-city-select'),
		_x('Salambande', 'MAPR', 'ry-wc-city-select'),
		_x('Telire', 'MAPR', 'ry-wc-city-select'),
		_x('Yimbering', 'MAPR', 'ry-wc-city-select'),
	],
	'MAPR2' => [
		_x('Bouliwel', 'MAPR2', 'ry-wc-city-select'),
		_x('Dounet', 'MAPR2', 'ry-wc-city-select'),
		_x('Gongoret', 'MAPR2', 'ry-wc-city-select'),
		_x('Kegneko', 'MAPR2', 'ry-wc-city-select'),
		_x('Kollet', 'MAPR2', 'ry-wc-city-select'),
		_x('Konkoure', 'MAPR2', 'ry-wc-city-select'),
		_x('Nyagara', 'MAPR2', 'ry-wc-city-select'),
		_x('Oure-Kaba', 'MAPR2', 'ry-wc-city-select'),
		_x('Poredaka', 'MAPR2', 'ry-wc-city-select'),
		_x('Saramoussaya', 'MAPR2', 'ry-wc-city-select'),
		_x('Soyah', 'MAPR2', 'ry-wc-city-select'),
		_x('Teguereya', 'MAPR2', 'ry-wc-city-select'),
		_x('Timbo', 'MAPR2', 'ry-wc-city-select'),
		_x('Tolo', 'MAPR2', 'ry-wc-city-select'),
	],
	'MAPR3' => [
		_x('Balandougouba', 'MAPR3', 'ry-wc-city-select'),
		_x('Faralako', 'MAPR3', 'ry-wc-city-select'),
		_x('Kantoumania', 'MAPR3', 'ry-wc-city-select'),
		_x('Koundian', 'MAPR3', 'ry-wc-city-select'),
		_x('Koundianakoro', 'MAPR3', 'ry-wc-city-select'),
		_x('Morodou', 'MAPR3', 'ry-wc-city-select'),
		_x('Niantania', 'MAPR3', 'ry-wc-city-select'),
		_x('Saladou', 'MAPR3', 'ry-wc-city-select'),
	],
	'NZPR' => [
		_x('Boola', 'NZPR', 'ry-wc-city-select'),
		_x('Bounouma', 'NZPR', 'ry-wc-city-select'),
		_x('Gouecke', 'NZPR', 'ry-wc-city-select'),
		_x('Kobela', 'NZPR', 'ry-wc-city-select'),
		_x('Koropara', 'NZPR', 'ry-wc-city-select'),
		_x('Pale', 'NZPR', 'ry-wc-city-select'),
		_x('Samoe', 'NZPR', 'ry-wc-city-select'),
		_x('Soulouta', 'NZPR', 'ry-wc-city-select'),
		_x('Womey', 'NZPR', 'ry-wc-city-select'),
		_x('Yalenzou', 'NZPR', 'ry-wc-city-select'),
	],
	'PI' => [
		_x('Bantignel', 'PI', 'ry-wc-city-select'),
		_x('Bourouwal-Tappe', 'PI', 'ry-wc-city-select'),
		_x('Dongol-Touma', 'PI', 'ry-wc-city-select'),
		_x('Ley-Miro', 'PI', 'ry-wc-city-select'),
		_x('Maci', 'PI', 'ry-wc-city-select'),
		_x('Ninguelande', 'PI', 'ry-wc-city-select'),
		_x('Noussy', 'PI', 'ry-wc-city-select'),
		_x('Sangareah', 'PI', 'ry-wc-city-select'),
		_x('Sintali', 'PI', 'ry-wc-city-select'),
		_x('Timbi-Madina', 'PI', 'ry-wc-city-select'),
		_x('Timbi-Touny', 'PI', 'ry-wc-city-select'),
	],
	'PRDU' => [
		_x('Falessade', 'PRDU', 'ry-wc-city-select'),
		_x('Khorira', 'PRDU', 'ry-wc-city-select'),
		_x('Kouriah', 'PRDU', 'ry-wc-city-select'),
		_x('Maneah', 'PRDU', 'ry-wc-city-select'),
		_x('Ouassou', 'PRDU', 'ry-wc-city-select'),
		_x('Tanene', 'PRDU', 'ry-wc-city-select'),
		_x('Tondon', 'PRDU', 'ry-wc-city-select'),
		_x('Wonkifong', 'PRDU', 'ry-wc-city-select'),
	],
	'PRFO' => [
		_x('Alassoya', 'PRFO', 'ry-wc-city-select'),
		_x('Benty', 'PRFO', 'ry-wc-city-select'),
		_x('Kaback', 'PRFO', 'ry-wc-city-select'),
		_x('Kakossa', 'PRFO', 'ry-wc-city-select'),
		_x('Kallia', 'PRFO', 'ry-wc-city-select'),
		_x('Maferinya', 'PRFO', 'ry-wc-city-select'),
		_x('Moussaya', 'PRFO', 'ry-wc-city-select'),
		_x('Sikhourou', 'PRFO', 'ry-wc-city-select'),
	],
	'PRGU' => [
		_x('Bolodou', 'PRGU', 'ry-wc-city-select'),
		_x('Fangamadou', 'PRGU', 'ry-wc-city-select'),
		_x('Guendembou', 'PRGU', 'ry-wc-city-select'),
		_x('Kassadou', 'PRGU', 'ry-wc-city-select'),
		_x('Koundou', 'PRGU', 'ry-wc-city-select'),
		_x('Nongoa', 'PRGU', 'ry-wc-city-select'),
		_x('Ouende-Kenema', 'PRGU', 'ry-wc-city-select'),
		_x('Tekoulo', 'PRGU', 'ry-wc-city-select'),
		_x('Termessadou-Dibo', 'PRGU', 'ry-wc-city-select'),
	],
	'SIPR' => [
		_x('Bankon', 'SIPR', 'ry-wc-city-select'),
		_x('Dialakoro', 'SIPR', 'ry-wc-city-select'),
		_x('Doko', 'SIPR', 'ry-wc-city-select'),
		_x('Doura', 'SIPR', 'ry-wc-city-select'),
		_x('Franwalia', 'SIPR', 'ry-wc-city-select'),
		_x('Kiniebakoura', 'SIPR', 'ry-wc-city-select'),
		_x('Kinieran', 'SIPR', 'ry-wc-city-select'),
		_x('Kintian', 'SIPR', 'ry-wc-city-select'),
		_x('Malea', 'SIPR', 'ry-wc-city-select'),
		_x('Naboun', 'SIPR', 'ry-wc-city-select'),
		_x('Niagassola', 'SIPR', 'ry-wc-city-select'),
		_x('Niandankoro', 'SIPR', 'ry-wc-city-select'),
		_x('Norassoba', 'SIPR', 'ry-wc-city-select'),
		_x('Sansando', 'SIPR', 'ry-wc-city-select'),
		_x('Siguiri-Centre', 'SIPR', 'ry-wc-city-select'),
		_x('Siguirini', 'SIPR', 'ry-wc-city-select'),
	],
	'TEPR' => [
		_x('Banguingny', 'TEPR', 'ry-wc-city-select'),
		_x('Daramagnaky', 'TEPR', 'ry-wc-city-select'),
		_x('Gougoudje', 'TEPR', 'ry-wc-city-select'),
		_x('Koba', 'TEPR', 'ry-wc-city-select'),
		_x('Konsotamy', 'TEPR', 'ry-wc-city-select'),
		_x('Missira', 'TEPR', 'ry-wc-city-select'),
		_x('Santou', 'TEPR', 'ry-wc-city-select'),
		_x('Sarekaly', 'TEPR', 'ry-wc-city-select'),
		_x('Sinta', 'TEPR', 'ry-wc-city-select'),
		_x('Tarihoye', 'TEPR', 'ry-wc-city-select'),
		_x('Thionthian', 'TEPR', 'ry-wc-city-select'),
	],
	'TOPR' => [
		_x('Daralabe', 'TOPR', 'ry-wc-city-select'),
		_x('Fatako', 'TOPR', 'ry-wc-city-select'),
		_x('Fello-Koundoua', 'TOPR', 'ry-wc-city-select'),
		_x('Kansangui', 'TOPR', 'ry-wc-city-select'),
		_x('Koin', 'TOPR', 'ry-wc-city-select'),
		_x('Kolangui', 'TOPR', 'ry-wc-city-select'),
		_x('Konah', 'TOPR', 'ry-wc-city-select'),
		_x('Kouratongo', 'TOPR', 'ry-wc-city-select'),
		_x('Tangali', 'TOPR', 'ry-wc-city-select'),
	],
	'YO' => [
		_x('Bheeta', 'YO', 'ry-wc-city-select'),
		_x('Dieke', 'YO', 'ry-wc-city-select'),
		_x('Koule', 'YO', 'ry-wc-city-select'),
		_x('Pela', 'YO', 'ry-wc-city-select'),
	],
	'KIRE' => [
		_x('Coyah', 'KIRE', 'ry-wc-city-select'),
	],
	]
];