<?php
/**
 * Hellenic Republic places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'GR' => [
	'CH' => [
		_x('Dimos Chios', 'CH', 'ry-wc-city-select'),
		_x('Dimos Oinousses', 'CH', 'ry-wc-city-select'),
		_x('Dimos Psara', 'CH', 'ry-wc-city-select'),
	],
	'DO' => [
		_x('Dimos Agathonisi', 'DO', 'ry-wc-city-select'),
		_x('Dimos Astypalaia', 'DO', 'ry-wc-city-select'),
		_x('Dimos Chalki', 'DO', 'ry-wc-city-select'),
		_x('Dimos Kalymnos', 'DO', 'ry-wc-city-select'),
		_x('Dimos Karpathos', 'DO', 'ry-wc-city-select'),
		_x('Dimos Kasos', 'DO', 'ry-wc-city-select'),
		_x('Dimos Kos', 'DO', 'ry-wc-city-select'),
		_x('Dimos Leipsoi', 'DO', 'ry-wc-city-select'),
		_x('Dimos Leros', 'DO', 'ry-wc-city-select'),
		_x('Dimos Nisyros', 'DO', 'ry-wc-city-select'),
		_x('Dimos Patmos', 'DO', 'ry-wc-city-select'),
		_x('Dimos Rhodes', 'DO', 'ry-wc-city-select'),
		_x('Dimos Symi', 'DO', 'ry-wc-city-select'),
		_x('Dimos Tilos', 'DO', 'ry-wc-city-select'),
		_x('Kastelorizo', 'DO', 'ry-wc-city-select'),
	],
	'LE' => [
		_x('Dimos Lefkada', 'LE', 'ry-wc-city-select'),
		_x('Dimos Meganisi', 'LE', 'ry-wc-city-select'),
	],
	'LE2' => [
		_x('Dimos Agios Efstratios', 'LE2', 'ry-wc-city-select'),
		_x('Dimos Lemnos', 'LE2', 'ry-wc-city-select'),
		_x('Dimos Lesbos', 'LE2', 'ry-wc-city-select'),
	],
	'NOANAT' => [
		_x('Dimos Acharnes', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Dionysos', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Kropia', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Lavreotiki', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Marathon', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Markopoulo Mesogaias', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Oropos', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Paiania', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Pallini', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Rafina-Pikermi', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Saronikos', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Spata-Artemida', 'NOANAT', 'ry-wc-city-select'),
		_x('Dimos Vari-Voula-Vouliagmeni', 'NOANAT', 'ry-wc-city-select'),
	],
	'NOAT' => [
		_x('Dimos Agia Paraskevi', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Agia Varvara', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Agioi Anargyroi-Kamatero', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Agios Dimitrios', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Aigaleo', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Alimos', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Athens', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Chaidari', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Chalandri', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Dafni-Ymittos', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Elliniko-Argyroupoli', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Filadelfeia-Chalkidona', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Filothei-Psychiko', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Galatsi', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Glyfada', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Ilio', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Ilioupoli', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Irakleio', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Kaisariani', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Kallithea', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Kifisia', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Lykovrysi-Pefki', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Marousi', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Metamorfosi', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Moschato-Tavros', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Nea Ionia', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Nea Smyrni', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Palaio Faliro', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Papagou-Cholargos', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Penteli', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Peristeri', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Petroupoli', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Vrilissia', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Vyronas', 'NOAT', 'ry-wc-city-select'),
		_x('Dimos Zografos', 'NOAT', 'ry-wc-city-select'),
	],
	'NOAC' => [
		_x('Dimos Aigialeia', 'NOAC', 'ry-wc-city-select'),
		_x('Dimos Erymanthos', 'NOAC', 'ry-wc-city-select'),
		_x('Dimos Kalavryta', 'NOAC', 'ry-wc-city-select'),
		_x('Dimos Patras', 'NOAC', 'ry-wc-city-select'),
		_x('Dimos West Achaea', 'NOAC', 'ry-wc-city-select'),
	],
	'NOAIKAAK' => [
		_x('Dimos Agrinio', 'NOAIKAAK', 'ry-wc-city-select'),
		_x('Dimos Aktio-Vonitsa', 'NOAIKAAK', 'ry-wc-city-select'),
		_x('Dimos Amfilochia', 'NOAIKAAK', 'ry-wc-city-select'),
		_x('Dimos Missolonghi', 'NOAIKAAK', 'ry-wc-city-select'),
		_x('Dimos Nafpaktia', 'NOAIKAAK', 'ry-wc-city-select'),
		_x('Dimos Thermo', 'NOAIKAAK', 'ry-wc-city-select'),
		_x('Dimos Xiromero', 'NOAIKAAK', 'ry-wc-city-select'),
	],
	'NOAR' => [
		_x('Dimos Argos-Mykines', 'NOAR', 'ry-wc-city-select'),
		_x('Dimos Epidaurus', 'NOAR', 'ry-wc-city-select'),
		_x('Dimos Ermionida', 'NOAR', 'ry-wc-city-select'),
		_x('Dimos Nafplio', 'NOAR', 'ry-wc-city-select'),
	],
	'NOAR2' => [
		_x('Dimos Gortynia', 'NOAR2', 'ry-wc-city-select'),
		_x('Dimos Megalopoli', 'NOAR2', 'ry-wc-city-select'),
		_x('Dimos North Kynouria', 'NOAR2', 'ry-wc-city-select'),
		_x('Dimos South Kynouria', 'NOAR2', 'ry-wc-city-select'),
		_x('Dimos Tripoli', 'NOAR2', 'ry-wc-city-select'),
	],
	'NOAR3' => [
		_x('Dimos Artas', 'NOAR3', 'ry-wc-city-select'),
		_x('Dimos Central Tzoumerka', 'NOAR3', 'ry-wc-city-select'),
		_x('Dimos Georgios Karaiskakis', 'NOAR3', 'ry-wc-city-select'),
		_x('Dimos Nikolaos Skoufas', 'NOAR3', 'ry-wc-city-select'),
	],
	'NOAT2' => [
		_x('Dimos Aspropyrgos', 'NOAT2', 'ry-wc-city-select'),
		_x('Dimos Elefsina', 'NOAT2', 'ry-wc-city-select'),
		_x('Dimos Fyli', 'NOAT2', 'ry-wc-city-select'),
		_x('Dimos Mandra-Eidyllia', 'NOAT2', 'ry-wc-city-select'),
		_x('Dimos Megara', 'NOAT2', 'ry-wc-city-select'),
	],
	'NOCH' => [
		_x('Dimos Aristotelis', 'NOCH', 'ry-wc-city-select'),
		_x('Dimos Kassandra', 'NOCH', 'ry-wc-city-select'),
		_x('Dimos Nea Propontida', 'NOCH', 'ry-wc-city-select'),
		_x('Dimos Polygyros', 'NOCH', 'ry-wc-city-select'),
		_x('Dimos Sithonia', 'NOCH', 'ry-wc-city-select'),
	],
	'NOCH2' => [
		_x('Chania', 'NOCH2', 'ry-wc-city-select'),
		_x('Dimos Apokoronas', 'NOCH2', 'ry-wc-city-select'),
		_x('Dimos Gavdos', 'NOCH2', 'ry-wc-city-select'),
		_x('Dimos Kantanos-Selino', 'NOCH2', 'ry-wc-city-select'),
		_x('Dimos Kissamos', 'NOCH2', 'ry-wc-city-select'),
		_x('Dimos Platanias', 'NOCH2', 'ry-wc-city-select'),
		_x('Dimos Sfakia', 'NOCH2', 'ry-wc-city-select'),
	],
	'NODR' => [
		_x('Dimos Doxato', 'NODR', 'ry-wc-city-select'),
		_x('Dimos Drama', 'NODR', 'ry-wc-city-select'),
		_x('Dimos Kato Nevrokopi', 'NODR', 'ry-wc-city-select'),
		_x('Dimos Paranesti', 'NODR', 'ry-wc-city-select'),
		_x('Dimos Prosotsani', 'NODR', 'ry-wc-city-select'),
	],
	'NOEV' => [
		_x('Dimos Alexandroupoli', 'NOEV', 'ry-wc-city-select'),
		_x('Dimos Didymoteicho', 'NOEV', 'ry-wc-city-select'),
		_x('Dimos Orestiada', 'NOEV', 'ry-wc-city-select'),
		_x('Dimos Samothrace', 'NOEV', 'ry-wc-city-select'),
		_x('Dimos Soufli', 'NOEV', 'ry-wc-city-select'),
	],
	'NOEV2' => [
		_x('Dimos Agrafa', 'NOEV2', 'ry-wc-city-select'),
		_x('Dimos Karpenisi', 'NOEV2', 'ry-wc-city-select'),
	],
	'NOEV3' => [
		_x('Dimos Chalcis', 'NOEV3', 'ry-wc-city-select'),
		_x('Dimos Dirfys-Messapia', 'NOEV3', 'ry-wc-city-select'),
		_x('Dimos Eretria', 'NOEV3', 'ry-wc-city-select'),
		_x('Dimos Istiaia-Aidipsos', 'NOEV3', 'ry-wc-city-select'),
		_x('Dimos Karystos', 'NOEV3', 'ry-wc-city-select'),
		_x('Dimos Kymi-Aliveri', 'NOEV3', 'ry-wc-city-select'),
		_x('Dimos Mantoudi-Limni-Agia Anna', 'NOEV3', 'ry-wc-city-select'),
		_x('Dimos Skyros', 'NOEV3', 'ry-wc-city-select'),
	],
	'NOFL' => [
		_x('Dimos Amyntaio', 'NOFL', 'ry-wc-city-select'),
		_x('Dimos Florina', 'NOFL', 'ry-wc-city-select'),
		_x('Dimos Prespes', 'NOFL', 'ry-wc-city-select'),
	],
	'NOFO' => [
		_x('Delphi', 'NOFO', 'ry-wc-city-select'),
		_x('Dimos Dorida', 'NOFO', 'ry-wc-city-select'),
	],
	'NOFT' => [
		_x('Dimos Amfikleia-Elateia', 'NOFT', 'ry-wc-city-select'),
		_x('Dimos Domokos', 'NOFT', 'ry-wc-city-select'),
		_x('Dimos Lamia', 'NOFT', 'ry-wc-city-select'),
		_x('Dimos Lokroi', 'NOFT', 'ry-wc-city-select'),
		_x('Dimos Makrakomi', 'NOFT', 'ry-wc-city-select'),
		_x('Dimos Molos-Agios Konstantinos', 'NOFT', 'ry-wc-city-select'),
		_x('Dimos Stylida', 'NOFT', 'ry-wc-city-select'),
	],
	'NOGR' => [
		_x('Dimos Deskati', 'NOGR', 'ry-wc-city-select'),
		_x('Dimos Grevena', 'NOGR', 'ry-wc-city-select'),
	],
	'NOIL' => [
		_x('Dimos Andravida-Kyllini', 'NOIL', 'ry-wc-city-select'),
		_x('Dimos Andritsaina-Krestena', 'NOIL', 'ry-wc-city-select'),
		_x('Dimos Ilida (Dimos Ilidas)', 'NOIL', 'ry-wc-city-select'),
		_x('Dimos Olympia', 'NOIL', 'ry-wc-city-select'),
		_x('Dimos Pineios', 'NOIL', 'ry-wc-city-select'),
		_x('Dimos Pyrgos', 'NOIL', 'ry-wc-city-select'),
		_x('Dimos Zacharo', 'NOIL', 'ry-wc-city-select'),
	],
	'NOIM' => [
		_x('Dimos Alexandreia', 'NOIM', 'ry-wc-city-select'),
		_x('Dimos Naousa', 'NOIM', 'ry-wc-city-select'),
		_x('Dimos Veroia', 'NOIM', 'ry-wc-city-select'),
	],
	'NOIO' => [
		_x('Dimos Dodoni', 'NOIO', 'ry-wc-city-select'),
		_x('Dimos Ioannina', 'NOIO', 'ry-wc-city-select'),
		_x('Dimos Konitsa', 'NOIO', 'ry-wc-city-select'),
		_x('Dimos Metsovo', 'NOIO', 'ry-wc-city-select'),
		_x('Dimos North Tzoumerka', 'NOIO', 'ry-wc-city-select'),
		_x('Dimos Pogoni', 'NOIO', 'ry-wc-city-select'),
		_x('Dimos Zagori', 'NOIO', 'ry-wc-city-select'),
		_x('Dimos Zitsa', 'NOIO', 'ry-wc-city-select'),
	],
	'NOIR' => [
		_x('Chersonisos', 'NOIR', 'ry-wc-city-select'),
		_x('Dimos Archanes-Asterousia', 'NOIR', 'ry-wc-city-select'),
		_x('Dimos Faistos', 'NOIR', 'ry-wc-city-select'),
		_x('Dimos Gortyna', 'NOIR', 'ry-wc-city-select'),
		_x('Dimos Heraklion', 'NOIR', 'ry-wc-city-select'),
		_x('Dimos Malevizi', 'NOIR', 'ry-wc-city-select'),
		_x('Dimos Minoa Pediada', 'NOIR', 'ry-wc-city-select'),
		_x('Dimos Viannos', 'NOIR', 'ry-wc-city-select'),
	],
	'NOKA' => [
		_x('Dimos Argithea', 'NOKA', 'ry-wc-city-select'),
		_x('Dimos Karditsa', 'NOKA', 'ry-wc-city-select'),
		_x('Dimos Lake Plastiras', 'NOKA', 'ry-wc-city-select'),
		_x('Dimos Mouzaki', 'NOKA', 'ry-wc-city-select'),
		_x('Dimos Palamas', 'NOKA', 'ry-wc-city-select'),
		_x('Dimos Sofades', 'NOKA', 'ry-wc-city-select'),
	],
	'NOKA2' => [
		_x('Dimos Kastoria', 'NOKA2', 'ry-wc-city-select'),
		_x('Dimos Nestorio', 'NOKA2', 'ry-wc-city-select'),
		_x('Dimos Orestida', 'NOKA2', 'ry-wc-city-select'),
	],
	'NOKA3' => [
		_x('Dimos Kavala', 'NOKA3', 'ry-wc-city-select'),
		_x('Dimos Nestos', 'NOKA3', 'ry-wc-city-select'),
		_x('Dimos Pangaio', 'NOKA3', 'ry-wc-city-select'),
		_x('Thasos', 'NOKA3', 'ry-wc-city-select'),
	],
	'NOKE' => [
		_x('Dimos Ithaca', 'NOKE', 'ry-wc-city-select'),
		_x('Dimos Kefalonia', 'NOKE', 'ry-wc-city-select'),
	],
	'NOKE2' => [
		_x('Dimos Corfu', 'NOKE2', 'ry-wc-city-select'),
		_x('Dimos Paxoi', 'NOKE2', 'ry-wc-city-select'),
	],
	'NOKI' => [
		_x('Dimos Kilkis', 'NOKI', 'ry-wc-city-select'),
		_x('Dimos Paionia', 'NOKI', 'ry-wc-city-select'),
	],
	'NOKO' => [
		_x('Dimos Corinth', 'NOKO', 'ry-wc-city-select'),
		_x('Dimos Loutraki-Agioi Theodoroi', 'NOKO', 'ry-wc-city-select'),
		_x('Dimos Nemea', 'NOKO', 'ry-wc-city-select'),
		_x('Dimos Sikyona', 'NOKO', 'ry-wc-city-select'),
		_x('Dimos Velo-Vocha', 'NOKO', 'ry-wc-city-select'),
		_x('Dimos Xylokastro-Evrostina', 'NOKO', 'ry-wc-city-select'),
	],
	'NOKO2' => [
		_x('Dimos Eordaia', 'NOKO2', 'ry-wc-city-select'),
		_x('Dimos Kozani', 'NOKO2', 'ry-wc-city-select'),
		_x('Dimos Servia-Velventos', 'NOKO2', 'ry-wc-city-select'),
		_x('Dimos Voio', 'NOKO2', 'ry-wc-city-select'),
	],
	'NOKY' => [
		_x('Dimos Amorgos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Anafi', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Andros', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Antiparos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Folegandros', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Ios', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Kea', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Kimolos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Kythnos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Milos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Mykonos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Naxos and Lesser Cyclades', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Paros', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Santorini', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Serifos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Sifnos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Sikinos', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Syros-Ermoupoli', 'NOKY', 'ry-wc-city-select'),
		_x('Dimos Tinos', 'NOKY', 'ry-wc-city-select'),
	],
	'NOLA' => [
		_x('Dimos East Mani', 'NOLA', 'ry-wc-city-select'),
		_x('Dimos Elafonisos', 'NOLA', 'ry-wc-city-select'),
		_x('Dimos Evrotas', 'NOLA', 'ry-wc-city-select'),
		_x('Dimos Monemvasia', 'NOLA', 'ry-wc-city-select'),
		_x('Dimos Sparti', 'NOLA', 'ry-wc-city-select'),
	],
	'NOLA2' => [
		_x('Dimos Agia', 'NOLA2', 'ry-wc-city-select'),
		_x('Dimos Elassona', 'NOLA2', 'ry-wc-city-select'),
		_x('Dimos Farsala', 'NOLA2', 'ry-wc-city-select'),
		_x('Dimos Kileler', 'NOLA2', 'ry-wc-city-select'),
		_x('Dimos Larissa', 'NOLA2', 'ry-wc-city-select'),
		_x('Dimos Tempi', 'NOLA2', 'ry-wc-city-select'),
		_x('Dimos Tyrnavos', 'NOLA2', 'ry-wc-city-select'),
	],
	'NOLA3' => [
		_x('Dimos Agios Nikolaos', 'NOLA3', 'ry-wc-city-select'),
		_x('Dimos Ierapetra', 'NOLA3', 'ry-wc-city-select'),
		_x('Dimos Oropedio Lasithiou', 'NOLA3', 'ry-wc-city-select'),
		_x('Dimos Siteia', 'NOLA3', 'ry-wc-city-select'),
	],
	'NOMA' => [
		_x('Dimos Almyros', 'NOMA', 'ry-wc-city-select'),
		_x('Dimos Alonnisos', 'NOMA', 'ry-wc-city-select'),
		_x('Dimos Rigas Feraios', 'NOMA', 'ry-wc-city-select'),
		_x('Dimos Skiathos', 'NOMA', 'ry-wc-city-select'),
		_x('Dimos Skopelos', 'NOMA', 'ry-wc-city-select'),
		_x('Dimos South Pelion', 'NOMA', 'ry-wc-city-select'),
		_x('Dimos Volos', 'NOMA', 'ry-wc-city-select'),
		_x('Dimos Zagora-Mouresi', 'NOMA', 'ry-wc-city-select'),
	],
	'NOME' => [
		_x('Dimos Kalamata', 'NOME', 'ry-wc-city-select'),
		_x('Dimos Messene', 'NOME', 'ry-wc-city-select'),
		_x('Dimos Oichalia', 'NOME', 'ry-wc-city-select'),
		_x('Dimos Pylos-Nestoras', 'NOME', 'ry-wc-city-select'),
		_x('Dimos Trifylia', 'NOME', 'ry-wc-city-select'),
		_x('Dimos West Mani', 'NOME', 'ry-wc-city-select'),
	],
	'NOPE' => [
		_x('Dimos Almopia', 'NOPE', 'ry-wc-city-select'),
		_x('Dimos Edessa', 'NOPE', 'ry-wc-city-select'),
		_x('Dimos Pella', 'NOPE', 'ry-wc-city-select'),
		_x('Dimos Skydra', 'NOPE', 'ry-wc-city-select'),
	],
	'NOPI' => [
		_x('Dimos Dio-Olympos', 'NOPI', 'ry-wc-city-select'),
		_x('Dimos Katerini', 'NOPI', 'ry-wc-city-select'),
		_x('Dimos Pydna-Kolindros', 'NOPI', 'ry-wc-city-select'),
	],
	'NOPI2' => [
		_x('Dimos Aegina', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Agkistri', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Hydra', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Keratsini-Drapetsona', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Korydallos', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Nikaia-Agios Ioannis Rentis', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Perama', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Piraeus', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Poros', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Salaminas', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Spetses', 'NOPI2', 'ry-wc-city-select'),
		_x('Dimos Troizinia-Methana', 'NOPI2', 'ry-wc-city-select'),
		_x('Kythira', 'NOPI2', 'ry-wc-city-select'),
	],
	'NOPR' => [
		_x('Dimos Parga', 'NOPR', 'ry-wc-city-select'),
		_x('Dimos Preveza', 'NOPR', 'ry-wc-city-select'),
		_x('Dimos Ziros', 'NOPR', 'ry-wc-city-select'),
	],
	'NORE' => [
		_x('Dimos Agios Vasileios', 'NORE', 'ry-wc-city-select'),
		_x('Dimos Amari', 'NORE', 'ry-wc-city-select'),
		_x('Dimos Anogeia', 'NORE', 'ry-wc-city-select'),
		_x('Dimos Mylopotamos', 'NORE', 'ry-wc-city-select'),
		_x('Dimos Rethymno', 'NORE', 'ry-wc-city-select'),
	],
	'NORO' => [
		_x('Dimos Arriana', 'NORO', 'ry-wc-city-select'),
		_x('Dimos Iasmos', 'NORO', 'ry-wc-city-select'),
		_x('Dimos Komotini', 'NORO', 'ry-wc-city-select'),
		_x('Dimos Maroneia-Sapes', 'NORO', 'ry-wc-city-select'),
	],
	'NOSA' => [
		_x('Dimos Fournoi Korseon', 'NOSA', 'ry-wc-city-select'),
		_x('Dimos Samos', 'NOSA', 'ry-wc-city-select'),
		_x('Ikaria', 'NOSA', 'ry-wc-city-select'),
	],
	'NOSE' => [
		_x('Dimos Amfipoli', 'NOSE', 'ry-wc-city-select'),
		_x('Dimos Emmanouil Pappas', 'NOSE', 'ry-wc-city-select'),
		_x('Dimos Irakleia', 'NOSE', 'ry-wc-city-select'),
		_x('Dimos Nea Zichni', 'NOSE', 'ry-wc-city-select'),
		_x('Dimos Serres', 'NOSE', 'ry-wc-city-select'),
		_x('Dimos Sintiki', 'NOSE', 'ry-wc-city-select'),
		_x('Dimos Visaltia', 'NOSE', 'ry-wc-city-select'),
	],
	'NOTH' => [
		_x('Dimos Filiates', 'NOTH', 'ry-wc-city-select'),
		_x('Dimos Igoumenitsa', 'NOTH', 'ry-wc-city-select'),
		_x('Dimos Souli', 'NOTH', 'ry-wc-city-select'),
	],
	'NOTH2' => [
		_x('Dimos Ampelokipoi-Menemeni', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Chalkidona', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Delta', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Kalamaria', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Kordelio-Evosmos', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Lagkadas', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Neapoli-Sykies', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Oraiokastro', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Pavlos Melas', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Pylaia-Chortiatis', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Thermaikos', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Thermi', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Thessaloniki', 'NOTH2', 'ry-wc-city-select'),
		_x('Dimos Volvi', 'NOTH2', 'ry-wc-city-select'),
	],
	'NOVO' => [
		_x('Dimos Aliartos', 'NOVO', 'ry-wc-city-select'),
		_x('Dimos Distomo-Arachova-Antikyra', 'NOVO', 'ry-wc-city-select'),
		_x('Dimos Livadeia', 'NOVO', 'ry-wc-city-select'),
		_x('Dimos Orchomenos', 'NOVO', 'ry-wc-city-select'),
		_x('Dimos Tanagra', 'NOVO', 'ry-wc-city-select'),
		_x('Dimos Thebes', 'NOVO', 'ry-wc-city-select'),
	],
	'NOXA' => [
		_x('Dimos Abdera', 'NOXA', 'ry-wc-city-select'),
		_x('Dimos Myki', 'NOXA', 'ry-wc-city-select'),
		_x('Dimos Topeiros', 'NOXA', 'ry-wc-city-select'),
		_x('Dimos Xanthi', 'NOXA', 'ry-wc-city-select'),
	],
	'NOZA' => [
		_x('Dimos Zakynthos', 'NOZA', 'ry-wc-city-select'),
	],
	'TR' => [
		_x('Dimos Farkadona', 'TR', 'ry-wc-city-select'),
		_x('Dimos Kalampaka', 'TR', 'ry-wc-city-select'),
		_x('Dimos Trikala', 'TR', 'ry-wc-city-select'),
		_x('Pyli', 'TR', 'ry-wc-city-select'),
	],
	]
];