<?php
/**
 * Republic of Guatemala places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'GT' => [
	'DEALVE' => [
		_x('Municipio de Cahabon', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Chahal', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Chisec', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Coban', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Fray Bartolome de las Casas', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Lanquin', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Panzos', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Raxruha', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de San Cristobal Verapaz', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de San Juan Chamelco', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de San Pedro Carcha', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Santa Catalina la Tinta', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Santa Cruz Verapaz', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Senahu', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Tactic', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Tamahu', 'DEALVE', 'ry-wc-city-select'),
		_x('Municipio de Tucuru', 'DEALVE', 'ry-wc-city-select'),
		_x('Raxruja', 'DEALVE', 'ry-wc-city-select'),
		_x('Santa Catarina La Tinta', 'DEALVE', 'ry-wc-city-select'),
	],
	'DEBAVE' => [
		_x('Municipio de Cubulco', 'DEBAVE', 'ry-wc-city-select'),
		_x('Municipio de El Chol', 'DEBAVE', 'ry-wc-city-select'),
		_x('Municipio de Granados', 'DEBAVE', 'ry-wc-city-select'),
		_x('Municipio de Purulha', 'DEBAVE', 'ry-wc-city-select'),
		_x('Municipio de Rabinal', 'DEBAVE', 'ry-wc-city-select'),
		_x('Municipio de Salama', 'DEBAVE', 'ry-wc-city-select'),
		_x('Municipio de San Jeronimo', 'DEBAVE', 'ry-wc-city-select'),
		_x('Municipio de San Miguel Chicaj', 'DEBAVE', 'ry-wc-city-select'),
	],
	'DECH' => [
		_x('Municipio de Acatenango', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Chimaltenango', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Comalapa', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de El Tejar', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Parramos', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Patzicia', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Patzun', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Pochuta', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de San Andres Itzapa', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de San Jose Poaquil', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de San Martin Jilotepeque', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Santa Apolonia', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Santa Cruz Balanya', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Tecpan Guatemala', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Yepocapa', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Zaragoza', 'DECH', 'ry-wc-city-select'),
		_x('San Juan Comalapa', 'DECH', 'ry-wc-city-select'),
	],
	'DECH2' => [
		_x('Municipio de Camotan', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Chiquimula', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Concepcion Las Minas', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Esquipulas', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Ipala', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Jocotan', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Olopa', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Quezaltepeque', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de San Jacinto', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de San Jose La Arada', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de San Juan la Ermita', 'DECH2', 'ry-wc-city-select'),
	],
	'DEPR' => [
		_x('Municipio de El Jicaro', 'DEPR', 'ry-wc-city-select'),
		_x('Municipio de El Progreso', 'DEPR', 'ry-wc-city-select'),
		_x('Municipio de Guastatoya', 'DEPR', 'ry-wc-city-select'),
		_x('Municipio de Morazan', 'DEPR', 'ry-wc-city-select'),
		_x('Municipio de San Agustin Acasaguastlan', 'DEPR', 'ry-wc-city-select'),
		_x('Municipio de San Antonio La Paz', 'DEPR', 'ry-wc-city-select'),
		_x('Municipio de San Cristobal Acasaguastlan', 'DEPR', 'ry-wc-city-select'),
		_x('Municipio de Sanarate', 'DEPR', 'ry-wc-city-select'),
		_x('Municipio de Sansare', 'DEPR', 'ry-wc-city-select'),
		_x('San Cristobal Acasguastlan', 'DEPR', 'ry-wc-city-select'),
	],
	'DEES' => [
		_x('Municipio de Escuintla', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Guanagazapa', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Iztapa', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de La Democracia', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de La Gomera', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Masagua', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Nueva Concepcion', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Palin', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de San Jose', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de San Vicente Pacaya', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Santa Lucia Cotzumalguapa', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Siquinala', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Tiquisate', 'DEES', 'ry-wc-city-select'),
		_x('Sipacate', 'DEES', 'ry-wc-city-select'),
	],
	'DEGU' => [
		_x('Lago de Amatitlan', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Amatitlan', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Chinautla', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Chuarrancho', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Fraijanes', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Guatemala', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Mixco', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Palencia', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Petapa', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de San Jose Pinula', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de San Jose del Golfo', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de San Juan Sacatepequez', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de San Pedro Ayampuc', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de San Pedro Sacatepequez', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de San Raymundo', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Santa Catarina Pinula', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Villa Canales', 'DEGU', 'ry-wc-city-select'),
		_x('Municipio de Villa Nueva', 'DEGU', 'ry-wc-city-select'),
	],
	'DEHU' => [
		_x('Municipio de Aguacatan', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Barillas', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Chiantla', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Colotenango', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Concepcion Huista', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Cuilco', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Huehuetenango', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Jacaltenango', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de La Democracia', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de La Libertad', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Malacatancito', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Nenton', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Antonio Huista', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Gaspar Ixchil', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Juan Atitan', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Juan Ixcoy', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Mateo Ixtatan', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Miguel Acatan', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Pedro Necta', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Rafael La Independencia', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Rafael Petzal', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Sebastian Coatan', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de San Sebastian Huehuetenango', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Santa Ana Huista', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Santa Barbara', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Santa Eulalia', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Santiago Chimaltenango', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Tectitan', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Todos Santos Cuchumatan', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Union Cantinil', 'DEHU', 'ry-wc-city-select'),
		_x('Municipio de Union Cantinil', 'DEHU', 'ry-wc-city-select'),
		_x('Municipo de San Ildefonso Ixtahuacan', 'DEHU', 'ry-wc-city-select'),
		_x('Petatan', 'DEHU', 'ry-wc-city-select'),
		_x('San Ildefonso Ixtahuacan', 'DEHU', 'ry-wc-city-select'),
		_x('San Pedro Soloma', 'DEHU', 'ry-wc-city-select'),
	],
	'DEIZ' => [
		_x('Municipio de El Estor', 'DEIZ', 'ry-wc-city-select'),
		_x('Municipio de Livingston', 'DEIZ', 'ry-wc-city-select'),
		_x('Municipio de Los Amates', 'DEIZ', 'ry-wc-city-select'),
		_x('Municipio de Morales', 'DEIZ', 'ry-wc-city-select'),
		_x('Municipio de Puerto Barrios', 'DEIZ', 'ry-wc-city-select'),
	],
	'DEJA' => [
		_x('Municipio de Jalapa', 'DEJA', 'ry-wc-city-select'),
		_x('Municipio de Mataquescuintla', 'DEJA', 'ry-wc-city-select'),
		_x('Municipio de Monjas', 'DEJA', 'ry-wc-city-select'),
		_x('Municipio de San Carlos Alzatate', 'DEJA', 'ry-wc-city-select'),
		_x('Municipio de San Luis Jilotepeque', 'DEJA', 'ry-wc-city-select'),
		_x('Municipio de San Manuel Chaparron', 'DEJA', 'ry-wc-city-select'),
		_x('Municipio de San Pedro Pinula', 'DEJA', 'ry-wc-city-select'),
	],
	'DEJU' => [
		_x('Municipio de Agua Blanca', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Asuncion Mita', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Atescatempa', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Comapa', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Conguaco', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de El Adelanto', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de El Progreso', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Jalpatagua', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Jerez', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Jutiapa', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Moyuta', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Pasaco', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Quesada', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de San Jose Acatempa', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Santa Catarina Mita', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Yupiltepeque', 'DEJU', 'ry-wc-city-select'),
		_x('Municipio de Zapotitlan', 'DEJU', 'ry-wc-city-select'),
	],
	'DEQU' => [
		_x('Municipio de Almolonga', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Cabrican', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Cajola', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Cantel', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Coatepeque', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Colomba', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Concepcion Chiquirichapa', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de El Palmar', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Flores Costa Cuca', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Genova', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Huitan', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de La Esperanza', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Olintepeque', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Palestina de los Altos', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Quetzaltenango', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Salcaja', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de San Carlos Sija', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de San Francisco La Union', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de San Juan Ostuncalco', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de San Martin Sacatepequez', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de San Mateo', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de San Miguel Siguila', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Sibilia', 'DEQU', 'ry-wc-city-select'),
		_x('Municipio de Zunil', 'DEQU', 'ry-wc-city-select'),
		_x('Municipo de San Juan Ostuncalco', 'DEQU', 'ry-wc-city-select'),
	],
	'DERE' => [
		_x('Municipio de Champerico', 'DERE', 'ry-wc-city-select'),
		_x('Municipio de El Asintal', 'DERE', 'ry-wc-city-select'),
		_x('Municipio de Nuevo San Carlos', 'DERE', 'ry-wc-city-select'),
		_x('Municipio de Retalhuleu', 'DERE', 'ry-wc-city-select'),
		_x('Municipio de San Andres Villa Seca', 'DERE', 'ry-wc-city-select'),
		_x('Municipio de San Felipe', 'DERE', 'ry-wc-city-select'),
		_x('Municipio de San Martin Zapotitlan', 'DERE', 'ry-wc-city-select'),
		_x('Municipio de San Sebastian', 'DERE', 'ry-wc-city-select'),
		_x('Municipio de Santa Cruz Mulua', 'DERE', 'ry-wc-city-select'),
	],
	'DESA' => [
		_x('Municipio de Alotenango', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Antigua Guatemala', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Ciudad Vieja', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Jocotenango', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Magdalena Milpas Altas', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Pastores', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de San Antonio Aguas Calientes', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de San Bartolome Milpas Altas', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de San Lucas Sacatepequez', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de San Miguel Duenas', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Santa Catarina Barahona', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Santa Lucia Milpas Altas', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Santa Maria de Jesus', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Santiago Sacatepequez', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Santo Domingo Xenacoj', 'DESA', 'ry-wc-city-select'),
		_x('Municipio de Sumpango', 'DESA', 'ry-wc-city-select'),
	],
	'DESAMA' => [
		_x('Municipio de Ayutla', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Catarina', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Comitancillo', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Concepcion Tutuapa', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de El Quetzal', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de El Rodeo', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de El Tumbador', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Esquipulas Palo Gordo', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Ixchiguan', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de La Blanca', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de La Reforma', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Malacatan', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Nuevo Progreso', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Ocos', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Pajapita', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Rio Blanco', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Antonio Sacatepequez', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Cristobal Cucho', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Jose Ojetenam', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Lorenzo', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Marcos', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Miguel Ixtahuacan', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Pablo', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Pedro Sacatepequez', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de San Rafael Pie de la Cuesta', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Sibinal', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Sipacapa', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Tacana', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Tajumulco', 'DESAMA', 'ry-wc-city-select'),
		_x('Municipio de Tejutla', 'DESAMA', 'ry-wc-city-select'),
	],
	'DESARO' => [
		_x('Municipio de Barberena', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Casillas', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Chiquimulilla', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Cuilapa', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Guazacapan', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Nueva Santa Rosa', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Oratorio', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Pueblo Nuevo Vinas', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de San Juan Tecuaco', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de San Rafael Las Flores', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Santa Cruz Naranjo', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Santa Maria Ixhuatan', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Santa Rosa de Lima', 'DESARO', 'ry-wc-city-select'),
		_x('Municipio de Taxisco', 'DESARO', 'ry-wc-city-select'),
	],
	'DESO' => [
		_x('Lago de Atitlan', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Concepcion', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Nahuala', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Panajachel', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de San Andres Semetabaj', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de San Antonio Palopo', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de San Jose Chacaya', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de San Juan La Laguna', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de San Lucas Toliman', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de San Marcos La Laguna', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de San Pablo La Laguna', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de San Pedro La Laguna', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Santa Catarina Ixtahuacan', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Santa Catarina Palopo', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Santa Clara La Laguna', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Santa Cruz La Laguna', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Santa Lucia Utatlan', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Santa Maria Visitacion', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Santiago Atitlan', 'DESO', 'ry-wc-city-select'),
		_x('Municipio de Solola', 'DESO', 'ry-wc-city-select'),
	],
	'DESU' => [
		_x('La Maquina', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Chicacao', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Cuyotenango', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Mazatenango', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Patulul', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Pueblo Nuevo', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Rio Bravo', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Samayac', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Antonio Suchitepequez', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Bernardino', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Francisco Zapotitlan', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Gabriel', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Jose El Idolo', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Juan Bautista', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Lorenzo', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Miguel Panan', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de San Pablo Jocopilas', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Santa Barbara', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Santo Domingo Suchitepequez', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Santo Tomas La Union', 'DESU', 'ry-wc-city-select'),
		_x('Municipio de Zunilito', 'DESU', 'ry-wc-city-select'),
	],
	'DETO' => [
		_x('Municipio de Momostenango', 'DETO', 'ry-wc-city-select'),
		_x('Municipio de San Andres Xecul', 'DETO', 'ry-wc-city-select'),
		_x('Municipio de San Bartolo Aguas Calientes', 'DETO', 'ry-wc-city-select'),
		_x('Municipio de San Cristobal Totonicapan', 'DETO', 'ry-wc-city-select'),
		_x('Municipio de San Francisco El Alto', 'DETO', 'ry-wc-city-select'),
		_x('Municipio de Santa Lucia La Reforma', 'DETO', 'ry-wc-city-select'),
		_x('Municipio de Santa Maria Chiquimula', 'DETO', 'ry-wc-city-select'),
		_x('Municipio de Totonicapan', 'DETO', 'ry-wc-city-select'),
	],
	'DEZA' => [
		_x('Municipio de Cabanas', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de Estanzuela', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de Gualan', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de Huite', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de La Union', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de Rio Hondo', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de San Diego', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de San Jorge', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de Teculutan', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de Usumatlan', 'DEZA', 'ry-wc-city-select'),
		_x('Municipio de Zacapa', 'DEZA', 'ry-wc-city-select'),
	],
	'DEDEPE' => [
		_x('Las Cruces', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de Dolores', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de El Chal', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de Flores', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de La Libertad', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de Melchor de Mencos', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de Poptun', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de San Andres', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de San Benito', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de San Francisco', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de San Jose', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de San Luis', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de Santa Ana', 'DEDEPE', 'ry-wc-city-select'),
		_x('Municipio de Sayaxche', 'DEDEPE', 'ry-wc-city-select'),
	],
	'DEDEQU' => [
		_x('Municipio de Canilla', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Chajul', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Chicaman', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Chiche', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Chichicastenango', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Chinique', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Cunen', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Ixcan', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Joyabaj', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Nebaj', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Pachalum', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Patzite', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Sacapulas', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de San Andres Sajcabaja', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de San Antonio Ilotenango', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de San Bartolome Jocotenango', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de San Juan Cotzal', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de San Pedro Jocopilas', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Santa Cruz del Quiche', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Uspantan', 'DEDEQU', 'ry-wc-city-select'),
		_x('Municipio de Zacualpa', 'DEDEQU', 'ry-wc-city-select'),
	],
	]
];