<?php
/**
 * Republic of Honduras places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'HN' => [
	'DEAT' => [
		_x('Arizona', 'DEAT', 'ry-wc-city-select'),
		_x('El Porvenir', 'DEAT', 'ry-wc-city-select'),
		_x('Esparta', 'DEAT', 'ry-wc-city-select'),
		_x('Jutiapa', 'DEAT', 'ry-wc-city-select'),
		_x('La Ceiba', 'DEAT', 'ry-wc-city-select'),
		_x('La Masica', 'DEAT', 'ry-wc-city-select'),
		_x('San Francisco', 'DEAT', 'ry-wc-city-select'),
		_x('Tela', 'DEAT', 'ry-wc-city-select'),
	],
	'DECH' => [
		_x('Apacilagua', 'DECH', 'ry-wc-city-select'),
		_x('Choluteca', 'DECH', 'ry-wc-city-select'),
		_x('Concepcion de Maria', 'DECH', 'ry-wc-city-select'),
		_x('Duyure', 'DECH', 'ry-wc-city-select'),
		_x('El Corpus', 'DECH', 'ry-wc-city-select'),
		_x('El Triunfo', 'DECH', 'ry-wc-city-select'),
		_x('Marcovia', 'DECH', 'ry-wc-city-select'),
		_x('Morolica', 'DECH', 'ry-wc-city-select'),
		_x('Namasigue', 'DECH', 'ry-wc-city-select'),
		_x('Orocuina', 'DECH', 'ry-wc-city-select'),
		_x('Pespire', 'DECH', 'ry-wc-city-select'),
		_x('San Antonio de Flores', 'DECH', 'ry-wc-city-select'),
		_x('San Isidro', 'DECH', 'ry-wc-city-select'),
		_x('San Jose', 'DECH', 'ry-wc-city-select'),
		_x('San Marcos de Colon', 'DECH', 'ry-wc-city-select'),
		_x('Santa Ana de Yusguare', 'DECH', 'ry-wc-city-select'),
	],
	'DECO' => [
		_x('Balfate', 'DECO', 'ry-wc-city-select'),
		_x('Bonito Oriental', 'DECO', 'ry-wc-city-select'),
		_x('Iriona', 'DECO', 'ry-wc-city-select'),
		_x('Limon', 'DECO', 'ry-wc-city-select'),
		_x('Municipio de Saba', 'DECO', 'ry-wc-city-select'),
		_x('Santa Fe', 'DECO', 'ry-wc-city-select'),
		_x('Santa Rosa de Aguan', 'DECO', 'ry-wc-city-select'),
		_x('Sonaguera', 'DECO', 'ry-wc-city-select'),
		_x('Tocoa', 'DECO', 'ry-wc-city-select'),
		_x('Trujillo', 'DECO', 'ry-wc-city-select'),
	],
	'DECO2' => [
		_x('Ajuterique', 'DECO2', 'ry-wc-city-select'),
		_x('Comayagua', 'DECO2', 'ry-wc-city-select'),
		_x('El Rosario', 'DECO2', 'ry-wc-city-select'),
		_x('Esquias', 'DECO2', 'ry-wc-city-select'),
		_x('Humuya', 'DECO2', 'ry-wc-city-select'),
		_x('La Libertad', 'DECO2', 'ry-wc-city-select'),
		_x('La Trinidad', 'DECO2', 'ry-wc-city-select'),
		_x('Lamani', 'DECO2', 'ry-wc-city-select'),
		_x('Las Lajas', 'DECO2', 'ry-wc-city-select'),
		_x('Lejamani', 'DECO2', 'ry-wc-city-select'),
		_x('Meambar', 'DECO2', 'ry-wc-city-select'),
		_x('Minas de Oro', 'DECO2', 'ry-wc-city-select'),
		_x('Ojos de Agua', 'DECO2', 'ry-wc-city-select'),
		_x('San Jeronimo', 'DECO2', 'ry-wc-city-select'),
		_x('San Jose de Comayagua', 'DECO2', 'ry-wc-city-select'),
		_x('San Jose del Potrero', 'DECO2', 'ry-wc-city-select'),
		_x('San Luis', 'DECO2', 'ry-wc-city-select'),
		_x('San Sebastian', 'DECO2', 'ry-wc-city-select'),
		_x('Siguatepeque', 'DECO2', 'ry-wc-city-select'),
		_x('Taulabe', 'DECO2', 'ry-wc-city-select'),
		_x('Villa de San Antonio', 'DECO2', 'ry-wc-city-select'),
	],
	'DECO3' => [
		_x('Cabanas', 'DECO3', 'ry-wc-city-select'),
		_x('Concepcion', 'DECO3', 'ry-wc-city-select'),
		_x('Copan Ruinas', 'DECO3', 'ry-wc-city-select'),
		_x('Corquin', 'DECO3', 'ry-wc-city-select'),
		_x('Cucuyagua', 'DECO3', 'ry-wc-city-select'),
		_x('Dolores', 'DECO3', 'ry-wc-city-select'),
		_x('Dulce Nombre', 'DECO3', 'ry-wc-city-select'),
		_x('El Paraiso', 'DECO3', 'ry-wc-city-select'),
		_x('Florida', 'DECO3', 'ry-wc-city-select'),
		_x('La Jigua', 'DECO3', 'ry-wc-city-select'),
		_x('La Union', 'DECO3', 'ry-wc-city-select'),
		_x('Nueva Arcadia', 'DECO3', 'ry-wc-city-select'),
		_x('San Agustin', 'DECO3', 'ry-wc-city-select'),
		_x('San Antonio', 'DECO3', 'ry-wc-city-select'),
		_x('San Jeronimo', 'DECO3', 'ry-wc-city-select'),
		_x('San Jose', 'DECO3', 'ry-wc-city-select'),
		_x('San Juan de Opoa', 'DECO3', 'ry-wc-city-select'),
		_x('San Nicolas', 'DECO3', 'ry-wc-city-select'),
		_x('San Pedro de Copan', 'DECO3', 'ry-wc-city-select'),
		_x('Santa Rita', 'DECO3', 'ry-wc-city-select'),
		_x('Santa Rosa de Copan', 'DECO3', 'ry-wc-city-select'),
		_x('Trinidad de Copan', 'DECO3', 'ry-wc-city-select'),
		_x('Veracruz', 'DECO3', 'ry-wc-city-select'),
	],
	'DECO4' => [
		_x('Choloma', 'DECO4', 'ry-wc-city-select'),
		_x('La Lima', 'DECO4', 'ry-wc-city-select'),
		_x('Omoa', 'DECO4', 'ry-wc-city-select'),
		_x('Pimienta', 'DECO4', 'ry-wc-city-select'),
		_x('Potrerillos', 'DECO4', 'ry-wc-city-select'),
		_x('Puerto Cortes', 'DECO4', 'ry-wc-city-select'),
		_x('San Antonio de Cortes', 'DECO4', 'ry-wc-city-select'),
		_x('San Francisco de Yojoa', 'DECO4', 'ry-wc-city-select'),
		_x('San Manuel', 'DECO4', 'ry-wc-city-select'),
		_x('San Pedro Sula', 'DECO4', 'ry-wc-city-select'),
		_x('Santa Cruz de Yojoa', 'DECO4', 'ry-wc-city-select'),
		_x('Villanueva', 'DECO4', 'ry-wc-city-select'),
	],
	'DEPA' => [
		_x('Alauca', 'DEPA', 'ry-wc-city-select'),
		_x('Danli', 'DEPA', 'ry-wc-city-select'),
		_x('El Paraiso', 'DEPA', 'ry-wc-city-select'),
		_x('Guinope', 'DEPA', 'ry-wc-city-select'),
		_x('Jacaleapa', 'DEPA', 'ry-wc-city-select'),
		_x('Liure', 'DEPA', 'ry-wc-city-select'),
		_x('Moroceli', 'DEPA', 'ry-wc-city-select'),
		_x('Municipio de Texiguat', 'DEPA', 'ry-wc-city-select'),
		_x('Oropoli', 'DEPA', 'ry-wc-city-select'),
		_x('Potrerillos', 'DEPA', 'ry-wc-city-select'),
		_x('San Antonio de Flores', 'DEPA', 'ry-wc-city-select'),
		_x('San Lucas', 'DEPA', 'ry-wc-city-select'),
		_x('San Matias', 'DEPA', 'ry-wc-city-select'),
		_x('Soledad', 'DEPA', 'ry-wc-city-select'),
		_x('Teupasenti', 'DEPA', 'ry-wc-city-select'),
		_x('Trojes', 'DEPA', 'ry-wc-city-select'),
		_x('Vado Ancho', 'DEPA', 'ry-wc-city-select'),
		_x('Yauyupe', 'DEPA', 'ry-wc-city-select'),
		_x('Yuscaran', 'DEPA', 'ry-wc-city-select'),
	],
	'DEFRMO' => [
		_x('Alubaren', 'DEFRMO', 'ry-wc-city-select'),
		_x('Cedros', 'DEFRMO', 'ry-wc-city-select'),
		_x('Curaren', 'DEFRMO', 'ry-wc-city-select'),
		_x('Distrito Central', 'DEFRMO', 'ry-wc-city-select'),
		_x('El Porvenir', 'DEFRMO', 'ry-wc-city-select'),
		_x('Guaimaca', 'DEFRMO', 'ry-wc-city-select'),
		_x('La Libertad', 'DEFRMO', 'ry-wc-city-select'),
		_x('La Venta', 'DEFRMO', 'ry-wc-city-select'),
		_x('Lepaterique', 'DEFRMO', 'ry-wc-city-select'),
		_x('Maraita', 'DEFRMO', 'ry-wc-city-select'),
		_x('Marale', 'DEFRMO', 'ry-wc-city-select'),
		_x('Nueva Armenia', 'DEFRMO', 'ry-wc-city-select'),
		_x('Ojojona', 'DEFRMO', 'ry-wc-city-select'),
		_x('Orica', 'DEFRMO', 'ry-wc-city-select'),
		_x('Reitoca', 'DEFRMO', 'ry-wc-city-select'),
		_x('Sabanagrande', 'DEFRMO', 'ry-wc-city-select'),
		_x('San Antonio de Oriente', 'DEFRMO', 'ry-wc-city-select'),
		_x('San Buenaventura', 'DEFRMO', 'ry-wc-city-select'),
		_x('San Ignacio', 'DEFRMO', 'ry-wc-city-select'),
		_x('San Juan de Flores', 'DEFRMO', 'ry-wc-city-select'),
		_x('San Miguelito', 'DEFRMO', 'ry-wc-city-select'),
		_x('Santa Ana', 'DEFRMO', 'ry-wc-city-select'),
		_x('Santa Lucia', 'DEFRMO', 'ry-wc-city-select'),
		_x('Talanga', 'DEFRMO', 'ry-wc-city-select'),
		_x('Tatumbla', 'DEFRMO', 'ry-wc-city-select'),
		_x('Valle de Angeles', 'DEFRMO', 'ry-wc-city-select'),
		_x('Vallecillo', 'DEFRMO', 'ry-wc-city-select'),
		_x('Villa de San Francisco', 'DEFRMO', 'ry-wc-city-select'),
	],
	'DEGRDI' => [
		_x('Ahuas', 'DEGRDI', 'ry-wc-city-select'),
		_x('Brus Laguna', 'DEGRDI', 'ry-wc-city-select'),
		_x('Juan Francisco Bulnes', 'DEGRDI', 'ry-wc-city-select'),
		_x('Puerto Lempira', 'DEGRDI', 'ry-wc-city-select'),
		_x('Villeda Morales', 'DEGRDI', 'ry-wc-city-select'),
		_x('Wampusirpi', 'DEGRDI', 'ry-wc-city-select'),
	],
	'DEIN' => [
		_x('Camasca', 'DEIN', 'ry-wc-city-select'),
		_x('Colomoncagua', 'DEIN', 'ry-wc-city-select'),
		_x('Concepcion', 'DEIN', 'ry-wc-city-select'),
		_x('Dolores', 'DEIN', 'ry-wc-city-select'),
		_x('Intibuca', 'DEIN', 'ry-wc-city-select'),
		_x('Jesus de Otoro', 'DEIN', 'ry-wc-city-select'),
		_x('La Esperanza', 'DEIN', 'ry-wc-city-select'),
		_x('Magdalena', 'DEIN', 'ry-wc-city-select'),
		_x('Masaguara', 'DEIN', 'ry-wc-city-select'),
		_x('San Antonio', 'DEIN', 'ry-wc-city-select'),
		_x('San Francisco de Opalaca', 'DEIN', 'ry-wc-city-select'),
		_x('San Isidro', 'DEIN', 'ry-wc-city-select'),
		_x('San Juan', 'DEIN', 'ry-wc-city-select'),
		_x('San Marcos de la Sierra', 'DEIN', 'ry-wc-city-select'),
		_x('San Miguelito', 'DEIN', 'ry-wc-city-select'),
		_x('Santa Lucia', 'DEIN', 'ry-wc-city-select'),
		_x('Yamaranguila', 'DEIN', 'ry-wc-city-select'),
	],
	'DEISBA' => [
		_x('Guanaja', 'DEISBA', 'ry-wc-city-select'),
		_x('Jose Santos Guardiola', 'DEISBA', 'ry-wc-city-select'),
		_x('Roatan', 'DEISBA', 'ry-wc-city-select'),
		_x('Utila', 'DEISBA', 'ry-wc-city-select'),
	],
	'DEPA2' => [
		_x('Aguanqueterique', 'DEPA2', 'ry-wc-city-select'),
		_x('Cabanas', 'DEPA2', 'ry-wc-city-select'),
		_x('Cane', 'DEPA2', 'ry-wc-city-select'),
		_x('Chinacla', 'DEPA2', 'ry-wc-city-select'),
		_x('Guajiquiro', 'DEPA2', 'ry-wc-city-select'),
		_x('La Paz', 'DEPA2', 'ry-wc-city-select'),
		_x('Lauterique', 'DEPA2', 'ry-wc-city-select'),
		_x('Marcala', 'DEPA2', 'ry-wc-city-select'),
		_x('Mercedes de Oriente', 'DEPA2', 'ry-wc-city-select'),
		_x('Opatoro', 'DEPA2', 'ry-wc-city-select'),
		_x('San Antonio del Norte', 'DEPA2', 'ry-wc-city-select'),
		_x('San Jose', 'DEPA2', 'ry-wc-city-select'),
		_x('San Juan', 'DEPA2', 'ry-wc-city-select'),
		_x('San Pedro de Tutule', 'DEPA2', 'ry-wc-city-select'),
		_x('Santa Ana', 'DEPA2', 'ry-wc-city-select'),
		_x('Santa Elena', 'DEPA2', 'ry-wc-city-select'),
		_x('Santa Maria', 'DEPA2', 'ry-wc-city-select'),
		_x('Santiago Puringla', 'DEPA2', 'ry-wc-city-select'),
		_x('Yarula', 'DEPA2', 'ry-wc-city-select'),
	],
	'DELE' => [
		_x('Belen', 'DELE', 'ry-wc-city-select'),
		_x('Candelaria', 'DELE', 'ry-wc-city-select'),
		_x('Cololaca', 'DELE', 'ry-wc-city-select'),
		_x('Erandique', 'DELE', 'ry-wc-city-select'),
		_x('Gracias', 'DELE', 'ry-wc-city-select'),
		_x('Gualcince', 'DELE', 'ry-wc-city-select'),
		_x('Guarita', 'DELE', 'ry-wc-city-select'),
		_x('La Campa', 'DELE', 'ry-wc-city-select'),
		_x('La Iguala', 'DELE', 'ry-wc-city-select'),
		_x('La Union', 'DELE', 'ry-wc-city-select'),
		_x('La Virtud', 'DELE', 'ry-wc-city-select'),
		_x('Las Flores', 'DELE', 'ry-wc-city-select'),
		_x('Lepaera', 'DELE', 'ry-wc-city-select'),
		_x('Mapulaca', 'DELE', 'ry-wc-city-select'),
		_x('Piraera', 'DELE', 'ry-wc-city-select'),
		_x('San Andres', 'DELE', 'ry-wc-city-select'),
		_x('San Francisco', 'DELE', 'ry-wc-city-select'),
		_x('San Juan Guarita', 'DELE', 'ry-wc-city-select'),
		_x('San Manuel Colohete', 'DELE', 'ry-wc-city-select'),
		_x('San Marcos de Caiquin', 'DELE', 'ry-wc-city-select'),
		_x('San Rafael', 'DELE', 'ry-wc-city-select'),
		_x('San Sebastian', 'DELE', 'ry-wc-city-select'),
		_x('Santa Cruz', 'DELE', 'ry-wc-city-select'),
		_x('Talgua', 'DELE', 'ry-wc-city-select'),
		_x('Tambla', 'DELE', 'ry-wc-city-select'),
		_x('Tomala', 'DELE', 'ry-wc-city-select'),
		_x('Valladolid', 'DELE', 'ry-wc-city-select'),
		_x('Virginia', 'DELE', 'ry-wc-city-select'),
	],
	'DEOC' => [
		_x('Belen Gualcho', 'DEOC', 'ry-wc-city-select'),
		_x('Concepcion', 'DEOC', 'ry-wc-city-select'),
		_x('Dolores Merendon', 'DEOC', 'ry-wc-city-select'),
		_x('Fraternidad', 'DEOC', 'ry-wc-city-select'),
		_x('La Encarnacion', 'DEOC', 'ry-wc-city-select'),
		_x('La Labor', 'DEOC', 'ry-wc-city-select'),
		_x('Lucerna', 'DEOC', 'ry-wc-city-select'),
		_x('Mercedes', 'DEOC', 'ry-wc-city-select'),
		_x('Nueva Ocotepeque', 'DEOC', 'ry-wc-city-select'),
		_x('San Fernando', 'DEOC', 'ry-wc-city-select'),
		_x('San Francisco del Valle', 'DEOC', 'ry-wc-city-select'),
		_x('San Jorge', 'DEOC', 'ry-wc-city-select'),
		_x('San Marcos', 'DEOC', 'ry-wc-city-select'),
		_x('Santa Fe', 'DEOC', 'ry-wc-city-select'),
		_x('Sensenti', 'DEOC', 'ry-wc-city-select'),
		_x('Sinuapa', 'DEOC', 'ry-wc-city-select'),
	],
	'DEOL' => [
		_x('Campamento', 'DEOL', 'ry-wc-city-select'),
		_x('Catacamas', 'DEOL', 'ry-wc-city-select'),
		_x('Concordia', 'DEOL', 'ry-wc-city-select'),
		_x('Dulce Nombre de Culmi', 'DEOL', 'ry-wc-city-select'),
		_x('El Rosario', 'DEOL', 'ry-wc-city-select'),
		_x('Esquipulas del Norte', 'DEOL', 'ry-wc-city-select'),
		_x('Gualaco', 'DEOL', 'ry-wc-city-select'),
		_x('Guarizama', 'DEOL', 'ry-wc-city-select'),
		_x('Guata', 'DEOL', 'ry-wc-city-select'),
		_x('Guayape', 'DEOL', 'ry-wc-city-select'),
		_x('Jano', 'DEOL', 'ry-wc-city-select'),
		_x('Juticalpa', 'DEOL', 'ry-wc-city-select'),
		_x('La Union', 'DEOL', 'ry-wc-city-select'),
		_x('Mangulile', 'DEOL', 'ry-wc-city-select'),
		_x('Manto', 'DEOL', 'ry-wc-city-select'),
		_x('Municipio de San Francisco de La Paz', 'DEOL', 'ry-wc-city-select'),
		_x('Patuca', 'DEOL', 'ry-wc-city-select'),
		_x('Salama', 'DEOL', 'ry-wc-city-select'),
		_x('San Esteban', 'DEOL', 'ry-wc-city-select'),
		_x('San Francisco de Becerra', 'DEOL', 'ry-wc-city-select'),
		_x('Santa Maria del Real', 'DEOL', 'ry-wc-city-select'),
		_x('Silca', 'DEOL', 'ry-wc-city-select'),
		_x('Yocon', 'DEOL', 'ry-wc-city-select'),
	],
	'DESABA' => [
		_x('Arada', 'DESABA', 'ry-wc-city-select'),
		_x('Atima', 'DESABA', 'ry-wc-city-select'),
		_x('Azacualpa', 'DESABA', 'ry-wc-city-select'),
		_x('Ceguaca', 'DESABA', 'ry-wc-city-select'),
		_x('Chinda', 'DESABA', 'ry-wc-city-select'),
		_x('Concepcion del Norte', 'DESABA', 'ry-wc-city-select'),
		_x('Concepcion del Sur', 'DESABA', 'ry-wc-city-select'),
		_x('El Nispero', 'DESABA', 'ry-wc-city-select'),
		_x('Gualala', 'DESABA', 'ry-wc-city-select'),
		_x('Ilama', 'DESABA', 'ry-wc-city-select'),
		_x('Las Vegas', 'DESABA', 'ry-wc-city-select'),
		_x('Macuelizo', 'DESABA', 'ry-wc-city-select'),
		_x('Naranjito', 'DESABA', 'ry-wc-city-select'),
		_x('Nueva Frontera', 'DESABA', 'ry-wc-city-select'),
		_x('Nuevo Celilac', 'DESABA', 'ry-wc-city-select'),
		_x('Petoa', 'DESABA', 'ry-wc-city-select'),
		_x('Proteccion', 'DESABA', 'ry-wc-city-select'),
		_x('Quimistan', 'DESABA', 'ry-wc-city-select'),
		_x('San Francisco de Ojuera', 'DESABA', 'ry-wc-city-select'),
		_x('San Jose de Colinas', 'DESABA', 'ry-wc-city-select'),
		_x('San Luis', 'DESABA', 'ry-wc-city-select'),
		_x('San Marcos', 'DESABA', 'ry-wc-city-select'),
		_x('San Nicolas', 'DESABA', 'ry-wc-city-select'),
		_x('San Pedro Zacapa', 'DESABA', 'ry-wc-city-select'),
		_x('San Vicente Centenario', 'DESABA', 'ry-wc-city-select'),
		_x('Santa Barbara', 'DESABA', 'ry-wc-city-select'),
		_x('Santa Rita', 'DESABA', 'ry-wc-city-select'),
		_x('Trinidad', 'DESABA', 'ry-wc-city-select'),
	],
	'DEVA' => [
		_x('Alianza', 'DEVA', 'ry-wc-city-select'),
		_x('Amapala', 'DEVA', 'ry-wc-city-select'),
		_x('Aramecina', 'DEVA', 'ry-wc-city-select'),
		_x('Caridad', 'DEVA', 'ry-wc-city-select'),
		_x('Goascoran', 'DEVA', 'ry-wc-city-select'),
		_x('Langue', 'DEVA', 'ry-wc-city-select'),
		_x('Nacaome', 'DEVA', 'ry-wc-city-select'),
		_x('San Francisco de Coray', 'DEVA', 'ry-wc-city-select'),
		_x('San Lorenzo', 'DEVA', 'ry-wc-city-select'),
	],
	'DEYO' => [
		_x('Arenal', 'DEYO', 'ry-wc-city-select'),
		_x('El Negrito', 'DEYO', 'ry-wc-city-select'),
		_x('El Progreso', 'DEYO', 'ry-wc-city-select'),
		_x('Jocon', 'DEYO', 'ry-wc-city-select'),
		_x('Morazan', 'DEYO', 'ry-wc-city-select'),
		_x('Olanchito', 'DEYO', 'ry-wc-city-select'),
		_x('Santa Rita', 'DEYO', 'ry-wc-city-select'),
		_x('Sulaco', 'DEYO', 'ry-wc-city-select'),
		_x('Victoria', 'DEYO', 'ry-wc-city-select'),
		_x('Yorito', 'DEYO', 'ry-wc-city-select'),
		_x('Yoro', 'DEYO', 'ry-wc-city-select'),
	],
	]
];