<?php
/**
 * Republic of Croatia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'HR' => [
	'BJZU' => [
		_x('Berek', 'BJZU', 'ry-wc-city-select'),
		_x('Dezanovac', 'BJZU', 'ry-wc-city-select'),
		_x('GJulovac', 'BJZU', 'ry-wc-city-select'),
		_x('Grad Bjelovar', 'BJZU', 'ry-wc-city-select'),
		_x('Grad Cazma', 'BJZU', 'ry-wc-city-select'),
		_x('Grad Daruvar', 'BJZU', 'ry-wc-city-select'),
		_x('Grad Garesnica', 'BJZU', 'ry-wc-city-select'),
		_x('Grad Grubisno Polje', 'BJZU', 'ry-wc-city-select'),
		_x('Hercegovac', 'BJZU', 'ry-wc-city-select'),
		_x('Ivanska', 'BJZU', 'ry-wc-city-select'),
		_x('Kapela', 'BJZU', 'ry-wc-city-select'),
		_x('Koncanica', 'BJZU', 'ry-wc-city-select'),
		_x('Nova Raca', 'BJZU', 'ry-wc-city-select'),
		_x('Rovisce', 'BJZU', 'ry-wc-city-select'),
		_x('Sandrovac', 'BJZU', 'ry-wc-city-select'),
		_x('Severin', 'BJZU', 'ry-wc-city-select'),
		_x('Sirac', 'BJZU', 'ry-wc-city-select'),
		_x('Stefanje', 'BJZU', 'ry-wc-city-select'),
		_x('Velika Pisanica', 'BJZU', 'ry-wc-city-select'),
		_x('Velika Trnovitica', 'BJZU', 'ry-wc-city-select'),
		_x('Veliki Grgevac', 'BJZU', 'ry-wc-city-select'),
		_x('Veliko Trojstvo', 'BJZU', 'ry-wc-city-select'),
		_x('Zrinski Topolovac', 'BJZU', 'ry-wc-city-select'),
	],
	'BRZU' => [
		_x('Bebrina', 'BRZU', 'ry-wc-city-select'),
		_x('Brodski Stupnik', 'BRZU', 'ry-wc-city-select'),
		_x('Bukovlje', 'BRZU', 'ry-wc-city-select'),
		_x('Cernik', 'BRZU', 'ry-wc-city-select'),
		_x('Davor', 'BRZU', 'ry-wc-city-select'),
		_x('Donji Andrijevci', 'BRZU', 'ry-wc-city-select'),
		_x('Dragalic', 'BRZU', 'ry-wc-city-select'),
		_x('Garcin', 'BRZU', 'ry-wc-city-select'),
		_x('Gornja Vrba', 'BRZU', 'ry-wc-city-select'),
		_x('Gornji Bogicevci', 'BRZU', 'ry-wc-city-select'),
		_x('Grad Nova Gradiska', 'BRZU', 'ry-wc-city-select'),
		_x('Grad Slavonski Brod', 'BRZU', 'ry-wc-city-select'),
		_x('Gundinci', 'BRZU', 'ry-wc-city-select'),
		_x('Klakar', 'BRZU', 'ry-wc-city-select'),
		_x('Nova Kapela', 'BRZU', 'ry-wc-city-select'),
		_x('Okucani', 'BRZU', 'ry-wc-city-select'),
		_x('Oprisavci', 'BRZU', 'ry-wc-city-select'),
		_x('Oriovac', 'BRZU', 'ry-wc-city-select'),
		_x('Podcrkavlje', 'BRZU', 'ry-wc-city-select'),
		_x('Resetari', 'BRZU', 'ry-wc-city-select'),
		_x('Sibinj', 'BRZU', 'ry-wc-city-select'),
		_x('Sikirevci', 'BRZU', 'ry-wc-city-select'),
		_x('Slavonski Samac', 'BRZU', 'ry-wc-city-select'),
		_x('Stara Gradiska', 'BRZU', 'ry-wc-city-select'),
		_x('Staro Petrovo Selo', 'BRZU', 'ry-wc-city-select'),
		_x('Velika Kopanica', 'BRZU', 'ry-wc-city-select'),
		_x('Vrbje', 'BRZU', 'ry-wc-city-select'),
		_x('Vrpolje', 'BRZU', 'ry-wc-city-select'),
	],
	'DUZU' => [
		_x('Blato', 'DUZU', 'ry-wc-city-select'),
		_x('Dubrovacko primorje', 'DUZU', 'ry-wc-city-select'),
		_x('Grad Dubrovnik', 'DUZU', 'ry-wc-city-select'),
		_x('Grad Korcula', 'DUZU', 'ry-wc-city-select'),
		_x('Grad Ploce', 'DUZU', 'ry-wc-city-select'),
		_x('Janjina', 'DUZU', 'ry-wc-city-select'),
		_x('Konavle', 'DUZU', 'ry-wc-city-select'),
		_x('Kula Norinska', 'DUZU', 'ry-wc-city-select'),
		_x('Lumbarda', 'DUZU', 'ry-wc-city-select'),
		_x('Metkovic', 'DUZU', 'ry-wc-city-select'),
		_x('Mljet', 'DUZU', 'ry-wc-city-select'),
		_x('Opcina Lastovo', 'DUZU', 'ry-wc-city-select'),
		_x('Opuzen', 'DUZU', 'ry-wc-city-select'),
		_x('Orebic', 'DUZU', 'ry-wc-city-select'),
		_x('Pojezerje', 'DUZU', 'ry-wc-city-select'),
		_x('Slivno', 'DUZU', 'ry-wc-city-select'),
		_x('Smokvica', 'DUZU', 'ry-wc-city-select'),
		_x('Ston', 'DUZU', 'ry-wc-city-select'),
		_x('Trpanj', 'DUZU', 'ry-wc-city-select'),
		_x('Vela Luka', 'DUZU', 'ry-wc-city-select'),
		_x('Zazablje', 'DUZU', 'ry-wc-city-select'),
		_x('Zupa dubrovacka', 'DUZU', 'ry-wc-city-select'),
	],
	'GRZA' => [
		_x('Gradska cetvrt Brezovica', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Crnomerec', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Donja Dubrava', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Donji grad', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Gornja Dubrava', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Gornji Grad - Medvescak', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Maksimir', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Novi Zagreb - istok', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Novi Zagreb - zapad', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Pescenica - Zitnjak', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Podsljeme', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Stenjevec', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Tresnjevka - jug', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Tresnjevka - sjever', 'GRZA', 'ry-wc-city-select'),
		_x('Gradska cetvrt Trnje', 'GRZA', 'ry-wc-city-select'),
		_x('Podsused - Vrapce', 'GRZA', 'ry-wc-city-select'),
		_x('Sesvete', 'GRZA', 'ry-wc-city-select'),
	],
	'ISZU' => [
		_x('Bale-Valle', 'ISZU', 'ry-wc-city-select'),
		_x('Barban', 'ISZU', 'ry-wc-city-select'),
		_x('Brtonigla-Verteneglio', 'ISZU', 'ry-wc-city-select'),
		_x('Buje-Buie', 'ISZU', 'ry-wc-city-select'),
		_x('Cerovlje', 'ISZU', 'ry-wc-city-select'),
		_x('Fazana-Fasana', 'ISZU', 'ry-wc-city-select'),
		_x('Funtana-Fontane', 'ISZU', 'ry-wc-city-select'),
		_x('Gracisce', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Buje', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Buzet', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Labin', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Pazin', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Porec', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Pula', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Rovinj', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Umag', 'ISZU', 'ry-wc-city-select'),
		_x('Grad Vodnjan', 'ISZU', 'ry-wc-city-select'),
		_x('Groznjan-Grisignana', 'ISZU', 'ry-wc-city-select'),
		_x('Kanfanar', 'ISZU', 'ry-wc-city-select'),
		_x('Karojba', 'ISZU', 'ry-wc-city-select'),
		_x('Kastelir-Labinci', 'ISZU', 'ry-wc-city-select'),
		_x('Krsan', 'ISZU', 'ry-wc-city-select'),
		_x('Liznjan-Lisignano', 'ISZU', 'ry-wc-city-select'),
		_x('Lupoglav', 'ISZU', 'ry-wc-city-select'),
		_x('Marcana', 'ISZU', 'ry-wc-city-select'),
		_x('Medulin', 'ISZU', 'ry-wc-city-select'),
		_x('Motovun-Montona', 'ISZU', 'ry-wc-city-select'),
		_x('Novigrad-Cittanova', 'ISZU', 'ry-wc-city-select'),
		_x('Opcina Lanisce', 'ISZU', 'ry-wc-city-select'),
		_x('Opcina Visnjan', 'ISZU', 'ry-wc-city-select'),
		_x('Opcina Vizinada', 'ISZU', 'ry-wc-city-select'),
		_x('Oprtalj-Portole', 'ISZU', 'ry-wc-city-select'),
		_x('Pican', 'ISZU', 'ry-wc-city-select'),
		_x('Porec-Parenzo', 'ISZU', 'ry-wc-city-select'),
		_x('Pula-Pola', 'ISZU', 'ry-wc-city-select'),
		_x('Rasa', 'ISZU', 'ry-wc-city-select'),
		_x('Rovinj-Rovigno', 'ISZU', 'ry-wc-city-select'),
		_x('Sveta Nedelja', 'ISZU', 'ry-wc-city-select'),
		_x('Sveti Lovrec', 'ISZU', 'ry-wc-city-select'),
		_x('Sveti Petar u Sumi', 'ISZU', 'ry-wc-city-select'),
		_x('Svetvincenat', 'ISZU', 'ry-wc-city-select'),
		_x('Tar-Vabriga-Torre Abrega', 'ISZU', 'ry-wc-city-select'),
		_x('Tinjan', 'ISZU', 'ry-wc-city-select'),
		_x('Umag-Umago', 'ISZU', 'ry-wc-city-select'),
		_x('Visnjan-Visignano', 'ISZU', 'ry-wc-city-select'),
		_x('Vizinada-Visinada', 'ISZU', 'ry-wc-city-select'),
		_x('Vodnjan-Dignano', 'ISZU', 'ry-wc-city-select'),
		_x('Vrsar-Orsera', 'ISZU', 'ry-wc-city-select'),
		_x('Zminj', 'ISZU', 'ry-wc-city-select'),
	],
	'KAZU' => [
		_x('Barilovic', 'KAZU', 'ry-wc-city-select'),
		_x('Bosiljevo', 'KAZU', 'ry-wc-city-select'),
		_x('Cetingrad', 'KAZU', 'ry-wc-city-select'),
		_x('Draganic', 'KAZU', 'ry-wc-city-select'),
		_x('Generalski Stol', 'KAZU', 'ry-wc-city-select'),
		_x('Grad Duga Resa', 'KAZU', 'ry-wc-city-select'),
		_x('Grad Karlovac', 'KAZU', 'ry-wc-city-select'),
		_x('Grad Ogulin', 'KAZU', 'ry-wc-city-select'),
		_x('Grad Ozalj', 'KAZU', 'ry-wc-city-select'),
		_x('Grad Slunj', 'KAZU', 'ry-wc-city-select'),
		_x('Josipdol', 'KAZU', 'ry-wc-city-select'),
		_x('Kamanje', 'KAZU', 'ry-wc-city-select'),
		_x('Krnjak', 'KAZU', 'ry-wc-city-select'),
		_x('Lasinja', 'KAZU', 'ry-wc-city-select'),
		_x('Netretic', 'KAZU', 'ry-wc-city-select'),
		_x('Opcina Vojnic', 'KAZU', 'ry-wc-city-select'),
		_x('Plaski', 'KAZU', 'ry-wc-city-select'),
		_x('Rakovica', 'KAZU', 'ry-wc-city-select'),
		_x('Ribnik', 'KAZU', 'ry-wc-city-select'),
		_x('Saborsko', 'KAZU', 'ry-wc-city-select'),
		_x('Tounj', 'KAZU', 'ry-wc-city-select'),
		_x('Zakanje', 'KAZU', 'ry-wc-city-select'),
	],
	'KOZU' => [
		_x('Drnje', 'KOZU', 'ry-wc-city-select'),
		_x('Ferdinandovac', 'KOZU', 'ry-wc-city-select'),
		_x('GJelekovec', 'KOZU', 'ry-wc-city-select'),
		_x('GJurgevac', 'KOZU', 'ry-wc-city-select'),
		_x('Gola', 'KOZU', 'ry-wc-city-select'),
		_x('Gornja Rijeka', 'KOZU', 'ry-wc-city-select'),
		_x('Grad GJurgevac', 'KOZU', 'ry-wc-city-select'),
		_x('Grad Koprivnica', 'KOZU', 'ry-wc-city-select'),
		_x('Grad Krizevci', 'KOZU', 'ry-wc-city-select'),
		_x('Hlebine', 'KOZU', 'ry-wc-city-select'),
		_x('Kalinovac', 'KOZU', 'ry-wc-city-select'),
		_x('Kalnik', 'KOZU', 'ry-wc-city-select'),
		_x('Klostar Podravski', 'KOZU', 'ry-wc-city-select'),
		_x('Koprivnicki Bregi', 'KOZU', 'ry-wc-city-select'),
		_x('Koprivnicki Ivanec', 'KOZU', 'ry-wc-city-select'),
		_x('Legrad', 'KOZU', 'ry-wc-city-select'),
		_x('Molve', 'KOZU', 'ry-wc-city-select'),
		_x('Novigrad Podravski', 'KOZU', 'ry-wc-city-select'),
		_x('Novo Virje', 'KOZU', 'ry-wc-city-select'),
		_x('Peteranec', 'KOZU', 'ry-wc-city-select'),
		_x('Podravske Sesvete', 'KOZU', 'ry-wc-city-select'),
		_x('Rasinja', 'KOZU', 'ry-wc-city-select'),
		_x('Sokolovac', 'KOZU', 'ry-wc-city-select'),
		_x('Sveti Ivan Zabno', 'KOZU', 'ry-wc-city-select'),
		_x('Sveti Petar Orehovec', 'KOZU', 'ry-wc-city-select'),
		_x('Virje', 'KOZU', 'ry-wc-city-select'),
	],
	'KRZU' => [
		_x('Bedekovcina', 'KRZU', 'ry-wc-city-select'),
		_x('Budinscina', 'KRZU', 'ry-wc-city-select'),
		_x('Desinic', 'KRZU', 'ry-wc-city-select'),
		_x('GJurmanec', 'KRZU', 'ry-wc-city-select'),
		_x('Gornja Stubica', 'KRZU', 'ry-wc-city-select'),
		_x('Grad Donja Stubica', 'KRZU', 'ry-wc-city-select'),
		_x('Grad Klanjec', 'KRZU', 'ry-wc-city-select'),
		_x('Grad Krapina', 'KRZU', 'ry-wc-city-select'),
		_x('Grad Zabok', 'KRZU', 'ry-wc-city-select'),
		_x('Grad Zlatar', 'KRZU', 'ry-wc-city-select'),
		_x('Hrascina', 'KRZU', 'ry-wc-city-select'),
		_x('Hum na Sutli', 'KRZU', 'ry-wc-city-select'),
		_x('Jesenje', 'KRZU', 'ry-wc-city-select'),
		_x('Konjscina', 'KRZU', 'ry-wc-city-select'),
		_x('Kraljevec na Sutli', 'KRZU', 'ry-wc-city-select'),
		_x('Krapinske Toplice', 'KRZU', 'ry-wc-city-select'),
		_x('Kumrovec', 'KRZU', 'ry-wc-city-select'),
		_x('Lobor', 'KRZU', 'ry-wc-city-select'),
		_x('Mace', 'KRZU', 'ry-wc-city-select'),
		_x('Marija Bistrica', 'KRZU', 'ry-wc-city-select'),
		_x('Mihovljan', 'KRZU', 'ry-wc-city-select'),
		_x('Novi Golubovec', 'KRZU', 'ry-wc-city-select'),
		_x('Oroslavje', 'KRZU', 'ry-wc-city-select'),
		_x('Petrovsko', 'KRZU', 'ry-wc-city-select'),
		_x('Pregrada', 'KRZU', 'ry-wc-city-select'),
		_x('Radoboj', 'KRZU', 'ry-wc-city-select'),
		_x('Stubicke Toplice', 'KRZU', 'ry-wc-city-select'),
		_x('Sveti Kriz Zacretje', 'KRZU', 'ry-wc-city-select'),
		_x('Tuhelj', 'KRZU', 'ry-wc-city-select'),
		_x('Veliko Trgovisce', 'KRZU', 'ry-wc-city-select'),
		_x('Zagorska Sela', 'KRZU', 'ry-wc-city-select'),
		_x('Zlatar Bistrica', 'KRZU', 'ry-wc-city-select'),
	],
	'LIZU' => [
		_x('Brinje', 'LIZU', 'ry-wc-city-select'),
		_x('Donji Lapac', 'LIZU', 'ry-wc-city-select'),
		_x('Gospic', 'LIZU', 'ry-wc-city-select'),
		_x('Karlobag', 'LIZU', 'ry-wc-city-select'),
		_x('Lovinac', 'LIZU', 'ry-wc-city-select'),
		_x('Novalja', 'LIZU', 'ry-wc-city-select'),
		_x('Otocac', 'LIZU', 'ry-wc-city-select'),
		_x('Perusic', 'LIZU', 'ry-wc-city-select'),
		_x('Plitvicka Jezera', 'LIZU', 'ry-wc-city-select'),
		_x('Senj', 'LIZU', 'ry-wc-city-select'),
		_x('Udbina', 'LIZU', 'ry-wc-city-select'),
		_x('Vrhovine', 'LIZU', 'ry-wc-city-select'),
	],
	'MEZU' => [
		_x('Belica', 'MEZU', 'ry-wc-city-select'),
		_x('Dekanovec', 'MEZU', 'ry-wc-city-select'),
		_x('Domasinec', 'MEZU', 'ry-wc-city-select'),
		_x('Donja Dubrava', 'MEZU', 'ry-wc-city-select'),
		_x('Donji Kraljevec', 'MEZU', 'ry-wc-city-select'),
		_x('Donji Vidovec', 'MEZU', 'ry-wc-city-select'),
		_x('Gorican', 'MEZU', 'ry-wc-city-select'),
		_x('Gornji Mihaljevec', 'MEZU', 'ry-wc-city-select'),
		_x('Grad Cakovec', 'MEZU', 'ry-wc-city-select'),
		_x('Kotoriba', 'MEZU', 'ry-wc-city-select'),
		_x('Mala Subotica', 'MEZU', 'ry-wc-city-select'),
		_x('Mursko Sredisce', 'MEZU', 'ry-wc-city-select'),
		_x('Nedelisce', 'MEZU', 'ry-wc-city-select'),
		_x('Orehovica', 'MEZU', 'ry-wc-city-select'),
		_x('Podturen', 'MEZU', 'ry-wc-city-select'),
		_x('Prelog', 'MEZU', 'ry-wc-city-select'),
		_x('Pribislavec', 'MEZU', 'ry-wc-city-select'),
		_x('Selnica', 'MEZU', 'ry-wc-city-select'),
		_x('Senkovec', 'MEZU', 'ry-wc-city-select'),
		_x('Strahoninec', 'MEZU', 'ry-wc-city-select'),
		_x('Strigova', 'MEZU', 'ry-wc-city-select'),
		_x('Sveta Marija', 'MEZU', 'ry-wc-city-select'),
		_x('Sveti Juraj na Bregu', 'MEZU', 'ry-wc-city-select'),
		_x('Sveti Martin na Muri', 'MEZU', 'ry-wc-city-select'),
		_x('Vratisinec', 'MEZU', 'ry-wc-city-select'),
	],
	'OSZU' => [
		_x('Antunovac', 'OSZU', 'ry-wc-city-select'),
		_x('Belisce', 'OSZU', 'ry-wc-city-select'),
		_x('Bilje', 'OSZU', 'ry-wc-city-select'),
		_x('Bizovac', 'OSZU', 'ry-wc-city-select'),
		_x('Ceminac', 'OSZU', 'ry-wc-city-select'),
		_x('Cepin', 'OSZU', 'ry-wc-city-select'),
		_x('Darda', 'OSZU', 'ry-wc-city-select'),
		_x('Donja Moticina', 'OSZU', 'ry-wc-city-select'),
		_x('Draz', 'OSZU', 'ry-wc-city-select'),
		_x('Drenje', 'OSZU', 'ry-wc-city-select'),
		_x('Erdut', 'OSZU', 'ry-wc-city-select'),
		_x('Ernestinovo', 'OSZU', 'ry-wc-city-select'),
		_x('Fericanci', 'OSZU', 'ry-wc-city-select'),
		_x('GJakovo', 'OSZU', 'ry-wc-city-select'),
		_x('GJurgenovac', 'OSZU', 'ry-wc-city-select'),
		_x('Gorjani', 'OSZU', 'ry-wc-city-select'),
		_x('Grad Beli Manastir', 'OSZU', 'ry-wc-city-select'),
		_x('Grad Donji Miholjac', 'OSZU', 'ry-wc-city-select'),
		_x('Grad GJakovo', 'OSZU', 'ry-wc-city-select'),
		_x('Grad Nasice', 'OSZU', 'ry-wc-city-select'),
		_x('Grad Osijek', 'OSZU', 'ry-wc-city-select'),
		_x('Grad Valpovo', 'OSZU', 'ry-wc-city-select'),
		_x('Jagodnjak', 'OSZU', 'ry-wc-city-select'),
		_x('Knezevi Vinogradi', 'OSZU', 'ry-wc-city-select'),
		_x('Koska', 'OSZU', 'ry-wc-city-select'),
		_x('Levanjska Varos', 'OSZU', 'ry-wc-city-select'),
		_x('Magadenovac', 'OSZU', 'ry-wc-city-select'),
		_x('Marijanci', 'OSZU', 'ry-wc-city-select'),
		_x('Petlovac', 'OSZU', 'ry-wc-city-select'),
		_x('Petrijevci', 'OSZU', 'ry-wc-city-select'),
		_x('Podgorac', 'OSZU', 'ry-wc-city-select'),
		_x('Podravska Moslavina', 'OSZU', 'ry-wc-city-select'),
		_x('Popovac', 'OSZU', 'ry-wc-city-select'),
		_x('Punitovci', 'OSZU', 'ry-wc-city-select'),
		_x('Satnica GJakovacka', 'OSZU', 'ry-wc-city-select'),
		_x('Semeljci', 'OSZU', 'ry-wc-city-select'),
		_x('Sodolovci', 'OSZU', 'ry-wc-city-select'),
		_x('Strizivojna', 'OSZU', 'ry-wc-city-select'),
		_x('Trnava', 'OSZU', 'ry-wc-city-select'),
		_x('Viljevo', 'OSZU', 'ry-wc-city-select'),
		_x('Viskovci', 'OSZU', 'ry-wc-city-select'),
		_x('Vladislavci', 'OSZU', 'ry-wc-city-select'),
		_x('Vuka', 'OSZU', 'ry-wc-city-select'),
	],
	'POZU' => [
		_x('Brestovac', 'POZU', 'ry-wc-city-select'),
		_x('Caglin', 'POZU', 'ry-wc-city-select'),
		_x('Grad Pakrac', 'POZU', 'ry-wc-city-select'),
		_x('Grad Pozega', 'POZU', 'ry-wc-city-select'),
		_x('Jaksic', 'POZU', 'ry-wc-city-select'),
		_x('Kaptol', 'POZU', 'ry-wc-city-select'),
		_x('Kutjevo', 'POZU', 'ry-wc-city-select'),
		_x('Lipik', 'POZU', 'ry-wc-city-select'),
		_x('Pleternica', 'POZU', 'ry-wc-city-select'),
		_x('Velika', 'POZU', 'ry-wc-city-select'),
	],
	'PRZU' => [
		_x('Bakar', 'PRZU', 'ry-wc-city-select'),
		_x('Baska', 'PRZU', 'ry-wc-city-select'),
		_x('Brod Moravice', 'PRZU', 'ry-wc-city-select'),
		_x('Cavle', 'PRZU', 'ry-wc-city-select'),
		_x('Cres', 'PRZU', 'ry-wc-city-select'),
		_x('Dobrinj', 'PRZU', 'ry-wc-city-select'),
		_x('Fuzine', 'PRZU', 'ry-wc-city-select'),
		_x('Grad Cabar', 'PRZU', 'ry-wc-city-select'),
		_x('Grad Crikvenica', 'PRZU', 'ry-wc-city-select'),
		_x('Grad Delnice', 'PRZU', 'ry-wc-city-select'),
		_x('Grad Krk', 'PRZU', 'ry-wc-city-select'),
		_x('Grad Opatija', 'PRZU', 'ry-wc-city-select'),
		_x('Grad Rijeka', 'PRZU', 'ry-wc-city-select'),
		_x('Grad Vrbovsko', 'PRZU', 'ry-wc-city-select'),
		_x('Jelenje', 'PRZU', 'ry-wc-city-select'),
		_x('Kastav', 'PRZU', 'ry-wc-city-select'),
		_x('Klana', 'PRZU', 'ry-wc-city-select'),
		_x('Kostrena', 'PRZU', 'ry-wc-city-select'),
		_x('Kraljevica', 'PRZU', 'ry-wc-city-select'),
		_x('Lokve', 'PRZU', 'ry-wc-city-select'),
		_x('Lopar', 'PRZU', 'ry-wc-city-select'),
		_x('Lovran', 'PRZU', 'ry-wc-city-select'),
		_x('Mali Losinj', 'PRZU', 'ry-wc-city-select'),
		_x('Malinska-Dubasnica', 'PRZU', 'ry-wc-city-select'),
		_x('Matulji', 'PRZU', 'ry-wc-city-select'),
		_x('Moscenicka Draga', 'PRZU', 'ry-wc-city-select'),
		_x('Mrkopalj', 'PRZU', 'ry-wc-city-select'),
		_x('Novi Vinodolski', 'PRZU', 'ry-wc-city-select'),
		_x('Omisalj', 'PRZU', 'ry-wc-city-select'),
		_x('Punat', 'PRZU', 'ry-wc-city-select'),
		_x('Rab', 'PRZU', 'ry-wc-city-select'),
		_x('Ravna Gora', 'PRZU', 'ry-wc-city-select'),
		_x('Skrad', 'PRZU', 'ry-wc-city-select'),
		_x('Vinodolska opcina', 'PRZU', 'ry-wc-city-select'),
		_x('Viskovo', 'PRZU', 'ry-wc-city-select'),
		_x('Vrbnik', 'PRZU', 'ry-wc-city-select'),
	],
	'SIZU' => [
		_x('Bilice', 'SIZU', 'ry-wc-city-select'),
		_x('Biskupija', 'SIZU', 'ry-wc-city-select'),
		_x('Civljane', 'SIZU', 'ry-wc-city-select'),
		_x('Ervenik', 'SIZU', 'ry-wc-city-select'),
		_x('Grad Drnis', 'SIZU', 'ry-wc-city-select'),
		_x('Grad Sibenik', 'SIZU', 'ry-wc-city-select'),
		_x('Kijevo', 'SIZU', 'ry-wc-city-select'),
		_x('Kistanje', 'SIZU', 'ry-wc-city-select'),
		_x('Knin', 'SIZU', 'ry-wc-city-select'),
		_x('Murter-Kornati', 'SIZU', 'ry-wc-city-select'),
		_x('Pirovac', 'SIZU', 'ry-wc-city-select'),
		_x('Primosten', 'SIZU', 'ry-wc-city-select'),
		_x('Promina', 'SIZU', 'ry-wc-city-select'),
		_x('Rogoznica Opcina', 'SIZU', 'ry-wc-city-select'),
		_x('Ruzic', 'SIZU', 'ry-wc-city-select'),
		_x('Skradin', 'SIZU', 'ry-wc-city-select'),
		_x('Tisno', 'SIZU', 'ry-wc-city-select'),
		_x('Tribunj', 'SIZU', 'ry-wc-city-select'),
		_x('Unesic', 'SIZU', 'ry-wc-city-select'),
		_x('Vodice', 'SIZU', 'ry-wc-city-select'),
	],
	'SIZU2' => [
		_x('Donji Kukuruzari', 'SIZU2', 'ry-wc-city-select'),
		_x('Grad Glina', 'SIZU2', 'ry-wc-city-select'),
		_x('Grad Hrvatska Kostajnica', 'SIZU2', 'ry-wc-city-select'),
		_x('Grad Kutina', 'SIZU2', 'ry-wc-city-select'),
		_x('Grad Novska', 'SIZU2', 'ry-wc-city-select'),
		_x('Grad Petrinja', 'SIZU2', 'ry-wc-city-select'),
		_x('Grad Sisak', 'SIZU2', 'ry-wc-city-select'),
		_x('Hrvatska Dubica', 'SIZU2', 'ry-wc-city-select'),
		_x('Jasenovac', 'SIZU2', 'ry-wc-city-select'),
		_x('Lekenik', 'SIZU2', 'ry-wc-city-select'),
		_x('Lipovljani', 'SIZU2', 'ry-wc-city-select'),
		_x('Majur', 'SIZU2', 'ry-wc-city-select'),
		_x('Martinska Ves', 'SIZU2', 'ry-wc-city-select'),
		_x('Opcina Dvor', 'SIZU2', 'ry-wc-city-select'),
		_x('Opcina Gvozd', 'SIZU2', 'ry-wc-city-select'),
		_x('Popovaca', 'SIZU2', 'ry-wc-city-select'),
		_x('Sunja', 'SIZU2', 'ry-wc-city-select'),
		_x('Topusko', 'SIZU2', 'ry-wc-city-select'),
		_x('Velika Ludina', 'SIZU2', 'ry-wc-city-select'),
	],
	'SPZU' => [
		_x('Baska Voda', 'SPZU', 'ry-wc-city-select'),
		_x('Bol', 'SPZU', 'ry-wc-city-select'),
		_x('Brela', 'SPZU', 'ry-wc-city-select'),
		_x('Cista Provo', 'SPZU', 'ry-wc-city-select'),
		_x('Dicmo', 'SPZU', 'ry-wc-city-select'),
		_x('Dugi Rat Opcina', 'SPZU', 'ry-wc-city-select'),
		_x('Dugopolje', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Hvar', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Imotski', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Makarska', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Omis', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Sinj', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Split', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Supetar', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Trogir', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Vis', 'SPZU', 'ry-wc-city-select'),
		_x('Grad Vrgorac', 'SPZU', 'ry-wc-city-select'),
		_x('Gradac', 'SPZU', 'ry-wc-city-select'),
		_x('Hrvace', 'SPZU', 'ry-wc-city-select'),
		_x('Jelsa', 'SPZU', 'ry-wc-city-select'),
		_x('Kastela', 'SPZU', 'ry-wc-city-select'),
		_x('Klis', 'SPZU', 'ry-wc-city-select'),
		_x('Komiza', 'SPZU', 'ry-wc-city-select'),
		_x('Lecevica', 'SPZU', 'ry-wc-city-select'),
		_x('Lokvicici', 'SPZU', 'ry-wc-city-select'),
		_x('Lovrec', 'SPZU', 'ry-wc-city-select'),
		_x('Marina', 'SPZU', 'ry-wc-city-select'),
		_x('Milna', 'SPZU', 'ry-wc-city-select'),
		_x('Muc', 'SPZU', 'ry-wc-city-select'),
		_x('Nerezisca', 'SPZU', 'ry-wc-city-select'),
		_x('Okrug', 'SPZU', 'ry-wc-city-select'),
		_x('Otok', 'SPZU', 'ry-wc-city-select'),
		_x('Podbablje', 'SPZU', 'ry-wc-city-select'),
		_x('Podgora', 'SPZU', 'ry-wc-city-select'),
		_x('Podstrana', 'SPZU', 'ry-wc-city-select'),
		_x('Postira', 'SPZU', 'ry-wc-city-select'),
		_x('Prgomet', 'SPZU', 'ry-wc-city-select'),
		_x('Primorski Dolac', 'SPZU', 'ry-wc-city-select'),
		_x('Prolozac', 'SPZU', 'ry-wc-city-select'),
		_x('Pucisca', 'SPZU', 'ry-wc-city-select'),
		_x('Runovici', 'SPZU', 'ry-wc-city-select'),
		_x('Seget', 'SPZU', 'ry-wc-city-select'),
		_x('Selca', 'SPZU', 'ry-wc-city-select'),
		_x('Sestanovac', 'SPZU', 'ry-wc-city-select'),
		_x('Solin', 'SPZU', 'ry-wc-city-select'),
		_x('Solta', 'SPZU', 'ry-wc-city-select'),
		_x('Stari Grad', 'SPZU', 'ry-wc-city-select'),
		_x('Sucuraj', 'SPZU', 'ry-wc-city-select'),
		_x('Sutivan', 'SPZU', 'ry-wc-city-select'),
		_x('Trilj', 'SPZU', 'ry-wc-city-select'),
		_x('Tucepi', 'SPZU', 'ry-wc-city-select'),
		_x('Vrlika', 'SPZU', 'ry-wc-city-select'),
		_x('Zadvarje', 'SPZU', 'ry-wc-city-select'),
		_x('Zagvozd', 'SPZU', 'ry-wc-city-select'),
		_x('Zmijavci', 'SPZU', 'ry-wc-city-select'),
	],
	'VAZU' => [
		_x('Bednja', 'VAZU', 'ry-wc-city-select'),
		_x('Beretinec', 'VAZU', 'ry-wc-city-select'),
		_x('Breznica', 'VAZU', 'ry-wc-city-select'),
		_x('Breznicki Hum', 'VAZU', 'ry-wc-city-select'),
		_x('Cestica', 'VAZU', 'ry-wc-city-select'),
		_x('Donja Voca', 'VAZU', 'ry-wc-city-select'),
		_x('Gornji Kneginec', 'VAZU', 'ry-wc-city-select'),
		_x('Grad Ivanec', 'VAZU', 'ry-wc-city-select'),
		_x('Grad Ludbreg', 'VAZU', 'ry-wc-city-select'),
		_x('Grad Novi Marof', 'VAZU', 'ry-wc-city-select'),
		_x('Grad Varazdin', 'VAZU', 'ry-wc-city-select'),
		_x('Jalzabet', 'VAZU', 'ry-wc-city-select'),
		_x('Klenovnik', 'VAZU', 'ry-wc-city-select'),
		_x('Lepoglava', 'VAZU', 'ry-wc-city-select'),
		_x('Ljubescica', 'VAZU', 'ry-wc-city-select'),
		_x('Mali Bukovec', 'VAZU', 'ry-wc-city-select'),
		_x('Martijanec', 'VAZU', 'ry-wc-city-select'),
		_x('Marusevec', 'VAZU', 'ry-wc-city-select'),
		_x('Petrijanec', 'VAZU', 'ry-wc-city-select'),
		_x('Sracinec', 'VAZU', 'ry-wc-city-select'),
		_x('Sveti GJurg', 'VAZU', 'ry-wc-city-select'),
		_x('Sveti Ilija', 'VAZU', 'ry-wc-city-select'),
		_x('Trnovec Bartolovecki', 'VAZU', 'ry-wc-city-select'),
		_x('Varazdinske Toplice', 'VAZU', 'ry-wc-city-select'),
		_x('Veliki Bukovec', 'VAZU', 'ry-wc-city-select'),
		_x('Vidovec', 'VAZU', 'ry-wc-city-select'),
		_x('Vinica', 'VAZU', 'ry-wc-city-select'),
		_x('Visoko', 'VAZU', 'ry-wc-city-select'),
	],
	'VIZU' => [
		_x('Cacinci', 'VIZU', 'ry-wc-city-select'),
		_x('Cagavica', 'VIZU', 'ry-wc-city-select'),
		_x('Crnac', 'VIZU', 'ry-wc-city-select'),
		_x('Grad Orahovica', 'VIZU', 'ry-wc-city-select'),
		_x('Grad Slatina', 'VIZU', 'ry-wc-city-select'),
		_x('Grad Virovitica', 'VIZU', 'ry-wc-city-select'),
		_x('Gradina', 'VIZU', 'ry-wc-city-select'),
		_x('Lukac', 'VIZU', 'ry-wc-city-select'),
		_x('Mikleus', 'VIZU', 'ry-wc-city-select'),
		_x('Nova Bukovica', 'VIZU', 'ry-wc-city-select'),
		_x('Pitomaca', 'VIZU', 'ry-wc-city-select'),
		_x('Sopje', 'VIZU', 'ry-wc-city-select'),
		_x('Spisic Bukovica', 'VIZU', 'ry-wc-city-select'),
		_x('Suhopolje', 'VIZU', 'ry-wc-city-select'),
		_x('Vocin', 'VIZU', 'ry-wc-city-select'),
		_x('Zdenci', 'VIZU', 'ry-wc-city-select'),
	],
	'VUZU' => [
		_x('Andrijasevci', 'VUZU', 'ry-wc-city-select'),
		_x('Babina Greda', 'VUZU', 'ry-wc-city-select'),
		_x('Bogdanovci', 'VUZU', 'ry-wc-city-select'),
		_x('Borovo', 'VUZU', 'ry-wc-city-select'),
		_x('Bosnjaci', 'VUZU', 'ry-wc-city-select'),
		_x('Cerna', 'VUZU', 'ry-wc-city-select'),
		_x('Drenovci', 'VUZU', 'ry-wc-city-select'),
		_x('Grad Vinkovci', 'VUZU', 'ry-wc-city-select'),
		_x('Grad Vukovar', 'VUZU', 'ry-wc-city-select'),
		_x('Grad Zupanja', 'VUZU', 'ry-wc-city-select'),
		_x('Gradiste', 'VUZU', 'ry-wc-city-select'),
		_x('Gunja', 'VUZU', 'ry-wc-city-select'),
		_x('Ilok', 'VUZU', 'ry-wc-city-select'),
		_x('Ivankovo', 'VUZU', 'ry-wc-city-select'),
		_x('Jarmina', 'VUZU', 'ry-wc-city-select'),
		_x('Lovas', 'VUZU', 'ry-wc-city-select'),
		_x('Markusica', 'VUZU', 'ry-wc-city-select'),
		_x('Negoslavci', 'VUZU', 'ry-wc-city-select'),
		_x('Nijemci', 'VUZU', 'ry-wc-city-select'),
		_x('Nustar', 'VUZU', 'ry-wc-city-select'),
		_x('Otok', 'VUZU', 'ry-wc-city-select'),
		_x('Privlaka', 'VUZU', 'ry-wc-city-select'),
		_x('Stari Jankovci', 'VUZU', 'ry-wc-city-select'),
		_x('Stari Mikanovci', 'VUZU', 'ry-wc-city-select'),
		_x('Stitar', 'VUZU', 'ry-wc-city-select'),
		_x('Tompojevci', 'VUZU', 'ry-wc-city-select'),
		_x('Tordinci', 'VUZU', 'ry-wc-city-select'),
		_x('Tovarnik', 'VUZU', 'ry-wc-city-select'),
		_x('Trpinja', 'VUZU', 'ry-wc-city-select'),
		_x('Voginci', 'VUZU', 'ry-wc-city-select'),
		_x('Vrbanja', 'VUZU', 'ry-wc-city-select'),
	],
	'ZAZU' => [
		_x('Benkovac', 'ZAZU', 'ry-wc-city-select'),
		_x('Bibinje', 'ZAZU', 'ry-wc-city-select'),
		_x('Galovac', 'ZAZU', 'ry-wc-city-select'),
		_x('Gracac', 'ZAZU', 'ry-wc-city-select'),
		_x('Grad Biograd na Moru', 'ZAZU', 'ry-wc-city-select'),
		_x('Jasenice', 'ZAZU', 'ry-wc-city-select'),
		_x('Kali', 'ZAZU', 'ry-wc-city-select'),
		_x('Kolan', 'ZAZU', 'ry-wc-city-select'),
		_x('Kukljica', 'ZAZU', 'ry-wc-city-select'),
		_x('Lisane Ostrovicke', 'ZAZU', 'ry-wc-city-select'),
		_x('Nin', 'ZAZU', 'ry-wc-city-select'),
		_x('Novigrad Opcina', 'ZAZU', 'ry-wc-city-select'),
		_x('Obrovac', 'ZAZU', 'ry-wc-city-select'),
		_x('Pag', 'ZAZU', 'ry-wc-city-select'),
		_x('Pakostane', 'ZAZU', 'ry-wc-city-select'),
		_x('Pasman', 'ZAZU', 'ry-wc-city-select'),
		_x('Polaca', 'ZAZU', 'ry-wc-city-select'),
		_x('Policnik', 'ZAZU', 'ry-wc-city-select'),
		_x('Posedarje', 'ZAZU', 'ry-wc-city-select'),
		_x('Povljana', 'ZAZU', 'ry-wc-city-select'),
		_x('Preko', 'ZAZU', 'ry-wc-city-select'),
		_x('Privlaka', 'ZAZU', 'ry-wc-city-select'),
		_x('Razanac', 'ZAZU', 'ry-wc-city-select'),
		_x('Sali', 'ZAZU', 'ry-wc-city-select'),
		_x('Skabrnja', 'ZAZU', 'ry-wc-city-select'),
		_x('Stankovci', 'ZAZU', 'ry-wc-city-select'),
		_x('Starigrad', 'ZAZU', 'ry-wc-city-select'),
		_x('Sukosan', 'ZAZU', 'ry-wc-city-select'),
		_x('Sveti Filip i Jakov', 'ZAZU', 'ry-wc-city-select'),
		_x('Tkon', 'ZAZU', 'ry-wc-city-select'),
		_x('Vir', 'ZAZU', 'ry-wc-city-select'),
		_x('Vrsi', 'ZAZU', 'ry-wc-city-select'),
		_x('Zadar', 'ZAZU', 'ry-wc-city-select'),
		_x('Zemunik Donji', 'ZAZU', 'ry-wc-city-select'),
	],
	'ZACO' => [
		_x('Bedenica', 'ZACO', 'ry-wc-city-select'),
		_x('Bistra', 'ZACO', 'ry-wc-city-select'),
		_x('Brckovljani', 'ZACO', 'ry-wc-city-select'),
		_x('Brdovec', 'ZACO', 'ry-wc-city-select'),
		_x('Dubravica', 'ZACO', 'ry-wc-city-select'),
		_x('Farkasevac', 'ZACO', 'ry-wc-city-select'),
		_x('Grad Dugo Selo', 'ZACO', 'ry-wc-city-select'),
		_x('Grad Jastrebarsko', 'ZACO', 'ry-wc-city-select'),
		_x('Grad Samobor', 'ZACO', 'ry-wc-city-select'),
		_x('Grad Sveti Ivan Zelina', 'ZACO', 'ry-wc-city-select'),
		_x('Grad Velika Gorica', 'ZACO', 'ry-wc-city-select'),
		_x('Grad Vrbovec', 'ZACO', 'ry-wc-city-select'),
		_x('Grad Zapresic', 'ZACO', 'ry-wc-city-select'),
		_x('Gradec', 'ZACO', 'ry-wc-city-select'),
		_x('Ivanic-Grad', 'ZACO', 'ry-wc-city-select'),
		_x('Jakovlje', 'ZACO', 'ry-wc-city-select'),
		_x('Klinca Sela', 'ZACO', 'ry-wc-city-select'),
		_x('Klostar Ivanic', 'ZACO', 'ry-wc-city-select'),
		_x('Krasic', 'ZACO', 'ry-wc-city-select'),
		_x('Kravarsko', 'ZACO', 'ry-wc-city-select'),
		_x('Kriz', 'ZACO', 'ry-wc-city-select'),
		_x('Luka', 'ZACO', 'ry-wc-city-select'),
		_x('Marija Gorica', 'ZACO', 'ry-wc-city-select'),
		_x('Opcina Dubrava', 'ZACO', 'ry-wc-city-select'),
		_x('Orle', 'ZACO', 'ry-wc-city-select'),
		_x('Pisarovina', 'ZACO', 'ry-wc-city-select'),
		_x('Pokupsko', 'ZACO', 'ry-wc-city-select'),
		_x('Preseka', 'ZACO', 'ry-wc-city-select'),
		_x('Pusca', 'ZACO', 'ry-wc-city-select'),
		_x('Rakovec', 'ZACO', 'ry-wc-city-select'),
		_x('Rugvica', 'ZACO', 'ry-wc-city-select'),
		_x('Stupnik', 'ZACO', 'ry-wc-city-select'),
		_x('Sveta Nedelja', 'ZACO', 'ry-wc-city-select'),
		_x('Zumberak', 'ZACO', 'ry-wc-city-select'),
	],
	]
];