<?php
/**
 * Hungary places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'HU' => [
	'BACO' => [
		_x('Bacsalmasi Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Bajai Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Janoshalmai Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Kalocsai Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Kecskemeti Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Kiskoroesi Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Kiskunfelegyhazi Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Kiskunhalasi Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Kiskunmajsai Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Kunszentmiklosi Jaras', 'BACO', 'ry-wc-city-select'),
		_x('Tiszakecskei Jaras', 'BACO', 'ry-wc-city-select'),
	],
	'BACO2' => [
		_x('Bolyi Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Hegyhati Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Komloi Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Mohacsi Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Pecsi Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Pecsvaradi Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Sellyei Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Siklosi Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Szentlorinci Jaras', 'BACO2', 'ry-wc-city-select'),
		_x('Szigetvari Jaras', 'BACO2', 'ry-wc-city-select'),
	],
	'BECO' => [
		_x('Bekescsabai Jaras', 'BECO', 'ry-wc-city-select'),
		_x('Bekesi Jaras', 'BECO', 'ry-wc-city-select'),
		_x('Gyomaendrodi Jaras', 'BECO', 'ry-wc-city-select'),
		_x('Gyulai Jaras', 'BECO', 'ry-wc-city-select'),
		_x('Mezokovacshazai Jaras', 'BECO', 'ry-wc-city-select'),
		_x('Oroshazi Jaras', 'BECO', 'ry-wc-city-select'),
		_x('Sarkadi Jaras', 'BECO', 'ry-wc-city-select'),
		_x('Szarvasi Jaras', 'BECO', 'ry-wc-city-select'),
		_x('Szeghalmi Jaras', 'BECO', 'ry-wc-city-select'),
	],
	'BOZECO' => [
		_x('Cigandi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Edelenyi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Encsi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Goenci Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Kazincbarcikai Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Mezocsati Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Mezokoevesdi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Miskolci Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Ozdi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Putnoki Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Sarospataki Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Satoraljaujhelyi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Szerencsi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Szikszoi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Tiszaujvarosi Jaras', 'BOZECO', 'ry-wc-city-select'),
		_x('Tokaji Jaras', 'BOZECO', 'ry-wc-city-select'),
	],
	'BU' => [
		_x('Budapest I.', 'BU', 'ry-wc-city-select'),
		_x('Budapest II.', 'BU', 'ry-wc-city-select'),
		_x('Budapest III.', 'BU', 'ry-wc-city-select'),
		_x('Budapest IV.', 'BU', 'ry-wc-city-select'),
		_x('Budapest IX.', 'BU', 'ry-wc-city-select'),
		_x('Budapest V.', 'BU', 'ry-wc-city-select'),
		_x('Budapest VI.', 'BU', 'ry-wc-city-select'),
		_x('Budapest VII.', 'BU', 'ry-wc-city-select'),
		_x('Budapest VIII.', 'BU', 'ry-wc-city-select'),
		_x('Budapest X.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XI.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XII.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XIII.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XIV.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XIX.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XV.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XVI.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XVII.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XVIII.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XX.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XXI.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XXII.', 'BU', 'ry-wc-city-select'),
		_x('Budapest XXIII.', 'BU', 'ry-wc-city-select'),
	],
	'CSME' => [
		_x('Csongradi Jaras', 'CSME', 'ry-wc-city-select'),
		_x('Hodmezovasarhelyi Jaras', 'CSME', 'ry-wc-city-select'),
		_x('Kisteleki Jaras', 'CSME', 'ry-wc-city-select'),
		_x('Makoi Jaras', 'CSME', 'ry-wc-city-select'),
		_x('Morahalmi Jaras', 'CSME', 'ry-wc-city-select'),
		_x('Szegedi Jaras', 'CSME', 'ry-wc-city-select'),
		_x('Szentesi Jaras', 'CSME', 'ry-wc-city-select'),
	],
	'FEME' => [
		_x('Bicskei Jaras', 'FEME', 'ry-wc-city-select'),
		_x('Dunaujvarosi Jaras', 'FEME', 'ry-wc-city-select'),
		_x('Enyingi Jaras', 'FEME', 'ry-wc-city-select'),
		_x('Gardonyi Jaras', 'FEME', 'ry-wc-city-select'),
		_x('Martonvasari Jaras', 'FEME', 'ry-wc-city-select'),
		_x('Mori Jaras', 'FEME', 'ry-wc-city-select'),
		_x('Sarbogardi Jaras', 'FEME', 'ry-wc-city-select'),
		_x('Szekesfehervari Jaras', 'FEME', 'ry-wc-city-select'),
	],
	'GYME' => [
		_x('Csornai Jaras', 'GYME', 'ry-wc-city-select'),
		_x('Gyori Jaras', 'GYME', 'ry-wc-city-select'),
		_x('Kapuvari Jaras', 'GYME', 'ry-wc-city-select'),
		_x('Mosonmagyarovari Jaras', 'GYME', 'ry-wc-city-select'),
		_x('Pannonhalmi Jaras', 'GYME', 'ry-wc-city-select'),
		_x('Soproni Jaras', 'GYME', 'ry-wc-city-select'),
		_x('Teti Jaras', 'GYME', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Balmazujvarosi Jaras', 'HA', 'ry-wc-city-select'),
		_x('Berettyoujfalui Jaras', 'HA', 'ry-wc-city-select'),
		_x('Debreceni Jaras', 'HA', 'ry-wc-city-select'),
		_x('Derecskei Jaras', 'HA', 'ry-wc-city-select'),
		_x('Hadjuszoboszloi Jaras', 'HA', 'ry-wc-city-select'),
		_x('Hajduboeszoermenyi Jaras', 'HA', 'ry-wc-city-select'),
		_x('Hajduhadhazi Jaras', 'HA', 'ry-wc-city-select'),
		_x('Hajdunanasi Jaras', 'HA', 'ry-wc-city-select'),
		_x('Nyiradonyi Jaras', 'HA', 'ry-wc-city-select'),
		_x('Puespoekladanyi Jaras', 'HA', 'ry-wc-city-select'),
	],
	'HEME' => [
		_x('Belapatfalvai Jaras', 'HEME', 'ry-wc-city-select'),
		_x('Egri Jaras', 'HEME', 'ry-wc-city-select'),
		_x('Fuezesabonyi Jaras', 'HEME', 'ry-wc-city-select'),
		_x('Gyoengyoesi Jaras', 'HEME', 'ry-wc-city-select'),
		_x('Hatvani Jaras', 'HEME', 'ry-wc-city-select'),
		_x('Hevesi Jaras', 'HEME', 'ry-wc-city-select'),
		_x('Petervasarai Jaras', 'HEME', 'ry-wc-city-select'),
	],
	'JA' => [
		_x('Jaszapati Jaras', 'JA', 'ry-wc-city-select'),
		_x('Jaszberenyi Jaras', 'JA', 'ry-wc-city-select'),
		_x('Karcagi Jaras', 'JA', 'ry-wc-city-select'),
		_x('Kunhegyesi Jaras', 'JA', 'ry-wc-city-select'),
		_x('Kunszentmartoni Jaras', 'JA', 'ry-wc-city-select'),
		_x('Mezoturi Jaras', 'JA', 'ry-wc-city-select'),
		_x('Szolnoki Jaras', 'JA', 'ry-wc-city-select'),
		_x('Tiszafueredi Jaras', 'JA', 'ry-wc-city-select'),
		_x('Toeroekszentmiklosi Jaras', 'JA', 'ry-wc-city-select'),
	],
	'KO' => [
		_x('Esztergomi Jaras', 'KO', 'ry-wc-city-select'),
		_x('Kisberi Jaras', 'KO', 'ry-wc-city-select'),
		_x('Komaromi Jaras', 'KO', 'ry-wc-city-select'),
		_x('Oroszlanyi Jaras', 'KO', 'ry-wc-city-select'),
		_x('Tatabanyai Jaras', 'KO', 'ry-wc-city-select'),
		_x('Tatai Jaras', 'KO', 'ry-wc-city-select'),
	],
	'NOME' => [
		_x('Balassagyarmati Jaras', 'NOME', 'ry-wc-city-select'),
		_x('Batonyterenyei Jaras', 'NOME', 'ry-wc-city-select'),
		_x('Pasztoi Jaras', 'NOME', 'ry-wc-city-select'),
		_x('Retsagi Jaras', 'NOME', 'ry-wc-city-select'),
		_x('Salgotarjani Jaras', 'NOME', 'ry-wc-city-select'),
		_x('Szecsenyi Jaras', 'NOME', 'ry-wc-city-select'),
	],
	'PEME' => [
		_x('Aszodi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Budakeszi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Cegledi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Dabasi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Dunakeszi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Erdi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Goedoelloi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Gyali Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Monori Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Nagykatai Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Nagykoroesi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Pilisvoeroesvari Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Rackevei Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Szentendrei Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Szigetszentmiklosi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Szobi Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Vaci Jaras', 'PEME', 'ry-wc-city-select'),
		_x('Vecsesi Jaras', 'PEME', 'ry-wc-city-select'),
	],
	'SOME' => [
		_x('Barcsi Jaras', 'SOME', 'ry-wc-city-select'),
		_x('Csurgoi Jaras', 'SOME', 'ry-wc-city-select'),
		_x('Fonyodi Jaras', 'SOME', 'ry-wc-city-select'),
		_x('Kaposvari Jaras', 'SOME', 'ry-wc-city-select'),
		_x('Marcali Jaras', 'SOME', 'ry-wc-city-select'),
		_x('Nagyatadi Jaras', 'SOME', 'ry-wc-city-select'),
		_x('Siofoki Jaras', 'SOME', 'ry-wc-city-select'),
		_x('Tabi Jaras', 'SOME', 'ry-wc-city-select'),
	],
	'SZ' => [
		_x('Baktaloranthazai Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Csengeri Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Fehergyarmati Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Ibranyi Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Kemecsei Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Kisvardai Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Mateszalkai Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Nagykalloi Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Nyirbatori Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Nyiregyhazi Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Tiszavasvari Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Vasarosnamenyi Jaras', 'SZ', 'ry-wc-city-select'),
		_x('Zahonyi Jaras', 'SZ', 'ry-wc-city-select'),
	],
	'TOME' => [
		_x('Bonyhadi Jaras', 'TOME', 'ry-wc-city-select'),
		_x('Dombovari Jaras', 'TOME', 'ry-wc-city-select'),
		_x('Paksi Jaras', 'TOME', 'ry-wc-city-select'),
		_x('Szekszardi Jaras', 'TOME', 'ry-wc-city-select'),
		_x('Tamasi Jaras', 'TOME', 'ry-wc-city-select'),
		_x('Tolnai Jaras', 'TOME', 'ry-wc-city-select'),
	],
	'VAME' => [
		_x('Celldoemoelki Jaras', 'VAME', 'ry-wc-city-select'),
		_x('Koermendi Jaras', 'VAME', 'ry-wc-city-select'),
		_x('Koszegi Jaras', 'VAME', 'ry-wc-city-select'),
		_x('Sarvari Jaras', 'VAME', 'ry-wc-city-select'),
		_x('Szentgotthardi Jaras', 'VAME', 'ry-wc-city-select'),
		_x('Szombathelyi Jaras', 'VAME', 'ry-wc-city-select'),
		_x('Vasvari Jaras', 'VAME', 'ry-wc-city-select'),
	],
	'VEME' => [
		_x('Ajkai Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Balatonalmadi Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Balatonfueredi Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Devecseri Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Papai Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Suemegi Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Tapolcai Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Varpalotai Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Veszpremi Jaras', 'VEME', 'ry-wc-city-select'),
		_x('Zirci Jaras', 'VEME', 'ry-wc-city-select'),
	],
	'ZAME' => [
		_x('Keszthelyi Jaras', 'ZAME', 'ry-wc-city-select'),
		_x('Lenti Jaras', 'ZAME', 'ry-wc-city-select'),
		_x('Letenyei Jaras', 'ZAME', 'ry-wc-city-select'),
		_x('Nagykanizsai Jaras', 'ZAME', 'ry-wc-city-select'),
		_x('Zalaegerszegi Jaras', 'ZAME', 'ry-wc-city-select'),
		_x('Zalaszentgroti Jaras', 'ZAME', 'ry-wc-city-select'),
	],
	]
];