<?php
/**
 * Republic of Indonesia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'ID' => [
	'EAHARE' => [
		_x('Maba District', 'EAHARE', 'ry-wc-city-select'),
	],
	'KAACBADA' => [
		_x('Kecamatan Jeumpa', 'KAACBADA', 'ry-wc-city-select'),
		_x('Kecamatan Setia', 'KAACBADA', 'ry-wc-city-select'),
		_x('Kecamatan Susoh', 'KAACBADA', 'ry-wc-city-select'),
	],
	'KABA' => [
		_x('Kecamatan Denpasar Selatan', 'KABA', 'ry-wc-city-select'),
		_x('Kecamatan Kuta', 'KABA', 'ry-wc-city-select'),
	],
	'KABA2' => [
		_x('Balantak Selatan', 'KABA2', 'ry-wc-city-select'),
		_x('Balantak Utara', 'KABA2', 'ry-wc-city-select'),
		_x('Batui', 'KABA2', 'ry-wc-city-select'),
		_x('Batui Selatan', 'KABA2', 'ry-wc-city-select'),
		_x('Bualemo', 'KABA2', 'ry-wc-city-select'),
		_x('Kecamatan Balantak', 'KABA2', 'ry-wc-city-select'),
		_x('Kecamatan Bunta', 'KABA2', 'ry-wc-city-select'),
		_x('Kecamatan Kinyo', 'KABA2', 'ry-wc-city-select'),
		_x('Kecamatan Lamala', 'KABA2', 'ry-wc-city-select'),
		_x('Kecamatan Luwuk', 'KABA2', 'ry-wc-city-select'),
		_x('Kecamatan Pagimana', 'KABA2', 'ry-wc-city-select'),
		_x('Lobu', 'KABA2', 'ry-wc-city-select'),
		_x('Luwuk Selatan', 'KABA2', 'ry-wc-city-select'),
		_x('Luwuk Timur', 'KABA2', 'ry-wc-city-select'),
		_x('Luwuk Utara', 'KABA2', 'ry-wc-city-select'),
		_x('Mantoh', 'KABA2', 'ry-wc-city-select'),
		_x('Masama', 'KABA2', 'ry-wc-city-select'),
		_x('Moilong', 'KABA2', 'ry-wc-city-select'),
		_x('Nambo', 'KABA2', 'ry-wc-city-select'),
		_x('Nuhon', 'KABA2', 'ry-wc-city-select'),
		_x('Simpang Raya', 'KABA2', 'ry-wc-city-select'),
		_x('Toili', 'KABA2', 'ry-wc-city-select'),
		_x('Toili Barat', 'KABA2', 'ry-wc-city-select'),
	],
	'KABAKE' => [
		_x('Buko Selatan', 'KABAKE', 'ry-wc-city-select'),
		_x('Bulagi Selatan', 'KABAKE', 'ry-wc-city-select'),
		_x('Bulagi Utara', 'KABAKE', 'ry-wc-city-select'),
		_x('Kecamatan Buko', 'KABAKE', 'ry-wc-city-select'),
		_x('Kecamatan Bulagi', 'KABAKE', 'ry-wc-city-select'),
		_x('Kecamatan Liang', 'KABAKE', 'ry-wc-city-select'),
		_x('Kecamatan Tinangkung', 'KABAKE', 'ry-wc-city-select'),
		_x('Kecamatan Totikum', 'KABAKE', 'ry-wc-city-select'),
		_x('Peling Tengah', 'KABAKE', 'ry-wc-city-select'),
		_x('Tinangkung Selatan', 'KABAKE', 'ry-wc-city-select'),
		_x('Tinangkung Utara', 'KABAKE', 'ry-wc-city-select'),
		_x('Totikum Selatan', 'KABAKE', 'ry-wc-city-select'),
	],
	'KABALA' => [
		_x('Banggai Selatan', 'KABALA', 'ry-wc-city-select'),
		_x('Banggai Tengah', 'KABALA', 'ry-wc-city-select'),
		_x('Banggai Utara', 'KABALA', 'ry-wc-city-select'),
		_x('Bangkurung', 'KABALA', 'ry-wc-city-select'),
		_x('Bokan Kepulauan', 'KABALA', 'ry-wc-city-select'),
		_x('Kecamatan Banggai', 'KABALA', 'ry-wc-city-select'),
		_x('Labobo', 'KABALA', 'ry-wc-city-select'),
	],
	'KABEME' => [
		_x('Kecamatan Permata', 'KABEME', 'ry-wc-city-select'),
	],
	'KABI' => [
		_x('Belo District', 'KABI', 'ry-wc-city-select'),
		_x('Bolo District', 'KABI', 'ry-wc-city-select'),
		_x('Donggo District', 'KABI', 'ry-wc-city-select'),
		_x('Kecamatan Ambalawi', 'KABI', 'ry-wc-city-select'),
		_x('Kecamatan Lambitu', 'KABI', 'ry-wc-city-select'),
		_x('Kecamatan Lambu', 'KABI', 'ry-wc-city-select'),
		_x('Kecamatan Langgudu', 'KABI', 'ry-wc-city-select'),
		_x('Kecamatan Madapangga', 'KABI', 'ry-wc-city-select'),
		_x('Kecamatan Palibelo', 'KABI', 'ry-wc-city-select'),
		_x('Kecamatan Parado', 'KABI', 'ry-wc-city-select'),
		_x('Kecamatan Soromandi', 'KABI', 'ry-wc-city-select'),
		_x('Monta District', 'KABI', 'ry-wc-city-select'),
		_x('Sanggar District', 'KABI', 'ry-wc-city-select'),
		_x('Sape District', 'KABI', 'ry-wc-city-select'),
		_x('Wawo District', 'KABI', 'ry-wc-city-select'),
		_x('Wera', 'KABI', 'ry-wc-city-select'),
		_x('Woha District', 'KABI', 'ry-wc-city-select'),
	],
	'KABU' => [
		_x('Kecamatan Banjar', 'KABU', 'ry-wc-city-select'),
		_x('Kecamatan Buleleng', 'KABU', 'ry-wc-city-select'),
		_x('Kecamatan Busung Biu', 'KABU', 'ry-wc-city-select'),
		_x('Kecamatan Kubutambahan', 'KABU', 'ry-wc-city-select'),
		_x('Kecamatan Sawan', 'KABU', 'ry-wc-city-select'),
		_x('Kecamatan Seririt', 'KABU', 'ry-wc-city-select'),
		_x('Kecamatan Sukasada', 'KABU', 'ry-wc-city-select'),
	],
	'KABU2' => [
		_x('Bukal', 'KABU2', 'ry-wc-city-select'),
		_x('Bunobogu', 'KABU2', 'ry-wc-city-select'),
		_x('Gadung', 'KABU2', 'ry-wc-city-select'),
		_x('Karamat', 'KABU2', 'ry-wc-city-select'),
		_x('Kecamatan Biau', 'KABU2', 'ry-wc-city-select'),
		_x('Kecamatan Bokat', 'KABU2', 'ry-wc-city-select'),
		_x('Kecamatan Momunu', 'KABU2', 'ry-wc-city-select'),
		_x('Kecamatan Paleleh', 'KABU2', 'ry-wc-city-select'),
		_x('Lakea', 'KABU2', 'ry-wc-city-select'),
		_x('Paleleh Barat', 'KABU2', 'ry-wc-city-select'),
		_x('Tiloan', 'KABU2', 'ry-wc-city-select'),
	],
	'KACI' => [
		_x('Kecamatan Weru', 'KACI', 'ry-wc-city-select'),
	],
	'KADO' => [
		_x('Balaesang Tanjung', 'KADO', 'ry-wc-city-select'),
		_x('Banawa Selatan', 'KADO', 'ry-wc-city-select'),
		_x('Banawa Tengah', 'KADO', 'ry-wc-city-select'),
		_x('Kecamatan Balaesang', 'KADO', 'ry-wc-city-select'),
		_x('Kecamatan Banawa', 'KADO', 'ry-wc-city-select'),
		_x('Kecamatan Dampelassojol', 'KADO', 'ry-wc-city-select'),
		_x('Kecamatan Sindue', 'KADO', 'ry-wc-city-select'),
		_x('Kecamatan Sirenja', 'KADO', 'ry-wc-city-select'),
		_x('Kecamatan Tanantovea', 'KADO', 'ry-wc-city-select'),
		_x('Labuan', 'KADO', 'ry-wc-city-select'),
		_x('Pinembani', 'KADO', 'ry-wc-city-select'),
		_x('Rio Pakava', 'KADO', 'ry-wc-city-select'),
		_x('Sindue Tobata', 'KADO', 'ry-wc-city-select'),
		_x('Sindue Tombusabora', 'KADO', 'ry-wc-city-select'),
		_x('Sojol', 'KADO', 'ry-wc-city-select'),
		_x('Sojol Utara', 'KADO', 'ry-wc-city-select'),
	],
	'KAFLTI' => [
		_x('Larantuka District', 'KAFLTI', 'ry-wc-city-select'),
	],
	'KAHABA' => [
		_x('Ibu Selatan', 'KAHABA', 'ry-wc-city-select'),
	],
	'KAKA' => [
		_x('Kecamatan Batujaya', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Cibuaya', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Cikampek', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Cilamaya', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Jatisari', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Karawang Barat', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Klari', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Lemahabang', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Lemahabang', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Pakisjaya', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Pangkalan', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Pedes', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Rawamerta', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Rengasdengklok', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Talagasari', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Telukjambe', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Tempuran', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Tirtajaya', 'KAKA', 'ry-wc-city-select'),
		_x('Kecamatan Tirtamulya', 'KAKA', 'ry-wc-city-select'),
	],
	'KAKUPR' => [
		_x('Kecamatan Temon', 'KAKUPR', 'ry-wc-city-select'),
	],
	'KALOBA' => [
		_x('Central Sekotong District', 'KALOBA', 'ry-wc-city-select'),
		_x('Gerung District', 'KALOBA', 'ry-wc-city-select'),
		_x('Gunungsari District', 'KALOBA', 'ry-wc-city-select'),
		_x('Kediri District', 'KALOBA', 'ry-wc-city-select'),
		_x('Narmada District', 'KALOBA', 'ry-wc-city-select'),
	],
	'KALOTE' => [
		_x('East Praya District', 'KALOTE', 'ry-wc-city-select'),
		_x('Janapria District', 'KALOTE', 'ry-wc-city-select'),
		_x('Jonggat District', 'KALOTE', 'ry-wc-city-select'),
		_x('Kopang District', 'KALOTE', 'ry-wc-city-select'),
		_x('Praya District', 'KALOTE', 'ry-wc-city-select'),
		_x('Pringgarata District', 'KALOTE', 'ry-wc-city-select'),
		_x('Pujut District', 'KALOTE', 'ry-wc-city-select'),
		_x('West Praya District', 'KALOTE', 'ry-wc-city-select'),
	],
	'KALOUT' => [
		_x('Bayan District', 'KALOUT', 'ry-wc-city-select'),
		_x('Gangga District', 'KALOUT', 'ry-wc-city-select'),
		_x('Tanjung District', 'KALOUT', 'ry-wc-city-select'),
	],
	'KAMABA' => [
		_x('Kecamatan Komodo', 'KAMABA', 'ry-wc-city-select'),
	],
	'KAMOUT' => [
		_x('Kecamatan Bungku Utara', 'KAMOUT', 'ry-wc-city-select'),
		_x('Kecamatan Lembo', 'KAMOUT', 'ry-wc-city-select'),
		_x('Kecamatan Petasia', 'KAMOUT', 'ry-wc-city-select'),
		_x('Lembo Raya', 'KAMOUT', 'ry-wc-city-select'),
		_x('Mamosalato', 'KAMOUT', 'ry-wc-city-select'),
		_x('Mori Atas', 'KAMOUT', 'ry-wc-city-select'),
		_x('Mori Utara', 'KAMOUT', 'ry-wc-city-select'),
		_x('Petasia Timur', 'KAMOUT', 'ry-wc-city-select'),
		_x('Soyo Jaya', 'KAMOUT', 'ry-wc-city-select'),
	],
	'KANU' => [
		_x('Kecamatan Sembakung', 'KANU', 'ry-wc-city-select'),
	],
	'KAPAMO' => [
		_x('Balinggi', 'KAPAMO', 'ry-wc-city-select'),
		_x('Bolano', 'KAPAMO', 'ry-wc-city-select'),
		_x('Bolano Lambunu', 'KAPAMO', 'ry-wc-city-select'),
		_x('Kasimbar', 'KAPAMO', 'ry-wc-city-select'),
		_x('Kecamatan Ampibabo', 'KAPAMO', 'ry-wc-city-select'),
		_x('Kecamatan Moutong', 'KAPAMO', 'ry-wc-city-select'),
		_x('Kecamatan Parigi', 'KAPAMO', 'ry-wc-city-select'),
		_x('Kecamatan Tinombo', 'KAPAMO', 'ry-wc-city-select'),
		_x('Kecamatan Tomini', 'KAPAMO', 'ry-wc-city-select'),
		_x('Mepanga', 'KAPAMO', 'ry-wc-city-select'),
		_x('Ongka Malino', 'KAPAMO', 'ry-wc-city-select'),
		_x('Palasa', 'KAPAMO', 'ry-wc-city-select'),
		_x('Parigi Barat', 'KAPAMO', 'ry-wc-city-select'),
		_x('Parigi Selatan', 'KAPAMO', 'ry-wc-city-select'),
		_x('Parigi Tengah', 'KAPAMO', 'ry-wc-city-select'),
		_x('Parigi Utara', 'KAPAMO', 'ry-wc-city-select'),
		_x('Sausu', 'KAPAMO', 'ry-wc-city-select'),
		_x('Sidoan', 'KAPAMO', 'ry-wc-city-select'),
		_x('Siniu', 'KAPAMO', 'ry-wc-city-select'),
		_x('Taopa', 'KAPAMO', 'ry-wc-city-select'),
		_x('Tinombo Selatan', 'KAPAMO', 'ry-wc-city-select'),
		_x('Toribulu', 'KAPAMO', 'ry-wc-city-select'),
		_x('Torue', 'KAPAMO', 'ry-wc-city-select'),
	],
	'KAPA' => [
		_x('Kecamatan Lumbang', 'KAPA', 'ry-wc-city-select'),
	],
	'KAPEBI' => [
		_x('Oksibil', 'KAPEBI', 'ry-wc-city-select'),
	],
	'KAPE' => [
		_x('Kecamatan Taman', 'KAPE', 'ry-wc-city-select'),
	],
	'KAPOMA' => [
		_x('Kecamatan Polewali', 'KAPOMA', 'ry-wc-city-select'),
	],
	'KAPO' => [
		_x('Kecamatan Lore Selatan', 'KAPO', 'ry-wc-city-select'),
		_x('Kecamatan Lore Utara', 'KAPO', 'ry-wc-city-select'),
		_x('Kecamatan Pamona Utara', 'KAPO', 'ry-wc-city-select'),
		_x('Kecamatan Poso Kota', 'KAPO', 'ry-wc-city-select'),
		_x('Kecamatan Poso Pesisir', 'KAPO', 'ry-wc-city-select'),
		_x('Lage', 'KAPO', 'ry-wc-city-select'),
		_x('Lore Barat', 'KAPO', 'ry-wc-city-select'),
		_x('Lore Peore', 'KAPO', 'ry-wc-city-select'),
		_x('Lore Tengah', 'KAPO', 'ry-wc-city-select'),
		_x('Lore Timur', 'KAPO', 'ry-wc-city-select'),
		_x('Pamona Barat', 'KAPO', 'ry-wc-city-select'),
		_x('Pamona Pusalemba', 'KAPO', 'ry-wc-city-select'),
		_x('Pamona Timur', 'KAPO', 'ry-wc-city-select'),
		_x('Poso Kota Selatan', 'KAPO', 'ry-wc-city-select'),
		_x('Poso Kota Utara', 'KAPO', 'ry-wc-city-select'),
		_x('Poso Pesisir', 'KAPO', 'ry-wc-city-select'),
		_x('Poso Pesisir Utara', 'KAPO', 'ry-wc-city-select'),
	],
	'KAPU' => [
		_x('Kecamatan Kemangkon', 'KAPU', 'ry-wc-city-select'),
	],
	'KASI' => [
		_x('Dolo Barat', 'KASI', 'ry-wc-city-select'),
		_x('Dolo Selatan', 'KASI', 'ry-wc-city-select'),
		_x('Gumbasa', 'KASI', 'ry-wc-city-select'),
		_x('Kecamatan Dolo', 'KASI', 'ry-wc-city-select'),
		_x('Kecamatan Kulawi', 'KASI', 'ry-wc-city-select'),
		_x('Kecamatan Marawola', 'KASI', 'ry-wc-city-select'),
		_x('Kecamatan Sigibiromaru', 'KASI', 'ry-wc-city-select'),
		_x('Kinovaro', 'KASI', 'ry-wc-city-select'),
		_x('Kulawi Selatan', 'KASI', 'ry-wc-city-select'),
		_x('Lindu', 'KASI', 'ry-wc-city-select'),
		_x('Marawola Barat', 'KASI', 'ry-wc-city-select'),
		_x('Nokilalaki', 'KASI', 'ry-wc-city-select'),
		_x('Palolo', 'KASI', 'ry-wc-city-select'),
		_x('Pipikoro', 'KASI', 'ry-wc-city-select'),
		_x('Tanambulava', 'KASI', 'ry-wc-city-select'),
	],
	'KASUBA' => [
		_x('Jereweh District', 'KASUBA', 'ry-wc-city-select'),
		_x('Labuapi District', 'KASUBA', 'ry-wc-city-select'),
		_x('Seteluk District', 'KASUBA', 'ry-wc-city-select'),
		_x('Taliwang District', 'KASUBA', 'ry-wc-city-select'),
	],
	'KASU' => [
		_x('Kecamatan Sumedang Selatan', 'KASU', 'ry-wc-city-select'),
		_x('Kecamatan Sumedang Utara', 'KASU', 'ry-wc-city-select'),
	],
	'KATO' => [
		_x('Basidondo', 'KATO', 'ry-wc-city-select'),
		_x('Dako Pemean', 'KATO', 'ry-wc-city-select'),
		_x('Kecamatan Baolan', 'KATO', 'ry-wc-city-select'),
		_x('Kecamatan Dampal Selatan', 'KATO', 'ry-wc-city-select'),
		_x('Kecamatan Dampal Utara', 'KATO', 'ry-wc-city-select'),
		_x('Kecamatan Dondo', 'KATO', 'ry-wc-city-select'),
		_x('Kecamatan Galang', 'KATO', 'ry-wc-city-select'),
		_x('Kecamatan Tolitoli Utara', 'KATO', 'ry-wc-city-select'),
		_x('Lampasio', 'KATO', 'ry-wc-city-select'),
		_x('Ogodeide', 'KATO', 'ry-wc-city-select'),
	],
	'KOBA' => [
		_x('Kecamatan Batam Kota', 'KOBA', 'ry-wc-city-select'),
		_x('Kecamatan Batu Aji', 'KOBA', 'ry-wc-city-select'),
		_x('Kecamatan Batu Ampar', 'KOBA', 'ry-wc-city-select'),
		_x('Kecamatan Bengkong', 'KOBA', 'ry-wc-city-select'),
		_x('Kecamatan Nongsa', 'KOBA', 'ry-wc-city-select'),
		_x('Kecamatan Sagulung', 'KOBA', 'ry-wc-city-select'),
		_x('Kecamatan Sekupang', 'KOBA', 'ry-wc-city-select'),
		_x('Kecamatan Sungei Beduk', 'KOBA', 'ry-wc-city-select'),
	],
	'KOBI' => [
		_x('East Rasanae District', 'KOBI', 'ry-wc-city-select'),
		_x('West Rasanae District', 'KOBI', 'ry-wc-city-select'),
	],
	'KODE' => [
		_x('Kecamatan Kesiman', 'KODE', 'ry-wc-city-select'),
	],
	'KOPA' => [
		_x('Kecamatan Palu Barat', 'KOPA', 'ry-wc-city-select'),
		_x('Kecamatan Palu Timur', 'KOPA', 'ry-wc-city-select'),
		_x('Mantikulore', 'KOPA', 'ry-wc-city-select'),
		_x('Palu Selatan', 'KOPA', 'ry-wc-city-select'),
		_x('Palu Utara', 'KOPA', 'ry-wc-city-select'),
		_x('Tatanga', 'KOPA', 'ry-wc-city-select'),
		_x('Tawaeli', 'KOPA', 'ry-wc-city-select'),
		_x('Ulujadi', 'KOPA', 'ry-wc-city-select'),
	],
	'LARE' => [
		_x('Kecamatan Jerai', 'LARE', 'ry-wc-city-select'),
		_x('Kecamatan Kikim', 'LARE', 'ry-wc-city-select'),
		_x('Kecamatan Kotaagung', 'LARE', 'ry-wc-city-select'),
		_x('Kecamatan Kotolahat', 'LARE', 'ry-wc-city-select'),
		_x('Kecamatan Merapi', 'LARE', 'ry-wc-city-select'),
		_x('Kecamatan Pulaupinang', 'LARE', 'ry-wc-city-select'),
		_x('Kecamatan Tanjungsakti', 'LARE', 'ry-wc-city-select'),
	],
	'MORE' => [
		_x('Bahodopi', 'MORE', 'ry-wc-city-select'),
		_x('Bumi Raya', 'MORE', 'ry-wc-city-select'),
		_x('Bungku Barat', 'MORE', 'ry-wc-city-select'),
		_x('Bungku Pesisir', 'MORE', 'ry-wc-city-select'),
		_x('Bungku Timur', 'MORE', 'ry-wc-city-select'),
		_x('Kecamatan Bungku Selatan', 'MORE', 'ry-wc-city-select'),
		_x('Kecamatan Bungku Tengah', 'MORE', 'ry-wc-city-select'),
		_x('Kecamatan Menuikepulauan', 'MORE', 'ry-wc-city-select'),
		_x('Wita Ponda', 'MORE', 'ry-wc-city-select'),
	],
	'TOUNRE' => [
		_x('Kecamatan Ampana Kota', 'TOUNRE', 'ry-wc-city-select'),
		_x('Kecamatan Ampana Tete', 'TOUNRE', 'ry-wc-city-select'),
		_x('Kecamatan Ulubongka', 'TOUNRE', 'ry-wc-city-select'),
		_x('Kecamatan Unauna', 'TOUNRE', 'ry-wc-city-select'),
		_x('Kecamatan Waleakepulauan', 'TOUNRE', 'ry-wc-city-select'),
		_x('Togean', 'TOUNRE', 'ry-wc-city-select'),
		_x('Tojo Barat', 'TOUNRE', 'ry-wc-city-select'),
		_x('Walea Besar', 'TOUNRE', 'ry-wc-city-select'),
	],
	'WARE' => [
		_x('Kecamatan Wangi-wangi', 'WARE', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Kabupaten Lebak', 'BA', 'ry-wc-city-select'),
		_x('Kabupaten Pandeglang', 'BA', 'ry-wc-city-select'),
		_x('Kabupaten Serang', 'BA', 'ry-wc-city-select'),
		_x('Kabupaten Tangerang', 'BA', 'ry-wc-city-select'),
		_x('Kota Cilegon', 'BA', 'ry-wc-city-select'),
		_x('Kota Serang', 'BA', 'ry-wc-city-select'),
		_x('Kota Tangerang', 'BA', 'ry-wc-city-select'),
		_x('Kota Tangerang Selatan', 'BA', 'ry-wc-city-select'),
	],
	'DAISYO' => [
		_x('Kabupaten Bantul', 'DAISYO', 'ry-wc-city-select'),
		_x('Kabupaten Gunung Kidul', 'DAISYO', 'ry-wc-city-select'),
		_x('Kabupaten Sleman', 'DAISYO', 'ry-wc-city-select'),
		_x('Kota Yogyakarta', 'DAISYO', 'ry-wc-city-select'),
	],
	'DAKHIBJA' => [
		_x('Kabupaten Administrasi Kepulauan Seribu', 'DAKHIBJA', 'ry-wc-city-select'),
		_x('Kota Administrasi Jakarta Barat', 'DAKHIBJA', 'ry-wc-city-select'),
		_x('Kota Administrasi Jakarta Pusat', 'DAKHIBJA', 'ry-wc-city-select'),
		_x('Kota Administrasi Jakarta Selatan', 'DAKHIBJA', 'ry-wc-city-select'),
		_x('Kota Administrasi Jakarta Timur', 'DAKHIBJA', 'ry-wc-city-select'),
		_x('Kota Administrasi Jakarta Utara', 'DAKHIBJA', 'ry-wc-city-select'),
	],
	'EANUTE' => [
		_x('Kabupaten Alor', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Belu', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Ende', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Kupang', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Lembata', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Malaka', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Manggarai', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Manggarai Timur', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Nagekeo', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Ngada', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Rote Ndao', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Sabu Raijua', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Sikka', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Sumba Barat', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Sumba Barat Daya', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Sumba Tengah', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Sumba Timur', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Timor Tengah Selatan', 'EANUTE', 'ry-wc-city-select'),
		_x('Kabupaten Timor Tengah Utara', 'EANUTE', 'ry-wc-city-select'),
		_x('Kota Kupang', 'EANUTE', 'ry-wc-city-select'),
	],
	'JABA' => [
		_x('Kabupaten Bandung', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Bandung Barat', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Bekasi', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Bogor', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Ciamis', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Cianjur', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Garut', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Indramayu', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Kuningan', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Majalengka', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Pangandaran', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Purwakarta', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Subang', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Sukabumi', 'JABA', 'ry-wc-city-select'),
		_x('Kabupaten Tasikmalaya', 'JABA', 'ry-wc-city-select'),
		_x('Kota Bandung', 'JABA', 'ry-wc-city-select'),
		_x('Kota Banjar', 'JABA', 'ry-wc-city-select'),
		_x('Kota Bekasi', 'JABA', 'ry-wc-city-select'),
		_x('Kota Bogor', 'JABA', 'ry-wc-city-select'),
		_x('Kota Cimahi', 'JABA', 'ry-wc-city-select'),
		_x('Kota Cirebon', 'JABA', 'ry-wc-city-select'),
		_x('Kota Depok', 'JABA', 'ry-wc-city-select'),
		_x('Kota Sukabumi', 'JABA', 'ry-wc-city-select'),
		_x('Kota Tasikmalaya', 'JABA', 'ry-wc-city-select'),
	],
	'JATI' => [
		_x('Gresik Regency', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Bangkalan', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Banyuwangi', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Blitar', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Bojonegoro', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Bondowoso', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Jember', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Jombang', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Kediri', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Lamongan', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Lumajang', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Madiun', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Magetan', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Malang', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Mojokerto', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Nganjuk', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Ngawi', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Pacitan', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Pamekasan', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Ponorogo', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Probolinggo', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Sampang', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Sidoarjo', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Situbondo', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Sumenep', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Trenggalek', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Tuban', 'JATI', 'ry-wc-city-select'),
		_x('Kabupaten Tulungagung', 'JATI', 'ry-wc-city-select'),
		_x('Kota Batu', 'JATI', 'ry-wc-city-select'),
		_x('Kota Blitar', 'JATI', 'ry-wc-city-select'),
		_x('Kota Kediri', 'JATI', 'ry-wc-city-select'),
		_x('Kota Madiun', 'JATI', 'ry-wc-city-select'),
		_x('Kota Malang', 'JATI', 'ry-wc-city-select'),
		_x('Kota Mojokerto', 'JATI', 'ry-wc-city-select'),
		_x('Kota Pasuruan', 'JATI', 'ry-wc-city-select'),
		_x('Kota Probolinggo', 'JATI', 'ry-wc-city-select'),
		_x('Kota Surabaya', 'JATI', 'ry-wc-city-select'),
	],
	'KEBABE' => [
		_x('Kabupaten Bangka', 'KEBABE', 'ry-wc-city-select'),
		_x('Kabupaten Bangka Barat', 'KEBABE', 'ry-wc-city-select'),
		_x('Kabupaten Bangka Selatan', 'KEBABE', 'ry-wc-city-select'),
		_x('Kabupaten Bangka Tengah', 'KEBABE', 'ry-wc-city-select'),
		_x('Kabupaten Belitung', 'KEBABE', 'ry-wc-city-select'),
		_x('Kabupaten Belitung Timur', 'KEBABE', 'ry-wc-city-select'),
		_x('Kota Pangkal Pinang', 'KEBABE', 'ry-wc-city-select'),
	],
	'NAACDAPR' => [
		_x('Kabupaten Aceh Barat', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Besar', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Jaya', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Selatan', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Singkil', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Tamiang', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Tengah', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Tenggara', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Timur', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Aceh Utara', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Bireuen', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Gayo Lues', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Nagan Raya', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Pidie', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Pidie Jaya', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kabupaten Simeulue', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kota Banda Aceh', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kota Langsa', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kota Lhokseumawe', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kota Sabang', 'NAACDAPR', 'ry-wc-city-select'),
		_x('Kota Subulussalam', 'NAACDAPR', 'ry-wc-city-select'),
	],
	'NOKA' => [
		_x('Kabupaten Bulungan', 'NOKA', 'ry-wc-city-select'),
		_x('Kabupaten Malinau', 'NOKA', 'ry-wc-city-select'),
		_x('Kabupaten Tana Tidung', 'NOKA', 'ry-wc-city-select'),
		_x('Kota Tarakan', 'NOKA', 'ry-wc-city-select'),
	],
	'NOMA' => [
		_x('Kabupaten Halmahera Selatan', 'NOMA', 'ry-wc-city-select'),
		_x('Kabupaten Halmahera Tengah', 'NOMA', 'ry-wc-city-select'),
		_x('Kabupaten Halmahera Utara', 'NOMA', 'ry-wc-city-select'),
		_x('Kabupaten Kepulauan Sula', 'NOMA', 'ry-wc-city-select'),
		_x('Kabupaten Pulau Morotai', 'NOMA', 'ry-wc-city-select'),
		_x('Kabupaten Pulau Taliabu', 'NOMA', 'ry-wc-city-select'),
		_x('Kota Ternate', 'NOMA', 'ry-wc-city-select'),
		_x('Kota Tidore Kepulauan', 'NOMA', 'ry-wc-city-select'),
	],
	'NOSU' => [
		_x('Kabupaten Asahan', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Batu Bara', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Dairi', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Deli Serdang', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Humbang Hasundutan', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Karo', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Labuhan Batu', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Labuhan Batu Selatan', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Labuhan Batu Utara', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Langkat', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Mandailing Natal', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Nias', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Nias Barat', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Nias Selatan', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Nias Utara', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Padang Lawas', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Padang Lawas Utara', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Pakpak Bharat', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Samosir', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Serdang Bedagai', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Simalungun', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Tapanuli Tengah', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Tapanuli Utara', 'NOSU', 'ry-wc-city-select'),
		_x('Kabupaten Toba Samosir', 'NOSU', 'ry-wc-city-select'),
		_x('Kota Binjai', 'NOSU', 'ry-wc-city-select'),
		_x('Kota Gunungsitoli', 'NOSU', 'ry-wc-city-select'),
		_x('Kota Medan', 'NOSU', 'ry-wc-city-select'),
		_x('Kota Padangsidimpuan', 'NOSU', 'ry-wc-city-select'),
		_x('Kota Pematang Siantar', 'NOSU', 'ry-wc-city-select'),
		_x('Kota Sibolga', 'NOSU', 'ry-wc-city-select'),
		_x('Kota Tanjung Balai', 'NOSU', 'ry-wc-city-select'),
		_x('Kota Tebing Tinggi', 'NOSU', 'ry-wc-city-select'),
		_x('South Tapanuli Regency', 'NOSU', 'ry-wc-city-select'),
	],
	'PRBE' => [
		_x('Kabupaten Bengkulu Selatan', 'PRBE', 'ry-wc-city-select'),
		_x('Kabupaten Bengkulu Tengah', 'PRBE', 'ry-wc-city-select'),
		_x('Kabupaten Bengkulu Utara', 'PRBE', 'ry-wc-city-select'),
		_x('Kabupaten Kaur', 'PRBE', 'ry-wc-city-select'),
		_x('Kabupaten Kepahiang', 'PRBE', 'ry-wc-city-select'),
		_x('Kabupaten Lebong', 'PRBE', 'ry-wc-city-select'),
		_x('Kabupaten Mukomuko', 'PRBE', 'ry-wc-city-select'),
		_x('Kabupaten Rejang Lebong', 'PRBE', 'ry-wc-city-select'),
		_x('Kabupaten Seluma', 'PRBE', 'ry-wc-city-select'),
		_x('Kota Bengkulu', 'PRBE', 'ry-wc-city-select'),
	],
	'PRBA' => [
		_x('Kabupaten Bangli', 'PRBA', 'ry-wc-city-select'),
		_x('Kabupaten Gianyar', 'PRBA', 'ry-wc-city-select'),
		_x('Kabupaten Jembrana', 'PRBA', 'ry-wc-city-select'),
		_x('Kabupaten Karang Asem', 'PRBA', 'ry-wc-city-select'),
		_x('Kabupaten Klungkung', 'PRBA', 'ry-wc-city-select'),
		_x('Kabupaten Tabanan', 'PRBA', 'ry-wc-city-select'),
	],
	'PRGO' => [
		_x('Kabupaten Boalemo', 'PRGO', 'ry-wc-city-select'),
		_x('Kabupaten Bone Bolango', 'PRGO', 'ry-wc-city-select'),
		_x('Kabupaten Gorontalo', 'PRGO', 'ry-wc-city-select'),
		_x('Kabupaten Gorontalo Utara', 'PRGO', 'ry-wc-city-select'),
		_x('Kabupaten Pohuwato', 'PRGO', 'ry-wc-city-select'),
		_x('Kota Gorontalo', 'PRGO', 'ry-wc-city-select'),
	],
	'PRJA' => [
		_x('Kabupaten Batang Hari', 'PRJA', 'ry-wc-city-select'),
		_x('Kabupaten Bungo', 'PRJA', 'ry-wc-city-select'),
		_x('Kabupaten Kerinci', 'PRJA', 'ry-wc-city-select'),
		_x('Kabupaten Merangin', 'PRJA', 'ry-wc-city-select'),
		_x('Kabupaten Muaro Jambi', 'PRJA', 'ry-wc-city-select'),
		_x('Kabupaten Sarolangun', 'PRJA', 'ry-wc-city-select'),
		_x('Kabupaten Tanjung Jabung Barat', 'PRJA', 'ry-wc-city-select'),
		_x('Kabupaten Tanjung Jabung Timur', 'PRJA', 'ry-wc-city-select'),
		_x('Kabupaten Tebo', 'PRJA', 'ry-wc-city-select'),
		_x('Kota Jambi', 'PRJA', 'ry-wc-city-select'),
		_x('Kota Sungai Penuh', 'PRJA', 'ry-wc-city-select'),
	],
	'PRJATE' => [
		_x('Kabupaten Banjarnegara', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Banyumas', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Batang', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Blora', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Boyolali', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Brebes', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Cilacap', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Demak', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Grobogan', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Jepara', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Karanganyar', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Kebumen', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Kendal', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Klaten', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Kudus', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Magelang', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Pati', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Pekalongan', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Purworejo', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Rembang', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Semarang', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Sragen', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Sukoharjo', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Tegal', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Temanggung', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Wonogiri', 'PRJATE', 'ry-wc-city-select'),
		_x('Kabupaten Wonosobo', 'PRJATE', 'ry-wc-city-select'),
		_x('Kota Magelang', 'PRJATE', 'ry-wc-city-select'),
		_x('Kota Pekalongan', 'PRJATE', 'ry-wc-city-select'),
		_x('Kota Salatiga', 'PRJATE', 'ry-wc-city-select'),
		_x('Kota Semarang', 'PRJATE', 'ry-wc-city-select'),
		_x('Kota Surakarta', 'PRJATE', 'ry-wc-city-select'),
		_x('Kota Tegal', 'PRJATE', 'ry-wc-city-select'),
	],
	'PRKABA' => [
		_x('Kabupaten Bengkayang', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Kapuas Hulu', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Kayong Utara', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Ketapang', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Kubu Raya', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Landak', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Melawi', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Mempawah', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Sambas', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Sanggau', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Sekadau', 'PRKABA', 'ry-wc-city-select'),
		_x('Kabupaten Sintang', 'PRKABA', 'ry-wc-city-select'),
		_x('Kota Pontianak', 'PRKABA', 'ry-wc-city-select'),
		_x('Kota Singkawang', 'PRKABA', 'ry-wc-city-select'),
	],
	'PRKASE' => [
		_x('Kabupaten Balangan', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Banjar', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Barito Kuala', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Hulu Sungai Selatan', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Hulu Sungai Tengah', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Hulu Sungai Utara', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Kota Baru', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Tabalong', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Tanah Bumbu', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Tanah Laut', 'PRKASE', 'ry-wc-city-select'),
		_x('Kabupaten Tapin', 'PRKASE', 'ry-wc-city-select'),
		_x('Kota Banjar Baru', 'PRKASE', 'ry-wc-city-select'),
		_x('Kota Banjarmasin', 'PRKASE', 'ry-wc-city-select'),
	],
	'PRKATE' => [
		_x('Kabupaten Barito Selatan', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Barito Timur', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Barito Utara', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Gunung Mas', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Kapuas', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Katingan', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Kotawaringin Barat', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Kotawaringin Timur', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Lamandau', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Murung Raya', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Pulang Pisau', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Seruyan', 'PRKATE', 'ry-wc-city-select'),
		_x('Kabupaten Sukamara', 'PRKATE', 'ry-wc-city-select'),
		_x('Kota Palangka Raya', 'PRKATE', 'ry-wc-city-select'),
	],
	'PRKATI' => [
		_x('Kabupaten Berau', 'PRKATI', 'ry-wc-city-select'),
		_x('Kabupaten Kutai Barat', 'PRKATI', 'ry-wc-city-select'),
		_x('Kabupaten Kutai Kartanegara', 'PRKATI', 'ry-wc-city-select'),
		_x('Kabupaten Kutai Timur', 'PRKATI', 'ry-wc-city-select'),
		_x('Kabupaten Mahakam Hulu', 'PRKATI', 'ry-wc-city-select'),
		_x('Kabupaten Paser', 'PRKATI', 'ry-wc-city-select'),
		_x('Kabupaten Penajam Paser Utara', 'PRKATI', 'ry-wc-city-select'),
		_x('Kota Balikpapan', 'PRKATI', 'ry-wc-city-select'),
		_x('Kota Bontang', 'PRKATI', 'ry-wc-city-select'),
		_x('Kota Samarinda', 'PRKATI', 'ry-wc-city-select'),
	],
	'PRKERI' => [
		_x('Kabupaten Bintan', 'PRKERI', 'ry-wc-city-select'),
		_x('Kabupaten Karimun', 'PRKERI', 'ry-wc-city-select'),
		_x('Kabupaten Kepulauan Anambas', 'PRKERI', 'ry-wc-city-select'),
		_x('Kabupaten Lingga', 'PRKERI', 'ry-wc-city-select'),
		_x('Kabupaten Natuna', 'PRKERI', 'ry-wc-city-select'),
		_x('Kota Tanjung Pinang', 'PRKERI', 'ry-wc-city-select'),
	],
	'PRLA' => [
		_x('Kabupaten Lampung Barat', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Lampung Selatan', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Lampung Tengah', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Lampung Timur', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Lampung Utara', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Mesuji', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Pesawaran', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Pringsewu', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Tanggamus', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Tulang Bawang Barat', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Tulangbawang', 'PRLA', 'ry-wc-city-select'),
		_x('Kabupaten Way Kanan', 'PRLA', 'ry-wc-city-select'),
		_x('Kota Bandar Lampung', 'PRLA', 'ry-wc-city-select'),
		_x('Kota Metro', 'PRLA', 'ry-wc-city-select'),
		_x('West Pesisir Regency', 'PRLA', 'ry-wc-city-select'),
	],
	'PRMA' => [
		_x('Kabupaten Buru', 'PRMA', 'ry-wc-city-select'),
		_x('Kabupaten Buru Selatan', 'PRMA', 'ry-wc-city-select'),
		_x('Kabupaten Kepulauan Aru', 'PRMA', 'ry-wc-city-select'),
		_x('Kabupaten Maluku Barat Daya', 'PRMA', 'ry-wc-city-select'),
		_x('Kabupaten Maluku Tengah', 'PRMA', 'ry-wc-city-select'),
		_x('Kabupaten Maluku Tenggara', 'PRMA', 'ry-wc-city-select'),
		_x('Kabupaten Maluku Tenggara Barat', 'PRMA', 'ry-wc-city-select'),
		_x('Kabupaten Seram Bagian Barat', 'PRMA', 'ry-wc-city-select'),
		_x('Kabupaten Seram Bagian Timur', 'PRMA', 'ry-wc-city-select'),
		_x('Kota Ambon', 'PRMA', 'ry-wc-city-select'),
		_x('Kota Tual', 'PRMA', 'ry-wc-city-select'),
	],
	'PRPA' => [
		_x('Kabupaten Asmat', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Biak Numfor', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Boven Digoel', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Deiyai', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Dogiyai', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Intan Jaya', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Jayapura', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Jayawijaya', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Keerom', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Kepulauan Yapen', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Lanny Jaya', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Mamberamo Raya', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Mamberamo Tengah', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Mappi', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Merauke', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Mimika', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Nabire', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Nduga', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Paniai', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Puncak', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Puncak Jaya', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Sarmi', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Supiori', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Tolikara', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Waropen', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Yahukimo', 'PRPA', 'ry-wc-city-select'),
		_x('Kabupaten Yalimo', 'PRPA', 'ry-wc-city-select'),
		_x('Kota Jayapura', 'PRPA', 'ry-wc-city-select'),
	],
	'PRPABA' => [
		_x('Kabupaten Fakfak', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Kaimana', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Manokwari', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Manokwari Selatan', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Maybrat', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Pegunungan Arfak', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Raja Ampat', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Sorong', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Sorong Selatan', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Tambrauw', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Teluk Bintuni', 'PRPABA', 'ry-wc-city-select'),
		_x('Kabupaten Teluk Wondama', 'PRPABA', 'ry-wc-city-select'),
		_x('Kota Sorong', 'PRPABA', 'ry-wc-city-select'),
	],
	'PRRI' => [
		_x('Kabupaten Bengkalis', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Indragiri Hilir', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Indragiri Hulu', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Kampar', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Kepulauan Meranti', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Kuantan Singingi', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Pelalawan', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Rokan Hilir', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Rokan Hulu', 'PRRI', 'ry-wc-city-select'),
		_x('Kabupaten Siak', 'PRRI', 'ry-wc-city-select'),
		_x('Kota Dumai', 'PRRI', 'ry-wc-city-select'),
		_x('Kota Pekanbaru', 'PRRI', 'ry-wc-city-select'),
	],
	'PRSUBA' => [
		_x('Kabupaten Majene', 'PRSUBA', 'ry-wc-city-select'),
		_x('Kabupaten Mamasa', 'PRSUBA', 'ry-wc-city-select'),
		_x('Kabupaten Mamuju', 'PRSUBA', 'ry-wc-city-select'),
		_x('Kabupaten Mamuju Tengah', 'PRSUBA', 'ry-wc-city-select'),
		_x('Kabupaten Mamuju Utara', 'PRSUBA', 'ry-wc-city-select'),
	],
	'PRSUSE' => [
		_x('Kabupaten Bantaeng', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Barru', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Bone', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Bulukumba', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Enrekang', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Gowa', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Jeneponto', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Luwu', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Luwu Timur', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Luwu Utara', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Maros', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Pangkajene Dan Kepulauan', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Pinrang', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Sidenreng Rappang', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Sinjai', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Soppeng', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Takalar', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Tana Toraja', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Toraja Utara', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kabupaten Wajo', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kota Makassar', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kota Palopo', 'PRSUSE', 'ry-wc-city-select'),
		_x('Kota Parepare', 'PRSUSE', 'ry-wc-city-select'),
		_x('Selayar Islands Regency', 'PRSUSE', 'ry-wc-city-select'),
	],
	'PRSUBA2' => [
		_x('Kabupaten Agam', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Dharmasraya', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Kepulauan Mentawai', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Lima Puluh Kota', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Padang Pariaman', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Pasaman', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Pasaman Barat', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Pesisir Selatan', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Sijunjung', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Solok', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Solok Selatan', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kabupaten Tanah Datar', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kota Bukittinggi', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kota Padang', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kota Padang Panjang', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kota Pariaman', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kota Payakumbuh', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kota Sawah Lunto', 'PRSUBA2', 'ry-wc-city-select'),
		_x('Kota Solok', 'PRSUBA2', 'ry-wc-city-select'),
	],
	'SUTE' => [
		_x('Kabupaten Bombana', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Buton', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Buton Selatan', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Buton Tengah', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Buton Utara', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Kolaka', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Kolaka Timur', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Kolaka Utara', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Konawe', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Konawe Kepulauan', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Konawe Selatan', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Konawe Utara', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Muna', 'SUTE', 'ry-wc-city-select'),
		_x('Kabupaten Muna Barat', 'SUTE', 'ry-wc-city-select'),
		_x('Kota Baubau', 'SUTE', 'ry-wc-city-select'),
		_x('Kota Kendari', 'SUTE', 'ry-wc-city-select'),
	],
	'SUUT' => [
		_x('Kabupaten Bolaang Mongondow', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Bolaang Mongondow Selatan', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Bolaang Mongondow Timur', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Bolaang Mongondow Utara', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Kepulauan Sangihe', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Kepulauan Talaud', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Minahasa', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Minahasa Selatan', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Minahasa Tenggara', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Minahasa Utara', 'SUUT', 'ry-wc-city-select'),
		_x('Kabupaten Siau Tagulandang Biaro', 'SUUT', 'ry-wc-city-select'),
		_x('Kota Bitung', 'SUUT', 'ry-wc-city-select'),
		_x('Kota Kotamobagu', 'SUUT', 'ry-wc-city-select'),
		_x('Kota Manado', 'SUUT', 'ry-wc-city-select'),
		_x('Kota Tomohon', 'SUUT', 'ry-wc-city-select'),
	],
	'SUSE' => [
		_x('Kabupaten Banyu Asin', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Empat Lawang', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Muara Enim', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Musi Banyuasin', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Musi Rawas', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Musi Rawas Utara', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Ogan Ilir', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Ogan Komering Ilir', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Ogan Komering Ulu', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Ogan Komering Ulu Selatan', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Ogan Komering Ulu Timur', 'SUSE', 'ry-wc-city-select'),
		_x('Kabupaten Penukal Abab Lematang Ilir', 'SUSE', 'ry-wc-city-select'),
		_x('Kota Lubuklinggau', 'SUSE', 'ry-wc-city-select'),
		_x('Kota Pagar Alam', 'SUSE', 'ry-wc-city-select'),
		_x('Kota Palembang', 'SUSE', 'ry-wc-city-select'),
		_x('Kota Prabumulih', 'SUSE', 'ry-wc-city-select'),
	],
	'WENUTE' => [
		_x('Kabupaten Dompu', 'WENUTE', 'ry-wc-city-select'),
		_x('Kabupaten Lombok Timur', 'WENUTE', 'ry-wc-city-select'),
		_x('Kabupaten Sumbawa', 'WENUTE', 'ry-wc-city-select'),
		_x('Kota Mataram', 'WENUTE', 'ry-wc-city-select'),
	],
	]
];