<?php
/**
 * Republic of India places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'IN' => [
	'BA' => [
		_x('Badami Taluk', 'BA', 'ry-wc-city-select'),
		_x('Bagalkot Taluk', 'BA', 'ry-wc-city-select'),
		_x('Bilgi Taluk', 'BA', 'ry-wc-city-select'),
		_x('Hungund Taluk', 'BA', 'ry-wc-city-select'),
		_x('Jamkhandi Taluk', 'BA', 'ry-wc-city-select'),
		_x('Mudhol Taluk', 'BA', 'ry-wc-city-select'),
	],
	'BA2' => [
		_x('Ballari', 'BA2', 'ry-wc-city-select'),
		_x('Hagaribommanahalli Taluk', 'BA2', 'ry-wc-city-select'),
		_x('Hoovina Hadagalli Taluk', 'BA2', 'ry-wc-city-select'),
		_x('Hospet', 'BA2', 'ry-wc-city-select'),
		_x('Kudligi', 'BA2', 'ry-wc-city-select'),
		_x('Siruguppa Taluk', 'BA2', 'ry-wc-city-select'),
		_x('Sonduru', 'BA2', 'ry-wc-city-select'),
	],
	'BARU' => [
		_x('Devanahalli', 'BARU', 'ry-wc-city-select'),
		_x('Doddaballapura', 'BARU', 'ry-wc-city-select'),
		_x('Hosakote', 'BARU', 'ry-wc-city-select'),
		_x('Nelamangala Taluk', 'BARU', 'ry-wc-city-select'),
	],
	'BAUR' => [
		_x('Anekal Taluk', 'BAUR', 'ry-wc-city-select'),
		_x('Bangalore (North)', 'BAUR', 'ry-wc-city-select'),
		_x('Bangalore (South)', 'BAUR', 'ry-wc-city-select'),
		_x('Bangalore(East)', 'BAUR', 'ry-wc-city-select'),
	],
	'BE' => [
		_x('Athani', 'BE', 'ry-wc-city-select'),
		_x('Bailahongal Taluk', 'BE', 'ry-wc-city-select'),
		_x('Belagavi', 'BE', 'ry-wc-city-select'),
		_x('Chikodi Taluk', 'BE', 'ry-wc-city-select'),
		_x('Gokak Taluk', 'BE', 'ry-wc-city-select'),
		_x('Hukeri Taluk', 'BE', 'ry-wc-city-select'),
		_x('Khanapur Taluk', 'BE', 'ry-wc-city-select'),
		_x('Ramdurg Taluk', 'BE', 'ry-wc-city-select'),
		_x('Raybag Taluk', 'BE', 'ry-wc-city-select'),
		_x('Saundatti Taluk', 'BE', 'ry-wc-city-select'),
	],
	'BI' => [
		_x('Aurad Taluk', 'BI', 'ry-wc-city-select'),
		_x('Basavakalyan Taluk', 'BI', 'ry-wc-city-select'),
		_x('Bhalki Taluk', 'BI', 'ry-wc-city-select'),
		_x('Bidar Taluk', 'BI', 'ry-wc-city-select'),
		_x('Homnabad Taluk', 'BI', 'ry-wc-city-select'),
	],
	'BI2' => [
		_x('Basavana Bagevadi Taluk', 'BI2', 'ry-wc-city-select'),
		_x('Indi Taluk', 'BI2', 'ry-wc-city-select'),
		_x('Muddebihal Taluk', 'BI2', 'ry-wc-city-select'),
		_x('Sindhagi', 'BI2', 'ry-wc-city-select'),
		_x('Vijayapura', 'BI2', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Chamrajnagar Taluk', 'CH', 'ry-wc-city-select'),
		_x('Gundlupet', 'CH', 'ry-wc-city-select'),
		_x('Kollegal Taluk', 'CH', 'ry-wc-city-select'),
		_x('Yelandur', 'CH', 'ry-wc-city-select'),
	],
	'CH2' => [
		_x('Bagepalli Taluk', 'CH2', 'ry-wc-city-select'),
		_x('Chik Ballapur Taluk', 'CH2', 'ry-wc-city-select'),
		_x('Chintamani Taluk', 'CH2', 'ry-wc-city-select'),
		_x('Gauribidanur Taluk', 'CH2', 'ry-wc-city-select'),
		_x('Gudibanda Taluk', 'CH2', 'ry-wc-city-select'),
		_x('Sidlaghatta Taluk', 'CH2', 'ry-wc-city-select'),
	],
	'CH3' => [
		_x('Chikmagalur Taluk', 'CH3', 'ry-wc-city-select'),
		_x('Kadur Taluk', 'CH3', 'ry-wc-city-select'),
		_x('Koppa', 'CH3', 'ry-wc-city-select'),
		_x('Mudigere Taluk', 'CH3', 'ry-wc-city-select'),
		_x('Narasimharajapura Taluk', 'CH3', 'ry-wc-city-select'),
		_x('Sringeri', 'CH3', 'ry-wc-city-select'),
		_x('Tarikere Taluk', 'CH3', 'ry-wc-city-select'),
	],
	'CH4' => [
		_x('Challakere Taluk', 'CH4', 'ry-wc-city-select'),
		_x('Chitradurga', 'CH4', 'ry-wc-city-select'),
		_x('Hiriyur Taluk', 'CH4', 'ry-wc-city-select'),
		_x('Holalkere Taluk', 'CH4', 'ry-wc-city-select'),
		_x('Hosdurga Taluk', 'CH4', 'ry-wc-city-select'),
		_x('Molakalmuru Taluk', 'CH4', 'ry-wc-city-select'),
	],
	'DAKA' => [
		_x('Bantwal Taluk', 'DAKA', 'ry-wc-city-select'),
		_x('Beltangadi Taluk', 'DAKA', 'ry-wc-city-select'),
		_x('Mangalore', 'DAKA', 'ry-wc-city-select'),
		_x('Puttur Taluk', 'DAKA', 'ry-wc-city-select'),
		_x('Sulya Taluk', 'DAKA', 'ry-wc-city-select'),
	],
	'DA' => [
		_x('Channagiri Taluk', 'DA', 'ry-wc-city-select'),
		_x('Davanagere', 'DA', 'ry-wc-city-select'),
		_x('Harihara', 'DA', 'ry-wc-city-select'),
		_x('Harpanahalli Taluk', 'DA', 'ry-wc-city-select'),
		_x('Honnali Taluk', 'DA', 'ry-wc-city-select'),
		_x('Jagalur Taluk', 'DA', 'ry-wc-city-select'),
	],
	'DH' => [
		_x('Dharwad', 'DH', 'ry-wc-city-select'),
		_x('Hubli Taluk', 'DH', 'ry-wc-city-select'),
		_x('Kalghatgi Taluk', 'DH', 'ry-wc-city-select'),
		_x('Kundgol Taluk', 'DH', 'ry-wc-city-select'),
		_x('Navalgund Taluk', 'DH', 'ry-wc-city-select'),
	],
	'GA' => [
		_x('Gadag', 'GA', 'ry-wc-city-select'),
		_x('Mundargi Taluk', 'GA', 'ry-wc-city-select'),
		_x('Nargund Taluk', 'GA', 'ry-wc-city-select'),
		_x('Ron Taluk', 'GA', 'ry-wc-city-select'),
		_x('Shirhatti Taluk', 'GA', 'ry-wc-city-select'),
	],
	'GU' => [
		_x('Afzalpur Taluk', 'GU', 'ry-wc-city-select'),
		_x('Aland Taluk', 'GU', 'ry-wc-city-select'),
		_x('Chincholi Taluk', 'GU', 'ry-wc-city-select'),
		_x('Chitapur Taluk', 'GU', 'ry-wc-city-select'),
		_x('Jevargi Taluk', 'GU', 'ry-wc-city-select'),
		_x('Kalburgi', 'GU', 'ry-wc-city-select'),
		_x('Sedam Taluk', 'GU', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Alur', 'HA', 'ry-wc-city-select'),
		_x('Arkalgud Taluk', 'HA', 'ry-wc-city-select'),
		_x('Arsikere Taluk', 'HA', 'ry-wc-city-select'),
		_x('Belur', 'HA', 'ry-wc-city-select'),
		_x('Channarayapattana Taluk', 'HA', 'ry-wc-city-select'),
		_x('Hassan Taluk', 'HA', 'ry-wc-city-select'),
		_x('Holenarsipur Taluk', 'HA', 'ry-wc-city-select'),
		_x('Sakleshpur Taluk', 'HA', 'ry-wc-city-select'),
	],
	'HA2' => [
		_x('Byadgi Taluk', 'HA2', 'ry-wc-city-select'),
		_x('Hanagal', 'HA2', 'ry-wc-city-select'),
		_x('Haveri', 'HA2', 'ry-wc-city-select'),
		_x('Hirekerur Taluk', 'HA2', 'ry-wc-city-select'),
		_x('Ranibennur Taluk', 'HA2', 'ry-wc-city-select'),
		_x('Savanur Taluk', 'HA2', 'ry-wc-city-select'),
		_x('Shiggaon Taluk', 'HA2', 'ry-wc-city-select'),
	],
	'KO' => [
		_x('Madikeri Taluk', 'KO', 'ry-wc-city-select'),
		_x('Somvarpet Taluk', 'KO', 'ry-wc-city-select'),
		_x('Virajpet Taluk', 'KO', 'ry-wc-city-select'),
	],
	'KO2' => [
		_x('Bangarapet Taluk', 'KO2', 'ry-wc-city-select'),
		_x('Kolar Taluk', 'KO2', 'ry-wc-city-select'),
		_x('Malur Taluk', 'KO2', 'ry-wc-city-select'),
		_x('Mulbagal Taluk', 'KO2', 'ry-wc-city-select'),
		_x('Srinivaspur Taluk', 'KO2', 'ry-wc-city-select'),
	],
	'KO3' => [
		_x('Gangawati Taluk', 'KO3', 'ry-wc-city-select'),
		_x('Koppal Taluk', 'KO3', 'ry-wc-city-select'),
		_x('Kushtagi Taluk', 'KO3', 'ry-wc-city-select'),
		_x('Yelbarga Taluk', 'KO3', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Krishnarajpet Taluk', 'MA', 'ry-wc-city-select'),
		_x('Maddur', 'MA', 'ry-wc-city-select'),
		_x('Malavalli Taluk', 'MA', 'ry-wc-city-select'),
		_x('Mandya Taluk', 'MA', 'ry-wc-city-select'),
		_x('Nagamangala Taluk', 'MA', 'ry-wc-city-select'),
		_x('Pandavpura', 'MA', 'ry-wc-city-select'),
		_x('Srirangapatna', 'MA', 'ry-wc-city-select'),
	],
	'MY' => [
		_x('Heggadadevanakote Taluk', 'MY', 'ry-wc-city-select'),
		_x('Hunsur Taluk', 'MY', 'ry-wc-city-select'),
		_x('Krishnarajanagara Taluk', 'MY', 'ry-wc-city-select'),
		_x('Mysuru', 'MY', 'ry-wc-city-select'),
		_x('Nanjangud Taluk', 'MY', 'ry-wc-city-select'),
		_x('Piriyapatna Taluk', 'MY', 'ry-wc-city-select'),
		_x('Tirumakudalu Narasipura Taluk', 'MY', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Devadurga', 'RA', 'ry-wc-city-select'),
		_x('Lingsugur Taluk', 'RA', 'ry-wc-city-select'),
		_x('Manvi Taluk', 'RA', 'ry-wc-city-select'),
		_x('Raichur Taluk', 'RA', 'ry-wc-city-select'),
		_x('Sindhnur Taluk', 'RA', 'ry-wc-city-select'),
	],
	'RA2' => [
		_x('Channapatna', 'RA2', 'ry-wc-city-select'),
		_x('Kanakapura Taluk', 'RA2', 'ry-wc-city-select'),
		_x('Magadi Taluk', 'RA2', 'ry-wc-city-select'),
		_x('Ramanagaram Taluk', 'RA2', 'ry-wc-city-select'),
	],
	'SH' => [
		_x('Bhadravathi', 'SH', 'ry-wc-city-select'),
		_x('Hosanagara', 'SH', 'ry-wc-city-select'),
		_x('Sagar Taluk', 'SH', 'ry-wc-city-select'),
		_x('Shikaripura Taluk', 'SH', 'ry-wc-city-select'),
		_x('Shimoga', 'SH', 'ry-wc-city-select'),
		_x('Sorab Taluk', 'SH', 'ry-wc-city-select'),
		_x('Tirthalli Taluk', 'SH', 'ry-wc-city-select'),
	],
	'TH' => [
		_x('Thiruvallom', 'TH', 'ry-wc-city-select'),
	],
	'TU' => [
		_x('Chiknayakanhalli Taluk', 'TU', 'ry-wc-city-select'),
		_x('Gubbi Taluk', 'TU', 'ry-wc-city-select'),
		_x('Koratagere Taluk', 'TU', 'ry-wc-city-select'),
		_x('Kunigal Taluk', 'TU', 'ry-wc-city-select'),
		_x('Madhugiri Taluk', 'TU', 'ry-wc-city-select'),
		_x('Pavagada Taluk', 'TU', 'ry-wc-city-select'),
		_x('Sira Taluk', 'TU', 'ry-wc-city-select'),
		_x('Tiptur Taluk', 'TU', 'ry-wc-city-select'),
		_x('Tumakuru', 'TU', 'ry-wc-city-select'),
		_x('Turuvekere Taluk', 'TU', 'ry-wc-city-select'),
	],
	'UD' => [
		_x('Karkal Taluk', 'UD', 'ry-wc-city-select'),
		_x('Kundapura Taluk', 'UD', 'ry-wc-city-select'),
		_x('Udupi Taluk', 'UD', 'ry-wc-city-select'),
	],
	'UTKA' => [
		_x('Ankola Taluk', 'UTKA', 'ry-wc-city-select'),
		_x('Bhatkal Taluk', 'UTKA', 'ry-wc-city-select'),
		_x('Haliyal Taluk', 'UTKA', 'ry-wc-city-select'),
		_x('Honavar Taluk', 'UTKA', 'ry-wc-city-select'),
		_x('Karwara', 'UTKA', 'ry-wc-city-select'),
		_x('Kumta Taluk', 'UTKA', 'ry-wc-city-select'),
		_x('Mundgod Taluk', 'UTKA', 'ry-wc-city-select'),
		_x('Siddhapura', 'UTKA', 'ry-wc-city-select'),
		_x('Sirsi', 'UTKA', 'ry-wc-city-select'),
		_x('Supa Taluk', 'UTKA', 'ry-wc-city-select'),
		_x('Yellapura', 'UTKA', 'ry-wc-city-select'),
	],
	'WETR' => [
		_x('Savar Upazila', 'WETR', 'ry-wc-city-select'),
	],
	'YA' => [
		_x('Shahapur', 'YA', 'ry-wc-city-select'),
		_x('Surapur', 'YA', 'ry-wc-city-select'),
		_x('Yadgir Taluk', 'YA', 'ry-wc-city-select'),
	],
	'AS' => [
		_x('Baksa', 'AS', 'ry-wc-city-select'),
		_x('Barpeta', 'AS', 'ry-wc-city-select'),
		_x('Biswanath', 'AS', 'ry-wc-city-select'),
		_x('Bongaigaon', 'AS', 'ry-wc-city-select'),
		_x('Cachar', 'AS', 'ry-wc-city-select'),
		_x('Charaideo', 'AS', 'ry-wc-city-select'),
		_x('Chirang', 'AS', 'ry-wc-city-select'),
		_x('Darrang', 'AS', 'ry-wc-city-select'),
		_x('Dhemaji', 'AS', 'ry-wc-city-select'),
		_x('Dhubri', 'AS', 'ry-wc-city-select'),
		_x('Dibrugarh', 'AS', 'ry-wc-city-select'),
		_x('Dima Hasao District', 'AS', 'ry-wc-city-select'),
		_x('Goalpara', 'AS', 'ry-wc-city-select'),
		_x('Golaghat', 'AS', 'ry-wc-city-select'),
		_x('Hailakandi', 'AS', 'ry-wc-city-select'),
		_x('Hojai', 'AS', 'ry-wc-city-select'),
		_x('Jorhat', 'AS', 'ry-wc-city-select'),
		_x('Kamrup', 'AS', 'ry-wc-city-select'),
		_x('Kamrup Metropolitan', 'AS', 'ry-wc-city-select'),
		_x('Karbi Anglong', 'AS', 'ry-wc-city-select'),
		_x('Karimganj', 'AS', 'ry-wc-city-select'),
		_x('Kokrajhar', 'AS', 'ry-wc-city-select'),
		_x('Lakhimpur', 'AS', 'ry-wc-city-select'),
		_x('Majuli', 'AS', 'ry-wc-city-select'),
		_x('Morigaon', 'AS', 'ry-wc-city-select'),
		_x('Nagaon', 'AS', 'ry-wc-city-select'),
		_x('Nalbari', 'AS', 'ry-wc-city-select'),
		_x('Sibsagar', 'AS', 'ry-wc-city-select'),
		_x('Sonitpur', 'AS', 'ry-wc-city-select'),
		_x('South Salmara Mancachar', 'AS', 'ry-wc-city-select'),
		_x('Tinsukia', 'AS', 'ry-wc-city-select'),
		_x('Udalguri', 'AS', 'ry-wc-city-select'),
		_x('West Karbi Anglong', 'AS', 'ry-wc-city-select'),
	],
	'GO' => [
		_x('North Goa', 'GO', 'ry-wc-city-select'),
		_x('South Goa', 'GO', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Kargil', 'LA', 'ry-wc-city-select'),
		_x('Leh', 'LA', 'ry-wc-city-select'),
	],
	'MAPR' => [
		_x('Agar Malwa', 'MAPR', 'ry-wc-city-select'),
		_x('Alirajpur', 'MAPR', 'ry-wc-city-select'),
		_x('Anuppur', 'MAPR', 'ry-wc-city-select'),
		_x('Ashoknagar', 'MAPR', 'ry-wc-city-select'),
		_x('Balaghat', 'MAPR', 'ry-wc-city-select'),
		_x('Barwani', 'MAPR', 'ry-wc-city-select'),
		_x('Betul', 'MAPR', 'ry-wc-city-select'),
		_x('Bhind', 'MAPR', 'ry-wc-city-select'),
		_x('Bhopal', 'MAPR', 'ry-wc-city-select'),
		_x('Burhanpur', 'MAPR', 'ry-wc-city-select'),
		_x('Chhatarpur', 'MAPR', 'ry-wc-city-select'),
		_x('Chhindwara', 'MAPR', 'ry-wc-city-select'),
		_x('Damoh', 'MAPR', 'ry-wc-city-select'),
		_x('Datia', 'MAPR', 'ry-wc-city-select'),
		_x('Dewas', 'MAPR', 'ry-wc-city-select'),
		_x('Dhar', 'MAPR', 'ry-wc-city-select'),
		_x('Dindori', 'MAPR', 'ry-wc-city-select'),
		_x('Guna', 'MAPR', 'ry-wc-city-select'),
		_x('Gwalior', 'MAPR', 'ry-wc-city-select'),
		_x('Harda', 'MAPR', 'ry-wc-city-select'),
		_x('Hoshangabad', 'MAPR', 'ry-wc-city-select'),
		_x('Indore', 'MAPR', 'ry-wc-city-select'),
		_x('Jabalpur', 'MAPR', 'ry-wc-city-select'),
		_x('Jhabua', 'MAPR', 'ry-wc-city-select'),
		_x('Katni', 'MAPR', 'ry-wc-city-select'),
		_x('Khandwa district', 'MAPR', 'ry-wc-city-select'),
		_x('Khargone', 'MAPR', 'ry-wc-city-select'),
		_x('Mandla', 'MAPR', 'ry-wc-city-select'),
		_x('Mandsaur', 'MAPR', 'ry-wc-city-select'),
		_x('Morena', 'MAPR', 'ry-wc-city-select'),
		_x('Narsimhapur', 'MAPR', 'ry-wc-city-select'),
		_x('Neemuch', 'MAPR', 'ry-wc-city-select'),
		_x('Panna', 'MAPR', 'ry-wc-city-select'),
		_x('Raisen', 'MAPR', 'ry-wc-city-select'),
		_x('Rajgarh', 'MAPR', 'ry-wc-city-select'),
		_x('Ratlam', 'MAPR', 'ry-wc-city-select'),
		_x('Rewa', 'MAPR', 'ry-wc-city-select'),
		_x('Sagar', 'MAPR', 'ry-wc-city-select'),
		_x('Satna', 'MAPR', 'ry-wc-city-select'),
		_x('Sehore', 'MAPR', 'ry-wc-city-select'),
		_x('Seoni', 'MAPR', 'ry-wc-city-select'),
		_x('Shahdol', 'MAPR', 'ry-wc-city-select'),
		_x('Shajapur', 'MAPR', 'ry-wc-city-select'),
		_x('Sheopur', 'MAPR', 'ry-wc-city-select'),
		_x('Shivpuri', 'MAPR', 'ry-wc-city-select'),
		_x('Sidhi', 'MAPR', 'ry-wc-city-select'),
		_x('Singrauli', 'MAPR', 'ry-wc-city-select'),
		_x('Tikamgarh', 'MAPR', 'ry-wc-city-select'),
		_x('Ujjain', 'MAPR', 'ry-wc-city-select'),
		_x('Umaria District', 'MAPR', 'ry-wc-city-select'),
		_x('Vidisha', 'MAPR', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('Bishnupur', 'MA2', 'ry-wc-city-select'),
		_x('Chandel', 'MA2', 'ry-wc-city-select'),
		_x('Churachandpur', 'MA2', 'ry-wc-city-select'),
		_x('Imphal East', 'MA2', 'ry-wc-city-select'),
		_x('Imphal West', 'MA2', 'ry-wc-city-select'),
		_x('Jiribam', 'MA2', 'ry-wc-city-select'),
		_x('Kakching', 'MA2', 'ry-wc-city-select'),
		_x('Kamjong', 'MA2', 'ry-wc-city-select'),
		_x('Kangpokpi', 'MA2', 'ry-wc-city-select'),
		_x('Noney', 'MA2', 'ry-wc-city-select'),
		_x('Pherzawl', 'MA2', 'ry-wc-city-select'),
		_x('Senapati', 'MA2', 'ry-wc-city-select'),
		_x('Tamenglong', 'MA2', 'ry-wc-city-select'),
		_x('Tengnoupal', 'MA2', 'ry-wc-city-select'),
		_x('Thoubal', 'MA2', 'ry-wc-city-select'),
		_x('Ukhrul', 'MA2', 'ry-wc-city-select'),
	],
	'ME' => [
		_x('East Garo Hills', 'ME', 'ry-wc-city-select'),
		_x('East Jaintia Hills', 'ME', 'ry-wc-city-select'),
		_x('East Khasi Hills', 'ME', 'ry-wc-city-select'),
		_x('North Garo Hills', 'ME', 'ry-wc-city-select'),
		_x('Ri-Bhoi', 'ME', 'ry-wc-city-select'),
		_x('South Garo Hills', 'ME', 'ry-wc-city-select'),
		_x('South West Garo Hills', 'ME', 'ry-wc-city-select'),
		_x('South West Khasi Hills', 'ME', 'ry-wc-city-select'),
		_x('West Garo Hills', 'ME', 'ry-wc-city-select'),
		_x('West Jaintia Hills', 'ME', 'ry-wc-city-select'),
		_x('West Khasi Hills', 'ME', 'ry-wc-city-select'),
	],
	'MI' => [
		_x('Aizawl', 'MI', 'ry-wc-city-select'),
		_x('Champhai', 'MI', 'ry-wc-city-select'),
		_x('Kolasib district', 'MI', 'ry-wc-city-select'),
		_x('Lawngtlai', 'MI', 'ry-wc-city-select'),
		_x('Lunglei', 'MI', 'ry-wc-city-select'),
		_x('Mamit', 'MI', 'ry-wc-city-select'),
		_x('Saiha', 'MI', 'ry-wc-city-select'),
		_x('Serchhip', 'MI', 'ry-wc-city-select'),
	],
	'NACATEDE' => [
		_x('Central Delhi', 'NACATEDE', 'ry-wc-city-select'),
		_x('East Delhi', 'NACATEDE', 'ry-wc-city-select'),
		_x('New Delhi', 'NACATEDE', 'ry-wc-city-select'),
		_x('North Delhi', 'NACATEDE', 'ry-wc-city-select'),
		_x('North East Delhi', 'NACATEDE', 'ry-wc-city-select'),
		_x('North West Delhi', 'NACATEDE', 'ry-wc-city-select'),
		_x('Shahdara', 'NACATEDE', 'ry-wc-city-select'),
		_x('South Delhi', 'NACATEDE', 'ry-wc-city-select'),
		_x('South East', 'NACATEDE', 'ry-wc-city-select'),
		_x('South West Delhi', 'NACATEDE', 'ry-wc-city-select'),
		_x('West Delhi', 'NACATEDE', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('East District', 'SI', 'ry-wc-city-select'),
		_x('North District', 'SI', 'ry-wc-city-select'),
		_x('South District', 'SI', 'ry-wc-city-select'),
		_x('West District', 'SI', 'ry-wc-city-select'),
	],
	'STANPR' => [
		_x('Anantapur', 'STANPR', 'ry-wc-city-select'),
		_x('Chittoor', 'STANPR', 'ry-wc-city-select'),
		_x('Cuddapah', 'STANPR', 'ry-wc-city-select'),
		_x('East Godavari', 'STANPR', 'ry-wc-city-select'),
		_x('Guntur', 'STANPR', 'ry-wc-city-select'),
		_x('Krishna', 'STANPR', 'ry-wc-city-select'),
		_x('Kurnool', 'STANPR', 'ry-wc-city-select'),
		_x('Nellore', 'STANPR', 'ry-wc-city-select'),
		_x('Prakasam', 'STANPR', 'ry-wc-city-select'),
		_x('Srikakulam', 'STANPR', 'ry-wc-city-select'),
		_x('Vishakhapatnam', 'STANPR', 'ry-wc-city-select'),
		_x('Vizianagaram District', 'STANPR', 'ry-wc-city-select'),
		_x('West Godavari', 'STANPR', 'ry-wc-city-select'),
	],
	'STARPR' => [
		_x('Anjaw', 'STARPR', 'ry-wc-city-select'),
		_x('Changlang', 'STARPR', 'ry-wc-city-select'),
		_x('Dibang Valley', 'STARPR', 'ry-wc-city-select'),
		_x('East Kameng', 'STARPR', 'ry-wc-city-select'),
		_x('East Siang', 'STARPR', 'ry-wc-city-select'),
		_x('Kra Daadi', 'STARPR', 'ry-wc-city-select'),
		_x('Kurung Kumey', 'STARPR', 'ry-wc-city-select'),
		_x('Lohit District', 'STARPR', 'ry-wc-city-select'),
		_x('Longding', 'STARPR', 'ry-wc-city-select'),
		_x('Lower Dibang Valley', 'STARPR', 'ry-wc-city-select'),
		_x('Lower Siang', 'STARPR', 'ry-wc-city-select'),
		_x('Lower Subansiri', 'STARPR', 'ry-wc-city-select'),
		_x('Namsai', 'STARPR', 'ry-wc-city-select'),
		_x('Papum Pare', 'STARPR', 'ry-wc-city-select'),
		_x('Siang', 'STARPR', 'ry-wc-city-select'),
		_x('Tawang', 'STARPR', 'ry-wc-city-select'),
		_x('Tirap', 'STARPR', 'ry-wc-city-select'),
		_x('Upper Siang', 'STARPR', 'ry-wc-city-select'),
		_x('Upper Subansiri', 'STARPR', 'ry-wc-city-select'),
		_x('West Kameng', 'STARPR', 'ry-wc-city-select'),
		_x('West Siang', 'STARPR', 'ry-wc-city-select'),
	],
	'STBI' => [
		_x('Araria', 'STBI', 'ry-wc-city-select'),
		_x('Arwal', 'STBI', 'ry-wc-city-select'),
		_x('Aurangabad', 'STBI', 'ry-wc-city-select'),
		_x('Banka', 'STBI', 'ry-wc-city-select'),
		_x('Begusarai', 'STBI', 'ry-wc-city-select'),
		_x('Bhagalpur', 'STBI', 'ry-wc-city-select'),
		_x('Bhojpur', 'STBI', 'ry-wc-city-select'),
		_x('Buxar', 'STBI', 'ry-wc-city-select'),
		_x('Darbhanga', 'STBI', 'ry-wc-city-select'),
		_x('Gaya', 'STBI', 'ry-wc-city-select'),
		_x('Gopalganj', 'STBI', 'ry-wc-city-select'),
		_x('Jamui', 'STBI', 'ry-wc-city-select'),
		_x('Jehanabad', 'STBI', 'ry-wc-city-select'),
		_x('Kaimur District', 'STBI', 'ry-wc-city-select'),
		_x('Katihar', 'STBI', 'ry-wc-city-select'),
		_x('Khagaria', 'STBI', 'ry-wc-city-select'),
		_x('Kishanganj', 'STBI', 'ry-wc-city-select'),
		_x('Lakhisarai', 'STBI', 'ry-wc-city-select'),
		_x('Madhepura', 'STBI', 'ry-wc-city-select'),
		_x('Madhubani', 'STBI', 'ry-wc-city-select'),
		_x('Munger', 'STBI', 'ry-wc-city-select'),
		_x('Muzaffarpur', 'STBI', 'ry-wc-city-select'),
		_x('Nalanda', 'STBI', 'ry-wc-city-select'),
		_x('Nawada', 'STBI', 'ry-wc-city-select'),
		_x('Pashchim Champaran', 'STBI', 'ry-wc-city-select'),
		_x('Patna', 'STBI', 'ry-wc-city-select'),
		_x('Purba Champaran', 'STBI', 'ry-wc-city-select'),
		_x('Purnia', 'STBI', 'ry-wc-city-select'),
		_x('Rohtas', 'STBI', 'ry-wc-city-select'),
		_x('Saharsa', 'STBI', 'ry-wc-city-select'),
		_x('Samastipur', 'STBI', 'ry-wc-city-select'),
		_x('Saran', 'STBI', 'ry-wc-city-select'),
		_x('Sheikhpura', 'STBI', 'ry-wc-city-select'),
		_x('Sheohar', 'STBI', 'ry-wc-city-select'),
		_x('Sitamarhi', 'STBI', 'ry-wc-city-select'),
		_x('Siwan', 'STBI', 'ry-wc-city-select'),
		_x('Supaul', 'STBI', 'ry-wc-city-select'),
		_x('Vaishali', 'STBI', 'ry-wc-city-select'),
	],
	'STCH' => [
		_x('Balod', 'STCH', 'ry-wc-city-select'),
		_x('Baloda Bazar', 'STCH', 'ry-wc-city-select'),
		_x('Balrampur', 'STCH', 'ry-wc-city-select'),
		_x('Bastar', 'STCH', 'ry-wc-city-select'),
		_x('Bemetara', 'STCH', 'ry-wc-city-select'),
		_x('Bijapur', 'STCH', 'ry-wc-city-select'),
		_x('Bilaspur', 'STCH', 'ry-wc-city-select'),
		_x('Dakshin Bastar Dantewada', 'STCH', 'ry-wc-city-select'),
		_x('Dhamtari', 'STCH', 'ry-wc-city-select'),
		_x('Durg', 'STCH', 'ry-wc-city-select'),
		_x('Gariyaband', 'STCH', 'ry-wc-city-select'),
		_x('Janjgir-Champa', 'STCH', 'ry-wc-city-select'),
		_x('Jashpur', 'STCH', 'ry-wc-city-select'),
		_x('Kabeerdham', 'STCH', 'ry-wc-city-select'),
		_x('Kondagaon', 'STCH', 'ry-wc-city-select'),
		_x('Korba', 'STCH', 'ry-wc-city-select'),
		_x('Koriya', 'STCH', 'ry-wc-city-select'),
		_x('Mahasamund', 'STCH', 'ry-wc-city-select'),
		_x('Mungeli', 'STCH', 'ry-wc-city-select'),
		_x('Narayanpur', 'STCH', 'ry-wc-city-select'),
		_x('Raigarh', 'STCH', 'ry-wc-city-select'),
		_x('Raipur', 'STCH', 'ry-wc-city-select'),
		_x('Raj Nandgaon', 'STCH', 'ry-wc-city-select'),
		_x('Sukma', 'STCH', 'ry-wc-city-select'),
		_x('Surajpur', 'STCH', 'ry-wc-city-select'),
		_x('Surguja', 'STCH', 'ry-wc-city-select'),
		_x('Uttar Bastar Kanker', 'STCH', 'ry-wc-city-select'),
	],
	'STGU' => [
		_x('Ahmadabad', 'STGU', 'ry-wc-city-select'),
		_x('Amreli', 'STGU', 'ry-wc-city-select'),
		_x('Anand', 'STGU', 'ry-wc-city-select'),
		_x('Arvalli', 'STGU', 'ry-wc-city-select'),
		_x('Banas Kantha', 'STGU', 'ry-wc-city-select'),
		_x('Bharuch', 'STGU', 'ry-wc-city-select'),
		_x('Bhavnagar', 'STGU', 'ry-wc-city-select'),
		_x('Botad', 'STGU', 'ry-wc-city-select'),
		_x('Chhotaudepur', 'STGU', 'ry-wc-city-select'),
		_x('Devbhumi Dwarka', 'STGU', 'ry-wc-city-select'),
		_x('Dohad', 'STGU', 'ry-wc-city-select'),
		_x('Gandhinagar', 'STGU', 'ry-wc-city-select'),
		_x('Gir Somnath', 'STGU', 'ry-wc-city-select'),
		_x('Jamnagar', 'STGU', 'ry-wc-city-select'),
		_x('Junagadh', 'STGU', 'ry-wc-city-select'),
		_x('Kachchh', 'STGU', 'ry-wc-city-select'),
		_x('Kheda', 'STGU', 'ry-wc-city-select'),
		_x('Mahesana', 'STGU', 'ry-wc-city-select'),
		_x('Mahisagar', 'STGU', 'ry-wc-city-select'),
		_x('Morbi', 'STGU', 'ry-wc-city-select'),
		_x('Narmada', 'STGU', 'ry-wc-city-select'),
		_x('Navsari', 'STGU', 'ry-wc-city-select'),
		_x('Panch Mahals', 'STGU', 'ry-wc-city-select'),
		_x('Patan', 'STGU', 'ry-wc-city-select'),
		_x('Porbandar', 'STGU', 'ry-wc-city-select'),
		_x('Rajkot', 'STGU', 'ry-wc-city-select'),
		_x('Sabar Kantha', 'STGU', 'ry-wc-city-select'),
		_x('Surat', 'STGU', 'ry-wc-city-select'),
		_x('Surendranagar', 'STGU', 'ry-wc-city-select'),
		_x('Tapi', 'STGU', 'ry-wc-city-select'),
		_x('The Dangs', 'STGU', 'ry-wc-city-select'),
		_x('Vadodara', 'STGU', 'ry-wc-city-select'),
		_x('Valsad', 'STGU', 'ry-wc-city-select'),
	],
	'STHA' => [
		_x('Ambala', 'STHA', 'ry-wc-city-select'),
		_x('Bhiwani', 'STHA', 'ry-wc-city-select'),
		_x('Charki Dadri', 'STHA', 'ry-wc-city-select'),
		_x('Faridabad District', 'STHA', 'ry-wc-city-select'),
		_x('Fatehabad District', 'STHA', 'ry-wc-city-select'),
		_x('Gurgaon', 'STHA', 'ry-wc-city-select'),
		_x('Hisar', 'STHA', 'ry-wc-city-select'),
		_x('Jhajjar', 'STHA', 'ry-wc-city-select'),
		_x('Jind', 'STHA', 'ry-wc-city-select'),
		_x('Kaithal', 'STHA', 'ry-wc-city-select'),
		_x('Karnal', 'STHA', 'ry-wc-city-select'),
		_x('Kurukshetra', 'STHA', 'ry-wc-city-select'),
		_x('Mahendragarh', 'STHA', 'ry-wc-city-select'),
		_x('Mewat', 'STHA', 'ry-wc-city-select'),
		_x('Palwal', 'STHA', 'ry-wc-city-select'),
		_x('Panchkula', 'STHA', 'ry-wc-city-select'),
		_x('Panipat', 'STHA', 'ry-wc-city-select'),
		_x('Rewari District', 'STHA', 'ry-wc-city-select'),
		_x('Rohtak', 'STHA', 'ry-wc-city-select'),
		_x('Sirsa', 'STHA', 'ry-wc-city-select'),
		_x('Sonipat', 'STHA', 'ry-wc-city-select'),
		_x('Yamunanagar', 'STHA', 'ry-wc-city-select'),
	],
	'STHIPR' => [
		_x('Bilaspur', 'STHIPR', 'ry-wc-city-select'),
		_x('Chamba', 'STHIPR', 'ry-wc-city-select'),
		_x('Hamirpur', 'STHIPR', 'ry-wc-city-select'),
		_x('Kangra', 'STHIPR', 'ry-wc-city-select'),
		_x('Kinnaur', 'STHIPR', 'ry-wc-city-select'),
		_x('Kulu', 'STHIPR', 'ry-wc-city-select'),
		_x('Lahul and Spiti', 'STHIPR', 'ry-wc-city-select'),
		_x('Mandi', 'STHIPR', 'ry-wc-city-select'),
		_x('Shimla', 'STHIPR', 'ry-wc-city-select'),
		_x('Sirmaur', 'STHIPR', 'ry-wc-city-select'),
		_x('Solan', 'STHIPR', 'ry-wc-city-select'),
		_x('Una', 'STHIPR', 'ry-wc-city-select'),
	],
	'STJAANKA' => [
		_x('Anantnag', 'STJAANKA', 'ry-wc-city-select'),
		_x('Badgam', 'STJAANKA', 'ry-wc-city-select'),
		_x('Bandipore', 'STJAANKA', 'ry-wc-city-select'),
		_x('Baramula', 'STJAANKA', 'ry-wc-city-select'),
		_x('Doda', 'STJAANKA', 'ry-wc-city-select'),
		_x('Ganderbal', 'STJAANKA', 'ry-wc-city-select'),
		_x('Jammu', 'STJAANKA', 'ry-wc-city-select'),
		_x('Kathua', 'STJAANKA', 'ry-wc-city-select'),
		_x('Kishtwar', 'STJAANKA', 'ry-wc-city-select'),
		_x('Kulgam', 'STJAANKA', 'ry-wc-city-select'),
		_x('Kupwara', 'STJAANKA', 'ry-wc-city-select'),
		_x('Pulwama', 'STJAANKA', 'ry-wc-city-select'),
		_x('Punch', 'STJAANKA', 'ry-wc-city-select'),
		_x('Rajauri', 'STJAANKA', 'ry-wc-city-select'),
		_x('Ramban', 'STJAANKA', 'ry-wc-city-select'),
		_x('Reasi', 'STJAANKA', 'ry-wc-city-select'),
		_x('Samba', 'STJAANKA', 'ry-wc-city-select'),
		_x('Shupiyan', 'STJAANKA', 'ry-wc-city-select'),
		_x('Srinagar', 'STJAANKA', 'ry-wc-city-select'),
		_x('Udhampur', 'STJAANKA', 'ry-wc-city-select'),
	],
	'STJH' => [
		_x('Bokaro', 'STJH', 'ry-wc-city-select'),
		_x('Chatra', 'STJH', 'ry-wc-city-select'),
		_x('Deogarh', 'STJH', 'ry-wc-city-select'),
		_x('Dhanbad', 'STJH', 'ry-wc-city-select'),
		_x('Dumka', 'STJH', 'ry-wc-city-select'),
		_x('Garhwa', 'STJH', 'ry-wc-city-select'),
		_x('Giridih', 'STJH', 'ry-wc-city-select'),
		_x('Godda', 'STJH', 'ry-wc-city-select'),
		_x('Gumla', 'STJH', 'ry-wc-city-select'),
		_x('Hazaribag', 'STJH', 'ry-wc-city-select'),
		_x('Jamtara', 'STJH', 'ry-wc-city-select'),
		_x('Khunti', 'STJH', 'ry-wc-city-select'),
		_x('Kodarma', 'STJH', 'ry-wc-city-select'),
		_x('Latehar', 'STJH', 'ry-wc-city-select'),
		_x('Lohardaga', 'STJH', 'ry-wc-city-select'),
		_x('Pakur', 'STJH', 'ry-wc-city-select'),
		_x('Palamu', 'STJH', 'ry-wc-city-select'),
		_x('Pashchim Singhbhum', 'STJH', 'ry-wc-city-select'),
		_x('Purba Singhbhum', 'STJH', 'ry-wc-city-select'),
		_x('Ramgarh', 'STJH', 'ry-wc-city-select'),
		_x('Ranchi', 'STJH', 'ry-wc-city-select'),
		_x('Sahibganj', 'STJH', 'ry-wc-city-select'),
		_x('Saraikela', 'STJH', 'ry-wc-city-select'),
		_x('Simdega', 'STJH', 'ry-wc-city-select'),
	],
	'STKE' => [
		_x('Alappuzha', 'STKE', 'ry-wc-city-select'),
		_x('Ernakulam', 'STKE', 'ry-wc-city-select'),
		_x('Idukki', 'STKE', 'ry-wc-city-select'),
		_x('Kannur', 'STKE', 'ry-wc-city-select'),
		_x('Kasaragod District', 'STKE', 'ry-wc-city-select'),
		_x('Kollam', 'STKE', 'ry-wc-city-select'),
		_x('Kottayam', 'STKE', 'ry-wc-city-select'),
		_x('Kozhikode', 'STKE', 'ry-wc-city-select'),
		_x('Malappuram', 'STKE', 'ry-wc-city-select'),
		_x('Palakkad district', 'STKE', 'ry-wc-city-select'),
		_x('Pattanamtitta', 'STKE', 'ry-wc-city-select'),
		_x('Thrissur District', 'STKE', 'ry-wc-city-select'),
		_x('Wayanad', 'STKE', 'ry-wc-city-select'),
	],
	'STMA' => [
		_x('Ahmadnagar', 'STMA', 'ry-wc-city-select'),
		_x('Akola', 'STMA', 'ry-wc-city-select'),
		_x('Amravati Division', 'STMA', 'ry-wc-city-select'),
		_x('Aurangabad', 'STMA', 'ry-wc-city-select'),
		_x('Bhandara', 'STMA', 'ry-wc-city-select'),
		_x('Bid', 'STMA', 'ry-wc-city-select'),
		_x('Buldana', 'STMA', 'ry-wc-city-select'),
		_x('Chandrapur', 'STMA', 'ry-wc-city-select'),
		_x('Dhule', 'STMA', 'ry-wc-city-select'),
		_x('Gadchiroli', 'STMA', 'ry-wc-city-select'),
		_x('Gondiya', 'STMA', 'ry-wc-city-select'),
		_x('Hingoli', 'STMA', 'ry-wc-city-select'),
		_x('Jalgaon', 'STMA', 'ry-wc-city-select'),
		_x('Jalna', 'STMA', 'ry-wc-city-select'),
		_x('Kolhapur', 'STMA', 'ry-wc-city-select'),
		_x('Latur', 'STMA', 'ry-wc-city-select'),
		_x('Mumbai', 'STMA', 'ry-wc-city-select'),
		_x('Mumbai Suburban', 'STMA', 'ry-wc-city-select'),
		_x('Nagpur Division', 'STMA', 'ry-wc-city-select'),
		_x('Nanded', 'STMA', 'ry-wc-city-select'),
		_x('Nandurbar', 'STMA', 'ry-wc-city-select'),
		_x('Nashik Division', 'STMA', 'ry-wc-city-select'),
		_x('Osmanabad', 'STMA', 'ry-wc-city-select'),
		_x('Palghar', 'STMA', 'ry-wc-city-select'),
		_x('Parbhani', 'STMA', 'ry-wc-city-select'),
		_x('Pune Division', 'STMA', 'ry-wc-city-select'),
		_x('Raigarh', 'STMA', 'ry-wc-city-select'),
		_x('Ratnagiri', 'STMA', 'ry-wc-city-select'),
		_x('Sangli', 'STMA', 'ry-wc-city-select'),
		_x('Satara Division', 'STMA', 'ry-wc-city-select'),
		_x('Sindhudurg', 'STMA', 'ry-wc-city-select'),
		_x('Solapur', 'STMA', 'ry-wc-city-select'),
		_x('Thane', 'STMA', 'ry-wc-city-select'),
		_x('Wardha', 'STMA', 'ry-wc-city-select'),
		_x('Washim', 'STMA', 'ry-wc-city-select'),
		_x('Yavatmal', 'STMA', 'ry-wc-city-select'),
	],
	'STNA' => [
		_x('Dimapur', 'STNA', 'ry-wc-city-select'),
		_x('Kiphire', 'STNA', 'ry-wc-city-select'),
		_x('Kohima', 'STNA', 'ry-wc-city-select'),
		_x('Longleng', 'STNA', 'ry-wc-city-select'),
		_x('Mokokchung', 'STNA', 'ry-wc-city-select'),
		_x('Mon', 'STNA', 'ry-wc-city-select'),
		_x('Peren', 'STNA', 'ry-wc-city-select'),
		_x('Phek', 'STNA', 'ry-wc-city-select'),
		_x('Tuensang District', 'STNA', 'ry-wc-city-select'),
		_x('Wokha', 'STNA', 'ry-wc-city-select'),
		_x('Zunheboto', 'STNA', 'ry-wc-city-select'),
	],
	'STOD' => [
		_x('Angul District', 'STOD', 'ry-wc-city-select'),
		_x('Balangir', 'STOD', 'ry-wc-city-select'),
		_x('Baleshwar', 'STOD', 'ry-wc-city-select'),
		_x('Baragarh', 'STOD', 'ry-wc-city-select'),
		_x('Baudh', 'STOD', 'ry-wc-city-select'),
		_x('Bhadrak', 'STOD', 'ry-wc-city-select'),
		_x('Cuttack', 'STOD', 'ry-wc-city-select'),
		_x('Debagarh', 'STOD', 'ry-wc-city-select'),
		_x('Dhenkanal', 'STOD', 'ry-wc-city-select'),
		_x('Gajapati', 'STOD', 'ry-wc-city-select'),
		_x('Ganjam', 'STOD', 'ry-wc-city-select'),
		_x('Jagatsinghpur', 'STOD', 'ry-wc-city-select'),
		_x('Jajpur', 'STOD', 'ry-wc-city-select'),
		_x('Jharsuguda District', 'STOD', 'ry-wc-city-select'),
		_x('Kalahandi', 'STOD', 'ry-wc-city-select'),
		_x('Kandhamal', 'STOD', 'ry-wc-city-select'),
		_x('Kendrapara', 'STOD', 'ry-wc-city-select'),
		_x('Kendujhar', 'STOD', 'ry-wc-city-select'),
		_x('Khordha', 'STOD', 'ry-wc-city-select'),
		_x('Koraput', 'STOD', 'ry-wc-city-select'),
		_x('Malkangiri', 'STOD', 'ry-wc-city-select'),
		_x('Mayurbhanj', 'STOD', 'ry-wc-city-select'),
		_x('Nabarangpur', 'STOD', 'ry-wc-city-select'),
		_x('Nayagarh District', 'STOD', 'ry-wc-city-select'),
		_x('Nuapada', 'STOD', 'ry-wc-city-select'),
		_x('Puri', 'STOD', 'ry-wc-city-select'),
		_x('Rayagada', 'STOD', 'ry-wc-city-select'),
		_x('Sambalpur', 'STOD', 'ry-wc-city-select'),
		_x('Subarnapur', 'STOD', 'ry-wc-city-select'),
		_x('Sundargarh', 'STOD', 'ry-wc-city-select'),
	],
	'STPU' => [
		_x('Ajitgarh', 'STPU', 'ry-wc-city-select'),
		_x('Amritsar', 'STPU', 'ry-wc-city-select'),
		_x('Barnala', 'STPU', 'ry-wc-city-select'),
		_x('Bathinda', 'STPU', 'ry-wc-city-select'),
		_x('Faridkot', 'STPU', 'ry-wc-city-select'),
		_x('Fatehgarh Sahib', 'STPU', 'ry-wc-city-select'),
		_x('Fazilka', 'STPU', 'ry-wc-city-select'),
		_x('Firozpur', 'STPU', 'ry-wc-city-select'),
		_x('Gurdaspur', 'STPU', 'ry-wc-city-select'),
		_x('Hoshiarpur', 'STPU', 'ry-wc-city-select'),
		_x('Jalandhar', 'STPU', 'ry-wc-city-select'),
		_x('Kapurthala', 'STPU', 'ry-wc-city-select'),
		_x('Ludhiana', 'STPU', 'ry-wc-city-select'),
		_x('Mansa', 'STPU', 'ry-wc-city-select'),
		_x('Moga', 'STPU', 'ry-wc-city-select'),
		_x('Muktsar', 'STPU', 'ry-wc-city-select'),
		_x('Pathankot', 'STPU', 'ry-wc-city-select'),
		_x('Patiala', 'STPU', 'ry-wc-city-select'),
		_x('Rupnagar', 'STPU', 'ry-wc-city-select'),
		_x('Sangrur', 'STPU', 'ry-wc-city-select'),
		_x('Shahid Bhagat Singh Nagar', 'STPU', 'ry-wc-city-select'),
		_x('Tarn Taran', 'STPU', 'ry-wc-city-select'),
	],
	'STRA' => [
		_x('Ajmer', 'STRA', 'ry-wc-city-select'),
		_x('Alwar', 'STRA', 'ry-wc-city-select'),
		_x('Banswara', 'STRA', 'ry-wc-city-select'),
		_x('Baran', 'STRA', 'ry-wc-city-select'),
		_x('Barmer', 'STRA', 'ry-wc-city-select'),
		_x('Bharatpur', 'STRA', 'ry-wc-city-select'),
		_x('Bhilwara', 'STRA', 'ry-wc-city-select'),
		_x('Bikaner', 'STRA', 'ry-wc-city-select'),
		_x('Bundi', 'STRA', 'ry-wc-city-select'),
		_x('Chittaurgarh', 'STRA', 'ry-wc-city-select'),
		_x('Churu', 'STRA', 'ry-wc-city-select'),
		_x('Dausa', 'STRA', 'ry-wc-city-select'),
		_x('Dhaulpur', 'STRA', 'ry-wc-city-select'),
		_x('Dungarpur', 'STRA', 'ry-wc-city-select'),
		_x('Ganganagar', 'STRA', 'ry-wc-city-select'),
		_x('Hanumangarh', 'STRA', 'ry-wc-city-select'),
		_x('Jaipur', 'STRA', 'ry-wc-city-select'),
		_x('Jaisalmer', 'STRA', 'ry-wc-city-select'),
		_x('Jalore', 'STRA', 'ry-wc-city-select'),
		_x('Jhalawar', 'STRA', 'ry-wc-city-select'),
		_x('Jhunjhunun', 'STRA', 'ry-wc-city-select'),
		_x('Jodhpur', 'STRA', 'ry-wc-city-select'),
		_x('Karauli', 'STRA', 'ry-wc-city-select'),
		_x('Kota', 'STRA', 'ry-wc-city-select'),
		_x('Nagaur', 'STRA', 'ry-wc-city-select'),
		_x('Pali', 'STRA', 'ry-wc-city-select'),
		_x('Pratapgarh', 'STRA', 'ry-wc-city-select'),
		_x('Rajsamand', 'STRA', 'ry-wc-city-select'),
		_x('Sawai Madhopur', 'STRA', 'ry-wc-city-select'),
		_x('Sikar', 'STRA', 'ry-wc-city-select'),
		_x('Sirohi', 'STRA', 'ry-wc-city-select'),
		_x('Tonk', 'STRA', 'ry-wc-city-select'),
		_x('Udaipur', 'STRA', 'ry-wc-city-select'),
	],
	'STTANA' => [
		_x('Ariyalur', 'STTANA', 'ry-wc-city-select'),
		_x('Chennai', 'STTANA', 'ry-wc-city-select'),
		_x('Coimbatore', 'STTANA', 'ry-wc-city-select'),
		_x('Cuddalore', 'STTANA', 'ry-wc-city-select'),
		_x('Dharmapuri', 'STTANA', 'ry-wc-city-select'),
		_x('Dindigul', 'STTANA', 'ry-wc-city-select'),
		_x('Erode', 'STTANA', 'ry-wc-city-select'),
		_x('Kancheepuram', 'STTANA', 'ry-wc-city-select'),
		_x('Kanniyakumari', 'STTANA', 'ry-wc-city-select'),
		_x('Karur', 'STTANA', 'ry-wc-city-select'),
		_x('Krishnagiri', 'STTANA', 'ry-wc-city-select'),
		_x('Madurai', 'STTANA', 'ry-wc-city-select'),
		_x('Nagapattinam', 'STTANA', 'ry-wc-city-select'),
		_x('Namakkal', 'STTANA', 'ry-wc-city-select'),
		_x('Nilgiris', 'STTANA', 'ry-wc-city-select'),
		_x('Perambalur', 'STTANA', 'ry-wc-city-select'),
		_x('Pudukkottai', 'STTANA', 'ry-wc-city-select'),
		_x('Ramanathapuram', 'STTANA', 'ry-wc-city-select'),
		_x('Salem', 'STTANA', 'ry-wc-city-select'),
		_x('Sivaganga', 'STTANA', 'ry-wc-city-select'),
		_x('Thanjavur', 'STTANA', 'ry-wc-city-select'),
		_x('Theni', 'STTANA', 'ry-wc-city-select'),
		_x('Thiruvallur', 'STTANA', 'ry-wc-city-select'),
		_x('Thiruvarur', 'STTANA', 'ry-wc-city-select'),
		_x('Thoothukkudi', 'STTANA', 'ry-wc-city-select'),
		_x('Tiruchirappalli', 'STTANA', 'ry-wc-city-select'),
		_x('Tirunelveli Kattabo', 'STTANA', 'ry-wc-city-select'),
		_x('Tiruppur', 'STTANA', 'ry-wc-city-select'),
		_x('Tiruvannamalai', 'STTANA', 'ry-wc-city-select'),
		_x('Vellore', 'STTANA', 'ry-wc-city-select'),
		_x('Villupuram', 'STTANA', 'ry-wc-city-select'),
		_x('Virudhunagar', 'STTANA', 'ry-wc-city-select'),
	],
	'STUT' => [
		_x('Almora', 'STUT', 'ry-wc-city-select'),
		_x('Bageshwar', 'STUT', 'ry-wc-city-select'),
		_x('Chamoli', 'STUT', 'ry-wc-city-select'),
		_x('Champawat', 'STUT', 'ry-wc-city-select'),
		_x('Dehradun', 'STUT', 'ry-wc-city-select'),
		_x('Garhwal', 'STUT', 'ry-wc-city-select'),
		_x('Haridwar', 'STUT', 'ry-wc-city-select'),
		_x('Naini Tal', 'STUT', 'ry-wc-city-select'),
		_x('Pithoragarh', 'STUT', 'ry-wc-city-select'),
		_x('Rudraprayag', 'STUT', 'ry-wc-city-select'),
		_x('Tehri-Garhwal', 'STUT', 'ry-wc-city-select'),
		_x('Udham Singh Nagar', 'STUT', 'ry-wc-city-select'),
		_x('Uttarkashi', 'STUT', 'ry-wc-city-select'),
	],
	'TE' => [
		_x('Adilabad', 'TE', 'ry-wc-city-select'),
		_x('Bhadradri Kothagudem', 'TE', 'ry-wc-city-select'),
		_x('Hyderabad', 'TE', 'ry-wc-city-select'),
		_x('Jagitial', 'TE', 'ry-wc-city-select'),
		_x('Jangoan', 'TE', 'ry-wc-city-select'),
		_x('Jayashankar Bhupalapally', 'TE', 'ry-wc-city-select'),
		_x('Jogulamba Gadwal', 'TE', 'ry-wc-city-select'),
		_x('Kamareddy', 'TE', 'ry-wc-city-select'),
		_x('Karimnagar', 'TE', 'ry-wc-city-select'),
		_x('Khammam', 'TE', 'ry-wc-city-select'),
		_x('Kumuram Bheem Asifabad', 'TE', 'ry-wc-city-select'),
		_x('Mahabubabad', 'TE', 'ry-wc-city-select'),
		_x('Mahbubnagar', 'TE', 'ry-wc-city-select'),
		_x('Mancherial', 'TE', 'ry-wc-city-select'),
		_x('Medak', 'TE', 'ry-wc-city-select'),
		_x('Medchal Malkajgiri', 'TE', 'ry-wc-city-select'),
		_x('Nagarkurnool', 'TE', 'ry-wc-city-select'),
		_x('Nalgonda', 'TE', 'ry-wc-city-select'),
		_x('Nirmal', 'TE', 'ry-wc-city-select'),
		_x('Nizamabad', 'TE', 'ry-wc-city-select'),
		_x('Peddapalli', 'TE', 'ry-wc-city-select'),
		_x('Rajanna Sircilla', 'TE', 'ry-wc-city-select'),
		_x('Rangareddi', 'TE', 'ry-wc-city-select'),
		_x('Sangareddy', 'TE', 'ry-wc-city-select'),
		_x('Siddipet', 'TE', 'ry-wc-city-select'),
		_x('Suryapet', 'TE', 'ry-wc-city-select'),
		_x('Vikarabad', 'TE', 'ry-wc-city-select'),
		_x('Wanaparthy', 'TE', 'ry-wc-city-select'),
		_x('Warangal', 'TE', 'ry-wc-city-select'),
		_x('Warangal Urban', 'TE', 'ry-wc-city-select'),
		_x('Yadadri Bhuvanagiri', 'TE', 'ry-wc-city-select'),
	],
	'TR' => [
		_x('Dhalai', 'TR', 'ry-wc-city-select'),
		_x('Gomati', 'TR', 'ry-wc-city-select'),
		_x('Khowai', 'TR', 'ry-wc-city-select'),
		_x('North Tripura', 'TR', 'ry-wc-city-select'),
		_x('Sepahijala', 'TR', 'ry-wc-city-select'),
		_x('South Tripura', 'TR', 'ry-wc-city-select'),
		_x('Unakoti', 'TR', 'ry-wc-city-select'),
	],
	'UNTEANANNI' => [
		_x('Nicobar', 'UNTEANANNI', 'ry-wc-city-select'),
		_x('North  & Middle Andaman', 'UNTEANANNI', 'ry-wc-city-select'),
		_x('South Andaman', 'UNTEANANNI', 'ry-wc-city-select'),
	],
	'UNTECH' => [
		_x('Chandigarh', 'UNTECH', 'ry-wc-city-select'),
	],
	'UNTEDAANNAHA' => [
		_x('Dadra & Nagar Haveli', 'UNTEDAANNAHA', 'ry-wc-city-select'),
	],
	'UNTEDAANDI' => [
		_x('Daman District', 'UNTEDAANDI', 'ry-wc-city-select'),
		_x('Diu', 'UNTEDAANDI', 'ry-wc-city-select'),
	],
	'UNTELA' => [
		_x('Lakshadweep', 'UNTELA', 'ry-wc-city-select'),
	],
	'UNTEPU' => [
		_x('Karaikal', 'UNTEPU', 'ry-wc-city-select'),
		_x('Mahe', 'UNTEPU', 'ry-wc-city-select'),
		_x('Puducherry', 'UNTEPU', 'ry-wc-city-select'),
		_x('Yanam', 'UNTEPU', 'ry-wc-city-select'),
	],
	'UTPR' => [
		_x('Agra', 'UTPR', 'ry-wc-city-select'),
		_x('Aligarh', 'UTPR', 'ry-wc-city-select'),
		_x('Allahabad', 'UTPR', 'ry-wc-city-select'),
		_x('Ambedkar Nagar', 'UTPR', 'ry-wc-city-select'),
		_x('Amethi', 'UTPR', 'ry-wc-city-select'),
		_x('Auraiya', 'UTPR', 'ry-wc-city-select'),
		_x('Azamgarh', 'UTPR', 'ry-wc-city-select'),
		_x('Baghpat', 'UTPR', 'ry-wc-city-select'),
		_x('Bahraich', 'UTPR', 'ry-wc-city-select'),
		_x('Ballia', 'UTPR', 'ry-wc-city-select'),
		_x('Balrampur', 'UTPR', 'ry-wc-city-select'),
		_x('Banda', 'UTPR', 'ry-wc-city-select'),
		_x('Bara Banki', 'UTPR', 'ry-wc-city-select'),
		_x('Bareilly', 'UTPR', 'ry-wc-city-select'),
		_x('Basti', 'UTPR', 'ry-wc-city-select'),
		_x('Bijnor', 'UTPR', 'ry-wc-city-select'),
		_x('Budaun', 'UTPR', 'ry-wc-city-select'),
		_x('Bulandshahr', 'UTPR', 'ry-wc-city-select'),
		_x('Chandauli District', 'UTPR', 'ry-wc-city-select'),
		_x('Chitrakoot', 'UTPR', 'ry-wc-city-select'),
		_x('Deoria', 'UTPR', 'ry-wc-city-select'),
		_x('Etah', 'UTPR', 'ry-wc-city-select'),
		_x('Etawah', 'UTPR', 'ry-wc-city-select'),
		_x('Faizabad', 'UTPR', 'ry-wc-city-select'),
		_x('Farrukhabad', 'UTPR', 'ry-wc-city-select'),
		_x('Fatehpur', 'UTPR', 'ry-wc-city-select'),
		_x('Firozabad', 'UTPR', 'ry-wc-city-select'),
		_x('Gautam Buddha Nagar', 'UTPR', 'ry-wc-city-select'),
		_x('Ghaziabad', 'UTPR', 'ry-wc-city-select'),
		_x('Ghazipur', 'UTPR', 'ry-wc-city-select'),
		_x('Gonda', 'UTPR', 'ry-wc-city-select'),
		_x('Gorakhpur', 'UTPR', 'ry-wc-city-select'),
		_x('Hamirpur', 'UTPR', 'ry-wc-city-select'),
		_x('Hapur', 'UTPR', 'ry-wc-city-select'),
		_x('Hardoi', 'UTPR', 'ry-wc-city-select'),
		_x('Hathras', 'UTPR', 'ry-wc-city-select'),
		_x('Jalaun', 'UTPR', 'ry-wc-city-select'),
		_x('Jaunpur', 'UTPR', 'ry-wc-city-select'),
		_x('Jhansi', 'UTPR', 'ry-wc-city-select'),
		_x('Jyotiba Phule Nagar', 'UTPR', 'ry-wc-city-select'),
		_x('Kannauj', 'UTPR', 'ry-wc-city-select'),
		_x('Kanpur', 'UTPR', 'ry-wc-city-select'),
		_x('Kanpur Dehat', 'UTPR', 'ry-wc-city-select'),
		_x('Kasganj', 'UTPR', 'ry-wc-city-select'),
		_x('Kaushambi District', 'UTPR', 'ry-wc-city-select'),
		_x('Kheri', 'UTPR', 'ry-wc-city-select'),
		_x('Kushinagar', 'UTPR', 'ry-wc-city-select'),
		_x('Lalitpur', 'UTPR', 'ry-wc-city-select'),
		_x('Lucknow District', 'UTPR', 'ry-wc-city-select'),
		_x('Maharajganj', 'UTPR', 'ry-wc-city-select'),
		_x('Mahoba', 'UTPR', 'ry-wc-city-select'),
		_x('Mainpuri', 'UTPR', 'ry-wc-city-select'),
		_x('Mathura', 'UTPR', 'ry-wc-city-select'),
		_x('Mau', 'UTPR', 'ry-wc-city-select'),
		_x('Meerut', 'UTPR', 'ry-wc-city-select'),
		_x('Mirzapur', 'UTPR', 'ry-wc-city-select'),
		_x('Moradabad', 'UTPR', 'ry-wc-city-select'),
		_x('Muzaffarnagar', 'UTPR', 'ry-wc-city-select'),
		_x('Pilibhit', 'UTPR', 'ry-wc-city-select'),
		_x('Pratapgarh', 'UTPR', 'ry-wc-city-select'),
		_x('Rae Bareli', 'UTPR', 'ry-wc-city-select'),
		_x('Rampur', 'UTPR', 'ry-wc-city-select'),
		_x('Saharanpur', 'UTPR', 'ry-wc-city-select'),
		_x('Sambhal', 'UTPR', 'ry-wc-city-select'),
		_x('Sant Kabir Nagar', 'UTPR', 'ry-wc-city-select'),
		_x('Sant Ravi Das Nagar', 'UTPR', 'ry-wc-city-select'),
		_x('Shahjahanpur', 'UTPR', 'ry-wc-city-select'),
		_x('Shamli', 'UTPR', 'ry-wc-city-select'),
		_x('Shrawasti', 'UTPR', 'ry-wc-city-select'),
		_x('Siddharthnagar', 'UTPR', 'ry-wc-city-select'),
		_x('Sitapur', 'UTPR', 'ry-wc-city-select'),
		_x('Sonbhadra', 'UTPR', 'ry-wc-city-select'),
		_x('Sultanpur', 'UTPR', 'ry-wc-city-select'),
		_x('Unnao', 'UTPR', 'ry-wc-city-select'),
		_x('Varanasi', 'UTPR', 'ry-wc-city-select'),
	],
	'WEBE' => [
		_x('Alipurduar', 'WEBE', 'ry-wc-city-select'),
		_x('Bankura', 'WEBE', 'ry-wc-city-select'),
		_x('Barddhaman', 'WEBE', 'ry-wc-city-select'),
		_x('Birbhum', 'WEBE', 'ry-wc-city-select'),
		_x('Dakshin Dinajpur', 'WEBE', 'ry-wc-city-select'),
		_x('Darjiling', 'WEBE', 'ry-wc-city-select'),
		_x('Haora', 'WEBE', 'ry-wc-city-select'),
		_x('Hugli', 'WEBE', 'ry-wc-city-select'),
		_x('Jalpaiguri', 'WEBE', 'ry-wc-city-select'),
		_x('Jhargram', 'WEBE', 'ry-wc-city-select'),
		_x('Kalimpong', 'WEBE', 'ry-wc-city-select'),
		_x('Koch Bihar', 'WEBE', 'ry-wc-city-select'),
		_x('Kolkata', 'WEBE', 'ry-wc-city-select'),
		_x('Maldah', 'WEBE', 'ry-wc-city-select'),
		_x('Murshidabad', 'WEBE', 'ry-wc-city-select'),
		_x('Nadia', 'WEBE', 'ry-wc-city-select'),
		_x('North 24 Parganas', 'WEBE', 'ry-wc-city-select'),
		_x('Paschim Bardhaman', 'WEBE', 'ry-wc-city-select'),
		_x('Paschim Medinipur', 'WEBE', 'ry-wc-city-select'),
		_x('Purba Medinipur', 'WEBE', 'ry-wc-city-select'),
		_x('Puruliya', 'WEBE', 'ry-wc-city-select'),
		_x('South 24 Parganas', 'WEBE', 'ry-wc-city-select'),
		_x('Uttar Dinajpur', 'WEBE', 'ry-wc-city-select'),
	],
	]
];