<?php
/**
 * Republic of Iraq places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'IQ' => [
	'NA' => [
		_x('Al-Manathera District', 'NA', 'ry-wc-city-select'),
		_x('Kufa', 'NA', 'ry-wc-city-select'),
		_x('Najaf District', 'NA', 'ry-wc-city-select'),
	],
	'DI' => [
		_x('Adhamiyah', 'DI', 'ry-wc-city-select'),
		_x('Dohuk District', 'DI', 'ry-wc-city-select'),
		_x('Qeza-i Semel', 'DI', 'ry-wc-city-select'),
		_x('Semel District', 'DI', 'ry-wc-city-select'),
		_x('Zakho District', 'DI', 'ry-wc-city-select'),
	],
	'DI2' => [
		_x('Al-Khalis District', 'DI2', 'ry-wc-city-select'),
		_x('Al-Muqdadiya District', 'DI2', 'ry-wc-city-select'),
		_x('Baquba District', 'DI2', 'ry-wc-city-select'),
		_x('Khanaqin District', 'DI2', 'ry-wc-city-select'),
		_x('Qada Balad Ruz', 'DI2', 'ry-wc-city-select'),
		_x('Qada Kifri', 'DI2', 'ry-wc-city-select'),
	],
	'MUAR' => [
		_x('Arbil', 'MUAR', 'ry-wc-city-select'),
		_x('Choman District', 'MUAR', 'ry-wc-city-select'),
		_x('Koisnjaq district', 'MUAR', 'ry-wc-city-select'),
		_x('Makhmur District', 'MUAR', 'ry-wc-city-select'),
		_x('Mergasur District', 'MUAR', 'ry-wc-city-select'),
		_x('Qada Dashti Hawlayr', 'MUAR', 'ry-wc-city-select'),
		_x('Qada Jawman', 'MUAR', 'ry-wc-city-select'),
		_x('Qada Khabat', 'MUAR', 'ry-wc-city-select'),
		_x('Qada Sawran', 'MUAR', 'ry-wc-city-select'),
		_x('Qada Shaqlawah', 'MUAR', 'ry-wc-city-select'),
		_x('Qeza-i Mergasur', 'MUAR', 'ry-wc-city-select'),
		_x('Qeza-i Ruwandiz', 'MUAR', 'ry-wc-city-select'),
		_x('Shaqlawa', 'MUAR', 'ry-wc-city-select'),
		_x('Soran District', 'MUAR', 'ry-wc-city-select'),
	],
	'MUBA' => [
		_x('Al-Hilla District', 'MUBA', 'ry-wc-city-select'),
		_x('Al-Mahawil District', 'MUBA', 'ry-wc-city-select'),
		_x('Al-Musayab District', 'MUBA', 'ry-wc-city-select'),
		_x('Hashimiya District', 'MUBA', 'ry-wc-city-select'),
	],
	'MUBA2' => [
		_x('Abu Ghraib District', 'MUBA2', 'ry-wc-city-select'),
		_x('Al Rusafa', 'MUBA2', 'ry-wc-city-select'),
		_x('Al Tarmia District', 'MUBA2', 'ry-wc-city-select'),
		_x('Al-Kazimiyyah', 'MUBA2', 'ry-wc-city-select'),
		_x('Al-Madain District', 'MUBA2', 'ry-wc-city-select'),
		_x('Baghdad', 'MUBA2', 'ry-wc-city-select'),
		_x('Karkh', 'MUBA2', 'ry-wc-city-select'),
		_x('Mahmudiya District', 'MUBA2', 'ry-wc-city-select'),
		_x('Qada Abu Ghurayb', 'MUBA2', 'ry-wc-city-select'),
		_x('Qada al A`zamiyah', 'MUBA2', 'ry-wc-city-select'),
		_x('Qada al Madain', 'MUBA2', 'ry-wc-city-select'),
		_x('Qada ar Rusafah', 'MUBA2', 'ry-wc-city-select'),
		_x('Qada at Tarmiyah', 'MUBA2', 'ry-wc-city-select'),
		_x('Sadr', 'MUBA2', 'ry-wc-city-select'),
		_x('Taji District', 'MUBA2', 'ry-wc-city-select'),
		_x('Thawra', 'MUBA2', 'ry-wc-city-select'),
	],
	'MUDHQA' => [
		_x('Al-Chibayish District', 'MUDHQA', 'ry-wc-city-select'),
		_x('Al-Rifai District', 'MUDHQA', 'ry-wc-city-select'),
		_x('Al-Shatra District', 'MUDHQA', 'ry-wc-city-select'),
		_x('Nassriya District', 'MUDHQA', 'ry-wc-city-select'),
		_x('Suq Al-Shoyokh District', 'MUDHQA', 'ry-wc-city-select'),
	],
	'MUKA' => [
		_x('Ain Al-Tamur District', 'MUKA', 'ry-wc-city-select'),
		_x('Al-Hindiya District', 'MUKA', 'ry-wc-city-select'),
		_x('Kerbala District', 'MUKA', 'ry-wc-city-select'),
		_x('Qada `Ayn Tamr', 'MUKA', 'ry-wc-city-select'),
	],
	'MUKI' => [
		_x('Al-Hawija District', 'MUKI', 'ry-wc-city-select'),
		_x('Dabes', 'MUKI', 'ry-wc-city-select'),
		_x('Daquq District', 'MUKI', 'ry-wc-city-select'),
		_x('Kirkuk District', 'MUKI', 'ry-wc-city-select'),
		_x('Qada Dibis', 'MUKI', 'ry-wc-city-select'),
	],
	'MUMA' => [
		_x('Al Kahla District', 'MUMA', 'ry-wc-city-select'),
		_x('Al-Maimouna District', 'MUMA', 'ry-wc-city-select'),
		_x('Al-Mejar Al-Kabi District', 'MUMA', 'ry-wc-city-select'),
		_x('Ali Al-Gharbi District', 'MUMA', 'ry-wc-city-select'),
		_x('Amara District', 'MUMA', 'ry-wc-city-select'),
		_x('Qada Qal`at Salih', 'MUMA', 'ry-wc-city-select'),
		_x('Qada al Majar al Kabir', 'MUMA', 'ry-wc-city-select'),
		_x('Qada al Maymunah', 'MUMA', 'ry-wc-city-select'),
	],
	'MUNI' => [
		_x('Akre District', 'MUNI', 'ry-wc-city-select'),
		_x('Al-Baaj District', 'MUNI', 'ry-wc-city-select'),
		_x('Al-Hamdaniya District', 'MUNI', 'ry-wc-city-select'),
		_x('Hatra District', 'MUNI', 'ry-wc-city-select'),
		_x('Mosul', 'MUNI', 'ry-wc-city-select'),
		_x('Qada Ba`aj', 'MUNI', 'ry-wc-city-select'),
		_x('Qada Tallkayf', 'MUNI', 'ry-wc-city-select'),
		_x('Shekhan District', 'MUNI', 'ry-wc-city-select'),
		_x('Sinjar', 'MUNI', 'ry-wc-city-select'),
		_x('Tel Afar District', 'MUNI', 'ry-wc-city-select'),
		_x('Tel Keppe District', 'MUNI', 'ry-wc-city-select'),
	],
	'MUSADI' => [
		_x('Al-Daur District', 'MUSADI', 'ry-wc-city-select'),
		_x('Al-Faris', 'MUSADI', 'ry-wc-city-select'),
		_x('Al-Shirqat District', 'MUSADI', 'ry-wc-city-select'),
		_x('Al-Thethar District', 'MUSADI', 'ry-wc-city-select'),
		_x('Baiji District', 'MUSADI', 'ry-wc-city-select'),
		_x('Balad District', 'MUSADI', 'ry-wc-city-select'),
		_x('Qada Samarra', 'MUSADI', 'ry-wc-city-select'),
		_x('Tikrit District', 'MUSADI', 'ry-wc-city-select'),
		_x('Tooz District', 'MUSADI', 'ry-wc-city-select'),
	],
	'MUWA' => [
		_x('Al-Hai District', 'MUWA', 'ry-wc-city-select'),
		_x('Al-Namaniya District', 'MUWA', 'ry-wc-city-select'),
		_x('Al-Suwaira District', 'MUWA', 'ry-wc-city-select'),
		_x('Badra District', 'MUWA', 'ry-wc-city-select'),
		_x('Kut District', 'MUWA', 'ry-wc-city-select'),
		_x('Qada Al-Azezia', 'MUWA', 'ry-wc-city-select'),
		_x('Qada al `Aziziyah', 'MUWA', 'ry-wc-city-select'),
		_x('Qada an Nu`maniyah', 'MUWA', 'ry-wc-city-select'),
	],
	'MUAN' => [
		_x('Al-Kaim District', 'MUAN', 'ry-wc-city-select'),
		_x('Al-Rutba District', 'MUAN', 'ry-wc-city-select'),
		_x('Anah District', 'MUAN', 'ry-wc-city-select'),
		_x('Falluja District', 'MUAN', 'ry-wc-city-select'),
		_x('Haditha District', 'MUAN', 'ry-wc-city-select'),
		_x('Hit District', 'MUAN', 'ry-wc-city-select'),
		_x('Qada al Qaim', 'MUAN', 'ry-wc-city-select'),
		_x('Ramadi District', 'MUAN', 'ry-wc-city-select'),
		_x('Rawah District', 'MUAN', 'ry-wc-city-select'),
	],
	'MUBA3' => [
		_x('Abu Al-Khaseeb District', 'MUBA3', 'ry-wc-city-select'),
		_x('Al-Faw District', 'MUBA3', 'ry-wc-city-select'),
		_x('Al-Midaina District', 'MUBA3', 'ry-wc-city-select'),
		_x('Al-Qurna District', 'MUBA3', 'ry-wc-city-select'),
		_x('Al-Zubair District', 'MUBA3', 'ry-wc-city-select'),
		_x('Basrah District', 'MUBA3', 'ry-wc-city-select'),
		_x('Qada al Madinah', 'MUBA3', 'ry-wc-city-select'),
	],
	'MUMU' => [
		_x('Al-Khidir District', 'MUMU', 'ry-wc-city-select'),
		_x('Al-Rumaitha District', 'MUMU', 'ry-wc-city-select'),
		_x('Al-Salman District', 'MUMU', 'ry-wc-city-select'),
		_x('Al-Samawa District', 'MUMU', 'ry-wc-city-select'),
		_x('Qada al Khidr', 'MUMU', 'ry-wc-city-select'),
		_x('Qada ar Rumaythah', 'MUMU', 'ry-wc-city-select'),
	],
	'MUQA' => [
		_x('Afaq District', 'MUQA', 'ry-wc-city-select'),
		_x('Hamza District', 'MUQA', 'ry-wc-city-select'),
		_x('Qada Al-Shamiya', 'MUQA', 'ry-wc-city-select'),
		_x('Qada Diwaniya', 'MUQA', 'ry-wc-city-select'),
	],
	'MUSU' => [
		_x('Chamchamal District', 'MUSU', 'ry-wc-city-select'),
		_x('Darbandokeh District', 'MUSU', 'ry-wc-city-select'),
		_x('Dokan District', 'MUSU', 'ry-wc-city-select'),
		_x('Kalar District', 'MUSU', 'ry-wc-city-select'),
		_x('Penjwin District', 'MUSU', 'ry-wc-city-select'),
		_x('Pshdar District', 'MUSU', 'ry-wc-city-select'),
		_x('Qada Darbandikhan', 'MUSU', 'ry-wc-city-select'),
		_x('Qada Halabchah', 'MUSU', 'ry-wc-city-select'),
		_x('Qada Mawat', 'MUSU', 'ry-wc-city-select'),
		_x('Qada Sayyid Sadiq', 'MUSU', 'ry-wc-city-select'),
		_x('Qada as Sulaymaniyah', 'MUSU', 'ry-wc-city-select'),
		_x('Qeza-i Penciwen', 'MUSU', 'ry-wc-city-select'),
		_x('Qeza-i Qeredagh', 'MUSU', 'ry-wc-city-select'),
		_x('Qeza-i Sharezur', 'MUSU', 'ry-wc-city-select'),
		_x('Rania District', 'MUSU', 'ry-wc-city-select'),
		_x('Sharbazher District', 'MUSU', 'ry-wc-city-select'),
	],
	]
];