<?php
/**
 * Islamic Republic of Iran places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'IR' => [
	'MA' => [
		_x('Shahmirzad', 'MA', 'ry-wc-city-select'),
	],
	'AL' => [
		_x('Fardis', 'AL', 'ry-wc-city-select'),
		_x('Karaj', 'AL', 'ry-wc-city-select'),
		_x('Shahrestan-e Eshtehard', 'AL', 'ry-wc-city-select'),
		_x('Shahrestan-e Nazarabad', 'AL', 'ry-wc-city-select'),
		_x('Shahrestan-e Savojbolagh', 'AL', 'ry-wc-city-select'),
		_x('Shahrestan-e Taleqan', 'AL', 'ry-wc-city-select'),
	],
	'BU' => [
		_x('Deylam', 'BU', 'ry-wc-city-select'),
		_x('Deyr', 'BU', 'ry-wc-city-select'),
		_x('Jam', 'BU', 'ry-wc-city-select'),
		_x('Shahrestan-e Asaluyeh', 'BU', 'ry-wc-city-select'),
		_x('Shahrestan-e Bushehr', 'BU', 'ry-wc-city-select'),
		_x('Shahrestan-e Dashtestan', 'BU', 'ry-wc-city-select'),
		_x('Shahrestan-e Dashti', 'BU', 'ry-wc-city-select'),
		_x('Shahrestan-e Genaveh', 'BU', 'ry-wc-city-select'),
		_x('Shahrestan-e Kangan', 'BU', 'ry-wc-city-select'),
		_x('Shahrestan-e Tangestan', 'BU', 'ry-wc-city-select'),
	],
	'EAAZ' => [
		_x('Ahar', 'EAAZ', 'ry-wc-city-select'),
		_x('Kaleybar', 'EAAZ', 'ry-wc-city-select'),
		_x('Marand', 'EAAZ', 'ry-wc-city-select'),
		_x('Shabestar', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Ajab Shir', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Azarshahr', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Bonab', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Bostanabad', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Charavimaq', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Hashtrud', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Heris', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Jolfa', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Khoda Afarin', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Malekan', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Maragheh', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Mianeh', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Osku', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Sarab', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Tabriz', 'EAAZ', 'ry-wc-city-select'),
		_x('Shahrestan-e Varzaqan', 'EAAZ', 'ry-wc-city-select'),
	],
	'FA' => [
		_x('Jahrom', 'FA', 'ry-wc-city-select'),
		_x('Khonj', 'FA', 'ry-wc-city-select'),
		_x('Mamasani', 'FA', 'ry-wc-city-select'),
		_x('Marvdasht', 'FA', 'ry-wc-city-select'),
		_x('Mohr', 'FA', 'ry-wc-city-select'),
		_x('Rostam', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Abadeh', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Arsanjan', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Bavanat', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Darab', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Eqlid', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Estahban', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Farashband', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Fasa', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Firuzabad', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Gerash', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Kavar', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Kazerun', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Kherameh', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Khorrambid', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Lamerd', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Larestan', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Neyriz', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Pasargad', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Qir va Karzin', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Sarvestan', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Sepidan', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Shiraz', 'FA', 'ry-wc-city-select'),
		_x('Shahrestan-e Zarrin Dasht', 'FA', 'ry-wc-city-select'),
	],
	'HO' => [
		_x('Bandar Lengeh', 'HO', 'ry-wc-city-select'),
		_x('Bastak', 'HO', 'ry-wc-city-select'),
		_x('Qeshm', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Abu Musa', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Bandar Abbas', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Bashagard', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Hajjiabad', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Jask', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Khamir', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Minab', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Parsian', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Rudan', 'HO', 'ry-wc-city-select'),
		_x('Shahrestan-e Sirik', 'HO', 'ry-wc-city-select'),
	],
	'ILPR' => [
		_x('Badreh', 'ILPR', 'ry-wc-city-select'),
		_x('Chardavol County', 'ILPR', 'ry-wc-city-select'),
		_x('Darrehshahr', 'ILPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Abdanan', 'ILPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Dehloran', 'ILPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Eyvan', 'ILPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Ilam', 'ILPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Malekshahi', 'ILPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Mehran', 'ILPR', 'ry-wc-city-select'),
		_x('Sirvan', 'ILPR', 'ry-wc-city-select'),
	],
	'IS' => [
		_x('Buin va Miandasht', 'IS', 'ry-wc-city-select'),
		_x('Fereydan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Aran va Bidgol', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Ardestan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Borkhvar', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Chadegan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Dehaqan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Esfahan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Falavarjan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Fareydunshahr', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Golpayegan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Kashan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Khomeyni Shahr', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Khur va Biabanak', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Khvansar', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Lenjan', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Mobarakeh', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Nain', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Najafabad', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Natanz', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Semirom', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Shahin Shahr va Meymeh', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Shahreza', 'IS', 'ry-wc-city-select'),
		_x('Shahrestan-e Tiran va Karvan', 'IS', 'ry-wc-city-select'),
	],
	'KE' => [
		_x('Bam', 'KE', 'ry-wc-city-select'),
		_x('Fahraj', 'KE', 'ry-wc-city-select'),
		_x('Ravar', 'KE', 'ry-wc-city-select'),
		_x('Rigan', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Anbarabad', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Anar', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Baft', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Bardsir', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Faryab', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Jiroft', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Kahnuj', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Kerman', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Kuhbanan', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Manujan', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Narmashir', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Orzuiyeh', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Qaleh Ganj', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Rabor', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Rafsanjan', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Rudbar-e Jonubi', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Shahr-e Babak', 'KE', 'ry-wc-city-select'),
		_x('Shahrestan-e Sirjan', 'KE', 'ry-wc-city-select'),
		_x('Zarand', 'KE', 'ry-wc-city-select'),
	],
	'KH' => [
		_x('Aghajari', 'KH', 'ry-wc-city-select'),
		_x('Bagh Shahrestan-e Malek', 'KH', 'ry-wc-city-select'),
		_x('Gotvand', 'KH', 'ry-wc-city-select'),
		_x('Haftkel', 'KH', 'ry-wc-city-select'),
		_x('Hamidiyeh', 'KH', 'ry-wc-city-select'),
		_x('Hoveyzeh', 'KH', 'ry-wc-city-select'),
		_x('Karun', 'KH', 'ry-wc-city-select'),
		_x('Khorramshahr', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Abadan', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Ahvaz', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Andika', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Andimeshk', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Bandar-e Mahshahr', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Bavi', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Behbahan', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Dasht-e Azadegan', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Dezful', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Hendijan', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Izeh', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Lali', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Masjed Soleyman', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Omidiyeh', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Ramhormoz', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Ramshir', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Shadegan', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Shush', 'KH', 'ry-wc-city-select'),
		_x('Shahrestan-e Shushtar', 'KH', 'ry-wc-city-select'),
	],
	'OSAR' => [
		_x('Shahrestan-e Ardabil', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Bileh Savar', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Germi', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Khalkhal', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Kowsar', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Meshgin Shahr', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Namin', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Nir', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Parsabad', 'OSAR', 'ry-wc-city-select'),
		_x('Shahrestan-e Sareyn', 'OSAR', 'ry-wc-city-select'),
	],
	'OSCHMABA' => [
		_x('Ardal', 'OSCHMABA', 'ry-wc-city-select'),
		_x('Ben', 'OSCHMABA', 'ry-wc-city-select'),
		_x('Saman', 'OSCHMABA', 'ry-wc-city-select'),
		_x('Shahrekord', 'OSCHMABA', 'ry-wc-city-select'),
		_x('Shahrestan-e Borujen', 'OSCHMABA', 'ry-wc-city-select'),
		_x('Shahrestan-e Farsan', 'OSCHMABA', 'ry-wc-city-select'),
		_x('Shahrestan-e Kiar', 'OSCHMABA', 'ry-wc-city-select'),
		_x('Shahrestan-e Kuhrang', 'OSCHMABA', 'ry-wc-city-select'),
		_x('Shahrestan-e Lordegan', 'OSCHMABA', 'ry-wc-city-select'),
	],
	'OSGI' => [
		_x('Amlash', 'OSGI', 'ry-wc-city-select'),
		_x('Rasht', 'OSGI', 'ry-wc-city-select'),
		_x('Shaft', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Astaneh-ye Ashrafiyeh', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Astara', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Bandar-e Anzali', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Fuman', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Lahijan', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Langarud', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Masal', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Rezvanshahr', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Rudbar', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Rudsar', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Siahkal', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Sowmeeh Sara', 'OSGI', 'ry-wc-city-select'),
		_x('Shahrestan-e Talesh', 'OSGI', 'ry-wc-city-select'),
	],
	'OSGO' => [
		_x('Bandar-e Gaz', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Aliabad', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Aq Qala', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Azadshahr', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Galikesh', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Gomishan', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Gonbad-e Kavus', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Gorgan', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Kalaleh', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Kordkuy', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Maraveh Tappeh', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Minudasht', 'OSGO', 'ry-wc-city-select'),
		_x('Shahrestan-e Ramian', 'OSGO', 'ry-wc-city-select'),
		_x('Torkaman', 'OSGO', 'ry-wc-city-select'),
	],
	'OSHA' => [
		_x('Razan', 'OSHA', 'ry-wc-city-select'),
		_x('Shahrestan-e Asadabad', 'OSHA', 'ry-wc-city-select'),
		_x('Shahrestan-e Bahar', 'OSHA', 'ry-wc-city-select'),
		_x('Shahrestan-e Famenin', 'OSHA', 'ry-wc-city-select'),
		_x('Shahrestan-e Hamadan', 'OSHA', 'ry-wc-city-select'),
		_x('Shahrestan-e Kabudarahang', 'OSHA', 'ry-wc-city-select'),
		_x('Shahrestan-e Malayer', 'OSHA', 'ry-wc-city-select'),
		_x('Shahrestan-e Nahavand', 'OSHA', 'ry-wc-city-select'),
		_x('Shahrestan-e Tuyserkan', 'OSHA', 'ry-wc-city-select'),
	],
	'OSKE' => [
		_x('Shahrestan-e Dalahu', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Eslamabad-e Gharb', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Gilan-e Gharb', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Harsin', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Javanrud', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Kangavar', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Kermanshah', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Paveh', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Qasr-e Shirin', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Ravansar', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Sahneh', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Salas-e Baba Jani', 'OSKE', 'ry-wc-city-select'),
		_x('Shahrestan-e Sarpol-e Zahab', 'OSKE', 'ry-wc-city-select'),
		_x('Sonqor', 'OSKE', 'ry-wc-city-select'),
	],
	'OSKHJO' => [
		_x('Boshruyeh', 'OSKHJO', 'ry-wc-city-select'),
		_x('Ferdows', 'OSKHJO', 'ry-wc-city-select'),
		_x('Shahrestan-e Birjand', 'OSKHJO', 'ry-wc-city-select'),
		_x('Shahrestan-e Darmian', 'OSKHJO', 'ry-wc-city-select'),
		_x('Shahrestan-e Khusf', 'OSKHJO', 'ry-wc-city-select'),
		_x('Shahrestan-e Nehbandan', 'OSKHJO', 'ry-wc-city-select'),
		_x('Shahrestan-e Qaen', 'OSKHJO', 'ry-wc-city-select'),
		_x('Shahrestan-e Sarayan', 'OSKHJO', 'ry-wc-city-select'),
		_x('Shahrestan-e Sarbisheh', 'OSKHJO', 'ry-wc-city-select'),
		_x('Shahrestan-e Zirkuh', 'OSKHJO', 'ry-wc-city-select'),
		_x('Tabas', 'OSKHJO', 'ry-wc-city-select'),
	],
	'OSKHRA' => [
		_x('Bardaskan', 'OSKHRA', 'ry-wc-city-select'),
		_x('Dargaz', 'OSKHRA', 'ry-wc-city-select'),
		_x('Davarzan', 'OSKHRA', 'ry-wc-city-select'),
		_x('Joveyn', 'OSKHRA', 'ry-wc-city-select'),
		_x('Mashhad', 'OSKHRA', 'ry-wc-city-select'),
		_x('Sarakhs', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Bajestan', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Bakharz', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Binalud', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Chenaran', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Fariman', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Firuzeh', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Gonabad', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Joghatay', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Kalat', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Kashmar', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Khalilabad', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Khowshab', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Khvaf', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Mah Velat', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Neyshabur', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Quchan', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Roshtkhvar', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Sabzevar', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Taybad', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Torbat-e Heydariyeh', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Torbat-e Jam', 'OSKHRA', 'ry-wc-city-select'),
		_x('Shahrestan-e Zaveh', 'OSKHRA', 'ry-wc-city-select'),
	],
	'OSKHSH' => [
		_x('Garmeh', 'OSKHSH', 'ry-wc-city-select'),
		_x('Raz and Jargalan', 'OSKHSH', 'ry-wc-city-select'),
		_x('Shahrestan-e Bojnurd', 'OSKHSH', 'ry-wc-city-select'),
		_x('Shahrestan-e Esfarayen', 'OSKHSH', 'ry-wc-city-select'),
		_x('Shahrestan-e Faruj', 'OSKHSH', 'ry-wc-city-select'),
		_x('Shahrestan-e Jajarm', 'OSKHSH', 'ry-wc-city-select'),
		_x('Shahrestan-e Maneh va Samalqan', 'OSKHSH', 'ry-wc-city-select'),
		_x('Shahrestan-e Shirvan', 'OSKHSH', 'ry-wc-city-select'),
	],
	'OSKOBOAH' => [
		_x('Landeh', 'OSKOBOAH', 'ry-wc-city-select'),
		_x('Shahrestan-e Bahmai', 'OSKOBOAH', 'ry-wc-city-select'),
		_x('Shahrestan-e Basht', 'OSKOBOAH', 'ry-wc-city-select'),
		_x('Shahrestan-e Bowyer Ahmad', 'OSKOBOAH', 'ry-wc-city-select'),
		_x('Shahrestan-e Charam', 'OSKOBOAH', 'ry-wc-city-select'),
		_x('Shahrestan-e Dana', 'OSKOBOAH', 'ry-wc-city-select'),
		_x('Shahrestan-e Gachsaran', 'OSKOBOAH', 'ry-wc-city-select'),
		_x('Shahrestan-e Kohgiluyeh', 'OSKOBOAH', 'ry-wc-city-select'),
	],
	'OSKO' => [
		_x('Qorveh', 'OSKO', 'ry-wc-city-select'),
		_x('Sanandaj', 'OSKO', 'ry-wc-city-select'),
		_x('Saqqez', 'OSKO', 'ry-wc-city-select'),
		_x('Shahrestan-e Baneh', 'OSKO', 'ry-wc-city-select'),
		_x('Shahrestan-e Bijar', 'OSKO', 'ry-wc-city-select'),
		_x('Shahrestan-e Dehgolan', 'OSKO', 'ry-wc-city-select'),
		_x('Shahrestan-e Divandarreh', 'OSKO', 'ry-wc-city-select'),
		_x('Shahrestan-e Kamyaran', 'OSKO', 'ry-wc-city-select'),
		_x('Shahrestan-e Marivan', 'OSKO', 'ry-wc-city-select'),
		_x('Shahrestan-e Sarvabad', 'OSKO', 'ry-wc-city-select'),
	],
	'OSLO' => [
		_x('Delfan', 'OSLO', 'ry-wc-city-select'),
		_x('Dorud', 'OSLO', 'ry-wc-city-select'),
		_x('Pol-e Dokhtar', 'OSLO', 'ry-wc-city-select'),
		_x('Rumeshkhan County', 'OSLO', 'ry-wc-city-select'),
		_x('Selseleh', 'OSLO', 'ry-wc-city-select'),
		_x('Shahrestan-e Aligudarz', 'OSLO', 'ry-wc-city-select'),
		_x('Shahrestan-e Azna', 'OSLO', 'ry-wc-city-select'),
		_x('Shahrestan-e Borujerd', 'OSLO', 'ry-wc-city-select'),
		_x('Shahrestan-e Dureh', 'OSLO', 'ry-wc-city-select'),
		_x('Shahrestan-e Khorramabad', 'OSLO', 'ry-wc-city-select'),
		_x('Shahrestan-e Kuhdasht', 'OSLO', 'ry-wc-city-select'),
	],
	'OSMA' => [
		_x('Khomeyn', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Arak', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Ashtian', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Delijan', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Farahan', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Khondab', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Komijan', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Mahallat', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Saveh', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Shazand', 'OSMA', 'ry-wc-city-select'),
		_x('Shahrestan-e Zarandiyeh', 'OSMA', 'ry-wc-city-select'),
		_x('Tafresh', 'OSMA', 'ry-wc-city-select'),
	],
	'OSMA2' => [
		_x('Behshahr', 'OSMA2', 'ry-wc-city-select'),
		_x('Nowshahr', 'OSMA2', 'ry-wc-city-select'),
		_x('Savadkuh-e Shomali', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Abbasabad', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Amol', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Babol', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Babolsar', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Chalus', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Fareydunkenar', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Galugah', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Juybar', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Kalar Dasht', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Mahmudabad', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Miandorud', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Neka', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Nur', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Qaem Shahr', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Ramsar', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Sari', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Savadkuh', 'OSMA2', 'ry-wc-city-select'),
		_x('Shahrestan-e Tonekabon', 'OSMA2', 'ry-wc-city-select'),
		_x('Simorgh County', 'OSMA2', 'ry-wc-city-select'),
	],
	'OSQA' => [
		_x('Abyek', 'OSQA', 'ry-wc-city-select'),
		_x('Alborz', 'OSQA', 'ry-wc-city-select'),
		_x('Avaj', 'OSQA', 'ry-wc-city-select'),
		_x('Shahrestan-e Buin Zahra', 'OSQA', 'ry-wc-city-select'),
		_x('Shahrestan-e Qazvin', 'OSQA', 'ry-wc-city-select'),
		_x('Shahrestan-e Takestan', 'OSQA', 'ry-wc-city-select'),
	],
	'OSTE' => [
		_x('Pardis', 'OSTE', 'ry-wc-city-select'),
		_x('Qarchak', 'OSTE', 'ry-wc-city-select'),
		_x('Qods', 'OSTE', 'ry-wc-city-select'),
		_x('Rey', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Baharestan', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Damavand', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Eslamshahr', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Firuzkuh', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Malard', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Pakdasht', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Pishva', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Robat Karim', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Shahriar', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Shemiranat', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Tehran', 'OSTE', 'ry-wc-city-select'),
		_x('Shahrestan-e Varamin', 'OSTE', 'ry-wc-city-select'),
	],
	'OSZA' => [
		_x('Abhar', 'OSZA', 'ry-wc-city-select'),
		_x('Khorramdarreh', 'OSZA', 'ry-wc-city-select'),
		_x('Shahrestan-e Ijrud', 'OSZA', 'ry-wc-city-select'),
		_x('Shahrestan-e Khodabandeh', 'OSZA', 'ry-wc-city-select'),
		_x('Shahrestan-e Mahneshan', 'OSZA', 'ry-wc-city-select'),
		_x('Shahrestan-e Tarom', 'OSZA', 'ry-wc-city-select'),
		_x('Shahrestan-e Zanjan', 'OSZA', 'ry-wc-city-select'),
		_x('Soltaniyeh', 'OSZA', 'ry-wc-city-select'),
	],
	'QO' => [
		_x('Qom', 'QO', 'ry-wc-city-select'),
	],
	'SEPR' => [
		_x('Shahrestan-e Aradan', 'SEPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Damghan', 'SEPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Garmsar', 'SEPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Mayamey', 'SEPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Semnan', 'SEPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Shahrud', 'SEPR', 'ry-wc-city-select'),
		_x('Sorkheh', 'SEPR', 'ry-wc-city-select'),
	],
	'SIANBA' => [
		_x('Fanuj', 'SIANBA', 'ry-wc-city-select'),
		_x('Hamoon', 'SIANBA', 'ry-wc-city-select'),
		_x('Mirjaveh', 'SIANBA', 'ry-wc-city-select'),
		_x('Nimruz', 'SIANBA', 'ry-wc-city-select'),
		_x('Qaser-e Qand', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Chabahar', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Dalgan', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Hirmand', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Iranshahr', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Khash', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Konarak', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Mehrestan', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Nikshahr', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Saravan', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Sarbaz', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Sib va Suran', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Zabol', 'SIANBA', 'ry-wc-city-select'),
		_x('Shahrestan-e Zahedan', 'SIANBA', 'ry-wc-city-select'),
		_x('Zehak', 'SIANBA', 'ry-wc-city-select'),
	],
	'WEAZPR' => [
		_x('Chaypareh', 'WEAZPR', 'ry-wc-city-select'),
		_x('Khowy', 'WEAZPR', 'ry-wc-city-select'),
		_x('Naqadeh', 'WEAZPR', 'ry-wc-city-select'),
		_x('Poldasht', 'WEAZPR', 'ry-wc-city-select'),
		_x('Sardasht', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Bukan', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Chaldoran', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Mahabad', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Maku', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Miandoab', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Orumiyeh', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Oshnaviyeh', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Piranshahr', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Salmas', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Shahin Dezh', 'WEAZPR', 'ry-wc-city-select'),
		_x('Shahrestan-e Takab', 'WEAZPR', 'ry-wc-city-select'),
		_x('Showt', 'WEAZPR', 'ry-wc-city-select'),
	],
	'YA' => [
		_x('Meybod', 'YA', 'ry-wc-city-select'),
		_x('Shahrestan-e Abarkuh', 'YA', 'ry-wc-city-select'),
		_x('Shahrestan-e Ardakan', 'YA', 'ry-wc-city-select'),
		_x('Shahrestan-e Ashkezar', 'YA', 'ry-wc-city-select'),
		_x('Shahrestan-e Bafq', 'YA', 'ry-wc-city-select'),
		_x('Shahrestan-e Behabad', 'YA', 'ry-wc-city-select'),
		_x('Shahrestan-e Khatam', 'YA', 'ry-wc-city-select'),
		_x('Shahrestan-e Mehriz', 'YA', 'ry-wc-city-select'),
		_x('Shahrestan-e Yazd', 'YA', 'ry-wc-city-select'),
		_x('Taft', 'YA', 'ry-wc-city-select'),
	],
	]
];