<?php
/**
 * Jamaica places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'JM' => [
	'CL' => [
		_x('Aenon Town', 'CL', 'ry-wc-city-select'),
		_x('Alley', 'CL', 'ry-wc-city-select'),
		_x('Alston', 'CL', 'ry-wc-city-select'),
		_x('Ashley', 'CL', 'ry-wc-city-select'),
		_x('Banks', 'CL', 'ry-wc-city-select'),
		_x('Beckford Kraal', 'CL', 'ry-wc-city-select'),
		_x('Brandon Hill', 'CL', 'ry-wc-city-select'),
		_x('Brixton Hill', 'CL', 'ry-wc-city-select'),
		_x('Bucknor', 'CL', 'ry-wc-city-select'),
		_x('Bucks Common', 'CL', 'ry-wc-city-select'),
		_x('Bushy Park', 'CL', 'ry-wc-city-select'),
		_x('Chapelton', 'CL', 'ry-wc-city-select'),
		_x('Chateau', 'CL', 'ry-wc-city-select'),
		_x('Cockpit', 'CL', 'ry-wc-city-select'),
		_x('Coffee Piece', 'CL', 'ry-wc-city-select'),
		_x('Colonels Ridge', 'CL', 'ry-wc-city-select'),
		_x('Coxswain', 'CL', 'ry-wc-city-select'),
		_x('Crofts Hill', 'CL', 'ry-wc-city-select'),
		_x('Crooked River', 'CL', 'ry-wc-city-select'),
		_x('Cumberland', 'CL', 'ry-wc-city-select'),
		_x('Curatoe Hill', 'CL', 'ry-wc-city-select'),
		_x('Dawkins', 'CL', 'ry-wc-city-select'),
		_x('Effortville', 'CL', 'ry-wc-city-select'),
		_x('Four Paths', 'CL', 'ry-wc-city-select'),
		_x('Frankfield', 'CL', 'ry-wc-city-select'),
		_x('Freetown', 'CL', 'ry-wc-city-select'),
		_x('Gimme-me-bit', 'CL', 'ry-wc-city-select'),
		_x('Glenmuir', 'CL', 'ry-wc-city-select'),
		_x('Grantham', 'CL', 'ry-wc-city-select'),
		_x('Gravel Hill', 'CL', 'ry-wc-city-select'),
		_x('Hayes', 'CL', 'ry-wc-city-select'),
		_x('Hazard', 'CL', 'ry-wc-city-select'),
		_x('Inverness', 'CL', 'ry-wc-city-select'),
		_x('James Hill', 'CL', 'ry-wc-city-select'),
		_x('Johns Hall', 'CL', 'ry-wc-city-select'),
		_x('Lionel Town', 'CL', 'ry-wc-city-select'),
		_x('Longville Park', 'CL', 'ry-wc-city-select'),
		_x('Longwood', 'CL', 'ry-wc-city-select'),
		_x('May Pen Proper', 'CL', 'ry-wc-city-select'),
		_x('Milk River', 'CL', 'ry-wc-city-select'),
		_x('Mineral Heights', 'CL', 'ry-wc-city-select'),
		_x('Mitchell Town', 'CL', 'ry-wc-city-select'),
		_x('Moores', 'CL', 'ry-wc-city-select'),
		_x('Morgans Forest', 'CL', 'ry-wc-city-select'),
		_x('Morgans Pass', 'CL', 'ry-wc-city-select'),
		_x('Mount Airy', 'CL', 'ry-wc-city-select'),
		_x('New Denbigh', 'CL', 'ry-wc-city-select'),
		_x('New Longsville', 'CL', 'ry-wc-city-select'),
		_x('Old Denbigh', 'CL', 'ry-wc-city-select'),
		_x('Orange Hill', 'CL', 'ry-wc-city-select'),
		_x('Osbourne Store', 'CL', 'ry-wc-city-select'),
		_x('Paisley', 'CL', 'ry-wc-city-select'),
		_x('Palmers Cross', 'CL', 'ry-wc-city-select'),
		_x('Part of Banana Ground', 'CL', 'ry-wc-city-select'),
		_x('Part of Douglas Castle', 'CL', 'ry-wc-city-select'),
		_x('Part of Kellits', 'CL', 'ry-wc-city-select'),
		_x('Peckham', 'CL', 'ry-wc-city-select'),
		_x('Pennants', 'CL', 'ry-wc-city-select'),
		_x('Pleasant Valley', 'CL', 'ry-wc-city-select'),
		_x('Portland Cottage', 'CL', 'ry-wc-city-select'),
		_x('Porus', 'CL', 'ry-wc-city-select'),
		_x('Race Course', 'CL', 'ry-wc-city-select'),
		_x('Richmond Park', 'CL', 'ry-wc-city-select'),
		_x('Ritchies', 'CL', 'ry-wc-city-select'),
		_x('Rock', 'CL', 'ry-wc-city-select'),
		_x('Rock River', 'CL', 'ry-wc-city-select'),
		_x('Rocky Point', 'CL', 'ry-wc-city-select'),
		_x('Salt River', 'CL', 'ry-wc-city-select'),
		_x('Sandy Bay', 'CL', 'ry-wc-city-select'),
		_x('Sanguinetti', 'CL', 'ry-wc-city-select'),
		_x('Sedgepond', 'CL', 'ry-wc-city-select'),
		_x('Silent Hill', 'CL', 'ry-wc-city-select'),
		_x('Smithville', 'CL', 'ry-wc-city-select'),
		_x('Spaldings', 'CL', 'ry-wc-city-select'),
		_x('Summerfield', 'CL', 'ry-wc-city-select'),
		_x('Thompson Town', 'CL', 'ry-wc-city-select'),
		_x('Tollgate', 'CL', 'ry-wc-city-select'),
		_x('Treadlight', 'CL', 'ry-wc-city-select'),
		_x('Trout Hall', 'CL', 'ry-wc-city-select'),
		_x('Turners', 'CL', 'ry-wc-city-select'),
		_x('Water Lane', 'CL', 'ry-wc-city-select'),
		_x('Woodhall', 'CL', 'ry-wc-city-select'),
		_x('York Town', 'CL', 'ry-wc-city-select'),
	],
	'KI' => [
		_x('Allman Town', 'KI', 'ry-wc-city-select'),
		_x('Bournemouth Gardens', 'KI', 'ry-wc-city-select'),
		_x('Campbell Town', 'KI', 'ry-wc-city-select'),
		_x('Central Down Town', 'KI', 'ry-wc-city-select'),
		_x('DAguilar Town/ Rennock Lodge', 'KI', 'ry-wc-city-select'),
		_x('Denham Town', 'KI', 'ry-wc-city-select'),
		_x('East Down Town', 'KI', 'ry-wc-city-select'),
		_x('Fletchers Land', 'KI', 'ry-wc-city-select'),
		_x('Franklyn Town', 'KI', 'ry-wc-city-select'),
		_x('Hannah Town/ Craig Town', 'KI', 'ry-wc-city-select'),
		_x('Johnson Town', 'KI', 'ry-wc-city-select'),
		_x('Kingston Gardens', 'KI', 'ry-wc-city-select'),
		_x('Manley Meadows', 'KI', 'ry-wc-city-select'),
		_x('Newport East', 'KI', 'ry-wc-city-select'),
		_x('Newton Square', 'KI', 'ry-wc-city-select'),
		_x('Norman Gardens', 'KI', 'ry-wc-city-select'),
		_x('Passmore Town', 'KI', 'ry-wc-city-select'),
		_x('Port Royal', 'KI', 'ry-wc-city-select'),
		_x('Rae Town', 'KI', 'ry-wc-city-select'),
		_x('Rollington Town', 'KI', 'ry-wc-city-select'),
		_x('Southside', 'KI', 'ry-wc-city-select'),
		_x('Springfield', 'KI', 'ry-wc-city-select'),
		_x('Tivoli Gardens', 'KI', 'ry-wc-city-select'),
		_x('West Down Town', 'KI', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Alligator Pond', 'MA', 'ry-wc-city-select'),
		_x('Asia/Pratville', 'MA', 'ry-wc-city-select'),
		_x('Auchtembeddie', 'MA', 'ry-wc-city-select'),
		_x('Bellefield', 'MA', 'ry-wc-city-select'),
		_x('Bethany', 'MA', 'ry-wc-city-select'),
		_x('Blue Mountain', 'MA', 'ry-wc-city-select'),
		_x('Bombay', 'MA', 'ry-wc-city-select'),
		_x('Butt-Up', 'MA', 'ry-wc-city-select'),
		_x('Cedar Grove', 'MA', 'ry-wc-city-select'),
		_x('Chantilly', 'MA', 'ry-wc-city-select'),
		_x('Christiana', 'MA', 'ry-wc-city-select'),
		_x('Chudleigh', 'MA', 'ry-wc-city-select'),
		_x('Cobbla', 'MA', 'ry-wc-city-select'),
		_x('Coleyville', 'MA', 'ry-wc-city-select'),
		_x('Comfort', 'MA', 'ry-wc-city-select'),
		_x('Comfort Hall', 'MA', 'ry-wc-city-select'),
		_x('Content', 'MA', 'ry-wc-city-select'),
		_x('Craig Head', 'MA', 'ry-wc-city-select'),
		_x('Cross Keys', 'MA', 'ry-wc-city-select'),
		_x('Devon', 'MA', 'ry-wc-city-select'),
		_x('Downs', 'MA', 'ry-wc-city-select'),
		_x('Ellen Street', 'MA', 'ry-wc-city-select'),
		_x('Evergreen', 'MA', 'ry-wc-city-select'),
		_x('Fairfield', 'MA', 'ry-wc-city-select'),
		_x('French Park', 'MA', 'ry-wc-city-select'),
		_x('Georges Valley', 'MA', 'ry-wc-city-select'),
		_x('Good Intent', 'MA', 'ry-wc-city-select'),
		_x('Greenvale', 'MA', 'ry-wc-city-select'),
		_x('Grove Place', 'MA', 'ry-wc-city-select'),
		_x('Grove Town', 'MA', 'ry-wc-city-select'),
		_x('Harmons', 'MA', 'ry-wc-city-select'),
		_x('Harry Watch', 'MA', 'ry-wc-city-select'),
		_x('Hatfield', 'MA', 'ry-wc-city-select'),
		_x('Heartease', 'MA', 'ry-wc-city-select'),
		_x('Hibernia', 'MA', 'ry-wc-city-select'),
		_x('Huntley', 'MA', 'ry-wc-city-select'),
		_x('Kendal', 'MA', 'ry-wc-city-select'),
		_x('Knockpatrick', 'MA', 'ry-wc-city-select'),
		_x('Lancaster', 'MA', 'ry-wc-city-select'),
		_x('Litchfield', 'MA', 'ry-wc-city-select'),
		_x('Maidstone', 'MA', 'ry-wc-city-select'),
		_x('Mandeville Proper', 'MA', 'ry-wc-city-select'),
		_x('Marlie Hill', 'MA', 'ry-wc-city-select'),
		_x('May Day', 'MA', 'ry-wc-city-select'),
		_x('Medina', 'MA', 'ry-wc-city-select'),
		_x('Mike Town', 'MA', 'ry-wc-city-select'),
		_x('Mile Gully', 'MA', 'ry-wc-city-select'),
		_x('New Forest', 'MA', 'ry-wc-city-select'),
		_x('New Green', 'MA', 'ry-wc-city-select'),
		_x('Newport', 'MA', 'ry-wc-city-select'),
		_x('Old England', 'MA', 'ry-wc-city-select'),
		_x('Part Of Banana Ground', 'MA', 'ry-wc-city-select'),
		_x('Part Of Gutters', 'MA', 'ry-wc-city-select'),
		_x('Part of Spaldings', 'MA', 'ry-wc-city-select'),
		_x('Pike', 'MA', 'ry-wc-city-select'),
		_x('Plowden', 'MA', 'ry-wc-city-select'),
		_x('Porus', 'MA', 'ry-wc-city-select'),
		_x('Prospect', 'MA', 'ry-wc-city-select'),
		_x('Richmond', 'MA', 'ry-wc-city-select'),
		_x('Robins Hall', 'MA', 'ry-wc-city-select'),
		_x('Rose Hill', 'MA', 'ry-wc-city-select'),
		_x('Royal Flat', 'MA', 'ry-wc-city-select'),
		_x('Scotts Pass', 'MA', 'ry-wc-city-select'),
		_x('Snowdon', 'MA', 'ry-wc-city-select'),
		_x('Somerset', 'MA', 'ry-wc-city-select'),
		_x('Spring Ground', 'MA', 'ry-wc-city-select'),
		_x('Spur Tree', 'MA', 'ry-wc-city-select'),
		_x('St. Pauls', 'MA', 'ry-wc-city-select'),
		_x('Swabys Hope', 'MA', 'ry-wc-city-select'),
		_x('Top Hill', 'MA', 'ry-wc-city-select'),
		_x('Victoria Town', 'MA', 'ry-wc-city-select'),
		_x('Walderston', 'MA', 'ry-wc-city-select'),
		_x('Watham', 'MA', 'ry-wc-city-select'),
		_x('Williamsfield', 'MA', 'ry-wc-city-select'),
	],
	'PAHA' => [
		_x('Askenish', 'PAHA', 'ry-wc-city-select'),
		_x('Cacoon', 'PAHA', 'ry-wc-city-select'),
		_x('Cacoon Castle', 'PAHA', 'ry-wc-city-select'),
		_x('Cascade', 'PAHA', 'ry-wc-city-select'),
		_x('Cash Hill', 'PAHA', 'ry-wc-city-select'),
		_x('Cauldwell', 'PAHA', 'ry-wc-city-select'),
		_x('Chambers Pen', 'PAHA', 'ry-wc-city-select'),
		_x('Chester Castle', 'PAHA', 'ry-wc-city-select'),
		_x('Copse', 'PAHA', 'ry-wc-city-select'),
		_x('Cousins Cove', 'PAHA', 'ry-wc-city-select'),
		_x('Dias', 'PAHA', 'ry-wc-city-select'),
		_x('Great Valley', 'PAHA', 'ry-wc-city-select'),
		_x('Green Island', 'PAHA', 'ry-wc-city-select'),
		_x('Haddington', 'PAHA', 'ry-wc-city-select'),
		_x('Hopewell', 'PAHA', 'ry-wc-city-select'),
		_x('Jericho', 'PAHA', 'ry-wc-city-select'),
		_x('Kendal', 'PAHA', 'ry-wc-city-select'),
		_x('Kingsvale', 'PAHA', 'ry-wc-city-select'),
		_x('Lances Bay', 'PAHA', 'ry-wc-city-select'),
		_x('Logwood', 'PAHA', 'ry-wc-city-select'),
		_x('Lucea East', 'PAHA', 'ry-wc-city-select'),
		_x('Lucea West', 'PAHA', 'ry-wc-city-select'),
		_x('March Town', 'PAHA', 'ry-wc-city-select'),
		_x('Maryland', 'PAHA', 'ry-wc-city-select'),
		_x('Mount Peto', 'PAHA', 'ry-wc-city-select'),
		_x('Orange Bay', 'PAHA', 'ry-wc-city-select'),
		_x('Pell River', 'PAHA', 'ry-wc-city-select'),
		_x('Pondside', 'PAHA', 'ry-wc-city-select'),
		_x('Ramble', 'PAHA', 'ry-wc-city-select'),
		_x('Rock Spring', 'PAHA', 'ry-wc-city-select'),
		_x('Sandy Bay', 'PAHA', 'ry-wc-city-select'),
		_x('Santoy', 'PAHA', 'ry-wc-city-select'),
		_x('Success', 'PAHA', 'ry-wc-city-select'),
		_x('Woodlands', 'PAHA', 'ry-wc-city-select'),
		_x('Woodsville', 'PAHA', 'ry-wc-city-select'),
	],
	'PASAAN' => [
		_x('Aboukir', 'PASAAN', 'ry-wc-city-select'),
		_x('Alderton', 'PASAAN', 'ry-wc-city-select'),
		_x('Alexandria', 'PASAAN', 'ry-wc-city-select'),
		_x('Alva', 'PASAAN', 'ry-wc-city-select'),
		_x('Bamboo', 'PASAAN', 'ry-wc-city-select'),
		_x('Beecher Town', 'PASAAN', 'ry-wc-city-select'),
		_x('Bensonton', 'PASAAN', 'ry-wc-city-select'),
		_x('Blackstonedge', 'PASAAN', 'ry-wc-city-select'),
		_x('Bohemia', 'PASAAN', 'ry-wc-city-select'),
		_x('Borobridge', 'PASAAN', 'ry-wc-city-select'),
		_x('Browns Town', 'PASAAN', 'ry-wc-city-select'),
		_x('Calderwood', 'PASAAN', 'ry-wc-city-select'),
		_x('Cascade', 'PASAAN', 'ry-wc-city-select'),
		_x('Cave Valley', 'PASAAN', 'ry-wc-city-select'),
		_x('Chalky Hill', 'PASAAN', 'ry-wc-city-select'),
		_x('Chester', 'PASAAN', 'ry-wc-city-select'),
		_x('Claremont', 'PASAAN', 'ry-wc-city-select'),
		_x('Cole Gate', 'PASAAN', 'ry-wc-city-select'),
		_x('Content Garden', 'PASAAN', 'ry-wc-city-select'),
		_x('Cuffie Ridge', 'PASAAN', 'ry-wc-city-select'),
		_x('Discovery Bay', 'PASAAN', 'ry-wc-city-select'),
		_x('Epworth', 'PASAAN', 'ry-wc-city-select'),
		_x('Exchange', 'PASAAN', 'ry-wc-city-select'),
		_x('Faiths Pen', 'PASAAN', 'ry-wc-city-select'),
		_x('Gibraltar', 'PASAAN', 'ry-wc-city-select'),
		_x('Gibraltar', 'PASAAN', 'ry-wc-city-select'),
		_x('Golden Grove', 'PASAAN', 'ry-wc-city-select'),
		_x('Great Pond', 'PASAAN', 'ry-wc-city-select'),
		_x('Higgin Land', 'PASAAN', 'ry-wc-city-select'),
		_x('Hinds Town', 'PASAAN', 'ry-wc-city-select'),
		_x('Inverness', 'PASAAN', 'ry-wc-city-select'),
		_x('Lime Hall', 'PASAAN', 'ry-wc-city-select'),
		_x('Lime Tree Gardens', 'PASAAN', 'ry-wc-city-select'),
		_x('Linton Park', 'PASAAN', 'ry-wc-city-select'),
		_x('Macknie', 'PASAAN', 'ry-wc-city-select'),
		_x('Madras', 'PASAAN', 'ry-wc-city-select'),
		_x('Mansfield', 'PASAAN', 'ry-wc-city-select'),
		_x('Moneague', 'PASAAN', 'ry-wc-city-select'),
		_x('Mount Moriah', 'PASAAN', 'ry-wc-city-select'),
		_x('Mount Zion', 'PASAAN', 'ry-wc-city-select'),
		_x('Ocho Rios', 'PASAAN', 'ry-wc-city-select'),
		_x('Parry Town', 'PASAAN', 'ry-wc-city-select'),
		_x('Philadelphia', 'PASAAN', 'ry-wc-city-select'),
		_x('Pimento Walk', 'PASAAN', 'ry-wc-city-select'),
		_x('Priory', 'PASAAN', 'ry-wc-city-select'),
		_x('River Head', 'PASAAN', 'ry-wc-city-select'),
		_x('Runaway Bay', 'PASAAN', 'ry-wc-city-select'),
		_x('St. Anns Bay', 'PASAAN', 'ry-wc-city-select'),
		_x('St. DAcre', 'PASAAN', 'ry-wc-city-select'),
		_x('Steer Town', 'PASAAN', 'ry-wc-city-select'),
		_x('Sturge Town', 'PASAAN', 'ry-wc-city-select'),
		_x('Walkers Wood', 'PASAAN', 'ry-wc-city-select'),
		_x('Watt Town', 'PASAAN', 'ry-wc-city-select'),
		_x('York Castle', 'PASAAN', 'ry-wc-city-select'),
	],
	'PO' => [
		_x('Balcarres', 'PO', 'ry-wc-city-select'),
		_x('Bangor Ridge', 'PO', 'ry-wc-city-select'),
		_x('Belvedere', 'PO', 'ry-wc-city-select'),
		_x('Black Hill', 'PO', 'ry-wc-city-select'),
		_x('Boundbrook', 'PO', 'ry-wc-city-select'),
		_x('Breastworks', 'PO', 'ry-wc-city-select'),
		_x('Buff Bay', 'PO', 'ry-wc-city-select'),
		_x('Bybrook', 'PO', 'ry-wc-city-select'),
		_x('Cascade', 'PO', 'ry-wc-city-select'),
		_x('Castle Comfort', 'PO', 'ry-wc-city-select'),
		_x('Central Port Antonio', 'PO', 'ry-wc-city-select'),
		_x('Charles Town', 'PO', 'ry-wc-city-select'),
		_x('Claverty Cottage', 'PO', 'ry-wc-city-select'),
		_x('Comfort Castle', 'PO', 'ry-wc-city-select'),
		_x('Drapers', 'PO', 'ry-wc-city-select'),
		_x('Durham', 'PO', 'ry-wc-city-select'),
		_x('Fairy Hill', 'PO', 'ry-wc-city-select'),
		_x('Fellowship', 'PO', 'ry-wc-city-select'),
		_x('Fruitfulvale', 'PO', 'ry-wc-city-select'),
		_x('Hectors River', 'PO', 'ry-wc-city-select'),
		_x('Hope Bay', 'PO', 'ry-wc-city-select'),
		_x('Kensington', 'PO', 'ry-wc-city-select'),
		_x('Long Bay', 'PO', 'ry-wc-city-select'),
		_x('Long Road', 'PO', 'ry-wc-city-select'),
		_x('Manchioneal', 'PO', 'ry-wc-city-select'),
		_x('Moore Town', 'PO', 'ry-wc-city-select'),
		_x('Mount Pleasant', 'PO', 'ry-wc-city-select'),
		_x('Nonsuch', 'PO', 'ry-wc-city-select'),
		_x('Norwich', 'PO', 'ry-wc-city-select'),
		_x('Orange Bay', 'PO', 'ry-wc-city-select'),
		_x('Prospect', 'PO', 'ry-wc-city-select'),
		_x('Rock Hall', 'PO', 'ry-wc-city-select'),
		_x('Sherwood Forest', 'PO', 'ry-wc-city-select'),
		_x('Shirley Castle', 'PO', 'ry-wc-city-select'),
		_x('Skibo', 'PO', 'ry-wc-city-select'),
		_x('Snow Hill', 'PO', 'ry-wc-city-select'),
		_x('Spring Hill', 'PO', 'ry-wc-city-select'),
		_x('St. Margarets Bay', 'PO', 'ry-wc-city-select'),
		_x('Swift River', 'PO', 'ry-wc-city-select'),
		_x('Tranquility', 'PO', 'ry-wc-city-select'),
		_x('Windsor', 'PO', 'ry-wc-city-select'),
		_x('Windsor Castle', 'PO', 'ry-wc-city-select'),
		_x('Windsor Forest', 'PO', 'ry-wc-city-select'),
	],
	'SAAN' => [
		_x('Arcadia', 'SAAN', 'ry-wc-city-select'),
		_x('Arlene Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Arnett Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('August Town', 'SAAN', 'ry-wc-city-select'),
		_x('Barbican', 'SAAN', 'ry-wc-city-select'),
		_x('Beverley Hills', 'SAAN', 'ry-wc-city-select'),
		_x('Bito', 'SAAN', 'ry-wc-city-select'),
		_x('Bloxborough', 'SAAN', 'ry-wc-city-select'),
		_x('Boucher Park', 'SAAN', 'ry-wc-city-select'),
		_x('Brandon Hill', 'SAAN', 'ry-wc-city-select'),
		_x('Bull Bay/ Seven Mile', 'SAAN', 'ry-wc-city-select'),
		_x('Cane River', 'SAAN', 'ry-wc-city-select'),
		_x('Cassia Park', 'SAAN', 'ry-wc-city-select'),
		_x('Cavaliers', 'SAAN', 'ry-wc-city-select'),
		_x('Cherry Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Cockburn Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Constant Spring', 'SAAN', 'ry-wc-city-select'),
		_x('Constant Spring Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Constitution Hill', 'SAAN', 'ry-wc-city-select'),
		_x('Content Gap', 'SAAN', 'ry-wc-city-select'),
		_x('Cooreville Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Cross Roads', 'SAAN', 'ry-wc-city-select'),
		_x('Dallas', 'SAAN', 'ry-wc-city-select'),
		_x('Delacree Park/ Union Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Delacree Pen', 'SAAN', 'ry-wc-city-select'),
		_x('Drewsland', 'SAAN', 'ry-wc-city-select'),
		_x('Drumblair', 'SAAN', 'ry-wc-city-select'),
		_x('Duhaney Park', 'SAAN', 'ry-wc-city-select'),
		_x('Eastwood Park Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Elleston Flats/ Mona Commons', 'SAAN', 'ry-wc-city-select'),
		_x('Ferry', 'SAAN', 'ry-wc-city-select'),
		_x('Forest Hills Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Forest Hills/ Plantation Height', 'SAAN', 'ry-wc-city-select'),
		_x('Golden Spring', 'SAAN', 'ry-wc-city-select'),
		_x('Gordon Town', 'SAAN', 'ry-wc-city-select'),
		_x('Grants Pen', 'SAAN', 'ry-wc-city-select'),
		_x('Greenwich Town/ Newport West', 'SAAN', 'ry-wc-city-select'),
		_x('Half-Way-Tree', 'SAAN', 'ry-wc-city-select'),
		_x('Harbour View', 'SAAN', 'ry-wc-city-select'),
		_x('Havendale', 'SAAN', 'ry-wc-city-select'),
		_x('Hermitage', 'SAAN', 'ry-wc-city-select'),
		_x('Hope Pastures/ UTECH', 'SAAN', 'ry-wc-city-select'),
		_x('Hope Tavern', 'SAAN', 'ry-wc-city-select'),
		_x('Hughenden', 'SAAN', 'ry-wc-city-select'),
		_x('Irish Town', 'SAAN', 'ry-wc-city-select'),
		_x('Jacks Hill', 'SAAN', 'ry-wc-city-select'),
		_x('Jones Town', 'SAAN', 'ry-wc-city-select'),
		_x('Kencot', 'SAAN', 'ry-wc-city-select'),
		_x('Kintyre', 'SAAN', 'ry-wc-city-select'),
		_x('Lawrence Tavern', 'SAAN', 'ry-wc-city-select'),
		_x('Liguanea', 'SAAN', 'ry-wc-city-select'),
		_x('Majestic Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Mannings Hill', 'SAAN', 'ry-wc-city-select'),
		_x('Mannings Hill (Rural)', 'SAAN', 'ry-wc-city-select'),
		_x('Marverley', 'SAAN', 'ry-wc-city-select'),
		_x('Maryland', 'SAAN', 'ry-wc-city-select'),
		_x('Mavis Bank', 'SAAN', 'ry-wc-city-select'),
		_x('Maxfield Park', 'SAAN', 'ry-wc-city-select'),
		_x('Meadowbrook', 'SAAN', 'ry-wc-city-select'),
		_x('Meadowbrook Estate', 'SAAN', 'ry-wc-city-select'),
		_x('Molynes Four Roads', 'SAAN', 'ry-wc-city-select'),
		_x('Molynes Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Mona Heights', 'SAAN', 'ry-wc-city-select'),
		_x('Mount James', 'SAAN', 'ry-wc-city-select'),
		_x('Mountain View Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Nannyville', 'SAAN', 'ry-wc-city-select'),
		_x('New Haven', 'SAAN', 'ry-wc-city-select'),
		_x('New Kingston', 'SAAN', 'ry-wc-city-select'),
		_x('Norbrook', 'SAAN', 'ry-wc-city-select'),
		_x('Oaklands', 'SAAN', 'ry-wc-city-select'),
		_x('Papine', 'SAAN', 'ry-wc-city-select'),
		_x('Parks Road', 'SAAN', 'ry-wc-city-select'),
		_x('Patrick City', 'SAAN', 'ry-wc-city-select'),
		_x('Pembroke Hall', 'SAAN', 'ry-wc-city-select'),
		_x('Penwood', 'SAAN', 'ry-wc-city-select'),
		_x('Queensborough/ Tunbridge', 'SAAN', 'ry-wc-city-select'),
		_x('Red Hills (Rural)', 'SAAN', 'ry-wc-city-select'),
		_x('Red Hills Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Red Hills/ Sterling Castle', 'SAAN', 'ry-wc-city-select'),
		_x('Richmond Park', 'SAAN', 'ry-wc-city-select'),
		_x('Riverton City', 'SAAN', 'ry-wc-city-select'),
		_x('Roehampton', 'SAAN', 'ry-wc-city-select'),
		_x('Rose Town', 'SAAN', 'ry-wc-city-select'),
		_x('Seaview Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Seaward Pen', 'SAAN', 'ry-wc-city-select'),
		_x('Seymour Lands', 'SAAN', 'ry-wc-city-select'),
		_x('St. Peters', 'SAAN', 'ry-wc-city-select'),
		_x('Stadium Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Stony Hill', 'SAAN', 'ry-wc-city-select'),
		_x('Swallowfield', 'SAAN', 'ry-wc-city-select'),
		_x('Temple Hall', 'SAAN', 'ry-wc-city-select'),
		_x('Three Oaks/ Glendale', 'SAAN', 'ry-wc-city-select'),
		_x('Tower Hill', 'SAAN', 'ry-wc-city-select'),
		_x('Trafalgar Park', 'SAAN', 'ry-wc-city-select'),
		_x('Trench Town', 'SAAN', 'ry-wc-city-select'),
		_x('University', 'SAAN', 'ry-wc-city-select'),
		_x('Vineyard Town', 'SAAN', 'ry-wc-city-select'),
		_x('Waltham Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Washington Gardens', 'SAAN', 'ry-wc-city-select'),
		_x('Waterhouse', 'SAAN', 'ry-wc-city-select'),
		_x('Whitehall', 'SAAN', 'ry-wc-city-select'),
		_x('Whitfield Town', 'SAAN', 'ry-wc-city-select'),
		_x('Wilton Gardens/ Rema', 'SAAN', 'ry-wc-city-select'),
		_x('Woodford', 'SAAN', 'ry-wc-city-select'),
		_x('Woodford Park', 'SAAN', 'ry-wc-city-select'),
		_x('Zaidie Gardens', 'SAAN', 'ry-wc-city-select'),
	],
	'SACA' => [
		_x('Above Rocks', 'SACA', 'ry-wc-city-select'),
		_x('Bartons', 'SACA', 'ry-wc-city-select'),
		_x('Bellas Gate', 'SACA', 'ry-wc-city-select'),
		_x('Bogwalk', 'SACA', 'ry-wc-city-select'),
		_x('Braeton', 'SACA', 'ry-wc-city-select'),
		_x('Bridgeport', 'SACA', 'ry-wc-city-select'),
		_x('Browns Hill', 'SACA', 'ry-wc-city-select'),
		_x('Caymanas', 'SACA', 'ry-wc-city-select'),
		_x('Central Village', 'SACA', 'ry-wc-city-select'),
		_x('Crescent', 'SACA', 'ry-wc-city-select'),
		_x('Cromarty', 'SACA', 'ry-wc-city-select'),
		_x('Cumberland', 'SACA', 'ry-wc-city-select'),
		_x('Edgewater', 'SACA', 'ry-wc-city-select'),
		_x('Ensom', 'SACA', 'ry-wc-city-select'),
		_x('Ewarton', 'SACA', 'ry-wc-city-select'),
		_x('Ginger Ridge', 'SACA', 'ry-wc-city-select'),
		_x('Glengoffe', 'SACA', 'ry-wc-city-select'),
		_x('Golden Acres', 'SACA', 'ry-wc-city-select'),
		_x('Greater Portmore', 'SACA', 'ry-wc-city-select'),
		_x('Greendale', 'SACA', 'ry-wc-city-select'),
		_x('Gregory Park', 'SACA', 'ry-wc-city-select'),
		_x('Hampton Green', 'SACA', 'ry-wc-city-select'),
		_x('Harewood', 'SACA', 'ry-wc-city-select'),
		_x('Harkers Hall', 'SACA', 'ry-wc-city-select'),
		_x('Hellshire', 'SACA', 'ry-wc-city-select'),
		_x('Independence City', 'SACA', 'ry-wc-city-select'),
		_x('Keystone', 'SACA', 'ry-wc-city-select'),
		_x('Kitson Town', 'SACA', 'ry-wc-city-select'),
		_x('Linstead', 'SACA', 'ry-wc-city-select'),
		_x('Lluidas Vale', 'SACA', 'ry-wc-city-select'),
		_x('Naggo Head', 'SACA', 'ry-wc-city-select'),
		_x('Old Harbour', 'SACA', 'ry-wc-city-select'),
		_x('Old Harbour Bay', 'SACA', 'ry-wc-city-select'),
		_x('Old Harbour Road', 'SACA', 'ry-wc-city-select'),
		_x('Part of Guys Hill', 'SACA', 'ry-wc-city-select'),
		_x('Part of Keystone', 'SACA', 'ry-wc-city-select'),
		_x('Part of Rock Hall', 'SACA', 'ry-wc-city-select'),
		_x('Passage Fort', 'SACA', 'ry-wc-city-select'),
		_x('Pear Tree Grove', 'SACA', 'ry-wc-city-select'),
		_x('Point Hill', 'SACA', 'ry-wc-city-select'),
		_x('Redwood', 'SACA', 'ry-wc-city-select'),
		_x('Riversdale', 'SACA', 'ry-wc-city-select'),
		_x('Sligoville', 'SACA', 'ry-wc-city-select'),
		_x('Spanish Town Central', 'SACA', 'ry-wc-city-select'),
		_x('St. Johns East', 'SACA', 'ry-wc-city-select'),
		_x('St. Johns West', 'SACA', 'ry-wc-city-select'),
		_x('Troja', 'SACA', 'ry-wc-city-select'),
		_x('Waterford', 'SACA', 'ry-wc-city-select'),
		_x('Watermount', 'SACA', 'ry-wc-city-select'),
		_x('West Cumberland', 'SACA', 'ry-wc-city-select'),
		_x('Willowdene', 'SACA', 'ry-wc-city-select'),
	],
	'SAEL' => [
		_x('Aberdeen', 'SAEL', 'ry-wc-city-select'),
		_x('Accompong', 'SAEL', 'ry-wc-city-select'),
		_x('Balaclava', 'SAEL', 'ry-wc-city-select'),
		_x('Ballards  Valley', 'SAEL', 'ry-wc-city-select'),
		_x('Barbary Hall', 'SAEL', 'ry-wc-city-select'),
		_x('Bigwoods', 'SAEL', 'ry-wc-city-select'),
		_x('Black River', 'SAEL', 'ry-wc-city-select'),
		_x('Bogue', 'SAEL', 'ry-wc-city-select'),
		_x('Braes River', 'SAEL', 'ry-wc-city-select'),
		_x('Brighton', 'SAEL', 'ry-wc-city-select'),
		_x('Brompton', 'SAEL', 'ry-wc-city-select'),
		_x('Bull Savannah', 'SAEL', 'ry-wc-city-select'),
		_x('Burnt Savannah', 'SAEL', 'ry-wc-city-select'),
		_x('Carisbrook', 'SAEL', 'ry-wc-city-select'),
		_x('Cotterwood', 'SAEL', 'ry-wc-city-select'),
		_x('Crawford', 'SAEL', 'ry-wc-city-select'),
		_x('Elderslie', 'SAEL', 'ry-wc-city-select'),
		_x('Fullerswood', 'SAEL', 'ry-wc-city-select'),
		_x('Giddy Hall', 'SAEL', 'ry-wc-city-select'),
		_x('Ginger Hill', 'SAEL', 'ry-wc-city-select'),
		_x('Goshen', 'SAEL', 'ry-wc-city-select'),
		_x('Holland', 'SAEL', 'ry-wc-city-select'),
		_x('Hopeton', 'SAEL', 'ry-wc-city-select'),
		_x('Junction', 'SAEL', 'ry-wc-city-select'),
		_x('Lacovia', 'SAEL', 'ry-wc-city-select'),
		_x('Leeds', 'SAEL', 'ry-wc-city-select'),
		_x('Lititz', 'SAEL', 'ry-wc-city-select'),
		_x('Maggotty', 'SAEL', 'ry-wc-city-select'),
		_x('Malvern', 'SAEL', 'ry-wc-city-select'),
		_x('Merrywood', 'SAEL', 'ry-wc-city-select'),
		_x('Middle Quarters', 'SAEL', 'ry-wc-city-select'),
		_x('Mountainside', 'SAEL', 'ry-wc-city-select'),
		_x('Mulgrave', 'SAEL', 'ry-wc-city-select'),
		_x('Myersville', 'SAEL', 'ry-wc-city-select'),
		_x('Nain', 'SAEL', 'ry-wc-city-select'),
		_x('New Market', 'SAEL', 'ry-wc-city-select'),
		_x('Newell', 'SAEL', 'ry-wc-city-select'),
		_x('Newton', 'SAEL', 'ry-wc-city-select'),
		_x('Parottee', 'SAEL', 'ry-wc-city-select'),
		_x('Pedro Plains', 'SAEL', 'ry-wc-city-select'),
		_x('Pepper', 'SAEL', 'ry-wc-city-select'),
		_x('Pisgah', 'SAEL', 'ry-wc-city-select'),
		_x('Pondside', 'SAEL', 'ry-wc-city-select'),
		_x('Potsdam', 'SAEL', 'ry-wc-city-select'),
		_x('Quick Step', 'SAEL', 'ry-wc-city-select'),
		_x('Red Bank', 'SAEL', 'ry-wc-city-select'),
		_x('Retirement', 'SAEL', 'ry-wc-city-select'),
		_x('Rose Hall', 'SAEL', 'ry-wc-city-select'),
		_x('Russels', 'SAEL', 'ry-wc-city-select'),
		_x('Santa Cruz', 'SAEL', 'ry-wc-city-select'),
		_x('Scholefield', 'SAEL', 'ry-wc-city-select'),
		_x('Siloah', 'SAEL', 'ry-wc-city-select'),
		_x('Slipe', 'SAEL', 'ry-wc-city-select'),
		_x('Southfield', 'SAEL', 'ry-wc-city-select'),
		_x('Springfield', 'SAEL', 'ry-wc-city-select'),
		_x('Thornton', 'SAEL', 'ry-wc-city-select'),
		_x('Top Hill', 'SAEL', 'ry-wc-city-select'),
		_x('Treasure Beach', 'SAEL', 'ry-wc-city-select'),
		_x('Warminister', 'SAEL', 'ry-wc-city-select'),
		_x('Watchwell', 'SAEL', 'ry-wc-city-select'),
		_x('White Hill', 'SAEL', 'ry-wc-city-select'),
	],
	'SAJA' => [
		_x('Adelphi', 'SAJA', 'ry-wc-city-select'),
		_x('Albion', 'SAJA', 'ry-wc-city-select'),
		_x('Anchovy', 'SAJA', 'ry-wc-city-select'),
		_x('Arcadia', 'SAJA', 'ry-wc-city-select'),
		_x('Barrett Town', 'SAJA', 'ry-wc-city-select'),
		_x('Bickersteth', 'SAJA', 'ry-wc-city-select'),
		_x('Bogue', 'SAJA', 'ry-wc-city-select'),
		_x('Brandon Hill', 'SAJA', 'ry-wc-city-select'),
		_x('Cambridge', 'SAJA', 'ry-wc-city-select'),
		_x('Canterbury', 'SAJA', 'ry-wc-city-select'),
		_x('Catadupa', 'SAJA', 'ry-wc-city-select'),
		_x('Catherine Hall', 'SAJA', 'ry-wc-city-select'),
		_x('Catherine Mount', 'SAJA', 'ry-wc-city-select'),
		_x('Comfort Hall', 'SAJA', 'ry-wc-city-select'),
		_x('Coral Gardens', 'SAJA', 'ry-wc-city-select'),
		_x('Cornwall', 'SAJA', 'ry-wc-city-select'),
		_x('Down Town Montego Bay', 'SAJA', 'ry-wc-city-select'),
		_x('Dumfries', 'SAJA', 'ry-wc-city-select'),
		_x('Fairfield', 'SAJA', 'ry-wc-city-select'),
		_x('Farm Heights', 'SAJA', 'ry-wc-city-select'),
		_x('Flagstaff', 'SAJA', 'ry-wc-city-select'),
		_x('Flamstead', 'SAJA', 'ry-wc-city-select'),
		_x('Flankers', 'SAJA', 'ry-wc-city-select'),
		_x('Flower Hill', 'SAJA', 'ry-wc-city-select'),
		_x('Friendship', 'SAJA', 'ry-wc-city-select'),
		_x('Garlands', 'SAJA', 'ry-wc-city-select'),
		_x('Glendevon', 'SAJA', 'ry-wc-city-select'),
		_x('Goodwill', 'SAJA', 'ry-wc-city-select'),
		_x('Granville', 'SAJA', 'ry-wc-city-select'),
		_x('Green Pond', 'SAJA', 'ry-wc-city-select'),
		_x('Greenwood', 'SAJA', 'ry-wc-city-select'),
		_x('Hopeton', 'SAJA', 'ry-wc-city-select'),
		_x('Ironshore', 'SAJA', 'ry-wc-city-select'),
		_x('Irwin', 'SAJA', 'ry-wc-city-select'),
		_x('Johns Hall', 'SAJA', 'ry-wc-city-select'),
		_x('Lilliput', 'SAJA', 'ry-wc-city-select'),
		_x('Lottery', 'SAJA', 'ry-wc-city-select'),
		_x('Maldon', 'SAJA', 'ry-wc-city-select'),
		_x('Maroon Town', 'SAJA', 'ry-wc-city-select'),
		_x('Mocho', 'SAJA', 'ry-wc-city-select'),
		_x('Montego Hill', 'SAJA', 'ry-wc-city-select'),
		_x('Montpelier', 'SAJA', 'ry-wc-city-select'),
		_x('Mount Carey', 'SAJA', 'ry-wc-city-select'),
		_x('Mount Horeb', 'SAJA', 'ry-wc-city-select'),
		_x('Mount Salem', 'SAJA', 'ry-wc-city-select'),
		_x('Niagara', 'SAJA', 'ry-wc-city-select'),
		_x('Norwood', 'SAJA', 'ry-wc-city-select'),
		_x('Orange', 'SAJA', 'ry-wc-city-select'),
		_x('Paradise', 'SAJA', 'ry-wc-city-select'),
		_x('Pitfour', 'SAJA', 'ry-wc-city-select'),
		_x('Porto Bello', 'SAJA', 'ry-wc-city-select'),
		_x('Reading', 'SAJA', 'ry-wc-city-select'),
		_x('Retirement', 'SAJA', 'ry-wc-city-select'),
		_x('Retrieve', 'SAJA', 'ry-wc-city-select'),
		_x('Roehampton', 'SAJA', 'ry-wc-city-select'),
		_x('Rose Hall', 'SAJA', 'ry-wc-city-select'),
		_x('Rose Heights', 'SAJA', 'ry-wc-city-select'),
		_x('Rose Mount Garden', 'SAJA', 'ry-wc-city-select'),
		_x('Rosemount', 'SAJA', 'ry-wc-city-select'),
		_x('Salt Spring', 'SAJA', 'ry-wc-city-select'),
		_x('Seven Rivers', 'SAJA', 'ry-wc-city-select'),
		_x('Somerton', 'SAJA', 'ry-wc-city-select'),
		_x('Spot Valley', 'SAJA', 'ry-wc-city-select'),
		_x('Stonehenge', 'SAJA', 'ry-wc-city-select'),
		_x('Summer Hill', 'SAJA', 'ry-wc-city-select'),
		_x('Sunderland', 'SAJA', 'ry-wc-city-select'),
		_x('Tangle River', 'SAJA', 'ry-wc-city-select'),
		_x('Tower Hill/Moy Hall', 'SAJA', 'ry-wc-city-select'),
		_x('Tucker', 'SAJA', 'ry-wc-city-select'),
		_x('Unity Hall', 'SAJA', 'ry-wc-city-select'),
		_x('Vaughnsfield', 'SAJA', 'ry-wc-city-select'),
		_x('Welcome Hall', 'SAJA', 'ry-wc-city-select'),
		_x('West Green', 'SAJA', 'ry-wc-city-select'),
	],
	'SAMA' => [
		_x('Amiel Town', 'SAMA', 'ry-wc-city-select'),
		_x('Annotto Bay', 'SAMA', 'ry-wc-city-select'),
		_x('Baileys Vale', 'SAMA', 'ry-wc-city-select'),
		_x('Baxter Mountain', 'SAMA', 'ry-wc-city-select'),
		_x('Belfield', 'SAMA', 'ry-wc-city-select'),
		_x('Bonnygate', 'SAMA', 'ry-wc-city-select'),
		_x('Brainerd', 'SAMA', 'ry-wc-city-select'),
		_x('Broadgate', 'SAMA', 'ry-wc-city-select'),
		_x('Camberwell', 'SAMA', 'ry-wc-city-select'),
		_x('Carron Hall', 'SAMA', 'ry-wc-city-select'),
		_x('Castleton', 'SAMA', 'ry-wc-city-select'),
		_x('Charles Town', 'SAMA', 'ry-wc-city-select'),
		_x('Clonmel', 'SAMA', 'ry-wc-city-select'),
		_x('Devon Pen', 'SAMA', 'ry-wc-city-select'),
		_x('Dover', 'SAMA', 'ry-wc-city-select'),
		_x('Enfield', 'SAMA', 'ry-wc-city-select'),
		_x('Epson', 'SAMA', 'ry-wc-city-select'),
		_x('Flint River', 'SAMA', 'ry-wc-city-select'),
		_x('Free Hill', 'SAMA', 'ry-wc-city-select'),
		_x('Friendship Gap', 'SAMA', 'ry-wc-city-select'),
		_x('Galina', 'SAMA', 'ry-wc-city-select'),
		_x('Gayle', 'SAMA', 'ry-wc-city-select'),
		_x('Guys Hill', 'SAMA', 'ry-wc-city-select'),
		_x('Hampstead', 'SAMA', 'ry-wc-city-select'),
		_x('Highgate', 'SAMA', 'ry-wc-city-select'),
		_x('Islington', 'SAMA', 'ry-wc-city-select'),
		_x('Jacks River', 'SAMA', 'ry-wc-city-select'),
		_x('Jeffery Town', 'SAMA', 'ry-wc-city-select'),
		_x('Labyrinth', 'SAMA', 'ry-wc-city-select'),
		_x('Long Road', 'SAMA', 'ry-wc-city-select'),
		_x('Lucky Hill', 'SAMA', 'ry-wc-city-select'),
		_x('Mango Valley', 'SAMA', 'ry-wc-city-select'),
		_x('Martin', 'SAMA', 'ry-wc-city-select'),
		_x('Mason Hall', 'SAMA', 'ry-wc-city-select'),
		_x('Mile Gully', 'SAMA', 'ry-wc-city-select'),
		_x('Oracabessa', 'SAMA', 'ry-wc-city-select'),
		_x('Port Maria', 'SAMA', 'ry-wc-city-select'),
		_x('Prospect', 'SAMA', 'ry-wc-city-select'),
		_x('Retreat', 'SAMA', 'ry-wc-city-select'),
		_x('Richmond', 'SAMA', 'ry-wc-city-select'),
		_x('Robins Bay', 'SAMA', 'ry-wc-city-select'),
		_x('Sandside', 'SAMA', 'ry-wc-city-select'),
		_x('Scotts Hall', 'SAMA', 'ry-wc-city-select'),
		_x('Woodpark', 'SAMA', 'ry-wc-city-select'),
		_x('Woodside', 'SAMA', 'ry-wc-city-select'),
	],
	'SATH' => [
		_x('Airy Castle', 'SATH', 'ry-wc-city-select'),
		_x('Albion', 'SATH', 'ry-wc-city-select'),
		_x('Amity Hall', 'SATH', 'ry-wc-city-select'),
		_x('Arcadia', 'SATH', 'ry-wc-city-select'),
		_x('Baptist', 'SATH', 'ry-wc-city-select'),
		_x('Barking Lodge', 'SATH', 'ry-wc-city-select'),
		_x('Bath', 'SATH', 'ry-wc-city-select'),
		_x('Bethel', 'SATH', 'ry-wc-city-select'),
		_x('Cedar Valley', 'SATH', 'ry-wc-city-select'),
		_x('Church Corner', 'SATH', 'ry-wc-city-select'),
		_x('Dalvey', 'SATH', 'ry-wc-city-select'),
		_x('Danvers Pen', 'SATH', 'ry-wc-city-select'),
		_x('Duckenfield', 'SATH', 'ry-wc-city-select'),
		_x('Duhaney Pen', 'SATH', 'ry-wc-city-select'),
		_x('Easington', 'SATH', 'ry-wc-city-select'),
		_x('Eleven Miles', 'SATH', 'ry-wc-city-select'),
		_x('Font Hill', 'SATH', 'ry-wc-city-select'),
		_x('Golden Grove', 'SATH', 'ry-wc-city-select'),
		_x('Hagley Gap', 'SATH', 'ry-wc-city-select'),
		_x('Hampton Court', 'SATH', 'ry-wc-city-select'),
		_x('Hayfield', 'SATH', 'ry-wc-city-select'),
		_x('Hillside', 'SATH', 'ry-wc-city-select'),
		_x('Johns Town', 'SATH', 'ry-wc-city-select'),
		_x('Johnson Mountain', 'SATH', 'ry-wc-city-select'),
		_x('Jones Pen', 'SATH', 'ry-wc-city-select'),
		_x('Leith Hall', 'SATH', 'ry-wc-city-select'),
		_x('Llandewey', 'SATH', 'ry-wc-city-select'),
		_x('Lloyds', 'SATH', 'ry-wc-city-select'),
		_x('Lyssons', 'SATH', 'ry-wc-city-select'),
		_x('Middleton', 'SATH', 'ry-wc-city-select'),
		_x('Morant Bay', 'SATH', 'ry-wc-city-select'),
		_x('Mount Lebanus', 'SATH', 'ry-wc-city-select'),
		_x('New Monkland', 'SATH', 'ry-wc-city-select'),
		_x('Pamphret', 'SATH', 'ry-wc-city-select'),
		_x('Pear Tree', 'SATH', 'ry-wc-city-select'),
		_x('Poormans Corner', 'SATH', 'ry-wc-city-select'),
		_x('Port Morant', 'SATH', 'ry-wc-city-select'),
		_x('Prospect', 'SATH', 'ry-wc-city-select'),
		_x('Ramble', 'SATH', 'ry-wc-city-select'),
		_x('Retreat', 'SATH', 'ry-wc-city-select'),
		_x('Richmond Vale', 'SATH', 'ry-wc-city-select'),
		_x('River Head', 'SATH', 'ry-wc-city-select'),
		_x('Rowlandsfield', 'SATH', 'ry-wc-city-select'),
		_x('Seaforth', 'SATH', 'ry-wc-city-select'),
		_x('Somerset', 'SATH', 'ry-wc-city-select'),
		_x('Spring Bank', 'SATH', 'ry-wc-city-select'),
		_x('Spring Garden', 'SATH', 'ry-wc-city-select'),
		_x('Sunning Hill', 'SATH', 'ry-wc-city-select'),
		_x('Trinityville', 'SATH', 'ry-wc-city-select'),
		_x('Wheelerfield', 'SATH', 'ry-wc-city-select'),
		_x('White Hall', 'SATH', 'ry-wc-city-select'),
		_x('White Horses', 'SATH', 'ry-wc-city-select'),
		_x('Wilmington', 'SATH', 'ry-wc-city-select'),
		_x('Winchester', 'SATH', 'ry-wc-city-select'),
		_x('Yallahs', 'SATH', 'ry-wc-city-select'),
		_x('York', 'SATH', 'ry-wc-city-select'),
	],
	'TR' => [
		_x('Albert Town', 'TR', 'ry-wc-city-select'),
		_x('Alps', 'TR', 'ry-wc-city-select'),
		_x('Bounty Hall', 'TR', 'ry-wc-city-select'),
		_x('Brampton', 'TR', 'ry-wc-city-select'),
		_x('Bunkers Hill', 'TR', 'ry-wc-city-select'),
		_x('Clarks Town', 'TR', 'ry-wc-city-select'),
		_x('Daniel Town', 'TR', 'ry-wc-city-select'),
		_x('Deeside', 'TR', 'ry-wc-city-select'),
		_x('Duanvale', 'TR', 'ry-wc-city-select'),
		_x('Duncans', 'TR', 'ry-wc-city-select'),
		_x('Falmouth', 'TR', 'ry-wc-city-select'),
		_x('Freemans Hall', 'TR', 'ry-wc-city-select'),
		_x('Granville', 'TR', 'ry-wc-city-select'),
		_x('Hampden', 'TR', 'ry-wc-city-select'),
		_x('Jackson Town', 'TR', 'ry-wc-city-select'),
		_x('Joe Hut', 'TR', 'ry-wc-city-select'),
		_x('Kinloss', 'TR', 'ry-wc-city-select'),
		_x('Lorrimers', 'TR', 'ry-wc-city-select'),
		_x('Martha Brae', 'TR', 'ry-wc-city-select'),
		_x('Perth Town', 'TR', 'ry-wc-city-select'),
		_x('Refuge', 'TR', 'ry-wc-city-select'),
		_x('Rio Bueno', 'TR', 'ry-wc-city-select'),
		_x('Salt Marsh', 'TR', 'ry-wc-city-select'),
		_x('Samuels Prospect', 'TR', 'ry-wc-city-select'),
		_x('Sawyers', 'TR', 'ry-wc-city-select'),
		_x('Sherwood Content', 'TR', 'ry-wc-city-select'),
		_x('Spicy Hill', 'TR', 'ry-wc-city-select'),
		_x('Spring Garden', 'TR', 'ry-wc-city-select'),
		_x('St. Vincent', 'TR', 'ry-wc-city-select'),
		_x('Stettin', 'TR', 'ry-wc-city-select'),
		_x('Stewart Town', 'TR', 'ry-wc-city-select'),
		_x('Troy', 'TR', 'ry-wc-city-select'),
		_x('Ulster Spring', 'TR', 'ry-wc-city-select'),
		_x('Wait-A-Bit', 'TR', 'ry-wc-city-select'),
		_x('Wakefield', 'TR', 'ry-wc-city-select'),
		_x('Warsop', 'TR', 'ry-wc-city-select'),
		_x('Wilsons Run', 'TR', 'ry-wc-city-select'),
		_x('Wirefence', 'TR', 'ry-wc-city-select'),
	],
	'WE' => [
		_x('12th Street', 'WE', 'ry-wc-city-select'),
		_x('Amity', 'WE', 'ry-wc-city-select'),
		_x('Amity', 'WE', 'ry-wc-city-select'),
		_x('Ashton', 'WE', 'ry-wc-city-select'),
		_x('Barneyside', 'WE', 'ry-wc-city-select'),
		_x('Bath', 'WE', 'ry-wc-city-select'),
		_x('Bath Mountain', 'WE', 'ry-wc-city-select'),
		_x('Beaufort', 'WE', 'ry-wc-city-select'),
		_x('Beeston Spring', 'WE', 'ry-wc-city-select'),
		_x('Belvedere', 'WE', 'ry-wc-city-select'),
		_x('Berkshire', 'WE', 'ry-wc-city-select'),
		_x('Bethel Town', 'WE', 'ry-wc-city-select'),
		_x('Big Bridge', 'WE', 'ry-wc-city-select'),
		_x('Bluefields', 'WE', 'ry-wc-city-select'),
		_x('Bog', 'WE', 'ry-wc-city-select'),
		_x('Broughton', 'WE', 'ry-wc-city-select'),
		_x('Burnt Savannah', 'WE', 'ry-wc-city-select'),
		_x('Cairn Curran', 'WE', 'ry-wc-city-select'),
		_x('Caledonia', 'WE', 'ry-wc-city-select'),
		_x('Carmel', 'WE', 'ry-wc-city-select'),
		_x('Cave', 'WE', 'ry-wc-city-select'),
		_x('Chantilly', 'WE', 'ry-wc-city-select'),
		_x('Content', 'WE', 'ry-wc-city-select'),
		_x('Cornwall Mountian', 'WE', 'ry-wc-city-select'),
		_x('Darliston', 'WE', 'ry-wc-city-select'),
		_x('Delveland', 'WE', 'ry-wc-city-select'),
		_x('Dillion Bigwoods', 'WE', 'ry-wc-city-select'),
		_x('Dundee', 'WE', 'ry-wc-city-select'),
		_x('Enfield', 'WE', 'ry-wc-city-select'),
		_x('Ferris', 'WE', 'ry-wc-city-select'),
		_x('Fort Williams', 'WE', 'ry-wc-city-select'),
		_x('Frome', 'WE', 'ry-wc-city-select'),
		_x('Fullersfield', 'WE', 'ry-wc-city-select'),
		_x('Georges Plain', 'WE', 'ry-wc-city-select'),
		_x('Goodens River', 'WE', 'ry-wc-city-select'),
		_x('Grange', 'WE', 'ry-wc-city-select'),
		_x('Grange Hill', 'WE', 'ry-wc-city-select'),
		_x('Haddo', 'WE', 'ry-wc-city-select'),
		_x('Harmony Town', 'WE', 'ry-wc-city-select'),
		_x('Hertford', 'WE', 'ry-wc-city-select'),
		_x('Jerusalem', 'WE', 'ry-wc-city-select'),
		_x('Kentucky', 'WE', 'ry-wc-city-select'),
		_x('Kilmarnoch', 'WE', 'ry-wc-city-select'),
		_x('Lambs River', 'WE', 'ry-wc-city-select'),
		_x('Leamington', 'WE', 'ry-wc-city-select'),
		_x('Lenox Bigwoods', 'WE', 'ry-wc-city-select'),
		_x('Little London', 'WE', 'ry-wc-city-select'),
		_x('Llandilo', 'WE', 'ry-wc-city-select'),
		_x('Mackfield', 'WE', 'ry-wc-city-select'),
		_x('Mearnsville', 'WE', 'ry-wc-city-select'),
		_x('Mount Airy', 'WE', 'ry-wc-city-select'),
		_x('Mount Stewart', 'WE', 'ry-wc-city-select'),
		_x('Negril', 'WE', 'ry-wc-city-select'),
		_x('New Market Oval', 'WE', 'ry-wc-city-select'),
		_x('New Roads', 'WE', 'ry-wc-city-select'),
		_x('New Works', 'WE', 'ry-wc-city-select'),
		_x('Orange Hill', 'WE', 'ry-wc-city-select'),
		_x('Paul Island', 'WE', 'ry-wc-city-select'),
		_x('Petersfield', 'WE', 'ry-wc-city-select'),
		_x('Petersville', 'WE', 'ry-wc-city-select'),
		_x('Porters Mountain', 'WE', 'ry-wc-city-select'),
		_x('Red Hills', 'WE', 'ry-wc-city-select'),
		_x('Revival', 'WE', 'ry-wc-city-select'),
		_x('Roaring River', 'WE', 'ry-wc-city-select'),
		_x('Russia', 'WE', 'ry-wc-city-select'),
		_x('Savannah-la-mar Business Dist.', 'WE', 'ry-wc-city-select'),
		_x('Seaford Town', 'WE', 'ry-wc-city-select'),
		_x('Seaton Crescent', 'WE', 'ry-wc-city-select'),
		_x('Shefield', 'WE', 'ry-wc-city-select'),
		_x('Shoalin Grotto', 'WE', 'ry-wc-city-select'),
		_x('Smithfield', 'WE', 'ry-wc-city-select'),
		_x('St. Leonards', 'WE', 'ry-wc-city-select'),
		_x('Strathbogie', 'WE', 'ry-wc-city-select'),
		_x('Strawberry', 'WE', 'ry-wc-city-select'),
		_x('Struie', 'WE', 'ry-wc-city-select'),
		_x('Three Mile River', 'WE', 'ry-wc-city-select'),
		_x('Town Head', 'WE', 'ry-wc-city-select'),
		_x('Truro', 'WE', 'ry-wc-city-select'),
		_x('Water Works', 'WE', 'ry-wc-city-select'),
		_x('Whitehouse', 'WE', 'ry-wc-city-select'),
		_x('Whithorn', 'WE', 'ry-wc-city-select'),
		_x('Williamsfield', 'WE', 'ry-wc-city-select'),
	],
	]
];