<?php
/**
 * Kingdom of Cambodia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'KH' => [
	'BAME' => [
		_x('Krong Paoy Pet', 'BAME', 'ry-wc-city-select'),
		_x('Mongkol Borei', 'BAME', 'ry-wc-city-select'),
		_x('Ou Chrov District', 'BAME', 'ry-wc-city-select'),
		_x('Phnom Srok', 'BAME', 'ry-wc-city-select'),
		_x('Preah Netr Preah', 'BAME', 'ry-wc-city-select'),
		_x('Serei Saophoan', 'BAME', 'ry-wc-city-select'),
		_x('Srok Kamrieng', 'BAME', 'ry-wc-city-select'),
		_x('Srok Koas Krala', 'BAME', 'ry-wc-city-select'),
		_x('Srok Malai', 'BAME', 'ry-wc-city-select'),
		_x('Srok Phnum Proek', 'BAME', 'ry-wc-city-select'),
		_x('Srok Rukh Kiri', 'BAME', 'ry-wc-city-select'),
		_x('Srok Sampou Lun', 'BAME', 'ry-wc-city-select'),
		_x('Srok Svay Chek', 'BAME', 'ry-wc-city-select'),
		_x('Srok Thma Pok', 'BAME', 'ry-wc-city-select'),
		_x('Thma Puok', 'BAME', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Moung Ruessei', 'BA', 'ry-wc-city-select'),
		_x('Sangkae', 'BA', 'ry-wc-city-select'),
		_x('Srok Ak Phnum', 'BA', 'ry-wc-city-select'),
		_x('Srok Banan', 'BA', 'ry-wc-city-select'),
		_x('Srok Bavil', 'BA', 'ry-wc-city-select'),
		_x('Srok Rotanak Mondol', 'BA', 'ry-wc-city-select'),
		_x('Srok Samlot', 'BA', 'ry-wc-city-select'),
		_x('Srok Thma Koul', 'BA', 'ry-wc-city-select'),
		_x('Svay Pao', 'BA', 'ry-wc-city-select'),
	],
	'KACH' => [
		_x('Chamkar Leu', 'KACH', 'ry-wc-city-select'),
		_x('Cheung Prey', 'KACH', 'ry-wc-city-select'),
		_x('Kampong Cham', 'KACH', 'ry-wc-city-select'),
		_x('Kampong Siem', 'KACH', 'ry-wc-city-select'),
		_x('Kang Meas', 'KACH', 'ry-wc-city-select'),
		_x('Kaoh Soutin', 'KACH', 'ry-wc-city-select'),
		_x('Prey Chhor', 'KACH', 'ry-wc-city-select'),
		_x('Srei Santhor', 'KACH', 'ry-wc-city-select'),
		_x('Srok Batheay', 'KACH', 'ry-wc-city-select'),
		_x('Steung Trang', 'KACH', 'ry-wc-city-select'),
	],
	'KACH2' => [
		_x('Baribour', 'KACH2', 'ry-wc-city-select'),
		_x('Kampong Chhnang', 'KACH2', 'ry-wc-city-select'),
		_x('Kampong Leaeng', 'KACH2', 'ry-wc-city-select'),
		_x('Kampong Tralach', 'KACH2', 'ry-wc-city-select'),
		_x('Rolea Bier', 'KACH2', 'ry-wc-city-select'),
		_x('Srok Chol Kiri', 'KACH2', 'ry-wc-city-select'),
		_x('Srok Sameakki Mean Chey', 'KACH2', 'ry-wc-city-select'),
		_x('Tuek Phos', 'KACH2', 'ry-wc-city-select'),
	],
	'KASP' => [
		_x('Aoral', 'KASP', 'ry-wc-city-select'),
		_x('Krong Chbar Mon', 'KASP', 'ry-wc-city-select'),
		_x('Phnum Sruoch', 'KASP', 'ry-wc-city-select'),
		_x('Samraong Tong', 'KASP', 'ry-wc-city-select'),
		_x('Srok Basedth', 'KASP', 'ry-wc-city-select'),
		_x('Srok Kong Pisei', 'KASP', 'ry-wc-city-select'),
		_x('Srok Odongk', 'KASP', 'ry-wc-city-select'),
		_x('Thpong', 'KASP', 'ry-wc-city-select'),
	],
	'KATH' => [
		_x('Baray', 'KATH', 'ry-wc-city-select'),
		_x('Prasat Balangk', 'KATH', 'ry-wc-city-select'),
		_x('Sandan', 'KATH', 'ry-wc-city-select'),
		_x('Santuk', 'KATH', 'ry-wc-city-select'),
		_x('Srok Kampong Svay', 'KATH', 'ry-wc-city-select'),
		_x('Srok Prasat Sambor', 'KATH', 'ry-wc-city-select'),
		_x('Srok Stoung', 'KATH', 'ry-wc-city-select'),
		_x('Stueng Saen', 'KATH', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Angkor Chey', 'KA', 'ry-wc-city-select'),
		_x('Banteay Meas', 'KA', 'ry-wc-city-select'),
		_x('Chhouk District', 'KA', 'ry-wc-city-select'),
		_x('Kampong Bay', 'KA', 'ry-wc-city-select'),
		_x('Kampong Tranch', 'KA', 'ry-wc-city-select'),
		_x('Mittakpheap District', 'KA', 'ry-wc-city-select'),
		_x('Prey Nob', 'KA', 'ry-wc-city-select'),
		_x('Srok Chum Kiri', 'KA', 'ry-wc-city-select'),
		_x('Srok Dangtong', 'KA', 'ry-wc-city-select'),
		_x('Srok Tuek Chhou', 'KA', 'ry-wc-city-select'),
	],
	'KA2' => [
		_x('Kaoh Thum', 'KA2', 'ry-wc-city-select'),
		_x('Kien Svay', 'KA2', 'ry-wc-city-select'),
		_x('Krong Ta Khmau', 'KA2', 'ry-wc-city-select'),
		_x('Leuk Daek', 'KA2', 'ry-wc-city-select'),
		_x('Mukh Kampul', 'KA2', 'ry-wc-city-select'),
		_x('Popnhea Lueu', 'KA2', 'ry-wc-city-select'),
		_x('Sang', 'KA2', 'ry-wc-city-select'),
		_x('Srok Khsach Kandal', 'KA2', 'ry-wc-city-select'),
	],
	'KE' => [
		_x('Srok Damnak Changaeur', 'KE', 'ry-wc-city-select'),
	],
	'KOKO' => [
		_x('Kampong Seila', 'KOKO', 'ry-wc-city-select'),
		_x('Kiri Sakor', 'KOKO', 'ry-wc-city-select'),
		_x('Krong Khemara Phumin', 'KOKO', 'ry-wc-city-select'),
		_x('Srae Ambel', 'KOKO', 'ry-wc-city-select'),
		_x('Srok Batum Sakor', 'KOKO', 'ry-wc-city-select'),
		_x('Srok Mondol Seima', 'KOKO', 'ry-wc-city-select'),
		_x('Thma Bang', 'KOKO', 'ry-wc-city-select'),
	],
	'KR' => [
		_x('Chhloung', 'KR', 'ry-wc-city-select'),
		_x('Kracheh', 'KR', 'ry-wc-city-select'),
		_x('Preaek Prasab', 'KR', 'ry-wc-city-select'),
		_x('Sambour', 'KR', 'ry-wc-city-select'),
		_x('Snuol', 'KR', 'ry-wc-city-select'),
		_x('Srok Chet Buri', 'KR', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Khaoh Neaek', 'MO', 'ry-wc-city-select'),
		_x('Krong Senmonourom', 'MO', 'ry-wc-city-select'),
		_x('Ou Reang', 'MO', 'ry-wc-city-select'),
		_x('Srok Kaev Seima', 'MO', 'ry-wc-city-select'),
		_x('Srok Pech Chreada', 'MO', 'ry-wc-city-select'),
	],
	'OTME' => [
		_x('Srok Anlong Veng', 'OTME', 'ry-wc-city-select'),
		_x('Srok Banteay Ampil', 'OTME', 'ry-wc-city-select'),
		_x('Srok Samraong', 'OTME', 'ry-wc-city-select'),
		_x('Srok Trapeang Prasat', 'OTME', 'ry-wc-city-select'),
	],
	'PA' => [
		_x('Khan Pailin', 'PA', 'ry-wc-city-select'),
		_x('Khan Sala Krau', 'PA', 'ry-wc-city-select'),
	],
	'PHPE' => [
		_x('Khan 7 Makara', 'PHPE', 'ry-wc-city-select'),
		_x('Khan Chamkar Mon', 'PHPE', 'ry-wc-city-select'),
		_x('Khan Chey Por Senchey', 'PHPE', 'ry-wc-city-select'),
		_x('Khan Dangkao', 'PHPE', 'ry-wc-city-select'),
		_x('Khan Duon Penh', 'PHPE', 'ry-wc-city-select'),
		_x('Khan Mean Chey', 'PHPE', 'ry-wc-city-select'),
		_x('Khan Russey Keo', 'PHPE', 'ry-wc-city-select'),
		_x('Khan Saen Sokh', 'PHPE', 'ry-wc-city-select'),
		_x('Khan Tuol Kouk', 'PHPE', 'ry-wc-city-select'),
		_x('Phnom Penh', 'PHPE', 'ry-wc-city-select'),
	],
	'PRSI' => [
		_x('Srok Stueng Hav', 'PRSI', 'ry-wc-city-select'),
	],
	'PRVI' => [
		_x('Choam Khsant', 'PRVI', 'ry-wc-city-select'),
		_x('Krong Preah Vihear', 'PRVI', 'ry-wc-city-select'),
		_x('Sangkom Thmei', 'PRVI', 'ry-wc-city-select'),
		_x('Srok Cheh Sen', 'PRVI', 'ry-wc-city-select'),
		_x('Srok Chheb', 'PRVI', 'ry-wc-city-select'),
		_x('Srok Kulen', 'PRVI', 'ry-wc-city-select'),
		_x('Srok Rovieng', 'PRVI', 'ry-wc-city-select'),
		_x('Srok Tbeng Meanchey', 'PRVI', 'ry-wc-city-select'),
	],
	'PRVE' => [
		_x('Ba Phnum', 'PRVE', 'ry-wc-city-select'),
		_x('Kamchay Mear', 'PRVE', 'ry-wc-city-select'),
		_x('Kampong Trabaek', 'PRVE', 'ry-wc-city-select'),
		_x('Kanhchriech', 'PRVE', 'ry-wc-city-select'),
		_x('Lvea Aem', 'PRVE', 'ry-wc-city-select'),
		_x('Me Sang', 'PRVE', 'ry-wc-city-select'),
		_x('Pea Reang', 'PRVE', 'ry-wc-city-select'),
		_x('Peam Chor', 'PRVE', 'ry-wc-city-select'),
		_x('Peam Ro', 'PRVE', 'ry-wc-city-select'),
		_x('Sithor Kandal', 'PRVE', 'ry-wc-city-select'),
		_x('Srok Kampong Leav', 'PRVE', 'ry-wc-city-select'),
		_x('Srok Mesang', 'PRVE', 'ry-wc-city-select'),
		_x('Srok Preah Sdech', 'PRVE', 'ry-wc-city-select'),
		_x('Srok Svay Antor', 'PRVE', 'ry-wc-city-select'),
	],
	'PU' => [
		_x('Bakan', 'PU', 'ry-wc-city-select'),
		_x('Krakor', 'PU', 'ry-wc-city-select'),
		_x('Krong Pouthisat', 'PU', 'ry-wc-city-select'),
		_x('Phnum Kravanh', 'PU', 'ry-wc-city-select'),
		_x('Sampov Meas', 'PU', 'ry-wc-city-select'),
		_x('Srok Kandieng', 'PU', 'ry-wc-city-select'),
		_x('Srok Veal Veng', 'PU', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Lumphat', 'RA', 'ry-wc-city-select'),
		_x('Srok Andong Meas', 'RA', 'ry-wc-city-select'),
		_x('Srok Ba Kev', 'RA', 'ry-wc-city-select'),
		_x('Srok Ban Lung', 'RA', 'ry-wc-city-select'),
		_x('Srok Koun Mom', 'RA', 'ry-wc-city-select'),
		_x('Srok Ou Chum', 'RA', 'ry-wc-city-select'),
		_x('Srok Ou Ya Dav', 'RA', 'ry-wc-city-select'),
		_x('Srok Ta Veng', 'RA', 'ry-wc-city-select'),
		_x('Veun Sai', 'RA', 'ry-wc-city-select'),
	],
	'SIRE' => [
		_x('Angkor Chum', 'SIRE', 'ry-wc-city-select'),
		_x('Banteay Srei', 'SIRE', 'ry-wc-city-select'),
		_x('Chi Kraeng', 'SIRE', 'ry-wc-city-select'),
		_x('Chong Kal', 'SIRE', 'ry-wc-city-select'),
		_x('Kralanh', 'SIRE', 'ry-wc-city-select'),
		_x('Siem Reap', 'SIRE', 'ry-wc-city-select'),
		_x('Soutr Nkom', 'SIRE', 'ry-wc-city-select'),
		_x('Srei Snam', 'SIRE', 'ry-wc-city-select'),
		_x('Srok Angkor Thum', 'SIRE', 'ry-wc-city-select'),
		_x('Srok Prasat Bakong', 'SIRE', 'ry-wc-city-select'),
		_x('Srok Puok', 'SIRE', 'ry-wc-city-select'),
		_x('Svay Leu', 'SIRE', 'ry-wc-city-select'),
		_x('Varin', 'SIRE', 'ry-wc-city-select'),
	],
	'STTR' => [
		_x('Siem Bouk', 'STTR', 'ry-wc-city-select'),
		_x('Siem Pang', 'STTR', 'ry-wc-city-select'),
		_x('Srok Sresen', 'STTR', 'ry-wc-city-select'),
		_x('Stueng Traeng', 'STTR', 'ry-wc-city-select'),
		_x('Thala Barivat', 'STTR', 'ry-wc-city-select'),
	],
	'SVRI' => [
		_x('Chantrea', 'SVRI', 'ry-wc-city-select'),
		_x('Kampong Rou', 'SVRI', 'ry-wc-city-select'),
		_x('Krong Bavet', 'SVRI', 'ry-wc-city-select'),
		_x('Romeas Haek', 'SVRI', 'ry-wc-city-select'),
		_x('Rumduol', 'SVRI', 'ry-wc-city-select'),
		_x('Srok Svay Chrum', 'SVRI', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Bati', 'TA', 'ry-wc-city-select'),
		_x('Kiri Vong', 'TA', 'ry-wc-city-select'),
		_x('Krong Doun Kaev', 'TA', 'ry-wc-city-select'),
		_x('Prey Kabbas', 'TA', 'ry-wc-city-select'),
		_x('Srok Angkor Borei', 'TA', 'ry-wc-city-select'),
		_x('Srok Borei Cholsar', 'TA', 'ry-wc-city-select'),
		_x('Tram Kak', 'TA', 'ry-wc-city-select'),
		_x('Treang', 'TA', 'ry-wc-city-select'),
	],
	'TBKH' => [
		_x('Krong Suong', 'TBKH', 'ry-wc-city-select'),
		_x('Srok Dambe', 'TBKH', 'ry-wc-city-select'),
		_x('Srok Kroch Chhmar', 'TBKH', 'ry-wc-city-select'),
		_x('Srok Memot', 'TBKH', 'ry-wc-city-select'),
		_x('Srok O Reang Au', 'TBKH', 'ry-wc-city-select'),
		_x('Srok Ponhe Krek', 'TBKH', 'ry-wc-city-select'),
		_x('Srok Tbong Khmum', 'TBKH', 'ry-wc-city-select'),
	],
	]
];