<?php
/**
 * Democratic People's Republic of Korea places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'KP' => [
	'CH' => [
		_x('Chosan-gun', 'CH', 'ry-wc-city-select'),
		_x('Changgang-gun', 'CH', 'ry-wc-city-select'),
		_x('Chasong-gun', 'CH', 'ry-wc-city-select'),
		_x('Chonchon-gun', 'CH', 'ry-wc-city-select'),
		_x('Chunggang-gun', 'CH', 'ry-wc-city-select'),
		_x('Huichon-si', 'CH', 'ry-wc-city-select'),
		_x('Hwapyong-gun', 'CH', 'ry-wc-city-select'),
		_x('Kanggye-si', 'CH', 'ry-wc-city-select'),
		_x('Kopung-gun', 'CH', 'ry-wc-city-select'),
		_x('Manpo-si', 'CH', 'ry-wc-city-select'),
		_x('Nangnim-gun', 'CH', 'ry-wc-city-select'),
		_x('Sijung-gun', 'CH', 'ry-wc-city-select'),
		_x('Songgan-gun', 'CH', 'ry-wc-city-select'),
		_x('Songwon-gun', 'CH', 'ry-wc-city-select'),
		_x('Tongsin-gun', 'CH', 'ry-wc-city-select'),
		_x('Usi-gun', 'CH', 'ry-wc-city-select'),
		_x('Wiwon-gun', 'CH', 'ry-wc-city-select'),
		_x('Yongnim-gun', 'CH', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Chongjin-si', 'HA', 'ry-wc-city-select'),
		_x('Hoeryong', 'HA', 'ry-wc-city-select'),
		_x('Hwadae-gun', 'HA', 'ry-wc-city-select'),
		_x('Hwasong-gun', 'HA', 'ry-wc-city-select'),
		_x('Kilchu-gun', 'HA', 'ry-wc-city-select'),
		_x('Kimchaek-si', 'HA', 'ry-wc-city-select'),
		_x('Kyonghung', 'HA', 'ry-wc-city-select'),
		_x('Kyongsong-gun', 'HA', 'ry-wc-city-select'),
		_x('Kyongwon', 'HA', 'ry-wc-city-select'),
		_x('Musan-gun', 'HA', 'ry-wc-city-select'),
		_x('Myongchon-gun', 'HA', 'ry-wc-city-select'),
		_x('Onsong-gun', 'HA', 'ry-wc-city-select'),
		_x('Orang-gun', 'HA', 'ry-wc-city-select'),
		_x('Puryong-gun', 'HA', 'ry-wc-city-select'),
		_x('Yonsa-gun', 'HA', 'ry-wc-city-select'),
	],
	'HA2' => [
		_x('Changjin-gun', 'HA2', 'ry-wc-city-select'),
		_x('Chongpyong County', 'HA2', 'ry-wc-city-select'),
		_x('Hamhung-si', 'HA2', 'ry-wc-city-select'),
		_x('Hamju-gun', 'HA2', 'ry-wc-city-select'),
		_x('Hochon-gun', 'HA2', 'ry-wc-city-select'),
		_x('Hongwon-gun', 'HA2', 'ry-wc-city-select'),
		_x('Iwon-gun', 'HA2', 'ry-wc-city-select'),
		_x('Kowon-gun', 'HA2', 'ry-wc-city-select'),
		_x('Kumya-gun', 'HA2', 'ry-wc-city-select'),
		_x('Nagwon-gun', 'HA2', 'ry-wc-city-select'),
		_x('Pujon-gun', 'HA2', 'ry-wc-city-select'),
		_x('Pukchong-gun', 'HA2', 'ry-wc-city-select'),
		_x('Sinhung-gun', 'HA2', 'ry-wc-city-select'),
		_x('Sinpo-si', 'HA2', 'ry-wc-city-select'),
		_x('Sudong-gu', 'HA2', 'ry-wc-city-select'),
		_x('Tanchon-gun', 'HA2', 'ry-wc-city-select'),
		_x('Toksong-gun', 'HA2', 'ry-wc-city-select'),
		_x('Yodok-kun', 'HA2', 'ry-wc-city-select'),
		_x('Yonggwang-gun', 'HA2', 'ry-wc-city-select'),
	],
	'HW' => [
		_x('Hwangju-gun', 'HW', 'ry-wc-city-select'),
		_x('Insan-gun', 'HW', 'ry-wc-city-select'),
		_x('Koksan-gun', 'HW', 'ry-wc-city-select'),
		_x('Kumchon-gun', 'HW', 'ry-wc-city-select'),
		_x('Panmun-gun', 'HW', 'ry-wc-city-select'),
		_x('Pyongsan-gun', 'HW', 'ry-wc-city-select'),
		_x('Pongsan-gun', 'HW', 'ry-wc-city-select'),
		_x('Sariwon-si', 'HW', 'ry-wc-city-select'),
		_x('Singye-gun', 'HW', 'ry-wc-city-select'),
		_x('Sinpyong-gun', 'HW', 'ry-wc-city-select'),
		_x('Sohung-gun', 'HW', 'ry-wc-city-select'),
		_x('Songnim-si', 'HW', 'ry-wc-city-select'),
		_x('Suan-gun', 'HW', 'ry-wc-city-select'),
		_x('Tosan-gun', 'HW', 'ry-wc-city-select'),
		_x('Unpa-gun', 'HW', 'ry-wc-city-select'),
		_x('Yonsan-gun', 'HW', 'ry-wc-city-select'),
		_x('Yontan-gun', 'HW', 'ry-wc-city-select'),
	],
	'HW2' => [
		_x('Anak-kun', 'HW2', 'ry-wc-city-select'),
		_x('Chongdan-gun', 'HW2', 'ry-wc-city-select'),
		_x('Chaeryong-gun', 'HW2', 'ry-wc-city-select'),
		_x('Changpung-gun', 'HW2', 'ry-wc-city-select'),
		_x('Changyon-gun', 'HW2', 'ry-wc-city-select'),
		_x('Haeju-si', 'HW2', 'ry-wc-city-select'),
		_x('Kaepung-gun', 'HW2', 'ry-wc-city-select'),
		_x('Kaesong-si', 'HW2', 'ry-wc-city-select'),
		_x('Kangnyong-gun', 'HW2', 'ry-wc-city-select'),
		_x('Kwail-gun', 'HW2', 'ry-wc-city-select'),
		_x('Ongjin-gun', 'HW2', 'ry-wc-city-select'),
		_x('Paechon-gun', 'HW2', 'ry-wc-city-select'),
		_x('Pongchon-gun', 'HW2', 'ry-wc-city-select'),
		_x('Pyoksong-gun', 'HW2', 'ry-wc-city-select'),
		_x('Samchon-gun', 'HW2', 'ry-wc-city-select'),
		_x('Sinchon-gun', 'HW2', 'ry-wc-city-select'),
		_x('Sinwon-gun', 'HW2', 'ry-wc-city-select'),
		_x('Songhwa-gun', 'HW2', 'ry-wc-city-select'),
		_x('Taetan-gun', 'HW2', 'ry-wc-city-select'),
		_x('Ullyul-gun', 'HW2', 'ry-wc-city-select'),
		_x('Unchon-gun', 'HW2', 'ry-wc-city-select'),
		_x('Yonan-gun', 'HW2', 'ry-wc-city-select'),
		_x('Yongyon-gun', 'HW2', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Anbyon-gun', 'KA', 'ry-wc-city-select'),
		_x('Changdo-gun', 'KA', 'ry-wc-city-select'),
		_x('Chonnae-gun', 'KA', 'ry-wc-city-select'),
		_x('Chorwon-gun', 'KA', 'ry-wc-city-select'),
		_x('Hoeyang-gun', 'KA', 'ry-wc-city-select'),
		_x('Ichon-gun', 'KA', 'ry-wc-city-select'),
		_x('Kimhwa-gun', 'KA', 'ry-wc-city-select'),
		_x('Kosan-gun', 'KA', 'ry-wc-city-select'),
		_x('Kosong-gun', 'KA', 'ry-wc-city-select'),
		_x('Kumgang-gun', 'KA', 'ry-wc-city-select'),
		_x('Munchon-si', 'KA', 'ry-wc-city-select'),
		_x('Pangyo-gun', 'KA', 'ry-wc-city-select'),
		_x('Pyonggang-gun', 'KA', 'ry-wc-city-select'),
		_x('Poptong-gun', 'KA', 'ry-wc-city-select'),
		_x('Sepo-gun', 'KA', 'ry-wc-city-select'),
		_x('Tongchon-gun', 'KA', 'ry-wc-city-select'),
		_x('Wonsan-si', 'KA', 'ry-wc-city-select'),
	],
	'PY' => [
		_x('Changsong-gun', 'PY', 'ry-wc-city-select'),
		_x('Cholsan-gun', 'PY', 'ry-wc-city-select'),
		_x('Chonma-gun', 'PY', 'ry-wc-city-select'),
		_x('Chongju-gun', 'PY', 'ry-wc-city-select'),
		_x('Hyangsan-gun', 'PY', 'ry-wc-city-select'),
		_x('Kujang-gun', 'PY', 'ry-wc-city-select'),
		_x('Kusong-si', 'PY', 'ry-wc-city-select'),
		_x('Kwaksan-gun', 'PY', 'ry-wc-city-select'),
		_x('Nyongbyon-gun', 'PY', 'ry-wc-city-select'),
		_x('Pihyon-gun', 'PY', 'ry-wc-city-select'),
		_x('Pakchon-gun', 'PY', 'ry-wc-city-select'),
		_x('Pyoktong-gun', 'PY', 'ry-wc-city-select'),
		_x('Sakchu-gun', 'PY', 'ry-wc-city-select'),
		_x('Sindo-gun', 'PY', 'ry-wc-city-select'),
		_x('Sinuiju-si', 'PY', 'ry-wc-city-select'),
		_x('Sonchon-gun', 'PY', 'ry-wc-city-select'),
		_x('Taechon-gun', 'PY', 'ry-wc-city-select'),
		_x('Taegwan-gun', 'PY', 'ry-wc-city-select'),
		_x('Tongchang-gun', 'PY', 'ry-wc-city-select'),
		_x('Tongnim-gun', 'PY', 'ry-wc-city-select'),
		_x('Uiju County', 'PY', 'ry-wc-city-select'),
		_x('Unjon-gun', 'PY', 'ry-wc-city-select'),
		_x('Unsan-gun', 'PY', 'ry-wc-city-select'),
		_x('Yomju-gun', 'PY', 'ry-wc-city-select'),
		_x('Yongchon-gun', 'PY', 'ry-wc-city-select'),
	],
	'PY2' => [
		_x('Anju-si', 'PY2', 'ry-wc-city-select'),
		_x('Chollima-guyok', 'PY2', 'ry-wc-city-select'),
		_x('Chongnam-gu', 'PY2', 'ry-wc-city-select'),
		_x('Chungsan-gun', 'PY2', 'ry-wc-city-select'),
		_x('Hanggu-guyok', 'PY2', 'ry-wc-city-select'),
		_x('Hoechang-gun', 'PY2', 'ry-wc-city-select'),
		_x('Kaechon-si', 'PY2', 'ry-wc-city-select'),
		_x('Kangso-guyok', 'PY2', 'ry-wc-city-select'),
		_x('Maengsan-gun', 'PY2', 'ry-wc-city-select'),
		_x('Mundok-kun', 'PY2', 'ry-wc-city-select'),
		_x('Nyongwon-gun', 'PY2', 'ry-wc-city-select'),
		_x('Onchon-gun', 'PY2', 'ry-wc-city-select'),
		_x('Pyongsong-si', 'PY2', 'ry-wc-city-select'),
		_x('Pyongwon-gun', 'PY2', 'ry-wc-city-select'),
		_x('Pukchang-gun', 'PY2', 'ry-wc-city-select'),
		_x('Sinyang-gun', 'PY2', 'ry-wc-city-select'),
		_x('Songchon-gun', 'PY2', 'ry-wc-city-select'),
		_x('Sukchon-gun', 'PY2', 'ry-wc-city-select'),
		_x('Sunchon-si', 'PY2', 'ry-wc-city-select'),
		_x('Taean-guyok', 'PY2', 'ry-wc-city-select'),
		_x('Taedong-gun', 'PY2', 'ry-wc-city-select'),
		_x('Taehung-gun', 'PY2', 'ry-wc-city-select'),
		_x('Tokchon-si', 'PY2', 'ry-wc-city-select'),
		_x('Unsan-gun', 'PY2', 'ry-wc-city-select'),
		_x('Waudo-guyok', 'PY2', 'ry-wc-city-select'),
		_x('Yangdok-kun', 'PY2', 'ry-wc-city-select'),
		_x('Yonggang-gun', 'PY2', 'ry-wc-city-select'),
	],
	'PY3' => [
		_x('Chung', 'PY3', 'ry-wc-city-select'),
		_x('Chunghwa-gun', 'PY3', 'ry-wc-city-select'),
		_x('Hyongjesan-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Kangdong-gun', 'PY3', 'ry-wc-city-select'),
		_x('Kangnam-gun', 'PY3', 'ry-wc-city-select'),
		_x('Mangyongdae', 'PY3', 'ry-wc-city-select'),
		_x('Moranbong', 'PY3', 'ry-wc-city-select'),
		_x('Pyongchon-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Potonggang-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Rangnang', 'PY3', 'ry-wc-city-select'),
		_x('Ryokpo-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Ryongsong-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Sadong-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Samsok-kuyok', 'PY3', 'ry-wc-city-select'),
		_x('Sangwon-gun', 'PY3', 'ry-wc-city-select'),
		_x('Songyo-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Sosong-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Sunan', 'PY3', 'ry-wc-city-select'),
		_x('Sungho-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Taedonggang', 'PY3', 'ry-wc-city-select'),
		_x('Taesong-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Tongdaewon-guyok', 'PY3', 'ry-wc-city-select'),
		_x('Unjong-guyok', 'PY3', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Rajin', 'RA', 'ry-wc-city-select'),
		_x('Sonbong-gun', 'RA', 'ry-wc-city-select'),
	],
	'RY' => [
		_x('Hyesan-si', 'RY', 'ry-wc-city-select'),
		_x('Kapsan-gun', 'RY', 'ry-wc-city-select'),
		_x('Kimhyonggwon-gun', 'RY', 'ry-wc-city-select'),
		_x('Kimhyongjik-kun', 'RY', 'ry-wc-city-select'),
		_x('Kimjongsuk-kun', 'RY', 'ry-wc-city-select'),
		_x('Pungso-gun', 'RY', 'ry-wc-city-select'),
		_x('Paegam-gun', 'RY', 'ry-wc-city-select'),
		_x('Pochon-gun', 'RY', 'ry-wc-city-select'),
		_x('Samjiyon-gun', 'RY', 'ry-wc-city-select'),
		_x('Samsu-gun', 'RY', 'ry-wc-city-select'),
		_x('Taehongdan-gun', 'RY', 'ry-wc-city-select'),
		_x('Unhung-gun', 'RY', 'ry-wc-city-select'),
	],
	]
];