<?php
/**
 * Republic of Kazakhstan places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'KZ' => [
	'TOAU' => [
		_x('Lenger Qalasy', 'TOAU', 'ry-wc-city-select'),
	],
	'AKOB' => [
		_x('Algha Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Aqtobe Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Aqtobe Qalasy', 'AKOB', 'ry-wc-city-select'),
		_x('Ayteke Bi Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Bayghanin Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Bogetkol Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Isatay Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Khromtau Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'AKOB', 'ry-wc-city-select'),
		_x('Mortyq Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Mughalzhar Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Oktyabrsk Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Oyyl Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Qobda Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Shalqar Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Temir Audany', 'AKOB', 'ry-wc-city-select'),
		_x('Yrghyz Audany', 'AKOB', 'ry-wc-city-select'),
	],
	'AL' => [
		_x('Auezovskiy Rayon', 'AL', 'ry-wc-city-select'),
	],
	'ALOB' => [
		_x('Alakol District', 'ALOB', 'ry-wc-city-select'),
		_x('Aqsu Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Balqash Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Borilitobe Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Engbekshiqazaq Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Gvardiya Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Ile Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Kapshagay city', 'ALOB', 'ry-wc-city-select'),
		_x('Karasay', 'ALOB', 'ry-wc-city-select'),
		_x('Kegen Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Kerbulaq Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Koksu Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Kurti Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Panfilov Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Qapal Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Qaratal Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Qaskeleng Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Rayymbek Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Sarqan Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Shelek Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Taldyqorghan Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Taldyqorghan Qalasy', 'ALOB', 'ry-wc-city-select'),
		_x('Talghar Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Talghar Qalasy', 'ALOB', 'ry-wc-city-select'),
		_x('Tekeli Qalasy', 'ALOB', 'ry-wc-city-select'),
		_x('Uygentas Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Uyghyr Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Zhambyl Audany', 'ALOB', 'ry-wc-city-select'),
		_x('Zhambyl District', 'ALOB', 'ry-wc-city-select'),
	],
	'AQOB' => [
		_x('Akkol', 'AQOB', 'ry-wc-city-select'),
		_x('Arshaly', 'AQOB', 'ry-wc-city-select'),
		_x('Astrakhan', 'AQOB', 'ry-wc-city-select'),
		_x('Atbasar', 'AQOB', 'ry-wc-city-select'),
		_x('Birzhan sal', 'AQOB', 'ry-wc-city-select'),
		_x('Bulandy', 'AQOB', 'ry-wc-city-select'),
		_x('Burabay', 'AQOB', 'ry-wc-city-select'),
		_x('Egindikol', 'AQOB', 'ry-wc-city-select'),
		_x('Ereymentau', 'AQOB', 'ry-wc-city-select'),
		_x('Esil', 'AQOB', 'ry-wc-city-select'),
		_x('Korgalzhyn', 'AQOB', 'ry-wc-city-select'),
		_x('Qima Audany', 'AQOB', 'ry-wc-city-select'),
		_x('Sandyktau', 'AQOB', 'ry-wc-city-select'),
		_x('Shortandy', 'AQOB', 'ry-wc-city-select'),
		_x('Sileti Audany', 'AQOB', 'ry-wc-city-select'),
		_x('Stepnogorsk Qalasy', 'AQOB', 'ry-wc-city-select'),
		_x('Tselinograd', 'AQOB', 'ry-wc-city-select'),
		_x('Zerendi', 'AQOB', 'ry-wc-city-select'),
		_x('Zhaksy', 'AQOB', 'ry-wc-city-select'),
		_x('Zhangadala Audany', 'AQOB', 'ry-wc-city-select'),
		_x('Zharkain', 'AQOB', 'ry-wc-city-select'),
	],
	'ATOB' => [
		_x('Atyrau Qalasy', 'ATOB', 'ry-wc-city-select'),
		_x('Balyqshy Audany', 'ATOB', 'ry-wc-city-select'),
		_x('Inder Audany', 'ATOB', 'ry-wc-city-select'),
		_x('Isatay Audany', 'ATOB', 'ry-wc-city-select'),
		_x('Kurmanghazy Audany', 'ATOB', 'ry-wc-city-select'),
		_x('Kyzylkoga', 'ATOB', 'ry-wc-city-select'),
		_x('Makhambet Audany', 'ATOB', 'ry-wc-city-select'),
		_x('Maqat Audany', 'ATOB', 'ry-wc-city-select'),
		_x('Qyzylqogha Audany', 'ATOB', 'ry-wc-city-select'),
		_x('Zhylyoi', 'ATOB', 'ry-wc-city-select'),
		_x('Zhylyoy Audany', 'ATOB', 'ry-wc-city-select'),
	],
	'EAKA' => [
		_x('Abay Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Abyraly Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Aqsuat Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Ayakoz Qalasy', 'EAKA', 'ry-wc-city-select'),
		_x('Besqaraghay Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Borodulikha Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Glubokoe Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Kokpekti Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Kurshim Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Leninogorsk Qalasy', 'EAKA', 'ry-wc-city-select'),
		_x('Maqanshy Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Marqakol Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Novoshulba Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Oskemen Qalasy', 'EAKA', 'ry-wc-city-select'),
		_x('Qotanqaraghay Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Samarskoe Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Semey Qalasy', 'EAKA', 'ry-wc-city-select'),
		_x('Serebryansk Qalasy', 'EAKA', 'ry-wc-city-select'),
		_x('Shar Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Shemonaikha Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Shubartau Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Tarbaghatay Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Taskesken Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Tavriya Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Ulan Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Ulkennaryn Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Urzhar Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Zaysan Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Zhangasemey Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Zharma Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Zyryanovsk Audany', 'EAKA', 'ry-wc-city-select'),
		_x('Zyryanovsk Qalasy', 'EAKA', 'ry-wc-city-select'),
	],
	'MAOB' => [
		_x('Aqtau Qalasy', 'MAOB', 'ry-wc-city-select'),
		_x('Beyneu Audany', 'MAOB', 'ry-wc-city-select'),
		_x('Mangghystau Audany', 'MAOB', 'ry-wc-city-select'),
		_x('Munaily', 'MAOB', 'ry-wc-city-select'),
		_x('Qaraqiya Audany', 'MAOB', 'ry-wc-city-select'),
		_x('Tupqaraghan Audany', 'MAOB', 'ry-wc-city-select'),
		_x('Zhangaozen Qalasy', 'MAOB', 'ry-wc-city-select'),
	],
	'NOKA' => [
		_x('Aryqbalyq Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Ayyrtau Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Beskol Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Bulaevo Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Chistopole Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Chkalov Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Kellerovka Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Kokshetau Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Krasnoarmeysk Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Kuybyshev Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Lenin Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Lenin Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Leningrad Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Mamlyutka Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Moskva Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Presnovka Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Qyzyltu Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Ruzaevka Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Sergeevka Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Sokolovka Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Sovet Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Timiryazev Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Ualikhanov Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Vozvyshenka Audany', 'NOKA', 'ry-wc-city-select'),
		_x('Zhambyl Audany', 'NOKA', 'ry-wc-city-select'),
	],
	'PARE' => [
		_x('Aqsu Audany', 'PARE', 'ry-wc-city-select'),
		_x('Aqtoghay Audany', 'PARE', 'ry-wc-city-select'),
		_x('Bayanauyl Audany', 'PARE', 'ry-wc-city-select'),
		_x('Ekibastuz Audany', 'PARE', 'ry-wc-city-select'),
		_x('Ekibastuz Qalasy', 'PARE', 'ry-wc-city-select'),
		_x('Ertis Audany', 'PARE', 'ry-wc-city-select'),
		_x('Gorod Aksu', 'PARE', 'ry-wc-city-select'),
		_x('Lebyazhe Audany', 'PARE', 'ry-wc-city-select'),
		_x('May Audany', 'PARE', 'ry-wc-city-select'),
		_x('Pavlodar Audany', 'PARE', 'ry-wc-city-select'),
		_x('Pavlodar Qalasy', 'PARE', 'ry-wc-city-select'),
		_x('Qashyr Audany', 'PARE', 'ry-wc-city-select'),
		_x('Qazaly Audany', 'PARE', 'ry-wc-city-select'),
		_x('Sharbaqty Audany', 'PARE', 'ry-wc-city-select'),
		_x('Ulyanov Audany', 'PARE', 'ry-wc-city-select'),
		_x('Uspenka Audany', 'PARE', 'ry-wc-city-select'),
		_x('Zhelezin Audany', 'PARE', 'ry-wc-city-select'),
	],
	'QAOB' => [
		_x('Abay Qalasy', 'QAOB', 'ry-wc-city-select'),
		_x('Aqadyr Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Aqtoghay Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Balqash Qalasy', 'QAOB', 'ry-wc-city-select'),
		_x('Bukhar-Zhyrau', 'QAOB', 'ry-wc-city-select'),
		_x('Michurin Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Molodezhnyy Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Nura Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Ordzhonikidze Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Osakarovka Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Qalasy Satbaev', 'QAOB', 'ry-wc-city-select'),
		_x('Qaraghandy Qalasy', 'QAOB', 'ry-wc-city-select'),
		_x('Qarazhal Qalasy', 'QAOB', 'ry-wc-city-select'),
		_x('Qarqaraly Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Qazybek Bi Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Shakhtinsk Qalasy', 'QAOB', 'ry-wc-city-select'),
		_x('Shet Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Sorang Qalasy', 'QAOB', 'ry-wc-city-select'),
		_x('Telman Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Temirtau Qalasy', 'QAOB', 'ry-wc-city-select'),
		_x('Tengiz Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Toqyrauyn Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Ulytau Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Zhangaarqa Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Zhezdi Audany', 'QAOB', 'ry-wc-city-select'),
		_x('Zhezqazghan Qalasy', 'QAOB', 'ry-wc-city-select'),
	],
	'QOOB' => [
		_x('Altynsarinskiy Rayon', 'QOOB', 'ry-wc-city-select'),
		_x('Amangeldi Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Amantoghay Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Arqalyq Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Fedorovskiy Rayon', 'QOOB', 'ry-wc-city-select'),
		_x('Komsomol Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Kustanayskiy Rayon', 'QOOB', 'ry-wc-city-select'),
		_x('Lenin Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Lisakovsk Qalasy', 'QOOB', 'ry-wc-city-select'),
		_x('Mendykarinskiy Rayon', 'QOOB', 'ry-wc-city-select'),
		_x('Nauryzym Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Oktyabr Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Qamysty Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Qarasu Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Qostanay Qalasy', 'QOOB', 'ry-wc-city-select'),
		_x('Rudnyy Qalasy', 'QOOB', 'ry-wc-city-select'),
		_x('Semiozernyy Rayon', 'QOOB', 'ry-wc-city-select'),
		_x('Taranovskiy Rayon', 'QOOB', 'ry-wc-city-select'),
		_x('Uritskiy Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Zhangeldin Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Zhetiqara Audany', 'QOOB', 'ry-wc-city-select'),
		_x('Zhetiqara Qalasy', 'QOOB', 'ry-wc-city-select'),
	],
	'QYOB' => [
		_x('Aral Audany', 'QYOB', 'ry-wc-city-select'),
		_x('Qarmaqshy Audany', 'QYOB', 'ry-wc-city-select'),
		_x('Shieli Audany', 'QYOB', 'ry-wc-city-select'),
		_x('Syrdariya Audany', 'QYOB', 'ry-wc-city-select'),
		_x('Terengoezek Audany', 'QYOB', 'ry-wc-city-select'),
		_x('Zhalaghash Audany', 'QYOB', 'ry-wc-city-select'),
		_x('Zhangaqorghan Audany', 'QYOB', 'ry-wc-city-select'),
	],
	'TU' => [
		_x('Alghabas Audany', 'TU', 'ry-wc-city-select'),
		_x('Arys Audany', 'TU', 'ry-wc-city-select'),
		_x('Arys Qalasy', 'TU', 'ry-wc-city-select'),
		_x('Kazygurt District', 'TU', 'ry-wc-city-select'),
		_x('Keles Audany', 'TU', 'ry-wc-city-select'),
		_x('Kentau Qalasy', 'TU', 'ry-wc-city-select'),
		_x('Kirov Audany', 'TU', 'ry-wc-city-select'),
		_x('Maqtaaral Audany', 'TU', 'ry-wc-city-select'),
		_x('Ordabasy Audany', 'TU', 'ry-wc-city-select'),
		_x('Otyrar Audany', 'TU', 'ry-wc-city-select'),
		_x('Qazyqurt Audany', 'TU', 'ry-wc-city-select'),
		_x('Saryaghash Audany', 'TU', 'ry-wc-city-select'),
		_x('Sayram Audany', 'TU', 'ry-wc-city-select'),
		_x('Shardara Audany', 'TU', 'ry-wc-city-select'),
		_x('Sozaq Audany', 'TU', 'ry-wc-city-select'),
		_x('Tuerkistan Qalasy', 'TU', 'ry-wc-city-select'),
		_x('Tulkibas Audany', 'TU', 'ry-wc-city-select'),
		_x('Turkistan Audany', 'TU', 'ry-wc-city-select'),
		_x('Zhetisay Audany', 'TU', 'ry-wc-city-select'),
	],
	'WEKA' => [
		_x('Aqzhayyq Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Borili Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Chapaev Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Kaztalovka Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Oral Qalasy', 'WEKA', 'ry-wc-city-select'),
		_x('Orda Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Priurale Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Qaratobe Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Shyngghyrlau Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Syrym Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Tasqala Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Taypaq Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Terekti Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Zelenoe Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Zhalpaqtal Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Zhangaqala Audany', 'WEKA', 'ry-wc-city-select'),
		_x('Zhanibek Audany', 'WEKA', 'ry-wc-city-select'),
	],
	'ZHOB' => [
		_x('Bayzak District', 'ZHOB', 'ry-wc-city-select'),
		_x('Korday', 'ZHOB', 'ry-wc-city-select'),
		_x('Lugovoe Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Merke Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Moyynqum Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Qaratau Qalasy', 'ZHOB', 'ry-wc-city-select'),
		_x('Qorday Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Sarysu Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Shu Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Shu Qalasy', 'ZHOB', 'ry-wc-city-select'),
		_x('Sverdlov Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Talas Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Zhambyl Audany', 'ZHOB', 'ry-wc-city-select'),
		_x('Zhambyl Qalasy', 'ZHOB', 'ry-wc-city-select'),
		_x('Zhangatas Qalasy', 'ZHOB', 'ry-wc-city-select'),
		_x('Zhualy Audany', 'ZHOB', 'ry-wc-city-select'),
	],
	]
];