<?php
/**
 * Lao People's Democratic Republic places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'LA' => [
	'AT' => [
		_x('Muang Phouvong', 'AT', 'ry-wc-city-select'),
		_x('Muang Samakhixai', 'AT', 'ry-wc-city-select'),
		_x('Muang Sanamxai', 'AT', 'ry-wc-city-select'),
		_x('Muang Sanxai', 'AT', 'ry-wc-city-select'),
		_x('Muang Xaisettha', 'AT', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Muang Bolikhan', 'BO', 'ry-wc-city-select'),
		_x('Muang Khamkeut', 'BO', 'ry-wc-city-select'),
		_x('Muang Pakkading', 'BO', 'ry-wc-city-select'),
		_x('Muang Thaphabat', 'BO', 'ry-wc-city-select'),
		_x('Muang Viangthong', 'BO', 'ry-wc-city-select'),
		_x('Paksane', 'BO', 'ry-wc-city-select'),
		_x('Xaychamphone', 'BO', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Muang Bachiangchaleunsook', 'CH', 'ry-wc-city-select'),
		_x('Muang Champasak', 'CH', 'ry-wc-city-select'),
		_x('Muang Khong', 'CH', 'ry-wc-city-select'),
		_x('Muang Mounlapamok', 'CH', 'ry-wc-city-select'),
		_x('Muang Pakxe', 'CH', 'ry-wc-city-select'),
		_x('Muang Pakxong', 'CH', 'ry-wc-city-select'),
		_x('Muang Pathoumphon', 'CH', 'ry-wc-city-select'),
		_x('Muang Phonthong', 'CH', 'ry-wc-city-select'),
		_x('Muang Soukhouma', 'CH', 'ry-wc-city-select'),
		_x('Muang Xanasomboun', 'CH', 'ry-wc-city-select'),
	],
	'HO' => [
		_x('Kuan', 'HO', 'ry-wc-city-select'),
		_x('Muang Et', 'HO', 'ry-wc-city-select'),
		_x('Muang Hiam', 'HO', 'ry-wc-city-select'),
		_x('Muang Houamuang', 'HO', 'ry-wc-city-select'),
		_x('Muang Viangxai', 'HO', 'ry-wc-city-select'),
		_x('Muang Xam-Tai', 'HO', 'ry-wc-city-select'),
		_x('Muang Xiengkhor', 'HO', 'ry-wc-city-select'),
		_x('Sopbao', 'HO', 'ry-wc-city-select'),
		_x('Viengxon', 'HO', 'ry-wc-city-select'),
		_x('Xam Neua', 'HO', 'ry-wc-city-select'),
	],
	'KH' => [
		_x('Kounkham', 'KH', 'ry-wc-city-select'),
		_x('Muang Boualapha', 'KH', 'ry-wc-city-select'),
		_x('Muang Gnommarat', 'KH', 'ry-wc-city-select'),
		_x('Muang Hinboun', 'KH', 'ry-wc-city-select'),
		_x('Muang Mahaxai', 'KH', 'ry-wc-city-select'),
		_x('Muang Na Kay', 'KH', 'ry-wc-city-select'),
		_x('Muang Nongbok', 'KH', 'ry-wc-city-select'),
		_x('Muang Thakhek', 'KH', 'ry-wc-city-select'),
		_x('Muang Xaibouathong', 'KH', 'ry-wc-city-select'),
		_x('Muang Xebangfai', 'KH', 'ry-wc-city-select'),
	],
	'KHBO' => [
		_x('Muang Houayxay', 'KHBO', 'ry-wc-city-select'),
		_x('Muang Meung', 'KHBO', 'ry-wc-city-select'),
		_x('Muang Paktha', 'KHBO', 'ry-wc-city-select'),
		_x('Muang Pha Oudom', 'KHBO', 'ry-wc-city-select'),
		_x('Muang Tonpheung', 'KHBO', 'ry-wc-city-select'),
	],
	'KHOU' => [
		_x('Muang Beng', 'KHOU', 'ry-wc-city-select'),
		_x('Muang Houn', 'KHOU', 'ry-wc-city-select'),
		_x('Muang La', 'KHOU', 'ry-wc-city-select'),
		_x('Muang Namo', 'KHOU', 'ry-wc-city-select'),
		_x('Muang Nga', 'KHOU', 'ry-wc-city-select'),
		_x('Muang Pakbeng', 'KHOU', 'ry-wc-city-select'),
		_x('Muang Xai', 'KHOU', 'ry-wc-city-select'),
	],
	'KHPH' => [
		_x('Muang Boun Tai', 'KHPH', 'ry-wc-city-select'),
		_x('Muang Boun-Nua', 'KHPH', 'ry-wc-city-select'),
		_x('Muang Gnot-Ou', 'KHPH', 'ry-wc-city-select'),
		_x('Muang Khoa', 'KHPH', 'ry-wc-city-select'),
		_x('Muang Mai', 'KHPH', 'ry-wc-city-select'),
		_x('Muang Phongsali', 'KHPH', 'ry-wc-city-select'),
		_x('Samphanh', 'KHPH', 'ry-wc-city-select'),
	],
	'KHSA' => [
		_x('Kaysone Phomvihane', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Alsaphangthong', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Atsaphan', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Champhon', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Nong', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Outhoumphon', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Phin', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Songkhon', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Thapangthong', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Vilabouli', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Xaibouli', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Xayphoothong', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Xepon', 'KHSA', 'ry-wc-city-select'),
		_x('Muang Xonbouli', 'KHSA', 'ry-wc-city-select'),
		_x('Thaphalanxay', 'KHSA', 'ry-wc-city-select'),
	],
	'KHXE' => [
		_x('Muang Dakchung', 'KHXE', 'ry-wc-city-select'),
		_x('Muang Khaleum', 'KHXE', 'ry-wc-city-select'),
		_x('Muang Laman', 'KHXE', 'ry-wc-city-select'),
		_x('Muang Thateng', 'KHXE', 'ry-wc-city-select'),
	],
	'LO' => [
		_x('Muang Long', 'LO', 'ry-wc-city-select'),
		_x('Muang Louang Namtha', 'LO', 'ry-wc-city-select'),
		_x('Muang Nale', 'LO', 'ry-wc-city-select'),
		_x('Muang Sing', 'LO', 'ry-wc-city-select'),
		_x('Muang Viangphoukha', 'LO', 'ry-wc-city-select'),
	],
	'LUPRPR' => [
		_x('Muang Chomphet', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Louangphabang', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Nambak', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Nan', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Ngoy', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Pak-Ou', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Pakxeng', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Phonxai', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Phou Khoun', 'LUPRPR', 'ry-wc-city-select'),
		_x('Muang Viangkhan', 'LUPRPR', 'ry-wc-city-select'),
		_x('Phonthong', 'LUPRPR', 'ry-wc-city-select'),
		_x('Xieng ngeun', 'LUPRPR', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Muang Khongxedon', 'SA', 'ry-wc-city-select'),
		_x('Muang Lakhonpheng', 'SA', 'ry-wc-city-select'),
		_x('Muang Laongam', 'SA', 'ry-wc-city-select'),
		_x('Muang Samouay', 'SA', 'ry-wc-city-select'),
		_x('Muang Saravan', 'SA', 'ry-wc-city-select'),
		_x('Muang Ta-Oy', 'SA', 'ry-wc-city-select'),
		_x('Muang Toumlan', 'SA', 'ry-wc-city-select'),
		_x('Muang Vapi', 'SA', 'ry-wc-city-select'),
	],
	'VIPR' => [
		_x('Muang Chanthabouli', 'VIPR', 'ry-wc-city-select'),
		_x('Muang Hatxayfong', 'VIPR', 'ry-wc-city-select'),
		_x('Muang Maypakngum', 'VIPR', 'ry-wc-city-select'),
		_x('Muang Naxaythong', 'VIPR', 'ry-wc-city-select'),
		_x('Muang Sangthong', 'VIPR', 'ry-wc-city-select'),
		_x('Muang Sikhottabong', 'VIPR', 'ry-wc-city-select'),
		_x('Muang Sisattanak', 'VIPR', 'ry-wc-city-select'),
		_x('Muang Xaisettha', 'VIPR', 'ry-wc-city-select'),
		_x('Muang Xaithani', 'VIPR', 'ry-wc-city-select'),
	],
	'VIPR2' => [
		_x('Hinherb', 'VIPR2', 'ry-wc-city-select'),
		_x('Mad', 'VIPR2', 'ry-wc-city-select'),
		_x('Muang Fuang', 'VIPR2', 'ry-wc-city-select'),
		_x('Muang Kasi', 'VIPR2', 'ry-wc-city-select'),
		_x('Muang Keo-Oudom', 'VIPR2', 'ry-wc-city-select'),
		_x('Muang Phon-Hong', 'VIPR2', 'ry-wc-city-select'),
		_x('Muang Thoulakhom', 'VIPR2', 'ry-wc-city-select'),
		_x('Muang Vangviang', 'VIPR2', 'ry-wc-city-select'),
		_x('Muen', 'VIPR2', 'ry-wc-city-select'),
		_x('Viengkham', 'VIPR2', 'ry-wc-city-select'),
		_x('Xanakharm', 'VIPR2', 'ry-wc-city-select'),
	],
	'XA' => [
		_x('Botene', 'XA', 'ry-wc-city-select'),
		_x('Muang Hongsa', 'XA', 'ry-wc-city-select'),
		_x('Muang Kenthao', 'XA', 'ry-wc-city-select'),
		_x('Muang Khop', 'XA', 'ry-wc-city-select'),
		_x('Muang Ngeun', 'XA', 'ry-wc-city-select'),
		_x('Muang Paklay', 'XA', 'ry-wc-city-select'),
		_x('Muang Phiang', 'XA', 'ry-wc-city-select'),
		_x('Muang Xaignabouli', 'XA', 'ry-wc-city-select'),
		_x('Muang Xianghon', 'XA', 'ry-wc-city-select'),
		_x('Thongmyxay', 'XA', 'ry-wc-city-select'),
		_x('Xaysathan', 'XA', 'ry-wc-city-select'),
	],
	'XAPR' => [
		_x('Anouvong district', 'XAPR', 'ry-wc-city-select'),
		_x('Longchaeng', 'XAPR', 'ry-wc-city-select'),
		_x('Muang Hom', 'XAPR', 'ry-wc-city-select'),
		_x('Muang Longxan', 'XAPR', 'ry-wc-city-select'),
		_x('Muang Thathom', 'XAPR', 'ry-wc-city-select'),
	],
	'XI' => [
		_x('Muang Kham', 'XI', 'ry-wc-city-select'),
		_x('Muang Khoun', 'XI', 'ry-wc-city-select'),
		_x('Muang Mok', 'XI', 'ry-wc-city-select'),
		_x('Muang Nonghet', 'XI', 'ry-wc-city-select'),
		_x('Muang Pek', 'XI', 'ry-wc-city-select'),
		_x('Muang Phaxai', 'XI', 'ry-wc-city-select'),
		_x('Muang Phou Kont', 'XI', 'ry-wc-city-select'),
	],
	]
];