<?php
/**
 * Saint Lucia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'LC' => [
	'AN' => [
		_x('Au Tabor', 'AN', 'ry-wc-city-select'),
		_x('Au Tabor Hill', 'AN', 'ry-wc-city-select'),
		_x('Bois DInde', 'AN', 'ry-wc-city-select'),
		_x('Caico/Millet', 'AN', 'ry-wc-city-select'),
		_x('Champen Estate', 'AN', 'ry-wc-city-select'),
		_x('Dame De Traversay', 'AN', 'ry-wc-city-select'),
		_x('Derriere Dos', 'AN', 'ry-wc-city-select'),
		_x('Derriere Lagoon', 'AN', 'ry-wc-city-select'),
		_x('Durandeau', 'AN', 'ry-wc-city-select'),
		_x('Enbar Pwin', 'AN', 'ry-wc-city-select'),
		_x('Fond Eau Rouge', 'AN', 'ry-wc-city-select'),
		_x('Invorgoil Estate', 'AN', 'ry-wc-city-select'),
		_x('Jacmel', 'AN', 'ry-wc-city-select'),
		_x('Jean Baptiste', 'AN', 'ry-wc-city-select'),
		_x('La Trielle', 'AN', 'ry-wc-city-select'),
		_x('Massacre', 'AN', 'ry-wc-city-select'),
		_x('Millet', 'AN', 'ry-wc-city-select'),
		_x('Morne Ciseaux', 'AN', 'ry-wc-city-select'),
		_x('Morne DOr', 'AN', 'ry-wc-city-select'),
		_x('Roseau Valley', 'AN', 'ry-wc-city-select'),
		_x('St Lawrence', 'AN', 'ry-wc-city-select'),
		_x('St Lawrence Estate', 'AN', 'ry-wc-city-select'),
		_x('Tete Chemin', 'AN', 'ry-wc-city-select'),
		_x('Vanard', 'AN', 'ry-wc-city-select'),
		_x('Venus', 'AN', 'ry-wc-city-select'),
		_x('Village', 'AN', 'ry-wc-city-select'),
		_x('Village/Petite Bourgh', 'AN', 'ry-wc-city-select'),
	],
	'CA' => [
		_x('Anse Cochon', 'CA', 'ry-wc-city-select'),
		_x('Anse Galet', 'CA', 'ry-wc-city-select'),
		_x('Anse La Verdue', 'CA', 'ry-wc-city-select'),
		_x('Belvedere', 'CA', 'ry-wc-city-select'),
		_x('Chalon', 'CA', 'ry-wc-city-select'),
		_x('Chatin', 'CA', 'ry-wc-city-select'),
		_x('Des Bottes', 'CA', 'ry-wc-city-select'),
		_x('Morne Siquot', 'CA', 'ry-wc-city-select'),
		_x('Riverside Road', 'CA', 'ry-wc-city-select'),
		_x('Theodrine', 'CA', 'ry-wc-city-select'),
		_x('Village', 'CA', 'ry-wc-city-select'),
	],
	'CA2' => [
		_x('Active Hill', 'CA2', 'ry-wc-city-select'),
		_x('Agard Lands/Morne Dudon', 'CA2', 'ry-wc-city-select'),
		_x('Almondale', 'CA2', 'ry-wc-city-select'),
		_x('Aurendel Hill', 'CA2', 'ry-wc-city-select'),
		_x('Babonneau Proper', 'CA2', 'ry-wc-city-select'),
		_x('Bagatelle', 'CA2', 'ry-wc-city-select'),
		_x('Balata', 'CA2', 'ry-wc-city-select'),
		_x('Banannes Bay', 'CA2', 'ry-wc-city-select'),
		_x('Barnard Hill', 'CA2', 'ry-wc-city-select'),
		_x('Barre Denis', 'CA2', 'ry-wc-city-select'),
		_x('Barre Duchaussee', 'CA2', 'ry-wc-city-select'),
		_x('Barre St.Joseph', 'CA2', 'ry-wc-city-select'),
		_x('Belair', 'CA2', 'ry-wc-city-select'),
		_x('Bella Rosa', 'CA2', 'ry-wc-city-select'),
		_x('Bexon', 'CA2', 'ry-wc-city-select'),
		_x('BishopS Gap', 'CA2', 'ry-wc-city-select'),
		_x('Bissee', 'CA2', 'ry-wc-city-select'),
		_x('Black Mallet', 'CA2', 'ry-wc-city-select'),
		_x('Bocage', 'CA2', 'ry-wc-city-select'),
		_x('Bois Catchet', 'CA2', 'ry-wc-city-select'),
		_x('Bois Patat', 'CA2', 'ry-wc-city-select'),
		_x('Cabiche/Babonneau', 'CA2', 'ry-wc-city-select'),
		_x('Cacoa/Babonneau', 'CA2', 'ry-wc-city-select'),
		_x('Calvary', 'CA2', 'ry-wc-city-select'),
		_x('Capital Hill', 'CA2', 'ry-wc-city-select'),
		_x('Carellie', 'CA2', 'ry-wc-city-select'),
		_x('Cedars', 'CA2', 'ry-wc-city-select'),
		_x('Chase Gardens', 'CA2', 'ry-wc-city-select'),
		_x('Chassin/Babonneau', 'CA2', 'ry-wc-city-select'),
		_x('Choc', 'CA2', 'ry-wc-city-select'),
		_x('Choppin Ridge/Sarot', 'CA2', 'ry-wc-city-select'),
		_x('Ciceron', 'CA2', 'ry-wc-city-select'),
		_x('City', 'CA2', 'ry-wc-city-select'),
		_x('City Gate/La Clery', 'CA2', 'ry-wc-city-select'),
		_x('Conway/Waterfront', 'CA2', 'ry-wc-city-select'),
		_x('Coolie Town', 'CA2', 'ry-wc-city-select'),
		_x('Coubaril', 'CA2', 'ry-wc-city-select'),
		_x('Crownlands/Marc', 'CA2', 'ry-wc-city-select'),
		_x('Cul De Sac', 'CA2', 'ry-wc-city-select'),
		_x('Darling Road', 'CA2', 'ry-wc-city-select'),
		_x('Deglos', 'CA2', 'ry-wc-city-select'),
		_x('Derierre Fort/Old Victoria Road', 'CA2', 'ry-wc-city-select'),
		_x('Dubrassay', 'CA2', 'ry-wc-city-select'),
		_x('En Pois Doux/Babonneau', 'CA2', 'ry-wc-city-select'),
		_x('Entrepot', 'CA2', 'ry-wc-city-select'),
		_x('Faux A Chaud', 'CA2', 'ry-wc-city-select'),
		_x('Ferrand', 'CA2', 'ry-wc-city-select'),
		_x('Floissac/Marc', 'CA2', 'ry-wc-city-select'),
		_x('Fond Assau/Babonneau', 'CA2', 'ry-wc-city-select'),
		_x('Fond Canie', 'CA2', 'ry-wc-city-select'),
		_x('Fond Manger', 'CA2', 'ry-wc-city-select'),
		_x('Forest Reserve', 'CA2', 'ry-wc-city-select'),
		_x('Forestiere', 'CA2', 'ry-wc-city-select'),
		_x('George Charles Boulevard', 'CA2', 'ry-wc-city-select'),
		_x('Girard', 'CA2', 'ry-wc-city-select'),
		_x('Goergeville', 'CA2', 'ry-wc-city-select'),
		_x('Goodlands', 'CA2', 'ry-wc-city-select'),
		_x('Grass Street', 'CA2', 'ry-wc-city-select'),
		_x('Green Gold', 'CA2', 'ry-wc-city-select'),
		_x('Guesneau', 'CA2', 'ry-wc-city-select'),
		_x('Hill 20/Babonneau', 'CA2', 'ry-wc-city-select'),
		_x('Hillcrest Gardens', 'CA2', 'ry-wc-city-select'),
		_x('Hospital Road', 'CA2', 'ry-wc-city-select'),
		_x('Independence City', 'CA2', 'ry-wc-city-select'),
		_x('John Compton Highway', 'CA2', 'ry-wc-city-select'),
		_x('LAnse Road', 'CA2', 'ry-wc-city-select'),
		_x('La Carierre', 'CA2', 'ry-wc-city-select'),
		_x('La Clery', 'CA2', 'ry-wc-city-select'),
		_x('La Croix Maingot', 'CA2', 'ry-wc-city-select'),
		_x('La Pansee', 'CA2', 'ry-wc-city-select'),
		_x('La Toc', 'CA2', 'ry-wc-city-select'),
		_x('Labayee', 'CA2', 'ry-wc-city-select'),
		_x('Lastic Hill', 'CA2', 'ry-wc-city-select'),
		_x('Leslie Land', 'CA2', 'ry-wc-city-select'),
		_x('Marc', 'CA2', 'ry-wc-city-select'),
		_x('Marchand', 'CA2', 'ry-wc-city-select'),
		_x('Marigot', 'CA2', 'ry-wc-city-select'),
		_x('Maynard Hill', 'CA2', 'ry-wc-city-select'),
		_x('Miami/Bexon', 'CA2', 'ry-wc-city-select'),
		_x('Monkey Town Ciceron', 'CA2', 'ry-wc-city-select'),
		_x('Morne Assau/Babonneau', 'CA2', 'ry-wc-city-select'),
		_x('Morne Dudon', 'CA2', 'ry-wc-city-select'),
		_x('Morne Road', 'CA2', 'ry-wc-city-select'),
		_x('Morne Rouge/Marc', 'CA2', 'ry-wc-city-select'),
		_x('Mount Pleasant', 'CA2', 'ry-wc-city-select'),
		_x('New Village', 'CA2', 'ry-wc-city-select'),
		_x('Odsan', 'CA2', 'ry-wc-city-select'),
		_x('ParkerS Hill', 'CA2', 'ry-wc-city-select'),
		_x('PattersonS Gap', 'CA2', 'ry-wc-city-select'),
		_x('Pavee', 'CA2', 'ry-wc-city-select'),
		_x('PeartS Gap', 'CA2', 'ry-wc-city-select'),
		_x('Perou', 'CA2', 'ry-wc-city-select'),
		_x('Piton Flore', 'CA2', 'ry-wc-city-select'),
		_x('Pointe Seraphine', 'CA2', 'ry-wc-city-select'),
		_x('Quarte Chemins', 'CA2', 'ry-wc-city-select'),
		_x('Ravine Chabot', 'CA2', 'ry-wc-city-select'),
		_x('Ravine Poisson', 'CA2', 'ry-wc-city-select'),
		_x('Ravine Touterelle', 'CA2', 'ry-wc-city-select'),
		_x('Resinard/Babonneau', 'CA2', 'ry-wc-city-select'),
		_x('Rock Hall', 'CA2', 'ry-wc-city-select'),
		_x('Rose Hill', 'CA2', 'ry-wc-city-select'),
		_x('San Soucis', 'CA2', 'ry-wc-city-select'),
		_x('Sand De Feu', 'CA2', 'ry-wc-city-select'),
		_x('Sarot', 'CA2', 'ry-wc-city-select'),
		_x('Soucis', 'CA2', 'ry-wc-city-select'),
		_x('Summersdale', 'CA2', 'ry-wc-city-select'),
		_x('Sunbilt', 'CA2', 'ry-wc-city-select'),
		_x('Sunny Acres', 'CA2', 'ry-wc-city-select'),
		_x('Talvern', 'CA2', 'ry-wc-city-select'),
		_x('Tapion', 'CA2', 'ry-wc-city-select'),
		_x('The Morne', 'CA2', 'ry-wc-city-select'),
		_x('Ti Colon', 'CA2', 'ry-wc-city-select'),
		_x('Ti Rocher', 'CA2', 'ry-wc-city-select'),
		_x('Tourat/Soucis', 'CA2', 'ry-wc-city-select'),
		_x('Trois Piton', 'CA2', 'ry-wc-city-select'),
		_x('Trou Cochan/Marc', 'CA2', 'ry-wc-city-select'),
		_x('Trou Florent/Marc', 'CA2', 'ry-wc-city-select'),
		_x('Trou Rouge', 'CA2', 'ry-wc-city-select'),
		_x('Vide Bouteille', 'CA2', 'ry-wc-city-select'),
		_x('Vigie', 'CA2', 'ry-wc-city-select'),
		_x('Waterworks', 'CA2', 'ry-wc-city-select'),
		_x('WiltonS Yard/Grave Yard', 'CA2', 'ry-wc-city-select'),
		_x('Yorke Hill', 'CA2', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Belle Vue', 'CH', 'ry-wc-city-select'),
		_x('Bois Dinde', 'CH', 'ry-wc-city-select'),
		_x('Caffiere', 'CH', 'ry-wc-city-select'),
		_x('Cedars/Chu Tigre', 'CH', 'ry-wc-city-select'),
		_x('Christian Hill', 'CH', 'ry-wc-city-select'),
		_x('Dacretin', 'CH', 'ry-wc-city-select'),
		_x('Debreuil', 'CH', 'ry-wc-city-select'),
		_x('Delcer', 'CH', 'ry-wc-city-select'),
		_x('Derriere Morne', 'CH', 'ry-wc-city-select'),
		_x('Dugard', 'CH', 'ry-wc-city-select'),
		_x('Dupre', 'CH', 'ry-wc-city-select'),
		_x('Esperance', 'CH', 'ry-wc-city-select'),
		_x('Franciou', 'CH', 'ry-wc-city-select'),
		_x('Industry', 'CH', 'ry-wc-city-select'),
		_x('La Fargue', 'CH', 'ry-wc-city-select'),
		_x('La Pointe', 'CH', 'ry-wc-city-select'),
		_x('Lamaze', 'CH', 'ry-wc-city-select'),
		_x('Le Riche', 'CH', 'ry-wc-city-select'),
		_x('Mailly Motete', 'CH', 'ry-wc-city-select'),
		_x('Marche Gaye', 'CH', 'ry-wc-city-select'),
		_x('Martin', 'CH', 'ry-wc-city-select'),
		_x('Mavay', 'CH', 'ry-wc-city-select'),
		_x('Mongouge', 'CH', 'ry-wc-city-select'),
		_x('Monzie', 'CH', 'ry-wc-city-select'),
		_x('Morne Jacques', 'CH', 'ry-wc-city-select'),
		_x('Morne Palama', 'CH', 'ry-wc-city-select'),
		_x('Morne Sion', 'CH', 'ry-wc-city-select'),
		_x('Motete', 'CH', 'ry-wc-city-select'),
		_x('New Field/Fiette', 'CH', 'ry-wc-city-select'),
		_x('Ponyon', 'CH', 'ry-wc-city-select'),
		_x('Port Alese', 'CH', 'ry-wc-city-select'),
		_x('Raveneau', 'CH', 'ry-wc-city-select'),
		_x('Reunion', 'CH', 'ry-wc-city-select'),
		_x('River Doree', 'CH', 'ry-wc-city-select'),
		_x('Roblot', 'CH', 'ry-wc-city-select'),
		_x('Sauzay', 'CH', 'ry-wc-city-select'),
		_x('Savannesgeorge/Constitution', 'CH', 'ry-wc-city-select'),
		_x('Victoria', 'CH', 'ry-wc-city-select'),
		_x('Village', 'CH', 'ry-wc-city-select'),
	],
	'DE' => [
		_x('Anse Canot', 'DE', 'ry-wc-city-select'),
		_x('Athens', 'DE', 'ry-wc-city-select'),
		_x('Au Leon', 'DE', 'ry-wc-city-select'),
		_x('Bara Bara', 'DE', 'ry-wc-city-select'),
		_x('Barre De LIsle', 'DE', 'ry-wc-city-select'),
		_x('Bazile', 'DE', 'ry-wc-city-select'),
		_x('Belmont', 'DE', 'ry-wc-city-select'),
		_x('Bois Joli', 'DE', 'ry-wc-city-select'),
		_x('Bordelais', 'DE', 'ry-wc-city-select'),
		_x('Bosquet DOr', 'DE', 'ry-wc-city-select'),
		_x('Central Forest Reserve', 'DE', 'ry-wc-city-select'),
		_x('Delaide', 'DE', 'ry-wc-city-select'),
		_x('Dennery By Pass', 'DE', 'ry-wc-city-select'),
		_x('Dennery By Pass/Green Mountain', 'DE', 'ry-wc-city-select'),
		_x('Dennery By Pass/Rocky Lane', 'DE', 'ry-wc-city-select'),
		_x('Dennery By Pass/White Rock Gardens', 'DE', 'ry-wc-city-select'),
		_x('Dennery Village', 'DE', 'ry-wc-city-select'),
		_x('Derniere Riviere', 'DE', 'ry-wc-city-select'),
		_x('Derniere Riviere/Fond Maricient', 'DE', 'ry-wc-city-select'),
		_x('Derniere Riviere/Fond Petit', 'DE', 'ry-wc-city-select'),
		_x('Derniere Riviere/Mardi Gras/Morne Caca C', 'DE', 'ry-wc-city-select'),
		_x('Derniere Riviere/Morne Panache', 'DE', 'ry-wc-city-select'),
		_x('Despinoze', 'DE', 'ry-wc-city-select'),
		_x('Dubonnaire', 'DE', 'ry-wc-city-select'),
		_x('Errard', 'DE', 'ry-wc-city-select'),
		_x('Fond DOr', 'DE', 'ry-wc-city-select'),
		_x('Gadette', 'DE', 'ry-wc-city-select'),
		_x('Glavier', 'DE', 'ry-wc-city-select'),
		_x('Grande Ravine', 'DE', 'ry-wc-city-select'),
		_x('Grande Riviere', 'DE', 'ry-wc-city-select'),
		_x('Grande Riviere/Des Branch', 'DE', 'ry-wc-city-select'),
		_x('Grande Riviere/En Leur Morne/Discompere', 'DE', 'ry-wc-city-select'),
		_x('Grande Riviere/Funier', 'DE', 'ry-wc-city-select'),
		_x('Grande Riviere/Morne Caca Cochon', 'DE', 'ry-wc-city-select'),
		_x('La Caye', 'DE', 'ry-wc-city-select'),
		_x('La Pelle', 'DE', 'ry-wc-city-select'),
		_x('La Pointe', 'DE', 'ry-wc-city-select'),
		_x('La Ressource', 'DE', 'ry-wc-city-select'),
		_x('La Sociere', 'DE', 'ry-wc-city-select'),
		_x('Louvet', 'DE', 'ry-wc-city-select'),
		_x('Lumiere', 'DE', 'ry-wc-city-select'),
		_x('Mandele', 'DE', 'ry-wc-city-select'),
		_x('Morne Panache', 'DE', 'ry-wc-city-select'),
		_x('Mount Beaujolais', 'DE', 'ry-wc-city-select'),
		_x('Pascal', 'DE', 'ry-wc-city-select'),
		_x('Riche Fond', 'DE', 'ry-wc-city-select'),
		_x('Riche Fond/La Belle Vie', 'DE', 'ry-wc-city-select'),
		_x('Riche Fond/New Village', 'DE', 'ry-wc-city-select'),
		_x('St. Joseph Estate', 'DE', 'ry-wc-city-select'),
		_x('Thamazo', 'DE', 'ry-wc-city-select'),
		_x('Thomazo/Tournesse', 'DE', 'ry-wc-city-select'),
	],
	'GR' => [
		_x('Americ', 'GR', 'ry-wc-city-select'),
		_x('Beausejour', 'GR', 'ry-wc-city-select'),
		_x('Beausejour/FostinS Development', 'GR', 'ry-wc-city-select'),
		_x('Beausejour/Ndc', 'GR', 'ry-wc-city-select'),
		_x('Bella Rosa', 'GR', 'ry-wc-city-select'),
		_x('Belle Vue', 'GR', 'ry-wc-city-select'),
		_x('Belle Vue Estate', 'GR', 'ry-wc-city-select'),
		_x('Boguis', 'GR', 'ry-wc-city-select'),
		_x('Boguis/Desa Blond', 'GR', 'ry-wc-city-select'),
		_x('Bois DOrange', 'GR', 'ry-wc-city-select'),
		_x('Bois DOrnange/Trouya', 'GR', 'ry-wc-city-select'),
		_x('Bonneterre', 'GR', 'ry-wc-city-select'),
		_x('Bonneterre Gardens', 'GR', 'ry-wc-city-select'),
		_x('Caille Des', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Anse Du Cap', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Becune Park', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Becune Point', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Caribbean Park', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Golf Park', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Lower Saline Point', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Mon Du Cap', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Ranch Site', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Saddlec Back', 'GR', 'ry-wc-city-select'),
		_x('Cap Estate/Upper Saline Point', 'GR', 'ry-wc-city-select'),
		_x('Cas En Bas', 'GR', 'ry-wc-city-select'),
		_x('Caye Manje', 'GR', 'ry-wc-city-select'),
		_x('Corinth', 'GR', 'ry-wc-city-select'),
		_x('Corinth Estate', 'GR', 'ry-wc-city-select'),
		_x('Corinth/La Bel Lair', 'GR', 'ry-wc-city-select'),
		_x('Dauphin', 'GR', 'ry-wc-city-select'),
		_x('Des Barras', 'GR', 'ry-wc-city-select'),
		_x('Des Barras/Cacolie', 'GR', 'ry-wc-city-select'),
		_x('Desrameaux', 'GR', 'ry-wc-city-select'),
		_x('Garrand', 'GR', 'ry-wc-city-select'),
		_x('Grand Riviere', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/Assou Canal', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/Degazon', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/Ingle Woods', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/Morne Elwin', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/Morne Serpent', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/Norbert', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/Piat', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/Postlewaithe', 'GR', 'ry-wc-city-select'),
		_x('Grande Riviere/White Rock', 'GR', 'ry-wc-city-select'),
		_x('Gros Islet Town', 'GR', 'ry-wc-city-select'),
		_x('Gros Islet/Edge Water', 'GR', 'ry-wc-city-select'),
		_x('LHermitage', 'GR', 'ry-wc-city-select'),
		_x('La Croix Chabourgh', 'GR', 'ry-wc-city-select'),
		_x('La Guerre', 'GR', 'ry-wc-city-select'),
		_x('La Guerre/Chicken Back Street', 'GR', 'ry-wc-city-select'),
		_x('Marisule', 'GR', 'ry-wc-city-select'),
		_x('Marisule/Bon Air', 'GR', 'ry-wc-city-select'),
		_x('Marisule/East Winds', 'GR', 'ry-wc-city-select'),
		_x('Marisule/La Brellotte', 'GR', 'ry-wc-city-select'),
		_x('Marisule/Top Of The World', 'GR', 'ry-wc-city-select'),
		_x('Marisule/Top Of The World/Belle Ville', 'GR', 'ry-wc-city-select'),
		_x('Marquis Estate', 'GR', 'ry-wc-city-select'),
		_x('Massade', 'GR', 'ry-wc-city-select'),
		_x('Monchy', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Cardinal', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Careffe', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Cletus Village', 'GR', 'ry-wc-city-select'),
		_x('Monchy/La Borne', 'GR', 'ry-wc-city-select'),
		_x('Monchy/La Borne/Sans Souci', 'GR', 'ry-wc-city-select'),
		_x('Monchy/La Retraite', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Lafeuillee', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Lawi Fwen', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Malgretoute', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Moulin A Vent', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Mount Layau', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Ravine Macock', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Riviere Mitan', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Ti Dauphin', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Vieux Sucreic', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Vieux Sucreic/Bois DInde', 'GR', 'ry-wc-city-select'),
		_x('Monchy/Vieux Sucreic/Careffe', 'GR', 'ry-wc-city-select'),
		_x('Mongiraud', 'GR', 'ry-wc-city-select'),
		_x('Monier', 'GR', 'ry-wc-city-select'),
		_x('Morne Citon', 'GR', 'ry-wc-city-select'),
		_x('Paix Bouche', 'GR', 'ry-wc-city-select'),
		_x('Pigeon Island', 'GR', 'ry-wc-city-select'),
		_x('Plateau', 'GR', 'ry-wc-city-select'),
		_x('Reduit', 'GR', 'ry-wc-city-select'),
		_x('Reduit Orchard', 'GR', 'ry-wc-city-select'),
		_x('Reduit Park', 'GR', 'ry-wc-city-select'),
		_x('Rodney Bay', 'GR', 'ry-wc-city-select'),
		_x('Rodney Heights', 'GR', 'ry-wc-city-select'),
		_x('Union', 'GR', 'ry-wc-city-select'),
		_x('Union Terrace', 'GR', 'ry-wc-city-select'),
		_x('Union/Ti Morne', 'GR', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Annus', 'LA', 'ry-wc-city-select'),
		_x('Balca', 'LA', 'ry-wc-city-select'),
		_x('Balca/En Leur Ba', 'LA', 'ry-wc-city-select'),
		_x('Balembouche', 'LA', 'ry-wc-city-select'),
		_x('Banse', 'LA', 'ry-wc-city-select'),
		_x('Banse La Grace', 'LA', 'ry-wc-city-select'),
		_x('Beyar', 'LA', 'ry-wc-city-select'),
		_x('Bongalo', 'LA', 'ry-wc-city-select'),
		_x('Daban', 'LA', 'ry-wc-city-select'),
		_x('Fond Berange', 'LA', 'ry-wc-city-select'),
		_x('Gayabois', 'LA', 'ry-wc-city-select'),
		_x('Gentil', 'LA', 'ry-wc-city-select'),
		_x('Getrine', 'LA', 'ry-wc-city-select'),
		_x('Giraud', 'LA', 'ry-wc-city-select'),
		_x('HErelle', 'LA', 'ry-wc-city-select'),
		_x('Kennedy Highway/Laborie Bypass', 'LA', 'ry-wc-city-select'),
		_x('La Haut', 'LA', 'ry-wc-city-select'),
		_x('La Perle', 'LA', 'ry-wc-city-select'),
		_x('Londonderry', 'LA', 'ry-wc-city-select'),
		_x('Macdomel', 'LA', 'ry-wc-city-select'),
		_x('Morne Gomier', 'LA', 'ry-wc-city-select'),
		_x('Morne Le Blanc', 'LA', 'ry-wc-city-select'),
		_x('Morne Lezard Estate', 'LA', 'ry-wc-city-select'),
		_x('Morne Paul', 'LA', 'ry-wc-city-select'),
		_x('Olibo', 'LA', 'ry-wc-city-select'),
		_x('Parc Estate', 'LA', 'ry-wc-city-select'),
		_x('Piaye', 'LA', 'ry-wc-city-select'),
		_x('Saltibus', 'LA', 'ry-wc-city-select'),
		_x('Saphire', 'LA', 'ry-wc-city-select'),
		_x('Tete Morne', 'LA', 'ry-wc-city-select'),
		_x('Village', 'LA', 'ry-wc-city-select'),
		_x('Warwick/Daban', 'LA', 'ry-wc-city-select'),
	],
	'MI' => [
		_x('Anbre', 'MI', 'ry-wc-city-select'),
		_x('Anse Ger', 'MI', 'ry-wc-city-select'),
		_x('Beauchamp', 'MI', 'ry-wc-city-select'),
		_x('Blanchard', 'MI', 'ry-wc-city-select'),
		_x('Bois Canot', 'MI', 'ry-wc-city-select'),
		_x('Calypso', 'MI', 'ry-wc-city-select'),
		_x('Canelles', 'MI', 'ry-wc-city-select'),
		_x('Carriere', 'MI', 'ry-wc-city-select'),
		_x('Catter Beaufond', 'MI', 'ry-wc-city-select'),
		_x('Cazuca', 'MI', 'ry-wc-city-select'),
		_x('Chique/Blanchard', 'MI', 'ry-wc-city-select'),
		_x('Choucomel', 'MI', 'ry-wc-city-select'),
		_x('Coolie Town', 'MI', 'ry-wc-city-select'),
		_x('Delomel', 'MI', 'ry-wc-city-select'),
		_x('Des Blanchard', 'MI', 'ry-wc-city-select'),
		_x('Descatier/Six Miles', 'MI', 'ry-wc-city-select'),
		_x('Desruisseaux', 'MI', 'ry-wc-city-select'),
		_x('Dugard', 'MI', 'ry-wc-city-select'),
		_x('En Mango', 'MI', 'ry-wc-city-select'),
		_x('Escap', 'MI', 'ry-wc-city-select'),
		_x('Fond DLor/Dugard', 'MI', 'ry-wc-city-select'),
		_x('Fond Estate', 'MI', 'ry-wc-city-select'),
		_x('Fond/Desruisseaux', 'MI', 'ry-wc-city-select'),
		_x('Galba', 'MI', 'ry-wc-city-select'),
		_x('Gomier', 'MI', 'ry-wc-city-select'),
		_x('Gouette', 'MI', 'ry-wc-city-select'),
		_x('Honeymoon Beach', 'MI', 'ry-wc-city-select'),
		_x('LEau Mineau', 'MI', 'ry-wc-city-select'),
		_x('LOrangerie Road', 'MI', 'ry-wc-city-select'),
		_x('LUnion', 'MI', 'ry-wc-city-select'),
		_x('La Courville', 'MI', 'ry-wc-city-select'),
		_x('La Croix', 'MI', 'ry-wc-city-select'),
		_x('La Fille', 'MI', 'ry-wc-city-select'),
		_x('La Gwen Ba', 'MI', 'ry-wc-city-select'),
		_x('La Haut', 'MI', 'ry-wc-city-select'),
		_x('La Pointe', 'MI', 'ry-wc-city-select'),
		_x('La Tille', 'MI', 'ry-wc-city-select'),
		_x('Lezy', 'MI', 'ry-wc-city-select'),
		_x('Lombard', 'MI', 'ry-wc-city-select'),
		_x('London Road', 'MI', 'ry-wc-city-select'),
		_x('Mahaut', 'MI', 'ry-wc-city-select'),
		_x('Malgretoute', 'MI', 'ry-wc-city-select'),
		_x('Mamiku', 'MI', 'ry-wc-city-select'),
		_x('Mine', 'MI', 'ry-wc-city-select'),
		_x('Mon Repos', 'MI', 'ry-wc-city-select'),
		_x('Moreau', 'MI', 'ry-wc-city-select'),
		_x('Morne Vient', 'MI', 'ry-wc-city-select'),
		_x('Mount Erole', 'MI', 'ry-wc-city-select'),
		_x('Myette Gardens', 'MI', 'ry-wc-city-select'),
		_x('New Village', 'MI', 'ry-wc-city-select'),
		_x('Paix Bouche', 'MI', 'ry-wc-city-select'),
		_x('Palmiste Estate', 'MI', 'ry-wc-city-select'),
		_x('Patience', 'MI', 'ry-wc-city-select'),
		_x('Pelouze', 'MI', 'ry-wc-city-select'),
		_x('Planard', 'MI', 'ry-wc-city-select'),
		_x('Praslin', 'MI', 'ry-wc-city-select'),
		_x('Raillon Road', 'MI', 'ry-wc-city-select'),
		_x('Rameau', 'MI', 'ry-wc-city-select'),
		_x('Rouarne', 'MI', 'ry-wc-city-select'),
		_x('Saint Marie Road', 'MI', 'ry-wc-city-select'),
		_x('Saut', 'MI', 'ry-wc-city-select'),
		_x('Savannes', 'MI', 'ry-wc-city-select'),
		_x('St Helen Estate', 'MI', 'ry-wc-city-select'),
		_x('Ti Riviere', 'MI', 'ry-wc-city-select'),
		_x('Ti Rocher', 'MI', 'ry-wc-city-select'),
		_x('Tou Cochan/Ti Rocher', 'MI', 'ry-wc-city-select'),
		_x('Troumassee', 'MI', 'ry-wc-city-select'),
		_x('Village', 'MI', 'ry-wc-city-select'),
		_x('Volet', 'MI', 'ry-wc-city-select'),
	],
	'SO' => [
		_x('Anse Chastanet', 'SO', 'ry-wc-city-select'),
		_x('Barons Drive/Coin De LAnse', 'SO', 'ry-wc-city-select'),
		_x('Beasejour/Myers Bridge', 'SO', 'ry-wc-city-select'),
		_x('Belle Plaine', 'SO', 'ry-wc-city-select'),
		_x('Bellefond', 'SO', 'ry-wc-city-select'),
		_x('Belvedere', 'SO', 'ry-wc-city-select'),
		_x('Bois DInde', 'SO', 'ry-wc-city-select'),
		_x('Bouton', 'SO', 'ry-wc-city-select'),
		_x('Calvary/Calvaire', 'SO', 'ry-wc-city-select'),
		_x('Cenac', 'SO', 'ry-wc-city-select'),
		_x('Chateau Belair', 'SO', 'ry-wc-city-select'),
		_x('Colombette', 'SO', 'ry-wc-city-select'),
		_x('Compar', 'SO', 'ry-wc-city-select'),
		_x('Coubaril Estate', 'SO', 'ry-wc-city-select'),
		_x('Cresslands', 'SO', 'ry-wc-city-select'),
		_x('Descolons', 'SO', 'ry-wc-city-select'),
		_x('Deville', 'SO', 'ry-wc-city-select'),
		_x('Diamond/Diamond Estate', 'SO', 'ry-wc-city-select'),
		_x('Esperance', 'SO', 'ry-wc-city-select'),
		_x('Etangs', 'SO', 'ry-wc-city-select'),
		_x('Fond Bernier', 'SO', 'ry-wc-city-select'),
		_x('Fond Cacoa', 'SO', 'ry-wc-city-select'),
		_x('Fond Doux', 'SO', 'ry-wc-city-select'),
		_x('Fond Gens Libre', 'SO', 'ry-wc-city-select'),
		_x('Gros Piton', 'SO', 'ry-wc-city-select'),
		_x('Jalousie', 'SO', 'ry-wc-city-select'),
		_x('La Dauphine', 'SO', 'ry-wc-city-select'),
		_x('La Haut', 'SO', 'ry-wc-city-select'),
		_x('La Pearle', 'SO', 'ry-wc-city-select'),
		_x('Lenny Hill', 'SO', 'ry-wc-city-select'),
		_x('Mal Maison', 'SO', 'ry-wc-city-select'),
		_x('Malgretoute', 'SO', 'ry-wc-city-select'),
		_x('Migny', 'SO', 'ry-wc-city-select'),
		_x('Mocha', 'SO', 'ry-wc-city-select'),
		_x('Morne Bonin', 'SO', 'ry-wc-city-select'),
		_x('Morne La Croix', 'SO', 'ry-wc-city-select'),
		_x('Morne Lastic/Desruisseaux', 'SO', 'ry-wc-city-select'),
		_x('Morne Tabac', 'SO', 'ry-wc-city-select'),
		_x('New Development', 'SO', 'ry-wc-city-select'),
		_x('Palmiste', 'SO', 'ry-wc-city-select'),
		_x('Plat Pays', 'SO', 'ry-wc-city-select'),
		_x('Rabot', 'SO', 'ry-wc-city-select'),
		_x('Ravine Claire', 'SO', 'ry-wc-city-select'),
		_x('Ruby Estate', 'SO', 'ry-wc-city-select'),
		_x('Sapphire', 'SO', 'ry-wc-city-select'),
		_x('Soufriere Estate', 'SO', 'ry-wc-city-select'),
		_x('St Phillip', 'SO', 'ry-wc-city-select'),
		_x('St Remy Estate', 'SO', 'ry-wc-city-select'),
		_x('Stonefield', 'SO', 'ry-wc-city-select'),
		_x('Sulphur Springs', 'SO', 'ry-wc-city-select'),
		_x('Terre Blanche', 'SO', 'ry-wc-city-select'),
		_x('Ti Boug', 'SO', 'ry-wc-city-select'),
		_x('Ti Delcer', 'SO', 'ry-wc-city-select'),
		_x('Toraille', 'SO', 'ry-wc-city-select'),
		_x('Town', 'SO', 'ry-wc-city-select'),
		_x('Union Vale', 'SO', 'ry-wc-city-select'),
		_x('Zenon', 'SO', 'ry-wc-city-select'),
	],
	'VI' => [
		_x('Anse De Sables/Beane Field', 'VI', 'ry-wc-city-select'),
		_x('Augier', 'VI', 'ry-wc-city-select'),
		_x('Beane Field', 'VI', 'ry-wc-city-select'),
		_x('Beausejour', 'VI', 'ry-wc-city-select'),
		_x('Belle Vue', 'VI', 'ry-wc-city-select'),
		_x('Black Bay', 'VI', 'ry-wc-city-select'),
		_x('Bruceville/Shanty Town', 'VI', 'ry-wc-city-select'),
		_x('Cacoa', 'VI', 'ry-wc-city-select'),
		_x('Cantonement', 'VI', 'ry-wc-city-select'),
		_x('Carierre', 'VI', 'ry-wc-city-select'),
		_x('Catin', 'VI', 'ry-wc-city-select'),
		_x('Cocoa Dan', 'VI', 'ry-wc-city-select'),
		_x('Coolie Town', 'VI', 'ry-wc-city-select'),
		_x('De Mailly', 'VI', 'ry-wc-city-select'),
		_x('Derierre Bois', 'VI', 'ry-wc-city-select'),
		_x('Derierre Morne', 'VI', 'ry-wc-city-select'),
		_x('Docamel/La Resource', 'VI', 'ry-wc-city-select'),
		_x('Eau Piquant/St Urbain', 'VI', 'ry-wc-city-select'),
		_x('En Bamboo', 'VI', 'ry-wc-city-select'),
		_x('Esperance', 'VI', 'ry-wc-city-select'),
		_x('Fond Capeche', 'VI', 'ry-wc-city-select'),
		_x('Fond Sabot', 'VI', 'ry-wc-city-select'),
		_x('Grace', 'VI', 'ry-wc-city-select'),
		_x('Hewanorra Orchard', 'VI', 'ry-wc-city-select'),
		_x('Hope Estate', 'VI', 'ry-wc-city-select'),
		_x('Industrial Estate', 'VI', 'ry-wc-city-select'),
		_x('Joyeux', 'VI', 'ry-wc-city-select'),
		_x('La Resource', 'VI', 'ry-wc-city-select'),
		_x('La Retraite', 'VI', 'ry-wc-city-select'),
		_x('La Tourney/Cedar Heights', 'VI', 'ry-wc-city-select'),
		_x('Maganier', 'VI', 'ry-wc-city-select'),
		_x('Morne Cayenne', 'VI', 'ry-wc-city-select'),
		_x('Morne Vert', 'VI', 'ry-wc-city-select'),
		_x('Moule A Chique', 'VI', 'ry-wc-city-select'),
		_x('Obrier', 'VI', 'ry-wc-city-select'),
		_x('Pierrot', 'VI', 'ry-wc-city-select'),
		_x('Plut', 'VI', 'ry-wc-city-select'),
		_x('Pomme', 'VI', 'ry-wc-city-select'),
		_x('St JudeS Highway', 'VI', 'ry-wc-city-select'),
		_x('Tete Morne/Morne Andrew', 'VI', 'ry-wc-city-select'),
		_x('Town', 'VI', 'ry-wc-city-select'),
		_x('Viancelle', 'VI', 'ry-wc-city-select'),
		_x('Vieux Fort/Laborie Highway', 'VI', 'ry-wc-city-select'),
		_x('Vige', 'VI', 'ry-wc-city-select'),
		_x('Westall Group/The Mangue', 'VI', 'ry-wc-city-select'),
		_x('Woodlands', 'VI', 'ry-wc-city-select'),
	],
	]
];