<?php
/**
 * Democratic Socialist Republic of Sri Lan places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'LK' => [
	'AMDI' => [
		_x('Addalaichenai', 'AMDI', 'ry-wc-city-select'),
		_x('Akkaraipattu', 'AMDI', 'ry-wc-city-select'),
		_x('Alayadiwembu Division', 'AMDI', 'ry-wc-city-select'),
		_x('Ampara', 'AMDI', 'ry-wc-city-select'),
		_x('Damana Division', 'AMDI', 'ry-wc-city-select'),
		_x('Dehiattakandiya', 'AMDI', 'ry-wc-city-select'),
		_x('Irakkamam', 'AMDI', 'ry-wc-city-select'),
		_x('Kalmunai', 'AMDI', 'ry-wc-city-select'),
		_x('Karaitivu', 'AMDI', 'ry-wc-city-select'),
		_x('Lahugala Division', 'AMDI', 'ry-wc-city-select'),
		_x('Mahaoya Division', 'AMDI', 'ry-wc-city-select'),
		_x('Navithanveli', 'AMDI', 'ry-wc-city-select'),
		_x('Nintavur', 'AMDI', 'ry-wc-city-select'),
		_x('Padiyathalawa', 'AMDI', 'ry-wc-city-select'),
		_x('Pottuvil Division', 'AMDI', 'ry-wc-city-select'),
		_x('Sainthamaruthu', 'AMDI', 'ry-wc-city-select'),
		_x('Sammanthurai', 'AMDI', 'ry-wc-city-select'),
		_x('Thirukkovil Division', 'AMDI', 'ry-wc-city-select'),
		_x('Uhana', 'AMDI', 'ry-wc-city-select'),
	],
	'ANDI' => [
		_x('Galenbidunuwewa', 'ANDI', 'ry-wc-city-select'),
		_x('Galnewa Division', 'ANDI', 'ry-wc-city-select'),
		_x('Horowupotana Division', 'ANDI', 'ry-wc-city-select'),
		_x('Ipalogama Division', 'ANDI', 'ry-wc-city-select'),
		_x('Kahatagasdigiliya Divison', 'ANDI', 'ry-wc-city-select'),
		_x('Kebitigollewa Division', 'ANDI', 'ry-wc-city-select'),
		_x('Kekirawa Division', 'ANDI', 'ry-wc-city-select'),
		_x('Mahavilachchiya Division', 'ANDI', 'ry-wc-city-select'),
		_x('Medawachchiya Division', 'ANDI', 'ry-wc-city-select'),
		_x('Mihinthale', 'ANDI', 'ry-wc-city-select'),
		_x('Nachchaduwa Division', 'ANDI', 'ry-wc-city-select'),
		_x('Nochchiyagama Division', 'ANDI', 'ry-wc-city-select'),
		_x('Nuwaragam Palata Central Division', 'ANDI', 'ry-wc-city-select'),
		_x('Padawiya Division', 'ANDI', 'ry-wc-city-select'),
		_x('Palagala Division', 'ANDI', 'ry-wc-city-select'),
		_x('Palugaswewa Division', 'ANDI', 'ry-wc-city-select'),
		_x('Rajangana Division', 'ANDI', 'ry-wc-city-select'),
		_x('Rambewa Divison', 'ANDI', 'ry-wc-city-select'),
		_x('Talawa Division', 'ANDI', 'ry-wc-city-select'),
		_x('Tambuttegama Division', 'ANDI', 'ry-wc-city-select'),
		_x('Thirappane', 'ANDI', 'ry-wc-city-select'),
	],
	'BADI' => [
		_x('Badulla Division', 'BADI', 'ry-wc-city-select'),
		_x('Bandarawela Division', 'BADI', 'ry-wc-city-select'),
		_x('Ella Division', 'BADI', 'ry-wc-city-select'),
		_x('Haldummulla Division', 'BADI', 'ry-wc-city-select'),
		_x('Hali Ela Division', 'BADI', 'ry-wc-city-select'),
		_x('Haputale Division', 'BADI', 'ry-wc-city-select'),
		_x('Kandeketiya', 'BADI', 'ry-wc-city-select'),
		_x('Lunugala Division', 'BADI', 'ry-wc-city-select'),
		_x('Mahiyanganaya', 'BADI', 'ry-wc-city-select'),
		_x('Meegahakiula', 'BADI', 'ry-wc-city-select'),
		_x('Passara Division', 'BADI', 'ry-wc-city-select'),
		_x('Rideemaliyadda', 'BADI', 'ry-wc-city-select'),
		_x('Soranathota', 'BADI', 'ry-wc-city-select'),
		_x('Uva Paranagama Division', 'BADI', 'ry-wc-city-select'),
		_x('Welimada Division', 'BADI', 'ry-wc-city-select'),
	],
	'BADI2' => [
		_x('Eravur Pattu', 'BADI2', 'ry-wc-city-select'),
		_x('Eravur Town Division', 'BADI2', 'ry-wc-city-select'),
		_x('Kattankudy Division', 'BADI2', 'ry-wc-city-select'),
		_x('Koralai Pattu', 'BADI2', 'ry-wc-city-select'),
		_x('Koralai Pattu Cent', 'BADI2', 'ry-wc-city-select'),
		_x('Koralai Pattu Nort', 'BADI2', 'ry-wc-city-select'),
		_x('Koralai Pattu Sout', 'BADI2', 'ry-wc-city-select'),
		_x('Koralai Pattu West', 'BADI2', 'ry-wc-city-select'),
		_x('Manmunai North Division', 'BADI2', 'ry-wc-city-select'),
		_x('Manmunai Pattu', 'BADI2', 'ry-wc-city-select'),
		_x('Manmunai South & East', 'BADI2', 'ry-wc-city-select'),
		_x('Manmunai South West', 'BADI2', 'ry-wc-city-select'),
		_x('Manmunai West', 'BADI2', 'ry-wc-city-select'),
		_x('Porativu Pattu', 'BADI2', 'ry-wc-city-select'),
	],
	'CODI' => [
		_x('Colombo Division', 'CODI', 'ry-wc-city-select'),
		_x('Dehiwala', 'CODI', 'ry-wc-city-select'),
		_x('Homagama Division', 'CODI', 'ry-wc-city-select'),
		_x('Kaduwela Division', 'CODI', 'ry-wc-city-select'),
		_x('Kesbewa Division', 'CODI', 'ry-wc-city-select'),
		_x('Kolonnawa Division', 'CODI', 'ry-wc-city-select'),
		_x('Maharagama', 'CODI', 'ry-wc-city-select'),
		_x('Moratuwa Division', 'CODI', 'ry-wc-city-select'),
		_x('Padukka', 'CODI', 'ry-wc-city-select'),
		_x('Ratmalana', 'CODI', 'ry-wc-city-select'),
		_x('Seethawaka', 'CODI', 'ry-wc-city-select'),
		_x('Sri Jayawardanapur', 'CODI', 'ry-wc-city-select'),
		_x('Thimbirigasyaya', 'CODI', 'ry-wc-city-select'),
	],
	'GADI' => [
		_x('Akmeemana Division', 'GADI', 'ry-wc-city-select'),
		_x('Ambalangoda', 'GADI', 'ry-wc-city-select'),
		_x('Baddegama', 'GADI', 'ry-wc-city-select'),
		_x('Balapitiya', 'GADI', 'ry-wc-city-select'),
		_x('Bentota Division', 'GADI', 'ry-wc-city-select'),
		_x('Bope Poddala Division', 'GADI', 'ry-wc-city-select'),
		_x('Elpitiya', 'GADI', 'ry-wc-city-select'),
		_x('Galle Four Gravets Division', 'GADI', 'ry-wc-city-select'),
		_x('Gonapinuwala', 'GADI', 'ry-wc-city-select'),
		_x('Habaraduwa Division', 'GADI', 'ry-wc-city-select'),
		_x('Hikkaduwa', 'GADI', 'ry-wc-city-select'),
		_x('Imaduwa Division', 'GADI', 'ry-wc-city-select'),
		_x('Karandeniya', 'GADI', 'ry-wc-city-select'),
		_x('Nagoda', 'GADI', 'ry-wc-city-select'),
		_x('Neluwa Division', 'GADI', 'ry-wc-city-select'),
		_x('Niyagama', 'GADI', 'ry-wc-city-select'),
		_x('Thawalama', 'GADI', 'ry-wc-city-select'),
		_x('Welivitiya-Divitur', 'GADI', 'ry-wc-city-select'),
		_x('Yakkalamulla', 'GADI', 'ry-wc-city-select'),
	],
	'GADI2' => [
		_x('Attanagalla Division', 'GADI2', 'ry-wc-city-select'),
		_x('Biyagama Division', 'GADI2', 'ry-wc-city-select'),
		_x('Divulapitiya Division', 'GADI2', 'ry-wc-city-select'),
		_x('Dompe', 'GADI2', 'ry-wc-city-select'),
		_x('Gampaha Division', 'GADI2', 'ry-wc-city-select'),
		_x('Ja-Ela Division', 'GADI2', 'ry-wc-city-select'),
		_x('Katana Division', 'GADI2', 'ry-wc-city-select'),
		_x('Kelaniya Division', 'GADI2', 'ry-wc-city-select'),
		_x('Mahara Division', 'GADI2', 'ry-wc-city-select'),
		_x('Minuwangoda Division', 'GADI2', 'ry-wc-city-select'),
		_x('Mirigama Division', 'GADI2', 'ry-wc-city-select'),
		_x('Negombo Division', 'GADI2', 'ry-wc-city-select'),
		_x('Wattala Division', 'GADI2', 'ry-wc-city-select'),
	],
	'HADI' => [
		_x('Ambalantota Division', 'HADI', 'ry-wc-city-select'),
		_x('Angunakolapelessa Division', 'HADI', 'ry-wc-city-select'),
		_x('Beliatta', 'HADI', 'ry-wc-city-select'),
		_x('Hambantota Division', 'HADI', 'ry-wc-city-select'),
		_x('Katuwana Division', 'HADI', 'ry-wc-city-select'),
		_x('Lunugamwehera', 'HADI', 'ry-wc-city-select'),
		_x('Okawela Division', 'HADI', 'ry-wc-city-select'),
		_x('Suriyawewa Division', 'HADI', 'ry-wc-city-select'),
		_x('Tangalle', 'HADI', 'ry-wc-city-select'),
		_x('Thissamaharama', 'HADI', 'ry-wc-city-select'),
		_x('Walasmulla', 'HADI', 'ry-wc-city-select'),
		_x('Weeraketiya Division', 'HADI', 'ry-wc-city-select'),
	],
	'JADI' => [
		_x('Delft', 'JADI', 'ry-wc-city-select'),
		_x('Islands North Division', 'JADI', 'ry-wc-city-select'),
		_x('Islands South Division', 'JADI', 'ry-wc-city-select'),
		_x('Jaffna Division', 'JADI', 'ry-wc-city-select'),
		_x('Karainagar', 'JADI', 'ry-wc-city-select'),
		_x('Nallur Division', 'JADI', 'ry-wc-city-select'),
		_x('Thenmaradchchi Division', 'JADI', 'ry-wc-city-select'),
		_x('Vadamaradchchi East Division', 'JADI', 'ry-wc-city-select'),
		_x('Vadamaradchchi Sou', 'JADI', 'ry-wc-city-select'),
		_x('Vadamaradchi North', 'JADI', 'ry-wc-city-select'),
		_x('Valikamam East', 'JADI', 'ry-wc-city-select'),
		_x('Valikamam North Division', 'JADI', 'ry-wc-city-select'),
		_x('Valikamam South Division', 'JADI', 'ry-wc-city-select'),
		_x('Valikamam South West Division', 'JADI', 'ry-wc-city-select'),
		_x('Valikamam West Division', 'JADI', 'ry-wc-city-select'),
	],
	'KADI' => [
		_x('Agalawatta Division', 'KADI', 'ry-wc-city-select'),
		_x('Bandaragama Division', 'KADI', 'ry-wc-city-select'),
		_x('Beruwala Division', 'KADI', 'ry-wc-city-select'),
		_x('Bulathsinhala Division', 'KADI', 'ry-wc-city-select'),
		_x('Dodangoda Division', 'KADI', 'ry-wc-city-select'),
		_x('Horana Division', 'KADI', 'ry-wc-city-select'),
		_x('Ingiriya Division', 'KADI', 'ry-wc-city-select'),
		_x('Kalutara Division', 'KADI', 'ry-wc-city-select'),
		_x('Madurawala Division', 'KADI', 'ry-wc-city-select'),
		_x('Matugama Division', 'KADI', 'ry-wc-city-select'),
		_x('Millaniya Division', 'KADI', 'ry-wc-city-select'),
		_x('Palinda Nuwara Division', 'KADI', 'ry-wc-city-select'),
		_x('Panadura Division', 'KADI', 'ry-wc-city-select'),
		_x('Walallawita Division', 'KADI', 'ry-wc-city-select'),
	],
	'KADI2' => [
		_x('Akurana Division', 'KADI2', 'ry-wc-city-select'),
		_x('Deltota Division', 'KADI2', 'ry-wc-city-select'),
		_x('Doluwa Division', 'KADI2', 'ry-wc-city-select'),
		_x('Ganga Ihala Korale Division', 'KADI2', 'ry-wc-city-select'),
		_x('Harispattuwa Division', 'KADI2', 'ry-wc-city-select'),
		_x('Hatharaliyadda', 'KADI2', 'ry-wc-city-select'),
		_x('Kandy and Four Gravets Gangawata Divisio', 'KADI2', 'ry-wc-city-select'),
		_x('Kundasale Division', 'KADI2', 'ry-wc-city-select'),
		_x('Medadumbara', 'KADI2', 'ry-wc-city-select'),
		_x('Minipe', 'KADI2', 'ry-wc-city-select'),
		_x('Panwila Division', 'KADI2', 'ry-wc-city-select'),
		_x('Pasbagekorale', 'KADI2', 'ry-wc-city-select'),
		_x('Patadumbara Division', 'KADI2', 'ry-wc-city-select'),
		_x('Patahewaheta Division', 'KADI2', 'ry-wc-city-select'),
		_x('Pujapitiya Division', 'KADI2', 'ry-wc-city-select'),
		_x('Thumpane Division', 'KADI2', 'ry-wc-city-select'),
		_x('Uda Palata Division', 'KADI2', 'ry-wc-city-select'),
		_x('Ududumbara', 'KADI2', 'ry-wc-city-select'),
		_x('Udunuwara Division', 'KADI2', 'ry-wc-city-select'),
		_x('Yatinuwara Division', 'KADI2', 'ry-wc-city-select'),
	],
	'KEDI' => [
		_x('Aranayaka Division', 'KEDI', 'ry-wc-city-select'),
		_x('Bulathkohupitiya Division', 'KEDI', 'ry-wc-city-select'),
		_x('Dehiowita', 'KEDI', 'ry-wc-city-select'),
		_x('Deraniyagala', 'KEDI', 'ry-wc-city-select'),
		_x('Galigamuwa', 'KEDI', 'ry-wc-city-select'),
		_x('Kegalla Division', 'KEDI', 'ry-wc-city-select'),
		_x('Mawanella Division', 'KEDI', 'ry-wc-city-select'),
		_x('Rambukkana Division', 'KEDI', 'ry-wc-city-select'),
		_x('Ruwanwella Division', 'KEDI', 'ry-wc-city-select'),
		_x('Warakapola Division', 'KEDI', 'ry-wc-city-select'),
		_x('Yatiyantota Division', 'KEDI', 'ry-wc-city-select'),
	],
	'KIDI' => [
		_x('Kandavalai', 'KIDI', 'ry-wc-city-select'),
		_x('Karachchi Division', 'KIDI', 'ry-wc-city-select'),
		_x('Pachchilaipallai Division', 'KIDI', 'ry-wc-city-select'),
		_x('Poonakary Division', 'KIDI', 'ry-wc-city-select'),
	],
	'KUDI' => [
		_x('Alawwa Division', 'KUDI', 'ry-wc-city-select'),
		_x('Ambanpola Division', 'KUDI', 'ry-wc-city-select'),
		_x('Bamunakotuwa', 'KUDI', 'ry-wc-city-select'),
		_x('Bingiriya Division', 'KUDI', 'ry-wc-city-select'),
		_x('Ehetuwewa Division', 'KUDI', 'ry-wc-city-select'),
		_x('Galgamuwa Division', 'KUDI', 'ry-wc-city-select'),
		_x('Ganewatta Division', 'KUDI', 'ry-wc-city-select'),
		_x('Giribawa Division', 'KUDI', 'ry-wc-city-select'),
		_x('Ibbagamuwa Division', 'KUDI', 'ry-wc-city-select'),
		_x('Kobeigane', 'KUDI', 'ry-wc-city-select'),
		_x('Kotawehera', 'KUDI', 'ry-wc-city-select'),
		_x('Kuliyapitiya East Division', 'KUDI', 'ry-wc-city-select'),
		_x('Kuliyapitiya West Division', 'KUDI', 'ry-wc-city-select'),
		_x('Kurunegala Division', 'KUDI', 'ry-wc-city-select'),
		_x('Maho', 'KUDI', 'ry-wc-city-select'),
		_x('Mallawapitiya Division', 'KUDI', 'ry-wc-city-select'),
		_x('Maspota Division', 'KUDI', 'ry-wc-city-select'),
		_x('Mawathagama Division', 'KUDI', 'ry-wc-city-select'),
		_x('Narammala Division', 'KUDI', 'ry-wc-city-select'),
		_x('Nikaweratiya', 'KUDI', 'ry-wc-city-select'),
		_x('Panduwasnuwara Division', 'KUDI', 'ry-wc-city-select'),
		_x('Panduwasnuwara East', 'KUDI', 'ry-wc-city-select'),
		_x('Pannala Division', 'KUDI', 'ry-wc-city-select'),
		_x('Polgahawela Division', 'KUDI', 'ry-wc-city-select'),
		_x('Polpitigama', 'KUDI', 'ry-wc-city-select'),
		_x('Rasnayakapura Division', 'KUDI', 'ry-wc-city-select'),
		_x('Ridigama Division', 'KUDI', 'ry-wc-city-select'),
		_x('Udubaddawa Division', 'KUDI', 'ry-wc-city-select'),
		_x('Wariyapola Division', 'KUDI', 'ry-wc-city-select'),
		_x('Weerambugedera Division', 'KUDI', 'ry-wc-city-select'),
	],
	'MADI' => [
		_x('Madhu', 'MADI', 'ry-wc-city-select'),
		_x('Mannar Town', 'MADI', 'ry-wc-city-select'),
		_x('Manthai West Division', 'MADI', 'ry-wc-city-select'),
		_x('Musali Division', 'MADI', 'ry-wc-city-select'),
		_x('Nanaddan', 'MADI', 'ry-wc-city-select'),
	],
	'MADI2' => [
		_x('Ambanganga Korale Division', 'MADI2', 'ry-wc-city-select'),
		_x('Dambulla', 'MADI2', 'ry-wc-city-select'),
		_x('Galewela', 'MADI2', 'ry-wc-city-select'),
		_x('Laggala', 'MADI2', 'ry-wc-city-select'),
		_x('Matale Division', 'MADI2', 'ry-wc-city-select'),
		_x('Naula', 'MADI2', 'ry-wc-city-select'),
		_x('Pallepola Division', 'MADI2', 'ry-wc-city-select'),
		_x('Rattota Division', 'MADI2', 'ry-wc-city-select'),
		_x('Ukuwela Division', 'MADI2', 'ry-wc-city-select'),
		_x('Wilgamuwa', 'MADI2', 'ry-wc-city-select'),
		_x('Yatawatta Division', 'MADI2', 'ry-wc-city-select'),
	],
	'MADI3' => [
		_x('Akuressa Division', 'MADI3', 'ry-wc-city-select'),
		_x('Aturaliya Division', 'MADI3', 'ry-wc-city-select'),
		_x('Devinuwara', 'MADI3', 'ry-wc-city-select'),
		_x('Dikwella', 'MADI3', 'ry-wc-city-select'),
		_x('Hakmana Division', 'MADI3', 'ry-wc-city-select'),
		_x('Kaburupitiya', 'MADI3', 'ry-wc-city-select'),
		_x('Kirinda Puhulwella', 'MADI3', 'ry-wc-city-select'),
		_x('Kotapola Division', 'MADI3', 'ry-wc-city-select'),
		_x('Malimbada', 'MADI3', 'ry-wc-city-select'),
		_x('Matara Four Gravet', 'MADI3', 'ry-wc-city-select'),
		_x('Mulatiyana Division', 'MADI3', 'ry-wc-city-select'),
		_x('Pasgoda Division', 'MADI3', 'ry-wc-city-select'),
		_x('Pitabeddara Division', 'MADI3', 'ry-wc-city-select'),
		_x('Thihagoda', 'MADI3', 'ry-wc-city-select'),
		_x('Weligama', 'MADI3', 'ry-wc-city-select'),
		_x('Welipitiya', 'MADI3', 'ry-wc-city-select'),
	],
	'MODI' => [
		_x('Badalkumbura Division', 'MODI', 'ry-wc-city-select'),
		_x('Bibile Division', 'MODI', 'ry-wc-city-select'),
		_x('Buttala Division', 'MODI', 'ry-wc-city-select'),
		_x('Katharagama', 'MODI', 'ry-wc-city-select'),
		_x('Madulla Division', 'MODI', 'ry-wc-city-select'),
		_x('Medagama Division', 'MODI', 'ry-wc-city-select'),
		_x('Monaragala Division', 'MODI', 'ry-wc-city-select'),
		_x('Sevanagala Division', 'MODI', 'ry-wc-city-select'),
		_x('Siyambalanduwa Division', 'MODI', 'ry-wc-city-select'),
		_x('Tanamalwila Division', 'MODI', 'ry-wc-city-select'),
		_x('Wellawaya Division', 'MODI', 'ry-wc-city-select'),
	],
	'MUDI' => [
		_x('Manthai East', 'MUDI', 'ry-wc-city-select'),
		_x('Maritimepattu', 'MUDI', 'ry-wc-city-select'),
		_x('Oddusuddan', 'MUDI', 'ry-wc-city-select'),
		_x('Puthukkudiyiruppu Division', 'MUDI', 'ry-wc-city-select'),
		_x('Thunukkai Divisional Secretariat', 'MUDI', 'ry-wc-city-select'),
		_x('Welioya', 'MUDI', 'ry-wc-city-select'),
	],
	'NUELDI' => [
		_x('Ambagamuwa Division', 'NUELDI', 'ry-wc-city-select'),
		_x('Hanguranketa', 'NUELDI', 'ry-wc-city-select'),
		_x('Kotmale Division', 'NUELDI', 'ry-wc-city-select'),
		_x('Nuwara Eliya Division', 'NUELDI', 'ry-wc-city-select'),
		_x('Walapane', 'NUELDI', 'ry-wc-city-select'),
	],
	'PODI' => [
		_x('Dimbulagala', 'PODI', 'ry-wc-city-select'),
		_x('Elahera', 'PODI', 'ry-wc-city-select'),
		_x('Higurakgoda', 'PODI', 'ry-wc-city-select'),
		_x('Lankapura', 'PODI', 'ry-wc-city-select'),
		_x('Medirigiriya Division', 'PODI', 'ry-wc-city-select'),
		_x('Thamankaduwa', 'PODI', 'ry-wc-city-select'),
		_x('Welikanda', 'PODI', 'ry-wc-city-select'),
	],
	'PUDI' => [
		_x('Anamaduwa Division', 'PUDI', 'ry-wc-city-select'),
		_x('Arachchikattuwa Division', 'PUDI', 'ry-wc-city-select'),
		_x('Chilaw Division', 'PUDI', 'ry-wc-city-select'),
		_x('Dankotuwa Division', 'PUDI', 'ry-wc-city-select'),
		_x('Kalpitiya Division', 'PUDI', 'ry-wc-city-select'),
		_x('Karuwalagaswewa Division', 'PUDI', 'ry-wc-city-select'),
		_x('Madampe Division', 'PUDI', 'ry-wc-city-select'),
		_x('Mahakumbukkadawala Division', 'PUDI', 'ry-wc-city-select'),
		_x('Mahawewa Division', 'PUDI', 'ry-wc-city-select'),
		_x('Mundel Division', 'PUDI', 'ry-wc-city-select'),
		_x('Nattandiya Division', 'PUDI', 'ry-wc-city-select'),
		_x('Nawagattegama Division', 'PUDI', 'ry-wc-city-select'),
		_x('Pallama Division', 'PUDI', 'ry-wc-city-select'),
		_x('Puttalam Division', 'PUDI', 'ry-wc-city-select'),
		_x('Vanathavillu Division', 'PUDI', 'ry-wc-city-select'),
		_x('Wennappuwa Division', 'PUDI', 'ry-wc-city-select'),
	],
	'RADI' => [
		_x('Ayagama Division', 'RADI', 'ry-wc-city-select'),
		_x('Balangoda Division', 'RADI', 'ry-wc-city-select'),
		_x('Eheliyagoda', 'RADI', 'ry-wc-city-select'),
		_x('Elapatha Division', 'RADI', 'ry-wc-city-select'),
		_x('Embilipitiya Division', 'RADI', 'ry-wc-city-select'),
		_x('Godakawela Division', 'RADI', 'ry-wc-city-select'),
		_x('Imbulpe Division', 'RADI', 'ry-wc-city-select'),
		_x('Kahawatta Division', 'RADI', 'ry-wc-city-select'),
		_x('Kalawana Division', 'RADI', 'ry-wc-city-select'),
		_x('Kiriella Division', 'RADI', 'ry-wc-city-select'),
		_x('Kolonna Division', 'RADI', 'ry-wc-city-select'),
		_x('Kuruvita', 'RADI', 'ry-wc-city-select'),
		_x('Nivithigala Division', 'RADI', 'ry-wc-city-select'),
		_x('Opanayaka Division', 'RADI', 'ry-wc-city-select'),
		_x('Pelmadulla Division', 'RADI', 'ry-wc-city-select'),
		_x('Ratnapura Division', 'RADI', 'ry-wc-city-select'),
		_x('Weligepola Division', 'RADI', 'ry-wc-city-select'),
	],
	'TRDI' => [
		_x('Gomarankadawela Division', 'TRDI', 'ry-wc-city-select'),
		_x('Kantale', 'TRDI', 'ry-wc-city-select'),
		_x('Kinniya', 'TRDI', 'ry-wc-city-select'),
		_x('Kuchchaveli Division', 'TRDI', 'ry-wc-city-select'),
		_x('Morawewa Division', 'TRDI', 'ry-wc-city-select'),
		_x('Muthur', 'TRDI', 'ry-wc-city-select'),
		_x('Padavi Sri Pura', 'TRDI', 'ry-wc-city-select'),
		_x('Seruvila', 'TRDI', 'ry-wc-city-select'),
		_x('Tampalakamam Division', 'TRDI', 'ry-wc-city-select'),
		_x('Trincomalee Town and Gravets Division', 'TRDI', 'ry-wc-city-select'),
		_x('Verugal', 'TRDI', 'ry-wc-city-select'),
	],
	'VADI' => [
		_x('Vavuniya', 'VADI', 'ry-wc-city-select'),
		_x('Vavuniya North', 'VADI', 'ry-wc-city-select'),
		_x('Vavuniya South Division', 'VADI', 'ry-wc-city-select'),
		_x('Venkalacheddikulam Division', 'VADI', 'ry-wc-city-select'),
	],
	]
];