<?php
/**
 * Republic of Liberia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'LR' => [
	'BOCO' => [
		_x('Dei', 'BOCO', 'ry-wc-city-select'),
		_x('Dowein District', 'BOCO', 'ry-wc-city-select'),
		_x('Gola', 'BOCO', 'ry-wc-city-select'),
		_x('Klay District', 'BOCO', 'ry-wc-city-select'),
		_x('Senjeh District', 'BOCO', 'ry-wc-city-select'),
		_x('Suehn Mecca District', 'BOCO', 'ry-wc-city-select'),
	],
	'BOCO2' => [
		_x('Boinsen District', 'BOCO2', 'ry-wc-city-select'),
		_x('Fuamah', 'BOCO2', 'ry-wc-city-select'),
		_x('Jorquelleh', 'BOCO2', 'ry-wc-city-select'),
		_x('Jorquelleh', 'BOCO2', 'ry-wc-city-select'),
		_x('Kokoyah', 'BOCO2', 'ry-wc-city-select'),
		_x('Kpaai District', 'BOCO2', 'ry-wc-city-select'),
		_x('Nyafokole', 'BOCO2', 'ry-wc-city-select'),
		_x('Panta', 'BOCO2', 'ry-wc-city-select'),
		_x('Salala', 'BOCO2', 'ry-wc-city-select'),
		_x('Sanoyeah', 'BOCO2', 'ry-wc-city-select'),
		_x('Suakoko', 'BOCO2', 'ry-wc-city-select'),
		_x('Tukpahblee District', 'BOCO2', 'ry-wc-city-select'),
		_x('Yeallequelleh District', 'BOCO2', 'ry-wc-city-select'),
		_x('Zota', 'BOCO2', 'ry-wc-city-select'),
	],
	'GBCO' => [
		_x('Belleh', 'GBCO', 'ry-wc-city-select'),
		_x('Bokomu', 'GBCO', 'ry-wc-city-select'),
		_x('Bopolu', 'GBCO', 'ry-wc-city-select'),
		_x('Gbarma District', 'GBCO', 'ry-wc-city-select'),
		_x('Goije', 'GBCO', 'ry-wc-city-select'),
		_x('Gounwolaila District', 'GBCO', 'ry-wc-city-select'),
		_x('Kongba District', 'GBCO', 'ry-wc-city-select'),
	],
	'GRBACO' => [
		_x('Campwood', 'GRBACO', 'ry-wc-city-select'),
		_x('Commonwealth District', 'GRBACO', 'ry-wc-city-select'),
		_x('District #1', 'GRBACO', 'ry-wc-city-select'),
		_x('District #2', 'GRBACO', 'ry-wc-city-select'),
		_x('District #3', 'GRBACO', 'ry-wc-city-select'),
		_x('District Number Four', 'GRBACO', 'ry-wc-city-select'),
		_x('District Number One', 'GRBACO', 'ry-wc-city-select'),
		_x('District Number Three', 'GRBACO', 'ry-wc-city-select'),
		_x('District Number Two', 'GRBACO', 'ry-wc-city-select'),
		_x('Five A', 'GRBACO', 'ry-wc-city-select'),
		_x('Glarkon', 'GRBACO', 'ry-wc-city-select'),
		_x('Jayah', 'GRBACO', 'ry-wc-city-select'),
		_x('Neekreen District', 'GRBACO', 'ry-wc-city-select'),
		_x('Owensgrove District', 'GRBACO', 'ry-wc-city-select'),
		_x('Saint John River City District', 'GRBACO', 'ry-wc-city-select'),
		_x('Tenor', 'GRBACO', 'ry-wc-city-select'),
		_x('Three A', 'GRBACO', 'ry-wc-city-select'),
		_x('Three B', 'GRBACO', 'ry-wc-city-select'),
		_x('Trade Town', 'GRBACO', 'ry-wc-city-select'),
	],
	'GRCAMOCO' => [
		_x('Commonwealth District', 'GRCAMOCO', 'ry-wc-city-select'),
		_x('Garwula', 'GRCAMOCO', 'ry-wc-city-select'),
		_x('Gola Konneh', 'GRCAMOCO', 'ry-wc-city-select'),
		_x('Kone', 'GRCAMOCO', 'ry-wc-city-select'),
		_x('Porkpa District', 'GRCAMOCO', 'ry-wc-city-select'),
		_x('Robertsport District', 'GRCAMOCO', 'ry-wc-city-select'),
		_x('Tewor', 'GRCAMOCO', 'ry-wc-city-select'),
		_x('Tombe', 'GRCAMOCO', 'ry-wc-city-select'),
	],
	'GRGECO' => [
		_x('Bhai District', 'GRGECO', 'ry-wc-city-select'),
		_x('Cavala District', 'GRGECO', 'ry-wc-city-select'),
		_x('Gbao District', 'GRGECO', 'ry-wc-city-select'),
		_x('Gbazohn', 'GRGECO', 'ry-wc-city-select'),
		_x('Gbobo', 'GRGECO', 'ry-wc-city-select'),
		_x('Gboe-Ploe District', 'GRGECO', 'ry-wc-city-select'),
		_x('Glio-Twarbo', 'GRGECO', 'ry-wc-city-select'),
		_x('Konobo', 'GRGECO', 'ry-wc-city-select'),
		_x('Niabo', 'GRGECO', 'ry-wc-city-select'),
		_x('Putu', 'GRGECO', 'ry-wc-city-select'),
		_x('Tchien', 'GRGECO', 'ry-wc-city-select'),
	],
	'GRKRCO' => [
		_x('Barclayville', 'GRKRCO', 'ry-wc-city-select'),
		_x('Bleebo District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Bolloh District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Buah', 'GRKRCO', 'ry-wc-city-select'),
		_x('Dorbor District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Dweh District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Felo-Jekwi District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Fenetoe District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Forpoh District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Garraway', 'GRKRCO', 'ry-wc-city-select'),
		_x('Grand Cess Wedabo', 'GRKRCO', 'ry-wc-city-select'),
		_x('Kpi District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Lower Jloh', 'GRKRCO', 'ry-wc-city-select'),
		_x('Nrokwia-Wesldow District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Sasstown', 'GRKRCO', 'ry-wc-city-select'),
		_x('Trenbo District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Upper Jloh District', 'GRKRCO', 'ry-wc-city-select'),
		_x('Webado', 'GRKRCO', 'ry-wc-city-select'),
		_x('Wlogba District', 'GRKRCO', 'ry-wc-city-select'),
	],
	'LOCO' => [
		_x('Bonde-Wubomai', 'LOCO', 'ry-wc-city-select'),
		_x('Foya District', 'LOCO', 'ry-wc-city-select'),
		_x('Gbalein Faala', 'LOCO', 'ry-wc-city-select'),
		_x('Gbandi', 'LOCO', 'ry-wc-city-select'),
		_x('Gizima-Ziema', 'LOCO', 'ry-wc-city-select'),
		_x('Guma', 'LOCO', 'ry-wc-city-select'),
		_x('Guma-Mendi', 'LOCO', 'ry-wc-city-select'),
		_x('Kambo Hills', 'LOCO', 'ry-wc-city-select'),
		_x('Kisi', 'LOCO', 'ry-wc-city-select'),
		_x('Kolahun District', 'LOCO', 'ry-wc-city-select'),
		_x('Quardu Gboni District', 'LOCO', 'ry-wc-city-select'),
		_x('Salayea District', 'LOCO', 'ry-wc-city-select'),
		_x('Vahun District', 'LOCO', 'ry-wc-city-select'),
		_x('Voinjama District', 'LOCO', 'ry-wc-city-select'),
		_x('Waiglomai-Woniglomai', 'LOCO', 'ry-wc-city-select'),
		_x('Zorzor District', 'LOCO', 'ry-wc-city-select'),
	],
	'MACO' => [
		_x('Firestone', 'MACO', 'ry-wc-city-select'),
		_x('Gibi', 'MACO', 'ry-wc-city-select'),
		_x('Mambah Kaba', 'MACO', 'ry-wc-city-select'),
	],
	'MACO2' => [
		_x('Barobo', 'MACO2', 'ry-wc-city-select'),
		_x('Bolobo', 'MACO2', 'ry-wc-city-select'),
		_x('Cavalla', 'MACO2', 'ry-wc-city-select'),
		_x('Dedabo', 'MACO2', 'ry-wc-city-select'),
		_x('Dorobo', 'MACO2', 'ry-wc-city-select'),
		_x('Firestone', 'MACO2', 'ry-wc-city-select'),
		_x('Flenipo', 'MACO2', 'ry-wc-city-select'),
		_x('Gbarlobo', 'MACO2', 'ry-wc-city-select'),
		_x('Gbelakpo', 'MACO2', 'ry-wc-city-select'),
		_x('Gbeta Klepo', 'MACO2', 'ry-wc-city-select'),
		_x('Gedabo', 'MACO2', 'ry-wc-city-select'),
		_x('Gedetarbo', 'MACO2', 'ry-wc-city-select'),
		_x('Glebo', 'MACO2', 'ry-wc-city-select'),
		_x('Grawa', 'MACO2', 'ry-wc-city-select'),
		_x('Gwelekpoken District', 'MACO2', 'ry-wc-city-select'),
		_x('Karluway Number One District', 'MACO2', 'ry-wc-city-select'),
		_x('Karluway Number Two District', 'MACO2', 'ry-wc-city-select'),
		_x('Little Wrebo', 'MACO2', 'ry-wc-city-select'),
		_x('Nemea', 'MACO2', 'ry-wc-city-select'),
		_x('Nyanbo', 'MACO2', 'ry-wc-city-select'),
		_x('Nyorken District', 'MACO2', 'ry-wc-city-select'),
		_x('Pate', 'MACO2', 'ry-wc-city-select'),
		_x('Picnicess', 'MACO2', 'ry-wc-city-select'),
		_x('Pleebo/Sodeken District', 'MACO2', 'ry-wc-city-select'),
		_x('Pleebo/Sodoken', 'MACO2', 'ry-wc-city-select'),
		_x('Po River', 'MACO2', 'ry-wc-city-select'),
		_x('Rock Town', 'MACO2', 'ry-wc-city-select'),
		_x('Sodoke', 'MACO2', 'ry-wc-city-select'),
		_x('Tuobo', 'MACO2', 'ry-wc-city-select'),
		_x('Whojah District', 'MACO2', 'ry-wc-city-select'),
		_x('Yederabo', 'MACO2', 'ry-wc-city-select'),
	],
	'MOCO' => [
		_x('Careysburg', 'MOCO', 'ry-wc-city-select'),
		_x('Commonwealth District', 'MOCO', 'ry-wc-city-select'),
		_x('Ding', 'MOCO', 'ry-wc-city-select'),
		_x('Greater Monrovia', 'MOCO', 'ry-wc-city-select'),
		_x('Kakata', 'MOCO', 'ry-wc-city-select'),
		_x('Mambah-Kaba', 'MOCO', 'ry-wc-city-select'),
		_x('Saint Paul River District', 'MOCO', 'ry-wc-city-select'),
		_x('St. Paul River', 'MOCO', 'ry-wc-city-select'),
		_x('Todee', 'MOCO', 'ry-wc-city-select'),
		_x('Topee', 'MOCO', 'ry-wc-city-select'),
	],
	'NICO' => [
		_x('Boe and Quilla District', 'NICO', 'ry-wc-city-select'),
		_x('Buu-Yao District', 'NICO', 'ry-wc-city-select'),
		_x('Doe', 'NICO', 'ry-wc-city-select'),
		_x('Garr-Bain District', 'NICO', 'ry-wc-city-select'),
		_x('Gbehlay-Geh', 'NICO', 'ry-wc-city-select'),
		_x('Gbi and Doru', 'NICO', 'ry-wc-city-select'),
		_x('Gbokole', 'NICO', 'ry-wc-city-select'),
		_x('Gbor District', 'NICO', 'ry-wc-city-select'),
		_x('Keaple', 'NICO', 'ry-wc-city-select'),
		_x('Kparblee District', 'NICO', 'ry-wc-city-select'),
		_x('Leewehpea-Mahn District', 'NICO', 'ry-wc-city-select'),
		_x('Meinpea-Mahn District', 'NICO', 'ry-wc-city-select'),
		_x('Saclepea-Mah', 'NICO', 'ry-wc-city-select'),
		_x('Sagleipie-Ma', 'NICO', 'ry-wc-city-select'),
		_x('Sanniquelleh- Mahn', 'NICO', 'ry-wc-city-select'),
		_x('Sanniquellie Mahn', 'NICO', 'ry-wc-city-select'),
		_x('Tappita', 'NICO', 'ry-wc-city-select'),
		_x('Twan River District', 'NICO', 'ry-wc-city-select'),
		_x('Wee-Gbehy-Mahn', 'NICO', 'ry-wc-city-select'),
		_x('Yarmein District', 'NICO', 'ry-wc-city-select'),
		_x('Yarpea Mahn District', 'NICO', 'ry-wc-city-select'),
		_x('Yarwein Mehnsonnoh', 'NICO', 'ry-wc-city-select'),
		_x('Zo-Ge', 'NICO', 'ry-wc-city-select'),
		_x('Zoe-Gbao District', 'NICO', 'ry-wc-city-select'),
	],
	'RICECO' => [
		_x('Beawor District', 'RICECO', 'ry-wc-city-select'),
		_x('Central River Cess District', 'RICECO', 'ry-wc-city-select'),
		_x('Doedain District', 'RICECO', 'ry-wc-city-select'),
		_x('Fen River District', 'RICECO', 'ry-wc-city-select'),
		_x('Jo River District', 'RICECO', 'ry-wc-city-select'),
		_x('Mowe', 'RICECO', 'ry-wc-city-select'),
		_x('Norwein District', 'RICECO', 'ry-wc-city-select'),
		_x('Rock Cess', 'RICECO', 'ry-wc-city-select'),
		_x('Sam Gbalor District', 'RICECO', 'ry-wc-city-select'),
		_x('Zarflahn District', 'RICECO', 'ry-wc-city-select'),
	],
	'RIGECO' => [
		_x('Chedepo', 'RIGECO', 'ry-wc-city-select'),
		_x('Gbeapo District', 'RIGECO', 'ry-wc-city-select'),
		_x('Glaro', 'RIGECO', 'ry-wc-city-select'),
		_x('Karforh District', 'RIGECO', 'ry-wc-city-select'),
		_x('Kitabo', 'RIGECO', 'ry-wc-city-select'),
		_x('Nanee District', 'RIGECO', 'ry-wc-city-select'),
		_x('Nyenawliken District', 'RIGECO', 'ry-wc-city-select'),
		_x('Nyenebo District', 'RIGECO', 'ry-wc-city-select'),
		_x('Palipo', 'RIGECO', 'ry-wc-city-select'),
		_x('Potupo District', 'RIGECO', 'ry-wc-city-select'),
		_x('Sarbo', 'RIGECO', 'ry-wc-city-select'),
		_x('Tienpo', 'RIGECO', 'ry-wc-city-select'),
		_x('Tuobo', 'RIGECO', 'ry-wc-city-select'),
		_x('Webbo District', 'RIGECO', 'ry-wc-city-select'),
	],
	'SICO' => [
		_x('Bodae District', 'SICO', 'ry-wc-city-select'),
		_x('Bokon District', 'SICO', 'ry-wc-city-select'),
		_x('Butaw', 'SICO', 'ry-wc-city-select'),
		_x('Dugbe River District', 'SICO', 'ry-wc-city-select'),
		_x('Greenville District', 'SICO', 'ry-wc-city-select'),
		_x('Jaedae District', 'SICO', 'ry-wc-city-select'),
		_x('Jeadepo', 'SICO', 'ry-wc-city-select'),
		_x('Jeetrah', 'SICO', 'ry-wc-city-select'),
		_x('Juarzon District', 'SICO', 'ry-wc-city-select'),
		_x('Kabor', 'SICO', 'ry-wc-city-select'),
		_x('Kpayan District', 'SICO', 'ry-wc-city-select'),
		_x('Kulu', 'SICO', 'ry-wc-city-select'),
		_x('Kulu Shaw Boe District', 'SICO', 'ry-wc-city-select'),
		_x('Matro', 'SICO', 'ry-wc-city-select'),
		_x('Nake', 'SICO', 'ry-wc-city-select'),
		_x('Nana Kru', 'SICO', 'ry-wc-city-select'),
		_x('Numo', 'SICO', 'ry-wc-city-select'),
		_x('Nuohn Point', 'SICO', 'ry-wc-city-select'),
		_x('Plahn Nyarn District', 'SICO', 'ry-wc-city-select'),
		_x('Pynes Town District', 'SICO', 'ry-wc-city-select'),
		_x('Pyneston District', 'SICO', 'ry-wc-city-select'),
		_x('Sanquin District Number One', 'SICO', 'ry-wc-city-select'),
		_x('Sanquin District Number Three', 'SICO', 'ry-wc-city-select'),
		_x('Sanquin District Number Two', 'SICO', 'ry-wc-city-select'),
		_x('Seedor', 'SICO', 'ry-wc-city-select'),
		_x('Seekon', 'SICO', 'ry-wc-city-select'),
		_x('Tarjuazon', 'SICO', 'ry-wc-city-select'),
		_x('Tasu', 'SICO', 'ry-wc-city-select'),
		_x('Topo', 'SICO', 'ry-wc-city-select'),
		_x('Toto', 'SICO', 'ry-wc-city-select'),
		_x('Wedjah District', 'SICO', 'ry-wc-city-select'),
		_x('Wedjah-Cabade', 'SICO', 'ry-wc-city-select'),
	],
	]
];