<?php
/**
 * Grand Duchy of Luxembourg places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'LU' => [
	'CADE' => [
		_x('Beaufort', 'CADE', 'ry-wc-city-select'),
		_x('Bech', 'CADE', 'ry-wc-city-select'),
		_x('Berdorf', 'CADE', 'ry-wc-city-select'),
		_x('Consdorf', 'CADE', 'ry-wc-city-select'),
		_x('Echternach', 'CADE', 'ry-wc-city-select'),
		_x('Mompach', 'CADE', 'ry-wc-city-select'),
		_x('Rosport', 'CADE', 'ry-wc-city-select'),
		_x('Waldbillig', 'CADE', 'ry-wc-city-select'),
	],
	'CADE2' => [
		_x('Bettembourg', 'CADE2', 'ry-wc-city-select'),
		_x('Differdange', 'CADE2', 'ry-wc-city-select'),
		_x('Dudelange', 'CADE2', 'ry-wc-city-select'),
		_x('Esch-sur-Alzette', 'CADE2', 'ry-wc-city-select'),
		_x('Frisange', 'CADE2', 'ry-wc-city-select'),
		_x('Kayl', 'CADE2', 'ry-wc-city-select'),
		_x('Leudelange', 'CADE2', 'ry-wc-city-select'),
		_x('Mondercange', 'CADE2', 'ry-wc-city-select'),
		_x('Petange', 'CADE2', 'ry-wc-city-select'),
		_x('Reckange-sur-Mess', 'CADE2', 'ry-wc-city-select'),
		_x('Roeser', 'CADE2', 'ry-wc-city-select'),
		_x('Rumelange', 'CADE2', 'ry-wc-city-select'),
		_x('Sanem', 'CADE2', 'ry-wc-city-select'),
		_x('Schifflange', 'CADE2', 'ry-wc-city-select'),
	],
	'CA' => [
		_x('Dippach', 'CA', 'ry-wc-city-select'),
		_x('Garnich', 'CA', 'ry-wc-city-select'),
		_x('Hobscheid', 'CA', 'ry-wc-city-select'),
		_x('Kaeerjeng', 'CA', 'ry-wc-city-select'),
		_x('Kehlen', 'CA', 'ry-wc-city-select'),
		_x('Koerich', 'CA', 'ry-wc-city-select'),
		_x('Kopstal', 'CA', 'ry-wc-city-select'),
		_x('Mamer', 'CA', 'ry-wc-city-select'),
		_x('Septfontaines', 'CA', 'ry-wc-city-select'),
		_x('Steinfort', 'CA', 'ry-wc-city-select'),
	],
	'CL' => [
		_x('Clervaux', 'CL', 'ry-wc-city-select'),
		_x('Parc Hosingen', 'CL', 'ry-wc-city-select'),
		_x('Troisvierges', 'CL', 'ry-wc-city-select'),
		_x('Weiswampach', 'CL', 'ry-wc-city-select'),
		_x('Wincrange', 'CL', 'ry-wc-city-select'),
	],
	'DI' => [
		_x('Aerenzdallgemeng', 'DI', 'ry-wc-city-select'),
		_x('Bettendorf', 'DI', 'ry-wc-city-select'),
		_x('Bourscheid', 'DI', 'ry-wc-city-select'),
		_x('Diekirch', 'DI', 'ry-wc-city-select'),
		_x('Erpeldange', 'DI', 'ry-wc-city-select'),
		_x('Ettelbruck', 'DI', 'ry-wc-city-select'),
		_x('Feulen', 'DI', 'ry-wc-city-select'),
		_x('Mertzig', 'DI', 'ry-wc-city-select'),
		_x('Reisdorf', 'DI', 'ry-wc-city-select'),
		_x('Schieren', 'DI', 'ry-wc-city-select'),
	],
	'GR' => [
		_x('Betzdorf', 'GR', 'ry-wc-city-select'),
		_x('Biwer', 'GR', 'ry-wc-city-select'),
		_x('Flaxweiler', 'GR', 'ry-wc-city-select'),
		_x('Grevenmacher', 'GR', 'ry-wc-city-select'),
		_x('Junglinster', 'GR', 'ry-wc-city-select'),
		_x('Manternach', 'GR', 'ry-wc-city-select'),
		_x('Mertert', 'GR', 'ry-wc-city-select'),
		_x('Wormeldange', 'GR', 'ry-wc-city-select'),
	],
	'LU' => [
		_x('Bertrange', 'LU', 'ry-wc-city-select'),
		_x('Contern', 'LU', 'ry-wc-city-select'),
		_x('Hesperange', 'LU', 'ry-wc-city-select'),
		_x('Niederanven', 'LU', 'ry-wc-city-select'),
		_x('Sandweiler', 'LU', 'ry-wc-city-select'),
		_x('Schuttrange', 'LU', 'ry-wc-city-select'),
		_x('Steinsel', 'LU', 'ry-wc-city-select'),
		_x('Strassen', 'LU', 'ry-wc-city-select'),
		_x('Ville de Luxembourg', 'LU', 'ry-wc-city-select'),
		_x('Walferdange', 'LU', 'ry-wc-city-select'),
		_x('Weiler-la-Tour', 'LU', 'ry-wc-city-select'),
	],
	'ME' => [
		_x('Berg', 'ME', 'ry-wc-city-select'),
		_x('Bissen', 'ME', 'ry-wc-city-select'),
		_x('Boevange-sur-Attert', 'ME', 'ry-wc-city-select'),
		_x('Fischbach', 'ME', 'ry-wc-city-select'),
		_x('Heffingen', 'ME', 'ry-wc-city-select'),
		_x('Larochette', 'ME', 'ry-wc-city-select'),
		_x('Lintgen', 'ME', 'ry-wc-city-select'),
		_x('Lorentzweiler', 'ME', 'ry-wc-city-select'),
		_x('Mersch', 'ME', 'ry-wc-city-select'),
		_x('Nommern', 'ME', 'ry-wc-city-select'),
		_x('Tuntange', 'ME', 'ry-wc-city-select'),
	],
	'RE' => [
		_x('Beckerich', 'RE', 'ry-wc-city-select'),
		_x('Commune de Preizerdaul', 'RE', 'ry-wc-city-select'),
		_x('Ell', 'RE', 'ry-wc-city-select'),
		_x('Grosbous', 'RE', 'ry-wc-city-select'),
		_x('Rambrouch', 'RE', 'ry-wc-city-select'),
		_x('Redange-sur-Attert', 'RE', 'ry-wc-city-select'),
		_x('Saeul', 'RE', 'ry-wc-city-select'),
		_x('Useldange', 'RE', 'ry-wc-city-select'),
		_x('Vichten', 'RE', 'ry-wc-city-select'),
		_x('Wahl', 'RE', 'ry-wc-city-select'),
	],
	'RE2' => [
		_x('Bous', 'RE2', 'ry-wc-city-select'),
		_x('Dalheim', 'RE2', 'ry-wc-city-select'),
		_x('Lenningen', 'RE2', 'ry-wc-city-select'),
		_x('Mondorf-les-Bains', 'RE2', 'ry-wc-city-select'),
		_x('Remich', 'RE2', 'ry-wc-city-select'),
		_x('Schengen', 'RE2', 'ry-wc-city-select'),
		_x('Stadtbredimus', 'RE2', 'ry-wc-city-select'),
		_x('Waldbredimus', 'RE2', 'ry-wc-city-select'),
	],
	'VI' => [
		_x('Putscheid', 'VI', 'ry-wc-city-select'),
		_x('Tandel', 'VI', 'ry-wc-city-select'),
		_x('Vianden', 'VI', 'ry-wc-city-select'),
	],
	'WI' => [
		_x('Boulaide', 'WI', 'ry-wc-city-select'),
		_x('Esch-sur-Sure', 'WI', 'ry-wc-city-select'),
		_x('Goesdorf', 'WI', 'ry-wc-city-select'),
		_x('Kiischpelt', 'WI', 'ry-wc-city-select'),
		_x('Lac de la Haute-Sure', 'WI', 'ry-wc-city-select'),
		_x('Wiltz', 'WI', 'ry-wc-city-select'),
		_x('Winseler', 'WI', 'ry-wc-city-select'),
	],
	]
];