<?php
/**
 * Republic of Latvia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'LV' => [
	'ADNO' => [
		_x('Adazu novads', 'ADNO', 'ry-wc-city-select'),
	],
	'AGNO' => [
		_x('Aglonas pagasts', 'AGNO', 'ry-wc-city-select'),
		_x('Graveru pagasts', 'AGNO', 'ry-wc-city-select'),
		_x('Kastulinas pagasts', 'AGNO', 'ry-wc-city-select'),
		_x('Skeltovas pagasts', 'AGNO', 'ry-wc-city-select'),
	],
	'AINO' => [
		_x('Aizkraukle', 'AINO', 'ry-wc-city-select'),
		_x('Aizkraukles pagasts', 'AINO', 'ry-wc-city-select'),
	],
	'AINO2' => [
		_x('Aizpute', 'AINO2', 'ry-wc-city-select'),
		_x('Aizputes pagasts', 'AINO2', 'ry-wc-city-select'),
		_x('Ciravas pagasts', 'AINO2', 'ry-wc-city-select'),
		_x('Kalvenes pagasts', 'AINO2', 'ry-wc-city-select'),
		_x('Kazdangas pagasts', 'AINO2', 'ry-wc-city-select'),
		_x('Lazas pagasts', 'AINO2', 'ry-wc-city-select'),
	],
	'AKNO' => [
		_x('Akniste', 'AKNO', 'ry-wc-city-select'),
		_x('Aknistes pagasts', 'AKNO', 'ry-wc-city-select'),
		_x('Asares pagasts', 'AKNO', 'ry-wc-city-select'),
		_x('Garsenes pagasts', 'AKNO', 'ry-wc-city-select'),
	],
	'ALNO' => [
		_x('Aloja', 'ALNO', 'ry-wc-city-select'),
		_x('Alojas pagasts', 'ALNO', 'ry-wc-city-select'),
		_x('Braslavas pagasts', 'ALNO', 'ry-wc-city-select'),
		_x('Brivzemnieku pagasts', 'ALNO', 'ry-wc-city-select'),
		_x('Staicele', 'ALNO', 'ry-wc-city-select'),
		_x('Staiceles pagasts', 'ALNO', 'ry-wc-city-select'),
	],
	'ALNO2' => [
		_x('Alsungas novads', 'ALNO2', 'ry-wc-city-select'),
	],
	'ALNO3' => [
		_x('Alsviku pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Aluksne', 'ALNO3', 'ry-wc-city-select'),
		_x('Annas pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Ilzenes pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Jaunaluksnes pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Jaunannas pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Jaunlaicenes pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Kalncempju pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Liepnas pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Malienas pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Malupes pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Markalnes pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Pededzes pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Veclaicenes pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Zeltinu pagasts', 'ALNO3', 'ry-wc-city-select'),
		_x('Ziemera pagasts', 'ALNO3', 'ry-wc-city-select'),
	],
	'AMNO' => [
		_x('Amatas pagasts', 'AMNO', 'ry-wc-city-select'),
		_x('Drabesu pagasts', 'AMNO', 'ry-wc-city-select'),
		_x('Nitaures pagasts', 'AMNO', 'ry-wc-city-select'),
		_x('Skujenes pagasts', 'AMNO', 'ry-wc-city-select'),
		_x('Zaubes pagasts', 'AMNO', 'ry-wc-city-select'),
	],
	'APNO' => [
		_x('Ape', 'APNO', 'ry-wc-city-select'),
		_x('Apes pagasts', 'APNO', 'ry-wc-city-select'),
		_x('Gaujienas pagasts', 'APNO', 'ry-wc-city-select'),
		_x('Trapenes pagasts', 'APNO', 'ry-wc-city-select'),
		_x('Viresu pagasts', 'APNO', 'ry-wc-city-select'),
	],
	'AUNO' => [
		_x('Auce', 'AUNO', 'ry-wc-city-select'),
		_x('Benes pagasts', 'AUNO', 'ry-wc-city-select'),
		_x('Iles pagasts', 'AUNO', 'ry-wc-city-select'),
		_x('Lielauces pagasts', 'AUNO', 'ry-wc-city-select'),
		_x('Ukru pagasts', 'AUNO', 'ry-wc-city-select'),
		_x('Vecauces pagasts', 'AUNO', 'ry-wc-city-select'),
		_x('Vitinu pagasts', 'AUNO', 'ry-wc-city-select'),
	],
	'BANO' => [
		_x('Babites pagasts', 'BANO', 'ry-wc-city-select'),
		_x('Salas pagasts', 'BANO', 'ry-wc-city-select'),
	],
	'BANO2' => [
		_x('Baldone', 'BANO2', 'ry-wc-city-select'),
		_x('Baldones pagasts', 'BANO2', 'ry-wc-city-select'),
	],
	'BANO3' => [
		_x('Baltinavas novads', 'BANO3', 'ry-wc-city-select'),
	],
	'BANO4' => [
		_x('Balvi', 'BANO4', 'ry-wc-city-select'),
		_x('Balvu pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Berzkalnes pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Berzpils pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Briezuciema pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Krisjanu pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Kubulu pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Lazdulejas pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Tilzas pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Vectilzas pagasts', 'BANO4', 'ry-wc-city-select'),
		_x('Viksnas pagasts', 'BANO4', 'ry-wc-city-select'),
	],
	'BANO5' => [
		_x('Bauska', 'BANO5', 'ry-wc-city-select'),
		_x('Brunavas pagasts', 'BANO5', 'ry-wc-city-select'),
		_x('Ceraukstes pagasts', 'BANO5', 'ry-wc-city-select'),
		_x('Codes pagasts', 'BANO5', 'ry-wc-city-select'),
		_x('Davinu pagasts', 'BANO5', 'ry-wc-city-select'),
		_x('Gailisu pagasts', 'BANO5', 'ry-wc-city-select'),
		_x('Islices pagasts', 'BANO5', 'ry-wc-city-select'),
		_x('Mezotnes pagasts', 'BANO5', 'ry-wc-city-select'),
		_x('Vecsaules pagasts', 'BANO5', 'ry-wc-city-select'),
	],
	'BENO' => [
		_x('Brengulu pagasts', 'BENO', 'ry-wc-city-select'),
		_x('Kauguru pagasts', 'BENO', 'ry-wc-city-select'),
		_x('Trikatas pagasts', 'BENO', 'ry-wc-city-select'),
	],
	'BRNO' => [
		_x('Blidenes pagasts', 'BRNO', 'ry-wc-city-select'),
		_x('Broceni', 'BRNO', 'ry-wc-city-select'),
		_x('Cieceres pagasts', 'BRNO', 'ry-wc-city-select'),
		_x('Gaiku pagasts', 'BRNO', 'ry-wc-city-select'),
		_x('Remtes pagasts', 'BRNO', 'ry-wc-city-select'),
	],
	'BUNO' => [
		_x('Burtnieku pagasts', 'BUNO', 'ry-wc-city-select'),
		_x('Eveles pagasts', 'BUNO', 'ry-wc-city-select'),
		_x('Matisu pagasts', 'BUNO', 'ry-wc-city-select'),
		_x('Rencenu pagasts', 'BUNO', 'ry-wc-city-select'),
		_x('Valmieras pagasts', 'BUNO', 'ry-wc-city-select'),
		_x('Vecates pagasts', 'BUNO', 'ry-wc-city-select'),
	],
	'CANO' => [
		_x('Carnikavas novads', 'CANO', 'ry-wc-city-select'),
	],
	'CENO' => [
		_x('Cesis', 'CENO', 'ry-wc-city-select'),
		_x('Vaives pagasts', 'CENO', 'ry-wc-city-select'),
	],
	'CENO2' => [
		_x('Cesvaine', 'CENO2', 'ry-wc-city-select'),
		_x('Cesvaines pagasts', 'CENO2', 'ry-wc-city-select'),
	],
	'CINO' => [
		_x('Blontu pagasts', 'CINO', 'ry-wc-city-select'),
		_x('Ciblas pagasts', 'CINO', 'ry-wc-city-select'),
		_x('Lidumnieku pagasts', 'CINO', 'ry-wc-city-select'),
		_x('Pusmucovas pagasts', 'CINO', 'ry-wc-city-select'),
		_x('Zvirgzdenes pagasts', 'CINO', 'ry-wc-city-select'),
	],
	'DANO' => [
		_x('Andrupenes pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Andzelu pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Asunes pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Berzinu pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Dagda', 'DANO', 'ry-wc-city-select'),
		_x('Dagdas pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Ezernieku pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Kepovas pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Konstantinovas pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Skaunes pagasts', 'DANO', 'ry-wc-city-select'),
		_x('Svarinu pagasts', 'DANO', 'ry-wc-city-select'),
	],
	'DA' => [
		_x('Daugavpils', 'DA', 'ry-wc-city-select'),
	],
	'DAMU' => [
		_x('Ambelu pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Bikernieku pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Demenes pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Dubnas pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Kalkunes pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Kalupes pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Laucesas pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Liksnas pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Malinovas pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Medumu pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Naujenes pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Nicgales pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Salienas pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Skrudalienas pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Sventes pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Tabores pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Vaboles pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Vecsalienas pagasts', 'DAMU', 'ry-wc-city-select'),
		_x('Visku pagasts', 'DAMU', 'ry-wc-city-select'),
	],
	'DONO' => [
		_x('Annenieku pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Auru pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Berzes pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Bikstu pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Dobele', 'DONO', 'ry-wc-city-select'),
		_x('Dobeles pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Jaunberzes pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Krimunu pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Naudites pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Penkules pagasts', 'DONO', 'ry-wc-city-select'),
		_x('Zebrenes pagasts', 'DONO', 'ry-wc-city-select'),
	],
	'DUNO' => [
		_x('Dundagas pagasts', 'DUNO', 'ry-wc-city-select'),
		_x('Kolkas pagasts', 'DUNO', 'ry-wc-city-select'),
	],
	'DUNO2' => [
		_x('Dunalkas pagasts', 'DUNO2', 'ry-wc-city-select'),
		_x('Durbe', 'DUNO2', 'ry-wc-city-select'),
		_x('Durbes pagasts', 'DUNO2', 'ry-wc-city-select'),
		_x('Tadaiku pagasts', 'DUNO2', 'ry-wc-city-select'),
		_x('Vecpils pagasts', 'DUNO2', 'ry-wc-city-select'),
	],
	'ENNO' => [
		_x('Engures pagasts', 'ENNO', 'ry-wc-city-select'),
		_x('Lapmezciema pagasts', 'ENNO', 'ry-wc-city-select'),
		_x('Smardes pagasts', 'ENNO', 'ry-wc-city-select'),
	],
	'ERNO' => [
		_x('Erglu pagasts', 'ERNO', 'ry-wc-city-select'),
		_x('Jumurdas pagasts', 'ERNO', 'ry-wc-city-select'),
		_x('Sausnejas pagasts', 'ERNO', 'ry-wc-city-select'),
	],
	'GAMU' => [
		_x('Garkalnes novads', 'GAMU', 'ry-wc-city-select'),
	],
	'GRNO' => [
		_x('Bartas pagasts', 'GRNO', 'ry-wc-city-select'),
		_x('Gaviezes pagasts', 'GRNO', 'ry-wc-city-select'),
		_x('Grobina', 'GRNO', 'ry-wc-city-select'),
		_x('Grobinas pagasts', 'GRNO', 'ry-wc-city-select'),
		_x('Medzes pagasts', 'GRNO', 'ry-wc-city-select'),
	],
	'GUNO' => [
		_x('Belavas pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Daukstu pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Druvienas pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Galgauskas pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Gulbene', 'GUNO', 'ry-wc-city-select'),
		_x('Jaungulbenes pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Lejasciema pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Ligo pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Litenes pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Lizuma pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Rankas pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Stamerienas pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Stradu pagasts', 'GUNO', 'ry-wc-city-select'),
		_x('Tirzas pagasts', 'GUNO', 'ry-wc-city-select'),
	],
	'IENO' => [
		_x('Iecavas novads', 'IENO', 'ry-wc-city-select'),
	],
	'IKNO' => [
		_x('Ikskile', 'IKNO', 'ry-wc-city-select'),
		_x('Tinuzu pagasts', 'IKNO', 'ry-wc-city-select'),
	],
	'ILNO' => [
		_x('Bebrenes pagasts', 'ILNO', 'ry-wc-city-select'),
		_x('Dvietes pagasts', 'ILNO', 'ry-wc-city-select'),
		_x('Eglaines pagasts', 'ILNO', 'ry-wc-city-select'),
		_x('Ilukste', 'ILNO', 'ry-wc-city-select'),
		_x('Pilskalnes pagasts', 'ILNO', 'ry-wc-city-select'),
		_x('Prodes pagasts', 'ILNO', 'ry-wc-city-select'),
		_x('Sederes pagasts', 'ILNO', 'ry-wc-city-select'),
		_x('Subate', 'ILNO', 'ry-wc-city-select'),
	],
	'INNO' => [
		_x('Incukalna pagasts', 'INNO', 'ry-wc-city-select'),
		_x('Vangazi', 'INNO', 'ry-wc-city-select'),
	],
	'JANO' => [
		_x('Daudzeses pagasts', 'JANO', 'ry-wc-city-select'),
		_x('Jaunjelgava', 'JANO', 'ry-wc-city-select'),
		_x('Jaunjelgavas pagasts', 'JANO', 'ry-wc-city-select'),
		_x('Seces pagasts', 'JANO', 'ry-wc-city-select'),
		_x('Serenes pagasts', 'JANO', 'ry-wc-city-select'),
		_x('Staburaga pagasts', 'JANO', 'ry-wc-city-select'),
		_x('Sunakstes pagasts', 'JANO', 'ry-wc-city-select'),
	],
	'JANO2' => [
		_x('Jaunpiebalgas pagasts', 'JANO2', 'ry-wc-city-select'),
		_x('Zosenu pagasts', 'JANO2', 'ry-wc-city-select'),
	],
	'JANO3' => [
		_x('Jaunpils pagasts', 'JANO3', 'ry-wc-city-select'),
		_x('Viesatu pagasts', 'JANO3', 'ry-wc-city-select'),
	],
	'JE' => [
		_x('Jekabpils', 'JE', 'ry-wc-city-select'),
	],
	'JEMU' => [
		_x('Abelu pagasts', 'JEMU', 'ry-wc-city-select'),
		_x('Dignajas pagasts', 'JEMU', 'ry-wc-city-select'),
		_x('Dunavas pagasts', 'JEMU', 'ry-wc-city-select'),
		_x('Kalna pagasts', 'JEMU', 'ry-wc-city-select'),
		_x('Leimanu pagasts', 'JEMU', 'ry-wc-city-select'),
		_x('Rubenes pagasts', 'JEMU', 'ry-wc-city-select'),
		_x('Zasas pagasts', 'JEMU', 'ry-wc-city-select'),
	],
	'JE2' => [
		_x('Jelgava', 'JE2', 'ry-wc-city-select'),
	],
	'JENO' => [
		_x('Elejas pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Gludas pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Jaunsvirlaukas pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Kalnciema pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Lielplatones pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Livberzes pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Platones pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Sesavas pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Svetes pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Valgundes pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Vilces pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Vircavas pagasts', 'JENO', 'ry-wc-city-select'),
		_x('Zalenieku pagasts', 'JENO', 'ry-wc-city-select'),
	],
	'JU' => [
		_x('Jurmala', 'JU', 'ry-wc-city-select'),
	],
	'KANO' => [
		_x('Ceres pagasts', 'KANO', 'ry-wc-city-select'),
		_x('Kandava', 'KANO', 'ry-wc-city-select'),
		_x('Kandavas pagasts', 'KANO', 'ry-wc-city-select'),
		_x('Matkules pagasts', 'KANO', 'ry-wc-city-select'),
		_x('Vanes pagasts', 'KANO', 'ry-wc-city-select'),
		_x('Zantes pagasts', 'KANO', 'ry-wc-city-select'),
		_x('Zemites pagasts', 'KANO', 'ry-wc-city-select'),
	],
	'KANO2' => [
		_x('Golisevas pagasts', 'KANO2', 'ry-wc-city-select'),
		_x('Karsava', 'KANO2', 'ry-wc-city-select'),
		_x('Malnavas pagasts', 'KANO2', 'ry-wc-city-select'),
		_x('Merdzenes pagasts', 'KANO2', 'ry-wc-city-select'),
		_x('Mezvidu pagasts', 'KANO2', 'ry-wc-city-select'),
		_x('Salnavas pagasts', 'KANO2', 'ry-wc-city-select'),
	],
	'KENO' => [
		_x('Birzgales pagasts', 'KENO', 'ry-wc-city-select'),
		_x('Kegums', 'KENO', 'ry-wc-city-select'),
		_x('Rembates pagasts', 'KENO', 'ry-wc-city-select'),
		_x('Tomes pagasts', 'KENO', 'ry-wc-city-select'),
	],
	'KENO2' => [
		_x('Balozi', 'KENO2', 'ry-wc-city-select'),
		_x('Daugmales pagasts', 'KENO2', 'ry-wc-city-select'),
		_x('Kekavas pagasts', 'KENO2', 'ry-wc-city-select'),
	],
	'KONO' => [
		_x('Berzaines pagasts', 'KONO', 'ry-wc-city-select'),
		_x('Diklu pagasts', 'KONO', 'ry-wc-city-select'),
		_x('Kocenu pagasts', 'KONO', 'ry-wc-city-select'),
		_x('Vaidavas pagasts', 'KONO', 'ry-wc-city-select'),
		_x('Zilakalna pagasts', 'KONO', 'ry-wc-city-select'),
	],
	'KONO2' => [
		_x('Bebru pagasts', 'KONO2', 'ry-wc-city-select'),
		_x('Irsu pagasts', 'KONO2', 'ry-wc-city-select'),
		_x('Kokneses pagasts', 'KONO2', 'ry-wc-city-select'),
	],
	'KRNO' => [
		_x('Aulejas pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Indras pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Izvaltas pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Kalniesu pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Kaplavas pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Kombulu pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Kraslava', 'KRNO', 'ry-wc-city-select'),
		_x('Kraslavas pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Piedrujas pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Robeznieku pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Skaistas pagasts', 'KRNO', 'ry-wc-city-select'),
		_x('Udrisu pagasts', 'KRNO', 'ry-wc-city-select'),
	],
	'KRNO2' => [
		_x('Krimuldas pagasts', 'KRNO2', 'ry-wc-city-select'),
		_x('Ledurgas pagasts', 'KRNO2', 'ry-wc-city-select'),
	],
	'KRNO3' => [
		_x('Atasienes pagasts', 'KRNO3', 'ry-wc-city-select'),
		_x('Krustpils pagasts', 'KRNO3', 'ry-wc-city-select'),
		_x('Kuku pagasts', 'KRNO3', 'ry-wc-city-select'),
		_x('Mezares pagasts', 'KRNO3', 'ry-wc-city-select'),
		_x('Variesu pagasts', 'KRNO3', 'ry-wc-city-select'),
		_x('Vipes pagasts', 'KRNO3', 'ry-wc-city-select'),
	],
	'KUNO' => [
		_x('Edoles pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Gudenieku pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Ivandes pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Kabiles pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Kuldiga', 'KUNO', 'ry-wc-city-select'),
		_x('Kurmales pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Laidu pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Padures pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Pelcu pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Rendas pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Rumbas pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Snepeles pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Turlavas pagasts', 'KUNO', 'ry-wc-city-select'),
		_x('Varmes pagasts', 'KUNO', 'ry-wc-city-select'),
	],
	'LINO' => [
		_x('Jumpravas pagasts', 'LINO', 'ry-wc-city-select'),
		_x('Ledmanes pagasts', 'LINO', 'ry-wc-city-select'),
		_x('Lielvarde', 'LINO', 'ry-wc-city-select'),
		_x('Lielvardes pagasts', 'LINO', 'ry-wc-city-select'),
	],
	'LI' => [
		_x('Liepaja', 'LI', 'ry-wc-city-select'),
	],
	'LINO2' => [
		_x('Ligatne', 'LINO2', 'ry-wc-city-select'),
		_x('Ligatnes pagasts', 'LINO2', 'ry-wc-city-select'),
	],
	'LINO3' => [
		_x('Katvaru pagasts', 'LINO3', 'ry-wc-city-select'),
		_x('Limbazi', 'LINO3', 'ry-wc-city-select'),
		_x('Limbazu pagasts', 'LINO3', 'ry-wc-city-select'),
		_x('Pales pagasts', 'LINO3', 'ry-wc-city-select'),
		_x('Skultes pagasts', 'LINO3', 'ry-wc-city-select'),
		_x('Umurgas pagasts', 'LINO3', 'ry-wc-city-select'),
		_x('Vidrizu pagasts', 'LINO3', 'ry-wc-city-select'),
		_x('Vilkenes pagasts', 'LINO3', 'ry-wc-city-select'),
	],
	'LINO4' => [
		_x('Jersikas pagasts', 'LINO4', 'ry-wc-city-select'),
		_x('Livani', 'LINO4', 'ry-wc-city-select'),
		_x('Rozupes pagasts', 'LINO4', 'ry-wc-city-select'),
		_x('Rudzatu pagasts', 'LINO4', 'ry-wc-city-select'),
		_x('Sutru pagasts', 'LINO4', 'ry-wc-city-select'),
		_x('Turku pagasts', 'LINO4', 'ry-wc-city-select'),
	],
	'LUNO' => [
		_x('Indranu pagasts', 'LUNO', 'ry-wc-city-select'),
		_x('Lubana', 'LUNO', 'ry-wc-city-select'),
	],
	'LUNO2' => [
		_x('Brigu pagasts', 'LUNO2', 'ry-wc-city-select'),
		_x('Cirmas pagasts', 'LUNO2', 'ry-wc-city-select'),
		_x('Isnaudas pagasts', 'LUNO2', 'ry-wc-city-select'),
		_x('Istras pagasts', 'LUNO2', 'ry-wc-city-select'),
		_x('Ludza', 'LUNO2', 'ry-wc-city-select'),
		_x('Nirzas pagasts', 'LUNO2', 'ry-wc-city-select'),
		_x('Nuksu pagasts', 'LUNO2', 'ry-wc-city-select'),
		_x('Pildas pagasts', 'LUNO2', 'ry-wc-city-select'),
		_x('Purenu pagasts', 'LUNO2', 'ry-wc-city-select'),
		_x('Rundenu pagasts', 'LUNO2', 'ry-wc-city-select'),
	],
	'MAMU' => [
		_x('Aronas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Barkavas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Berzaunes pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Dzelzavas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Kalsnavas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Laudonas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Lazdonas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Liezeres pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Madona', 'MAMU', 'ry-wc-city-select'),
		_x('Marcienas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Metrienas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Osupes pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Praulienas pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Sarkanu pagasts', 'MAMU', 'ry-wc-city-select'),
		_x('Vestienas pagasts', 'MAMU', 'ry-wc-city-select'),
	],
	'MANO' => [
		_x('Malpils novads', 'MANO', 'ry-wc-city-select'),
	],
	'MANO2' => [
		_x('Marupes novads', 'MANO2', 'ry-wc-city-select'),
	],
	'MANO3' => [
		_x('Mazsalaca', 'MANO3', 'ry-wc-city-select'),
		_x('Mazsalacas pagasts', 'MANO3', 'ry-wc-city-select'),
		_x('Ramatas pagasts', 'MANO3', 'ry-wc-city-select'),
		_x('Selu pagasts', 'MANO3', 'ry-wc-city-select'),
		_x('Skankalnes pagasts', 'MANO3', 'ry-wc-city-select'),
	],
	'MENO' => [
		_x('Mersraga novads', 'MENO', 'ry-wc-city-select'),
	],
	'NANO' => [
		_x('Konu pagasts', 'NANO', 'ry-wc-city-select'),
		_x('Nauksenu pagasts', 'NANO', 'ry-wc-city-select'),
	],
	'NENO' => [
		_x('Mazzalves pagasts', 'NENO', 'ry-wc-city-select'),
		_x('Neretas pagasts', 'NENO', 'ry-wc-city-select'),
		_x('Pilskalnes pagasts', 'NENO', 'ry-wc-city-select'),
		_x('Zalves pagasts', 'NENO', 'ry-wc-city-select'),
	],
	'NINO' => [
		_x('Nicas pagasts', 'NINO', 'ry-wc-city-select'),
		_x('Otanku pagasts', 'NINO', 'ry-wc-city-select'),
	],
	'OGNO' => [
		_x('Keipenes pagasts', 'OGNO', 'ry-wc-city-select'),
		_x('Krapes pagasts', 'OGNO', 'ry-wc-city-select'),
		_x('Lauberes pagasts', 'OGNO', 'ry-wc-city-select'),
		_x('Madlienas pagasts', 'OGNO', 'ry-wc-city-select'),
		_x('Mazozolu pagasts', 'OGNO', 'ry-wc-city-select'),
		_x('Mengeles pagasts', 'OGNO', 'ry-wc-city-select'),
		_x('Ogre', 'OGNO', 'ry-wc-city-select'),
		_x('Ogresgala pagasts', 'OGNO', 'ry-wc-city-select'),
		_x('Suntazu pagasts', 'OGNO', 'ry-wc-city-select'),
		_x('Taurupes pagasts', 'OGNO', 'ry-wc-city-select'),
	],
	'OLNO' => [
		_x('Olaine', 'OLNO', 'ry-wc-city-select'),
		_x('Olaines pagasts', 'OLNO', 'ry-wc-city-select'),
	],
	'OZNO' => [
		_x('Cenu pagasts', 'OZNO', 'ry-wc-city-select'),
		_x('Ozolnieku pagasts', 'OZNO', 'ry-wc-city-select'),
		_x('Salgales pagasts', 'OZNO', 'ry-wc-city-select'),
	],
	'PANO' => [
		_x('Raiskuma pagasts', 'PANO', 'ry-wc-city-select'),
		_x('Stalbes pagasts', 'PANO', 'ry-wc-city-select'),
		_x('Straupes pagasts', 'PANO', 'ry-wc-city-select'),
	],
	'PANO2' => [
		_x('Pavilosta', 'PANO2', 'ry-wc-city-select'),
		_x('Sakas pagasts', 'PANO2', 'ry-wc-city-select'),
		_x('Vergales pagasts', 'PANO2', 'ry-wc-city-select'),
	],
	'PLNO' => [
		_x('Aiviekstes pagasts', 'PLNO', 'ry-wc-city-select'),
		_x('Klintaines pagasts', 'PLNO', 'ry-wc-city-select'),
		_x('Plavinas', 'PLNO', 'ry-wc-city-select'),
		_x('Vietalvas pagasts', 'PLNO', 'ry-wc-city-select'),
	],
	'PRMU' => [
		_x('Aizkalnes pagasts', 'PRMU', 'ry-wc-city-select'),
		_x('Pelecu pagasts', 'PRMU', 'ry-wc-city-select'),
		_x('Preili', 'PRMU', 'ry-wc-city-select'),
		_x('Preilu pagasts', 'PRMU', 'ry-wc-city-select'),
		_x('Saunas pagasts', 'PRMU', 'ry-wc-city-select'),
	],
	'PRNO' => [
		_x('Bunkas pagasts', 'PRNO', 'ry-wc-city-select'),
		_x('Gramzdas pagasts', 'PRNO', 'ry-wc-city-select'),
		_x('Kaletu pagasts', 'PRNO', 'ry-wc-city-select'),
		_x('Priekule', 'PRNO', 'ry-wc-city-select'),
		_x('Priekules pagasts', 'PRNO', 'ry-wc-city-select'),
		_x('Virgas pagasts', 'PRNO', 'ry-wc-city-select'),
	],
	'PRMU2' => [
		_x('Liepas pagasts', 'PRMU2', 'ry-wc-city-select'),
		_x('Marsnenu pagasts', 'PRMU2', 'ry-wc-city-select'),
		_x('Priekulu pagasts', 'PRMU2', 'ry-wc-city-select'),
		_x('Veselavas pagasts', 'PRMU2', 'ry-wc-city-select'),
	],
	'RANO' => [
		_x('Drustu pagasts', 'RANO', 'ry-wc-city-select'),
		_x('Raunas pagasts', 'RANO', 'ry-wc-city-select'),
	],
	'RE' => [
		_x('Rezekne', 'RE', 'ry-wc-city-select'),
	],
	'RENO' => [
		_x('Audrinu pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Berzgales pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Cornajas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Dricanu pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Feimanu pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Gaigalavas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Griskanu pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Ilzeskalna pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Kantinieku pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Kaunatas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Lendzu pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Luznavas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Makonkalna pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Maltas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Naglu pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Nautrenu pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Ozolaines pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Ozolmuizas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Pusas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Rikavas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Sakstagala pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Silmalas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Stolerovas pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Struzanu pagasts', 'RENO', 'ry-wc-city-select'),
		_x('Veremu pagasts', 'RENO', 'ry-wc-city-select'),
	],
	'RINO' => [
		_x('Galenu pagasts', 'RINO', 'ry-wc-city-select'),
		_x('Riebinu pagasts', 'RINO', 'ry-wc-city-select'),
		_x('Rusonas pagasts', 'RINO', 'ry-wc-city-select'),
		_x('Silajanu pagasts', 'RINO', 'ry-wc-city-select'),
		_x('Silukalna pagasts', 'RINO', 'ry-wc-city-select'),
		_x('Stabulnieku pagasts', 'RINO', 'ry-wc-city-select'),
	],
	'RI' => [
		_x('Riga', 'RI', 'ry-wc-city-select'),
	],
	'RONO' => [
		_x('Rojas novads', 'RONO', 'ry-wc-city-select'),
	],
	'RONO2' => [
		_x('Ropazu novads', 'RONO2', 'ry-wc-city-select'),
	],
	'RUNO' => [
		_x('Dunikas pagasts', 'RUNO', 'ry-wc-city-select'),
		_x('Rucavas pagasts', 'RUNO', 'ry-wc-city-select'),
	],
	'RUNO2' => [
		_x('Lazdukalna pagasts', 'RUNO2', 'ry-wc-city-select'),
		_x('Rugaju pagasts', 'RUNO2', 'ry-wc-city-select'),
	],
	'RUNO3' => [
		_x('Ipiku pagasts', 'RUNO3', 'ry-wc-city-select'),
		_x('Jeru pagasts', 'RUNO3', 'ry-wc-city-select'),
		_x('Lodes pagasts', 'RUNO3', 'ry-wc-city-select'),
		_x('Rujiena', 'RUNO3', 'ry-wc-city-select'),
		_x('Vilpulkas pagasts', 'RUNO3', 'ry-wc-city-select'),
	],
	'RUNO4' => [
		_x('Rundales pagasts', 'RUNO4', 'ry-wc-city-select'),
		_x('Svitenes pagasts', 'RUNO4', 'ry-wc-city-select'),
		_x('Viesturu pagasts', 'RUNO4', 'ry-wc-city-select'),
	],
	'SANO' => [
		_x('Ainazi', 'SANO', 'ry-wc-city-select'),
		_x('Ainazu pagasts', 'SANO', 'ry-wc-city-select'),
		_x('Liepupes pagasts', 'SANO', 'ry-wc-city-select'),
		_x('Salacgriva', 'SANO', 'ry-wc-city-select'),
		_x('Salacgrivas pagasts', 'SANO', 'ry-wc-city-select'),
	],
	'SANO2' => [
		_x('Salas pagasts', 'SANO2', 'ry-wc-city-select'),
		_x('Selpils pagasts', 'SANO2', 'ry-wc-city-select'),
	],
	'SANO3' => [
		_x('Salaspils', 'SANO3', 'ry-wc-city-select'),
		_x('Salaspils pagasts', 'SANO3', 'ry-wc-city-select'),
	],
	'SAMU' => [
		_x('Ezeres pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Jaunauces pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Jaunlutrinu pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Kursisu pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Lutrinu pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Nigrandes pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Novadnieku pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Pampalu pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Rubas pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Saldus', 'SAMU', 'ry-wc-city-select'),
		_x('Saldus pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Skedes pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Vadakstes pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Zanas pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Zirnu pagasts', 'SAMU', 'ry-wc-city-select'),
		_x('Zvardes pagasts', 'SAMU', 'ry-wc-city-select'),
	],
	'SANO4' => [
		_x('Saulkrasti', 'SANO4', 'ry-wc-city-select'),
		_x('Saulkrastu pagasts', 'SANO4', 'ry-wc-city-select'),
	],
	'SENO' => [
		_x('Sejas novads', 'SENO', 'ry-wc-city-select'),
	],
	'SINO' => [
		_x('Allazu pagasts', 'SINO', 'ry-wc-city-select'),
		_x('Mores pagasts', 'SINO', 'ry-wc-city-select'),
		_x('Sigulda', 'SINO', 'ry-wc-city-select'),
		_x('Siguldas pagasts', 'SINO', 'ry-wc-city-select'),
	],
	'SKNO' => [
		_x('Skriveru novads', 'SKNO', 'ry-wc-city-select'),
	],
	'SKNO2' => [
		_x('Nikraces pagasts', 'SKNO2', 'ry-wc-city-select'),
		_x('Ranku pagasts', 'SKNO2', 'ry-wc-city-select'),
		_x('Rudbarzu pagasts', 'SKNO2', 'ry-wc-city-select'),
		_x('Skrunda', 'SKNO2', 'ry-wc-city-select'),
		_x('Skrundas pagasts', 'SKNO2', 'ry-wc-city-select'),
	],
	'SMNO' => [
		_x('Bilskas pagasts', 'SMNO', 'ry-wc-city-select'),
		_x('Blomes pagasts', 'SMNO', 'ry-wc-city-select'),
		_x('Brantu pagasts', 'SMNO', 'ry-wc-city-select'),
		_x('Grundzales pagasts', 'SMNO', 'ry-wc-city-select'),
		_x('Launkalnes pagasts', 'SMNO', 'ry-wc-city-select'),
		_x('Palsmanes pagasts', 'SMNO', 'ry-wc-city-select'),
		_x('Smiltene', 'SMNO', 'ry-wc-city-select'),
		_x('Smiltenes pagasts', 'SMNO', 'ry-wc-city-select'),
		_x('Varinu pagasts', 'SMNO', 'ry-wc-city-select'),
	],
	'STNO' => [
		_x('Stopinu novads', 'STNO', 'ry-wc-city-select'),
	],
	'STNO2' => [
		_x('Jercenu pagasts', 'STNO2', 'ry-wc-city-select'),
		_x('Planu pagasts', 'STNO2', 'ry-wc-city-select'),
		_x('Seda', 'STNO2', 'ry-wc-city-select'),
		_x('Strenci', 'STNO2', 'ry-wc-city-select'),
	],
	'TAMU' => [
		_x('Abavas pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Arlavas pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Balgales pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Gibulu pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Ives pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Kulciema pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Laidzes pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Laucienes pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Libagu pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Lubes pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Sabile', 'TAMU', 'ry-wc-city-select'),
		_x('Stende', 'TAMU', 'ry-wc-city-select'),
		_x('Strazdes pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Talsi', 'TAMU', 'ry-wc-city-select'),
		_x('Valdemarpils', 'TAMU', 'ry-wc-city-select'),
		_x('Valdgales pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Vandzenes pagasts', 'TAMU', 'ry-wc-city-select'),
		_x('Virbu pagasts', 'TAMU', 'ry-wc-city-select'),
	],
	'TENO' => [
		_x('Augstkalnes pagasts', 'TENO', 'ry-wc-city-select'),
		_x('Bukaisu pagasts', 'TENO', 'ry-wc-city-select'),
		_x('Tervetes pagasts', 'TENO', 'ry-wc-city-select'),
	],
	'TUNO' => [
		_x('Degoles pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Dzukstes pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Irlavas pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Jaunsatu pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Lestenes pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Pures pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Semes pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Slampes pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Tukums', 'TUNO', 'ry-wc-city-select'),
		_x('Tumes pagasts', 'TUNO', 'ry-wc-city-select'),
		_x('Zentenes pagasts', 'TUNO', 'ry-wc-city-select'),
	],
	'VANO' => [
		_x('Embutes pagasts', 'VANO', 'ry-wc-city-select'),
		_x('Vainodes pagasts', 'VANO', 'ry-wc-city-select'),
	],
	'VAMU' => [
		_x('Ergemes pagasts', 'VAMU', 'ry-wc-city-select'),
		_x('Karku pagasts', 'VAMU', 'ry-wc-city-select'),
		_x('Valka', 'VAMU', 'ry-wc-city-select'),
		_x('Valkas pagasts', 'VAMU', 'ry-wc-city-select'),
		_x('Vijciema pagasts', 'VAMU', 'ry-wc-city-select'),
		_x('Zvartavas pagasts', 'VAMU', 'ry-wc-city-select'),
	],
	'VA' => [
		_x('Valmiera', 'VA', 'ry-wc-city-select'),
	],
	'VANO2' => [
		_x('Murmastienes pagasts', 'VANO2', 'ry-wc-city-select'),
		_x('Varaklani', 'VANO2', 'ry-wc-city-select'),
		_x('Varaklanu pagasts', 'VANO2', 'ry-wc-city-select'),
	],
	'VANO3' => [
		_x('Rozkalnu pagasts', 'VANO3', 'ry-wc-city-select'),
		_x('Upmalas pagasts', 'VANO3', 'ry-wc-city-select'),
		_x('Varkavas pagasts', 'VANO3', 'ry-wc-city-select'),
	],
	'VENO' => [
		_x('Dzerbenes pagasts', 'VENO', 'ry-wc-city-select'),
		_x('Inesu pagasts', 'VENO', 'ry-wc-city-select'),
		_x('Kaives pagasts', 'VENO', 'ry-wc-city-select'),
		_x('Taurenes pagasts', 'VENO', 'ry-wc-city-select'),
		_x('Vecpiebalgas pagasts', 'VENO', 'ry-wc-city-select'),
	],
	'VENO2' => [
		_x('Barbeles pagasts', 'VENO2', 'ry-wc-city-select'),
		_x('Kurmenes pagasts', 'VENO2', 'ry-wc-city-select'),
		_x('Skaistkalnes pagasts', 'VENO2', 'ry-wc-city-select'),
		_x('Stelpes pagasts', 'VENO2', 'ry-wc-city-select'),
		_x('Valles pagasts', 'VENO2', 'ry-wc-city-select'),
		_x('Vecumnieku pagasts', 'VENO2', 'ry-wc-city-select'),
	],
	'VE' => [
		_x('Ventspils', 'VE', 'ry-wc-city-select'),
	],
	'VEMU' => [
		_x('Ances pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Jurkalnes pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Piltene', 'VEMU', 'ry-wc-city-select'),
		_x('Piltenes pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Popes pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Puzes pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Targales pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Ugales pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Usmas pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Uzavas pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Varves pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Ziru pagasts', 'VEMU', 'ry-wc-city-select'),
		_x('Zleku pagasts', 'VEMU', 'ry-wc-city-select'),
	],
	'VINO' => [
		_x('Elksnu pagasts', 'VINO', 'ry-wc-city-select'),
		_x('Rites pagasts', 'VINO', 'ry-wc-city-select'),
		_x('Saukas pagasts', 'VINO', 'ry-wc-city-select'),
		_x('Viesite', 'VINO', 'ry-wc-city-select'),
		_x('Viesites pagasts', 'VINO', 'ry-wc-city-select'),
	],
	'VINO2' => [
		_x('Kupravas pagasts', 'VINO2', 'ry-wc-city-select'),
		_x('Mednevas pagasts', 'VINO2', 'ry-wc-city-select'),
		_x('Skilbenu pagasts', 'VINO2', 'ry-wc-city-select'),
		_x('Susaju pagasts', 'VINO2', 'ry-wc-city-select'),
		_x('Vecumu pagasts', 'VINO2', 'ry-wc-city-select'),
		_x('Vilaka', 'VINO2', 'ry-wc-city-select'),
		_x('Ziguru pagasts', 'VINO2', 'ry-wc-city-select'),
	],
	'VINO3' => [
		_x('Deksares pagasts', 'VINO3', 'ry-wc-city-select'),
		_x('Sokolku pagasts', 'VINO3', 'ry-wc-city-select'),
		_x('Vilani', 'VINO3', 'ry-wc-city-select'),
		_x('Vilanu pagasts', 'VINO3', 'ry-wc-city-select'),
	],
	'ZINO' => [
		_x('Lauderu pagasts', 'ZINO', 'ry-wc-city-select'),
		_x('Pasienes pagasts', 'ZINO', 'ry-wc-city-select'),
		_x('Zalesjes pagasts', 'ZINO', 'ry-wc-city-select'),
		_x('Zilupe', 'ZINO', 'ry-wc-city-select'),
	],
	]
];