<?php
/**
 * Kingdom of Morocco places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MA' => [
	'AG' => [
		_x('Agadir', 'AG', 'ry-wc-city-select'),
		_x('Amskroud', 'AG', 'ry-wc-city-select'),
		_x('Aourir', 'AG', 'ry-wc-city-select'),
		_x('Aqesri', 'AG', 'ry-wc-city-select'),
		_x('Aziar', 'AG', 'ry-wc-city-select'),
		_x('Drargua', 'AG', 'ry-wc-city-select'),
		_x('Idmine', 'AG', 'ry-wc-city-select'),
		_x('Imouzzer', 'AG', 'ry-wc-city-select'),
		_x('Imsouane', 'AG', 'ry-wc-city-select'),
		_x('Tadrart', 'AG', 'ry-wc-city-select'),
		_x('Taghazout', 'AG', 'ry-wc-city-select'),
		_x('Tamri', 'AG', 'ry-wc-city-select'),
		_x('Tiqqi', 'AG', 'ry-wc-city-select'),
	],
	'AL' => [
		_x('Abadou', 'AL', 'ry-wc-city-select'),
		_x('Aghbar', 'AL', 'ry-wc-city-select'),
		_x('Ait Aadel', 'AL', 'ry-wc-city-select'),
		_x('Ait Faska', 'AL', 'ry-wc-city-select'),
		_x('Ait Hkim Ait Yzid', 'AL', 'ry-wc-city-select'),
		_x('Ait Ourir', 'AL', 'ry-wc-city-select'),
		_x('Ait Sidi Daoud', 'AL', 'ry-wc-city-select'),
		_x('Amghras', 'AL', 'ry-wc-city-select'),
		_x('Amizmiz', 'AL', 'ry-wc-city-select'),
		_x('Anougal', 'AL', 'ry-wc-city-select'),
		_x('Asni', 'AL', 'ry-wc-city-select'),
		_x('Azgour', 'AL', 'ry-wc-city-select'),
		_x('Dar Jamaa', 'AL', 'ry-wc-city-select'),
		_x('Ghmate', 'AL', 'ry-wc-city-select'),
		_x('Ighil', 'AL', 'ry-wc-city-select'),
		_x('Iguerferouane', 'AL', 'ry-wc-city-select'),
		_x('Ijoukak', 'AL', 'ry-wc-city-select'),
		_x('Imgdal', 'AL', 'ry-wc-city-select'),
		_x('Lalla Takarkoust', 'AL', 'ry-wc-city-select'),
		_x('Moulay Brahim', 'AL', 'ry-wc-city-select'),
		_x('Ouazguita', 'AL', 'ry-wc-city-select'),
		_x('Ouirgane', 'AL', 'ry-wc-city-select'),
		_x('Oukaimden', 'AL', 'ry-wc-city-select'),
		_x('Oulad Mtaa', 'AL', 'ry-wc-city-select'),
		_x('Ourika', 'AL', 'ry-wc-city-select'),
		_x('Sidi Abdallah Ghiat', 'AL', 'ry-wc-city-select'),
		_x('Sidi Badhaj', 'AL', 'ry-wc-city-select'),
		_x('Sti Fadma', 'AL', 'ry-wc-city-select'),
		_x('Tahannaout', 'AL', 'ry-wc-city-select'),
		_x('Talat N Yaaqoub', 'AL', 'ry-wc-city-select'),
		_x('Tamaguert', 'AL', 'ry-wc-city-select'),
		_x('Tamazouzte', 'AL', 'ry-wc-city-select'),
		_x('Tameslohte', 'AL', 'ry-wc-city-select'),
		_x('Tazart', 'AL', 'ry-wc-city-select'),
		_x('Tidili Mesfioua', 'AL', 'ry-wc-city-select'),
		_x('Tighedouine', 'AL', 'ry-wc-city-select'),
		_x('Tizguine', 'AL', 'ry-wc-city-select'),
		_x('Touama', 'AL', 'ry-wc-city-select'),
		_x('Zerkten', 'AL', 'ry-wc-city-select'),
	],
	'AL2' => [
		_x('Abdelghaya Souahel', 'AL2', 'ry-wc-city-select'),
		_x('Ait Kamra', 'AL2', 'ry-wc-city-select'),
		_x('Ait Youssef Ou Ali', 'AL2', 'ry-wc-city-select'),
		_x('Al Hoceima', 'AL2', 'ry-wc-city-select'),
		_x('Arbaa Taourirt', 'AL2', 'ry-wc-city-select'),
		_x('Bni Abdallah', 'AL2', 'ry-wc-city-select'),
		_x('Bni Ahmed Imoukzan', 'AL2', 'ry-wc-city-select'),
		_x('Bni Ammart', 'AL2', 'ry-wc-city-select'),
		_x('Bni Bchir', 'AL2', 'ry-wc-city-select'),
		_x('Bni Bouayach', 'AL2', 'ry-wc-city-select'),
		_x('Bni Bouchibet', 'AL2', 'ry-wc-city-select'),
		_x('Bni Boufrah', 'AL2', 'ry-wc-city-select'),
		_x('Bni Bounsar', 'AL2', 'ry-wc-city-select'),
		_x('Bni Gmil', 'AL2', 'ry-wc-city-select'),
		_x('Bni Gmil Maksouline', 'AL2', 'ry-wc-city-select'),
		_x('Bni Hadifa', 'AL2', 'ry-wc-city-select'),
		_x('Chakrane', 'AL2', 'ry-wc-city-select'),
		_x('Imrabten', 'AL2', 'ry-wc-city-select'),
		_x('Imzouren', 'AL2', 'ry-wc-city-select'),
		_x('Issaguen', 'AL2', 'ry-wc-city-select'),
		_x('Izemmouren', 'AL2', 'ry-wc-city-select'),
		_x('Ketama', 'AL2', 'ry-wc-city-select'),
		_x('Louta', 'AL2', 'ry-wc-city-select'),
		_x('Moulay Ahmed Cherif', 'AL2', 'ry-wc-city-select'),
		_x('Nekkour', 'AL2', 'ry-wc-city-select'),
		_x('Rouadi', 'AL2', 'ry-wc-city-select'),
		_x('Senada', 'AL2', 'ry-wc-city-select'),
		_x('Sidi Boutmim', 'AL2', 'ry-wc-city-select'),
		_x('Sidi Bouzineb', 'AL2', 'ry-wc-city-select'),
		_x('Taghzout', 'AL2', 'ry-wc-city-select'),
		_x('Tamassint', 'AL2', 'ry-wc-city-select'),
		_x('Tamsaout', 'AL2', 'ry-wc-city-select'),
		_x('Targuist', 'AL2', 'ry-wc-city-select'),
		_x('Tifarouine', 'AL2', 'ry-wc-city-select'),
		_x('Zaouiat Sidi Abdelka', 'AL2', 'ry-wc-city-select'),
		_x('Zarkt', 'AL2', 'ry-wc-city-select'),
	],
	'AO' => [
		_x('Aghouinite', 'AO', 'ry-wc-city-select'),
		_x('Aousserd', 'AO', 'ry-wc-city-select'),
		_x('Bir Gandouz', 'AO', 'ry-wc-city-select'),
		_x('Lagouira', 'AO', 'ry-wc-city-select'),
		_x('Tichla', 'AO', 'ry-wc-city-select'),
		_x('Zoug', 'AO', 'ry-wc-city-select'),
	],
	'AS' => [
		_x('Almahbass', 'AS', 'ry-wc-city-select'),
		_x('Aouint Lahna', 'AS', 'ry-wc-city-select'),
		_x('Aouint Yghomane', 'AS', 'ry-wc-city-select'),
		_x('Assa', 'AS', 'ry-wc-city-select'),
		_x('Labouirat', 'AS', 'ry-wc-city-select'),
		_x('Touizgui', 'AS', 'ry-wc-city-select'),
		_x('Zag', 'AS', 'ry-wc-city-select'),
	],
	'AZPR' => [
		_x('Afourar', 'AZPR', 'ry-wc-city-select'),
		_x('Agoudi N Lkhair', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Abbas', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Blal', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Bou Oulli', 'AZPR', 'ry-wc-city-select'),
		_x('Ait M Hamed', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Majden', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Mazigh', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Ouaarda', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Oumdis', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Ouqabli', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Taguella', 'AZPR', 'ry-wc-city-select'),
		_x('Ait Tamlil', 'AZPR', 'ry-wc-city-select'),
		_x('Anergui', 'AZPR', 'ry-wc-city-select'),
		_x('Anzou', 'AZPR', 'ry-wc-city-select'),
		_x('Azilal', 'AZPR', 'ry-wc-city-select'),
		_x('Bin El Ouidane', 'AZPR', 'ry-wc-city-select'),
		_x('Bni Ayat', 'AZPR', 'ry-wc-city-select'),
		_x('Bni Hassane', 'AZPR', 'ry-wc-city-select'),
		_x('Bzou', 'AZPR', 'ry-wc-city-select'),
		_x('Demnate', 'AZPR', 'ry-wc-city-select'),
		_x('Foum Jemaa', 'AZPR', 'ry-wc-city-select'),
		_x('Imlil', 'AZPR', 'ry-wc-city-select'),
		_x('Isseksi', 'AZPR', 'ry-wc-city-select'),
		_x('Moulay Aissa Ben Dri', 'AZPR', 'ry-wc-city-select'),
		_x('Ouaouizaght', 'AZPR', 'ry-wc-city-select'),
		_x('Ouaouizeght', 'AZPR', 'ry-wc-city-select'),
		_x('Ouaoula', 'AZPR', 'ry-wc-city-select'),
		_x('Rfala', 'AZPR', 'ry-wc-city-select'),
		_x('Sidi Boulkhalf', 'AZPR', 'ry-wc-city-select'),
		_x('Sidi Yacoub', 'AZPR', 'ry-wc-city-select'),
		_x('Tabant', 'AZPR', 'ry-wc-city-select'),
		_x('Tabaroucht', 'AZPR', 'ry-wc-city-select'),
		_x('Tabia', 'AZPR', 'ry-wc-city-select'),
		_x('Tagleft', 'AZPR', 'ry-wc-city-select'),
		_x('Tamda Noumercid', 'AZPR', 'ry-wc-city-select'),
		_x('Tanant', 'AZPR', 'ry-wc-city-select'),
		_x('Taounza', 'AZPR', 'ry-wc-city-select'),
		_x('Tidili Fetouaka', 'AZPR', 'ry-wc-city-select'),
		_x('Tiffert N Ait Hamza', 'AZPR', 'ry-wc-city-select'),
		_x('Tifni', 'AZPR', 'ry-wc-city-select'),
		_x('Tilougguite', 'AZPR', 'ry-wc-city-select'),
		_x('Timoulilt', 'AZPR', 'ry-wc-city-select'),
		_x('Tisqi', 'AZPR', 'ry-wc-city-select'),
		_x('Zaouiat Ahansal', 'AZPR', 'ry-wc-city-select'),
	],
	'BE' => [
		_x('Aghbala', 'BE', 'ry-wc-city-select'),
		_x('Ait Oum El Bekht', 'BE', 'ry-wc-city-select'),
		_x('Alkhalfia', 'BE', 'ry-wc-city-select'),
		_x('Beni Mellal', 'BE', 'ry-wc-city-select'),
		_x('Bni Chegdale', 'BE', 'ry-wc-city-select'),
		_x('Bni Oukil', 'BE', 'ry-wc-city-select'),
		_x('Boutferda', 'BE', 'ry-wc-city-select'),
		_x('Bradia', 'BE', 'ry-wc-city-select'),
		_x('Dar Ould Zidouh', 'BE', 'ry-wc-city-select'),
		_x('Dir El Ksiba', 'BE', 'ry-wc-city-select'),
		_x('El Ksiba', 'BE', 'ry-wc-city-select'),
		_x('Foum El Anceur', 'BE', 'ry-wc-city-select'),
		_x('Foum Oudi', 'BE', 'ry-wc-city-select'),
		_x('Guettaya', 'BE', 'ry-wc-city-select'),
		_x('Had Boumoussa', 'BE', 'ry-wc-city-select'),
		_x('Hel Merbaa', 'BE', 'ry-wc-city-select'),
		_x('Kasba Tadla', 'BE', 'ry-wc-city-select'),
		_x('Krifate', 'BE', 'ry-wc-city-select'),
		_x('Naour', 'BE', 'ry-wc-city-select'),
		_x('Oulad Ayad', 'BE', 'ry-wc-city-select'),
		_x('Oulad Bourahmoune', 'BE', 'ry-wc-city-select'),
		_x('Oulad Gnaou', 'BE', 'ry-wc-city-select'),
		_x('Oulad M Barek', 'BE', 'ry-wc-city-select'),
		_x('Oulad MBarek', 'BE', 'ry-wc-city-select'),
		_x('Oulad Nacer', 'BE', 'ry-wc-city-select'),
		_x('Oulad Said L Oued', 'BE', 'ry-wc-city-select'),
		_x('Oulad Yaich', 'BE', 'ry-wc-city-select'),
		_x('Oulad Youssef', 'BE', 'ry-wc-city-select'),
		_x('Oulad Zmam', 'BE', 'ry-wc-city-select'),
		_x('Semguet', 'BE', 'ry-wc-city-select'),
		_x('Sidi Aissa Ben Ali', 'BE', 'ry-wc-city-select'),
		_x('Sidi Hammadi', 'BE', 'ry-wc-city-select'),
		_x('Sidi Jaber', 'BE', 'ry-wc-city-select'),
		_x('Souk Sebt Oulad Nemm', 'BE', 'ry-wc-city-select'),
		_x('Taghzirt', 'BE', 'ry-wc-city-select'),
		_x('Tanougha', 'BE', 'ry-wc-city-select'),
		_x('Tizi N Isly', 'BE', 'ry-wc-city-select'),
		_x('Zaouiat Cheikh', 'BE', 'ry-wc-city-select'),
	],
	'BE2' => [
		_x('Ahlaf', 'BE2', 'ry-wc-city-select'),
		_x('Ain Tizgha', 'BE2', 'ry-wc-city-select'),
		_x('Benslimane', 'BE2', 'ry-wc-city-select'),
		_x('Bir Ennasr', 'BE2', 'ry-wc-city-select'),
		_x('Bouznika', 'BE2', 'ry-wc-city-select'),
		_x('Cherrat', 'BE2', 'ry-wc-city-select'),
		_x('El Mansouria', 'BE2', 'ry-wc-city-select'),
		_x('Fdalate', 'BE2', 'ry-wc-city-select'),
		_x('Mellila', 'BE2', 'ry-wc-city-select'),
		_x('Moualine El Ghaba', 'BE2', 'ry-wc-city-select'),
		_x('Moualine El Oued', 'BE2', 'ry-wc-city-select'),
		_x('Oulad Ali Toualaa', 'BE2', 'ry-wc-city-select'),
		_x('Oulad Yahya Louta', 'BE2', 'ry-wc-city-select'),
		_x('Rdadna Oulad Malek', 'BE2', 'ry-wc-city-select'),
		_x('Sidi Bettache', 'BE2', 'ry-wc-city-select'),
		_x('Ziaida', 'BE2', 'ry-wc-city-select'),
	],
	'BE3' => [
		_x('Aghbal', 'BE3', 'ry-wc-city-select'),
		_x('Ahfir', 'BE3', 'ry-wc-city-select'),
		_x('Ain Erreggada', 'BE3', 'ry-wc-city-select'),
		_x('Aklim', 'BE3', 'ry-wc-city-select'),
		_x('Berkane', 'BE3', 'ry-wc-city-select'),
		_x('Boughriba', 'BE3', 'ry-wc-city-select'),
		_x('Bouhdila', 'BE3', 'ry-wc-city-select'),
		_x('Chouihia', 'BE3', 'ry-wc-city-select'),
		_x('El Atef', 'BE3', 'ry-wc-city-select'),
		_x('Fezouane', 'BE3', 'ry-wc-city-select'),
		_x('Laatamna', 'BE3', 'ry-wc-city-select'),
		_x('Madagh', 'BE3', 'ry-wc-city-select'),
		_x('Rislane', 'BE3', 'ry-wc-city-select'),
		_x('Saidia', 'BE3', 'ry-wc-city-select'),
		_x('Sidi Bouhria', 'BE3', 'ry-wc-city-select'),
		_x('Sidi Sliman Echchara', 'BE3', 'ry-wc-city-select'),
		_x('Tafoughalt', 'BE3', 'ry-wc-city-select'),
		_x('Zegzel', 'BE3', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Boujdour', 'BO', 'ry-wc-city-select'),
		_x('Gueltat Zemmour', 'BO', 'ry-wc-city-select'),
		_x('Jraifia', 'BO', 'ry-wc-city-select'),
		_x('Lamssid', 'BO', 'ry-wc-city-select'),
	],
	'BO2' => [
		_x('Ait Bazza', 'BO2', 'ry-wc-city-select'),
		_x('Ait El Mane', 'BO2', 'ry-wc-city-select'),
		_x('Almis Marmoucha', 'BO2', 'ry-wc-city-select'),
		_x('Boulemane', 'BO2', 'ry-wc-city-select'),
		_x('Elmers', 'BO2', 'ry-wc-city-select'),
		_x('Elorjane', 'BO2', 'ry-wc-city-select'),
		_x('Enjil', 'BO2', 'ry-wc-city-select'),
		_x('Ermila', 'BO2', 'ry-wc-city-select'),
		_x('Fritissa', 'BO2', 'ry-wc-city-select'),
		_x('Guigou', 'BO2', 'ry-wc-city-select'),
		_x('Imouzzer Marmoucha', 'BO2', 'ry-wc-city-select'),
		_x('Ksabi Moulouya', 'BO2', 'ry-wc-city-select'),
		_x('Missour', 'BO2', 'ry-wc-city-select'),
		_x('Ouizeght', 'BO2', 'ry-wc-city-select'),
		_x('Oulad Ali Youssef', 'BO2', 'ry-wc-city-select'),
		_x('Outat El Haj', 'BO2', 'ry-wc-city-select'),
		_x('Serghina', 'BO2', 'ry-wc-city-select'),
		_x('Sidi Boutayeb', 'BO2', 'ry-wc-city-select'),
		_x('Skoura M Daz', 'BO2', 'ry-wc-city-select'),
		_x('Talzemt', 'BO2', 'ry-wc-city-select'),
		_x('Tissaf', 'BO2', 'ry-wc-city-select'),
	],
	'CA' => [
		_x('Ain-Chock', 'CA', 'ry-wc-city-select'),
		_x('Ain-Sebaa', 'CA', 'ry-wc-city-select'),
		_x('Al-Fida', 'CA', 'ry-wc-city-select'),
		_x('Anfa', 'CA', 'ry-wc-city-select'),
		_x('Assoukhour Assawda', 'CA', 'ry-wc-city-select'),
		_x('Ben MSick', 'CA', 'ry-wc-city-select'),
		_x('Elmaarif', 'CA', 'ry-wc-city-select'),
		_x('Hay Mohammadi', 'CA', 'ry-wc-city-select'),
		_x('Hay-Hassani', 'CA', 'ry-wc-city-select'),
		_x('Mechouar Casablanca', 'CA', 'ry-wc-city-select'),
		_x('Mers-Sultan', 'CA', 'ry-wc-city-select'),
		_x('Moulay Rachid', 'CA', 'ry-wc-city-select'),
		_x('Sbata', 'CA', 'ry-wc-city-select'),
		_x('Sidi Belyout', 'CA', 'ry-wc-city-select'),
		_x('Sidi Bernoussi', 'CA', 'ry-wc-city-select'),
		_x('Sidi Moumen', 'CA', 'ry-wc-city-select'),
		_x('Sidi Othmane', 'CA', 'ry-wc-city-select'),
	],
	'CHPR' => [
		_x('Ain Beida', 'CHPR', 'ry-wc-city-select'),
		_x('Amtar', 'CHPR', 'ry-wc-city-select'),
		_x('Asjen', 'CHPR', 'ry-wc-city-select'),
		_x('Bab Berred', 'CHPR', 'ry-wc-city-select'),
		_x('Bab Taza', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Ahmed Cherqia', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Ahmed Gharbia', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Bouzra', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Darkoul', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Faghloum', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Mansour', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Rzine', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Salah', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Selmane', 'CHPR', 'ry-wc-city-select'),
		_x('Bni Smih', 'CHPR', 'ry-wc-city-select'),
		_x('Brikcha', 'CHPR', 'ry-wc-city-select'),
		_x('Chefchaouen', 'CHPR', 'ry-wc-city-select'),
		_x('Derdara', 'CHPR', 'ry-wc-city-select'),
		_x('Fifi', 'CHPR', 'ry-wc-city-select'),
		_x('Iounane', 'CHPR', 'ry-wc-city-select'),
		_x('Jebha', 'CHPR', 'ry-wc-city-select'),
		_x('Kalaat Bouqorra', 'CHPR', 'ry-wc-city-select'),
		_x('Laghdir', 'CHPR', 'ry-wc-city-select'),
		_x('MTioua', 'CHPR', 'ry-wc-city-select'),
		_x('Mansoura', 'CHPR', 'ry-wc-city-select'),
		_x('Moqrisset', 'CHPR', 'ry-wc-city-select'),
		_x('Ouaouzgane', 'CHPR', 'ry-wc-city-select'),
		_x('Oued Malha', 'CHPR', 'ry-wc-city-select'),
		_x('Steha', 'CHPR', 'ry-wc-city-select'),
		_x('Talambote', 'CHPR', 'ry-wc-city-select'),
		_x('Tamorot', 'CHPR', 'ry-wc-city-select'),
		_x('Tanaqoub', 'CHPR', 'ry-wc-city-select'),
		_x('Tassift', 'CHPR', 'ry-wc-city-select'),
		_x('Tizgane', 'CHPR', 'ry-wc-city-select'),
		_x('Zoumi', 'CHPR', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Adassil', 'CH', 'ry-wc-city-select'),
		_x('Afalla Issen', 'CH', 'ry-wc-city-select'),
		_x('Ahdil', 'CH', 'ry-wc-city-select'),
		_x('Ain Tazitounte', 'CH', 'ry-wc-city-select'),
		_x('Ait Haddou Youssef', 'CH', 'ry-wc-city-select'),
		_x('Ait Hadi', 'CH', 'ry-wc-city-select'),
		_x('Assif El Mal', 'CH', 'ry-wc-city-select'),
		_x('Bouabout', 'CH', 'ry-wc-city-select'),
		_x('Bouabout Amdlane', 'CH', 'ry-wc-city-select'),
		_x('Chichaoua', 'CH', 'ry-wc-city-select'),
		_x('Douirane', 'CH', 'ry-wc-city-select'),
		_x('Gmassa', 'CH', 'ry-wc-city-select'),
		_x('Ichamraren', 'CH', 'ry-wc-city-select'),
		_x('Imindounit', 'CH', 'ry-wc-city-select'),
		_x('Imintanoute', 'CH', 'ry-wc-city-select'),
		_x('Irohalen', 'CH', 'ry-wc-city-select'),
		_x('Kouzemt', 'CH', 'ry-wc-city-select'),
		_x('Lalla Aaziza', 'CH', 'ry-wc-city-select'),
		_x('Lamzoudia', 'CH', 'ry-wc-city-select'),
		_x('M Zouda', 'CH', 'ry-wc-city-select'),
		_x('Majjat', 'CH', 'ry-wc-city-select'),
		_x('Nfifa', 'CH', 'ry-wc-city-select'),
		_x('Oued L Bour', 'CH', 'ry-wc-city-select'),
		_x('Oulad Moumna', 'CH', 'ry-wc-city-select'),
		_x('Rahhala', 'CH', 'ry-wc-city-select'),
		_x('Saidate', 'CH', 'ry-wc-city-select'),
		_x('Sidi Abdelmoumen', 'CH', 'ry-wc-city-select'),
		_x('Sidi Bouzid Arragrag', 'CH', 'ry-wc-city-select'),
		_x('Sidi Ghanem', 'CH', 'ry-wc-city-select'),
		_x('Sidi LMokhtar', 'CH', 'ry-wc-city-select'),
		_x('Sidi M Hamed Dalil', 'CH', 'ry-wc-city-select'),
		_x('Taouloukoult', 'CH', 'ry-wc-city-select'),
		_x('Timezgadiouine', 'CH', 'ry-wc-city-select'),
		_x('Timlilt', 'CH', 'ry-wc-city-select'),
		_x('Zaouia Annahlia', 'CH', 'ry-wc-city-select'),
	],
	'CH2' => [
		_x('Ait Amira', 'CH2', 'ry-wc-city-select'),
		_x('Ait Baha', 'CH2', 'ry-wc-city-select'),
		_x('Ait Milk', 'CH2', 'ry-wc-city-select'),
		_x('Ait Mzal', 'CH2', 'ry-wc-city-select'),
		_x('Ait Ouadrim', 'CH2', 'ry-wc-city-select'),
		_x('Aouguenz', 'CH2', 'ry-wc-city-select'),
		_x('Belfaa', 'CH2', 'ry-wc-city-select'),
		_x('Biougra', 'CH2', 'ry-wc-city-select'),
		_x('Hilala', 'CH2', 'ry-wc-city-select'),
		_x('Ida Ougnidif', 'CH2', 'ry-wc-city-select'),
		_x('Imi Mqourn', 'CH2', 'ry-wc-city-select'),
		_x('Inchaden', 'CH2', 'ry-wc-city-select'),
		_x('Massa', 'CH2', 'ry-wc-city-select'),
		_x('Ouad Essafa', 'CH2', 'ry-wc-city-select'),
		_x('Sidi Abdallah El Bou', 'CH2', 'ry-wc-city-select'),
		_x('Sidi Bibi', 'CH2', 'ry-wc-city-select'),
		_x('Sidi Boushab', 'CH2', 'ry-wc-city-select'),
		_x('Sidi Ouassay', 'CH2', 'ry-wc-city-select'),
		_x('Tanalt', 'CH2', 'ry-wc-city-select'),
		_x('Targua Ntouchka', 'CH2', 'ry-wc-city-select'),
		_x('Tassegdelt', 'CH2', 'ry-wc-city-select'),
		_x('Tizi Ntakoucht', 'CH2', 'ry-wc-city-select'),
	],
	'EL' => [
		_x('Agourai', 'EL', 'ry-wc-city-select'),
		_x('Ain Taoujdate', 'EL', 'ry-wc-city-select'),
		_x('Ait Boubidmane', 'EL', 'ry-wc-city-select'),
		_x('Ait Bourzouine', 'EL', 'ry-wc-city-select'),
		_x('Ait Harz Allah', 'EL', 'ry-wc-city-select'),
		_x('Ait Naamane', 'EL', 'ry-wc-city-select'),
		_x('Ait Ouikhalfen', 'EL', 'ry-wc-city-select'),
		_x('Ait Yaazem', 'EL', 'ry-wc-city-select'),
		_x('Bitit', 'EL', 'ry-wc-city-select'),
		_x('Bouderbala', 'EL', 'ry-wc-city-select'),
		_x('El Hajeb', 'EL', 'ry-wc-city-select'),
		_x('Iqaddar', 'EL', 'ry-wc-city-select'),
		_x('Jahjouh', 'EL', 'ry-wc-city-select'),
		_x('Laqsir', 'EL', 'ry-wc-city-select'),
		_x('Ras Ijerri', 'EL', 'ry-wc-city-select'),
		_x('Sabaa Aiyoun', 'EL', 'ry-wc-city-select'),
		_x('Sebt Jahjouh', 'EL', 'ry-wc-city-select'),
		_x('Tamchachate', 'EL', 'ry-wc-city-select'),
	],
	'EL2' => [
		_x('Azemmour', 'EL2', 'ry-wc-city-select'),
		_x('Bni Hilal', 'EL2', 'ry-wc-city-select'),
		_x('Bni Tsiriss', 'EL2', 'ry-wc-city-select'),
		_x('Bouhmame', 'EL2', 'ry-wc-city-select'),
		_x('Boulaouane', 'EL2', 'ry-wc-city-select'),
		_x('Chaibate', 'EL2', 'ry-wc-city-select'),
		_x('Chtouka', 'EL2', 'ry-wc-city-select'),
		_x('El-Jadida', 'EL2', 'ry-wc-city-select'),
		_x('Haouzia', 'EL2', 'ry-wc-city-select'),
		_x('Jabria', 'EL2', 'ry-wc-city-select'),
		_x('Karia', 'EL2', 'ry-wc-city-select'),
		_x('Khmis Ksiba', 'EL2', 'ry-wc-city-select'),
		_x('Koudiat Bni Dghough', 'EL2', 'ry-wc-city-select'),
		_x('Kridid', 'EL2', 'ry-wc-city-select'),
		_x('Laagagcha', 'EL2', 'ry-wc-city-select'),
		_x('Laamria', 'EL2', 'ry-wc-city-select'),
		_x('Laaounate', 'EL2', 'ry-wc-city-select'),
		_x('Laatatra', 'EL2', 'ry-wc-city-select'),
		_x('Laghdira', 'EL2', 'ry-wc-city-select'),
		_x('Laghnadra', 'EL2', 'ry-wc-city-select'),
		_x('Lamharza Essahel', 'EL2', 'ry-wc-city-select'),
		_x('Lbir Jdid', 'EL2', 'ry-wc-city-select'),
		_x('Lgharbia', 'EL2', 'ry-wc-city-select'),
		_x('Lmechrek', 'EL2', 'ry-wc-city-select'),
		_x('Loualidia', 'EL2', 'ry-wc-city-select'),
		_x('M Tal', 'EL2', 'ry-wc-city-select'),
		_x('Metrane', 'EL2', 'ry-wc-city-select'),
		_x('Mettouh', 'EL2', 'ry-wc-city-select'),
		_x('Mogress', 'EL2', 'ry-wc-city-select'),
		_x('Moulay Abdallah', 'EL2', 'ry-wc-city-select'),
		_x('My Abdallah', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Aissa', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Amrane', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Boussaken', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Frej', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Ghadbane', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Ghanem', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Hamdane', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Hcine', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Rahmoune', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Sbaita', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Si Bouhya', 'EL2', 'ry-wc-city-select'),
		_x('Oulad Sidi Ali  Ben', 'EL2', 'ry-wc-city-select'),
		_x('Saniat Berguig', 'EL2', 'ry-wc-city-select'),
		_x('Sebt Lamaarif', 'EL2', 'ry-wc-city-select'),
		_x('Sebt Saiss', 'EL2', 'ry-wc-city-select'),
		_x('Sidi Abed', 'EL2', 'ry-wc-city-select'),
		_x('Sidi Ali Ben Hamdouc', 'EL2', 'ry-wc-city-select'),
		_x('Sidi Bennour', 'EL2', 'ry-wc-city-select'),
		_x('Sidi Bouzid', 'EL2', 'ry-wc-city-select'),
		_x('Sidi M Hamed  Akhdim', 'EL2', 'ry-wc-city-select'),
		_x('Sidi Smail', 'EL2', 'ry-wc-city-select'),
		_x('Sihsaien Ben  Abderr', 'EL2', 'ry-wc-city-select'),
		_x('Tamda', 'EL2', 'ry-wc-city-select'),
		_x('Zaouiat Lakouacem', 'EL2', 'ry-wc-city-select'),
		_x('Zaouiat Saiss', 'EL2', 'ry-wc-city-select'),
		_x('Zemamra', 'EL2', 'ry-wc-city-select'),
	],
	'ER' => [
		_x('Aarab Sebbah Gheris', 'ER', 'ry-wc-city-select'),
		_x('Aarab Sebbah Ziz', 'ER', 'ry-wc-city-select'),
		_x('Aghbalou N Kerdous', 'ER', 'ry-wc-city-select'),
		_x('Ait Hani', 'ER', 'ry-wc-city-select'),
		_x('Ait Yahya', 'ER', 'ry-wc-city-select'),
		_x('Alnif', 'ER', 'ry-wc-city-select'),
		_x('Amellagou', 'ER', 'ry-wc-city-select'),
		_x('Amouguer', 'ER', 'ry-wc-city-select'),
		_x('Aoufous', 'ER', 'ry-wc-city-select'),
		_x('Arfoud', 'ER', 'ry-wc-city-select'),
		_x('Assoul', 'ER', 'ry-wc-city-select'),
		_x('Bni M Hamed  Sijelma', 'ER', 'ry-wc-city-select'),
		_x('Bou Azmou', 'ER', 'ry-wc-city-select'),
		_x('Boudnib', 'ER', 'ry-wc-city-select'),
		_x('Chorfa M Daghra', 'ER', 'ry-wc-city-select'),
		_x('En-Nzala', 'ER', 'ry-wc-city-select'),
		_x('Er-Rich', 'ER', 'ry-wc-city-select'),
		_x('Er-Rissani', 'ER', 'ry-wc-city-select'),
		_x('Er-Rteb', 'ER', 'ry-wc-city-select'),
		_x('Errachidia', 'ER', 'ry-wc-city-select'),
		_x('Es-Sfalat', 'ER', 'ry-wc-city-select'),
		_x('Es-Sifa', 'ER', 'ry-wc-city-select'),
		_x('Et-Taous', 'ER', 'ry-wc-city-select'),
		_x('Ferkla El Oulia', 'ER', 'ry-wc-city-select'),
		_x('Ferkla Es-Soufla', 'ER', 'ry-wc-city-select'),
		_x('Fezna', 'ER', 'ry-wc-city-select'),
		_x('Gheris El Ouloui', 'ER', 'ry-wc-city-select'),
		_x('Gheris Es-Soufli', 'ER', 'ry-wc-city-select'),
		_x('Goulmima', 'ER', 'ry-wc-city-select'),
		_x('Gourrama', 'ER', 'ry-wc-city-select'),
		_x('Guers Tiaallaline', 'ER', 'ry-wc-city-select'),
		_x('Guir', 'ER', 'ry-wc-city-select'),
		_x('H Ssyia', 'ER', 'ry-wc-city-select'),
		_x('Imilchil', 'ER', 'ry-wc-city-select'),
		_x('Jorf', 'ER', 'ry-wc-city-select'),
		_x('Lkheng', 'ER', 'ry-wc-city-select'),
		_x('M Ssici', 'ER', 'ry-wc-city-select'),
		_x('M Zizel', 'ER', 'ry-wc-city-select'),
		_x('Melaab', 'ER', 'ry-wc-city-select'),
		_x('Moulay Ali Cherif', 'ER', 'ry-wc-city-select'),
		_x('Oued Naam', 'ER', 'ry-wc-city-select'),
		_x('Outerbat', 'ER', 'ry-wc-city-select'),
		_x('Sidi Aayad', 'ER', 'ry-wc-city-select'),
		_x('Sidi Ali', 'ER', 'ry-wc-city-select'),
		_x('Tadighoust', 'ER', 'ry-wc-city-select'),
		_x('Tinejdad', 'ER', 'ry-wc-city-select'),
		_x('Zaouiat Sidi Hamza', 'ER', 'ry-wc-city-select'),
	],
	'ES' => [
		_x('Amgala', 'ES', 'ry-wc-city-select'),
		_x('Es-Semara', 'ES', 'ry-wc-city-select'),
		_x('Haouza', 'ES', 'ry-wc-city-select'),
		_x('Jdiriya', 'ES', 'ry-wc-city-select'),
		_x('Sidi Ahmed Laaroussi', 'ES', 'ry-wc-city-select'),
		_x('Tifariti', 'ES', 'ry-wc-city-select'),
	],
	'ES2' => [
		_x('Adaghas', 'ES2', 'ry-wc-city-select'),
		_x('Aglif', 'ES2', 'ry-wc-city-select'),
		_x('Aguerd', 'ES2', 'ry-wc-city-select'),
		_x('Ait Aissi Ihahane', 'ES2', 'ry-wc-city-select'),
		_x('Ait Daoud', 'ES2', 'ry-wc-city-select'),
		_x('Ait Said', 'ES2', 'ry-wc-city-select'),
		_x('Aquermoud', 'ES2', 'ry-wc-city-select'),
		_x('Assais', 'ES2', 'ry-wc-city-select'),
		_x('Bizdad', 'ES2', 'ry-wc-city-select'),
		_x('Bouzemmour', 'ES2', 'ry-wc-city-select'),
		_x('Elhanchane', 'ES2', 'ry-wc-city-select'),
		_x('Essaouira', 'ES2', 'ry-wc-city-select'),
		_x('Ezzaouite', 'ES2', 'ry-wc-city-select'),
		_x('Had Dra', 'ES2', 'ry-wc-city-select'),
		_x('Ida Ou Aazza', 'ES2', 'ry-wc-city-select'),
		_x('Ida Ou Guelloul', 'ES2', 'ry-wc-city-select'),
		_x('Ida Ou Kazzou', 'ES2', 'ry-wc-city-select'),
		_x('Imgrade', 'ES2', 'ry-wc-city-select'),
		_x('Imi N Tlit', 'ES2', 'ry-wc-city-select'),
		_x('Kechoula', 'ES2', 'ry-wc-city-select'),
		_x('Korimate', 'ES2', 'ry-wc-city-select'),
		_x('Lagdadra', 'ES2', 'ry-wc-city-select'),
		_x('Lahsinate', 'ES2', 'ry-wc-city-select'),
		_x('M Khalif', 'ES2', 'ry-wc-city-select'),
		_x('M Ramer', 'ES2', 'ry-wc-city-select'),
		_x('Mejji', 'ES2', 'ry-wc-city-select'),
		_x('Meskala', 'ES2', 'ry-wc-city-select'),
		_x('Mouarid', 'ES2', 'ry-wc-city-select'),
		_x('Moulay Bouzarqtoune', 'ES2', 'ry-wc-city-select'),
		_x('Mzilate', 'ES2', 'ry-wc-city-select'),
		_x('Oulad M Rabet', 'ES2', 'ry-wc-city-select'),
		_x('Ounagha', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Abdeljalil', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Ahmed Essayeh', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Aissa Regragui', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Ali El Korati', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Boulaalam', 'ES2', 'ry-wc-city-select'),
		_x('Sidi El Jazouli', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Ghaneme', 'ES2', 'ry-wc-city-select'),
		_x('Sidi H Mad  Ou M Bar', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Hmad Ou Hamed', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Ishaq', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Kaouki', 'ES2', 'ry-wc-city-select'),
		_x('Sidi Laaroussi', 'ES2', 'ry-wc-city-select'),
		_x('Sidi M Hamed Ou Marz', 'ES2', 'ry-wc-city-select'),
		_x('Smimou', 'ES2', 'ry-wc-city-select'),
		_x('Tafedna', 'ES2', 'ry-wc-city-select'),
		_x('Tafetachte', 'ES2', 'ry-wc-city-select'),
		_x('Tahelouante', 'ES2', 'ry-wc-city-select'),
		_x('Takate', 'ES2', 'ry-wc-city-select'),
		_x('Takoucht', 'ES2', 'ry-wc-city-select'),
		_x('Talmest', 'ES2', 'ry-wc-city-select'),
		_x('Tamanar', 'ES2', 'ry-wc-city-select'),
		_x('Targante', 'ES2', 'ry-wc-city-select'),
		_x('Tidzi', 'ES2', 'ry-wc-city-select'),
		_x('Timizguida Ouftas', 'ES2', 'ry-wc-city-select'),
		_x('Zaouiat Ben Hmida', 'ES2', 'ry-wc-city-select'),
	],
	'FA' => [
		_x('Albahraoyine', 'FA', 'ry-wc-city-select'),
		_x('Anjra', 'FA', 'ry-wc-city-select'),
		_x('Jouamaa', 'FA', 'ry-wc-city-select'),
		_x('Ksar El Majaz', 'FA', 'ry-wc-city-select'),
		_x('Ksar Sghir', 'FA', 'ry-wc-city-select'),
		_x('Laaouama', 'FA', 'ry-wc-city-select'),
		_x('Malloussa', 'FA', 'ry-wc-city-select'),
		_x('Taghramt', 'FA', 'ry-wc-city-select'),
	],
	'FE' => [
		_x('Agdal', 'FE', 'ry-wc-city-select'),
		_x('Ain Bida', 'FE', 'ry-wc-city-select'),
		_x('Elmariniyine', 'FE', 'ry-wc-city-select'),
		_x('Fes-Medina', 'FE', 'ry-wc-city-select'),
		_x('Jnan El Ouard', 'FE', 'ry-wc-city-select'),
		_x('Mechouar Fes Jdid', 'FE', 'ry-wc-city-select'),
		_x('Oulad Tayeb', 'FE', 'ry-wc-city-select'),
		_x('Saiss', 'FE', 'ry-wc-city-select'),
		_x('Sidi Harazem', 'FE', 'ry-wc-city-select'),
		_x('Skhinate', 'FE', 'ry-wc-city-select'),
		_x('Zouagha', 'FE', 'ry-wc-city-select'),
	],
	'FI' => [
		_x('Abbou Lakhal', 'FI', 'ry-wc-city-select'),
		_x('Ain Chouater', 'FI', 'ry-wc-city-select'),
		_x('Bni Guil', 'FI', 'ry-wc-city-select'),
		_x('Bni Tadjite', 'FI', 'ry-wc-city-select'),
		_x('Bouanane', 'FI', 'ry-wc-city-select'),
		_x('Bouarfa', 'FI', 'ry-wc-city-select'),
		_x('Bouchaouene', 'FI', 'ry-wc-city-select'),
		_x('Boumerieme', 'FI', 'ry-wc-city-select'),
		_x('Figuig', 'FI', 'ry-wc-city-select'),
		_x('Maatarka', 'FI', 'ry-wc-city-select'),
		_x('Talsint', 'FI', 'ry-wc-city-select'),
		_x('Tendrara', 'FI', 'ry-wc-city-select'),
	],
	'FQBESAPR' => [
		_x('Fquih Ben Salah', 'FQBESAPR', 'ry-wc-city-select'),
	],
	'GU' => [
		_x('Abaynou', 'GU', 'ry-wc-city-select'),
		_x('Aday', 'GU', 'ry-wc-city-select'),
		_x('Aferkat', 'GU', 'ry-wc-city-select'),
		_x('Ait Boufoulen', 'GU', 'ry-wc-city-select'),
		_x('Amtdi', 'GU', 'ry-wc-city-select'),
		_x('Asrir', 'GU', 'ry-wc-city-select'),
		_x('Bouizakarne', 'GU', 'ry-wc-city-select'),
		_x('Echatea El Abied', 'GU', 'ry-wc-city-select'),
		_x('Fask', 'GU', 'ry-wc-city-select'),
		_x('Guelmim', 'GU', 'ry-wc-city-select'),
		_x('Ifrane Atlas Saghir', 'GU', 'ry-wc-city-select'),
		_x('Labyar', 'GU', 'ry-wc-city-select'),
		_x('Laqsabi Tagoust', 'GU', 'ry-wc-city-select'),
		_x('Rass Oumlil', 'GU', 'ry-wc-city-select'),
		_x('Tagante', 'GU', 'ry-wc-city-select'),
		_x('Taghjijt', 'GU', 'ry-wc-city-select'),
		_x('Taliouine Assaka', 'GU', 'ry-wc-city-select'),
		_x('Targa Wassay', 'GU', 'ry-wc-city-select'),
		_x('Tiglit', 'GU', 'ry-wc-city-select'),
		_x('Timoulay', 'GU', 'ry-wc-city-select'),
	],
	'IF' => [
		_x('Ain Leuh', 'IF', 'ry-wc-city-select'),
		_x('Azrou', 'IF', 'ry-wc-city-select'),
		_x('Ben Smim', 'IF', 'ry-wc-city-select'),
		_x('Dayat Aoua', 'IF', 'ry-wc-city-select'),
		_x('Ifrane', 'IF', 'ry-wc-city-select'),
		_x('Oued Ifrane', 'IF', 'ry-wc-city-select'),
		_x('Sidi Addi', 'IF', 'ry-wc-city-select'),
		_x('Sidi El Makhfi', 'IF', 'ry-wc-city-select'),
		_x('Souk LHad', 'IF', 'ry-wc-city-select'),
		_x('Tigrigra', 'IF', 'ry-wc-city-select'),
		_x('Timahdite', 'IF', 'ry-wc-city-select'),
		_x('Tizguite', 'IF', 'ry-wc-city-select'),
	],
	'INME' => [
		_x('Ait Melloul', 'INME', 'ry-wc-city-select'),
		_x('Dcheira El Jihadia', 'INME', 'ry-wc-city-select'),
		_x('Inezgane', 'INME', 'ry-wc-city-select'),
		_x('Lqliaa', 'INME', 'ry-wc-city-select'),
		_x('Oulad Dahou', 'INME', 'ry-wc-city-select'),
		_x('Temsia', 'INME', 'ry-wc-city-select'),
	],
	'JE' => [
		_x('Ain Bni Mathar', 'JE', 'ry-wc-city-select'),
		_x('Bni Mathar', 'JE', 'ry-wc-city-select'),
		_x('Gafait', 'JE', 'ry-wc-city-select'),
		_x('Guenfouda', 'JE', 'ry-wc-city-select'),
		_x('Jerada', 'JE', 'ry-wc-city-select'),
		_x('Laaouinate', 'JE', 'ry-wc-city-select'),
		_x('Lebkhata', 'JE', 'ry-wc-city-select'),
		_x('Mrija', 'JE', 'ry-wc-city-select'),
		_x('Oued El Heimer', 'JE', 'ry-wc-city-select'),
		_x('Oulad Ghziyel', 'JE', 'ry-wc-city-select'),
		_x('Oulad Sidi  Abdelhak', 'JE', 'ry-wc-city-select'),
		_x('Ras Asfour', 'JE', 'ry-wc-city-select'),
		_x('Sidi Boubker', 'JE', 'ry-wc-city-select'),
		_x('Tiouli', 'JE', 'ry-wc-city-select'),
		_x('Touissit', 'JE', 'ry-wc-city-select'),
	],
	'KE' => [
		_x('Ait Hammou', 'KE', 'ry-wc-city-select'),
		_x('Ait Taleb', 'KE', 'ry-wc-city-select'),
		_x('Akarma', 'KE', 'ry-wc-city-select'),
		_x('Assahrij', 'KE', 'ry-wc-city-select'),
		_x('Ben Guerir', 'KE', 'ry-wc-city-select'),
		_x('Bouchane', 'KE', 'ry-wc-city-select'),
		_x('Bourrous', 'KE', 'ry-wc-city-select'),
		_x('Bouya Omar', 'KE', 'ry-wc-city-select'),
		_x('Choara', 'KE', 'ry-wc-city-select'),
		_x('Chtaiba', 'KE', 'ry-wc-city-select'),
		_x('Dzouz', 'KE', 'ry-wc-city-select'),
		_x('Eddachra', 'KE', 'ry-wc-city-select'),
		_x('El Kelaa Des Sraghna', 'KE', 'ry-wc-city-select'),
		_x('Elaamria', 'KE', 'ry-wc-city-select'),
		_x('Elmarbouh', 'KE', 'ry-wc-city-select'),
		_x('Errafiaya', 'KE', 'ry-wc-city-select'),
		_x('Fraita', 'KE', 'ry-wc-city-select'),
		_x('Hiadna', 'KE', 'ry-wc-city-select'),
		_x('Jaafra', 'KE', 'ry-wc-city-select'),
		_x('Jaidate', 'KE', 'ry-wc-city-select'),
		_x('Jbiel', 'KE', 'ry-wc-city-select'),
		_x('Jouala', 'KE', 'ry-wc-city-select'),
		_x('Laatamna', 'KE', 'ry-wc-city-select'),
		_x('Laattaouia', 'KE', 'ry-wc-city-select'),
		_x('Laattaouia  Ech-Chay', 'KE', 'ry-wc-city-select'),
		_x('Labrikiyne', 'KE', 'ry-wc-city-select'),
		_x('Lamharra', 'KE', 'ry-wc-city-select'),
		_x('Loued Lakhdar', 'KE', 'ry-wc-city-select'),
		_x('Lounasda', 'KE', 'ry-wc-city-select'),
		_x('M Zem Sanhaja', 'KE', 'ry-wc-city-select'),
		_x('Mayate', 'KE', 'ry-wc-city-select'),
		_x('Nzalat Laadam', 'KE', 'ry-wc-city-select'),
		_x('Ouargui', 'KE', 'ry-wc-city-select'),
		_x('Oulad Aamer', 'KE', 'ry-wc-city-select'),
		_x('Oulad Aamer  Tizmari', 'KE', 'ry-wc-city-select'),
		_x('Oulad Aarrad', 'KE', 'ry-wc-city-select'),
		_x('Oulad Bouali Loued', 'KE', 'ry-wc-city-select'),
		_x('Oulad Cherki', 'KE', 'ry-wc-city-select'),
		_x('Oulad El Garne', 'KE', 'ry-wc-city-select'),
		_x('Oulad Hassoune Hamri', 'KE', 'ry-wc-city-select'),
		_x('Oulad Imloul', 'KE', 'ry-wc-city-select'),
		_x('Oulad Khallouf', 'KE', 'ry-wc-city-select'),
		_x('Oulad Massaoud', 'KE', 'ry-wc-city-select'),
		_x('Oulad Msabbel', 'KE', 'ry-wc-city-select'),
		_x('Oulad Sbih', 'KE', 'ry-wc-city-select'),
		_x('Oulad Yaacoub', 'KE', 'ry-wc-city-select'),
		_x('Oulad Zarrad', 'KE', 'ry-wc-city-select'),
		_x('Ras Ain Rhamna', 'KE', 'ry-wc-city-select'),
		_x('Sidi Abdallah', 'KE', 'ry-wc-city-select'),
		_x('Sidi Aissa Ben  Slim', 'KE', 'ry-wc-city-select'),
		_x('Sidi Ali Labrahla', 'KE', 'ry-wc-city-select'),
		_x('Sidi Bou Othmane', 'KE', 'ry-wc-city-select'),
		_x('Sidi Boubker', 'KE', 'ry-wc-city-select'),
		_x('Sidi El Hattab', 'KE', 'ry-wc-city-select'),
		_x('Sidi Ghanem', 'KE', 'ry-wc-city-select'),
		_x('Sidi Mansour', 'KE', 'ry-wc-city-select'),
		_x('Sidi Moussa', 'KE', 'ry-wc-city-select'),
		_x('Sidi Rahhal', 'KE', 'ry-wc-city-select'),
		_x('Skhour Rhamna', 'KE', 'ry-wc-city-select'),
		_x('Skoura Lhadra', 'KE', 'ry-wc-city-select'),
		_x('Sour El Aaz', 'KE', 'ry-wc-city-select'),
		_x('Tamallalt', 'KE', 'ry-wc-city-select'),
		_x('Taouzint', 'KE', 'ry-wc-city-select'),
		_x('Tlauh', 'KE', 'ry-wc-city-select'),
		_x('Zemrane', 'KE', 'ry-wc-city-select'),
		_x('Zemrane Charqia', 'KE', 'ry-wc-city-select'),
		_x('Znada', 'KE', 'ry-wc-city-select'),
	],
	'KEPR' => [
		_x('Ameur Seflia', 'KEPR', 'ry-wc-city-select'),
		_x('Arbaoua', 'KEPR', 'ry-wc-city-select'),
		_x('Azghar', 'KEPR', 'ry-wc-city-select'),
		_x('Bahhara Oulad Ayad', 'KEPR', 'ry-wc-city-select'),
		_x('Ben Mansour', 'KEPR', 'ry-wc-city-select'),
		_x('Beni Malek', 'KEPR', 'ry-wc-city-select'),
		_x('Boumaiz', 'KEPR', 'ry-wc-city-select'),
		_x('Chouafaa', 'KEPR', 'ry-wc-city-select'),
		_x('Dar Bel Amri', 'KEPR', 'ry-wc-city-select'),
		_x('Haddada', 'KEPR', 'ry-wc-city-select'),
		_x('Kariat Ben Aouda', 'KEPR', 'ry-wc-city-select'),
		_x('Kceibya', 'KEPR', 'ry-wc-city-select'),
		_x('Kenitra', 'KEPR', 'ry-wc-city-select'),
		_x('Lalla Mimouna', 'KEPR', 'ry-wc-city-select'),
		_x('M Saada', 'KEPR', 'ry-wc-city-select'),
		_x('Mehdya', 'KEPR', 'ry-wc-city-select'),
		_x('Mnasra', 'KEPR', 'ry-wc-city-select'),
		_x('Mograne', 'KEPR', 'ry-wc-city-select'),
		_x('Moulay Bousselham', 'KEPR', 'ry-wc-city-select'),
		_x('Oued El Makhazine', 'KEPR', 'ry-wc-city-select'),
		_x('Oulad Ben Hammadi', 'KEPR', 'ry-wc-city-select'),
		_x('Oulad H Cine', 'KEPR', 'ry-wc-city-select'),
		_x('Oulad Slama', 'KEPR', 'ry-wc-city-select'),
		_x('Sfafaa', 'KEPR', 'ry-wc-city-select'),
		_x('Sidi Allal Tazi', 'KEPR', 'ry-wc-city-select'),
		_x('Sidi Boubker El Haj', 'KEPR', 'ry-wc-city-select'),
		_x('Sidi Mohamed Lahmar', 'KEPR', 'ry-wc-city-select'),
		_x('Sidi Slimane', 'KEPR', 'ry-wc-city-select'),
		_x('Sidi Taibi', 'KEPR', 'ry-wc-city-select'),
		_x('Souk El Arbaa', 'KEPR', 'ry-wc-city-select'),
		_x('Souk Tlet El Gharb', 'KEPR', 'ry-wc-city-select'),
	],
	'KH' => [
		_x('Ain Johra', 'KH', 'ry-wc-city-select'),
		_x('Ain Sbit', 'KH', 'ry-wc-city-select'),
		_x('Ait Belkacem', 'KH', 'ry-wc-city-select'),
		_x('Ait Bouyahya  El Haj', 'KH', 'ry-wc-city-select'),
		_x('Ait Ichou', 'KH', 'ry-wc-city-select'),
		_x('Ait Ikkou', 'KH', 'ry-wc-city-select'),
		_x('Ait Malek', 'KH', 'ry-wc-city-select'),
		_x('Ait Mimoune', 'KH', 'ry-wc-city-select'),
		_x('Ait Ouribel', 'KH', 'ry-wc-city-select'),
		_x('Ait Siberne', 'KH', 'ry-wc-city-select'),
		_x('Ait Yadine', 'KH', 'ry-wc-city-select'),
		_x('Bouqachmir', 'KH', 'ry-wc-city-select'),
		_x('Brachoua', 'KH', 'ry-wc-city-select'),
		_x('Elganzra', 'KH', 'ry-wc-city-select'),
		_x('Ezzhiliga', 'KH', 'ry-wc-city-select'),
		_x('Houderrane', 'KH', 'ry-wc-city-select'),
		_x('Jemaat Moul Blad', 'KH', 'ry-wc-city-select'),
		_x('Khemis Sidi Yahya', 'KH', 'ry-wc-city-select'),
		_x('Khemisset', 'KH', 'ry-wc-city-select'),
		_x('Laghoualem', 'KH', 'ry-wc-city-select'),
		_x('M Qam Tolba', 'KH', 'ry-wc-city-select'),
		_x('Maaziz', 'KH', 'ry-wc-city-select'),
		_x('Majmaa Tolba', 'KH', 'ry-wc-city-select'),
		_x('Marchouch', 'KH', 'ry-wc-city-select'),
		_x('Moulay Driss Aghbal', 'KH', 'ry-wc-city-select'),
		_x('Oulmes', 'KH', 'ry-wc-city-select'),
		_x('Rommani', 'KH', 'ry-wc-city-select'),
		_x('Sfassif', 'KH', 'ry-wc-city-select'),
		_x('Sidi Abderrazak', 'KH', 'ry-wc-city-select'),
		_x('Sidi Allal El Bahrao', 'KH', 'ry-wc-city-select'),
		_x('Sidi Allal Lamsadder', 'KH', 'ry-wc-city-select'),
		_x('Sidi Boukhalkhal', 'KH', 'ry-wc-city-select'),
		_x('Sidi El Ghandour', 'KH', 'ry-wc-city-select'),
		_x('Tiddas', 'KH', 'ry-wc-city-select'),
		_x('Tiflet', 'KH', 'ry-wc-city-select'),
	],
	'KH2' => [
		_x('Aghbalou', 'KH2', 'ry-wc-city-select'),
		_x('Aghbalou Nssardane', 'KH2', 'ry-wc-city-select'),
		_x('Agoudim', 'KH2', 'ry-wc-city-select'),
		_x('Aguelmam Azegza', 'KH2', 'ry-wc-city-select'),
		_x('Aguelmous', 'KH2', 'ry-wc-city-select'),
		_x('Ait Ayach', 'KH2', 'ry-wc-city-select'),
		_x('Ait Ben Yacoub', 'KH2', 'ry-wc-city-select'),
		_x('Ait Ishaq', 'KH2', 'ry-wc-city-select'),
		_x('Ait Izdeg', 'KH2', 'ry-wc-city-select'),
		_x('Ait Saadelli', 'KH2', 'ry-wc-city-select'),
		_x('Amalou Ighriben', 'KH2', 'ry-wc-city-select'),
		_x('Amersid', 'KH2', 'ry-wc-city-select'),
		_x('Anemzi', 'KH2', 'ry-wc-city-select'),
		_x('Boumia', 'KH2', 'ry-wc-city-select'),
		_x('El Hammam', 'KH2', 'ry-wc-city-select'),
		_x('El Kbab', 'KH2', 'ry-wc-city-select'),
		_x('Elborj', 'KH2', 'ry-wc-city-select'),
		_x('Had Bouhssoussen', 'KH2', 'ry-wc-city-select'),
		_x('Itzer', 'KH2', 'ry-wc-city-select'),
		_x('Kahf Nsour', 'KH2', 'ry-wc-city-select'),
		_x('Kerrouchen', 'KH2', 'ry-wc-city-select'),
		_x('Khenifra', 'KH2', 'ry-wc-city-select'),
		_x('Lehri', 'KH2', 'ry-wc-city-select'),
		_x('MRirt', 'KH2', 'ry-wc-city-select'),
		_x('Mibladen', 'KH2', 'ry-wc-city-select'),
		_x('Midelt', 'KH2', 'ry-wc-city-select'),
		_x('Moha Ou Hammou Zayan', 'KH2', 'ry-wc-city-select'),
		_x('Moulay Bouazza', 'KH2', 'ry-wc-city-select'),
		_x('Ouaoumana', 'KH2', 'ry-wc-city-select'),
		_x('Oum Rabia', 'KH2', 'ry-wc-city-select'),
		_x('Sebt Ait Rahou', 'KH2', 'ry-wc-city-select'),
		_x('Sidi Amar', 'KH2', 'ry-wc-city-select'),
		_x('Sidi Hcine', 'KH2', 'ry-wc-city-select'),
		_x('Sidi Lamine', 'KH2', 'ry-wc-city-select'),
		_x('Sidi Yahya Ou Saad', 'KH2', 'ry-wc-city-select'),
		_x('Sidi Yahya Ou Yousse', 'KH2', 'ry-wc-city-select'),
		_x('Tanourdi', 'KH2', 'ry-wc-city-select'),
		_x('Tighassaline', 'KH2', 'ry-wc-city-select'),
		_x('Tighza', 'KH2', 'ry-wc-city-select'),
		_x('Tizi N Ghachou', 'KH2', 'ry-wc-city-select'),
		_x('Tounfite', 'KH2', 'ry-wc-city-select'),
		_x('Zaida', 'KH2', 'ry-wc-city-select'),
	],
	'KHPR' => [
		_x('Ain Kaicher', 'KHPR', 'ry-wc-city-select'),
		_x('Ait Ammar', 'KHPR', 'ry-wc-city-select'),
		_x('Bejaad', 'KHPR', 'ry-wc-city-select'),
		_x('Bir Mezoui', 'KHPR', 'ry-wc-city-select'),
		_x('Bni Bataou', 'KHPR', 'ry-wc-city-select'),
		_x('Bni Smir', 'KHPR', 'ry-wc-city-select'),
		_x('Bni Ykhlef', 'KHPR', 'ry-wc-city-select'),
		_x('Bni Zrantel', 'KHPR', 'ry-wc-city-select'),
		_x('Boukhrisse', 'KHPR', 'ry-wc-city-select'),
		_x('Boulanouare', 'KHPR', 'ry-wc-city-select'),
		_x('Braksa', 'KHPR', 'ry-wc-city-select'),
		_x('Chougrane', 'KHPR', 'ry-wc-city-select'),
		_x('Elfoqra', 'KHPR', 'ry-wc-city-select'),
		_x('Hattane', 'KHPR', 'ry-wc-city-select'),
		_x('Kasbat Troch', 'KHPR', 'ry-wc-city-select'),
		_x('Khouribga', 'KHPR', 'ry-wc-city-select'),
		_x('Lagfaf', 'KHPR', 'ry-wc-city-select'),
		_x('Lagnadiz', 'KHPR', 'ry-wc-city-select'),
		_x('M Fassis', 'KHPR', 'ry-wc-city-select'),
		_x('Maadna', 'KHPR', 'ry-wc-city-select'),
		_x('Oued Zem', 'KHPR', 'ry-wc-city-select'),
		_x('Oulad Abdoune', 'KHPR', 'ry-wc-city-select'),
		_x('Oulad Aissa', 'KHPR', 'ry-wc-city-select'),
		_x('Oulad Azzouz', 'KHPR', 'ry-wc-city-select'),
		_x('Oulad Boughadi', 'KHPR', 'ry-wc-city-select'),
		_x('Oulad Fennane', 'KHPR', 'ry-wc-city-select'),
		_x('Oulad Ftata', 'KHPR', 'ry-wc-city-select'),
		_x('Oulad Gouaouch', 'KHPR', 'ry-wc-city-select'),
		_x('Rouached', 'KHPR', 'ry-wc-city-select'),
		_x('Tachrafat', 'KHPR', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Akhfennir', 'LA', 'ry-wc-city-select'),
		_x('Boukraa', 'LA', 'ry-wc-city-select'),
		_x('Daoura', 'LA', 'ry-wc-city-select'),
		_x('Dcheira', 'LA', 'ry-wc-city-select'),
		_x('Elhagounia', 'LA', 'ry-wc-city-select'),
		_x('Elmarsa', 'LA', 'ry-wc-city-select'),
		_x('Foum El Oued', 'LA', 'ry-wc-city-select'),
		_x('Laayoune', 'LA', 'ry-wc-city-select'),
		_x('Tah', 'LA', 'ry-wc-city-select'),
		_x('Tarfaya', 'LA', 'ry-wc-city-select'),
	],
	'LA2' => [
		_x('Ayacha', 'LA2', 'ry-wc-city-select'),
		_x('Bni Arouss', 'LA2', 'ry-wc-city-select'),
		_x('Bni Garfett', 'LA2', 'ry-wc-city-select'),
		_x('Bou Jedyane', 'LA2', 'ry-wc-city-select'),
		_x('Khemis Sahel', 'LA2', 'ry-wc-city-select'),
		_x('Ksar Bjir', 'LA2', 'ry-wc-city-select'),
		_x('Ksar El Kebir', 'LA2', 'ry-wc-city-select'),
		_x('Laouamra', 'LA2', 'ry-wc-city-select'),
		_x('Larache', 'LA2', 'ry-wc-city-select'),
		_x('Oulad Ouchih', 'LA2', 'ry-wc-city-select'),
		_x('Rissana Chamalia', 'LA2', 'ry-wc-city-select'),
		_x('Rissana Janoubia', 'LA2', 'ry-wc-city-select'),
		_x('Sahel', 'LA2', 'ry-wc-city-select'),
		_x('Souaken', 'LA2', 'ry-wc-city-select'),
		_x('Souk L Qolla', 'LA2', 'ry-wc-city-select'),
		_x('Souk Tolba', 'LA2', 'ry-wc-city-select'),
		_x('Tatoft', 'LA2', 'ry-wc-city-select'),
		_x('Tazroute', 'LA2', 'ry-wc-city-select'),
		_x('Zaaroura', 'LA2', 'ry-wc-city-select'),
		_x('Zouada', 'LA2', 'ry-wc-city-select'),
	],
	'MD' => [
		_x('MDiq', 'MD', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Agafay', 'MA', 'ry-wc-city-select'),
		_x('Ait Imour', 'MA', 'ry-wc-city-select'),
		_x('Alouidane', 'MA', 'ry-wc-city-select'),
		_x('Annakhil', 'MA', 'ry-wc-city-select'),
		_x('Gueliz', 'MA', 'ry-wc-city-select'),
		_x('Harbil', 'MA', 'ry-wc-city-select'),
		_x('Kettara', 'MA', 'ry-wc-city-select'),
		_x('Loudaya', 'MA', 'ry-wc-city-select'),
		_x('MNabha', 'MA', 'ry-wc-city-select'),
		_x('Marrakech-Medina', 'MA', 'ry-wc-city-select'),
		_x('Mechouar Kasba', 'MA', 'ry-wc-city-select'),
		_x('Menara', 'MA', 'ry-wc-city-select'),
		_x('Ouahat Sidi Brahim', 'MA', 'ry-wc-city-select'),
		_x('Oulad Hassoune', 'MA', 'ry-wc-city-select'),
		_x('Ouled Dlim', 'MA', 'ry-wc-city-select'),
		_x('Saada', 'MA', 'ry-wc-city-select'),
		_x('Sid Zouine', 'MA', 'ry-wc-city-select'),
		_x('Sidi Youssef Ben Ali', 'MA', 'ry-wc-city-select'),
		_x('Souihla', 'MA', 'ry-wc-city-select'),
		_x('Tassoultante', 'MA', 'ry-wc-city-select'),
	],
	'ME' => [
		_x('Almajjatia Oulad Tal', 'ME', 'ry-wc-city-select'),
		_x('Lahraouyine', 'ME', 'ry-wc-city-select'),
		_x('Mediouna', 'ME', 'ry-wc-city-select'),
		_x('Sidi Hajjaj Oued Has', 'ME', 'ry-wc-city-select'),
		_x('Tit Mellil', 'ME', 'ry-wc-city-select'),
	],
	'ME2' => [
		_x('Ain Jemaa', 'ME2', 'ry-wc-city-select'),
		_x('Ain Karma', 'ME2', 'ry-wc-city-select'),
		_x('Ain Orma', 'ME2', 'ry-wc-city-select'),
		_x('Ait Ouallal', 'ME2', 'ry-wc-city-select'),
		_x('Al Machouar-Stinia', 'ME2', 'ry-wc-city-select'),
		_x('Boufakrane', 'ME2', 'ry-wc-city-select'),
		_x('Charqaoua', 'ME2', 'ry-wc-city-select'),
		_x('Dar Oum Soltane', 'ME2', 'ry-wc-city-select'),
		_x('Dkhissa', 'ME2', 'ry-wc-city-select'),
		_x('Hadj Kaddour', 'ME2', 'ry-wc-city-select'),
		_x('Karmet Ben Salem', 'ME2', 'ry-wc-city-select'),
		_x('M Haya', 'ME2', 'ry-wc-city-select'),
		_x('MRhassiyine', 'ME2', 'ry-wc-city-select'),
		_x('Majjate', 'ME2', 'ry-wc-city-select'),
		_x('Meknes', 'ME2', 'ry-wc-city-select'),
		_x('Moulay Driss Zerhoun', 'ME2', 'ry-wc-city-select'),
		_x('NZalat', 'ME2', 'ry-wc-city-select'),
		_x('NZalat Bni Amar', 'ME2', 'ry-wc-city-select'),
		_x('Oualili', 'ME2', 'ry-wc-city-select'),
		_x('Oued Jdida', 'ME2', 'ry-wc-city-select'),
		_x('Oued Rommane', 'ME2', 'ry-wc-city-select'),
		_x('Ouislane', 'ME2', 'ry-wc-city-select'),
		_x('Sidi Abdallah Khayat', 'ME2', 'ry-wc-city-select'),
		_x('Sidi Sliman Mol Kifa', 'ME2', 'ry-wc-city-select'),
		_x('Toulal', 'ME2', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Ain Harrouda', 'MO', 'ry-wc-city-select'),
		_x('Bni Yakhlef', 'MO', 'ry-wc-city-select'),
		_x('Ech-Challalate', 'MO', 'ry-wc-city-select'),
		_x('Mohammedia', 'MO', 'ry-wc-city-select'),
		_x('Sidi Moussa Ben Ali', 'MO', 'ry-wc-city-select'),
		_x('Sidi Moussa Majdoub', 'MO', 'ry-wc-city-select'),
	],
	'MO2' => [
		_x('Ain Bou Ali', 'MO2', 'ry-wc-city-select'),
		_x('Ain Chkef', 'MO2', 'ry-wc-city-select'),
		_x('Ain Kansra', 'MO2', 'ry-wc-city-select'),
		_x('Laajajra', 'MO2', 'ry-wc-city-select'),
		_x('Louadaine', 'MO2', 'ry-wc-city-select'),
		_x('Mikkes', 'MO2', 'ry-wc-city-select'),
		_x('Moulay Yacoub', 'MO2', 'ry-wc-city-select'),
		_x('Oulad Mimoun', 'MO2', 'ry-wc-city-select'),
		_x('Sebaa Rouadi', 'MO2', 'ry-wc-city-select'),
		_x('Sebt Loudaya', 'MO2', 'ry-wc-city-select'),
		_x('Sidi Daoud', 'MO2', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Afsou', 'NA', 'ry-wc-city-select'),
		_x('Ain Zohra', 'NA', 'ry-wc-city-select'),
		_x('Ait Mait', 'NA', 'ry-wc-city-select'),
		_x('Al Aaroui', 'NA', 'ry-wc-city-select'),
		_x('Albarkanyene', 'NA', 'ry-wc-city-select'),
		_x('Amejjaou', 'NA', 'ry-wc-city-select'),
		_x('Arekmane', 'NA', 'ry-wc-city-select'),
		_x('Azlaf', 'NA', 'ry-wc-city-select'),
		_x('Ben Taieb', 'NA', 'ry-wc-city-select'),
		_x('Bni Ansar', 'NA', 'ry-wc-city-select'),
		_x('Bni Bouifrour', 'NA', 'ry-wc-city-select'),
		_x('Bni Chiker', 'NA', 'ry-wc-city-select'),
		_x('Bni Marghnine', 'NA', 'ry-wc-city-select'),
		_x('Bni Oukil  Oulad M H', 'NA', 'ry-wc-city-select'),
		_x('Bni Sidel Jbel', 'NA', 'ry-wc-city-select'),
		_x('Bni Sidel Louta', 'NA', 'ry-wc-city-select'),
		_x('Bouarg', 'NA', 'ry-wc-city-select'),
		_x('Boudinar', 'NA', 'ry-wc-city-select'),
		_x('Bouizazarene Ihaddad', 'NA', 'ry-wc-city-select'),
		_x('Dar El Kebdani', 'NA', 'ry-wc-city-select'),
		_x('Driouch', 'NA', 'ry-wc-city-select'),
		_x('Farkhana', 'NA', 'ry-wc-city-select'),
		_x('Hassi Berkane', 'NA', 'ry-wc-city-select'),
		_x('Iaazzanene', 'NA', 'ry-wc-city-select'),
		_x('Iferni', 'NA', 'ry-wc-city-select'),
		_x('Ihaddadene', 'NA', 'ry-wc-city-select'),
		_x('Ijermaouas', 'NA', 'ry-wc-city-select'),
		_x('Iksane', 'NA', 'ry-wc-city-select'),
		_x('Jaadar', 'NA', 'ry-wc-city-select'),
		_x('Kariat Arkmane', 'NA', 'ry-wc-city-select'),
		_x('Kassita', 'NA', 'ry-wc-city-select'),
		_x('Kourouna', 'NA', 'ry-wc-city-select'),
		_x('M Hajer', 'NA', 'ry-wc-city-select'),
		_x('Midar', 'NA', 'ry-wc-city-select'),
		_x('Nador', 'NA', 'ry-wc-city-select'),
		_x('Ouardana', 'NA', 'ry-wc-city-select'),
		_x('Oulad Amghar', 'NA', 'ry-wc-city-select'),
		_x('Oulad Boubker', 'NA', 'ry-wc-city-select'),
		_x('Oulad Daoud Zkhanine', 'NA', 'ry-wc-city-select'),
		_x('Oulad Settout', 'NA', 'ry-wc-city-select'),
		_x('Ras El Ma', 'NA', 'ry-wc-city-select'),
		_x('Selouane', 'NA', 'ry-wc-city-select'),
		_x('Tafersit', 'NA', 'ry-wc-city-select'),
		_x('Talilit', 'NA', 'ry-wc-city-select'),
		_x('Taouima', 'NA', 'ry-wc-city-select'),
		_x('Tazaghine', 'NA', 'ry-wc-city-select'),
		_x('Temsamane', 'NA', 'ry-wc-city-select'),
		_x('Tiztoutine', 'NA', 'ry-wc-city-select'),
		_x('Trougout', 'NA', 'ry-wc-city-select'),
		_x('Tsaft', 'NA', 'ry-wc-city-select'),
		_x('Zaio', 'NA', 'ry-wc-city-select'),
		_x('Zeghanghane', 'NA', 'ry-wc-city-select'),
	],
	'NO' => [
		_x('Bouskoura', 'NO', 'ry-wc-city-select'),
		_x('Dar Bouazza', 'NO', 'ry-wc-city-select'),
		_x('Lamkansa', 'NO', 'ry-wc-city-select'),
		_x('Nouaceur', 'NO', 'ry-wc-city-select'),
		_x('Oulad Salah', 'NO', 'ry-wc-city-select'),
	],
	'OU' => [
		_x('Ait El Farsi', 'OU', 'ry-wc-city-select'),
		_x('Ait Ouassif', 'OU', 'ry-wc-city-select'),
		_x('Ait Sedrate Jbel  El', 'OU', 'ry-wc-city-select'),
		_x('Ait Sedrate Jbel  El', 'OU', 'ry-wc-city-select'),
		_x('Ait Sedrate Sahl Cha', 'OU', 'ry-wc-city-select'),
		_x('Ait Sedrate Sahl El', 'OU', 'ry-wc-city-select'),
		_x('Ait Youl', 'OU', 'ry-wc-city-select'),
		_x('Ait Zineb', 'OU', 'ry-wc-city-select'),
		_x('Amerzgane', 'OU', 'ry-wc-city-select'),
		_x('Aznaguen', 'OU', 'ry-wc-city-select'),
		_x('Boumalne Dades', 'OU', 'ry-wc-city-select'),
		_x('Ghassate', 'OU', 'ry-wc-city-select'),
		_x('Idelsane', 'OU', 'ry-wc-city-select'),
		_x('Ighil N Oumgoun', 'OU', 'ry-wc-city-select'),
		_x('Ighrem N Ougdal', 'OU', 'ry-wc-city-select'),
		_x('Ikniouen', 'OU', 'ry-wc-city-select'),
		_x('Imi N Oulaoune', 'OU', 'ry-wc-city-select'),
		_x('Imider', 'OU', 'ry-wc-city-select'),
		_x('Khouzama', 'OU', 'ry-wc-city-select'),
		_x('M Semrir', 'OU', 'ry-wc-city-select'),
		_x('Ouaklim', 'OU', 'ry-wc-city-select'),
		_x('Ouarzazate', 'OU', 'ry-wc-city-select'),
		_x('Ouisselsate', 'OU', 'ry-wc-city-select'),
		_x('Siroua', 'OU', 'ry-wc-city-select'),
		_x('Skoura', 'OU', 'ry-wc-city-select'),
		_x('Skoura Ahl El Oust', 'OU', 'ry-wc-city-select'),
		_x('Souk Lakhmis Dades', 'OU', 'ry-wc-city-select'),
		_x('Tabounte', 'OU', 'ry-wc-city-select'),
		_x('Taghzoute N Ait Atta', 'OU', 'ry-wc-city-select'),
		_x('Tarmigt', 'OU', 'ry-wc-city-select'),
		_x('Taznakht', 'OU', 'ry-wc-city-select'),
		_x('Telouet', 'OU', 'ry-wc-city-select'),
		_x('Tidli', 'OU', 'ry-wc-city-select'),
		_x('Tilmi', 'OU', 'ry-wc-city-select'),
		_x('Toudgha El Oulia', 'OU', 'ry-wc-city-select'),
		_x('Toudgha Essoufla', 'OU', 'ry-wc-city-select'),
		_x('Toundoute', 'OU', 'ry-wc-city-select'),
	],
	'OU2' => [
		_x('Bir Anzarane', 'OU2', 'ry-wc-city-select'),
		_x('Dakhla', 'OU2', 'ry-wc-city-select'),
		_x('El Argoub', 'OU2', 'ry-wc-city-select'),
		_x('Gleibat El Foula', 'OU2', 'ry-wc-city-select'),
		_x('Imlili', 'OU2', 'ry-wc-city-select'),
		_x('Mijik', 'OU2', 'ry-wc-city-select'),
		_x('Oum Dreyga', 'OU2', 'ry-wc-city-select'),
	],
	'OUPR' => [
		_x('Ouezzane', 'OUPR', 'ry-wc-city-select'),
	],
	'OU3' => [
		_x('Ahl Angad', 'OU3', 'ry-wc-city-select'),
		_x('Ain Sfa', 'OU3', 'ry-wc-city-select'),
		_x('Bni Drar', 'OU3', 'ry-wc-city-select'),
		_x('Bni Khaled', 'OU3', 'ry-wc-city-select'),
		_x('Bsara', 'OU3', 'ry-wc-city-select'),
		_x('Isly', 'OU3', 'ry-wc-city-select'),
		_x('Mestferki', 'OU3', 'ry-wc-city-select'),
		_x('Naima', 'OU3', 'ry-wc-city-select'),
		_x('Oujda', 'OU3', 'ry-wc-city-select'),
		_x('Sidi Boulenouar', 'OU3', 'ry-wc-city-select'),
		_x('Sidi Moussa Lemhaya', 'OU3', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Agdal Riyad', 'RA', 'ry-wc-city-select'),
		_x('El Youssoufia', 'RA', 'ry-wc-city-select'),
		_x('Hassan', 'RA', 'ry-wc-city-select'),
		_x('Souissi', 'RA', 'ry-wc-city-select'),
		_x('Touarga', 'RA', 'ry-wc-city-select'),
		_x('Yacoub El Mansour', 'RA', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Atiamim', 'SA', 'ry-wc-city-select'),
		_x('Atouabet', 'SA', 'ry-wc-city-select'),
		_x('Ayir', 'SA', 'ry-wc-city-select'),
		_x('Bouguedra', 'SA', 'ry-wc-city-select'),
		_x('Dar Si Aissa', 'SA', 'ry-wc-city-select'),
		_x('Echemmaia', 'SA', 'ry-wc-city-select'),
		_x('El Gantour', 'SA', 'ry-wc-city-select'),
		_x('Elbeddouza', 'SA', 'ry-wc-city-select'),
		_x('Elghiate', 'SA', 'ry-wc-city-select'),
		_x('Elgouraani', 'SA', 'ry-wc-city-select'),
		_x('Esbiaat', 'SA', 'ry-wc-city-select'),
		_x('Hrara', 'SA', 'ry-wc-city-select'),
		_x('Ighoud', 'SA', 'ry-wc-city-select'),
		_x('Jamaat Shaim', 'SA', 'ry-wc-city-select'),
		_x('Jdour', 'SA', 'ry-wc-city-select'),
		_x('Jnane Bouih', 'SA', 'ry-wc-city-select'),
		_x('Khatazakane', 'SA', 'ry-wc-city-select'),
		_x('Laakarta', 'SA', 'ry-wc-city-select'),
		_x('Laamamra', 'SA', 'ry-wc-city-select'),
		_x('Labkhati', 'SA', 'ry-wc-city-select'),
		_x('Lahdar', 'SA', 'ry-wc-city-select'),
		_x('Lakhoualqa', 'SA', 'ry-wc-city-select'),
		_x('Lamaachate', 'SA', 'ry-wc-city-select'),
		_x('Lamrasla', 'SA', 'ry-wc-city-select'),
		_x('Lamsabih', 'SA', 'ry-wc-city-select'),
		_x('Moul El Bergui', 'SA', 'ry-wc-city-select'),
		_x('Nagga', 'SA', 'ry-wc-city-select'),
		_x('Oulad Salmane', 'SA', 'ry-wc-city-select'),
		_x('Ras El Ain', 'SA', 'ry-wc-city-select'),
		_x('Saadla', 'SA', 'ry-wc-city-select'),
		_x('Safi', 'SA', 'ry-wc-city-select'),
		_x('Sebt Gzoula', 'SA', 'ry-wc-city-select'),
		_x('Sidi Ahmed', 'SA', 'ry-wc-city-select'),
		_x('Sidi Aissa', 'SA', 'ry-wc-city-select'),
		_x('Sidi Chiker', 'SA', 'ry-wc-city-select'),
		_x('Sidi Ettiji', 'SA', 'ry-wc-city-select'),
		_x('Youssoufia', 'SA', 'ry-wc-city-select'),
	],
	'SA2' => [
		_x('Bab Lamrissa', 'SA2', 'ry-wc-city-select'),
		_x('Bettana', 'SA2', 'ry-wc-city-select'),
		_x('Bouknadel', 'SA2', 'ry-wc-city-select'),
		_x('Hssaine', 'SA2', 'ry-wc-city-select'),
		_x('Layayda', 'SA2', 'ry-wc-city-select'),
		_x('Shoul', 'SA2', 'ry-wc-city-select'),
		_x('Sidi Bouknadel', 'SA2', 'ry-wc-city-select'),
		_x('Tabriquet', 'SA2', 'ry-wc-city-select'),
	],
	'SE' => [
		_x('Adrej', 'SE', 'ry-wc-city-select'),
		_x('Aghbalou Aqorar', 'SE', 'ry-wc-city-select'),
		_x('Ahl Sidi Lahcen', 'SE', 'ry-wc-city-select'),
		_x('Ain Cheggag', 'SE', 'ry-wc-city-select'),
		_x('Ain Timguenai', 'SE', 'ry-wc-city-select'),
		_x('Ait Sebaa Lajrouf', 'SE', 'ry-wc-city-select'),
		_x('Azzaba', 'SE', 'ry-wc-city-select'),
		_x('Bhalil', 'SE', 'ry-wc-city-select'),
		_x('Bir Tam Tam', 'SE', 'ry-wc-city-select'),
		_x('Dar El Hamra', 'SE', 'ry-wc-city-select'),
		_x('Elmenzel', 'SE', 'ry-wc-city-select'),
		_x('Ighzrane', 'SE', 'ry-wc-city-select'),
		_x('Imouzzer Kandar', 'SE', 'ry-wc-city-select'),
		_x('Kandar Sidi Khiar', 'SE', 'ry-wc-city-select'),
		_x('Laanoussar', 'SE', 'ry-wc-city-select'),
		_x('Mtarnagha', 'SE', 'ry-wc-city-select'),
		_x('Oulad Mkoudou', 'SE', 'ry-wc-city-select'),
		_x('Ras Tabouda', 'SE', 'ry-wc-city-select'),
		_x('Ribate El Kheir', 'SE', 'ry-wc-city-select'),
		_x('Sefrou', 'SE', 'ry-wc-city-select'),
		_x('Sidi Youssef  Ben Ah', 'SE', 'ry-wc-city-select'),
		_x('Tafajight', 'SE', 'ry-wc-city-select'),
		_x('Tazouta', 'SE', 'ry-wc-city-select'),
		_x('Zaouiat Bougrine', 'SE', 'ry-wc-city-select'),
	],
	'SEPR' => [
		_x('Ain Blal', 'SEPR', 'ry-wc-city-select'),
		_x('Ain Dorbane', 'SEPR', 'ry-wc-city-select'),
		_x('Ain Nzagh', 'SEPR', 'ry-wc-city-select'),
		_x('Ben Ahmed', 'SEPR', 'ry-wc-city-select'),
		_x('Ben Maachou', 'SEPR', 'ry-wc-city-select'),
		_x('Berrechid', 'SEPR', 'ry-wc-city-select'),
		_x('Bni Khloug', 'SEPR', 'ry-wc-city-select'),
		_x('Bni Yagrine', 'SEPR', 'ry-wc-city-select'),
		_x('Bouguargouh', 'SEPR', 'ry-wc-city-select'),
		_x('Dar Chaffai', 'SEPR', 'ry-wc-city-select'),
		_x('Deroua', 'SEPR', 'ry-wc-city-select'),
		_x('Elborouj', 'SEPR', 'ry-wc-city-select'),
		_x('Elgara', 'SEPR', 'ry-wc-city-select'),
		_x('Foqra Oulad Aameur', 'SEPR', 'ry-wc-city-select'),
		_x('Gdana', 'SEPR', 'ry-wc-city-select'),
		_x('Guisser', 'SEPR', 'ry-wc-city-select'),
		_x('Jaqma', 'SEPR', 'ry-wc-city-select'),
		_x('Kasbat Ben Mchich', 'SEPR', 'ry-wc-city-select'),
		_x('Khemisset Chaouia', 'SEPR', 'ry-wc-city-select'),
		_x('Laghnimyine', 'SEPR', 'ry-wc-city-select'),
		_x('Lahlaf M Zab', 'SEPR', 'ry-wc-city-select'),
		_x('Lahouaza', 'SEPR', 'ry-wc-city-select'),
		_x('Lahsasna', 'SEPR', 'ry-wc-city-select'),
		_x('Lakhiaita', 'SEPR', 'ry-wc-city-select'),
		_x('Lakhzazra', 'SEPR', 'ry-wc-city-select'),
		_x('Lambarkiyine', 'SEPR', 'ry-wc-city-select'),
		_x('Laqraqra', 'SEPR', 'ry-wc-city-select'),
		_x('Loulad', 'SEPR', 'ry-wc-city-select'),
		_x('M Garto', 'SEPR', 'ry-wc-city-select'),
		_x('Machraa Ben Abbou', 'SEPR', 'ry-wc-city-select'),
		_x('Meskoura', 'SEPR', 'ry-wc-city-select'),
		_x('Mniaa', 'SEPR', 'ry-wc-city-select'),
		_x('Mrizigue', 'SEPR', 'ry-wc-city-select'),
		_x('Mzoura', 'SEPR', 'ry-wc-city-select'),
		_x('N Khila', 'SEPR', 'ry-wc-city-select'),
		_x('Oued Naanaa', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Aafif', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Abbou', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Amer', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Bouali Nouaja', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Chbana', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Fares', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Fares El Halla', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Freiha', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad HRiz Sahel', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad M Hamed', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad MRah', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Said', 'SEPR', 'ry-wc-city-select'),
		_x('Oulad Sghir', 'SEPR', 'ry-wc-city-select'),
		_x('Ouled Cebbah', 'SEPR', 'ry-wc-city-select'),
		_x('Ouled Zidane', 'SEPR', 'ry-wc-city-select'),
		_x('Ras El Ain Chaouia', 'SEPR', 'ry-wc-city-select'),
		_x('Riah', 'SEPR', 'ry-wc-city-select'),
		_x('Rima', 'SEPR', 'ry-wc-city-select'),
		_x('Sahel Oulad H Riz', 'SEPR', 'ry-wc-city-select'),
		_x('Settat City', 'SEPR', 'ry-wc-city-select'),
		_x('Sgamna', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi Abdelkhaleq', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi Abdelkrim', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi Ahmed El Khadir', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi Boumehdi', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi Dahbi', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi El Aidi', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi El Mekki', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi Hajjaj', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi Mohammed  Ben R', 'SEPR', 'ry-wc-city-select'),
		_x('Sidi Rahal Chatai', 'SEPR', 'ry-wc-city-select'),
		_x('Soualem', 'SEPR', 'ry-wc-city-select'),
		_x('Tamadroust', 'SEPR', 'ry-wc-city-select'),
		_x('Toualet', 'SEPR', 'ry-wc-city-select'),
		_x('Zaouiat Sidi Ben Ham', 'SEPR', 'ry-wc-city-select'),
	],
	'SISL' => [
		_x('Sidi Yahya El Gharb', 'SISL', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Ain Dfali', 'SI', 'ry-wc-city-select'),
		_x('Ain Dorij', 'SI', 'ry-wc-city-select'),
		_x('Alhaouafate', 'SI', 'ry-wc-city-select'),
		_x('Bab Tiouka', 'SI', 'ry-wc-city-select'),
		_x('Bir Taleb', 'SI', 'ry-wc-city-select'),
		_x('Bni Oual', 'SI', 'ry-wc-city-select'),
		_x('Bni Quolla', 'SI', 'ry-wc-city-select'),
		_x('Chbanate', 'SI', 'ry-wc-city-select'),
		_x('Dar Gueddari', 'SI', 'ry-wc-city-select'),
		_x('Dar Laaslouji', 'SI', 'ry-wc-city-select'),
		_x('Ermilate', 'SI', 'ry-wc-city-select'),
		_x('Had Kourt', 'SI', 'ry-wc-city-select'),
		_x('Jorf El Melha', 'SI', 'ry-wc-city-select'),
		_x('Khnichet', 'SI', 'ry-wc-city-select'),
		_x('Lamjaara', 'SI', 'ry-wc-city-select'),
		_x('Lamrabih', 'SI', 'ry-wc-city-select'),
		_x('Masmouda', 'SI', 'ry-wc-city-select'),
		_x('Mechra Bel Ksiri', 'SI', 'ry-wc-city-select'),
		_x('Moulay Abdelkader', 'SI', 'ry-wc-city-select'),
		_x('Mzefroune', 'SI', 'ry-wc-city-select'),
		_x('Nouirate', 'SI', 'ry-wc-city-select'),
		_x('Oulad Nouel', 'SI', 'ry-wc-city-select'),
		_x('Ounnana', 'SI', 'ry-wc-city-select'),
		_x('Sefsaf', 'SI', 'ry-wc-city-select'),
		_x('Selfat', 'SI', 'ry-wc-city-select'),
		_x('Sidi Ahmed Benaissa', 'SI', 'ry-wc-city-select'),
		_x('Sidi Ahmed Cherif', 'SI', 'ry-wc-city-select'),
		_x('Sidi Al Kamel', 'SI', 'ry-wc-city-select'),
		_x('Sidi Ameur Al Hadi', 'SI', 'ry-wc-city-select'),
		_x('Sidi Azzouz', 'SI', 'ry-wc-city-select'),
		_x('Sidi Bousber', 'SI', 'ry-wc-city-select'),
		_x('Sidi M Hamed Chelh', 'SI', 'ry-wc-city-select'),
		_x('Sidi Redouane', 'SI', 'ry-wc-city-select'),
		_x('Sidi-Kacem', 'SI', 'ry-wc-city-select'),
		_x('Taoughilt', 'SI', 'ry-wc-city-select'),
		_x('Tekna', 'SI', 'ry-wc-city-select'),
		_x('Teroual', 'SI', 'ry-wc-city-select'),
		_x('Zaggota', 'SI', 'ry-wc-city-select'),
		_x('Zghira', 'SI', 'ry-wc-city-select'),
		_x('Zirara', 'SI', 'ry-wc-city-select'),
	],
	'SK' => [
		_x('Ain Attig', 'SK', 'ry-wc-city-select'),
		_x('Ain El Aouda', 'SK', 'ry-wc-city-select'),
		_x('Elmenzeh', 'SK', 'ry-wc-city-select'),
		_x('Harhoura', 'SK', 'ry-wc-city-select'),
		_x('Mers El Kheir', 'SK', 'ry-wc-city-select'),
		_x('Oumazza', 'SK', 'ry-wc-city-select'),
		_x('Sabbah', 'SK', 'ry-wc-city-select'),
		_x('Sidi Yahya Zaer', 'SK', 'ry-wc-city-select'),
		_x('Skhirate', 'SK', 'ry-wc-city-select'),
		_x('Temara', 'SK', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Abteh', 'TA', 'ry-wc-city-select'),
		_x('Ben Khlil', 'TA', 'ry-wc-city-select'),
		_x('Chbika', 'TA', 'ry-wc-city-select'),
		_x('Elouatia', 'TA', 'ry-wc-city-select'),
		_x('Msied', 'TA', 'ry-wc-city-select'),
		_x('Tan Tan', 'TA', 'ry-wc-city-select'),
		_x('Tilemzoun', 'TA', 'ry-wc-city-select'),
	],
	'TA2' => [
		_x('Almanzla', 'TA2', 'ry-wc-city-select'),
		_x('Aquouass Briech', 'TA2', 'ry-wc-city-select'),
		_x('Assilah', 'TA2', 'ry-wc-city-select'),
		_x('Azzinate', 'TA2', 'ry-wc-city-select'),
		_x('Bni Makada', 'TA2', 'ry-wc-city-select'),
		_x('Boukhalef', 'TA2', 'ry-wc-city-select'),
		_x('Charf-Mghogha', 'TA2', 'ry-wc-city-select'),
		_x('Charf-Souani', 'TA2', 'ry-wc-city-select'),
		_x('Dar Chaoui', 'TA2', 'ry-wc-city-select'),
		_x('Gueznaia', 'TA2', 'ry-wc-city-select'),
		_x('Lkhaloua', 'TA2', 'ry-wc-city-select'),
		_x('Sahel Chamali', 'TA2', 'ry-wc-city-select'),
		_x('Sidi Lyamani', 'TA2', 'ry-wc-city-select'),
		_x('Tanger-Medina', 'TA2', 'ry-wc-city-select'),
		_x('Tnin Sidi Lyamani', 'TA2', 'ry-wc-city-select'),
	],
	'TA3' => [
		_x('Ain Aicha', 'TA3', 'ry-wc-city-select'),
		_x('Ain Legdah', 'TA3', 'ry-wc-city-select'),
		_x('Ain Maatouf', 'TA3', 'ry-wc-city-select'),
		_x('Ain Mediouna', 'TA3', 'ry-wc-city-select'),
		_x('Bni Oulid', 'TA3', 'ry-wc-city-select'),
		_x('Bni Ounjel Tafraout', 'TA3', 'ry-wc-city-select'),
		_x('Bni Snous', 'TA3', 'ry-wc-city-select'),
		_x('Bouadel', 'TA3', 'ry-wc-city-select'),
		_x('Bouarouss', 'TA3', 'ry-wc-city-select'),
		_x('Bouchabel', 'TA3', 'ry-wc-city-select'),
		_x('Bouhouda', 'TA3', 'ry-wc-city-select'),
		_x('Elbibane', 'TA3', 'ry-wc-city-select'),
		_x('Elbsabsa', 'TA3', 'ry-wc-city-select'),
		_x('Fennassa Bab El Hit', 'TA3', 'ry-wc-city-select'),
		_x('Galaz', 'TA3', 'ry-wc-city-select'),
		_x('Ghafsai', 'TA3', 'ry-wc-city-select'),
		_x('Ghouazi', 'TA3', 'ry-wc-city-select'),
		_x('Jbabra', 'TA3', 'ry-wc-city-select'),
		_x('Karia Ba Mohamed', 'TA3', 'ry-wc-city-select'),
		_x('Khlalfa', 'TA3', 'ry-wc-city-select'),
		_x('Kissane', 'TA3', 'ry-wc-city-select'),
		_x('Loulja', 'TA3', 'ry-wc-city-select'),
		_x('Messassa', 'TA3', 'ry-wc-city-select'),
		_x('Mezraoua', 'TA3', 'ry-wc-city-select'),
		_x('Mkansa', 'TA3', 'ry-wc-city-select'),
		_x('Moulay Abdelkrim', 'TA3', 'ry-wc-city-select'),
		_x('Moulay Bouchta', 'TA3', 'ry-wc-city-select'),
		_x('Oudka', 'TA3', 'ry-wc-city-select'),
		_x('Oued Jemaa', 'TA3', 'ry-wc-city-select'),
		_x('Oulad Ayyad', 'TA3', 'ry-wc-city-select'),
		_x('Oulad Daoud', 'TA3', 'ry-wc-city-select'),
		_x('Ourtzagh', 'TA3', 'ry-wc-city-select'),
		_x('Outabouabane', 'TA3', 'ry-wc-city-select'),
		_x('Ras El Oued', 'TA3', 'ry-wc-city-select'),
		_x('Ratba', 'TA3', 'ry-wc-city-select'),
		_x('Rghioua', 'TA3', 'ry-wc-city-select'),
		_x('Sidi El Abed', 'TA3', 'ry-wc-city-select'),
		_x('Sidi Haj M Hamed', 'TA3', 'ry-wc-city-select'),
		_x('Sidi M Hamed  Ben La', 'TA3', 'ry-wc-city-select'),
		_x('Sidi Mokhfi', 'TA3', 'ry-wc-city-select'),
		_x('Sidi Yahya  Bni Zero', 'TA3', 'ry-wc-city-select'),
		_x('Tabouda', 'TA3', 'ry-wc-city-select'),
		_x('Tafrant', 'TA3', 'ry-wc-city-select'),
		_x('Tamedit', 'TA3', 'ry-wc-city-select'),
		_x('Taounate', 'TA3', 'ry-wc-city-select'),
		_x('Thar Es-Souk', 'TA3', 'ry-wc-city-select'),
		_x('Timezgana', 'TA3', 'ry-wc-city-select'),
		_x('Tissa', 'TA3', 'ry-wc-city-select'),
		_x('Zrizer', 'TA3', 'ry-wc-city-select'),
	],
	'TA4' => [
		_x('Ahl Oued Za', 'TA4', 'ry-wc-city-select'),
		_x('Ain Lehjer', 'TA4', 'ry-wc-city-select'),
		_x('Debdou', 'TA4', 'ry-wc-city-select'),
		_x('El Aioun Sidi Mellou', 'TA4', 'ry-wc-city-select'),
		_x('Elatef', 'TA4', 'ry-wc-city-select'),
		_x('Gteter', 'TA4', 'ry-wc-city-select'),
		_x('Mechraa Hammadi', 'TA4', 'ry-wc-city-select'),
		_x('Melg El Ouidane', 'TA4', 'ry-wc-city-select'),
		_x('Mestegmer', 'TA4', 'ry-wc-city-select'),
		_x('Oulad M Hammed', 'TA4', 'ry-wc-city-select'),
		_x('Sidi Ali Belkassem', 'TA4', 'ry-wc-city-select'),
		_x('Sidi Lahsen', 'TA4', 'ry-wc-city-select'),
		_x('Tancherfi', 'TA4', 'ry-wc-city-select'),
		_x('Taourirt', 'TA4', 'ry-wc-city-select'),
	],
	'TA5' => [
		_x('Adar', 'TA5', 'ry-wc-city-select'),
		_x('Agadir Melloul', 'TA5', 'ry-wc-city-select'),
		_x('Ahl Ramel', 'TA5', 'ry-wc-city-select'),
		_x('Ahl Tifnoute', 'TA5', 'ry-wc-city-select'),
		_x('Ahmar Laglalcha', 'TA5', 'ry-wc-city-select'),
		_x('Ait Abdallah', 'TA5', 'ry-wc-city-select'),
		_x('Ait Iaaza', 'TA5', 'ry-wc-city-select'),
		_x('Ait Igas', 'TA5', 'ry-wc-city-select'),
		_x('Ait Makhlouf', 'TA5', 'ry-wc-city-select'),
		_x('Amalou', 'TA5', 'ry-wc-city-select'),
		_x('Aoulouz', 'TA5', 'ry-wc-city-select'),
		_x('Arazane', 'TA5', 'ry-wc-city-select'),
		_x('Argana', 'TA5', 'ry-wc-city-select'),
		_x('Askaouen', 'TA5', 'ry-wc-city-select'),
		_x('Assads', 'TA5', 'ry-wc-city-select'),
		_x('Assaisse', 'TA5', 'ry-wc-city-select'),
		_x('Assaki', 'TA5', 'ry-wc-city-select'),
		_x('Azaghar N Irs', 'TA5', 'ry-wc-city-select'),
		_x('Azrar', 'TA5', 'ry-wc-city-select'),
		_x('Bigoudine', 'TA5', 'ry-wc-city-select'),
		_x('Bounrar', 'TA5', 'ry-wc-city-select'),
		_x('Eddir', 'TA5', 'ry-wc-city-select'),
		_x('Elfaid', 'TA5', 'ry-wc-city-select'),
		_x('Elguerdane', 'TA5', 'ry-wc-city-select'),
		_x('Elkoudia El Beida', 'TA5', 'ry-wc-city-select'),
		_x('Freija', 'TA5', 'ry-wc-city-select'),
		_x('Ida Ou Gailal', 'TA5', 'ry-wc-city-select'),
		_x('Ida Ou Moumen', 'TA5', 'ry-wc-city-select'),
		_x('Ida Ougoummad', 'TA5', 'ry-wc-city-select'),
		_x('Igli', 'TA5', 'ry-wc-city-select'),
		_x('Igoudar Mnabha', 'TA5', 'ry-wc-city-select'),
		_x('Iguidi', 'TA5', 'ry-wc-city-select'),
		_x('Imaouen', 'TA5', 'ry-wc-city-select'),
		_x('Imi N Tayart', 'TA5', 'ry-wc-city-select'),
		_x('Imilmaiss', 'TA5', 'ry-wc-city-select'),
		_x('Imoulass', 'TA5', 'ry-wc-city-select'),
		_x('Irherm', 'TA5', 'ry-wc-city-select'),
		_x('Issen', 'TA5', 'ry-wc-city-select'),
		_x('Lagfifat', 'TA5', 'ry-wc-city-select'),
		_x('Lakhnafif', 'TA5', 'ry-wc-city-select'),
		_x('Lamhadi', 'TA5', 'ry-wc-city-select'),
		_x('Lamhara', 'TA5', 'ry-wc-city-select'),
		_x('Lamnizla', 'TA5', 'ry-wc-city-select'),
		_x('Machraa El Ain', 'TA5', 'ry-wc-city-select'),
		_x('Nihit', 'TA5', 'ry-wc-city-select'),
		_x('Oualqadi', 'TA5', 'ry-wc-city-select'),
		_x('Oulad Aissa', 'TA5', 'ry-wc-city-select'),
		_x('Oulad Berhil', 'TA5', 'ry-wc-city-select'),
		_x('Oulad Teima', 'TA5', 'ry-wc-city-select'),
		_x('Ouneine', 'TA5', 'ry-wc-city-select'),
		_x('Ouzioua', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Abdellah Ou Sai', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Ahmed Ou Abdall', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Ahmed Ou Amar', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Boaal', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Borja', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Boumoussa', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Dahmane', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Hsaine', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Moussa Lhamri', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Mzal', 'TA5', 'ry-wc-city-select'),
		_x('Sidi Ouaaziz', 'TA5', 'ry-wc-city-select'),
		_x('Tabia', 'TA5', 'ry-wc-city-select'),
		_x('Tafingoult', 'TA5', 'ry-wc-city-select'),
		_x('Tafraouten', 'TA5', 'ry-wc-city-select'),
		_x('Talgjount', 'TA5', 'ry-wc-city-select'),
		_x('Taliouine', 'TA5', 'ry-wc-city-select'),
		_x('Talmakante', 'TA5', 'ry-wc-city-select'),
		_x('Tamaloukte', 'TA5', 'ry-wc-city-select'),
		_x('Taouyalte', 'TA5', 'ry-wc-city-select'),
		_x('Taroudant', 'TA5', 'ry-wc-city-select'),
		_x('Tassousfi', 'TA5', 'ry-wc-city-select'),
		_x('Tataoute', 'TA5', 'ry-wc-city-select'),
		_x('Tazemmourt', 'TA5', 'ry-wc-city-select'),
		_x('Tidsi Nissendalene', 'TA5', 'ry-wc-city-select'),
		_x('Tigouga', 'TA5', 'ry-wc-city-select'),
		_x('Tindine', 'TA5', 'ry-wc-city-select'),
		_x('Tinzart', 'TA5', 'ry-wc-city-select'),
		_x('Tiout', 'TA5', 'ry-wc-city-select'),
		_x('Tisfane', 'TA5', 'ry-wc-city-select'),
		_x('Tisrasse', 'TA5', 'ry-wc-city-select'),
		_x('Tizgzaouine', 'TA5', 'ry-wc-city-select'),
		_x('Toubkal', 'TA5', 'ry-wc-city-select'),
		_x('Toufelaazt', 'TA5', 'ry-wc-city-select'),
		_x('Toughmart', 'TA5', 'ry-wc-city-select'),
		_x('Toumliline', 'TA5', 'ry-wc-city-select'),
		_x('Zagmouzen', 'TA5', 'ry-wc-city-select'),
		_x('Zaouia Sidi Tahar', 'TA5', 'ry-wc-city-select'),
	],
	'TA6' => [
		_x('Adis', 'TA6', 'ry-wc-city-select'),
		_x('Aguinane', 'TA6', 'ry-wc-city-select'),
		_x('Ait Ouabelli', 'TA6', 'ry-wc-city-select'),
		_x('Akka', 'TA6', 'ry-wc-city-select'),
		_x('Akka Ighane', 'TA6', 'ry-wc-city-select'),
		_x('Allougoum', 'TA6', 'ry-wc-city-select'),
		_x('Fam El Hisn', 'TA6', 'ry-wc-city-select'),
		_x('Foum Zguid', 'TA6', 'ry-wc-city-select'),
		_x('Ibn Yacoub', 'TA6', 'ry-wc-city-select'),
		_x('Issafen', 'TA6', 'ry-wc-city-select'),
		_x('Kasbat S Abdellah M-', 'TA6', 'ry-wc-city-select'),
		_x('Oum El Guerdane', 'TA6', 'ry-wc-city-select'),
		_x('Tagmout', 'TA6', 'ry-wc-city-select'),
		_x('Tamanarte', 'TA6', 'ry-wc-city-select'),
		_x('Tata', 'TA6', 'ry-wc-city-select'),
		_x('Tigzmerte', 'TA6', 'ry-wc-city-select'),
		_x('Tissint', 'TA6', 'ry-wc-city-select'),
		_x('Tizaghte', 'TA6', 'ry-wc-city-select'),
		_x('Tizounine', 'TA6', 'ry-wc-city-select'),
		_x('Tlite', 'TA6', 'ry-wc-city-select'),
	],
	'TA7' => [
		_x('Ait Saghrouchen', 'TA7', 'ry-wc-city-select'),
		_x('Ajdir', 'TA7', 'ry-wc-city-select'),
		_x('Aknoul', 'TA7', 'ry-wc-city-select'),
		_x('Assebbab', 'TA7', 'ry-wc-city-select'),
		_x('Bab Boudir', 'TA7', 'ry-wc-city-select'),
		_x('Bab Marzouka', 'TA7', 'ry-wc-city-select'),
		_x('Barkine', 'TA7', 'ry-wc-city-select'),
		_x('Bni Frassen', 'TA7', 'ry-wc-city-select'),
		_x('Bni Ftah', 'TA7', 'ry-wc-city-select'),
		_x('Bni Lent', 'TA7', 'ry-wc-city-select'),
		_x('Bouchfaa', 'TA7', 'ry-wc-city-select'),
		_x('Bouhlou', 'TA7', 'ry-wc-city-select'),
		_x('Bourd', 'TA7', 'ry-wc-city-select'),
		_x('Bouyablane', 'TA7', 'ry-wc-city-select'),
		_x('Brarha', 'TA7', 'ry-wc-city-select'),
		_x('Elgouzate', 'TA7', 'ry-wc-city-select'),
		_x('Galdamane', 'TA7', 'ry-wc-city-select'),
		_x('Ghiata Al Gharbia', 'TA7', 'ry-wc-city-select'),
		_x('Guercif', 'TA7', 'ry-wc-city-select'),
		_x('Gzenaya Al Janoubia', 'TA7', 'ry-wc-city-select'),
		_x('Houara Oulad Raho', 'TA7', 'ry-wc-city-select'),
		_x('Jbarna', 'TA7', 'ry-wc-city-select'),
		_x('Kaf El Ghar', 'TA7', 'ry-wc-city-select'),
		_x('Lamrija', 'TA7', 'ry-wc-city-select'),
		_x('Maghraoua', 'TA7', 'ry-wc-city-select'),
		_x('Matmata', 'TA7', 'ry-wc-city-select'),
		_x('Mazguitam', 'TA7', 'ry-wc-city-select'),
		_x('Meknassa Acharqia', 'TA7', 'ry-wc-city-select'),
		_x('Meknassa Al Gharbia', 'TA7', 'ry-wc-city-select'),
		_x('Msila', 'TA7', 'ry-wc-city-select'),
		_x('Oued Amlil', 'TA7', 'ry-wc-city-select'),
		_x('Oulad Bourima', 'TA7', 'ry-wc-city-select'),
		_x('Oulad Chrif', 'TA7', 'ry-wc-city-select'),
		_x('Oulad Zbair', 'TA7', 'ry-wc-city-select'),
		_x('Ras Laksar', 'TA7', 'ry-wc-city-select'),
		_x('Rbaa El Fouki', 'TA7', 'ry-wc-city-select'),
		_x('Saka', 'TA7', 'ry-wc-city-select'),
		_x('Sidi Ali Bourakba', 'TA7', 'ry-wc-city-select'),
		_x('Smia', 'TA7', 'ry-wc-city-select'),
		_x('Taddart', 'TA7', 'ry-wc-city-select'),
		_x('Tahla', 'TA7', 'ry-wc-city-select'),
		_x('Taifa', 'TA7', 'ry-wc-city-select'),
		_x('Tainaste', 'TA7', 'ry-wc-city-select'),
		_x('Taza', 'TA7', 'ry-wc-city-select'),
		_x('Tazarine', 'TA7', 'ry-wc-city-select'),
		_x('Tizi Ouasli', 'TA7', 'ry-wc-city-select'),
		_x('Traiba', 'TA7', 'ry-wc-city-select'),
		_x('Zrarda', 'TA7', 'ry-wc-city-select'),
	],
	'TE' => [
		_x('Ain Lahsan', 'TE', 'ry-wc-city-select'),
		_x('Alhamra', 'TE', 'ry-wc-city-select'),
		_x('Alkhrroub', 'TE', 'ry-wc-city-select'),
		_x('Allyene', 'TE', 'ry-wc-city-select'),
		_x('Aloued', 'TE', 'ry-wc-city-select'),
		_x('Azla', 'TE', 'ry-wc-city-select'),
		_x('Bghaghza', 'TE', 'ry-wc-city-select'),
		_x('Bni Harchen', 'TE', 'ry-wc-city-select'),
		_x('Bni Idder', 'TE', 'ry-wc-city-select'),
		_x('Bni Leit', 'TE', 'ry-wc-city-select'),
		_x('Bni Said', 'TE', 'ry-wc-city-select'),
		_x('Dar Bni Karrich', 'TE', 'ry-wc-city-select'),
		_x('Fnidq', 'TE', 'ry-wc-city-select'),
		_x('Jbel Lahbib', 'TE', 'ry-wc-city-select'),
		_x('Karia', 'TE', 'ry-wc-city-select'),
		_x('Mallalienne', 'TE', 'ry-wc-city-select'),
		_x('Martil', 'TE', 'ry-wc-city-select'),
		_x('Oued Laou', 'TE', 'ry-wc-city-select'),
		_x('Oulad Ali Mansour', 'TE', 'ry-wc-city-select'),
		_x('Saddina', 'TE', 'ry-wc-city-select'),
		_x('Sahtryine', 'TE', 'ry-wc-city-select'),
		_x('Souk Kdim', 'TE', 'ry-wc-city-select'),
		_x('Tetouan', 'TE', 'ry-wc-city-select'),
		_x('Zaitoune', 'TE', 'ry-wc-city-select'),
		_x('Zaouiat Sidi Kacem', 'TE', 'ry-wc-city-select'),
		_x('Zinat', 'TE', 'ry-wc-city-select'),
	],
	'TIPR' => [
		_x('Kalaat MGouna', 'TIPR', 'ry-wc-city-select'),
		_x('Tinghir', 'TIPR', 'ry-wc-city-select'),
	],
	'TI' => [
		_x('Afella Ighir', 'TI', 'ry-wc-city-select'),
		_x('Ait Erkha', 'TI', 'ry-wc-city-select'),
		_x('Ait Issafen', 'TI', 'ry-wc-city-select'),
		_x('Ait Ouafqa', 'TI', 'ry-wc-city-select'),
		_x('Ammelne', 'TI', 'ry-wc-city-select'),
		_x('Anfeg', 'TI', 'ry-wc-city-select'),
		_x('Anzi', 'TI', 'ry-wc-city-select'),
		_x('Arbaa Ait Abdellah', 'TI', 'ry-wc-city-select'),
		_x('Arbaa Ait Ahmed', 'TI', 'ry-wc-city-select'),
		_x('Arbaa Rasmouka', 'TI', 'ry-wc-city-select'),
		_x('Arbaa Sahel', 'TI', 'ry-wc-city-select'),
		_x('Bounaamane', 'TI', 'ry-wc-city-select'),
		_x('Boutrouch', 'TI', 'ry-wc-city-select'),
		_x('Elmaader El Kabir', 'TI', 'ry-wc-city-select'),
		_x('Ibdar', 'TI', 'ry-wc-city-select'),
		_x('Ida Ou Gougmar', 'TI', 'ry-wc-city-select'),
		_x('Imi N Fast', 'TI', 'ry-wc-city-select'),
		_x('Irigh N Tahala', 'TI', 'ry-wc-city-select'),
		_x('Lakhsas', 'TI', 'ry-wc-city-select'),
		_x('Mesti', 'TI', 'ry-wc-city-select'),
		_x('Mirleft', 'TI', 'ry-wc-city-select'),
		_x('Ouijjane', 'TI', 'ry-wc-city-select'),
		_x('Reggada', 'TI', 'ry-wc-city-select'),
		_x('Sbouya', 'TI', 'ry-wc-city-select'),
		_x('Sebt Ennabour', 'TI', 'ry-wc-city-select'),
		_x('Sidi Abdallah  Ou Be', 'TI', 'ry-wc-city-select'),
		_x('Sidi Ahmed Ou Moussa', 'TI', 'ry-wc-city-select'),
		_x('Sidi Bouabdelli', 'TI', 'ry-wc-city-select'),
		_x('Sidi H Saine Ou Ali', 'TI', 'ry-wc-city-select'),
		_x('Sidi Ifni', 'TI', 'ry-wc-city-select'),
		_x('Sidi M Bark', 'TI', 'ry-wc-city-select'),
		_x('Tafraout', 'TI', 'ry-wc-city-select'),
		_x('Tafraout El Mouloud', 'TI', 'ry-wc-city-select'),
		_x('Tangarfa', 'TI', 'ry-wc-city-select'),
		_x('Tarsouat', 'TI', 'ry-wc-city-select'),
		_x('Tassrirt', 'TI', 'ry-wc-city-select'),
		_x('Tighirt', 'TI', 'ry-wc-city-select'),
		_x('Tighmi', 'TI', 'ry-wc-city-select'),
		_x('Tioughza', 'TI', 'ry-wc-city-select'),
		_x('Tiznit', 'TI', 'ry-wc-city-select'),
		_x('Tizoughrane', 'TI', 'ry-wc-city-select'),
		_x('Tnine Aday', 'TI', 'ry-wc-city-select'),
		_x('Tnine Aglou', 'TI', 'ry-wc-city-select'),
		_x('Tnine Amellou', 'TI', 'ry-wc-city-select'),
	],
	'ZA' => [
		_x('Afella N Dra', 'ZA', 'ry-wc-city-select'),
		_x('Afra', 'ZA', 'ry-wc-city-select'),
		_x('Agdz', 'ZA', 'ry-wc-city-select'),
		_x('Ait Boudaoud', 'ZA', 'ry-wc-city-select'),
		_x('Ait Ouallal', 'ZA', 'ry-wc-city-select'),
		_x('Bleida', 'ZA', 'ry-wc-city-select'),
		_x('Bni Zoli', 'ZA', 'ry-wc-city-select'),
		_x('Bouzeroual', 'ZA', 'ry-wc-city-select'),
		_x('Errouha', 'ZA', 'ry-wc-city-select'),
		_x('Fezouata', 'ZA', 'ry-wc-city-select'),
		_x('Ktaoua', 'ZA', 'ry-wc-city-select'),
		_x('M Hamid El Ghizlane', 'ZA', 'ry-wc-city-select'),
		_x('Mezguita', 'ZA', 'ry-wc-city-select'),
		_x('N Kob', 'ZA', 'ry-wc-city-select'),
		_x('Oulad Yahia Lagraire', 'ZA', 'ry-wc-city-select'),
		_x('Taftechna', 'ZA', 'ry-wc-city-select'),
		_x('Taghbalte', 'ZA', 'ry-wc-city-select'),
		_x('Tagounite', 'ZA', 'ry-wc-city-select'),
		_x('Tamegroute', 'ZA', 'ry-wc-city-select'),
		_x('Tamezmoute', 'ZA', 'ry-wc-city-select'),
		_x('Tansifte', 'ZA', 'ry-wc-city-select'),
		_x('Tazarine', 'ZA', 'ry-wc-city-select'),
		_x('Ternata', 'ZA', 'ry-wc-city-select'),
		_x('Tinzouline', 'ZA', 'ry-wc-city-select'),
		_x('Zagora', 'ZA', 'ry-wc-city-select'),
	],
	'CA2' => [
		_x('Berrechid Province', 'CA2', 'ry-wc-city-select'),
		_x('Sidi Bennour', 'CA2', 'ry-wc-city-select'),
	],
	'DR' => [
		_x('Midelt', 'DR', 'ry-wc-city-select'),
	],
	'GUNO' => [
		_x('Sidi Ifni', 'GUNO', 'ry-wc-city-select'),
	],
	'LAHA' => [
		_x('Tarfaya', 'LAHA', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('Rehamna', 'MA2', 'ry-wc-city-select'),
		_x('Youssoufia', 'MA2', 'ry-wc-city-select'),
	],
	'OR' => [
		_x('Driouch Province', 'OR', 'ry-wc-city-select'),
		_x('Guercif Province', 'OR', 'ry-wc-city-select'),
	],
	]
];