<?php
/**
 * Republic of Madagascar places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MG' => [
	'1EAR' => [
		_x('1er Arrondissement', '1EAR', 'ry-wc-city-select'),
	],
	'AR' => [
		_x('2e Arrondissement', 'AR', 'ry-wc-city-select'),
	],
	'AR2' => [
		_x('3e Arrondissement', 'AR2', 'ry-wc-city-select'),
	],
	'AR3' => [
		_x('4e Arrondissement', 'AR3', 'ry-wc-city-select'),
	],
	'AR4' => [
		_x('5e Arrondissement', 'AR4', 'ry-wc-city-select'),
	],
	'AR5' => [
		_x('6e Arrondissement', 'AR5', 'ry-wc-city-select'),
	],
	'AM' => [
		_x('Ambalavao', 'AM', 'ry-wc-city-select'),
		_x('Ambinanindovoka', 'AM', 'ry-wc-city-select'),
		_x('Ambinaniroa', 'AM', 'ry-wc-city-select'),
		_x('Ambohimahamasina', 'AM', 'ry-wc-city-select'),
		_x('Ambohimandroso', 'AM', 'ry-wc-city-select'),
		_x('Andrainjato', 'AM', 'ry-wc-city-select'),
		_x('Anjoma', 'AM', 'ry-wc-city-select'),
		_x('Ankaramena', 'AM', 'ry-wc-city-select'),
		_x('Besoa', 'AM', 'ry-wc-city-select'),
		_x('Fenoarivo', 'AM', 'ry-wc-city-select'),
		_x('Iarintsena', 'AM', 'ry-wc-city-select'),
		_x('Kirano', 'AM', 'ry-wc-city-select'),
		_x('Mahazony', 'AM', 'ry-wc-city-select'),
		_x('Manamisoa', 'AM', 'ry-wc-city-select'),
		_x('Miarinarivo', 'AM', 'ry-wc-city-select'),
		_x('Sendrisoa', 'AM', 'ry-wc-city-select'),
		_x('Vohitsaoka', 'AM', 'ry-wc-city-select'),
	],
	'AM2' => [
		_x('Ambalahonko', 'AM2', 'ry-wc-city-select'),
		_x('Ambaliha', 'AM2', 'ry-wc-city-select'),
		_x('Ambanja', 'AM2', 'ry-wc-city-select'),
		_x('Ambodimanga Ramena', 'AM2', 'ry-wc-city-select'),
		_x('Ambohimarina', 'AM2', 'ry-wc-city-select'),
		_x('Ambohimena', 'AM2', 'ry-wc-city-select'),
		_x('Ambohitrandriana', 'AM2', 'ry-wc-city-select'),
		_x('Ankatafa', 'AM2', 'ry-wc-city-select'),
		_x('Ankingameloka', 'AM2', 'ry-wc-city-select'),
		_x('Anorontsangana', 'AM2', 'ry-wc-city-select'),
		_x('Antafiambotry', 'AM2', 'ry-wc-city-select'),
		_x('Antranokarany', 'AM2', 'ry-wc-city-select'),
		_x('Antsakoamanondro', 'AM2', 'ry-wc-city-select'),
		_x('Antsatsaka', 'AM2', 'ry-wc-city-select'),
		_x('Antsirabe', 'AM2', 'ry-wc-city-select'),
		_x('Bemaneviky Haut Sambirano', 'AM2', 'ry-wc-city-select'),
		_x('Bemaneviky Ouest', 'AM2', 'ry-wc-city-select'),
		_x('Benavony', 'AM2', 'ry-wc-city-select'),
		_x('Djangoa', 'AM2', 'ry-wc-city-select'),
		_x('Maevatanana', 'AM2', 'ry-wc-city-select'),
		_x('Maherivaratra', 'AM2', 'ry-wc-city-select'),
		_x('Marotolana', 'AM2', 'ry-wc-city-select'),
		_x('Marovato', 'AM2', 'ry-wc-city-select'),
	],
	'AMBO' => [
		_x('Ambato Ambarimay', 'AMBO', 'ry-wc-city-select'),
		_x('Ambondromamy', 'AMBO', 'ry-wc-city-select'),
		_x('Andranofasika', 'AMBO', 'ry-wc-city-select'),
		_x('Andranomamy', 'AMBO', 'ry-wc-city-select'),
		_x('Anjiajia', 'AMBO', 'ry-wc-city-select'),
		_x('Ankijabe', 'AMBO', 'ry-wc-city-select'),
		_x('Ankirihitra', 'AMBO', 'ry-wc-city-select'),
		_x('Madirovalo', 'AMBO', 'ry-wc-city-select'),
		_x('Manerinerina', 'AMBO', 'ry-wc-city-select'),
		_x('Sitampiky', 'AMBO', 'ry-wc-city-select'),
		_x('Tsaramandroso', 'AMBO', 'ry-wc-city-select'),
	],
	'AMDI' => [
		_x('Ambatofinandrahana', 'AMDI', 'ry-wc-city-select'),
		_x('Ambatomifanongoa', 'AMDI', 'ry-wc-city-select'),
		_x('Ambondromisotra', 'AMDI', 'ry-wc-city-select'),
		_x('Amborompotsy', 'AMDI', 'ry-wc-city-select'),
		_x('Fenoarivo', 'AMDI', 'ry-wc-city-select'),
		_x('Itremo', 'AMDI', 'ry-wc-city-select'),
		_x('Mandrosonoro', 'AMDI', 'ry-wc-city-select'),
		_x('Mangataboahangy', 'AMDI', 'ry-wc-city-select'),
		_x('Soavina', 'AMDI', 'ry-wc-city-select'),
	],
	'AM3' => [
		_x('Ambatolampy', 'AM3', 'ry-wc-city-select'),
		_x('Ambatondrakalavao', 'AM3', 'ry-wc-city-select'),
		_x('Ambodifarihy Fenomanana', 'AM3', 'ry-wc-city-select'),
		_x('Ambohipihaonana', 'AM3', 'ry-wc-city-select'),
		_x('Andranovelona', 'AM3', 'ry-wc-city-select'),
		_x('Andravola Vohipeno', 'AM3', 'ry-wc-city-select'),
		_x('Andriambilany', 'AM3', 'ry-wc-city-select'),
		_x('Antakasina', 'AM3', 'ry-wc-city-select'),
		_x('Antanamalaza', 'AM3', 'ry-wc-city-select'),
		_x('Antanimasaka', 'AM3', 'ry-wc-city-select'),
		_x('Antsampandrano', 'AM3', 'ry-wc-city-select'),
		_x('Behenjy', 'AM3', 'ry-wc-city-select'),
		_x('Belambo Firaisana', 'AM3', 'ry-wc-city-select'),
		_x('Manjakatompo', 'AM3', 'ry-wc-city-select'),
		_x('Morarano', 'AM3', 'ry-wc-city-select'),
		_x('Sabotsy Namatoana', 'AM3', 'ry-wc-city-select'),
		_x('Tsiafajavona Ankaratra', 'AM3', 'ry-wc-city-select'),
		_x('Tsinjoarivo', 'AM3', 'ry-wc-city-select'),
	],
	'AM4' => [
		_x('Ambatomainty', 'AM4', 'ry-wc-city-select'),
		_x('Bemarivo', 'AM4', 'ry-wc-city-select'),
		_x('Marotsialeha', 'AM4', 'ry-wc-city-select'),
		_x('Sarodrano', 'AM4', 'ry-wc-city-select'),
	],
	'AMDI2' => [
		_x('Ambandrika', 'AMDI2', 'ry-wc-city-select'),
		_x('Ambatondrazaka', 'AMDI2', 'ry-wc-city-select'),
		_x('Ambatondrazaka Suburbaine', 'AMDI2', 'ry-wc-city-select'),
		_x('Ambatosoratra', 'AMDI2', 'ry-wc-city-select'),
		_x('Ambohitsilaozana', 'AMDI2', 'ry-wc-city-select'),
		_x('Amparihintsokatra', 'AMDI2', 'ry-wc-city-select'),
		_x('Ampitatsimo', 'AMDI2', 'ry-wc-city-select'),
		_x('Andilanatoby', 'AMDI2', 'ry-wc-city-select'),
		_x('Andromba', 'AMDI2', 'ry-wc-city-select'),
		_x('Antanandava', 'AMDI2', 'ry-wc-city-select'),
		_x('Antsangasanga', 'AMDI2', 'ry-wc-city-select'),
		_x('Bejofo', 'AMDI2', 'ry-wc-city-select'),
		_x('Didy', 'AMDI2', 'ry-wc-city-select'),
		_x('Feramanga Nord', 'AMDI2', 'ry-wc-city-select'),
		_x('Ilafy', 'AMDI2', 'ry-wc-city-select'),
		_x('Imerimandroso', 'AMDI2', 'ry-wc-city-select'),
		_x('Manakambahiny Andrefana', 'AMDI2', 'ry-wc-city-select'),
		_x('Manakambahiny Antsinanana', 'AMDI2', 'ry-wc-city-select'),
		_x('Soalazaina', 'AMDI2', 'ry-wc-city-select'),
		_x('Tanambao Besakay', 'AMDI2', 'ry-wc-city-select'),
	],
	'AM5' => [
		_x('Ambakirano', 'AM5', 'ry-wc-city-select'),
		_x('Ambarakaraka', 'AM5', 'ry-wc-city-select'),
		_x('Ambatobenanjavy', 'AM5', 'ry-wc-city-select'),
		_x('Ambilobe', 'AM5', 'ry-wc-city-select'),
		_x('Ambodibonara', 'AM5', 'ry-wc-city-select'),
		_x('Ampondralava', 'AM5', 'ry-wc-city-select'),
		_x('Anaborano Ifasy', 'AM5', 'ry-wc-city-select'),
		_x('Anjiabe Ambony', 'AM5', 'ry-wc-city-select'),
		_x('Antsaravibe', 'AM5', 'ry-wc-city-select'),
		_x('Antsohimbondrona', 'AM5', 'ry-wc-city-select'),
		_x('Beramanja', 'AM5', 'ry-wc-city-select'),
		_x('Betsiaka', 'AM5', 'ry-wc-city-select'),
		_x('Manambato', 'AM5', 'ry-wc-city-select'),
		_x('Mantaly', 'AM5', 'ry-wc-city-select'),
		_x('Tanambao Marivorahona', 'AM5', 'ry-wc-city-select'),
	],
	'AMDI3' => [
		_x('Amboasary-Atsimo', 'AMDI3', 'ry-wc-city-select'),
		_x('Behara', 'AMDI3', 'ry-wc-city-select'),
		_x('Ebelo', 'AMDI3', 'ry-wc-city-select'),
		_x('Elonty', 'AMDI3', 'ry-wc-city-select'),
		_x('Esira', 'AMDI3', 'ry-wc-city-select'),
		_x('Ifotaka', 'AMDI3', 'ry-wc-city-select'),
		_x('Mahaly', 'AMDI3', 'ry-wc-city-select'),
		_x('Manevy', 'AMDI3', 'ry-wc-city-select'),
		_x('Maromby', 'AMDI3', 'ry-wc-city-select'),
		_x('Marotsiraka', 'AMDI3', 'ry-wc-city-select'),
		_x('Ranobe', 'AMDI3', 'ry-wc-city-select'),
		_x('Sampona', 'AMDI3', 'ry-wc-city-select'),
		_x('Tanandava Sud', 'AMDI3', 'ry-wc-city-select'),
		_x('Tomboarivo', 'AMDI3', 'ry-wc-city-select'),
		_x('Tranomaro', 'AMDI3', 'ry-wc-city-select'),
		_x('Tsivory', 'AMDI3', 'ry-wc-city-select'),
	],
	'AMDI4' => [
		_x('Ambato', 'AMDI4', 'ry-wc-city-select'),
		_x('Ambatolampy', 'AMDI4', 'ry-wc-city-select'),
		_x('Ambohidratrimo', 'AMDI4', 'ry-wc-city-select'),
		_x('Ambohimanjaka', 'AMDI4', 'ry-wc-city-select'),
		_x('Ambohipihaonana', 'AMDI4', 'ry-wc-city-select'),
		_x('Ambohitrimanjaka', 'AMDI4', 'ry-wc-city-select'),
		_x('Ampangabe', 'AMDI4', 'ry-wc-city-select'),
		_x('Ampanotokana', 'AMDI4', 'ry-wc-city-select'),
		_x('Anjanadoria', 'AMDI4', 'ry-wc-city-select'),
		_x('Anosiala', 'AMDI4', 'ry-wc-city-select'),
		_x('Antanetibe', 'AMDI4', 'ry-wc-city-select'),
		_x('Antehiroka', 'AMDI4', 'ry-wc-city-select'),
		_x('Antsahafilo', 'AMDI4', 'ry-wc-city-select'),
		_x('Avaratsena', 'AMDI4', 'ry-wc-city-select'),
		_x('Fiadanana', 'AMDI4', 'ry-wc-city-select'),
		_x('Iarinarivo', 'AMDI4', 'ry-wc-city-select'),
		_x('Ivato Aeroport', 'AMDI4', 'ry-wc-city-select'),
		_x('Ivato Firaisana', 'AMDI4', 'ry-wc-city-select'),
		_x('Mahabo', 'AMDI4', 'ry-wc-city-select'),
		_x('Mahereza', 'AMDI4', 'ry-wc-city-select'),
		_x('Mahitsy', 'AMDI4', 'ry-wc-city-select'),
		_x('Mananjara', 'AMDI4', 'ry-wc-city-select'),
		_x('Manjakavaradrano', 'AMDI4', 'ry-wc-city-select'),
		_x('Merimandroso', 'AMDI4', 'ry-wc-city-select'),
		_x('Talatamaty', 'AMDI4', 'ry-wc-city-select'),
	],
	'AM6' => [
		_x('Ambalakindresy', 'AM6', 'ry-wc-city-select'),
		_x('Ambatosoa', 'AM6', 'ry-wc-city-select'),
		_x('Ambohimahasoa', 'AM6', 'ry-wc-city-select'),
		_x('Ambohinamboarina', 'AM6', 'ry-wc-city-select'),
		_x('Ampitana', 'AM6', 'ry-wc-city-select'),
		_x('Ankafina Tsarafidy', 'AM6', 'ry-wc-city-select'),
		_x('Ankerana', 'AM6', 'ry-wc-city-select'),
		_x('Befeta', 'AM6', 'ry-wc-city-select'),
		_x('Camp Robin', 'AM6', 'ry-wc-city-select'),
		_x('Fiadanana', 'AM6', 'ry-wc-city-select'),
		_x('Ikalalao', 'AM6', 'ry-wc-city-select'),
		_x('Isaka', 'AM6', 'ry-wc-city-select'),
		_x('Manandroy', 'AM6', 'ry-wc-city-select'),
		_x('Morafeno', 'AM6', 'ry-wc-city-select'),
		_x('Sahatona', 'AM6', 'ry-wc-city-select'),
		_x('Sahave', 'AM6', 'ry-wc-city-select'),
		_x('Vohiposa', 'AM6', 'ry-wc-city-select'),
		_x('Vohitrarivo', 'AM6', 'ry-wc-city-select'),
	],
	'AMDI5' => [
		_x('Alakamisy Ambohijato', 'AMDI5', 'ry-wc-city-select'),
		_x('Ambalamanakana', 'AMDI5', 'ry-wc-city-select'),
		_x('Ambatofitorahana', 'AMDI5', 'ry-wc-city-select'),
		_x('Ambinanindrano', 'AMDI5', 'ry-wc-city-select'),
		_x('Ambohimitombo I', 'AMDI5', 'ry-wc-city-select'),
		_x('Ambohimitombo II', 'AMDI5', 'ry-wc-city-select'),
		_x('Ambositra I', 'AMDI5', 'ry-wc-city-select'),
		_x('Ambositra II', 'AMDI5', 'ry-wc-city-select'),
		_x('Andina', 'AMDI5', 'ry-wc-city-select'),
		_x('Ankazoambo', 'AMDI5', 'ry-wc-city-select'),
		_x('Antoetra', 'AMDI5', 'ry-wc-city-select'),
		_x('Fahizay', 'AMDI5', 'ry-wc-city-select'),
		_x('Ihadilanana', 'AMDI5', 'ry-wc-city-select'),
		_x('Ilaka Centre', 'AMDI5', 'ry-wc-city-select'),
		_x('Imerina Imady', 'AMDI5', 'ry-wc-city-select'),
		_x('Ivato', 'AMDI5', 'ry-wc-city-select'),
		_x('Ivony Miaramiasa', 'AMDI5', 'ry-wc-city-select'),
		_x('Kianjandrakefina', 'AMDI5', 'ry-wc-city-select'),
		_x('Mahazina Ambohipierenana', 'AMDI5', 'ry-wc-city-select'),
		_x('Marosoa', 'AMDI5', 'ry-wc-city-select'),
		_x('Sahatsiho Ambohimanjaka', 'AMDI5', 'ry-wc-city-select'),
		_x('Tsarasaotra', 'AMDI5', 'ry-wc-city-select'),
		_x('Vohidahy', 'AMDI5', 'ry-wc-city-select'),
	],
	'AMDI6' => [
		_x('Ambanisarika', 'AMDI6', 'ry-wc-city-select'),
		_x('Ambazoa', 'AMDI6', 'ry-wc-city-select'),
		_x('Ambohimalaza', 'AMDI6', 'ry-wc-city-select'),
		_x('Ambonaivo', 'AMDI6', 'ry-wc-city-select'),
		_x('Ambondro', 'AMDI6', 'ry-wc-city-select'),
		_x('Ambovombe', 'AMDI6', 'ry-wc-city-select'),
		_x('Ampamata', 'AMDI6', 'ry-wc-city-select'),
		_x('Analamary', 'AMDI6', 'ry-wc-city-select'),
		_x('Andalatanosy', 'AMDI6', 'ry-wc-city-select'),
		_x('Anjeky Ankilikira', 'AMDI6', 'ry-wc-city-select'),
		_x('Antanimora Atsimo', 'AMDI6', 'ry-wc-city-select'),
		_x('Erada', 'AMDI6', 'ry-wc-city-select'),
		_x('Imanombo', 'AMDI6', 'ry-wc-city-select'),
		_x('Jafaro', 'AMDI6', 'ry-wc-city-select'),
		_x('Maroalomainty', 'AMDI6', 'ry-wc-city-select'),
		_x('Maroalopoty', 'AMDI6', 'ry-wc-city-select'),
		_x('Marovato Befeno', 'AMDI6', 'ry-wc-city-select'),
		_x('Sihanamaro', 'AMDI6', 'ry-wc-city-select'),
		_x('Tsimananada', 'AMDI6', 'ry-wc-city-select'),
	],
	'AMDI7' => [
		_x('Amborompotsy', 'AMDI7', 'ry-wc-city-select'),
		_x('Ampanihy Ouest', 'AMDI7', 'ry-wc-city-select'),
		_x('Androka', 'AMDI7', 'ry-wc-city-select'),
		_x('Ankiliabo', 'AMDI7', 'ry-wc-city-select'),
		_x('Ankilimivory', 'AMDI7', 'ry-wc-city-select'),
		_x('Ankilizato', 'AMDI7', 'ry-wc-city-select'),
		_x('Antaly', 'AMDI7', 'ry-wc-city-select'),
		_x('Beahitse', 'AMDI7', 'ry-wc-city-select'),
		_x('Belafike Haut', 'AMDI7', 'ry-wc-city-select'),
		_x('Beroy Atsimo', 'AMDI7', 'ry-wc-city-select'),
		_x('Ejeda', 'AMDI7', 'ry-wc-city-select'),
		_x('Fotadrevo', 'AMDI7', 'ry-wc-city-select'),
		_x('Gogogogo', 'AMDI7', 'ry-wc-city-select'),
		_x('Itampolo', 'AMDI7', 'ry-wc-city-select'),
		_x('Maniry', 'AMDI7', 'ry-wc-city-select'),
		_x('Vohitany', 'AMDI7', 'ry-wc-city-select'),
	],
	'AMDI8' => [
		_x('Ambatomainty', 'AMDI8', 'ry-wc-city-select'),
		_x('Amboavory', 'AMDI8', 'ry-wc-city-select'),
		_x('Ambodimanga', 'AMDI8', 'ry-wc-city-select'),
		_x('Ambohijanahary', 'AMDI8', 'ry-wc-city-select'),
		_x('Ambohimandroso', 'AMDI8', 'ry-wc-city-select'),
		_x('Ambohitrarivo', 'AMDI8', 'ry-wc-city-select'),
		_x('Amparafaravola', 'AMDI8', 'ry-wc-city-select'),
		_x('Ampasikely', 'AMDI8', 'ry-wc-city-select'),
		_x('Andilana Nord', 'AMDI8', 'ry-wc-city-select'),
		_x('Andrebakely Nord', 'AMDI8', 'ry-wc-city-select'),
		_x('Andrebakely Sud', 'AMDI8', 'ry-wc-city-select'),
		_x('Anororo', 'AMDI8', 'ry-wc-city-select'),
		_x('Beanana', 'AMDI8', 'ry-wc-city-select'),
		_x('Bedidy', 'AMDI8', 'ry-wc-city-select'),
		_x('Morarano Chrome', 'AMDI8', 'ry-wc-city-select'),
		_x('Ranomainty', 'AMDI8', 'ry-wc-city-select'),
		_x('Sahamamy', 'AMDI8', 'ry-wc-city-select'),
		_x('Tanambe', 'AMDI8', 'ry-wc-city-select'),
		_x('Vohimena', 'AMDI8', 'ry-wc-city-select'),
		_x('Vohitsara', 'AMDI8', 'ry-wc-city-select'),
	],
	'AN' => [
		_x('Ambaliha', 'AN', 'ry-wc-city-select'),
		_x('Ambarijeby Sud', 'AN', 'ry-wc-city-select'),
		_x('Ambolobozo', 'AN', 'ry-wc-city-select'),
		_x('Analalava', 'AN', 'ry-wc-city-select'),
		_x('Andribavontsona', 'AN', 'ry-wc-city-select'),
		_x('Angoaka Sud', 'AN', 'ry-wc-city-select'),
		_x('Ankaramy', 'AN', 'ry-wc-city-select'),
		_x('Antonibe', 'AN', 'ry-wc-city-select'),
		_x('Befotaka Nord', 'AN', 'ry-wc-city-select'),
		_x('Mahadrodroka', 'AN', 'ry-wc-city-select'),
		_x('Maromandia', 'AN', 'ry-wc-city-select'),
		_x('Marovantaza', 'AN', 'ry-wc-city-select'),
		_x('Marovatolena', 'AN', 'ry-wc-city-select'),
	],
	'ANDI' => [
		_x('Ambalamanasy II', 'ANDI', 'ry-wc-city-select'),
		_x('Ambodiangezoka', 'ANDI', 'ry-wc-city-select'),
		_x('Ambodimanga I', 'ANDI', 'ry-wc-city-select'),
		_x('Andapa', 'ANDI', 'ry-wc-city-select'),
		_x('Andrakata', 'ANDI', 'ry-wc-city-select'),
		_x('Andranomena', 'ANDI', 'ry-wc-city-select'),
		_x('Anjialavabe', 'ANDI', 'ry-wc-city-select'),
		_x('Ankiakabe Nord', 'ANDI', 'ry-wc-city-select'),
		_x('Anoviara', 'ANDI', 'ry-wc-city-select'),
		_x('Antsahamena', 'ANDI', 'ry-wc-city-select'),
		_x('Bealampona', 'ANDI', 'ry-wc-city-select'),
		_x('Belaoka Lokoho', 'ANDI', 'ry-wc-city-select'),
		_x('Belaoka Marovato', 'ANDI', 'ry-wc-city-select'),
		_x('Betsakotsako Andranotsara', 'ANDI', 'ry-wc-city-select'),
		_x('Doany', 'ANDI', 'ry-wc-city-select'),
		_x('Marovato', 'ANDI', 'ry-wc-city-select'),
		_x('Matsohely', 'ANDI', 'ry-wc-city-select'),
		_x('Tanandava', 'ANDI', 'ry-wc-city-select'),
	],
	'ANDI2' => [
		_x('Andilamena', 'ANDI2', 'ry-wc-city-select'),
		_x('Antanimenabaka', 'ANDI2', 'ry-wc-city-select'),
		_x('Bemaitso', 'ANDI2', 'ry-wc-city-select'),
		_x('Maitsokely', 'ANDI2', 'ry-wc-city-select'),
		_x('Maroadabo', 'ANDI2', 'ry-wc-city-select'),
		_x('Marovato', 'ANDI2', 'ry-wc-city-select'),
		_x('Miarinarivo', 'ANDI2', 'ry-wc-city-select'),
		_x('Tanananifololahy', 'ANDI2', 'ry-wc-city-select'),
	],
	'ANDI3' => [
		_x('Alarobia Vatosola', 'ANDI3', 'ry-wc-city-select'),
		_x('Alatsinainy Bakaro', 'ANDI3', 'ry-wc-city-select'),
		_x('Ambohimiadana', 'ANDI3', 'ry-wc-city-select'),
		_x('Andohariana', 'ANDI3', 'ry-wc-city-select'),
		_x('Andramasina', 'ANDI3', 'ry-wc-city-select'),
		_x('Anosibe Trimoloharano', 'ANDI3', 'ry-wc-city-select'),
		_x('Antotohazo', 'ANDI3', 'ry-wc-city-select'),
		_x('Fitsinjovana Bakaro', 'ANDI3', 'ry-wc-city-select'),
		_x('Mandrosoa', 'ANDI3', 'ry-wc-city-select'),
		_x('Sabotsy Ambohitromby', 'ANDI3', 'ry-wc-city-select'),
		_x('Sabotsy Manjakavahoaka', 'ANDI3', 'ry-wc-city-select'),
		_x('Tankafatra', 'ANDI3', 'ry-wc-city-select'),
	],
	'AN2' => [
		_x('Alakamisy', 'AN2', 'ry-wc-city-select'),
		_x('Ambatomanoina', 'AN2', 'ry-wc-city-select'),
		_x('Amboasary Nord', 'AN2', 'ry-wc-city-select'),
		_x('Ambohibary Vohilena', 'AN2', 'ry-wc-city-select'),
		_x('Ambohimanarina Marovazaha', 'AN2', 'ry-wc-city-select'),
		_x('Ambohimirary', 'AN2', 'ry-wc-city-select'),
		_x('Ambongamarina', 'AN2', 'ry-wc-city-select'),
		_x('Amparatanjona', 'AN2', 'ry-wc-city-select'),
		_x('Analaroa', 'AN2', 'ry-wc-city-select'),
		_x('Androvakely', 'AN2', 'ry-wc-city-select'),
		_x('Anjozorobe', 'AN2', 'ry-wc-city-select'),
		_x('Antanetibe', 'AN2', 'ry-wc-city-select'),
		_x('Belanitra', 'AN2', 'ry-wc-city-select'),
		_x('Beronono', 'AN2', 'ry-wc-city-select'),
		_x('Betatao', 'AN2', 'ry-wc-city-select'),
		_x('Mangamila', 'AN2', 'ry-wc-city-select'),
		_x('Marotsipoy', 'AN2', 'ry-wc-city-select'),
		_x('Tsarasaotra', 'AN2', 'ry-wc-city-select'),
	],
	'ANDI4' => [
		_x('Andranomafana', 'ANDI4', 'ry-wc-city-select'),
		_x('Ankazoabo Sud', 'ANDI4', 'ry-wc-city-select'),
		_x('Berenty', 'ANDI4', 'ry-wc-city-select'),
		_x('Fotivolo', 'ANDI4', 'ry-wc-city-select'),
		_x('Ilemby', 'ANDI4', 'ry-wc-city-select'),
		_x('Tandrano', 'ANDI4', 'ry-wc-city-select'),
	],
	'ANDI5' => [
		_x('Ambohitromby', 'ANDI5', 'ry-wc-city-select'),
		_x('Ambolotarakely', 'ANDI5', 'ry-wc-city-select'),
		_x('Ankazobe', 'ANDI5', 'ry-wc-city-select'),
		_x('Antakavana', 'ANDI5', 'ry-wc-city-select'),
		_x('Antotohazo', 'ANDI5', 'ry-wc-city-select'),
		_x('Fiadanana', 'ANDI5', 'ry-wc-city-select'),
		_x('Fihaonana', 'ANDI5', 'ry-wc-city-select'),
		_x('Kiangara', 'ANDI5', 'ry-wc-city-select'),
		_x('Mahavelona', 'ANDI5', 'ry-wc-city-select'),
		_x('Marondry', 'ANDI5', 'ry-wc-city-select'),
		_x('Miantso', 'ANDI5', 'ry-wc-city-select'),
		_x('Talata Angavo', 'ANDI5', 'ry-wc-city-select'),
		_x('Tsaramasoandro', 'ANDI5', 'ry-wc-city-select'),
	],
	'ANANDI' => [
		_x('Ambalaomby', 'ANANDI', 'ry-wc-city-select'),
		_x('Ambatoharanana', 'ANANDI', 'ry-wc-city-select'),
		_x('Ampandroantraka', 'ANANDI', 'ry-wc-city-select'),
		_x('Ampasimaneva', 'ANANDI', 'ry-wc-city-select'),
		_x('Anosibe Anala', 'ANANDI', 'ry-wc-city-select'),
		_x('Antandrokomby', 'ANANDI', 'ry-wc-city-select'),
		_x('Longozabe', 'ANANDI', 'ry-wc-city-select'),
		_x('Niarovana Marosampanana', 'ANANDI', 'ry-wc-city-select'),
		_x('Tratramarina', 'ANANDI', 'ry-wc-city-select'),
		_x('Tsaravinany', 'ANANDI', 'ry-wc-city-select'),
	],
	'AN3' => [
		_x('Ambalabe', 'AN3', 'ry-wc-city-select'),
		_x('Ambinanifaho', 'AN3', 'ry-wc-city-select'),
		_x('Ambohitralanana', 'AN3', 'ry-wc-city-select'),
		_x('Ampahana', 'AN3', 'ry-wc-city-select'),
		_x('Ampanavoana', 'AN3', 'ry-wc-city-select'),
		_x('Ampohibe', 'AN3', 'ry-wc-city-select'),
		_x('Andampy', 'AN3', 'ry-wc-city-select'),
		_x('Antalaha Ambonivohitra', 'AN3', 'ry-wc-city-select'),
		_x('Antananambo', 'AN3', 'ry-wc-city-select'),
		_x('Antombana', 'AN3', 'ry-wc-city-select'),
		_x('Antsahanoro', 'AN3', 'ry-wc-city-select'),
		_x('Antsambalahy', 'AN3', 'ry-wc-city-select'),
		_x('Lanjarivo', 'AN3', 'ry-wc-city-select'),
		_x('Marofinaritra', 'AN3', 'ry-wc-city-select'),
		_x('Sarahandrano', 'AN3', 'ry-wc-city-select'),
		_x('Vinanivao', 'AN3', 'ry-wc-city-select'),
	],
	'ANMA' => [
		_x('Antanambao Manampontsy', 'ANMA', 'ry-wc-city-select'),
		_x('Antanandehibe', 'ANMA', 'ry-wc-city-select'),
		_x('Mahela', 'ANMA', 'ry-wc-city-select'),
		_x('Manakana', 'ANMA', 'ry-wc-city-select'),
		_x('Saivaza', 'ANMA', 'ry-wc-city-select'),
	],
	'ANAV' => [
		_x('Alasora', 'ANAV', 'ry-wc-city-select'),
		_x('Ambohimalaza Miray', 'ANAV', 'ry-wc-city-select'),
		_x('Ambohimanambola', 'ANAV', 'ry-wc-city-select'),
		_x('Ambohimanga Rova', 'ANAV', 'ry-wc-city-select'),
		_x('Ambohimangakely', 'ANAV', 'ry-wc-city-select'),
		_x('Anjeva Gara', 'ANAV', 'ry-wc-city-select'),
		_x('Ankadikely Ilafy', 'ANAV', 'ry-wc-city-select'),
		_x('Ankadinandriana', 'ANAV', 'ry-wc-city-select'),
		_x('Fiaferana', 'ANAV', 'ry-wc-city-select'),
		_x('Manandriana', 'ANAV', 'ry-wc-city-select'),
		_x('Masindray', 'ANAV', 'ry-wc-city-select'),
		_x('Sabotsy Namehana', 'ANAV', 'ry-wc-city-select'),
		_x('Talata Volonondry', 'ANAV', 'ry-wc-city-select'),
		_x('Viliahazo', 'ANAV', 'ry-wc-city-select'),
	],
	'AN4' => [
		_x('Alakamisy Fenoarivo', 'AN4', 'ry-wc-city-select'),
		_x('Alatsinainy Ambazaha', 'AN4', 'ry-wc-city-select'),
		_x('Ambalavao', 'AN4', 'ry-wc-city-select'),
		_x('Ambatofahavalo', 'AN4', 'ry-wc-city-select'),
		_x('Ambavahaditokana', 'AN4', 'ry-wc-city-select'),
		_x('Ambohidrapeto', 'AN4', 'ry-wc-city-select'),
		_x('Ambohijanaka', 'AN4', 'ry-wc-city-select'),
		_x('Ampahitrosy', 'AN4', 'ry-wc-city-select'),
		_x('Ampanefy', 'AN4', 'ry-wc-city-select'),
		_x('Ampitatafika', 'AN4', 'ry-wc-city-select'),
		_x('Andoharanofotsy', 'AN4', 'ry-wc-city-select'),
		_x('Andranonahoatra', 'AN4', 'ry-wc-city-select'),
		_x('Androhibe', 'AN4', 'ry-wc-city-select'),
		_x('Ankadimanga', 'AN4', 'ry-wc-city-select'),
		_x('Ankaraobato', 'AN4', 'ry-wc-city-select'),
		_x('Anosizato Andrefana', 'AN4', 'ry-wc-city-select'),
		_x('Antanetikely', 'AN4', 'ry-wc-city-select'),
		_x('Bemasoandro', 'AN4', 'ry-wc-city-select'),
		_x('Bongatsara', 'AN4', 'ry-wc-city-select'),
		_x('Fenoarivo', 'AN4', 'ry-wc-city-select'),
		_x('Fiombonana', 'AN4', 'ry-wc-city-select'),
		_x('Itaosy', 'AN4', 'ry-wc-city-select'),
		_x('Soalandy', 'AN4', 'ry-wc-city-select'),
		_x('Soavina', 'AN4', 'ry-wc-city-select'),
		_x('Tanjombato', 'AN4', 'ry-wc-city-select'),
		_x('Tsiafahy', 'AN4', 'ry-wc-city-select'),
	],
	'AN5' => [
		_x('Ambatolahy', 'AN5', 'ry-wc-city-select'),
		_x('Ambatomiady', 'AN5', 'ry-wc-city-select'),
		_x('Ambatotsipihina', 'AN5', 'ry-wc-city-select'),
		_x('Ambodiriana', 'AN5', 'ry-wc-city-select'),
		_x('Ambohimandroso', 'AN5', 'ry-wc-city-select'),
		_x('Ambohitompoina', 'AN5', 'ry-wc-city-select'),
		_x('Ampitatafika', 'AN5', 'ry-wc-city-select'),
		_x('Andranofito', 'AN5', 'ry-wc-city-select'),
		_x('Antanifotsy', 'AN5', 'ry-wc-city-select'),
		_x('Antsahalava', 'AN5', 'ry-wc-city-select'),
		_x('Antsampandrano', 'AN5', 'ry-wc-city-select'),
		_x('Belanitra', 'AN5', 'ry-wc-city-select'),
	],
	'AN6' => [
		_x('Antsalova', 'AN6', 'ry-wc-city-select'),
		_x('Bekopaka', 'AN6', 'ry-wc-city-select'),
		_x('Masoarivo', 'AN6', 'ry-wc-city-select'),
		_x('Soahany', 'AN6', 'ry-wc-city-select'),
		_x('Trangahy', 'AN6', 'ry-wc-city-select'),
	],
	'ANDI6' => [
		_x('Ampatana Mandriankeniheny', 'ANDI6', 'ry-wc-city-select'),
		_x('Antsenakely Andraikiba', 'ANDI6', 'ry-wc-city-select'),
		_x('Antsirabe Afovoany Atsinanana', 'ANDI6', 'ry-wc-city-select'),
		_x('Mahazoarivo Avarabohitra', 'ANDI6', 'ry-wc-city-select'),
		_x('Manodidina Ny Gara Ambilombe', 'ANDI6', 'ry-wc-city-select'),
		_x('Soamalaza Mahatsinjo', 'ANDI6', 'ry-wc-city-select'),
	],
	'AN7' => [
		_x('Alakamisy', 'AN7', 'ry-wc-city-select'),
		_x('Alatsinainy Ibity', 'AN7', 'ry-wc-city-select'),
		_x('Ambano', 'AN7', 'ry-wc-city-select'),
		_x('Ambatomena', 'AN7', 'ry-wc-city-select'),
		_x('Ambohibary', 'AN7', 'ry-wc-city-select'),
		_x('Ambohidranandriana', 'AN7', 'ry-wc-city-select'),
		_x('Ambohimiarivo', 'AN7', 'ry-wc-city-select'),
		_x('Ambohitsimanova', 'AN7', 'ry-wc-city-select'),
		_x('Andranomanelatra', 'AN7', 'ry-wc-city-select'),
		_x('Antanambao', 'AN7', 'ry-wc-city-select'),
		_x('Antanimandry', 'AN7', 'ry-wc-city-select'),
		_x('Antsoatany', 'AN7', 'ry-wc-city-select'),
		_x('Belazao', 'AN7', 'ry-wc-city-select'),
		_x('Manandona', 'AN7', 'ry-wc-city-select'),
		_x('Mandrosohasina', 'AN7', 'ry-wc-city-select'),
		_x('Mangarano', 'AN7', 'ry-wc-city-select'),
		_x('Sahanivotry Manandona', 'AN7', 'ry-wc-city-select'),
		_x('Soanindrariny', 'AN7', 'ry-wc-city-select'),
		_x('Tsarahonenana Sahanivotry', 'AN7', 'ry-wc-city-select'),
		_x('Vinaninkarena', 'AN7', 'ry-wc-city-select'),
	],
	'AN8' => [
		_x('Diego Suarez', 'AN8', 'ry-wc-city-select'),
	],
	'AN9' => [
		_x('Ambondrona', 'AN9', 'ry-wc-city-select'),
		_x('Andrafiabe', 'AN9', 'ry-wc-city-select'),
		_x('Andranofanjava', 'AN9', 'ry-wc-city-select'),
		_x('Andranovondronina', 'AN9', 'ry-wc-city-select'),
		_x('Anivorano Nord', 'AN9', 'ry-wc-city-select'),
		_x('Ankarongana', 'AN9', 'ry-wc-city-select'),
		_x('Anketrakabe', 'AN9', 'ry-wc-city-select'),
		_x('Antanamitarana', 'AN9', 'ry-wc-city-select'),
		_x('Antsahampano', 'AN9', 'ry-wc-city-select'),
		_x('Antsalaka', 'AN9', 'ry-wc-city-select'),
		_x('Antsoha', 'AN9', 'ry-wc-city-select'),
		_x('Bobakilandy', 'AN9', 'ry-wc-city-select'),
		_x('Bobasakoa', 'AN9', 'ry-wc-city-select'),
		_x('Joffre Ville', 'AN9', 'ry-wc-city-select'),
		_x('Mahalina', 'AN9', 'ry-wc-city-select'),
		_x('Mahavanona', 'AN9', 'ry-wc-city-select'),
		_x('Mangaoka', 'AN9', 'ry-wc-city-select'),
		_x('Mosorolava', 'AN9', 'ry-wc-city-select'),
		_x('Ramena', 'AN9', 'ry-wc-city-select'),
		_x('Sadjoavato', 'AN9', 'ry-wc-city-select'),
		_x('Sakaramy', 'AN9', 'ry-wc-city-select'),
	],
	'AN10' => [
		_x('Ambodimadiro', 'AN10', 'ry-wc-city-select'),
		_x('Ambodimanary', 'AN10', 'ry-wc-city-select'),
		_x('Ambodimandresy', 'AN10', 'ry-wc-city-select'),
		_x('Ampandriankilandy', 'AN10', 'ry-wc-city-select'),
		_x('Anahidrano', 'AN10', 'ry-wc-city-select'),
		_x('Andreba', 'AN10', 'ry-wc-city-select'),
		_x('Anjalazala', 'AN10', 'ry-wc-city-select'),
		_x('Anjiamangirana', 'AN10', 'ry-wc-city-select'),
		_x('Ankerika', 'AN10', 'ry-wc-city-select'),
		_x('Antsahabe', 'AN10', 'ry-wc-city-select'),
		_x('Antsohihy', 'AN10', 'ry-wc-city-select'),
		_x('Maroala', 'AN10', 'ry-wc-city-select'),
	],
	'AR6' => [
		_x('Alakamisikely', 'AR6', 'ry-wc-city-select'),
		_x('Ambatomanga', 'AR6', 'ry-wc-city-select'),
		_x('Ambatomirahavavy', 'AR6', 'ry-wc-city-select'),
		_x('Amboanana', 'AR6', 'ry-wc-city-select'),
		_x('Ambohimandry', 'AR6', 'ry-wc-city-select'),
		_x('Ambohimasina', 'AR6', 'ry-wc-city-select'),
		_x('Ambohipandrano', 'AR6', 'ry-wc-city-select'),
		_x('Ambohitrambo', 'AR6', 'ry-wc-city-select'),
		_x('Ampahimanga', 'AR6', 'ry-wc-city-select'),
		_x('Antambolo', 'AR6', 'ry-wc-city-select'),
		_x('Antenimbe', 'AR6', 'ry-wc-city-select'),
		_x('Arivonimamo I', 'AR6', 'ry-wc-city-select'),
		_x('Arivonimamo II', 'AR6', 'ry-wc-city-select'),
		_x('Imerintsiatosika', 'AR6', 'ry-wc-city-select'),
		_x('Mahatsinjo Est', 'AR6', 'ry-wc-city-select'),
		_x('Manalalondo', 'AR6', 'ry-wc-city-select'),
		_x('Marofangady', 'AR6', 'ry-wc-city-select'),
		_x('Miandrandra', 'AR6', 'ry-wc-city-select'),
		_x('Miantsoarivo', 'AR6', 'ry-wc-city-select'),
		_x('Morafeno', 'AR6', 'ry-wc-city-select'),
		_x('Morarano', 'AR6', 'ry-wc-city-select'),
		_x('Rambolamasoandro Andranomiely', 'AR6', 'ry-wc-city-select'),
	],
	'BEDI' => [
		_x('Ambalaromba', 'BEDI', 'ry-wc-city-select'),
		_x('Ambararata Sofia', 'BEDI', 'ry-wc-city-select'),
		_x('Ambararatabe Nord', 'BEDI', 'ry-wc-city-select'),
		_x('Ambatoriha Est', 'BEDI', 'ry-wc-city-select'),
		_x('Ambatosia', 'BEDI', 'ry-wc-city-select'),
		_x('Ambodiadabo M', 'BEDI', 'ry-wc-city-select'),
		_x('Ambodiampana', 'BEDI', 'ry-wc-city-select'),
		_x('Ambodisikidy', 'BEDI', 'ry-wc-city-select'),
		_x('Ambovonomby', 'BEDI', 'ry-wc-city-select'),
		_x('Analila', 'BEDI', 'ry-wc-city-select'),
		_x('Anjozoromadosy', 'BEDI', 'ry-wc-city-select'),
		_x('Ankazotokana', 'BEDI', 'ry-wc-city-select'),
		_x('Antananivo Haut', 'BEDI', 'ry-wc-city-select'),
		_x('Antsamaka', 'BEDI', 'ry-wc-city-select'),
		_x('Bealanana', 'BEDI', 'ry-wc-city-select'),
		_x('Beandrarezona', 'BEDI', 'ry-wc-city-select'),
		_x('Mangindrano', 'BEDI', 'ry-wc-city-select'),
		_x('Marotolana', 'BEDI', 'ry-wc-city-select'),
	],
	'BENO' => [
		_x('Ambararata', 'BENO', 'ry-wc-city-select'),
		_x('Ambodimotso Sud', 'BENO', 'ry-wc-city-select'),
		_x('Ambolidibe Est', 'BENO', 'ry-wc-city-select'),
		_x('Ankarongana', 'BENO', 'ry-wc-city-select'),
		_x('Antsakabary', 'BENO', 'ry-wc-city-select'),
		_x('Antsakanalabe', 'BENO', 'ry-wc-city-select'),
		_x('Befandriana Nord', 'BENO', 'ry-wc-city-select'),
		_x('Maroamalona', 'BENO', 'ry-wc-city-select'),
		_x('Matsondakana', 'BENO', 'ry-wc-city-select'),
		_x('Morafeno', 'BENO', 'ry-wc-city-select'),
		_x('Tsarahonenana', 'BENO', 'ry-wc-city-select'),
		_x('Tsiamalao', 'BENO', 'ry-wc-city-select'),
	],
	'BE' => [
		_x('Antaninarenina', 'BE', 'ry-wc-city-select'),
		_x('Antondabe', 'BE', 'ry-wc-city-select'),
		_x('Befotaka Sud', 'BE', 'ry-wc-city-select'),
		_x('Beharena', 'BE', 'ry-wc-city-select'),
		_x('Bekofafa Sud', 'BE', 'ry-wc-city-select'),
		_x('Marovitsika Sud', 'BE', 'ry-wc-city-select'),
		_x('Ranotsara Sud', 'BE', 'ry-wc-city-select'),
	],
	'BEDI2' => [
		_x('Ambahita', 'BEDI2', 'ry-wc-city-select'),
		_x('Ambatosola', 'BEDI2', 'ry-wc-city-select'),
		_x('Anivorano Mitsinjo', 'BEDI2', 'ry-wc-city-select'),
		_x('Anja Nord', 'BEDI2', 'ry-wc-city-select'),
		_x('Ankaranabo Nord', 'BEDI2', 'ry-wc-city-select'),
		_x('Antsakoamaro', 'BEDI2', 'ry-wc-city-select'),
		_x('Bekitro Commune', 'BEDI2', 'ry-wc-city-select'),
		_x('Belindo Mahasoa', 'BEDI2', 'ry-wc-city-select'),
		_x('Beraketa', 'BEDI2', 'ry-wc-city-select'),
		_x('Besakoa', 'BEDI2', 'ry-wc-city-select'),
		_x('Beteza', 'BEDI2', 'ry-wc-city-select'),
		_x('Bevitiky', 'BEDI2', 'ry-wc-city-select'),
		_x('Manakompy', 'BEDI2', 'ry-wc-city-select'),
		_x('Maroviro', 'BEDI2', 'ry-wc-city-select'),
		_x('Morafeno Bekily', 'BEDI2', 'ry-wc-city-select'),
		_x('Tanandava', 'BEDI2', 'ry-wc-city-select'),
		_x('Tsikolaky', 'BEDI2', 'ry-wc-city-select'),
		_x('Tsirandrany', 'BEDI2', 'ry-wc-city-select'),
		_x('Vohimanga', 'BEDI2', 'ry-wc-city-select'),
	],
	'BESUTS' => [
		_x('Aboalimena', 'BESUTS', 'ry-wc-city-select'),
		_x('Ambiky', 'BESUTS', 'ry-wc-city-select'),
		_x('Andimaky Manambolo', 'BESUTS', 'ry-wc-city-select'),
		_x('Ankalalobe', 'BESUTS', 'ry-wc-city-select'),
		_x('Ankiroroky', 'BESUTS', 'ry-wc-city-select'),
		_x('Antsoha', 'BESUTS', 'ry-wc-city-select'),
		_x('Belinta', 'BESUTS', 'ry-wc-city-select'),
		_x('Belo Sur Tsiribihina', 'BESUTS', 'ry-wc-city-select'),
		_x('Bemarivo Ankirondro', 'BESUTS', 'ry-wc-city-select'),
		_x('Berevo', 'BESUTS', 'ry-wc-city-select'),
		_x('Beroboka Nord', 'BESUTS', 'ry-wc-city-select'),
		_x('Masoarivo', 'BESUTS', 'ry-wc-city-select'),
		_x('Tsaraotana', 'BESUTS', 'ry-wc-city-select'),
		_x('Tsimafana', 'BESUTS', 'ry-wc-city-select'),
	],
	'BEDI3' => [
		_x('Behabobo', 'BEDI3', 'ry-wc-city-select'),
		_x('Beloha', 'BEDI3', 'ry-wc-city-select'),
		_x('Kopoky', 'BEDI3', 'ry-wc-city-select'),
		_x('Marolinta', 'BEDI3', 'ry-wc-city-select'),
		_x('Tranoroa', 'BEDI3', 'ry-wc-city-select'),
		_x('Tranovaho', 'BEDI3', 'ry-wc-city-select'),
	],
	'BE2' => [
		_x('Ambalavato', 'BE2', 'ry-wc-city-select'),
		_x('Benenitra', 'BE2', 'ry-wc-city-select'),
		_x('Ehara', 'BE2', 'ry-wc-city-select'),
		_x('Ianapera', 'BE2', 'ry-wc-city-select'),
	],
	'BEDI4' => [
		_x('Behisatsy', 'BEDI4', 'ry-wc-city-select'),
		_x('Bemavo', 'BEDI4', 'ry-wc-city-select'),
		_x('Beroroha', 'BEDI4', 'ry-wc-city-select'),
		_x('Fanjakana', 'BEDI4', 'ry-wc-city-select'),
		_x('Mandronarivo', 'BEDI4', 'ry-wc-city-select'),
		_x('Marerano', 'BEDI4', 'ry-wc-city-select'),
		_x('Sakena', 'BEDI4', 'ry-wc-city-select'),
		_x('Tanamary', 'BEDI4', 'ry-wc-city-select'),
	],
	'BE3' => [
		_x('Ambolodia Sud', 'BE3', 'ry-wc-city-select'),
		_x('Ampako', 'BE3', 'ry-wc-city-select'),
		_x('Ankasakasa Tsibiray', 'BE3', 'ry-wc-city-select'),
		_x('Bekodoka', 'BE3', 'ry-wc-city-select'),
		_x('Besalampy', 'BE3', 'ry-wc-city-select'),
		_x('Mahabe', 'BE3', 'ry-wc-city-select'),
		_x('Marovoay Sud', 'BE3', 'ry-wc-city-select'),
		_x('Soanenga', 'BE3', 'ry-wc-city-select'),
	],
	'BEDI5' => [
		_x('Alakamisy Anativato', 'BEDI5', 'ry-wc-city-select'),
		_x('Alakamisy Marososona', 'BEDI5', 'ry-wc-city-select'),
		_x('Alarobia Bemaha', 'BEDI5', 'ry-wc-city-select'),
		_x('Ambatonikonilahy', 'BEDI5', 'ry-wc-city-select'),
		_x('Ambohimanambola', 'BEDI5', 'ry-wc-city-select'),
		_x('Ambohimasina', 'BEDI5', 'ry-wc-city-select'),
		_x('Andranomafana', 'BEDI5', 'ry-wc-city-select'),
		_x('Andrembesoa', 'BEDI5', 'ry-wc-city-select'),
		_x('Anosiarivo Manapa', 'BEDI5', 'ry-wc-city-select'),
		_x('Antohobe', 'BEDI5', 'ry-wc-city-select'),
		_x('Antsoso', 'BEDI5', 'ry-wc-city-select'),
		_x('Betafo', 'BEDI5', 'ry-wc-city-select'),
		_x('Inanantonana', 'BEDI5', 'ry-wc-city-select'),
		_x('Mahaiza', 'BEDI5', 'ry-wc-city-select'),
		_x('Mandritsara', 'BEDI5', 'ry-wc-city-select'),
		_x('Manohisoa', 'BEDI5', 'ry-wc-city-select'),
		_x('Soavina', 'BEDI5', 'ry-wc-city-select'),
		_x('Tritriva', 'BEDI5', 'ry-wc-city-select'),
	],
	'BEDI6' => [
		_x('Ambatry Mitsinjo', 'BEDI6', 'ry-wc-city-select'),
		_x('Andranomangatsiaka', 'BEDI6', 'ry-wc-city-select'),
		_x('Ankazomanga Ouest', 'BEDI6', 'ry-wc-city-select'),
		_x('Ankazombalala', 'BEDI6', 'ry-wc-city-select'),
		_x('Ankilivalo', 'BEDI6', 'ry-wc-city-select'),
		_x('Antohabato', 'BEDI6', 'ry-wc-city-select'),
		_x('Antsavoa', 'BEDI6', 'ry-wc-city-select'),
		_x('Beantake', 'BEDI6', 'ry-wc-city-select'),
		_x('Belamoty', 'BEDI6', 'ry-wc-city-select'),
		_x('Besely', 'BEDI6', 'ry-wc-city-select'),
		_x('Betioky Atsimo', 'BEDI6', 'ry-wc-city-select'),
		_x('Bezaha', 'BEDI6', 'ry-wc-city-select'),
		_x('Fenoandala', 'BEDI6', 'ry-wc-city-select'),
		_x('Lazarivo', 'BEDI6', 'ry-wc-city-select'),
		_x('Manalobe', 'BEDI6', 'ry-wc-city-select'),
		_x('Maroarivo Ankazomanga', 'BEDI6', 'ry-wc-city-select'),
		_x('Marosavoa', 'BEDI6', 'ry-wc-city-select'),
		_x('Masiaboay', 'BEDI6', 'ry-wc-city-select'),
		_x('Montifeno', 'BEDI6', 'ry-wc-city-select'),
		_x('Sakamasay', 'BEDI6', 'ry-wc-city-select'),
		_x('Salobe', 'BEDI6', 'ry-wc-city-select'),
		_x('Soamanonga', 'BEDI6', 'ry-wc-city-select'),
		_x('Soaserana', 'BEDI6', 'ry-wc-city-select'),
		_x('Tameantsoa', 'BEDI6', 'ry-wc-city-select'),
		_x('Tanambao Haut', 'BEDI6', 'ry-wc-city-select'),
		_x('Tongobory', 'BEDI6', 'ry-wc-city-select'),
		_x('Vatolatsaka', 'BEDI6', 'ry-wc-city-select'),
	],
	'BEDI7' => [
		_x('Ambalasoa', 'BEDI7', 'ry-wc-city-select'),
		_x('Ambatomivary', 'BEDI7', 'ry-wc-city-select'),
		_x('Analamary', 'BEDI7', 'ry-wc-city-select'),
		_x('Andriandampy', 'BEDI7', 'ry-wc-city-select'),
		_x('Beampombo I', 'BEDI7', 'ry-wc-city-select'),
		_x('Beampombo II', 'BEDI7', 'ry-wc-city-select'),
		_x('Bekorobo', 'BEDI7', 'ry-wc-city-select'),
		_x('Benato Toby', 'BEDI7', 'ry-wc-city-select'),
		_x('Betroka', 'BEDI7', 'ry-wc-city-select'),
		_x('Iaborotra', 'BEDI7', 'ry-wc-city-select'),
		_x('Ianabinda', 'BEDI7', 'ry-wc-city-select'),
		_x('Ianakafy', 'BEDI7', 'ry-wc-city-select'),
		_x('Isoanala', 'BEDI7', 'ry-wc-city-select'),
		_x('Ivahona', 'BEDI7', 'ry-wc-city-select'),
		_x('Jangany', 'BEDI7', 'ry-wc-city-select'),
		_x('Mahabo', 'BEDI7', 'ry-wc-city-select'),
		_x('Mahasoa Est', 'BEDI7', 'ry-wc-city-select'),
		_x('Nanarena Besakoa', 'BEDI7', 'ry-wc-city-select'),
		_x('Naninora', 'BEDI7', 'ry-wc-city-select'),
		_x('Sakamahily', 'BEDI7', 'ry-wc-city-select'),
	],
	'BR' => [
		_x('Ambalarondra', 'BR', 'ry-wc-city-select'),
		_x('Ambinaninony', 'BR', 'ry-wc-city-select'),
		_x('Ambohimanana', 'BR', 'ry-wc-city-select'),
		_x('Ampasimbe', 'BR', 'ry-wc-city-select'),
		_x('Andekaleka', 'BR', 'ry-wc-city-select'),
		_x('Andevoranto', 'BR', 'ry-wc-city-select'),
		_x('Anivorano Est', 'BR', 'ry-wc-city-select'),
		_x('Anjahamana', 'BR', 'ry-wc-city-select'),
		_x('Brickaville', 'BR', 'ry-wc-city-select'),
		_x('Fanasana', 'BR', 'ry-wc-city-select'),
		_x('Fetraomby', 'BR', 'ry-wc-city-select'),
		_x('Lohariandava', 'BR', 'ry-wc-city-select'),
		_x('Mahatsara', 'BR', 'ry-wc-city-select'),
		_x('Maroseranana', 'BR', 'ry-wc-city-select'),
		_x('Ranomafana Est', 'BR', 'ry-wc-city-select'),
		_x('Vohipeno Razanaka', 'BR', 'ry-wc-city-select'),
		_x('Vohitranivona', 'BR', 'ry-wc-city-select'),
	],
	'FADI' => [
		_x('Alakamisy Ambohimahazo', 'FADI', 'ry-wc-city-select'),
		_x('Ankarinoro', 'FADI', 'ry-wc-city-select'),
		_x('Betsimisotra', 'FADI', 'ry-wc-city-select'),
		_x('Fandriana', 'FADI', 'ry-wc-city-select'),
		_x('Fiadanana', 'FADI', 'ry-wc-city-select'),
		_x('Imito', 'FADI', 'ry-wc-city-select'),
		_x('Mahazoarivo', 'FADI', 'ry-wc-city-select'),
		_x('Miarinavaratra', 'FADI', 'ry-wc-city-select'),
		_x('Milamaina', 'FADI', 'ry-wc-city-select'),
		_x('Sahamadio Fisakana', 'FADI', 'ry-wc-city-select'),
		_x('Sandrandahy', 'FADI', 'ry-wc-city-select'),
		_x('Tatamalaza', 'FADI', 'ry-wc-city-select'),
		_x('Tsarazaza', 'FADI', 'ry-wc-city-select'),
	],
	'FADI2' => [
		_x('Ambalatany', 'FADI2', 'ry-wc-city-select'),
		_x('Ambalavato Antevato', 'FADI2', 'ry-wc-city-select'),
		_x('Ambalavato Nord', 'FADI2', 'ry-wc-city-select'),
		_x('Ambohigogo', 'FADI2', 'ry-wc-city-select'),
		_x('Ambohimandroso', 'FADI2', 'ry-wc-city-select'),
		_x('Amporoforo', 'FADI2', 'ry-wc-city-select'),
		_x('Ankarana Miraihina', 'FADI2', 'ry-wc-city-select'),
		_x('Anosivelo', 'FADI2', 'ry-wc-city-select'),
		_x('Anosy Tsararafa', 'FADI2', 'ry-wc-city-select'),
		_x('Antseranambe', 'FADI2', 'ry-wc-city-select'),
		_x('Beretra Bevoay', 'FADI2', 'ry-wc-city-select'),
		_x('Efatsy', 'FADI2', 'ry-wc-city-select'),
		_x('Etrotroka Atsimo', 'FADI2', 'ry-wc-city-select'),
		_x('Evato', 'FADI2', 'ry-wc-city-select'),
		_x('Farafangana', 'FADI2', 'ry-wc-city-select'),
		_x('Fenoarivo', 'FADI2', 'ry-wc-city-select'),
		_x('Iabohazo', 'FADI2', 'ry-wc-city-select'),
		_x('Ihorombe', 'FADI2', 'ry-wc-city-select'),
		_x('Ivandrika', 'FADI2', 'ry-wc-city-select'),
		_x('Mahabo Mananivo', 'FADI2', 'ry-wc-city-select'),
		_x('Mahafasa Centre', 'FADI2', 'ry-wc-city-select'),
		_x('Mahavelo', 'FADI2', 'ry-wc-city-select'),
		_x('Maheriraty', 'FADI2', 'ry-wc-city-select'),
		_x('Manambotra Atsimo', 'FADI2', 'ry-wc-city-select'),
		_x('Marovandrika', 'FADI2', 'ry-wc-city-select'),
		_x('Namohora Iaborano', 'FADI2', 'ry-wc-city-select'),
		_x('Sahamadio', 'FADI2', 'ry-wc-city-select'),
		_x('Tangainony', 'FADI2', 'ry-wc-city-select'),
		_x('Tovona', 'FADI2', 'ry-wc-city-select'),
		_x('Vohilengo', 'FADI2', 'ry-wc-city-select'),
		_x('Vohimasy', 'FADI2', 'ry-wc-city-select'),
		_x('Vohitromby', 'FADI2', 'ry-wc-city-select'),
	],
	'FA' => [
		_x('Ambohiborona', 'FA', 'ry-wc-city-select'),
		_x('Andranomiady', 'FA', 'ry-wc-city-select'),
		_x('Antsampanimahazo', 'FA', 'ry-wc-city-select'),
		_x('Faratsiho', 'FA', 'ry-wc-city-select'),
		_x('Faravohitra', 'FA', 'ry-wc-city-select'),
		_x('Miandrarivo', 'FA', 'ry-wc-city-select'),
		_x('Ramainandro', 'FA', 'ry-wc-city-select'),
		_x('Valabetokana', 'FA', 'ry-wc-city-select'),
		_x('Vinaninony Atsimo', 'FA', 'ry-wc-city-select'),
	],
	'FEES' => [
		_x('Ambatoharanana', 'FEES', 'ry-wc-city-select'),
		_x('Ambodimanga II', 'FEES', 'ry-wc-city-select'),
		_x('Ampasimbe Manantsatrana', 'FEES', 'ry-wc-city-select'),
		_x('Ampasina Maningory', 'FEES', 'ry-wc-city-select'),
		_x('Antsiatsiaka', 'FEES', 'ry-wc-city-select'),
		_x('Fenerive Est', 'FEES', 'ry-wc-city-select'),
		_x('Mahambo', 'FEES', 'ry-wc-city-select'),
		_x('Mahanoro', 'FEES', 'ry-wc-city-select'),
		_x('Miorimivalana', 'FEES', 'ry-wc-city-select'),
		_x('Saranambana', 'FEES', 'ry-wc-city-select'),
		_x('Vohilengo', 'FEES', 'ry-wc-city-select'),
		_x('Vohipeno', 'FEES', 'ry-wc-city-select'),
	],
	'FE' => [
		_x('Ambatomainty Atsimo', 'FE', 'ry-wc-city-select'),
		_x('Ambohitromby', 'FE', 'ry-wc-city-select'),
		_x('Fenoarivo Centre', 'FE', 'ry-wc-city-select'),
		_x('Firavahana', 'FE', 'ry-wc-city-select'),
		_x('Kiranomena', 'FE', 'ry-wc-city-select'),
		_x('Mahajeby', 'FE', 'ry-wc-city-select'),
		_x('Morarano Maritampona', 'FE', 'ry-wc-city-select'),
		_x('Tsinjoarivo 22', 'FE', 'ry-wc-city-select'),
	],
	'FI' => [
		_x('Andrainjato Avaratra', 'FI', 'ry-wc-city-select'),
		_x('Andrainjato Sud', 'FI', 'ry-wc-city-select'),
		_x('Lalazana', 'FI', 'ry-wc-city-select'),
		_x('Manolafaka', 'FI', 'ry-wc-city-select'),
		_x('Tanana Ambany', 'FI', 'ry-wc-city-select'),
		_x('Tanana Ambony', 'FI', 'ry-wc-city-select'),
		_x('Vatosola', 'FI', 'ry-wc-city-select'),
	],
	'IA' => [
		_x('Begogo', 'IA', 'ry-wc-city-select'),
		_x('Iakora', 'IA', 'ry-wc-city-select'),
		_x('Ranotsara Nord', 'IA', 'ry-wc-city-select'),
	],
	'IF' => [
		_x('Ambohimanga Du Sud', 'IF', 'ry-wc-city-select'),
		_x('Ambohimiera', 'IF', 'ry-wc-city-select'),
		_x('Analampasina', 'IF', 'ry-wc-city-select'),
		_x('Androrangavola', 'IF', 'ry-wc-city-select'),
		_x('Antaretra', 'IF', 'ry-wc-city-select'),
		_x('Antsindra', 'IF', 'ry-wc-city-select'),
		_x('Fasintsara', 'IF', 'ry-wc-city-select'),
		_x('Ifanadiana', 'IF', 'ry-wc-city-select'),
		_x('Kelilalina', 'IF', 'ry-wc-city-select'),
		_x('Maroharatra', 'IF', 'ry-wc-city-select'),
		_x('Marotoko', 'IF', 'ry-wc-city-select'),
		_x('Ranomafana', 'IF', 'ry-wc-city-select'),
		_x('Tsaratanana', 'IF', 'ry-wc-city-select'),
	],
	'IH' => [
		_x('Ambatolahy', 'IH', 'ry-wc-city-select'),
		_x('Ambia', 'IH', 'ry-wc-city-select'),
		_x('Analaliry', 'IH', 'ry-wc-city-select'),
		_x('Analavoka', 'IH', 'ry-wc-city-select'),
		_x('Andiolava', 'IH', 'ry-wc-city-select'),
		_x('Ankily', 'IH', 'ry-wc-city-select'),
		_x('Antsoha', 'IH', 'ry-wc-city-select'),
		_x('Ihosy', 'IH', 'ry-wc-city-select'),
		_x('Ilakaka', 'IH', 'ry-wc-city-select'),
		_x('Irina', 'IH', 'ry-wc-city-select'),
		_x('Mahasoa', 'IH', 'ry-wc-city-select'),
		_x('Menamaty Iloto', 'IH', 'ry-wc-city-select'),
		_x('Ranohira', 'IH', 'ry-wc-city-select'),
		_x('Sahambano', 'IH', 'ry-wc-city-select'),
		_x('Sakalalina', 'IH', 'ry-wc-city-select'),
		_x('Satrokala', 'IH', 'ry-wc-city-select'),
		_x('Soamatasy', 'IH', 'ry-wc-city-select'),
		_x('Tolohomiady', 'IH', 'ry-wc-city-select'),
		_x('Zazafotsy', 'IH', 'ry-wc-city-select'),
	],
	'IK' => [
		_x('Ambatomainty', 'IK', 'ry-wc-city-select'),
		_x('Fitampito', 'IK', 'ry-wc-city-select'),
		_x('Ikalamavony', 'IK', 'ry-wc-city-select'),
		_x('Mangidy', 'IK', 'ry-wc-city-select'),
		_x('Solila', 'IK', 'ry-wc-city-select'),
		_x('Tanamarina Bekisopa', 'IK', 'ry-wc-city-select'),
		_x('Tanamarina Sakay', 'IK', 'ry-wc-city-select'),
		_x('Tsitondroina', 'IK', 'ry-wc-city-select'),
	],
	'IK2' => [
		_x('Ambatofotsy', 'IK2', 'ry-wc-city-select'),
		_x('Ambinanitromby', 'IK2', 'ry-wc-city-select'),
		_x('Ambohimisafy', 'IK2', 'ry-wc-city-select'),
		_x('Ambolomadinika', 'IK2', 'ry-wc-city-select'),
		_x('Ankarimbelo', 'IK2', 'ry-wc-city-select'),
		_x('Antodinga', 'IK2', 'ry-wc-city-select'),
		_x('Belemoka', 'IK2', 'ry-wc-city-select'),
		_x('Ifanirea', 'IK2', 'ry-wc-city-select'),
		_x('Ikongo', 'IK2', 'ry-wc-city-select'),
		_x('Kalafotsy', 'IK2', 'ry-wc-city-select'),
		_x('Manampatrana', 'IK2', 'ry-wc-city-select'),
		_x('Maromiandra', 'IK2', 'ry-wc-city-select'),
		_x('Sahalanona', 'IK2', 'ry-wc-city-select'),
		_x('Tanakambana', 'IK2', 'ry-wc-city-select'),
		_x('Tolongoina', 'IK2', 'ry-wc-city-select'),
	],
	'IS' => [
		_x('Ambalamidera II', 'IS', 'ry-wc-city-select'),
		_x('Ambondrona', 'IS', 'ry-wc-city-select'),
		_x('Andoharanomaitso', 'IS', 'ry-wc-city-select'),
		_x('Anjoma Itsara', 'IS', 'ry-wc-city-select'),
		_x('Ankarinarivo Manirisoa', 'IS', 'ry-wc-city-select'),
		_x('Fanjakana', 'IS', 'ry-wc-city-select'),
		_x('Iavonomby Vohibola', 'IS', 'ry-wc-city-select'),
		_x('Isorana', 'IS', 'ry-wc-city-select'),
		_x('Mahazoarivo', 'IS', 'ry-wc-city-select'),
		_x('Nasandratrony', 'IS', 'ry-wc-city-select'),
		_x('Soatanana', 'IS', 'ry-wc-city-select'),
	],
	'IV' => [
		_x('Antambohobe', 'IV', 'ry-wc-city-select'),
		_x('Ivohibe', 'IV', 'ry-wc-city-select'),
		_x('Ivongo', 'IV', 'ry-wc-city-select'),
		_x('Maropaika', 'IV', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Ambaliha', 'KA', 'ry-wc-city-select'),
		_x('Andasibe', 'KA', 'ry-wc-city-select'),
		_x('Antanimbaribe', 'KA', 'ry-wc-city-select'),
		_x('Behazomaty', 'KA', 'ry-wc-city-select'),
		_x('Betaimboay', 'KA', 'ry-wc-city-select'),
		_x('Kandreho', 'KA', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Alakamisy Ambohimaha', 'LA', 'ry-wc-city-select'),
		_x('Alatsinainy Ialamarina', 'LA', 'ry-wc-city-select'),
		_x('Ambalakely', 'LA', 'ry-wc-city-select'),
		_x('Ambalamahasoa', 'LA', 'ry-wc-city-select'),
		_x('Andrainjato Centre', 'LA', 'ry-wc-city-select'),
		_x('Andrainjato Est', 'LA', 'ry-wc-city-select'),
		_x('Androy', 'LA', 'ry-wc-city-select'),
		_x('Fandrandava', 'LA', 'ry-wc-city-select'),
		_x('Ialananindro', 'LA', 'ry-wc-city-select'),
		_x('Ivoamba', 'LA', 'ry-wc-city-select'),
		_x('Mahatsinjony', 'LA', 'ry-wc-city-select'),
		_x('Sahambavy', 'LA', 'ry-wc-city-select'),
		_x('Taindambo', 'LA', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Ambalajia', 'MA', 'ry-wc-city-select'),
		_x('Ambalanjanakomby', 'MA', 'ry-wc-city-select'),
		_x('Andriba', 'MA', 'ry-wc-city-select'),
		_x('Antanimbary', 'MA', 'ry-wc-city-select'),
		_x('Antsiafabositra', 'MA', 'ry-wc-city-select'),
		_x('Bemokotra', 'MA', 'ry-wc-city-select'),
		_x('Beratsimanina', 'MA', 'ry-wc-city-select'),
		_x('Madiromirafy', 'MA', 'ry-wc-city-select'),
		_x('Maevatanana I', 'MA', 'ry-wc-city-select'),
		_x('Maevatanana II', 'MA', 'ry-wc-city-select'),
		_x('Mahatsinjo', 'MA', 'ry-wc-city-select'),
		_x('Mahazoma', 'MA', 'ry-wc-city-select'),
		_x('Mangabe', 'MA', 'ry-wc-city-select'),
		_x('Maria', 'MA', 'ry-wc-city-select'),
		_x('Marokoro', 'MA', 'ry-wc-city-select'),
		_x('Morafeno', 'MA', 'ry-wc-city-select'),
		_x('Tsararano', 'MA', 'ry-wc-city-select'),
	],
	'MADI' => [
		_x('Ambia', 'MADI', 'ry-wc-city-select'),
		_x('Ampanihy', 'MADI', 'ry-wc-city-select'),
		_x('Analamitsivalana', 'MADI', 'ry-wc-city-select'),
		_x('Ankilivalo', 'MADI', 'ry-wc-city-select'),
		_x('Ankilizato', 'MADI', 'ry-wc-city-select'),
		_x('Befotaka', 'MADI', 'ry-wc-city-select'),
		_x('Beronono', 'MADI', 'ry-wc-city-select'),
		_x('Mahabo', 'MADI', 'ry-wc-city-select'),
		_x('Malaimbandy', 'MADI', 'ry-wc-city-select'),
		_x('Mandabe', 'MADI', 'ry-wc-city-select'),
		_x('Mazavasoa', 'MADI', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('Mahabibo', 'MA2', 'ry-wc-city-select'),
		_x('Mahajanga', 'MA2', 'ry-wc-city-select'),
	],
	'MA3' => [
		_x('Ambalabe Befanjava', 'MA3', 'ry-wc-city-select'),
		_x('Ambalakida', 'MA3', 'ry-wc-city-select'),
		_x('Andranoboka', 'MA3', 'ry-wc-city-select'),
		_x('Bekobay', 'MA3', 'ry-wc-city-select'),
		_x('Belobaka', 'MA3', 'ry-wc-city-select'),
		_x('Betsako', 'MA3', 'ry-wc-city-select'),
		_x('Boanamary', 'MA3', 'ry-wc-city-select'),
		_x('Mahajamba Usine', 'MA3', 'ry-wc-city-select'),
		_x('Mariarano', 'MA3', 'ry-wc-city-select'),
	],
	'MA4' => [
		_x('Ambinanidilana', 'MA4', 'ry-wc-city-select'),
		_x('Ambinanindrano', 'MA4', 'ry-wc-city-select'),
		_x('Ambodibonara', 'MA4', 'ry-wc-city-select'),
		_x('Ambodiharina', 'MA4', 'ry-wc-city-select'),
		_x('Ankazotsifantatra', 'MA4', 'ry-wc-city-select'),
		_x('Befotaka', 'MA4', 'ry-wc-city-select'),
		_x('Betsizaraina', 'MA4', 'ry-wc-city-select'),
		_x('Mahanoro', 'MA4', 'ry-wc-city-select'),
		_x('Manjakandriana', 'MA4', 'ry-wc-city-select'),
		_x('Masomeloka', 'MA4', 'ry-wc-city-select'),
		_x('Tsaravinany', 'MA4', 'ry-wc-city-select'),
	],
	'MA5' => [
		_x('Andabotoka', 'MA5', 'ry-wc-city-select'),
		_x('Andranovao', 'MA5', 'ry-wc-city-select'),
		_x('Andrea', 'MA5', 'ry-wc-city-select'),
		_x('Ankisatra', 'MA5', 'ry-wc-city-select'),
		_x('Antsaidoha Bebao', 'MA5', 'ry-wc-city-select'),
		_x('Antsondrodava', 'MA5', 'ry-wc-city-select'),
		_x('Bebaboky Sud', 'MA5', 'ry-wc-city-select'),
		_x('Belitsaky', 'MA5', 'ry-wc-city-select'),
		_x('Bemokotra Sud', 'MA5', 'ry-wc-city-select'),
		_x('Berevo/ranobe', 'MA5', 'ry-wc-city-select'),
		_x('Betanatanana', 'MA5', 'ry-wc-city-select'),
		_x('Mafaijijo', 'MA5', 'ry-wc-city-select'),
		_x('Maintirano', 'MA5', 'ry-wc-city-select'),
		_x('Marohazo', 'MA5', 'ry-wc-city-select'),
		_x('Maromavo', 'MA5', 'ry-wc-city-select'),
		_x('Tambohorano', 'MA5', 'ry-wc-city-select'),
		_x('Veromanga', 'MA5', 'ry-wc-city-select'),
	],
	'MA6' => [
		_x('Ambodihazoambo', 'MA6', 'ry-wc-city-select'),
		_x('Ambohitoaka', 'MA6', 'ry-wc-city-select'),
		_x('Ampasimatera', 'MA6', 'ry-wc-city-select'),
		_x('Ankiririky', 'MA6', 'ry-wc-city-select'),
		_x('Bekoratsaka', 'MA6', 'ry-wc-city-select'),
		_x('Betaramahamay', 'MA6', 'ry-wc-city-select'),
		_x('Komajia', 'MA6', 'ry-wc-city-select'),
		_x('Malakialina', 'MA6', 'ry-wc-city-select'),
		_x('Mampikony I', 'MA6', 'ry-wc-city-select'),
		_x('Mampikony II', 'MA6', 'ry-wc-city-select'),
	],
	'MA7' => [
		_x('Ambahatrazo', 'MA7', 'ry-wc-city-select'),
		_x('Ambahive', 'MA7', 'ry-wc-city-select'),
		_x('Ambalaroka', 'MA7', 'ry-wc-city-select'),
		_x('Ambalavero', 'MA7', 'ry-wc-city-select'),
		_x('Ambandrika', 'MA7', 'ry-wc-city-select'),
		_x('Ambila', 'MA7', 'ry-wc-city-select'),
		_x('Amboanjo', 'MA7', 'ry-wc-city-select'),
		_x('Ambohitsara M', 'MA7', 'ry-wc-city-select'),
		_x('Amborondra', 'MA7', 'ry-wc-city-select'),
		_x('Ambotaka', 'MA7', 'ry-wc-city-select'),
		_x('Ampasimanjeva', 'MA7', 'ry-wc-city-select'),
		_x('Ampasimboraka', 'MA7', 'ry-wc-city-select'),
		_x('Ampasimpotsy Sud', 'MA7', 'ry-wc-city-select'),
		_x('Analavory', 'MA7', 'ry-wc-city-select'),
		_x('Anorombato', 'MA7', 'ry-wc-city-select'),
		_x('Anosiala', 'MA7', 'ry-wc-city-select'),
		_x('Anteza', 'MA7', 'ry-wc-city-select'),
		_x('Bekatra', 'MA7', 'ry-wc-city-select'),
		_x('Betampona', 'MA7', 'ry-wc-city-select'),
		_x('Fenomby', 'MA7', 'ry-wc-city-select'),
		_x('Kianjanomby', 'MA7', 'ry-wc-city-select'),
		_x('Lokomby', 'MA7', 'ry-wc-city-select'),
		_x('Mahabako', 'MA7', 'ry-wc-city-select'),
		_x('Mahamaibe', 'MA7', 'ry-wc-city-select'),
		_x('Manakara', 'MA7', 'ry-wc-city-select'),
		_x('Mangatsiotra', 'MA7', 'ry-wc-city-select'),
		_x('Marofarihy', 'MA7', 'ry-wc-city-select'),
		_x('Mavorano', 'MA7', 'ry-wc-city-select'),
		_x('Mitanty', 'MA7', 'ry-wc-city-select'),
		_x('Mizilo Gara', 'MA7', 'ry-wc-city-select'),
		_x('Nihaonana', 'MA7', 'ry-wc-city-select'),
		_x('Onilahy', 'MA7', 'ry-wc-city-select'),
		_x('Sahanambohitra', 'MA7', 'ry-wc-city-select'),
		_x('Saharefo', 'MA7', 'ry-wc-city-select'),
		_x('Sahasinaka', 'MA7', 'ry-wc-city-select'),
		_x('Sakoana', 'MA7', 'ry-wc-city-select'),
		_x('Sorombo', 'MA7', 'ry-wc-city-select'),
		_x('Tataho', 'MA7', 'ry-wc-city-select'),
		_x('Vatana', 'MA7', 'ry-wc-city-select'),
		_x('Vinanitelo', 'MA7', 'ry-wc-city-select'),
		_x('Vohilava', 'MA7', 'ry-wc-city-select'),
		_x('Vohimanitra', 'MA7', 'ry-wc-city-select'),
		_x('Vohimasina Nord', 'MA7', 'ry-wc-city-select'),
		_x('Vohimasina Sud', 'MA7', 'ry-wc-city-select'),
		_x('Vohimasy', 'MA7', 'ry-wc-city-select'),
	],
	'MANODI' => [
		_x('Ambatoharanana', 'MANODI', 'ry-wc-city-select'),
		_x('Ambodiampana', 'MANODI', 'ry-wc-city-select'),
		_x('Ambodivoanio', 'MANODI', 'ry-wc-city-select'),
		_x('Andasibe I', 'MANODI', 'ry-wc-city-select'),
		_x('Antanambaobe', 'MANODI', 'ry-wc-city-select'),
		_x('Antanambe', 'MANODI', 'ry-wc-city-select'),
		_x('Antanananivo', 'MANODI', 'ry-wc-city-select'),
		_x('Imorona', 'MANODI', 'ry-wc-city-select'),
		_x('Manambolosy', 'MANODI', 'ry-wc-city-select'),
		_x('Mananara Avaratra', 'MANODI', 'ry-wc-city-select'),
		_x('Sandrakatsy', 'MANODI', 'ry-wc-city-select'),
		_x('Saromaona', 'MANODI', 'ry-wc-city-select'),
		_x('Tanibe', 'MANODI', 'ry-wc-city-select'),
		_x('Vanono', 'MANODI', 'ry-wc-city-select'),
	],
	'MADI2' => [
		_x('Ambatomarina', 'MADI2', 'ry-wc-city-select'),
		_x('Ambohimahazo', 'MADI2', 'ry-wc-city-select'),
		_x('Ambohimilanja', 'MADI2', 'ry-wc-city-select'),
		_x('Ambohipo', 'MADI2', 'ry-wc-city-select'),
		_x('Ambovombe Centre', 'MADI2', 'ry-wc-city-select'),
		_x('Andakatany', 'MADI2', 'ry-wc-city-select'),
		_x('Anjoma Nandihizana', 'MADI2', 'ry-wc-city-select'),
		_x('Anjomanankona', 'MADI2', 'ry-wc-city-select'),
		_x('Talata Vohimena', 'MADI2', 'ry-wc-city-select'),
		_x('Vinany Andakatanikely', 'MADI2', 'ry-wc-city-select'),
	],
	'MA8' => [
		_x('Ambalahosy Nord', 'MA8', 'ry-wc-city-select'),
		_x('Ambodinonoka', 'MA8', 'ry-wc-city-select'),
		_x('Ambohimiarina II', 'MA8', 'ry-wc-city-select'),
		_x('Ambohinihaonana', 'MA8', 'ry-wc-city-select'),
		_x('Ambohitsara Est', 'MA8', 'ry-wc-city-select'),
		_x('Andonabe', 'MA8', 'ry-wc-city-select'),
		_x('Andranambolava', 'MA8', 'ry-wc-city-select'),
		_x('Andranomavo', 'MA8', 'ry-wc-city-select'),
		_x('Ankatafana', 'MA8', 'ry-wc-city-select'),
		_x('Anosimparihy', 'MA8', 'ry-wc-city-select'),
		_x('Antaretra', 'MA8', 'ry-wc-city-select'),
		_x('Antsenavolo', 'MA8', 'ry-wc-city-select'),
		_x('Kianjavato', 'MA8', 'ry-wc-city-select'),
		_x('Mahatsara Iefaka', 'MA8', 'ry-wc-city-select'),
		_x('Mahatsara Sud', 'MA8', 'ry-wc-city-select'),
		_x('Mahavoky Nord', 'MA8', 'ry-wc-city-select'),
		_x('Mahela', 'MA8', 'ry-wc-city-select'),
		_x('Manakana Nord', 'MA8', 'ry-wc-city-select'),
		_x('Mananjary', 'MA8', 'ry-wc-city-select'),
		_x('Marofototra', 'MA8', 'ry-wc-city-select'),
		_x('Marokarima', 'MA8', 'ry-wc-city-select'),
		_x('Marosangy', 'MA8', 'ry-wc-city-select'),
		_x('Morafeno', 'MA8', 'ry-wc-city-select'),
		_x('Namorona', 'MA8', 'ry-wc-city-select'),
		_x('Sandrohy', 'MA8', 'ry-wc-city-select'),
		_x('Tsaravary', 'MA8', 'ry-wc-city-select'),
		_x('Tsiatosika', 'MA8', 'ry-wc-city-select'),
		_x('Vatohandrina', 'MA8', 'ry-wc-city-select'),
		_x('Vohilava', 'MA8', 'ry-wc-city-select'),
	],
	'MA9' => [
		_x('Anjoma Ramartina', 'MA9', 'ry-wc-city-select'),
		_x('Ankazomiriotra', 'MA9', 'ry-wc-city-select'),
		_x('Antanambao Ambary', 'MA9', 'ry-wc-city-select'),
		_x('Betsohana', 'MA9', 'ry-wc-city-select'),
		_x('Fidirana', 'MA9', 'ry-wc-city-select'),
		_x('Mandoto', 'MA9', 'ry-wc-city-select'),
		_x('Vasiana', 'MA9', 'ry-wc-city-select'),
		_x('Vinany', 'MA9', 'ry-wc-city-select'),
	],
	'MA10' => [
		_x('Ambalakirajy', 'MA10', 'ry-wc-city-select'),
		_x('Ambarikorano', 'MA10', 'ry-wc-city-select'),
		_x('Ambaripaika', 'MA10', 'ry-wc-city-select'),
		_x('Ambilombe', 'MA10', 'ry-wc-city-select'),
		_x('Amboaboa', 'MA10', 'ry-wc-city-select'),
		_x('Ambodiadabo', 'MA10', 'ry-wc-city-select'),
		_x('Ambodiamontana Kianga', 'MA10', 'ry-wc-city-select'),
		_x('Ambohisoa', 'MA10', 'ry-wc-city-select'),
		_x('Amborondolo', 'MA10', 'ry-wc-city-select'),
		_x('Ampatakamaroreny', 'MA10', 'ry-wc-city-select'),
		_x('Andohajango', 'MA10', 'ry-wc-city-select'),
		_x('Andratamarina', 'MA10', 'ry-wc-city-select'),
		_x('Anjiabe', 'MA10', 'ry-wc-city-select'),
		_x('Ankiabe-Salohy', 'MA10', 'ry-wc-city-select'),
		_x('Ankiakabe-Fonoko', 'MA10', 'ry-wc-city-select'),
		_x('Antanambaonamberina', 'MA10', 'ry-wc-city-select'),
		_x('Antanandava', 'MA10', 'ry-wc-city-select'),
		_x('Antsatramidola', 'MA10', 'ry-wc-city-select'),
		_x('Antsiatsiaka', 'MA10', 'ry-wc-city-select'),
		_x('Antsirabe Centre', 'MA10', 'ry-wc-city-select'),
		_x('Antsoha', 'MA10', 'ry-wc-city-select'),
		_x('Kalandy', 'MA10', 'ry-wc-city-select'),
		_x('Manampaneva', 'MA10', 'ry-wc-city-select'),
		_x('Mandritsara', 'MA10', 'ry-wc-city-select'),
		_x('Marotandrano', 'MA10', 'ry-wc-city-select'),
		_x('Pont Sofia', 'MA10', 'ry-wc-city-select'),
		_x('Tsarajomoka', 'MA10', 'ry-wc-city-select'),
		_x('Tsaratanana', 'MA10', 'ry-wc-city-select'),
	],
	'MADI3' => [
		_x('Andranopasy', 'MADI3', 'ry-wc-city-select'),
		_x('Ankiliabo', 'MADI3', 'ry-wc-city-select'),
		_x('Anontsibe Centre', 'MADI3', 'ry-wc-city-select'),
		_x('Beharona', 'MADI3', 'ry-wc-city-select'),
		_x('Manja', 'MADI3', 'ry-wc-city-select'),
		_x('Soaserana', 'MADI3', 'ry-wc-city-select'),
	],
	'MA11' => [
		_x('Alarobia', 'MA11', 'ry-wc-city-select'),
		_x('Ambanitsena', 'MA11', 'ry-wc-city-select'),
		_x('Ambatolaona', 'MA11', 'ry-wc-city-select'),
		_x('Ambatomanga', 'MA11', 'ry-wc-city-select'),
		_x('Ambatomena', 'MA11', 'ry-wc-city-select'),
		_x('Ambohibao Sud', 'MA11', 'ry-wc-city-select'),
		_x('Ambohibary', 'MA11', 'ry-wc-city-select'),
		_x('Ambohitrandriamanitra', 'MA11', 'ry-wc-city-select'),
		_x('Ambohitrolomahitsy', 'MA11', 'ry-wc-city-select'),
		_x('Ambohitrony', 'MA11', 'ry-wc-city-select'),
		_x('Ambohitseheno', 'MA11', 'ry-wc-city-select'),
		_x('Ampaneva', 'MA11', 'ry-wc-city-select'),
		_x('Anjepy', 'MA11', 'ry-wc-city-select'),
		_x('Anjoma Betoho', 'MA11', 'ry-wc-city-select'),
		_x('Ankazondandy', 'MA11', 'ry-wc-city-select'),
		_x('Antsahalalina', 'MA11', 'ry-wc-city-select'),
		_x('Manjakandriana', 'MA11', 'ry-wc-city-select'),
		_x('Mantasoa', 'MA11', 'ry-wc-city-select'),
		_x('Merikanjaka', 'MA11', 'ry-wc-city-select'),
		_x('Miadanandriana', 'MA11', 'ry-wc-city-select'),
		_x('Nandihizana', 'MA11', 'ry-wc-city-select'),
		_x('Ranovao', 'MA11', 'ry-wc-city-select'),
		_x('Sadabe', 'MA11', 'ry-wc-city-select'),
		_x('Sambaina', 'MA11', 'ry-wc-city-select'),
		_x('Soavinandriana', 'MA11', 'ry-wc-city-select'),
	],
	'MADI4' => [
		_x('Ambanizana', 'MADI4', 'ry-wc-city-select'),
		_x('Ambinanitelo', 'MADI4', 'ry-wc-city-select'),
		_x('Ambodimanga Rantabe', 'MADI4', 'ry-wc-city-select'),
		_x('Anandrivola', 'MADI4', 'ry-wc-city-select'),
		_x('Andranofotsy', 'MADI4', 'ry-wc-city-select'),
		_x('Androndrono', 'MADI4', 'ry-wc-city-select'),
		_x('Anjahana', 'MADI4', 'ry-wc-city-select'),
		_x('Anjanazana', 'MADI4', 'ry-wc-city-select'),
		_x('Ankofa', 'MADI4', 'ry-wc-city-select'),
		_x('Ankofabe', 'MADI4', 'ry-wc-city-select'),
		_x('Antakotako', 'MADI4', 'ry-wc-city-select'),
		_x('Antsirabe Sahatany', 'MADI4', 'ry-wc-city-select'),
		_x('Mahalevona', 'MADI4', 'ry-wc-city-select'),
		_x('Manambolo', 'MADI4', 'ry-wc-city-select'),
		_x('Maroantsetra', 'MADI4', 'ry-wc-city-select'),
		_x('Morafeno', 'MADI4', 'ry-wc-city-select'),
		_x('Rantabe', 'MADI4', 'ry-wc-city-select'),
		_x('Voloina', 'MADI4', 'ry-wc-city-select'),
	],
	'MA12' => [
		_x('Ambalapaiso II', 'MA12', 'ry-wc-city-select'),
		_x('Ambatofisaka II', 'MA12', 'ry-wc-city-select'),
		_x('Amboasary', 'MA12', 'ry-wc-city-select'),
		_x('Ambodinonoka', 'MA12', 'ry-wc-city-select'),
		_x('Ambodivoangy', 'MA12', 'ry-wc-city-select'),
		_x('Ambohimilanja', 'MA12', 'ry-wc-city-select'),
		_x('Andonabe Sud', 'MA12', 'ry-wc-city-select'),
		_x('Androrangavola', 'MA12', 'ry-wc-city-select'),
		_x('Anosiarivo I', 'MA12', 'ry-wc-city-select'),
		_x('Betampona', 'MA12', 'ry-wc-city-select'),
		_x('Lohavanana', 'MA12', 'ry-wc-city-select'),
		_x('Marolambo', 'MA12', 'ry-wc-city-select'),
		_x('Sahakevo', 'MA12', 'ry-wc-city-select'),
		_x('Tanambao Rabemanana', 'MA12', 'ry-wc-city-select'),
	],
	'MADI5' => [
		_x('Ambolomoty', 'MADI5', 'ry-wc-city-select'),
		_x('Ankaraobato', 'MADI5', 'ry-wc-city-select'),
		_x('Ankazomborona', 'MADI5', 'ry-wc-city-select'),
		_x('Anosinalainolona', 'MADI5', 'ry-wc-city-select'),
		_x('Antanambao Andranolava', 'MADI5', 'ry-wc-city-select'),
		_x('Antanimasaka', 'MADI5', 'ry-wc-city-select'),
		_x('Bemaharivo', 'MADI5', 'ry-wc-city-select'),
		_x('Manaratsandry', 'MADI5', 'ry-wc-city-select'),
		_x('Marovoay', 'MADI5', 'ry-wc-city-select'),
		_x('Marovoay Banlieue', 'MADI5', 'ry-wc-city-select'),
		_x('Marovoay Ville', 'MADI5', 'ry-wc-city-select'),
		_x('Tsararano', 'MADI5', 'ry-wc-city-select'),
	],
	'MIDI' => [
		_x('Ambatolahy', 'MIDI', 'ry-wc-city-select'),
		_x('Ampanihy', 'MIDI', 'ry-wc-city-select'),
		_x('Ankavandra', 'MIDI', 'ry-wc-city-select'),
		_x('Ankondromena', 'MIDI', 'ry-wc-city-select'),
		_x('Ankotrofotsy', 'MIDI', 'ry-wc-city-select'),
		_x('Anosimena', 'MIDI', 'ry-wc-city-select'),
		_x('Bemahatazana', 'MIDI', 'ry-wc-city-select'),
		_x('Betsipolitra', 'MIDI', 'ry-wc-city-select'),
		_x('Dabolava', 'MIDI', 'ry-wc-city-select'),
		_x('Isalo', 'MIDI', 'ry-wc-city-select'),
		_x('Itondy', 'MIDI', 'ry-wc-city-select'),
		_x('Manambina', 'MIDI', 'ry-wc-city-select'),
		_x('Manandaza', 'MIDI', 'ry-wc-city-select'),
		_x('Miandrivazo', 'MIDI', 'ry-wc-city-select'),
		_x('Soaloka', 'MIDI', 'ry-wc-city-select'),
	],
	'MI' => [
		_x('Alatsinainikely', 'MI', 'ry-wc-city-select'),
		_x('Ambatomanjaka', 'MI', 'ry-wc-city-select'),
		_x('Analavory', 'MI', 'ry-wc-city-select'),
		_x('Andolofotsy', 'MI', 'ry-wc-city-select'),
		_x('Anosibe Ifanja', 'MI', 'ry-wc-city-select'),
		_x('Antoby Est', 'MI', 'ry-wc-city-select'),
		_x('Manazary', 'MI', 'ry-wc-city-select'),
		_x('Mandiavato', 'MI', 'ry-wc-city-select'),
		_x('Miarinarivo I', 'MI', 'ry-wc-city-select'),
		_x('Miarinarivo II', 'MI', 'ry-wc-city-select'),
		_x('Sarobaratra Ifanja', 'MI', 'ry-wc-city-select'),
		_x('Soamahamanina', 'MI', 'ry-wc-city-select'),
		_x('Soavimbazaha', 'MI', 'ry-wc-city-select'),
		_x('Zoma Bealoka', 'MI', 'ry-wc-city-select'),
	],
	'MI2' => [
		_x('Andranolalina', 'MI2', 'ry-wc-city-select'),
		_x('Ankazovelo', 'MI2', 'ry-wc-city-select'),
		_x('Ivondro', 'MI2', 'ry-wc-city-select'),
		_x('Maliorano', 'MI2', 'ry-wc-city-select'),
		_x('Nosifeno', 'MI2', 'ry-wc-city-select'),
		_x('Soakibany', 'MI2', 'ry-wc-city-select'),
	],
	'MI3' => [
		_x('Ambarimaninga', 'MI3', 'ry-wc-city-select'),
		_x('Antongomena Bevary', 'MI3', 'ry-wc-city-select'),
		_x('Antseza', 'MI3', 'ry-wc-city-select'),
		_x('Bekipay', 'MI3', 'ry-wc-city-select'),
		_x('Katsepy', 'MI3', 'ry-wc-city-select'),
		_x('Matsakabanja', 'MI3', 'ry-wc-city-select'),
		_x('Mitsinjo', 'MI3', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Andramy', 'MO', 'ry-wc-city-select'),
		_x('Beravina', 'MO', 'ry-wc-city-select'),
		_x('Morafenobe', 'MO', 'ry-wc-city-select'),
	],
	'MODI' => [
		_x('Ambatovola', 'MODI', 'ry-wc-city-select'),
		_x('Amboasary', 'MODI', 'ry-wc-city-select'),
		_x('Ambohibary', 'MODI', 'ry-wc-city-select'),
		_x('Ambohidronono', 'MODI', 'ry-wc-city-select'),
		_x('Ampasimpotsy Gara', 'MODI', 'ry-wc-city-select'),
		_x('Ampasipotsy Mandialaza', 'MODI', 'ry-wc-city-select'),
		_x('Andaingo', 'MODI', 'ry-wc-city-select'),
		_x('Andasibe', 'MODI', 'ry-wc-city-select'),
		_x('Anosibe Ifody', 'MODI', 'ry-wc-city-select'),
		_x('Antanandava', 'MODI', 'ry-wc-city-select'),
		_x('Antaniditra', 'MODI', 'ry-wc-city-select'),
		_x('Beforona', 'MODI', 'ry-wc-city-select'),
		_x('Belavabary', 'MODI', 'ry-wc-city-select'),
		_x('Fierenana', 'MODI', 'ry-wc-city-select'),
		_x('Lakato', 'MODI', 'ry-wc-city-select'),
		_x('Mandialaza', 'MODI', 'ry-wc-city-select'),
		_x('Mangarivotra', 'MODI', 'ry-wc-city-select'),
		_x('Moramanga', 'MODI', 'ry-wc-city-select'),
		_x('Morarano Gara', 'MODI', 'ry-wc-city-select'),
		_x('Sabotsy Anjiro', 'MODI', 'ry-wc-city-select'),
		_x('Vodiriana', 'MODI', 'ry-wc-city-select'),
	],
	'MODI2' => [
		_x('Ambahikily', 'MODI2', 'ry-wc-city-select'),
		_x('Antanimieva', 'MODI2', 'ry-wc-city-select'),
		_x('Antongo Vaovao', 'MODI2', 'ry-wc-city-select'),
		_x('Basibasy', 'MODI2', 'ry-wc-city-select'),
		_x('Befandefa', 'MODI2', 'ry-wc-city-select'),
		_x('Befandriana Sud', 'MODI2', 'ry-wc-city-select'),
		_x('Cu Morombe', 'MODI2', 'ry-wc-city-select'),
		_x('Nosy Ambositra', 'MODI2', 'ry-wc-city-select'),
	],
	'MODI3' => [
		_x('Analaiva', 'MODI3', 'ry-wc-city-select'),
		_x('Befasy', 'MODI3', 'ry-wc-city-select'),
		_x('Belo Sur Mer', 'MODI3', 'ry-wc-city-select'),
		_x('Bemanonga', 'MODI3', 'ry-wc-city-select'),
		_x('Morondava', 'MODI3', 'ry-wc-city-select'),
	],
	'NO' => [
		_x('Ambatozavavy', 'NO', 'ry-wc-city-select'),
		_x('Ampangorina', 'NO', 'ry-wc-city-select'),
		_x('Bemanondrobe', 'NO', 'ry-wc-city-select'),
		_x('Dzamandzar', 'NO', 'ry-wc-city-select'),
		_x('Hell-Ville', 'NO', 'ry-wc-city-select'),
	],
	'NOBO' => [
		_x('Sainte Marie', 'NOBO', 'ry-wc-city-select'),
	],
	'NO2' => [
		_x('Ambahy', 'NO2', 'ry-wc-city-select'),
		_x('Ambakobe', 'NO2', 'ry-wc-city-select'),
		_x('Ambodiara', 'NO2', 'ry-wc-city-select'),
		_x('Ambodilafa', 'NO2', 'ry-wc-city-select'),
		_x('Ambodiriani Sahafary', 'NO2', 'ry-wc-city-select'),
		_x('Ampasinambo', 'NO2', 'ry-wc-city-select'),
		_x('Andara', 'NO2', 'ry-wc-city-select'),
		_x('Androrangavola', 'NO2', 'ry-wc-city-select'),
		_x('Angodongodona', 'NO2', 'ry-wc-city-select'),
		_x('Antanambao', 'NO2', 'ry-wc-city-select'),
		_x('Befody', 'NO2', 'ry-wc-city-select'),
		_x('Fiadanana', 'NO2', 'ry-wc-city-select'),
		_x('Nosy Varika', 'NO2', 'ry-wc-city-select'),
		_x('Sahavato', 'NO2', 'ry-wc-city-select'),
		_x('Soavina', 'NO2', 'ry-wc-city-select'),
		_x('Vohidroa', 'NO2', 'ry-wc-city-select'),
		_x('Vohilava', 'NO2', 'ry-wc-city-select'),
		_x('Vohitrandriana', 'NO2', 'ry-wc-city-select'),
	],
	'PO(B' => [
		_x('Ambanjabe', 'PO(B', 'ry-wc-city-select'),
		_x('Ambodimahabibo', 'PO(B', 'ry-wc-city-select'),
		_x('Ambodisakoana', 'PO(B', 'ry-wc-city-select'),
		_x('Ambodivongo', 'PO(B', 'ry-wc-city-select'),
		_x('Amparihy', 'PO(B', 'ry-wc-city-select'),
		_x('Andranomeva', 'PO(B', 'ry-wc-city-select'),
		_x('Leanja', 'PO(B', 'ry-wc-city-select'),
		_x('Maevaranohely', 'PO(B', 'ry-wc-city-select'),
		_x('Marovato', 'PO(B', 'ry-wc-city-select'),
		_x('Port Berge', 'PO(B', 'ry-wc-city-select'),
		_x('Port Berge II', 'PO(B', 'ry-wc-city-select'),
		_x('Tsarahasina', 'PO(B', 'ry-wc-city-select'),
		_x('Tsaratanana I', 'PO(B', 'ry-wc-city-select'),
		_x('Tsiningia', 'PO(B', 'ry-wc-city-select'),
		_x('Tsinjomitondraka', 'PO(B', 'ry-wc-city-select'),
	],
	'SADI' => [
		_x('Ambinany', 'SADI', 'ry-wc-city-select'),
		_x('Amboronabo', 'SADI', 'ry-wc-city-select'),
		_x('Andamasiny Vineta', 'SADI', 'ry-wc-city-select'),
		_x('Andranolava', 'SADI', 'ry-wc-city-select'),
		_x('Bereketa', 'SADI', 'ry-wc-city-select'),
		_x('Mahaboboka', 'SADI', 'ry-wc-city-select'),
		_x('Miary Lamatihy', 'SADI', 'ry-wc-city-select'),
		_x('Miary Taheza', 'SADI', 'ry-wc-city-select'),
		_x('Mihavatsy', 'SADI', 'ry-wc-city-select'),
		_x('Mikoboka', 'SADI', 'ry-wc-city-select'),
		_x('Mitsinjo', 'SADI', 'ry-wc-city-select'),
		_x('Sakaraha', 'SADI', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Ambatoafo', 'SA', 'ry-wc-city-select'),
		_x('Amboangibe', 'SA', 'ry-wc-city-select'),
		_x('Ambodiampana', 'SA', 'ry-wc-city-select'),
		_x('Ambodivoara', 'SA', 'ry-wc-city-select'),
		_x('Ambohimalaza', 'SA', 'ry-wc-city-select'),
		_x('Ambohimitsinjo', 'SA', 'ry-wc-city-select'),
		_x('Analamaho', 'SA', 'ry-wc-city-select'),
		_x('Andrahanjo', 'SA', 'ry-wc-city-select'),
		_x('Andratamarina', 'SA', 'ry-wc-city-select'),
		_x('Andrembona', 'SA', 'ry-wc-city-select'),
		_x('Anjangoveratra', 'SA', 'ry-wc-city-select'),
		_x('Anjialava', 'SA', 'ry-wc-city-select'),
		_x('Anjinjaomby', 'SA', 'ry-wc-city-select'),
		_x('Antindra', 'SA', 'ry-wc-city-select'),
		_x('Antsahavaribe', 'SA', 'ry-wc-city-select'),
		_x('Antsambaharo', 'SA', 'ry-wc-city-select'),
		_x('Bemanevika', 'SA', 'ry-wc-city-select'),
		_x('Bevonotra', 'SA', 'ry-wc-city-select'),
		_x('Farahalana', 'SA', 'ry-wc-city-select'),
		_x('Maroambihy', 'SA', 'ry-wc-city-select'),
		_x('Marogaona', 'SA', 'ry-wc-city-select'),
		_x('Marojala', 'SA', 'ry-wc-city-select'),
		_x('Morafeno', 'SA', 'ry-wc-city-select'),
		_x('Nosiarina', 'SA', 'ry-wc-city-select'),
		_x('Sambava Cu', 'SA', 'ry-wc-city-select'),
		_x('Tanambao Daoud', 'SA', 'ry-wc-city-select'),
	],
	'SO' => [
		_x('Ambohipaky', 'SO', 'ry-wc-city-select'),
		_x('Andranomavo', 'SO', 'ry-wc-city-select'),
		_x('Soalala', 'SO', 'ry-wc-city-select'),
	],
	'SOIV' => [
		_x('Ambahoabe', 'SOIV', 'ry-wc-city-select'),
		_x('Ambodiampana', 'SOIV', 'ry-wc-city-select'),
		_x('Andapafito', 'SOIV', 'ry-wc-city-select'),
		_x('Antanifotsy', 'SOIV', 'ry-wc-city-select'),
		_x('Antenina', 'SOIV', 'ry-wc-city-select'),
		_x('Fotsialanana', 'SOIV', 'ry-wc-city-select'),
		_x('Manompana', 'SOIV', 'ry-wc-city-select'),
		_x('Soanierana Ivongo', 'SOIV', 'ry-wc-city-select'),
	],
	'SO2' => [
		_x('Ambatoasana Centre', 'SO2', 'ry-wc-city-select'),
		_x('Amberomanga', 'SO2', 'ry-wc-city-select'),
		_x('Amparaky', 'SO2', 'ry-wc-city-select'),
		_x('Amparibohitra', 'SO2', 'ry-wc-city-select'),
		_x('Ampary', 'SO2', 'ry-wc-city-select'),
		_x('Ampefy', 'SO2', 'ry-wc-city-select'),
		_x('Ankaranana', 'SO2', 'ry-wc-city-select'),
		_x('Ankisabe', 'SO2', 'ry-wc-city-select'),
		_x('Antanetibe', 'SO2', 'ry-wc-city-select'),
		_x('Dondona', 'SO2', 'ry-wc-city-select'),
		_x('Mahavelona', 'SO2', 'ry-wc-city-select'),
		_x('Mananasy', 'SO2', 'ry-wc-city-select'),
		_x('Masindray', 'SO2', 'ry-wc-city-select'),
		_x('Soavinandriana', 'SO2', 'ry-wc-city-select'),
		_x('Tamponala', 'SO2', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Ambatoabo', 'TA', 'ry-wc-city-select'),
		_x('Ampasimena', 'TA', 'ry-wc-city-select'),
		_x('Ampasy Nahampoana', 'TA', 'ry-wc-city-select'),
		_x('Analamary', 'TA', 'ry-wc-city-select'),
		_x('Analapatsy', 'TA', 'ry-wc-city-select'),
		_x('Andranobory', 'TA', 'ry-wc-city-select'),
		_x('Ankaramena', 'TA', 'ry-wc-city-select'),
		_x('Ankariera', 'TA', 'ry-wc-city-select'),
		_x('Bevoay', 'TA', 'ry-wc-city-select'),
		_x('Emagnobo', 'TA', 'ry-wc-city-select'),
		_x('Enakara-Haut', 'TA', 'ry-wc-city-select'),
		_x('Enaniliha', 'TA', 'ry-wc-city-select'),
		_x('Fenoevo-Efita', 'TA', 'ry-wc-city-select'),
		_x('Fort-Dauphin', 'TA', 'ry-wc-city-select'),
		_x('Iaboakoho', 'TA', 'ry-wc-city-select'),
		_x('Ifarantsa', 'TA', 'ry-wc-city-select'),
		_x('Isaka-Ivondro', 'TA', 'ry-wc-city-select'),
		_x('Mahatalaky', 'TA', 'ry-wc-city-select'),
		_x('Manambaro', 'TA', 'ry-wc-city-select'),
		_x('Manantenina', 'TA', 'ry-wc-city-select'),
		_x('Mandiso', 'TA', 'ry-wc-city-select'),
		_x('Mandromondromotra', 'TA', 'ry-wc-city-select'),
		_x('Ranomafana', 'TA', 'ry-wc-city-select'),
		_x('Ranopiso', 'TA', 'ry-wc-city-select'),
		_x('Sarisambo', 'TA', 'ry-wc-city-select'),
		_x('Soanierana', 'TA', 'ry-wc-city-select'),
		_x('Soavary', 'TA', 'ry-wc-city-select'),
	],
	'TO' => [
		_x('Ambodimanga', 'TO', 'ry-wc-city-select'),
		_x('Anjoma', 'TO', 'ry-wc-city-select'),
		_x('Ankirihiry', 'TO', 'ry-wc-city-select'),
		_x('Morarano', 'TO', 'ry-wc-city-select'),
		_x('Tanambao V', 'TO', 'ry-wc-city-select'),
	],
	'TO2' => [
		_x('Ambodilazana', 'TO2', 'ry-wc-city-select'),
		_x('Ambodiriana', 'TO2', 'ry-wc-city-select'),
		_x('Amboditandroroho', 'TO2', 'ry-wc-city-select'),
		_x('Ampasimadinika Manambolo', 'TO2', 'ry-wc-city-select'),
		_x('Ampasimbe Onibe', 'TO2', 'ry-wc-city-select'),
		_x('Ampisokina', 'TO2', 'ry-wc-city-select'),
		_x('Amporoforo', 'TO2', 'ry-wc-city-select'),
		_x('Andondabe', 'TO2', 'ry-wc-city-select'),
		_x('Andranobolaha', 'TO2', 'ry-wc-city-select'),
		_x('Antenina', 'TO2', 'ry-wc-city-select'),
		_x('Antetezambaro', 'TO2', 'ry-wc-city-select'),
		_x('Fanandrana', 'TO2', 'ry-wc-city-select'),
		_x('Fito', 'TO2', 'ry-wc-city-select'),
		_x('Mahavelona (Foulpointe)', 'TO2', 'ry-wc-city-select'),
		_x('Mangabe', 'TO2', 'ry-wc-city-select'),
		_x('Sahambala', 'TO2', 'ry-wc-city-select'),
		_x('Toamasina Suburbaine', 'TO2', 'ry-wc-city-select'),
	],
	'TODI' => [
		_x('Besakoa', 'TODI', 'ry-wc-city-select'),
		_x('Betania', 'TODI', 'ry-wc-city-select'),
		_x('Mahavatse I', 'TODI', 'ry-wc-city-select'),
		_x('Mahavatse II', 'TODI', 'ry-wc-city-select'),
		_x('Tanambao I', 'TODI', 'ry-wc-city-select'),
		_x('Tanambao II Tsf Nord', 'TODI', 'ry-wc-city-select'),
	],
	'TODI2' => [
		_x('Ambohimahavelona', 'TODI2', 'ry-wc-city-select'),
		_x('Ambolofoty', 'TODI2', 'ry-wc-city-select'),
		_x('Anakao', 'TODI2', 'ry-wc-city-select'),
		_x('Analamisampy', 'TODI2', 'ry-wc-city-select'),
		_x('Andranohinaly', 'TODI2', 'ry-wc-city-select'),
		_x('Andranovory', 'TODI2', 'ry-wc-city-select'),
		_x('Ankililoaka', 'TODI2', 'ry-wc-city-select'),
		_x('Ankilimalinike', 'TODI2', 'ry-wc-city-select'),
		_x('Antanimena Onilahy', 'TODI2', 'ry-wc-city-select'),
		_x('Beheloka', 'TODI2', 'ry-wc-city-select'),
		_x('Behompy', 'TODI2', 'ry-wc-city-select'),
		_x('Belalanda', 'TODI2', 'ry-wc-city-select'),
		_x('Betsinjaka', 'TODI2', 'ry-wc-city-select'),
		_x('Manombo Sud', 'TODI2', 'ry-wc-city-select'),
		_x('Manorofify', 'TODI2', 'ry-wc-city-select'),
		_x('Marofoty', 'TODI2', 'ry-wc-city-select'),
		_x('Maromiandra', 'TODI2', 'ry-wc-city-select'),
		_x('Miary Ambohibola', 'TODI2', 'ry-wc-city-select'),
		_x('Milenaka', 'TODI2', 'ry-wc-city-select'),
		_x('Mitsinjo Betanimena', 'TODI2', 'ry-wc-city-select'),
		_x('Saint Augustin', 'TODI2', 'ry-wc-city-select'),
		_x('Soalara Sud', 'TODI2', 'ry-wc-city-select'),
		_x('Tsianisiha', 'TODI2', 'ry-wc-city-select'),
	],
	'TS' => [
		_x('Ambakireny', 'TS', 'ry-wc-city-select'),
		_x('Ampandrana', 'TS', 'ry-wc-city-select'),
		_x('Andriamena', 'TS', 'ry-wc-city-select'),
		_x('Bekapaika', 'TS', 'ry-wc-city-select'),
		_x('Betrandraka', 'TS', 'ry-wc-city-select'),
		_x('Brieville', 'TS', 'ry-wc-city-select'),
		_x('Keliloha', 'TS', 'ry-wc-city-select'),
		_x('Manakana', 'TS', 'ry-wc-city-select'),
		_x('Sakoamadinika', 'TS', 'ry-wc-city-select'),
		_x('Sarobaratra', 'TS', 'ry-wc-city-select'),
		_x('Tsararova', 'TS', 'ry-wc-city-select'),
		_x('Tsaratanana', 'TS', 'ry-wc-city-select'),
	],
	'TS2' => [
		_x('Anjampaly', 'TS2', 'ry-wc-city-select'),
		_x('Antaritarika', 'TS2', 'ry-wc-city-select'),
		_x('Betanty (Faux Cap)', 'TS2', 'ry-wc-city-select'),
		_x('Imongy', 'TS2', 'ry-wc-city-select'),
		_x('Marovato', 'TS2', 'ry-wc-city-select'),
		_x('Nikoly', 'TS2', 'ry-wc-city-select'),
		_x('Tsihombe', 'TS2', 'ry-wc-city-select'),
	],
	'TS3' => [
		_x('Ambalanirana', 'TS3', 'ry-wc-city-select'),
		_x('Ambararatabe', 'TS3', 'ry-wc-city-select'),
		_x('Ambatolampy', 'TS3', 'ry-wc-city-select'),
		_x('Ankadinondry Sakay', 'TS3', 'ry-wc-city-select'),
		_x('Ankerana Avaratra', 'TS3', 'ry-wc-city-select'),
		_x('Anosy', 'TS3', 'ry-wc-city-select'),
		_x('Belobaka', 'TS3', 'ry-wc-city-select'),
		_x('Bemahatazana', 'TS3', 'ry-wc-city-select'),
		_x('Bevato', 'TS3', 'ry-wc-city-select'),
		_x('Fierenana', 'TS3', 'ry-wc-city-select'),
		_x('Mahasolo', 'TS3', 'ry-wc-city-select'),
		_x('Maritampona', 'TS3', 'ry-wc-city-select'),
		_x('Maroharona', 'TS3', 'ry-wc-city-select'),
		_x('Miandrarivo', 'TS3', 'ry-wc-city-select'),
		_x('Soanierana', 'TS3', 'ry-wc-city-select'),
		_x('Tsinjoarivo Imanga', 'TS3', 'ry-wc-city-select'),
		_x('Tsiroanomandidy Fihaonana', 'TS3', 'ry-wc-city-select'),
	],
	'VADI' => [
		_x('Ambatolava', 'VADI', 'ry-wc-city-select'),
		_x('Ambongo', 'VADI', 'ry-wc-city-select'),
		_x('Amparihy Est', 'VADI', 'ry-wc-city-select'),
		_x('Ampasimalemy', 'VADI', 'ry-wc-city-select'),
		_x('Ampataka', 'VADI', 'ry-wc-city-select'),
		_x('Anilobe', 'VADI', 'ry-wc-city-select'),
		_x('Bekaraoky', 'VADI', 'ry-wc-city-select'),
		_x('Bema', 'VADI', 'ry-wc-city-select'),
		_x('Bevata', 'VADI', 'ry-wc-city-select'),
		_x('Fenoambany', 'VADI', 'ry-wc-city-select'),
		_x('Iara', 'VADI', 'ry-wc-city-select'),
		_x('Isahara', 'VADI', 'ry-wc-city-select'),
		_x('Karimbary', 'VADI', 'ry-wc-city-select'),
		_x('Lohafary', 'VADI', 'ry-wc-city-select'),
		_x('Lopary', 'VADI', 'ry-wc-city-select'),
		_x('Manambondro', 'VADI', 'ry-wc-city-select'),
		_x('Marokibo', 'VADI', 'ry-wc-city-select'),
		_x('Masianaka', 'VADI', 'ry-wc-city-select'),
		_x('Matanga', 'VADI', 'ry-wc-city-select'),
		_x('Ranomena', 'VADI', 'ry-wc-city-select'),
		_x('Sandravinany', 'VADI', 'ry-wc-city-select'),
		_x('Soamanova', 'VADI', 'ry-wc-city-select'),
		_x('Tsianofana', 'VADI', 'ry-wc-city-select'),
		_x('Tsiately', 'VADI', 'ry-wc-city-select'),
		_x('Vangaindrano', 'VADI', 'ry-wc-city-select'),
		_x('Vatanato', 'VADI', 'ry-wc-city-select'),
		_x('Vohimalaza', 'VADI', 'ry-wc-city-select'),
		_x('Vohipaho', 'VADI', 'ry-wc-city-select'),
		_x('Vohitrambo', 'VADI', 'ry-wc-city-select'),
	],
	'VA' => [
		_x('Ambalabe', 'VA', 'ry-wc-city-select'),
		_x('Ambalavolo', 'VA', 'ry-wc-city-select'),
		_x('Amboditavolo', 'VA', 'ry-wc-city-select'),
		_x('Ambodivoananto', 'VA', 'ry-wc-city-select'),
		_x('Ampasimadinika', 'VA', 'ry-wc-city-select'),
		_x('Ampasimazava', 'VA', 'ry-wc-city-select'),
		_x('Antanambao Mahatsara', 'VA', 'ry-wc-city-select'),
		_x('Iamborano', 'VA', 'ry-wc-city-select'),
		_x('Ifasina I', 'VA', 'ry-wc-city-select'),
		_x('Ifasina II', 'VA', 'ry-wc-city-select'),
		_x('Ilaka Est', 'VA', 'ry-wc-city-select'),
		_x('Maintinandry', 'VA', 'ry-wc-city-select'),
		_x('Niarovana Caroline', 'VA', 'ry-wc-city-select'),
		_x('Niherenana', 'VA', 'ry-wc-city-select'),
		_x('Sahamatevina', 'VA', 'ry-wc-city-select'),
		_x('Tanambao Vahatrakaka', 'VA', 'ry-wc-city-select'),
		_x('Tsarasambo', 'VA', 'ry-wc-city-select'),
		_x('Tsivangiana', 'VA', 'ry-wc-city-select'),
		_x('Vatomandry', 'VA', 'ry-wc-city-select'),
	],
	'VADI2' => [
		_x('Ambatoharanana', 'VADI2', 'ry-wc-city-select'),
		_x('Ambodimangavalo', 'VADI2', 'ry-wc-city-select'),
		_x('Ambohibe', 'VADI2', 'ry-wc-city-select'),
		_x('Ampasimazava', 'VADI2', 'ry-wc-city-select'),
		_x('Andasibe', 'VADI2', 'ry-wc-city-select'),
		_x('Anjahambe', 'VADI2', 'ry-wc-city-select'),
		_x('Maromitety', 'VADI2', 'ry-wc-city-select'),
		_x('Miarinarivo', 'VADI2', 'ry-wc-city-select'),
		_x('Sahatavy', 'VADI2', 'ry-wc-city-select'),
		_x('Vavatenina', 'VADI2', 'ry-wc-city-select'),
	],
	'VO' => [
		_x('Ambalasatrana', 'VO', 'ry-wc-city-select'),
		_x('Ambinaninandravory', 'VO', 'ry-wc-city-select'),
		_x('Ambodisambalahy', 'VO', 'ry-wc-city-select'),
		_x('Amboriala', 'VO', 'ry-wc-city-select'),
		_x('Ampanefena', 'VO', 'ry-wc-city-select'),
		_x('Ampisikinana', 'VO', 'ry-wc-city-select'),
		_x('Ampondra', 'VO', 'ry-wc-city-select'),
		_x('Andrafainkona', 'VO', 'ry-wc-city-select'),
		_x('Andravory', 'VO', 'ry-wc-city-select'),
		_x('Antsirabe Nord', 'VO', 'ry-wc-city-select'),
		_x('Belambo', 'VO', 'ry-wc-city-select'),
		_x('Bobakindro', 'VO', 'ry-wc-city-select'),
		_x('Daraina', 'VO', 'ry-wc-city-select'),
		_x('Fanambana', 'VO', 'ry-wc-city-select'),
		_x('Maromokotra Loky', 'VO', 'ry-wc-city-select'),
		_x('Milanoa', 'VO', 'ry-wc-city-select'),
		_x('Nosibe', 'VO', 'ry-wc-city-select'),
		_x('Tsarabaria', 'VO', 'ry-wc-city-select'),
		_x('Vohemar', 'VO', 'ry-wc-city-select'),
	],
	'VO2' => [
		_x('Alakamisy Itenina', 'VO2', 'ry-wc-city-select'),
		_x('Andranomiditra', 'VO2', 'ry-wc-city-select'),
		_x('Andranovorivato', 'VO2', 'ry-wc-city-select'),
		_x('Ankaromalaza Mifanasoa', 'VO2', 'ry-wc-city-select'),
		_x('Ihazoara', 'VO2', 'ry-wc-city-select'),
		_x('Mahaditra', 'VO2', 'ry-wc-city-select'),
		_x('Mahasoabe', 'VO2', 'ry-wc-city-select'),
		_x('Maneva', 'VO2', 'ry-wc-city-select'),
		_x('Soaindrana', 'VO2', 'ry-wc-city-select'),
		_x('Talata Ampano', 'VO2', 'ry-wc-city-select'),
		_x('Vinanitelo', 'VO2', 'ry-wc-city-select'),
		_x('Vohibato Ouest', 'VO2', 'ry-wc-city-select'),
		_x('Vohimarina', 'VO2', 'ry-wc-city-select'),
		_x('Vohitrafeno', 'VO2', 'ry-wc-city-select'),
	],
	'VO3' => [
		_x('Andemaka', 'VO3', 'ry-wc-city-select'),
		_x('Ankarimbary', 'VO3', 'ry-wc-city-select'),
		_x('Anoloka', 'VO3', 'ry-wc-city-select'),
		_x('Antananabo', 'VO3', 'ry-wc-city-select'),
		_x('Ifatsy', 'VO3', 'ry-wc-city-select'),
		_x('Ilakatra', 'VO3', 'ry-wc-city-select'),
		_x('Ivato', 'VO3', 'ry-wc-city-select'),
		_x('Lanivo', 'VO3', 'ry-wc-city-select'),
		_x('Mahabo', 'VO3', 'ry-wc-city-select'),
		_x('Mahasoabe', 'VO3', 'ry-wc-city-select'),
		_x('Mahazoarivo', 'VO3', 'ry-wc-city-select'),
		_x('Nato', 'VO3', 'ry-wc-city-select'),
		_x('Onjatsy', 'VO3', 'ry-wc-city-select'),
		_x('Sahalava', 'VO3', 'ry-wc-city-select'),
		_x('Savana', 'VO3', 'ry-wc-city-select'),
		_x('Vohilany', 'VO3', 'ry-wc-city-select'),
		_x('Vohindava', 'VO3', 'ry-wc-city-select'),
		_x('Vohipeno', 'VO3', 'ry-wc-city-select'),
		_x('Vohitrindry', 'VO3', 'ry-wc-city-select'),
	],
	'VO4' => [
		_x('Ambohimana', 'VO4', 'ry-wc-city-select'),
		_x('Anandravy', 'VO4', 'ry-wc-city-select'),
		_x('Andakana', 'VO4', 'ry-wc-city-select'),
		_x('Antokonala', 'VO4', 'ry-wc-city-select'),
		_x('Iamonta', 'VO4', 'ry-wc-city-select'),
		_x('Ivato', 'VO4', 'ry-wc-city-select'),
		_x('Karianga', 'VO4', 'ry-wc-city-select'),
		_x('Mahatsinjo', 'VO4', 'ry-wc-city-select'),
		_x('Mahavelo', 'VO4', 'ry-wc-city-select'),
		_x('Mahazoarivo', 'VO4', 'ry-wc-city-select'),
		_x('Manambidala', 'VO4', 'ry-wc-city-select'),
		_x('Manato', 'VO4', 'ry-wc-city-select'),
		_x('Moroteza', 'VO4', 'ry-wc-city-select'),
		_x('Vohiboreka', 'VO4', 'ry-wc-city-select'),
		_x('Vohimary', 'VO4', 'ry-wc-city-select'),
		_x('Vondrozo', 'VO4', 'ry-wc-city-select'),
	],
	]
];