<?php
/**
 * Union of Burma places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MM' => [
	'BADI' => [
		_x('Bago', 'BADI', 'ry-wc-city-select'),
		_x('Daik-U', 'BADI', 'ry-wc-city-select'),
		_x('Kawa', 'BADI', 'ry-wc-city-select'),
		_x('Kyauktaga', 'BADI', 'ry-wc-city-select'),
		_x('Nyaunglebin', 'BADI', 'ry-wc-city-select'),
		_x('Shwegyin', 'BADI', 'ry-wc-city-select'),
		_x('Thanatpin', 'BADI', 'ry-wc-city-select'),
		_x('Waw', 'BADI', 'ry-wc-city-select'),
	],
	'BADI2' => [
		_x('Bawlakhe', 'BADI2', 'ry-wc-city-select'),
		_x('Hpasawng', 'BADI2', 'ry-wc-city-select'),
		_x('Mese', 'BADI2', 'ry-wc-city-select'),
	],
	'BHDI' => [
		_x('Bhamo', 'BHDI', 'ry-wc-city-select'),
		_x('Mansi', 'BHDI', 'ry-wc-city-select'),
		_x('Momauk', 'BHDI', 'ry-wc-city-select'),
		_x('Shwegu', 'BHDI', 'ry-wc-city-select'),
	],
	'DADI' => [
		_x('Dawei', 'DADI', 'ry-wc-city-select'),
		_x('Launglon', 'DADI', 'ry-wc-city-select'),
		_x('Thayetchaung', 'DADI', 'ry-wc-city-select'),
		_x('Yebyu', 'DADI', 'ry-wc-city-select'),
	],
	'FA' => [
		_x('Falam', 'FA', 'ry-wc-city-select'),
		_x('Tedim', 'FA', 'ry-wc-city-select'),
		_x('Tonzang', 'FA', 'ry-wc-city-select'),
	],
	'GADI' => [
		_x('Gangaw', 'GADI', 'ry-wc-city-select'),
		_x('Saw', 'GADI', 'ry-wc-city-select'),
		_x('Tilin', 'GADI', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Hakha', 'HA', 'ry-wc-city-select'),
		_x('Thantlang', 'HA', 'ry-wc-city-select'),
	],
	'HIDI' => [
		_x('Hinthada', 'HIDI', 'ry-wc-city-select'),
		_x('Ingapu', 'HIDI', 'ry-wc-city-select'),
		_x('Kyangin', 'HIDI', 'ry-wc-city-select'),
		_x('Lemyethna', 'HIDI', 'ry-wc-city-select'),
		_x('Myanaung', 'HIDI', 'ry-wc-city-select'),
		_x('Zalun', 'HIDI', 'ry-wc-city-select'),
	],
	'HKDI' => [
		_x('Hkamti', 'HKDI', 'ry-wc-city-select'),
		_x('Homalin', 'HKDI', 'ry-wc-city-select'),
		_x('Lahe', 'HKDI', 'ry-wc-city-select'),
		_x('Lay Shi', 'HKDI', 'ry-wc-city-select'),
		_x('Nanyun', 'HKDI', 'ry-wc-city-select'),
	],
	'HO' => [
		_x('Hopang', 'HO', 'ry-wc-city-select'),
		_x('Mongmao', 'HO', 'ry-wc-city-select'),
		_x('Pangwaun', 'HO', 'ry-wc-city-select'),
	],
	'HPDI' => [
		_x('Hlaingbwe Township', 'HPDI', 'ry-wc-city-select'),
		_x('Hpa-An', 'HPDI', 'ry-wc-city-select'),
		_x('Thandaunggyi', 'HPDI', 'ry-wc-city-select'),
	],
	'HP' => [
		_x('Hpapun', 'HP', 'ry-wc-city-select'),
	],
	'KADI' => [
		_x('Kale', 'KADI', 'ry-wc-city-select'),
		_x('Kalewa', 'KADI', 'ry-wc-city-select'),
		_x('Mingin', 'KADI', 'ry-wc-city-select'),
	],
	'KADI2' => [
		_x('Banmauk', 'KADI2', 'ry-wc-city-select'),
		_x('Indaw', 'KADI2', 'ry-wc-city-select'),
		_x('Katha', 'KADI2', 'ry-wc-city-select'),
		_x('Kawlin', 'KADI2', 'ry-wc-city-select'),
		_x('Pinlebu', 'KADI2', 'ry-wc-city-select'),
		_x('Tigyaing', 'KADI2', 'ry-wc-city-select'),
		_x('Wuntho', 'KADI2', 'ry-wc-city-select'),
	],
	'KADI3' => [
		_x('Kawkareik', 'KADI3', 'ry-wc-city-select'),
		_x('Kyain Seikgyi Township', 'KADI3', 'ry-wc-city-select'),
	],
	'KADI4' => [
		_x('Bokpyin', 'KADI4', 'ry-wc-city-select'),
		_x('Kawthoung', 'KADI4', 'ry-wc-city-select'),
		_x('Kyunsu', 'KADI4', 'ry-wc-city-select'),
	],
	'KEDI' => [
		_x('Kengtung', 'KEDI', 'ry-wc-city-select'),
		_x('Mongkhet', 'KEDI', 'ry-wc-city-select'),
		_x('Mongla', 'KEDI', 'ry-wc-city-select'),
		_x('Mongping', 'KEDI', 'ry-wc-city-select'),
		_x('Mongyang', 'KEDI', 'ry-wc-city-select'),
	],
	'KYDI' => [
		_x('Hsipaw', 'KYDI', 'ry-wc-city-select'),
		_x('Kyaukme', 'KYDI', 'ry-wc-city-select'),
		_x('Manton', 'KYDI', 'ry-wc-city-select'),
		_x('Namhsan', 'KYDI', 'ry-wc-city-select'),
		_x('Namtu', 'KYDI', 'ry-wc-city-select'),
		_x('Nawnghkio', 'KYDI', 'ry-wc-city-select'),
	],
	'KYDI2' => [
		_x('Kyaukse', 'KYDI2', 'ry-wc-city-select'),
		_x('Myittha', 'KYDI2', 'ry-wc-city-select'),
		_x('Sintgaing', 'KYDI2', 'ry-wc-city-select'),
		_x('Tada-U', 'KYDI2', 'ry-wc-city-select'),
	],
	'KYDI3' => [
		_x('Ann Township', 'KYDI3', 'ry-wc-city-select'),
		_x('Kyaukpyu Township', 'KYDI3', 'ry-wc-city-select'),
		_x('Munaung', 'KYDI3', 'ry-wc-city-select'),
		_x('Ramree', 'KYDI3', 'ry-wc-city-select'),
	],
	'LADI' => [
		_x('Labutta', 'LADI', 'ry-wc-city-select'),
		_x('Mawlamyinegyun', 'LADI', 'ry-wc-city-select'),
	],
	'LADI2' => [
		_x('Langkho', 'LADI2', 'ry-wc-city-select'),
		_x('Mawkmai', 'LADI2', 'ry-wc-city-select'),
		_x('Mongnai', 'LADI2', 'ry-wc-city-select'),
		_x('Mongpan', 'LADI2', 'ry-wc-city-select'),
	],
	'LADI3' => [
		_x('Hseni', 'LADI3', 'ry-wc-city-select'),
		_x('Kunlong', 'LADI3', 'ry-wc-city-select'),
		_x('Lashio', 'LADI3', 'ry-wc-city-select'),
		_x('Mongyai', 'LADI3', 'ry-wc-city-select'),
		_x('Tangyan', 'LADI3', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Konkyan', 'LA', 'ry-wc-city-select'),
		_x('Laukkaing', 'LA', 'ry-wc-city-select'),
	],
	'LODI' => [
		_x('Demoso', 'LODI', 'ry-wc-city-select'),
		_x('Hpruso', 'LODI', 'ry-wc-city-select'),
		_x('Loikaw', 'LODI', 'ry-wc-city-select'),
		_x('Shadaw', 'LODI', 'ry-wc-city-select'),
	],
	'LODI2' => [
		_x('Kunhing', 'LODI2', 'ry-wc-city-select'),
		_x('Kyethi', 'LODI2', 'ry-wc-city-select'),
		_x('Laihka', 'LODI2', 'ry-wc-city-select'),
		_x('Loilen', 'LODI2', 'ry-wc-city-select'),
		_x('Monghsu', 'LODI2', 'ry-wc-city-select'),
		_x('Mongkaing', 'LODI2', 'ry-wc-city-select'),
		_x('Nansang', 'LODI2', 'ry-wc-city-select'),
	],
	'MADI' => [
		_x('Danubyu', 'MADI', 'ry-wc-city-select'),
		_x('Maubin', 'MADI', 'ry-wc-city-select'),
		_x('Nyaungdon', 'MADI', 'ry-wc-city-select'),
		_x('Pantanaw', 'MADI', 'ry-wc-city-select'),
	],
	'MADI2' => [
		_x('Chauk', 'MADI2', 'ry-wc-city-select'),
		_x('Magway', 'MADI2', 'ry-wc-city-select'),
		_x('Myothit', 'MADI2', 'ry-wc-city-select'),
		_x('Natmauk', 'MADI2', 'ry-wc-city-select'),
		_x('Taungdwingyi', 'MADI2', 'ry-wc-city-select'),
		_x('Yenangyaung', 'MADI2', 'ry-wc-city-select'),
	],
	'MADI3' => [
		_x('Amarapura', 'MADI3', 'ry-wc-city-select'),
		_x('Aungmyaythazan', 'MADI3', 'ry-wc-city-select'),
		_x('Chanayethazan', 'MADI3', 'ry-wc-city-select'),
		_x('Chanmyathazi', 'MADI3', 'ry-wc-city-select'),
		_x('Mahaaungmyay', 'MADI3', 'ry-wc-city-select'),
		_x('Patheingyi', 'MADI3', 'ry-wc-city-select'),
		_x('Pyigyitagon', 'MADI3', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Matman', 'MA', 'ry-wc-city-select'),
		_x('Narphan', 'MA', 'ry-wc-city-select'),
		_x('Pangsang', 'MA', 'ry-wc-city-select'),
	],
	'MADI4' => [
		_x('Buthidaung Township', 'MADI4', 'ry-wc-city-select'),
		_x('Maungdaw', 'MADI4', 'ry-wc-city-select'),
	],
	'MADI5' => [
		_x('Mawlaik', 'MADI5', 'ry-wc-city-select'),
		_x('Paungbyin', 'MADI5', 'ry-wc-city-select'),
	],
	'MADI6' => [
		_x('Chaungzon', 'MADI6', 'ry-wc-city-select'),
		_x('Kyaikmaraw', 'MADI6', 'ry-wc-city-select'),
		_x('Mawlamyine', 'MADI6', 'ry-wc-city-select'),
		_x('Mudon', 'MADI6', 'ry-wc-city-select'),
		_x('Thanbyuzayat', 'MADI6', 'ry-wc-city-select'),
		_x('Ye', 'MADI6', 'ry-wc-city-select'),
	],
	'MEDI' => [
		_x('Mahlaing', 'MEDI', 'ry-wc-city-select'),
		_x('Meiktila', 'MEDI', 'ry-wc-city-select'),
		_x('Thazi', 'MEDI', 'ry-wc-city-select'),
		_x('Wundwin', 'MEDI', 'ry-wc-city-select'),
	],
	'MIDI' => [
		_x('Minbu', 'MIDI', 'ry-wc-city-select'),
		_x('Ngape', 'MIDI', 'ry-wc-city-select'),
		_x('Pwintbyu', 'MIDI', 'ry-wc-city-select'),
		_x('Salin', 'MIDI', 'ry-wc-city-select'),
		_x('Sidoktaya', 'MIDI', 'ry-wc-city-select'),
	],
	'MI' => [
		_x('Kanpetlet', 'MI', 'ry-wc-city-select'),
		_x('Matupi', 'MI', 'ry-wc-city-select'),
		_x('Mindat', 'MI', 'ry-wc-city-select'),
		_x('Paletwa', 'MI', 'ry-wc-city-select'),
	],
	'MODI' => [
		_x('Hpakant', 'MODI', 'ry-wc-city-select'),
		_x('Mogaung', 'MODI', 'ry-wc-city-select'),
		_x('Mohnyin', 'MODI', 'ry-wc-city-select'),
	],
	'MOHSDI' => [
		_x('Monghsat', 'MOHSDI', 'ry-wc-city-select'),
		_x('Mongton', 'MOHSDI', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Mabein', 'MO', 'ry-wc-city-select'),
		_x('Mongmit', 'MO', 'ry-wc-city-select'),
	],
	'MO2' => [
		_x('Ayadaw', 'MO2', 'ry-wc-city-select'),
		_x('Budalin', 'MO2', 'ry-wc-city-select'),
		_x('Chaung-U', 'MO2', 'ry-wc-city-select'),
		_x('Monywa', 'MO2', 'ry-wc-city-select'),
	],
	'MR' => [
		_x('Kyauktaw Township', 'MR', 'ry-wc-city-select'),
		_x('Minbya', 'MR', 'ry-wc-city-select'),
		_x('Mrauk-U', 'MR', 'ry-wc-city-select'),
		_x('Myebon', 'MR', 'ry-wc-city-select'),
	],
	'DI' => [
		_x('Kutkai', 'DI', 'ry-wc-city-select'),
		_x('Muse', 'DI', 'ry-wc-city-select'),
		_x('Namhkan', 'DI', 'ry-wc-city-select'),
	],
	'MYDI' => [
		_x('Einme', 'MYDI', 'ry-wc-city-select'),
		_x('Myaungmya', 'MYDI', 'ry-wc-city-select'),
		_x('Wakema', 'MYDI', 'ry-wc-city-select'),
	],
	'MYDI2' => [
		_x('Myawaddy', 'MYDI2', 'ry-wc-city-select'),
	],
	'MYDI3' => [
		_x('Myeik', 'MYDI3', 'ry-wc-city-select'),
		_x('Palaw', 'MYDI3', 'ry-wc-city-select'),
		_x('Tanintharyi', 'MYDI3', 'ry-wc-city-select'),
	],
	'MYDI4' => [
		_x('Myingyan', 'MYDI4', 'ry-wc-city-select'),
		_x('Natogyi', 'MYDI4', 'ry-wc-city-select'),
		_x('Ngazun', 'MYDI4', 'ry-wc-city-select'),
		_x('Taungtha', 'MYDI4', 'ry-wc-city-select'),
	],
	'MYDI5' => [
		_x('Chipwi', 'MYDI5', 'ry-wc-city-select'),
		_x('Injangyang', 'MYDI5', 'ry-wc-city-select'),
		_x('Myitkyina', 'MYDI5', 'ry-wc-city-select'),
		_x('Tanai', 'MYDI5', 'ry-wc-city-select'),
		_x('Tsawlaw', 'MYDI5', 'ry-wc-city-select'),
		_x('Waingmaw', 'MYDI5', 'ry-wc-city-select'),
	],
	'NAPYTA(N' => [
		_x('Ottara Thiri', 'NAPYTA(N', 'ry-wc-city-select'),
		_x('Pobba Thiri', 'NAPYTA(N', 'ry-wc-city-select'),
		_x('Tatkon', 'NAPYTA(N', 'ry-wc-city-select'),
		_x('Zay Yar Thi Ri', 'NAPYTA(N', 'ry-wc-city-select'),
	],
	'NAPYTA(S' => [
		_x('Dekkhina Thiri', 'NAPYTA(S', 'ry-wc-city-select'),
		_x('Lewe', 'NAPYTA(S', 'ry-wc-city-select'),
		_x('Pyinmana', 'NAPYTA(S', 'ry-wc-city-select'),
		_x('Zabu Thiri', 'NAPYTA(S', 'ry-wc-city-select'),
	],
	'NYDI' => [
		_x('Kyaukpadaung', 'NYDI', 'ry-wc-city-select'),
		_x('Nyaung-U', 'NYDI', 'ry-wc-city-select'),
	],
	'PADI' => [
		_x('Myaing', 'PADI', 'ry-wc-city-select'),
		_x('Pakokku', 'PADI', 'ry-wc-city-select'),
		_x('Pauk', 'PADI', 'ry-wc-city-select'),
		_x('Seikphyu', 'PADI', 'ry-wc-city-select'),
		_x('Yesagyo', 'PADI', 'ry-wc-city-select'),
	],
	'PADI2' => [
		_x('Kangyidaunt', 'PADI2', 'ry-wc-city-select'),
		_x('Kyaunggon', 'PADI2', 'ry-wc-city-select'),
		_x('Kyonpyaw', 'PADI2', 'ry-wc-city-select'),
		_x('Ngapudaw', 'PADI2', 'ry-wc-city-select'),
		_x('Pathein', 'PADI2', 'ry-wc-city-select'),
		_x('Thabaung', 'PADI2', 'ry-wc-city-select'),
		_x('Yegyi', 'PADI2', 'ry-wc-city-select'),
	],
	'PUDI' => [
		_x('Khaunglanhpu', 'PUDI', 'ry-wc-city-select'),
		_x('Machanbaw', 'PUDI', 'ry-wc-city-select'),
		_x('Nawngmun', 'PUDI', 'ry-wc-city-select'),
		_x('Puta-O', 'PUDI', 'ry-wc-city-select'),
		_x('Sumprabum', 'PUDI', 'ry-wc-city-select'),
	],
	'PYDI' => [
		_x('Bogale', 'PYDI', 'ry-wc-city-select'),
		_x('Dedaye', 'PYDI', 'ry-wc-city-select'),
		_x('Kyaiklat', 'PYDI', 'ry-wc-city-select'),
		_x('Pyapon', 'PYDI', 'ry-wc-city-select'),
	],
	'PYDI2' => [
		_x('Padaung', 'PYDI2', 'ry-wc-city-select'),
		_x('Paukkhaung', 'PYDI2', 'ry-wc-city-select'),
		_x('Paungde', 'PYDI2', 'ry-wc-city-select'),
		_x('Pyay', 'PYDI2', 'ry-wc-city-select'),
		_x('Shwedaung', 'PYDI2', 'ry-wc-city-select'),
		_x('Thegon', 'PYDI2', 'ry-wc-city-select'),
	],
	'PYLWDI' => [
		_x('Madaya', 'PYLWDI', 'ry-wc-city-select'),
		_x('Mogoke', 'PYLWDI', 'ry-wc-city-select'),
		_x('Pyinoolwin', 'PYLWDI', 'ry-wc-city-select'),
		_x('Singu', 'PYLWDI', 'ry-wc-city-select'),
		_x('Thabeikkyin', 'PYLWDI', 'ry-wc-city-select'),
	],
	'SADI' => [
		_x('Myaung', 'SADI', 'ry-wc-city-select'),
		_x('Myinmu', 'SADI', 'ry-wc-city-select'),
		_x('Sagaing', 'SADI', 'ry-wc-city-select'),
	],
	'SHDI' => [
		_x('Kanbalu', 'SHDI', 'ry-wc-city-select'),
		_x('Khin-U', 'SHDI', 'ry-wc-city-select'),
		_x('Kyunhla', 'SHDI', 'ry-wc-city-select'),
		_x('Shwebo', 'SHDI', 'ry-wc-city-select'),
		_x('Tabayin', 'SHDI', 'ry-wc-city-select'),
		_x('Taze', 'SHDI', 'ry-wc-city-select'),
		_x('Wetlet', 'SHDI', 'ry-wc-city-select'),
		_x('Ye-U', 'SHDI', 'ry-wc-city-select'),
	],
	'SIDI' => [
		_x('Pauktaw', 'SIDI', 'ry-wc-city-select'),
		_x('Ponnagyun', 'SIDI', 'ry-wc-city-select'),
		_x('Rathedaung', 'SIDI', 'ry-wc-city-select'),
		_x('Sittwe', 'SIDI', 'ry-wc-city-select'),
	],
	'TADI' => [
		_x('Monghpyak', 'TADI', 'ry-wc-city-select'),
		_x('Mongyawng', 'TADI', 'ry-wc-city-select'),
		_x('Tachileik', 'TADI', 'ry-wc-city-select'),
	],
	'TADI2' => [
		_x('Tamu', 'TADI2', 'ry-wc-city-select'),
	],
	'TADI3' => [
		_x('Hopong', 'TADI3', 'ry-wc-city-select'),
		_x('Hsihseng', 'TADI3', 'ry-wc-city-select'),
		_x('Kalaw', 'TADI3', 'ry-wc-city-select'),
		_x('Lawksawk', 'TADI3', 'ry-wc-city-select'),
		_x('Nyaungshwe', 'TADI3', 'ry-wc-city-select'),
		_x('Pekon', 'TADI3', 'ry-wc-city-select'),
		_x('Pindaya', 'TADI3', 'ry-wc-city-select'),
		_x('Pinlaung', 'TADI3', 'ry-wc-city-select'),
		_x('Taunggyi', 'TADI3', 'ry-wc-city-select'),
		_x('Ywangan', 'TADI3', 'ry-wc-city-select'),
	],
	'TADI4' => [
		_x('Htantabin', 'TADI4', 'ry-wc-city-select'),
		_x('Kyaukkyi', 'TADI4', 'ry-wc-city-select'),
		_x('Oktwin', 'TADI4', 'ry-wc-city-select'),
		_x('Phyu', 'TADI4', 'ry-wc-city-select'),
		_x('Taungoo', 'TADI4', 'ry-wc-city-select'),
		_x('Yedashe', 'TADI4', 'ry-wc-city-select'),
	],
	'THDI' => [
		_x('Gwa Twonship', 'THDI', 'ry-wc-city-select'),
		_x('Thandwe', 'THDI', 'ry-wc-city-select'),
		_x('Toungup', 'THDI', 'ry-wc-city-select'),
	],
	'THDI2' => [
		_x('Bilin', 'THDI2', 'ry-wc-city-select'),
		_x('Kyaikto', 'THDI2', 'ry-wc-city-select'),
		_x('Paung', 'THDI2', 'ry-wc-city-select'),
		_x('Thaton', 'THDI2', 'ry-wc-city-select'),
	],
	'THDI3' => [
		_x('Gyobingauk', 'THDI3', 'ry-wc-city-select'),
		_x('Letpadan', 'THDI3', 'ry-wc-city-select'),
		_x('Minhla', 'THDI3', 'ry-wc-city-select'),
		_x('Monyo', 'THDI3', 'ry-wc-city-select'),
		_x('Nattalin', 'THDI3', 'ry-wc-city-select'),
		_x('Okpho', 'THDI3', 'ry-wc-city-select'),
		_x('Thayarwady', 'THDI3', 'ry-wc-city-select'),
		_x('Zigon', 'THDI3', 'ry-wc-city-select'),
	],
	'THDI4' => [
		_x('Aunglan', 'THDI4', 'ry-wc-city-select'),
		_x('Kamma', 'THDI4', 'ry-wc-city-select'),
		_x('Mindon', 'THDI4', 'ry-wc-city-select'),
		_x('Minhla', 'THDI4', 'ry-wc-city-select'),
		_x('Sinbaungwe', 'THDI4', 'ry-wc-city-select'),
		_x('Thayet', 'THDI4', 'ry-wc-city-select'),
	],
	'YADI' => [
		_x('Pyawbwe', 'YADI', 'ry-wc-city-select'),
		_x('Yamethin', 'YADI', 'ry-wc-city-select'),
	],
	'YA(E' => [
		_x('Botahtaung', 'YA(E', 'ry-wc-city-select'),
		_x('Dagon Myothit (East)', 'YA(E', 'ry-wc-city-select'),
		_x('Dagon Myothit (North)', 'YA(E', 'ry-wc-city-select'),
		_x('Dagon Myothit (Seikkan)', 'YA(E', 'ry-wc-city-select'),
		_x('Dagon Myothit (South)', 'YA(E', 'ry-wc-city-select'),
		_x('Dawbon', 'YA(E', 'ry-wc-city-select'),
		_x('Mingalartaungnyunt', 'YA(E', 'ry-wc-city-select'),
		_x('North Okkalapa', 'YA(E', 'ry-wc-city-select'),
		_x('Pazundaung', 'YA(E', 'ry-wc-city-select'),
		_x('South Okkalapa', 'YA(E', 'ry-wc-city-select'),
		_x('Tamwe', 'YA(E', 'ry-wc-city-select'),
		_x('Thaketa', 'YA(E', 'ry-wc-city-select'),
		_x('Thingangyun', 'YA(E', 'ry-wc-city-select'),
		_x('Yankin Township', 'YA(E', 'ry-wc-city-select'),
	],
	'YA(N' => [
		_x('Hlaingtharya', 'YA(N', 'ry-wc-city-select'),
		_x('Hlegu', 'YA(N', 'ry-wc-city-select'),
		_x('Hmawbi', 'YA(N', 'ry-wc-city-select'),
		_x('Htantabin', 'YA(N', 'ry-wc-city-select'),
		_x('Insein', 'YA(N', 'ry-wc-city-select'),
		_x('Mingaladon', 'YA(N', 'ry-wc-city-select'),
		_x('Shwepyithar', 'YA(N', 'ry-wc-city-select'),
		_x('Taikkyi', 'YA(N', 'ry-wc-city-select'),
	],
	'YAEADI' => [
		_x('Ahlone', 'YAEADI', 'ry-wc-city-select'),
		_x('Bahan', 'YAEADI', 'ry-wc-city-select'),
		_x('Dagon', 'YAEADI', 'ry-wc-city-select'),
		_x('Hlaing', 'YAEADI', 'ry-wc-city-select'),
		_x('Kamaryut', 'YAEADI', 'ry-wc-city-select'),
		_x('Kyauktada', 'YAEADI', 'ry-wc-city-select'),
		_x('Kyeemyindaing', 'YAEADI', 'ry-wc-city-select'),
		_x('Lanmadaw', 'YAEADI', 'ry-wc-city-select'),
		_x('Latha', 'YAEADI', 'ry-wc-city-select'),
		_x('Mayangone', 'YAEADI', 'ry-wc-city-select'),
		_x('Pabedan Township', 'YAEADI', 'ry-wc-city-select'),
		_x('Sanchaung', 'YAEADI', 'ry-wc-city-select'),
		_x('Seikkan', 'YAEADI', 'ry-wc-city-select'),
	],
	'YASODI' => [
		_x('Cocokyun', 'YASODI', 'ry-wc-city-select'),
		_x('Dala', 'YASODI', 'ry-wc-city-select'),
		_x('Kawhmu', 'YASODI', 'ry-wc-city-select'),
		_x('Kayan', 'YASODI', 'ry-wc-city-select'),
		_x('Kungyangon', 'YASODI', 'ry-wc-city-select'),
		_x('Kyauktan', 'YASODI', 'ry-wc-city-select'),
		_x('Seikgyikanaungto', 'YASODI', 'ry-wc-city-select'),
		_x('Thanlyin', 'YASODI', 'ry-wc-city-select'),
		_x('Thongwa', 'YASODI', 'ry-wc-city-select'),
		_x('Twantay', 'YASODI', 'ry-wc-city-select'),
	],
	'YI' => [
		_x('Kani', 'YI', 'ry-wc-city-select'),
		_x('Pale', 'YI', 'ry-wc-city-select'),
		_x('Salingyi', 'YI', 'ry-wc-city-select'),
		_x('Yinmabin', 'YI', 'ry-wc-city-select'),
	],
	]
];