<?php
/**
 * Mongolia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MN' => [
	'ARAY' => [
		_x('Battsengel', 'ARAY', 'ry-wc-city-select'),
		_x('Bulgan', 'ARAY', 'ry-wc-city-select'),
		_x('Bulgan Sum', 'ARAY', 'ry-wc-city-select'),
		_x('Chuluut', 'ARAY', 'ry-wc-city-select'),
		_x('Erdenebulgan', 'ARAY', 'ry-wc-city-select'),
		_x('Erdenebulgan Sum', 'ARAY', 'ry-wc-city-select'),
		_x('Erdenemandal', 'ARAY', 'ry-wc-city-select'),
		_x('Hangay', 'ARAY', 'ry-wc-city-select'),
		_x('Hashaat', 'ARAY', 'ry-wc-city-select'),
		_x('Hayrhan', 'ARAY', 'ry-wc-city-select'),
		_x('Hotont', 'ARAY', 'ry-wc-city-select'),
		_x('Ihtamir', 'ARAY', 'ry-wc-city-select'),
		_x('Jargalant', 'ARAY', 'ry-wc-city-select'),
		_x('Khairkhan', 'ARAY', 'ry-wc-city-select'),
		_x('OEgiynuur', 'ARAY', 'ry-wc-city-select'),
		_x('OEldziyt', 'ARAY', 'ry-wc-city-select'),
		_x('OEndoer-Ulaan', 'ARAY', 'ry-wc-city-select'),
		_x('Rashaant', 'ARAY', 'ry-wc-city-select'),
		_x('Tariat Sum', 'ARAY', 'ry-wc-city-select'),
		_x('Tsahir', 'ARAY', 'ry-wc-city-select'),
		_x('Tsenher', 'ARAY', 'ry-wc-city-select'),
		_x('Tsetserleg', 'ARAY', 'ry-wc-city-select'),
		_x('Tuevshrueueleh', 'ARAY', 'ry-wc-city-select'),
	],
	'BAAY' => [
		_x('Altantsoegts', 'BAAY', 'ry-wc-city-select'),
		_x('Altay', 'BAAY', 'ry-wc-city-select'),
		_x('Bayannuur', 'BAAY', 'ry-wc-city-select'),
		_x('Bugat', 'BAAY', 'ry-wc-city-select'),
		_x('Bulgan', 'BAAY', 'ry-wc-city-select'),
		_x('Buyant', 'BAAY', 'ry-wc-city-select'),
		_x('Delueuen', 'BAAY', 'ry-wc-city-select'),
		_x('Nogoonnuur', 'BAAY', 'ry-wc-city-select'),
		_x('OElgii', 'BAAY', 'ry-wc-city-select'),
		_x('Olgiy Sum', 'BAAY', 'ry-wc-city-select'),
		_x('Sagsay sum', 'BAAY', 'ry-wc-city-select'),
		_x('Tolbo', 'BAAY', 'ry-wc-city-select'),
		_x('Tsagaannuur', 'BAAY', 'ry-wc-city-select'),
		_x('Tsengel', 'BAAY', 'ry-wc-city-select'),
		_x('Ulaanhus', 'BAAY', 'ry-wc-city-select'),
	],
	'BAAY2' => [
		_x('Baatsagaan', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayan-OEndoer', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayan-Ovoo', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayanbulag', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayanbulag Sum', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayangovi', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayanhongor', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayanhongor Sum', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayanlig', 'BAAY2', 'ry-wc-city-select'),
		_x('Bayantsagaan', 'BAAY2', 'ry-wc-city-select'),
		_x('Boemboegoer', 'BAAY2', 'ry-wc-city-select'),
		_x('Bogd', 'BAAY2', 'ry-wc-city-select'),
		_x('Buutsagaan', 'BAAY2', 'ry-wc-city-select'),
		_x('Dzag', 'BAAY2', 'ry-wc-city-select'),
		_x('Erdenetsogt', 'BAAY2', 'ry-wc-city-select'),
		_x('Erdenetsogt Sum', 'BAAY2', 'ry-wc-city-select'),
		_x('Galuut', 'BAAY2', 'ry-wc-city-select'),
		_x('Gurvanbulag', 'BAAY2', 'ry-wc-city-select'),
		_x('Huereemaral', 'BAAY2', 'ry-wc-city-select'),
		_x('Jargalant', 'BAAY2', 'ry-wc-city-select'),
		_x('Jinst', 'BAAY2', 'ry-wc-city-select'),
		_x('OEldziyt', 'BAAY2', 'ry-wc-city-select'),
		_x('Olziit', 'BAAY2', 'ry-wc-city-select'),
		_x('Shinejinst', 'BAAY2', 'ry-wc-city-select'),
	],
	'BU' => [
		_x('Bayan-Agt', 'BU', 'ry-wc-city-select'),
		_x('Bayannuur', 'BU', 'ry-wc-city-select'),
		_x('Bayannuur Sum', 'BU', 'ry-wc-city-select'),
		_x('Buereghangay', 'BU', 'ry-wc-city-select'),
		_x('Bugat', 'BU', 'ry-wc-city-select'),
		_x('Bulgan District', 'BU', 'ry-wc-city-select'),
		_x('Bureghangay Sum', 'BU', 'ry-wc-city-select'),
		_x('Dashinchilen', 'BU', 'ry-wc-city-select'),
		_x('Dashinchilen Sum', 'BU', 'ry-wc-city-select'),
		_x('Gurvanbulag', 'BU', 'ry-wc-city-select'),
		_x('Gurvanbulag Sum', 'BU', 'ry-wc-city-select'),
		_x('Hangal', 'BU', 'ry-wc-city-select'),
		_x('Hishig-OEndoer', 'BU', 'ry-wc-city-select'),
		_x('Hutag-OEndoer', 'BU', 'ry-wc-city-select'),
		_x('Hutag-Ondor Sum', 'BU', 'ry-wc-city-select'),
		_x('Mogod', 'BU', 'ry-wc-city-select'),
		_x('Orhon', 'BU', 'ry-wc-city-select'),
		_x('Orhon Sum', 'BU', 'ry-wc-city-select'),
		_x('Rashaant Sum', 'BU', 'ry-wc-city-select'),
		_x('Sayhan', 'BU', 'ry-wc-city-select'),
		_x('Selenge', 'BU', 'ry-wc-city-select'),
		_x('Teshig', 'BU', 'ry-wc-city-select'),
	],
	'DAAY' => [
		_x('Hongor', 'DAAY', 'ry-wc-city-select'),
		_x('Orhon', 'DAAY', 'ry-wc-city-select'),
		_x('Sharingol', 'DAAY', 'ry-wc-city-select'),
	],
	'DOAY' => [
		_x('Bayan-Uul', 'DOAY', 'ry-wc-city-select'),
		_x('Bayandun', 'DOAY', 'ry-wc-city-select'),
		_x('Bayantuemen', 'DOAY', 'ry-wc-city-select'),
		_x('Bayantumen Sum', 'DOAY', 'ry-wc-city-select'),
		_x('Bulgan', 'DOAY', 'ry-wc-city-select'),
		_x('Choybalsan', 'DOAY', 'ry-wc-city-select'),
		_x('Choybalsan Sum', 'DOAY', 'ry-wc-city-select'),
		_x('Chuluunhoroot', 'DOAY', 'ry-wc-city-select'),
		_x('Dashbalbar', 'DOAY', 'ry-wc-city-select'),
		_x('Gurvandzagal', 'DOAY', 'ry-wc-city-select'),
		_x('Gurvanzagal Sum', 'DOAY', 'ry-wc-city-select'),
		_x('Halhgol', 'DOAY', 'ry-wc-city-select'),
		_x('Herlen', 'DOAY', 'ry-wc-city-select'),
		_x('Hoeloenbuyr', 'DOAY', 'ry-wc-city-select'),
		_x('Kherlen', 'DOAY', 'ry-wc-city-select'),
		_x('Khoeloenbuir', 'DOAY', 'ry-wc-city-select'),
		_x('Matad', 'DOAY', 'ry-wc-city-select'),
		_x('Sergelen', 'DOAY', 'ry-wc-city-select'),
		_x('Tsagaan-Ovoo', 'DOAY', 'ry-wc-city-select'),
		_x('Tsagaan-Ovoo Sum', 'DOAY', 'ry-wc-city-select'),
	],
	'DOAY2' => [
		_x('Altanshiree', 'DOAY2', 'ry-wc-city-select'),
		_x('Ayrag', 'DOAY2', 'ry-wc-city-select'),
		_x('Dalanjargalan', 'DOAY2', 'ry-wc-city-select'),
		_x('Delgereh', 'DOAY2', 'ry-wc-city-select'),
		_x('Dzamin-Uud Sum', 'DOAY2', 'ry-wc-city-select'),
		_x('Dzamyn UEued', 'DOAY2', 'ry-wc-city-select'),
		_x('Erdene', 'DOAY2', 'ry-wc-city-select'),
		_x('Hatanbulag', 'DOAY2', 'ry-wc-city-select'),
		_x('Hoevsgoel', 'DOAY2', 'ry-wc-city-select'),
		_x('Ihhet', 'DOAY2', 'ry-wc-city-select'),
		_x('Mandah', 'DOAY2', 'ry-wc-city-select'),
		_x('OErgoen', 'DOAY2', 'ry-wc-city-select'),
		_x('Sainshand', 'DOAY2', 'ry-wc-city-select'),
		_x('Sayhandulaan', 'DOAY2', 'ry-wc-city-select'),
		_x('Saynshand', 'DOAY2', 'ry-wc-city-select'),
		_x('Saynshand Sum', 'DOAY2', 'ry-wc-city-select'),
		_x('Shiveegovi', 'DOAY2', 'ry-wc-city-select'),
		_x('Ulaanbadrah', 'DOAY2', 'ry-wc-city-select'),
	],
	'DUAY' => [
		_x('Adaatsag', 'DUAY', 'ry-wc-city-select'),
		_x('Bayanjargalan', 'DUAY', 'ry-wc-city-select'),
		_x('Delgerhangay', 'DUAY', 'ry-wc-city-select'),
		_x('Delgertsogt', 'DUAY', 'ry-wc-city-select'),
		_x('Deren', 'DUAY', 'ry-wc-city-select'),
		_x('Erdenedalay', 'DUAY', 'ry-wc-city-select'),
		_x('Govi-Ugtaal', 'DUAY', 'ry-wc-city-select'),
		_x('Gurvansayhan', 'DUAY', 'ry-wc-city-select'),
		_x('Huld', 'DUAY', 'ry-wc-city-select'),
		_x('Luus', 'DUAY', 'ry-wc-city-select'),
		_x('OEldziyt', 'DUAY', 'ry-wc-city-select'),
		_x('OEndoershil', 'DUAY', 'ry-wc-city-select'),
		_x('Oldziyt Sum', 'DUAY', 'ry-wc-city-select'),
		_x('Saintsagaan', 'DUAY', 'ry-wc-city-select'),
		_x('Sayhan-Ovoo', 'DUAY', 'ry-wc-city-select'),
		_x('Sayntsagaan Sum', 'DUAY', 'ry-wc-city-select'),
		_x('Suember', 'DUAY', 'ry-wc-city-select'),
		_x('Tsagaandelger', 'DUAY', 'ry-wc-city-select'),
	],
	'DZAY' => [
		_x('Aldarhaan', 'DZAY', 'ry-wc-city-select'),
		_x('Asgat', 'DZAY', 'ry-wc-city-select'),
		_x('Asgat Sum', 'DZAY', 'ry-wc-city-select'),
		_x('Bayanhayrhan', 'DZAY', 'ry-wc-city-select'),
		_x('Bayantes', 'DZAY', 'ry-wc-city-select'),
		_x('Dorvoljin Sum', 'DZAY', 'ry-wc-city-select'),
		_x('Dzavhanmandal', 'DZAY', 'ry-wc-city-select'),
		_x('Erdenehayrhan', 'DZAY', 'ry-wc-city-select'),
		_x('Ider', 'DZAY', 'ry-wc-city-select'),
		_x('Ih-Uul', 'DZAY', 'ry-wc-city-select'),
		_x('Noemroeg', 'DZAY', 'ry-wc-city-select'),
		_x('Otgon', 'DZAY', 'ry-wc-city-select'),
		_x('Santmargats', 'DZAY', 'ry-wc-city-select'),
		_x('Shilueuestey', 'DZAY', 'ry-wc-city-select'),
		_x('Songino', 'DZAY', 'ry-wc-city-select'),
		_x('Telmen', 'DZAY', 'ry-wc-city-select'),
		_x('Tes', 'DZAY', 'ry-wc-city-select'),
		_x('Tes Sum', 'DZAY', 'ry-wc-city-select'),
		_x('Tosontsengel', 'DZAY', 'ry-wc-city-select'),
		_x('Tsagaanchuluut', 'DZAY', 'ry-wc-city-select'),
		_x('Tsagaanhayrhan', 'DZAY', 'ry-wc-city-select'),
		_x('Tsetsen-Uul', 'DZAY', 'ry-wc-city-select'),
		_x('Tuedevtey', 'DZAY', 'ry-wc-city-select'),
		_x('Uliastay', 'DZAY', 'ry-wc-city-select'),
		_x('Urgamal', 'DZAY', 'ry-wc-city-select'),
		_x('Yaruu', 'DZAY', 'ry-wc-city-select'),
	],
	'GOAY' => [
		_x('Altay', 'GOAY', 'ry-wc-city-select'),
		_x('Bayan-Uul', 'GOAY', 'ry-wc-city-select'),
		_x('Biger', 'GOAY', 'ry-wc-city-select'),
		_x('Bugat', 'GOAY', 'ry-wc-city-select'),
		_x('Chandmani', 'GOAY', 'ry-wc-city-select'),
		_x('Darvi', 'GOAY', 'ry-wc-city-select'),
		_x('Delger', 'GOAY', 'ry-wc-city-select'),
		_x('Doervoeljin', 'GOAY', 'ry-wc-city-select'),
		_x('Erdene', 'GOAY', 'ry-wc-city-select'),
		_x('Haliun', 'GOAY', 'ry-wc-city-select'),
		_x('Hoehmorit', 'GOAY', 'ry-wc-city-select'),
		_x('Jargalan', 'GOAY', 'ry-wc-city-select'),
		_x('Sharga', 'GOAY', 'ry-wc-city-select'),
		_x('Tayshir', 'GOAY', 'ry-wc-city-select'),
		_x('Toegroeg', 'GOAY', 'ry-wc-city-select'),
		_x('Tonhil', 'GOAY', 'ry-wc-city-select'),
		_x('Tseel', 'GOAY', 'ry-wc-city-select'),
		_x('Tsogt', 'GOAY', 'ry-wc-city-select'),
		_x('Yesoenbulag', 'GOAY', 'ry-wc-city-select'),
		_x('Yoesoenbulag', 'GOAY', 'ry-wc-city-select'),
	],
	'GO' => [
		_x('Bayantal Sum', 'GO', 'ry-wc-city-select'),
		_x('Shiveegovi Sum', 'GO', 'ry-wc-city-select'),
		_x('Sumber Sum', 'GO', 'ry-wc-city-select'),
	],
	'HEAY' => [
		_x('Batnorov', 'HEAY', 'ry-wc-city-select'),
		_x('Batshireet', 'HEAY', 'ry-wc-city-select'),
		_x('Bayan-Adarga', 'HEAY', 'ry-wc-city-select'),
		_x('Bayan-Ovoo', 'HEAY', 'ry-wc-city-select'),
		_x('Bayanhutag', 'HEAY', 'ry-wc-city-select'),
		_x('Bayanmoenh', 'HEAY', 'ry-wc-city-select'),
		_x('Binder', 'HEAY', 'ry-wc-city-select'),
		_x('Bor-Ondor Sum', 'HEAY', 'ry-wc-city-select'),
		_x('Dadal', 'HEAY', 'ry-wc-city-select'),
		_x('Darhan', 'HEAY', 'ry-wc-city-select'),
		_x('Darhan Sum', 'HEAY', 'ry-wc-city-select'),
		_x('Delgerhaan', 'HEAY', 'ry-wc-city-select'),
		_x('Galshar', 'HEAY', 'ry-wc-city-select'),
		_x('Herlen', 'HEAY', 'ry-wc-city-select'),
		_x('Jargalthaan', 'HEAY', 'ry-wc-city-select'),
		_x('Moeroen', 'HEAY', 'ry-wc-city-select'),
		_x('Norovlin', 'HEAY', 'ry-wc-city-select'),
		_x('OEmnoedelger', 'HEAY', 'ry-wc-city-select'),
		_x('Tsenhermandal', 'HEAY', 'ry-wc-city-select'),
	],
	'HO' => [
		_x('Altay', 'HO', 'ry-wc-city-select'),
		_x('Bulgan District', 'HO', 'ry-wc-city-select'),
		_x('Buyant', 'HO', 'ry-wc-city-select'),
		_x('Chandmani', 'HO', 'ry-wc-city-select'),
		_x('Darvi', 'HO', 'ry-wc-city-select'),
		_x('Doergoen', 'HO', 'ry-wc-city-select'),
		_x('Duut', 'HO', 'ry-wc-city-select'),
		_x('Dzereg', 'HO', 'ry-wc-city-select'),
		_x('Erdenebueren', 'HO', 'ry-wc-city-select'),
		_x('Jargalant', 'HO', 'ry-wc-city-select'),
		_x('Khovd', 'HO', 'ry-wc-city-select'),
		_x('Manhan', 'HO', 'ry-wc-city-select'),
		_x('Moenhhayrhan', 'HO', 'ry-wc-city-select'),
		_x('Moenkhkhairkhan', 'HO', 'ry-wc-city-select'),
		_x('Moest', 'HO', 'ry-wc-city-select'),
		_x('Myangad', 'HO', 'ry-wc-city-select'),
		_x('Tsetseg', 'HO', 'ry-wc-city-select'),
		_x('UEyoench', 'HO', 'ry-wc-city-select'),
	],
	'HOAY' => [
		_x('Alag-Erdene', 'HOAY', 'ry-wc-city-select'),
		_x('Arbulag', 'HOAY', 'ry-wc-city-select'),
		_x('Bayandzuerh', 'HOAY', 'ry-wc-city-select'),
		_x('Bayanzuerkh', 'HOAY', 'ry-wc-city-select'),
		_x('Buerentogtoh', 'HOAY', 'ry-wc-city-select'),
		_x('Chandmani-OEndoer', 'HOAY', 'ry-wc-city-select'),
		_x('Erdenebulgan', 'HOAY', 'ry-wc-city-select'),
		_x('Galt', 'HOAY', 'ry-wc-city-select'),
		_x('Hanh', 'HOAY', 'ry-wc-city-select'),
		_x('Ih-Uul Sum', 'HOAY', 'ry-wc-city-select'),
		_x('Jargalant', 'HOAY', 'ry-wc-city-select'),
		_x('Jargalant Sum', 'HOAY', 'ry-wc-city-select'),
		_x('Khatgal', 'HOAY', 'ry-wc-city-select'),
		_x('Moeroen', 'HOAY', 'ry-wc-city-select'),
		_x('Moron Sum', 'HOAY', 'ry-wc-city-select'),
		_x('Rashaant', 'HOAY', 'ry-wc-city-select'),
		_x('Renchinlhuembe', 'HOAY', 'ry-wc-city-select'),
		_x('Shine-Ider', 'HOAY', 'ry-wc-city-select'),
		_x('Tarialan', 'HOAY', 'ry-wc-city-select'),
		_x('Toemoerbulag', 'HOAY', 'ry-wc-city-select'),
		_x('Tosontsengel', 'HOAY', 'ry-wc-city-select'),
		_x('Tsagaan-UEuer', 'HOAY', 'ry-wc-city-select'),
		_x('Tsagaan-Uul', 'HOAY', 'ry-wc-city-select'),
		_x('Tsagaan-Uul Sum', 'HOAY', 'ry-wc-city-select'),
		_x('Tsagaannuur', 'HOAY', 'ry-wc-city-select'),
		_x('Tsetserleg', 'HOAY', 'ry-wc-city-select'),
		_x('Tuenel', 'HOAY', 'ry-wc-city-select'),
		_x('Ulaan-Uul', 'HOAY', 'ry-wc-city-select'),
	],
	'OEPR' => [
		_x('Bayan-Ovoo', 'OEPR', 'ry-wc-city-select'),
		_x('Bayan-Ovoo Sum', 'OEPR', 'ry-wc-city-select'),
		_x('Bayandalay', 'OEPR', 'ry-wc-city-select'),
		_x('Bulgan', 'OEPR', 'ry-wc-city-select'),
		_x('Dalandzadgad', 'OEPR', 'ry-wc-city-select'),
		_x('Gurvantes', 'OEPR', 'ry-wc-city-select'),
		_x('Hanbogd', 'OEPR', 'ry-wc-city-select'),
		_x('Hanhongor', 'OEPR', 'ry-wc-city-select'),
		_x('Huermen', 'OEPR', 'ry-wc-city-select'),
		_x('Mandal-Ovoo', 'OEPR', 'ry-wc-city-select'),
		_x('Manlay', 'OEPR', 'ry-wc-city-select'),
		_x('Nomgon Sum', 'OEPR', 'ry-wc-city-select'),
		_x('Noyon', 'OEPR', 'ry-wc-city-select'),
		_x('Sevrey', 'OEPR', 'ry-wc-city-select'),
		_x('Tsogt-Ovoo', 'OEPR', 'ry-wc-city-select'),
		_x('Tsogttsetsiy', 'OEPR', 'ry-wc-city-select'),
	],
	'OEAY' => [
		_x('Arvayheer', 'OEAY', 'ry-wc-city-select'),
		_x('Baruun Bayan-Ulaan', 'OEAY', 'ry-wc-city-select'),
		_x('Baruunbayan-Ulaan', 'OEAY', 'ry-wc-city-select'),
		_x('Bat-OEldziy', 'OEAY', 'ry-wc-city-select'),
		_x('Bat-OElzii', 'OEAY', 'ry-wc-city-select'),
		_x('Bayan-OEndoer', 'OEAY', 'ry-wc-city-select'),
		_x('Bayangol', 'OEAY', 'ry-wc-city-select'),
		_x('Bogd', 'OEAY', 'ry-wc-city-select'),
		_x('Buerd', 'OEAY', 'ry-wc-city-select'),
		_x('Dzueuenbayan-Ulaan', 'OEAY', 'ry-wc-city-select'),
		_x('Guchin-Us', 'OEAY', 'ry-wc-city-select'),
		_x('Harhorin', 'OEAY', 'ry-wc-city-select'),
		_x('Hayrhandulaan', 'OEAY', 'ry-wc-city-select'),
		_x('Hujirt', 'OEAY', 'ry-wc-city-select'),
		_x('Nariynteel', 'OEAY', 'ry-wc-city-select'),
		_x('OEldziyt', 'OEAY', 'ry-wc-city-select'),
		_x('Sant', 'OEAY', 'ry-wc-city-select'),
		_x('Taragt', 'OEAY', 'ry-wc-city-select'),
		_x('Toegroeg', 'OEAY', 'ry-wc-city-select'),
		_x('Uyanga', 'OEAY', 'ry-wc-city-select'),
		_x('Yesoenzueil', 'OEAY', 'ry-wc-city-select'),
		_x('Yoesoendzueyl', 'OEAY', 'ry-wc-city-select'),
		_x('Yusun Tszuyl Somon', 'OEAY', 'ry-wc-city-select'),
		_x('Zueuenbayan-Ulaan', 'OEAY', 'ry-wc-city-select'),
	],
	'ORAY' => [
		_x('Bayan-OEndoer', 'ORAY', 'ry-wc-city-select'),
		_x('Erdenet Sum', 'ORAY', 'ry-wc-city-select'),
		_x('Jargalant', 'ORAY', 'ry-wc-city-select'),
		_x('Jargalant Sum', 'ORAY', 'ry-wc-city-select'),
	],
	'SEAY' => [
		_x('Altanbulag', 'SEAY', 'ry-wc-city-select'),
		_x('Baruunbueren', 'SEAY', 'ry-wc-city-select'),
		_x('Bayangol', 'SEAY', 'ry-wc-city-select'),
		_x('Bayangol Sum', 'SEAY', 'ry-wc-city-select'),
		_x('Dzueuenbueren', 'SEAY', 'ry-wc-city-select'),
		_x('Hueder', 'SEAY', 'ry-wc-city-select'),
		_x('Hushaat', 'SEAY', 'ry-wc-city-select'),
		_x('Javhlant', 'SEAY', 'ry-wc-city-select'),
		_x('Khueder', 'SEAY', 'ry-wc-city-select'),
		_x('Mandal', 'SEAY', 'ry-wc-city-select'),
		_x('Mandal Sum', 'SEAY', 'ry-wc-city-select'),
		_x('Orhon', 'SEAY', 'ry-wc-city-select'),
		_x('Orhontuul', 'SEAY', 'ry-wc-city-select'),
		_x('Orhontuul Sum', 'SEAY', 'ry-wc-city-select'),
		_x('Sant', 'SEAY', 'ry-wc-city-select'),
		_x('Sayhan', 'SEAY', 'ry-wc-city-select'),
		_x('Shaamar', 'SEAY', 'ry-wc-city-select'),
		_x('Suehbaatar', 'SEAY', 'ry-wc-city-select'),
		_x('Tsagaannuur', 'SEAY', 'ry-wc-city-select'),
		_x('Tueshig', 'SEAY', 'ry-wc-city-select'),
		_x('Yoroo Sum', 'SEAY', 'ry-wc-city-select'),
		_x('Zueuenbueren', 'SEAY', 'ry-wc-city-select'),
	],
	'SUAY' => [
		_x('Asgat', 'SUAY', 'ry-wc-city-select'),
		_x('Baruun-Urt', 'SUAY', 'ry-wc-city-select'),
		_x('Bayandelger', 'SUAY', 'ry-wc-city-select'),
		_x('Dariganga', 'SUAY', 'ry-wc-city-select'),
		_x('Dariganga Sum', 'SUAY', 'ry-wc-city-select'),
		_x('Erdenetsagaan', 'SUAY', 'ry-wc-city-select'),
		_x('Haldzan', 'SUAY', 'ry-wc-city-select'),
		_x('Moenhhaan', 'SUAY', 'ry-wc-city-select'),
		_x('Naran', 'SUAY', 'ry-wc-city-select'),
		_x('Ongon', 'SUAY', 'ry-wc-city-select'),
		_x('Suehbaatar', 'SUAY', 'ry-wc-city-select'),
		_x('Tuementsogt', 'SUAY', 'ry-wc-city-select'),
		_x('Tuevshinshiree', 'SUAY', 'ry-wc-city-select'),
		_x('Uulbayan', 'SUAY', 'ry-wc-city-select'),
	],
	'TOAY' => [
		_x('Altanbulag', 'TOAY', 'ry-wc-city-select'),
		_x('Argalant', 'TOAY', 'ry-wc-city-select'),
		_x('Arhust', 'TOAY', 'ry-wc-city-select'),
		_x('Baganuur', 'TOAY', 'ry-wc-city-select'),
		_x('Batsuember', 'TOAY', 'ry-wc-city-select'),
		_x('Bayan', 'TOAY', 'ry-wc-city-select'),
		_x('Bayan Sum', 'TOAY', 'ry-wc-city-select'),
		_x('Bayan-Onjuul Sum', 'TOAY', 'ry-wc-city-select'),
		_x('Bayanchandmani', 'TOAY', 'ry-wc-city-select'),
		_x('Bayandelger', 'TOAY', 'ry-wc-city-select'),
		_x('Bayanhangay', 'TOAY', 'ry-wc-city-select'),
		_x('Bayanjargalan', 'TOAY', 'ry-wc-city-select'),
		_x('Bayantal', 'TOAY', 'ry-wc-city-select'),
		_x('Bayantsagaan', 'TOAY', 'ry-wc-city-select'),
		_x('Bayantsagaan Sum', 'TOAY', 'ry-wc-city-select'),
		_x('Bayantsogt', 'TOAY', 'ry-wc-city-select'),
		_x('Bayantsogt Sum', 'TOAY', 'ry-wc-city-select'),
		_x('Bornuur', 'TOAY', 'ry-wc-city-select'),
		_x('Bueren', 'TOAY', 'ry-wc-city-select'),
		_x('Delgerhaan', 'TOAY', 'ry-wc-city-select'),
		_x('Dzaamar', 'TOAY', 'ry-wc-city-select'),
		_x('Dzuunmod', 'TOAY', 'ry-wc-city-select'),
		_x('Erdene', 'TOAY', 'ry-wc-city-select'),
		_x('Erdenesant', 'TOAY', 'ry-wc-city-select'),
		_x('Jargalant', 'TOAY', 'ry-wc-city-select'),
		_x('Khan-Uul', 'TOAY', 'ry-wc-city-select'),
		_x('Luen', 'TOAY', 'ry-wc-city-select'),
		_x('Moengoenmorit', 'TOAY', 'ry-wc-city-select'),
		_x('OEndoershireet', 'TOAY', 'ry-wc-city-select'),
		_x('Sergelen', 'TOAY', 'ry-wc-city-select'),
		_x('Suember', 'TOAY', 'ry-wc-city-select'),
		_x('Tseel', 'TOAY', 'ry-wc-city-select'),
		_x('Ugtaal', 'TOAY', 'ry-wc-city-select'),
		_x('Ugtaaltsaydam Sum', 'TOAY', 'ry-wc-city-select'),
	],
	'ULHO' => [
		_x('Bayandzuerh', 'ULHO', 'ry-wc-city-select'),
	],
	'UVAY' => [
		_x('Baruunturuun', 'UVAY', 'ry-wc-city-select'),
		_x('Boehmoeroen', 'UVAY', 'ry-wc-city-select'),
		_x('Davst', 'UVAY', 'ry-wc-city-select'),
		_x('Dzavhan', 'UVAY', 'ry-wc-city-select'),
		_x('Dzueuengovi', 'UVAY', 'ry-wc-city-select'),
		_x('Dzueuenhangay', 'UVAY', 'ry-wc-city-select'),
		_x('Dzuungovi Sum', 'UVAY', 'ry-wc-city-select'),
		_x('Hovd', 'UVAY', 'ry-wc-city-select'),
		_x('Hyargas', 'UVAY', 'ry-wc-city-select'),
		_x('Malchin', 'UVAY', 'ry-wc-city-select'),
		_x('Naranbulag', 'UVAY', 'ry-wc-city-select'),
		_x('OElgiy', 'UVAY', 'ry-wc-city-select'),
		_x('OEmnoegovi', 'UVAY', 'ry-wc-city-select'),
		_x('OEndoerhangay', 'UVAY', 'ry-wc-city-select'),
		_x('OEndoerkhangai', 'UVAY', 'ry-wc-city-select'),
		_x('Sagil', 'UVAY', 'ry-wc-city-select'),
		_x('Tarialan', 'UVAY', 'ry-wc-city-select'),
		_x('Tes', 'UVAY', 'ry-wc-city-select'),
		_x('Tsagaanhayrhan', 'UVAY', 'ry-wc-city-select'),
		_x('Tuergen', 'UVAY', 'ry-wc-city-select'),
		_x('Ulaangom', 'UVAY', 'ry-wc-city-select'),
		_x('Zueuengovi', 'UVAY', 'ry-wc-city-select'),
		_x('Zueuenkhangai', 'UVAY', 'ry-wc-city-select'),
	],
	]
];