<?php
/**
 * Republic of Mozambique places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MZ' => [
	'CH' => [
		_x('Katapua', 'CH', 'ry-wc-city-select'),
	],
	'CADEPR' => [
		_x('Ancuabe District', 'CADEPR', 'ry-wc-city-select'),
		_x('Balama District', 'CADEPR', 'ry-wc-city-select'),
		_x('Cidade de Pemba', 'CADEPR', 'ry-wc-city-select'),
		_x('Circunscricao da Quissanga', 'CADEPR', 'ry-wc-city-select'),
		_x('Circunscricao de Macomia', 'CADEPR', 'ry-wc-city-select'),
		_x('Circunscricao de Palma', 'CADEPR', 'ry-wc-city-select'),
		_x('Concelho do Ibo', 'CADEPR', 'ry-wc-city-select'),
		_x('Mecufi', 'CADEPR', 'ry-wc-city-select'),
		_x('Meluco', 'CADEPR', 'ry-wc-city-select'),
		_x('Metuge District', 'CADEPR', 'ry-wc-city-select'),
		_x('Mocimboa da Praia', 'CADEPR', 'ry-wc-city-select'),
		_x('Montepuez District', 'CADEPR', 'ry-wc-city-select'),
		_x('Mueda District', 'CADEPR', 'ry-wc-city-select'),
		_x('Muidumbe', 'CADEPR', 'ry-wc-city-select'),
		_x('Namuno District', 'CADEPR', 'ry-wc-city-select'),
		_x('Nangade', 'CADEPR', 'ry-wc-city-select'),
	],
	'CIMA' => [
		_x('KaMavota', 'CIMA', 'ry-wc-city-select'),
		_x('KaMaxakeni', 'CIMA', 'ry-wc-city-select'),
		_x('KaMpfumo', 'CIMA', 'ry-wc-city-select'),
		_x('KaMubukwana', 'CIMA', 'ry-wc-city-select'),
		_x('KaNyaka', 'CIMA', 'ry-wc-city-select'),
		_x('KaTembe', 'CIMA', 'ry-wc-city-select'),
		_x('Nhlamankulo', 'CIMA', 'ry-wc-city-select'),
	],
	'GAPR' => [
		_x('Bilene Macia District', 'GAPR', 'ry-wc-city-select'),
		_x('Chicualacuala', 'GAPR', 'ry-wc-city-select'),
		_x('Chigubo', 'GAPR', 'ry-wc-city-select'),
		_x('Chokwe District', 'GAPR', 'ry-wc-city-select'),
		_x('Cidade de Xai-Xai', 'GAPR', 'ry-wc-city-select'),
		_x('Distrito de Chibuto', 'GAPR', 'ry-wc-city-select'),
		_x('Guija', 'GAPR', 'ry-wc-city-select'),
		_x('Mabalane', 'GAPR', 'ry-wc-city-select'),
		_x('Mandlakaze', 'GAPR', 'ry-wc-city-select'),
		_x('Massangena', 'GAPR', 'ry-wc-city-select'),
		_x('Massingir', 'GAPR', 'ry-wc-city-select'),
		_x('Xai-Xai District', 'GAPR', 'ry-wc-city-select'),
	],
	'INPR' => [
		_x('Cidade de Inhambane', 'INPR', 'ry-wc-city-select'),
		_x('Circunscricao do Govuro', 'INPR', 'ry-wc-city-select'),
		_x('Funhalouro District', 'INPR', 'ry-wc-city-select'),
		_x('Homoine District', 'INPR', 'ry-wc-city-select'),
		_x('Inharrime District', 'INPR', 'ry-wc-city-select'),
		_x('Inhassoro District', 'INPR', 'ry-wc-city-select'),
		_x('Jangamo District', 'INPR', 'ry-wc-city-select'),
		_x('Mabote', 'INPR', 'ry-wc-city-select'),
		_x('Massinga District', 'INPR', 'ry-wc-city-select'),
		_x('Maxixe', 'INPR', 'ry-wc-city-select'),
		_x('Morrumbene District', 'INPR', 'ry-wc-city-select'),
		_x('Panda', 'INPR', 'ry-wc-city-select'),
		_x('Vilankulos District', 'INPR', 'ry-wc-city-select'),
		_x('Zavala District', 'INPR', 'ry-wc-city-select'),
	],
	'MAPR' => [
		_x('Barue District', 'MAPR', 'ry-wc-city-select'),
		_x('Circunscricao de Mossurize', 'MAPR', 'ry-wc-city-select'),
		_x('Concelho de Manica', 'MAPR', 'ry-wc-city-select'),
		_x('Concelho do Chimoio', 'MAPR', 'ry-wc-city-select'),
		_x('Distrito de Macate', 'MAPR', 'ry-wc-city-select'),
		_x('Distrito de Vanduzi', 'MAPR', 'ry-wc-city-select'),
		_x('Gondola District', 'MAPR', 'ry-wc-city-select'),
		_x('Guro', 'MAPR', 'ry-wc-city-select'),
		_x('Guro District', 'MAPR', 'ry-wc-city-select'),
		_x('Machaze District', 'MAPR', 'ry-wc-city-select'),
		_x('Macossa District', 'MAPR', 'ry-wc-city-select'),
		_x('Sussundenga District', 'MAPR', 'ry-wc-city-select'),
		_x('Tambara District', 'MAPR', 'ry-wc-city-select'),
	],
	'MAPR2' => [
		_x('Aeroporto', 'MAPR2', 'ry-wc-city-select'),
		_x('Boane District', 'MAPR2', 'ry-wc-city-select'),
		_x('Cidade de Manhica', 'MAPR2', 'ry-wc-city-select'),
		_x('Concelho de Matola', 'MAPR2', 'ry-wc-city-select'),
		_x('Magude District', 'MAPR2', 'ry-wc-city-select'),
		_x('Manhica', 'MAPR2', 'ry-wc-city-select'),
		_x('Marracuene District', 'MAPR2', 'ry-wc-city-select'),
		_x('Matutiune District', 'MAPR2', 'ry-wc-city-select'),
		_x('Moamba District', 'MAPR2', 'ry-wc-city-select'),
		_x('Namaacha District', 'MAPR2', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Angoche District', 'NA', 'ry-wc-city-select'),
		_x('Cidade de Nampula', 'NA', 'ry-wc-city-select'),
		_x('Circunscricao de Mogovolas', 'NA', 'ry-wc-city-select'),
		_x('Circunscricao de Murrupula', 'NA', 'ry-wc-city-select'),
		_x('Circunscricao do Erati', 'NA', 'ry-wc-city-select'),
		_x('Circunscricao do Mogincual', 'NA', 'ry-wc-city-select'),
		_x('Concelho de Monapo', 'NA', 'ry-wc-city-select'),
		_x('Distrito de Larde', 'NA', 'ry-wc-city-select'),
		_x('Distrito de Liupo', 'NA', 'ry-wc-city-select'),
		_x('Distrito de Moma', 'NA', 'ry-wc-city-select'),
		_x('Distrito de Rapale', 'NA', 'ry-wc-city-select'),
		_x('Ilha de Mocambique', 'NA', 'ry-wc-city-select'),
		_x('Lalaua District', 'NA', 'ry-wc-city-select'),
		_x('Malema', 'NA', 'ry-wc-city-select'),
		_x('Meconta', 'NA', 'ry-wc-city-select'),
		_x('Mecuburi', 'NA', 'ry-wc-city-select'),
		_x('Memba', 'NA', 'ry-wc-city-select'),
		_x('Mossuril', 'NA', 'ry-wc-city-select'),
		_x('Muecate District', 'NA', 'ry-wc-city-select'),
		_x('Nacala-Porto', 'NA', 'ry-wc-city-select'),
		_x('Nacala-a-Velha', 'NA', 'ry-wc-city-select'),
		_x('Nacaroa District', 'NA', 'ry-wc-city-select'),
		_x('Nampula', 'NA', 'ry-wc-city-select'),
		_x('Ribaue', 'NA', 'ry-wc-city-select'),
	],
	'NIPR' => [
		_x('Cidade de Lichinga', 'NIPR', 'ry-wc-city-select'),
		_x('Circunscricao de Mandimba', 'NIPR', 'ry-wc-city-select'),
		_x('Circunscricao de Sanga', 'NIPR', 'ry-wc-city-select'),
		_x('Cuamba', 'NIPR', 'ry-wc-city-select'),
		_x('Lago District', 'NIPR', 'ry-wc-city-select'),
		_x('Lichinga District', 'NIPR', 'ry-wc-city-select'),
		_x('Majune District', 'NIPR', 'ry-wc-city-select'),
		_x('Marrupa District', 'NIPR', 'ry-wc-city-select'),
		_x('Maua District', 'NIPR', 'ry-wc-city-select'),
		_x('Mavago', 'NIPR', 'ry-wc-city-select'),
		_x('Mecanhelas District', 'NIPR', 'ry-wc-city-select'),
		_x('Mecula', 'NIPR', 'ry-wc-city-select'),
		_x('Metarica District', 'NIPR', 'ry-wc-city-select'),
		_x('Muembe District', 'NIPR', 'ry-wc-city-select'),
		_x('Ngauma District', 'NIPR', 'ry-wc-city-select'),
		_x('Nipepe District', 'NIPR', 'ry-wc-city-select'),
	],
	'PRZA' => [
		_x('Alto Molocue', 'PRZA', 'ry-wc-city-select'),
		_x('Circunscricao de Mopeia', 'PRZA', 'ry-wc-city-select'),
		_x('Circunscricao do Ile', 'PRZA', 'ry-wc-city-select'),
		_x('Concelho de Quelimane', 'PRZA', 'ry-wc-city-select'),
		_x('Concelho do Chinde', 'PRZA', 'ry-wc-city-select'),
		_x('Distrito de Derre', 'PRZA', 'ry-wc-city-select'),
		_x('Distrito de Luabo', 'PRZA', 'ry-wc-city-select'),
		_x('Distrito de Mocubela', 'PRZA', 'ry-wc-city-select'),
		_x('Distrito de Molumbo', 'PRZA', 'ry-wc-city-select'),
		_x('Distrito de Mulevala', 'PRZA', 'ry-wc-city-select'),
		_x('Gile District', 'PRZA', 'ry-wc-city-select'),
		_x('Gurue District', 'PRZA', 'ry-wc-city-select'),
		_x('Inhassunge District', 'PRZA', 'ry-wc-city-select'),
		_x('Lugela District', 'PRZA', 'ry-wc-city-select'),
		_x('Maganja da Costa District', 'PRZA', 'ry-wc-city-select'),
		_x('Milange District', 'PRZA', 'ry-wc-city-select'),
		_x('Mocuba District', 'PRZA', 'ry-wc-city-select'),
		_x('Mopeia District', 'PRZA', 'ry-wc-city-select'),
		_x('Morrumbala District', 'PRZA', 'ry-wc-city-select'),
		_x('Namacurra District', 'PRZA', 'ry-wc-city-select'),
		_x('Namarroi District', 'PRZA', 'ry-wc-city-select'),
		_x('Nicodala District', 'PRZA', 'ry-wc-city-select'),
		_x('Pebane District', 'PRZA', 'ry-wc-city-select'),
	],
	'SOPR' => [
		_x('Caia District', 'SOPR', 'ry-wc-city-select'),
		_x('Chemba District', 'SOPR', 'ry-wc-city-select'),
		_x('Cheringoma District', 'SOPR', 'ry-wc-city-select'),
		_x('Chibabava District', 'SOPR', 'ry-wc-city-select'),
		_x('Circunscricao de Marromeu', 'SOPR', 'ry-wc-city-select'),
		_x('Concelho da Beira', 'SOPR', 'ry-wc-city-select'),
		_x('Concelho do Buzi', 'SOPR', 'ry-wc-city-select'),
		_x('Dondo District', 'SOPR', 'ry-wc-city-select'),
		_x('Gorongosa District', 'SOPR', 'ry-wc-city-select'),
		_x('Machanga District', 'SOPR', 'ry-wc-city-select'),
		_x('Maringue District', 'SOPR', 'ry-wc-city-select'),
		_x('Muanza District', 'SOPR', 'ry-wc-city-select'),
		_x('Nhamatanda District', 'SOPR', 'ry-wc-city-select'),
	],
	'TE' => [
		_x('Angonia District', 'TE', 'ry-wc-city-select'),
		_x('Cahora Bassa District', 'TE', 'ry-wc-city-select'),
		_x('Changara District', 'TE', 'ry-wc-city-select'),
		_x('Chifunde District', 'TE', 'ry-wc-city-select'),
		_x('Chiuta District', 'TE', 'ry-wc-city-select'),
		_x('Cidade de Tete', 'TE', 'ry-wc-city-select'),
		_x('Circunscricao da Angonia', 'TE', 'ry-wc-city-select'),
		_x('Circunscricao da Macanga', 'TE', 'ry-wc-city-select'),
		_x('Circunscricao da Mutarara', 'TE', 'ry-wc-city-select'),
		_x('Circunscricao de Magoe', 'TE', 'ry-wc-city-select'),
		_x('Circunscricao de Maravia', 'TE', 'ry-wc-city-select'),
		_x('Distrito de Doa', 'TE', 'ry-wc-city-select'),
		_x('Distrito de Marara', 'TE', 'ry-wc-city-select'),
		_x('Luenha', 'TE', 'ry-wc-city-select'),
		_x('Moatize', 'TE', 'ry-wc-city-select'),
		_x('Tsangano District', 'TE', 'ry-wc-city-select'),
		_x('Zumbu', 'TE', 'ry-wc-city-select'),
	],
	]
];