<?php
/**
 * Republic of Nicaragua places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'NI' => [
	'MUMA' => [
		_x('Distrito II', 'MUMA', 'ry-wc-city-select'),
		_x('Distrito III', 'MUMA', 'ry-wc-city-select'),
		_x('Distrito V', 'MUMA', 'ry-wc-city-select'),
		_x('Distrito VI', 'MUMA', 'ry-wc-city-select'),
	],
	'COCANO' => [
		_x('Mulukuku', 'COCANO', 'ry-wc-city-select'),
		_x('Municipio de Bonanza', 'COCANO', 'ry-wc-city-select'),
		_x('Municipio de Prinzapolka', 'COCANO', 'ry-wc-city-select'),
		_x('Municipio de Puerto Cabezas', 'COCANO', 'ry-wc-city-select'),
		_x('Municipio de Rosita', 'COCANO', 'ry-wc-city-select'),
		_x('Municipio de Siuna', 'COCANO', 'ry-wc-city-select'),
		_x('Municipio de Waslala', 'COCANO', 'ry-wc-city-select'),
		_x('Municipio de Waspan', 'COCANO', 'ry-wc-city-select'),
	],
	'COCASU' => [
		_x('Desembocadura de la Cruz de Rio Grande', 'COCASU', 'ry-wc-city-select'),
		_x('El Rama', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio El Ayote', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio El Tortuguero', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio de Bluefields', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio de Bocana de Paiwas', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio de Corn Island', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio de Kukra Hill', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio de La Cruz de Rio Grande', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio de Laguna', 'COCASU', 'ry-wc-city-select'),
		_x('Municipio de Muelle de los Bueyes', 'COCASU', 'ry-wc-city-select'),
		_x('Nueva Guinea', 'COCASU', 'ry-wc-city-select'),
	],
	'DEBO' => [
		_x('Municipio de Boaco', 'DEBO', 'ry-wc-city-select'),
		_x('Municipio de Camoapa', 'DEBO', 'ry-wc-city-select'),
		_x('Municipio de San Jose de los Remates', 'DEBO', 'ry-wc-city-select'),
		_x('Municipio de San Lorenzo', 'DEBO', 'ry-wc-city-select'),
		_x('Municipio de Santa Lucia', 'DEBO', 'ry-wc-city-select'),
		_x('Municipio de Teustepe', 'DEBO', 'ry-wc-city-select'),
	],
	'DECA' => [
		_x('La Paz de Carazo', 'DECA', 'ry-wc-city-select'),
		_x('Municipio de Diriamba', 'DECA', 'ry-wc-city-select'),
		_x('Municipio de Dolores', 'DECA', 'ry-wc-city-select'),
		_x('Municipio de El Rosario', 'DECA', 'ry-wc-city-select'),
		_x('Municipio de Jinotepe', 'DECA', 'ry-wc-city-select'),
		_x('Municipio de La Conquista', 'DECA', 'ry-wc-city-select'),
		_x('Municipio de San Marcos', 'DECA', 'ry-wc-city-select'),
		_x('Municipio de Santa Teresa', 'DECA', 'ry-wc-city-select'),
	],
	'DECH' => [
		_x('Municipio de Chichigalpa', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Chinandega', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Cinco Pinos', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Corinto', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de El Realejo', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de El Viejo', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Posoltega', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Puerto Morazan', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de San Francisco del Norte', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de San Pedro del Norte', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Santo Tomas del Norte', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Somotillo', 'DECH', 'ry-wc-city-select'),
		_x('Municipio de Villanueva', 'DECH', 'ry-wc-city-select'),
	],
	'DECH2' => [
		_x('El Coral', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Acoyapa', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Comalapa', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Juigalpa', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de La Libertad', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de San Francisco de Cuapa', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de San Pedro de Lovago', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Santo Domingo', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Santo Tomas', 'DECH2', 'ry-wc-city-select'),
		_x('Municipio de Villa Sandino', 'DECH2', 'ry-wc-city-select'),
	],
	'DEES' => [
		_x('Municipio de Condega', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Esteli', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de La Trinidad', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de Pueblo Nuevo', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de San Juan de Limay', 'DEES', 'ry-wc-city-select'),
		_x('Municipio de San Nicolas', 'DEES', 'ry-wc-city-select'),
	],
	'DEGR' => [
		_x('Municipio de Diria', 'DEGR', 'ry-wc-city-select'),
		_x('Municipio de Diriomo', 'DEGR', 'ry-wc-city-select'),
		_x('Municipio de Granada', 'DEGR', 'ry-wc-city-select'),
		_x('Municipio de Nandaime', 'DEGR', 'ry-wc-city-select'),
	],
	'DEJI' => [
		_x('Municipio El Cua', 'DEJI', 'ry-wc-city-select'),
		_x('Municipio de Jinotega', 'DEJI', 'ry-wc-city-select'),
		_x('Municipio de La Concordia', 'DEJI', 'ry-wc-city-select'),
		_x('Municipio de San Jose de Bocay', 'DEJI', 'ry-wc-city-select'),
		_x('Municipio de San Rafael del Norte', 'DEJI', 'ry-wc-city-select'),
		_x('Municipio de San Sebastian de Yali', 'DEJI', 'ry-wc-city-select'),
		_x('Municipio de Santa Maria de Pantasma', 'DEJI', 'ry-wc-city-select'),
		_x('Wiwili de Jinotega', 'DEJI', 'ry-wc-city-select'),
	],
	'DELE' => [
		_x('La Paz Centro', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de Achuapa', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de El Jicaral', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de El Sauce', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de Larreynaga', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de Leon', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de Nagarote', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de Quezalguaque', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de Santa Rosa del Penon', 'DELE', 'ry-wc-city-select'),
		_x('Municipio de Telica', 'DELE', 'ry-wc-city-select'),
	],
	'DEMA' => [
		_x('Municipio de Las Sabanas', 'DEMA', 'ry-wc-city-select'),
		_x('Municipio de Palacagueina', 'DEMA', 'ry-wc-city-select'),
		_x('Municipio de San Jose de Cusmapa', 'DEMA', 'ry-wc-city-select'),
		_x('Municipio de San Juan de Rio Coco', 'DEMA', 'ry-wc-city-select'),
		_x('Municipio de San Lucas', 'DEMA', 'ry-wc-city-select'),
		_x('Municipio de Somoto', 'DEMA', 'ry-wc-city-select'),
		_x('Municipio de Telpaneca', 'DEMA', 'ry-wc-city-select'),
		_x('Municipio de Totogalpa', 'DEMA', 'ry-wc-city-select'),
		_x('Municipio de Yalagueina', 'DEMA', 'ry-wc-city-select'),
	],
	'DEMA2' => [
		_x('Ciudad Sandino', 'DEMA2', 'ry-wc-city-select'),
		_x('El Crucero', 'DEMA2', 'ry-wc-city-select'),
		_x('Municipio de Mateare', 'DEMA2', 'ry-wc-city-select'),
		_x('Municipio de San Francisco Libre', 'DEMA2', 'ry-wc-city-select'),
		_x('Municipio de San Rafael del Sur', 'DEMA2', 'ry-wc-city-select'),
		_x('Municipio de Tipitapa', 'DEMA2', 'ry-wc-city-select'),
		_x('Ticuantepe', 'DEMA2', 'ry-wc-city-select'),
		_x('Villa El Carmen', 'DEMA2', 'ry-wc-city-select'),
	],
	'DEMA3' => [
		_x('Municipio de Catarina', 'DEMA3', 'ry-wc-city-select'),
		_x('Municipio de La Concepcion', 'DEMA3', 'ry-wc-city-select'),
		_x('Municipio de Masatepe', 'DEMA3', 'ry-wc-city-select'),
		_x('Municipio de Masaya', 'DEMA3', 'ry-wc-city-select'),
		_x('Municipio de Nandasmo', 'DEMA3', 'ry-wc-city-select'),
		_x('Municipio de Nindiri', 'DEMA3', 'ry-wc-city-select'),
		_x('Municipio de Niquinohomo', 'DEMA3', 'ry-wc-city-select'),
		_x('Municipio de San Juan de Oriente', 'DEMA3', 'ry-wc-city-select'),
		_x('Municipio de Tisma', 'DEMA3', 'ry-wc-city-select'),
	],
	'DEMA4' => [
		_x('Municipio de Ciudad Dario', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de Esquipulas', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de Matagalpa', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de Matiguas', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de Muy Muy', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de Rancho Grande', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de Rio Blanco', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de San Dionisio', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de San Isidro', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de San Ramon', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de Sebaco', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio de Terrabona', 'DEMA4', 'ry-wc-city-select'),
		_x('Municipio del Tuma-La Dalia', 'DEMA4', 'ry-wc-city-select'),
	],
	'DENUSE' => [
		_x('El Jicaro', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Ciudad Antigua', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Dipilto', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Jalapa', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Macuelizo', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Mozonte', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Murra', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Ocotal', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Quilali', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de San Fernando', 'DENUSE', 'ry-wc-city-select'),
		_x('Municipio de Santa Maria', 'DENUSE', 'ry-wc-city-select'),
		_x('Wiwili de Nueva Segovia', 'DENUSE', 'ry-wc-city-select'),
	],
	'DERISAJU' => [
		_x('El Almendro', 'DERISAJU', 'ry-wc-city-select'),
		_x('El Castillo', 'DERISAJU', 'ry-wc-city-select'),
		_x('Municipio de Morrito', 'DERISAJU', 'ry-wc-city-select'),
		_x('Municipio de San Carlos', 'DERISAJU', 'ry-wc-city-select'),
		_x('Municipio de San Miguelito', 'DERISAJU', 'ry-wc-city-select'),
		_x('San Juan del Nicaragua', 'DERISAJU', 'ry-wc-city-select'),
	],
	'DERI' => [
		_x('Municipio de Altagracia', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de Belen', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de Buenos Aires', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de Cardenas', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de Moyogalpa', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de Potosi', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de Rivas', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de San Jorge', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de San Juan del Sur', 'DERI', 'ry-wc-city-select'),
		_x('Municipio de Tola', 'DERI', 'ry-wc-city-select'),
	],
	]
];