<?php
/**
 * Kingdom of the Netherlands places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'NL' => [
	'GEAM' => [
		_x('Centrum', 'GEAM', 'ry-wc-city-select'),
		_x('Nieuw-West', 'GEAM', 'ry-wc-city-select'),
		_x('Noord', 'GEAM', 'ry-wc-city-select'),
		_x('Oost', 'GEAM', 'ry-wc-city-select'),
		_x('West', 'GEAM', 'ry-wc-city-select'),
		_x('Westpoort', 'GEAM', 'ry-wc-city-select'),
		_x('Zuid', 'GEAM', 'ry-wc-city-select'),
		_x('Zuidoost', 'GEAM', 'ry-wc-city-select'),
	],
	'GEDEHA' => [
		_x('Centrum', 'GEDEHA', 'ry-wc-city-select'),
		_x('Escamp', 'GEDEHA', 'ry-wc-city-select'),
		_x('Haagse Hout', 'GEDEHA', 'ry-wc-city-select'),
		_x('Laak', 'GEDEHA', 'ry-wc-city-select'),
		_x('Leidschenveen-Ypenburg', 'GEDEHA', 'ry-wc-city-select'),
		_x('Loosduinen', 'GEDEHA', 'ry-wc-city-select'),
		_x('Scheveningen', 'GEDEHA', 'ry-wc-city-select'),
		_x('Segbroek', 'GEDEHA', 'ry-wc-city-select'),
	],
	'PRDR' => [
		_x('Gemeente Aa en Hunze', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Assen', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Borger-Odoorn', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Coevorden', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente De Wolden', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Emmen', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Hoogeveen', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Meppel', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Midden-Drenthe', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Noordenveld', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Tynaarlo', 'PRDR', 'ry-wc-city-select'),
		_x('Gemeente Westerveld', 'PRDR', 'ry-wc-city-select'),
	],
	'PRFL' => [
		_x('Gemeente Almere', 'PRFL', 'ry-wc-city-select'),
		_x('Gemeente Dronten', 'PRFL', 'ry-wc-city-select'),
		_x('Gemeente Lelystad', 'PRFL', 'ry-wc-city-select'),
		_x('Gemeente Noordoostpolder', 'PRFL', 'ry-wc-city-select'),
		_x('Gemeente Urk', 'PRFL', 'ry-wc-city-select'),
		_x('Gemeente Zeewolde', 'PRFL', 'ry-wc-city-select'),
	],
	'PRFR' => [
		_x('De Fryske Marren', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Achtkarspelen', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Ameland', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Dantumadiel', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Harlingen', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Heerenveen', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Leeuwarden', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Ooststellingwerf', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Opsterland', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Schiermonnikoog', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Smallingerland', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Terschelling', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Tytsjerksteradiel', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Vlieland', 'PRFR', 'ry-wc-city-select'),
		_x('Gemeente Weststellingwerf', 'PRFR', 'ry-wc-city-select'),
		_x('Noardeast-Fryslan', 'PRFR', 'ry-wc-city-select'),
		_x('Sudwest Fryslan', 'PRFR', 'ry-wc-city-select'),
		_x('Waadhoeke', 'PRFR', 'ry-wc-city-select'),
	],
	'PRGE' => [
		_x('Berkelland', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Aalten', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Apeldoorn', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Arnhem', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Barneveld', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Berg en Dal', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Beuningen', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Bronckhorst', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Brummen', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Buren', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Culemborg', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Doesburg', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Doetinchem', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Druten', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Duiven', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Ede', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Elburg', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Epe', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Ermelo', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Harderwijk', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Hattem', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Heerde', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Heumen', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Lingewaard', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Lochem', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Maasdriel', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Montferland', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Neder-Betuwe', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Nijkerk', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Nijmegen', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Nunspeet', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Oldebroek', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Overbetuwe', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Putten', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Renkum', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Rheden', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Rozendaal', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Scherpenzeel', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Tiel', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Voorst', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Wageningen', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente West Maas en Waal', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Westervoort', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Wijchen', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Winterswijk', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Zaltbommel', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Zevenaar', 'PRGE', 'ry-wc-city-select'),
		_x('Gemeente Zutphen', 'PRGE', 'ry-wc-city-select'),
		_x('Oost Gelre', 'PRGE', 'ry-wc-city-select'),
		_x('Oude IJsselstreek', 'PRGE', 'ry-wc-city-select'),
		_x('West Betuwe', 'PRGE', 'ry-wc-city-select'),
	],
	'PRGR' => [
		_x('Gemeente  Oldambt', 'PRGR', 'ry-wc-city-select'),
		_x('Gemeente Appingedam', 'PRGR', 'ry-wc-city-select'),
		_x('Gemeente Delfzijl', 'PRGR', 'ry-wc-city-select'),
		_x('Gemeente Groningen', 'PRGR', 'ry-wc-city-select'),
		_x('Gemeente Loppersum', 'PRGR', 'ry-wc-city-select'),
		_x('Gemeente Pekela', 'PRGR', 'ry-wc-city-select'),
		_x('Gemeente Stadskanaal', 'PRGR', 'ry-wc-city-select'),
		_x('Gemeente Veendam', 'PRGR', 'ry-wc-city-select'),
		_x('Het Hogeland', 'PRGR', 'ry-wc-city-select'),
		_x('Midden-Groningen', 'PRGR', 'ry-wc-city-select'),
		_x('Westerkwartier', 'PRGR', 'ry-wc-city-select'),
		_x('Westerwolde', 'PRGR', 'ry-wc-city-select'),
	],
	'PRLI' => [
		_x('Beekdaelen', 'PRLI', 'ry-wc-city-select'),
		_x('Eijsden-Margraten', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Beek', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Beesel', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Bergen', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Brunssum', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Echt-Susteren', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Gennep', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Heerlen', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Horst aan de Maas', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Kerkrade', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Leudal', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Maasgouw', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Maastricht', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Meerssen', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Mook en Middelaar', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Nederweert', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Peel en Maas', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Roerdalen', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Roermond', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Simpelveld', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Sittard-Geleen', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Stein', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Vaals', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Venlo', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Venray', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Voerendaal', 'PRLI', 'ry-wc-city-select'),
		_x('Gemeente Weert', 'PRLI', 'ry-wc-city-select'),
		_x('Gulpen-Wittem', 'PRLI', 'ry-wc-city-select'),
		_x('Landgraaf', 'PRLI', 'ry-wc-city-select'),
		_x('Valkenburg aan de Geul', 'PRLI', 'ry-wc-city-select'),
	],
	'PRNO' => [
		_x('Altena', 'PRNO', 'ry-wc-city-select'),
		_x('Bergeijk', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente s-Hertogenbosch', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Alphen-Chaam', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Asten', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Baarle-Nassau', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Bergen op Zoom', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Bernheze', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Best', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Bladel', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Boekel', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Boxmeer', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Boxtel', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Breda', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Cranendonck', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Cuijk', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Deurne', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Dongen', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Drimmelen', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Eersel', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Eindhoven', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Etten-Leur', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Geertruidenberg', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Geldrop-Mierlo', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Gemert-Bakel', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Gilze en Rijen', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Goirle', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Grave', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Haaren', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Halderberge', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Heeze-Leende', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Helmond', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Heusden', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Hilvarenbeek', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Laarbeek', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Landerd', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Loon op Zand', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Mill en Sint Hubert', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Moerdijk', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Nuenen, Gerwen en Nederwetten', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Oirschot', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Oisterwijk', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Oosterhout', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Oss', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Reusel-De Mierden', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Rucphen', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Sint Anthonis', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Sint-Michielsgestel', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Someren', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Son en Breugel', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Steenbergen', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Tilburg', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Uden', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Valkenswaard', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Veldhoven', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Vught', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Waalre', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Waalwijk', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Woensdrecht', 'PRNO', 'ry-wc-city-select'),
		_x('Gemeente Zundert', 'PRNO', 'ry-wc-city-select'),
		_x('Meierijstad', 'PRNO', 'ry-wc-city-select'),
		_x('Roosendaal', 'PRNO', 'ry-wc-city-select'),
	],
	'PRNO2' => [
		_x('Gemeente Aalsmeer', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Alkmaar', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Amstelveen', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Beemster', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Bergen', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Beverwijk', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Blaricum', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Bloemendaal', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Castricum', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Den Helder', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Diemen', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Drechterland', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Edam-Volendam', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Enkhuizen', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Haarlem', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Haarlemmermeer', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Heemskerk', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Heemstede', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Heerhugowaard', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Heiloo', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Hilversum', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Hollands Kroon', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Hoorn', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Huizen', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Koggenland', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Landsmeer', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Langedijk', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Laren', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Medemblik', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Oostzaan', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Opmeer', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Ouder-Amstel', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Purmerend', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Schagen', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Stede Broec', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Texel', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Uitgeest', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Uithoorn', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Velsen', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Waterland', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Weesp', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Wijdemeren', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Wormerland', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Zaanstad', 'PRNO2', 'ry-wc-city-select'),
		_x('Gemeente Zandvoort', 'PRNO2', 'ry-wc-city-select'),
		_x('Gooise Meren', 'PRNO2', 'ry-wc-city-select'),
	],
	'PROV' => [
		_x('Gemeente Almelo', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Borne', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Dalfsen', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Deventer', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Dinkelland', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Enschede', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Haaksbergen', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Hardenberg', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Hellendoorn', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Hengelo', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Hof van Twente', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Kampen', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Losser', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Oldenzaal', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Olst-Wijhe', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Ommen', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Raalte', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Rijssen-Holten', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Staphorst', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Steenwijkerland', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Tubbergen', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Twenterand', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Wierden', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Zwartewaterland', 'PROV', 'ry-wc-city-select'),
		_x('Gemeente Zwolle', 'PROV', 'ry-wc-city-select'),
	],
	'PRUT' => [
		_x('Gemeente Amersfoort', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Baarn', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Bunnik', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Bunschoten', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente De Bilt', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente De Ronde Venen', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Eemnes', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Houten', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente IJsselstein', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Leusden', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Lopik', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Montfoort', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Nieuwegein', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Oudewater', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Renswoude', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Rhenen', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Soest', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Utrecht', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Utrechtse Heuvelrug', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Veenendaal', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Wijk bij Duurstede', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Woerden', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Woudenberg', 'PRUT', 'ry-wc-city-select'),
		_x('Gemeente Zeist', 'PRUT', 'ry-wc-city-select'),
		_x('Stichtse Vecht', 'PRUT', 'ry-wc-city-select'),
		_x('Vijfheerenlanden', 'PRUT', 'ry-wc-city-select'),
	],
	'PRZE' => [
		_x('Gemeente Borsele', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Goes', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Hulst', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Kapelle', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Middelburg', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Noord-Beveland', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Reimerswaal', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Sluis', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Terneuzen', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Tholen', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Veere', 'PRZE', 'ry-wc-city-select'),
		_x('Gemeente Vlissingen', 'PRZE', 'ry-wc-city-select'),
		_x('Schouwen-Duiveland', 'PRZE', 'ry-wc-city-select'),
	],
	'PRZU' => [
		_x('Bodegraven-Reeuwijk', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Alblasserdam', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Albrandswaard', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Alphen aan den Rijn', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Barendrecht', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Brielle', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Capelle aan den IJssel', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Delft', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Dordrecht', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Goeree-Overflakkee', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Gorinchem', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Gouda', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Hardinxveld-Giessendam', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Hellevoetsluis', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Hendrik-Ido-Ambacht', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Hillegom', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Kaag en Braassem', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Katwijk', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Krimpen aan den IJssel', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Lansingerland', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Leiden', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Leiderdorp', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Leidschendam-Voorburg', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Lisse', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Maassluis', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Midden-Delfland', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Nieuwkoop', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Noordwijk', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Oegstgeest', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Papendrecht', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Pijnacker-Nootdorp', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Ridderkerk', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Rijswijk', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Rotterdam', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Schiedam', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Sliedrecht', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Teylingen', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Vlaardingen', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Voorschoten', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Waddinxveen', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Wassenaar', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Westland', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Westvoorne', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Zoetermeer', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Zoeterwoude', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Zuidplas', 'PRZU', 'ry-wc-city-select'),
		_x('Gemeente Zwijndrecht', 'PRZU', 'ry-wc-city-select'),
		_x('Hoeksche Waard', 'PRZU', 'ry-wc-city-select'),
		_x('Krimpenerwaard', 'PRZU', 'ry-wc-city-select'),
		_x('Molenlanden', 'PRZU', 'ry-wc-city-select'),
		_x('Nissewaard', 'PRZU', 'ry-wc-city-select'),
	],
	]
];