<?php
/**
 * Kingdom of Norway places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'NO' => [
	'OS' => [
		_x('Alna District', 'OS', 'ry-wc-city-select'),
		_x('Bjerke District', 'OS', 'ry-wc-city-select'),
		_x('Frogner District', 'OS', 'ry-wc-city-select'),
		_x('Gamle Oslo District', 'OS', 'ry-wc-city-select'),
		_x('Grorud District', 'OS', 'ry-wc-city-select'),
		_x('Gruenerlokka District', 'OS', 'ry-wc-city-select'),
		_x('Marka', 'OS', 'ry-wc-city-select'),
		_x('Nordre Aker District', 'OS', 'ry-wc-city-select'),
		_x('Nordstrand District', 'OS', 'ry-wc-city-select'),
		_x('Sagene District', 'OS', 'ry-wc-city-select'),
		_x('Sentrum', 'OS', 'ry-wc-city-select'),
		_x('Sondre Nordstrand District', 'OS', 'ry-wc-city-select'),
		_x('St. Hanshaugen District', 'OS', 'ry-wc-city-select'),
		_x('Ullern District', 'OS', 'ry-wc-city-select'),
		_x('Vestre Aker District', 'OS', 'ry-wc-city-select'),
	],
	'AG' => [
		_x('Amli', 'AG', 'ry-wc-city-select'),
		_x('Arendal', 'AG', 'ry-wc-city-select'),
		_x('Aseral', 'AG', 'ry-wc-city-select'),
		_x('Birkenes', 'AG', 'ry-wc-city-select'),
		_x('Bygland', 'AG', 'ry-wc-city-select'),
		_x('Bykle', 'AG', 'ry-wc-city-select'),
		_x('Evje og Hornnes', 'AG', 'ry-wc-city-select'),
		_x('Farsund', 'AG', 'ry-wc-city-select'),
		_x('Flekkefjord', 'AG', 'ry-wc-city-select'),
		_x('Froland', 'AG', 'ry-wc-city-select'),
		_x('Gjerstad', 'AG', 'ry-wc-city-select'),
		_x('Grimstad', 'AG', 'ry-wc-city-select'),
		_x('Haegebostad', 'AG', 'ry-wc-city-select'),
		_x('Iveland', 'AG', 'ry-wc-city-select'),
		_x('Kristiansand', 'AG', 'ry-wc-city-select'),
		_x('Kvinesdal', 'AG', 'ry-wc-city-select'),
		_x('Lillesand', 'AG', 'ry-wc-city-select'),
		_x('Lindesnes', 'AG', 'ry-wc-city-select'),
		_x('Lyngdal', 'AG', 'ry-wc-city-select'),
		_x('Risor', 'AG', 'ry-wc-city-select'),
		_x('Sirdal', 'AG', 'ry-wc-city-select'),
		_x('Tvedestrand', 'AG', 'ry-wc-city-select'),
		_x('Valle', 'AG', 'ry-wc-city-select'),
		_x('Vegarshei', 'AG', 'ry-wc-city-select'),
		_x('Vennesla', 'AG', 'ry-wc-city-select'),
	],
	'IN' => [
		_x('Alvdal', 'IN', 'ry-wc-city-select'),
		_x('Amot', 'IN', 'ry-wc-city-select'),
		_x('Asnes', 'IN', 'ry-wc-city-select'),
		_x('Dovre', 'IN', 'ry-wc-city-select'),
		_x('Eidskog', 'IN', 'ry-wc-city-select'),
		_x('Elverum', 'IN', 'ry-wc-city-select'),
		_x('Engerdal', 'IN', 'ry-wc-city-select'),
		_x('Etnedal', 'IN', 'ry-wc-city-select'),
		_x('Folldal', 'IN', 'ry-wc-city-select'),
		_x('Gausdal', 'IN', 'ry-wc-city-select'),
		_x('Gjovik', 'IN', 'ry-wc-city-select'),
		_x('Gran', 'IN', 'ry-wc-city-select'),
		_x('Grue', 'IN', 'ry-wc-city-select'),
		_x('Hamar', 'IN', 'ry-wc-city-select'),
		_x('Kongsvinger', 'IN', 'ry-wc-city-select'),
		_x('Lesja', 'IN', 'ry-wc-city-select'),
		_x('Lillehammer', 'IN', 'ry-wc-city-select'),
		_x('Lom', 'IN', 'ry-wc-city-select'),
		_x('Loten', 'IN', 'ry-wc-city-select'),
		_x('Nord-Aurdal', 'IN', 'ry-wc-city-select'),
		_x('Nord-Fron', 'IN', 'ry-wc-city-select'),
		_x('Nord-Odal', 'IN', 'ry-wc-city-select'),
		_x('Nordre Land', 'IN', 'ry-wc-city-select'),
		_x('Os', 'IN', 'ry-wc-city-select'),
		_x('Ostre Toten', 'IN', 'ry-wc-city-select'),
		_x('Oyer', 'IN', 'ry-wc-city-select'),
		_x('Oystre Slidre', 'IN', 'ry-wc-city-select'),
		_x('Rendalen', 'IN', 'ry-wc-city-select'),
		_x('Ringebu', 'IN', 'ry-wc-city-select'),
		_x('Ringsaker', 'IN', 'ry-wc-city-select'),
		_x('Sel', 'IN', 'ry-wc-city-select'),
		_x('Skjak', 'IN', 'ry-wc-city-select'),
		_x('Sondre Land', 'IN', 'ry-wc-city-select'),
		_x('Sor-Aurdal', 'IN', 'ry-wc-city-select'),
		_x('Sor-Fron', 'IN', 'ry-wc-city-select'),
		_x('Sor-Odal', 'IN', 'ry-wc-city-select'),
		_x('Stange', 'IN', 'ry-wc-city-select'),
		_x('Stor-Elvdal', 'IN', 'ry-wc-city-select'),
		_x('Tolga', 'IN', 'ry-wc-city-select'),
		_x('Trysil', 'IN', 'ry-wc-city-select'),
		_x('Tynset', 'IN', 'ry-wc-city-select'),
		_x('Vaga', 'IN', 'ry-wc-city-select'),
		_x('Valer', 'IN', 'ry-wc-city-select'),
		_x('Vang', 'IN', 'ry-wc-city-select'),
		_x('Vestre Slidre', 'IN', 'ry-wc-city-select'),
		_x('Vestre Toten', 'IN', 'ry-wc-city-select'),
	],
	'MOROFY' => [
		_x('Alesund', 'MOROFY', 'ry-wc-city-select'),
		_x('Aukra', 'MOROFY', 'ry-wc-city-select'),
		_x('Aure', 'MOROFY', 'ry-wc-city-select'),
		_x('Averoy', 'MOROFY', 'ry-wc-city-select'),
		_x('Fjord', 'MOROFY', 'ry-wc-city-select'),
		_x('Giske', 'MOROFY', 'ry-wc-city-select'),
		_x('Gjemnes', 'MOROFY', 'ry-wc-city-select'),
		_x('Hareid', 'MOROFY', 'ry-wc-city-select'),
		_x('Heroy', 'MOROFY', 'ry-wc-city-select'),
		_x('Hustadvika', 'MOROFY', 'ry-wc-city-select'),
		_x('Kristiansund', 'MOROFY', 'ry-wc-city-select'),
		_x('Molde', 'MOROFY', 'ry-wc-city-select'),
		_x('Orsta', 'MOROFY', 'ry-wc-city-select'),
		_x('Rauma', 'MOROFY', 'ry-wc-city-select'),
		_x('Sande', 'MOROFY', 'ry-wc-city-select'),
		_x('Smola', 'MOROFY', 'ry-wc-city-select'),
		_x('Stranda', 'MOROFY', 'ry-wc-city-select'),
		_x('Sula', 'MOROFY', 'ry-wc-city-select'),
		_x('Sunndal', 'MOROFY', 'ry-wc-city-select'),
		_x('Surnadal', 'MOROFY', 'ry-wc-city-select'),
		_x('Sykkylven', 'MOROFY', 'ry-wc-city-select'),
		_x('Tingvoll', 'MOROFY', 'ry-wc-city-select'),
		_x('Ulstein', 'MOROFY', 'ry-wc-city-select'),
		_x('Vanylven', 'MOROFY', 'ry-wc-city-select'),
		_x('Vestnes', 'MOROFY', 'ry-wc-city-select'),
		_x('Volda', 'MOROFY', 'ry-wc-city-select'),
	],
	'NOFY' => [
		_x('Alstahaug', 'NOFY', 'ry-wc-city-select'),
		_x('Andoy', 'NOFY', 'ry-wc-city-select'),
		_x('Beiarn', 'NOFY', 'ry-wc-city-select'),
		_x('Bindal', 'NOFY', 'ry-wc-city-select'),
		_x('Bo', 'NOFY', 'ry-wc-city-select'),
		_x('Bodo', 'NOFY', 'ry-wc-city-select'),
		_x('Bronnoy', 'NOFY', 'ry-wc-city-select'),
		_x('Donna', 'NOFY', 'ry-wc-city-select'),
		_x('Evenes', 'NOFY', 'ry-wc-city-select'),
		_x('Fauske', 'NOFY', 'ry-wc-city-select'),
		_x('Flakstad', 'NOFY', 'ry-wc-city-select'),
		_x('Gildeskal', 'NOFY', 'ry-wc-city-select'),
		_x('Grane', 'NOFY', 'ry-wc-city-select'),
		_x('Hadsel', 'NOFY', 'ry-wc-city-select'),
		_x('Hamaroy', 'NOFY', 'ry-wc-city-select'),
		_x('Hattfjelldal', 'NOFY', 'ry-wc-city-select'),
		_x('Hemnes', 'NOFY', 'ry-wc-city-select'),
		_x('Heroy', 'NOFY', 'ry-wc-city-select'),
		_x('Leirfjord', 'NOFY', 'ry-wc-city-select'),
		_x('Lodingen', 'NOFY', 'ry-wc-city-select'),
		_x('Luroy', 'NOFY', 'ry-wc-city-select'),
		_x('Meloy', 'NOFY', 'ry-wc-city-select'),
		_x('Moskenes', 'NOFY', 'ry-wc-city-select'),
		_x('Narvik', 'NOFY', 'ry-wc-city-select'),
		_x('Nesna', 'NOFY', 'ry-wc-city-select'),
		_x('Oksnes', 'NOFY', 'ry-wc-city-select'),
		_x('Rana', 'NOFY', 'ry-wc-city-select'),
		_x('Rodoy', 'NOFY', 'ry-wc-city-select'),
		_x('Rost', 'NOFY', 'ry-wc-city-select'),
		_x('Saltdal', 'NOFY', 'ry-wc-city-select'),
		_x('Somna', 'NOFY', 'ry-wc-city-select'),
		_x('Sorfold', 'NOFY', 'ry-wc-city-select'),
		_x('Sortland', 'NOFY', 'ry-wc-city-select'),
		_x('Steigen', 'NOFY', 'ry-wc-city-select'),
		_x('Traena', 'NOFY', 'ry-wc-city-select'),
		_x('Vaeroy', 'NOFY', 'ry-wc-city-select'),
		_x('Vagan', 'NOFY', 'ry-wc-city-select'),
		_x('Vefsn', 'NOFY', 'ry-wc-city-select'),
		_x('Vega', 'NOFY', 'ry-wc-city-select'),
		_x('Vestvagoy', 'NOFY', 'ry-wc-city-select'),
		_x('Vevelstad', 'NOFY', 'ry-wc-city-select'),
	],
	'ROFY' => [
		_x('Bjerkreim', 'ROFY', 'ry-wc-city-select'),
		_x('Bokn', 'ROFY', 'ry-wc-city-select'),
		_x('Eigersund', 'ROFY', 'ry-wc-city-select'),
		_x('Gjesdal', 'ROFY', 'ry-wc-city-select'),
		_x('Ha', 'ROFY', 'ry-wc-city-select'),
		_x('Haugesund', 'ROFY', 'ry-wc-city-select'),
		_x('Hjelmeland', 'ROFY', 'ry-wc-city-select'),
		_x('Karmoy', 'ROFY', 'ry-wc-city-select'),
		_x('Klepp', 'ROFY', 'ry-wc-city-select'),
		_x('Kvitsoy', 'ROFY', 'ry-wc-city-select'),
		_x('Lund', 'ROFY', 'ry-wc-city-select'),
		_x('Randaberg', 'ROFY', 'ry-wc-city-select'),
		_x('Sandnes', 'ROFY', 'ry-wc-city-select'),
		_x('Sauda', 'ROFY', 'ry-wc-city-select'),
		_x('Sokndal', 'ROFY', 'ry-wc-city-select'),
		_x('Sola', 'ROFY', 'ry-wc-city-select'),
		_x('Stavanger', 'ROFY', 'ry-wc-city-select'),
		_x('Strand', 'ROFY', 'ry-wc-city-select'),
		_x('Suldal', 'ROFY', 'ry-wc-city-select'),
		_x('Time', 'ROFY', 'ry-wc-city-select'),
		_x('Tysvaer', 'ROFY', 'ry-wc-city-select'),
		_x('Utsira', 'ROFY', 'ry-wc-city-select'),
		_x('Vindafjord', 'ROFY', 'ry-wc-city-select'),
	],
	'TRFI' => [
		_x('Alta', 'TRFI', 'ry-wc-city-select'),
		_x('Balsfjord', 'TRFI', 'ry-wc-city-select'),
		_x('Bardu', 'TRFI', 'ry-wc-city-select'),
		_x('Batsfjord', 'TRFI', 'ry-wc-city-select'),
		_x('Berlevag', 'TRFI', 'ry-wc-city-select'),
		_x('Dyroy', 'TRFI', 'ry-wc-city-select'),
		_x('Gamvik', 'TRFI', 'ry-wc-city-select'),
		_x('Gratangen', 'TRFI', 'ry-wc-city-select'),
		_x('Hammerfest', 'TRFI', 'ry-wc-city-select'),
		_x('Harstad', 'TRFI', 'ry-wc-city-select'),
		_x('Hasvik', 'TRFI', 'ry-wc-city-select'),
		_x('Ibestad', 'TRFI', 'ry-wc-city-select'),
		_x('Kafjord', 'TRFI', 'ry-wc-city-select'),
		_x('Karasjok', 'TRFI', 'ry-wc-city-select'),
		_x('Karlsoy', 'TRFI', 'ry-wc-city-select'),
		_x('Kautokeino', 'TRFI', 'ry-wc-city-select'),
		_x('Kvaefjord', 'TRFI', 'ry-wc-city-select'),
		_x('Kvaenangen', 'TRFI', 'ry-wc-city-select'),
		_x('Lavangen', 'TRFI', 'ry-wc-city-select'),
		_x('Lebesby', 'TRFI', 'ry-wc-city-select'),
		_x('Loppa', 'TRFI', 'ry-wc-city-select'),
		_x('Lyngen', 'TRFI', 'ry-wc-city-select'),
		_x('Malselv', 'TRFI', 'ry-wc-city-select'),
		_x('Masoy', 'TRFI', 'ry-wc-city-select'),
		_x('Nesseby', 'TRFI', 'ry-wc-city-select'),
		_x('Nordkapp', 'TRFI', 'ry-wc-city-select'),
		_x('Nordreisa', 'TRFI', 'ry-wc-city-select'),
		_x('Porsanger', 'TRFI', 'ry-wc-city-select'),
		_x('Salangen', 'TRFI', 'ry-wc-city-select'),
		_x('Senja', 'TRFI', 'ry-wc-city-select'),
		_x('Skjervoy', 'TRFI', 'ry-wc-city-select'),
		_x('Sor-Varanger', 'TRFI', 'ry-wc-city-select'),
		_x('Sorreisa', 'TRFI', 'ry-wc-city-select'),
		_x('Storfjord', 'TRFI', 'ry-wc-city-select'),
		_x('Tana', 'TRFI', 'ry-wc-city-select'),
		_x('Tjeldsund', 'TRFI', 'ry-wc-city-select'),
		_x('Tromso', 'TRFI', 'ry-wc-city-select'),
		_x('Vadso', 'TRFI', 'ry-wc-city-select'),
		_x('Vardo', 'TRFI', 'ry-wc-city-select'),
	],
	'TR' => [
		_x('Afjord', 'TR', 'ry-wc-city-select'),
		_x('Flatanger', 'TR', 'ry-wc-city-select'),
		_x('Frosta', 'TR', 'ry-wc-city-select'),
		_x('Froya', 'TR', 'ry-wc-city-select'),
		_x('Grong', 'TR', 'ry-wc-city-select'),
		_x('Heim', 'TR', 'ry-wc-city-select'),
		_x('Hitra', 'TR', 'ry-wc-city-select'),
		_x('Holtalen', 'TR', 'ry-wc-city-select'),
		_x('Hoylandet', 'TR', 'ry-wc-city-select'),
		_x('Inderoy', 'TR', 'ry-wc-city-select'),
		_x('Indre Fosen', 'TR', 'ry-wc-city-select'),
		_x('Leka', 'TR', 'ry-wc-city-select'),
		_x('Levanger', 'TR', 'ry-wc-city-select'),
		_x('Lierne', 'TR', 'ry-wc-city-select'),
		_x('Malvik', 'TR', 'ry-wc-city-select'),
		_x('Melhus', 'TR', 'ry-wc-city-select'),
		_x('Meraker', 'TR', 'ry-wc-city-select'),
		_x('Midtre Gauldal', 'TR', 'ry-wc-city-select'),
		_x('Naeroysund', 'TR', 'ry-wc-city-select'),
		_x('Namsos', 'TR', 'ry-wc-city-select'),
		_x('Namsskogan', 'TR', 'ry-wc-city-select'),
		_x('Oppdal', 'TR', 'ry-wc-city-select'),
		_x('Orkland', 'TR', 'ry-wc-city-select'),
		_x('Orland', 'TR', 'ry-wc-city-select'),
		_x('Osen', 'TR', 'ry-wc-city-select'),
		_x('Overhalla', 'TR', 'ry-wc-city-select'),
		_x('Raarvihke - Royrvik', 'TR', 'ry-wc-city-select'),
		_x('Rennebu', 'TR', 'ry-wc-city-select'),
		_x('Rindal', 'TR', 'ry-wc-city-select'),
		_x('Roros', 'TR', 'ry-wc-city-select'),
		_x('Selbu', 'TR', 'ry-wc-city-select'),
		_x('Skaun', 'TR', 'ry-wc-city-select'),
		_x('Snaase - Snasa', 'TR', 'ry-wc-city-select'),
		_x('Steinkjer', 'TR', 'ry-wc-city-select'),
		_x('Stjordal', 'TR', 'ry-wc-city-select'),
		_x('Trondheim', 'TR', 'ry-wc-city-select'),
		_x('Tydal', 'TR', 'ry-wc-city-select'),
		_x('Verdal', 'TR', 'ry-wc-city-select'),
	],
	'VETE' => [
		_x('Bamble', 'VETE', 'ry-wc-city-select'),
		_x('Drangedal', 'VETE', 'ry-wc-city-select'),
		_x('Faerder', 'VETE', 'ry-wc-city-select'),
		_x('Fyresdal', 'VETE', 'ry-wc-city-select'),
		_x('Hjartdal', 'VETE', 'ry-wc-city-select'),
		_x('Holmestrand', 'VETE', 'ry-wc-city-select'),
		_x('Horten', 'VETE', 'ry-wc-city-select'),
		_x('Kragero', 'VETE', 'ry-wc-city-select'),
		_x('Kviteseid', 'VETE', 'ry-wc-city-select'),
		_x('Larvik', 'VETE', 'ry-wc-city-select'),
		_x('Midt-Telemark', 'VETE', 'ry-wc-city-select'),
		_x('Nissedal', 'VETE', 'ry-wc-city-select'),
		_x('Nome', 'VETE', 'ry-wc-city-select'),
		_x('Notodden', 'VETE', 'ry-wc-city-select'),
		_x('Porsgrunn', 'VETE', 'ry-wc-city-select'),
		_x('Sandefjord', 'VETE', 'ry-wc-city-select'),
		_x('Seljord', 'VETE', 'ry-wc-city-select'),
		_x('Siljan', 'VETE', 'ry-wc-city-select'),
		_x('Skien', 'VETE', 'ry-wc-city-select'),
		_x('Tinn', 'VETE', 'ry-wc-city-select'),
		_x('Tokke', 'VETE', 'ry-wc-city-select'),
		_x('Tonsberg', 'VETE', 'ry-wc-city-select'),
		_x('Vinje', 'VETE', 'ry-wc-city-select'),
	],
	'VE' => [
		_x('Alver', 'VE', 'ry-wc-city-select'),
		_x('Ardal', 'VE', 'ry-wc-city-select'),
		_x('Askoy', 'VE', 'ry-wc-city-select'),
		_x('Askvoll', 'VE', 'ry-wc-city-select'),
		_x('Aurland', 'VE', 'ry-wc-city-select'),
		_x('Austevoll', 'VE', 'ry-wc-city-select'),
		_x('Austrheim', 'VE', 'ry-wc-city-select'),
		_x('Bergen', 'VE', 'ry-wc-city-select'),
		_x('Bjornafjorden', 'VE', 'ry-wc-city-select'),
		_x('Bomlo', 'VE', 'ry-wc-city-select'),
		_x('Bremanger', 'VE', 'ry-wc-city-select'),
		_x('Eidfjord', 'VE', 'ry-wc-city-select'),
		_x('Etne', 'VE', 'ry-wc-city-select'),
		_x('Fedje', 'VE', 'ry-wc-city-select'),
		_x('Fitjar', 'VE', 'ry-wc-city-select'),
		_x('Fjaler', 'VE', 'ry-wc-city-select'),
		_x('Gloppen', 'VE', 'ry-wc-city-select'),
		_x('Gulen', 'VE', 'ry-wc-city-select'),
		_x('Hoyanger', 'VE', 'ry-wc-city-select'),
		_x('Hyllestad', 'VE', 'ry-wc-city-select'),
		_x('Kinn', 'VE', 'ry-wc-city-select'),
		_x('Kvam', 'VE', 'ry-wc-city-select'),
		_x('Kvinnherad', 'VE', 'ry-wc-city-select'),
		_x('Laerdal', 'VE', 'ry-wc-city-select'),
		_x('Luster', 'VE', 'ry-wc-city-select'),
		_x('Masfjorden', 'VE', 'ry-wc-city-select'),
		_x('Modalen', 'VE', 'ry-wc-city-select'),
		_x('Osteroy', 'VE', 'ry-wc-city-select'),
		_x('Oygarden', 'VE', 'ry-wc-city-select'),
		_x('Samnanger', 'VE', 'ry-wc-city-select'),
		_x('Sogndal', 'VE', 'ry-wc-city-select'),
		_x('Solund', 'VE', 'ry-wc-city-select'),
		_x('Stad', 'VE', 'ry-wc-city-select'),
		_x('Stord', 'VE', 'ry-wc-city-select'),
		_x('Stryn', 'VE', 'ry-wc-city-select'),
		_x('Sunnfjord', 'VE', 'ry-wc-city-select'),
		_x('Sveio', 'VE', 'ry-wc-city-select'),
		_x('Tysnes', 'VE', 'ry-wc-city-select'),
		_x('Ullensvang', 'VE', 'ry-wc-city-select'),
		_x('Ulvik', 'VE', 'ry-wc-city-select'),
		_x('Vaksdal', 'VE', 'ry-wc-city-select'),
		_x('Vik', 'VE', 'ry-wc-city-select'),
		_x('Voss', 'VE', 'ry-wc-city-select'),
	],
	'VI' => [
		_x('Al', 'VI', 'ry-wc-city-select'),
		_x('Aremark', 'VI', 'ry-wc-city-select'),
		_x('As', 'VI', 'ry-wc-city-select'),
		_x('Asker', 'VI', 'ry-wc-city-select'),
		_x('Aurskog-Holand', 'VI', 'ry-wc-city-select'),
		_x('Baerum', 'VI', 'ry-wc-city-select'),
		_x('Drammen', 'VI', 'ry-wc-city-select'),
		_x('Eidsvoll', 'VI', 'ry-wc-city-select'),
		_x('Enebakk', 'VI', 'ry-wc-city-select'),
		_x('Fla', 'VI', 'ry-wc-city-select'),
		_x('Flesberg', 'VI', 'ry-wc-city-select'),
		_x('Fredrikstad', 'VI', 'ry-wc-city-select'),
		_x('Frogn', 'VI', 'ry-wc-city-select'),
		_x('Gjerdrum', 'VI', 'ry-wc-city-select'),
		_x('Gol', 'VI', 'ry-wc-city-select'),
		_x('Halden', 'VI', 'ry-wc-city-select'),
		_x('Hemsedal', 'VI', 'ry-wc-city-select'),
		_x('Hol', 'VI', 'ry-wc-city-select'),
		_x('Hole', 'VI', 'ry-wc-city-select'),
		_x('Hurdal', 'VI', 'ry-wc-city-select'),
		_x('Hvaler', 'VI', 'ry-wc-city-select'),
		_x('Indre Ostfold', 'VI', 'ry-wc-city-select'),
		_x('Jevnaker', 'VI', 'ry-wc-city-select'),
		_x('Kongsberg', 'VI', 'ry-wc-city-select'),
		_x('Krodsherad', 'VI', 'ry-wc-city-select'),
		_x('Lier', 'VI', 'ry-wc-city-select'),
		_x('Lillestrom', 'VI', 'ry-wc-city-select'),
		_x('Lorenskog', 'VI', 'ry-wc-city-select'),
		_x('Lunner', 'VI', 'ry-wc-city-select'),
		_x('Marker', 'VI', 'ry-wc-city-select'),
		_x('Modum', 'VI', 'ry-wc-city-select'),
		_x('Moss', 'VI', 'ry-wc-city-select'),
		_x('Nannestad', 'VI', 'ry-wc-city-select'),
		_x('Nes', 'VI', 'ry-wc-city-select'),
		_x('Nesbyen', 'VI', 'ry-wc-city-select'),
		_x('Nesodden', 'VI', 'ry-wc-city-select'),
		_x('Nittedal', 'VI', 'ry-wc-city-select'),
		_x('Nordre Follo', 'VI', 'ry-wc-city-select'),
		_x('Nore og Uvdal', 'VI', 'ry-wc-city-select'),
		_x('Ovre Eiker', 'VI', 'ry-wc-city-select'),
		_x('Rade', 'VI', 'ry-wc-city-select'),
		_x('Raelingen', 'VI', 'ry-wc-city-select'),
		_x('Rakkestad', 'VI', 'ry-wc-city-select'),
		_x('Ringerike', 'VI', 'ry-wc-city-select'),
		_x('Rollag', 'VI', 'ry-wc-city-select'),
		_x('Sarpsborg', 'VI', 'ry-wc-city-select'),
		_x('Sigdal', 'VI', 'ry-wc-city-select'),
		_x('Skiptvet', 'VI', 'ry-wc-city-select'),
		_x('Ullensaker', 'VI', 'ry-wc-city-select'),
		_x('Valer', 'VI', 'ry-wc-city-select'),
		_x('Vestby', 'VI', 'ry-wc-city-select'),
	],
	]
];