<?php
/**
 * Federal Democratic Republic of Nepal places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'NP' => [
	'AC' => [
		_x('Bannigadi Jayagadh', 'AC', 'ry-wc-city-select'),
		_x('Chaurpati', 'AC', 'ry-wc-city-select'),
		_x('Dhakari', 'AC', 'ry-wc-city-select'),
		_x('Kamalbazar', 'AC', 'ry-wc-city-select'),
		_x('Mangalsen', 'AC', 'ry-wc-city-select'),
		_x('Mellekh', 'AC', 'ry-wc-city-select'),
		_x('Panchadewal Binayak', 'AC', 'ry-wc-city-select'),
		_x('Ramaroshan', 'AC', 'ry-wc-city-select'),
		_x('Sanphebagar', 'AC', 'ry-wc-city-select'),
		_x('Turmakhad', 'AC', 'ry-wc-city-select'),
	],
	'AR' => [
		_x('Bhumikasthan', 'AR', 'ry-wc-city-select'),
		_x('Chattradev', 'AR', 'ry-wc-city-select'),
		_x('Malarani', 'AR', 'ry-wc-city-select'),
		_x('Panini', 'AR', 'ry-wc-city-select'),
		_x('Sandhikharka', 'AR', 'ry-wc-city-select'),
		_x('Sitaganga', 'AR', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Badigad', 'BA', 'ry-wc-city-select'),
		_x('Baglung', 'BA', 'ry-wc-city-select'),
		_x('Dhorpatan', 'BA', 'ry-wc-city-select'),
		_x('Galkot', 'BA', 'ry-wc-city-select'),
		_x('Jaimuni', 'BA', 'ry-wc-city-select'),
		_x('Kathekhola', 'BA', 'ry-wc-city-select'),
		_x('Nisikhola', 'BA', 'ry-wc-city-select'),
		_x('Tamankhola', 'BA', 'ry-wc-city-select'),
		_x('Tarakhola', 'BA', 'ry-wc-city-select'),
		_x('Woreng', 'BA', 'ry-wc-city-select'),
	],
	'BA2' => [
		_x('Dasarathchand', 'BA2', 'ry-wc-city-select'),
		_x('Dilasaini', 'BA2', 'ry-wc-city-select'),
		_x('Dogadakedar', 'BA2', 'ry-wc-city-select'),
		_x('Melauli', 'BA2', 'ry-wc-city-select'),
		_x('Pancheswar', 'BA2', 'ry-wc-city-select'),
		_x('Patan', 'BA2', 'ry-wc-city-select'),
		_x('Purchaudi', 'BA2', 'ry-wc-city-select'),
		_x('Shivanath', 'BA2', 'ry-wc-city-select'),
		_x('Sigas', 'BA2', 'ry-wc-city-select'),
		_x('Surnaya', 'BA2', 'ry-wc-city-select'),
	],
	'BA3' => [
		_x('Bithadchir', 'BA3', 'ry-wc-city-select'),
		_x('Bungal', 'BA3', 'ry-wc-city-select'),
		_x('Chabispathivera', 'BA3', 'ry-wc-city-select'),
		_x('Durgathali', 'BA3', 'ry-wc-city-select'),
		_x('Jayaprithivi', 'BA3', 'ry-wc-city-select'),
		_x('Kanda', 'BA3', 'ry-wc-city-select'),
		_x('Kedarseu', 'BA3', 'ry-wc-city-select'),
		_x('Khaptachhanna', 'BA3', 'ry-wc-city-select'),
		_x('Masta', 'BA3', 'ry-wc-city-select'),
		_x('Surma', 'BA3', 'ry-wc-city-select'),
		_x('Talkot', 'BA3', 'ry-wc-city-select'),
		_x('Thalara', 'BA3', 'ry-wc-city-select'),
	],
	'BA4' => [
		_x('Badimalika', 'BA4', 'ry-wc-city-select'),
		_x('Budhiganga', 'BA4', 'ry-wc-city-select'),
		_x('Budhinanda', 'BA4', 'ry-wc-city-select'),
		_x('Chhededaha', 'BA4', 'ry-wc-city-select'),
		_x('Gaumul', 'BA4', 'ry-wc-city-select'),
		_x('Himali', 'BA4', 'ry-wc-city-select'),
		_x('Pandav Ghupa', 'BA4', 'ry-wc-city-select'),
		_x('Swami Kartik', 'BA4', 'ry-wc-city-select'),
		_x('Tribeni', 'BA4', 'ry-wc-city-select'),
	],
	'BA5' => [
		_x('Baijanath', 'BA5', 'ry-wc-city-select'),
		_x('Duduwa', 'BA5', 'ry-wc-city-select'),
		_x('Janaki', 'BA5', 'ry-wc-city-select'),
		_x('Khajura', 'BA5', 'ry-wc-city-select'),
		_x('Kohalpur', 'BA5', 'ry-wc-city-select'),
		_x('Narainapur', 'BA5', 'ry-wc-city-select'),
		_x('Nepalganj', 'BA5', 'ry-wc-city-select'),
		_x('Raptisonari', 'BA5', 'ry-wc-city-select'),
	],
	'BA6' => [
		_x('Adarshkotwal', 'BA6', 'ry-wc-city-select'),
		_x('Baragadhi', 'BA6', 'ry-wc-city-select'),
		_x('Devtal', 'BA6', 'ry-wc-city-select'),
		_x('Jitpur Simara', 'BA6', 'ry-wc-city-select'),
		_x('Kaliya', 'BA6', 'ry-wc-city-select'),
		_x('Karaiyamai', 'BA6', 'ry-wc-city-select'),
		_x('Kolhabi', 'BA6', 'ry-wc-city-select'),
		_x('Mahagadhimai', 'BA6', 'ry-wc-city-select'),
		_x('Nijgadh', 'BA6', 'ry-wc-city-select'),
		_x('Pacharauta', 'BA6', 'ry-wc-city-select'),
		_x('Parwanipur', 'BA6', 'ry-wc-city-select'),
		_x('Pheta', 'BA6', 'ry-wc-city-select'),
		_x('Prasauni', 'BA6', 'ry-wc-city-select'),
		_x('Simraungadh', 'BA6', 'ry-wc-city-select'),
		_x('Suwarna', 'BA6', 'ry-wc-city-select'),
	],
	'BA7' => [
		_x('Badhaiyatal', 'BA7', 'ry-wc-city-select'),
		_x('Bansagadhi', 'BA7', 'ry-wc-city-select'),
		_x('Bansagadhi', 'BA7', 'ry-wc-city-select'),
		_x('Barbardiya', 'BA7', 'ry-wc-city-select'),
		_x('Bardiya', 'BA7', 'ry-wc-city-select'),
		_x('Geruwa', 'BA7', 'ry-wc-city-select'),
		_x('Gulariya', 'BA7', 'ry-wc-city-select'),
		_x('Madhuwan', 'BA7', 'ry-wc-city-select'),
		_x('Rajapur', 'BA7', 'ry-wc-city-select'),
		_x('Thakurbaba', 'BA7', 'ry-wc-city-select'),
	],
	'BH' => [
		_x('Bhaktapur', 'BH', 'ry-wc-city-select'),
		_x('Changunarayan', 'BH', 'ry-wc-city-select'),
		_x('Madhyapur Thimi', 'BH', 'ry-wc-city-select'),
		_x('Suryabinayak', 'BH', 'ry-wc-city-select'),
	],
	'BH2' => [
		_x('Aamchowk', 'BH2', 'ry-wc-city-select'),
		_x('Arun', 'BH2', 'ry-wc-city-select'),
		_x('Bhojpur', 'BH2', 'ry-wc-city-select'),
		_x('Hatuwagadhi', 'BH2', 'ry-wc-city-select'),
		_x('Pauwadungma', 'BH2', 'ry-wc-city-select'),
		_x('Ramprasad Rai', 'BH2', 'ry-wc-city-select'),
		_x('Salpasilichho', 'BH2', 'ry-wc-city-select'),
		_x('Shadananda', 'BH2', 'ry-wc-city-select'),
		_x('Tyamkemaiyung', 'BH2', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Bharatpur', 'CH', 'ry-wc-city-select'),
		_x('Ichchhyakamana', 'CH', 'ry-wc-city-select'),
		_x('Kalika', 'CH', 'ry-wc-city-select'),
		_x('Khairahani', 'CH', 'ry-wc-city-select'),
		_x('Madi', 'CH', 'ry-wc-city-select'),
		_x('Rapti', 'CH', 'ry-wc-city-select'),
		_x('Ratnanagar', 'CH', 'ry-wc-city-select'),
	],
	'DA' => [
		_x('Ajaymeru', 'DA', 'ry-wc-city-select'),
		_x('Alital', 'DA', 'ry-wc-city-select'),
		_x('Amargadhi', 'DA', 'ry-wc-city-select'),
		_x('Bhageshwar', 'DA', 'ry-wc-city-select'),
		_x('Ganyapadhura', 'DA', 'ry-wc-city-select'),
		_x('Nawadurga', 'DA', 'ry-wc-city-select'),
		_x('Parashuram', 'DA', 'ry-wc-city-select'),
	],
	'DA2' => [
		_x('Aathbis Nagarpalika', 'DA2', 'ry-wc-city-select'),
		_x('Bhagawatimai', 'DA2', 'ry-wc-city-select'),
		_x('Bhairabi', 'DA2', 'ry-wc-city-select'),
		_x('Chamunda Bindrasaini', 'DA2', 'ry-wc-city-select'),
		_x('Dullu', 'DA2', 'ry-wc-city-select'),
		_x('Dungeshwor', 'DA2', 'ry-wc-city-select'),
		_x('Gurans', 'DA2', 'ry-wc-city-select'),
		_x('Mahabu', 'DA2', 'ry-wc-city-select'),
		_x('Narayan', 'DA2', 'ry-wc-city-select'),
		_x('Naumule', 'DA2', 'ry-wc-city-select'),
		_x('Thantikandh Gaunpalika', 'DA2', 'ry-wc-city-select'),
	],
	'DA3' => [
		_x('Babai', 'DA3', 'ry-wc-city-select'),
		_x('Banglachuli', 'DA3', 'ry-wc-city-select'),
		_x('Dangisharan', 'DA3', 'ry-wc-city-select'),
		_x('Gadwa', 'DA3', 'ry-wc-city-select'),
		_x('Ghorahi', 'DA3', 'ry-wc-city-select'),
		_x('Lamhi', 'DA3', 'ry-wc-city-select'),
		_x('Rajpur', 'DA3', 'ry-wc-city-select'),
		_x('Rapti', 'DA3', 'ry-wc-city-select'),
		_x('Shantinagar', 'DA3', 'ry-wc-city-select'),
		_x('Tulsipur', 'DA3', 'ry-wc-city-select'),
	],
	'DA4' => [
		_x('Apihimal', 'DA4', 'ry-wc-city-select'),
		_x('Byas', 'DA4', 'ry-wc-city-select'),
		_x('Dunhu', 'DA4', 'ry-wc-city-select'),
		_x('Lekam', 'DA4', 'ry-wc-city-select'),
		_x('Mahakali', 'DA4', 'ry-wc-city-select'),
		_x('Malikarjun', 'DA4', 'ry-wc-city-select'),
		_x('Marma', 'DA4', 'ry-wc-city-select'),
		_x('Naugad', 'DA4', 'ry-wc-city-select'),
		_x('Shailyashikhar', 'DA4', 'ry-wc-city-select'),
	],
	'DH' => [
		_x('Benighat Rorang', 'DH', 'ry-wc-city-select'),
		_x('Dhunibesi', 'DH', 'ry-wc-city-select'),
		_x('Gajuri', 'DH', 'ry-wc-city-select'),
		_x('Galchi', 'DH', 'ry-wc-city-select'),
		_x('Gangajamuna', 'DH', 'ry-wc-city-select'),
		_x('Jwalamukhi', 'DH', 'ry-wc-city-select'),
		_x('Khaniyabas', 'DH', 'ry-wc-city-select'),
		_x('Netrawati', 'DH', 'ry-wc-city-select'),
		_x('Nilkantha', 'DH', 'ry-wc-city-select'),
		_x('Rubi Valley', 'DH', 'ry-wc-city-select'),
		_x('Siddhalek', 'DH', 'ry-wc-city-select'),
		_x('Thakre', 'DH', 'ry-wc-city-select'),
		_x('Tripurasundari', 'DH', 'ry-wc-city-select'),
	],
	'DH2' => [
		_x('Chaubise', 'DH2', 'ry-wc-city-select'),
		_x('Chhathar Jorpati', 'DH2', 'ry-wc-city-select'),
		_x('Dhankuta', 'DH2', 'ry-wc-city-select'),
		_x('Khalsa Chhintang Shahidbhumi', 'DH2', 'ry-wc-city-select'),
		_x('Mahalaxmi', 'DH2', 'ry-wc-city-select'),
		_x('Pakhribas', 'DH2', 'ry-wc-city-select'),
		_x('Sagurigadhi', 'DH2', 'ry-wc-city-select'),
	],
	'DH3' => [
		_x('Aaurahi', 'DH3', 'ry-wc-city-select'),
		_x('Bateshwor', 'DH3', 'ry-wc-city-select'),
		_x('Bideha', 'DH3', 'ry-wc-city-select'),
		_x('Chhireshwornath', 'DH3', 'ry-wc-city-select'),
		_x('Dhanusadham', 'DH3', 'ry-wc-city-select'),
		_x('Ganeshman Charnath', 'DH3', 'ry-wc-city-select'),
		_x('Hansapur Kathapulla', 'DH3', 'ry-wc-city-select'),
		_x('Janaknandani', 'DH3', 'ry-wc-city-select'),
		_x('Janakpur', 'DH3', 'ry-wc-city-select'),
		_x('Kamala Siddhidatri', 'DH3', 'ry-wc-city-select'),
		_x('Lakshminiya', 'DH3', 'ry-wc-city-select'),
		_x('Mithila', 'DH3', 'ry-wc-city-select'),
		_x('Mithila Bihari', 'DH3', 'ry-wc-city-select'),
		_x('Mukhiyapatti Musarmiya', 'DH3', 'ry-wc-city-select'),
		_x('Nagarain', 'DH3', 'ry-wc-city-select'),
		_x('Sabaila', 'DH3', 'ry-wc-city-select'),
		_x('Sahidnagar', 'DH3', 'ry-wc-city-select'),
	],
	'DO' => [
		_x('Baiteshwor', 'DO', 'ry-wc-city-select'),
		_x('Bhimeshwor', 'DO', 'ry-wc-city-select'),
		_x('Bigu', 'DO', 'ry-wc-city-select'),
		_x('Gaurishankar', 'DO', 'ry-wc-city-select'),
		_x('Jiri', 'DO', 'ry-wc-city-select'),
		_x('Kalinchok', 'DO', 'ry-wc-city-select'),
		_x('Melung', 'DO', 'ry-wc-city-select'),
		_x('Sailung', 'DO', 'ry-wc-city-select'),
		_x('Tamakoshi', 'DO', 'ry-wc-city-select'),
	],
	'DO2' => [
		_x('Chharka Tangsong', 'DO2', 'ry-wc-city-select'),
		_x('Dolpo Buddha', 'DO2', 'ry-wc-city-select'),
		_x('Jagadulla', 'DO2', 'ry-wc-city-select'),
		_x('Kaike', 'DO2', 'ry-wc-city-select'),
		_x('Mudkechula', 'DO2', 'ry-wc-city-select'),
		_x('She Foksundo', 'DO2', 'ry-wc-city-select'),
		_x('Thuli Bheri', 'DO2', 'ry-wc-city-select'),
		_x('Tripurasundari', 'DO2', 'ry-wc-city-select'),
	],
	'DO3' => [
		_x('Adharsha', 'DO3', 'ry-wc-city-select'),
		_x('Badikedar', 'DO3', 'ry-wc-city-select'),
		_x('Bogtan', 'DO3', 'ry-wc-city-select'),
		_x('Dipayal Silgadi', 'DO3', 'ry-wc-city-select'),
		_x('Jorayal', 'DO3', 'ry-wc-city-select'),
		_x('Purbichauki', 'DO3', 'ry-wc-city-select'),
		_x('Sayal', 'DO3', 'ry-wc-city-select'),
		_x('Shikhar', 'DO3', 'ry-wc-city-select'),
		_x('k i Singh', 'DO3', 'ry-wc-city-select'),
	],
	'GO' => [
		_x('Aarughat', 'GO', 'ry-wc-city-select'),
		_x('Ajirkot', 'GO', 'ry-wc-city-select'),
		_x('Bhimsen', 'GO', 'ry-wc-city-select'),
		_x('Chumnuwri', 'GO', 'ry-wc-city-select'),
		_x('Dharche', 'GO', 'ry-wc-city-select'),
		_x('Gandaki', 'GO', 'ry-wc-city-select'),
		_x('Gorkha', 'GO', 'ry-wc-city-select'),
		_x('Palungtar', 'GO', 'ry-wc-city-select'),
		_x('Sahid Lakhan', 'GO', 'ry-wc-city-select'),
		_x('Siranchok', 'GO', 'ry-wc-city-select'),
		_x('Sulikot', 'GO', 'ry-wc-city-select'),
	],
	'GU' => [
		_x('Chandrakot', 'GU', 'ry-wc-city-select'),
		_x('Chatrakot', 'GU', 'ry-wc-city-select'),
		_x('Dhurkot', 'GU', 'ry-wc-city-select'),
		_x('Gulmidarbar', 'GU', 'ry-wc-city-select'),
		_x('Isma', 'GU', 'ry-wc-city-select'),
		_x('Kaligandaki', 'GU', 'ry-wc-city-select'),
		_x('Madane', 'GU', 'ry-wc-city-select'),
		_x('Malika', 'GU', 'ry-wc-city-select'),
		_x('Musikot', 'GU', 'ry-wc-city-select'),
		_x('Resunga', 'GU', 'ry-wc-city-select'),
		_x('Ruru', 'GU', 'ry-wc-city-select'),
		_x('Satyawati', 'GU', 'ry-wc-city-select'),
	],
	'HU' => [
		_x('Adanchuli', 'HU', 'ry-wc-city-select'),
		_x('Chankheli', 'HU', 'ry-wc-city-select'),
		_x('Kharpunath', 'HU', 'ry-wc-city-select'),
		_x('Namkha', 'HU', 'ry-wc-city-select'),
		_x('Sarkegad', 'HU', 'ry-wc-city-select'),
		_x('Simkot', 'HU', 'ry-wc-city-select'),
		_x('Tanjakot', 'HU', 'ry-wc-city-select'),
	],
	'IL' => [
		_x('Chulachuli', 'IL', 'ry-wc-city-select'),
		_x('Deumai', 'IL', 'ry-wc-city-select'),
		_x('Fakphokthum', 'IL', 'ry-wc-city-select'),
		_x('Ilam', 'IL', 'ry-wc-city-select'),
		_x('Mai', 'IL', 'ry-wc-city-select'),
		_x('Maijogmai', 'IL', 'ry-wc-city-select'),
		_x('Mangsebung', 'IL', 'ry-wc-city-select'),
		_x('Rong', 'IL', 'ry-wc-city-select'),
		_x('Sandakpur', 'IL', 'ry-wc-city-select'),
		_x('Suryodaya', 'IL', 'ry-wc-city-select'),
	],
	'JA' => [
		_x('Barekot Gaunpalika', 'JA', 'ry-wc-city-select'),
		_x('Bheri', 'JA', 'ry-wc-city-select'),
		_x('Chhedagad', 'JA', 'ry-wc-city-select'),
		_x('Junichande', 'JA', 'ry-wc-city-select'),
		_x('Kuse', 'JA', 'ry-wc-city-select'),
		_x('Shiwalaya', 'JA', 'ry-wc-city-select'),
		_x('Tribeni Nalagad', 'JA', 'ry-wc-city-select'),
	],
	'JH' => [
		_x('Arjundhara', 'JH', 'ry-wc-city-select'),
		_x('Bhadrapur', 'JH', 'ry-wc-city-select'),
		_x('Birtamod', 'JH', 'ry-wc-city-select'),
		_x('Buddhashanti', 'JH', 'ry-wc-city-select'),
		_x('Damak', 'JH', 'ry-wc-city-select'),
		_x('Garhadashi', 'JH', 'ry-wc-city-select'),
		_x('Gauradhaha', 'JH', 'ry-wc-city-select'),
		_x('Gauriganj', 'JH', 'ry-wc-city-select'),
		_x('Haldibari', 'JH', 'ry-wc-city-select'),
		_x('Jhapa', 'JH', 'ry-wc-city-select'),
		_x('Kachankawal', 'JH', 'ry-wc-city-select'),
		_x('Kamal', 'JH', 'ry-wc-city-select'),
		_x('Kankai', 'JH', 'ry-wc-city-select'),
		_x('Mechinagar', 'JH', 'ry-wc-city-select'),
		_x('Shivasataxi', 'JH', 'ry-wc-city-select'),
	],
	'JU' => [
		_x('Chandannath', 'JU', 'ry-wc-city-select'),
		_x('Guthichaur', 'JU', 'ry-wc-city-select'),
		_x('Hima', 'JU', 'ry-wc-city-select'),
		_x('Kankasundari Gaunpalika', 'JU', 'ry-wc-city-select'),
		_x('Patarasi', 'JU', 'ry-wc-city-select'),
		_x('Sinja', 'JU', 'ry-wc-city-select'),
		_x('Tatopani', 'JU', 'ry-wc-city-select'),
		_x('Tatopani', 'JU', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Bardagariya', 'KA', 'ry-wc-city-select'),
		_x('Bhajani', 'KA', 'ry-wc-city-select'),
		_x('Chure', 'KA', 'ry-wc-city-select'),
		_x('Dhangadhi', 'KA', 'ry-wc-city-select'),
		_x('Gadawari', 'KA', 'ry-wc-city-select'),
		_x('Gauriganga', 'KA', 'ry-wc-city-select'),
		_x('Ghodaghodi', 'KA', 'ry-wc-city-select'),
		_x('Janaki', 'KA', 'ry-wc-city-select'),
		_x('Joshipur', 'KA', 'ry-wc-city-select'),
		_x('Kailari', 'KA', 'ry-wc-city-select'),
		_x('Karnali', 'KA', 'ry-wc-city-select'),
		_x('Mohanyal', 'KA', 'ry-wc-city-select'),
		_x('Tikapur', 'KA', 'ry-wc-city-select'),
	],
	'KA2' => [
		_x('Kalika', 'KA2', 'ry-wc-city-select'),
		_x('Khandachakra', 'KA2', 'ry-wc-city-select'),
		_x('Mahawai', 'KA2', 'ry-wc-city-select'),
		_x('Naraharinath', 'KA2', 'ry-wc-city-select'),
		_x('Pachaljharana', 'KA2', 'ry-wc-city-select'),
		_x('Palata', 'KA2', 'ry-wc-city-select'),
		_x('Raskot', 'KA2', 'ry-wc-city-select'),
		_x('Sanni Tribeni', 'KA2', 'ry-wc-city-select'),
		_x('Tilagufa', 'KA2', 'ry-wc-city-select'),
	],
	'KA3' => [
		_x('Bedkot', 'KA3', 'ry-wc-city-select'),
		_x('Belauri', 'KA3', 'ry-wc-city-select'),
		_x('Beldandi', 'KA3', 'ry-wc-city-select'),
		_x('Bhimdatta', 'KA3', 'ry-wc-city-select'),
		_x('Krishnapur', 'KA3', 'ry-wc-city-select'),
		_x('Laljhadi', 'KA3', 'ry-wc-city-select'),
		_x('Mahakali', 'KA3', 'ry-wc-city-select'),
		_x('Punarbas', 'KA3', 'ry-wc-city-select'),
		_x('Suklaphat', 'KA3', 'ry-wc-city-select'),
		_x('Suklaphata', 'KA3', 'ry-wc-city-select'),
	],
	'KA4' => [
		_x('Banganga', 'KA4', 'ry-wc-city-select'),
		_x('Bijayanagar', 'KA4', 'ry-wc-city-select'),
		_x('Buddhabhumi', 'KA4', 'ry-wc-city-select'),
		_x('Kapilvastu', 'KA4', 'ry-wc-city-select'),
		_x('Krishnanagar', 'KA4', 'ry-wc-city-select'),
		_x('Maharajgunj', 'KA4', 'ry-wc-city-select'),
		_x('Mayadevi', 'KA4', 'ry-wc-city-select'),
		_x('Shivraj', 'KA4', 'ry-wc-city-select'),
		_x('Suddhodhan', 'KA4', 'ry-wc-city-select'),
		_x('Yashodhara', 'KA4', 'ry-wc-city-select'),
	],
	'KA5' => [
		_x('Annapurna', 'KA5', 'ry-wc-city-select'),
		_x('Machhapuchchhre', 'KA5', 'ry-wc-city-select'),
		_x('Madi', 'KA5', 'ry-wc-city-select'),
		_x('Pokhara Lekhnath', 'KA5', 'ry-wc-city-select'),
		_x('Rupa', 'KA5', 'ry-wc-city-select'),
	],
	'KA6' => [
		_x('Budhanilakantha', 'KA6', 'ry-wc-city-select'),
		_x('Chandragiri', 'KA6', 'ry-wc-city-select'),
		_x('Dakshinkali', 'KA6', 'ry-wc-city-select'),
		_x('Gokarneshwor', 'KA6', 'ry-wc-city-select'),
		_x('Kageshwori Manahora', 'KA6', 'ry-wc-city-select'),
		_x('Kathmandu', 'KA6', 'ry-wc-city-select'),
		_x('Kirtipur', 'KA6', 'ry-wc-city-select'),
		_x('Nagarjun', 'KA6', 'ry-wc-city-select'),
		_x('Shankharapur', 'KA6', 'ry-wc-city-select'),
		_x('Tarakeshwor', 'KA6', 'ry-wc-city-select'),
		_x('Tokha', 'KA6', 'ry-wc-city-select'),
	],
	'KA7' => [
		_x('Banepa', 'KA7', 'ry-wc-city-select'),
		_x('Bethanchowk', 'KA7', 'ry-wc-city-select'),
		_x('Bhumlu', 'KA7', 'ry-wc-city-select'),
		_x('Chaurideurali', 'KA7', 'ry-wc-city-select'),
		_x('Dhulikhel', 'KA7', 'ry-wc-city-select'),
		_x('Khanikhola', 'KA7', 'ry-wc-city-select'),
		_x('Mahabharat', 'KA7', 'ry-wc-city-select'),
		_x('Mandandeupur', 'KA7', 'ry-wc-city-select'),
		_x('Namobuddha', 'KA7', 'ry-wc-city-select'),
		_x('Panauti', 'KA7', 'ry-wc-city-select'),
		_x('Panchkhal', 'KA7', 'ry-wc-city-select'),
		_x('Roshi', 'KA7', 'ry-wc-city-select'),
		_x('Temal', 'KA7', 'ry-wc-city-select'),
	],
	'KH' => [
		_x('Ainselukharka', 'KH', 'ry-wc-city-select'),
		_x('Barahapokhari', 'KH', 'ry-wc-city-select'),
		_x('Diprung', 'KH', 'ry-wc-city-select'),
		_x('Halesi Tuwachung', 'KH', 'ry-wc-city-select'),
		_x('Jantedhunga', 'KH', 'ry-wc-city-select'),
		_x('Kepilasgadhi', 'KH', 'ry-wc-city-select'),
		_x('Khotehang', 'KH', 'ry-wc-city-select'),
		_x('Lamidanda', 'KH', 'ry-wc-city-select'),
		_x('Rupakot Majhuwagadhi', 'KH', 'ry-wc-city-select'),
		_x('Sakela', 'KH', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Bagmati', 'LA', 'ry-wc-city-select'),
		_x('Godawari', 'LA', 'ry-wc-city-select'),
		_x('Konjyosom', 'LA', 'ry-wc-city-select'),
		_x('Lalitpur', 'LA', 'ry-wc-city-select'),
		_x('Mahalaxmi', 'LA', 'ry-wc-city-select'),
		_x('Mahankal', 'LA', 'ry-wc-city-select'),
	],
	'LA2' => [
		_x('Besishahar', 'LA2', 'ry-wc-city-select'),
		_x('Dordi', 'LA2', 'ry-wc-city-select'),
		_x('Dudhpokhar', 'LA2', 'ry-wc-city-select'),
		_x('Kwholasothar', 'LA2', 'ry-wc-city-select'),
		_x('Madhyanepal', 'LA2', 'ry-wc-city-select'),
		_x('Marsyangdi Gaunpalika', 'LA2', 'ry-wc-city-select'),
		_x('Rainas', 'LA2', 'ry-wc-city-select'),
		_x('Sundarbazar', 'LA2', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Aurahi', 'MA', 'ry-wc-city-select'),
		_x('Balwa', 'MA', 'ry-wc-city-select'),
		_x('Bardibas', 'MA', 'ry-wc-city-select'),
		_x('Bhangaha', 'MA', 'ry-wc-city-select'),
		_x('Ekdanra', 'MA', 'ry-wc-city-select'),
		_x('Gaushala', 'MA', 'ry-wc-city-select'),
		_x('Jaleswor', 'MA', 'ry-wc-city-select'),
		_x('Loharpatti', 'MA', 'ry-wc-city-select'),
		_x('Mahottari', 'MA', 'ry-wc-city-select'),
		_x('Manra', 'MA', 'ry-wc-city-select'),
		_x('Matihani', 'MA', 'ry-wc-city-select'),
		_x('Pipra', 'MA', 'ry-wc-city-select'),
		_x('Ramgopalpur', 'MA', 'ry-wc-city-select'),
		_x('Samsi', 'MA', 'ry-wc-city-select'),
		_x('Sonama', 'MA', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('Bagmati', 'MA2', 'ry-wc-city-select'),
		_x('Bakaiya', 'MA2', 'ry-wc-city-select'),
		_x('Bhimphedi', 'MA2', 'ry-wc-city-select'),
		_x('Hetauda', 'MA2', 'ry-wc-city-select'),
		_x('Indrasarawor', 'MA2', 'ry-wc-city-select'),
		_x('Kailash', 'MA2', 'ry-wc-city-select'),
		_x('Makwanpurgadhi', 'MA2', 'ry-wc-city-select'),
		_x('Manahari', 'MA2', 'ry-wc-city-select'),
		_x('Rakshirang', 'MA2', 'ry-wc-city-select'),
		_x('Thaha', 'MA2', 'ry-wc-city-select'),
	],
	'MA3' => [
		_x('Chame', 'MA3', 'ry-wc-city-select'),
		_x('Narphu', 'MA3', 'ry-wc-city-select'),
		_x('Nashong', 'MA3', 'ry-wc-city-select'),
		_x('Neshang', 'MA3', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Belbari', 'MO', 'ry-wc-city-select'),
		_x('Biratnagar', 'MO', 'ry-wc-city-select'),
		_x('Budhiganga', 'MO', 'ry-wc-city-select'),
		_x('Dhanpalthan', 'MO', 'ry-wc-city-select'),
		_x('Gramthan', 'MO', 'ry-wc-city-select'),
		_x('Jahada', 'MO', 'ry-wc-city-select'),
		_x('Kanepokhari', 'MO', 'ry-wc-city-select'),
		_x('Katahari', 'MO', 'ry-wc-city-select'),
		_x('Kerabari', 'MO', 'ry-wc-city-select'),
		_x('Letang', 'MO', 'ry-wc-city-select'),
		_x('Miklajunga', 'MO', 'ry-wc-city-select'),
		_x('Pathrisanishchare', 'MO', 'ry-wc-city-select'),
		_x('Rangeli', 'MO', 'ry-wc-city-select'),
		_x('Ratuwamai', 'MO', 'ry-wc-city-select'),
		_x('Sunawarshi', 'MO', 'ry-wc-city-select'),
		_x('Sundarharicha', 'MO', 'ry-wc-city-select'),
		_x('Uralabari', 'MO', 'ry-wc-city-select'),
	],
	'MU' => [
		_x('Chhayanath Rara', 'MU', 'ry-wc-city-select'),
		_x('Khatyad', 'MU', 'ry-wc-city-select'),
		_x('Mugum Karmarong', 'MU', 'ry-wc-city-select'),
		_x('Soru', 'MU', 'ry-wc-city-select'),
	],
	'MU2' => [
		_x('Barhagaun Muktichhetra', 'MU2', 'ry-wc-city-select'),
		_x('Dalome', 'MU2', 'ry-wc-city-select'),
		_x('Gharapjhong', 'MU2', 'ry-wc-city-select'),
		_x('Lomanthang', 'MU2', 'ry-wc-city-select'),
		_x('Thasang', 'MU2', 'ry-wc-city-select'),
	],
	'MY' => [
		_x('Annapurna', 'MY', 'ry-wc-city-select'),
		_x('Beni', 'MY', 'ry-wc-city-select'),
		_x('Dhawalagiri Gaunpalika', 'MY', 'ry-wc-city-select'),
		_x('Malika', 'MY', 'ry-wc-city-select'),
		_x('Mangala', 'MY', 'ry-wc-city-select'),
		_x('Raghuganga', 'MY', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Binayee', 'NA', 'ry-wc-city-select'),
		_x('Bulingtar', 'NA', 'ry-wc-city-select'),
		_x('Bungdikali', 'NA', 'ry-wc-city-select'),
		_x('Devchuli', 'NA', 'ry-wc-city-select'),
		_x('Gaidakot', 'NA', 'ry-wc-city-select'),
		_x('Hupsekot', 'NA', 'ry-wc-city-select'),
		_x('Kawasoti', 'NA', 'ry-wc-city-select'),
		_x('Madhyabindu', 'NA', 'ry-wc-city-select'),
	],
	'NU' => [
		_x('Belkotgadhi', 'NU', 'ry-wc-city-select'),
		_x('Bidur', 'NU', 'ry-wc-city-select'),
		_x('Dupcheshwar', 'NU', 'ry-wc-city-select'),
		_x('Kakani', 'NU', 'ry-wc-city-select'),
		_x('Kispang', 'NU', 'ry-wc-city-select'),
		_x('Likhu', 'NU', 'ry-wc-city-select'),
		_x('Meghang', 'NU', 'ry-wc-city-select'),
		_x('Panchakanya', 'NU', 'ry-wc-city-select'),
		_x('Shivapuri', 'NU', 'ry-wc-city-select'),
		_x('Suryagadhi', 'NU', 'ry-wc-city-select'),
		_x('Tadi', 'NU', 'ry-wc-city-select'),
		_x('Tarkeshwar', 'NU', 'ry-wc-city-select'),
	],
	'OK' => [
		_x('Champadevi', 'OK', 'ry-wc-city-select'),
		_x('Chisankhugadi', 'OK', 'ry-wc-city-select'),
		_x('Khijidemba', 'OK', 'ry-wc-city-select'),
		_x('Likhu', 'OK', 'ry-wc-city-select'),
		_x('Manebhanjyang', 'OK', 'ry-wc-city-select'),
		_x('Molung', 'OK', 'ry-wc-city-select'),
		_x('Siddhicharan', 'OK', 'ry-wc-city-select'),
		_x('Sukoshi', 'OK', 'ry-wc-city-select'),
	],
	'PA' => [
		_x('Bagnaskali', 'PA', 'ry-wc-city-select'),
		_x('Mathagadhi', 'PA', 'ry-wc-city-select'),
		_x('Nisdi', 'PA', 'ry-wc-city-select'),
		_x('Purbakhola', 'PA', 'ry-wc-city-select'),
		_x('Rainadevi Chahara', 'PA', 'ry-wc-city-select'),
		_x('Rambha', 'PA', 'ry-wc-city-select'),
		_x('Rampur', 'PA', 'ry-wc-city-select'),
		_x('Ribdikot', 'PA', 'ry-wc-city-select'),
		_x('Tansen', 'PA', 'ry-wc-city-select'),
		_x('Tinau', 'PA', 'ry-wc-city-select'),
	],
	'PA2' => [
		_x('Falelung', 'PA2', 'ry-wc-city-select'),
		_x('Galgunanda', 'PA2', 'ry-wc-city-select'),
		_x('Hilihang', 'PA2', 'ry-wc-city-select'),
		_x('Kummayak', 'PA2', 'ry-wc-city-select'),
		_x('Miklajung', 'PA2', 'ry-wc-city-select'),
		_x('Phidim', 'PA2', 'ry-wc-city-select'),
		_x('Tumbewa', 'PA2', 'ry-wc-city-select'),
		_x('Yangwarak', 'PA2', 'ry-wc-city-select'),
	],
	'PA3' => [
		_x('Bihadi', 'PA3', 'ry-wc-city-select'),
		_x('Falebas', 'PA3', 'ry-wc-city-select'),
		_x('Jaljala', 'PA3', 'ry-wc-city-select'),
		_x('Kushma', 'PA3', 'ry-wc-city-select'),
		_x('Mahashila', 'PA3', 'ry-wc-city-select'),
		_x('Modi', 'PA3', 'ry-wc-city-select'),
		_x('Painyu', 'PA3', 'ry-wc-city-select'),
	],
	'PA4' => [
		_x('Bahudaramai', 'PA4', 'ry-wc-city-select'),
		_x('Belwa', 'PA4', 'ry-wc-city-select'),
		_x('Bindabasini', 'PA4', 'ry-wc-city-select'),
		_x('Birgunj', 'PA4', 'ry-wc-city-select'),
		_x('Chhipaharmai', 'PA4', 'ry-wc-city-select'),
		_x('Dhobini', 'PA4', 'ry-wc-city-select'),
		_x('Jagarnathpur', 'PA4', 'ry-wc-city-select'),
		_x('Pakahamainpur', 'PA4', 'ry-wc-city-select'),
		_x('Parsa', 'PA4', 'ry-wc-city-select'),
		_x('Parsagadhi', 'PA4', 'ry-wc-city-select'),
		_x('Paterwasugauli', 'PA4', 'ry-wc-city-select'),
		_x('Pokhariya', 'PA4', 'ry-wc-city-select'),
		_x('Sakhuwa Prasauni', 'PA4', 'ry-wc-city-select'),
		_x('Subarnapur', 'PA4', 'ry-wc-city-select'),
	],
	'PY' => [
		_x('Airawati', 'PY', 'ry-wc-city-select'),
		_x('Gaumukhi', 'PY', 'ry-wc-city-select'),
		_x('Jhimruk', 'PY', 'ry-wc-city-select'),
		_x('Mallarani', 'PY', 'ry-wc-city-select'),
		_x('Mandawi', 'PY', 'ry-wc-city-select'),
		_x('Naubahini', 'PY', 'ry-wc-city-select'),
		_x('Pyuthan', 'PY', 'ry-wc-city-select'),
		_x('Sarumarani', 'PY', 'ry-wc-city-select'),
		_x('Sworgadwari', 'PY', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Doraamba', 'RA', 'ry-wc-city-select'),
		_x('Gokulganga', 'RA', 'ry-wc-city-select'),
		_x('Khadadevi', 'RA', 'ry-wc-city-select'),
		_x('Likhu', 'RA', 'ry-wc-city-select'),
		_x('Manthali', 'RA', 'ry-wc-city-select'),
		_x('Ramechhap', 'RA', 'ry-wc-city-select'),
		_x('Sunapati', 'RA', 'ry-wc-city-select'),
		_x('Umakunda', 'RA', 'ry-wc-city-select'),
	],
	'RA2' => [
		_x('Gosaikunda', 'RA2', 'ry-wc-city-select'),
		_x('Kalika', 'RA2', 'ry-wc-city-select'),
		_x('Naukunda', 'RA2', 'ry-wc-city-select'),
		_x('Parwatikunda', 'RA2', 'ry-wc-city-select'),
		_x('Uttargaya', 'RA2', 'ry-wc-city-select'),
	],
	'RA3' => [
		_x('Baudhimal', 'RA3', 'ry-wc-city-select'),
		_x('Birndaban', 'RA3', 'ry-wc-city-select'),
		_x('Chandrapur', 'RA3', 'ry-wc-city-select'),
		_x('Dawahi Gonahi', 'RA3', 'ry-wc-city-select'),
		_x('Durga Bagwati', 'RA3', 'ry-wc-city-select'),
		_x('Gadhimai', 'RA3', 'ry-wc-city-select'),
		_x('Garuda', 'RA3', 'ry-wc-city-select'),
		_x('Gaur', 'RA3', 'ry-wc-city-select'),
		_x('Gujara', 'RA3', 'ry-wc-city-select'),
		_x('Ishanath', 'RA3', 'ry-wc-city-select'),
		_x('Katahariya', 'RA3', 'ry-wc-city-select'),
		_x('Madhav Narayan', 'RA3', 'ry-wc-city-select'),
		_x('Maulapur', 'RA3', 'ry-wc-city-select'),
		_x('Paroha', 'RA3', 'ry-wc-city-select'),
		_x('Phatuwa Bijayapur', 'RA3', 'ry-wc-city-select'),
		_x('Rajpur', 'RA3', 'ry-wc-city-select'),
	],
	'RO' => [
		_x('Duikholi', 'RO', 'ry-wc-city-select'),
		_x('Lungri', 'RO', 'ry-wc-city-select'),
		_x('Madi', 'RO', 'ry-wc-city-select'),
		_x('Rolpa', 'RO', 'ry-wc-city-select'),
		_x('Runtigadhi', 'RO', 'ry-wc-city-select'),
		_x('Sukidaha', 'RO', 'ry-wc-city-select'),
		_x('Sunchhahari', 'RO', 'ry-wc-city-select'),
		_x('Suwarnabati', 'RO', 'ry-wc-city-select'),
		_x('Thawang', 'RO', 'ry-wc-city-select'),
		_x('Triveni', 'RO', 'ry-wc-city-select'),
	],
	'RU' => [
		_x('Bhume', 'RU', 'ry-wc-city-select'),
		_x('Putha Uttarganga', 'RU', 'ry-wc-city-select'),
		_x('Sisne Gaunpalika', 'RU', 'ry-wc-city-select'),
	],
	'RU2' => [
		_x('Butwal', 'RU2', 'ry-wc-city-select'),
		_x('Devdaha', 'RU2', 'ry-wc-city-select'),
		_x('Gaidahawa', 'RU2', 'ry-wc-city-select'),
		_x('Kanchan', 'RU2', 'ry-wc-city-select'),
		_x('Lumbini Sanskritik', 'RU2', 'ry-wc-city-select'),
		_x('Marchawari', 'RU2', 'ry-wc-city-select'),
		_x('Mayadevi', 'RU2', 'ry-wc-city-select'),
		_x('Omsatiya', 'RU2', 'ry-wc-city-select'),
		_x('Rohini', 'RU2', 'ry-wc-city-select'),
		_x('Sainamaina', 'RU2', 'ry-wc-city-select'),
		_x('Sammarimai', 'RU2', 'ry-wc-city-select'),
		_x('Sammarimai', 'RU2', 'ry-wc-city-select'),
		_x('Siddharthanagar', 'RU2', 'ry-wc-city-select'),
		_x('Siyari', 'RU2', 'ry-wc-city-select'),
		_x('Suddhodhan', 'RU2', 'ry-wc-city-select'),
		_x('Tillotama', 'RU2', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Bagchaur', 'SA', 'ry-wc-city-select'),
		_x('Bangad Kupinde', 'SA', 'ry-wc-city-select'),
		_x('Chhatreswari', 'SA', 'ry-wc-city-select'),
		_x('Darma', 'SA', 'ry-wc-city-select'),
		_x('Dhorchaur', 'SA', 'ry-wc-city-select'),
		_x('Kalimati', 'SA', 'ry-wc-city-select'),
		_x('Kapurkot', 'SA', 'ry-wc-city-select'),
		_x('Kumakh Malika', 'SA', 'ry-wc-city-select'),
		_x('Sarada', 'SA', 'ry-wc-city-select'),
		_x('Tribeni', 'SA', 'ry-wc-city-select'),
	],
	'SA2' => [
		_x('Bhotkhola', 'SA2', 'ry-wc-city-select'),
		_x('Chainpur', 'SA2', 'ry-wc-city-select'),
		_x('Chichila', 'SA2', 'ry-wc-city-select'),
		_x('Dharmadevi', 'SA2', 'ry-wc-city-select'),
		_x('Khandbari', 'SA2', 'ry-wc-city-select'),
		_x('Madi', 'SA2', 'ry-wc-city-select'),
		_x('Makalu', 'SA2', 'ry-wc-city-select'),
		_x('Makalu', 'SA2', 'ry-wc-city-select'),
		_x('Panchakhapan', 'SA2', 'ry-wc-city-select'),
		_x('Sabhapokhari', 'SA2', 'ry-wc-city-select'),
		_x('Silichong', 'SA2', 'ry-wc-city-select'),
	],
	'SA3' => [
		_x('Belhi Chapena', 'SA3', 'ry-wc-city-select'),
		_x('Bishnupur', 'SA3', 'ry-wc-city-select'),
		_x('Bode Barsain', 'SA3', 'ry-wc-city-select'),
		_x('Chhinnamasta', 'SA3', 'ry-wc-city-select'),
		_x('Dakneshwari', 'SA3', 'ry-wc-city-select'),
		_x('Hanumannagar Kankalan', 'SA3', 'ry-wc-city-select'),
		_x('Kanchanrup', 'SA3', 'ry-wc-city-select'),
		_x('Khadak', 'SA3', 'ry-wc-city-select'),
		_x('Koshi Tappu', 'SA3', 'ry-wc-city-select'),
		_x('Krishna Sawaran', 'SA3', 'ry-wc-city-select'),
		_x('Mahadewa', 'SA3', 'ry-wc-city-select'),
		_x('Rajbiraj', 'SA3', 'ry-wc-city-select'),
		_x('Rupani', 'SA3', 'ry-wc-city-select'),
		_x('Saptakoshi', 'SA3', 'ry-wc-city-select'),
		_x('Shambhunath', 'SA3', 'ry-wc-city-select'),
		_x('Surunga', 'SA3', 'ry-wc-city-select'),
		_x('Tilathi Koiladi', 'SA3', 'ry-wc-city-select'),
		_x('Tirahut', 'SA3', 'ry-wc-city-select'),
	],
	'SA4' => [
		_x('Bagmati', 'SA4', 'ry-wc-city-select'),
		_x('Balara', 'SA4', 'ry-wc-city-select'),
		_x('Barahathawa', 'SA4', 'ry-wc-city-select'),
		_x('Bishnu', 'SA4', 'ry-wc-city-select'),
		_x('Bramhapuri', 'SA4', 'ry-wc-city-select'),
		_x('Chakraghatta', 'SA4', 'ry-wc-city-select'),
		_x('Chandranagar', 'SA4', 'ry-wc-city-select'),
		_x('Dhankaul', 'SA4', 'ry-wc-city-select'),
		_x('Gaudeta', 'SA4', 'ry-wc-city-select'),
		_x('Haripur', 'SA4', 'ry-wc-city-select'),
		_x('Haripurwa', 'SA4', 'ry-wc-city-select'),
		_x('Hariwan', 'SA4', 'ry-wc-city-select'),
		_x('Ishworpur', 'SA4', 'ry-wc-city-select'),
		_x('Kabilasi', 'SA4', 'ry-wc-city-select'),
		_x('Lalbandi', 'SA4', 'ry-wc-city-select'),
		_x('Malangawa', 'SA4', 'ry-wc-city-select'),
		_x('Ramnagar', 'SA4', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Dudhouli', 'SI', 'ry-wc-city-select'),
		_x('Ghyanglekh', 'SI', 'ry-wc-city-select'),
		_x('Golanjor', 'SI', 'ry-wc-city-select'),
		_x('Hariharpurgadhi', 'SI', 'ry-wc-city-select'),
		_x('Kamalamai', 'SI', 'ry-wc-city-select'),
		_x('Marin', 'SI', 'ry-wc-city-select'),
		_x('Phikkal', 'SI', 'ry-wc-city-select'),
		_x('Sunkoshi', 'SI', 'ry-wc-city-select'),
		_x('Tinpatan', 'SI', 'ry-wc-city-select'),
	],
	'SI2' => [
		_x('Balefi', 'SI2', 'ry-wc-city-select'),
		_x('Barhabise', 'SI2', 'ry-wc-city-select'),
		_x('Bhotekoshi', 'SI2', 'ry-wc-city-select'),
		_x('Chautara Sangachokgadhi', 'SI2', 'ry-wc-city-select'),
		_x('Helambu', 'SI2', 'ry-wc-city-select'),
		_x('Indrawati', 'SI2', 'ry-wc-city-select'),
		_x('Jugal', 'SI2', 'ry-wc-city-select'),
		_x('Lisangkhu Pakhar', 'SI2', 'ry-wc-city-select'),
		_x('Melamchi', 'SI2', 'ry-wc-city-select'),
		_x('Panchpokhari Thangpal', 'SI2', 'ry-wc-city-select'),
		_x('Sunkoshi', 'SI2', 'ry-wc-city-select'),
		_x('Tripurasundari', 'SI2', 'ry-wc-city-select'),
	],
	'SI3' => [
		_x('Arnama', 'SI3', 'ry-wc-city-select'),
		_x('Aurahi', 'SI3', 'ry-wc-city-select'),
		_x('Bariyarpatti', 'SI3', 'ry-wc-city-select'),
		_x('Bhagawanpur', 'SI3', 'ry-wc-city-select'),
		_x('Bishnupur', 'SI3', 'ry-wc-city-select'),
		_x('Dhangadhimai', 'SI3', 'ry-wc-city-select'),
		_x('Golbazar', 'SI3', 'ry-wc-city-select'),
		_x('Kalyanpur', 'SI3', 'ry-wc-city-select'),
		_x('Karjanha', 'SI3', 'ry-wc-city-select'),
		_x('Lahan', 'SI3', 'ry-wc-city-select'),
		_x('Laxmi Patari', 'SI3', 'ry-wc-city-select'),
		_x('Mirchaiya', 'SI3', 'ry-wc-city-select'),
		_x('Narha', 'SI3', 'ry-wc-city-select'),
		_x('Nawarajpur', 'SI3', 'ry-wc-city-select'),
		_x('Sakhuwa Nankarkatti', 'SI3', 'ry-wc-city-select'),
		_x('Siraha', 'SI3', 'ry-wc-city-select'),
		_x('Siraha', 'SI3', 'ry-wc-city-select'),
		_x('Sukhipur', 'SI3', 'ry-wc-city-select'),
	],
	'SO' => [
		_x('Dudhkaushika', 'SO', 'ry-wc-city-select'),
		_x('Dudhkoshi', 'SO', 'ry-wc-city-select'),
		_x('Khumbu Pasanglamhu', 'SO', 'ry-wc-city-select'),
		_x('Likhupike', 'SO', 'ry-wc-city-select'),
		_x('Mahakulung', 'SO', 'ry-wc-city-select'),
		_x('Nechasalyan', 'SO', 'ry-wc-city-select'),
		_x('Solududhkunda', 'SO', 'ry-wc-city-select'),
		_x('Sotang', 'SO', 'ry-wc-city-select'),
	],
	'SU' => [
		_x('Barah', 'SU', 'ry-wc-city-select'),
		_x('Barju', 'SU', 'ry-wc-city-select'),
		_x('Bhokraha', 'SU', 'ry-wc-city-select'),
		_x('Dewanganj', 'SU', 'ry-wc-city-select'),
		_x('Dharan', 'SU', 'ry-wc-city-select'),
		_x('Duhabi', 'SU', 'ry-wc-city-select'),
		_x('Gadhi', 'SU', 'ry-wc-city-select'),
		_x('Harinagara', 'SU', 'ry-wc-city-select'),
		_x('Inaruwa', 'SU', 'ry-wc-city-select'),
		_x('Itahari', 'SU', 'ry-wc-city-select'),
		_x('Koshi', 'SU', 'ry-wc-city-select'),
		_x('Koshi Tappu', 'SU', 'ry-wc-city-select'),
		_x('Ramdhuni', 'SU', 'ry-wc-city-select'),
	],
	'SU2' => [
		_x('Barahtaal', 'SU2', 'ry-wc-city-select'),
		_x('Bheriganga', 'SU2', 'ry-wc-city-select'),
		_x('Birendranagar', 'SU2', 'ry-wc-city-select'),
		_x('Chaukune', 'SU2', 'ry-wc-city-select'),
		_x('Chingad', 'SU2', 'ry-wc-city-select'),
		_x('Gurbhakot', 'SU2', 'ry-wc-city-select'),
		_x('Lekbeshi', 'SU2', 'ry-wc-city-select'),
		_x('Panchpuri', 'SU2', 'ry-wc-city-select'),
		_x('Simta', 'SU2', 'ry-wc-city-select'),
	],
	'SY' => [
		_x('Aandhikhola', 'SY', 'ry-wc-city-select'),
		_x('Arjunchaupri', 'SY', 'ry-wc-city-select'),
		_x('Bhirkot', 'SY', 'ry-wc-city-select'),
		_x('Biruwa', 'SY', 'ry-wc-city-select'),
		_x('Chapakot', 'SY', 'ry-wc-city-select'),
		_x('Galyang', 'SY', 'ry-wc-city-select'),
		_x('Harinas', 'SY', 'ry-wc-city-select'),
		_x('Kaligandagkii', 'SY', 'ry-wc-city-select'),
		_x('Phedikhola', 'SY', 'ry-wc-city-select'),
		_x('Putalibazar', 'SY', 'ry-wc-city-select'),
		_x('Waling', 'SY', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Aabunkhareni', 'TA', 'ry-wc-city-select'),
		_x('Bandipur', 'TA', 'ry-wc-city-select'),
		_x('Bhanu', 'TA', 'ry-wc-city-select'),
		_x('Bhimad', 'TA', 'ry-wc-city-select'),
		_x('Byas', 'TA', 'ry-wc-city-select'),
		_x('Devghat', 'TA', 'ry-wc-city-select'),
		_x('Ghiring', 'TA', 'ry-wc-city-select'),
		_x('Myagde', 'TA', 'ry-wc-city-select'),
		_x('Rhising', 'TA', 'ry-wc-city-select'),
		_x('Shuklagandaki', 'TA', 'ry-wc-city-select'),
	],
	'TA2' => [
		_x('Aathrai Tribeni', 'TA2', 'ry-wc-city-select'),
		_x('Maiwakhola', 'TA2', 'ry-wc-city-select'),
		_x('Meringden', 'TA2', 'ry-wc-city-select'),
		_x('Meringden', 'TA2', 'ry-wc-city-select'),
		_x('Mikwakhola', 'TA2', 'ry-wc-city-select'),
		_x('Phaktanglung', 'TA2', 'ry-wc-city-select'),
		_x('Phungling', 'TA2', 'ry-wc-city-select'),
		_x('Sidingba', 'TA2', 'ry-wc-city-select'),
		_x('Sirijangha', 'TA2', 'ry-wc-city-select'),
		_x('Yangwarak', 'TA2', 'ry-wc-city-select'),
	],
	'TE' => [
		_x('Aathrai', 'TE', 'ry-wc-city-select'),
		_x('Chhathar', 'TE', 'ry-wc-city-select'),
		_x('Laliguras', 'TE', 'ry-wc-city-select'),
		_x('Menchhayam', 'TE', 'ry-wc-city-select'),
		_x('Myanglung', 'TE', 'ry-wc-city-select'),
		_x('Phedap', 'TE', 'ry-wc-city-select'),
	],
	'UD' => [
		_x('Belaka', 'UD', 'ry-wc-city-select'),
		_x('Chaudandigadi', 'UD', 'ry-wc-city-select'),
		_x('Katari', 'UD', 'ry-wc-city-select'),
		_x('Koshi Tappu', 'UD', 'ry-wc-city-select'),
		_x('Rautamai', 'UD', 'ry-wc-city-select'),
		_x('Sunkoshi', 'UD', 'ry-wc-city-select'),
		_x('Tapli', 'UD', 'ry-wc-city-select'),
		_x('Triyuga', 'UD', 'ry-wc-city-select'),
		_x('Udayapurgadhi', 'UD', 'ry-wc-city-select'),
	],
	]
];