<?php
/**
 * Republic of Panama places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'PA' => [
	'BE' => [
		_x('Corregimiento Boca de Balsa', 'BE', 'ry-wc-city-select'),
		_x('Corregimiento Camaron Arriba', 'BE', 'ry-wc-city-select'),
		_x('Corregimiento Cerro Banco', 'BE', 'ry-wc-city-select'),
		_x('Corregimiento Cerro de Patena', 'BE', 'ry-wc-city-select'),
		_x('Corregimiento Emplanada de Chorcha', 'BE', 'ry-wc-city-select'),
		_x('Corregimiento Soloy', 'BE', 'ry-wc-city-select'),
		_x('Namnoni', 'BE', 'ry-wc-city-select'),
		_x('Niba', 'BE', 'ry-wc-city-select'),
	],
	'CE' => [
		_x('Cirilo Guainora', 'CE', 'ry-wc-city-select'),
		_x('Lajas Blancas', 'CE', 'ry-wc-city-select'),
		_x('Manuel Ortega', 'CE', 'ry-wc-city-select'),
	],
	'DIAR' => [
		_x('Burunga', 'DIAR', 'ry-wc-city-select'),
		_x('Cerro Silvestre', 'DIAR', 'ry-wc-city-select'),
		_x('Corregimiento Arraijan', 'DIAR', 'ry-wc-city-select'),
		_x('Corregimiento Juan Demostenes Arosemena', 'DIAR', 'ry-wc-city-select'),
		_x('Corregimiento Nuevo Emperador', 'DIAR', 'ry-wc-city-select'),
		_x('Corregimiento Santa Clara', 'DIAR', 'ry-wc-city-select'),
		_x('Corregimiento Veracruz', 'DIAR', 'ry-wc-city-select'),
		_x('Corregimiento Vista Alegre', 'DIAR', 'ry-wc-city-select'),
	],
	'DICHGR' => [
		_x('Bajo Cedro', 'DICHGR', 'ry-wc-city-select'),
		_x('Corregimiento Chiriqui Grande', 'DICHGR', 'ry-wc-city-select'),
		_x('Corregimiento Punta Robalo', 'DICHGR', 'ry-wc-city-select'),
		_x('Miramar', 'DICHGR', 'ry-wc-city-select'),
		_x('Punta Pena', 'DICHGR', 'ry-wc-city-select'),
		_x('Rambala', 'DICHGR', 'ry-wc-city-select'),
	],
	'DIPE' => [
		_x('Corregimiento Canaveral', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento Chiguiri Arriba', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento Cocle', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento El Coco', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento Pajonal', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento Penonome', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento Rio Grande', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento Rio Indio', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento Toabre', 'DIPE', 'ry-wc-city-select'),
		_x('Corregimiento Tulu', 'DIPE', 'ry-wc-city-select'),
	],
	'DISAMI' => [
		_x('Belisario Frias', 'DISAMI', 'ry-wc-city-select'),
		_x('Corregimiento Amelia Denis de Icaza', 'DISAMI', 'ry-wc-city-select'),
		_x('Corregimiento Arnulfo Arias', 'DISAMI', 'ry-wc-city-select'),
		_x('Corregimiento Belisario Porras', 'DISAMI', 'ry-wc-city-select'),
		_x('Corregimiento Jose Domingo Espinar', 'DISAMI', 'ry-wc-city-select'),
		_x('Corregimiento Mateo Iturralde', 'DISAMI', 'ry-wc-city-select'),
		_x('Corregimiento Omar Torrijos', 'DISAMI', 'ry-wc-city-select'),
		_x('Corregimiento Rufina Alfaro', 'DISAMI', 'ry-wc-city-select'),
		_x('Corregimiento Victoriano Lorenzo', 'DISAMI', 'ry-wc-city-select'),
	],
	'DIAG' => [
		_x('Barrios Unidos', 'DIAG', 'ry-wc-city-select'),
		_x('Corregimiento Aguadulce', 'DIAG', 'ry-wc-city-select'),
		_x('Corregimiento El Cristo', 'DIAG', 'ry-wc-city-select'),
		_x('Corregimiento El Roble', 'DIAG', 'ry-wc-city-select'),
		_x('Corregimiento Pocri', 'DIAG', 'ry-wc-city-select'),
	],
	'DIAL' => [
		_x('Canta Gallo', 'DIAL', 'ry-wc-city-select'),
		_x('Corregimiento Alanje', 'DIAL', 'ry-wc-city-select'),
		_x('Corregimiento Divala', 'DIAL', 'ry-wc-city-select'),
		_x('Corregimiento El Tejar', 'DIAL', 'ry-wc-city-select'),
		_x('Corregimiento Guarumal', 'DIAL', 'ry-wc-city-select'),
		_x('Corregimiento Palo Grande', 'DIAL', 'ry-wc-city-select'),
		_x('Corregimiento Querevalo', 'DIAL', 'ry-wc-city-select'),
		_x('Corregimiento Santo Tomas', 'DIAL', 'ry-wc-city-select'),
		_x('Nuevo Mexico', 'DIAL', 'ry-wc-city-select'),
	],
	'DIAN' => [
		_x('Caballero', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento Anton', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento Cabuya', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento El Chiru', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento El Retiro', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento El Valle', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento Juan Diaz', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento Rio Hato', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento San Juan de Dios', 'DIAN', 'ry-wc-city-select'),
		_x('Corregimiento Santa Rita', 'DIAN', 'ry-wc-city-select'),
	],
	'DIAT' => [
		_x('Corregimiento Atalaya', 'DIAT', 'ry-wc-city-select'),
		_x('Corregimiento El Barrito', 'DIAT', 'ry-wc-city-select'),
		_x('Corregimiento La Montanuela', 'DIAT', 'ry-wc-city-select'),
		_x('La Carrillo', 'DIAT', 'ry-wc-city-select'),
		_x('San Antonio', 'DIAT', 'ry-wc-city-select'),
	],
	'DIBA' => [
		_x('Corregimiento La Ensenada', 'DIBA', 'ry-wc-city-select'),
		_x('Corregimiento La Esmeralda', 'DIBA', 'ry-wc-city-select'),
		_x('Corregimiento La Guinea', 'DIBA', 'ry-wc-city-select'),
		_x('Corregimiento Pedro Gonzalez', 'DIBA', 'ry-wc-city-select'),
		_x('Corregimiento Saboga', 'DIBA', 'ry-wc-city-select'),
		_x('Corregimiento San Miguel', 'DIBA', 'ry-wc-city-select'),
	],
	'DIBA2' => [
		_x('Baco', 'DIBA2', 'ry-wc-city-select'),
		_x('Corregimiento Limones', 'DIBA2', 'ry-wc-city-select'),
		_x('Corregimiento Progreso', 'DIBA2', 'ry-wc-city-select'),
		_x('Corregimiento Puerto Armuelles', 'DIBA2', 'ry-wc-city-select'),
		_x('Rodolfo Aguilar Delgado', 'DIBA2', 'ry-wc-city-select'),
	],
	'DIBODETO' => [
		_x('Cauchero', 'DIBODETO', 'ry-wc-city-select'),
		_x('Corregimiento Bastimentos', 'DIBODETO', 'ry-wc-city-select'),
		_x('Corregimiento Bocas del Toro', 'DIBODETO', 'ry-wc-city-select'),
		_x('Corregimiento Punta Laurel', 'DIBODETO', 'ry-wc-city-select'),
		_x('Tierra Oscura', 'DIBODETO', 'ry-wc-city-select'),
	],
	'DIBO' => [
		_x('Corregimiento Bagala', 'DIBO', 'ry-wc-city-select'),
		_x('Corregimiento Boqueron', 'DIBO', 'ry-wc-city-select'),
		_x('Corregimiento Cordillera', 'DIBO', 'ry-wc-city-select'),
		_x('Corregimiento Guabal', 'DIBO', 'ry-wc-city-select'),
		_x('Corregimiento Guayabal', 'DIBO', 'ry-wc-city-select'),
		_x('Corregimiento Paraiso', 'DIBO', 'ry-wc-city-select'),
		_x('Corregimiento Pedregal', 'DIBO', 'ry-wc-city-select'),
		_x('Corregimiento Tijeras', 'DIBO', 'ry-wc-city-select'),
	],
	'DIBO2' => [
		_x('Alto Boquete', 'DIBO2', 'ry-wc-city-select'),
		_x('Corregimiento Bajo Boquete', 'DIBO2', 'ry-wc-city-select'),
		_x('Corregimiento Caldera', 'DIBO2', 'ry-wc-city-select'),
		_x('Corregimiento Palmira', 'DIBO2', 'ry-wc-city-select'),
		_x('Jaramillo', 'DIBO2', 'ry-wc-city-select'),
		_x('Los Naranjos', 'DIBO2', 'ry-wc-city-select'),
	],
	'DIBU' => [
		_x('Corregimiento Aserrio de Gariche', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento Bugaba', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento Cerro Punta', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento Gomez', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento La Concepcion', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento La Estrella', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento San Andres', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento Santa Marta', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento Santa Rosa', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento Santo Domingo', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento Sortova', 'DIBU', 'ry-wc-city-select'),
		_x('Corregimiento Volcan', 'DIBU', 'ry-wc-city-select'),
		_x('El Bongo', 'DIBU', 'ry-wc-city-select'),
	],
	'DICA' => [
		_x('Corregimiento Barnizal', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento Calobre', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento Chitra', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento El Cocla', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento El Potrero', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento La Laguna', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento La Raya de Calobre', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento La Tetilla', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento La Yeguada', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento Las Guias', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento Monjaras', 'DICA', 'ry-wc-city-select'),
		_x('Corregimiento San Jose', 'DICA', 'ry-wc-city-select'),
	],
	'DICA2' => [
		_x('Corregimiento Canazas', 'DICA2', 'ry-wc-city-select'),
		_x('Corregimiento Cerro Plata', 'DICA2', 'ry-wc-city-select'),
		_x('Corregimiento Los Valles', 'DICA2', 'ry-wc-city-select'),
		_x('Corregimiento San Marcelo', 'DICA2', 'ry-wc-city-select'),
		_x('El Aromillo', 'DICA2', 'ry-wc-city-select'),
		_x('El Picador', 'DICA2', 'ry-wc-city-select'),
		_x('Las Cruces', 'DICA2', 'ry-wc-city-select'),
		_x('San Jose', 'DICA2', 'ry-wc-city-select'),
	],
	'DICA3' => [
		_x('Corregimiento Caimito', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Campana', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Capira', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Cermeno', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Ciri Grande', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Ciri de los Sotos', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento El Cacao', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento La Trinidad', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Las Ollas Arriba', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Lidice', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Villa Carmen', 'DICA3', 'ry-wc-city-select'),
		_x('Corregimiento Villa Rosario', 'DICA3', 'ry-wc-city-select'),
		_x('Santa Rosa', 'DICA3', 'ry-wc-city-select'),
	],
	'DICH' => [
		_x('Corregimiento Achiote', 'DICH', 'ry-wc-city-select'),
		_x('Corregimiento El Guabo', 'DICH', 'ry-wc-city-select'),
		_x('Corregimiento La Encantada', 'DICH', 'ry-wc-city-select'),
		_x('Corregimiento Nuevo Chagres', 'DICH', 'ry-wc-city-select'),
		_x('Corregimiento Palmas Bellas', 'DICH', 'ry-wc-city-select'),
		_x('Corregimiento Pina', 'DICH', 'ry-wc-city-select'),
		_x('Corregimiento Salud', 'DICH', 'ry-wc-city-select'),
	],
	'DICH2' => [
		_x('Corregimiento Bejuco', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Buenos Aires', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Cabuya', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Chame', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Chica', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento El Libano', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Las Lajas', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Nueva Gorgona', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Punta Chame', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Sajalices (Chame)', 'DICH2', 'ry-wc-city-select'),
		_x('Corregimiento Sora', 'DICH2', 'ry-wc-city-select'),
	],
	'DICH3' => [
		_x('Cochigro', 'DICH3', 'ry-wc-city-select'),
		_x('Corregimiento Almirante', 'DICH3', 'ry-wc-city-select'),
		_x('Corregimiento Guabito', 'DICH3', 'ry-wc-city-select'),
		_x('Corregimiento de Changuinola', 'DICH3', 'ry-wc-city-select'),
		_x('El Empalme', 'DICH3', 'ry-wc-city-select'),
		_x('El Teribe', 'DICH3', 'ry-wc-city-select'),
		_x('La Gloria', 'DICH3', 'ry-wc-city-select'),
		_x('Las Delicias', 'DICH3', 'ry-wc-city-select'),
		_x('Las Tablas', 'DICH3', 'ry-wc-city-select'),
		_x('Nance Del Risco', 'DICH3', 'ry-wc-city-select'),
		_x('Valle De Agua Arriba', 'DICH3', 'ry-wc-city-select'),
		_x('Valle Del Risco', 'DICH3', 'ry-wc-city-select'),
	],
	'DICH4' => [
		_x('Agua Fria', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Camoganti', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Chepigana', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Garachine', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Jaque', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento La Palma', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Puerto Pina', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Rio Congo', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Rio Iglesias', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Sambu', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Seteganti', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Taimati', 'DICH4', 'ry-wc-city-select'),
		_x('Corregimiento Tucuti', 'DICH4', 'ry-wc-city-select'),
		_x('Cucunati', 'DICH4', 'ry-wc-city-select'),
		_x('Rio Congo Arriba', 'DICH4', 'ry-wc-city-select'),
		_x('Santa Fe', 'DICH4', 'ry-wc-city-select'),
	],
	'DICH5' => [
		_x('Corregimiento Canita', 'DICH5', 'ry-wc-city-select'),
		_x('Corregimiento Chepillo', 'DICH5', 'ry-wc-city-select'),
		_x('Corregimiento Chepo', 'DICH5', 'ry-wc-city-select'),
		_x('Corregimiento El Llano', 'DICH5', 'ry-wc-city-select'),
		_x('Corregimiento Las Margaritas', 'DICH5', 'ry-wc-city-select'),
		_x('Corregimiento Santa Cruz de Chinina', 'DICH5', 'ry-wc-city-select'),
		_x('Kuna de Madugandi', 'DICH5', 'ry-wc-city-select'),
		_x('Torti', 'DICH5', 'ry-wc-city-select'),
	],
	'DICH6' => [
		_x('Corregimiento Brujas', 'DICH6', 'ry-wc-city-select'),
		_x('Corregimiento Chiman', 'DICH6', 'ry-wc-city-select'),
		_x('Corregimiento Gonzalo Vasquez', 'DICH6', 'ry-wc-city-select'),
		_x('Pasiga', 'DICH6', 'ry-wc-city-select'),
		_x('Union Santena', 'DICH6', 'ry-wc-city-select'),
	],
	'DICH7' => [
		_x('Corregimiento Chitre', 'DICH7', 'ry-wc-city-select'),
		_x('Corregimiento La Arena', 'DICH7', 'ry-wc-city-select'),
		_x('Corregimiento Monagrillo', 'DICH7', 'ry-wc-city-select'),
		_x('Llano Bonito', 'DICH7', 'ry-wc-city-select'),
		_x('San Juan Bautista', 'DICH7', 'ry-wc-city-select'),
	],
	'DICO' => [
		_x('Corregimiento Barrio Norte', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Barrio Sur', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Buena Vista', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Cativa', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Ciricito', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Cristobal', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Escobal', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Limon', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Nueva Providencia', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Puerto Pilon', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Sabanitas', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Salamanca', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento San Juan', 'DICO', 'ry-wc-city-select'),
		_x('Corregimiento Santa Rosa', 'DICO', 'ry-wc-city-select'),
	],
	'DIDA' => [
		_x('Corregimiento Bijagual', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento Chiriqui', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento Cochea', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento David', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento Guaca', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento Las Lomas', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento Pedregal', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento San Carlos', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento San Pablo Nuevo', 'DIDA', 'ry-wc-city-select'),
		_x('Corregimiento San Pablo Viejo', 'DIDA', 'ry-wc-city-select'),
	],
	'DIDO' => [
		_x('Corregimiento Dolega', 'DIDO', 'ry-wc-city-select'),
		_x('Corregimiento Dos Rios', 'DIDO', 'ry-wc-city-select'),
		_x('Corregimiento Los Anastacios', 'DIDO', 'ry-wc-city-select'),
		_x('Corregimiento Potrerillos', 'DIDO', 'ry-wc-city-select'),
		_x('Corregimiento Potrerillos Abajo', 'DIDO', 'ry-wc-city-select'),
		_x('Corregimiento Rovira', 'DIDO', 'ry-wc-city-select'),
		_x('Corregimiento Tinajas', 'DIDO', 'ry-wc-city-select'),
		_x('Los Algarrobos', 'DIDO', 'ry-wc-city-select'),
	],
	'DIDO2' => [
		_x('Corregimiento Cocle del Norte', 'DIDO2', 'ry-wc-city-select'),
		_x('Corregimiento El Guasimo', 'DIDO2', 'ry-wc-city-select'),
		_x('Corregimiento Gobea', 'DIDO2', 'ry-wc-city-select'),
		_x('Corregimiento Miguel de la Borda', 'DIDO2', 'ry-wc-city-select'),
		_x('Corregimiento Rio Indio', 'DIDO2', 'ry-wc-city-select'),
		_x('Corregimiento San Jose del General', 'DIDO2', 'ry-wc-city-select'),
	],
	'DIGU' => [
		_x('Corregimiento Gualaca', 'DIGU', 'ry-wc-city-select'),
		_x('Corregimiento Hornito', 'DIGU', 'ry-wc-city-select'),
		_x('Corregimiento Los Angeles', 'DIGU', 'ry-wc-city-select'),
		_x('Corregimiento Paja de Sombrero', 'DIGU', 'ry-wc-city-select'),
		_x('Corregimiento Rincon', 'DIGU', 'ry-wc-city-select'),
	],
	'DIGU2' => [
		_x('Corregimiento El Espinal', 'DIGU2', 'ry-wc-city-select'),
		_x('Corregimiento El Macano', 'DIGU2', 'ry-wc-city-select'),
		_x('Corregimiento Guarare', 'DIGU2', 'ry-wc-city-select'),
		_x('Corregimiento Guarare Arriba', 'DIGU2', 'ry-wc-city-select'),
		_x('Corregimiento La Enea', 'DIGU2', 'ry-wc-city-select'),
		_x('Corregimiento La Pasera', 'DIGU2', 'ry-wc-city-select'),
		_x('Corregimiento Las Trancas', 'DIGU2', 'ry-wc-city-select'),
		_x('Corregimiento Llano Abajo', 'DIGU2', 'ry-wc-city-select'),
		_x('El Hato', 'DIGU2', 'ry-wc-city-select'),
		_x('Perales', 'DIGU2', 'ry-wc-city-select'),
	],
	'DICH8' => [
		_x('Corregimiento Amador', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Arosemena', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Barrio Balboa', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Barrio Colon', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento El Arado', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento El Coco', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Feuillet', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Guadalupe', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Herrera', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Hurtado', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Iturralde', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento La Represa', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Los Diaz', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Mendoza', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Obaldia', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Playa Leona', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Puerto Caimito', 'DICH8', 'ry-wc-city-select'),
		_x('Corregimiento Santa Rita', 'DICH8', 'ry-wc-city-select'),
	],
	'DIME' => [
		_x('Corregimiento Bisvalles', 'DIME', 'ry-wc-city-select'),
		_x('Corregimiento Boro', 'DIME', 'ry-wc-city-select'),
		_x('Corregimiento La Mesa', 'DIME', 'ry-wc-city-select'),
		_x('Corregimiento Llano Grande', 'DIME', 'ry-wc-city-select'),
		_x('Corregimiento San Bartolo', 'DIME', 'ry-wc-city-select'),
		_x('Los Milagros', 'DIME', 'ry-wc-city-select'),
	],
	'DIPI' => [
		_x('Corregimiento El Harino', 'DIPI', 'ry-wc-city-select'),
		_x('Corregimiento El Potrero', 'DIPI', 'ry-wc-city-select'),
		_x('Corregimiento La Pintada', 'DIPI', 'ry-wc-city-select'),
		_x('Corregimiento Llano Grande', 'DIPI', 'ry-wc-city-select'),
		_x('Corregimiento Piedras Gordas', 'DIPI', 'ry-wc-city-select'),
		_x('Las Lomas', 'DIPI', 'ry-wc-city-select'),
	],
	'DILAMI' => [
		_x('Corregimiento Chepo', 'DILAMI', 'ry-wc-city-select'),
		_x('Corregimiento Chumical', 'DILAMI', 'ry-wc-city-select'),
		_x('Corregimiento El Toro', 'DILAMI', 'ry-wc-city-select'),
		_x('Corregimiento Las Minas', 'DILAMI', 'ry-wc-city-select'),
		_x('Corregimiento Leones', 'DILAMI', 'ry-wc-city-select'),
		_x('Corregimiento Quebrada del Rosario', 'DILAMI', 'ry-wc-city-select'),
		_x('Quebrada El Ciprian', 'DILAMI', 'ry-wc-city-select'),
	],
	'DILAPA' => [
		_x('Corregimiento Cerro de Casa', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento Corozal', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento El Maria', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento El Prado', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento El Rincon', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento Las Palmas', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento Lola', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento Pixvae', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento Puerto Vidal', 'DILAPA', 'ry-wc-city-select'),
		_x('Corregimiento Zapotillo', 'DILAPA', 'ry-wc-city-select'),
		_x('San Martin De Porres', 'DILAPA', 'ry-wc-city-select'),
		_x('Vigui', 'DILAPA', 'ry-wc-city-select'),
	],
	'DILATA' => [
		_x('Corregimiento Bajo Corral', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Bayano', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento El Carate', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento El Cocal', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento El Manantial', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento El Munoz', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento El Pedregoso', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento La Laja', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento La Miel', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento La Palma', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento La Tiza', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Las Palmitas', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Las Tablas', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Las Tablas Abajo', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Nuario', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Palmira', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Pena Blanca', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Rio Hondo', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento San Jose', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento San Miguel', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Santo Domingo', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Sesteadero', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Valle Rico', 'DILATA', 'ry-wc-city-select'),
		_x('Corregimiento Vallerriquito', 'DILATA', 'ry-wc-city-select'),
	],
	'DILOPO' => [
		_x('Corregimiento El Calabacito', 'DILOPO', 'ry-wc-city-select'),
		_x('Corregimiento El Capuri', 'DILOPO', 'ry-wc-city-select'),
		_x('Corregimiento El Cedro', 'DILOPO', 'ry-wc-city-select'),
		_x('Corregimiento La Arena', 'DILOPO', 'ry-wc-city-select'),
		_x('Corregimiento La Pitaloza', 'DILOPO', 'ry-wc-city-select'),
		_x('Corregimiento Los Cerritos', 'DILOPO', 'ry-wc-city-select'),
		_x('Corregimiento Los Cerros de Paja', 'DILOPO', 'ry-wc-city-select'),
		_x('Corregimiento Los Pozos', 'DILOPO', 'ry-wc-city-select'),
		_x('Las Llanas', 'DILOPO', 'ry-wc-city-select'),
	],
	'DILOSA' => [
		_x('Agua Buena', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento El Guasimo', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento La Colorada', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento La Espigadilla', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Las Cruces', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Las Guabas', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Llano Largo', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Los Angeles', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Los Olivos', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Los Santos', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Sabana Grande', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Santa Ana', 'DILOSA', 'ry-wc-city-select'),
		_x('Corregimiento Tres Quebradas', 'DILOSA', 'ry-wc-city-select'),
		_x('Villa Lourdes', 'DILOSA', 'ry-wc-city-select'),
	],
	'DIMA' => [
		_x('Corregimiento Bahia Honda', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento Bajos de Gueera', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento Chupa', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento Corozal', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento El Cedro', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento Espino Amarillo', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento La Mesa', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento Las Palmas', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento Llano de Piedra', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento Macaracas', 'DIMA', 'ry-wc-city-select'),
		_x('Corregimiento Mogollon', 'DIMA', 'ry-wc-city-select'),
	],
	'DIMO' => [
		_x('Cebaco', 'DIMO', 'ry-wc-city-select'),
		_x('Corregimiento Gobernadora', 'DIMO', 'ry-wc-city-select'),
		_x('Corregimiento La Garceana', 'DIMO', 'ry-wc-city-select'),
		_x('Corregimiento Leones', 'DIMO', 'ry-wc-city-select'),
		_x('Corregimiento Montijo', 'DIMO', 'ry-wc-city-select'),
		_x('Corregimiento Pilon', 'DIMO', 'ry-wc-city-select'),
		_x('Costa Hermosa', 'DIMO', 'ry-wc-city-select'),
		_x('Union Del Norte', 'DIMO', 'ry-wc-city-select'),
	],
	'DINA' => [
		_x('Corregimiento Capellania', 'DINA', 'ry-wc-city-select'),
		_x('Corregimiento El Cano', 'DINA', 'ry-wc-city-select'),
		_x('Corregimiento Guzman', 'DINA', 'ry-wc-city-select'),
		_x('Corregimiento Las Huacas', 'DINA', 'ry-wc-city-select'),
		_x('Corregimiento Nata', 'DINA', 'ry-wc-city-select'),
		_x('Corregimiento Toza', 'DINA', 'ry-wc-city-select'),
	],
	'DIOC' => [
		_x('Corregimiento Cerro Largo', 'DIOC', 'ry-wc-city-select'),
		_x('Corregimiento Llano Grande', 'DIOC', 'ry-wc-city-select'),
		_x('Corregimiento Los Llanos', 'DIOC', 'ry-wc-city-select'),
		_x('Corregimiento Ocu', 'DIOC', 'ry-wc-city-select'),
		_x('Corregimiento Penas Chatas', 'DIOC', 'ry-wc-city-select'),
		_x('El Tijera', 'DIOC', 'ry-wc-city-select'),
		_x('Menchaca', 'DIOC', 'ry-wc-city-select'),
	],
	'DIOL' => [
		_x('Corregimiento El Cope', 'DIOL', 'ry-wc-city-select'),
		_x('Corregimiento El Palmar', 'DIOL', 'ry-wc-city-select'),
		_x('Corregimiento El Picacho', 'DIOL', 'ry-wc-city-select'),
		_x('Corregimiento La Pava', 'DIOL', 'ry-wc-city-select'),
		_x('Corregimiento Ola', 'DIOL', 'ry-wc-city-select'),
	],
	'DIPA' => [
		_x('24 De Diciembre', 'DIPA', 'ry-wc-city-select'),
		_x('Alcalde Diaz', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Ancon', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Bella Vista', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Betania', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Calidonia', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Chilibre', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Curundu', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento El Chorrillo', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Juan Diaz', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Las Cumbres', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Pacora', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Parque Lefevre', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Pedregal', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Pueblo Nuevo', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Rio Abajo', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento San Felipe', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento San Francisco', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento San Martin', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Santa Ana', 'DIPA', 'ry-wc-city-select'),
		_x('Corregimiento Tocumen', 'DIPA', 'ry-wc-city-select'),
		_x('Ernesto Cordoba Campos', 'DIPA', 'ry-wc-city-select'),
		_x('Las Mananitas', 'DIPA', 'ry-wc-city-select'),
	],
	'DIPA2' => [
		_x('Corregimiento Cabuya', 'DIPA2', 'ry-wc-city-select'),
		_x('Corregimiento Llano de la Cruz', 'DIPA2', 'ry-wc-city-select'),
		_x('Corregimiento Los Castillos', 'DIPA2', 'ry-wc-city-select'),
		_x('Corregimiento Paris', 'DIPA2', 'ry-wc-city-select'),
		_x('Corregimiento Parita', 'DIPA2', 'ry-wc-city-select'),
		_x('Corregimiento Portobelillo', 'DIPA2', 'ry-wc-city-select'),
		_x('Corregimiento Potuga', 'DIPA2', 'ry-wc-city-select'),
	],
	'DIPE2' => [
		_x('Corregimiento Los Asientos', 'DIPE2', 'ry-wc-city-select'),
		_x('Corregimiento Mariabe', 'DIPE2', 'ry-wc-city-select'),
		_x('Corregimiento Pedasi', 'DIPE2', 'ry-wc-city-select'),
		_x('Corregimiento Purio', 'DIPE2', 'ry-wc-city-select'),
		_x('Oria Arriba', 'DIPE2', 'ry-wc-city-select'),
	],
	'DIPE3' => [
		_x('Corregimiento Pese', 'DIPE3', 'ry-wc-city-select'),
		_x('El Barrero', 'DIPE3', 'ry-wc-city-select'),
		_x('El Ciruelo', 'DIPE3', 'ry-wc-city-select'),
		_x('El Pajaro', 'DIPE3', 'ry-wc-city-select'),
		_x('El Pedregoso', 'DIPE3', 'ry-wc-city-select'),
		_x('Las Cabras', 'DIPE3', 'ry-wc-city-select'),
		_x('Rincon Hondo', 'DIPE3', 'ry-wc-city-select'),
		_x('Sabana Grande', 'DIPE3', 'ry-wc-city-select'),
	],
	'DIPI2' => [
		_x('Corregimiento Boca de Cupe', 'DIPI2', 'ry-wc-city-select'),
		_x('Corregimiento El Real de Santa Maria', 'DIPI2', 'ry-wc-city-select'),
		_x('Corregimiento Paya', 'DIPI2', 'ry-wc-city-select'),
		_x('Corregimiento Pinogana', 'DIPI2', 'ry-wc-city-select'),
		_x('Corregimiento Yape', 'DIPI2', 'ry-wc-city-select'),
		_x('Corregimiento Yaviza', 'DIPI2', 'ry-wc-city-select'),
		_x('Kuna de Wargandi', 'DIPI2', 'ry-wc-city-select'),
		_x('Meteti', 'DIPI2', 'ry-wc-city-select'),
		_x('Pucuro', 'DIPI2', 'ry-wc-city-select'),
	],
	'DIPO' => [
		_x('Corregimiento El Canafistulo', 'DIPO', 'ry-wc-city-select'),
		_x('Corregimiento Lajamina', 'DIPO', 'ry-wc-city-select'),
		_x('Corregimiento Paraiso', 'DIPO', 'ry-wc-city-select'),
		_x('Corregimiento Paritilla', 'DIPO', 'ry-wc-city-select'),
		_x('Corregimiento Pocri', 'DIPO', 'ry-wc-city-select'),
	],
	'DIPO2' => [
		_x('Corregimiento Cacique', 'DIPO2', 'ry-wc-city-select'),
		_x('Corregimiento Garrote', 'DIPO2', 'ry-wc-city-select'),
		_x('Corregimiento Isla Grande', 'DIPO2', 'ry-wc-city-select'),
		_x('Corregimiento Maria Chiquita', 'DIPO2', 'ry-wc-city-select'),
		_x('Corregimiento Portobelo', 'DIPO2', 'ry-wc-city-select'),
	],
	'DIRE' => [
		_x('Corregimiento El Nancito', 'DIRE', 'ry-wc-city-select'),
		_x('Corregimiento Remedios', 'DIRE', 'ry-wc-city-select'),
		_x('El Porvenir', 'DIRE', 'ry-wc-city-select'),
		_x('El Puerto', 'DIRE', 'ry-wc-city-select'),
		_x('Santa Lucia', 'DIRE', 'ry-wc-city-select'),
	],
	'DIRE2' => [
		_x('Corregimiento Brenon', 'DIRE2', 'ry-wc-city-select'),
		_x('Corregimiento Canas Gordas', 'DIRE2', 'ry-wc-city-select'),
		_x('Corregimiento Monte Lirio', 'DIRE2', 'ry-wc-city-select'),
		_x('Corregimiento Plaza de Caisan', 'DIRE2', 'ry-wc-city-select'),
		_x('Corregimiento Rio Sereno', 'DIRE2', 'ry-wc-city-select'),
		_x('Corregimiento Santa Cruz', 'DIRE2', 'ry-wc-city-select'),
		_x('Dominical', 'DIRE2', 'ry-wc-city-select'),
		_x('Santa Clara', 'DIRE2', 'ry-wc-city-select'),
	],
	'DIRIJE' => [
		_x('Catorce De Noviembre', 'DIRIJE', 'ry-wc-city-select'),
		_x('Corregimiento Las Huacas', 'DIRIJE', 'ry-wc-city-select'),
		_x('Corregimiento Los Castillos', 'DIRIJE', 'ry-wc-city-select'),
		_x('Corregimiento Rio de Jesus', 'DIRIJE', 'ry-wc-city-select'),
		_x('Corregimiento Utira', 'DIRIJE', 'ry-wc-city-select'),
	],
	'DISACA' => [
		_x('Corregimiento El Espino', 'DISACA', 'ry-wc-city-select'),
		_x('Corregimiento El Higo', 'DISACA', 'ry-wc-city-select'),
		_x('Corregimiento Guayabito', 'DISACA', 'ry-wc-city-select'),
		_x('Corregimiento La Ermita', 'DISACA', 'ry-wc-city-select'),
		_x('Corregimiento La Laguna', 'DISACA', 'ry-wc-city-select'),
		_x('Corregimiento Las Uvas', 'DISACA', 'ry-wc-city-select'),
		_x('Corregimiento Los Llanitos', 'DISACA', 'ry-wc-city-select'),
		_x('Corregimiento San Carlos', 'DISACA', 'ry-wc-city-select'),
		_x('Corregimiento San Jose', 'DISACA', 'ry-wc-city-select'),
	],
	'DISAFE' => [
		_x('Corregimiento Juay', 'DISAFE', 'ry-wc-city-select'),
		_x('Corregimiento Las Lajas', 'DISAFE', 'ry-wc-city-select'),
		_x('Corregimiento San Felix', 'DISAFE', 'ry-wc-city-select'),
		_x('Lajas Adentro', 'DISAFE', 'ry-wc-city-select'),
		_x('Santa Cruz', 'DISAFE', 'ry-wc-city-select'),
	],
	'DISAFR' => [
		_x('Corregimiento Corral Falso', 'DISAFR', 'ry-wc-city-select'),
		_x('Corregimiento Los Hatillos', 'DISAFR', 'ry-wc-city-select'),
		_x('Corregimiento Remance', 'DISAFR', 'ry-wc-city-select'),
		_x('Corregimiento San Francisco', 'DISAFR', 'ry-wc-city-select'),
		_x('Corregimiento San Juan', 'DISAFR', 'ry-wc-city-select'),
		_x('San Jose', 'DISAFR', 'ry-wc-city-select'),
	],
	'DISALO' => [
		_x('Corregimiento Boca Chica', 'DISALO', 'ry-wc-city-select'),
		_x('Corregimiento Boca del Monte', 'DISALO', 'ry-wc-city-select'),
		_x('Corregimiento Horoncitos', 'DISALO', 'ry-wc-city-select'),
		_x('Corregimiento San Juan', 'DISALO', 'ry-wc-city-select'),
		_x('Corregimiento San Lorenzo', 'DISALO', 'ry-wc-city-select'),
	],
	'DISA' => [
		_x('Corregimiento Calovebora', 'DISA', 'ry-wc-city-select'),
		_x('Corregimiento El Alto', 'DISA', 'ry-wc-city-select'),
		_x('Corregimiento El Cuay', 'DISA', 'ry-wc-city-select'),
		_x('Corregimiento El Pantano', 'DISA', 'ry-wc-city-select'),
		_x('Corregimiento Gatu o Gatucito', 'DISA', 'ry-wc-city-select'),
		_x('Corregimiento Santa Fe', 'DISA', 'ry-wc-city-select'),
		_x('Rio Luis', 'DISA', 'ry-wc-city-select'),
		_x('Ruben Cantu', 'DISA', 'ry-wc-city-select'),
	],
	'DISAIS' => [
		_x('Corregimiento Cuango', 'DISAIS', 'ry-wc-city-select'),
		_x('Corregimiento Miramar', 'DISAIS', 'ry-wc-city-select'),
		_x('Corregimiento Nombre de Dios', 'DISAIS', 'ry-wc-city-select'),
		_x('Corregimiento Palenque', 'DISAIS', 'ry-wc-city-select'),
		_x('Corregimiento Palmira', 'DISAIS', 'ry-wc-city-select'),
		_x('Corregimiento Playa Chiquita', 'DISAIS', 'ry-wc-city-select'),
		_x('Corregimiento Santa Isabel', 'DISAIS', 'ry-wc-city-select'),
		_x('Corregimiento Viento Frio', 'DISAIS', 'ry-wc-city-select'),
	],
	'DISAMA' => [
		_x('Corregimiento Chupampa', 'DISAMA', 'ry-wc-city-select'),
		_x('Corregimiento El Rincon', 'DISAMA', 'ry-wc-city-select'),
		_x('Corregimiento Santa Maria', 'DISAMA', 'ry-wc-city-select'),
		_x('El Limon', 'DISAMA', 'ry-wc-city-select'),
		_x('Los Canelos', 'DISAMA', 'ry-wc-city-select'),
	],
	'DISA2' => [
		_x('Canto Del Llano', 'DISA2', 'ry-wc-city-select'),
		_x('Carlos Santana Avila', 'DISA2', 'ry-wc-city-select'),
		_x('Corregimiento La Colorada', 'DISA2', 'ry-wc-city-select'),
		_x('Corregimiento La Pena', 'DISA2', 'ry-wc-city-select'),
		_x('Corregimiento La Raya de Santa Maria', 'DISA2', 'ry-wc-city-select'),
		_x('Corregimiento Ponuga', 'DISA2', 'ry-wc-city-select'),
		_x('Corregimiento San Pedro del Espino', 'DISA2', 'ry-wc-city-select'),
		_x('Corregimiento Santiago', 'DISA2', 'ry-wc-city-select'),
		_x('Edwin Fabrega', 'DISA2', 'ry-wc-city-select'),
		_x('Los Algarrobos', 'DISA2', 'ry-wc-city-select'),
		_x('San Martin De Porres', 'DISA2', 'ry-wc-city-select'),
		_x('Urraca', 'DISA2', 'ry-wc-city-select'),
	],
	'DISO' => [
		_x('Corregimiento Bahia Honda', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento Calidonia', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento Cative', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento El Maranon', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento Guarumal', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento La Soledad', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento Quebrada de Oro', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento Rio Grande', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento Rodeo Viejo', 'DISO', 'ry-wc-city-select'),
		_x('Corregimiento Sona', 'DISO', 'ry-wc-city-select'),
	],
	'DITA' => [
		_x('Corregimiento Otoque Occidente', 'DITA', 'ry-wc-city-select'),
		_x('Corregimiento Otoque Oriente', 'DITA', 'ry-wc-city-select'),
		_x('Corregimiento Taboga', 'DITA', 'ry-wc-city-select'),
	],
	'DITO' => [
		_x('Bella Vista', 'DITO', 'ry-wc-city-select'),
		_x('Corregimiento Cerro Viejo', 'DITO', 'ry-wc-city-select'),
		_x('Corregimiento Lajas de Tole', 'DITO', 'ry-wc-city-select'),
		_x('Corregimiento Potrero de Cana', 'DITO', 'ry-wc-city-select'),
		_x('Corregimiento Quebrada de Piedra', 'DITO', 'ry-wc-city-select'),
		_x('Corregimiento Tole', 'DITO', 'ry-wc-city-select'),
		_x('El Cristo', 'DITO', 'ry-wc-city-select'),
		_x('Justo Fidel Palacios', 'DITO', 'ry-wc-city-select'),
		_x('Veladero', 'DITO', 'ry-wc-city-select'),
	],
	'DITO2' => [
		_x('Cambutal', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento Altos de Gueera', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento Canas', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento El Bebedero', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento El Cacao', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento El Cortezo', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento Flores', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento Guanico', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento La Tronosa', 'DITO2', 'ry-wc-city-select'),
		_x('Corregimiento Tonosi', 'DITO2', 'ry-wc-city-select'),
		_x('Isla De Canas', 'DITO2', 'ry-wc-city-select'),
	],
	'PO' => [
		_x('Corregimiento Ailigandi', 'PO', 'ry-wc-city-select'),
		_x('Corregimiento Puerto Obaldia', 'PO', 'ry-wc-city-select'),
		_x('Corregimiento Tubuala', 'PO', 'ry-wc-city-select'),
		_x('Nargana', 'PO', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Bisira', 'KA', 'ry-wc-city-select'),
		_x('Buri', 'KA', 'ry-wc-city-select'),
		_x('Corregimiento Canquintu', 'KA', 'ry-wc-city-select'),
		_x('Corregimiento Guoroni', 'KA', 'ry-wc-city-select'),
		_x('Corregimiento Mununi', 'KA', 'ry-wc-city-select'),
		_x('Corregimiento Piedra Roja', 'KA', 'ry-wc-city-select'),
		_x('Guariviara', 'KA', 'ry-wc-city-select'),
		_x('Man Creek', 'KA', 'ry-wc-city-select'),
		_x('Tuwai', 'KA', 'ry-wc-city-select'),
	],
	'KU' => [
		_x('Corregimiento Bahia Azul', 'KU', 'ry-wc-city-select'),
		_x('Corregimiento Calovebora', 'KU', 'ry-wc-city-select'),
		_x('Corregimiento Tobobe', 'KU', 'ry-wc-city-select'),
		_x('Kusapin', 'KU', 'ry-wc-city-select'),
		_x('Loma Yuca', 'KU', 'ry-wc-city-select'),
		_x('Rio Chiriqui', 'KU', 'ry-wc-city-select'),
		_x('Valle Bonito', 'KU', 'ry-wc-city-select'),
	],
	'MADI' => [
		_x('Corregimiento Arenas', 'MADI', 'ry-wc-city-select'),
		_x('Corregimiento Llano de Catival', 'MADI', 'ry-wc-city-select'),
		_x('Corregimiento Quebro', 'MADI', 'ry-wc-city-select'),
		_x('Corregimiento Tebario', 'MADI', 'ry-wc-city-select'),
		_x('El Cacao', 'MADI', 'ry-wc-city-select'),
	],
	'MI' => [
		_x('Corregimiento Cascabel', 'MI', 'ry-wc-city-select'),
		_x('Corregimiento Hato Corotu', 'MI', 'ry-wc-city-select'),
		_x('Corregimiento Hato Culantro', 'MI', 'ry-wc-city-select'),
		_x('Corregimiento Hato Jobo', 'MI', 'ry-wc-city-select'),
		_x('Corregimiento Hato Juli', 'MI', 'ry-wc-city-select'),
		_x('Corregimiento Hato Pilon', 'MI', 'ry-wc-city-select'),
		_x('Corregimiento Quebrada de Loro', 'MI', 'ry-wc-city-select'),
		_x('Corregimiento Salto Dupi', 'MI', 'ry-wc-city-select'),
	],
	'MU' => [
		_x('Bakama', 'MU', 'ry-wc-city-select'),
		_x('Corregimiento Alto Caballero', 'MU', 'ry-wc-city-select'),
		_x('Corregimiento Cerro Cana', 'MU', 'ry-wc-city-select'),
		_x('Corregimiento Cerro Puerco', 'MU', 'ry-wc-city-select'),
		_x('Corregimiento Chichica', 'MU', 'ry-wc-city-select'),
		_x('Corregimiento Maraca', 'MU', 'ry-wc-city-select'),
		_x('Corregimiento Pena Blanca', 'MU', 'ry-wc-city-select'),
		_x('Corregimiento Sitio Prado', 'MU', 'ry-wc-city-select'),
		_x('Krua', 'MU', 'ry-wc-city-select'),
		_x('Nibra', 'MU', 'ry-wc-city-select'),
		_x('Roka', 'MU', 'ry-wc-city-select'),
		_x('Umani', 'MU', 'ry-wc-city-select'),
	],
	'NODU' => [
		_x('Corregimiento Cerro Iglesias', 'NODU', 'ry-wc-city-select'),
		_x('Corregimiento Hato Chami', 'NODU', 'ry-wc-city-select'),
		_x('Corregimiento Lajero', 'NODU', 'ry-wc-city-select'),
		_x('Jadeberi', 'NODU', 'ry-wc-city-select'),
		_x('Susama', 'NODU', 'ry-wc-city-select'),
	],
	'NU' => [
		_x('Alto De Jesus', 'NU', 'ry-wc-city-select'),
		_x('Buenos Aires', 'NU', 'ry-wc-city-select'),
		_x('Cerro Pelado', 'NU', 'ry-wc-city-select'),
		_x('Corregimiento Agua de Salud', 'NU', 'ry-wc-city-select'),
		_x('Corregimiento El Piro', 'NU', 'ry-wc-city-select'),
		_x('El Bale', 'NU', 'ry-wc-city-select'),
		_x('El Paredon', 'NU', 'ry-wc-city-select'),
		_x('Guayabito', 'NU', 'ry-wc-city-select'),
		_x('Guibale', 'NU', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Jingurudo', 'SA', 'ry-wc-city-select'),
		_x('Rio Sabalo', 'SA', 'ry-wc-city-select'),
	],
	]
];