<?php
/**
 * Republic of Peru places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'PE' => [
	'AS' => [
		_x('Ascope', 'AS', 'ry-wc-city-select'),
		_x('Casa Grande', 'AS', 'ry-wc-city-select'),
		_x('Chicama', 'AS', 'ry-wc-city-select'),
		_x('Chocope', 'AS', 'ry-wc-city-select'),
		_x('Magdalena De Cao', 'AS', 'ry-wc-city-select'),
		_x('Paijan', 'AS', 'ry-wc-city-select'),
		_x('Razuri', 'AS', 'ry-wc-city-select'),
		_x('Santiago De Cao', 'AS', 'ry-wc-city-select'),
	],
	'AS2' => [
		_x('Acochaca', 'AS2', 'ry-wc-city-select'),
		_x('Chacas', 'AS2', 'ry-wc-city-select'),
	],
	'AT' => [
		_x('Raymondi', 'AT', 'ry-wc-city-select'),
		_x('Sepahua', 'AT', 'ry-wc-city-select'),
		_x('Tahuania', 'AT', 'ry-wc-city-select'),
		_x('Yurua', 'AT', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Barranca', 'BA', 'ry-wc-city-select'),
		_x('Paramonga', 'BA', 'ry-wc-city-select'),
		_x('Pativilca', 'BA', 'ry-wc-city-select'),
		_x('Supe', 'BA', 'ry-wc-city-select'),
		_x('Supe Puerto', 'BA', 'ry-wc-city-select'),
	],
	'BE' => [
		_x('Alto Biavo', 'BE', 'ry-wc-city-select'),
		_x('Bajo Biavo', 'BE', 'ry-wc-city-select'),
		_x('Bellavista', 'BE', 'ry-wc-city-select'),
		_x('Huallaga', 'BE', 'ry-wc-city-select'),
		_x('San Pablo', 'BE', 'ry-wc-city-select'),
		_x('San Rafael', 'BE', 'ry-wc-city-select'),
	],
	'CA2' => [
		_x('Cairani', 'CA2', 'ry-wc-city-select'),
		_x('Camilaca', 'CA2', 'ry-wc-city-select'),
		_x('Candarave', 'CA2', 'ry-wc-city-select'),
		_x('Curibaya', 'CA2', 'ry-wc-city-select'),
		_x('Huanuara', 'CA2', 'ry-wc-city-select'),
		_x('Quilahuani', 'CA2', 'ry-wc-city-select'),
	],
	'CAFEFI' => [
		_x('San Luis', 'CAFEFI', 'ry-wc-city-select'),
		_x('San Nicolas', 'CAFEFI', 'ry-wc-city-select'),
		_x('Yauya', 'CAFEFI', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Chanchamayo', 'CH', 'ry-wc-city-select'),
		_x('Perene', 'CH', 'ry-wc-city-select'),
		_x('Pichanaqui', 'CH', 'ry-wc-city-select'),
		_x('San Luis De Shuaro', 'CH', 'ry-wc-city-select'),
		_x('San Ramon', 'CH', 'ry-wc-city-select'),
		_x('Vitoc', 'CH', 'ry-wc-city-select'),
	],
	'CH2' => [
		_x('Chepen', 'CH2', 'ry-wc-city-select'),
		_x('Pacanga', 'CH2', 'ry-wc-city-select'),
		_x('Pueblo Nuevo', 'CH2', 'ry-wc-city-select'),
	],
	'CH3' => [
		_x('Anco_Huallo', 'CH3', 'ry-wc-city-select'),
		_x('Chincheros', 'CH3', 'ry-wc-city-select'),
		_x('Cocharcas', 'CH3', 'ry-wc-city-select'),
		_x('El Porvenir', 'CH3', 'ry-wc-city-select'),
		_x('Huaccana', 'CH3', 'ry-wc-city-select'),
		_x('Los Chankas', 'CH3', 'ry-wc-city-select'),
		_x('Ocobamba', 'CH3', 'ry-wc-city-select'),
		_x('Ongoy', 'CH3', 'ry-wc-city-select'),
		_x('Ranracancha', 'CH3', 'ry-wc-city-select'),
		_x('Rocchacc', 'CH3', 'ry-wc-city-select'),
		_x('Uranmarca', 'CH3', 'ry-wc-city-select'),
	],
	'CO' => [
		_x('El Cenepa', 'CO', 'ry-wc-city-select'),
		_x('Nieva', 'CO', 'ry-wc-city-select'),
		_x('Rio Santiago', 'CO', 'ry-wc-city-select'),
	],
	'DADEMA' => [
		_x('Andoas', 'DADEMA', 'ry-wc-city-select'),
		_x('Barranca', 'DADEMA', 'ry-wc-city-select'),
		_x('Cahuapanas', 'DADEMA', 'ry-wc-city-select'),
		_x('Manseriche', 'DADEMA', 'ry-wc-city-select'),
		_x('Morona', 'DADEMA', 'ry-wc-city-select'),
		_x('Pastaza', 'DADEMA', 'ry-wc-city-select'),
	],
	'CO2' => [
		_x('Capazo', 'CO2', 'ry-wc-city-select'),
		_x('Conduriri', 'CO2', 'ry-wc-city-select'),
		_x('Ilave', 'CO2', 'ry-wc-city-select'),
		_x('Pilcuyo', 'CO2', 'ry-wc-city-select'),
		_x('Santa Rosa', 'CO2', 'ry-wc-city-select'),
	],
	'DO' => [
		_x('Agua Blanca', 'DO', 'ry-wc-city-select'),
		_x('San Jose De Sisa', 'DO', 'ry-wc-city-select'),
		_x('San Martin', 'DO', 'ry-wc-city-select'),
		_x('Santa Rosa', 'DO', 'ry-wc-city-select'),
		_x('Shatoja', 'DO', 'ry-wc-city-select'),
	],
	'GRCH' => [
		_x('Cascas', 'GRCH', 'ry-wc-city-select'),
		_x('Compin', 'GRCH', 'ry-wc-city-select'),
		_x('Lucma', 'GRCH', 'ry-wc-city-select'),
		_x('Sayapullo', 'GRCH', 'ry-wc-city-select'),
	],
	'HU' => [
		_x('Canchabamba', 'HU', 'ry-wc-city-select'),
		_x('Cochabamba', 'HU', 'ry-wc-city-select'),
		_x('Huacaybamba', 'HU', 'ry-wc-city-select'),
		_x('Pinra', 'HU', 'ry-wc-city-select'),
	],
	'HU2' => [
		_x('Ambar', 'HU2', 'ry-wc-city-select'),
		_x('Caleta De Carquin', 'HU2', 'ry-wc-city-select'),
		_x('Checras', 'HU2', 'ry-wc-city-select'),
		_x('Huacho', 'HU2', 'ry-wc-city-select'),
		_x('Hualmay', 'HU2', 'ry-wc-city-select'),
		_x('Huaura', 'HU2', 'ry-wc-city-select'),
		_x('Leoncio Prado', 'HU2', 'ry-wc-city-select'),
		_x('Paccho', 'HU2', 'ry-wc-city-select'),
		_x('Santa Leonor', 'HU2', 'ry-wc-city-select'),
		_x('Santa Maria', 'HU2', 'ry-wc-city-select'),
		_x('Sayan', 'HU2', 'ry-wc-city-select'),
		_x('Vegueta', 'HU2', 'ry-wc-city-select'),
	],
	'HU3' => [
		_x('Ayavi', 'HU3', 'ry-wc-city-select'),
		_x('Cordova', 'HU3', 'ry-wc-city-select'),
		_x('Huayacundo Arma', 'HU3', 'ry-wc-city-select'),
		_x('Huaytara', 'HU3', 'ry-wc-city-select'),
		_x('Laramarca', 'HU3', 'ry-wc-city-select'),
		_x('Ocoyo', 'HU3', 'ry-wc-city-select'),
		_x('Pilpichaca', 'HU3', 'ry-wc-city-select'),
		_x('Querco', 'HU3', 'ry-wc-city-select'),
		_x('Quito-Arma', 'HU3', 'ry-wc-city-select'),
		_x('San Antonio De Cusicancha', 'HU3', 'ry-wc-city-select'),
		_x('San Francisco De Sangayaico', 'HU3', 'ry-wc-city-select'),
		_x('San Isidro', 'HU3', 'ry-wc-city-select'),
		_x('Santiago De Chocorvos', 'HU3', 'ry-wc-city-select'),
		_x('Santiago De Quirahuara', 'HU3', 'ry-wc-city-select'),
		_x('Santo Domingo De Capillas', 'HU3', 'ry-wc-city-select'),
		_x('Tambo', 'HU3', 'ry-wc-city-select'),
	],
	'JOBA' => [
		_x('Ilabaya', 'JOBA', 'ry-wc-city-select'),
		_x('Ite', 'JOBA', 'ry-wc-city-select'),
		_x('Locumba', 'JOBA', 'ry-wc-city-select'),
	],
	'JU' => [
		_x('Calamarca', 'JU', 'ry-wc-city-select'),
		_x('Carabamba', 'JU', 'ry-wc-city-select'),
		_x('Huaso', 'JU', 'ry-wc-city-select'),
		_x('Julcan', 'JU', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Banos', 'LA', 'ry-wc-city-select'),
		_x('Jesus', 'LA', 'ry-wc-city-select'),
		_x('Jivia', 'LA', 'ry-wc-city-select'),
		_x('Queropalca', 'LA', 'ry-wc-city-select'),
		_x('Rondos', 'LA', 'ry-wc-city-select'),
		_x('San Francisco De Asis', 'LA', 'ry-wc-city-select'),
		_x('San Miguel De Cauri', 'LA', 'ry-wc-city-select'),
	],
	'MARACA' => [
		_x('Pebas', 'MARACA', 'ry-wc-city-select'),
		_x('Ramon Castilla', 'MARACA', 'ry-wc-city-select'),
		_x('San Pablo', 'MARACA', 'ry-wc-city-select'),
		_x('Yavari', 'MARACA', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Conima', 'MO', 'ry-wc-city-select'),
		_x('Huayrapata', 'MO', 'ry-wc-city-select'),
		_x('Moho', 'MO', 'ry-wc-city-select'),
		_x('Tilali', 'MO', 'ry-wc-city-select'),
	],
	'MO2' => [
		_x('Buenos Aires', 'MO2', 'ry-wc-city-select'),
		_x('Chalaco', 'MO2', 'ry-wc-city-select'),
		_x('Chulucanas', 'MO2', 'ry-wc-city-select'),
		_x('La Matanza', 'MO2', 'ry-wc-city-select'),
		_x('Morropon', 'MO2', 'ry-wc-city-select'),
		_x('Salitral', 'MO2', 'ry-wc-city-select'),
		_x('San Juan De Bigote', 'MO2', 'ry-wc-city-select'),
		_x('Santa Catalina De Mossa', 'MO2', 'ry-wc-city-select'),
		_x('Santo Domingo', 'MO2', 'ry-wc-city-select'),
		_x('Yamango', 'MO2', 'ry-wc-city-select'),
	],
	'OC' => [
		_x('Acas', 'OC', 'ry-wc-city-select'),
		_x('Cajamarquilla', 'OC', 'ry-wc-city-select'),
		_x('Carhuapampa', 'OC', 'ry-wc-city-select'),
		_x('Cochas', 'OC', 'ry-wc-city-select'),
		_x('Congas', 'OC', 'ry-wc-city-select'),
		_x('Llipa', 'OC', 'ry-wc-city-select'),
		_x('Ocros', 'OC', 'ry-wc-city-select'),
		_x('San Cristobal De Rajan', 'OC', 'ry-wc-city-select'),
		_x('San Pedro', 'OC', 'ry-wc-city-select'),
		_x('Santiago De Chilcas', 'OC', 'ry-wc-city-select'),
	],
	'OY' => [
		_x('Andajes', 'OY', 'ry-wc-city-select'),
		_x('Caujul', 'OY', 'ry-wc-city-select'),
		_x('Cochamarca', 'OY', 'ry-wc-city-select'),
		_x('Navan', 'OY', 'ry-wc-city-select'),
		_x('Oyon', 'OY', 'ry-wc-city-select'),
		_x('Pachangara', 'OY', 'ry-wc-city-select'),
	],
	'PAAB' => [
		_x('Alexander Von Humboldt', 'PAAB', 'ry-wc-city-select'),
		_x('Curimana', 'PAAB', 'ry-wc-city-select'),
		_x('Irazola', 'PAAB', 'ry-wc-city-select'),
		_x('Neshuya', 'PAAB', 'ry-wc-city-select'),
		_x('Padre Abad', 'PAAB', 'ry-wc-city-select'),
	],
	'PADESASA' => [
		_x('Colta', 'PADESASA', 'ry-wc-city-select'),
		_x('Corculla', 'PADESASA', 'ry-wc-city-select'),
		_x('Lampa', 'PADESASA', 'ry-wc-city-select'),
		_x('Marcabamba', 'PADESASA', 'ry-wc-city-select'),
		_x('Oyolo', 'PADESASA', 'ry-wc-city-select'),
		_x('Pararca', 'PADESASA', 'ry-wc-city-select'),
		_x('Pausa', 'PADESASA', 'ry-wc-city-select'),
		_x('San Javier De Alpabamba', 'PADESASA', 'ry-wc-city-select'),
		_x('San Jose De Ushua', 'PADESASA', 'ry-wc-city-select'),
		_x('Sara Sara', 'PADESASA', 'ry-wc-city-select'),
	],
	'PI' => [
		_x('Buenos Aires', 'PI', 'ry-wc-city-select'),
		_x('Caspisapa', 'PI', 'ry-wc-city-select'),
		_x('Picota', 'PI', 'ry-wc-city-select'),
		_x('Pilluana', 'PI', 'ry-wc-city-select'),
		_x('Pucacaca', 'PI', 'ry-wc-city-select'),
		_x('San Cristobal', 'PI', 'ry-wc-city-select'),
		_x('San Hilarion', 'PI', 'ry-wc-city-select'),
		_x('Shamboyacu', 'PI', 'ry-wc-city-select'),
		_x('Tingo De Ponasa', 'PI', 'ry-wc-city-select'),
		_x('Tres Unidos', 'PI', 'ry-wc-city-select'),
	],
	'PRAB' => [
		_x('Abancay', 'PRAB', 'ry-wc-city-select'),
		_x('Chacoche', 'PRAB', 'ry-wc-city-select'),
		_x('Circa', 'PRAB', 'ry-wc-city-select'),
		_x('Curahuasi', 'PRAB', 'ry-wc-city-select'),
		_x('Huanipaca', 'PRAB', 'ry-wc-city-select'),
		_x('Lambrama', 'PRAB', 'ry-wc-city-select'),
		_x('Pichirhua', 'PRAB', 'ry-wc-city-select'),
		_x('San Pedro De Cachora', 'PRAB', 'ry-wc-city-select'),
		_x('Tamburco', 'PRAB', 'ry-wc-city-select'),
	],
	'PRAC' => [
		_x('Acobamba', 'PRAC', 'ry-wc-city-select'),
		_x('Andabamba', 'PRAC', 'ry-wc-city-select'),
		_x('Anta', 'PRAC', 'ry-wc-city-select'),
		_x('Caja', 'PRAC', 'ry-wc-city-select'),
		_x('Marcas', 'PRAC', 'ry-wc-city-select'),
		_x('Paucara', 'PRAC', 'ry-wc-city-select'),
		_x('Pomacocha', 'PRAC', 'ry-wc-city-select'),
		_x('Rosario', 'PRAC', 'ry-wc-city-select'),
	],
	'PRAC2' => [
		_x('Acomayo', 'PRAC2', 'ry-wc-city-select'),
		_x('Acopia', 'PRAC2', 'ry-wc-city-select'),
		_x('Acos', 'PRAC2', 'ry-wc-city-select'),
		_x('Mosoc Llacta', 'PRAC2', 'ry-wc-city-select'),
		_x('Pomacanchi', 'PRAC2', 'ry-wc-city-select'),
		_x('Rondocan', 'PRAC2', 'ry-wc-city-select'),
		_x('Sangarara', 'PRAC2', 'ry-wc-city-select'),
	],
	'PRAI' => [
		_x('Aija', 'PRAI', 'ry-wc-city-select'),
		_x('Coris', 'PRAI', 'ry-wc-city-select'),
		_x('Huacllan', 'PRAI', 'ry-wc-city-select'),
		_x('La Merced', 'PRAI', 'ry-wc-city-select'),
		_x('Succha', 'PRAI', 'ry-wc-city-select'),
	],
	'PRALAM' => [
		_x('Balsapuerto', 'PRALAM', 'ry-wc-city-select'),
		_x('Jeberos', 'PRALAM', 'ry-wc-city-select'),
		_x('Lagunas', 'PRALAM', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRALAM', 'ry-wc-city-select'),
		_x('Teniente Cesar Lopez Rojas', 'PRALAM', 'ry-wc-city-select'),
		_x('Yurimaguas', 'PRALAM', 'ry-wc-city-select'),
	],
	'PRAM' => [
		_x('Ambo', 'PRAM', 'ry-wc-city-select'),
		_x('Cayna', 'PRAM', 'ry-wc-city-select'),
		_x('Colpas', 'PRAM', 'ry-wc-city-select'),
		_x('Conchamarca', 'PRAM', 'ry-wc-city-select'),
		_x('Huacar', 'PRAM', 'ry-wc-city-select'),
		_x('San Francisco', 'PRAM', 'ry-wc-city-select'),
		_x('San Rafael', 'PRAM', 'ry-wc-city-select'),
		_x('Tomay Kichwa', 'PRAM', 'ry-wc-city-select'),
	],
	'PRAN' => [
		_x('Andahuaylas', 'PRAN', 'ry-wc-city-select'),
		_x('Andarapa', 'PRAN', 'ry-wc-city-select'),
		_x('Chiara', 'PRAN', 'ry-wc-city-select'),
		_x('Huancarama', 'PRAN', 'ry-wc-city-select'),
		_x('Huancaray', 'PRAN', 'ry-wc-city-select'),
		_x('Huayana', 'PRAN', 'ry-wc-city-select'),
		_x('Jose Maria Arguedas', 'PRAN', 'ry-wc-city-select'),
		_x('Kaquiabamba', 'PRAN', 'ry-wc-city-select'),
		_x('Kishuara', 'PRAN', 'ry-wc-city-select'),
		_x('Pacobamba', 'PRAN', 'ry-wc-city-select'),
		_x('Pacucha', 'PRAN', 'ry-wc-city-select'),
		_x('Pampachiri', 'PRAN', 'ry-wc-city-select'),
		_x('Pomacocha', 'PRAN', 'ry-wc-city-select'),
		_x('San Antonio De Cachi', 'PRAN', 'ry-wc-city-select'),
		_x('San Jeronimo', 'PRAN', 'ry-wc-city-select'),
		_x('San Miguel De Chaccrampa', 'PRAN', 'ry-wc-city-select'),
		_x('Santa Maria De Chicmo', 'PRAN', 'ry-wc-city-select'),
		_x('Talavera', 'PRAN', 'ry-wc-city-select'),
		_x('Tumay Huaraca', 'PRAN', 'ry-wc-city-select'),
		_x('Turpo', 'PRAN', 'ry-wc-city-select'),
	],
	'PRAN2' => [
		_x('Anchonga', 'PRAN2', 'ry-wc-city-select'),
		_x('Callanmarca', 'PRAN2', 'ry-wc-city-select'),
		_x('Ccochaccasa', 'PRAN2', 'ry-wc-city-select'),
		_x('Chincho', 'PRAN2', 'ry-wc-city-select'),
		_x('Congalla', 'PRAN2', 'ry-wc-city-select'),
		_x('Huanca-Huanca', 'PRAN2', 'ry-wc-city-select'),
		_x('Huayllay Grande', 'PRAN2', 'ry-wc-city-select'),
		_x('Julcamarca', 'PRAN2', 'ry-wc-city-select'),
		_x('Lircay', 'PRAN2', 'ry-wc-city-select'),
		_x('San Antonio De Antaparco', 'PRAN2', 'ry-wc-city-select'),
		_x('Santo Tomas De Pata', 'PRAN2', 'ry-wc-city-select'),
		_x('Secclla', 'PRAN2', 'ry-wc-city-select'),
	],
	'PRAN3' => [
		_x('Ancahuasi', 'PRAN3', 'ry-wc-city-select'),
		_x('Anta', 'PRAN3', 'ry-wc-city-select'),
		_x('Cachimayo', 'PRAN3', 'ry-wc-city-select'),
		_x('Chinchaypujio', 'PRAN3', 'ry-wc-city-select'),
		_x('Huarocondo', 'PRAN3', 'ry-wc-city-select'),
		_x('Limatambo', 'PRAN3', 'ry-wc-city-select'),
		_x('Mollepata', 'PRAN3', 'ry-wc-city-select'),
		_x('Pucyura', 'PRAN3', 'ry-wc-city-select'),
		_x('Zurite', 'PRAN3', 'ry-wc-city-select'),
	],
	'PRAN4' => [
		_x('Antabamba', 'PRAN4', 'ry-wc-city-select'),
		_x('El Oro', 'PRAN4', 'ry-wc-city-select'),
		_x('Huaquirca', 'PRAN4', 'ry-wc-city-select'),
		_x('Juan Espinoza Medrano', 'PRAN4', 'ry-wc-city-select'),
		_x('Oropesa', 'PRAN4', 'ry-wc-city-select'),
		_x('Pachaconas', 'PRAN4', 'ry-wc-city-select'),
		_x('Sabaino', 'PRAN4', 'ry-wc-city-select'),
	],
	'PRANRA' => [
		_x('Aczo', 'PRANRA', 'ry-wc-city-select'),
		_x('Chaccho', 'PRANRA', 'ry-wc-city-select'),
		_x('Chingas', 'PRANRA', 'ry-wc-city-select'),
		_x('Llamellin', 'PRANRA', 'ry-wc-city-select'),
		_x('Mirgas', 'PRANRA', 'ry-wc-city-select'),
		_x('San Juan De Rontoy', 'PRANRA', 'ry-wc-city-select'),
	],
	'PRAR' => [
		_x('Alto Selva Alegre', 'PRAR', 'ry-wc-city-select'),
		_x('Arequipa', 'PRAR', 'ry-wc-city-select'),
		_x('Cayma', 'PRAR', 'ry-wc-city-select'),
		_x('Cerro Colorado', 'PRAR', 'ry-wc-city-select'),
		_x('Characato', 'PRAR', 'ry-wc-city-select'),
		_x('Chiguata', 'PRAR', 'ry-wc-city-select'),
		_x('Jacobo Hunter', 'PRAR', 'ry-wc-city-select'),
		_x('Jose Luis Bustamante Y Rivero', 'PRAR', 'ry-wc-city-select'),
		_x('La Joya', 'PRAR', 'ry-wc-city-select'),
		_x('Mariano Melgar', 'PRAR', 'ry-wc-city-select'),
		_x('Miraflores', 'PRAR', 'ry-wc-city-select'),
		_x('Mollebaya', 'PRAR', 'ry-wc-city-select'),
		_x('Paucarpata', 'PRAR', 'ry-wc-city-select'),
		_x('Pocsi', 'PRAR', 'ry-wc-city-select'),
		_x('Polobaya', 'PRAR', 'ry-wc-city-select'),
		_x('Quequena', 'PRAR', 'ry-wc-city-select'),
		_x('Sabandia', 'PRAR', 'ry-wc-city-select'),
		_x('Sachaca', 'PRAR', 'ry-wc-city-select'),
		_x('San Juan De Siguas', 'PRAR', 'ry-wc-city-select'),
		_x('San Juan De Tarucani', 'PRAR', 'ry-wc-city-select'),
		_x('Santa Isabel De Siguas', 'PRAR', 'ry-wc-city-select'),
		_x('Santa Rita De Siguas', 'PRAR', 'ry-wc-city-select'),
		_x('Socabaya', 'PRAR', 'ry-wc-city-select'),
		_x('Tiabaya', 'PRAR', 'ry-wc-city-select'),
		_x('Uchumayo', 'PRAR', 'ry-wc-city-select'),
		_x('Vitor', 'PRAR', 'ry-wc-city-select'),
		_x('Yanahuara', 'PRAR', 'ry-wc-city-select'),
		_x('Yarabamba', 'PRAR', 'ry-wc-city-select'),
		_x('Yura', 'PRAR', 'ry-wc-city-select'),
	],
	'PRAY' => [
		_x('Ayabaca', 'PRAY', 'ry-wc-city-select'),
		_x('Frias', 'PRAY', 'ry-wc-city-select'),
		_x('Jilili', 'PRAY', 'ry-wc-city-select'),
		_x('Lagunas', 'PRAY', 'ry-wc-city-select'),
		_x('Montero', 'PRAY', 'ry-wc-city-select'),
		_x('Pacaipampa', 'PRAY', 'ry-wc-city-select'),
		_x('Paimas', 'PRAY', 'ry-wc-city-select'),
		_x('Sapillica', 'PRAY', 'ry-wc-city-select'),
		_x('Sicchez', 'PRAY', 'ry-wc-city-select'),
		_x('Suyo', 'PRAY', 'ry-wc-city-select'),
	],
	'PRAY2' => [
		_x('Capaya', 'PRAY2', 'ry-wc-city-select'),
		_x('Caraybamba', 'PRAY2', 'ry-wc-city-select'),
		_x('Chalhuanca', 'PRAY2', 'ry-wc-city-select'),
		_x('Chapimarca', 'PRAY2', 'ry-wc-city-select'),
		_x('Colcabamba', 'PRAY2', 'ry-wc-city-select'),
		_x('Cotaruse', 'PRAY2', 'ry-wc-city-select'),
		_x('Huayllo', 'PRAY2', 'ry-wc-city-select'),
		_x('Justo Apu Sahuaraura', 'PRAY2', 'ry-wc-city-select'),
		_x('Lucre', 'PRAY2', 'ry-wc-city-select'),
		_x('Pocohuanca', 'PRAY2', 'ry-wc-city-select'),
		_x('San Juan De Chacna', 'PRAY2', 'ry-wc-city-select'),
		_x('Sanayca', 'PRAY2', 'ry-wc-city-select'),
		_x('Soraya', 'PRAY2', 'ry-wc-city-select'),
		_x('Tapairihua', 'PRAY2', 'ry-wc-city-select'),
		_x('Tintay', 'PRAY2', 'ry-wc-city-select'),
		_x('Toraya', 'PRAY2', 'ry-wc-city-select'),
		_x('Yanaca', 'PRAY2', 'ry-wc-city-select'),
	],
	'PRAZ' => [
		_x('Achaya', 'PRAZ', 'ry-wc-city-select'),
		_x('Arapa', 'PRAZ', 'ry-wc-city-select'),
		_x('Asillo', 'PRAZ', 'ry-wc-city-select'),
		_x('Azangaro', 'PRAZ', 'ry-wc-city-select'),
		_x('Caminaca', 'PRAZ', 'ry-wc-city-select'),
		_x('Chupa', 'PRAZ', 'ry-wc-city-select'),
		_x('Jose Domingo Choquehuanca', 'PRAZ', 'ry-wc-city-select'),
		_x('Munani', 'PRAZ', 'ry-wc-city-select'),
		_x('Potoni', 'PRAZ', 'ry-wc-city-select'),
		_x('Saman', 'PRAZ', 'ry-wc-city-select'),
		_x('San Anton', 'PRAZ', 'ry-wc-city-select'),
		_x('San Jose', 'PRAZ', 'ry-wc-city-select'),
		_x('San Juan De Salinas', 'PRAZ', 'ry-wc-city-select'),
		_x('Santiago De Pupuja', 'PRAZ', 'ry-wc-city-select'),
		_x('Tirapata', 'PRAZ', 'ry-wc-city-select'),
	],
	'PRBA' => [
		_x('Aramango', 'PRBA', 'ry-wc-city-select'),
		_x('Bagua', 'PRBA', 'ry-wc-city-select'),
		_x('Copallin', 'PRBA', 'ry-wc-city-select'),
		_x('El Parco', 'PRBA', 'ry-wc-city-select'),
		_x('Imaza', 'PRBA', 'ry-wc-city-select'),
		_x('La Peca', 'PRBA', 'ry-wc-city-select'),
	],
	'PRBO' => [
		_x('Bambamarca', 'PRBO', 'ry-wc-city-select'),
		_x('Bolivar', 'PRBO', 'ry-wc-city-select'),
		_x('Condormarca', 'PRBO', 'ry-wc-city-select'),
		_x('Longotea', 'PRBO', 'ry-wc-city-select'),
		_x('Uchumarca', 'PRBO', 'ry-wc-city-select'),
		_x('Ucuncha', 'PRBO', 'ry-wc-city-select'),
	],
	'PRBO2' => [
		_x('Abelardo Pardo Lezameta', 'PRBO2', 'ry-wc-city-select'),
		_x('Antonio Raymondi', 'PRBO2', 'ry-wc-city-select'),
		_x('Aquia', 'PRBO2', 'ry-wc-city-select'),
		_x('Cajacay', 'PRBO2', 'ry-wc-city-select'),
		_x('Canis', 'PRBO2', 'ry-wc-city-select'),
		_x('Chiquian', 'PRBO2', 'ry-wc-city-select'),
		_x('Colquioc', 'PRBO2', 'ry-wc-city-select'),
		_x('Huallanca', 'PRBO2', 'ry-wc-city-select'),
		_x('Huasta', 'PRBO2', 'ry-wc-city-select'),
		_x('Huayllacayan', 'PRBO2', 'ry-wc-city-select'),
		_x('La Primavera', 'PRBO2', 'ry-wc-city-select'),
		_x('Mangas', 'PRBO2', 'ry-wc-city-select'),
		_x('Pacllon', 'PRBO2', 'ry-wc-city-select'),
		_x('San Miguel De Corpanqui', 'PRBO2', 'ry-wc-city-select'),
		_x('Ticllos', 'PRBO2', 'ry-wc-city-select'),
	],
	'PRBO3' => [
		_x('Chisquilla', 'PRBO3', 'ry-wc-city-select'),
		_x('Churuja', 'PRBO3', 'ry-wc-city-select'),
		_x('Corosha', 'PRBO3', 'ry-wc-city-select'),
		_x('Cuispes', 'PRBO3', 'ry-wc-city-select'),
		_x('Florida', 'PRBO3', 'ry-wc-city-select'),
		_x('Jazan', 'PRBO3', 'ry-wc-city-select'),
		_x('Jumbilla', 'PRBO3', 'ry-wc-city-select'),
		_x('Recta', 'PRBO3', 'ry-wc-city-select'),
		_x('San Carlos', 'PRBO3', 'ry-wc-city-select'),
		_x('Shipasbamba', 'PRBO3', 'ry-wc-city-select'),
		_x('Valera', 'PRBO3', 'ry-wc-city-select'),
		_x('Yambrasbamba', 'PRBO3', 'ry-wc-city-select'),
	],
	'PRCA' => [
		_x('Cachachi', 'PRCA', 'ry-wc-city-select'),
		_x('Cajabamba', 'PRCA', 'ry-wc-city-select'),
		_x('Condebamba', 'PRCA', 'ry-wc-city-select'),
		_x('Sitacocha', 'PRCA', 'ry-wc-city-select'),
	],
	'PRCA2' => [
		_x('Asuncion', 'PRCA2', 'ry-wc-city-select'),
		_x('Cajamarca', 'PRCA2', 'ry-wc-city-select'),
		_x('Chetilla', 'PRCA2', 'ry-wc-city-select'),
		_x('Cospan', 'PRCA2', 'ry-wc-city-select'),
		_x('Encanada', 'PRCA2', 'ry-wc-city-select'),
		_x('Jesus', 'PRCA2', 'ry-wc-city-select'),
		_x('Llacanora', 'PRCA2', 'ry-wc-city-select'),
		_x('Los Banos Del Inca', 'PRCA2', 'ry-wc-city-select'),
		_x('Magdalena', 'PRCA2', 'ry-wc-city-select'),
		_x('Matara', 'PRCA2', 'ry-wc-city-select'),
		_x('Namora', 'PRCA2', 'ry-wc-city-select'),
		_x('San Juan', 'PRCA2', 'ry-wc-city-select'),
	],
	'PRCA3' => [
		_x('Cajatambo', 'PRCA3', 'ry-wc-city-select'),
		_x('Copa', 'PRCA3', 'ry-wc-city-select'),
		_x('Gorgor', 'PRCA3', 'ry-wc-city-select'),
		_x('Huancapon', 'PRCA3', 'ry-wc-city-select'),
		_x('Manas', 'PRCA3', 'ry-wc-city-select'),
	],
	'PRCA4' => [
		_x('Calca', 'PRCA4', 'ry-wc-city-select'),
		_x('Coya', 'PRCA4', 'ry-wc-city-select'),
		_x('Lamay', 'PRCA4', 'ry-wc-city-select'),
		_x('Lares', 'PRCA4', 'ry-wc-city-select'),
		_x('Pisac', 'PRCA4', 'ry-wc-city-select'),
		_x('San Salvador', 'PRCA4', 'ry-wc-city-select'),
		_x('Taray', 'PRCA4', 'ry-wc-city-select'),
		_x('Yanatile', 'PRCA4', 'ry-wc-city-select'),
	],
	'PRCA5' => [
		_x('Camana', 'PRCA5', 'ry-wc-city-select'),
		_x('Jose Maria Quimper', 'PRCA5', 'ry-wc-city-select'),
		_x('Mariano Nicolas Valcarcel', 'PRCA5', 'ry-wc-city-select'),
		_x('Mariscal Caceres', 'PRCA5', 'ry-wc-city-select'),
		_x('Nicolas De Pierola', 'PRCA5', 'ry-wc-city-select'),
		_x('Ocona', 'PRCA5', 'ry-wc-city-select'),
		_x('Quilca', 'PRCA5', 'ry-wc-city-select'),
		_x('Samuel Pastor', 'PRCA5', 'ry-wc-city-select'),
	],
	'PRCA6' => [
		_x('Checca', 'PRCA6', 'ry-wc-city-select'),
		_x('Kunturkanki', 'PRCA6', 'ry-wc-city-select'),
		_x('Langui', 'PRCA6', 'ry-wc-city-select'),
		_x('Layo', 'PRCA6', 'ry-wc-city-select'),
		_x('Pampamarca', 'PRCA6', 'ry-wc-city-select'),
		_x('Quehue', 'PRCA6', 'ry-wc-city-select'),
		_x('Tupac Amaru', 'PRCA6', 'ry-wc-city-select'),
		_x('Yanaoca', 'PRCA6', 'ry-wc-city-select'),
	],
	'PRCA7' => [
		_x('Checacupe', 'PRCA7', 'ry-wc-city-select'),
		_x('Combapata', 'PRCA7', 'ry-wc-city-select'),
		_x('Marangani', 'PRCA7', 'ry-wc-city-select'),
		_x('Pitumarca', 'PRCA7', 'ry-wc-city-select'),
		_x('San Pablo', 'PRCA7', 'ry-wc-city-select'),
		_x('San Pedro', 'PRCA7', 'ry-wc-city-select'),
		_x('Sicuani', 'PRCA7', 'ry-wc-city-select'),
		_x('Tinta', 'PRCA7', 'ry-wc-city-select'),
	],
	'PRCA8' => [
		_x('Asia', 'PRCA8', 'ry-wc-city-select'),
		_x('Calango', 'PRCA8', 'ry-wc-city-select'),
		_x('Cerro Azul', 'PRCA8', 'ry-wc-city-select'),
		_x('Chilca', 'PRCA8', 'ry-wc-city-select'),
		_x('Coayllo', 'PRCA8', 'ry-wc-city-select'),
		_x('Imperial', 'PRCA8', 'ry-wc-city-select'),
		_x('Lunahuana', 'PRCA8', 'ry-wc-city-select'),
		_x('Mala', 'PRCA8', 'ry-wc-city-select'),
		_x('Nuevo Imperial', 'PRCA8', 'ry-wc-city-select'),
		_x('Pacaran', 'PRCA8', 'ry-wc-city-select'),
		_x('Quilmana', 'PRCA8', 'ry-wc-city-select'),
		_x('San Antonio', 'PRCA8', 'ry-wc-city-select'),
		_x('San Luis', 'PRCA8', 'ry-wc-city-select'),
		_x('San Vicente De Canete', 'PRCA8', 'ry-wc-city-select'),
		_x('Santa Cruz De Flores', 'PRCA8', 'ry-wc-city-select'),
		_x('Zuniga', 'PRCA8', 'ry-wc-city-select'),
	],
	'PRCA9' => [
		_x('Cangallo', 'PRCA9', 'ry-wc-city-select'),
		_x('Chuschi', 'PRCA9', 'ry-wc-city-select'),
		_x('Los Morochucos', 'PRCA9', 'ry-wc-city-select'),
		_x('Maria Parado De Bellido', 'PRCA9', 'ry-wc-city-select'),
		_x('Paras', 'PRCA9', 'ry-wc-city-select'),
		_x('Totos', 'PRCA9', 'ry-wc-city-select'),
	],
	'PRCA10' => [
		_x('Arahuay', 'PRCA10', 'ry-wc-city-select'),
		_x('Canta', 'PRCA10', 'ry-wc-city-select'),
		_x('Huamantanga', 'PRCA10', 'ry-wc-city-select'),
		_x('Huaros', 'PRCA10', 'ry-wc-city-select'),
		_x('Lachaqui', 'PRCA10', 'ry-wc-city-select'),
		_x('San Buenaventura', 'PRCA10', 'ry-wc-city-select'),
		_x('Santa Rosa De Quives', 'PRCA10', 'ry-wc-city-select'),
	],
	'PRCA11' => [
		_x('Ajoyani', 'PRCA11', 'ry-wc-city-select'),
		_x('Ayapata', 'PRCA11', 'ry-wc-city-select'),
		_x('Coasa', 'PRCA11', 'ry-wc-city-select'),
		_x('Corani', 'PRCA11', 'ry-wc-city-select'),
		_x('Crucero', 'PRCA11', 'ry-wc-city-select'),
		_x('Ituata', 'PRCA11', 'ry-wc-city-select'),
		_x('Macusani', 'PRCA11', 'ry-wc-city-select'),
		_x('Ollachea', 'PRCA11', 'ry-wc-city-select'),
		_x('San Gaban', 'PRCA11', 'ry-wc-city-select'),
		_x('Usicayos', 'PRCA11', 'ry-wc-city-select'),
	],
	'PRCA12' => [
		_x('Acari', 'PRCA12', 'ry-wc-city-select'),
		_x('Atico', 'PRCA12', 'ry-wc-city-select'),
		_x('Atiquipa', 'PRCA12', 'ry-wc-city-select'),
		_x('Bella Union', 'PRCA12', 'ry-wc-city-select'),
		_x('Cahuacho', 'PRCA12', 'ry-wc-city-select'),
		_x('Caraveli', 'PRCA12', 'ry-wc-city-select'),
		_x('Chala', 'PRCA12', 'ry-wc-city-select'),
		_x('Chaparra', 'PRCA12', 'ry-wc-city-select'),
		_x('Huanuhuanu', 'PRCA12', 'ry-wc-city-select'),
		_x('Jaqui', 'PRCA12', 'ry-wc-city-select'),
		_x('Lomas', 'PRCA12', 'ry-wc-city-select'),
		_x('Quicacha', 'PRCA12', 'ry-wc-city-select'),
		_x('Yauca', 'PRCA12', 'ry-wc-city-select'),
	],
	'PRCA13' => [
		_x('Acopampa', 'PRCA13', 'ry-wc-city-select'),
		_x('Amashca', 'PRCA13', 'ry-wc-city-select'),
		_x('Anta', 'PRCA13', 'ry-wc-city-select'),
		_x('Ataquero', 'PRCA13', 'ry-wc-city-select'),
		_x('Carhuaz', 'PRCA13', 'ry-wc-city-select'),
		_x('Marcara', 'PRCA13', 'ry-wc-city-select'),
		_x('Pariahuanca', 'PRCA13', 'ry-wc-city-select'),
		_x('San Miguel De Aco', 'PRCA13', 'ry-wc-city-select'),
		_x('Shilla', 'PRCA13', 'ry-wc-city-select'),
		_x('Tinco', 'PRCA13', 'ry-wc-city-select'),
		_x('Yungar', 'PRCA13', 'ry-wc-city-select'),
	],
	'PRCA14' => [
		_x('Buena Vista Alta', 'PRCA14', 'ry-wc-city-select'),
		_x('Casma', 'PRCA14', 'ry-wc-city-select'),
		_x('Comandante Noel', 'PRCA14', 'ry-wc-city-select'),
		_x('Yautan', 'PRCA14', 'ry-wc-city-select'),
	],
	'PRCA15' => [
		_x('Andagua', 'PRCA15', 'ry-wc-city-select'),
		_x('Aplao', 'PRCA15', 'ry-wc-city-select'),
		_x('Ayo', 'PRCA15', 'ry-wc-city-select'),
		_x('Chachas', 'PRCA15', 'ry-wc-city-select'),
		_x('Chilcaymarca', 'PRCA15', 'ry-wc-city-select'),
		_x('Choco', 'PRCA15', 'ry-wc-city-select'),
		_x('Huancarqui', 'PRCA15', 'ry-wc-city-select'),
		_x('Machaguay', 'PRCA15', 'ry-wc-city-select'),
		_x('Orcopampa', 'PRCA15', 'ry-wc-city-select'),
		_x('Pampacolca', 'PRCA15', 'ry-wc-city-select'),
		_x('Tipan', 'PRCA15', 'ry-wc-city-select'),
		_x('Unon', 'PRCA15', 'ry-wc-city-select'),
		_x('Uraca', 'PRCA15', 'ry-wc-city-select'),
		_x('Viraco', 'PRCA15', 'ry-wc-city-select'),
	],
	'PRCA16' => [
		_x('Arma', 'PRCA16', 'ry-wc-city-select'),
		_x('Aurahua', 'PRCA16', 'ry-wc-city-select'),
		_x('Capillas', 'PRCA16', 'ry-wc-city-select'),
		_x('Castrovirreyna', 'PRCA16', 'ry-wc-city-select'),
		_x('Chupamarca', 'PRCA16', 'ry-wc-city-select'),
		_x('Cocas', 'PRCA16', 'ry-wc-city-select'),
		_x('Huachos', 'PRCA16', 'ry-wc-city-select'),
		_x('Huamatambo', 'PRCA16', 'ry-wc-city-select'),
		_x('Mollepampa', 'PRCA16', 'ry-wc-city-select'),
		_x('San Juan', 'PRCA16', 'ry-wc-city-select'),
		_x('Santa Ana', 'PRCA16', 'ry-wc-city-select'),
		_x('Tantara', 'PRCA16', 'ry-wc-city-select'),
		_x('Ticrapo', 'PRCA16', 'ry-wc-city-select'),
	],
	'PRCA17' => [
		_x('Achoma', 'PRCA17', 'ry-wc-city-select'),
		_x('Cabanaconde', 'PRCA17', 'ry-wc-city-select'),
		_x('Callalli', 'PRCA17', 'ry-wc-city-select'),
		_x('Caylloma', 'PRCA17', 'ry-wc-city-select'),
		_x('Chivay', 'PRCA17', 'ry-wc-city-select'),
		_x('Coporaque', 'PRCA17', 'ry-wc-city-select'),
		_x('Huambo', 'PRCA17', 'ry-wc-city-select'),
		_x('Huanca', 'PRCA17', 'ry-wc-city-select'),
		_x('Ichupampa', 'PRCA17', 'ry-wc-city-select'),
		_x('Lari', 'PRCA17', 'ry-wc-city-select'),
		_x('Lluta', 'PRCA17', 'ry-wc-city-select'),
		_x('Maca', 'PRCA17', 'ry-wc-city-select'),
		_x('Madrigal', 'PRCA17', 'ry-wc-city-select'),
		_x('Majes', 'PRCA17', 'ry-wc-city-select'),
		_x('San Antonio De Chuca', 'PRCA17', 'ry-wc-city-select'),
		_x('Sibayo', 'PRCA17', 'ry-wc-city-select'),
		_x('Tapay', 'PRCA17', 'ry-wc-city-select'),
		_x('Tisco', 'PRCA17', 'ry-wc-city-select'),
		_x('Tuti', 'PRCA17', 'ry-wc-city-select'),
		_x('Yanque', 'PRCA17', 'ry-wc-city-select'),
	],
	'PRCE' => [
		_x('Celendin', 'PRCE', 'ry-wc-city-select'),
		_x('Chumuch', 'PRCE', 'ry-wc-city-select'),
		_x('Cortegana', 'PRCE', 'ry-wc-city-select'),
		_x('Huasmin', 'PRCE', 'ry-wc-city-select'),
		_x('Jorge Chavez', 'PRCE', 'ry-wc-city-select'),
		_x('Jose Galvez', 'PRCE', 'ry-wc-city-select'),
		_x('La Libertad De Pallan', 'PRCE', 'ry-wc-city-select'),
		_x('Miguel Iglesias', 'PRCE', 'ry-wc-city-select'),
		_x('Oxamarca', 'PRCE', 'ry-wc-city-select'),
		_x('Sorochuco', 'PRCE', 'ry-wc-city-select'),
		_x('Sucre', 'PRCE', 'ry-wc-city-select'),
		_x('Utco', 'PRCE', 'ry-wc-city-select'),
	],
	'PRCH' => [
		_x('Asuncion', 'PRCH', 'ry-wc-city-select'),
		_x('Balsas', 'PRCH', 'ry-wc-city-select'),
		_x('Chachapoyas', 'PRCH', 'ry-wc-city-select'),
		_x('Cheto', 'PRCH', 'ry-wc-city-select'),
		_x('Chiliquin', 'PRCH', 'ry-wc-city-select'),
		_x('Chuquibamba', 'PRCH', 'ry-wc-city-select'),
		_x('Granada', 'PRCH', 'ry-wc-city-select'),
		_x('Huancas', 'PRCH', 'ry-wc-city-select'),
		_x('La Jalca', 'PRCH', 'ry-wc-city-select'),
		_x('Leimebamba', 'PRCH', 'ry-wc-city-select'),
		_x('Levanto', 'PRCH', 'ry-wc-city-select'),
		_x('Magdalena', 'PRCH', 'ry-wc-city-select'),
		_x('Mariscal Castilla', 'PRCH', 'ry-wc-city-select'),
		_x('Molinopampa', 'PRCH', 'ry-wc-city-select'),
		_x('Montevideo', 'PRCH', 'ry-wc-city-select'),
		_x('Olleros', 'PRCH', 'ry-wc-city-select'),
		_x('Quinjalca', 'PRCH', 'ry-wc-city-select'),
		_x('San Francisco De Daguas', 'PRCH', 'ry-wc-city-select'),
		_x('San Isidro De Maino', 'PRCH', 'ry-wc-city-select'),
		_x('Soloco', 'PRCH', 'ry-wc-city-select'),
		_x('Sonche', 'PRCH', 'ry-wc-city-select'),
	],
	'PRCH2' => [
		_x('Cayalti', 'PRCH2', 'ry-wc-city-select'),
		_x('Chiclayo', 'PRCH2', 'ry-wc-city-select'),
		_x('Chongoyape', 'PRCH2', 'ry-wc-city-select'),
		_x('Eten', 'PRCH2', 'ry-wc-city-select'),
		_x('Eten Puerto', 'PRCH2', 'ry-wc-city-select'),
		_x('Jose Leonardo Ortiz', 'PRCH2', 'ry-wc-city-select'),
		_x('La Victoria', 'PRCH2', 'ry-wc-city-select'),
		_x('Lagunas', 'PRCH2', 'ry-wc-city-select'),
		_x('Monsefu', 'PRCH2', 'ry-wc-city-select'),
		_x('Nueva Arica', 'PRCH2', 'ry-wc-city-select'),
		_x('Oyotun', 'PRCH2', 'ry-wc-city-select'),
		_x('Patapo', 'PRCH2', 'ry-wc-city-select'),
		_x('Picsi', 'PRCH2', 'ry-wc-city-select'),
		_x('Pimentel', 'PRCH2', 'ry-wc-city-select'),
		_x('Pomalca', 'PRCH2', 'ry-wc-city-select'),
		_x('Pucala', 'PRCH2', 'ry-wc-city-select'),
		_x('Reque', 'PRCH2', 'ry-wc-city-select'),
		_x('Sana', 'PRCH2', 'ry-wc-city-select'),
		_x('Santa Rosa', 'PRCH2', 'ry-wc-city-select'),
		_x('Tuman', 'PRCH2', 'ry-wc-city-select'),
	],
	'PRCH3' => [
		_x('Alto Laran', 'PRCH3', 'ry-wc-city-select'),
		_x('Chavin', 'PRCH3', 'ry-wc-city-select'),
		_x('Chincha Alta', 'PRCH3', 'ry-wc-city-select'),
		_x('Chincha Baja', 'PRCH3', 'ry-wc-city-select'),
		_x('El Carmen', 'PRCH3', 'ry-wc-city-select'),
		_x('Grocio Prado', 'PRCH3', 'ry-wc-city-select'),
		_x('Pueblo Nuevo', 'PRCH3', 'ry-wc-city-select'),
		_x('San Juan De Yanac', 'PRCH3', 'ry-wc-city-select'),
		_x('San Pedro De Huacarpana', 'PRCH3', 'ry-wc-city-select'),
		_x('Sunampe', 'PRCH3', 'ry-wc-city-select'),
		_x('Tambo De Mora', 'PRCH3', 'ry-wc-city-select'),
	],
	'PRCH4' => [
		_x('Anguia', 'PRCH4', 'ry-wc-city-select'),
		_x('Chadin', 'PRCH4', 'ry-wc-city-select'),
		_x('Chalamarca', 'PRCH4', 'ry-wc-city-select'),
		_x('Chiguirip', 'PRCH4', 'ry-wc-city-select'),
		_x('Chimban', 'PRCH4', 'ry-wc-city-select'),
		_x('Choropampa', 'PRCH4', 'ry-wc-city-select'),
		_x('Chota', 'PRCH4', 'ry-wc-city-select'),
		_x('Cochabamba', 'PRCH4', 'ry-wc-city-select'),
		_x('Conchan', 'PRCH4', 'ry-wc-city-select'),
		_x('Huambos', 'PRCH4', 'ry-wc-city-select'),
		_x('Lajas', 'PRCH4', 'ry-wc-city-select'),
		_x('Llama', 'PRCH4', 'ry-wc-city-select'),
		_x('Miracosta', 'PRCH4', 'ry-wc-city-select'),
		_x('Paccha', 'PRCH4', 'ry-wc-city-select'),
		_x('Pion', 'PRCH4', 'ry-wc-city-select'),
		_x('Querocoto', 'PRCH4', 'ry-wc-city-select'),
		_x('San Juan De Licupis', 'PRCH4', 'ry-wc-city-select'),
		_x('Tacabamba', 'PRCH4', 'ry-wc-city-select'),
		_x('Tocmoche', 'PRCH4', 'ry-wc-city-select'),
	],
	'PRCH5' => [
		_x('Desaguadero', 'PRCH5', 'ry-wc-city-select'),
		_x('Huacullani', 'PRCH5', 'ry-wc-city-select'),
		_x('Juli', 'PRCH5', 'ry-wc-city-select'),
		_x('Kelluyo', 'PRCH5', 'ry-wc-city-select'),
		_x('Pisacoma', 'PRCH5', 'ry-wc-city-select'),
		_x('Pomata', 'PRCH5', 'ry-wc-city-select'),
		_x('Zepita', 'PRCH5', 'ry-wc-city-select'),
	],
	'PRCH6' => [
		_x('Capacmarca', 'PRCH6', 'ry-wc-city-select'),
		_x('Chamaca', 'PRCH6', 'ry-wc-city-select'),
		_x('Colquemarca', 'PRCH6', 'ry-wc-city-select'),
		_x('Livitaca', 'PRCH6', 'ry-wc-city-select'),
		_x('Llusco', 'PRCH6', 'ry-wc-city-select'),
		_x('Quinota', 'PRCH6', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRCH6', 'ry-wc-city-select'),
		_x('Velille', 'PRCH6', 'ry-wc-city-select'),
	],
	'PRCH7' => [
		_x('Ahuac', 'PRCH7', 'ry-wc-city-select'),
		_x('Chongos Bajo', 'PRCH7', 'ry-wc-city-select'),
		_x('Chupaca', 'PRCH7', 'ry-wc-city-select'),
		_x('Huachac', 'PRCH7', 'ry-wc-city-select'),
		_x('Huamancaca Chico', 'PRCH7', 'ry-wc-city-select'),
		_x('San Juan De Jarpa', 'PRCH7', 'ry-wc-city-select'),
		_x('San Juan De Yscos', 'PRCH7', 'ry-wc-city-select'),
		_x('Tres De Diciembre', 'PRCH7', 'ry-wc-city-select'),
		_x('Yanacancha', 'PRCH7', 'ry-wc-city-select'),
	],
	'PRCH8' => [
		_x('Anco', 'PRCH8', 'ry-wc-city-select'),
		_x('Chinchihuasi', 'PRCH8', 'ry-wc-city-select'),
		_x('Churcampa', 'PRCH8', 'ry-wc-city-select'),
		_x('Cosme', 'PRCH8', 'ry-wc-city-select'),
		_x('El Carmen', 'PRCH8', 'ry-wc-city-select'),
		_x('La Merced', 'PRCH8', 'ry-wc-city-select'),
		_x('Locroja', 'PRCH8', 'ry-wc-city-select'),
		_x('Pachamarca', 'PRCH8', 'ry-wc-city-select'),
		_x('Paucarbamba', 'PRCH8', 'ry-wc-city-select'),
		_x('San Miguel De Mayocc', 'PRCH8', 'ry-wc-city-select'),
		_x('San Pedro De Coris', 'PRCH8', 'ry-wc-city-select'),
	],
	'PRCO' => [
		_x('Aco', 'PRCO', 'ry-wc-city-select'),
		_x('Andamarca', 'PRCO', 'ry-wc-city-select'),
		_x('Chambara', 'PRCO', 'ry-wc-city-select'),
		_x('Cochas', 'PRCO', 'ry-wc-city-select'),
		_x('Comas', 'PRCO', 'ry-wc-city-select'),
		_x('Concepcion', 'PRCO', 'ry-wc-city-select'),
		_x('Heroinas Toledo', 'PRCO', 'ry-wc-city-select'),
		_x('Manzanares', 'PRCO', 'ry-wc-city-select'),
		_x('Mariscal Castilla', 'PRCO', 'ry-wc-city-select'),
		_x('Matahuasi', 'PRCO', 'ry-wc-city-select'),
		_x('Mito', 'PRCO', 'ry-wc-city-select'),
		_x('Nueve De Julio', 'PRCO', 'ry-wc-city-select'),
		_x('Orcotuna', 'PRCO', 'ry-wc-city-select'),
		_x('San Jose De Quero', 'PRCO', 'ry-wc-city-select'),
		_x('Santa Rosa De Ocopa', 'PRCO', 'ry-wc-city-select'),
	],
	'PRCO2' => [
		_x('Andaray', 'PRCO2', 'ry-wc-city-select'),
		_x('Cayarani', 'PRCO2', 'ry-wc-city-select'),
		_x('Chichas', 'PRCO2', 'ry-wc-city-select'),
		_x('Chuquibamba', 'PRCO2', 'ry-wc-city-select'),
		_x('Iray', 'PRCO2', 'ry-wc-city-select'),
		_x('Rio Grande', 'PRCO2', 'ry-wc-city-select'),
		_x('Salamanca', 'PRCO2', 'ry-wc-city-select'),
		_x('Yanaquihua', 'PRCO2', 'ry-wc-city-select'),
	],
	'PRCOVI' => [
		_x('Canoas De Punta Sal', 'PRCOVI', 'ry-wc-city-select'),
		_x('Casitas', 'PRCOVI', 'ry-wc-city-select'),
		_x('Zorritos', 'PRCOVI', 'ry-wc-city-select'),
	],
	'PRCO3' => [
		_x('Chilete', 'PRCO3', 'ry-wc-city-select'),
		_x('Contumaza', 'PRCO3', 'ry-wc-city-select'),
		_x('Cupisnique', 'PRCO3', 'ry-wc-city-select'),
		_x('Guzmango', 'PRCO3', 'ry-wc-city-select'),
		_x('San Benito', 'PRCO3', 'ry-wc-city-select'),
		_x('Santa Cruz De Toled', 'PRCO3', 'ry-wc-city-select'),
		_x('Tantarica', 'PRCO3', 'ry-wc-city-select'),
		_x('Yonan', 'PRCO3', 'ry-wc-city-select'),
	],
	'PRCOPO' => [
		_x('Calleria', 'PRCOPO', 'ry-wc-city-select'),
		_x('Campoverde', 'PRCOPO', 'ry-wc-city-select'),
		_x('Iparia', 'PRCOPO', 'ry-wc-city-select'),
		_x('Manantay', 'PRCOPO', 'ry-wc-city-select'),
		_x('Masisea', 'PRCOPO', 'ry-wc-city-select'),
		_x('Nueva Requena', 'PRCOPO', 'ry-wc-city-select'),
		_x('Yarinacocha', 'PRCOPO', 'ry-wc-city-select'),
	],
	'PRCO4' => [
		_x('Aco', 'PRCO4', 'ry-wc-city-select'),
		_x('Bambas', 'PRCO4', 'ry-wc-city-select'),
		_x('Corongo', 'PRCO4', 'ry-wc-city-select'),
		_x('Cusca', 'PRCO4', 'ry-wc-city-select'),
		_x('La Pampa', 'PRCO4', 'ry-wc-city-select'),
		_x('Yanac', 'PRCO4', 'ry-wc-city-select'),
		_x('Yupan', 'PRCO4', 'ry-wc-city-select'),
	],
	'PRCO5' => [
		_x('Challhuahuacho', 'PRCO5', 'ry-wc-city-select'),
		_x('Cotabambas', 'PRCO5', 'ry-wc-city-select'),
		_x('Coyllurqui', 'PRCO5', 'ry-wc-city-select'),
		_x('Haquira', 'PRCO5', 'ry-wc-city-select'),
		_x('Mara', 'PRCO5', 'ry-wc-city-select'),
		_x('Tambobamba', 'PRCO5', 'ry-wc-city-select'),
	],
	'PRCU' => [
		_x('Ccorca', 'PRCU', 'ry-wc-city-select'),
		_x('Cusco', 'PRCU', 'ry-wc-city-select'),
		_x('Poroy', 'PRCU', 'ry-wc-city-select'),
		_x('San Jeronimo', 'PRCU', 'ry-wc-city-select'),
		_x('San Sebastian', 'PRCU', 'ry-wc-city-select'),
		_x('Santiago', 'PRCU', 'ry-wc-city-select'),
		_x('Saylla', 'PRCU', 'ry-wc-city-select'),
		_x('Wanchaq', 'PRCU', 'ry-wc-city-select'),
	],
	'PRCU2' => [
		_x('Callayuc', 'PRCU2', 'ry-wc-city-select'),
		_x('Choros', 'PRCU2', 'ry-wc-city-select'),
		_x('Cujillo', 'PRCU2', 'ry-wc-city-select'),
		_x('Cutervo', 'PRCU2', 'ry-wc-city-select'),
		_x('La Ramada', 'PRCU2', 'ry-wc-city-select'),
		_x('Pimpingos', 'PRCU2', 'ry-wc-city-select'),
		_x('Querocotillo', 'PRCU2', 'ry-wc-city-select'),
		_x('San Andres De Cutervo', 'PRCU2', 'ry-wc-city-select'),
		_x('San Juan De Cutervo', 'PRCU2', 'ry-wc-city-select'),
		_x('San Luis De Lucma', 'PRCU2', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRCU2', 'ry-wc-city-select'),
		_x('Santo Domingo De La Capilla', 'PRCU2', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRCU2', 'ry-wc-city-select'),
		_x('Socota', 'PRCU2', 'ry-wc-city-select'),
		_x('Toribio Casanova', 'PRCU2', 'ry-wc-city-select'),
	],
	'PRDACA' => [
		_x('Chacayan', 'PRDACA', 'ry-wc-city-select'),
		_x('Goyllarisquizga', 'PRDACA', 'ry-wc-city-select'),
		_x('Paucar', 'PRDACA', 'ry-wc-city-select'),
		_x('San Pedro De Pillao', 'PRDACA', 'ry-wc-city-select'),
		_x('Santa Ana De Tusi', 'PRDACA', 'ry-wc-city-select'),
		_x('Tapuc', 'PRDACA', 'ry-wc-city-select'),
		_x('Vilcabamba', 'PRDACA', 'ry-wc-city-select'),
		_x('Yanahuanca', 'PRDACA', 'ry-wc-city-select'),
	],
	'PRDOMA' => [
		_x('Chuquis', 'PRDOMA', 'ry-wc-city-select'),
		_x('La Union', 'PRDOMA', 'ry-wc-city-select'),
		_x('Marias', 'PRDOMA', 'ry-wc-city-select'),
		_x('Pachas', 'PRDOMA', 'ry-wc-city-select'),
		_x('Quivilla', 'PRDOMA', 'ry-wc-city-select'),
		_x('Ripan', 'PRDOMA', 'ry-wc-city-select'),
		_x('Shunqui', 'PRDOMA', 'ry-wc-city-select'),
		_x('Sillapata', 'PRDOMA', 'ry-wc-city-select'),
		_x('Yanas', 'PRDOMA', 'ry-wc-city-select'),
	],
	'PRES' => [
		_x('Alto Pichigua', 'PRES', 'ry-wc-city-select'),
		_x('Condoroma', 'PRES', 'ry-wc-city-select'),
		_x('Coporaque', 'PRES', 'ry-wc-city-select'),
		_x('Espinar', 'PRES', 'ry-wc-city-select'),
		_x('Ocoruro', 'PRES', 'ry-wc-city-select'),
		_x('Pallpata', 'PRES', 'ry-wc-city-select'),
		_x('Pichigua', 'PRES', 'ry-wc-city-select'),
		_x('Suyckutambo', 'PRES', 'ry-wc-city-select'),
	],
	'PRFE' => [
		_x('Canaris', 'PRFE', 'ry-wc-city-select'),
		_x('Ferrenafe', 'PRFE', 'ry-wc-city-select'),
		_x('Incahuasi', 'PRFE', 'ry-wc-city-select'),
		_x('Manuel Antonio Mesones Muro', 'PRFE', 'ry-wc-city-select'),
		_x('Pitipo', 'PRFE', 'ry-wc-city-select'),
		_x('Pueblo Nuevo', 'PRFE', 'ry-wc-city-select'),
	],
	'PRGESACE' => [
		_x('Chojata', 'PRGESACE', 'ry-wc-city-select'),
		_x('Coalaque', 'PRGESACE', 'ry-wc-city-select'),
		_x('Ichuna', 'PRGESACE', 'ry-wc-city-select'),
		_x('La Capilla', 'PRGESACE', 'ry-wc-city-select'),
		_x('Lloque', 'PRGESACE', 'ry-wc-city-select'),
		_x('Matalaque', 'PRGESACE', 'ry-wc-city-select'),
		_x('Omate', 'PRGESACE', 'ry-wc-city-select'),
		_x('Puquina', 'PRGESACE', 'ry-wc-city-select'),
		_x('Quinistaquillas', 'PRGESACE', 'ry-wc-city-select'),
		_x('Ubinas', 'PRGESACE', 'ry-wc-city-select'),
		_x('Yunga', 'PRGESACE', 'ry-wc-city-select'),
	],
	'PRGR' => [
		_x('Chuquibambilla', 'PRGR', 'ry-wc-city-select'),
		_x('Curasco', 'PRGR', 'ry-wc-city-select'),
		_x('Curpahuasi', 'PRGR', 'ry-wc-city-select'),
		_x('Gamarra', 'PRGR', 'ry-wc-city-select'),
		_x('Huayllati', 'PRGR', 'ry-wc-city-select'),
		_x('Mamara', 'PRGR', 'ry-wc-city-select'),
		_x('Micaela Bastidas', 'PRGR', 'ry-wc-city-select'),
		_x('Pataypampa', 'PRGR', 'ry-wc-city-select'),
		_x('Progreso', 'PRGR', 'ry-wc-city-select'),
		_x('San Antonio', 'PRGR', 'ry-wc-city-select'),
		_x('Santa Rosa', 'PRGR', 'ry-wc-city-select'),
		_x('Turpay', 'PRGR', 'ry-wc-city-select'),
		_x('Vilcabamba', 'PRGR', 'ry-wc-city-select'),
		_x('Virundo', 'PRGR', 'ry-wc-city-select'),
	],
	'PRHU' => [
		_x('Bambamarca', 'PRHU', 'ry-wc-city-select'),
		_x('Chugur', 'PRHU', 'ry-wc-city-select'),
		_x('Hualgayoc', 'PRHU', 'ry-wc-city-select'),
	],
	'PRHU2' => [
		_x('Alto Saposoa', 'PRHU2', 'ry-wc-city-select'),
		_x('El Eslabon', 'PRHU2', 'ry-wc-city-select'),
		_x('Piscoyacu', 'PRHU2', 'ry-wc-city-select'),
		_x('Sacanche', 'PRHU2', 'ry-wc-city-select'),
		_x('Saposoa', 'PRHU2', 'ry-wc-city-select'),
		_x('Tingo De Saposoa', 'PRHU2', 'ry-wc-city-select'),
	],
	'PRHU3' => [
		_x('Arancay', 'PRHU3', 'ry-wc-city-select'),
		_x('Chavin De Pariarca', 'PRHU3', 'ry-wc-city-select'),
		_x('Jacas Grande', 'PRHU3', 'ry-wc-city-select'),
		_x('Jircan', 'PRHU3', 'ry-wc-city-select'),
		_x('Llata', 'PRHU3', 'ry-wc-city-select'),
		_x('Miraflores', 'PRHU3', 'ry-wc-city-select'),
		_x('Monzon', 'PRHU3', 'ry-wc-city-select'),
		_x('Punchao', 'PRHU3', 'ry-wc-city-select'),
		_x('Punos', 'PRHU3', 'ry-wc-city-select'),
		_x('Singa', 'PRHU3', 'ry-wc-city-select'),
		_x('Tantamayo', 'PRHU3', 'ry-wc-city-select'),
	],
	'PRHU4' => [
		_x('Acocro', 'PRHU4', 'ry-wc-city-select'),
		_x('Acos Vinchos', 'PRHU4', 'ry-wc-city-select'),
		_x('Andres Avelino Caceres Dorregaray', 'PRHU4', 'ry-wc-city-select'),
		_x('Ayacucho', 'PRHU4', 'ry-wc-city-select'),
		_x('Carmen Alto', 'PRHU4', 'ry-wc-city-select'),
		_x('Chiara', 'PRHU4', 'ry-wc-city-select'),
		_x('Jesus Nazareno', 'PRHU4', 'ry-wc-city-select'),
		_x('Ocros', 'PRHU4', 'ry-wc-city-select'),
		_x('Pacaycasa', 'PRHU4', 'ry-wc-city-select'),
		_x('Quinua', 'PRHU4', 'ry-wc-city-select'),
		_x('San Jose De Ticllas', 'PRHU4', 'ry-wc-city-select'),
		_x('San Juan Bautista', 'PRHU4', 'ry-wc-city-select'),
		_x('Santiago De Pischa', 'PRHU4', 'ry-wc-city-select'),
		_x('Socos', 'PRHU4', 'ry-wc-city-select'),
		_x('Tambillo', 'PRHU4', 'ry-wc-city-select'),
		_x('Vinchos', 'PRHU4', 'ry-wc-city-select'),
	],
	'PRHUSA' => [
		_x('Carapo', 'PRHUSA', 'ry-wc-city-select'),
		_x('Sacsamarca', 'PRHUSA', 'ry-wc-city-select'),
		_x('Sancos', 'PRHUSA', 'ry-wc-city-select'),
		_x('Santiago De Lucanamarca', 'PRHUSA', 'ry-wc-city-select'),
	],
	'PRHU5' => [
		_x('Canchaque', 'PRHU5', 'ry-wc-city-select'),
		_x('El Carmen De La Frontera', 'PRHU5', 'ry-wc-city-select'),
		_x('Huancabamba', 'PRHU5', 'ry-wc-city-select'),
		_x('Huarmaca', 'PRHU5', 'ry-wc-city-select'),
		_x('Lalaquiz', 'PRHU5', 'ry-wc-city-select'),
		_x('San Miguel De El Faique', 'PRHU5', 'ry-wc-city-select'),
		_x('Sondor', 'PRHU5', 'ry-wc-city-select'),
		_x('Sondorillo', 'PRHU5', 'ry-wc-city-select'),
	],
	'PRHU6' => [
		_x('Cojata', 'PRHU6', 'ry-wc-city-select'),
		_x('Huancane', 'PRHU6', 'ry-wc-city-select'),
		_x('Huatasani', 'PRHU6', 'ry-wc-city-select'),
		_x('Inchupalla', 'PRHU6', 'ry-wc-city-select'),
		_x('Pusi', 'PRHU6', 'ry-wc-city-select'),
		_x('Rosaspata', 'PRHU6', 'ry-wc-city-select'),
		_x('Taraco', 'PRHU6', 'ry-wc-city-select'),
		_x('Vilque Chico', 'PRHU6', 'ry-wc-city-select'),
	],
	'PRHU7' => [
		_x('Acobambilla', 'PRHU7', 'ry-wc-city-select'),
		_x('Acoria', 'PRHU7', 'ry-wc-city-select'),
		_x('Ascension', 'PRHU7', 'ry-wc-city-select'),
		_x('Conayca', 'PRHU7', 'ry-wc-city-select'),
		_x('Cuenca', 'PRHU7', 'ry-wc-city-select'),
		_x('Huachocolpa', 'PRHU7', 'ry-wc-city-select'),
		_x('Huancavelica', 'PRHU7', 'ry-wc-city-select'),
		_x('Huando', 'PRHU7', 'ry-wc-city-select'),
		_x('Huayllahuara', 'PRHU7', 'ry-wc-city-select'),
		_x('Izcuchaca', 'PRHU7', 'ry-wc-city-select'),
		_x('Laria', 'PRHU7', 'ry-wc-city-select'),
		_x('Manta', 'PRHU7', 'ry-wc-city-select'),
		_x('Mariscal Caceres', 'PRHU7', 'ry-wc-city-select'),
		_x('Moya', 'PRHU7', 'ry-wc-city-select'),
		_x('Nuevo Occoro', 'PRHU7', 'ry-wc-city-select'),
		_x('Palca', 'PRHU7', 'ry-wc-city-select'),
		_x('Pilchaca', 'PRHU7', 'ry-wc-city-select'),
		_x('Vilca', 'PRHU7', 'ry-wc-city-select'),
		_x('Yauli', 'PRHU7', 'ry-wc-city-select'),
	],
	'PRHU8' => [
		_x('Carhuacallanga', 'PRHU8', 'ry-wc-city-select'),
		_x('Chacapampa', 'PRHU8', 'ry-wc-city-select'),
		_x('Chicche', 'PRHU8', 'ry-wc-city-select'),
		_x('Chilca', 'PRHU8', 'ry-wc-city-select'),
		_x('Chongos Alto', 'PRHU8', 'ry-wc-city-select'),
		_x('Chupuro', 'PRHU8', 'ry-wc-city-select'),
		_x('Colca', 'PRHU8', 'ry-wc-city-select'),
		_x('Cullhuas', 'PRHU8', 'ry-wc-city-select'),
		_x('El Tambo', 'PRHU8', 'ry-wc-city-select'),
		_x('Huacrapuquio', 'PRHU8', 'ry-wc-city-select'),
		_x('Hualhuas', 'PRHU8', 'ry-wc-city-select'),
		_x('Huancan', 'PRHU8', 'ry-wc-city-select'),
		_x('Huancayo', 'PRHU8', 'ry-wc-city-select'),
		_x('Huasicancha', 'PRHU8', 'ry-wc-city-select'),
		_x('Huayucachi', 'PRHU8', 'ry-wc-city-select'),
		_x('Ingenio', 'PRHU8', 'ry-wc-city-select'),
		_x('Pariahuanca', 'PRHU8', 'ry-wc-city-select'),
		_x('Pilcomayo', 'PRHU8', 'ry-wc-city-select'),
		_x('Pucara', 'PRHU8', 'ry-wc-city-select'),
		_x('Quichuay', 'PRHU8', 'ry-wc-city-select'),
		_x('Quilcas', 'PRHU8', 'ry-wc-city-select'),
		_x('San Agustin', 'PRHU8', 'ry-wc-city-select'),
		_x('San Jeronimo De Tunan', 'PRHU8', 'ry-wc-city-select'),
		_x('Sano', 'PRHU8', 'ry-wc-city-select'),
		_x('Santo Domingo De Acobamba', 'PRHU8', 'ry-wc-city-select'),
		_x('Sapallanga', 'PRHU8', 'ry-wc-city-select'),
		_x('Sicaya', 'PRHU8', 'ry-wc-city-select'),
		_x('Viques', 'PRHU8', 'ry-wc-city-select'),
	],
	'PRHU9' => [
		_x('Ayahuanco', 'PRHU9', 'ry-wc-city-select'),
		_x('Canayre', 'PRHU9', 'ry-wc-city-select'),
		_x('Chaca', 'PRHU9', 'ry-wc-city-select'),
		_x('Huamanguilla', 'PRHU9', 'ry-wc-city-select'),
		_x('Huanta', 'PRHU9', 'ry-wc-city-select'),
		_x('Iguain', 'PRHU9', 'ry-wc-city-select'),
		_x('Llochegua', 'PRHU9', 'ry-wc-city-select'),
		_x('Luricocha', 'PRHU9', 'ry-wc-city-select'),
		_x('Pucacolpa', 'PRHU9', 'ry-wc-city-select'),
		_x('Santillana', 'PRHU9', 'ry-wc-city-select'),
		_x('Sivia', 'PRHU9', 'ry-wc-city-select'),
		_x('Uchuraccay', 'PRHU9', 'ry-wc-city-select'),
	],
	'PRHU10' => [
		_x('Amarilis', 'PRHU10', 'ry-wc-city-select'),
		_x('Chinchao', 'PRHU10', 'ry-wc-city-select'),
		_x('Churubamba', 'PRHU10', 'ry-wc-city-select'),
		_x('Huanuco', 'PRHU10', 'ry-wc-city-select'),
		_x('Margos', 'PRHU10', 'ry-wc-city-select'),
		_x('Pillco Marca', 'PRHU10', 'ry-wc-city-select'),
		_x('Quisqui', 'PRHU10', 'ry-wc-city-select'),
		_x('San Francisco De Cayran', 'PRHU10', 'ry-wc-city-select'),
		_x('San Pablo De Pillao', 'PRHU10', 'ry-wc-city-select'),
		_x('San Pedro De Chaulan', 'PRHU10', 'ry-wc-city-select'),
		_x('Santa Maria Del Valle', 'PRHU10', 'ry-wc-city-select'),
		_x('Yacus', 'PRHU10', 'ry-wc-city-select'),
		_x('Yarumayo', 'PRHU10', 'ry-wc-city-select'),
	],
	'PRHU11' => [
		_x('Atavillos Alto', 'PRHU11', 'ry-wc-city-select'),
		_x('Atavillos Bajo', 'PRHU11', 'ry-wc-city-select'),
		_x('Aucallama', 'PRHU11', 'ry-wc-city-select'),
		_x('Chancay', 'PRHU11', 'ry-wc-city-select'),
		_x('Huaral', 'PRHU11', 'ry-wc-city-select'),
		_x('Ihuari', 'PRHU11', 'ry-wc-city-select'),
		_x('Lampian', 'PRHU11', 'ry-wc-city-select'),
		_x('Pacaraos', 'PRHU11', 'ry-wc-city-select'),
		_x('San Miguel De Acos', 'PRHU11', 'ry-wc-city-select'),
		_x('Santa Cruz De Andamarca', 'PRHU11', 'ry-wc-city-select'),
		_x('Sumbilca', 'PRHU11', 'ry-wc-city-select'),
		_x('Veintisiete De Noviembre', 'PRHU11', 'ry-wc-city-select'),
	],
	'PRHU12' => [
		_x('Cochabamba', 'PRHU12', 'ry-wc-city-select'),
		_x('Colcabamba', 'PRHU12', 'ry-wc-city-select'),
		_x('Huanchay', 'PRHU12', 'ry-wc-city-select'),
		_x('Huaraz', 'PRHU12', 'ry-wc-city-select'),
		_x('Independencia', 'PRHU12', 'ry-wc-city-select'),
		_x('Jangas', 'PRHU12', 'ry-wc-city-select'),
		_x('La Libertad', 'PRHU12', 'ry-wc-city-select'),
		_x('Olleros', 'PRHU12', 'ry-wc-city-select'),
		_x('Pampas', 'PRHU12', 'ry-wc-city-select'),
		_x('Pariacoto', 'PRHU12', 'ry-wc-city-select'),
		_x('Pira', 'PRHU12', 'ry-wc-city-select'),
		_x('Tarica', 'PRHU12', 'ry-wc-city-select'),
	],
	'PRHU13' => [
		_x('Anra', 'PRHU13', 'ry-wc-city-select'),
		_x('Cajay', 'PRHU13', 'ry-wc-city-select'),
		_x('Chavin De Huantar', 'PRHU13', 'ry-wc-city-select'),
		_x('Huacachi', 'PRHU13', 'ry-wc-city-select'),
		_x('Huacchis', 'PRHU13', 'ry-wc-city-select'),
		_x('Huachis', 'PRHU13', 'ry-wc-city-select'),
		_x('Huantar', 'PRHU13', 'ry-wc-city-select'),
		_x('Huari', 'PRHU13', 'ry-wc-city-select'),
		_x('Masin', 'PRHU13', 'ry-wc-city-select'),
		_x('Paucas', 'PRHU13', 'ry-wc-city-select'),
		_x('Ponto', 'PRHU13', 'ry-wc-city-select'),
		_x('Rahuapampa', 'PRHU13', 'ry-wc-city-select'),
		_x('Rapayan', 'PRHU13', 'ry-wc-city-select'),
		_x('San Marcos', 'PRHU13', 'ry-wc-city-select'),
		_x('San Pedro De Chana', 'PRHU13', 'ry-wc-city-select'),
		_x('Uco', 'PRHU13', 'ry-wc-city-select'),
	],
	'PRHU14' => [
		_x('Cochapeti', 'PRHU14', 'ry-wc-city-select'),
		_x('Culebras', 'PRHU14', 'ry-wc-city-select'),
		_x('Huarmey', 'PRHU14', 'ry-wc-city-select'),
		_x('Huayan', 'PRHU14', 'ry-wc-city-select'),
		_x('Malvas', 'PRHU14', 'ry-wc-city-select'),
	],
	'PRHU15' => [
		_x('Antioquia', 'PRHU15', 'ry-wc-city-select'),
		_x('Callahuanca', 'PRHU15', 'ry-wc-city-select'),
		_x('Carampoma', 'PRHU15', 'ry-wc-city-select'),
		_x('Chicla', 'PRHU15', 'ry-wc-city-select'),
		_x('Cuenca', 'PRHU15', 'ry-wc-city-select'),
		_x('Huachupampa', 'PRHU15', 'ry-wc-city-select'),
		_x('Huanza', 'PRHU15', 'ry-wc-city-select'),
		_x('Huarochiri', 'PRHU15', 'ry-wc-city-select'),
		_x('Lahuaytambo', 'PRHU15', 'ry-wc-city-select'),
		_x('Langa', 'PRHU15', 'ry-wc-city-select'),
		_x('Laraos', 'PRHU15', 'ry-wc-city-select'),
		_x('Mariatana', 'PRHU15', 'ry-wc-city-select'),
		_x('Matucana', 'PRHU15', 'ry-wc-city-select'),
		_x('Ricardo Palma', 'PRHU15', 'ry-wc-city-select'),
		_x('San Andres De Tupicocha', 'PRHU15', 'ry-wc-city-select'),
		_x('San Antonio', 'PRHU15', 'ry-wc-city-select'),
		_x('San Bartolome', 'PRHU15', 'ry-wc-city-select'),
		_x('San Damian', 'PRHU15', 'ry-wc-city-select'),
		_x('San Juan De Iris', 'PRHU15', 'ry-wc-city-select'),
		_x('San Juan De Tantaranche', 'PRHU15', 'ry-wc-city-select'),
		_x('San Lorenzo De Quinti', 'PRHU15', 'ry-wc-city-select'),
		_x('San Mateo', 'PRHU15', 'ry-wc-city-select'),
		_x('San Mateo De Otao', 'PRHU15', 'ry-wc-city-select'),
		_x('San Pedro De Casta', 'PRHU15', 'ry-wc-city-select'),
		_x('San Pedro De Huancayre', 'PRHU15', 'ry-wc-city-select'),
		_x('Sangallaya', 'PRHU15', 'ry-wc-city-select'),
		_x('Santa Cruz De Cocachacra', 'PRHU15', 'ry-wc-city-select'),
		_x('Santa Eulalia', 'PRHU15', 'ry-wc-city-select'),
		_x('Santiago De Anchucaya', 'PRHU15', 'ry-wc-city-select'),
		_x('Santiago De Tuna', 'PRHU15', 'ry-wc-city-select'),
		_x('Santo Domingo De Los Olleros', 'PRHU15', 'ry-wc-city-select'),
		_x('Surco', 'PRHU15', 'ry-wc-city-select'),
	],
	'PRHU16' => [
		_x('Caraz', 'PRHU16', 'ry-wc-city-select'),
		_x('Huallanca', 'PRHU16', 'ry-wc-city-select'),
		_x('Huata', 'PRHU16', 'ry-wc-city-select'),
		_x('Huaylas', 'PRHU16', 'ry-wc-city-select'),
		_x('Mato', 'PRHU16', 'ry-wc-city-select'),
		_x('Pamparomas', 'PRHU16', 'ry-wc-city-select'),
		_x('Pueblo Libre', 'PRHU16', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRHU16', 'ry-wc-city-select'),
		_x('Santo Toribio', 'PRHU16', 'ry-wc-city-select'),
		_x('Yuracmarca', 'PRHU16', 'ry-wc-city-select'),
	],
	'PRIC' => [
		_x('Ica', 'PRIC', 'ry-wc-city-select'),
		_x('La Tinguina', 'PRIC', 'ry-wc-city-select'),
		_x('Los Aquijes', 'PRIC', 'ry-wc-city-select'),
		_x('Ocucaje', 'PRIC', 'ry-wc-city-select'),
		_x('Pachacutec', 'PRIC', 'ry-wc-city-select'),
		_x('Parcona', 'PRIC', 'ry-wc-city-select'),
		_x('Pueblo Nuevo', 'PRIC', 'ry-wc-city-select'),
		_x('Salas', 'PRIC', 'ry-wc-city-select'),
		_x('San Jose De Los Molinos', 'PRIC', 'ry-wc-city-select'),
		_x('San Juan Bautista', 'PRIC', 'ry-wc-city-select'),
		_x('Santiago', 'PRIC', 'ry-wc-city-select'),
		_x('Subtanjalla', 'PRIC', 'ry-wc-city-select'),
		_x('Tate', 'PRIC', 'ry-wc-city-select'),
		_x('Yauca Del Rosario', 'PRIC', 'ry-wc-city-select'),
	],
	'PRIL' => [
		_x('El Algarrobal', 'PRIL', 'ry-wc-city-select'),
		_x('Ilo', 'PRIL', 'ry-wc-city-select'),
		_x('Pacocha', 'PRIL', 'ry-wc-city-select'),
	],
	'PRIS' => [
		_x('Cocachacra', 'PRIS', 'ry-wc-city-select'),
		_x('Dean Valdivia', 'PRIS', 'ry-wc-city-select'),
		_x('Islay', 'PRIS', 'ry-wc-city-select'),
		_x('Mejia', 'PRIS', 'ry-wc-city-select'),
		_x('Mollendo', 'PRIS', 'ry-wc-city-select'),
		_x('Punta De Bombon', 'PRIS', 'ry-wc-city-select'),
	],
	'PRJA' => [
		_x('Bellavista', 'PRJA', 'ry-wc-city-select'),
		_x('Chontali', 'PRJA', 'ry-wc-city-select'),
		_x('Colasay', 'PRJA', 'ry-wc-city-select'),
		_x('Huabal', 'PRJA', 'ry-wc-city-select'),
		_x('Jaen', 'PRJA', 'ry-wc-city-select'),
		_x('Las Pirias', 'PRJA', 'ry-wc-city-select'),
		_x('Pomahuaca', 'PRJA', 'ry-wc-city-select'),
		_x('Pucara', 'PRJA', 'ry-wc-city-select'),
		_x('Sallique', 'PRJA', 'ry-wc-city-select'),
		_x('San Felipe', 'PRJA', 'ry-wc-city-select'),
		_x('San Jose Del Alto', 'PRJA', 'ry-wc-city-select'),
		_x('Santa Rosa', 'PRJA', 'ry-wc-city-select'),
	],
	'PRJA2' => [
		_x('Acolla', 'PRJA2', 'ry-wc-city-select'),
		_x('Apata', 'PRJA2', 'ry-wc-city-select'),
		_x('Ataura', 'PRJA2', 'ry-wc-city-select'),
		_x('Canchayllo', 'PRJA2', 'ry-wc-city-select'),
		_x('Curicaca', 'PRJA2', 'ry-wc-city-select'),
		_x('El Mantaro', 'PRJA2', 'ry-wc-city-select'),
		_x('Huamali', 'PRJA2', 'ry-wc-city-select'),
		_x('Huaripampa', 'PRJA2', 'ry-wc-city-select'),
		_x('Huertas', 'PRJA2', 'ry-wc-city-select'),
		_x('Janjaillo', 'PRJA2', 'ry-wc-city-select'),
		_x('Jauja', 'PRJA2', 'ry-wc-city-select'),
		_x('Julcan', 'PRJA2', 'ry-wc-city-select'),
		_x('Leonor Ordonez', 'PRJA2', 'ry-wc-city-select'),
		_x('Llocllapampa', 'PRJA2', 'ry-wc-city-select'),
		_x('Marco', 'PRJA2', 'ry-wc-city-select'),
		_x('Masma', 'PRJA2', 'ry-wc-city-select'),
		_x('Masma Chicche', 'PRJA2', 'ry-wc-city-select'),
		_x('Molinos', 'PRJA2', 'ry-wc-city-select'),
		_x('Monobamba', 'PRJA2', 'ry-wc-city-select'),
		_x('Muqui', 'PRJA2', 'ry-wc-city-select'),
		_x('Muquiyauyo', 'PRJA2', 'ry-wc-city-select'),
		_x('Paca', 'PRJA2', 'ry-wc-city-select'),
		_x('Paccha', 'PRJA2', 'ry-wc-city-select'),
		_x('Pancan', 'PRJA2', 'ry-wc-city-select'),
		_x('Parco', 'PRJA2', 'ry-wc-city-select'),
		_x('Pomacancha', 'PRJA2', 'ry-wc-city-select'),
		_x('Ricran', 'PRJA2', 'ry-wc-city-select'),
		_x('San Lorenzo', 'PRJA2', 'ry-wc-city-select'),
		_x('San Pedro De Chunan', 'PRJA2', 'ry-wc-city-select'),
		_x('Sausa', 'PRJA2', 'ry-wc-city-select'),
		_x('Sincos', 'PRJA2', 'ry-wc-city-select'),
		_x('Tunan Marca', 'PRJA2', 'ry-wc-city-select'),
		_x('Yauli', 'PRJA2', 'ry-wc-city-select'),
		_x('Yauyos', 'PRJA2', 'ry-wc-city-select'),
	],
	'PRJU' => [
		_x('Carhuamayo', 'PRJU', 'ry-wc-city-select'),
		_x('Junin', 'PRJU', 'ry-wc-city-select'),
		_x('Ondores', 'PRJU', 'ry-wc-city-select'),
		_x('Ulcumayo', 'PRJU', 'ry-wc-city-select'),
	],
	'PRCO6' => [
		_x('Echarate', 'PRCO6', 'ry-wc-city-select'),
		_x('Huayopata', 'PRCO6', 'ry-wc-city-select'),
		_x('Inkawasi', 'PRCO6', 'ry-wc-city-select'),
		_x('Kimbiri', 'PRCO6', 'ry-wc-city-select'),
		_x('Maranura', 'PRCO6', 'ry-wc-city-select'),
		_x('Megantoni', 'PRCO6', 'ry-wc-city-select'),
		_x('Ocobamba', 'PRCO6', 'ry-wc-city-select'),
		_x('Pichari', 'PRCO6', 'ry-wc-city-select'),
		_x('Quellouno', 'PRCO6', 'ry-wc-city-select'),
		_x('Santa Ana', 'PRCO6', 'ry-wc-city-select'),
		_x('Santa Teresa', 'PRCO6', 'ry-wc-city-select'),
		_x('Vilcabamba', 'PRCO6', 'ry-wc-city-select'),
		_x('Villa Kintiarina', 'PRCO6', 'ry-wc-city-select'),
		_x('Villa Virgen', 'PRCO6', 'ry-wc-city-select'),
	],
	'PRMA' => [
		_x('Anchihuay', 'PRMA', 'ry-wc-city-select'),
		_x('Anco', 'PRMA', 'ry-wc-city-select'),
		_x('Ayna', 'PRMA', 'ry-wc-city-select'),
		_x('Chilcas', 'PRMA', 'ry-wc-city-select'),
		_x('Chungui', 'PRMA', 'ry-wc-city-select'),
		_x('Luis Carranza', 'PRMA', 'ry-wc-city-select'),
		_x('Oronccoy', 'PRMA', 'ry-wc-city-select'),
		_x('Samugari', 'PRMA', 'ry-wc-city-select'),
		_x('San Miguel', 'PRMA', 'ry-wc-city-select'),
		_x('Santa Rosa', 'PRMA', 'ry-wc-city-select'),
		_x('Tambo', 'PRMA', 'ry-wc-city-select'),
	],
	'PRUN' => [
		_x('Alca', 'PRUN', 'ry-wc-city-select'),
		_x('Charcana', 'PRUN', 'ry-wc-city-select'),
		_x('Cotahuasi', 'PRUN', 'ry-wc-city-select'),
		_x('Huaynacotas', 'PRUN', 'ry-wc-city-select'),
		_x('Pampamarca', 'PRUN', 'ry-wc-city-select'),
		_x('Puyca', 'PRUN', 'ry-wc-city-select'),
		_x('Quechualla', 'PRUN', 'ry-wc-city-select'),
		_x('Sayla', 'PRUN', 'ry-wc-city-select'),
		_x('Tauria', 'PRUN', 'ry-wc-city-select'),
		_x('Tomepampa', 'PRUN', 'ry-wc-city-select'),
		_x('Toro', 'PRUN', 'ry-wc-city-select'),
	],
	'PRLA' => [
		_x('Alonso De Alvarado', 'PRLA', 'ry-wc-city-select'),
		_x('Barranquita', 'PRLA', 'ry-wc-city-select'),
		_x('Caynarachi', 'PRLA', 'ry-wc-city-select'),
		_x('Cunumbuqui', 'PRLA', 'ry-wc-city-select'),
		_x('Lamas', 'PRLA', 'ry-wc-city-select'),
		_x('Pinto Recodo', 'PRLA', 'ry-wc-city-select'),
		_x('Rumisapa', 'PRLA', 'ry-wc-city-select'),
		_x('San Roque De Cumbaza', 'PRLA', 'ry-wc-city-select'),
		_x('Shanao', 'PRLA', 'ry-wc-city-select'),
		_x('Tabalosos', 'PRLA', 'ry-wc-city-select'),
		_x('Zapatero', 'PRLA', 'ry-wc-city-select'),
	],
	'PRLA2' => [
		_x('Chochope', 'PRLA2', 'ry-wc-city-select'),
		_x('Illimo', 'PRLA2', 'ry-wc-city-select'),
		_x('Jayanca', 'PRLA2', 'ry-wc-city-select'),
		_x('Lambayeque', 'PRLA2', 'ry-wc-city-select'),
		_x('Mochumi', 'PRLA2', 'ry-wc-city-select'),
		_x('Morrope', 'PRLA2', 'ry-wc-city-select'),
		_x('Motupe', 'PRLA2', 'ry-wc-city-select'),
		_x('Olmos', 'PRLA2', 'ry-wc-city-select'),
		_x('Pacora', 'PRLA2', 'ry-wc-city-select'),
		_x('Salas', 'PRLA2', 'ry-wc-city-select'),
		_x('San Jose', 'PRLA2', 'ry-wc-city-select'),
		_x('Tucume', 'PRLA2', 'ry-wc-city-select'),
	],
	'PRLA3' => [
		_x('Cabanilla', 'PRLA3', 'ry-wc-city-select'),
		_x('Calapuja', 'PRLA3', 'ry-wc-city-select'),
		_x('Lampa', 'PRLA3', 'ry-wc-city-select'),
		_x('Nicasio', 'PRLA3', 'ry-wc-city-select'),
		_x('Ocuviri', 'PRLA3', 'ry-wc-city-select'),
		_x('Palca', 'PRLA3', 'ry-wc-city-select'),
		_x('Paratia', 'PRLA3', 'ry-wc-city-select'),
		_x('Pucara', 'PRLA3', 'ry-wc-city-select'),
		_x('Santa Lucia', 'PRLA3', 'ry-wc-city-select'),
		_x('Vilavila', 'PRLA3', 'ry-wc-city-select'),
	],
	'PRLEPR' => [
		_x('Castillo Grande', 'PRLEPR', 'ry-wc-city-select'),
		_x('Daniel Alomias Robles', 'PRLEPR', 'ry-wc-city-select'),
		_x('Hermilio Valdizan', 'PRLEPR', 'ry-wc-city-select'),
		_x('Jose Crespo Y Castillo', 'PRLEPR', 'ry-wc-city-select'),
		_x('Luyando', 'PRLEPR', 'ry-wc-city-select'),
		_x('Mariano Damaso Beraun', 'PRLEPR', 'ry-wc-city-select'),
		_x('Pucayacu', 'PRLEPR', 'ry-wc-city-select'),
		_x('Pueblo Nuevo', 'PRLEPR', 'ry-wc-city-select'),
		_x('Rupa-Rupa', 'PRLEPR', 'ry-wc-city-select'),
		_x('Santo Domingo De Anda', 'PRLEPR', 'ry-wc-city-select'),
	],
	'PRLO' => [
		_x('Nauta', 'PRLO', 'ry-wc-city-select'),
		_x('Parinari', 'PRLO', 'ry-wc-city-select'),
		_x('Tigre', 'PRLO', 'ry-wc-city-select'),
		_x('Trompeteros', 'PRLO', 'ry-wc-city-select'),
		_x('Urarinas', 'PRLO', 'ry-wc-city-select'),
	],
	'PRLU' => [
		_x('Aucara', 'PRLU', 'ry-wc-city-select'),
		_x('Cabana', 'PRLU', 'ry-wc-city-select'),
		_x('Carmen Salcedo', 'PRLU', 'ry-wc-city-select'),
		_x('Chavina', 'PRLU', 'ry-wc-city-select'),
		_x('Chipao', 'PRLU', 'ry-wc-city-select'),
		_x('Huac-Huas', 'PRLU', 'ry-wc-city-select'),
		_x('Laramate', 'PRLU', 'ry-wc-city-select'),
		_x('Leoncio Prado', 'PRLU', 'ry-wc-city-select'),
		_x('Llauta', 'PRLU', 'ry-wc-city-select'),
		_x('Lucanas', 'PRLU', 'ry-wc-city-select'),
		_x('Ocana', 'PRLU', 'ry-wc-city-select'),
		_x('Otoca', 'PRLU', 'ry-wc-city-select'),
		_x('Puquio', 'PRLU', 'ry-wc-city-select'),
		_x('Saisa', 'PRLU', 'ry-wc-city-select'),
		_x('San Cristobal', 'PRLU', 'ry-wc-city-select'),
		_x('San Juan', 'PRLU', 'ry-wc-city-select'),
		_x('San Pedro', 'PRLU', 'ry-wc-city-select'),
		_x('San Pedro De Palco', 'PRLU', 'ry-wc-city-select'),
		_x('Sancos', 'PRLU', 'ry-wc-city-select'),
		_x('Santa Ana De Huaycahuacho', 'PRLU', 'ry-wc-city-select'),
		_x('Santa Lucia', 'PRLU', 'ry-wc-city-select'),
	],
	'PRLU2' => [
		_x('Camporredondo', 'PRLU2', 'ry-wc-city-select'),
		_x('Cocabamba', 'PRLU2', 'ry-wc-city-select'),
		_x('Colcamar', 'PRLU2', 'ry-wc-city-select'),
		_x('Conila', 'PRLU2', 'ry-wc-city-select'),
		_x('Inguilpata', 'PRLU2', 'ry-wc-city-select'),
		_x('Lamud', 'PRLU2', 'ry-wc-city-select'),
		_x('Longuita', 'PRLU2', 'ry-wc-city-select'),
		_x('Lonya Chico', 'PRLU2', 'ry-wc-city-select'),
		_x('Luya', 'PRLU2', 'ry-wc-city-select'),
		_x('Luya Viejo', 'PRLU2', 'ry-wc-city-select'),
		_x('Maria', 'PRLU2', 'ry-wc-city-select'),
		_x('Ocalli', 'PRLU2', 'ry-wc-city-select'),
		_x('Ocumal', 'PRLU2', 'ry-wc-city-select'),
		_x('Pisuquia', 'PRLU2', 'ry-wc-city-select'),
		_x('Providencia', 'PRLU2', 'ry-wc-city-select'),
		_x('San Cristobal', 'PRLU2', 'ry-wc-city-select'),
		_x('San Francisco Del Yeso', 'PRLU2', 'ry-wc-city-select'),
		_x('San Jeronimo', 'PRLU2', 'ry-wc-city-select'),
		_x('San Juan De Lopecancha', 'PRLU2', 'ry-wc-city-select'),
		_x('Santa Catalina', 'PRLU2', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRLU2', 'ry-wc-city-select'),
		_x('Tingo', 'PRLU2', 'ry-wc-city-select'),
		_x('Trita', 'PRLU2', 'ry-wc-city-select'),
	],
	'PRMA2' => [
		_x('Fitzcarrald', 'PRMA2', 'ry-wc-city-select'),
		_x('Huepetuhe', 'PRMA2', 'ry-wc-city-select'),
		_x('Madre De Dios', 'PRMA2', 'ry-wc-city-select'),
		_x('Manu', 'PRMA2', 'ry-wc-city-select'),
	],
	'PRMA3' => [
		_x('Cholon', 'PRMA3', 'ry-wc-city-select'),
		_x('Huacrachuco', 'PRMA3', 'ry-wc-city-select'),
		_x('La Morada', 'PRMA3', 'ry-wc-city-select'),
		_x('San Buenaventura', 'PRMA3', 'ry-wc-city-select'),
		_x('Santa Rosa De Alto Yanajanca', 'PRMA3', 'ry-wc-city-select'),
	],
	'PRMACA' => [
		_x('Campanilla', 'PRMACA', 'ry-wc-city-select'),
		_x('Huicungo', 'PRMACA', 'ry-wc-city-select'),
		_x('Juanjui', 'PRMACA', 'ry-wc-city-select'),
		_x('Pachiza', 'PRMACA', 'ry-wc-city-select'),
		_x('Pajarillo', 'PRMACA', 'ry-wc-city-select'),
	],
	'PRMALU' => [
		_x('Casca', 'PRMALU', 'ry-wc-city-select'),
		_x('Eleazar Guzman Barron', 'PRMALU', 'ry-wc-city-select'),
		_x('Fidel Olivas Escudero', 'PRMALU', 'ry-wc-city-select'),
		_x('Llama', 'PRMALU', 'ry-wc-city-select'),
		_x('Llumpa', 'PRMALU', 'ry-wc-city-select'),
		_x('Lucma', 'PRMALU', 'ry-wc-city-select'),
		_x('Musga', 'PRMALU', 'ry-wc-city-select'),
		_x('Piscobamba', 'PRMALU', 'ry-wc-city-select'),
	],
	'PRMANI' => [
		_x('Carumas', 'PRMANI', 'ry-wc-city-select'),
		_x('Cuchumbaya', 'PRMANI', 'ry-wc-city-select'),
		_x('Moquegua', 'PRMANI', 'ry-wc-city-select'),
		_x('Samegua', 'PRMANI', 'ry-wc-city-select'),
		_x('San Cristobal', 'PRMANI', 'ry-wc-city-select'),
		_x('Torata', 'PRMANI', 'ry-wc-city-select'),
	],
	'PRMA4' => [
		_x('Alto Nanay', 'PRMA4', 'ry-wc-city-select'),
		_x('Belen', 'PRMA4', 'ry-wc-city-select'),
		_x('Fernando Lores', 'PRMA4', 'ry-wc-city-select'),
		_x('Indiana District', 'PRMA4', 'ry-wc-city-select'),
		_x('Iquitos', 'PRMA4', 'ry-wc-city-select'),
		_x('Las Amazonas', 'PRMA4', 'ry-wc-city-select'),
		_x('Mazan', 'PRMA4', 'ry-wc-city-select'),
		_x('Napo', 'PRMA4', 'ry-wc-city-select'),
		_x('Punchana', 'PRMA4', 'ry-wc-city-select'),
		_x('San Juan Bautista', 'PRMA4', 'ry-wc-city-select'),
		_x('Torres Causana', 'PRMA4', 'ry-wc-city-select'),
	],
	'PRME' => [
		_x('Antauta', 'PRME', 'ry-wc-city-select'),
		_x('Ayaviri', 'PRME', 'ry-wc-city-select'),
		_x('Cupi', 'PRME', 'ry-wc-city-select'),
		_x('Llalli', 'PRME', 'ry-wc-city-select'),
		_x('Macari', 'PRME', 'ry-wc-city-select'),
		_x('Nunoa', 'PRME', 'ry-wc-city-select'),
		_x('Orurillo', 'PRME', 'ry-wc-city-select'),
		_x('Santa Rosa', 'PRME', 'ry-wc-city-select'),
		_x('Umachiri', 'PRME', 'ry-wc-city-select'),
	],
	'PRMO' => [
		_x('Calzada', 'PRMO', 'ry-wc-city-select'),
		_x('Habana', 'PRMO', 'ry-wc-city-select'),
		_x('Jepelacio', 'PRMO', 'ry-wc-city-select'),
		_x('Moyobamba', 'PRMO', 'ry-wc-city-select'),
		_x('Soritor', 'PRMO', 'ry-wc-city-select'),
		_x('Yantalo', 'PRMO', 'ry-wc-city-select'),
	],
	'PRNA' => [
		_x('Changuillo', 'PRNA', 'ry-wc-city-select'),
		_x('El Ingenio', 'PRNA', 'ry-wc-city-select'),
		_x('Marcona', 'PRNA', 'ry-wc-city-select'),
		_x('Nazca', 'PRNA', 'ry-wc-city-select'),
		_x('Vista Alegre', 'PRNA', 'ry-wc-city-select'),
	],
	'PROT' => [
		_x('Agallpampa', 'PROT', 'ry-wc-city-select'),
		_x('Charat', 'PROT', 'ry-wc-city-select'),
		_x('Huaranchal', 'PROT', 'ry-wc-city-select'),
		_x('La Cuesta', 'PROT', 'ry-wc-city-select'),
		_x('Mache', 'PROT', 'ry-wc-city-select'),
		_x('Otuzco', 'PROT', 'ry-wc-city-select'),
		_x('Paranday', 'PROT', 'ry-wc-city-select'),
		_x('Salpo', 'PROT', 'ry-wc-city-select'),
		_x('Sinsicap', 'PROT', 'ry-wc-city-select'),
		_x('Usquil', 'PROT', 'ry-wc-city-select'),
	],
	'PROX' => [
		_x('Chontabamba', 'PROX', 'ry-wc-city-select'),
		_x('Constitucion', 'PROX', 'ry-wc-city-select'),
		_x('Huancabamba', 'PROX', 'ry-wc-city-select'),
		_x('Oxapampa District', 'PROX', 'ry-wc-city-select'),
		_x('Palcazu', 'PROX', 'ry-wc-city-select'),
		_x('Pozuzo', 'PROX', 'ry-wc-city-select'),
		_x('Puerto Bermudez', 'PROX', 'ry-wc-city-select'),
		_x('Villa Rica', 'PROX', 'ry-wc-city-select'),
	],
	'PRPA' => [
		_x('Guadalupe', 'PRPA', 'ry-wc-city-select'),
		_x('Jequetepeque', 'PRPA', 'ry-wc-city-select'),
		_x('Pacasmayo', 'PRPA', 'ry-wc-city-select'),
		_x('San Jose', 'PRPA', 'ry-wc-city-select'),
		_x('San Pedro De Lloc', 'PRPA', 'ry-wc-city-select'),
	],
	'PRPA2' => [
		_x('Chaglla', 'PRPA2', 'ry-wc-city-select'),
		_x('Molino', 'PRPA2', 'ry-wc-city-select'),
		_x('Panao', 'PRPA2', 'ry-wc-city-select'),
		_x('Umari', 'PRPA2', 'ry-wc-city-select'),
	],
	'PRPA3' => [
		_x('Amotape', 'PRPA3', 'ry-wc-city-select'),
		_x('Arenal', 'PRPA3', 'ry-wc-city-select'),
		_x('Colan', 'PRPA3', 'ry-wc-city-select'),
		_x('La Huaca', 'PRPA3', 'ry-wc-city-select'),
		_x('Paita', 'PRPA3', 'ry-wc-city-select'),
		_x('Tamarindo', 'PRPA3', 'ry-wc-city-select'),
		_x('Vichayal', 'PRPA3', 'ry-wc-city-select'),
	],
	'PRPA4' => [
		_x('Bolognesi', 'PRPA4', 'ry-wc-city-select'),
		_x('Cabana', 'PRPA4', 'ry-wc-city-select'),
		_x('Conchucos', 'PRPA4', 'ry-wc-city-select'),
		_x('Huacaschuque', 'PRPA4', 'ry-wc-city-select'),
		_x('Huandoval', 'PRPA4', 'ry-wc-city-select'),
		_x('Lacabamba', 'PRPA4', 'ry-wc-city-select'),
		_x('Llapo', 'PRPA4', 'ry-wc-city-select'),
		_x('Pallasca', 'PRPA4', 'ry-wc-city-select'),
		_x('Pampas', 'PRPA4', 'ry-wc-city-select'),
		_x('Santa Rosa', 'PRPA4', 'ry-wc-city-select'),
		_x('Tauca', 'PRPA4', 'ry-wc-city-select'),
	],
	'PRPA5' => [
		_x('Llipata', 'PRPA5', 'ry-wc-city-select'),
		_x('Palpa', 'PRPA5', 'ry-wc-city-select'),
		_x('Rio Grande', 'PRPA5', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRPA5', 'ry-wc-city-select'),
		_x('Tibillo', 'PRPA5', 'ry-wc-city-select'),
	],
	'PRPA6' => [
		_x('Chumpi', 'PRPA6', 'ry-wc-city-select'),
		_x('Coracora', 'PRPA6', 'ry-wc-city-select'),
		_x('Coronel Castaneda', 'PRPA6', 'ry-wc-city-select'),
		_x('Pacapausa', 'PRPA6', 'ry-wc-city-select'),
		_x('Pullo', 'PRPA6', 'ry-wc-city-select'),
		_x('Puyusca', 'PRPA6', 'ry-wc-city-select'),
		_x('San Francisco De Ravacayco', 'PRPA6', 'ry-wc-city-select'),
		_x('Upahuacho', 'PRPA6', 'ry-wc-city-select'),
	],
	'PRPA7' => [
		_x('Accha', 'PRPA7', 'ry-wc-city-select'),
		_x('Ccapi', 'PRPA7', 'ry-wc-city-select'),
		_x('Colcha', 'PRPA7', 'ry-wc-city-select'),
		_x('Huanoquite', 'PRPA7', 'ry-wc-city-select'),
		_x('Omacha', 'PRPA7', 'ry-wc-city-select'),
		_x('Paccaritambo', 'PRPA7', 'ry-wc-city-select'),
		_x('Paruro', 'PRPA7', 'ry-wc-city-select'),
		_x('Pillpinto', 'PRPA7', 'ry-wc-city-select'),
		_x('Yaurisque', 'PRPA7', 'ry-wc-city-select'),
	],
	'PRPA8' => [
		_x('Chaupimarca', 'PRPA8', 'ry-wc-city-select'),
		_x('Huachon', 'PRPA8', 'ry-wc-city-select'),
		_x('Huariaca', 'PRPA8', 'ry-wc-city-select'),
		_x('Huayllay', 'PRPA8', 'ry-wc-city-select'),
		_x('Ninacaca', 'PRPA8', 'ry-wc-city-select'),
		_x('Pallanchacra', 'PRPA8', 'ry-wc-city-select'),
		_x('Paucartambo', 'PRPA8', 'ry-wc-city-select'),
		_x('San Francisco De Asis De Yarusyacan', 'PRPA8', 'ry-wc-city-select'),
		_x('Simon Bolivar', 'PRPA8', 'ry-wc-city-select'),
		_x('Ticlacayan', 'PRPA8', 'ry-wc-city-select'),
		_x('Tinyahuarco', 'PRPA8', 'ry-wc-city-select'),
		_x('Vicco', 'PRPA8', 'ry-wc-city-select'),
		_x('Yanacancha', 'PRPA8', 'ry-wc-city-select'),
	],
	'PRPA9' => [
		_x('Buldibuyo', 'PRPA9', 'ry-wc-city-select'),
		_x('Chillia', 'PRPA9', 'ry-wc-city-select'),
		_x('Huancaspata', 'PRPA9', 'ry-wc-city-select'),
		_x('Huaylillas', 'PRPA9', 'ry-wc-city-select'),
		_x('Huayo', 'PRPA9', 'ry-wc-city-select'),
		_x('Ongon', 'PRPA9', 'ry-wc-city-select'),
		_x('Parcoy', 'PRPA9', 'ry-wc-city-select'),
		_x('Pataz', 'PRPA9', 'ry-wc-city-select'),
		_x('Pias', 'PRPA9', 'ry-wc-city-select'),
		_x('Santiago De Challas', 'PRPA9', 'ry-wc-city-select'),
		_x('Taurija', 'PRPA9', 'ry-wc-city-select'),
		_x('Tayabamba', 'PRPA9', 'ry-wc-city-select'),
		_x('Urpay', 'PRPA9', 'ry-wc-city-select'),
	],
	'PRPA10' => [
		_x('Caicay', 'PRPA10', 'ry-wc-city-select'),
		_x('Challabamba', 'PRPA10', 'ry-wc-city-select'),
		_x('Colquepata', 'PRPA10', 'ry-wc-city-select'),
		_x('Huancarani', 'PRPA10', 'ry-wc-city-select'),
		_x('Kosnipata', 'PRPA10', 'ry-wc-city-select'),
		_x('Paucartambo', 'PRPA10', 'ry-wc-city-select'),
	],
	'PRPI' => [
		_x('Huancano', 'PRPI', 'ry-wc-city-select'),
		_x('Humay', 'PRPI', 'ry-wc-city-select'),
		_x('Independencia', 'PRPI', 'ry-wc-city-select'),
		_x('Paracas', 'PRPI', 'ry-wc-city-select'),
		_x('Pisco', 'PRPI', 'ry-wc-city-select'),
		_x('San Andres', 'PRPI', 'ry-wc-city-select'),
		_x('San Clemente', 'PRPI', 'ry-wc-city-select'),
		_x('Tupac Amaru Inca', 'PRPI', 'ry-wc-city-select'),
	],
	'PRPI2' => [
		_x('Castilla', 'PRPI2', 'ry-wc-city-select'),
		_x('Catacaos', 'PRPI2', 'ry-wc-city-select'),
		_x('Cura Mori', 'PRPI2', 'ry-wc-city-select'),
		_x('El Tallan', 'PRPI2', 'ry-wc-city-select'),
		_x('La Arena', 'PRPI2', 'ry-wc-city-select'),
		_x('La Union', 'PRPI2', 'ry-wc-city-select'),
		_x('Las Lomas', 'PRPI2', 'ry-wc-city-select'),
		_x('Piura', 'PRPI2', 'ry-wc-city-select'),
		_x('Tambo Grande', 'PRPI2', 'ry-wc-city-select'),
		_x('Veintiseis De Octubre', 'PRPI2', 'ry-wc-city-select'),
	],
	'PRPO' => [
		_x('Huayllan', 'PRPO', 'ry-wc-city-select'),
		_x('Parobamba', 'PRPO', 'ry-wc-city-select'),
		_x('Pomabamba', 'PRPO', 'ry-wc-city-select'),
		_x('Quinuabamba', 'PRPO', 'ry-wc-city-select'),
	],
	'PRPU' => [
		_x('Acora', 'PRPU', 'ry-wc-city-select'),
		_x('Amantani', 'PRPU', 'ry-wc-city-select'),
		_x('Atuncolla', 'PRPU', 'ry-wc-city-select'),
		_x('Capachica', 'PRPU', 'ry-wc-city-select'),
		_x('Chucuito', 'PRPU', 'ry-wc-city-select'),
		_x('Coata', 'PRPU', 'ry-wc-city-select'),
		_x('Huata', 'PRPU', 'ry-wc-city-select'),
		_x('Manazo', 'PRPU', 'ry-wc-city-select'),
		_x('Paucarcolla', 'PRPU', 'ry-wc-city-select'),
		_x('Pichacani', 'PRPU', 'ry-wc-city-select'),
		_x('Plateria', 'PRPU', 'ry-wc-city-select'),
		_x('Puno', 'PRPU', 'ry-wc-city-select'),
		_x('San Antonio', 'PRPU', 'ry-wc-city-select'),
		_x('Tiquillaca', 'PRPU', 'ry-wc-city-select'),
		_x('Vilque', 'PRPU', 'ry-wc-city-select'),
	],
	'PRQU' => [
		_x('Andahuaylillas', 'PRQU', 'ry-wc-city-select'),
		_x('Camanti', 'PRQU', 'ry-wc-city-select'),
		_x('Ccarhuayo', 'PRQU', 'ry-wc-city-select'),
		_x('Ccatca', 'PRQU', 'ry-wc-city-select'),
		_x('Cusipata', 'PRQU', 'ry-wc-city-select'),
		_x('Huaro', 'PRQU', 'ry-wc-city-select'),
		_x('Lucre', 'PRQU', 'ry-wc-city-select'),
		_x('Marcapata', 'PRQU', 'ry-wc-city-select'),
		_x('Ocongate', 'PRQU', 'ry-wc-city-select'),
		_x('Oropesa', 'PRQU', 'ry-wc-city-select'),
		_x('Quiquijana', 'PRQU', 'ry-wc-city-select'),
		_x('Urcos', 'PRQU', 'ry-wc-city-select'),
	],
	'PRRE' => [
		_x('Catac', 'PRRE', 'ry-wc-city-select'),
		_x('Cotaparaco', 'PRRE', 'ry-wc-city-select'),
		_x('Huayllapampa', 'PRRE', 'ry-wc-city-select'),
		_x('Llacllin', 'PRRE', 'ry-wc-city-select'),
		_x('Marca', 'PRRE', 'ry-wc-city-select'),
		_x('Pampas Chico', 'PRRE', 'ry-wc-city-select'),
		_x('Pararin', 'PRRE', 'ry-wc-city-select'),
		_x('Recuay', 'PRRE', 'ry-wc-city-select'),
		_x('Tapacocha', 'PRRE', 'ry-wc-city-select'),
		_x('Ticapampa', 'PRRE', 'ry-wc-city-select'),
	],
	'PRRE2' => [
		_x('Alto Tapiche', 'PRRE2', 'ry-wc-city-select'),
		_x('Capelo', 'PRRE2', 'ry-wc-city-select'),
		_x('Emilio San Martin', 'PRRE2', 'ry-wc-city-select'),
		_x('Jenaro Herrera', 'PRRE2', 'ry-wc-city-select'),
		_x('Maquia', 'PRRE2', 'ry-wc-city-select'),
		_x('Puinahua', 'PRRE2', 'ry-wc-city-select'),
		_x('Requena', 'PRRE2', 'ry-wc-city-select'),
		_x('Saquena', 'PRRE2', 'ry-wc-city-select'),
		_x('Soplin', 'PRRE2', 'ry-wc-city-select'),
		_x('Tapiche', 'PRRE2', 'ry-wc-city-select'),
		_x('Yaquerana', 'PRRE2', 'ry-wc-city-select'),
	],
	'PRRI' => [
		_x('Awajun', 'PRRI', 'ry-wc-city-select'),
		_x('Elias Soplin Vargas', 'PRRI', 'ry-wc-city-select'),
		_x('Nueva Cajamarca', 'PRRI', 'ry-wc-city-select'),
		_x('Pardo Miguel', 'PRRI', 'ry-wc-city-select'),
		_x('Posic', 'PRRI', 'ry-wc-city-select'),
		_x('Rioja', 'PRRI', 'ry-wc-city-select'),
		_x('San Fernando', 'PRRI', 'ry-wc-city-select'),
		_x('Yorongos', 'PRRI', 'ry-wc-city-select'),
		_x('Yuracyacu', 'PRRI', 'ry-wc-city-select'),
	],
	'PRROME' => [
		_x('Chirimoto', 'PRROME', 'ry-wc-city-select'),
		_x('Cochamal', 'PRROME', 'ry-wc-city-select'),
		_x('Huambo', 'PRROME', 'ry-wc-city-select'),
		_x('Limabamba', 'PRROME', 'ry-wc-city-select'),
		_x('Longar', 'PRROME', 'ry-wc-city-select'),
		_x('Mariscal Benavides', 'PRROME', 'ry-wc-city-select'),
		_x('Milpuc', 'PRROME', 'ry-wc-city-select'),
		_x('Omia', 'PRROME', 'ry-wc-city-select'),
		_x('San Nicolas', 'PRROME', 'ry-wc-city-select'),
		_x('Santa Rosa', 'PRROME', 'ry-wc-city-select'),
		_x('Totora', 'PRROME', 'ry-wc-city-select'),
		_x('Vista Alegre', 'PRROME', 'ry-wc-city-select'),
	],
	'PRSAIG' => [
		_x('Chirinos', 'PRSAIG', 'ry-wc-city-select'),
		_x('Huarango', 'PRSAIG', 'ry-wc-city-select'),
		_x('La Coipa', 'PRSAIG', 'ry-wc-city-select'),
		_x('Namballe', 'PRSAIG', 'ry-wc-city-select'),
		_x('San Ignacio', 'PRSAIG', 'ry-wc-city-select'),
		_x('San Jose De Lourdes', 'PRSAIG', 'ry-wc-city-select'),
		_x('Tabaconas', 'PRSAIG', 'ry-wc-city-select'),
	],
	'PRSAMA' => [
		_x('Alberto Leveau', 'PRSAMA', 'ry-wc-city-select'),
		_x('Cacatachi', 'PRSAMA', 'ry-wc-city-select'),
		_x('Chazuta', 'PRSAMA', 'ry-wc-city-select'),
		_x('Chipurana', 'PRSAMA', 'ry-wc-city-select'),
		_x('El Porvenir', 'PRSAMA', 'ry-wc-city-select'),
		_x('Huimbayoc', 'PRSAMA', 'ry-wc-city-select'),
		_x('Juan Guerra', 'PRSAMA', 'ry-wc-city-select'),
		_x('La Banda De Shilcayo', 'PRSAMA', 'ry-wc-city-select'),
		_x('Morales', 'PRSAMA', 'ry-wc-city-select'),
		_x('Papaplaya', 'PRSAMA', 'ry-wc-city-select'),
		_x('San Antonio', 'PRSAMA', 'ry-wc-city-select'),
		_x('Sauce', 'PRSAMA', 'ry-wc-city-select'),
		_x('Shapaja', 'PRSAMA', 'ry-wc-city-select'),
		_x('Tarapoto', 'PRSAMA', 'ry-wc-city-select'),
	],
	'PRSAMI' => [
		_x('Bolivar', 'PRSAMI', 'ry-wc-city-select'),
		_x('Calquis', 'PRSAMI', 'ry-wc-city-select'),
		_x('Catilluc', 'PRSAMI', 'ry-wc-city-select'),
		_x('El Prado', 'PRSAMI', 'ry-wc-city-select'),
		_x('La Florida', 'PRSAMI', 'ry-wc-city-select'),
		_x('Llapa', 'PRSAMI', 'ry-wc-city-select'),
		_x('Nanchoc', 'PRSAMI', 'ry-wc-city-select'),
		_x('Niepos', 'PRSAMI', 'ry-wc-city-select'),
		_x('San Gregorio', 'PRSAMI', 'ry-wc-city-select'),
		_x('San Miguel', 'PRSAMI', 'ry-wc-city-select'),
		_x('San Silvestre De Cochan', 'PRSAMI', 'ry-wc-city-select'),
		_x('Tongod', 'PRSAMI', 'ry-wc-city-select'),
		_x('Union Agua Blanca', 'PRSAMI', 'ry-wc-city-select'),
	],
	'PRSA' => [
		_x('Alto Inambari', 'PRSA', 'ry-wc-city-select'),
		_x('Cuyocuyo', 'PRSA', 'ry-wc-city-select'),
		_x('Limbani', 'PRSA', 'ry-wc-city-select'),
		_x('Patambuco', 'PRSA', 'ry-wc-city-select'),
		_x('Phara', 'PRSA', 'ry-wc-city-select'),
		_x('Quiaca', 'PRSA', 'ry-wc-city-select'),
		_x('San Juan Del Oro', 'PRSA', 'ry-wc-city-select'),
		_x('San Pedro De Putina Punco', 'PRSA', 'ry-wc-city-select'),
		_x('Sandia', 'PRSA', 'ry-wc-city-select'),
		_x('Yanahuaya', 'PRSA', 'ry-wc-city-select'),
	],
	'PRSA2' => [
		_x('Caceres Del Peru', 'PRSA2', 'ry-wc-city-select'),
		_x('Chimbote', 'PRSA2', 'ry-wc-city-select'),
		_x('Coishco', 'PRSA2', 'ry-wc-city-select'),
		_x('Macate', 'PRSA2', 'ry-wc-city-select'),
		_x('Moro', 'PRSA2', 'ry-wc-city-select'),
		_x('Nepena', 'PRSA2', 'ry-wc-city-select'),
		_x('Nuevo Chimbote', 'PRSA2', 'ry-wc-city-select'),
		_x('Samanco', 'PRSA2', 'ry-wc-city-select'),
		_x('Santa', 'PRSA2', 'ry-wc-city-select'),
	],
	'PRSACR' => [
		_x('Andabamba', 'PRSACR', 'ry-wc-city-select'),
		_x('Catache', 'PRSACR', 'ry-wc-city-select'),
		_x('Chancaybanos', 'PRSACR', 'ry-wc-city-select'),
		_x('La Esperanza', 'PRSACR', 'ry-wc-city-select'),
		_x('Ninabamba', 'PRSACR', 'ry-wc-city-select'),
		_x('Pulan', 'PRSACR', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRSACR', 'ry-wc-city-select'),
		_x('Saucepampa', 'PRSACR', 'ry-wc-city-select'),
		_x('Sexi', 'PRSACR', 'ry-wc-city-select'),
		_x('Uticyacu', 'PRSACR', 'ry-wc-city-select'),
		_x('Yauyucan', 'PRSACR', 'ry-wc-city-select'),
	],
	'PRSACH' => [
		_x('Angasmarca', 'PRSACH', 'ry-wc-city-select'),
		_x('Cachicadan', 'PRSACH', 'ry-wc-city-select'),
		_x('Mollebamba', 'PRSACH', 'ry-wc-city-select'),
		_x('Mollepata', 'PRSACH', 'ry-wc-city-select'),
		_x('Quiruvilca', 'PRSACH', 'ry-wc-city-select'),
		_x('Santa Cruz De Chuca', 'PRSACH', 'ry-wc-city-select'),
		_x('Santiago De Chuco', 'PRSACH', 'ry-wc-city-select'),
		_x('Sitabamba', 'PRSACH', 'ry-wc-city-select'),
	],
	'PRSA3' => [
		_x('Coviriali', 'PRSA3', 'ry-wc-city-select'),
		_x('Llaylla', 'PRSA3', 'ry-wc-city-select'),
		_x('Mazamari - Pangoa', 'PRSA3', 'ry-wc-city-select'),
		_x('Pampa Hermosa', 'PRSA3', 'ry-wc-city-select'),
		_x('Rio Negro', 'PRSA3', 'ry-wc-city-select'),
		_x('Rio Tambo', 'PRSA3', 'ry-wc-city-select'),
		_x('Satipo', 'PRSA3', 'ry-wc-city-select'),
		_x('Vizcatan Del Ene', 'PRSA3', 'ry-wc-city-select'),
	],
	'PRSI' => [
		_x('Acobamba', 'PRSI', 'ry-wc-city-select'),
		_x('Alfonso Ugarte', 'PRSI', 'ry-wc-city-select'),
		_x('Cashapampa', 'PRSI', 'ry-wc-city-select'),
		_x('Chingalpo', 'PRSI', 'ry-wc-city-select'),
		_x('Huayllabamba', 'PRSI', 'ry-wc-city-select'),
		_x('Quiches', 'PRSI', 'ry-wc-city-select'),
		_x('Ragash', 'PRSI', 'ry-wc-city-select'),
		_x('San Juan', 'PRSI', 'ry-wc-city-select'),
		_x('Sicsibamba', 'PRSI', 'ry-wc-city-select'),
		_x('Sihuas', 'PRSI', 'ry-wc-city-select'),
	],
	'PRSU' => [
		_x('Belen', 'PRSU', 'ry-wc-city-select'),
		_x('Chalcos', 'PRSU', 'ry-wc-city-select'),
		_x('Chilcayoc', 'PRSU', 'ry-wc-city-select'),
		_x('Huacana', 'PRSU', 'ry-wc-city-select'),
		_x('Morcolla', 'PRSU', 'ry-wc-city-select'),
		_x('Paico', 'PRSU', 'ry-wc-city-select'),
		_x('Querobamba', 'PRSU', 'ry-wc-city-select'),
		_x('San Pedro De Larcay', 'PRSU', 'ry-wc-city-select'),
		_x('San Salvador De Quije', 'PRSU', 'ry-wc-city-select'),
		_x('Santiago De Paucaray', 'PRSU', 'ry-wc-city-select'),
		_x('Soras', 'PRSU', 'ry-wc-city-select'),
	],
	'PRSU2' => [
		_x('Bellavista', 'PRSU2', 'ry-wc-city-select'),
		_x('Ignacio Escudero', 'PRSU2', 'ry-wc-city-select'),
		_x('Lancones', 'PRSU2', 'ry-wc-city-select'),
		_x('Marcavelica', 'PRSU2', 'ry-wc-city-select'),
		_x('Miguel Checa', 'PRSU2', 'ry-wc-city-select'),
		_x('Querecotillo', 'PRSU2', 'ry-wc-city-select'),
		_x('Salitral', 'PRSU2', 'ry-wc-city-select'),
		_x('Sullana', 'PRSU2', 'ry-wc-city-select'),
	],
	'PRTA' => [
		_x('Alto De La Alianza', 'PRTA', 'ry-wc-city-select'),
		_x('Calana', 'PRTA', 'ry-wc-city-select'),
		_x('Ciudad Nueva', 'PRTA', 'ry-wc-city-select'),
		_x('Coronel Gregorio Albarracin Lanchipa', 'PRTA', 'ry-wc-city-select'),
		_x('Inclan', 'PRTA', 'ry-wc-city-select'),
		_x('La Yarada Los Palos', 'PRTA', 'ry-wc-city-select'),
		_x('Pachia', 'PRTA', 'ry-wc-city-select'),
		_x('Palca', 'PRTA', 'ry-wc-city-select'),
		_x('Pocollay', 'PRTA', 'ry-wc-city-select'),
		_x('Sama', 'PRTA', 'ry-wc-city-select'),
		_x('Tacna', 'PRTA', 'ry-wc-city-select'),
	],
	'PRTA2' => [
		_x('Iberia', 'PRTA2', 'ry-wc-city-select'),
		_x('Inapari', 'PRTA2', 'ry-wc-city-select'),
		_x('Tahuamanu', 'PRTA2', 'ry-wc-city-select'),
	],
	'PRTA3' => [
		_x('El Alto', 'PRTA3', 'ry-wc-city-select'),
		_x('La Brea', 'PRTA3', 'ry-wc-city-select'),
		_x('Lobitos', 'PRTA3', 'ry-wc-city-select'),
		_x('Los Organos', 'PRTA3', 'ry-wc-city-select'),
		_x('Mancora', 'PRTA3', 'ry-wc-city-select'),
		_x('Parinas', 'PRTA3', 'ry-wc-city-select'),
	],
	'PRTA4' => [
		_x('Inambari', 'PRTA4', 'ry-wc-city-select'),
		_x('Laberinto', 'PRTA4', 'ry-wc-city-select'),
		_x('Las Piedras', 'PRTA4', 'ry-wc-city-select'),
		_x('Tambopata', 'PRTA4', 'ry-wc-city-select'),
	],
	'PRTA5' => [
		_x('Estique', 'PRTA5', 'ry-wc-city-select'),
		_x('Estique-Pampa', 'PRTA5', 'ry-wc-city-select'),
		_x('Heroes Albarracin', 'PRTA5', 'ry-wc-city-select'),
		_x('Sitajara', 'PRTA5', 'ry-wc-city-select'),
		_x('Susapaya', 'PRTA5', 'ry-wc-city-select'),
		_x('Tarata', 'PRTA5', 'ry-wc-city-select'),
		_x('Tarucachi', 'PRTA5', 'ry-wc-city-select'),
		_x('Ticaco', 'PRTA5', 'ry-wc-city-select'),
	],
	'PRTA6' => [
		_x('Acobamba', 'PRTA6', 'ry-wc-city-select'),
		_x('Huaricolca', 'PRTA6', 'ry-wc-city-select'),
		_x('Huasahuasi', 'PRTA6', 'ry-wc-city-select'),
		_x('La Union', 'PRTA6', 'ry-wc-city-select'),
		_x('Palca', 'PRTA6', 'ry-wc-city-select'),
		_x('Palcamayo', 'PRTA6', 'ry-wc-city-select'),
		_x('San Pedro De Cajas', 'PRTA6', 'ry-wc-city-select'),
		_x('Tapo', 'PRTA6', 'ry-wc-city-select'),
		_x('Tarma', 'PRTA6', 'ry-wc-city-select'),
	],
	'PRTA7' => [
		_x('Acostambo', 'PRTA7', 'ry-wc-city-select'),
		_x('Acraquia', 'PRTA7', 'ry-wc-city-select'),
		_x('Ahuaycha', 'PRTA7', 'ry-wc-city-select'),
		_x('Andaymarca', 'PRTA7', 'ry-wc-city-select'),
		_x('Colcabamba', 'PRTA7', 'ry-wc-city-select'),
		_x('Daniel Hernandez', 'PRTA7', 'ry-wc-city-select'),
		_x('Huachocolpa', 'PRTA7', 'ry-wc-city-select'),
		_x('Huaribamba', 'PRTA7', 'ry-wc-city-select'),
		_x('Nahuimpuquio', 'PRTA7', 'ry-wc-city-select'),
		_x('Pampas', 'PRTA7', 'ry-wc-city-select'),
		_x('Pazos', 'PRTA7', 'ry-wc-city-select'),
		_x('Pichos', 'PRTA7', 'ry-wc-city-select'),
		_x('Quichuas', 'PRTA7', 'ry-wc-city-select'),
		_x('Quishuar', 'PRTA7', 'ry-wc-city-select'),
		_x('Roble', 'PRTA7', 'ry-wc-city-select'),
		_x('Salcabamba', 'PRTA7', 'ry-wc-city-select'),
		_x('Salcahuasi', 'PRTA7', 'ry-wc-city-select'),
		_x('San Marcos De Rocchac', 'PRTA7', 'ry-wc-city-select'),
		_x('Santiago De Tucuma', 'PRTA7', 'ry-wc-city-select'),
		_x('Surcubamba', 'PRTA7', 'ry-wc-city-select'),
		_x('Tintay Puncu', 'PRTA7', 'ry-wc-city-select'),
	],
	'PRTR' => [
		_x('El Porvenir', 'PRTR', 'ry-wc-city-select'),
		_x('Florencia De Mora', 'PRTR', 'ry-wc-city-select'),
		_x('Huanchaco', 'PRTR', 'ry-wc-city-select'),
		_x('La Esperanza', 'PRTR', 'ry-wc-city-select'),
		_x('Laredo', 'PRTR', 'ry-wc-city-select'),
		_x('Moche', 'PRTR', 'ry-wc-city-select'),
		_x('Poroto', 'PRTR', 'ry-wc-city-select'),
		_x('Salaverry', 'PRTR', 'ry-wc-city-select'),
		_x('Simbal', 'PRTR', 'ry-wc-city-select'),
		_x('Trujillo', 'PRTR', 'ry-wc-city-select'),
		_x('Victor Larco Herrera', 'PRTR', 'ry-wc-city-select'),
	],
	'PRTU' => [
		_x('Corrales', 'PRTU', 'ry-wc-city-select'),
		_x('La Cruz', 'PRTU', 'ry-wc-city-select'),
		_x('Pampas De Hospital', 'PRTU', 'ry-wc-city-select'),
		_x('San Jacinto', 'PRTU', 'ry-wc-city-select'),
		_x('San Juan De La Virgen', 'PRTU', 'ry-wc-city-select'),
		_x('Tumbes', 'PRTU', 'ry-wc-city-select'),
	],
	'PRUC' => [
		_x('Contamana', 'PRUC', 'ry-wc-city-select'),
		_x('Inahuaya', 'PRUC', 'ry-wc-city-select'),
		_x('Padre Marquez', 'PRUC', 'ry-wc-city-select'),
		_x('Pampa Hermosa', 'PRUC', 'ry-wc-city-select'),
		_x('Sarayacu', 'PRUC', 'ry-wc-city-select'),
		_x('Vargas Guerra', 'PRUC', 'ry-wc-city-select'),
	],
	'PRUR' => [
		_x('Chinchero', 'PRUR', 'ry-wc-city-select'),
		_x('Huayllabamba', 'PRUR', 'ry-wc-city-select'),
		_x('Machupicchu', 'PRUR', 'ry-wc-city-select'),
		_x('Maras', 'PRUR', 'ry-wc-city-select'),
		_x('Ollantaytambo', 'PRUR', 'ry-wc-city-select'),
		_x('Urubamba', 'PRUR', 'ry-wc-city-select'),
		_x('Yucay', 'PRUR', 'ry-wc-city-select'),
	],
	'PRVIFA' => [
		_x('Alcamenca', 'PRVIFA', 'ry-wc-city-select'),
		_x('Apongo', 'PRVIFA', 'ry-wc-city-select'),
		_x('Asquipata', 'PRVIFA', 'ry-wc-city-select'),
		_x('Canaria', 'PRVIFA', 'ry-wc-city-select'),
		_x('Cayara', 'PRVIFA', 'ry-wc-city-select'),
		_x('Colca', 'PRVIFA', 'ry-wc-city-select'),
		_x('Huamanquiquia', 'PRVIFA', 'ry-wc-city-select'),
		_x('Huancapi', 'PRVIFA', 'ry-wc-city-select'),
		_x('Huancaraylla', 'PRVIFA', 'ry-wc-city-select'),
		_x('Huaya', 'PRVIFA', 'ry-wc-city-select'),
		_x('Sarhua', 'PRVIFA', 'ry-wc-city-select'),
		_x('Vilcanchos', 'PRVIFA', 'ry-wc-city-select'),
	],
	'PRVIHU' => [
		_x('Accomarca', 'PRVIHU', 'ry-wc-city-select'),
		_x('Carhuanca', 'PRVIHU', 'ry-wc-city-select'),
		_x('Concepcion', 'PRVIHU', 'ry-wc-city-select'),
		_x('Huambalpa', 'PRVIHU', 'ry-wc-city-select'),
		_x('Independencia', 'PRVIHU', 'ry-wc-city-select'),
		_x('Saurama', 'PRVIHU', 'ry-wc-city-select'),
		_x('Vilcas Huaman', 'PRVIHU', 'ry-wc-city-select'),
		_x('Vischongo', 'PRVIHU', 'ry-wc-city-select'),
	],
	'PRYA' => [
		_x('Chacapalpa', 'PRYA', 'ry-wc-city-select'),
		_x('Huay-Huay', 'PRYA', 'ry-wc-city-select'),
		_x('La Oroya', 'PRYA', 'ry-wc-city-select'),
		_x('Marcapomacocha', 'PRYA', 'ry-wc-city-select'),
		_x('Morococha', 'PRYA', 'ry-wc-city-select'),
		_x('Paccha', 'PRYA', 'ry-wc-city-select'),
		_x('Santa Barbara De Carhuacayan', 'PRYA', 'ry-wc-city-select'),
		_x('Santa Rosa De Sacco', 'PRYA', 'ry-wc-city-select'),
		_x('Suitucancha', 'PRYA', 'ry-wc-city-select'),
		_x('Yauli', 'PRYA', 'ry-wc-city-select'),
	],
	'PRYA2' => [
		_x('Alis', 'PRYA2', 'ry-wc-city-select'),
		_x('Ayauca', 'PRYA2', 'ry-wc-city-select'),
		_x('Ayaviri', 'PRYA2', 'ry-wc-city-select'),
		_x('Azangaro', 'PRYA2', 'ry-wc-city-select'),
		_x('Cacra', 'PRYA2', 'ry-wc-city-select'),
		_x('Carania', 'PRYA2', 'ry-wc-city-select'),
		_x('Catahuasi', 'PRYA2', 'ry-wc-city-select'),
		_x('Chocos', 'PRYA2', 'ry-wc-city-select'),
		_x('Cochas', 'PRYA2', 'ry-wc-city-select'),
		_x('Colonia', 'PRYA2', 'ry-wc-city-select'),
		_x('Hongos', 'PRYA2', 'ry-wc-city-select'),
		_x('Huampara', 'PRYA2', 'ry-wc-city-select'),
		_x('Huancaya', 'PRYA2', 'ry-wc-city-select'),
		_x('Huanec', 'PRYA2', 'ry-wc-city-select'),
		_x('Huangascar', 'PRYA2', 'ry-wc-city-select'),
		_x('Huantan', 'PRYA2', 'ry-wc-city-select'),
		_x('Laraos', 'PRYA2', 'ry-wc-city-select'),
		_x('Lincha', 'PRYA2', 'ry-wc-city-select'),
		_x('Madean', 'PRYA2', 'ry-wc-city-select'),
		_x('Miraflores', 'PRYA2', 'ry-wc-city-select'),
		_x('Omas', 'PRYA2', 'ry-wc-city-select'),
		_x('Putinza', 'PRYA2', 'ry-wc-city-select'),
		_x('Quinches', 'PRYA2', 'ry-wc-city-select'),
		_x('Quinocay', 'PRYA2', 'ry-wc-city-select'),
		_x('San Joaquin', 'PRYA2', 'ry-wc-city-select'),
		_x('San Pedro De Pilas', 'PRYA2', 'ry-wc-city-select'),
		_x('Tanta', 'PRYA2', 'ry-wc-city-select'),
		_x('Tauripampa', 'PRYA2', 'ry-wc-city-select'),
		_x('Tomas', 'PRYA2', 'ry-wc-city-select'),
		_x('Tupe', 'PRYA2', 'ry-wc-city-select'),
		_x('Vinac', 'PRYA2', 'ry-wc-city-select'),
		_x('Vitis', 'PRYA2', 'ry-wc-city-select'),
		_x('Yauyos', 'PRYA2', 'ry-wc-city-select'),
	],
	'PRYU' => [
		_x('Cascapara', 'PRYU', 'ry-wc-city-select'),
		_x('Mancos', 'PRYU', 'ry-wc-city-select'),
		_x('Matacoto', 'PRYU', 'ry-wc-city-select'),
		_x('Quillo', 'PRYU', 'ry-wc-city-select'),
		_x('Ranrahirca', 'PRYU', 'ry-wc-city-select'),
		_x('Shupluy', 'PRYU', 'ry-wc-city-select'),
		_x('Yanama', 'PRYU', 'ry-wc-city-select'),
		_x('Yungay', 'PRYU', 'ry-wc-city-select'),
	],
	'PRZA' => [
		_x('Aguas Verdes', 'PRZA', 'ry-wc-city-select'),
		_x('Matapalo', 'PRZA', 'ry-wc-city-select'),
		_x('Papayal', 'PRZA', 'ry-wc-city-select'),
		_x('Zarumilla', 'PRZA', 'ry-wc-city-select'),
	],
	'PUIN' => [
		_x('Codo Del Pozuzo', 'PUIN', 'ry-wc-city-select'),
		_x('Honoria', 'PUIN', 'ry-wc-city-select'),
		_x('Puerto Inca', 'PUIN', 'ry-wc-city-select'),
		_x('Tournavista', 'PUIN', 'ry-wc-city-select'),
		_x('Yuyapichis', 'PUIN', 'ry-wc-city-select'),
	],
	'PU' => [
		_x('Purus', 'PU', 'ry-wc-city-select'),
	],
	'PU2' => [
		_x('Putumayo', 'PU2', 'ry-wc-city-select'),
		_x('Rosa Panduro', 'PU2', 'ry-wc-city-select'),
		_x('Teniente Manuel Clavero', 'PU2', 'ry-wc-city-select'),
		_x('Yaguas', 'PU2', 'ry-wc-city-select'),
	],
	'SAANPU' => [
		_x('Ananea', 'SAANPU', 'ry-wc-city-select'),
		_x('Pedro Vilca Apaza', 'SAANPU', 'ry-wc-city-select'),
		_x('Putina', 'SAANPU', 'ry-wc-city-select'),
		_x('Quilcapuncu', 'SAANPU', 'ry-wc-city-select'),
		_x('Sina', 'SAANPU', 'ry-wc-city-select'),
	],
	'SAMA' => [
		_x('Chancay', 'SAMA', 'ry-wc-city-select'),
		_x('Eduardo Villanueva', 'SAMA', 'ry-wc-city-select'),
		_x('Gregorio Pita', 'SAMA', 'ry-wc-city-select'),
		_x('Ichocan', 'SAMA', 'ry-wc-city-select'),
		_x('Jose Manuel Quiroz', 'SAMA', 'ry-wc-city-select'),
		_x('Jose Sabogal', 'SAMA', 'ry-wc-city-select'),
		_x('Pedro Galvez', 'SAMA', 'ry-wc-city-select'),
	],
	'SAPA' => [
		_x('San Bernardino', 'SAPA', 'ry-wc-city-select'),
		_x('San Luis', 'SAPA', 'ry-wc-city-select'),
		_x('San Pablo', 'SAPA', 'ry-wc-city-select'),
		_x('Tumbaden', 'SAPA', 'ry-wc-city-select'),
	],
	'SARO' => [
		_x('Cabana', 'SARO', 'ry-wc-city-select'),
		_x('Cabanillas', 'SARO', 'ry-wc-city-select'),
		_x('Caracoto', 'SARO', 'ry-wc-city-select'),
		_x('Juliaca', 'SARO', 'ry-wc-city-select'),
		_x('San Miguel', 'SARO', 'ry-wc-city-select'),
	],
	'SACA' => [
		_x('Chugay', 'SACA', 'ry-wc-city-select'),
		_x('Cochorco', 'SACA', 'ry-wc-city-select'),
		_x('Curgos', 'SACA', 'ry-wc-city-select'),
		_x('Huamachuco', 'SACA', 'ry-wc-city-select'),
		_x('Marcabal', 'SACA', 'ry-wc-city-select'),
		_x('Sanagoran', 'SACA', 'ry-wc-city-select'),
		_x('Sarin', 'SACA', 'ry-wc-city-select'),
		_x('Sartimbamba', 'SACA', 'ry-wc-city-select'),
	],
	'SE' => [
		_x('Bellavista De La Union', 'SE', 'ry-wc-city-select'),
		_x('Bernal', 'SE', 'ry-wc-city-select'),
		_x('Cristo Nos Valga', 'SE', 'ry-wc-city-select'),
		_x('Rinconada Llicuar', 'SE', 'ry-wc-city-select'),
		_x('Sechura', 'SE', 'ry-wc-city-select'),
		_x('Vice', 'SE', 'ry-wc-city-select'),
	],
	'TO' => [
		_x('Nuevo Progreso', 'TO', 'ry-wc-city-select'),
		_x('Polvora', 'TO', 'ry-wc-city-select'),
		_x('Shunte', 'TO', 'ry-wc-city-select'),
		_x('Tocache', 'TO', 'ry-wc-city-select'),
		_x('Uchiza', 'TO', 'ry-wc-city-select'),
	],
	'UT' => [
		_x('Bagua Grande', 'UT', 'ry-wc-city-select'),
		_x('Cajaruro', 'UT', 'ry-wc-city-select'),
		_x('Cumba', 'UT', 'ry-wc-city-select'),
		_x('El Milagro', 'UT', 'ry-wc-city-select'),
		_x('Jamalca', 'UT', 'ry-wc-city-select'),
		_x('Lonya Grande', 'UT', 'ry-wc-city-select'),
		_x('Yamon', 'UT', 'ry-wc-city-select'),
	],
	'VI' => [
		_x('Chao', 'VI', 'ry-wc-city-select'),
		_x('Guadalupito', 'VI', 'ry-wc-city-select'),
		_x('Viru', 'VI', 'ry-wc-city-select'),
	],
	'YA' => [
		_x('Aparicio Pomares', 'YA', 'ry-wc-city-select'),
		_x('Cahuac', 'YA', 'ry-wc-city-select'),
		_x('Chacabamba', 'YA', 'ry-wc-city-select'),
		_x('Chavinillo', 'YA', 'ry-wc-city-select'),
		_x('Choras', 'YA', 'ry-wc-city-select'),
		_x('Jacas Chico', 'YA', 'ry-wc-city-select'),
		_x('Obas', 'YA', 'ry-wc-city-select'),
		_x('Pampamarca', 'YA', 'ry-wc-city-select'),
	],
	'YU' => [
		_x('Anapia', 'YU', 'ry-wc-city-select'),
		_x('Copani', 'YU', 'ry-wc-city-select'),
		_x('Cuturapi', 'YU', 'ry-wc-city-select'),
		_x('Ollaraya', 'YU', 'ry-wc-city-select'),
		_x('Tinicachi', 'YU', 'ry-wc-city-select'),
		_x('Unicachi', 'YU', 'ry-wc-city-select'),
		_x('Yunguyo', 'YU', 'ry-wc-city-select'),
	],
	]
];