<?php
/**
 * Republic of the Philippines places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'PH' => [
	'AP' => [
		_x('Calanasan (Bayag)', 'AP', 'ry-wc-city-select'),
		_x('Conner', 'AP', 'ry-wc-city-select'),
		_x('Flora', 'AP', 'ry-wc-city-select'),
		_x('Kabugao', 'AP', 'ry-wc-city-select'),
		_x('Luna', 'AP', 'ry-wc-city-select'),
		_x('Pudtol', 'AP', 'ry-wc-city-select'),
		_x('Santa Marcela', 'AP', 'ry-wc-city-select'),
	],
	'BI' => [
		_x('Almeria', 'BI', 'ry-wc-city-select'),
		_x('Biliran', 'BI', 'ry-wc-city-select'),
		_x('Cabucgayan', 'BI', 'ry-wc-city-select'),
		_x('Caibiran', 'BI', 'ry-wc-city-select'),
		_x('Culaba', 'BI', 'ry-wc-city-select'),
		_x('Kawayan', 'BI', 'ry-wc-city-select'),
		_x('Maripipi', 'BI', 'ry-wc-city-select'),
		_x('Naval', 'BI', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Alburquerque', 'BO', 'ry-wc-city-select'),
		_x('Alicia', 'BO', 'ry-wc-city-select'),
		_x('Anda', 'BO', 'ry-wc-city-select'),
		_x('Antequera', 'BO', 'ry-wc-city-select'),
		_x('Baclayon', 'BO', 'ry-wc-city-select'),
		_x('Balilihan', 'BO', 'ry-wc-city-select'),
		_x('Batuan', 'BO', 'ry-wc-city-select'),
		_x('Bien Unido', 'BO', 'ry-wc-city-select'),
		_x('Bilar', 'BO', 'ry-wc-city-select'),
		_x('Buenavista', 'BO', 'ry-wc-city-select'),
		_x('Calape', 'BO', 'ry-wc-city-select'),
		_x('Candijay', 'BO', 'ry-wc-city-select'),
		_x('Carmen', 'BO', 'ry-wc-city-select'),
		_x('Catigbian', 'BO', 'ry-wc-city-select'),
		_x('Clarin', 'BO', 'ry-wc-city-select'),
		_x('Corella', 'BO', 'ry-wc-city-select'),
		_x('Cortes', 'BO', 'ry-wc-city-select'),
		_x('Dagohoy', 'BO', 'ry-wc-city-select'),
		_x('Danao', 'BO', 'ry-wc-city-select'),
		_x('Dauis', 'BO', 'ry-wc-city-select'),
		_x('Dimiao', 'BO', 'ry-wc-city-select'),
		_x('Duero', 'BO', 'ry-wc-city-select'),
		_x('Garcia Hernandez', 'BO', 'ry-wc-city-select'),
		_x('Getafe', 'BO', 'ry-wc-city-select'),
		_x('Guindulman', 'BO', 'ry-wc-city-select'),
		_x('Inabanga', 'BO', 'ry-wc-city-select'),
		_x('Jagna', 'BO', 'ry-wc-city-select'),
		_x('Lila', 'BO', 'ry-wc-city-select'),
		_x('Loay', 'BO', 'ry-wc-city-select'),
		_x('Loboc', 'BO', 'ry-wc-city-select'),
		_x('Loon', 'BO', 'ry-wc-city-select'),
		_x('Mabini', 'BO', 'ry-wc-city-select'),
		_x('Maribojoc', 'BO', 'ry-wc-city-select'),
		_x('Panglao', 'BO', 'ry-wc-city-select'),
		_x('Pilar', 'BO', 'ry-wc-city-select'),
		_x('Pres. Carlos P. Garcia (Pitogo)', 'BO', 'ry-wc-city-select'),
		_x('Sagbayan (Borja)', 'BO', 'ry-wc-city-select'),
		_x('San Isidro', 'BO', 'ry-wc-city-select'),
		_x('San Miguel', 'BO', 'ry-wc-city-select'),
		_x('Sevilla', 'BO', 'ry-wc-city-select'),
		_x('Sierra Bullones', 'BO', 'ry-wc-city-select'),
		_x('Sikatuna', 'BO', 'ry-wc-city-select'),
		_x('Tagbilaran City', 'BO', 'ry-wc-city-select'),
		_x('Talibon', 'BO', 'ry-wc-city-select'),
		_x('Trinidad', 'BO', 'ry-wc-city-select'),
		_x('Tubigon', 'BO', 'ry-wc-city-select'),
		_x('Ubay', 'BO', 'ry-wc-city-select'),
		_x('Valencia', 'BO', 'ry-wc-city-select'),
	],
	'CADI' => [
		_x('Binondo', 'CADI', 'ry-wc-city-select'),
		_x('Ermita', 'CADI', 'ry-wc-city-select'),
		_x('Intramuros', 'CADI', 'ry-wc-city-select'),
		_x('Malate', 'CADI', 'ry-wc-city-select'),
		_x('Paco', 'CADI', 'ry-wc-city-select'),
		_x('Pandacan', 'CADI', 'ry-wc-city-select'),
		_x('Port Area', 'CADI', 'ry-wc-city-select'),
		_x('Quiapo', 'CADI', 'ry-wc-city-select'),
		_x('Sampaloc', 'CADI', 'ry-wc-city-select'),
		_x('San Miguel', 'CADI', 'ry-wc-city-select'),
		_x('San Nicolas', 'CADI', 'ry-wc-city-select'),
		_x('Santa Ana', 'CADI', 'ry-wc-city-select'),
		_x('Santa Cruz', 'CADI', 'ry-wc-city-select'),
		_x('Tondo I / Ii', 'CADI', 'ry-wc-city-select'),
	],
	'COVA' => [
		_x('Compostela', 'COVA', 'ry-wc-city-select'),
		_x('Laak (San Vicente)', 'COVA', 'ry-wc-city-select'),
		_x('Mabini (Dona Alicia)', 'COVA', 'ry-wc-city-select'),
		_x('Maco', 'COVA', 'ry-wc-city-select'),
		_x('Maragusan (San Mariano)', 'COVA', 'ry-wc-city-select'),
		_x('Mawab', 'COVA', 'ry-wc-city-select'),
		_x('Monkayo', 'COVA', 'ry-wc-city-select'),
		_x('Montevista', 'COVA', 'ry-wc-city-select'),
		_x('Nabunturan', 'COVA', 'ry-wc-city-select'),
		_x('New Bataan', 'COVA', 'ry-wc-city-select'),
		_x('Pantukan', 'COVA', 'ry-wc-city-select'),
	],
	'DAOC' => [
		_x('Don Marcelino', 'DAOC', 'ry-wc-city-select'),
		_x('Jose Abad Santos (Trinidad)', 'DAOC', 'ry-wc-city-select'),
		_x('Malita', 'DAOC', 'ry-wc-city-select'),
		_x('Santa Maria', 'DAOC', 'ry-wc-city-select'),
		_x('Sarangani', 'DAOC', 'ry-wc-city-select'),
	],
	'DIIS' => [
		_x('Basilisa (Rizal)', 'DIIS', 'ry-wc-city-select'),
		_x('Cagdianao', 'DIIS', 'ry-wc-city-select'),
		_x('Dinagat', 'DIIS', 'ry-wc-city-select'),
		_x('Libjo (Albor)', 'DIIS', 'ry-wc-city-select'),
		_x('Loreto', 'DIIS', 'ry-wc-city-select'),
		_x('San Jose', 'DIIS', 'ry-wc-city-select'),
		_x('Tubajon', 'DIIS', 'ry-wc-city-select'),
	],
	'EAMADI' => [
		_x('City of Mandaluyong', 'EAMADI', 'ry-wc-city-select'),
		_x('City of Marikina', 'EAMADI', 'ry-wc-city-select'),
		_x('City of Pasig', 'EAMADI', 'ry-wc-city-select'),
		_x('City of San Juan', 'EAMADI', 'ry-wc-city-select'),
		_x('Quezon City', 'EAMADI', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Balbalan', 'KA', 'ry-wc-city-select'),
		_x('City of Tabuk', 'KA', 'ry-wc-city-select'),
		_x('Lubuagan', 'KA', 'ry-wc-city-select'),
		_x('Pasil', 'KA', 'ry-wc-city-select'),
		_x('Pinukpuk', 'KA', 'ry-wc-city-select'),
		_x('Rizal (Liwan)', 'KA', 'ry-wc-city-select'),
		_x('Tanudan', 'KA', 'ry-wc-city-select'),
		_x('Tinglayan', 'KA', 'ry-wc-city-select'),
	],
	'MOPR' => [
		_x('Barlig', 'MOPR', 'ry-wc-city-select'),
		_x('Bauko', 'MOPR', 'ry-wc-city-select'),
		_x('Besao', 'MOPR', 'ry-wc-city-select'),
		_x('Bontoc', 'MOPR', 'ry-wc-city-select'),
		_x('Natonin', 'MOPR', 'ry-wc-city-select'),
		_x('Paracelis', 'MOPR', 'ry-wc-city-select'),
		_x('Sabangan', 'MOPR', 'ry-wc-city-select'),
		_x('Sadanga', 'MOPR', 'ry-wc-city-select'),
		_x('Sagada', 'MOPR', 'ry-wc-city-select'),
		_x('Tadian', 'MOPR', 'ry-wc-city-select'),
	],
	'NOMADI' => [
		_x('Caloocan City', 'NOMADI', 'ry-wc-city-select'),
		_x('City of Malabon', 'NOMADI', 'ry-wc-city-select'),
	],
	'PRZADESU' => [
		_x('Aurora', 'PRZADESU', 'ry-wc-city-select'),
		_x('Bayog', 'PRZADESU', 'ry-wc-city-select'),
		_x('Dimataling', 'PRZADESU', 'ry-wc-city-select'),
		_x('Dinas', 'PRZADESU', 'ry-wc-city-select'),
		_x('Dumalinao', 'PRZADESU', 'ry-wc-city-select'),
		_x('Dumingag', 'PRZADESU', 'ry-wc-city-select'),
		_x('Guipos', 'PRZADESU', 'ry-wc-city-select'),
		_x('Josefina', 'PRZADESU', 'ry-wc-city-select'),
		_x('Kumalarang', 'PRZADESU', 'ry-wc-city-select'),
		_x('Labangan', 'PRZADESU', 'ry-wc-city-select'),
		_x('Lakewood', 'PRZADESU', 'ry-wc-city-select'),
		_x('Lapuyan', 'PRZADESU', 'ry-wc-city-select'),
		_x('Mahayag', 'PRZADESU', 'ry-wc-city-select'),
		_x('Margosatubig', 'PRZADESU', 'ry-wc-city-select'),
		_x('Midsalip', 'PRZADESU', 'ry-wc-city-select'),
		_x('Molave', 'PRZADESU', 'ry-wc-city-select'),
		_x('Pagadian City', 'PRZADESU', 'ry-wc-city-select'),
		_x('Pitogo', 'PRZADESU', 'ry-wc-city-select'),
		_x('Ramon Magsaysay (Liargo)', 'PRZADESU', 'ry-wc-city-select'),
		_x('San Miguel', 'PRZADESU', 'ry-wc-city-select'),
		_x('San Pablo', 'PRZADESU', 'ry-wc-city-select'),
		_x('Sominot (Don Mariano Marcos)', 'PRZADESU', 'ry-wc-city-select'),
		_x('Tabina', 'PRZADESU', 'ry-wc-city-select'),
		_x('Tambulig', 'PRZADESU', 'ry-wc-city-select'),
		_x('Tigbao', 'PRZADESU', 'ry-wc-city-select'),
		_x('Tukuran', 'PRZADESU', 'ry-wc-city-select'),
		_x('Vincenzo A. Sagun', 'PRZADESU', 'ry-wc-city-select'),
		_x('Zamboanga City', 'PRZADESU', 'ry-wc-city-select'),
	],
	'PRAB' => [
		_x('Bangued', 'PRAB', 'ry-wc-city-select'),
		_x('Boliney', 'PRAB', 'ry-wc-city-select'),
		_x('Bucay', 'PRAB', 'ry-wc-city-select'),
		_x('Bucloc', 'PRAB', 'ry-wc-city-select'),
		_x('Daguioman', 'PRAB', 'ry-wc-city-select'),
		_x('Danglas', 'PRAB', 'ry-wc-city-select'),
		_x('Dolores', 'PRAB', 'ry-wc-city-select'),
		_x('La Paz', 'PRAB', 'ry-wc-city-select'),
		_x('Lacub', 'PRAB', 'ry-wc-city-select'),
		_x('Lagangilang', 'PRAB', 'ry-wc-city-select'),
		_x('Lagayan', 'PRAB', 'ry-wc-city-select'),
		_x('Langiden', 'PRAB', 'ry-wc-city-select'),
		_x('Licuan-Baay (Licuan)', 'PRAB', 'ry-wc-city-select'),
		_x('Luba', 'PRAB', 'ry-wc-city-select'),
		_x('Malibcong', 'PRAB', 'ry-wc-city-select'),
		_x('Manabo', 'PRAB', 'ry-wc-city-select'),
		_x('Penarrubia', 'PRAB', 'ry-wc-city-select'),
		_x('Pidigan', 'PRAB', 'ry-wc-city-select'),
		_x('Pilar', 'PRAB', 'ry-wc-city-select'),
		_x('Sallapadan', 'PRAB', 'ry-wc-city-select'),
		_x('San Isidro', 'PRAB', 'ry-wc-city-select'),
		_x('San Juan', 'PRAB', 'ry-wc-city-select'),
		_x('San Quintin', 'PRAB', 'ry-wc-city-select'),
		_x('Tayum', 'PRAB', 'ry-wc-city-select'),
		_x('Tineg', 'PRAB', 'ry-wc-city-select'),
		_x('Tubo', 'PRAB', 'ry-wc-city-select'),
		_x('Villaviciosa', 'PRAB', 'ry-wc-city-select'),
	],
	'PRAGDENO' => [
		_x('Buenavista', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Butuan City', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Carmen', 'PRAGDENO', 'ry-wc-city-select'),
		_x('City of Cabadbaran', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Jabonga', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Kitcharao', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Las Nieves', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Magallanes', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Nasipit', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Remedios T. Romualdez', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Santiago', 'PRAGDENO', 'ry-wc-city-select'),
		_x('Tubay', 'PRAGDENO', 'ry-wc-city-select'),
	],
	'PRAGDESU' => [
		_x('Bunawan', 'PRAGDESU', 'ry-wc-city-select'),
		_x('City of Bayugan', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Esperanza', 'PRAGDESU', 'ry-wc-city-select'),
		_x('La Paz', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Loreto', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Prosperidad', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Rosario', 'PRAGDESU', 'ry-wc-city-select'),
		_x('San Francisco', 'PRAGDESU', 'ry-wc-city-select'),
		_x('San Luis', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Santa Josefa', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Sibagat', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Talacogon', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Trento', 'PRAGDESU', 'ry-wc-city-select'),
		_x('Veruela', 'PRAGDESU', 'ry-wc-city-select'),
	],
	'PRAK' => [
		_x('Altavas', 'PRAK', 'ry-wc-city-select'),
		_x('Balete', 'PRAK', 'ry-wc-city-select'),
		_x('Banga', 'PRAK', 'ry-wc-city-select'),
		_x('Batan', 'PRAK', 'ry-wc-city-select'),
		_x('Buruanga', 'PRAK', 'ry-wc-city-select'),
		_x('Ibajay', 'PRAK', 'ry-wc-city-select'),
		_x('Kalibo', 'PRAK', 'ry-wc-city-select'),
		_x('Lezo', 'PRAK', 'ry-wc-city-select'),
		_x('Libacao', 'PRAK', 'ry-wc-city-select'),
		_x('Madalag', 'PRAK', 'ry-wc-city-select'),
		_x('Makato', 'PRAK', 'ry-wc-city-select'),
		_x('Malay', 'PRAK', 'ry-wc-city-select'),
		_x('Malinao', 'PRAK', 'ry-wc-city-select'),
		_x('Nabas', 'PRAK', 'ry-wc-city-select'),
		_x('New Washington', 'PRAK', 'ry-wc-city-select'),
		_x('Numancia', 'PRAK', 'ry-wc-city-select'),
		_x('Tangalan', 'PRAK', 'ry-wc-city-select'),
	],
	'PRAL' => [
		_x('Bacacay', 'PRAL', 'ry-wc-city-select'),
		_x('Camalig', 'PRAL', 'ry-wc-city-select'),
		_x('City of Ligao', 'PRAL', 'ry-wc-city-select'),
		_x('City of Tabaco', 'PRAL', 'ry-wc-city-select'),
		_x('Daraga (Locsin)', 'PRAL', 'ry-wc-city-select'),
		_x('Guinobatan', 'PRAL', 'ry-wc-city-select'),
		_x('Jovellar', 'PRAL', 'ry-wc-city-select'),
		_x('Legazpi City', 'PRAL', 'ry-wc-city-select'),
		_x('Libon', 'PRAL', 'ry-wc-city-select'),
		_x('Malilipot', 'PRAL', 'ry-wc-city-select'),
		_x('Malinao', 'PRAL', 'ry-wc-city-select'),
		_x('Manito', 'PRAL', 'ry-wc-city-select'),
		_x('Oas', 'PRAL', 'ry-wc-city-select'),
		_x('Pio Duran', 'PRAL', 'ry-wc-city-select'),
		_x('Polangui', 'PRAL', 'ry-wc-city-select'),
		_x('Rapu-Rapu', 'PRAL', 'ry-wc-city-select'),
		_x('Santo Domingo (Libog)', 'PRAL', 'ry-wc-city-select'),
		_x('Tiwi', 'PRAL', 'ry-wc-city-select'),
	],
	'PRAN' => [
		_x('Anini-Y', 'PRAN', 'ry-wc-city-select'),
		_x('Barbaza', 'PRAN', 'ry-wc-city-select'),
		_x('Belison', 'PRAN', 'ry-wc-city-select'),
		_x('Bugasong', 'PRAN', 'ry-wc-city-select'),
		_x('Caluya', 'PRAN', 'ry-wc-city-select'),
		_x('Culasi', 'PRAN', 'ry-wc-city-select'),
		_x('Hamtic', 'PRAN', 'ry-wc-city-select'),
		_x('Laua-An', 'PRAN', 'ry-wc-city-select'),
		_x('Libertad', 'PRAN', 'ry-wc-city-select'),
		_x('Pandan', 'PRAN', 'ry-wc-city-select'),
		_x('Patnongon', 'PRAN', 'ry-wc-city-select'),
		_x('San Jose', 'PRAN', 'ry-wc-city-select'),
		_x('San Remigio', 'PRAN', 'ry-wc-city-select'),
		_x('Sebaste', 'PRAN', 'ry-wc-city-select'),
		_x('Sibalom', 'PRAN', 'ry-wc-city-select'),
		_x('Tibiao', 'PRAN', 'ry-wc-city-select'),
		_x('Tobias Fornier', 'PRAN', 'ry-wc-city-select'),
		_x('Valderrama', 'PRAN', 'ry-wc-city-select'),
	],
	'PRAU' => [
		_x('Baler', 'PRAU', 'ry-wc-city-select'),
		_x('Casiguran', 'PRAU', 'ry-wc-city-select'),
		_x('Dilasag', 'PRAU', 'ry-wc-city-select'),
		_x('Dinalungan', 'PRAU', 'ry-wc-city-select'),
		_x('Dingalan', 'PRAU', 'ry-wc-city-select'),
		_x('Dipaculao', 'PRAU', 'ry-wc-city-select'),
		_x('Maria Aurora', 'PRAU', 'ry-wc-city-select'),
		_x('San Luis', 'PRAU', 'ry-wc-city-select'),
	],
	'PRBA' => [
		_x('Akbar', 'PRBA', 'ry-wc-city-select'),
		_x('Al-Barka', 'PRBA', 'ry-wc-city-select'),
		_x('City of Isabela', 'PRBA', 'ry-wc-city-select'),
		_x('City of Lamitan', 'PRBA', 'ry-wc-city-select'),
		_x('Hadji Mohammad Ajul', 'PRBA', 'ry-wc-city-select'),
		_x('Hadji Muhtamad', 'PRBA', 'ry-wc-city-select'),
		_x('Lantawan', 'PRBA', 'ry-wc-city-select'),
		_x('Maluso', 'PRBA', 'ry-wc-city-select'),
		_x('Sumisip', 'PRBA', 'ry-wc-city-select'),
		_x('Tabuan-Lasa', 'PRBA', 'ry-wc-city-select'),
		_x('Tipo-Tipo', 'PRBA', 'ry-wc-city-select'),
		_x('Tuburan', 'PRBA', 'ry-wc-city-select'),
		_x('Ungkaya Pukan', 'PRBA', 'ry-wc-city-select'),
	],
	'PRBA2' => [
		_x('Abucay', 'PRBA2', 'ry-wc-city-select'),
		_x('Bagac', 'PRBA2', 'ry-wc-city-select'),
		_x('City of Balanga', 'PRBA2', 'ry-wc-city-select'),
		_x('Dinalupihan', 'PRBA2', 'ry-wc-city-select'),
		_x('Hermosa', 'PRBA2', 'ry-wc-city-select'),
		_x('Limay', 'PRBA2', 'ry-wc-city-select'),
		_x('Mariveles', 'PRBA2', 'ry-wc-city-select'),
		_x('Morong', 'PRBA2', 'ry-wc-city-select'),
		_x('Orani', 'PRBA2', 'ry-wc-city-select'),
		_x('Orion', 'PRBA2', 'ry-wc-city-select'),
		_x('Pilar', 'PRBA2', 'ry-wc-city-select'),
		_x('Samal', 'PRBA2', 'ry-wc-city-select'),
	],
	'PRBA3' => [
		_x('Basco', 'PRBA3', 'ry-wc-city-select'),
		_x('Itbayat', 'PRBA3', 'ry-wc-city-select'),
		_x('Ivana', 'PRBA3', 'ry-wc-city-select'),
		_x('Mahatao', 'PRBA3', 'ry-wc-city-select'),
		_x('Sabtang', 'PRBA3', 'ry-wc-city-select'),
		_x('Uyugan', 'PRBA3', 'ry-wc-city-select'),
	],
	'PRBA4' => [
		_x('Agoncillo', 'PRBA4', 'ry-wc-city-select'),
		_x('Alitagtag', 'PRBA4', 'ry-wc-city-select'),
		_x('Balayan', 'PRBA4', 'ry-wc-city-select'),
		_x('Balete', 'PRBA4', 'ry-wc-city-select'),
		_x('Batangas City', 'PRBA4', 'ry-wc-city-select'),
		_x('Bauan', 'PRBA4', 'ry-wc-city-select'),
		_x('Calaca', 'PRBA4', 'ry-wc-city-select'),
		_x('Calatagan', 'PRBA4', 'ry-wc-city-select'),
		_x('City of Tanauan', 'PRBA4', 'ry-wc-city-select'),
		_x('Cuenca', 'PRBA4', 'ry-wc-city-select'),
		_x('Ibaan', 'PRBA4', 'ry-wc-city-select'),
		_x('Laurel', 'PRBA4', 'ry-wc-city-select'),
		_x('Lemery', 'PRBA4', 'ry-wc-city-select'),
		_x('Lian', 'PRBA4', 'ry-wc-city-select'),
		_x('Lipa City', 'PRBA4', 'ry-wc-city-select'),
		_x('Lobo', 'PRBA4', 'ry-wc-city-select'),
		_x('Mabini', 'PRBA4', 'ry-wc-city-select'),
		_x('Malvar', 'PRBA4', 'ry-wc-city-select'),
		_x('Mataasnakahoy', 'PRBA4', 'ry-wc-city-select'),
		_x('Nasugbu', 'PRBA4', 'ry-wc-city-select'),
		_x('Padre Garcia', 'PRBA4', 'ry-wc-city-select'),
		_x('Rosario', 'PRBA4', 'ry-wc-city-select'),
		_x('San Jose', 'PRBA4', 'ry-wc-city-select'),
		_x('San Juan', 'PRBA4', 'ry-wc-city-select'),
		_x('San Luis', 'PRBA4', 'ry-wc-city-select'),
		_x('San Nicolas', 'PRBA4', 'ry-wc-city-select'),
		_x('San Pascual', 'PRBA4', 'ry-wc-city-select'),
		_x('Santa Teresita', 'PRBA4', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRBA4', 'ry-wc-city-select'),
		_x('Taal', 'PRBA4', 'ry-wc-city-select'),
		_x('Talisay', 'PRBA4', 'ry-wc-city-select'),
		_x('Taysan', 'PRBA4', 'ry-wc-city-select'),
		_x('Tingloy', 'PRBA4', 'ry-wc-city-select'),
		_x('Tuy', 'PRBA4', 'ry-wc-city-select'),
	],
	'PRBE' => [
		_x('Atok', 'PRBE', 'ry-wc-city-select'),
		_x('Baguio City', 'PRBE', 'ry-wc-city-select'),
		_x('Bakun', 'PRBE', 'ry-wc-city-select'),
		_x('Bokod', 'PRBE', 'ry-wc-city-select'),
		_x('Buguias', 'PRBE', 'ry-wc-city-select'),
		_x('Itogon', 'PRBE', 'ry-wc-city-select'),
		_x('Kabayan', 'PRBE', 'ry-wc-city-select'),
		_x('Kapangan', 'PRBE', 'ry-wc-city-select'),
		_x('Kibungan', 'PRBE', 'ry-wc-city-select'),
		_x('La Trinidad', 'PRBE', 'ry-wc-city-select'),
		_x('Mankayan', 'PRBE', 'ry-wc-city-select'),
		_x('Sablan', 'PRBE', 'ry-wc-city-select'),
		_x('Tuba', 'PRBE', 'ry-wc-city-select'),
		_x('Tublay', 'PRBE', 'ry-wc-city-select'),
	],
	'PRBU' => [
		_x('Baungon', 'PRBU', 'ry-wc-city-select'),
		_x('Cabanglasan', 'PRBU', 'ry-wc-city-select'),
		_x('City of Malaybalay', 'PRBU', 'ry-wc-city-select'),
		_x('City of Valencia', 'PRBU', 'ry-wc-city-select'),
		_x('Damulog', 'PRBU', 'ry-wc-city-select'),
		_x('Dangcagan', 'PRBU', 'ry-wc-city-select'),
		_x('Don Carlos', 'PRBU', 'ry-wc-city-select'),
		_x('Impasug-Ong', 'PRBU', 'ry-wc-city-select'),
		_x('Kadingilan', 'PRBU', 'ry-wc-city-select'),
		_x('Kalilangan', 'PRBU', 'ry-wc-city-select'),
		_x('Kibawe', 'PRBU', 'ry-wc-city-select'),
		_x('Kitaotao', 'PRBU', 'ry-wc-city-select'),
		_x('Lantapan', 'PRBU', 'ry-wc-city-select'),
		_x('Libona', 'PRBU', 'ry-wc-city-select'),
		_x('Malitbog', 'PRBU', 'ry-wc-city-select'),
		_x('Manolo Fortich', 'PRBU', 'ry-wc-city-select'),
		_x('Maramag', 'PRBU', 'ry-wc-city-select'),
		_x('Pangantucan', 'PRBU', 'ry-wc-city-select'),
		_x('Quezon', 'PRBU', 'ry-wc-city-select'),
		_x('San Fernando', 'PRBU', 'ry-wc-city-select'),
		_x('Sumilao', 'PRBU', 'ry-wc-city-select'),
		_x('Talakag', 'PRBU', 'ry-wc-city-select'),
	],
	'PRBU2' => [
		_x('Angat', 'PRBU2', 'ry-wc-city-select'),
		_x('Balagtas (Bigaa)', 'PRBU2', 'ry-wc-city-select'),
		_x('Baliuag', 'PRBU2', 'ry-wc-city-select'),
		_x('Bocaue', 'PRBU2', 'ry-wc-city-select'),
		_x('Bulacan', 'PRBU2', 'ry-wc-city-select'),
		_x('Bustos', 'PRBU2', 'ry-wc-city-select'),
		_x('Calumpit', 'PRBU2', 'ry-wc-city-select'),
		_x('City of Malolos', 'PRBU2', 'ry-wc-city-select'),
		_x('City of Meycauayan', 'PRBU2', 'ry-wc-city-select'),
		_x('City of San Jose Del Monte', 'PRBU2', 'ry-wc-city-select'),
		_x('Dona Remedios Trinidad', 'PRBU2', 'ry-wc-city-select'),
		_x('Guiguinto', 'PRBU2', 'ry-wc-city-select'),
		_x('Hagonoy', 'PRBU2', 'ry-wc-city-select'),
		_x('Marilao', 'PRBU2', 'ry-wc-city-select'),
		_x('Norzagaray', 'PRBU2', 'ry-wc-city-select'),
		_x('Obando', 'PRBU2', 'ry-wc-city-select'),
		_x('Pandi', 'PRBU2', 'ry-wc-city-select'),
		_x('Paombong', 'PRBU2', 'ry-wc-city-select'),
		_x('Plaridel', 'PRBU2', 'ry-wc-city-select'),
		_x('Pulilan', 'PRBU2', 'ry-wc-city-select'),
		_x('San Ildefonso', 'PRBU2', 'ry-wc-city-select'),
		_x('San Miguel', 'PRBU2', 'ry-wc-city-select'),
		_x('San Rafael', 'PRBU2', 'ry-wc-city-select'),
		_x('Santa Maria', 'PRBU2', 'ry-wc-city-select'),
	],
	'PRCA' => [
		_x('Abulug', 'PRCA', 'ry-wc-city-select'),
		_x('Alcala', 'PRCA', 'ry-wc-city-select'),
		_x('Allacapan', 'PRCA', 'ry-wc-city-select'),
		_x('Amulung', 'PRCA', 'ry-wc-city-select'),
		_x('Aparri', 'PRCA', 'ry-wc-city-select'),
		_x('Baggao', 'PRCA', 'ry-wc-city-select'),
		_x('Ballesteros', 'PRCA', 'ry-wc-city-select'),
		_x('Buguey', 'PRCA', 'ry-wc-city-select'),
		_x('Calayan', 'PRCA', 'ry-wc-city-select'),
		_x('Camalaniugan', 'PRCA', 'ry-wc-city-select'),
		_x('Claveria', 'PRCA', 'ry-wc-city-select'),
		_x('Enrile', 'PRCA', 'ry-wc-city-select'),
		_x('Gattaran', 'PRCA', 'ry-wc-city-select'),
		_x('Gonzaga', 'PRCA', 'ry-wc-city-select'),
		_x('Iguig', 'PRCA', 'ry-wc-city-select'),
		_x('Lal-Lo', 'PRCA', 'ry-wc-city-select'),
		_x('Lasam', 'PRCA', 'ry-wc-city-select'),
		_x('Pamplona', 'PRCA', 'ry-wc-city-select'),
		_x('Penablanca', 'PRCA', 'ry-wc-city-select'),
		_x('Piat', 'PRCA', 'ry-wc-city-select'),
		_x('Rizal', 'PRCA', 'ry-wc-city-select'),
		_x('Sanchez-Mira', 'PRCA', 'ry-wc-city-select'),
		_x('Santa Ana', 'PRCA', 'ry-wc-city-select'),
		_x('Santa Praxedes', 'PRCA', 'ry-wc-city-select'),
		_x('Santa Teresita', 'PRCA', 'ry-wc-city-select'),
		_x('Santo Nino (Faire)', 'PRCA', 'ry-wc-city-select'),
		_x('Solana', 'PRCA', 'ry-wc-city-select'),
		_x('Tuao', 'PRCA', 'ry-wc-city-select'),
		_x('Tuguegarao City', 'PRCA', 'ry-wc-city-select'),
	],
	'PRCANO' => [
		_x('Basud', 'PRCANO', 'ry-wc-city-select'),
		_x('Capalonga', 'PRCANO', 'ry-wc-city-select'),
		_x('Daet', 'PRCANO', 'ry-wc-city-select'),
		_x('Jose Panganiban', 'PRCANO', 'ry-wc-city-select'),
		_x('Labo', 'PRCANO', 'ry-wc-city-select'),
		_x('Mercedes', 'PRCANO', 'ry-wc-city-select'),
		_x('Paracale', 'PRCANO', 'ry-wc-city-select'),
		_x('San Lorenzo Ruiz (Imelda)', 'PRCANO', 'ry-wc-city-select'),
		_x('San Vicente', 'PRCANO', 'ry-wc-city-select'),
		_x('Santa Elena', 'PRCANO', 'ry-wc-city-select'),
		_x('Talisay', 'PRCANO', 'ry-wc-city-select'),
		_x('Vinzons', 'PRCANO', 'ry-wc-city-select'),
	],
	'PRCASU' => [
		_x('Baao', 'PRCASU', 'ry-wc-city-select'),
		_x('Balatan', 'PRCASU', 'ry-wc-city-select'),
		_x('Bato', 'PRCASU', 'ry-wc-city-select'),
		_x('Bombon', 'PRCASU', 'ry-wc-city-select'),
		_x('Buhi', 'PRCASU', 'ry-wc-city-select'),
		_x('Bula', 'PRCASU', 'ry-wc-city-select'),
		_x('Cabusao', 'PRCASU', 'ry-wc-city-select'),
		_x('Calabanga', 'PRCASU', 'ry-wc-city-select'),
		_x('Camaligan', 'PRCASU', 'ry-wc-city-select'),
		_x('Canaman', 'PRCASU', 'ry-wc-city-select'),
		_x('Caramoan', 'PRCASU', 'ry-wc-city-select'),
		_x('Del Gallego', 'PRCASU', 'ry-wc-city-select'),
		_x('Gainza', 'PRCASU', 'ry-wc-city-select'),
		_x('Garchitorena', 'PRCASU', 'ry-wc-city-select'),
		_x('Goa', 'PRCASU', 'ry-wc-city-select'),
		_x('Iriga City', 'PRCASU', 'ry-wc-city-select'),
		_x('Lagonoy', 'PRCASU', 'ry-wc-city-select'),
		_x('Libmanan', 'PRCASU', 'ry-wc-city-select'),
		_x('Lupi', 'PRCASU', 'ry-wc-city-select'),
		_x('Magarao', 'PRCASU', 'ry-wc-city-select'),
		_x('Milaor', 'PRCASU', 'ry-wc-city-select'),
		_x('Minalabac', 'PRCASU', 'ry-wc-city-select'),
		_x('Nabua', 'PRCASU', 'ry-wc-city-select'),
		_x('Naga City', 'PRCASU', 'ry-wc-city-select'),
		_x('Ocampo', 'PRCASU', 'ry-wc-city-select'),
		_x('Pamplona', 'PRCASU', 'ry-wc-city-select'),
		_x('Pasacao', 'PRCASU', 'ry-wc-city-select'),
		_x('Pili', 'PRCASU', 'ry-wc-city-select'),
		_x('Presentacion (Parubcan)', 'PRCASU', 'ry-wc-city-select'),
		_x('Ragay', 'PRCASU', 'ry-wc-city-select'),
		_x('Sagnay', 'PRCASU', 'ry-wc-city-select'),
		_x('San Fernando', 'PRCASU', 'ry-wc-city-select'),
		_x('San Jose', 'PRCASU', 'ry-wc-city-select'),
		_x('Sipocot', 'PRCASU', 'ry-wc-city-select'),
		_x('Siruma', 'PRCASU', 'ry-wc-city-select'),
		_x('Tigaon', 'PRCASU', 'ry-wc-city-select'),
		_x('Tinambac', 'PRCASU', 'ry-wc-city-select'),
	],
	'PRCA2' => [
		_x('Catarman', 'PRCA2', 'ry-wc-city-select'),
		_x('Guinsiliban', 'PRCA2', 'ry-wc-city-select'),
		_x('Mahinog', 'PRCA2', 'ry-wc-city-select'),
		_x('Mambajao', 'PRCA2', 'ry-wc-city-select'),
		_x('Sagay', 'PRCA2', 'ry-wc-city-select'),
	],
	'PRCA3' => [
		_x('Cuartero', 'PRCA3', 'ry-wc-city-select'),
		_x('Dao', 'PRCA3', 'ry-wc-city-select'),
		_x('Dumalag', 'PRCA3', 'ry-wc-city-select'),
		_x('Dumarao', 'PRCA3', 'ry-wc-city-select'),
		_x('Ivisan', 'PRCA3', 'ry-wc-city-select'),
		_x('Jamindan', 'PRCA3', 'ry-wc-city-select'),
		_x('Ma-Ayon', 'PRCA3', 'ry-wc-city-select'),
		_x('Mambusao', 'PRCA3', 'ry-wc-city-select'),
		_x('Panay', 'PRCA3', 'ry-wc-city-select'),
		_x('Panitan', 'PRCA3', 'ry-wc-city-select'),
		_x('Pilar', 'PRCA3', 'ry-wc-city-select'),
		_x('Pontevedra', 'PRCA3', 'ry-wc-city-select'),
		_x('President Roxas', 'PRCA3', 'ry-wc-city-select'),
		_x('Roxas City', 'PRCA3', 'ry-wc-city-select'),
		_x('Sapi-An', 'PRCA3', 'ry-wc-city-select'),
		_x('Sigma', 'PRCA3', 'ry-wc-city-select'),
		_x('Tapaz', 'PRCA3', 'ry-wc-city-select'),
	],
	'PRCA4' => [
		_x('Bagamanoc', 'PRCA4', 'ry-wc-city-select'),
		_x('Baras', 'PRCA4', 'ry-wc-city-select'),
		_x('Bato', 'PRCA4', 'ry-wc-city-select'),
		_x('Caramoran', 'PRCA4', 'ry-wc-city-select'),
		_x('Gigmoto', 'PRCA4', 'ry-wc-city-select'),
		_x('Pandan', 'PRCA4', 'ry-wc-city-select'),
		_x('Panganiban (Payo)', 'PRCA4', 'ry-wc-city-select'),
		_x('San Andres (Calolbon)', 'PRCA4', 'ry-wc-city-select'),
		_x('San Miguel', 'PRCA4', 'ry-wc-city-select'),
		_x('Viga', 'PRCA4', 'ry-wc-city-select'),
		_x('Virac', 'PRCA4', 'ry-wc-city-select'),
	],
	'PRCA5' => [
		_x('Alfonso', 'PRCA5', 'ry-wc-city-select'),
		_x('Amadeo', 'PRCA5', 'ry-wc-city-select'),
		_x('Bacoor City', 'PRCA5', 'ry-wc-city-select'),
		_x('Carmona', 'PRCA5', 'ry-wc-city-select'),
		_x('Cavite', 'PRCA5', 'ry-wc-city-select'),
		_x('City of Dasmarinas', 'PRCA5', 'ry-wc-city-select'),
		_x('City of General Trias', 'PRCA5', 'ry-wc-city-select'),
		_x('Gen. Mariano Alvarez', 'PRCA5', 'ry-wc-city-select'),
		_x('General Emilio Aguinaldo', 'PRCA5', 'ry-wc-city-select'),
		_x('Imus City', 'PRCA5', 'ry-wc-city-select'),
		_x('Indang', 'PRCA5', 'ry-wc-city-select'),
		_x('Kawit', 'PRCA5', 'ry-wc-city-select'),
		_x('Magallanes', 'PRCA5', 'ry-wc-city-select'),
		_x('Maragondon', 'PRCA5', 'ry-wc-city-select'),
		_x('Mendez (Mendez-Nunez)', 'PRCA5', 'ry-wc-city-select'),
		_x('Naic', 'PRCA5', 'ry-wc-city-select'),
		_x('Noveleta', 'PRCA5', 'ry-wc-city-select'),
		_x('Rosario', 'PRCA5', 'ry-wc-city-select'),
		_x('Silang', 'PRCA5', 'ry-wc-city-select'),
		_x('Tagaytay City', 'PRCA5', 'ry-wc-city-select'),
		_x('Tanza', 'PRCA5', 'ry-wc-city-select'),
		_x('Ternate', 'PRCA5', 'ry-wc-city-select'),
		_x('Trece Martires City', 'PRCA5', 'ry-wc-city-select'),
	],
	'PRCE' => [
		_x('Alcantara', 'PRCE', 'ry-wc-city-select'),
		_x('Alcoy', 'PRCE', 'ry-wc-city-select'),
		_x('Alegria', 'PRCE', 'ry-wc-city-select'),
		_x('Aloguinsan', 'PRCE', 'ry-wc-city-select'),
		_x('Argao', 'PRCE', 'ry-wc-city-select'),
		_x('Asturias', 'PRCE', 'ry-wc-city-select'),
		_x('Badian', 'PRCE', 'ry-wc-city-select'),
		_x('Balamban', 'PRCE', 'ry-wc-city-select'),
		_x('Bantayan', 'PRCE', 'ry-wc-city-select'),
		_x('Barili', 'PRCE', 'ry-wc-city-select'),
		_x('Boljoon', 'PRCE', 'ry-wc-city-select'),
		_x('Borbon', 'PRCE', 'ry-wc-city-select'),
		_x('Carmen', 'PRCE', 'ry-wc-city-select'),
		_x('Catmon', 'PRCE', 'ry-wc-city-select'),
		_x('Cebu City', 'PRCE', 'ry-wc-city-select'),
		_x('City of Bogo', 'PRCE', 'ry-wc-city-select'),
		_x('City of Carcar', 'PRCE', 'ry-wc-city-select'),
		_x('City of Naga', 'PRCE', 'ry-wc-city-select'),
		_x('City of Talisay', 'PRCE', 'ry-wc-city-select'),
		_x('Compostela', 'PRCE', 'ry-wc-city-select'),
		_x('Consolacion', 'PRCE', 'ry-wc-city-select'),
		_x('Cordova', 'PRCE', 'ry-wc-city-select'),
		_x('Daanbantayan', 'PRCE', 'ry-wc-city-select'),
		_x('Dalaguete', 'PRCE', 'ry-wc-city-select'),
		_x('Danao City', 'PRCE', 'ry-wc-city-select'),
		_x('Dumanjug', 'PRCE', 'ry-wc-city-select'),
		_x('Ginatilan', 'PRCE', 'ry-wc-city-select'),
		_x('Lapu-Lapu City (Opon)', 'PRCE', 'ry-wc-city-select'),
		_x('Liloan', 'PRCE', 'ry-wc-city-select'),
		_x('Madridejos', 'PRCE', 'ry-wc-city-select'),
		_x('Malabuyoc', 'PRCE', 'ry-wc-city-select'),
		_x('Mandaue City', 'PRCE', 'ry-wc-city-select'),
		_x('Medellin', 'PRCE', 'ry-wc-city-select'),
		_x('Minglanilla', 'PRCE', 'ry-wc-city-select'),
		_x('Moalboal', 'PRCE', 'ry-wc-city-select'),
		_x('Oslob', 'PRCE', 'ry-wc-city-select'),
		_x('Pilar', 'PRCE', 'ry-wc-city-select'),
		_x('Pinamungahan', 'PRCE', 'ry-wc-city-select'),
		_x('Poro', 'PRCE', 'ry-wc-city-select'),
		_x('Ronda', 'PRCE', 'ry-wc-city-select'),
		_x('Samboan', 'PRCE', 'ry-wc-city-select'),
		_x('San Fernando', 'PRCE', 'ry-wc-city-select'),
		_x('San Francisco', 'PRCE', 'ry-wc-city-select'),
		_x('San Remigio', 'PRCE', 'ry-wc-city-select'),
		_x('Santa Fe', 'PRCE', 'ry-wc-city-select'),
		_x('Santander', 'PRCE', 'ry-wc-city-select'),
		_x('Sibonga', 'PRCE', 'ry-wc-city-select'),
		_x('Sogod', 'PRCE', 'ry-wc-city-select'),
		_x('Tabogon', 'PRCE', 'ry-wc-city-select'),
		_x('Tabuelan', 'PRCE', 'ry-wc-city-select'),
		_x('Toledo City', 'PRCE', 'ry-wc-city-select'),
		_x('Tuburan', 'PRCE', 'ry-wc-city-select'),
		_x('Tudela', 'PRCE', 'ry-wc-city-select'),
	],
	'PRCO' => [
		_x('Alamada', 'PRCO', 'ry-wc-city-select'),
		_x('Aleosan', 'PRCO', 'ry-wc-city-select'),
		_x('Antipas', 'PRCO', 'ry-wc-city-select'),
		_x('Arakan', 'PRCO', 'ry-wc-city-select'),
		_x('Banisilan', 'PRCO', 'ry-wc-city-select'),
		_x('Carmen', 'PRCO', 'ry-wc-city-select'),
		_x('City of Kidapawan', 'PRCO', 'ry-wc-city-select'),
		_x('Kabacan', 'PRCO', 'ry-wc-city-select'),
		_x('Libungan', 'PRCO', 'ry-wc-city-select'),
		_x('MLang', 'PRCO', 'ry-wc-city-select'),
		_x('Magpet', 'PRCO', 'ry-wc-city-select'),
		_x('Makilala', 'PRCO', 'ry-wc-city-select'),
		_x('Matalam', 'PRCO', 'ry-wc-city-select'),
		_x('Midsayap', 'PRCO', 'ry-wc-city-select'),
		_x('Pigkawayan', 'PRCO', 'ry-wc-city-select'),
		_x('Pikit', 'PRCO', 'ry-wc-city-select'),
		_x('President Roxas', 'PRCO', 'ry-wc-city-select'),
		_x('Tulunan', 'PRCO', 'ry-wc-city-select'),
	],
	'PRDAOR' => [
		_x('Baganga', 'PRDAOR', 'ry-wc-city-select'),
		_x('Banaybanay', 'PRDAOR', 'ry-wc-city-select'),
		_x('Boston', 'PRDAOR', 'ry-wc-city-select'),
		_x('Caraga', 'PRDAOR', 'ry-wc-city-select'),
		_x('Cateel', 'PRDAOR', 'ry-wc-city-select'),
		_x('City of Mati', 'PRDAOR', 'ry-wc-city-select'),
		_x('Governor Generoso', 'PRDAOR', 'ry-wc-city-select'),
		_x('Lupon', 'PRDAOR', 'ry-wc-city-select'),
		_x('Manay', 'PRDAOR', 'ry-wc-city-select'),
		_x('San Isidro', 'PRDAOR', 'ry-wc-city-select'),
		_x('Tarragona', 'PRDAOR', 'ry-wc-city-select'),
	],
	'PRDADENO' => [
		_x('Asuncion (Saug)', 'PRDADENO', 'ry-wc-city-select'),
		_x('Braulio E. Dujali', 'PRDADENO', 'ry-wc-city-select'),
		_x('Carmen', 'PRDADENO', 'ry-wc-city-select'),
		_x('City of Panabo', 'PRDADENO', 'ry-wc-city-select'),
		_x('City of Tagum', 'PRDADENO', 'ry-wc-city-select'),
		_x('Island Garden City of Samal', 'PRDADENO', 'ry-wc-city-select'),
		_x('Kapalong', 'PRDADENO', 'ry-wc-city-select'),
		_x('New Corella', 'PRDADENO', 'ry-wc-city-select'),
		_x('San Isidro', 'PRDADENO', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRDADENO', 'ry-wc-city-select'),
		_x('Talaingod', 'PRDADENO', 'ry-wc-city-select'),
	],
	'PRDADESU' => [
		_x('Bansalan', 'PRDADESU', 'ry-wc-city-select'),
		_x('City of Digos', 'PRDADESU', 'ry-wc-city-select'),
		_x('Davao City', 'PRDADESU', 'ry-wc-city-select'),
		_x('Hagonoy', 'PRDADESU', 'ry-wc-city-select'),
		_x('Kiblawan', 'PRDADESU', 'ry-wc-city-select'),
		_x('Magsaysay', 'PRDADESU', 'ry-wc-city-select'),
		_x('Malalag', 'PRDADESU', 'ry-wc-city-select'),
		_x('Matanao', 'PRDADESU', 'ry-wc-city-select'),
		_x('Padada', 'PRDADESU', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRDADESU', 'ry-wc-city-select'),
		_x('Sulop', 'PRDADESU', 'ry-wc-city-select'),
	],
	'PREASA' => [
		_x('Arteche', 'PREASA', 'ry-wc-city-select'),
		_x('Balangiga', 'PREASA', 'ry-wc-city-select'),
		_x('Balangkayan', 'PREASA', 'ry-wc-city-select'),
		_x('Can-Avid', 'PREASA', 'ry-wc-city-select'),
		_x('City of Borongan', 'PREASA', 'ry-wc-city-select'),
		_x('Dolores', 'PREASA', 'ry-wc-city-select'),
		_x('General Macarthur', 'PREASA', 'ry-wc-city-select'),
		_x('Giporlos', 'PREASA', 'ry-wc-city-select'),
		_x('Guiuan', 'PREASA', 'ry-wc-city-select'),
		_x('Hernani', 'PREASA', 'ry-wc-city-select'),
		_x('Jipapad', 'PREASA', 'ry-wc-city-select'),
		_x('Lawaan', 'PREASA', 'ry-wc-city-select'),
		_x('Llorente', 'PREASA', 'ry-wc-city-select'),
		_x('Maslog', 'PREASA', 'ry-wc-city-select'),
		_x('Maydolong', 'PREASA', 'ry-wc-city-select'),
		_x('Mercedes', 'PREASA', 'ry-wc-city-select'),
		_x('Oras', 'PREASA', 'ry-wc-city-select'),
		_x('Quinapondan', 'PREASA', 'ry-wc-city-select'),
		_x('Salcedo', 'PREASA', 'ry-wc-city-select'),
		_x('San Julian', 'PREASA', 'ry-wc-city-select'),
		_x('San Policarpo', 'PREASA', 'ry-wc-city-select'),
		_x('Sulat', 'PREASA', 'ry-wc-city-select'),
		_x('Taft', 'PREASA', 'ry-wc-city-select'),
	],
	'PRGU' => [
		_x('Buenavista', 'PRGU', 'ry-wc-city-select'),
		_x('Jordan', 'PRGU', 'ry-wc-city-select'),
		_x('Nueva Valencia', 'PRGU', 'ry-wc-city-select'),
		_x('San Lorenzo', 'PRGU', 'ry-wc-city-select'),
		_x('Sibunag', 'PRGU', 'ry-wc-city-select'),
	],
	'PRIF' => [
		_x('Aguinaldo', 'PRIF', 'ry-wc-city-select'),
		_x('Alfonso Lista (Potia)', 'PRIF', 'ry-wc-city-select'),
		_x('Asipulo', 'PRIF', 'ry-wc-city-select'),
		_x('Banaue', 'PRIF', 'ry-wc-city-select'),
		_x('Hingyon', 'PRIF', 'ry-wc-city-select'),
		_x('Hungduan', 'PRIF', 'ry-wc-city-select'),
		_x('Kiangan', 'PRIF', 'ry-wc-city-select'),
		_x('Lagawe', 'PRIF', 'ry-wc-city-select'),
		_x('Lamut', 'PRIF', 'ry-wc-city-select'),
		_x('Mayoyao', 'PRIF', 'ry-wc-city-select'),
		_x('Tinoc', 'PRIF', 'ry-wc-city-select'),
	],
	'PRILNO' => [
		_x('Adams', 'PRILNO', 'ry-wc-city-select'),
		_x('Bacarra', 'PRILNO', 'ry-wc-city-select'),
		_x('Badoc', 'PRILNO', 'ry-wc-city-select'),
		_x('Bangui', 'PRILNO', 'ry-wc-city-select'),
		_x('Banna (Espiritu)', 'PRILNO', 'ry-wc-city-select'),
		_x('Burgos', 'PRILNO', 'ry-wc-city-select'),
		_x('Carasi', 'PRILNO', 'ry-wc-city-select'),
		_x('City of Batac', 'PRILNO', 'ry-wc-city-select'),
		_x('Currimao', 'PRILNO', 'ry-wc-city-select'),
		_x('Dingras', 'PRILNO', 'ry-wc-city-select'),
		_x('Dumalneg', 'PRILNO', 'ry-wc-city-select'),
		_x('Laoag City', 'PRILNO', 'ry-wc-city-select'),
		_x('Marcos', 'PRILNO', 'ry-wc-city-select'),
		_x('Nueva Era', 'PRILNO', 'ry-wc-city-select'),
		_x('Pagudpud', 'PRILNO', 'ry-wc-city-select'),
		_x('Paoay', 'PRILNO', 'ry-wc-city-select'),
		_x('Pasuquin', 'PRILNO', 'ry-wc-city-select'),
		_x('Piddig', 'PRILNO', 'ry-wc-city-select'),
		_x('Pinili', 'PRILNO', 'ry-wc-city-select'),
		_x('San Nicolas', 'PRILNO', 'ry-wc-city-select'),
		_x('Sarrat', 'PRILNO', 'ry-wc-city-select'),
		_x('Solsona', 'PRILNO', 'ry-wc-city-select'),
		_x('Vintar', 'PRILNO', 'ry-wc-city-select'),
	],
	'PRILSU' => [
		_x('Alilem', 'PRILSU', 'ry-wc-city-select'),
		_x('Banayoyo', 'PRILSU', 'ry-wc-city-select'),
		_x('Bantay', 'PRILSU', 'ry-wc-city-select'),
		_x('Burgos', 'PRILSU', 'ry-wc-city-select'),
		_x('Cabugao', 'PRILSU', 'ry-wc-city-select'),
		_x('Caoayan', 'PRILSU', 'ry-wc-city-select'),
		_x('Cervantes', 'PRILSU', 'ry-wc-city-select'),
		_x('City of Candon', 'PRILSU', 'ry-wc-city-select'),
		_x('City of Vigan', 'PRILSU', 'ry-wc-city-select'),
		_x('Galimuyod', 'PRILSU', 'ry-wc-city-select'),
		_x('Gregorio Del Pilar (Concepcion)', 'PRILSU', 'ry-wc-city-select'),
		_x('Lidlidda', 'PRILSU', 'ry-wc-city-select'),
		_x('Magsingal', 'PRILSU', 'ry-wc-city-select'),
		_x('Nagbukel', 'PRILSU', 'ry-wc-city-select'),
		_x('Narvacan', 'PRILSU', 'ry-wc-city-select'),
		_x('Quirino (Angkaki)', 'PRILSU', 'ry-wc-city-select'),
		_x('Salcedo (Baugen)', 'PRILSU', 'ry-wc-city-select'),
		_x('San Emilio', 'PRILSU', 'ry-wc-city-select'),
		_x('San Esteban', 'PRILSU', 'ry-wc-city-select'),
		_x('San Ildefonso', 'PRILSU', 'ry-wc-city-select'),
		_x('San Juan (Lapog)', 'PRILSU', 'ry-wc-city-select'),
		_x('San Vicente', 'PRILSU', 'ry-wc-city-select'),
		_x('Santa', 'PRILSU', 'ry-wc-city-select'),
		_x('Santa Catalina', 'PRILSU', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRILSU', 'ry-wc-city-select'),
		_x('Santa Lucia', 'PRILSU', 'ry-wc-city-select'),
		_x('Santa Maria', 'PRILSU', 'ry-wc-city-select'),
		_x('Santiago', 'PRILSU', 'ry-wc-city-select'),
		_x('Santo Domingo', 'PRILSU', 'ry-wc-city-select'),
		_x('Sigay', 'PRILSU', 'ry-wc-city-select'),
		_x('Sinait', 'PRILSU', 'ry-wc-city-select'),
		_x('Sugpon', 'PRILSU', 'ry-wc-city-select'),
		_x('Suyo', 'PRILSU', 'ry-wc-city-select'),
		_x('Tagudin', 'PRILSU', 'ry-wc-city-select'),
	],
	'PRIL' => [
		_x('Ajuy', 'PRIL', 'ry-wc-city-select'),
		_x('Alimodian', 'PRIL', 'ry-wc-city-select'),
		_x('Anilao', 'PRIL', 'ry-wc-city-select'),
		_x('Badiangan', 'PRIL', 'ry-wc-city-select'),
		_x('Balasan', 'PRIL', 'ry-wc-city-select'),
		_x('Banate', 'PRIL', 'ry-wc-city-select'),
		_x('Barotac Nuevo', 'PRIL', 'ry-wc-city-select'),
		_x('Barotac Viejo', 'PRIL', 'ry-wc-city-select'),
		_x('Batad', 'PRIL', 'ry-wc-city-select'),
		_x('Bingawan', 'PRIL', 'ry-wc-city-select'),
		_x('Cabatuan', 'PRIL', 'ry-wc-city-select'),
		_x('Calinog', 'PRIL', 'ry-wc-city-select'),
		_x('Carles', 'PRIL', 'ry-wc-city-select'),
		_x('City of Passi', 'PRIL', 'ry-wc-city-select'),
		_x('Concepcion', 'PRIL', 'ry-wc-city-select'),
		_x('Dingle', 'PRIL', 'ry-wc-city-select'),
		_x('Duenas', 'PRIL', 'ry-wc-city-select'),
		_x('Dumangas', 'PRIL', 'ry-wc-city-select'),
		_x('Estancia', 'PRIL', 'ry-wc-city-select'),
		_x('Guimbal', 'PRIL', 'ry-wc-city-select'),
		_x('Igbaras', 'PRIL', 'ry-wc-city-select'),
		_x('Iloilo City', 'PRIL', 'ry-wc-city-select'),
		_x('Janiuay', 'PRIL', 'ry-wc-city-select'),
		_x('Lambunao', 'PRIL', 'ry-wc-city-select'),
		_x('Leganes', 'PRIL', 'ry-wc-city-select'),
		_x('Lemery', 'PRIL', 'ry-wc-city-select'),
		_x('Leon', 'PRIL', 'ry-wc-city-select'),
		_x('Maasin', 'PRIL', 'ry-wc-city-select'),
		_x('Miagao', 'PRIL', 'ry-wc-city-select'),
		_x('Mina', 'PRIL', 'ry-wc-city-select'),
		_x('New Lucena', 'PRIL', 'ry-wc-city-select'),
		_x('Oton', 'PRIL', 'ry-wc-city-select'),
		_x('Pavia', 'PRIL', 'ry-wc-city-select'),
		_x('Pototan', 'PRIL', 'ry-wc-city-select'),
		_x('San Dionisio', 'PRIL', 'ry-wc-city-select'),
		_x('San Enrique', 'PRIL', 'ry-wc-city-select'),
		_x('San Joaquin', 'PRIL', 'ry-wc-city-select'),
		_x('San Miguel', 'PRIL', 'ry-wc-city-select'),
		_x('San Rafael', 'PRIL', 'ry-wc-city-select'),
		_x('Santa Barbara', 'PRIL', 'ry-wc-city-select'),
		_x('Sara', 'PRIL', 'ry-wc-city-select'),
		_x('Tigbauan', 'PRIL', 'ry-wc-city-select'),
		_x('Tubungan', 'PRIL', 'ry-wc-city-select'),
		_x('Zarraga', 'PRIL', 'ry-wc-city-select'),
	],
	'PRIS' => [
		_x('Alicia', 'PRIS', 'ry-wc-city-select'),
		_x('Angadanan', 'PRIS', 'ry-wc-city-select'),
		_x('Aurora', 'PRIS', 'ry-wc-city-select'),
		_x('Benito Soliven', 'PRIS', 'ry-wc-city-select'),
		_x('Burgos', 'PRIS', 'ry-wc-city-select'),
		_x('Cabagan', 'PRIS', 'ry-wc-city-select'),
		_x('Cabatuan', 'PRIS', 'ry-wc-city-select'),
		_x('City of Cauayan', 'PRIS', 'ry-wc-city-select'),
		_x('City of Santiago', 'PRIS', 'ry-wc-city-select'),
		_x('Cordon', 'PRIS', 'ry-wc-city-select'),
		_x('Delfin Albano', 'PRIS', 'ry-wc-city-select'),
		_x('Dinapigue', 'PRIS', 'ry-wc-city-select'),
		_x('Divilacan', 'PRIS', 'ry-wc-city-select'),
		_x('Echague', 'PRIS', 'ry-wc-city-select'),
		_x('Gamu', 'PRIS', 'ry-wc-city-select'),
		_x('Ilagan City', 'PRIS', 'ry-wc-city-select'),
		_x('Jones', 'PRIS', 'ry-wc-city-select'),
		_x('Luna', 'PRIS', 'ry-wc-city-select'),
		_x('Maconacon', 'PRIS', 'ry-wc-city-select'),
		_x('Mallig', 'PRIS', 'ry-wc-city-select'),
		_x('Naguilian', 'PRIS', 'ry-wc-city-select'),
		_x('Palanan', 'PRIS', 'ry-wc-city-select'),
		_x('Quezon', 'PRIS', 'ry-wc-city-select'),
		_x('Quirino', 'PRIS', 'ry-wc-city-select'),
		_x('Ramon', 'PRIS', 'ry-wc-city-select'),
		_x('Reina Mercedes', 'PRIS', 'ry-wc-city-select'),
		_x('Roxas', 'PRIS', 'ry-wc-city-select'),
		_x('San Agustin', 'PRIS', 'ry-wc-city-select'),
		_x('San Guillermo', 'PRIS', 'ry-wc-city-select'),
		_x('San Isidro', 'PRIS', 'ry-wc-city-select'),
		_x('San Manuel', 'PRIS', 'ry-wc-city-select'),
		_x('San Mariano', 'PRIS', 'ry-wc-city-select'),
		_x('San Mateo', 'PRIS', 'ry-wc-city-select'),
		_x('San Pablo', 'PRIS', 'ry-wc-city-select'),
		_x('Santa Maria', 'PRIS', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRIS', 'ry-wc-city-select'),
		_x('Tumauini', 'PRIS', 'ry-wc-city-select'),
	],
	'PRUN' => [
		_x('Agoo', 'PRUN', 'ry-wc-city-select'),
		_x('Aringay', 'PRUN', 'ry-wc-city-select'),
		_x('Bacnotan', 'PRUN', 'ry-wc-city-select'),
		_x('Bagulin', 'PRUN', 'ry-wc-city-select'),
		_x('Balaoan', 'PRUN', 'ry-wc-city-select'),
		_x('Bangar', 'PRUN', 'ry-wc-city-select'),
		_x('Bauang', 'PRUN', 'ry-wc-city-select'),
		_x('Burgos', 'PRUN', 'ry-wc-city-select'),
		_x('Caba', 'PRUN', 'ry-wc-city-select'),
		_x('City of San Fernando', 'PRUN', 'ry-wc-city-select'),
		_x('Luna', 'PRUN', 'ry-wc-city-select'),
		_x('Naguilian', 'PRUN', 'ry-wc-city-select'),
		_x('Pugo', 'PRUN', 'ry-wc-city-select'),
		_x('Rosario', 'PRUN', 'ry-wc-city-select'),
		_x('San Gabriel', 'PRUN', 'ry-wc-city-select'),
		_x('San Juan', 'PRUN', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRUN', 'ry-wc-city-select'),
		_x('Santol', 'PRUN', 'ry-wc-city-select'),
		_x('Sudipen', 'PRUN', 'ry-wc-city-select'),
		_x('Tubao', 'PRUN', 'ry-wc-city-select'),
	],
	'PRLA' => [
		_x('Alaminos', 'PRLA', 'ry-wc-city-select'),
		_x('Bay', 'PRLA', 'ry-wc-city-select'),
		_x('Cabuyao City', 'PRLA', 'ry-wc-city-select'),
		_x('Calauan', 'PRLA', 'ry-wc-city-select'),
		_x('Cavinti', 'PRLA', 'ry-wc-city-select'),
		_x('City of Binan', 'PRLA', 'ry-wc-city-select'),
		_x('City of Calamba', 'PRLA', 'ry-wc-city-select'),
		_x('City of San Pedro', 'PRLA', 'ry-wc-city-select'),
		_x('City of Santa Rosa', 'PRLA', 'ry-wc-city-select'),
		_x('Famy', 'PRLA', 'ry-wc-city-select'),
		_x('Kalayaan', 'PRLA', 'ry-wc-city-select'),
		_x('Liliw', 'PRLA', 'ry-wc-city-select'),
		_x('Los Banos', 'PRLA', 'ry-wc-city-select'),
		_x('Luisiana', 'PRLA', 'ry-wc-city-select'),
		_x('Lumban', 'PRLA', 'ry-wc-city-select'),
		_x('Mabitac', 'PRLA', 'ry-wc-city-select'),
		_x('Magdalena', 'PRLA', 'ry-wc-city-select'),
		_x('Majayjay', 'PRLA', 'ry-wc-city-select'),
		_x('Nagcarlan', 'PRLA', 'ry-wc-city-select'),
		_x('Paete', 'PRLA', 'ry-wc-city-select'),
		_x('Pagsanjan', 'PRLA', 'ry-wc-city-select'),
		_x('Pakil', 'PRLA', 'ry-wc-city-select'),
		_x('Pangil', 'PRLA', 'ry-wc-city-select'),
		_x('Pila', 'PRLA', 'ry-wc-city-select'),
		_x('Rizal', 'PRLA', 'ry-wc-city-select'),
		_x('San Pablo City', 'PRLA', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRLA', 'ry-wc-city-select'),
		_x('Santa Maria', 'PRLA', 'ry-wc-city-select'),
		_x('Siniloan', 'PRLA', 'ry-wc-city-select'),
		_x('Victoria', 'PRLA', 'ry-wc-city-select'),
	],
	'PRLADENO' => [
		_x('Bacolod', 'PRLADENO', 'ry-wc-city-select'),
		_x('Baloi', 'PRLADENO', 'ry-wc-city-select'),
		_x('Baroy', 'PRLADENO', 'ry-wc-city-select'),
		_x('Iligan City', 'PRLADENO', 'ry-wc-city-select'),
		_x('Kapatagan', 'PRLADENO', 'ry-wc-city-select'),
		_x('Kauswagan', 'PRLADENO', 'ry-wc-city-select'),
		_x('Kolambugan', 'PRLADENO', 'ry-wc-city-select'),
		_x('Lala', 'PRLADENO', 'ry-wc-city-select'),
		_x('Linamon', 'PRLADENO', 'ry-wc-city-select'),
		_x('Magsaysay', 'PRLADENO', 'ry-wc-city-select'),
		_x('Maigo', 'PRLADENO', 'ry-wc-city-select'),
		_x('Matungao', 'PRLADENO', 'ry-wc-city-select'),
		_x('Munai', 'PRLADENO', 'ry-wc-city-select'),
		_x('Nunungan', 'PRLADENO', 'ry-wc-city-select'),
		_x('Pantao Ragat', 'PRLADENO', 'ry-wc-city-select'),
		_x('Pantar', 'PRLADENO', 'ry-wc-city-select'),
		_x('Poona Piagapo', 'PRLADENO', 'ry-wc-city-select'),
		_x('Salvador', 'PRLADENO', 'ry-wc-city-select'),
		_x('Sapad', 'PRLADENO', 'ry-wc-city-select'),
		_x('Sultan Naga Dimaporo (Karomatan)', 'PRLADENO', 'ry-wc-city-select'),
		_x('Tagoloan', 'PRLADENO', 'ry-wc-city-select'),
		_x('Tangcal', 'PRLADENO', 'ry-wc-city-select'),
		_x('Tubod', 'PRLADENO', 'ry-wc-city-select'),
	],
	'PRLADESU' => [
		_x('Bacolod-Kalawi (Bacolod Grande)', 'PRLADESU', 'ry-wc-city-select'),
		_x('Balabagan', 'PRLADESU', 'ry-wc-city-select'),
		_x('Balindong (Watu)', 'PRLADESU', 'ry-wc-city-select'),
		_x('Bayang', 'PRLADESU', 'ry-wc-city-select'),
		_x('Binidayan', 'PRLADESU', 'ry-wc-city-select'),
		_x('Buadiposo-Buntong', 'PRLADESU', 'ry-wc-city-select'),
		_x('Bubong', 'PRLADESU', 'ry-wc-city-select'),
		_x('Bumbaran', 'PRLADESU', 'ry-wc-city-select'),
		_x('Butig', 'PRLADESU', 'ry-wc-city-select'),
		_x('Calanogas', 'PRLADESU', 'ry-wc-city-select'),
		_x('Ditsaan-Ramain', 'PRLADESU', 'ry-wc-city-select'),
		_x('Ganassi', 'PRLADESU', 'ry-wc-city-select'),
		_x('Kapai', 'PRLADESU', 'ry-wc-city-select'),
		_x('Kapatagan', 'PRLADESU', 'ry-wc-city-select'),
		_x('Lumba-Bayabao (Maguing)', 'PRLADESU', 'ry-wc-city-select'),
		_x('Lumbaca-Unayan', 'PRLADESU', 'ry-wc-city-select'),
		_x('Lumbatan', 'PRLADESU', 'ry-wc-city-select'),
		_x('Lumbayanague', 'PRLADESU', 'ry-wc-city-select'),
		_x('Madalum', 'PRLADESU', 'ry-wc-city-select'),
		_x('Madamba', 'PRLADESU', 'ry-wc-city-select'),
		_x('Maguing', 'PRLADESU', 'ry-wc-city-select'),
		_x('Malabang', 'PRLADESU', 'ry-wc-city-select'),
		_x('Marantao', 'PRLADESU', 'ry-wc-city-select'),
		_x('Marawi City', 'PRLADESU', 'ry-wc-city-select'),
		_x('Marogong', 'PRLADESU', 'ry-wc-city-select'),
		_x('Masiu', 'PRLADESU', 'ry-wc-city-select'),
		_x('Mulondo', 'PRLADESU', 'ry-wc-city-select'),
		_x('Pagayawan (Tatarikan)', 'PRLADESU', 'ry-wc-city-select'),
		_x('Piagapo', 'PRLADESU', 'ry-wc-city-select'),
		_x('Picong (Sultan Gumander)', 'PRLADESU', 'ry-wc-city-select'),
		_x('Poona Bayabao (Gata)', 'PRLADESU', 'ry-wc-city-select'),
		_x('Pualas', 'PRLADESU', 'ry-wc-city-select'),
		_x('Saguiaran', 'PRLADESU', 'ry-wc-city-select'),
		_x('Sultan Dumalondong', 'PRLADESU', 'ry-wc-city-select'),
		_x('Tagoloan Ii', 'PRLADESU', 'ry-wc-city-select'),
		_x('Tamparan', 'PRLADESU', 'ry-wc-city-select'),
		_x('Taraka', 'PRLADESU', 'ry-wc-city-select'),
		_x('Tubaran', 'PRLADESU', 'ry-wc-city-select'),
		_x('Tugaya', 'PRLADESU', 'ry-wc-city-select'),
		_x('Wao', 'PRLADESU', 'ry-wc-city-select'),
	],
	'PRLE' => [
		_x('Abuyog', 'PRLE', 'ry-wc-city-select'),
		_x('Alangalang', 'PRLE', 'ry-wc-city-select'),
		_x('Albuera', 'PRLE', 'ry-wc-city-select'),
		_x('Babatngon', 'PRLE', 'ry-wc-city-select'),
		_x('Barugo', 'PRLE', 'ry-wc-city-select'),
		_x('Bato', 'PRLE', 'ry-wc-city-select'),
		_x('Burauen', 'PRLE', 'ry-wc-city-select'),
		_x('Calubian', 'PRLE', 'ry-wc-city-select'),
		_x('Capoocan', 'PRLE', 'ry-wc-city-select'),
		_x('Carigara', 'PRLE', 'ry-wc-city-select'),
		_x('City of Baybay', 'PRLE', 'ry-wc-city-select'),
		_x('Dagami', 'PRLE', 'ry-wc-city-select'),
		_x('Dulag', 'PRLE', 'ry-wc-city-select'),
		_x('Hilongos', 'PRLE', 'ry-wc-city-select'),
		_x('Hindang', 'PRLE', 'ry-wc-city-select'),
		_x('Inopacan', 'PRLE', 'ry-wc-city-select'),
		_x('Isabel', 'PRLE', 'ry-wc-city-select'),
		_x('Jaro', 'PRLE', 'ry-wc-city-select'),
		_x('Javier (Bugho)', 'PRLE', 'ry-wc-city-select'),
		_x('Julita', 'PRLE', 'ry-wc-city-select'),
		_x('Kananga', 'PRLE', 'ry-wc-city-select'),
		_x('La Paz', 'PRLE', 'ry-wc-city-select'),
		_x('Leyte', 'PRLE', 'ry-wc-city-select'),
		_x('Macarthur', 'PRLE', 'ry-wc-city-select'),
		_x('Mahaplag', 'PRLE', 'ry-wc-city-select'),
		_x('Matag-Ob', 'PRLE', 'ry-wc-city-select'),
		_x('Matalom', 'PRLE', 'ry-wc-city-select'),
		_x('Mayorga', 'PRLE', 'ry-wc-city-select'),
		_x('Merida', 'PRLE', 'ry-wc-city-select'),
		_x('Ormoc City', 'PRLE', 'ry-wc-city-select'),
		_x('Palo', 'PRLE', 'ry-wc-city-select'),
		_x('Palompon', 'PRLE', 'ry-wc-city-select'),
		_x('Pastrana', 'PRLE', 'ry-wc-city-select'),
		_x('San Isidro', 'PRLE', 'ry-wc-city-select'),
		_x('San Miguel', 'PRLE', 'ry-wc-city-select'),
		_x('Santa Fe', 'PRLE', 'ry-wc-city-select'),
		_x('Tabango', 'PRLE', 'ry-wc-city-select'),
		_x('Tabontabon', 'PRLE', 'ry-wc-city-select'),
		_x('Tacloban City', 'PRLE', 'ry-wc-city-select'),
		_x('Tanauan', 'PRLE', 'ry-wc-city-select'),
		_x('Tolosa', 'PRLE', 'ry-wc-city-select'),
		_x('Tunga', 'PRLE', 'ry-wc-city-select'),
		_x('Villaba', 'PRLE', 'ry-wc-city-select'),
	],
	'PRMA' => [
		_x('Ampatuan', 'PRMA', 'ry-wc-city-select'),
		_x('Barira', 'PRMA', 'ry-wc-city-select'),
		_x('Buldon', 'PRMA', 'ry-wc-city-select'),
		_x('Buluan', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Abdullah Sangki', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Anggal Midtimbang', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Blah T. Sinsuat', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Hoffer Ampatuan', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Odin Sinsuat (Dinaig)', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Paglas', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Piang', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Salibo', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Saudi-Ampatuan', 'PRMA', 'ry-wc-city-select'),
		_x('Datu Unsay', 'PRMA', 'ry-wc-city-select'),
		_x('Gen. S.K. Pendatun', 'PRMA', 'ry-wc-city-select'),
		_x('Guindulungan', 'PRMA', 'ry-wc-city-select'),
		_x('Kabuntalan (Tumbao)', 'PRMA', 'ry-wc-city-select'),
		_x('Mamasapano', 'PRMA', 'ry-wc-city-select'),
		_x('Mangudadatu', 'PRMA', 'ry-wc-city-select'),
		_x('Matanog', 'PRMA', 'ry-wc-city-select'),
		_x('Northern Kabuntalan', 'PRMA', 'ry-wc-city-select'),
		_x('Pagagawan', 'PRMA', 'ry-wc-city-select'),
		_x('Pagalungan', 'PRMA', 'ry-wc-city-select'),
		_x('Paglat', 'PRMA', 'ry-wc-city-select'),
		_x('Pandag', 'PRMA', 'ry-wc-city-select'),
		_x('Parang', 'PRMA', 'ry-wc-city-select'),
		_x('Rajah Buayan', 'PRMA', 'ry-wc-city-select'),
		_x('Shariff Aguak (Maganoy)', 'PRMA', 'ry-wc-city-select'),
		_x('Shariff Saydona Mustapha', 'PRMA', 'ry-wc-city-select'),
		_x('South Upi', 'PRMA', 'ry-wc-city-select'),
		_x('Sultan Kudarat (Nuling)', 'PRMA', 'ry-wc-city-select'),
		_x('Sultan Mastura', 'PRMA', 'ry-wc-city-select'),
		_x('Sultan Sa Barongis (Lambayong)', 'PRMA', 'ry-wc-city-select'),
		_x('Talayan', 'PRMA', 'ry-wc-city-select'),
		_x('Talitay', 'PRMA', 'ry-wc-city-select'),
		_x('Upi', 'PRMA', 'ry-wc-city-select'),
	],
	'PRMA2' => [
		_x('Boac', 'PRMA2', 'ry-wc-city-select'),
		_x('Buenavista', 'PRMA2', 'ry-wc-city-select'),
		_x('Gasan', 'PRMA2', 'ry-wc-city-select'),
		_x('Mogpog', 'PRMA2', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRMA2', 'ry-wc-city-select'),
		_x('Torrijos', 'PRMA2', 'ry-wc-city-select'),
	],
	'PRMA3' => [
		_x('Aroroy', 'PRMA3', 'ry-wc-city-select'),
		_x('Baleno', 'PRMA3', 'ry-wc-city-select'),
		_x('Balud', 'PRMA3', 'ry-wc-city-select'),
		_x('Batuan', 'PRMA3', 'ry-wc-city-select'),
		_x('Cataingan', 'PRMA3', 'ry-wc-city-select'),
		_x('Cawayan', 'PRMA3', 'ry-wc-city-select'),
		_x('City of Masbate', 'PRMA3', 'ry-wc-city-select'),
		_x('Claveria', 'PRMA3', 'ry-wc-city-select'),
		_x('Dimasalang', 'PRMA3', 'ry-wc-city-select'),
		_x('Esperanza', 'PRMA3', 'ry-wc-city-select'),
		_x('Mandaon', 'PRMA3', 'ry-wc-city-select'),
		_x('Milagros', 'PRMA3', 'ry-wc-city-select'),
		_x('Mobo', 'PRMA3', 'ry-wc-city-select'),
		_x('Monreal', 'PRMA3', 'ry-wc-city-select'),
		_x('Palanas', 'PRMA3', 'ry-wc-city-select'),
		_x('Pio V. Corpuz (Limbuhan)', 'PRMA3', 'ry-wc-city-select'),
		_x('Placer', 'PRMA3', 'ry-wc-city-select'),
		_x('San Fernando', 'PRMA3', 'ry-wc-city-select'),
		_x('San Jacinto', 'PRMA3', 'ry-wc-city-select'),
		_x('San Pascual', 'PRMA3', 'ry-wc-city-select'),
		_x('Uson', 'PRMA3', 'ry-wc-city-select'),
	],
	'PRMIOC' => [
		_x('Abra De Ilog', 'PRMIOC', 'ry-wc-city-select'),
		_x('Calintaan', 'PRMIOC', 'ry-wc-city-select'),
		_x('Looc', 'PRMIOC', 'ry-wc-city-select'),
		_x('Lubang', 'PRMIOC', 'ry-wc-city-select'),
		_x('Magsaysay', 'PRMIOC', 'ry-wc-city-select'),
		_x('Mamburao', 'PRMIOC', 'ry-wc-city-select'),
		_x('Paluan', 'PRMIOC', 'ry-wc-city-select'),
		_x('Rizal', 'PRMIOC', 'ry-wc-city-select'),
		_x('Sablayan', 'PRMIOC', 'ry-wc-city-select'),
		_x('San Jose', 'PRMIOC', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRMIOC', 'ry-wc-city-select'),
	],
	'PRMIOR' => [
		_x('Baco', 'PRMIOR', 'ry-wc-city-select'),
		_x('Bansud', 'PRMIOR', 'ry-wc-city-select'),
		_x('Bongabong', 'PRMIOR', 'ry-wc-city-select'),
		_x('Bulalacao (San Pedro)', 'PRMIOR', 'ry-wc-city-select'),
		_x('City of Calapan', 'PRMIOR', 'ry-wc-city-select'),
		_x('Gloria', 'PRMIOR', 'ry-wc-city-select'),
		_x('Mansalay', 'PRMIOR', 'ry-wc-city-select'),
		_x('Naujan', 'PRMIOR', 'ry-wc-city-select'),
		_x('Pinamalayan', 'PRMIOR', 'ry-wc-city-select'),
		_x('Pola', 'PRMIOR', 'ry-wc-city-select'),
		_x('Puerto Galera', 'PRMIOR', 'ry-wc-city-select'),
		_x('Roxas', 'PRMIOR', 'ry-wc-city-select'),
		_x('San Teodoro', 'PRMIOR', 'ry-wc-city-select'),
		_x('Socorro', 'PRMIOR', 'ry-wc-city-select'),
		_x('Victoria', 'PRMIOR', 'ry-wc-city-select'),
	],
	'PRMIOC2' => [
		_x('Aloran', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Baliangao', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Bonifacio', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Calamba', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Clarin', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Concepcion', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Don Victoriano Chiongbian  (Don Mariano', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Jimenez', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Lopez Jaena', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Oroquieta City', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Ozamiz City', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Panaon', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Plaridel', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Sapang Dalaga', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Sinacaban', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Tangub City', 'PRMIOC2', 'ry-wc-city-select'),
		_x('Tudela', 'PRMIOC2', 'ry-wc-city-select'),
	],
	'PRMIOR2' => [
		_x('Alubijid', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Balingasag', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Balingoan', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Binuangan', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Cagayan De Oro City', 'PRMIOR2', 'ry-wc-city-select'),
		_x('City of El Salvador', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Claveria', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Gingoog City', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Gitagum', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Initao', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Jasaan', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Kinoguitan', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Lagonglong', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Laguindingan', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Libertad', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Lugait', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Magsaysay (Linugos)', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Manticao', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Medina', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Naawan', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Opol', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Salay', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Sugbongcogon', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Tagoloan', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Talisayan', 'PRMIOR2', 'ry-wc-city-select'),
		_x('Villanueva', 'PRMIOR2', 'ry-wc-city-select'),
	],
	'PRNEOC' => [
		_x('Bacolod City', 'PRNEOC', 'ry-wc-city-select'),
		_x('Bago City', 'PRNEOC', 'ry-wc-city-select'),
		_x('Binalbagan', 'PRNEOC', 'ry-wc-city-select'),
		_x('Cadiz City', 'PRNEOC', 'ry-wc-city-select'),
		_x('Calatrava', 'PRNEOC', 'ry-wc-city-select'),
		_x('Candoni', 'PRNEOC', 'ry-wc-city-select'),
		_x('Cauayan', 'PRNEOC', 'ry-wc-city-select'),
		_x('City of Escalante', 'PRNEOC', 'ry-wc-city-select'),
		_x('City of Himamaylan', 'PRNEOC', 'ry-wc-city-select'),
		_x('City of Kabankalan', 'PRNEOC', 'ry-wc-city-select'),
		_x('City of Sipalay', 'PRNEOC', 'ry-wc-city-select'),
		_x('City of Talisay', 'PRNEOC', 'ry-wc-city-select'),
		_x('City of Victorias', 'PRNEOC', 'ry-wc-city-select'),
		_x('Enrique B. Magalona (Saravia)', 'PRNEOC', 'ry-wc-city-select'),
		_x('Hinigaran', 'PRNEOC', 'ry-wc-city-select'),
		_x('Hinoba-An', 'PRNEOC', 'ry-wc-city-select'),
		_x('Ilog', 'PRNEOC', 'ry-wc-city-select'),
		_x('Isabela', 'PRNEOC', 'ry-wc-city-select'),
		_x('La Carlota City', 'PRNEOC', 'ry-wc-city-select'),
		_x('La Castellana', 'PRNEOC', 'ry-wc-city-select'),
		_x('Manapla', 'PRNEOC', 'ry-wc-city-select'),
		_x('Moises Padilla (Magallon)', 'PRNEOC', 'ry-wc-city-select'),
		_x('Murcia', 'PRNEOC', 'ry-wc-city-select'),
		_x('Pontevedra', 'PRNEOC', 'ry-wc-city-select'),
		_x('Pulupandan', 'PRNEOC', 'ry-wc-city-select'),
		_x('Sagay City', 'PRNEOC', 'ry-wc-city-select'),
		_x('Salvador Benedicto', 'PRNEOC', 'ry-wc-city-select'),
		_x('San Carlos City', 'PRNEOC', 'ry-wc-city-select'),
		_x('San Enrique', 'PRNEOC', 'ry-wc-city-select'),
		_x('Silay City', 'PRNEOC', 'ry-wc-city-select'),
		_x('Toboso', 'PRNEOC', 'ry-wc-city-select'),
		_x('Valladolid', 'PRNEOC', 'ry-wc-city-select'),
	],
	'PRNEOR' => [
		_x('Amlan (Ayuquitan)', 'PRNEOR', 'ry-wc-city-select'),
		_x('Ayungon', 'PRNEOR', 'ry-wc-city-select'),
		_x('Bacong', 'PRNEOR', 'ry-wc-city-select'),
		_x('Bais City', 'PRNEOR', 'ry-wc-city-select'),
		_x('Basay', 'PRNEOR', 'ry-wc-city-select'),
		_x('Bindoy (Payabon)', 'PRNEOR', 'ry-wc-city-select'),
		_x('Canlaon City', 'PRNEOR', 'ry-wc-city-select'),
		_x('City of Bayawan (Tulong)', 'PRNEOR', 'ry-wc-city-select'),
		_x('City of Guihulngan', 'PRNEOR', 'ry-wc-city-select'),
		_x('City of Tanjay', 'PRNEOR', 'ry-wc-city-select'),
		_x('Dauin', 'PRNEOR', 'ry-wc-city-select'),
		_x('Dumaguete City', 'PRNEOR', 'ry-wc-city-select'),
		_x('Jimalalud', 'PRNEOR', 'ry-wc-city-select'),
		_x('La Libertad', 'PRNEOR', 'ry-wc-city-select'),
		_x('Mabinay', 'PRNEOR', 'ry-wc-city-select'),
		_x('Manjuyod', 'PRNEOR', 'ry-wc-city-select'),
		_x('Pamplona', 'PRNEOR', 'ry-wc-city-select'),
		_x('San Jose', 'PRNEOR', 'ry-wc-city-select'),
		_x('Santa Catalina', 'PRNEOR', 'ry-wc-city-select'),
		_x('Siaton', 'PRNEOR', 'ry-wc-city-select'),
		_x('Sibulan', 'PRNEOR', 'ry-wc-city-select'),
		_x('Tayasan', 'PRNEOR', 'ry-wc-city-select'),
		_x('Valencia (Luzurriaga)', 'PRNEOR', 'ry-wc-city-select'),
		_x('Vallehermoso', 'PRNEOR', 'ry-wc-city-select'),
		_x('Zamboanguita', 'PRNEOR', 'ry-wc-city-select'),
	],
	'PRNOSA' => [
		_x('Allen', 'PRNOSA', 'ry-wc-city-select'),
		_x('Biri', 'PRNOSA', 'ry-wc-city-select'),
		_x('Bobon', 'PRNOSA', 'ry-wc-city-select'),
		_x('Capul', 'PRNOSA', 'ry-wc-city-select'),
		_x('Catarman', 'PRNOSA', 'ry-wc-city-select'),
		_x('Catubig', 'PRNOSA', 'ry-wc-city-select'),
		_x('Gamay', 'PRNOSA', 'ry-wc-city-select'),
		_x('Laoang', 'PRNOSA', 'ry-wc-city-select'),
		_x('Lapinig', 'PRNOSA', 'ry-wc-city-select'),
		_x('Las Navas', 'PRNOSA', 'ry-wc-city-select'),
		_x('Lavezares', 'PRNOSA', 'ry-wc-city-select'),
		_x('Lope De Vega', 'PRNOSA', 'ry-wc-city-select'),
		_x('Mapanas', 'PRNOSA', 'ry-wc-city-select'),
		_x('Mondragon', 'PRNOSA', 'ry-wc-city-select'),
		_x('Palapag', 'PRNOSA', 'ry-wc-city-select'),
		_x('Pambujan', 'PRNOSA', 'ry-wc-city-select'),
		_x('Rosario', 'PRNOSA', 'ry-wc-city-select'),
		_x('San Antonio', 'PRNOSA', 'ry-wc-city-select'),
		_x('San Isidro', 'PRNOSA', 'ry-wc-city-select'),
		_x('San Jose', 'PRNOSA', 'ry-wc-city-select'),
		_x('San Roque', 'PRNOSA', 'ry-wc-city-select'),
		_x('San Vicente', 'PRNOSA', 'ry-wc-city-select'),
		_x('Silvino Lobos', 'PRNOSA', 'ry-wc-city-select'),
		_x('Victoria', 'PRNOSA', 'ry-wc-city-select'),
	],
	'PRNUEC' => [
		_x('Aliaga', 'PRNUEC', 'ry-wc-city-select'),
		_x('Bongabon', 'PRNUEC', 'ry-wc-city-select'),
		_x('Cabanatuan City', 'PRNUEC', 'ry-wc-city-select'),
		_x('Cabiao', 'PRNUEC', 'ry-wc-city-select'),
		_x('Carranglan', 'PRNUEC', 'ry-wc-city-select'),
		_x('City of Gapan', 'PRNUEC', 'ry-wc-city-select'),
		_x('Cuyapo', 'PRNUEC', 'ry-wc-city-select'),
		_x('Gabaldon (Bitulok & Sabani)', 'PRNUEC', 'ry-wc-city-select'),
		_x('General Mamerto Natividad', 'PRNUEC', 'ry-wc-city-select'),
		_x('General Tinio (Papaya)', 'PRNUEC', 'ry-wc-city-select'),
		_x('Guimba', 'PRNUEC', 'ry-wc-city-select'),
		_x('Jaen', 'PRNUEC', 'ry-wc-city-select'),
		_x('Laur', 'PRNUEC', 'ry-wc-city-select'),
		_x('Licab', 'PRNUEC', 'ry-wc-city-select'),
		_x('Llanera', 'PRNUEC', 'ry-wc-city-select'),
		_x('Lupao', 'PRNUEC', 'ry-wc-city-select'),
		_x('Nampicuan', 'PRNUEC', 'ry-wc-city-select'),
		_x('Palayan City', 'PRNUEC', 'ry-wc-city-select'),
		_x('Pantabangan', 'PRNUEC', 'ry-wc-city-select'),
		_x('Penaranda', 'PRNUEC', 'ry-wc-city-select'),
		_x('Quezon', 'PRNUEC', 'ry-wc-city-select'),
		_x('Rizal', 'PRNUEC', 'ry-wc-city-select'),
		_x('San Antonio', 'PRNUEC', 'ry-wc-city-select'),
		_x('San Isidro', 'PRNUEC', 'ry-wc-city-select'),
		_x('San Jose City', 'PRNUEC', 'ry-wc-city-select'),
		_x('San Leonardo', 'PRNUEC', 'ry-wc-city-select'),
		_x('Santa Rosa', 'PRNUEC', 'ry-wc-city-select'),
		_x('Santo Domingo', 'PRNUEC', 'ry-wc-city-select'),
		_x('Science City of Munoz', 'PRNUEC', 'ry-wc-city-select'),
		_x('Talavera', 'PRNUEC', 'ry-wc-city-select'),
		_x('Talugtug', 'PRNUEC', 'ry-wc-city-select'),
		_x('Zaragoza', 'PRNUEC', 'ry-wc-city-select'),
	],
	'PRNUVI' => [
		_x('Alfonso Castaneda', 'PRNUVI', 'ry-wc-city-select'),
		_x('Ambaguio', 'PRNUVI', 'ry-wc-city-select'),
		_x('Aritao', 'PRNUVI', 'ry-wc-city-select'),
		_x('Bagabag', 'PRNUVI', 'ry-wc-city-select'),
		_x('Bambang', 'PRNUVI', 'ry-wc-city-select'),
		_x('Bayombong', 'PRNUVI', 'ry-wc-city-select'),
		_x('Diadi', 'PRNUVI', 'ry-wc-city-select'),
		_x('Dupax Del Norte', 'PRNUVI', 'ry-wc-city-select'),
		_x('Dupax Del Sur', 'PRNUVI', 'ry-wc-city-select'),
		_x('Kasibu', 'PRNUVI', 'ry-wc-city-select'),
		_x('Kayapa', 'PRNUVI', 'ry-wc-city-select'),
		_x('Quezon', 'PRNUVI', 'ry-wc-city-select'),
		_x('Santa Fe', 'PRNUVI', 'ry-wc-city-select'),
		_x('Solano', 'PRNUVI', 'ry-wc-city-select'),
		_x('Villaverde', 'PRNUVI', 'ry-wc-city-select'),
	],
	'PRPA' => [
		_x('Aborlan', 'PRPA', 'ry-wc-city-select'),
		_x('Agutaya', 'PRPA', 'ry-wc-city-select'),
		_x('Araceli', 'PRPA', 'ry-wc-city-select'),
		_x('Balabac', 'PRPA', 'ry-wc-city-select'),
		_x('Bataraza', 'PRPA', 'ry-wc-city-select'),
		_x('BrookeS Point', 'PRPA', 'ry-wc-city-select'),
		_x('Busuanga', 'PRPA', 'ry-wc-city-select'),
		_x('Cagayancillo', 'PRPA', 'ry-wc-city-select'),
		_x('Coron', 'PRPA', 'ry-wc-city-select'),
		_x('Culion', 'PRPA', 'ry-wc-city-select'),
		_x('Cuyo', 'PRPA', 'ry-wc-city-select'),
		_x('Dumaran', 'PRPA', 'ry-wc-city-select'),
		_x('El Nido', 'PRPA', 'ry-wc-city-select'),
		_x('Kalayaan', 'PRPA', 'ry-wc-city-select'),
		_x('Linapacan', 'PRPA', 'ry-wc-city-select'),
		_x('Magsaysay', 'PRPA', 'ry-wc-city-select'),
		_x('Narra', 'PRPA', 'ry-wc-city-select'),
		_x('Puerto Princesa City', 'PRPA', 'ry-wc-city-select'),
		_x('Quezon', 'PRPA', 'ry-wc-city-select'),
		_x('Rizal (Marcos)', 'PRPA', 'ry-wc-city-select'),
		_x('Roxas', 'PRPA', 'ry-wc-city-select'),
		_x('San Vicente', 'PRPA', 'ry-wc-city-select'),
		_x('Sofronio Espanola', 'PRPA', 'ry-wc-city-select'),
		_x('Taytay', 'PRPA', 'ry-wc-city-select'),
	],
	'PRPA2' => [
		_x('Angeles City', 'PRPA2', 'ry-wc-city-select'),
		_x('Apalit', 'PRPA2', 'ry-wc-city-select'),
		_x('Arayat', 'PRPA2', 'ry-wc-city-select'),
		_x('Bacolor', 'PRPA2', 'ry-wc-city-select'),
		_x('Candaba', 'PRPA2', 'ry-wc-city-select'),
		_x('City of San Fernando', 'PRPA2', 'ry-wc-city-select'),
		_x('Floridablanca', 'PRPA2', 'ry-wc-city-select'),
		_x('Guagua', 'PRPA2', 'ry-wc-city-select'),
		_x('Lubao', 'PRPA2', 'ry-wc-city-select'),
		_x('Mabalacat City', 'PRPA2', 'ry-wc-city-select'),
		_x('Macabebe', 'PRPA2', 'ry-wc-city-select'),
		_x('Magalang', 'PRPA2', 'ry-wc-city-select'),
		_x('Masantol', 'PRPA2', 'ry-wc-city-select'),
		_x('Mexico', 'PRPA2', 'ry-wc-city-select'),
		_x('Minalin', 'PRPA2', 'ry-wc-city-select'),
		_x('Porac', 'PRPA2', 'ry-wc-city-select'),
		_x('San Luis', 'PRPA2', 'ry-wc-city-select'),
		_x('San Simon', 'PRPA2', 'ry-wc-city-select'),
		_x('Santa Ana', 'PRPA2', 'ry-wc-city-select'),
		_x('Santa Rita', 'PRPA2', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRPA2', 'ry-wc-city-select'),
		_x('Sasmuan (Sexmoan)', 'PRPA2', 'ry-wc-city-select'),
	],
	'PRPA3' => [
		_x('Agno', 'PRPA3', 'ry-wc-city-select'),
		_x('Aguilar', 'PRPA3', 'ry-wc-city-select'),
		_x('Alcala', 'PRPA3', 'ry-wc-city-select'),
		_x('Anda', 'PRPA3', 'ry-wc-city-select'),
		_x('Asingan', 'PRPA3', 'ry-wc-city-select'),
		_x('Balungao', 'PRPA3', 'ry-wc-city-select'),
		_x('Bani', 'PRPA3', 'ry-wc-city-select'),
		_x('Basista', 'PRPA3', 'ry-wc-city-select'),
		_x('Bautista', 'PRPA3', 'ry-wc-city-select'),
		_x('Bayambang', 'PRPA3', 'ry-wc-city-select'),
		_x('Binalonan', 'PRPA3', 'ry-wc-city-select'),
		_x('Binmaley', 'PRPA3', 'ry-wc-city-select'),
		_x('Bolinao', 'PRPA3', 'ry-wc-city-select'),
		_x('Bugallon', 'PRPA3', 'ry-wc-city-select'),
		_x('Burgos', 'PRPA3', 'ry-wc-city-select'),
		_x('Calasiao', 'PRPA3', 'ry-wc-city-select'),
		_x('City of Alaminos', 'PRPA3', 'ry-wc-city-select'),
		_x('City of Urdaneta', 'PRPA3', 'ry-wc-city-select'),
		_x('Dagupan City', 'PRPA3', 'ry-wc-city-select'),
		_x('Dasol', 'PRPA3', 'ry-wc-city-select'),
		_x('Infanta', 'PRPA3', 'ry-wc-city-select'),
		_x('Labrador', 'PRPA3', 'ry-wc-city-select'),
		_x('Laoac', 'PRPA3', 'ry-wc-city-select'),
		_x('Lingayen', 'PRPA3', 'ry-wc-city-select'),
		_x('Mabini', 'PRPA3', 'ry-wc-city-select'),
		_x('Malasiqui', 'PRPA3', 'ry-wc-city-select'),
		_x('Manaoag', 'PRPA3', 'ry-wc-city-select'),
		_x('Mangaldan', 'PRPA3', 'ry-wc-city-select'),
		_x('Mangatarem', 'PRPA3', 'ry-wc-city-select'),
		_x('Mapandan', 'PRPA3', 'ry-wc-city-select'),
		_x('Natividad', 'PRPA3', 'ry-wc-city-select'),
		_x('Pozorrubio', 'PRPA3', 'ry-wc-city-select'),
		_x('Rosales', 'PRPA3', 'ry-wc-city-select'),
		_x('San Carlos City', 'PRPA3', 'ry-wc-city-select'),
		_x('San Fabian', 'PRPA3', 'ry-wc-city-select'),
		_x('San Jacinto', 'PRPA3', 'ry-wc-city-select'),
		_x('San Manuel', 'PRPA3', 'ry-wc-city-select'),
		_x('San Nicolas', 'PRPA3', 'ry-wc-city-select'),
		_x('San Quintin', 'PRPA3', 'ry-wc-city-select'),
		_x('Santa Barbara', 'PRPA3', 'ry-wc-city-select'),
		_x('Santa Maria', 'PRPA3', 'ry-wc-city-select'),
		_x('Santo Tomas', 'PRPA3', 'ry-wc-city-select'),
		_x('Sison', 'PRPA3', 'ry-wc-city-select'),
		_x('Sual', 'PRPA3', 'ry-wc-city-select'),
		_x('Tayug', 'PRPA3', 'ry-wc-city-select'),
		_x('Umingan', 'PRPA3', 'ry-wc-city-select'),
		_x('Urbiztondo', 'PRPA3', 'ry-wc-city-select'),
		_x('Villasis', 'PRPA3', 'ry-wc-city-select'),
	],
	'PRQU' => [
		_x('Agdangan', 'PRQU', 'ry-wc-city-select'),
		_x('Alabat', 'PRQU', 'ry-wc-city-select'),
		_x('Atimonan', 'PRQU', 'ry-wc-city-select'),
		_x('Buenavista', 'PRQU', 'ry-wc-city-select'),
		_x('Burdeos', 'PRQU', 'ry-wc-city-select'),
		_x('Calauag', 'PRQU', 'ry-wc-city-select'),
		_x('Candelaria', 'PRQU', 'ry-wc-city-select'),
		_x('Catanauan', 'PRQU', 'ry-wc-city-select'),
		_x('City of Tayabas', 'PRQU', 'ry-wc-city-select'),
		_x('Dolores', 'PRQU', 'ry-wc-city-select'),
		_x('General Luna', 'PRQU', 'ry-wc-city-select'),
		_x('General Nakar', 'PRQU', 'ry-wc-city-select'),
		_x('Guinayangan', 'PRQU', 'ry-wc-city-select'),
		_x('Gumaca', 'PRQU', 'ry-wc-city-select'),
		_x('Infanta', 'PRQU', 'ry-wc-city-select'),
		_x('Jomalig', 'PRQU', 'ry-wc-city-select'),
		_x('Lopez', 'PRQU', 'ry-wc-city-select'),
		_x('Lucban', 'PRQU', 'ry-wc-city-select'),
		_x('Lucena City', 'PRQU', 'ry-wc-city-select'),
		_x('Macalelon', 'PRQU', 'ry-wc-city-select'),
		_x('Mauban', 'PRQU', 'ry-wc-city-select'),
		_x('Mulanay', 'PRQU', 'ry-wc-city-select'),
		_x('Padre Burgos', 'PRQU', 'ry-wc-city-select'),
		_x('Pagbilao', 'PRQU', 'ry-wc-city-select'),
		_x('Panukulan', 'PRQU', 'ry-wc-city-select'),
		_x('Patnanungan', 'PRQU', 'ry-wc-city-select'),
		_x('Perez', 'PRQU', 'ry-wc-city-select'),
		_x('Pitogo', 'PRQU', 'ry-wc-city-select'),
		_x('Plaridel', 'PRQU', 'ry-wc-city-select'),
		_x('Polillo', 'PRQU', 'ry-wc-city-select'),
		_x('Quezon', 'PRQU', 'ry-wc-city-select'),
		_x('Real', 'PRQU', 'ry-wc-city-select'),
		_x('Sampaloc', 'PRQU', 'ry-wc-city-select'),
		_x('San Andres', 'PRQU', 'ry-wc-city-select'),
		_x('San Antonio', 'PRQU', 'ry-wc-city-select'),
		_x('San Francisco (Aurora)', 'PRQU', 'ry-wc-city-select'),
		_x('San Narciso', 'PRQU', 'ry-wc-city-select'),
		_x('Sariaya', 'PRQU', 'ry-wc-city-select'),
		_x('Tagkawayan', 'PRQU', 'ry-wc-city-select'),
		_x('Tiaong', 'PRQU', 'ry-wc-city-select'),
		_x('Unisan', 'PRQU', 'ry-wc-city-select'),
	],
	'PRQU2' => [
		_x('Aglipay', 'PRQU2', 'ry-wc-city-select'),
		_x('Cabarroguis', 'PRQU2', 'ry-wc-city-select'),
		_x('Diffun', 'PRQU2', 'ry-wc-city-select'),
		_x('Maddela', 'PRQU2', 'ry-wc-city-select'),
		_x('Nagtipunan', 'PRQU2', 'ry-wc-city-select'),
		_x('Saguday', 'PRQU2', 'ry-wc-city-select'),
	],
	'PRRI' => [
		_x('Angono', 'PRRI', 'ry-wc-city-select'),
		_x('Baras', 'PRRI', 'ry-wc-city-select'),
		_x('Binangonan', 'PRRI', 'ry-wc-city-select'),
		_x('Cainta', 'PRRI', 'ry-wc-city-select'),
		_x('Cardona', 'PRRI', 'ry-wc-city-select'),
		_x('City of Antipolo', 'PRRI', 'ry-wc-city-select'),
		_x('Jala-Jala', 'PRRI', 'ry-wc-city-select'),
		_x('Morong', 'PRRI', 'ry-wc-city-select'),
		_x('Pililla', 'PRRI', 'ry-wc-city-select'),
		_x('Rodriguez (Montalban)', 'PRRI', 'ry-wc-city-select'),
		_x('San Mateo', 'PRRI', 'ry-wc-city-select'),
		_x('Tanay', 'PRRI', 'ry-wc-city-select'),
		_x('Taytay', 'PRRI', 'ry-wc-city-select'),
		_x('Teresa', 'PRRI', 'ry-wc-city-select'),
	],
	'PRRO' => [
		_x('Alcantara', 'PRRO', 'ry-wc-city-select'),
		_x('Banton', 'PRRO', 'ry-wc-city-select'),
		_x('Cajidiocan', 'PRRO', 'ry-wc-city-select'),
		_x('Calatrava', 'PRRO', 'ry-wc-city-select'),
		_x('Concepcion', 'PRRO', 'ry-wc-city-select'),
		_x('Corcuera', 'PRRO', 'ry-wc-city-select'),
		_x('Ferrol', 'PRRO', 'ry-wc-city-select'),
		_x('Looc', 'PRRO', 'ry-wc-city-select'),
		_x('Magdiwang', 'PRRO', 'ry-wc-city-select'),
		_x('Odiongan', 'PRRO', 'ry-wc-city-select'),
		_x('Romblon', 'PRRO', 'ry-wc-city-select'),
		_x('San Agustin', 'PRRO', 'ry-wc-city-select'),
		_x('San Andres', 'PRRO', 'ry-wc-city-select'),
		_x('San Fernando', 'PRRO', 'ry-wc-city-select'),
		_x('San Jose', 'PRRO', 'ry-wc-city-select'),
		_x('Santa Fe', 'PRRO', 'ry-wc-city-select'),
		_x('Santa Maria (Imelda)', 'PRRO', 'ry-wc-city-select'),
	],
	'PRSA' => [
		_x('Almagro', 'PRSA', 'ry-wc-city-select'),
		_x('Basey', 'PRSA', 'ry-wc-city-select'),
		_x('Calbayog City', 'PRSA', 'ry-wc-city-select'),
		_x('Calbiga', 'PRSA', 'ry-wc-city-select'),
		_x('City of Catbalogan', 'PRSA', 'ry-wc-city-select'),
		_x('Daram', 'PRSA', 'ry-wc-city-select'),
		_x('Gandara', 'PRSA', 'ry-wc-city-select'),
		_x('Hinabangan', 'PRSA', 'ry-wc-city-select'),
		_x('Jiabong', 'PRSA', 'ry-wc-city-select'),
		_x('Marabut', 'PRSA', 'ry-wc-city-select'),
		_x('Matuguinao', 'PRSA', 'ry-wc-city-select'),
		_x('Motiong', 'PRSA', 'ry-wc-city-select'),
		_x('Pagsanghan', 'PRSA', 'ry-wc-city-select'),
		_x('Paranas (Wright)', 'PRSA', 'ry-wc-city-select'),
		_x('Pinabacdao', 'PRSA', 'ry-wc-city-select'),
		_x('San Jorge', 'PRSA', 'ry-wc-city-select'),
		_x('San Jose De Buan', 'PRSA', 'ry-wc-city-select'),
		_x('San Sebastian', 'PRSA', 'ry-wc-city-select'),
		_x('Santa Margarita', 'PRSA', 'ry-wc-city-select'),
		_x('Santa Rita', 'PRSA', 'ry-wc-city-select'),
		_x('Santo Nino', 'PRSA', 'ry-wc-city-select'),
		_x('Tagapul-An', 'PRSA', 'ry-wc-city-select'),
		_x('Talalora', 'PRSA', 'ry-wc-city-select'),
		_x('Tarangnan', 'PRSA', 'ry-wc-city-select'),
		_x('Villareal', 'PRSA', 'ry-wc-city-select'),
		_x('Zumarraga', 'PRSA', 'ry-wc-city-select'),
	],
	'PRSA2' => [
		_x('Alabel', 'PRSA2', 'ry-wc-city-select'),
		_x('Glan', 'PRSA2', 'ry-wc-city-select'),
		_x('Kiamba', 'PRSA2', 'ry-wc-city-select'),
		_x('Maasim', 'PRSA2', 'ry-wc-city-select'),
		_x('Maitum', 'PRSA2', 'ry-wc-city-select'),
		_x('Malapatan', 'PRSA2', 'ry-wc-city-select'),
		_x('Malungon', 'PRSA2', 'ry-wc-city-select'),
	],
	'PRSI' => [
		_x('Enrique Villanueva', 'PRSI', 'ry-wc-city-select'),
		_x('Larena', 'PRSI', 'ry-wc-city-select'),
		_x('Lazi', 'PRSI', 'ry-wc-city-select'),
		_x('Maria', 'PRSI', 'ry-wc-city-select'),
		_x('San Juan', 'PRSI', 'ry-wc-city-select'),
		_x('Siquijor', 'PRSI', 'ry-wc-city-select'),
	],
	'PRSO' => [
		_x('Barcelona', 'PRSO', 'ry-wc-city-select'),
		_x('Bulan', 'PRSO', 'ry-wc-city-select'),
		_x('Bulusan', 'PRSO', 'ry-wc-city-select'),
		_x('Casiguran', 'PRSO', 'ry-wc-city-select'),
		_x('Castilla', 'PRSO', 'ry-wc-city-select'),
		_x('City of Sorsogon', 'PRSO', 'ry-wc-city-select'),
		_x('Donsol', 'PRSO', 'ry-wc-city-select'),
		_x('Gubat', 'PRSO', 'ry-wc-city-select'),
		_x('Irosin', 'PRSO', 'ry-wc-city-select'),
		_x('Juban', 'PRSO', 'ry-wc-city-select'),
		_x('Magallanes', 'PRSO', 'ry-wc-city-select'),
		_x('Matnog', 'PRSO', 'ry-wc-city-select'),
		_x('Pilar', 'PRSO', 'ry-wc-city-select'),
		_x('Prieto Diaz', 'PRSO', 'ry-wc-city-select'),
		_x('Santa Magdalena', 'PRSO', 'ry-wc-city-select'),
	],
	'PRSOCO' => [
		_x('Banga', 'PRSOCO', 'ry-wc-city-select'),
		_x('City of Koronadal', 'PRSOCO', 'ry-wc-city-select'),
		_x('General Santos City (Dadiangas)', 'PRSOCO', 'ry-wc-city-select'),
		_x('Lake Sebu', 'PRSOCO', 'ry-wc-city-select'),
		_x('Norala', 'PRSOCO', 'ry-wc-city-select'),
		_x('Polomolok', 'PRSOCO', 'ry-wc-city-select'),
		_x('Santo Nino', 'PRSOCO', 'ry-wc-city-select'),
		_x('Surallah', 'PRSOCO', 'ry-wc-city-select'),
		_x('TBoli', 'PRSOCO', 'ry-wc-city-select'),
		_x('Tampakan', 'PRSOCO', 'ry-wc-city-select'),
		_x('Tantangan', 'PRSOCO', 'ry-wc-city-select'),
		_x('Tupi', 'PRSOCO', 'ry-wc-city-select'),
	],
	'PRSOLE' => [
		_x('Anahawan', 'PRSOLE', 'ry-wc-city-select'),
		_x('Bontoc', 'PRSOLE', 'ry-wc-city-select'),
		_x('City of Maasin', 'PRSOLE', 'ry-wc-city-select'),
		_x('Hinunangan', 'PRSOLE', 'ry-wc-city-select'),
		_x('Hinundayan', 'PRSOLE', 'ry-wc-city-select'),
		_x('Libagon', 'PRSOLE', 'ry-wc-city-select'),
		_x('Liloan', 'PRSOLE', 'ry-wc-city-select'),
		_x('Limasawa', 'PRSOLE', 'ry-wc-city-select'),
		_x('Macrohon', 'PRSOLE', 'ry-wc-city-select'),
		_x('Malitbog', 'PRSOLE', 'ry-wc-city-select'),
		_x('Padre Burgos', 'PRSOLE', 'ry-wc-city-select'),
		_x('Pintuyan', 'PRSOLE', 'ry-wc-city-select'),
		_x('Saint Bernard', 'PRSOLE', 'ry-wc-city-select'),
		_x('San Francisco', 'PRSOLE', 'ry-wc-city-select'),
		_x('San Juan (Cabalian)', 'PRSOLE', 'ry-wc-city-select'),
		_x('San Ricardo', 'PRSOLE', 'ry-wc-city-select'),
		_x('Silago', 'PRSOLE', 'ry-wc-city-select'),
		_x('Sogod', 'PRSOLE', 'ry-wc-city-select'),
		_x('Tomas Oppus', 'PRSOLE', 'ry-wc-city-select'),
	],
	'PRSUKU' => [
		_x('Bagumbayan', 'PRSUKU', 'ry-wc-city-select'),
		_x('City of Tacurong', 'PRSUKU', 'ry-wc-city-select'),
		_x('Columbio', 'PRSUKU', 'ry-wc-city-select'),
		_x('Esperanza', 'PRSUKU', 'ry-wc-city-select'),
		_x('Isulan', 'PRSUKU', 'ry-wc-city-select'),
		_x('Kalamansig', 'PRSUKU', 'ry-wc-city-select'),
		_x('Lambayong (Mariano Marcos)', 'PRSUKU', 'ry-wc-city-select'),
		_x('Lebak', 'PRSUKU', 'ry-wc-city-select'),
		_x('Lutayan', 'PRSUKU', 'ry-wc-city-select'),
		_x('Palimbang', 'PRSUKU', 'ry-wc-city-select'),
		_x('President Quirino', 'PRSUKU', 'ry-wc-city-select'),
		_x('Sen. Ninoy Aquino', 'PRSUKU', 'ry-wc-city-select'),
	],
	'PRSU' => [
		_x('Hadji Panglima Tahil (Marunggas)', 'PRSU', 'ry-wc-city-select'),
		_x('Indanan', 'PRSU', 'ry-wc-city-select'),
		_x('Jolo', 'PRSU', 'ry-wc-city-select'),
		_x('Kalingalan Caluang', 'PRSU', 'ry-wc-city-select'),
		_x('Lugus', 'PRSU', 'ry-wc-city-select'),
		_x('Luuk', 'PRSU', 'ry-wc-city-select'),
		_x('Maimbung', 'PRSU', 'ry-wc-city-select'),
		_x('Old Panamao', 'PRSU', 'ry-wc-city-select'),
		_x('Omar', 'PRSU', 'ry-wc-city-select'),
		_x('Pandami', 'PRSU', 'ry-wc-city-select'),
		_x('Panglima Estino (New Panamao)', 'PRSU', 'ry-wc-city-select'),
		_x('Pangutaran', 'PRSU', 'ry-wc-city-select'),
		_x('Parang', 'PRSU', 'ry-wc-city-select'),
		_x('Pata', 'PRSU', 'ry-wc-city-select'),
		_x('Patikul', 'PRSU', 'ry-wc-city-select'),
		_x('Siasi', 'PRSU', 'ry-wc-city-select'),
		_x('Talipao', 'PRSU', 'ry-wc-city-select'),
		_x('Tapul', 'PRSU', 'ry-wc-city-select'),
		_x('Tongkil', 'PRSU', 'ry-wc-city-select'),
	],
	'PRSUDENO' => [
		_x('Alegria', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Bacuag', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Burgos', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Claver', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Dapa', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Del Carmen', 'PRSUDENO', 'ry-wc-city-select'),
		_x('General Luna', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Gigaquit', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Mainit', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Malimono', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Pilar', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Placer', 'PRSUDENO', 'ry-wc-city-select'),
		_x('San Benito', 'PRSUDENO', 'ry-wc-city-select'),
		_x('San Francisco (Anao-Aon)', 'PRSUDENO', 'ry-wc-city-select'),
		_x('San Isidro', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Santa Monica (Sapao)', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Sison', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Socorro', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Surigao City', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Tagana-An', 'PRSUDENO', 'ry-wc-city-select'),
		_x('Tubod', 'PRSUDENO', 'ry-wc-city-select'),
	],
	'PRSUDESU' => [
		_x('Barobo', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Bayabas', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Cagwait', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Cantilan', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Carmen', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Carrascal', 'PRSUDESU', 'ry-wc-city-select'),
		_x('City of Bislig', 'PRSUDESU', 'ry-wc-city-select'),
		_x('City of Tandag', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Cortes', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Hinatuan', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Lanuza', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Lianga', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Lingig', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Madrid', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Marihatag', 'PRSUDESU', 'ry-wc-city-select'),
		_x('San Agustin', 'PRSUDESU', 'ry-wc-city-select'),
		_x('San Miguel', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Tagbina', 'PRSUDESU', 'ry-wc-city-select'),
		_x('Tago', 'PRSUDESU', 'ry-wc-city-select'),
	],
	'PRTA' => [
		_x('Anao', 'PRTA', 'ry-wc-city-select'),
		_x('Bamban', 'PRTA', 'ry-wc-city-select'),
		_x('Camiling', 'PRTA', 'ry-wc-city-select'),
		_x('Capas', 'PRTA', 'ry-wc-city-select'),
		_x('City of Tarlac', 'PRTA', 'ry-wc-city-select'),
		_x('Concepcion', 'PRTA', 'ry-wc-city-select'),
		_x('Gerona', 'PRTA', 'ry-wc-city-select'),
		_x('La Paz', 'PRTA', 'ry-wc-city-select'),
		_x('Mayantoc', 'PRTA', 'ry-wc-city-select'),
		_x('Moncada', 'PRTA', 'ry-wc-city-select'),
		_x('Paniqui', 'PRTA', 'ry-wc-city-select'),
		_x('Pura', 'PRTA', 'ry-wc-city-select'),
		_x('Ramos', 'PRTA', 'ry-wc-city-select'),
		_x('San Clemente', 'PRTA', 'ry-wc-city-select'),
		_x('San Jose', 'PRTA', 'ry-wc-city-select'),
		_x('San Manuel', 'PRTA', 'ry-wc-city-select'),
		_x('Santa Ignacia', 'PRTA', 'ry-wc-city-select'),
		_x('Victoria', 'PRTA', 'ry-wc-city-select'),
	],
	'PRTA2' => [
		_x('Bongao', 'PRTA2', 'ry-wc-city-select'),
		_x('Languyan', 'PRTA2', 'ry-wc-city-select'),
		_x('Municipality of Mapun', 'PRTA2', 'ry-wc-city-select'),
		_x('Panglima Sugala (Balimbing)', 'PRTA2', 'ry-wc-city-select'),
		_x('Sapa-Sapa', 'PRTA2', 'ry-wc-city-select'),
		_x('Sibutu', 'PRTA2', 'ry-wc-city-select'),
		_x('Simunul', 'PRTA2', 'ry-wc-city-select'),
		_x('Sitangkai', 'PRTA2', 'ry-wc-city-select'),
		_x('South Ubian', 'PRTA2', 'ry-wc-city-select'),
		_x('Tandubas', 'PRTA2', 'ry-wc-city-select'),
		_x('Turtle Islands', 'PRTA2', 'ry-wc-city-select'),
	],
	'PRZA' => [
		_x('Botolan', 'PRZA', 'ry-wc-city-select'),
		_x('Cabangan', 'PRZA', 'ry-wc-city-select'),
		_x('Candelaria', 'PRZA', 'ry-wc-city-select'),
		_x('Castillejos', 'PRZA', 'ry-wc-city-select'),
		_x('Iba', 'PRZA', 'ry-wc-city-select'),
		_x('Masinloc', 'PRZA', 'ry-wc-city-select'),
		_x('Olongapo City', 'PRZA', 'ry-wc-city-select'),
		_x('Palauig', 'PRZA', 'ry-wc-city-select'),
		_x('San Antonio', 'PRZA', 'ry-wc-city-select'),
		_x('San Felipe', 'PRZA', 'ry-wc-city-select'),
		_x('San Marcelino', 'PRZA', 'ry-wc-city-select'),
		_x('San Narciso', 'PRZA', 'ry-wc-city-select'),
		_x('Santa Cruz', 'PRZA', 'ry-wc-city-select'),
		_x('Subic', 'PRZA', 'ry-wc-city-select'),
	],
	'PRZASI' => [
		_x('Alicia', 'PRZASI', 'ry-wc-city-select'),
		_x('Buug', 'PRZASI', 'ry-wc-city-select'),
		_x('Diplahan', 'PRZASI', 'ry-wc-city-select'),
		_x('Imelda', 'PRZASI', 'ry-wc-city-select'),
		_x('Ipil', 'PRZASI', 'ry-wc-city-select'),
		_x('Kabasalan', 'PRZASI', 'ry-wc-city-select'),
		_x('Mabuhay', 'PRZASI', 'ry-wc-city-select'),
		_x('Malangas', 'PRZASI', 'ry-wc-city-select'),
		_x('Naga', 'PRZASI', 'ry-wc-city-select'),
		_x('Olutanga', 'PRZASI', 'ry-wc-city-select'),
		_x('Payao', 'PRZASI', 'ry-wc-city-select'),
		_x('Roseller Lim', 'PRZASI', 'ry-wc-city-select'),
		_x('Siay', 'PRZASI', 'ry-wc-city-select'),
		_x('Talusan', 'PRZASI', 'ry-wc-city-select'),
		_x('Titay', 'PRZASI', 'ry-wc-city-select'),
		_x('Tungawan', 'PRZASI', 'ry-wc-city-select'),
	],
	'PRZADENO' => [
		_x('Bacungan (Leon T. Postigo)', 'PRZADENO', 'ry-wc-city-select'),
		_x('Baliguian', 'PRZADENO', 'ry-wc-city-select'),
		_x('Dapitan City', 'PRZADENO', 'ry-wc-city-select'),
		_x('Dipolog City', 'PRZADENO', 'ry-wc-city-select'),
		_x('Godod', 'PRZADENO', 'ry-wc-city-select'),
		_x('Gutalac', 'PRZADENO', 'ry-wc-city-select'),
		_x('Jose Dalman (Ponot)', 'PRZADENO', 'ry-wc-city-select'),
		_x('Kalawit', 'PRZADENO', 'ry-wc-city-select'),
		_x('Katipunan', 'PRZADENO', 'ry-wc-city-select'),
		_x('La Libertad', 'PRZADENO', 'ry-wc-city-select'),
		_x('Labason', 'PRZADENO', 'ry-wc-city-select'),
		_x('Liloy', 'PRZADENO', 'ry-wc-city-select'),
		_x('Manukan', 'PRZADENO', 'ry-wc-city-select'),
		_x('Mutia', 'PRZADENO', 'ry-wc-city-select'),
		_x('Pinan (New Pinan)', 'PRZADENO', 'ry-wc-city-select'),
		_x('Polanco', 'PRZADENO', 'ry-wc-city-select'),
		_x('Pres. Manuel A. Roxas', 'PRZADENO', 'ry-wc-city-select'),
		_x('Rizal', 'PRZADENO', 'ry-wc-city-select'),
		_x('Salug', 'PRZADENO', 'ry-wc-city-select'),
		_x('Sergio Osmena Sr.', 'PRZADENO', 'ry-wc-city-select'),
		_x('Siayan', 'PRZADENO', 'ry-wc-city-select'),
		_x('Sibuco', 'PRZADENO', 'ry-wc-city-select'),
		_x('Sibutad', 'PRZADENO', 'ry-wc-city-select'),
		_x('Sindangan', 'PRZADENO', 'ry-wc-city-select'),
		_x('Siocon', 'PRZADENO', 'ry-wc-city-select'),
		_x('Sirawai', 'PRZADENO', 'ry-wc-city-select'),
		_x('Tampilisan', 'PRZADENO', 'ry-wc-city-select'),
	],
	'SOMADI' => [
		_x('City of Makati', 'SOMADI', 'ry-wc-city-select'),
		_x('City of Paranaque', 'SOMADI', 'ry-wc-city-select'),
		_x('Pasay City', 'SOMADI', 'ry-wc-city-select'),
	],
	'SO' => [
		_x('Cotabato City', 'SO', 'ry-wc-city-select'),
	],
	]
];