<?php
/**
 * Islamic Republic of Pakistan places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'PK' => [
	'BADI' => [
		_x('Allai Tehsil', 'BADI', 'ry-wc-city-select'),
		_x('Battagram Tehsil', 'BADI', 'ry-wc-city-select'),
	],
	'AZKA' => [
		_x('Bagh District', 'AZKA', 'ry-wc-city-select'),
		_x('Bhimbar District', 'AZKA', 'ry-wc-city-select'),
		_x('Hatian', 'AZKA', 'ry-wc-city-select'),
		_x('Haveli', 'AZKA', 'ry-wc-city-select'),
		_x('Kotli District', 'AZKA', 'ry-wc-city-select'),
		_x('Mirpur District', 'AZKA', 'ry-wc-city-select'),
		_x('Muzaffarabad District', 'AZKA', 'ry-wc-city-select'),
		_x('Neelum District', 'AZKA', 'ry-wc-city-select'),
		_x('Poonch District', 'AZKA', 'ry-wc-city-select'),
		_x('Sudhanoti District', 'AZKA', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Awaran District', 'BA', 'ry-wc-city-select'),
		_x('Barkhan District', 'BA', 'ry-wc-city-select'),
		_x('Chagai District', 'BA', 'ry-wc-city-select'),
		_x('Dera Bugti District', 'BA', 'ry-wc-city-select'),
		_x('Gwadar District', 'BA', 'ry-wc-city-select'),
		_x('Harnai', 'BA', 'ry-wc-city-select'),
		_x('Jafarabad District', 'BA', 'ry-wc-city-select'),
		_x('Jhal Magsi District', 'BA', 'ry-wc-city-select'),
		_x('Kachhi District', 'BA', 'ry-wc-city-select'),
		_x('Kalat District', 'BA', 'ry-wc-city-select'),
		_x('Kech District', 'BA', 'ry-wc-city-select'),
		_x('Kharan District', 'BA', 'ry-wc-city-select'),
		_x('Khuzdar District', 'BA', 'ry-wc-city-select'),
		_x('Kohlu District', 'BA', 'ry-wc-city-select'),
		_x('Lasbela District', 'BA', 'ry-wc-city-select'),
		_x('Loralai District', 'BA', 'ry-wc-city-select'),
		_x('Mastung District', 'BA', 'ry-wc-city-select'),
		_x('Musa Khel District', 'BA', 'ry-wc-city-select'),
		_x('Nasirabad District', 'BA', 'ry-wc-city-select'),
		_x('Nushki District', 'BA', 'ry-wc-city-select'),
		_x('Panjgur District', 'BA', 'ry-wc-city-select'),
		_x('Pishin District', 'BA', 'ry-wc-city-select'),
		_x('Qila Abdullah District', 'BA', 'ry-wc-city-select'),
		_x('Qila Saifullah District', 'BA', 'ry-wc-city-select'),
		_x('Quetta District', 'BA', 'ry-wc-city-select'),
		_x('Shirani', 'BA', 'ry-wc-city-select'),
		_x('Sibi District', 'BA', 'ry-wc-city-select'),
		_x('Sohbatpur District', 'BA', 'ry-wc-city-select'),
		_x('Washuk District', 'BA', 'ry-wc-city-select'),
		_x('Zhob District', 'BA', 'ry-wc-city-select'),
		_x('Ziarat District', 'BA', 'ry-wc-city-select'),
	],
	'GI' => [
		_x('Astor', 'GI', 'ry-wc-city-select'),
		_x('Diamir', 'GI', 'ry-wc-city-select'),
		_x('Ghanche District', 'GI', 'ry-wc-city-select'),
		_x('Ghizer District', 'GI', 'ry-wc-city-select'),
		_x('Gilgit', 'GI', 'ry-wc-city-select'),
		_x('Hunza-Nagar District', 'GI', 'ry-wc-city-select'),
		_x('Kharmang District', 'GI', 'ry-wc-city-select'),
		_x('Nagar District', 'GI', 'ry-wc-city-select'),
		_x('Shigar District', 'GI', 'ry-wc-city-select'),
		_x('Skardu District', 'GI', 'ry-wc-city-select'),
	],
	'KHPAPR' => [
		_x('Abbottabad District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Bajaur Agency', 'KHPAPR', 'ry-wc-city-select'),
		_x('Bannu District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Bannu Tribal Area', 'KHPAPR', 'ry-wc-city-select'),
		_x('Buner District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Charsadda District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Chitral District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Dera Ismail Khan District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Dera Ismail Khan Tribal Area', 'KHPAPR', 'ry-wc-city-select'),
		_x('Hangu District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Haripur District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Karak District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Khyber Agency', 'KHPAPR', 'ry-wc-city-select'),
		_x('Kohat District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Kohat Tribal Area', 'KHPAPR', 'ry-wc-city-select'),
		_x('Kurram District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Lakki Marwat District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Lakki Marwat Tribal Area', 'KHPAPR', 'ry-wc-city-select'),
		_x('Lower Dir District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Lower Kohistan District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Malakand Protected Area', 'KHPAPR', 'ry-wc-city-select'),
		_x('Mansehra District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Mardan District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Mohmand Agency', 'KHPAPR', 'ry-wc-city-select'),
		_x('North Waziristan District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Nowshera District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Orakzai Agency', 'KHPAPR', 'ry-wc-city-select'),
		_x('Peshawar District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Peshawar Tribal Area', 'KHPAPR', 'ry-wc-city-select'),
		_x('Shangla District', 'KHPAPR', 'ry-wc-city-select'),
		_x('South Waziristan District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Swabi District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Swat District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Tank District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Tank Tribal Area', 'KHPAPR', 'ry-wc-city-select'),
		_x('Tor Ghar', 'KHPAPR', 'ry-wc-city-select'),
		_x('Upper Dir District', 'KHPAPR', 'ry-wc-city-select'),
		_x('Upper Kohistan District', 'KHPAPR', 'ry-wc-city-select'),
	],
	'PUPR' => [
		_x('Attock District', 'PUPR', 'ry-wc-city-select'),
		_x('Bahawalnagar District', 'PUPR', 'ry-wc-city-select'),
		_x('Bahawalpur District', 'PUPR', 'ry-wc-city-select'),
		_x('Bhakkar District', 'PUPR', 'ry-wc-city-select'),
		_x('Chakwal District', 'PUPR', 'ry-wc-city-select'),
		_x('Chiniot', 'PUPR', 'ry-wc-city-select'),
		_x('Dera Ghazi Khan District', 'PUPR', 'ry-wc-city-select'),
		_x('Faisalabad District', 'PUPR', 'ry-wc-city-select'),
		_x('Gujranwala District', 'PUPR', 'ry-wc-city-select'),
		_x('Gujrat District', 'PUPR', 'ry-wc-city-select'),
		_x('Hafizabad District', 'PUPR', 'ry-wc-city-select'),
		_x('Jhang District', 'PUPR', 'ry-wc-city-select'),
		_x('Jhelum District', 'PUPR', 'ry-wc-city-select'),
		_x('Kasur District', 'PUPR', 'ry-wc-city-select'),
		_x('Khanewal District', 'PUPR', 'ry-wc-city-select'),
		_x('Khushab District', 'PUPR', 'ry-wc-city-select'),
		_x('Lahore District', 'PUPR', 'ry-wc-city-select'),
		_x('Layyah District', 'PUPR', 'ry-wc-city-select'),
		_x('Lodhran District', 'PUPR', 'ry-wc-city-select'),
		_x('Mandi Bahauddin District', 'PUPR', 'ry-wc-city-select'),
		_x('Mianwali District', 'PUPR', 'ry-wc-city-select'),
		_x('Multan District', 'PUPR', 'ry-wc-city-select'),
		_x('Muzaffargarh District', 'PUPR', 'ry-wc-city-select'),
		_x('Nankana Sahib District', 'PUPR', 'ry-wc-city-select'),
		_x('Narowal District', 'PUPR', 'ry-wc-city-select'),
		_x('Okara District', 'PUPR', 'ry-wc-city-select'),
		_x('Pakpattan District', 'PUPR', 'ry-wc-city-select'),
		_x('Rahimyar Khan District', 'PUPR', 'ry-wc-city-select'),
		_x('Rajanpur', 'PUPR', 'ry-wc-city-select'),
		_x('Rawalpindi District', 'PUPR', 'ry-wc-city-select'),
		_x('Sahiwal District', 'PUPR', 'ry-wc-city-select'),
		_x('Sargodha District', 'PUPR', 'ry-wc-city-select'),
		_x('Shekhupura District', 'PUPR', 'ry-wc-city-select'),
		_x('Sialkot District', 'PUPR', 'ry-wc-city-select'),
		_x('Toba Tek Singh District', 'PUPR', 'ry-wc-city-select'),
		_x('Vehari District', 'PUPR', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Badin District', 'SI', 'ry-wc-city-select'),
		_x('Dadu District', 'SI', 'ry-wc-city-select'),
		_x('District of West Karachi', 'SI', 'ry-wc-city-select'),
		_x('Ghotki District', 'SI', 'ry-wc-city-select'),
		_x('Hyderabad District', 'SI', 'ry-wc-city-select'),
		_x('Jacobabad District', 'SI', 'ry-wc-city-select'),
		_x('Jamshoro District', 'SI', 'ry-wc-city-select'),
		_x('Karachi Central District', 'SI', 'ry-wc-city-select'),
		_x('Karachi East District', 'SI', 'ry-wc-city-select'),
		_x('Karachi South District', 'SI', 'ry-wc-city-select'),
		_x('Kashmore District', 'SI', 'ry-wc-city-select'),
		_x('Khairpur District', 'SI', 'ry-wc-city-select'),
		_x('Korangi District', 'SI', 'ry-wc-city-select'),
		_x('Larkana District', 'SI', 'ry-wc-city-select'),
		_x('Malir District', 'SI', 'ry-wc-city-select'),
		_x('Matiari District', 'SI', 'ry-wc-city-select'),
		_x('Mirpur Khas District', 'SI', 'ry-wc-city-select'),
		_x('Naushahro Firoz District', 'SI', 'ry-wc-city-select'),
		_x('Qamber Shahdadkot District', 'SI', 'ry-wc-city-select'),
		_x('Sanghar District', 'SI', 'ry-wc-city-select'),
		_x('Shaheed Benazirabad District', 'SI', 'ry-wc-city-select'),
		_x('Shikarpur District', 'SI', 'ry-wc-city-select'),
		_x('Sujawal District', 'SI', 'ry-wc-city-select'),
		_x('Sukkur District', 'SI', 'ry-wc-city-select'),
		_x('Tando Allahyar District', 'SI', 'ry-wc-city-select'),
		_x('Tando Mohammad Khan District', 'SI', 'ry-wc-city-select'),
		_x('Thar Parkar District', 'SI', 'ry-wc-city-select'),
		_x('Thatta District', 'SI', 'ry-wc-city-select'),
		_x('Umerkot District', 'SI', 'ry-wc-city-select'),
	],
	]
];