<?php
/**
 * Serbia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'RS' => [
	'BE' => [
		_x('Opstina Beograd-Barajevo', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Cukarica', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Grocka', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Lazarevac', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Mladenovac', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Novi Beograd', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Obrenovac', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Palilula', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Rakovica', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Savski Venac', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Sopot', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Stari Grad', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Surcin', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Vozdovac', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Vracar', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Zemun', 'BE', 'ry-wc-city-select'),
		_x('Opstina Beograd-Zvezdara', 'BE', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Opstina Bor', 'BO', 'ry-wc-city-select'),
		_x('Opstina Kladovo', 'BO', 'ry-wc-city-select'),
		_x('Opstina Majdanpek', 'BO', 'ry-wc-city-select'),
		_x('Opstina Negotin', 'BO', 'ry-wc-city-select'),
	],
	'BR' => [
		_x('Opstina Golubac', 'BR', 'ry-wc-city-select'),
		_x('Opstina Kostolac', 'BR', 'ry-wc-city-select'),
		_x('Opstina Kucevo', 'BR', 'ry-wc-city-select'),
		_x('Opstina Malo Crnice', 'BR', 'ry-wc-city-select'),
		_x('Opstina Petrovac na Mlavi', 'BR', 'ry-wc-city-select'),
		_x('Opstina Pozarevac', 'BR', 'ry-wc-city-select'),
		_x('Opstina Veliko Gradiste', 'BR', 'ry-wc-city-select'),
		_x('Opstina Zabari', 'BR', 'ry-wc-city-select'),
		_x('Opstina Zagubica', 'BR', 'ry-wc-city-select'),
	],
	'CEBA' => [
		_x('Opstina Nova Crnja', 'CEBA', 'ry-wc-city-select'),
		_x('Opstina Novi Becej', 'CEBA', 'ry-wc-city-select'),
		_x('Opstina Secanj', 'CEBA', 'ry-wc-city-select'),
		_x('Opstina Zitiste', 'CEBA', 'ry-wc-city-select'),
		_x('Opstina Zrenjanin', 'CEBA', 'ry-wc-city-select'),
	],
	'JA' => [
		_x('Opstina Bojnik', 'JA', 'ry-wc-city-select'),
		_x('Opstina Crna Trava', 'JA', 'ry-wc-city-select'),
		_x('Opstina Lebane', 'JA', 'ry-wc-city-select'),
		_x('Opstina Leskovac', 'JA', 'ry-wc-city-select'),
		_x('Opstina Medveda', 'JA', 'ry-wc-city-select'),
		_x('Opstina Vlasotince', 'JA', 'ry-wc-city-select'),
	],
	'KO' => [
		_x('Opstina Lajkovac', 'KO', 'ry-wc-city-select'),
		_x('Opstina Ljig', 'KO', 'ry-wc-city-select'),
		_x('Opstina Mionica', 'KO', 'ry-wc-city-select'),
		_x('Opstina Osecina', 'KO', 'ry-wc-city-select'),
		_x('Opstina Ub', 'KO', 'ry-wc-city-select'),
		_x('Opstina Valjevo', 'KO', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Opstina Bogatic', 'MA', 'ry-wc-city-select'),
		_x('Opstina Koceljeva', 'MA', 'ry-wc-city-select'),
		_x('Opstina Krupanj', 'MA', 'ry-wc-city-select'),
		_x('Opstina Ljubovija', 'MA', 'ry-wc-city-select'),
		_x('Opstina Loznica', 'MA', 'ry-wc-city-select'),
		_x('Opstina Mali Zvornik', 'MA', 'ry-wc-city-select'),
		_x('Opstina Sabac-grad', 'MA', 'ry-wc-city-select'),
		_x('Opstina Vladimirci', 'MA', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Opstina Cacak-grad', 'MO', 'ry-wc-city-select'),
		_x('Opstina Gornji Milanovac', 'MO', 'ry-wc-city-select'),
		_x('Opstina Ivanjica', 'MO', 'ry-wc-city-select'),
		_x('Opstina Lucani', 'MO', 'ry-wc-city-select'),
	],
	'NI' => [
		_x('Opstina Aleksinac', 'NI', 'ry-wc-city-select'),
		_x('Opstina Doljevac', 'NI', 'ry-wc-city-select'),
		_x('Opstina Gadzin Han', 'NI', 'ry-wc-city-select'),
		_x('Opstina Merosina', 'NI', 'ry-wc-city-select'),
		_x('Opstina Nis-Crveni Krst', 'NI', 'ry-wc-city-select'),
		_x('Opstina Nis-Medijana', 'NI', 'ry-wc-city-select'),
		_x('Opstina Nis-Palilula', 'NI', 'ry-wc-city-select'),
		_x('Opstina Nis-Pantelej', 'NI', 'ry-wc-city-select'),
		_x('Opstina Niska Banja', 'NI', 'ry-wc-city-select'),
		_x('Opstina Razanj', 'NI', 'ry-wc-city-select'),
		_x('Opstina Svrljig', 'NI', 'ry-wc-city-select'),
	],
	'NOBA' => [
		_x('Opstina Backa Topola', 'NOBA', 'ry-wc-city-select'),
		_x('Opstina Mali Idos', 'NOBA', 'ry-wc-city-select'),
		_x('Opstina Subotica', 'NOBA', 'ry-wc-city-select'),
	],
	'NOBA2' => [
		_x('Opstina Ada', 'NOBA2', 'ry-wc-city-select'),
		_x('Opstina Coka', 'NOBA2', 'ry-wc-city-select'),
		_x('Opstina Kanjiza', 'NOBA2', 'ry-wc-city-select'),
		_x('Opstina Kikinda', 'NOBA2', 'ry-wc-city-select'),
		_x('Opstina Novi Knezevac', 'NOBA2', 'ry-wc-city-select'),
		_x('Opstina Senta', 'NOBA2', 'ry-wc-city-select'),
	],
	'PC' => [
		_x('Opstina Bosilegrad', 'PC', 'ry-wc-city-select'),
		_x('Opstina Bujanovac', 'PC', 'ry-wc-city-select'),
		_x('Opstina Presevo', 'PC', 'ry-wc-city-select'),
		_x('Opstina Surdulica', 'PC', 'ry-wc-city-select'),
		_x('Opstina Trgoviste', 'PC', 'ry-wc-city-select'),
		_x('Opstina Vladicin Han', 'PC', 'ry-wc-city-select'),
		_x('Opstina Vranje', 'PC', 'ry-wc-city-select'),
		_x('Opstina Vranjska Banja', 'PC', 'ry-wc-city-select'),
	],
	'PI' => [
		_x('Opstina Babusnica', 'PI', 'ry-wc-city-select'),
		_x('Opstina Bela Palanka', 'PI', 'ry-wc-city-select'),
		_x('Opstina Dimitrovgrad', 'PI', 'ry-wc-city-select'),
		_x('Opstina Pirot', 'PI', 'ry-wc-city-select'),
	],
	'PODI' => [
		_x('Opstina Smederevo', 'PODI', 'ry-wc-city-select'),
		_x('Opstina Smederevska Palanka', 'PODI', 'ry-wc-city-select'),
		_x('Opstina Velika Plana', 'PODI', 'ry-wc-city-select'),
	],
	'PO' => [
		_x('Opstina Cuprija', 'PO', 'ry-wc-city-select'),
		_x('Opstina Despotovac', 'PO', 'ry-wc-city-select'),
		_x('Opstina Jagodina', 'PO', 'ry-wc-city-select'),
		_x('Opstina Paracin', 'PO', 'ry-wc-city-select'),
		_x('Opstina Rekovac', 'PO', 'ry-wc-city-select'),
		_x('Opstina Svilajnac', 'PO', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Opstina Aleksandrovac', 'RA', 'ry-wc-city-select'),
		_x('Opstina Brus', 'RA', 'ry-wc-city-select'),
		_x('Opstina Cicevac', 'RA', 'ry-wc-city-select'),
		_x('Opstina Krusevac-grad', 'RA', 'ry-wc-city-select'),
		_x('Opstina Trstenik', 'RA', 'ry-wc-city-select'),
		_x('Opstina Varvarin', 'RA', 'ry-wc-city-select'),
	],
	'RA2' => [
		_x('Opstina Kraljevo', 'RA2', 'ry-wc-city-select'),
		_x('Opstina Novi Pazar', 'RA2', 'ry-wc-city-select'),
		_x('Opstina Raska', 'RA2', 'ry-wc-city-select'),
		_x('Opstina Tutin', 'RA2', 'ry-wc-city-select'),
		_x('Opstina Vrnjacka Banja', 'RA2', 'ry-wc-city-select'),
	],
	'SOBA' => [
		_x('Opstina Bac', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Backa Palanka', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Backi Petrovac', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Becej', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Beocin', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Novi Sad', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Petrovaradin', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Srbobran', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Sremski Karlovci', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Temerin', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Titel', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Vrbas', 'SOBA', 'ry-wc-city-select'),
		_x('Opstina Zabalj', 'SOBA', 'ry-wc-city-select'),
	],
	'SOBA2' => [
		_x('Opstina Alibunar', 'SOBA2', 'ry-wc-city-select'),
		_x('Opstina Bela Crkva', 'SOBA2', 'ry-wc-city-select'),
		_x('Opstina Kovacica', 'SOBA2', 'ry-wc-city-select'),
		_x('Opstina Kovin', 'SOBA2', 'ry-wc-city-select'),
		_x('Opstina Opovo', 'SOBA2', 'ry-wc-city-select'),
		_x('Opstina Plandiste', 'SOBA2', 'ry-wc-city-select'),
		_x('Opstina Vrsac', 'SOBA2', 'ry-wc-city-select'),
		_x('Pancevo-grad', 'SOBA2', 'ry-wc-city-select'),
	],
	'SR' => [
		_x('Opstina Indija', 'SR', 'ry-wc-city-select'),
		_x('Opstina Irig', 'SR', 'ry-wc-city-select'),
		_x('Opstina Pecinci', 'SR', 'ry-wc-city-select'),
		_x('Opstina Ruma', 'SR', 'ry-wc-city-select'),
		_x('Opstina Sid', 'SR', 'ry-wc-city-select'),
		_x('Opstina Sremska Mitrovica', 'SR', 'ry-wc-city-select'),
		_x('Opstina Stara Pazova', 'SR', 'ry-wc-city-select'),
	],
	'SU' => [
		_x('Opstina Arandelovac', 'SU', 'ry-wc-city-select'),
		_x('Opstina Batocina', 'SU', 'ry-wc-city-select'),
		_x('Opstina Knic', 'SU', 'ry-wc-city-select'),
		_x('Opstina Kragujevac', 'SU', 'ry-wc-city-select'),
		_x('Opstina Lapovo', 'SU', 'ry-wc-city-select'),
		_x('Opstina Raca', 'SU', 'ry-wc-city-select'),
		_x('Opstina Topola', 'SU', 'ry-wc-city-select'),
	],
	'TO' => [
		_x('Opstina Blace', 'TO', 'ry-wc-city-select'),
		_x('Opstina Kursumlija', 'TO', 'ry-wc-city-select'),
		_x('Opstina Prokuplje', 'TO', 'ry-wc-city-select'),
		_x('Opstina Zitoraga', 'TO', 'ry-wc-city-select'),
	],
	'WEBA' => [
		_x('Opstina Apatin', 'WEBA', 'ry-wc-city-select'),
		_x('Opstina Kula', 'WEBA', 'ry-wc-city-select'),
		_x('Opstina Odzaci', 'WEBA', 'ry-wc-city-select'),
		_x('Opstina Sombor', 'WEBA', 'ry-wc-city-select'),
	],
	'ZA' => [
		_x('Opstina Boljevac', 'ZA', 'ry-wc-city-select'),
		_x('Opstina Knjazevac', 'ZA', 'ry-wc-city-select'),
		_x('Opstina Sokobanja', 'ZA', 'ry-wc-city-select'),
		_x('Zajeear-grad', 'ZA', 'ry-wc-city-select'),
	],
	'ZL' => [
		_x('Opstina Arilje', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Bajina Basta', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Cajetina', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Kosjeric', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Nova Varos', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Pozega', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Priboj', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Prijepolje', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Sjenica', 'ZL', 'ry-wc-city-select'),
		_x('Opstina Uzice-grad', 'ZL', 'ry-wc-city-select'),
	],
	]
];