<?php
/**
 * Russian Federation places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'RU' => [
	'AGBUOK' => [
		_x('Aginskiy Rayon', 'AGBUOK', 'ry-wc-city-select'),
		_x('Duldurginskiy Rayon', 'AGBUOK', 'ry-wc-city-select'),
		_x('Mogoytuyskiy Rayon', 'AGBUOK', 'ry-wc-city-select'),
	],
	'BAUROK' => [
		_x('Industrialnyy Rayon', 'BAUROK', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'BAUROK', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'BAUROK', 'ry-wc-city-select'),
		_x('Tsentralnyy Rayon', 'BAUROK', 'ry-wc-city-select'),
		_x('Zheleznodorozhnyy Rayon', 'BAUROK', 'ry-wc-city-select'),
	],
	'EAADOK' => [
		_x('Bogorodskoye District', 'EAADOK', 'ry-wc-city-select'),
		_x('Golyanovo District', 'EAADOK', 'ry-wc-city-select'),
		_x('Ivanovskoye District', 'EAADOK', 'ry-wc-city-select'),
		_x('Izmaylovo District', 'EAADOK', 'ry-wc-city-select'),
		_x('Kosino-Ukhtomsky District', 'EAADOK', 'ry-wc-city-select'),
		_x('Metrogorodok District', 'EAADOK', 'ry-wc-city-select'),
		_x('Novogireyevo District', 'EAADOK', 'ry-wc-city-select'),
		_x('Novokosino District', 'EAADOK', 'ry-wc-city-select'),
		_x('Preobrazhenskoye District', 'EAADOK', 'ry-wc-city-select'),
		_x('Severnoye Izmaylovo District', 'EAADOK', 'ry-wc-city-select'),
		_x('Sokolinaya gora District', 'EAADOK', 'ry-wc-city-select'),
		_x('Sokolniki District', 'EAADOK', 'ry-wc-city-select'),
		_x('Veshnyaki District', 'EAADOK', 'ry-wc-city-select'),
		_x('Vostochnoye Izmaylovo District', 'EAADOK', 'ry-wc-city-select'),
		_x('Vostochny District', 'EAADOK', 'ry-wc-city-select'),
	],
	'GOAS' => [
		_x('Sovetskiy Rayon', 'GOAS', 'ry-wc-city-select'),
		_x('Trusovskiy Rayon', 'GOAS', 'ry-wc-city-select'),
	],
	'GOKA' => [
		_x('Aviastroitelnyy Rayon', 'GOKA', 'ry-wc-city-select'),
		_x('Baumanskiy Rayon', 'GOKA', 'ry-wc-city-select'),
		_x('Kirovskiy Rayon', 'GOKA', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'GOKA', 'ry-wc-city-select'),
		_x('Moskovskiy Rayon', 'GOKA', 'ry-wc-city-select'),
		_x('Privolzhskiy Rayon', 'GOKA', 'ry-wc-city-select'),
		_x('Rayon Novo-Savinovskiy', 'GOKA', 'ry-wc-city-select'),
		_x('Sovetskiy Rayon', 'GOKA', 'ry-wc-city-select'),
		_x('Vakhitovskiy Rayon', 'GOKA', 'ry-wc-city-select'),
	],
	'GONACH' => [
		_x('Avtozavodskiy Rayon', 'GONACH', 'ry-wc-city-select'),
	],
	'GRUROK' => [
		_x('Leninskiy Rayon', 'GRUROK', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'GRUROK', 'ry-wc-city-select'),
		_x('Staropromyslovskiy Rayon', 'GRUROK', 'ry-wc-city-select'),
		_x('Zavodskoy Rayon', 'GRUROK', 'ry-wc-city-select'),
	],
	'NINOUROK' => [
		_x('Avtozavodskiy Rayon', 'NINOUROK', 'ry-wc-city-select'),
		_x('Kanavinskiy Rayon', 'NINOUROK', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'NINOUROK', 'ry-wc-city-select'),
		_x('Moskovskiy Rayon', 'NINOUROK', 'ry-wc-city-select'),
		_x('Nizhegorodskiy Rayon', 'NINOUROK', 'ry-wc-city-select'),
		_x('Priokskiy Rayon', 'NINOUROK', 'ry-wc-city-select'),
		_x('Sormovskiy Rayon', 'NINOUROK', 'ry-wc-city-select'),
		_x('Sovetskiy Rayon', 'NINOUROK', 'ry-wc-city-select'),
	],
	'NORA' => [
		_x('Zheleznodorozhnyy Rayon', 'NORA', 'ry-wc-city-select'),
	],
	'SEADOK' => [
		_x('Aeroport District', 'SEADOK', 'ry-wc-city-select'),
		_x('Begovoy District', 'SEADOK', 'ry-wc-city-select'),
		_x('Beskudnikovo', 'SEADOK', 'ry-wc-city-select'),
		_x('Dmitrovsky District', 'SEADOK', 'ry-wc-city-select'),
		_x('Golovinsky District', 'SEADOK', 'ry-wc-city-select'),
		_x('Khoroshyovsky District', 'SEADOK', 'ry-wc-city-select'),
		_x('Khovrino District', 'SEADOK', 'ry-wc-city-select'),
		_x('Koptevo District', 'SEADOK', 'ry-wc-city-select'),
		_x('Levoberezhny District', 'SEADOK', 'ry-wc-city-select'),
		_x('Otradnoye District', 'SEADOK', 'ry-wc-city-select'),
		_x('Savyolovsky District', 'SEADOK', 'ry-wc-city-select'),
		_x('Sokol District', 'SEADOK', 'ry-wc-city-select'),
		_x('Timiryazevsky District', 'SEADOK', 'ry-wc-city-select'),
		_x('Vostochnoye Degunino District', 'SEADOK', 'ry-wc-city-select'),
		_x('Voykovsky District', 'SEADOK', 'ry-wc-city-select'),
		_x('Zapadnoye Degunino District', 'SEADOK', 'ry-wc-city-select'),
	],
	'SEADOK2' => [
		_x('Alexeyevsky District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Altufyevsky District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Babushkinsky District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Bibirevo District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Butyrsky District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Lianozovo District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Losinoostrovsky District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Maryina Roshcha District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Ostankinsky District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Rostokino District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Severnoye Medvedkovo District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Severny District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Sviblovo District', 'SEADOK2', 'ry-wc-city-select'),
		_x('Yaroslavsky District', 'SEADOK2', 'ry-wc-city-select'),
	],
	'SEADOK3' => [
		_x('Khoroshevo-Mnevniki District', 'SEADOK3', 'ry-wc-city-select'),
		_x('Kurkino District', 'SEADOK3', 'ry-wc-city-select'),
		_x('Mitino District', 'SEADOK3', 'ry-wc-city-select'),
		_x('Pokrovskoye-Streshnevo District', 'SEADOK3', 'ry-wc-city-select'),
		_x('Severnoye Tushino District', 'SEADOK3', 'ry-wc-city-select'),
		_x('Shchukino District', 'SEADOK3', 'ry-wc-city-select'),
		_x('Strogino District', 'SEADOK3', 'ry-wc-city-select'),
		_x('Yuzhnoye Tushino District', 'SEADOK3', 'ry-wc-city-select'),
	],
	'TSADOK' => [
		_x('Arbat District', 'TSADOK', 'ry-wc-city-select'),
		_x('Basmanny District', 'TSADOK', 'ry-wc-city-select'),
		_x('Khamovniki District', 'TSADOK', 'ry-wc-city-select'),
		_x('Krasnoselsky District', 'TSADOK', 'ry-wc-city-select'),
		_x('Meshchansky District', 'TSADOK', 'ry-wc-city-select'),
		_x('Presnensky District', 'TSADOK', 'ry-wc-city-select'),
		_x('Tagansky District', 'TSADOK', 'ry-wc-city-select'),
		_x('Tverskoy District', 'TSADOK', 'ry-wc-city-select'),
		_x('Yakimanka District', 'TSADOK', 'ry-wc-city-select'),
		_x('Zamoskvorechye District', 'TSADOK', 'ry-wc-city-select'),
	],
	'TURA' => [
		_x('Komsomolsky Rayon', 'TURA', 'ry-wc-city-select'),
	],
	'YUADOK' => [
		_x('Kapotnya District', 'YUADOK', 'ry-wc-city-select'),
		_x('Kuzminki District', 'YUADOK', 'ry-wc-city-select'),
		_x('Lefortovo District', 'YUADOK', 'ry-wc-city-select'),
		_x('Lyublino District', 'YUADOK', 'ry-wc-city-select'),
		_x('Maryino District', 'YUADOK', 'ry-wc-city-select'),
		_x('Nekrasovka District', 'YUADOK', 'ry-wc-city-select'),
		_x('Nizhegorodsky District', 'YUADOK', 'ry-wc-city-select'),
		_x('Pechatniki District', 'YUADOK', 'ry-wc-city-select'),
		_x('Ryazansky District', 'YUADOK', 'ry-wc-city-select'),
		_x('Tekstilshchiki District', 'YUADOK', 'ry-wc-city-select'),
		_x('Vykhino-Zhulebino District', 'YUADOK', 'ry-wc-city-select'),
		_x('Yuzhnoportovy District', 'YUADOK', 'ry-wc-city-select'),
	],
	'YUADOK2' => [
		_x('Akademichesky District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Cheryomushki District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Gagarinsky District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Konkovo District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Kotlovka District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Lomonosovsky District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Obruchevsky District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Severnoye Butovo District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Tyoply Stan District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Yasenevo District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Yuzhnoye Butovo District', 'YUADOK2', 'ry-wc-city-select'),
		_x('Zyuzino District', 'YUADOK2', 'ry-wc-city-select'),
	],
	'YUADOK3' => [
		_x('Biryulyovo Vostochnoye District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Biryulyovo Zapadnoye District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Brateyevo District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Chertanovo Severnoye District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Chertanovo Tsentralnoye District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Chertanovo Yuzhnoye District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Danilovsky District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Donskoy District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Moskvorechye-Saburovo District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Nagatino-Sadovniki District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Nagatinsky Zaton District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Nagorny District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Orekhovo-Borisovo Severnoye District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Orekhovo-Borisovo Yuzhnoye District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Tsaritsyno District', 'YUADOK3', 'ry-wc-city-select'),
		_x('Zyablikovo District', 'YUADOK3', 'ry-wc-city-select'),
	],
	'ZAADOK' => [
		_x('Dorogomilovo District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Fili-Davydkovo District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Filyovsky park District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Krylatskoye District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Kuntsevo District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Mozhaysky District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Novo-Peredelkino District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Ochakovo-Matveyevskoye District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Prospekt Vernadskogo District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Ramenki District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Solntsevo District', 'ZAADOK', 'ry-wc-city-select'),
		_x('Vnukovo', 'ZAADOK', 'ry-wc-city-select'),
	],
	'ZEADOK' => [
		_x('Kryukovo District', 'ZEADOK', 'ry-wc-city-select'),
		_x('Matushkino District', 'ZEADOK', 'ry-wc-city-select'),
		_x('Silino District', 'ZEADOK', 'ry-wc-city-select'),
		_x('Staroye Kryukovo District', 'ZEADOK', 'ry-wc-city-select'),
	],
	'ALKR' => [
		_x('Aleyskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Altayskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Bayevskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Biyskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Blagoveshchenskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Burlinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Bystroistokskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Charyshskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Kalmanskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Kamenskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Khabarskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Klyuchevskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Kosikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Krasnogorskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Krasnoshchekovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Krutikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Kulundinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Kurinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Kytmanovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Loktevskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Mamontovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Mikhaylovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Natsionalnyy Rayon Nemetskiy', 'ALKR', 'ry-wc-city-select'),
		_x('Novichikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Pankrushikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Pavlovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Pervomayskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Petropavlovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Pospelikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Rebrikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Rodinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Romanovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Rubtsovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Shelabolikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Shipunovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Slavgorodskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Smolenskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Soloneshenskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Soltonskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Sovetskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Suyetskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Tabunskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Talmenskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Togulskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Topchikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Tretyakovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Troitskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Tselinnyy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Tyumentsevskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Uglovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Ust-Kalmanskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Ust-Pristanskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Volchikhinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Yegoryevskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Yeltsovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Zalesovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Zarinskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Zavyalovskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Zmeinogorskiy Rayon', 'ALKR', 'ry-wc-city-select'),
		_x('Zonalnyy Rayon', 'ALKR', 'ry-wc-city-select'),
	],
	'AMOB' => [
		_x('Arkharinskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Belogorskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Blagoveshchenskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Bureyskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Gorod Blagoveshchensk', 'AMOB', 'ry-wc-city-select'),
		_x('Gorod Raychikhinsk', 'AMOB', 'ry-wc-city-select'),
		_x('Ivanovskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Konstantinovskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Magdagachinskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Mazanovskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Mikhaylovskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Romnenskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Selemdzhinskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Seryshevskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Shimanovskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Skovorodinskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Svobodnenskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Tambovskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Tyndinskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Zavitinskiy Rayon', 'AMOB', 'ry-wc-city-select'),
		_x('Zeyskiy Rayon', 'AMOB', 'ry-wc-city-select'),
	],
	'AROB' => [
		_x('Kargopolskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Kholmogorskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Konoshskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Kotlasskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Krasnoborskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Lenskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Leshukonskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Mezenskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Nyandomskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Onezhskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Pinezhskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Primorskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Shenkurskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Ustyanskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Velskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Verkhnetoyemskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Vilegodskiy Rayon', 'AROB', 'ry-wc-city-select'),
		_x('Vinogradovskiy Rayon', 'AROB', 'ry-wc-city-select'),
	],
	'ASOB' => [
		_x('Akhtubinskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Chernoyarskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Ikryaninskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Kamyzyakskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Kharabalinskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Krasnoyarskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Limanskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Narimanovskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Privolzhskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Volodarskiy Rayon', 'ASOB', 'ry-wc-city-select'),
		_x('Yenotayevskiy Rayon', 'ASOB', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Abzelilovskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Alsheyevskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Arkhangelskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Askinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Aurgazinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Bakalinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Baltachevskiy rayon', 'BA', 'ry-wc-city-select'),
		_x('Baymakskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Belebeyevskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Belokatayskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Beloretskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Birskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Bizhbulyakskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Blagovarskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Blagoveshchenskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Burayevskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Burzyanskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Buzdyakskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Chekmagushevskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Chishminskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Davlekanovskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Duvanskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Dyurtyulinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Fedorovskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Gafuriyskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Iglinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Ilishevskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Ishimbayskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Kaltasinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Karaidelskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Karmaskalinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Khaybullinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Kiginskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Krasnokamskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Kugarchinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Kumertau Urban Okrug', 'BA', 'ry-wc-city-select'),
		_x('Kushnarenkovskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Mechetlinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Meleuzovskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Mishkinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Miyakinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Nurimanovskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Salavatskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Sharanskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Sterlibashevskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Sterlitamakskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Tatyshlinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Tuymazinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Uchalinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Ufimskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Yanaulskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Yermekeyevskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Zianchurinskiy Rayon', 'BA', 'ry-wc-city-select'),
		_x('Zilairskiy Rayon', 'BA', 'ry-wc-city-select'),
	],
	'BEOB' => [
		_x('Alekseyevskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Belgorodskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Borisovskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Chernyanskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Gorod Alekseyevka', 'BEOB', 'ry-wc-city-select'),
		_x('Grayvoronskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Gubkinsky Urban Okrug', 'BEOB', 'ry-wc-city-select'),
		_x('Ivnyanskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Korochanskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Krasnenskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Krasnogvardeyskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Krasnoyaruzhskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Novooskolskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Prokhorovskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Rakityanskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Rovenskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Shebekinskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Starooskolsky Urban Okrug', 'BEOB', 'ry-wc-city-select'),
		_x('Valuyskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Veydelevskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Volokonovskiy Rayon', 'BEOB', 'ry-wc-city-select'),
		_x('Yakovlevskiy Rayon', 'BEOB', 'ry-wc-city-select'),
	],
	'BROB' => [
		_x('Brasovskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Bryanskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Dubrovskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Dyatkovskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Gordeyevskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Gorod Bryansk', 'BROB', 'ry-wc-city-select'),
		_x('Gorod Dyatkovo', 'BROB', 'ry-wc-city-select'),
		_x('Gorod Novozybkov', 'BROB', 'ry-wc-city-select'),
		_x('Karachevskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Kletnyanskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Klimovskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Klintsovskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Komarichskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Krasnogorskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Mglinskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Navlinskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Novozybkovskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Pochepskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Pogarskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Rognedinskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Sevskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Starodubskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Surazhskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Suzemskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Trubchevskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Unechskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Vygonichskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Zhiryatinskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Zhukovskiy Rayon', 'BROB', 'ry-wc-city-select'),
		_x('Zlynkovskiy Rayon', 'BROB', 'ry-wc-city-select'),
	],
	'CHRE' => [
		_x('Achkhoy-Martanovskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Groznenskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Gudermesskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Itum-Kalinskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Kurchaloyevskiy rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Nadterechnyy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Naurskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Nozhay-Yurtovskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Shalinskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Shelkovskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Urus-Martanovskiy Rayon', 'CHRE', 'ry-wc-city-select'),
		_x('Vedenskiy Rayon', 'CHRE', 'ry-wc-city-select'),
	],
	'CHOB' => [
		_x('Agapovskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Argayashskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Ashinskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Bredinskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Chebarkulskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Chesmenskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Chelyabinsk', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Karabash', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Kopeysk', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Kyshtym', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Magnitogorsk', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Miass', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Ust-Katav', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Verkhniy Ufaley', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Yuzhnouralsk', 'CHOB', 'ry-wc-city-select'),
		_x('Gorod Zlatoust', 'CHOB', 'ry-wc-city-select'),
		_x('Kartalinskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Kaslinskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Katav-Ivanovskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Kizilskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Korkinskij rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Krasnoarmeyskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Kunashakskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Kusinskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Nagaybakskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Nyazepetrovskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Plastovskij rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Satkinskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Sosnovskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Troitskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Uvelskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Uyskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Varnenskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Verkhneuralskiy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Yemanzhelinskiy rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Yetkulskiy Rayon', 'CHOB', 'ry-wc-city-select'),
	],
	'CHAVOK' => [
		_x('Anadyrskiy Rayon', 'CHAVOK', 'ry-wc-city-select'),
		_x('Bilibinskiy Rayon', 'CHAVOK', 'ry-wc-city-select'),
		_x('Chaunskiy Rayon', 'CHAVOK', 'ry-wc-city-select'),
		_x('Chukotskiy Rayon', 'CHAVOK', 'ry-wc-city-select'),
		_x('Iultinskiy Rayon', 'CHAVOK', 'ry-wc-city-select'),
		_x('Providenskiy Rayon', 'CHAVOK', 'ry-wc-city-select'),
	],
	'CHRE2' => [
		_x('Alatyrskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Alikovskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Batyrevskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Cheboksarskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Ibresinskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Kanashskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Komsomolskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Kozlovskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Krasnoarmeyskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Krasnochetayskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Mariinsko-Posadskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Morgaushskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Poretskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Shemurshinskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Shumerlinskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Tsivilskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Urmarskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Vurnarskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Yadrinskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Yalchikskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
		_x('Yantikovskiy Rayon', 'CHRE2', 'ry-wc-city-select'),
	],
	'DA' => [
		_x('Agulskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Akhtynskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Akhvakhskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Akushinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Babayurtovskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Bezhtinskiy Uchastok Rayon', 'DA', 'ry-wc-city-select'),
		_x('Botlikhskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Buynakskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Charodinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Dakhadayevskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Derbentskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Dokuzparinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Gergebilsky', 'DA', 'ry-wc-city-select'),
		_x('Gorod Buynaksk', 'DA', 'ry-wc-city-select'),
		_x('Gorod Dagestanskiye Ogni', 'DA', 'ry-wc-city-select'),
		_x('Gorod Derbent', 'DA', 'ry-wc-city-select'),
		_x('Gorod Izberbash', 'DA', 'ry-wc-city-select'),
		_x('Gorod Kaspiysk', 'DA', 'ry-wc-city-select'),
		_x('Gorod Kizlyar', 'DA', 'ry-wc-city-select'),
		_x('Gorod Makhachkala', 'DA', 'ry-wc-city-select'),
		_x('Gorod Yuzhno-Sukhokumsk', 'DA', 'ry-wc-city-select'),
		_x('Gumbetovskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Gunibskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Karabudakhkentskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Kayakentskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Kaytagskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Kazbekovskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Khasavyurtovskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Khivskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Khunzakhskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Kizilyurtovskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Kizlyarskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Kulinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Kumtorkalinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Kurakhskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Lakskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Levashinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Magaramkentskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Nogayskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Novolakskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Rutulskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Sergokalinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Shamilsky District', 'DA', 'ry-wc-city-select'),
		_x('Suleyman-Stalskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Tabasaranskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Tarumovskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Tlyaratinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Tsumadinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Tsuntinskiy Rayon', 'DA', 'ry-wc-city-select'),
		_x('Untsukulsky District', 'DA', 'ry-wc-city-select'),
	],
	'IROB' => [
		_x('Alarskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Angarskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Balaganskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Bayandayevskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Bodaybinskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Bokhanskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Bratsk Urban Okrug', 'IROB', 'ry-wc-city-select'),
		_x('Bratskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Cheremkhovskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Chunskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Ekhirit-Bulagatskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Irkutskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Kachugskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Katangskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Kazachinsko-Lenskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Kirenskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Kuytunskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Mamsko-Chuyskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Nizhneilimskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Nizhneudinskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Nukutskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Olkhonskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Osinskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Shelekhovskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Slyudyanskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Tayshetskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Tulunskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Usolskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Ust-Ilimskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Ust-Kutskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Ust-Udinskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Zalarinskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Zhigalovskiy Rayon', 'IROB', 'ry-wc-city-select'),
		_x('Ziminskiy Rayon', 'IROB', 'ry-wc-city-select'),
	],
	'IVOB' => [
		_x('Furmanovskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Gavrilovo-Posadskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Gorod Furmanovo', 'IVOB', 'ry-wc-city-select'),
		_x('Gorod Ivanovo', 'IVOB', 'ry-wc-city-select'),
		_x('Gorod Kineshma', 'IVOB', 'ry-wc-city-select'),
		_x('Gorod Shuya', 'IVOB', 'ry-wc-city-select'),
		_x('Gorod Teykovo', 'IVOB', 'ry-wc-city-select'),
		_x('Gorod Vichuga', 'IVOB', 'ry-wc-city-select'),
		_x('Ilinskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Ivanovskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Kineshemskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Komsomolskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Lezhnevskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Lukhskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Palekhskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Pestyakovskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Privolzhskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Puchezhskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Rodnikovskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Savinskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Shuyskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Teykovskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Verkhnelandekhovskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Vichugskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Yuryevetskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Yuzhskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Zavolzhskiy Rayon', 'IVOB', 'ry-wc-city-select'),
	],
	'KARE' => [
		_x('Baksanskiy Rayon', 'KARE', 'ry-wc-city-select'),
		_x('Chegemskiy Rayon', 'KARE', 'ry-wc-city-select'),
		_x('Cherekskiy Rayon', 'KARE', 'ry-wc-city-select'),
		_x('Elbrusskiy Rayon', 'KARE', 'ry-wc-city-select'),
		_x('Leskenskiy rayon', 'KARE', 'ry-wc-city-select'),
		_x('Mayskiy Rayon', 'KARE', 'ry-wc-city-select'),
		_x('Nalchik Urban Okrug', 'KARE', 'ry-wc-city-select'),
		_x('Prokhladnenskiy Rayon', 'KARE', 'ry-wc-city-select'),
		_x('Terskiy Rayon', 'KARE', 'ry-wc-city-select'),
		_x('Urvanskiy Rayon', 'KARE', 'ry-wc-city-select'),
		_x('Zolskiy Rayon', 'KARE', 'ry-wc-city-select'),
	],
	'KAOB' => [
		_x('Bagrationovskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Chernyakhovskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Gorod Baltiysk', 'KAOB', 'ry-wc-city-select'),
		_x('Gorod Kaliningrad', 'KAOB', 'ry-wc-city-select'),
		_x('Gorod Neman', 'KAOB', 'ry-wc-city-select'),
		_x('Gorod Pionerskiy', 'KAOB', 'ry-wc-city-select'),
		_x('Gorod Sovetsk', 'KAOB', 'ry-wc-city-select'),
		_x('Gorod Svetlogorsk', 'KAOB', 'ry-wc-city-select'),
		_x('Gorod Svetlyy', 'KAOB', 'ry-wc-city-select'),
		_x('Guryevskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Gusevskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Gvardeyskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Krasnoznamenskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Nemanskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Nesterovskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Ozerskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Polesskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Pravdinskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Slavskiy Rayon', 'KAOB', 'ry-wc-city-select'),
		_x('Zelenogradskiy Rayon', 'KAOB', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Chernozemelskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Elista Urban Okrug', 'KA', 'ry-wc-city-select'),
		_x('Gorodovikovskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Iki-Burulskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Ketchenerovskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Laganskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Maloderbetovskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Priyutnenskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Sarpinskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Tselinnyy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Yashaltinskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Yashkulskiy Rayon', 'KA', 'ry-wc-city-select'),
		_x('Yustinskiy Rayon', 'KA', 'ry-wc-city-select'),
	],
	'KAOB2' => [
		_x('Babyninskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Baryatinskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Borovskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Duminichskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Dzerzhinskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Ferzikovskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Iznoskovskiy rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Khvastovichskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Kirovskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Kozelskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Kuybyshevskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Lyudinovskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Maloyaroslavetskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Medynskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Meshchovskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Mosalskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Peremyshlskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Spas-Demenskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Sukhinichskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Tarusskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Ulyanovskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Yukhnovskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Zhizdrinskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
		_x('Zhukovskiy Rayon', 'KAOB2', 'ry-wc-city-select'),
	],
	'KAKR' => [
		_x('Aleutskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Bystrinskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Karaginsky District', 'KAKR', 'ry-wc-city-select'),
		_x('Milkovskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Olyutorskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Penzhinskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Sobolevskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Tigilskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Ust-Bolsheretskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Ust-Kamchatskiy Rayon', 'KAKR', 'ry-wc-city-select'),
		_x('Yelizovskiy Rayon', 'KAKR', 'ry-wc-city-select'),
	],
	'KA2' => [
		_x('Adyge-Khablskiy Rayon', 'KA2', 'ry-wc-city-select'),
		_x('Karachayevskiy Rayon', 'KA2', 'ry-wc-city-select'),
		_x('Khabezskiy Rayon', 'KA2', 'ry-wc-city-select'),
		_x('Malokarachayevskiy Rayon', 'KA2', 'ry-wc-city-select'),
		_x('Nogayskiy rayon', 'KA2', 'ry-wc-city-select'),
		_x('Prikubanskiy Rayon', 'KA2', 'ry-wc-city-select'),
		_x('Urupskiy Rayon', 'KA2', 'ry-wc-city-select'),
		_x('Ust-Dzhegutinskiy Rayon', 'KA2', 'ry-wc-city-select'),
		_x('Zelenchukskiy Rayon', 'KA2', 'ry-wc-city-select'),
	],
	'KEOB' => [
		_x('Belovskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Chebulinskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Guryevskiy rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Izhmorskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Kemerovskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Krapivinskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Leninsk-Kuznetskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Mariinskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Novokuznetskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Prokopyevskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Promyshlennovskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Tashtagolskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Tisulskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Topkinskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Tyazhinskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Yashkinskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Yayskiy Rayon', 'KEOB', 'ry-wc-city-select'),
		_x('Yurginskiy Rayon', 'KEOB', 'ry-wc-city-select'),
	],
	'KHKR' => [
		_x('Amurskiy Rayon', 'KHKR', 'ry-wc-city-select'),
		_x('Bikinskiy Rayon', 'KHKR', 'ry-wc-city-select'),
		_x('Khabarovskiy Rayon', 'KHKR', 'ry-wc-city-select'),
		_x('Tuguro-Chumikanskiy Rayon', 'KHKR', 'ry-wc-city-select'),
		_x('Ulchskiy Rayon', 'KHKR', 'ry-wc-city-select'),
		_x('Vaninskiy Rayon', 'KHKR', 'ry-wc-city-select'),
		_x('Verkhnebureinskiy Rayon', 'KHKR', 'ry-wc-city-select'),
		_x('Vyazemskiy Rayon', 'KHKR', 'ry-wc-city-select'),
	],
	'KIOB' => [
		_x('Afanasyevskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Arbazhskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Belokholunitskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Bogorodskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Darovskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Falenskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Kiknurskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Kilmezskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Kirovo-Chepetskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Kotelnichskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Kumenskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Lebyazhskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Luzskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Malmyzhskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Murashinskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Nagorskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Nemskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Nolinskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Omutninskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Oparinskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Orichevskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Orlovskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Pizhanskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Podosinovskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Sanchurskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Shabalinskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Slobodskoy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Sovetskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Sunskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Svechinskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Tuzhinskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Uninskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Urzhumskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Verkhnekamskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Verkhoshizhemskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Vyatsko-Polyanskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Yaranskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Yuryanskiy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Zuyevskiy Rayon', 'KIOB', 'ry-wc-city-select'),
	],
	'KO' => [
		_x('Izhemskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Knyazhpogostskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Kortkerosskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Koygorodskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Priluzskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Syktyvdinskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Sysolskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Troitsko-Pechorskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Udorskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Ust-Kulomskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Ust-Tsilemskiy Rayon', 'KO', 'ry-wc-city-select'),
		_x('Ust-Vymskiy Rayon', 'KO', 'ry-wc-city-select'),
	],
	'KOOB' => [
		_x('Antropovskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Buyskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Chukhlomskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Galichskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Kadyyskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Kologrivskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Kostromskoy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Krasnoselskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Makaryevskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Manturovskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Mezhevskoy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Nerekhtskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Neyskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Ostrovskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Parfenyevskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Pavinskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Ponazyrevskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Pyshchugskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Sharinskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Soligalichskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Sudislavskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Susaninskiy Rayon', 'KOOB', 'ry-wc-city-select'),
		_x('Vokhomskiy Rayon', 'KOOB', 'ry-wc-city-select'),
	],
	'KRKR' => [
		_x('Abinskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Anapskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Apsheronskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Beloglinskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Belorechenskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Bryukhovetskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Dinskoy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Gulkevichskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Kalininskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Kanevskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Kavkazskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Korenovskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Krasnoarmeyskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Krylovskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Krymskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Kurganinskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Kushchevskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Labinskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Leningradskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Mostovskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Novokubanskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Novopokrovskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Otradnenskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Pavlovskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Primorsko-Akhtarskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Severskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Shcherbinovskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Slavyansky rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Sochi City', 'KRKR', 'ry-wc-city-select'),
		_x('Starominskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Tbilisskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Temruksky rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Tikhoretskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Timashevskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Tuapsinskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Uspenskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Ust-Labinskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Vyselkovskiy Rayon', 'KRKR', 'ry-wc-city-select'),
		_x('Yeyskiy Rayon', 'KRKR', 'ry-wc-city-select'),
	],
	'KRKR2' => [
		_x('Abanskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Achinskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Balakhtinskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Berezovskiy rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Birilyusskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Bogotolskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Boguchanskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Bolshemurtinskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Bolsheuluyskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Dzerzhinskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Evenkiyskiy District', 'KRKR2', 'ry-wc-city-select'),
		_x('Idrinskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Ilanskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Irbeyskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Kanskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Karatuzskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Kazachinskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Kezhemskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Khatangskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Kozulskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Krasnoturanskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Kuraginskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Manskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Minusinskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Motyginskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Nazarovskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Nizhneingashskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Novoselovskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Partizanskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Pirovskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Rybinskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Sayanskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Severo-Yeniseyskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Sharypovskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Shushenskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Sukhobuzimskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Taseyevskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Taymyrsky Dolgano-Nenetsky District', 'KRKR2', 'ry-wc-city-select'),
		_x('Turukhanskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Tyukhtetskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Uyarskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Uzhurskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Yemelyanovskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Yeniseyskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
		_x('Yermakovskiy Rayon', 'KRKR2', 'ry-wc-city-select'),
	],
	'KUOB' => [
		_x('Almenevskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Belozerskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Chastoozerskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Dalmatovskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Kargapolskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Katayskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Ketovskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Kurtamyshskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Lebyazhyevskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Makushinskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Mishkinskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Mokrousovskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Petukhovskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Polovinskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Pritobolnyy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Safakulevskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Shadrinskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Shatrovskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Shchuchanskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Shumikhinskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Tselinnyy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Vargashinskiy Rayon', 'KUOB', 'ry-wc-city-select'),
		_x('Yurgamyshskiy Rayon', 'KUOB', 'ry-wc-city-select'),
	],
	'KUOB2' => [
		_x('Belovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Bolshesoldatskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Cheremisinovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Dmitriyevskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Fatezhskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Glushkovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Gorshechenskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Kastorenskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Khomutovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Konyshevskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Korenevskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Kurchatovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Kurskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Lgovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Manturovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Medvenskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Oboyanskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Ponyrovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Pristenskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Rylskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Shchigrovskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Solntsevskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Sovetskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Sudzhanskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Timskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Zheleznogorskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
		_x('Zolotukhinskiy Rayon', 'KUOB2', 'ry-wc-city-select'),
	],
	'LEOB' => [
		_x('Boksitogorskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Gatchinskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Kingiseppskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Kirishskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Kirovskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Lodeynopolskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Lomonosovskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Luzhskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Podporozhskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Priozersky', 'LEOB', 'ry-wc-city-select'),
		_x('Slantsevskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Sosnovoborsky Urban Okrug', 'LEOB', 'ry-wc-city-select'),
		_x('Tikhvinskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Tosnenskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Volkhovskiy rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Volosovskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Vsevolozhskiy Rayon', 'LEOB', 'ry-wc-city-select'),
		_x('Vyborgskiy Rayon', 'LEOB', 'ry-wc-city-select'),
	],
	'LIOB' => [
		_x('Chaplyginskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Dankovskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Dobrinskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Dobrovskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Dolgorukovskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Gryazinskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Izmalkovskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Khlevenskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Krasninskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Lebedyanskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Lev-Tolstovskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Lipetskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Stanovlyanskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Terbunskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Usmanskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Volovskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Yeletskiy Rayon', 'LIOB', 'ry-wc-city-select'),
		_x('Zadonskiy Rayon', 'LIOB', 'ry-wc-city-select'),
	],
	'MAOB' => [
		_x('Gorod Magadan', 'MAOB', 'ry-wc-city-select'),
		_x('Khasynskiy Rayon', 'MAOB', 'ry-wc-city-select'),
		_x('Olskiy Rayon', 'MAOB', 'ry-wc-city-select'),
		_x('Omsukchanskiy Rayon', 'MAOB', 'ry-wc-city-select'),
		_x('Severo-Evenskiy Rayon', 'MAOB', 'ry-wc-city-select'),
		_x('Srednekanskiy Rayon', 'MAOB', 'ry-wc-city-select'),
		_x('Susumanskiy Rayon', 'MAOB', 'ry-wc-city-select'),
		_x('Tenkinskiy Rayon', 'MAOB', 'ry-wc-city-select'),
		_x('Yagodninskiy Rayon', 'MAOB', 'ry-wc-city-select'),
	],
	'MOOB' => [
		_x('Balashikha Urban Okrug', 'MOOB', 'ry-wc-city-select'),
		_x('Chekhovskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Dmitrovskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Domodedovskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Istrinskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Kashira Urban Okrug', 'MOOB', 'ry-wc-city-select'),
		_x('Khimki Urban Okrug', 'MOOB', 'ry-wc-city-select'),
		_x('Klinskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Kolomenskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Korolyov', 'MOOB', 'ry-wc-city-select'),
		_x('Krasnogorskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Lotoshinskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Lukhovitskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Lyuberetskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Mozhayskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Mytishchi Urban Okrug', 'MOOB', 'ry-wc-city-select'),
		_x('Naro-Fominskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Noginskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Odintsovskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Orekhovo-Zuyevskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Ozyory Urban Okrug', 'MOOB', 'ry-wc-city-select'),
		_x('Pavlovo-Posadskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Podolsk Urban Okrug', 'MOOB', 'ry-wc-city-select'),
		_x('Pushkinskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Ramenskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Ruzskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Serebryano-Prudskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Sergiyevo-Posadskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Serpukhovskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Shakhovskoy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Shaturskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Shchelkovskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Solnechnogorskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Stupinskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Taldomskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Volokolamskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Voskresenskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Yegoryevskiy Rayon', 'MOOB', 'ry-wc-city-select'),
		_x('Zarayskiy Rayon', 'MOOB', 'ry-wc-city-select'),
	],
	'MO' => [
		_x('Novomoskovsky Administrative Okrug', 'MO', 'ry-wc-city-select'),
		_x('Troitsky Administrative Okrug', 'MO', 'ry-wc-city-select'),
	],
	'MUOB' => [
		_x('Kandalakshskiy rayon', 'MUOB', 'ry-wc-city-select'),
		_x('Kolskiy Rayon', 'MUOB', 'ry-wc-city-select'),
		_x('Kovdorskiy Rayon', 'MUOB', 'ry-wc-city-select'),
		_x('Lovozerskiy Rayon', 'MUOB', 'ry-wc-city-select'),
		_x('Pechengskiy Rayon', 'MUOB', 'ry-wc-city-select'),
		_x('Terskiy Rayon', 'MUOB', 'ry-wc-city-select'),
	],
	'NIOB' => [
		_x('Ardatovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Arzamas Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Arzamasskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Balakhninskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Bogorodskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Bolsheboldinskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Bolshemurashkinskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Bor Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Buturlinskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Chkalovsky Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Dalnekonstantinovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Diveyevskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Dzerzhinsk Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Gaginskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Gorodetskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Knyagininskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Koverninskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Krasnobakovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Krasnooktyabrskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Kstovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Kulebaksky Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Lukoyanovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Lyskovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Navashinsky Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Nizhny Novgorod Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Pavlovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Perevozsky Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Pervomaysky Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Pilninskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Pochinkovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Sechenovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Sergachskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Shakhunya Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Sharangskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Shatkovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Sokolsky Urban Okrug', 'NIOB', 'ry-wc-city-select'),
		_x('Sosnovskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Spasskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Tonkinskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Tonshayevskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Urenskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Vachskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Vadskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Varnavinskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Vetluzhskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Volodarskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Vorotynskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Voskresenskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Voznesenskiy Rayon', 'NIOB', 'ry-wc-city-select'),
		_x('Vyksa Urban Okrug', 'NIOB', 'ry-wc-city-select'),
	],
	'NOOS' => [
		_x('Alagirskiy Rayon', 'NOOS', 'ry-wc-city-select'),
		_x('Ardonskiy Rayon', 'NOOS', 'ry-wc-city-select'),
		_x('Digorskiy Rayon', 'NOOS', 'ry-wc-city-select'),
		_x('Irafskiy Rayon', 'NOOS', 'ry-wc-city-select'),
		_x('Kirovskiy Rayon', 'NOOS', 'ry-wc-city-select'),
		_x('Mozdokskiy Rayon', 'NOOS', 'ry-wc-city-select'),
		_x('Pravoberezhnyy Rayon', 'NOOS', 'ry-wc-city-select'),
		_x('Prigorodnyy Rayon', 'NOOS', 'ry-wc-city-select'),
	],
	'NOOB' => [
		_x('Batetskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Borovichskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Chudovskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Demyanskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Kholmskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Khvoyninskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Krestetskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Lyubytinskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Malovisherskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Marevskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Moshenskoy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Novgorodskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Okulovskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Parfinskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Pestovskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Poddorskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Shimskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Soletskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Starorusskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Valdayskiy Rayon', 'NOOB', 'ry-wc-city-select'),
		_x('Volotovskiy Rayon', 'NOOB', 'ry-wc-city-select'),
	],
	'NOOB2' => [
		_x('Baganskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Barabinskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Bolotninskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Chanovskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Cherepanovskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Chistoozernyy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Chulymskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Dovolenskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Iskitimskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Karasukskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Kargatskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Kochenevskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Kochkovskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Kolyvanskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Krasnozerskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Kupinskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Kuybyshevskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Kyshtovskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Maslyaninskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Moshkovskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Ordynskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Severnyy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Suzunskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Tatarskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Toguchinskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Ubinskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Ust-Tarkskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Vengerovskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
		_x('Zdvinskiy Rayon', 'NOOB2', 'ry-wc-city-select'),
	],
	'OMOB' => [
		_x('Bolsherechenskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Bolsheukovskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Cherlakskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Gorkovskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Isilkulskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Kalachinskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Kolosovskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Kormilovskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Krutinskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Lyubinskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Maryanovskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Muromtsevskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Nizhneomskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Okoneshnikovskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Sargatskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Sedelnikovskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Tarskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Tavricheskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Tevrizskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Tyukalinskiy Rayon', 'OMOB', 'ry-wc-city-select'),
		_x('Znamenskiy Rayon', 'OMOB', 'ry-wc-city-select'),
	],
	'OROB' => [
		_x('Gayskiy Rayon', 'OROB', 'ry-wc-city-select'),
		_x('Kvarkenskiy Rayon', 'OROB', 'ry-wc-city-select'),
		_x('Novoorskiy Rayon', 'OROB', 'ry-wc-city-select'),
		_x('Saraktashskiy Rayon', 'OROB', 'ry-wc-city-select'),
	],
	'OROB2' => [
		_x('Bolkhovskiy Rayon', 'OROB2', 'ry-wc-city-select'),
	],
	'PEOB' => [
		_x('Issinskiy Rayon', 'PEOB', 'ry-wc-city-select'),
		_x('Kameshkirskiy Rayon', 'PEOB', 'ry-wc-city-select'),
		_x('Kuznetskiy Rayon', 'PEOB', 'ry-wc-city-select'),
		_x('Neverkinskiy Rayon', 'PEOB', 'ry-wc-city-select'),
	],
	'PEKR' => [
		_x('Cherdynskiy Rayon', 'PEKR', 'ry-wc-city-select'),
		_x('Dobryanskiy Rayon', 'PEKR', 'ry-wc-city-select'),
		_x('Gaynskiy Rayon', 'PEKR', 'ry-wc-city-select'),
		_x('Kochevskiy Rayon', 'PEKR', 'ry-wc-city-select'),
		_x('Kosinskiy Rayon', 'PEKR', 'ry-wc-city-select'),
		_x('Krasnovisherskiy Rayon', 'PEKR', 'ry-wc-city-select'),
		_x('Kudymkarskiy Rayon', 'PEKR', 'ry-wc-city-select'),
		_x('Yurlinskiy Rayon', 'PEKR', 'ry-wc-city-select'),
		_x('Yusvinskiy Rayon', 'PEKR', 'ry-wc-city-select'),
	],
	'PRKR' => [
		_x('Anuchinskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Chernigovskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Khasanskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Khorolskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Kirovskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Lazovskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Mikhaylovskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Nadezhdinskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Shkotovskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Spasskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Terneyskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Ussuriyskiy Rayon', 'PRKR', 'ry-wc-city-select'),
		_x('Yakovlevskiy Rayon', 'PRKR', 'ry-wc-city-select'),
	],
	'PSOB' => [
		_x('Bezhanitskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Gdovskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Kuninskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Novorzhevskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Novosokolnicheskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Opochetskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Ostrovskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Palkinskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Pechorskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Porkhovskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Pskovskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Pushkino-Gorskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Pustoshkinskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Pytalovskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Sebezhskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Strugo-Krasnenskiy Rayon', 'PSOB', 'ry-wc-city-select'),
		_x('Velikolukskiy Rayon', 'PSOB', 'ry-wc-city-select'),
	],
	'READ' => [
		_x('Adygeysk Republican Urban Okrug', 'READ', 'ry-wc-city-select'),
		_x('Giaginskiy Rayon', 'READ', 'ry-wc-city-select'),
		_x('Koshekhablskiy Rayon', 'READ', 'ry-wc-city-select'),
		_x('Krasnogvardeyskiy Rayon', 'READ', 'ry-wc-city-select'),
		_x('Maykop Republican Urban Okrug', 'READ', 'ry-wc-city-select'),
		_x('Maykopskiy Rayon', 'READ', 'ry-wc-city-select'),
		_x('Shovgenovskiy Rayon', 'READ', 'ry-wc-city-select'),
		_x('Takhtamukayskiy Rayon', 'READ', 'ry-wc-city-select'),
		_x('Teuchezhskiy Rayon', 'READ', 'ry-wc-city-select'),
	],
	'REAL' => [
		_x('Chemalskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Choyskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Gorno-Altaysk Urban Okrug', 'REAL', 'ry-wc-city-select'),
		_x('Kosh-Agachskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Mayminskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Ongudayskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Shebalinskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Turochakskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Ulaganskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Ust-Kanskiy Rayon', 'REAL', 'ry-wc-city-select'),
		_x('Ust-Koksinskiy Rayon', 'REAL', 'ry-wc-city-select'),
	],
	'REBU' => [
		_x('Barguzinskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Bauntovskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Bichurskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Dzhidinskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Ivolginskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Kabanskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Khorinskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Kizhinginskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Kurumkanskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Kyakhtinskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Mukhorshibirskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Muyskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Okinskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Pribaykalskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Selenginskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Severo-Baykalskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Tarbagatayskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Tunkinskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Yeravninskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Zaigrayevskiy Rayon', 'REBU', 'ry-wc-city-select'),
		_x('Zakamenskiy Rayon', 'REBU', 'ry-wc-city-select'),
	],
	'REIN' => [
		_x('Dzhayrakhskiy Rayon', 'REIN', 'ry-wc-city-select'),
		_x('Malgobekskiy Rayon', 'REIN', 'ry-wc-city-select'),
		_x('Nazranovskiy Rayon', 'REIN', 'ry-wc-city-select'),
		_x('Sunzhenskiy Rayon', 'REIN', 'ry-wc-city-select'),
	],
	'REKA' => [
		_x('Belomorskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Kalevalskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Kemskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Kondopozhskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Lakhdenpokhskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Loukhskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Medvezhyegorskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Muyezerskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Olonetskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Pitkyarantskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Prionezhskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Pryazhinskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Pudozhskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Segezhskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Sortavalskiy Rayon', 'REKA', 'ry-wc-city-select'),
		_x('Suoyarvskiy Rayon', 'REKA', 'ry-wc-city-select'),
	],
	'REKH' => [
		_x('Abakan Gorod', 'REKH', 'ry-wc-city-select'),
		_x('Altayskiy Rayon', 'REKH', 'ry-wc-city-select'),
		_x('Askizskiy Rayon', 'REKH', 'ry-wc-city-select'),
		_x('Beyskiy Rayon', 'REKH', 'ry-wc-city-select'),
		_x('Bogradskiy Rayon', 'REKH', 'ry-wc-city-select'),
		_x('Chernogorsk Gorod', 'REKH', 'ry-wc-city-select'),
		_x('Ordzhonikidzevskiy Rayon', 'REKH', 'ry-wc-city-select'),
		_x('Sayanogorsk Gorod', 'REKH', 'ry-wc-city-select'),
		_x('Shirinskiy Rayon', 'REKH', 'ry-wc-city-select'),
		_x('Tashtypskiy Rayon', 'REKH', 'ry-wc-city-select'),
		_x('Ust-Abakanskiy Rayon', 'REKH', 'ry-wc-city-select'),
	],
	'REMA' => [
		_x('Gornomariyskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Kilemarskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Kuzhenerskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Mari-Turekskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Medvedevskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Morkinskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Novotoryalskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Orshanskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Paranginskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Sernurskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Sovetskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Volzhskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Yurinskiy Rayon', 'REMA', 'ry-wc-city-select'),
		_x('Zvenigovskiy Rayon', 'REMA', 'ry-wc-city-select'),
	],
	'REMO' => [
		_x('Ardatovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Atyashevskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Atyuryevskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Bolshebereznikovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Bolsheignatovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Chamzinskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Dubenskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Ichalkovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Insarskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Kadoshkinskiy rayon', 'REMO', 'ry-wc-city-select'),
		_x('Kochkurovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Kovylkinskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Krasnoslobodskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Lyambirskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Romodanovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Ruzayevskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Sarov Urban Okrug', 'REMO', 'ry-wc-city-select'),
		_x('Staroshaygovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Temnikovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Tengushevskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Torbeyevskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Yelnikovskiy Rayon', 'REMO', 'ry-wc-city-select'),
		_x('Zubovo-Polyanskiy Rayon', 'REMO', 'ry-wc-city-select'),
	],
	'RESA(Y' => [
		_x('Abyysky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Aldansky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Allaikhovskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Anabarskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Bulunskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Churapchinskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Eveno-Bytantaysky National District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Gornyy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Kobyayskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Megino-Kangalasskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Mirninskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Momsky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Namskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Nyurbinsky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Olenyoksky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Olyokminsky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Oymyakonskiy District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Srednekolymsky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Suntarskiy District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Tomponskiy District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Ust-Yanskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Ust-Aldansky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Verkhnekolymsky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Verkhnevilyuysky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Verkhoyansky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Vilyuyskiy Rayon', 'RESA(Y', 'ry-wc-city-select'),
		_x('Vilyuysky District', 'RESA(Y', 'ry-wc-city-select'),
		_x('Yakutsk', 'RESA(Y', 'ry-wc-city-select'),
		_x('Zhigansky District', 'RESA(Y', 'ry-wc-city-select'),
	],
	'RETY' => [
		_x('Ovyurskiy Rayon', 'RETY', 'ry-wc-city-select'),
	],
	'ROOB' => [
		_x('Belokalitvenskiy Rayon', 'ROOB', 'ry-wc-city-select'),
		_x('Dubovskiy Rayon', 'ROOB', 'ry-wc-city-select'),
		_x('Kamenskiy Rayon', 'ROOB', 'ry-wc-city-select'),
		_x('Krasnosulinskiy Rayon', 'ROOB', 'ry-wc-city-select'),
		_x('Martynovskiy Rayon', 'ROOB', 'ry-wc-city-select'),
		_x('Milyutinskiy Rayon', 'ROOB', 'ry-wc-city-select'),
		_x('Rayon Aksayskiy', 'ROOB', 'ry-wc-city-select'),
	],
	'RYOB' => [
		_x('Kasimovskiy Rayon', 'RYOB', 'ry-wc-city-select'),
		_x('Klepikovskiy Rayon', 'RYOB', 'ry-wc-city-select'),
		_x('Ryazanskiy Rayon', 'RYOB', 'ry-wc-city-select'),
		_x('Rybnovskiy Rayon', 'RYOB', 'ry-wc-city-select'),
		_x('Zakharovskiy Rayon', 'RYOB', 'ry-wc-city-select'),
	],
	'SAOB' => [
		_x('Aleksandrovsk-Sakhalinskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Anivskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Korsakovskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Kurilsky District', 'SAOB', 'ry-wc-city-select'),
		_x('Nevelskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Okhinskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Poronayskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Smirnykhovskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Tomarinskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Uglegorskiy Rayon', 'SAOB', 'ry-wc-city-select'),
		_x('Yuzhno-Kurilsky District', 'SAOB', 'ry-wc-city-select'),
	],
	'SAOB2' => [
		_x('Bezenchukskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Bogatovskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Bolshechernigovskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Bolsheglushitskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Borskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Kinelskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Koshkinskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Krasnoyarskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Neftegorskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
		_x('Volzhskiy Rayon', 'SAOB2', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Admiralteysky Rayon', 'SA', 'ry-wc-city-select'),
		_x('Frunzenskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Kalininskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Kirovskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Kolpinskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Krasnogvardeyskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Krasnoselskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Kronshtadtskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Kurortnyy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Moskovskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Nevskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Petrodvortsovyy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Petrogradskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Primorskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Pushkinskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Sestroretskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Tsentralniy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Vasileostrovskiy Rayon', 'SA', 'ry-wc-city-select'),
		_x('Vyborgskiy Rayon', 'SA', 'ry-wc-city-select'),
	],
	'SAOB3' => [
		_x('Atkarskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Baltayskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Bazarno-Karabulakskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Engelsskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Khvalynskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Krasnoarmeyskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Krasnokutskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Marksovskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Saratovskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Sovetskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Volskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
		_x('Voskresenskiy Rayon', 'SAOB3', 'ry-wc-city-select'),
	],
	'SMOB' => [
		_x('Safonovskiy Rayon', 'SMOB', 'ry-wc-city-select'),
		_x('Ugranskiy Rayon', 'SMOB', 'ry-wc-city-select'),
	],
	'STKR' => [
		_x('Georgiyevskiy Rayon', 'STKR', 'ry-wc-city-select'),
		_x('Kurskiy Rayon', 'STKR', 'ry-wc-city-select'),
	],
	'SVOB' => [
		_x('Beloyarskiy Rayon', 'SVOB', 'ry-wc-city-select'),
		_x('Bogdanovichskiy Rayon', 'SVOB', 'ry-wc-city-select'),
		_x('Kamenskiy Rayon', 'SVOB', 'ry-wc-city-select'),
		_x('Krasnoufimskiy Rayon', 'SVOB', 'ry-wc-city-select'),
		_x('Polevskoy Gorod', 'SVOB', 'ry-wc-city-select'),
		_x('Sukholozhskiy Rayon', 'SVOB', 'ry-wc-city-select'),
		_x('Sysertskiy Rayon', 'SVOB', 'ry-wc-city-select'),
	],
	'TAOB' => [
		_x('Bondarskiy Rayon', 'TAOB', 'ry-wc-city-select'),
		_x('Kirsanovskiy Rayon', 'TAOB', 'ry-wc-city-select'),
		_x('Rasskazovskiy Rayon', 'TAOB', 'ry-wc-city-select'),
		_x('Sampurskiy Rayon', 'TAOB', 'ry-wc-city-select'),
		_x('Tokarevskiy Rayon', 'TAOB', 'ry-wc-city-select'),
		_x('Znamenskiy Rayon', 'TAOB', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Agryzskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Aksubayevskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Aktanyshskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Alkeyevskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Alekseyevskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Almetyevsky District', 'TA', 'ry-wc-city-select'),
		_x('Apastovsky District', 'TA', 'ry-wc-city-select'),
		_x('Arskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Atninskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Aznakayevskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Baltasinskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Bavlinskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Bugulminsky District', 'TA', 'ry-wc-city-select'),
		_x('Buinskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Cheremshanskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Chistopolsky District', 'TA', 'ry-wc-city-select'),
		_x('Drozhzhanovskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Gorod Almetyevsk', 'TA', 'ry-wc-city-select'),
		_x('Gorod Aznakayevo', 'TA', 'ry-wc-city-select'),
		_x('Gorod Bavly', 'TA', 'ry-wc-city-select'),
		_x('Gorod Bugulma', 'TA', 'ry-wc-city-select'),
		_x('Gorod Buinsk', 'TA', 'ry-wc-city-select'),
		_x('Gorod Chistopol', 'TA', 'ry-wc-city-select'),
		_x('Gorod Leninogorsk', 'TA', 'ry-wc-city-select'),
		_x('Gorod Nizhnekamsk', 'TA', 'ry-wc-city-select'),
		_x('Gorod Yelabuga', 'TA', 'ry-wc-city-select'),
		_x('Gorod Zainsk', 'TA', 'ry-wc-city-select'),
		_x('Gorod Zelenodolsk', 'TA', 'ry-wc-city-select'),
		_x('Kamsko-Ustyinsky District', 'TA', 'ry-wc-city-select'),
		_x('Kaybitsky District', 'TA', 'ry-wc-city-select'),
		_x('Kukmorskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Laishevskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Leninogorskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Mamadyshskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Mendeleyevskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Menzelinskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Muslyumovskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Nizhnekamskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Novosheshminskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Nurlatskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Nurlatskiy rayon', 'TA', 'ry-wc-city-select'),
		_x('Pestrechinskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Rybno-Slobodskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Sabinskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Sarmanovskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Spasskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Tetyushskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Tyulyachinskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Verkhneuslonskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Vysokogorskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Yelabuzhskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Yutazinskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Zainskiy Rayon', 'TA', 'ry-wc-city-select'),
		_x('Zelenodolsky District', 'TA', 'ry-wc-city-select'),
	],
	'TOOB' => [
		_x('Asinovkiy Rayon', 'TOOB', 'ry-wc-city-select'),
		_x('Bakcharskiy Rayon', 'TOOB', 'ry-wc-city-select'),
		_x('Chainskiy Rayon', 'TOOB', 'ry-wc-city-select'),
		_x('Molchanovskiy Rayon', 'TOOB', 'ry-wc-city-select'),
		_x('Teguldetskiy Rayon', 'TOOB', 'ry-wc-city-select'),
		_x('Tomskiy Rayon', 'TOOB', 'ry-wc-city-select'),
		_x('Verkhneketskiy Rayon', 'TOOB', 'ry-wc-city-select'),
	],
	'TUOB' => [
		_x('Aleksinskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Arsenyevskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Arsenyevskiy rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Kamenskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Kireyevskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Suvorovskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Teplo-Ogarevskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Venevskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Yasnogorskiy Rayon', 'TUOB', 'ry-wc-city-select'),
		_x('Zaokskiy Rayon', 'TUOB', 'ry-wc-city-select'),
	],
	'TVOB' => [
		_x('Andreapolskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Belskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Bezhetskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Bologovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Firovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Kalininskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Kalyazinskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Kashinskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Kesovogorskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Kimrskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Konakovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Krasnokholmskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Kuvshinovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Lesnoy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Likhoslavlskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Maksatikhinskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Ostashkovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Penovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Rameshkovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Sandovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Selizharovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Spirovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Staritskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Toropetskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Torzhokskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Udomelskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Vesyegonskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Vyshnevolotskiy Rayon', 'TVOB', 'ry-wc-city-select'),
		_x('Zubtsovskiy Rayon', 'TVOB', 'ry-wc-city-select'),
	],
	'TYOB' => [
		_x('Armizonskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Berdyuzhskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Golyshmanovskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Isetskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Ishimskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Kazanskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Omutinskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Sladkovskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Uporovskiy Rayon', 'TYOB', 'ry-wc-city-select'),
		_x('Vagayskiy Rayon', 'TYOB', 'ry-wc-city-select'),
	],
	'UDRE' => [
		_x('Karakulinskiy Rayon', 'UDRE', 'ry-wc-city-select'),
		_x('Kiyasovskiy Rayon', 'UDRE', 'ry-wc-city-select'),
		_x('Malopurginskiy Rayon', 'UDRE', 'ry-wc-city-select'),
		_x('Sarapulskiy Rayon', 'UDRE', 'ry-wc-city-select'),
		_x('Zavyalovskiy Rayon', 'UDRE', 'ry-wc-city-select'),
	],
	'ULOB' => [
		_x('Cherdaklinskiy Rayon', 'ULOB', 'ry-wc-city-select'),
		_x('Karsunskiy Rayon', 'ULOB', 'ry-wc-city-select'),
		_x('Maynskiy Rayon', 'ULOB', 'ry-wc-city-select'),
		_x('Pavlovskiy Rayon', 'ULOB', 'ry-wc-city-select'),
		_x('Starokulatkinskiy Rayon', 'ULOB', 'ry-wc-city-select'),
		_x('Terengulskiy Rayon', 'ULOB', 'ry-wc-city-select'),
		_x('Tsilninskiy Rayon', 'ULOB', 'ry-wc-city-select'),
		_x('Ulyanovskiy Rayon', 'ULOB', 'ry-wc-city-select'),
	],
	'VLOB' => [
		_x('Aleksandrovskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Gorokhovetskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Gus-Khrustalnyy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Kameshkovskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Kirzhachskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Kolchuginskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Kovrovskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Melenkovskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Muromskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Petushinskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Selivanovskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Sobinskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Sudogodskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Suzdalskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Vyaznikovskiy Rayon', 'VLOB', 'ry-wc-city-select'),
		_x('Yuryev-Polskiy Rayon', 'VLOB', 'ry-wc-city-select'),
	],
	'VOOB' => [
		_x('Alekseyevskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Bykovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Chernyshkovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Danilovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Dubovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Frolovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Gorodishchenskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Ilovlinskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Kalachevskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Kamyshinskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Kikvidzenskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Kletskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Kotelnikovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Kotovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Kumylzhenskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Mikhaylovka Urban Okrug', 'VOOB', 'ry-wc-city-select'),
		_x('Nekhayevskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Nikolayevskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Novoanninskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Novonikolayevskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Olkhovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Pallasovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Rudnyanskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Serafimovichskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Sredneakhtubinskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Staropoltavskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Surovikinskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Svetloyarskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Uryupinskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Yelanskiy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Zhirnovskiy Rayon', 'VOOB', 'ry-wc-city-select'),
	],
	'VOOB2' => [
		_x('Babayevskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Babushkinskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Belozerskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Chagodoshchenskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Cherepovetskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Gryazovetskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Kaduyskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Kharovskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Kichmengsko-Gorodetskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Kirillovskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Mezhdurechenskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Sheksninskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Sokolskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Syamzhenskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Tarnogskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Totemskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Ust-Kubinskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Ustyuzhenskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Vashkinskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Velikoustyugskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Verkhovazhskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Vologodskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Vozhegodskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
		_x('Vytegorskiy Rayon', 'VOOB2', 'ry-wc-city-select'),
	],
	'VOOB3' => [
		_x('Anninskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Bobrovskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Bogucharskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Borisoglebsky Urban Okrug', 'VOOB3', 'ry-wc-city-select'),
		_x('Buturlinovskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Ertilskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Gribanovskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Kalacheyevskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Kamenskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Kantemirovskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Kashirskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Khokholskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Liskinskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Nizhnedevitskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Novokhoperskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Novousmanskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Olkhovatskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Ostrogozhskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Paninskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Pavlovskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Petropavlovskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Podgorenskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Povorinskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Ramonskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Repyevskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Rossoshanskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Semilukskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Talovskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Ternovskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Verkhnekhavskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Verkhnemamonskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
		_x('Vorobyevskiy Rayon', 'VOOB3', 'ry-wc-city-select'),
	],
	'YAAVOK' => [
		_x('Krasnoselkupskiy Rayon', 'YAAVOK', 'ry-wc-city-select'),
		_x('Nadymskiy Rayon', 'YAAVOK', 'ry-wc-city-select'),
		_x('Priuralskiy Rayon', 'YAAVOK', 'ry-wc-city-select'),
		_x('Purovskiy Rayon', 'YAAVOK', 'ry-wc-city-select'),
		_x('Shuryshkarskiy Rayon', 'YAAVOK', 'ry-wc-city-select'),
		_x('Tazovskiy Rayon', 'YAAVOK', 'ry-wc-city-select'),
		_x('Yamalskiy Rayon', 'YAAVOK', 'ry-wc-city-select'),
	],
	'YAOB' => [
		_x('Bolsheselskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Borisoglebskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Breytovskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Danilovskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Gavrilov-Yamskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Lyubimskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Myshkinskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Nekouzskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Nekrasovskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Pereslavskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Pervomayskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Poshekhonskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Rostovskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Rybinskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Tutayevskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Uglichskiy Rayon', 'YAOB', 'ry-wc-city-select'),
		_x('Yaroslavskiy Rayon', 'YAOB', 'ry-wc-city-select'),
	],
	'YEAVOB' => [
		_x('Birobidzhanskiy Rayon', 'YEAVOB', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'YEAVOB', 'ry-wc-city-select'),
		_x('Obluchenskiy Rayon', 'YEAVOB', 'ry-wc-city-select'),
		_x('Oktyabrskiy Rayon', 'YEAVOB', 'ry-wc-city-select'),
		_x('Smidovichskiy Rayon', 'YEAVOB', 'ry-wc-city-select'),
	],
	'ZAKR' => [
		_x('Akshinskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Aleksandrovo-Zavodskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Baleyskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Borzinskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Chernyshevskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Chitinskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Gazimuro-Zavodskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Kalarskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Kalganskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Karymskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Khilokskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Krasnochikoyskiy rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Krasnokamenskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Kyrinskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Mogochinskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Nerchinskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Nerchinsko-Zavodskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Olovyanninskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Ononskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Petrovsk-Zabaykalskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Priargunskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Shelopuginskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Shilkinskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Sretenskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Tungiro-Olekminskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Tungokochenskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Uletovskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
		_x('Zabaykalskiy Rayon', 'ZAKR', 'ry-wc-city-select'),
	],
	]
];