<?php
/**
 * Kingdom of Saudi Arabia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'SA' => [
	'JA' => [
		_x('Al Qurayyat', 'JA', 'ry-wc-city-select'),
		_x('Dawmat al Jandal', 'JA', 'ry-wc-city-select'),
		_x('Sakaka', 'JA', 'ry-wc-city-select'),
	],
	'MAMU' => [
		_x('Al Hinakiyah', 'MAMU', 'ry-wc-city-select'),
		_x('Al Madinah al Munawwarah', 'MAMU', 'ry-wc-city-select'),
		_x('Al Mahd', 'MAMU', 'ry-wc-city-select'),
		_x('Al `Ula', 'MAMU', 'ry-wc-city-select'),
		_x('Badr', 'MAMU', 'ry-wc-city-select'),
		_x('Khaybar', 'MAMU', 'ry-wc-city-select'),
		_x('Yanbu` al Bahr', 'MAMU', 'ry-wc-city-select'),
	],
	'MIASSH' => [
		_x('Ad Dammam', 'MIASSH', 'ry-wc-city-select'),
		_x('Al Ahsa', 'MIASSH', 'ry-wc-city-select'),
		_x('Al Jubayl', 'MIASSH', 'ry-wc-city-select'),
		_x('Al Khafji', 'MIASSH', 'ry-wc-city-select'),
		_x('Al Khubar', 'MIASSH', 'ry-wc-city-select'),
		_x('Al Qatif', 'MIASSH', 'ry-wc-city-select'),
		_x('An Nu`ayriyah', 'MIASSH', 'ry-wc-city-select'),
		_x('Buqayq', 'MIASSH', 'ry-wc-city-select'),
		_x('Hafr al Batin', 'MIASSH', 'ry-wc-city-select'),
		_x('Qaryah al `Ulya', 'MIASSH', 'ry-wc-city-select'),
		_x('Ras Tannurah', 'MIASSH', 'ry-wc-city-select'),
	],
	'ALPR' => [
		_x('Al Asyah', 'ALPR', 'ry-wc-city-select'),
		_x('Al Badai`', 'ALPR', 'ry-wc-city-select'),
		_x('Al Bukayriyah', 'ALPR', 'ry-wc-city-select'),
		_x('Al Midhnab', 'ALPR', 'ry-wc-city-select'),
		_x('An Nabhaniyah', 'ALPR', 'ry-wc-city-select'),
		_x('Ar Rass', 'ALPR', 'ry-wc-city-select'),
		_x('Ash Shimasiyah', 'ALPR', 'ry-wc-city-select'),
		_x('Buraydah', 'ALPR', 'ry-wc-city-select'),
		_x('Governorate of Unaizah', 'ALPR', 'ry-wc-city-select'),
		_x('Riyad al Khabra', 'ALPR', 'ry-wc-city-select'),
		_x('`Uyun al Jiwa', 'ALPR', 'ry-wc-city-select'),
	],
	'HARE' => [
		_x('Al Ghazalah', 'HARE', 'ry-wc-city-select'),
		_x('Ash Shinan', 'HARE', 'ry-wc-city-select'),
		_x('Baq`a', 'HARE', 'ry-wc-city-select'),
		_x('Hail', 'HARE', 'ry-wc-city-select'),
	],
	'JIRE' => [
		_x('Abu `Arish', 'JIRE', 'ry-wc-city-select'),
		_x('Ad Dair', 'JIRE', 'ry-wc-city-select'),
		_x('Ad Darb', 'JIRE', 'ry-wc-city-select'),
		_x('Ahad al Musarihah', 'JIRE', 'ry-wc-city-select'),
		_x('Al Harth', 'JIRE', 'ry-wc-city-select'),
		_x('Al `Aridah', 'JIRE', 'ry-wc-city-select'),
		_x('Al `Idabi', 'JIRE', 'ry-wc-city-select'),
		_x('Ar Rayth', 'JIRE', 'ry-wc-city-select'),
		_x('Baysh', 'JIRE', 'ry-wc-city-select'),
		_x('Damad', 'JIRE', 'ry-wc-city-select'),
		_x('Farasan', 'JIRE', 'ry-wc-city-select'),
		_x('Jazan', 'JIRE', 'ry-wc-city-select'),
		_x('Sabya', 'JIRE', 'ry-wc-city-select'),
		_x('Samitah', 'JIRE', 'ry-wc-city-select'),
	],
	'MAPR' => [
		_x('Al Jumum', 'MAPR', 'ry-wc-city-select'),
		_x('Al Kamil', 'MAPR', 'ry-wc-city-select'),
		_x('Al Khurmah', 'MAPR', 'ry-wc-city-select'),
		_x('Al Lith', 'MAPR', 'ry-wc-city-select'),
		_x('Al Qunfudhah', 'MAPR', 'ry-wc-city-select'),
		_x('At Taif', 'MAPR', 'ry-wc-city-select'),
		_x('Ghran', 'MAPR', 'ry-wc-city-select'),
		_x('Jiddah', 'MAPR', 'ry-wc-city-select'),
		_x('Khulays', 'MAPR', 'ry-wc-city-select'),
		_x('Makkah al Mukarramah', 'MAPR', 'ry-wc-city-select'),
		_x('Rabigh', 'MAPR', 'ry-wc-city-select'),
		_x('Ranyah', 'MAPR', 'ry-wc-city-select'),
		_x('Turubah', 'MAPR', 'ry-wc-city-select'),
	],
	'MIAS' => [
		_x('Abha', 'MIAS', 'ry-wc-city-select'),
		_x('Ahad Rufaydah', 'MIAS', 'ry-wc-city-select'),
		_x('Al Majaridah', 'MIAS', 'ry-wc-city-select'),
		_x('An Namas', 'MIAS', 'ry-wc-city-select'),
		_x('Bishah', 'MIAS', 'ry-wc-city-select'),
		_x('Khamis Mushayt', 'MIAS', 'ry-wc-city-select'),
		_x('Muhail', 'MIAS', 'ry-wc-city-select'),
		_x('Rijal Alma`', 'MIAS', 'ry-wc-city-select'),
		_x('Sabt Al Alayah', 'MIAS', 'ry-wc-city-select'),
		_x('Sarat `Abidah', 'MIAS', 'ry-wc-city-select'),
		_x('Tathlith', 'MIAS', 'ry-wc-city-select'),
		_x('Zahran al Janub', 'MIAS', 'ry-wc-city-select'),
	],
	'MINA' => [
		_x('Al Kharkhir', 'MINA', 'ry-wc-city-select'),
		_x('Badr al Janub', 'MINA', 'ry-wc-city-select'),
		_x('Hubuna', 'MINA', 'ry-wc-city-select'),
		_x('Khubash', 'MINA', 'ry-wc-city-select'),
		_x('Najran', 'MINA', 'ry-wc-city-select'),
		_x('Sharurah', 'MINA', 'ry-wc-city-select'),
		_x('Thar', 'MINA', 'ry-wc-city-select'),
		_x('Yadamah', 'MINA', 'ry-wc-city-select'),
	],
	'MITA' => [
		_x('Al Wajh', 'MITA', 'ry-wc-city-select'),
		_x('Duba', 'MITA', 'ry-wc-city-select'),
		_x('Haql', 'MITA', 'ry-wc-city-select'),
		_x('Tabuk', 'MITA', 'ry-wc-city-select'),
		_x('Tayma', 'MITA', 'ry-wc-city-select'),
		_x('Umluj', 'MITA', 'ry-wc-city-select'),
	],
	'MIBA' => [
		_x('Al Bahah', 'MIBA', 'ry-wc-city-select'),
		_x('Al Mandaq', 'MIBA', 'ry-wc-city-select'),
		_x('Al Mikhwah', 'MIBA', 'ry-wc-city-select'),
		_x('Al Qura', 'MIBA', 'ry-wc-city-select'),
		_x('Al `Aqiq', 'MIBA', 'ry-wc-city-select'),
		_x('Baljurashi', 'MIBA', 'ry-wc-city-select'),
		_x('Qilwah', 'MIBA', 'ry-wc-city-select'),
	],
	'MIHUASSH' => [
		_x('Rafha', 'MIHUASSH', 'ry-wc-city-select'),
		_x('Turayf', 'MIHUASSH', 'ry-wc-city-select'),
		_x('`Ar`ar', 'MIHUASSH', 'ry-wc-city-select'),
	],
	'MIRI' => [
		_x('Ad Dawadimi', 'MIRI', 'ry-wc-city-select'),
		_x('Ad Dir`iyah', 'MIRI', 'ry-wc-city-select'),
		_x('Al Aflaj', 'MIRI', 'ry-wc-city-select'),
		_x('Al Ghat', 'MIRI', 'ry-wc-city-select'),
		_x('Al Hariq', 'MIRI', 'ry-wc-city-select'),
		_x('Al Kharj', 'MIRI', 'ry-wc-city-select'),
		_x('Al Majma`ah', 'MIRI', 'ry-wc-city-select'),
		_x('Al Muzahimiyah', 'MIRI', 'ry-wc-city-select'),
		_x('Al Quway`iyah', 'MIRI', 'ry-wc-city-select'),
		_x('Ar Riyad', 'MIRI', 'ry-wc-city-select'),
		_x('As Sulayyil', 'MIRI', 'ry-wc-city-select'),
		_x('Az Zulfi', 'MIRI', 'ry-wc-city-select'),
		_x('Duruma', 'MIRI', 'ry-wc-city-select'),
		_x('Hawtat Bani Tamim', 'MIRI', 'ry-wc-city-select'),
		_x('Huraymila', 'MIRI', 'ry-wc-city-select'),
		_x('Rumah', 'MIRI', 'ry-wc-city-select'),
		_x('Shaqra', 'MIRI', 'ry-wc-city-select'),
		_x('Thadiq', 'MIRI', 'ry-wc-city-select'),
		_x('Wadi ad Dawasir', 'MIRI', 'ry-wc-city-select'),
		_x('`Afif', 'MIRI', 'ry-wc-city-select'),
	],
	]
];