<?php
/**
 * Solomon Islands places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'SB' => [
	'CEPR' => [
		_x('East Gela', 'CEPR', 'ry-wc-city-select'),
		_x('Lovukol', 'CEPR', 'ry-wc-city-select'),
		_x('Mbanika', 'CEPR', 'ry-wc-city-select'),
		_x('North East Gela', 'CEPR', 'ry-wc-city-select'),
		_x('North Savo', 'CEPR', 'ry-wc-city-select'),
		_x('North West Gela', 'CEPR', 'ry-wc-city-select'),
		_x('Pavuvu', 'CEPR', 'ry-wc-city-select'),
		_x('Sandfly-Buenavista', 'CEPR', 'ry-wc-city-select'),
		_x('South East Gela', 'CEPR', 'ry-wc-city-select'),
		_x('South Savo', 'CEPR', 'ry-wc-city-select'),
		_x('South West Gela', 'CEPR', 'ry-wc-city-select'),
		_x('Tulagi', 'CEPR', 'ry-wc-city-select'),
		_x('West Gela', 'CEPR', 'ry-wc-city-select'),
	],
	'CH' => [
		_x('Babatana', 'CH', 'ry-wc-city-select'),
		_x('Bangara', 'CH', 'ry-wc-city-select'),
		_x('Batava', 'CH', 'ry-wc-city-select'),
		_x('Katupika', 'CH', 'ry-wc-city-select'),
		_x('Kerepangara', 'CH', 'ry-wc-city-select'),
		_x('Kirugela', 'CH', 'ry-wc-city-select'),
		_x('Polo', 'CH', 'ry-wc-city-select'),
		_x('Senga', 'CH', 'ry-wc-city-select'),
		_x('Susuka', 'CH', 'ry-wc-city-select'),
		_x('Tavula', 'CH', 'ry-wc-city-select'),
		_x('Tepakaza', 'CH', 'ry-wc-city-select'),
		_x('Vasiduki', 'CH', 'ry-wc-city-select'),
		_x('Viviru', 'CH', 'ry-wc-city-select'),
		_x('Waghina', 'CH', 'ry-wc-city-select'),
	],
	'GUPR' => [
		_x('Aola', 'GUPR', 'ry-wc-city-select'),
		_x('Avuavu', 'GUPR', 'ry-wc-city-select'),
		_x('Birao', 'GUPR', 'ry-wc-city-select'),
		_x('Duidui', 'GUPR', 'ry-wc-city-select'),
		_x('East Ghaobata', 'GUPR', 'ry-wc-city-select'),
		_x('East Tasimboko', 'GUPR', 'ry-wc-city-select'),
		_x('Kolokarako', 'GUPR', 'ry-wc-city-select'),
		_x('Longgu', 'GUPR', 'ry-wc-city-select'),
		_x('Malango', 'GUPR', 'ry-wc-city-select'),
		_x('Moli', 'GUPR', 'ry-wc-city-select'),
		_x('Paripao', 'GUPR', 'ry-wc-city-select'),
		_x('Saghalu', 'GUPR', 'ry-wc-city-select'),
		_x('Savulei', 'GUPR', 'ry-wc-city-select'),
		_x('Talise', 'GUPR', 'ry-wc-city-select'),
		_x('Tandai', 'GUPR', 'ry-wc-city-select'),
		_x('Tangarare', 'GUPR', 'ry-wc-city-select'),
		_x('Tetekanji', 'GUPR', 'ry-wc-city-select'),
		_x('Valasi', 'GUPR', 'ry-wc-city-select'),
		_x('Vatukulau', 'GUPR', 'ry-wc-city-select'),
		_x('Vulolo', 'GUPR', 'ry-wc-city-select'),
		_x('Wanderer Bay', 'GUPR', 'ry-wc-city-select'),
		_x('West Ghaobata', 'GUPR', 'ry-wc-city-select'),
	],
	'HO' => [
		_x('Cruz', 'HO', 'ry-wc-city-select'),
		_x('KolaA', 'HO', 'ry-wc-city-select'),
		_x('Kukum', 'HO', 'ry-wc-city-select'),
		_x('Mataniko', 'HO', 'ry-wc-city-select'),
		_x('Mbumburu', 'HO', 'ry-wc-city-select'),
		_x('Naha', 'HO', 'ry-wc-city-select'),
		_x('Nggosi', 'HO', 'ry-wc-city-select'),
		_x('Panatina', 'HO', 'ry-wc-city-select'),
		_x('Rove - Lengakiki', 'HO', 'ry-wc-city-select'),
		_x('Vavaea', 'HO', 'ry-wc-city-select'),
		_x('Vuhokesa', 'HO', 'ry-wc-city-select'),
		_x('Vura', 'HO', 'ry-wc-city-select'),
	],
	'ISPR' => [
		_x('Buala', 'ISPR', 'ry-wc-city-select'),
		_x('Havulei', 'ISPR', 'ry-wc-city-select'),
		_x('Hovukoilo', 'ISPR', 'ry-wc-city-select'),
		_x('Japuana', 'ISPR', 'ry-wc-city-select'),
		_x('Kaloka', 'ISPR', 'ry-wc-city-select'),
		_x('Kia', 'ISPR', 'ry-wc-city-select'),
		_x('Kmaga', 'ISPR', 'ry-wc-city-select'),
		_x('Kokota', 'ISPR', 'ry-wc-city-select'),
		_x('Kolomola', 'ISPR', 'ry-wc-city-select'),
		_x('Kolotubi', 'ISPR', 'ry-wc-city-select'),
		_x('Koviloko', 'ISPR', 'ry-wc-city-select'),
		_x('Samasodu', 'ISPR', 'ry-wc-city-select'),
		_x('Sigana', 'ISPR', 'ry-wc-city-select'),
		_x('Susubona', 'ISPR', 'ry-wc-city-select'),
		_x('Tatamba', 'ISPR', 'ry-wc-city-select'),
		_x('Tirotonga', 'ISPR', 'ry-wc-city-select'),
	],
	'MAPR' => [
		_x('Arosi East', 'MAPR', 'ry-wc-city-select'),
		_x('Arosi North', 'MAPR', 'ry-wc-city-select'),
		_x('Arosi South', 'MAPR', 'ry-wc-city-select'),
		_x('Arosi West', 'MAPR', 'ry-wc-city-select'),
		_x('Bauro Central', 'MAPR', 'ry-wc-city-select'),
		_x('Bauro East', 'MAPR', 'ry-wc-city-select'),
		_x('Bauro West', 'MAPR', 'ry-wc-city-select'),
		_x('Haununu', 'MAPR', 'ry-wc-city-select'),
		_x('North Ulawa', 'MAPR', 'ry-wc-city-select'),
		_x('Rawo', 'MAPR', 'ry-wc-city-select'),
		_x('Santa Ana', 'MAPR', 'ry-wc-city-select'),
		_x('Santa Catalina', 'MAPR', 'ry-wc-city-select'),
		_x('South Ulawa', 'MAPR', 'ry-wc-city-select'),
		_x('Star Harbour North', 'MAPR', 'ry-wc-city-select'),
		_x('Star Harbour South', 'MAPR', 'ry-wc-city-select'),
		_x('Ugi And Pio', 'MAPR', 'ry-wc-city-select'),
		_x('Wainoni East', 'MAPR', 'ry-wc-city-select'),
		_x('Wainoni West', 'MAPR', 'ry-wc-city-select'),
		_x('Weather Coast', 'MAPR', 'ry-wc-city-select'),
		_x('West Ulawa', 'MAPR', 'ry-wc-city-select'),
	],
	'MAPR2' => [
		_x('Aba - Asimeuru', 'MAPR2', 'ry-wc-city-select'),
		_x('Aiaisi', 'MAPR2', 'ry-wc-city-select'),
		_x('Aimela', 'MAPR2', 'ry-wc-city-select'),
		_x('Areare', 'MAPR2', 'ry-wc-city-select'),
		_x('Asimae', 'MAPR2', 'ry-wc-city-select'),
		_x('Auki', 'MAPR2', 'ry-wc-city-select'),
		_x('Buma', 'MAPR2', 'ry-wc-city-select'),
		_x('East Baegu', 'MAPR2', 'ry-wc-city-select'),
		_x('Fauabu', 'MAPR2', 'ry-wc-city-select'),
		_x('Faumamanu - Kwai', 'MAPR2', 'ry-wc-city-select'),
		_x('Foondo - Gwaiau', 'MAPR2', 'ry-wc-city-select'),
		_x('Fouenda', 'MAPR2', 'ry-wc-city-select'),
		_x('Gulalafou', 'MAPR2', 'ry-wc-city-select'),
		_x('Kwaimela - Radefasu', 'MAPR2', 'ry-wc-city-select'),
		_x('Kwarekwareo', 'MAPR2', 'ry-wc-city-select'),
		_x('Langalanga', 'MAPR2', 'ry-wc-city-select'),
		_x('Luaniua', 'MAPR2', 'ry-wc-city-select'),
		_x('MaluU', 'MAPR2', 'ry-wc-city-select'),
		_x('Mandalua - Folotana', 'MAPR2', 'ry-wc-city-select'),
		_x('Mareho', 'MAPR2', 'ry-wc-city-select'),
		_x('Matakwalao', 'MAPR2', 'ry-wc-city-select'),
		_x('Nafinua', 'MAPR2', 'ry-wc-city-select'),
		_x('Pelau', 'MAPR2', 'ry-wc-city-select'),
		_x('Raroisuu', 'MAPR2', 'ry-wc-city-select'),
		_x('Siesie', 'MAPR2', 'ry-wc-city-select'),
		_x('Sikaiana', 'MAPR2', 'ry-wc-city-select'),
		_x('Sububenu- Burianias', 'MAPR2', 'ry-wc-city-select'),
		_x('Sulufou - Kwarande', 'MAPR2', 'ry-wc-city-select'),
		_x('Tai', 'MAPR2', 'ry-wc-city-select'),
		_x('Takwa', 'MAPR2', 'ry-wc-city-select'),
		_x('Waneagu - Taelanasin', 'MAPR2', 'ry-wc-city-select'),
		_x('Weagu Silana Sina', 'MAPR2', 'ry-wc-city-select'),
		_x('West Baegu - Fatale', 'MAPR2', 'ry-wc-city-select'),
	],
	'REANBE' => [
		_x('East Ghongau', 'REANBE', 'ry-wc-city-select'),
		_x('East Te Nggano', 'REANBE', 'ry-wc-city-select'),
		_x('Kangava', 'REANBE', 'ry-wc-city-select'),
		_x('Lughu', 'REANBE', 'ry-wc-city-select'),
		_x('Matangi', 'REANBE', 'ry-wc-city-select'),
		_x('Mugihenua', 'REANBE', 'ry-wc-city-select'),
		_x('SaAiho', 'REANBE', 'ry-wc-city-select'),
		_x('Tetau Nangoto', 'REANBE', 'ry-wc-city-select'),
		_x('West Ghongau', 'REANBE', 'ry-wc-city-select'),
		_x('West Te Nggano', 'REANBE', 'ry-wc-city-select'),
	],
	'TEPR' => [
		_x('Duff Islands', 'TEPR', 'ry-wc-city-select'),
		_x('Fenualoa', 'TEPR', 'ry-wc-city-select'),
		_x('Graciosa Bay', 'TEPR', 'ry-wc-city-select'),
		_x('Lipe-Temua', 'TEPR', 'ry-wc-city-select'),
		_x('Luva Station', 'TEPR', 'ry-wc-city-select'),
		_x('Manuopo', 'TEPR', 'ry-wc-city-select'),
		_x('Nanggu-Lord Howe', 'TEPR', 'ry-wc-city-select'),
		_x('Nea-Noole', 'TEPR', 'ry-wc-city-select'),
		_x('Nenumpo', 'TEPR', 'ry-wc-city-select'),
		_x('Neo', 'TEPR', 'ry-wc-city-select'),
		_x('Nevenema', 'TEPR', 'ry-wc-city-select'),
		_x('Nipua-Nopoli', 'TEPR', 'ry-wc-city-select'),
		_x('North East Santa Cruz', 'TEPR', 'ry-wc-city-select'),
		_x('Polynesian Outer Islands', 'TEPR', 'ry-wc-city-select'),
		_x('Tikopia', 'TEPR', 'ry-wc-city-select'),
		_x('Utupua', 'TEPR', 'ry-wc-city-select'),
		_x('Vanikoro', 'TEPR', 'ry-wc-city-select'),
	],
	'WEPR' => [
		_x('Bilua', 'WEPR', 'ry-wc-city-select'),
		_x('Buini Tusu', 'WEPR', 'ry-wc-city-select'),
		_x('Central Ranongga', 'WEPR', 'ry-wc-city-select'),
		_x('Dovele', 'WEPR', 'ry-wc-city-select'),
		_x('Gizo', 'WEPR', 'ry-wc-city-select'),
		_x('Inner Shortlands', 'WEPR', 'ry-wc-city-select'),
		_x('Iringgila', 'WEPR', 'ry-wc-city-select'),
		_x('Kolombaghea', 'WEPR', 'ry-wc-city-select'),
		_x('Kusaghe', 'WEPR', 'ry-wc-city-select'),
		_x('Munda', 'WEPR', 'ry-wc-city-select'),
		_x('Nggatokae', 'WEPR', 'ry-wc-city-select'),
		_x('Nono', 'WEPR', 'ry-wc-city-select'),
		_x('Noro', 'WEPR', 'ry-wc-city-select'),
		_x('North Kolombangara', 'WEPR', 'ry-wc-city-select'),
		_x('North Ranongga', 'WEPR', 'ry-wc-city-select'),
		_x('North Rendova', 'WEPR', 'ry-wc-city-select'),
		_x('North Vangunu', 'WEPR', 'ry-wc-city-select'),
		_x('Nusa Roviana', 'WEPR', 'ry-wc-city-select'),
		_x('Outer Shortlands', 'WEPR', 'ry-wc-city-select'),
		_x('Roviana Lagoon', 'WEPR', 'ry-wc-city-select'),
		_x('Simbo', 'WEPR', 'ry-wc-city-select'),
		_x('South Kolombangara', 'WEPR', 'ry-wc-city-select'),
		_x('South Ranongga', 'WEPR', 'ry-wc-city-select'),
		_x('South Rendova', 'WEPR', 'ry-wc-city-select'),
		_x('Vonavona', 'WEPR', 'ry-wc-city-select'),
		_x('Vonunu', 'WEPR', 'ry-wc-city-select'),
	],
	]
];