<?php
/**
 * Kingdom of Sweden places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'SE' => [
	'AEKO' => [
		_x('AElvdalen', 'AEKO', 'ry-wc-city-select'),
		_x('Idre', 'AEKO', 'ry-wc-city-select'),
		_x('Saerna', 'AEKO', 'ry-wc-city-select'),
	],
	'ALKO' => [
		_x('Halanda', 'ALKO', 'ry-wc-city-select'),
		_x('Noedinge', 'ALKO', 'ry-wc-city-select'),
		_x('Skepplanda', 'ALKO', 'ry-wc-city-select'),
		_x('Starrkaerr-Kilanda', 'ALKO', 'ry-wc-city-select'),
	],
	'ALKO2' => [
		_x('Alingsas', 'ALKO2', 'ry-wc-city-select'),
		_x('Bjaerke, del', 'ALKO2', 'ry-wc-city-select'),
		_x('Hemsjoe', 'ALKO2', 'ry-wc-city-select'),
		_x('OEdenaes', 'ALKO2', 'ry-wc-city-select'),
	],
	'ALKO3' => [
		_x('AElmhult', 'ALKO3', 'ry-wc-city-select'),
		_x('Goeteryd', 'ALKO3', 'ry-wc-city-select'),
		_x('Haerlunda', 'ALKO3', 'ry-wc-city-select'),
		_x('Hallaryd', 'ALKO3', 'ry-wc-city-select'),
		_x('Pjaetteryd', 'ALKO3', 'ry-wc-city-select'),
		_x('Stenbrohult', 'ALKO3', 'ry-wc-city-select'),
		_x('Virestad', 'ALKO3', 'ry-wc-city-select'),
	],
	'ALKO4' => [
		_x('Alvesta', 'ALKO4', 'ry-wc-city-select'),
		_x('Blaedinge', 'ALKO4', 'ry-wc-city-select'),
		_x('Haerloev', 'ALKO4', 'ry-wc-city-select'),
		_x('Hjortsberga med Kvenneberga', 'ALKO4', 'ry-wc-city-select'),
		_x('Lekaryd', 'ALKO4', 'ry-wc-city-select'),
		_x('Mistelas', 'ALKO4', 'ry-wc-city-select'),
		_x('Moheda', 'ALKO4', 'ry-wc-city-select'),
		_x('Skateloev', 'ALKO4', 'ry-wc-city-select'),
		_x('Slaetthoeg', 'ALKO4', 'ry-wc-city-select'),
		_x('Vaestra Torsas', 'ALKO4', 'ry-wc-city-select'),
		_x('Vislanda', 'ALKO4', 'ry-wc-city-select'),
	],
	'ALKO5' => [
		_x('AElvkarleby-Skutskaer', 'ALKO5', 'ry-wc-city-select'),
	],
	'ALKO6' => [
		_x('AElvsby', 'ALKO6', 'ry-wc-city-select'),
	],
	'AMKO' => [
		_x('Amal', 'AMKO', 'ry-wc-city-select'),
		_x('Animskog', 'AMKO', 'ry-wc-city-select'),
		_x('Froeskog-Edsleskog', 'AMKO', 'ry-wc-city-select'),
		_x('Mo', 'AMKO', 'ry-wc-city-select'),
		_x('Toesse med Tydje', 'AMKO', 'ry-wc-city-select'),
	],
	'ANKO' => [
		_x('Aneby', 'ANKO', 'ry-wc-city-select'),
		_x('Askeryd', 'ANKO', 'ry-wc-city-select'),
		_x('Frinnaryd', 'ANKO', 'ry-wc-city-select'),
		_x('Haurida-Vireda', 'ANKO', 'ry-wc-city-select'),
		_x('Lommaryd', 'ANKO', 'ry-wc-city-select'),
	],
	'ANKO2' => [
		_x('Borgsjoe', 'ANKO2', 'ry-wc-city-select'),
		_x('Haveroe', 'ANKO2', 'ry-wc-city-select'),
		_x('Torp', 'ANKO2', 'ry-wc-city-select'),
	],
	'ANKO3' => [
		_x('AEngelholm', 'ANKO3', 'ry-wc-city-select'),
		_x('Barkakra', 'ANKO3', 'ry-wc-city-select'),
		_x('Hjaernarp-Tastarp', 'ANKO3', 'ry-wc-city-select'),
		_x('Hoeja', 'ANKO3', 'ry-wc-city-select'),
		_x('Munka Ljungby', 'ANKO3', 'ry-wc-city-select'),
		_x('Rebbelberga', 'ANKO3', 'ry-wc-city-select'),
		_x('Stroevelstorp', 'ANKO3', 'ry-wc-city-select'),
	],
	'ARKO' => [
		_x('Arbogabygden', 'ARKO', 'ry-wc-city-select'),
	],
	'ARKO2' => [
		_x('Are', 'ARKO2', 'ry-wc-city-select'),
		_x('Kall', 'ARKO2', 'ry-wc-city-select'),
		_x('Undersaker', 'ARKO2', 'ry-wc-city-select'),
		_x('Vaestra Storsjoebygden', 'ARKO2', 'ry-wc-city-select'),
	],
	'ARKO3' => [
		_x('Blomskog', 'ARKO3', 'ry-wc-city-select'),
		_x('Holmedal-Karlanda', 'ARKO3', 'ry-wc-city-select'),
		_x('OEstervallskog', 'ARKO3', 'ry-wc-city-select'),
		_x('Silbodal', 'ARKO3', 'ry-wc-city-select'),
		_x('Sillerud', 'ARKO3', 'ry-wc-city-select'),
		_x('Toecksmark', 'ARKO3', 'ry-wc-city-select'),
		_x('Trankil', 'ARKO3', 'ry-wc-city-select'),
		_x('Vaestra Fagelvik', 'ARKO3', 'ry-wc-city-select'),
	],
	'ARKO4' => [
		_x('Arjeplog', 'ARKO4', 'ry-wc-city-select'),
	],
	'ARKO5' => [
		_x('Arvidsjaur', 'ARKO5', 'ry-wc-city-select'),
	],
	'ARKO6' => [
		_x('AElga', 'ARKO6', 'ry-wc-city-select'),
		_x('Arvika oestra', 'ARKO6', 'ry-wc-city-select'),
		_x('Arvika vaestra', 'ARKO6', 'ry-wc-city-select'),
		_x('Bogen', 'ARKO6', 'ry-wc-city-select'),
		_x('Brunskog', 'ARKO6', 'ry-wc-city-select'),
		_x('Glava', 'ARKO6', 'ry-wc-city-select'),
		_x('Gunnarskog', 'ARKO6', 'ry-wc-city-select'),
		_x('Mangskog', 'ARKO6', 'ry-wc-city-select'),
		_x('Ny', 'ARKO6', 'ry-wc-city-select'),
		_x('Stavnaes-Hoegerud', 'ARKO6', 'ry-wc-city-select'),
	],
	'ASKO' => [
		_x('Asele', 'ASKO', 'ry-wc-city-select'),
		_x('Fredrika', 'ASKO', 'ry-wc-city-select'),
	],
	'ASKO2' => [
		_x('Askersund', 'ASKO2', 'ry-wc-city-select'),
		_x('Hammar', 'ASKO2', 'ry-wc-city-select'),
		_x('Lerbaeck', 'ASKO2', 'ry-wc-city-select'),
		_x('Snavlunda', 'ASKO2', 'ry-wc-city-select'),
	],
	'ASKO3' => [
		_x('Bjoernekulla-Vaestra Broby', 'ASKO3', 'ry-wc-city-select'),
		_x('Kvidinge', 'ASKO3', 'ry-wc-city-select'),
	],
	'ATKO' => [
		_x('Atvid', 'ATKO', 'ry-wc-city-select'),
		_x('Bjoersaeter-Yxnerum', 'ATKO', 'ry-wc-city-select'),
		_x('Gaerdserum', 'ATKO', 'ry-wc-city-select'),
		_x('Grebo-Vaerna', 'ATKO', 'ry-wc-city-select'),
		_x('Hannaes', 'ATKO', 'ry-wc-city-select'),
	],
	'AVKO' => [
		_x('Avesta', 'AVKO', 'ry-wc-city-select'),
		_x('By', 'AVKO', 'ry-wc-city-select'),
		_x('Folkaerna', 'AVKO', 'ry-wc-city-select'),
		_x('Grytnaes', 'AVKO', 'ry-wc-city-select'),
	],
	'BAKO' => [
		_x('Bastad', 'BAKO', 'ry-wc-city-select'),
		_x('Foersloev-Grevie', 'BAKO', 'ry-wc-city-select'),
		_x('Hov', 'BAKO', 'ry-wc-city-select'),
		_x('OEstra Karup', 'BAKO', 'ry-wc-city-select'),
		_x('Torekov', 'BAKO', 'ry-wc-city-select'),
		_x('Vaestra Karup', 'BAKO', 'ry-wc-city-select'),
	],
	'BEKO' => [
		_x('AErtemark', 'BEKO', 'ry-wc-city-select'),
		_x('Baecke', 'BEKO', 'ry-wc-city-select'),
		_x('Laxarby', 'BEKO', 'ry-wc-city-select'),
		_x('OEdskoelt', 'BEKO', 'ry-wc-city-select'),
		_x('Steneby', 'BEKO', 'ry-wc-city-select'),
		_x('Tisselskog', 'BEKO', 'ry-wc-city-select'),
		_x('Torrskog', 'BEKO', 'ry-wc-city-select'),
		_x('Varvik', 'BEKO', 'ry-wc-city-select'),
	],
	'BEKO2' => [
		_x('Asarne', 'BEKO2', 'ry-wc-city-select'),
		_x('Berg', 'BEKO2', 'ry-wc-city-select'),
		_x('Hackas', 'BEKO2', 'ry-wc-city-select'),
		_x('Kloevsjoe', 'BEKO2', 'ry-wc-city-select'),
		_x('Myssjoe', 'BEKO2', 'ry-wc-city-select'),
		_x('Oviken', 'BEKO2', 'ry-wc-city-select'),
		_x('Raetan', 'BEKO2', 'ry-wc-city-select'),
		_x('Storsjoe', 'BEKO2', 'ry-wc-city-select'),
	],
	'BJKO' => [
		_x('Bjurholm', 'BJKO', 'ry-wc-city-select'),
	],
	'BJKO2' => [
		_x('Bjuv', 'BJKO2', 'ry-wc-city-select'),
		_x('Ekeby', 'BJKO2', 'ry-wc-city-select'),
	],
	'BOKO' => [
		_x('Edefors', 'BOKO', 'ry-wc-city-select'),
		_x('Gunnarsbyn', 'BOKO', 'ry-wc-city-select'),
		_x('OEverlulea', 'BOKO', 'ry-wc-city-select'),
		_x('Saevast', 'BOKO', 'ry-wc-city-select'),
	],
	'BOKO2' => [
		_x('Bollebygd', 'BOKO2', 'ry-wc-city-select'),
		_x('Toellsjoe', 'BOKO2', 'ry-wc-city-select'),
	],
	'BOKO3' => [
		_x('Arbra-Undersvik', 'BOKO3', 'ry-wc-city-select'),
		_x('Bollnaes', 'BOKO3', 'ry-wc-city-select'),
		_x('Hanebo-Segersta', 'BOKO3', 'ry-wc-city-select'),
		_x('Rengsjoe', 'BOKO3', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('AEspered', 'BO', 'ry-wc-city-select'),
		_x('Boras Caroli', 'BO', 'ry-wc-city-select'),
		_x('Boras Gustav Adolf', 'BO', 'ry-wc-city-select'),
		_x('Borgstena', 'BO', 'ry-wc-city-select'),
		_x('Braemhult', 'BO', 'ry-wc-city-select'),
		_x('Bredared', 'BO', 'ry-wc-city-select'),
		_x('Dannike', 'BO', 'ry-wc-city-select'),
		_x('Fristad-Gingri', 'BO', 'ry-wc-city-select'),
		_x('Kinnarumma', 'BO', 'ry-wc-city-select'),
		_x('Rangedala', 'BO', 'ry-wc-city-select'),
		_x('Sandhult', 'BO', 'ry-wc-city-select'),
		_x('Seglora', 'BO', 'ry-wc-city-select'),
		_x('Sexdrega, del', 'BO', 'ry-wc-city-select'),
		_x('Taemta', 'BO', 'ry-wc-city-select'),
		_x('Taerby', 'BO', 'ry-wc-city-select'),
		_x('Toarp', 'BO', 'ry-wc-city-select'),
		_x('Vaenga', 'BO', 'ry-wc-city-select'),
	],
	'BOKO4' => [
		_x('Boeda', 'BOKO4', 'ry-wc-city-select'),
		_x('Borgholm', 'BOKO4', 'ry-wc-city-select'),
		_x('Foera-Alboeke-Loet', 'BOKO4', 'ry-wc-city-select'),
		_x('Gaerdsloesa, Langloet och Runsten', 'BOKO4', 'ry-wc-city-select'),
		_x('Hoegby-Kaella-Persnaes', 'BOKO4', 'ry-wc-city-select'),
		_x('Koepingsvik', 'BOKO4', 'ry-wc-city-select'),
		_x('Raepplinge-Hoegsrum', 'BOKO4', 'ry-wc-city-select'),
	],
	'BOKO5' => [
		_x('Stora Tuna', 'BOKO5', 'ry-wc-city-select'),
		_x('Torsang', 'BOKO5', 'ry-wc-city-select'),
	],
	'BOKO6' => [
		_x('Botkyrka', 'BOKO6', 'ry-wc-city-select'),
		_x('Groedinge', 'BOKO6', 'ry-wc-city-select'),
	],
	'BOKO7' => [
		_x('Asbo', 'BOKO7', 'ry-wc-city-select'),
		_x('Blavik', 'BOKO7', 'ry-wc-city-select'),
		_x('Ekeby', 'BOKO7', 'ry-wc-city-select'),
		_x('Malexander', 'BOKO7', 'ry-wc-city-select'),
		_x('Rinna', 'BOKO7', 'ry-wc-city-select'),
	],
	'BRKO' => [
		_x('Bodsjoe', 'BRKO', 'ry-wc-city-select'),
		_x('Braecke-Nyhem', 'BRKO', 'ry-wc-city-select'),
		_x('Haellesjoe-Hasjoe', 'BRKO', 'ry-wc-city-select'),
		_x('Revsund', 'BRKO', 'ry-wc-city-select'),
		_x('Sundsjoe', 'BRKO', 'ry-wc-city-select'),
	],
	'BRKO2' => [
		_x('Gualoev', 'BRKO2', 'ry-wc-city-select'),
		_x('Ivetofta', 'BRKO2', 'ry-wc-city-select'),
		_x('Naesum', 'BRKO2', 'ry-wc-city-select'),
	],
	'BUKO' => [
		_x('Burloev', 'BUKO', 'ry-wc-city-select'),
	],
	'DAKO' => [
		_x('Dals-Ed', 'DAKO', 'ry-wc-city-select'),
		_x('Gesaeter', 'DAKO', 'ry-wc-city-select'),
		_x('Habol', 'DAKO', 'ry-wc-city-select'),
		_x('Noessemark', 'DAKO', 'ry-wc-city-select'),
		_x('Roelanda', 'DAKO', 'ry-wc-city-select'),
		_x('Toeftedal', 'DAKO', 'ry-wc-city-select'),
	],
	'DAKO2' => [
		_x('Danderyd', 'DAKO2', 'ry-wc-city-select'),
	],
	'DEKO' => [
		_x('Degerfors-Nysund', 'DEKO', 'ry-wc-city-select'),
	],
	'DOKO' => [
		_x('Dorotea-Risbaeck', 'DOKO', 'ry-wc-city-select'),
	],
	'EDKO' => [
		_x('Eda', 'EDKO', 'ry-wc-city-select'),
		_x('Jaernskog', 'EDKO', 'ry-wc-city-select'),
		_x('Koela', 'EDKO', 'ry-wc-city-select'),
		_x('Skillingmark', 'EDKO', 'ry-wc-city-select'),
	],
	'EKKO' => [
		_x('Adelsoe-Munsoe', 'EKKO', 'ry-wc-city-select'),
		_x('Ekeroe', 'EKKO', 'ry-wc-city-select'),
		_x('Faeringsoe', 'EKKO', 'ry-wc-city-select'),
		_x('Lovoe', 'EKKO', 'ry-wc-city-select'),
	],
	'EKKO2' => [
		_x('Edshult', 'EKKO2', 'ry-wc-city-select'),
		_x('Eksjoe', 'EKKO2', 'ry-wc-city-select'),
		_x('Haessleby', 'EKKO2', 'ry-wc-city-select'),
		_x('Hoereda', 'EKKO2', 'ry-wc-city-select'),
		_x('Hult', 'EKKO2', 'ry-wc-city-select'),
		_x('Ingatorp-Belloe', 'EKKO2', 'ry-wc-city-select'),
		_x('Krakshult', 'EKKO2', 'ry-wc-city-select'),
		_x('Mellby', 'EKKO2', 'ry-wc-city-select'),
	],
	'EMKO' => [
		_x('Algutsboda', 'EMKO', 'ry-wc-city-select'),
		_x('Emmaboda', 'EMKO', 'ry-wc-city-select'),
		_x('Langasjoe', 'EMKO', 'ry-wc-city-select'),
		_x('Vissefjaerda', 'EMKO', 'ry-wc-city-select'),
	],
	'ENKO' => [
		_x('Biskopskulla', 'ENKO', 'ry-wc-city-select'),
		_x('Bogloesa', 'ENKO', 'ry-wc-city-select'),
		_x('Enkoeping', 'ENKO', 'ry-wc-city-select'),
		_x('Fittja', 'ENKO', 'ry-wc-city-select'),
		_x('Fjaerdhundra', 'ENKO', 'ry-wc-city-select'),
		_x('Froeslunda', 'ENKO', 'ry-wc-city-select'),
		_x('Giresta', 'ENKO', 'ry-wc-city-select'),
		_x('Gryta', 'ENKO', 'ry-wc-city-select'),
		_x('Haerkeberga', 'ENKO', 'ry-wc-city-select'),
		_x('Hjaelsta', 'ENKO', 'ry-wc-city-select'),
		_x('Holm', 'ENKO', 'ry-wc-city-select'),
		_x('Husby-Sjutolft', 'ENKO', 'ry-wc-city-select'),
		_x('Kulla', 'ENKO', 'ry-wc-city-select'),
		_x('Langtora', 'ENKO', 'ry-wc-city-select'),
		_x('Litslena', 'ENKO', 'ry-wc-city-select'),
		_x('Nysaetra', 'ENKO', 'ry-wc-city-select'),
		_x('Soedra Asunda', 'ENKO', 'ry-wc-city-select'),
		_x('Sparrsaetra-Bred', 'ENKO', 'ry-wc-city-select'),
		_x('Tillinge', 'ENKO', 'ry-wc-city-select'),
		_x('Veckholm', 'ENKO', 'ry-wc-city-select'),
		_x('Villberga-Hacksta-Loet', 'ENKO', 'ry-wc-city-select'),
	],
	'ESKO' => [
		_x('Eskilstuna Fors', 'ESKO', 'ry-wc-city-select'),
		_x('Eskilstuna Kloster', 'ESKO', 'ry-wc-city-select'),
		_x('Haellby foers. med Tumbo och Raby-Rekarn', 'ESKO', 'ry-wc-city-select'),
		_x('Husby-Rekarne', 'ESKO', 'ry-wc-city-select'),
		_x('Kafjaerden', 'ESKO', 'ry-wc-city-select'),
		_x('Naeshulta', 'ESKO', 'ry-wc-city-select'),
		_x('Stenkvista-AErla', 'ESKO', 'ry-wc-city-select'),
		_x('Torshaella', 'ESKO', 'ry-wc-city-select'),
		_x('Vaestra Rekarne', 'ESKO', 'ry-wc-city-select'),
	],
	'ESKO2' => [
		_x('Esloev', 'ESKO2', 'ry-wc-city-select'),
		_x('Loeberoed', 'ESKO2', 'ry-wc-city-select'),
		_x('OEstra Onsjoe', 'ESKO2', 'ry-wc-city-select'),
		_x('Resloev-OEstra Karaby', 'ESKO2', 'ry-wc-city-select'),
		_x('Ringsjoe, del', 'ESKO2', 'ry-wc-city-select'),
	],
	'ESKO3' => [
		_x('Essunga', 'ESKO3', 'ry-wc-city-select'),
		_x('Fraemmestad-Baereberg', 'ESKO3', 'ry-wc-city-select'),
		_x('Fridhem, del', 'ESKO3', 'ry-wc-city-select'),
		_x('Lekasa-Barne Asaka', 'ESKO3', 'ry-wc-city-select'),
	],
	'FAKO' => [
		_x('Vaestanfors-Vaestervala', 'FAKO', 'ry-wc-city-select'),
	],
	'FAKO2' => [
		_x('AElvsered', 'FAKO2', 'ry-wc-city-select'),
		_x('Abild', 'FAKO2', 'ry-wc-city-select'),
		_x('Arstad', 'FAKO2', 'ry-wc-city-select'),
		_x('Asige', 'FAKO2', 'ry-wc-city-select'),
		_x('Eftra', 'FAKO2', 'ry-wc-city-select'),
		_x('Fagered', 'FAKO2', 'ry-wc-city-select'),
		_x('Falkenberg', 'FAKO2', 'ry-wc-city-select'),
		_x('Gaellared', 'FAKO2', 'ry-wc-city-select'),
		_x('Gunnarp', 'FAKO2', 'ry-wc-city-select'),
		_x('Kaellsjoe', 'FAKO2', 'ry-wc-city-select'),
		_x('Krogsered', 'FAKO2', 'ry-wc-city-select'),
		_x('Ljungby', 'FAKO2', 'ry-wc-city-select'),
		_x('Morup', 'FAKO2', 'ry-wc-city-select'),
		_x('Okome', 'FAKO2', 'ry-wc-city-select'),
		_x('Skrea', 'FAKO2', 'ry-wc-city-select'),
		_x('Sloeinge', 'FAKO2', 'ry-wc-city-select'),
		_x('Stafsinge', 'FAKO2', 'ry-wc-city-select'),
		_x('Ullared', 'FAKO2', 'ry-wc-city-select'),
		_x('Vessige', 'FAKO2', 'ry-wc-city-select'),
		_x('Vinberg', 'FAKO2', 'ry-wc-city-select'),
	],
	'FAKO3' => [
		_x('Asarp', 'FAKO3', 'ry-wc-city-select'),
		_x('Asle', 'FAKO3', 'ry-wc-city-select'),
		_x('Boerstig', 'FAKO3', 'ry-wc-city-select'),
		_x('Borgunda', 'FAKO3', 'ry-wc-city-select'),
		_x('Dala', 'FAKO3', 'ry-wc-city-select'),
		_x('Falkoeping', 'FAKO3', 'ry-wc-city-select'),
		_x('Floby', 'FAKO3', 'ry-wc-city-select'),
		_x('Friggeraker', 'FAKO3', 'ry-wc-city-select'),
		_x('Goekhem', 'FAKO3', 'ry-wc-city-select'),
		_x('Grolanda-Jaela', 'FAKO3', 'ry-wc-city-select'),
		_x('Gudhem', 'FAKO3', 'ry-wc-city-select'),
		_x('Hoegstena', 'FAKO3', 'ry-wc-city-select'),
		_x('Hornborga', 'FAKO3', 'ry-wc-city-select'),
		_x('Karleby', 'FAKO3', 'ry-wc-city-select'),
		_x('Kinneved', 'FAKO3', 'ry-wc-city-select'),
		_x('Marka', 'FAKO3', 'ry-wc-city-select'),
		_x('Mularp', 'FAKO3', 'ry-wc-city-select'),
		_x('Skoerstorp', 'FAKO3', 'ry-wc-city-select'),
		_x('Sloeta', 'FAKO3', 'ry-wc-city-select'),
		_x('Stenstorp', 'FAKO3', 'ry-wc-city-select'),
		_x('Tiarp', 'FAKO3', 'ry-wc-city-select'),
		_x('Torbjoerntorp', 'FAKO3', 'ry-wc-city-select'),
		_x('Vilske-Kleva', 'FAKO3', 'ry-wc-city-select'),
		_x('Yllestad', 'FAKO3', 'ry-wc-city-select'),
	],
	'FAKO4' => [
		_x('Aspeboda', 'FAKO4', 'ry-wc-city-select'),
		_x('Bjursas', 'FAKO4', 'ry-wc-city-select'),
		_x('Enviken', 'FAKO4', 'ry-wc-city-select'),
		_x('Falu Kristine', 'FAKO4', 'ry-wc-city-select'),
		_x('Grycksbo', 'FAKO4', 'ry-wc-city-select'),
		_x('Hosjoe', 'FAKO4', 'ry-wc-city-select'),
		_x('Stora Kopparberg', 'FAKO4', 'ry-wc-city-select'),
		_x('Sundborn', 'FAKO4', 'ry-wc-city-select'),
		_x('Svaerdsjoe', 'FAKO4', 'ry-wc-city-select'),
		_x('Vika', 'FAKO4', 'ry-wc-city-select'),
	],
	'FAKO5' => [
		_x('Faergelanda', 'FAKO5', 'ry-wc-city-select'),
		_x('Hoegsaeter', 'FAKO5', 'ry-wc-city-select'),
		_x('Jaerbo', 'FAKO5', 'ry-wc-city-select'),
		_x('Lerdal', 'FAKO5', 'ry-wc-city-select'),
		_x('OEdeborg', 'FAKO5', 'ry-wc-city-select'),
		_x('Raennelanda', 'FAKO5', 'ry-wc-city-select'),
		_x('Raggaerd', 'FAKO5', 'ry-wc-city-select'),
		_x('Torp', 'FAKO5', 'ry-wc-city-select'),
	],
	'FIKO' => [
		_x('Brattfors', 'FIKO', 'ry-wc-city-select'),
		_x('Filipstad', 'FIKO', 'ry-wc-city-select'),
		_x('Gasborn', 'FIKO', 'ry-wc-city-select'),
		_x('Kroppa', 'FIKO', 'ry-wc-city-select'),
		_x('Nordmark', 'FIKO', 'ry-wc-city-select'),
		_x('Raemmen', 'FIKO', 'ry-wc-city-select'),
	],
	'FIKO2' => [
		_x('Haellestad', 'FIKO2', 'ry-wc-city-select'),
		_x('Regna', 'FIKO2', 'ry-wc-city-select'),
		_x('Risinge', 'FIKO2', 'ry-wc-city-select'),
		_x('Skedevi', 'FIKO2', 'ry-wc-city-select'),
	],
	'FLKO' => [
		_x('Ardala', 'FLKO', 'ry-wc-city-select'),
		_x('Bettna', 'FLKO', 'ry-wc-city-select'),
		_x('Blacksta', 'FLKO', 'ry-wc-city-select'),
		_x('Dunker-Lilla Malma', 'FLKO', 'ry-wc-city-select'),
		_x('Flen', 'FLKO', 'ry-wc-city-select'),
		_x('Forssa', 'FLKO', 'ry-wc-city-select'),
		_x('Helgesta-Hyltinge', 'FLKO', 'ry-wc-city-select'),
		_x('Melloesa', 'FLKO', 'ry-wc-city-select'),
		_x('Vadsbro', 'FLKO', 'ry-wc-city-select'),
	],
	'FOKO' => [
		_x('Forshaga', 'FOKO', 'ry-wc-city-select'),
		_x('Ullerud', 'FOKO', 'ry-wc-city-select'),
	],
	'GAKO' => [
		_x('Gaellivare', 'GAKO', 'ry-wc-city-select'),
		_x('Hakkas', 'GAKO', 'ry-wc-city-select'),
		_x('Malmberget', 'GAKO', 'ry-wc-city-select'),
		_x('Nilivaara', 'GAKO', 'ry-wc-city-select'),
	],
	'GAKO2' => [
		_x('Floda', 'GAKO2', 'ry-wc-city-select'),
		_x('Gagnef', 'GAKO2', 'ry-wc-city-select'),
		_x('Mockfjaerd', 'GAKO2', 'ry-wc-city-select'),
	],
	'GAKO3' => [
		_x('Bomhus', 'GAKO3', 'ry-wc-city-select'),
		_x('Gaevle Heliga Trefaldighet', 'GAKO3', 'ry-wc-city-select'),
		_x('Gaevle Maria', 'GAKO3', 'ry-wc-city-select'),
		_x('Gaevle Staffan', 'GAKO3', 'ry-wc-city-select'),
		_x('Gaevle Tomas', 'GAKO3', 'ry-wc-city-select'),
		_x('Hamrange', 'GAKO3', 'ry-wc-city-select'),
		_x('Hedesunda', 'GAKO3', 'ry-wc-city-select'),
		_x('Hille', 'GAKO3', 'ry-wc-city-select'),
		_x('Valbo', 'GAKO3', 'ry-wc-city-select'),
	],
	'GIKO' => [
		_x('Anderstorp', 'GIKO', 'ry-wc-city-select'),
		_x('As', 'GIKO', 'ry-wc-city-select'),
		_x('Bosebo', 'GIKO', 'ry-wc-city-select'),
		_x('Burseryd', 'GIKO', 'ry-wc-city-select'),
		_x('Gislaved', 'GIKO', 'ry-wc-city-select'),
		_x('Gryteryd', 'GIKO', 'ry-wc-city-select'),
		_x('Kallerstad', 'GIKO', 'ry-wc-city-select'),
		_x('Norra Hestra', 'GIKO', 'ry-wc-city-select'),
		_x('OEreryd', 'GIKO', 'ry-wc-city-select'),
		_x('Reftele', 'GIKO', 'ry-wc-city-select'),
		_x('Soedra Hestra', 'GIKO', 'ry-wc-city-select'),
		_x('Stengardshult', 'GIKO', 'ry-wc-city-select'),
		_x('Valdshult', 'GIKO', 'ry-wc-city-select'),
		_x('Vathult', 'GIKO', 'ry-wc-city-select'),
		_x('Villstad', 'GIKO', 'ry-wc-city-select'),
	],
	'GNKO' => [
		_x('Daga', 'GNKO', 'ry-wc-city-select'),
		_x('Frustuna', 'GNKO', 'ry-wc-city-select'),
	],
	'GNKO2' => [
		_x('Asenhoega', 'GNKO2', 'ry-wc-city-select'),
		_x('Gnosjoe', 'GNKO2', 'ry-wc-city-select'),
		_x('Kaelleryd', 'GNKO2', 'ry-wc-city-select'),
		_x('Kaevsjoe', 'GNKO2', 'ry-wc-city-select'),
		_x('Kulltorp, del', 'GNKO2', 'ry-wc-city-select'),
	],
	'GOST' => [
		_x('AElvsborg', 'GOST', 'ry-wc-city-select'),
		_x('Angered', 'GOST', 'ry-wc-city-select'),
		_x('Askim', 'GOST', 'ry-wc-city-select'),
		_x('Backa', 'GOST', 'ry-wc-city-select'),
		_x('Baeckebol', 'GOST', 'ry-wc-city-select'),
		_x('Bergsjoen', 'GOST', 'ry-wc-city-select'),
		_x('Bergum', 'GOST', 'ry-wc-city-select'),
		_x('Biskopsgarden', 'GOST', 'ry-wc-city-select'),
		_x('Bjoerkekaerr', 'GOST', 'ry-wc-city-select'),
		_x('Bjoerlanda', 'GOST', 'ry-wc-city-select'),
		_x('Braemaregarden', 'GOST', 'ry-wc-city-select'),
		_x('Brunnsbo', 'GOST', 'ry-wc-city-select'),
		_x('Domkyrkofoers. i Goeteborg', 'GOST', 'ry-wc-city-select'),
		_x('Goeteborgs Annedal', 'GOST', 'ry-wc-city-select'),
		_x('Goeteborgs Carl Johan', 'GOST', 'ry-wc-city-select'),
		_x('Goeteborgs Haga', 'GOST', 'ry-wc-city-select'),
		_x('Goeteborgs Johanneberg', 'GOST', 'ry-wc-city-select'),
		_x('Goeteborgs Masthugg', 'GOST', 'ry-wc-city-select'),
		_x('Goeteborgs Oscar Fredrik', 'GOST', 'ry-wc-city-select'),
		_x('Goeteborgs S:t Pauli', 'GOST', 'ry-wc-city-select'),
		_x('Goeteborgs Vasa', 'GOST', 'ry-wc-city-select'),
		_x('Gunnared', 'GOST', 'ry-wc-city-select'),
		_x('Haerlanda', 'GOST', 'ry-wc-city-select'),
		_x('Hoegsbo', 'GOST', 'ry-wc-city-select'),
		_x('Kortedala', 'GOST', 'ry-wc-city-select'),
		_x('Lundby', 'GOST', 'ry-wc-city-select'),
		_x('Naeset', 'GOST', 'ry-wc-city-select'),
		_x('Nyloese', 'GOST', 'ry-wc-city-select'),
		_x('OErgryte', 'GOST', 'ry-wc-city-select'),
		_x('Roedbo', 'GOST', 'ry-wc-city-select'),
		_x('Saeve', 'GOST', 'ry-wc-city-select'),
		_x('Styrsoe', 'GOST', 'ry-wc-city-select'),
		_x('Torslanda', 'GOST', 'ry-wc-city-select'),
		_x('Tuve', 'GOST', 'ry-wc-city-select'),
		_x('Tynnered', 'GOST', 'ry-wc-city-select'),
		_x('Vaestra Froelunda', 'GOST', 'ry-wc-city-select'),
	],
	'GOKO' => [
		_x('Goetene', 'GOKO', 'ry-wc-city-select'),
		_x('Husaby', 'GOKO', 'ry-wc-city-select'),
		_x('Kaellby', 'GOKO', 'ry-wc-city-select'),
		_x('Kinnekulle', 'GOKO', 'ry-wc-city-select'),
		_x('Kleva-Sil', 'GOKO', 'ry-wc-city-select'),
		_x('Ledsjoe', 'GOKO', 'ry-wc-city-select'),
		_x('Ova', 'GOKO', 'ry-wc-city-select'),
		_x('Skaelvum', 'GOKO', 'ry-wc-city-select'),
	],
	'GRKO' => [
		_x('Flo', 'GRKO', 'ry-wc-city-select'),
		_x('Fridhem, del', 'GRKO', 'ry-wc-city-select'),
		_x('Saerestad', 'GRKO', 'ry-wc-city-select'),
		_x('Tengene', 'GRKO', 'ry-wc-city-select'),
		_x('Troekoerna', 'GRKO', 'ry-wc-city-select'),
	],
	'GRKO2' => [
		_x('Borgvik', 'GRKO2', 'ry-wc-city-select'),
		_x('Ed', 'GRKO2', 'ry-wc-city-select'),
		_x('Grums', 'GRKO2', 'ry-wc-city-select'),
		_x('Vaermskog', 'GRKO2', 'ry-wc-city-select'),
	],
	'GUKO' => [
		_x('Amnehaerad', 'GUKO', 'ry-wc-city-select'),
		_x('Hova-AElgaras, del', 'GUKO', 'ry-wc-city-select'),
	],
	'HAKO' => [
		_x('Brandstorp', 'HAKO', 'ry-wc-city-select'),
		_x('Gustav Adolf', 'HAKO', 'ry-wc-city-select'),
		_x('Habo', 'HAKO', 'ry-wc-city-select'),
	],
	'HAKO2' => [
		_x('Haeggeby', 'HAKO2', 'ry-wc-city-select'),
		_x('Kalmar', 'HAKO2', 'ry-wc-city-select'),
		_x('OEvergran', 'HAKO2', 'ry-wc-city-select'),
		_x('Skokloster', 'HAKO2', 'ry-wc-city-select'),
		_x('Yttergran', 'HAKO2', 'ry-wc-city-select'),
	],
	'HAKO3' => [
		_x('Hede', 'HAKO3', 'ry-wc-city-select'),
		_x('Svegsbygden', 'HAKO3', 'ry-wc-city-select'),
		_x('Taennaes-Ljusnedal', 'HAKO3', 'ry-wc-city-select'),
		_x('Vemdalen', 'HAKO3', 'ry-wc-city-select'),
		_x('Ytterhogdal, OEverhogdal och AEngersjoe', 'HAKO3', 'ry-wc-city-select'),
	],
	'HAKO4' => [
		_x('Haeggdanger', 'HAKO4', 'ry-wc-city-select'),
		_x('Haernoesands domkyrkofoers.', 'HAKO4', 'ry-wc-city-select'),
		_x('Hemsoe', 'HAKO4', 'ry-wc-city-select'),
		_x('Hoegsjoe', 'HAKO4', 'ry-wc-city-select'),
		_x('Saebra', 'HAKO4', 'ry-wc-city-select'),
		_x('Stigsjoe', 'HAKO4', 'ry-wc-city-select'),
		_x('Viksjoe', 'HAKO4', 'ry-wc-city-select'),
	],
	'HAKO5' => [
		_x('Ekshaerad', 'HAKO5', 'ry-wc-city-select'),
		_x('Hagfors-Gustav Adolf', 'HAKO5', 'ry-wc-city-select'),
		_x('Norra Rada', 'HAKO5', 'ry-wc-city-select'),
		_x('Sunnemo', 'HAKO5', 'ry-wc-city-select'),
	],
	'HAKO6' => [
		_x('Grythyttan', 'HAKO6', 'ry-wc-city-select'),
		_x('Haellefors-Hjulsjoe', 'HAKO6', 'ry-wc-city-select'),
	],
	'HAKO7' => [
		_x('Bo-Svennevad', 'HAKO7', 'ry-wc-city-select'),
		_x('Hallsberg', 'HAKO7', 'ry-wc-city-select'),
		_x('Skoellersta', 'HAKO7', 'ry-wc-city-select'),
		_x('Viby', 'HAKO7', 'ry-wc-city-select'),
	],
	'HAKO8' => [
		_x('Hallstahammar-Berg', 'HAKO8', 'ry-wc-city-select'),
		_x('Kolbaeck-Saeby', 'HAKO8', 'ry-wc-city-select'),
	],
	'HAKO9' => [
		_x('Breared', 'HAKO9', 'ry-wc-city-select'),
		_x('Eldsbergabygden', 'HAKO9', 'ry-wc-city-select'),
		_x('Ensloev', 'HAKO9', 'ry-wc-city-select'),
		_x('Getinge-Raevinge', 'HAKO9', 'ry-wc-city-select'),
		_x('Harplinge', 'HAKO9', 'ry-wc-city-select'),
		_x('Holm', 'HAKO9', 'ry-wc-city-select'),
		_x('Martin Luther', 'HAKO9', 'ry-wc-city-select'),
		_x('OEvraby', 'HAKO9', 'ry-wc-city-select'),
		_x('Oskarstroem', 'HAKO9', 'ry-wc-city-select'),
		_x('S:t Nikolai', 'HAKO9', 'ry-wc-city-select'),
		_x('Slaettakra-Kvibille', 'HAKO9', 'ry-wc-city-select'),
		_x('Snoestorp', 'HAKO9', 'ry-wc-city-select'),
		_x('Soendrum-Vapnoe', 'HAKO9', 'ry-wc-city-select'),
		_x('Steninge', 'HAKO9', 'ry-wc-city-select'),
	],
	'HAKO10' => [
		_x('Hammaroe', 'HAKO10', 'ry-wc-city-select'),
	],
	'HAKO11' => [
		_x('Dalaroe-Ornoe-Utoe', 'HAKO11', 'ry-wc-city-select'),
		_x('OEsterhaninge', 'HAKO11', 'ry-wc-city-select'),
		_x('Vaesterhaninge-Muskoe', 'HAKO11', 'ry-wc-city-select'),
	],
	'HAKO12' => [
		_x('Karl Gustav', 'HAKO12', 'ry-wc-city-select'),
		_x('Nedertornea-Haparanda', 'HAKO12', 'ry-wc-city-select'),
	],
	'HAKO13' => [
		_x('Bjoerketorp', 'HAKO13', 'ry-wc-city-select'),
		_x('Haerryda', 'HAKO13', 'ry-wc-city-select'),
		_x('Landvetter', 'HAKO13', 'ry-wc-city-select'),
		_x('Rada', 'HAKO13', 'ry-wc-city-select'),
	],
	'HAKO14' => [
		_x('Broennestad', 'HAKO14', 'ry-wc-city-select'),
		_x('Farstorp', 'HAKO14', 'ry-wc-city-select'),
		_x('Finja', 'HAKO14', 'ry-wc-city-select'),
		_x('Haeglinge', 'HAKO14', 'ry-wc-city-select'),
		_x('Haessleholm', 'HAKO14', 'ry-wc-city-select'),
		_x('Haestveda', 'HAKO14', 'ry-wc-city-select'),
		_x('Hoerja', 'HAKO14', 'ry-wc-city-select'),
		_x('Matteroed', 'HAKO14', 'ry-wc-city-select'),
		_x('Norra Akarp', 'HAKO14', 'ry-wc-city-select'),
		_x('Norra Mellby', 'HAKO14', 'ry-wc-city-select'),
		_x('Roeke', 'HAKO14', 'ry-wc-city-select'),
		_x('Stoby', 'HAKO14', 'ry-wc-city-select'),
		_x('Vaestra Torup', 'HAKO14', 'ry-wc-city-select'),
		_x('Vankiva', 'HAKO14', 'ry-wc-city-select'),
		_x('Verum', 'HAKO14', 'ry-wc-city-select'),
		_x('Vinsloev', 'HAKO14', 'ry-wc-city-select'),
		_x('Vittsjoe', 'HAKO14', 'ry-wc-city-select'),
	],
	'HEKO' => [
		_x('Enaker', 'HEKO', 'ry-wc-city-select'),
		_x('Harbo', 'HEKO', 'ry-wc-city-select'),
		_x('Huddunge', 'HEKO', 'ry-wc-city-select'),
		_x('Nora', 'HEKO', 'ry-wc-city-select'),
		_x('OEstervala', 'HEKO', 'ry-wc-city-select'),
		_x('Vaesterloevsta', 'HEKO', 'ry-wc-city-select'),
		_x('Vittinge', 'HEKO', 'ry-wc-city-select'),
	],
	'HEKO2' => [
		_x('Garpenberg', 'HEKO2', 'ry-wc-city-select'),
		_x('Hedemora', 'HEKO2', 'ry-wc-city-select'),
		_x('Husby', 'HEKO2', 'ry-wc-city-select'),
	],
	'HE' => [
		_x('Allerum', 'HE', 'ry-wc-city-select'),
		_x('Barsloev', 'HE', 'ry-wc-city-select'),
		_x('Filborna', 'HE', 'ry-wc-city-select'),
		_x('Fjaerestad', 'HE', 'ry-wc-city-select'),
		_x('Fleninge', 'HE', 'ry-wc-city-select'),
		_x('Helsingborgs Gustav Adolf', 'HE', 'ry-wc-city-select'),
		_x('Helsingborgs Maria', 'HE', 'ry-wc-city-select'),
		_x('Kropp', 'HE', 'ry-wc-city-select'),
		_x('Kvistofta', 'HE', 'ry-wc-city-select'),
		_x('Landskrona, del', 'HE', 'ry-wc-city-select'),
		_x('Moerarp-Haesslunda', 'HE', 'ry-wc-city-select'),
		_x('Raus', 'HE', 'ry-wc-city-select'),
		_x('Vaelinge-Kattarp', 'HE', 'ry-wc-city-select'),
		_x('Vaelluv-Frillestad', 'HE', 'ry-wc-city-select'),
	],
	'HEKO3' => [
		_x('Alboga', 'HEKO3', 'ry-wc-city-select'),
		_x('Brattensby', 'HEKO3', 'ry-wc-city-select'),
		_x('Broddarp', 'HEKO3', 'ry-wc-city-select'),
		_x('Eggvena', 'HEKO3', 'ry-wc-city-select'),
		_x('Eriksberg', 'HEKO3', 'ry-wc-city-select'),
		_x('Foelene', 'HEKO3', 'ry-wc-city-select'),
		_x('Grude', 'HEKO3', 'ry-wc-city-select'),
		_x('Herrljunga', 'HEKO3', 'ry-wc-city-select'),
		_x('Hov', 'HEKO3', 'ry-wc-city-select'),
		_x('Hudene', 'HEKO3', 'ry-wc-city-select'),
		_x('Jaellby', 'HEKO3', 'ry-wc-city-select'),
		_x('Kaellunga', 'HEKO3', 'ry-wc-city-select'),
		_x('Mjaeldrunga', 'HEKO3', 'ry-wc-city-select'),
		_x('Molla', 'HEKO3', 'ry-wc-city-select'),
		_x('OEra', 'HEKO3', 'ry-wc-city-select'),
		_x('Od', 'HEKO3', 'ry-wc-city-select'),
		_x('Remmene', 'HEKO3', 'ry-wc-city-select'),
		_x('Skoelvene', 'HEKO3', 'ry-wc-city-select'),
		_x('Soedra Bjoerke', 'HEKO3', 'ry-wc-city-select'),
		_x('Vesene', 'HEKO3', 'ry-wc-city-select'),
	],
	'HJKO' => [
		_x('Fagelas', 'HJKO', 'ry-wc-city-select'),
		_x('Fridene', 'HJKO', 'ry-wc-city-select'),
		_x('Hjo', 'HJKO', 'ry-wc-city-select'),
		_x('Korsberga', 'HJKO', 'ry-wc-city-select'),
		_x('Mofalla', 'HJKO', 'ry-wc-city-select'),
	],
	'HOKO' => [
		_x('Hofors', 'HOKO', 'ry-wc-city-select'),
		_x('Torsaker', 'HOKO', 'ry-wc-city-select'),
	],
	'HOKO2' => [
		_x('Brunnby', 'HOKO2', 'ry-wc-city-select'),
		_x('Farhult-Jonstorp', 'HOKO2', 'ry-wc-city-select'),
		_x('Hoeganaes', 'HOKO2', 'ry-wc-city-select'),
		_x('Vaesby', 'HOKO2', 'ry-wc-city-select'),
		_x('Viken', 'HOKO2', 'ry-wc-city-select'),
	],
	'HOKO3' => [
		_x('Fagelfors', 'HOKO3', 'ry-wc-city-select'),
		_x('Fagerhult', 'HOKO3', 'ry-wc-city-select'),
		_x('Hoegsby', 'HOKO3', 'ry-wc-city-select'),
		_x('Langemala', 'HOKO3', 'ry-wc-city-select'),
	],
	'HOKO4' => [
		_x('Hoeoer', 'HOKO4', 'ry-wc-city-select'),
		_x('Ringsjoe, del', 'HOKO4', 'ry-wc-city-select'),
	],
	'HOKO5' => [
		_x('Hoerby', 'HOKO5', 'ry-wc-city-select'),
		_x('Vaesterstad', 'HOKO5', 'ry-wc-city-select'),
	],
	'HUKO' => [
		_x('Flemingsberg', 'HUKO', 'ry-wc-city-select'),
		_x('Huddinge', 'HUKO', 'ry-wc-city-select'),
		_x('S:t Mikael', 'HUKO', 'ry-wc-city-select'),
		_x('Trangsund', 'HUKO', 'ry-wc-city-select'),
	],
	'HUKO2' => [
		_x('Bjuraker-Norrbo', 'HUKO2', 'ry-wc-city-select'),
		_x('Delsbo', 'HUKO2', 'ry-wc-city-select'),
		_x('Enanger-Njutanger', 'HUKO2', 'ry-wc-city-select'),
		_x('Forsa-Hoeg', 'HUKO2', 'ry-wc-city-select'),
		_x('Haelsingtuna', 'HUKO2', 'ry-wc-city-select'),
		_x('Hudiksvall-Idenor', 'HUKO2', 'ry-wc-city-select'),
		_x('Rogsta', 'HUKO2', 'ry-wc-city-select'),
	],
	'HUKO3' => [
		_x('Hultsfred', 'HUKO3', 'ry-wc-city-select'),
		_x('Jaereda', 'HUKO3', 'ry-wc-city-select'),
		_x('Loenneberga', 'HUKO3', 'ry-wc-city-select'),
		_x('Malilla med Gardveda', 'HUKO3', 'ry-wc-city-select'),
		_x('Moerlunda-Tveta', 'HUKO3', 'ry-wc-city-select'),
		_x('Vena', 'HUKO3', 'ry-wc-city-select'),
		_x('Virserum', 'HUKO3', 'ry-wc-city-select'),
	],
	'HYKO' => [
		_x('Draengsered', 'HYKO', 'ry-wc-city-select'),
		_x('Faergaryd', 'HYKO', 'ry-wc-city-select'),
		_x('Femsjoe', 'HYKO', 'ry-wc-city-select'),
		_x('Jaelluntofta', 'HYKO', 'ry-wc-city-select'),
		_x('Kinnared', 'HYKO', 'ry-wc-city-select'),
		_x('Langaryd', 'HYKO', 'ry-wc-city-select'),
		_x('Soedra Unnaryd', 'HYKO', 'ry-wc-city-select'),
		_x('Torup', 'HYKO', 'ry-wc-city-select'),
	],
	'JAKO' => [
		_x('Barkarby', 'JAKO', 'ry-wc-city-select'),
		_x('Jakobsberg', 'JAKO', 'ry-wc-city-select'),
		_x('Kallhaell', 'JAKO', 'ry-wc-city-select'),
		_x('Viksjoe', 'JAKO', 'ry-wc-city-select'),
	],
	'JOKO' => [
		_x('Jokkmokk', 'JOKO', 'ry-wc-city-select'),
	],
	'JOKO2' => [
		_x('Bankeryd', 'JOKO2', 'ry-wc-city-select'),
		_x('Barnarp', 'JOKO2', 'ry-wc-city-select'),
		_x('Graenna', 'JOKO2', 'ry-wc-city-select'),
		_x('Hakarp', 'JOKO2', 'ry-wc-city-select'),
		_x('Huskvarna', 'JOKO2', 'ry-wc-city-select'),
		_x('Jaerstorp', 'JOKO2', 'ry-wc-city-select'),
		_x('Joenkoepings Kristina-Ljungarum', 'JOKO2', 'ry-wc-city-select'),
		_x('Joenkoepings Sofia', 'JOKO2', 'ry-wc-city-select'),
		_x('Lekeryd', 'JOKO2', 'ry-wc-city-select'),
		_x('Mansarp', 'JOKO2', 'ry-wc-city-select'),
		_x('Norra Mo', 'JOKO2', 'ry-wc-city-select'),
		_x('Norrahammar', 'JOKO2', 'ry-wc-city-select'),
		_x('OEdestugu', 'JOKO2', 'ry-wc-city-select'),
		_x('OElmstad', 'JOKO2', 'ry-wc-city-select'),
		_x('Rogberga-OEggestorp', 'JOKO2', 'ry-wc-city-select'),
		_x('Skaerstad', 'JOKO2', 'ry-wc-city-select'),
		_x('Visingsoe', 'JOKO2', 'ry-wc-city-select'),
	],
	'KAKO' => [
		_x('Nederkalix', 'KAKO', 'ry-wc-city-select'),
		_x('Toere', 'KAKO', 'ry-wc-city-select'),
	],
	'KAKO2' => [
		_x('Aby', 'KAKO2', 'ry-wc-city-select'),
		_x('Arby', 'KAKO2', 'ry-wc-city-select'),
		_x('Doerby', 'KAKO2', 'ry-wc-city-select'),
		_x('Foerloesa-Klaeckeberga', 'KAKO2', 'ry-wc-city-select'),
		_x('Hagby', 'KAKO2', 'ry-wc-city-select'),
		_x('Halltorp', 'KAKO2', 'ry-wc-city-select'),
		_x('Heliga Korset', 'KAKO2', 'ry-wc-city-select'),
		_x('Hossmo', 'KAKO2', 'ry-wc-city-select'),
		_x('Kalmar S:t Johannes', 'KAKO2', 'ry-wc-city-select'),
		_x('Kalmar domkyrkofoers.', 'KAKO2', 'ry-wc-city-select'),
		_x('Karlslunda', 'KAKO2', 'ry-wc-city-select'),
		_x('Ljungby', 'KAKO2', 'ry-wc-city-select'),
		_x('Mortorp', 'KAKO2', 'ry-wc-city-select'),
		_x('Ryssby', 'KAKO2', 'ry-wc-city-select'),
		_x('S:ta Birgitta', 'KAKO2', 'ry-wc-city-select'),
		_x('Tva systrar', 'KAKO2', 'ry-wc-city-select'),
		_x('Voxtorp', 'KAKO2', 'ry-wc-city-select'),
	],
	'KAKO3' => [
		_x('Brevik', 'KAKO3', 'ry-wc-city-select'),
		_x('Karlsborg', 'KAKO3', 'ry-wc-city-select'),
		_x('Moelltorp', 'KAKO3', 'ry-wc-city-select'),
		_x('Undenaes', 'KAKO3', 'ry-wc-city-select'),
	],
	'KAKO4' => [
		_x('Aryd', 'KAKO4', 'ry-wc-city-select'),
		_x('Asarum', 'KAKO4', 'ry-wc-city-select'),
		_x('Haellaryd', 'KAKO4', 'ry-wc-city-select'),
		_x('Karlshamn', 'KAKO4', 'ry-wc-city-select'),
		_x('Moerrum-Elleholm', 'KAKO4', 'ry-wc-city-select'),
		_x('Ringamala', 'KAKO4', 'ry-wc-city-select'),
	],
	'KAKO5' => [
		_x('Karlskoga', 'KAKO5', 'ry-wc-city-select'),
	],
	'KAKO6' => [
		_x('Aspoe', 'KAKO6', 'ry-wc-city-select'),
		_x('Fridlevstad', 'KAKO6', 'ry-wc-city-select'),
		_x('Hassloe', 'KAKO6', 'ry-wc-city-select'),
		_x('Jaemjoe', 'KAKO6', 'ry-wc-city-select'),
		_x('Karlskrona stadsfoers.', 'KAKO6', 'ry-wc-city-select'),
		_x('Kristianopel', 'KAKO6', 'ry-wc-city-select'),
		_x('Lycka', 'KAKO6', 'ry-wc-city-select'),
		_x('Naettraby', 'KAKO6', 'ry-wc-city-select'),
		_x('Ramdala', 'KAKO6', 'ry-wc-city-select'),
		_x('Roedeby', 'KAKO6', 'ry-wc-city-select'),
		_x('Sillhoevda', 'KAKO6', 'ry-wc-city-select'),
		_x('Sturkoe', 'KAKO6', 'ry-wc-city-select'),
		_x('Torhamn', 'KAKO6', 'ry-wc-city-select'),
		_x('Tving', 'KAKO6', 'ry-wc-city-select'),
	],
	'KAKO7' => [
		_x('Alster-Nyedsbygden', 'KAKO7', 'ry-wc-city-select'),
		_x('Grava', 'KAKO7', 'ry-wc-city-select'),
		_x('Karlstads domkyrkofoers.', 'KAKO7', 'ry-wc-city-select'),
		_x('Nor-Segerstad', 'KAKO7', 'ry-wc-city-select'),
		_x('Norrstrand', 'KAKO7', 'ry-wc-city-select'),
		_x('Vaese-Fagelvik', 'KAKO7', 'ry-wc-city-select'),
		_x('Vaesterstrand', 'KAKO7', 'ry-wc-city-select'),
	],
	'KAKO8' => [
		_x('Bjoerkvik', 'KAKO8', 'ry-wc-city-select'),
		_x('Floda', 'KAKO8', 'ry-wc-city-select'),
		_x('Julita', 'KAKO8', 'ry-wc-city-select'),
		_x('Katrineholm-Stora Malm', 'KAKO8', 'ry-wc-city-select'),
		_x('Lerbo', 'KAKO8', 'ry-wc-city-select'),
		_x('Naevertorp-OEstra Vingaker', 'KAKO8', 'ry-wc-city-select'),
		_x('Skoeldinge', 'KAKO8', 'ry-wc-city-select'),
	],
	'KAKO9' => [
		_x('Dagstorp', 'KAKO9', 'ry-wc-city-select'),
		_x('Hofterup', 'KAKO9', 'ry-wc-city-select'),
		_x('Kaevlinge', 'KAKO9', 'ry-wc-city-select'),
		_x('Lackalaenga-Staevie', 'KAKO9', 'ry-wc-city-select'),
		_x('Loeddebygden', 'KAKO9', 'ry-wc-city-select'),
		_x('Vaestra Karaby', 'KAKO9', 'ry-wc-city-select'),
	],
	'KIKO' => [
		_x('Boda', 'KIKO', 'ry-wc-city-select'),
		_x('Frykerud', 'KIKO', 'ry-wc-city-select'),
		_x('Stora Kil', 'KIKO', 'ry-wc-city-select'),
	],
	'KIKO2' => [
		_x('Haegerstad', 'KIKO2', 'ry-wc-city-select'),
		_x('Horn', 'KIKO2', 'ry-wc-city-select'),
		_x('Hycklinge', 'KIKO2', 'ry-wc-city-select'),
		_x('Kaettilstad', 'KIKO2', 'ry-wc-city-select'),
		_x('Kisa', 'KIKO2', 'ry-wc-city-select'),
		_x('Oppeby', 'KIKO2', 'ry-wc-city-select'),
		_x('Tidersrum', 'KIKO2', 'ry-wc-city-select'),
		_x('Tjaerstad', 'KIKO2', 'ry-wc-city-select'),
		_x('Vaestra Eneby', 'KIKO2', 'ry-wc-city-select'),
	],
	'KIKO3' => [
		_x('Jukkasjaervi', 'KIKO3', 'ry-wc-city-select'),
		_x('Karesuando', 'KIKO3', 'ry-wc-city-select'),
		_x('Vittangi', 'KIKO3', 'ry-wc-city-select'),
	],
	'KLKO' => [
		_x('Faeringtofta', 'KLKO', 'ry-wc-city-select'),
		_x('Klippan', 'KLKO', 'ry-wc-city-select'),
		_x('OEstra Ljungby', 'KLKO', 'ry-wc-city-select'),
		_x('Riseberga', 'KLKO', 'ry-wc-city-select'),
	],
	'KNKO' => [
		_x('Alsike', 'KNKO', 'ry-wc-city-select'),
		_x('Husby-Langhundra', 'KNKO', 'ry-wc-city-select'),
		_x('Knivsta', 'KNKO', 'ry-wc-city-select'),
		_x('Lagga', 'KNKO', 'ry-wc-city-select'),
		_x('OEstuna', 'KNKO', 'ry-wc-city-select'),
		_x('Vassunda', 'KNKO', 'ry-wc-city-select'),
	],
	'KOKO' => [
		_x('Himmeta-Bro', 'KOKO', 'ry-wc-city-select'),
		_x('Koeping', 'KOKO', 'ry-wc-city-select'),
		_x('Kolsva', 'KOKO', 'ry-wc-city-select'),
		_x('Munktorp', 'KOKO', 'ry-wc-city-select'),
		_x('Odensvi', 'KOKO', 'ry-wc-city-select'),
		_x('Vaestra Skedvi', 'KOKO', 'ry-wc-city-select'),
	],
	'KRKO' => [
		_x('Bjaertra', 'KRKO', 'ry-wc-city-select'),
		_x('Dal', 'KRKO', 'ry-wc-city-select'),
		_x('Gudmundra', 'KRKO', 'ry-wc-city-select'),
		_x('Nora-Skog', 'KRKO', 'ry-wc-city-select'),
		_x('Nordingra', 'KRKO', 'ry-wc-city-select'),
		_x('Styrnaes', 'KRKO', 'ry-wc-city-select'),
		_x('Torsaker', 'KRKO', 'ry-wc-city-select'),
		_x('Ullanger', 'KRKO', 'ry-wc-city-select'),
		_x('Vibyggera', 'KRKO', 'ry-wc-city-select'),
		_x('Ytterlaennaes', 'KRKO', 'ry-wc-city-select'),
	],
	'KRKO2' => [
		_x('AEsphult', 'KRKO2', 'ry-wc-city-select'),
		_x('Ahus', 'KRKO2', 'ry-wc-city-select'),
		_x('Arasloev', 'KRKO2', 'ry-wc-city-select'),
		_x('Baeckaskog', 'KRKO2', 'ry-wc-city-select'),
		_x('Degeberga', 'KRKO2', 'ry-wc-city-select'),
		_x('Everoedsbygden', 'KRKO2', 'ry-wc-city-select'),
		_x('Fjaelkinge-Nymoe', 'KRKO2', 'ry-wc-city-select'),
		_x('Gustav Adolf-Rinkaby', 'KRKO2', 'ry-wc-city-select'),
		_x('Hoerroed', 'KRKO2', 'ry-wc-city-select'),
		_x('Huaroed', 'KRKO2', 'ry-wc-city-select'),
		_x('Koepinge', 'KRKO2', 'ry-wc-city-select'),
		_x('Kristianstads Heliga Trefaldighet', 'KRKO2', 'ry-wc-city-select'),
		_x('Linderoed', 'KRKO2', 'ry-wc-city-select'),
		_x('Maglehem', 'KRKO2', 'ry-wc-city-select'),
		_x('Norra Asum', 'KRKO2', 'ry-wc-city-select'),
		_x('Nosaby', 'KRKO2', 'ry-wc-city-select'),
		_x('Oppmanna', 'KRKO2', 'ry-wc-city-select'),
		_x('Traene-Djurroed', 'KRKO2', 'ry-wc-city-select'),
		_x('Vae-Skepparsloev', 'KRKO2', 'ry-wc-city-select'),
		_x('Vaestra och OEstra Vram', 'KRKO2', 'ry-wc-city-select'),
		_x('Vanga', 'KRKO2', 'ry-wc-city-select'),
		_x('Vittskoevle', 'KRKO2', 'ry-wc-city-select'),
	],
	'KRKO3' => [
		_x('Kristinehamn', 'KRKO3', 'ry-wc-city-select'),
		_x('OElme', 'KRKO3', 'ry-wc-city-select'),
		_x('Rudskoga', 'KRKO3', 'ry-wc-city-select'),
		_x('Visnum', 'KRKO3', 'ry-wc-city-select'),
		_x('Visnums-Kil', 'KRKO3', 'ry-wc-city-select'),
	],
	'KRKO4' => [
		_x('Alsen', 'KRKO4', 'ry-wc-city-select'),
		_x('As', 'KRKO4', 'ry-wc-city-select'),
		_x('Aspas', 'KRKO4', 'ry-wc-city-select'),
		_x('Foellinge, Hotagen och Laxsjoe', 'KRKO4', 'ry-wc-city-select'),
		_x('Naeskott', 'KRKO4', 'ry-wc-city-select'),
		_x('Offerdal', 'KRKO4', 'ry-wc-city-select'),
		_x('Roedoen', 'KRKO4', 'ry-wc-city-select'),
	],
	'KUKO' => [
		_x('Ekeby', 'KUKO', 'ry-wc-city-select'),
		_x('Hardemo', 'KUKO', 'ry-wc-city-select'),
		_x('Kumla', 'KUKO', 'ry-wc-city-select'),
	],
	'KUKO2' => [
		_x('Halta', 'KUKO2', 'ry-wc-city-select'),
		_x('Harestad', 'KUKO2', 'ry-wc-city-select'),
		_x('Kareby', 'KUKO2', 'ry-wc-city-select'),
		_x('Kungaelv', 'KUKO2', 'ry-wc-city-select'),
		_x('Lycke', 'KUKO2', 'ry-wc-city-select'),
		_x('Marstrand', 'KUKO2', 'ry-wc-city-select'),
		_x('Romelanda', 'KUKO2', 'ry-wc-city-select'),
		_x('Solberga', 'KUKO2', 'ry-wc-city-select'),
		_x('Torsby', 'KUKO2', 'ry-wc-city-select'),
		_x('Ytterby', 'KUKO2', 'ry-wc-city-select'),
	],
	'KUKO3' => [
		_x('AElvsaker', 'KUKO3', 'ry-wc-city-select'),
		_x('Fjaeras', 'KUKO3', 'ry-wc-city-select'),
		_x('Foerlanda', 'KUKO3', 'ry-wc-city-select'),
		_x('Frillesas', 'KUKO3', 'ry-wc-city-select'),
		_x('Gaellinge', 'KUKO3', 'ry-wc-city-select'),
		_x('Hanhals', 'KUKO3', 'ry-wc-city-select'),
		_x('Idala', 'KUKO3', 'ry-wc-city-select'),
		_x('Kungsbacka', 'KUKO3', 'ry-wc-city-select'),
		_x('Landa', 'KUKO3', 'ry-wc-city-select'),
		_x('OElmevalla', 'KUKO3', 'ry-wc-city-select'),
		_x('Onsala', 'KUKO3', 'ry-wc-city-select'),
		_x('Slaep', 'KUKO3', 'ry-wc-city-select'),
		_x('Toeloe', 'KUKO3', 'ry-wc-city-select'),
		_x('Vallda', 'KUKO3', 'ry-wc-city-select'),
	],
	'KUKO4' => [
		_x('Kungsoer', 'KUKO4', 'ry-wc-city-select'),
	],
	'LAKO' => [
		_x('Hassloev-Vaxtorp', 'LAKO', 'ry-wc-city-select'),
		_x('Hishult', 'LAKO', 'ry-wc-city-select'),
		_x('Knaered', 'LAKO', 'ry-wc-city-select'),
		_x('Laholm', 'LAKO', 'ry-wc-city-select'),
		_x('Raennesloev-Ysby', 'LAKO', 'ry-wc-city-select'),
		_x('Skummesloev', 'LAKO', 'ry-wc-city-select'),
		_x('Veinge-Tjaerby', 'LAKO', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Asmundtorp-Tofta', 'LA', 'ry-wc-city-select'),
		_x('Glumsloev', 'LA', 'ry-wc-city-select'),
		_x('Landskrona, del', 'LA', 'ry-wc-city-select'),
		_x('Saxtorp-Anneloev', 'LA', 'ry-wc-city-select'),
	],
	'LAKO2' => [
		_x('Finneroedja-Tived', 'LAKO2', 'ry-wc-city-select'),
		_x('Ramundeboda', 'LAKO2', 'ry-wc-city-select'),
		_x('Skagershult', 'LAKO2', 'ry-wc-city-select'),
	],
	'LEKO' => [
		_x('Edsberg', 'LEKO', 'ry-wc-city-select'),
		_x('Knista', 'LEKO', 'ry-wc-city-select'),
	],
	'LEKO2' => [
		_x('Al', 'LEKO2', 'ry-wc-city-select'),
		_x('Djura', 'LEKO2', 'ry-wc-city-select'),
		_x('Leksand', 'LEKO2', 'ry-wc-city-select'),
		_x('Siljansnaes', 'LEKO2', 'ry-wc-city-select'),
	],
	'LEKO3' => [
		_x('Lerum', 'LEKO3', 'ry-wc-city-select'),
		_x('OEstad', 'LEKO3', 'ry-wc-city-select'),
		_x('Skallsjoe', 'LEKO3', 'ry-wc-city-select'),
		_x('Stora Lundby', 'LEKO3', 'ry-wc-city-select'),
	],
	'LEKO4' => [
		_x('Ekeberga', 'LEKO4', 'ry-wc-city-select'),
		_x('Hovmantorp', 'LEKO4', 'ry-wc-city-select'),
		_x('Lessebo', 'LEKO4', 'ry-wc-city-select'),
		_x('Ljuder', 'LEKO4', 'ry-wc-city-select'),
	],
	'LI' => [
		_x('Lidingoe', 'LI', 'ry-wc-city-select'),
	],
	'LIKO' => [
		_x('Jaerpas', 'LIKO', 'ry-wc-city-select'),
		_x('Kallands-Rada', 'LIKO', 'ry-wc-city-select'),
		_x('Lidkoeping', 'LIKO', 'ry-wc-city-select'),
		_x('OErsloesa', 'LIKO', 'ry-wc-city-select'),
		_x('Saevare', 'LIKO', 'ry-wc-city-select'),
		_x('Sunnersberg', 'LIKO', 'ry-wc-city-select'),
	],
	'LIEDKO' => [
		_x('Ale-Skoevde', 'LIEDKO', 'ry-wc-city-select'),
		_x('Fuxerna-Asbraecka', 'LIEDKO', 'ry-wc-city-select'),
		_x('Hjaertum', 'LIEDKO', 'ry-wc-city-select'),
		_x('S:t Peder', 'LIEDKO', 'ry-wc-city-select'),
		_x('Tunge', 'LIEDKO', 'ry-wc-city-select'),
		_x('Vaesterlanda', 'LIEDKO', 'ry-wc-city-select'),
	],
	'LIKO2' => [
		_x('Fellingsbro', 'LIKO2', 'ry-wc-city-select'),
		_x('Guldsmedshyttan', 'LIKO2', 'ry-wc-city-select'),
		_x('Lindesberg', 'LIKO2', 'ry-wc-city-select'),
		_x('Naesby', 'LIKO2', 'ry-wc-city-select'),
		_x('Ramsberg', 'LIKO2', 'ry-wc-city-select'),
	],
	'LIKO3' => [
		_x('Akerbo', 'LIKO3', 'ry-wc-city-select'),
		_x('Gammalkil', 'LIKO3', 'ry-wc-city-select'),
		_x('Gottfridsberg', 'LIKO3', 'ry-wc-city-select'),
		_x('Kaerna', 'LIKO3', 'ry-wc-city-select'),
		_x('Kaga', 'LIKO3', 'ry-wc-city-select'),
		_x('Landeryd', 'LIKO3', 'ry-wc-city-select'),
		_x('Ledberg', 'LIKO3', 'ry-wc-city-select'),
		_x('Linkoepings Berga', 'LIKO3', 'ry-wc-city-select'),
		_x('Linkoepings Johannelund', 'LIKO3', 'ry-wc-city-select'),
		_x('Linkoepings Ryd', 'LIKO3', 'ry-wc-city-select'),
		_x('Linkoepings S:t Lars', 'LIKO3', 'ry-wc-city-select'),
		_x('Linkoepings Skaeggetorp', 'LIKO3', 'ry-wc-city-select'),
		_x('Linkoepings domkyrkofoers.', 'LIKO3', 'ry-wc-city-select'),
		_x('Nykil', 'LIKO3', 'ry-wc-city-select'),
		_x('Skeda', 'LIKO3', 'ry-wc-city-select'),
		_x('Slaka', 'LIKO3', 'ry-wc-city-select'),
		_x('Stjaernorp', 'LIKO3', 'ry-wc-city-select'),
		_x('Ulrika', 'LIKO3', 'ry-wc-city-select'),
		_x('Vardnaes', 'LIKO3', 'ry-wc-city-select'),
		_x('Vikingstad', 'LIKO3', 'ry-wc-city-select'),
		_x('Vist', 'LIKO3', 'ry-wc-city-select'),
		_x('Vreta kloster', 'LIKO3', 'ry-wc-city-select'),
	],
	'LJKO' => [
		_x('Agunnaryd', 'LJKO', 'ry-wc-city-select'),
		_x('Angelstad', 'LJKO', 'ry-wc-city-select'),
		_x('Annerstad', 'LJKO', 'ry-wc-city-select'),
		_x('Berga', 'LJKO', 'ry-wc-city-select'),
		_x('Bolmsoe', 'LJKO', 'ry-wc-city-select'),
		_x('Doerarp', 'LJKO', 'ry-wc-city-select'),
		_x('Lidhult', 'LJKO', 'ry-wc-city-select'),
		_x('Ljungby', 'LJKO', 'ry-wc-city-select'),
		_x('Ljungby Maria', 'LJKO', 'ry-wc-city-select'),
		_x('Odensjoe', 'LJKO', 'ry-wc-city-select'),
		_x('Ryssby', 'LJKO', 'ry-wc-city-select'),
		_x('Soedra Ljunga', 'LJKO', 'ry-wc-city-select'),
		_x('Tannaker', 'LJKO', 'ry-wc-city-select'),
		_x('Torpa', 'LJKO', 'ry-wc-city-select'),
		_x('Tutaryd', 'LJKO', 'ry-wc-city-select'),
		_x('Vittaryd', 'LJKO', 'ry-wc-city-select'),
		_x('Vra', 'LJKO', 'ry-wc-city-select'),
	],
	'LJKO2' => [
		_x('Faerila', 'LJKO2', 'ry-wc-city-select'),
		_x('Jaervsoe', 'LJKO2', 'ry-wc-city-select'),
		_x('Karboele', 'LJKO2', 'ry-wc-city-select'),
		_x('Ljusdal-Ramsjoe', 'LJKO2', 'ry-wc-city-select'),
		_x('Los-Hamra', 'LJKO2', 'ry-wc-city-select'),
	],
	'LJKO3' => [
		_x('Ljusnarsberg', 'LJKO3', 'ry-wc-city-select'),
	],
	'LOKO' => [
		_x('Bjaerred', 'LOKO', 'ry-wc-city-select'),
		_x('Lomma', 'LOKO', 'ry-wc-city-select'),
	],
	'LUKO' => [
		_x('Graengesberg', 'LUKO', 'ry-wc-city-select'),
		_x('Grangaerde', 'LUKO', 'ry-wc-city-select'),
		_x('Ludvika', 'LUKO', 'ry-wc-city-select'),
		_x('Saefsnaes', 'LUKO', 'ry-wc-city-select'),
	],
	'LUKO2' => [
		_x('Lulea domkyrkofoers.', 'LUKO2', 'ry-wc-city-select'),
		_x('Nederlulea', 'LUKO2', 'ry-wc-city-select'),
		_x('OErnaeset', 'LUKO2', 'ry-wc-city-select'),
		_x('Ranea', 'LUKO2', 'ry-wc-city-select'),
	],
	'LUKO3' => [
		_x('Dalby', 'LUKO3', 'ry-wc-city-select'),
		_x('Genarp', 'LUKO3', 'ry-wc-city-select'),
		_x('Helgeand', 'LUKO3', 'ry-wc-city-select'),
		_x('Lunds Allhelgonafoers.', 'LUKO3', 'ry-wc-city-select'),
		_x('Lunds domkyrkofoers.', 'LUKO3', 'ry-wc-city-select'),
		_x('Norra Noebbeloev', 'LUKO3', 'ry-wc-city-select'),
		_x('OEstra Torn', 'LUKO3', 'ry-wc-city-select'),
		_x('S:t Hans', 'LUKO3', 'ry-wc-city-select'),
		_x('S:t Peters Kloster', 'LUKO3', 'ry-wc-city-select'),
		_x('Soedra Sandby', 'LUKO3', 'ry-wc-city-select'),
		_x('Stora Raby', 'LUKO3', 'ry-wc-city-select'),
		_x('Torn', 'LUKO3', 'ry-wc-city-select'),
		_x('Veberoed', 'LUKO3', 'ry-wc-city-select'),
	],
	'LYKO' => [
		_x('Lycksele', 'LYKO', 'ry-wc-city-select'),
	],
	'LYKO2' => [
		_x('Brastad', 'LYKO2', 'ry-wc-city-select'),
		_x('Bro', 'LYKO2', 'ry-wc-city-select'),
		_x('Lyse', 'LYKO2', 'ry-wc-city-select'),
		_x('Lysekil', 'LYKO2', 'ry-wc-city-select'),
		_x('Skaftoe', 'LYKO2', 'ry-wc-city-select'),
	],
	'MAKO' => [
		_x('Mala', 'MAKO', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Bunkeflo', 'MA', 'ry-wc-city-select'),
		_x('Eriksfaelt', 'MA', 'ry-wc-city-select'),
		_x('Fosie', 'MA', 'ry-wc-city-select'),
		_x('Husie och Soedra Sallerup', 'MA', 'ry-wc-city-select'),
		_x('Hyllie', 'MA', 'ry-wc-city-select'),
		_x('Kirseberg', 'MA', 'ry-wc-city-select'),
		_x('Kulladal', 'MA', 'ry-wc-city-select'),
		_x('Limhamn', 'MA', 'ry-wc-city-select'),
		_x('Malmoe S:t Johannes', 'MA', 'ry-wc-city-select'),
		_x('Malmoe S:t Pauli', 'MA', 'ry-wc-city-select'),
		_x('Malmoe S:t Petri', 'MA', 'ry-wc-city-select'),
		_x('Moellevangen-Sofielund', 'MA', 'ry-wc-city-select'),
		_x('Oxie', 'MA', 'ry-wc-city-select'),
		_x('Slottsstaden', 'MA', 'ry-wc-city-select'),
		_x('Tygelsjoe-Vaestra Klagstorp', 'MA', 'ry-wc-city-select'),
		_x('Vaestra Skraevlinge', 'MA', 'ry-wc-city-select'),
	],
	'MAKO2' => [
		_x('Lima-Transtrand', 'MAKO2', 'ry-wc-city-select'),
		_x('Malung', 'MAKO2', 'ry-wc-city-select'),
	],
	'MAKO3' => [
		_x('Lugnas', 'MAKO3', 'ry-wc-city-select'),
		_x('Lyrestad', 'MAKO3', 'ry-wc-city-select'),
		_x('Mariestad', 'MAKO3', 'ry-wc-city-select'),
		_x('Ullervad', 'MAKO3', 'ry-wc-city-select'),
	],
	'MAKO4' => [
		_x('Hinneryd', 'MAKO4', 'ry-wc-city-select'),
		_x('Markaryd', 'MAKO4', 'ry-wc-city-select'),
		_x('Traryd', 'MAKO4', 'ry-wc-city-select'),
	],
	'MAKO5' => [
		_x('AElekulla', 'MAKO5', 'ry-wc-city-select'),
		_x('Berghem', 'MAKO5', 'ry-wc-city-select'),
		_x('Fotskael', 'MAKO5', 'ry-wc-city-select'),
		_x('Fritsla', 'MAKO5', 'ry-wc-city-select'),
		_x('Hajom', 'MAKO5', 'ry-wc-city-select'),
		_x('Horred', 'MAKO5', 'ry-wc-city-select'),
		_x('Hyssna', 'MAKO5', 'ry-wc-city-select'),
		_x('Istorp', 'MAKO5', 'ry-wc-city-select'),
		_x('Kinna', 'MAKO5', 'ry-wc-city-select'),
		_x('OErby-Skene', 'MAKO5', 'ry-wc-city-select'),
		_x('OExabaeck', 'MAKO5', 'ry-wc-city-select'),
		_x('OExnevalla', 'MAKO5', 'ry-wc-city-select'),
		_x('Saetila', 'MAKO5', 'ry-wc-city-select'),
		_x('Skephult', 'MAKO5', 'ry-wc-city-select'),
		_x('Surteby-Kattunga', 'MAKO5', 'ry-wc-city-select'),
		_x('Torestorp', 'MAKO5', 'ry-wc-city-select'),
		_x('Tostared', 'MAKO5', 'ry-wc-city-select'),
	],
	'MEKO' => [
		_x('Bolstad', 'MEKO', 'ry-wc-city-select'),
		_x('Dalskog', 'MEKO', 'ry-wc-city-select'),
		_x('Erikstad', 'MEKO', 'ry-wc-city-select'),
		_x('Grinstad', 'MEKO', 'ry-wc-city-select'),
		_x('Gunnarsnaes', 'MEKO', 'ry-wc-city-select'),
		_x('Holm', 'MEKO', 'ry-wc-city-select'),
		_x('Jaern', 'MEKO', 'ry-wc-city-select'),
		_x('OEr', 'MEKO', 'ry-wc-city-select'),
		_x('Skallerud', 'MEKO', 'ry-wc-city-select'),
	],
	'MJKO' => [
		_x('Bjaelbo', 'MJKO', 'ry-wc-city-select'),
		_x('Herrberga', 'MJKO', 'ry-wc-city-select'),
		_x('Jaerstad', 'MJKO', 'ry-wc-city-select'),
		_x('Mjoelby', 'MJKO', 'ry-wc-city-select'),
		_x('Normloesa', 'MJKO', 'ry-wc-city-select'),
		_x('OEstra Tollstad', 'MJKO', 'ry-wc-city-select'),
		_x('Skaenninge-Allhelgona', 'MJKO', 'ry-wc-city-select'),
		_x('Skeppsas', 'MJKO', 'ry-wc-city-select'),
		_x('Sya', 'MJKO', 'ry-wc-city-select'),
		_x('Vaederstad', 'MJKO', 'ry-wc-city-select'),
		_x('Vaestra Harg', 'MJKO', 'ry-wc-city-select'),
		_x('Vallerstad', 'MJKO', 'ry-wc-city-select'),
		_x('Veta', 'MJKO', 'ry-wc-city-select'),
		_x('Viby', 'MJKO', 'ry-wc-city-select'),
	],
	'MOKO' => [
		_x('Faessberg', 'MOKO', 'ry-wc-city-select'),
		_x('Kallered', 'MOKO', 'ry-wc-city-select'),
		_x('Lindome', 'MOKO', 'ry-wc-city-select'),
		_x('Stensjoen', 'MOKO', 'ry-wc-city-select'),
	],
	'MOKO2' => [
		_x('Alem', 'MOKO2', 'ry-wc-city-select'),
		_x('Fliseryd', 'MOKO2', 'ry-wc-city-select'),
		_x('Moensteras', 'MOKO2', 'ry-wc-city-select'),
	],
	'MOKO3' => [
		_x('Mora', 'MOKO3', 'ry-wc-city-select'),
		_x('Solleroen', 'MOKO3', 'ry-wc-city-select'),
		_x('Vamhus', 'MOKO3', 'ry-wc-city-select'),
		_x('Venjan', 'MOKO3', 'ry-wc-city-select'),
	],
	'MOKO4' => [
		_x('Algutsrum', 'MOKO4', 'ry-wc-city-select'),
		_x('Gloemminge', 'MOKO4', 'ry-wc-city-select'),
		_x('Hulterstad-Stenasa', 'MOKO4', 'ry-wc-city-select'),
		_x('Moerbylanga-Kastloesa', 'MOKO4', 'ry-wc-city-select'),
		_x('Norra Moeckleby, Sandby och Gardby', 'MOKO4', 'ry-wc-city-select'),
		_x('Resmo-Vickleby', 'MOKO4', 'ry-wc-city-select'),
		_x('Sydoeland', 'MOKO4', 'ry-wc-city-select'),
		_x('Torslunda', 'MOKO4', 'ry-wc-city-select'),
	],
	'MOKO5' => [
		_x('Aska, del', 'MOKO5', 'ry-wc-city-select'),
		_x('Borensberg', 'MOKO5', 'ry-wc-city-select'),
		_x('Fornasa', 'MOKO5', 'ry-wc-city-select'),
		_x('Godegard', 'MOKO5', 'ry-wc-city-select'),
		_x('Klockrike', 'MOKO5', 'ry-wc-city-select'),
		_x('Motala', 'MOKO5', 'ry-wc-city-select'),
		_x('Tjaellmo', 'MOKO5', 'ry-wc-city-select'),
		_x('Vaestra Ny', 'MOKO5', 'ry-wc-city-select'),
	],
	'MUKO' => [
		_x('Mullsjoe', 'MUKO', 'ry-wc-city-select'),
		_x('Sandhem-Utvaengstorp', 'MUKO', 'ry-wc-city-select'),
	],
	'MUKO2' => [
		_x('Baerfendal', 'MUKO2', 'ry-wc-city-select'),
		_x('Foss', 'MUKO2', 'ry-wc-city-select'),
		_x('Soerbygden', 'MUKO2', 'ry-wc-city-select'),
		_x('Svarteborg', 'MUKO2', 'ry-wc-city-select'),
	],
	'MUKO3' => [
		_x('Munkfors', 'MUKO3', 'ry-wc-city-select'),
		_x('Ransaeter', 'MUKO3', 'ry-wc-city-select'),
	],
	'NAKO' => [
		_x('Boo', 'NAKO', 'ry-wc-city-select'),
		_x('Nacka', 'NAKO', 'ry-wc-city-select'),
		_x('Saltsjoebaden', 'NAKO', 'ry-wc-city-select'),
	],
	'NAKO2' => [
		_x('Almesakra', 'NAKO2', 'ry-wc-city-select'),
		_x('Barkeryd', 'NAKO2', 'ry-wc-city-select'),
		_x('Bringetofta', 'NAKO2', 'ry-wc-city-select'),
		_x('Forserum', 'NAKO2', 'ry-wc-city-select'),
		_x('Malmbaeck', 'NAKO2', 'ry-wc-city-select'),
		_x('Naessjoe', 'NAKO2', 'ry-wc-city-select'),
		_x('Norra Sandsjoe', 'NAKO2', 'ry-wc-city-select'),
		_x('Norra Solberga-Flisby', 'NAKO2', 'ry-wc-city-select'),
	],
	'NOKO' => [
		_x('Jaernboas', 'NOKO', 'ry-wc-city-select'),
		_x('Nora bergsfoers.', 'NOKO', 'ry-wc-city-select'),
		_x('Viker', 'NOKO', 'ry-wc-city-select'),
	],
	'NOKO2' => [
		_x('Karbenning', 'NOKO2', 'ry-wc-city-select'),
		_x('Norberg', 'NOKO2', 'ry-wc-city-select'),
	],
	'NOKO3' => [
		_x('Bergsjoe', 'NOKO3', 'ry-wc-city-select'),
		_x('Gnarp', 'NOKO3', 'ry-wc-city-select'),
		_x('Harmanger-Jaettendal', 'NOKO3', 'ry-wc-city-select'),
		_x('Hassela', 'NOKO3', 'ry-wc-city-select'),
		_x('Ilsbo', 'NOKO3', 'ry-wc-city-select'),
	],
	'NOKO4' => [
		_x('Nordmaling', 'NOKO4', 'ry-wc-city-select'),
	],
	'NOKO5' => [
		_x('Haeradshammar', 'NOKO5', 'ry-wc-city-select'),
		_x('Jonsberg', 'NOKO5', 'ry-wc-city-select'),
		_x('Kimstad', 'NOKO5', 'ry-wc-city-select'),
		_x('Krokek', 'NOKO5', 'ry-wc-city-select'),
		_x('Kullerstad', 'NOKO5', 'ry-wc-city-select'),
		_x('Kvarsebo', 'NOKO5', 'ry-wc-city-select'),
		_x('Kvillinge', 'NOKO5', 'ry-wc-city-select'),
		_x('Norrkoepings Borg', 'NOKO5', 'ry-wc-city-select'),
		_x('Norrkoepings Hedvig', 'NOKO5', 'ry-wc-city-select'),
		_x('Norrkoepings Matteus', 'NOKO5', 'ry-wc-city-select'),
		_x('Norrkoepings OEstra Eneby', 'NOKO5', 'ry-wc-city-select'),
		_x('Norrkoepings S:t Johannes', 'NOKO5', 'ry-wc-city-select'),
		_x('Norrkoepings S:t Olai', 'NOKO5', 'ry-wc-city-select'),
		_x('OEstra Husby', 'NOKO5', 'ry-wc-city-select'),
		_x('OEstra Ny', 'NOKO5', 'ry-wc-city-select'),
		_x('Roenoe', 'NOKO5', 'ry-wc-city-select'),
		_x('Simonstorp', 'NOKO5', 'ry-wc-city-select'),
		_x('Skaerkind', 'NOKO5', 'ry-wc-city-select'),
		_x('Styrstad', 'NOKO5', 'ry-wc-city-select'),
		_x('Svaertinge', 'NOKO5', 'ry-wc-city-select'),
		_x('Tingstad', 'NOKO5', 'ry-wc-city-select'),
		_x('Vaestra Vikbolandet', 'NOKO5', 'ry-wc-city-select'),
		_x('Vanga', 'NOKO5', 'ry-wc-city-select'),
		_x('Vrinnevi', 'NOKO5', 'ry-wc-city-select'),
	],
	'NOKO6' => [
		_x('Bjoerkoe-Arholma', 'NOKO6', 'ry-wc-city-select'),
		_x('Blidoe', 'NOKO6', 'ry-wc-city-select'),
		_x('Edebo', 'NOKO6', 'ry-wc-city-select'),
		_x('Edsbro', 'NOKO6', 'ry-wc-city-select'),
		_x('Estuna och Soederby-Karl', 'NOKO6', 'ry-wc-city-select'),
		_x('Fasterna', 'NOKO6', 'ry-wc-city-select'),
		_x('Froetuna', 'NOKO6', 'ry-wc-city-select'),
		_x('Gottroera', 'NOKO6', 'ry-wc-city-select'),
		_x('Haeveroe-Singoe', 'NOKO6', 'ry-wc-city-select'),
		_x('Husby, Skederid och Roe', 'NOKO6', 'ry-wc-city-select'),
		_x('Laenna', 'NOKO6', 'ry-wc-city-select'),
		_x('Lohaerad', 'NOKO6', 'ry-wc-city-select'),
		_x('Naertuna', 'NOKO6', 'ry-wc-city-select'),
		_x('Norrtaelje-Malsta', 'NOKO6', 'ry-wc-city-select'),
		_x('Radmansoe', 'NOKO6', 'ry-wc-city-select'),
		_x('Riala', 'NOKO6', 'ry-wc-city-select'),
		_x('Rimbo', 'NOKO6', 'ry-wc-city-select'),
		_x('Roslags-Bro', 'NOKO6', 'ry-wc-city-select'),
		_x('Ununge', 'NOKO6', 'ry-wc-city-select'),
		_x('Vaeddoe', 'NOKO6', 'ry-wc-city-select'),
		_x('Vaetoe', 'NOKO6', 'ry-wc-city-select'),
	],
	'NOKO7' => [
		_x('Norsjoe', 'NOKO7', 'ry-wc-city-select'),
	],
	'NYKO' => [
		_x('Baeckebo', 'NYKO', 'ry-wc-city-select'),
		_x('Haelleberga', 'NYKO', 'ry-wc-city-select'),
		_x('Kraksmala', 'NYKO', 'ry-wc-city-select'),
		_x('Kristvalla', 'NYKO', 'ry-wc-city-select'),
		_x('Madesjoe', 'NYKO', 'ry-wc-city-select'),
		_x('Nybro-S:t Sigfrid', 'NYKO', 'ry-wc-city-select'),
		_x('OErsjoe', 'NYKO', 'ry-wc-city-select'),
		_x('Oskar', 'NYKO', 'ry-wc-city-select'),
	],
	'NYKO2' => [
		_x('Kiladalen', 'NYKO2', 'ry-wc-city-select'),
		_x('Nykoepings Alla Helgona', 'NYKO2', 'ry-wc-city-select'),
		_x('Nykoepings S:t Nicolai', 'NYKO2', 'ry-wc-city-select'),
		_x('Roenoe', 'NYKO2', 'ry-wc-city-select'),
		_x('Stigtomta-Vrena', 'NYKO2', 'ry-wc-city-select'),
		_x('Tunaberg', 'NYKO2', 'ry-wc-city-select'),
		_x('Tystbergabygden', 'NYKO2', 'ry-wc-city-select'),
	],
	'NYKO3' => [
		_x('Turinge-Taxinge', 'NYKO3', 'ry-wc-city-select'),
	],
	'NYKO4' => [
		_x('Nynaeshamn', 'NYKO4', 'ry-wc-city-select'),
		_x('OEsmo-Toroe', 'NYKO4', 'ry-wc-city-select'),
		_x('Sorunda', 'NYKO4', 'ry-wc-city-select'),
	],
	'OEKO' => [
		_x('Anundsjoe', 'OEKO', 'ry-wc-city-select'),
		_x('Arnaes', 'OEKO', 'ry-wc-city-select'),
		_x('Bjoerna', 'OEKO', 'ry-wc-city-select'),
		_x('Gidea', 'OEKO', 'ry-wc-city-select'),
		_x('Grundsunda', 'OEKO', 'ry-wc-city-select'),
		_x('Mo', 'OEKO', 'ry-wc-city-select'),
		_x('Naetra', 'OEKO', 'ry-wc-city-select'),
		_x('OErnskoeldsvik', 'OEKO', 'ry-wc-city-select'),
		_x('Sidensjoe', 'OEKO', 'ry-wc-city-select'),
		_x('Sjaelevad', 'OEKO', 'ry-wc-city-select'),
		_x('Skorped', 'OEKO', 'ry-wc-city-select'),
		_x('Trehoerningsjoe', 'OEKO', 'ry-wc-city-select'),
	],
	'OEKO2' => [
		_x('Brunflo', 'OEKO2', 'ry-wc-city-select'),
		_x('Froesoe', 'OEKO2', 'ry-wc-city-select'),
		_x('Haeggenas', 'OEKO2', 'ry-wc-city-select'),
		_x('Kyrkas', 'OEKO2', 'ry-wc-city-select'),
		_x('Lit', 'OEKO2', 'ry-wc-city-select'),
		_x('Lockne', 'OEKO2', 'ry-wc-city-select'),
		_x('Marieby', 'OEKO2', 'ry-wc-city-select'),
		_x('Naes', 'OEKO2', 'ry-wc-city-select'),
		_x('Norderoe', 'OEKO2', 'ry-wc-city-select'),
		_x('OEstersund', 'OEKO2', 'ry-wc-city-select'),
		_x('Sunne', 'OEKO2', 'ry-wc-city-select'),
	],
	'OCKO' => [
		_x('Ockelbo', 'OCKO', 'ry-wc-city-select'),
	],
	'OCKO2' => [
		_x('OEckeroe', 'OCKO2', 'ry-wc-city-select'),
	],
	'ODKO' => [
		_x('OEdeshoeg', 'ODKO', 'ry-wc-city-select'),
	],
	'OLKO' => [
		_x('Jaemshoeg', 'OLKO', 'ry-wc-city-select'),
		_x('Kyrkhult', 'OLKO', 'ry-wc-city-select'),
	],
	'ORKO' => [
		_x('Adolfsberg', 'ORKO', 'ry-wc-city-select'),
		_x('Almby', 'ORKO', 'ry-wc-city-select'),
		_x('Asker', 'ORKO', 'ry-wc-city-select'),
		_x('Axberg', 'ORKO', 'ry-wc-city-select'),
		_x('Gaellersta-Norrbyas', 'ORKO', 'ry-wc-city-select'),
		_x('Glanshammar', 'ORKO', 'ry-wc-city-select'),
		_x('Laengbro', 'ORKO', 'ry-wc-city-select'),
		_x('Laennaes', 'ORKO', 'ry-wc-city-select'),
		_x('Mikael', 'ORKO', 'ry-wc-city-select'),
		_x('Mosjoe', 'ORKO', 'ry-wc-city-select'),
		_x('OErebro Nikolai', 'ORKO', 'ry-wc-city-select'),
		_x('OErebro Olaus Petri', 'ORKO', 'ry-wc-city-select'),
		_x('Stora Melloesa', 'ORKO', 'ry-wc-city-select'),
		_x('Taeby', 'ORKO', 'ry-wc-city-select'),
		_x('Tysslinge', 'ORKO', 'ry-wc-city-select'),
	],
	'ORKO2' => [
		_x('OErkelljunga', 'ORKO2', 'ry-wc-city-select'),
		_x('Rya', 'ORKO2', 'ry-wc-city-select'),
		_x('Skanes-Fagerhult', 'ORKO2', 'ry-wc-city-select'),
	],
	'ORKO3' => [
		_x('Orsa', 'ORKO3', 'ry-wc-city-select'),
	],
	'OR' => [
		_x('Langelanda', 'OR', 'ry-wc-city-select'),
		_x('Morlanda', 'OR', 'ry-wc-city-select'),
		_x('Myckleby', 'OR', 'ry-wc-city-select'),
		_x('Roera', 'OR', 'ry-wc-city-select'),
		_x('Stala', 'OR', 'ry-wc-city-select'),
		_x('Tegneby', 'OR', 'ry-wc-city-select'),
		_x('Torp', 'OR', 'ry-wc-city-select'),
	],
	'OSKO' => [
		_x('Loshult', 'OSKO', 'ry-wc-city-select'),
		_x('OErkened', 'OSKO', 'ry-wc-city-select'),
		_x('Osby-Visseltofta', 'OSKO', 'ry-wc-city-select'),
	],
	'OSKO2' => [
		_x('Doederhult', 'OSKO2', 'ry-wc-city-select'),
		_x('Kristdala', 'OSKO2', 'ry-wc-city-select'),
		_x('Misterhult', 'OSKO2', 'ry-wc-city-select'),
		_x('Oskarshamn', 'OSKO2', 'ry-wc-city-select'),
	],
	'OSKO3' => [
		_x('Ljusteroe-Kulla', 'OSKO3', 'ry-wc-city-select'),
		_x('OEsteraker-OEstra Ryd', 'OSKO3', 'ry-wc-city-select'),
	],
	'OSKO4' => [
		_x('Alunda', 'OSKO4', 'ry-wc-city-select'),
		_x('Dannemora', 'OSKO4', 'ry-wc-city-select'),
		_x('Ekeby', 'OSKO4', 'ry-wc-city-select'),
		_x('Film', 'OSKO4', 'ry-wc-city-select'),
		_x('Froesaker', 'OSKO4', 'ry-wc-city-select'),
		_x('Hoekhuvud', 'OSKO4', 'ry-wc-city-select'),
		_x('Morkarla', 'OSKO4', 'ry-wc-city-select'),
		_x('OEregrund-Graesoe', 'OSKO4', 'ry-wc-city-select'),
		_x('Skaefthammar', 'OSKO4', 'ry-wc-city-select'),
	],
	'OSGOKO' => [
		_x('Emmisloev', 'OSGOKO', 'ry-wc-city-select'),
		_x('Glimakra', 'OSGOKO', 'ry-wc-city-select'),
		_x('Hjaersas', 'OSGOKO', 'ry-wc-city-select'),
		_x('Knislinge-Gryt', 'OSGOKO', 'ry-wc-city-select'),
		_x('Kviinge', 'OSGOKO', 'ry-wc-city-select'),
		_x('OEstra Broby', 'OSGOKO', 'ry-wc-city-select'),
	],
	'OVKO' => [
		_x('Alfta', 'OVKO', 'ry-wc-city-select'),
		_x('Ovanaker', 'OVKO', 'ry-wc-city-select'),
	],
	'OVKO2' => [
		_x('OEverkalix', 'OVKO2', 'ry-wc-city-select'),
	],
	'OVKO3' => [
		_x('OEvertornea', 'OVKO3', 'ry-wc-city-select'),
	],
	'OXKO' => [
		_x('Oxeloesund', 'OXKO', 'ry-wc-city-select'),
	],
	'PAKO' => [
		_x('Korpilombolo', 'PAKO', 'ry-wc-city-select'),
		_x('Pajala', 'PAKO', 'ry-wc-city-select'),
	],
	'PAKO2' => [
		_x('Partille', 'PAKO2', 'ry-wc-city-select'),
		_x('Saevedalen', 'PAKO2', 'ry-wc-city-select'),
	],
	'PEKO' => [
		_x('Perstorp', 'PEKO', 'ry-wc-city-select'),
	],
	'PIKO' => [
		_x('Hortlax', 'PIKO', 'ry-wc-city-select'),
		_x('Norrfjaerden', 'PIKO', 'ry-wc-city-select'),
		_x('Pitea landsfoers.', 'PIKO', 'ry-wc-city-select'),
		_x('Pitea stadsfoers.', 'PIKO', 'ry-wc-city-select'),
	],
	'RAKO' => [
		_x('Borgvattnet', 'RAKO', 'ry-wc-city-select'),
		_x('Fors', 'RAKO', 'ry-wc-city-select'),
		_x('Ragunda', 'RAKO', 'ry-wc-city-select'),
		_x('Stugun', 'RAKO', 'ry-wc-city-select'),
	],
	'RAKO2' => [
		_x('Boda', 'RAKO2', 'ry-wc-city-select'),
		_x('Ore', 'RAKO2', 'ry-wc-city-select'),
		_x('Raettvik', 'RAKO2', 'ry-wc-city-select'),
	],
	'ROKO' => [
		_x('Bygdea', 'ROKO', 'ry-wc-city-select'),
	],
	'ROKO2' => [
		_x('Braekne-Hoby', 'ROKO2', 'ry-wc-city-select'),
		_x('Listerby', 'ROKO2', 'ry-wc-city-select'),
		_x('Ronneby', 'ROKO2', 'ry-wc-city-select'),
	],
	'SAKO' => [
		_x('Botilsaeter', 'SAKO', 'ry-wc-city-select'),
		_x('Bro', 'SAKO', 'ry-wc-city-select'),
		_x('Eskilsaeter', 'SAKO', 'ry-wc-city-select'),
		_x('Gillberga', 'SAKO', 'ry-wc-city-select'),
		_x('Kila', 'SAKO', 'ry-wc-city-select'),
		_x('Langserud', 'SAKO', 'ry-wc-city-select'),
		_x('Millesvik', 'SAKO', 'ry-wc-city-select'),
		_x('Ny-Huggenaes', 'SAKO', 'ry-wc-city-select'),
		_x('OElserud', 'SAKO', 'ry-wc-city-select'),
		_x('Saeffle', 'SAKO', 'ry-wc-city-select'),
		_x('Svanskog', 'SAKO', 'ry-wc-city-select'),
		_x('Tveta', 'SAKO', 'ry-wc-city-select'),
	],
	'SAKO2' => [
		_x('Kila', 'SAKO2', 'ry-wc-city-select'),
		_x('Kumla', 'SAKO2', 'ry-wc-city-select'),
		_x('Moeklinta', 'SAKO2', 'ry-wc-city-select'),
		_x('Norrby', 'SAKO2', 'ry-wc-city-select'),
		_x('Sala', 'SAKO2', 'ry-wc-city-select'),
		_x('Taerna', 'SAKO2', 'ry-wc-city-select'),
		_x('Vaesterfaernebo-Flaeckebo', 'SAKO2', 'ry-wc-city-select'),
	],
	'SAKO3' => [
		_x('Salem', 'SAKO3', 'ry-wc-city-select'),
	],
	'SAKO4' => [
		_x('Arsunda', 'SAKO4', 'ry-wc-city-select'),
		_x('Jaerbo', 'SAKO4', 'ry-wc-city-select'),
		_x('OEsterfaernebo', 'SAKO4', 'ry-wc-city-select'),
		_x('Ovansjoe', 'SAKO4', 'ry-wc-city-select'),
		_x('Sandviken', 'SAKO4', 'ry-wc-city-select'),
	],
	'SAKO5' => [
		_x('Gustafs', 'SAKO5', 'ry-wc-city-select'),
		_x('Saeter', 'SAKO5', 'ry-wc-city-select'),
		_x('Silvberg', 'SAKO5', 'ry-wc-city-select'),
		_x('Stora Skedvi', 'SAKO5', 'ry-wc-city-select'),
	],
	'SAKO6' => [
		_x('Hjaelmseryd', 'SAKO6', 'ry-wc-city-select'),
		_x('Hjaertlanda', 'SAKO6', 'ry-wc-city-select'),
		_x('Hultsjoe', 'SAKO6', 'ry-wc-city-select'),
		_x('Saevsjoe', 'SAKO6', 'ry-wc-city-select'),
		_x('Skepperstad', 'SAKO6', 'ry-wc-city-select'),
		_x('Stockaryd', 'SAKO6', 'ry-wc-city-select'),
		_x('Vrigstad-Hylletofta', 'SAKO6', 'ry-wc-city-select'),
	],
	'SIKO' => [
		_x('Husby-AErlinghundra', 'SIKO', 'ry-wc-city-select'),
		_x('Norrsunda', 'SIKO', 'ry-wc-city-select'),
		_x('Sigtuna', 'SIKO', 'ry-wc-city-select'),
		_x('Skepptuna', 'SIKO', 'ry-wc-city-select'),
		_x('Valsta', 'SIKO', 'ry-wc-city-select'),
	],
	'SIKO2' => [
		_x('Borrby-OEstra Hoby', 'SIKO2', 'ry-wc-city-select'),
		_x('Hammenhoeg', 'SIKO2', 'ry-wc-city-select'),
		_x('Kivik', 'SIKO2', 'ry-wc-city-select'),
		_x('Roerum', 'SIKO2', 'ry-wc-city-select'),
		_x('S:t Olof', 'SIKO2', 'ry-wc-city-select'),
		_x('Simrishamn', 'SIKO2', 'ry-wc-city-select'),
		_x('Stiby', 'SIKO2', 'ry-wc-city-select'),
	],
	'SJKO' => [
		_x('Blentarp', 'SJKO', 'ry-wc-city-select'),
		_x('Fraenninge-Vollsjoe', 'SJKO', 'ry-wc-city-select'),
		_x('Loevestad', 'SJKO', 'ry-wc-city-select'),
		_x('OEstra Kaerrstorp', 'SJKO', 'ry-wc-city-select'),
		_x('Roeddinge', 'SJKO', 'ry-wc-city-select'),
		_x('Sjoebo', 'SJKO', 'ry-wc-city-select'),
		_x('Tolanga', 'SJKO', 'ry-wc-city-select'),
		_x('Vanstad', 'SJKO', 'ry-wc-city-select'),
	],
	'SKKO' => [
		_x('Ardala', 'SKKO', 'ry-wc-city-select'),
		_x('Eggby-OEglunda', 'SKKO', 'ry-wc-city-select'),
		_x('Norra Ving', 'SKKO', 'ry-wc-city-select'),
		_x('Skaerv', 'SKKO', 'ry-wc-city-select'),
		_x('Skara domkyrkofoers.', 'SKKO', 'ry-wc-city-select'),
		_x('Varnhem', 'SKKO', 'ry-wc-city-select'),
	],
	'SKKO2' => [
		_x('Burea', 'SKKO2', 'ry-wc-city-select'),
		_x('Burtraesk', 'SKKO2', 'ry-wc-city-select'),
		_x('Byske-Faellfors', 'SKKO2', 'ry-wc-city-select'),
		_x('Joern-Boliden', 'SKKO2', 'ry-wc-city-select'),
		_x('Kagedalen', 'SKKO2', 'ry-wc-city-select'),
		_x('Loevanger', 'SKKO2', 'ry-wc-city-select'),
		_x('Skelleftea S:t OErjan', 'SKKO2', 'ry-wc-city-select'),
		_x('Skelleftea S:t Olov', 'SKKO2', 'ry-wc-city-select'),
		_x('Skelleftea landsfoers.', 'SKKO2', 'ry-wc-city-select'),
	],
	'SKKO3' => [
		_x('Skinnskatteberg med Hed och Gunnilbo', 'SKKO3', 'ry-wc-city-select'),
	],
	'SKKO4' => [
		_x('Berg', 'SKKO4', 'ry-wc-city-select'),
		_x('Froesve', 'SKKO4', 'ry-wc-city-select'),
		_x('Goetlunda', 'SKKO4', 'ry-wc-city-select'),
		_x('Haeggum', 'SKKO4', 'ry-wc-city-select'),
		_x('Norra Kyrketorp', 'SKKO4', 'ry-wc-city-select'),
		_x('Ryd', 'SKKO4', 'ry-wc-city-select'),
		_x('Sjogerstad-Radene', 'SKKO4', 'ry-wc-city-select'),
		_x('Skoevde', 'SKKO4', 'ry-wc-city-select'),
		_x('Sventorp-Forsby', 'SKKO4', 'ry-wc-city-select'),
		_x('Vaering', 'SKKO4', 'ry-wc-city-select'),
		_x('Vaersas', 'SKKO4', 'ry-wc-city-select'),
		_x('Vamb', 'SKKO4', 'ry-wc-city-select'),
		_x('Varola', 'SKKO4', 'ry-wc-city-select'),
		_x('Vreten', 'SKKO4', 'ry-wc-city-select'),
	],
	'SKKO5' => [
		_x('Skivarp', 'SKKO5', 'ry-wc-city-select'),
		_x('Skurup', 'SKKO5', 'ry-wc-city-select'),
		_x('Villie', 'SKKO5', 'ry-wc-city-select'),
	],
	'SMKO' => [
		_x('Norrbaerke', 'SMKO', 'ry-wc-city-select'),
		_x('Soederbaerke', 'SMKO', 'ry-wc-city-select'),
	],
	'SOKO' => [
		_x('Ljusne', 'SOKO', 'ry-wc-city-select'),
		_x('Mo-Bergvik', 'SOKO', 'ry-wc-city-select'),
		_x('Norrala', 'SOKO', 'ry-wc-city-select'),
		_x('Sandarne', 'SOKO', 'ry-wc-city-select'),
		_x('Skog', 'SOKO', 'ry-wc-city-select'),
		_x('Soederala', 'SOKO', 'ry-wc-city-select'),
		_x('Soederhamn', 'SOKO', 'ry-wc-city-select'),
		_x('Troenoe', 'SOKO', 'ry-wc-city-select'),
	],
	'SOKO2' => [
		_x('Gardeby', 'SOKO2', 'ry-wc-city-select'),
		_x('OEstra Ryd', 'SOKO2', 'ry-wc-city-select'),
		_x('S:t Anna', 'SOKO2', 'ry-wc-city-select'),
		_x('Soederkoeping', 'SOKO2', 'ry-wc-city-select'),
		_x('Vaestra Husby', 'SOKO2', 'ry-wc-city-select'),
	],
	'SOKO3' => [
		_x('Enhoerna', 'SOKO3', 'ry-wc-city-select'),
		_x('Hoeloe', 'SOKO3', 'ry-wc-city-select'),
		_x('Moerkoe', 'SOKO3', 'ry-wc-city-select'),
		_x('OEstertaelje', 'SOKO3', 'ry-wc-city-select'),
		_x('OEverjaerna', 'SOKO3', 'ry-wc-city-select'),
		_x('Soedertaelje-Tveta', 'SOKO3', 'ry-wc-city-select'),
		_x('Vaestertaelje', 'SOKO3', 'ry-wc-city-select'),
		_x('Vardinge', 'SOKO3', 'ry-wc-city-select'),
		_x('Ytterjaerna', 'SOKO3', 'ry-wc-city-select'),
	],
	'SOKO4' => [
		_x('Gammalstorp-Ysane', 'SOKO4', 'ry-wc-city-select'),
		_x('Mjaellby', 'SOKO4', 'ry-wc-city-select'),
		_x('Soelvesborg', 'SOKO4', 'ry-wc-city-select'),
	],
	'SOKO5' => [
		_x('Adals-Liden', 'SOKO5', 'ry-wc-city-select'),
		_x('Botea', 'SOKO5', 'ry-wc-city-select'),
		_x('Ed', 'SOKO5', 'ry-wc-city-select'),
		_x('Graninge', 'SOKO5', 'ry-wc-city-select'),
		_x('Helgum', 'SOKO5', 'ry-wc-city-select'),
		_x('Junsele', 'SOKO5', 'ry-wc-city-select'),
		_x('Langsele', 'SOKO5', 'ry-wc-city-select'),
		_x('Multra och Sanga', 'SOKO5', 'ry-wc-city-select'),
		_x('OEverlaennaes', 'SOKO5', 'ry-wc-city-select'),
		_x('Ramsele-Edsele', 'SOKO5', 'ry-wc-city-select'),
		_x('Resele', 'SOKO5', 'ry-wc-city-select'),
		_x('Solleftea', 'SOKO5', 'ry-wc-city-select'),
	],
	'SOKO6' => [
		_x('Sollentuna', 'SOKO6', 'ry-wc-city-select'),
	],
	'SOKO7' => [
		_x('Solna', 'SOKO7', 'ry-wc-city-select'),
	],
	'SOKO8' => [
		_x('Sorsele', 'SOKO8', 'ry-wc-city-select'),
	],
	'SOKO9' => [
		_x('Askum', 'SOKO9', 'ry-wc-city-select'),
		_x('Hunnebostrand', 'SOKO9', 'ry-wc-city-select'),
		_x('Kungshamn', 'SOKO9', 'ry-wc-city-select'),
		_x('Malmoen', 'SOKO9', 'ry-wc-city-select'),
		_x('Smoegen', 'SOKO9', 'ry-wc-city-select'),
		_x('Tossene', 'SOKO9', 'ry-wc-city-select'),
	],
	'STKO' => [
		_x('S:t Staffan', 'STKO', 'ry-wc-city-select'),
		_x('Uppakra', 'STKO', 'ry-wc-city-select'),
	],
	'STKO2' => [
		_x('Joerlanda', 'STKO2', 'ry-wc-city-select'),
		_x('Norum', 'STKO2', 'ry-wc-city-select'),
		_x('OEdsmal', 'STKO2', 'ry-wc-city-select'),
		_x('Spekeroed', 'STKO2', 'ry-wc-city-select'),
		_x('Ucklum', 'STKO2', 'ry-wc-city-select'),
	],
	'STKO3' => [
		_x('Adolf Fredrik', 'STKO3', 'ry-wc-city-select'),
		_x('Braennkyrka', 'STKO3', 'ry-wc-city-select'),
		_x('Bromma', 'STKO3', 'ry-wc-city-select'),
		_x('Engelbrekt', 'STKO3', 'ry-wc-city-select'),
		_x('Enskede-Arsta', 'STKO3', 'ry-wc-city-select'),
		_x('Essinge', 'STKO3', 'ry-wc-city-select'),
		_x('Farsta', 'STKO3', 'ry-wc-city-select'),
		_x('Gustav Vasa', 'STKO3', 'ry-wc-city-select'),
		_x('Haegersten', 'STKO3', 'ry-wc-city-select'),
		_x('Haesselby', 'STKO3', 'ry-wc-city-select'),
		_x('Hedvig Eleonora', 'STKO3', 'ry-wc-city-select'),
		_x('Hoegalid', 'STKO3', 'ry-wc-city-select'),
		_x('Katarina', 'STKO3', 'ry-wc-city-select'),
		_x('Kista', 'STKO3', 'ry-wc-city-select'),
		_x('Kungsholm', 'STKO3', 'ry-wc-city-select'),
		_x('Maria Magdalena', 'STKO3', 'ry-wc-city-select'),
		_x('Oscar', 'STKO3', 'ry-wc-city-select'),
		_x('S:t Goeran', 'STKO3', 'ry-wc-city-select'),
		_x('S:t Johannes', 'STKO3', 'ry-wc-city-select'),
		_x('S:t Matteus', 'STKO3', 'ry-wc-city-select'),
		_x('Skaerholmen', 'STKO3', 'ry-wc-city-select'),
		_x('Skarpnaeck', 'STKO3', 'ry-wc-city-select'),
		_x('Sofia', 'STKO3', 'ry-wc-city-select'),
		_x('Spanga', 'STKO3', 'ry-wc-city-select'),
		_x('Stockholms domkyrkofoers.', 'STKO3', 'ry-wc-city-select'),
		_x('Vaellingby', 'STKO3', 'ry-wc-city-select'),
		_x('Vaesterled', 'STKO3', 'ry-wc-city-select'),
		_x('Vantoer', 'STKO3', 'ry-wc-city-select'),
	],
	'STKO4' => [
		_x('Bjurtjaern', 'STKO4', 'ry-wc-city-select'),
		_x('Lungsund', 'STKO4', 'ry-wc-city-select'),
		_x('Storfors', 'STKO4', 'ry-wc-city-select'),
	],
	'STKO5' => [
		_x('Stensele', 'STKO5', 'ry-wc-city-select'),
		_x('Taerna', 'STKO5', 'ry-wc-city-select'),
	],
	'STKO6' => [
		_x('Aker-Laenna', 'STKO6', 'ry-wc-city-select'),
		_x('Mariefred', 'STKO6', 'ry-wc-city-select'),
		_x('Stallarholmen', 'STKO6', 'ry-wc-city-select'),
		_x('Straengnaes domkyrkofoers. med Aspoe', 'STKO6', 'ry-wc-city-select'),
		_x('Varfruberga-Haerad', 'STKO6', 'ry-wc-city-select'),
	],
	'STKO7' => [
		_x('Alanaes', 'STKO7', 'ry-wc-city-select'),
		_x('Bodum', 'STKO7', 'ry-wc-city-select'),
		_x('Fjaellsjoe', 'STKO7', 'ry-wc-city-select'),
		_x('Frostviken', 'STKO7', 'ry-wc-city-select'),
		_x('Gaxsjoe', 'STKO7', 'ry-wc-city-select'),
		_x('Hammerdal', 'STKO7', 'ry-wc-city-select'),
		_x('Stroem', 'STKO7', 'ry-wc-city-select'),
		_x('Tasjoe', 'STKO7', 'ry-wc-city-select'),
	],
	'STKO8' => [
		_x('Idefjorden', 'STKO8', 'ry-wc-city-select'),
		_x('Skee-Tjaernoe', 'STKO8', 'ry-wc-city-select'),
		_x('Stroemstad', 'STKO8', 'ry-wc-city-select'),
	],
	'SUKO' => [
		_x('Sundbyberg', 'SUKO', 'ry-wc-city-select'),
	],
	'SUKO2' => [
		_x('Alnoe', 'SUKO2', 'ry-wc-city-select'),
		_x('Attmar', 'SUKO2', 'ry-wc-city-select'),
		_x('Holm', 'SUKO2', 'ry-wc-city-select'),
		_x('Indal', 'SUKO2', 'ry-wc-city-select'),
		_x('Liden', 'SUKO2', 'ry-wc-city-select'),
		_x('Njurunda', 'SUKO2', 'ry-wc-city-select'),
		_x('Saettna', 'SUKO2', 'ry-wc-city-select'),
		_x('Selanger', 'SUKO2', 'ry-wc-city-select'),
		_x('Skoen', 'SUKO2', 'ry-wc-city-select'),
		_x('Skoensmon', 'SUKO2', 'ry-wc-city-select'),
		_x('Stoede', 'SUKO2', 'ry-wc-city-select'),
		_x('Sundsvalls Gustav Adolf', 'SUKO2', 'ry-wc-city-select'),
		_x('Tuna', 'SUKO2', 'ry-wc-city-select'),
	],
	'SUKO3' => [
		_x('Graesmark', 'SUKO3', 'ry-wc-city-select'),
		_x('Lysvik', 'SUKO3', 'ry-wc-city-select'),
		_x('OEstra AEmtervik', 'SUKO3', 'ry-wc-city-select'),
		_x('Sunne', 'SUKO3', 'ry-wc-city-select'),
		_x('Vaestra AEmtervik', 'SUKO3', 'ry-wc-city-select'),
	],
	'SUKO4' => [
		_x('Ramnaes', 'SUKO4', 'ry-wc-city-select'),
		_x('Sura', 'SUKO4', 'ry-wc-city-select'),
	],
	'SVKO' => [
		_x('Billeberga-Sirekoepinge', 'SVKO', 'ry-wc-city-select'),
		_x('Kageroed-Roestanga', 'SVKO', 'ry-wc-city-select'),
		_x('Svaloevsbygden', 'SVKO', 'ry-wc-city-select'),
		_x('Teckomatorp', 'SVKO', 'ry-wc-city-select'),
	],
	'SVKO2' => [
		_x('Svedala', 'SVKO2', 'ry-wc-city-select'),
		_x('Vaerby', 'SVKO2', 'ry-wc-city-select'),
	],
	'SVKO3' => [
		_x('Holsljunga', 'SVKO3', 'ry-wc-city-select'),
		_x('Kindaholm', 'SVKO3', 'ry-wc-city-select'),
		_x('Mjoebaeck', 'SVKO3', 'ry-wc-city-select'),
		_x('Sexdrega, del', 'SVKO3', 'ry-wc-city-select'),
		_x('Svenljungabygden', 'SVKO3', 'ry-wc-city-select'),
	],
	'TAKO' => [
		_x('Taeby', 'TAKO', 'ry-wc-city-select'),
	],
	'TAKO2' => [
		_x('Bottna', 'TAKO2', 'ry-wc-city-select'),
		_x('Fjaellbacka', 'TAKO2', 'ry-wc-city-select'),
		_x('Kville', 'TAKO2', 'ry-wc-city-select'),
		_x('Lur', 'TAKO2', 'ry-wc-city-select'),
		_x('Naverstad-Mo', 'TAKO2', 'ry-wc-city-select'),
		_x('Svenneby', 'TAKO2', 'ry-wc-city-select'),
		_x('Tanum', 'TAKO2', 'ry-wc-city-select'),
	],
	'TIKO' => [
		_x('Ransberg', 'TIKO', 'ry-wc-city-select'),
		_x('Tibro', 'TIKO', 'ry-wc-city-select'),
	],
	'TIKO2' => [
		_x('Acklinga', 'TIKO2', 'ry-wc-city-select'),
		_x('Baltak', 'TIKO2', 'ry-wc-city-select'),
		_x('Daretorp', 'TIKO2', 'ry-wc-city-select'),
		_x('Dimbo-Ottravad', 'TIKO2', 'ry-wc-city-select'),
		_x('Froejered', 'TIKO2', 'ry-wc-city-select'),
		_x('Haerja', 'TIKO2', 'ry-wc-city-select'),
		_x('Kungslena-Hoemb', 'TIKO2', 'ry-wc-city-select'),
		_x('Tidaholm', 'TIKO2', 'ry-wc-city-select'),
		_x('Valstad', 'TIKO2', 'ry-wc-city-select'),
		_x('Varv', 'TIKO2', 'ry-wc-city-select'),
		_x('Velinga', 'TIKO2', 'ry-wc-city-select'),
	],
	'TIKO3' => [
		_x('Hallnaes-OEsterloevsta', 'TIKO3', 'ry-wc-city-select'),
		_x('Tegelsmora', 'TIKO3', 'ry-wc-city-select'),
		_x('Tierp-Soederfors', 'TIKO3', 'ry-wc-city-select'),
		_x('Tolfta', 'TIKO3', 'ry-wc-city-select'),
		_x('Vaestland', 'TIKO3', 'ry-wc-city-select'),
		_x('Vendel', 'TIKO3', 'ry-wc-city-select'),
	],
	'TIKO4' => [
		_x('Haessjoe', 'TIKO4', 'ry-wc-city-select'),
		_x('Ljustorp', 'TIKO4', 'ry-wc-city-select'),
		_x('Timra', 'TIKO4', 'ry-wc-city-select'),
		_x('Tynderoe', 'TIKO4', 'ry-wc-city-select'),
	],
	'TIKO5' => [
		_x('AElmeboda', 'TIKO5', 'ry-wc-city-select'),
		_x('Almundsryd', 'TIKO5', 'ry-wc-city-select'),
		_x('Linneryd', 'TIKO5', 'ry-wc-city-select'),
		_x('Soedra Sandsjoe', 'TIKO5', 'ry-wc-city-select'),
		_x('Tingsas', 'TIKO5', 'ry-wc-city-select'),
		_x('Urshult', 'TIKO5', 'ry-wc-city-select'),
		_x('Vaeckelsang', 'TIKO5', 'ry-wc-city-select'),
	],
	'TJKO' => [
		_x('Klaedesholmen', 'TJKO', 'ry-wc-city-select'),
		_x('Kloevedal', 'TJKO', 'ry-wc-city-select'),
		_x('Roennaeng', 'TJKO', 'ry-wc-city-select'),
		_x('Stenkyrka', 'TJKO', 'ry-wc-city-select'),
		_x('Valla', 'TJKO', 'ry-wc-city-select'),
	],
	'TOKO' => [
		_x('Broesarp-Tranas', 'TOKO', 'ry-wc-city-select'),
		_x('Smedstorp', 'TOKO', 'ry-wc-city-select'),
		_x('Tomelillabygden', 'TOKO', 'ry-wc-city-select'),
	],
	'TOKO2' => [
		_x('Baeck', 'TOKO2', 'ry-wc-city-select'),
		_x('Faegre', 'TOKO2', 'ry-wc-city-select'),
		_x('Fredsberg', 'TOKO2', 'ry-wc-city-select'),
		_x('Hova-AElgaras, del', 'TOKO2', 'ry-wc-city-select'),
		_x('Toereboda', 'TOKO2', 'ry-wc-city-select'),
	],
	'TOKO3' => [
		_x('Gullabo', 'TOKO3', 'ry-wc-city-select'),
		_x('Soederakra', 'TOKO3', 'ry-wc-city-select'),
		_x('Torsas', 'TOKO3', 'ry-wc-city-select'),
	],
	'TOKO4' => [
		_x('Dalby', 'TOKO4', 'ry-wc-city-select'),
		_x('Fryksaende', 'TOKO4', 'ry-wc-city-select'),
		_x('Lekvattnet', 'TOKO4', 'ry-wc-city-select'),
		_x('Norra Finnskoga', 'TOKO4', 'ry-wc-city-select'),
		_x('Norra Ny-Nyskoga', 'TOKO4', 'ry-wc-city-select'),
		_x('OEstmark', 'TOKO4', 'ry-wc-city-select'),
		_x('Soedra Finnskoga', 'TOKO4', 'ry-wc-city-select'),
		_x('Vitsand', 'TOKO4', 'ry-wc-city-select'),
	],
	'TRKO' => [
		_x('Adeloev', 'TRKO', 'ry-wc-city-select'),
		_x('Linderas', 'TRKO', 'ry-wc-city-select'),
		_x('Saeby', 'TRKO', 'ry-wc-city-select'),
	],
	'TRKO2' => [
		_x('Ambjoernarp', 'TRKO2', 'ry-wc-city-select'),
		_x('Dalstorp', 'TRKO2', 'ry-wc-city-select'),
		_x('Hulared', 'TRKO2', 'ry-wc-city-select'),
		_x('Laenghem', 'TRKO2', 'ry-wc-city-select'),
		_x('Ljungsarp', 'TRKO2', 'ry-wc-city-select'),
		_x('Manstad', 'TRKO2', 'ry-wc-city-select'),
		_x('Mossebo', 'TRKO2', 'ry-wc-city-select'),
		_x('Nittorp', 'TRKO2', 'ry-wc-city-select'),
		_x('OElsremma', 'TRKO2', 'ry-wc-city-select'),
		_x('Sjoetofta', 'TRKO2', 'ry-wc-city-select'),
		_x('Soedra Asarp', 'TRKO2', 'ry-wc-city-select'),
		_x('Tranemo', 'TRKO2', 'ry-wc-city-select'),
	],
	'TRKO3' => [
		_x('Alstad', 'TRKO3', 'ry-wc-city-select'),
		_x('Andersloev', 'TRKO3', 'ry-wc-city-select'),
		_x('Dalkoepinge', 'TRKO3', 'ry-wc-city-select'),
		_x('Hammarloev', 'TRKO3', 'ry-wc-city-select'),
		_x('Kaellstorp', 'TRKO3', 'ry-wc-city-select'),
		_x('Trelleborg', 'TRKO3', 'ry-wc-city-select'),
	],
	'TR' => [
		_x('Asaka-Bjoerke', 'TR', 'ry-wc-city-select'),
		_x('Bjaerke, del', 'TR', 'ry-wc-city-select'),
		_x('Fors-Rommele', 'TR', 'ry-wc-city-select'),
		_x('Gaerdhem', 'TR', 'ry-wc-city-select'),
		_x('Goetalunden', 'TR', 'ry-wc-city-select'),
		_x('Lextorp', 'TR', 'ry-wc-city-select'),
		_x('Trollhaettan', 'TR', 'ry-wc-city-select'),
		_x('Upphaerad', 'TR', 'ry-wc-city-select'),
	],
	'TRKO4' => [
		_x('Trosa stadsfoers.', 'TRKO4', 'ry-wc-city-select'),
		_x('Trosa-Vagnhaerad', 'TRKO4', 'ry-wc-city-select'),
		_x('Vaesterljung', 'TRKO4', 'ry-wc-city-select'),
	],
	'TYKO' => [
		_x('Tyresoe', 'TYKO', 'ry-wc-city-select'),
	],
	'UDKO' => [
		_x('Baeve', 'UDKO', 'ry-wc-city-select'),
		_x('Bokenaes', 'UDKO', 'ry-wc-city-select'),
		_x('Dragsmark', 'UDKO', 'ry-wc-city-select'),
		_x('Forshaella', 'UDKO', 'ry-wc-city-select'),
		_x('Grinneroed', 'UDKO', 'ry-wc-city-select'),
		_x('Herrestad', 'UDKO', 'ry-wc-city-select'),
		_x('Hoegas', 'UDKO', 'ry-wc-city-select'),
		_x('Lane-Ryr', 'UDKO', 'ry-wc-city-select'),
		_x('Ljung', 'UDKO', 'ry-wc-city-select'),
		_x('Resteroed', 'UDKO', 'ry-wc-city-select'),
		_x('Skredsvik', 'UDKO', 'ry-wc-city-select'),
		_x('Uddevalla', 'UDKO', 'ry-wc-city-select'),
	],
	'ULKO' => [
		_x('Asunden', 'ULKO', 'ry-wc-city-select'),
		_x('Haellstad', 'ULKO', 'ry-wc-city-select'),
		_x('Hoessna', 'ULKO', 'ry-wc-city-select'),
		_x('Redvaeg', 'ULKO', 'ry-wc-city-select'),
		_x('Soedra Ving', 'ULKO', 'ry-wc-city-select'),
		_x('Timmele', 'ULKO', 'ry-wc-city-select'),
		_x('Ulricehamn', 'ULKO', 'ry-wc-city-select'),
	],
	'UMKO' => [
		_x('Alidhem', 'UMKO', 'ry-wc-city-select'),
		_x('Hoernefors', 'UMKO', 'ry-wc-city-select'),
		_x('Holmsund', 'UMKO', 'ry-wc-city-select'),
		_x('Saevar-Holmoen', 'UMKO', 'ry-wc-city-select'),
		_x('Tavelsjoe', 'UMKO', 'ry-wc-city-select'),
		_x('Teg', 'UMKO', 'ry-wc-city-select'),
		_x('Umea Maria', 'UMKO', 'ry-wc-city-select'),
		_x('Umea landsfoers.', 'UMKO', 'ry-wc-city-select'),
		_x('Umea stadsfoers.', 'UMKO', 'ry-wc-city-select'),
	],
	'UPVAKO' => [
		_x('Ed', 'UPVAKO', 'ry-wc-city-select'),
		_x('Fresta', 'UPVAKO', 'ry-wc-city-select'),
		_x('Hammarby', 'UPVAKO', 'ry-wc-city-select'),
	],
	'UPKO' => [
		_x('Bro', 'UPKO', 'ry-wc-city-select'),
		_x('Hatuna', 'UPKO', 'ry-wc-city-select'),
		_x('Kungsaengen-Vaestra Ryd', 'UPKO', 'ry-wc-city-select'),
	],
	'UPKO2' => [
		_x('AErentuna', 'UPKO2', 'ry-wc-city-select'),
		_x('Akerby', 'UPKO2', 'ry-wc-city-select'),
		_x('Almunge', 'UPKO2', 'ry-wc-city-select'),
		_x('Baelinge', 'UPKO2', 'ry-wc-city-select'),
		_x('Balingsta', 'UPKO2', 'ry-wc-city-select'),
		_x('Bjoerklinge', 'UPKO2', 'ry-wc-city-select'),
		_x('Bladaker', 'UPKO2', 'ry-wc-city-select'),
		_x('Boerje', 'UPKO2', 'ry-wc-city-select'),
		_x('Dalby', 'UPKO2', 'ry-wc-city-select'),
		_x('Danmark', 'UPKO2', 'ry-wc-city-select'),
		_x('Faringe', 'UPKO2', 'ry-wc-city-select'),
		_x('Funbo', 'UPKO2', 'ry-wc-city-select'),
		_x('Gamla Uppsala', 'UPKO2', 'ry-wc-city-select'),
		_x('Gottsunda', 'UPKO2', 'ry-wc-city-select'),
		_x('Hagby', 'UPKO2', 'ry-wc-city-select'),
		_x('Helga Trefaldighet', 'UPKO2', 'ry-wc-city-select'),
		_x('Jumkil', 'UPKO2', 'ry-wc-city-select'),
		_x('Knutby', 'UPKO2', 'ry-wc-city-select'),
		_x('Lena', 'UPKO2', 'ry-wc-city-select'),
		_x('Norra Hagunda', 'UPKO2', 'ry-wc-city-select'),
		_x('Ramsta', 'UPKO2', 'ry-wc-city-select'),
		_x('Rasbo', 'UPKO2', 'ry-wc-city-select'),
		_x('Rasbokil', 'UPKO2', 'ry-wc-city-select'),
		_x('Skuttunge', 'UPKO2', 'ry-wc-city-select'),
		_x('Stavby', 'UPKO2', 'ry-wc-city-select'),
		_x('Tensta', 'UPKO2', 'ry-wc-city-select'),
		_x('Tuna', 'UPKO2', 'ry-wc-city-select'),
		_x('Uppsala domkyrkofoers.', 'UPKO2', 'ry-wc-city-select'),
		_x('Uppsala-Naes', 'UPKO2', 'ry-wc-city-select'),
		_x('Vaesteraker', 'UPKO2', 'ry-wc-city-select'),
		_x('Vaksala', 'UPKO2', 'ry-wc-city-select'),
		_x('Viksta', 'UPKO2', 'ry-wc-city-select'),
	],
	'UPKO3' => [
		_x('AElghult', 'UPKO3', 'ry-wc-city-select'),
		_x('Aseda', 'UPKO3', 'ry-wc-city-select'),
		_x('Herrakra', 'UPKO3', 'ry-wc-city-select'),
		_x('Lenhovda', 'UPKO3', 'ry-wc-city-select'),
		_x('Nottebaeck', 'UPKO3', 'ry-wc-city-select'),
	],
	'VAKO' => [
		_x('Aska, del', 'VAKO', 'ry-wc-city-select'),
		_x('Dal', 'VAKO', 'ry-wc-city-select'),
		_x('Vadstena', 'VAKO', 'ry-wc-city-select'),
	],
	'VAKO2' => [
		_x('Aker', 'VAKO2', 'ry-wc-city-select'),
		_x('Bondstorp', 'VAKO2', 'ry-wc-city-select'),
		_x('Byarum', 'VAKO2', 'ry-wc-city-select'),
		_x('Hagshult', 'VAKO2', 'ry-wc-city-select'),
		_x('Svenarum', 'VAKO2', 'ry-wc-city-select'),
		_x('Tofteryd', 'VAKO2', 'ry-wc-city-select'),
	],
	'VAKO3' => [
		_x('Gryt', 'VAKO3', 'ry-wc-city-select'),
		_x('OEstra Ed', 'VAKO3', 'ry-wc-city-select'),
		_x('Ringarum', 'VAKO3', 'ry-wc-city-select'),
		_x('Tryserum', 'VAKO3', 'ry-wc-city-select'),
		_x('Valdemarsvik', 'VAKO3', 'ry-wc-city-select'),
	],
	'VAKO4' => [
		_x('OEsseby', 'VAKO4', 'ry-wc-city-select'),
		_x('Vallentuna', 'VAKO4', 'ry-wc-city-select'),
	],
	'VAKO5' => [
		_x('Bralanda', 'VAKO5', 'ry-wc-city-select'),
		_x('Fraendefors', 'VAKO5', 'ry-wc-city-select'),
		_x('Gestad', 'VAKO5', 'ry-wc-city-select'),
		_x('Sundals-Ryr', 'VAKO5', 'ry-wc-city-select'),
		_x('Vaene-Ryr', 'VAKO5', 'ry-wc-city-select'),
		_x('Vaenersborg', 'VAKO5', 'ry-wc-city-select'),
		_x('Vaenersnaes', 'VAKO5', 'ry-wc-city-select'),
		_x('Vaestra Tunhem', 'VAKO5', 'ry-wc-city-select'),
	],
	'VAKO6' => [
		_x('Vaennaes', 'VAKO6', 'ry-wc-city-select'),
	],
	'VAKO7' => [
		_x('AEppelbo', 'VAKO7', 'ry-wc-city-select'),
		_x('Jaerna', 'VAKO7', 'ry-wc-city-select'),
		_x('Nas', 'VAKO7', 'ry-wc-city-select'),
	],
	'VAKO8' => [
		_x('Kvaenum', 'VAKO8', 'ry-wc-city-select'),
		_x('Larv', 'VAKO8', 'ry-wc-city-select'),
		_x('Levene', 'VAKO8', 'ry-wc-city-select'),
		_x('Ryda', 'VAKO8', 'ry-wc-city-select'),
		_x('Vara', 'VAKO8', 'ry-wc-city-select'),
		_x('Vedum', 'VAKO8', 'ry-wc-city-select'),
	],
	'VAKO9' => [
		_x('Himledalen', 'VAKO9', 'ry-wc-city-select'),
		_x('Kungsaeter', 'VAKO9', 'ry-wc-city-select'),
		_x('Lindberg', 'VAKO9', 'ry-wc-city-select'),
		_x('Sibbarp-Dagsas', 'VAKO9', 'ry-wc-city-select'),
		_x('Spannarp', 'VAKO9', 'ry-wc-city-select'),
		_x('Stamnared', 'VAKO9', 'ry-wc-city-select'),
		_x('Stravalla', 'VAKO9', 'ry-wc-city-select'),
		_x('Torpa', 'VAKO9', 'ry-wc-city-select'),
		_x('Traesloev', 'VAKO9', 'ry-wc-city-select'),
		_x('Tvaaker', 'VAKO9', 'ry-wc-city-select'),
		_x('Vaeroe', 'VAKO9', 'ry-wc-city-select'),
		_x('Valinge', 'VAKO9', 'ry-wc-city-select'),
		_x('Varberg', 'VAKO9', 'ry-wc-city-select'),
		_x('Veddige', 'VAKO9', 'ry-wc-city-select'),
	],
	'VAKO10' => [
		_x('Algutstorp', 'VAKO10', 'ry-wc-city-select'),
		_x('Asklanda', 'VAKO10', 'ry-wc-city-select'),
		_x('Hol', 'VAKO10', 'ry-wc-city-select'),
		_x('Lena', 'VAKO10', 'ry-wc-city-select'),
		_x('Narunga', 'VAKO10', 'ry-wc-city-select'),
	],
	'VAKO11' => [
		_x('Djuroe, Moeja och Naemdoe', 'VAKO11', 'ry-wc-city-select'),
		_x('Gustavsberg', 'VAKO11', 'ry-wc-city-select'),
		_x('Ingaroe', 'VAKO11', 'ry-wc-city-select'),
		_x('Vaermdoe', 'VAKO11', 'ry-wc-city-select'),
	],
	'VAKO12' => [
		_x('Bredaryd', 'VAKO12', 'ry-wc-city-select'),
		_x('Dannaes', 'VAKO12', 'ry-wc-city-select'),
		_x('Forsheda', 'VAKO12', 'ry-wc-city-select'),
		_x('Fryele', 'VAKO12', 'ry-wc-city-select'),
		_x('Gaellaryd', 'VAKO12', 'ry-wc-city-select'),
		_x('Hanger', 'VAKO12', 'ry-wc-city-select'),
		_x('Kaerda', 'VAKO12', 'ry-wc-city-select'),
		_x('Kulltorp, del', 'VAKO12', 'ry-wc-city-select'),
		_x('Nydala', 'VAKO12', 'ry-wc-city-select'),
		_x('Rydaholm', 'VAKO12', 'ry-wc-city-select'),
		_x('Tannoe', 'VAKO12', 'ry-wc-city-select'),
		_x('Torskinge', 'VAKO12', 'ry-wc-city-select'),
		_x('Vaernamo', 'VAKO12', 'ry-wc-city-select'),
		_x('Voxtorp', 'VAKO12', 'ry-wc-city-select'),
	],
	'VA' => [
		_x('Dingtuna-Lillhaerad', 'VA', 'ry-wc-city-select'),
		_x('Kungsara', 'VA', 'ry-wc-city-select'),
		_x('Norrbo', 'VA', 'ry-wc-city-select'),
		_x('OEnsta', 'VA', 'ry-wc-city-select'),
		_x('Rytterne', 'VA', 'ry-wc-city-select'),
		_x('Skerike-Gideonsberg', 'VA', 'ry-wc-city-select'),
		_x('Tillberga', 'VA', 'ry-wc-city-select'),
		_x('Vaesteras Badelunda', 'VA', 'ry-wc-city-select'),
		_x('Vaesteras Lundby', 'VA', 'ry-wc-city-select'),
		_x('Vaesteras domkyrkofoers.', 'VA', 'ry-wc-city-select'),
		_x('Vaesteras-Barkaroe', 'VA', 'ry-wc-city-select'),
	],
	'VAKO13' => [
		_x('Blackstad', 'VAKO13', 'ry-wc-city-select'),
		_x('Dalhem', 'VAKO13', 'ry-wc-city-select'),
		_x('Gamleby', 'VAKO13', 'ry-wc-city-select'),
		_x('Gladhammar-Vaestrum', 'VAKO13', 'ry-wc-city-select'),
		_x('Hallingeberg', 'VAKO13', 'ry-wc-city-select'),
		_x('Hjorted', 'VAKO13', 'ry-wc-city-select'),
		_x('Lofta', 'VAKO13', 'ry-wc-city-select'),
		_x('Loftahammar', 'VAKO13', 'ry-wc-city-select'),
		_x('OEverum', 'VAKO13', 'ry-wc-city-select'),
		_x('Odensvi', 'VAKO13', 'ry-wc-city-select'),
		_x('Toernsfall', 'VAKO13', 'ry-wc-city-select'),
		_x('Ukna', 'VAKO13', 'ry-wc-city-select'),
		_x('Vaestervik', 'VAKO13', 'ry-wc-city-select'),
		_x('Vaestra Ed', 'VAKO13', 'ry-wc-city-select'),
	],
	'VAKO14' => [
		_x('Vaxholm', 'VAKO14', 'ry-wc-city-select'),
	],
	'VAKO15' => [
		_x('Aneboda', 'VAKO15', 'ry-wc-city-select'),
		_x('Asa', 'VAKO15', 'ry-wc-city-select'),
		_x('Berg', 'VAKO15', 'ry-wc-city-select'),
		_x('Bergunda', 'VAKO15', 'ry-wc-city-select'),
		_x('Daedesjoe', 'VAKO15', 'ry-wc-city-select'),
		_x('Drev-Hornaryd', 'VAKO15', 'ry-wc-city-select'),
		_x('Furuby', 'VAKO15', 'ry-wc-city-select'),
		_x('Gardsby', 'VAKO15', 'ry-wc-city-select'),
		_x('Hemmesjoe med Tegnaby', 'VAKO15', 'ry-wc-city-select'),
		_x('Jaet', 'VAKO15', 'ry-wc-city-select'),
		_x('Kalvsvik', 'VAKO15', 'ry-wc-city-select'),
		_x('Noebbele', 'VAKO15', 'ry-wc-city-select'),
		_x('OEja', 'VAKO15', 'ry-wc-city-select'),
		_x('OEjaby', 'VAKO15', 'ry-wc-city-select'),
		_x('OEr-Ormesberga', 'VAKO15', 'ry-wc-city-select'),
		_x('OEstra Torsas', 'VAKO15', 'ry-wc-city-select'),
		_x('Sjoesas', 'VAKO15', 'ry-wc-city-select'),
		_x('Skogslyckan', 'VAKO15', 'ry-wc-city-select'),
		_x('Soeraby, Tolg och Tjureda', 'VAKO15', 'ry-wc-city-select'),
		_x('Taevelsas', 'VAKO15', 'ry-wc-city-select'),
		_x('Teleborg', 'VAKO15', 'ry-wc-city-select'),
		_x('Urasa', 'VAKO15', 'ry-wc-city-select'),
		_x('Vaexjoe Maria', 'VAKO15', 'ry-wc-city-select'),
		_x('Vaexjoe domkyrkofoers.', 'VAKO15', 'ry-wc-city-select'),
		_x('Vedersloev-Daenningelanda', 'VAKO15', 'ry-wc-city-select'),
	],
	'VEKO' => [
		_x('Hoellviken', 'VEKO', 'ry-wc-city-select'),
		_x('Skanoer-Falsterbo', 'VEKO', 'ry-wc-city-select'),
		_x('Vellinge-Manstorp', 'VEKO', 'ry-wc-city-select'),
	],
	'VEKO2' => [
		_x('Alseda', 'VEKO2', 'ry-wc-city-select'),
		_x('Baeckaby', 'VEKO2', 'ry-wc-city-select'),
		_x('Baeckseda', 'VEKO2', 'ry-wc-city-select'),
		_x('Bjoerkoe', 'VEKO2', 'ry-wc-city-select'),
		_x('Froederyd', 'VEKO2', 'ry-wc-city-select'),
		_x('Karlstorp', 'VEKO2', 'ry-wc-city-select'),
		_x('Korsberga', 'VEKO2', 'ry-wc-city-select'),
		_x('Lannaskede', 'VEKO2', 'ry-wc-city-select'),
		_x('Myresjoe', 'VEKO2', 'ry-wc-city-select'),
		_x('Naesby', 'VEKO2', 'ry-wc-city-select'),
		_x('Naevelsjoe', 'VEKO2', 'ry-wc-city-select'),
		_x('Nye, Naeshult och Stenberga', 'VEKO2', 'ry-wc-city-select'),
		_x('OEkna', 'VEKO2', 'ry-wc-city-select'),
		_x('Ramkvilla', 'VEKO2', 'ry-wc-city-select'),
		_x('Skede', 'VEKO2', 'ry-wc-city-select'),
		_x('Skiroe', 'VEKO2', 'ry-wc-city-select'),
		_x('Vetlanda', 'VEKO2', 'ry-wc-city-select'),
	],
	'VIKO' => [
		_x('Vilhelmina', 'VIKO', 'ry-wc-city-select'),
	],
	'VIKO2' => [
		_x('Froedinge', 'VIKO2', 'ry-wc-city-select'),
		_x('Locknevi', 'VIKO2', 'ry-wc-city-select'),
		_x('Pelarne', 'VIKO2', 'ry-wc-city-select'),
		_x('Rumskulla', 'VIKO2', 'ry-wc-city-select'),
		_x('Soedra Vi-Djursdala', 'VIKO2', 'ry-wc-city-select'),
		_x('Tuna', 'VIKO2', 'ry-wc-city-select'),
		_x('Vimmerby', 'VIKO2', 'ry-wc-city-select'),
	],
	'VIKO3' => [
		_x('Vindeln', 'VIKO3', 'ry-wc-city-select'),
	],
	'VIKO4' => [
		_x('OEsteraker', 'VIKO4', 'ry-wc-city-select'),
		_x('Vaestra Vingaker', 'VIKO4', 'ry-wc-city-select'),
	],
	'YDKO' => [
		_x('Norra Ydre', 'YDKO', 'ry-wc-city-select'),
		_x('Sund-Svinhult', 'YDKO', 'ry-wc-city-select'),
		_x('Vaestra Ryd', 'YDKO', 'ry-wc-city-select'),
	],
	'YSKO' => [
		_x('Ljunits', 'YSKO', 'ry-wc-city-select'),
		_x('Loederup', 'YSKO', 'ry-wc-city-select'),
		_x('Soevestadsbygden', 'YSKO', 'ry-wc-city-select'),
		_x('Stora Koepinge', 'YSKO', 'ry-wc-city-select'),
		_x('Ystad', 'YSKO', 'ry-wc-city-select'),
	],
	]
];