<?php
/**
 * Republic of El Salvador places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'SV' => [
	'DEAH' => [
		_x('Apaneca', 'DEAH', 'ry-wc-city-select'),
		_x('Concepcion de Ataco', 'DEAH', 'ry-wc-city-select'),
		_x('Distrito de Ahuachapan', 'DEAH', 'ry-wc-city-select'),
		_x('Distrito de Atiquizaya', 'DEAH', 'ry-wc-city-select'),
		_x('El Refugio', 'DEAH', 'ry-wc-city-select'),
		_x('Guaymango', 'DEAH', 'ry-wc-city-select'),
		_x('Jujutla', 'DEAH', 'ry-wc-city-select'),
		_x('San Francisco Menendez', 'DEAH', 'ry-wc-city-select'),
		_x('San Lorenzo', 'DEAH', 'ry-wc-city-select'),
		_x('San Pedro Puxtla', 'DEAH', 'ry-wc-city-select'),
		_x('Tacuba', 'DEAH', 'ry-wc-city-select'),
		_x('Turin', 'DEAH', 'ry-wc-city-select'),
	],
	'DECA' => [
		_x('Cinquera', 'DECA', 'ry-wc-city-select'),
		_x('Distrito de Ilobasco', 'DECA', 'ry-wc-city-select'),
		_x('Distrito de Sensuntepeque', 'DECA', 'ry-wc-city-select'),
		_x('Dolores', 'DECA', 'ry-wc-city-select'),
		_x('Guacotecti', 'DECA', 'ry-wc-city-select'),
		_x('Jutiapa', 'DECA', 'ry-wc-city-select'),
		_x('San Isidro', 'DECA', 'ry-wc-city-select'),
		_x('Tejutepeque', 'DECA', 'ry-wc-city-select'),
		_x('Victoria', 'DECA', 'ry-wc-city-select'),
	],
	'DECH' => [
		_x('Agua Caliente', 'DECH', 'ry-wc-city-select'),
		_x('Arcatao', 'DECH', 'ry-wc-city-select'),
		_x('Azacualpa', 'DECH', 'ry-wc-city-select'),
		_x('Cancasque', 'DECH', 'ry-wc-city-select'),
		_x('Citala', 'DECH', 'ry-wc-city-select'),
		_x('Comalapa', 'DECH', 'ry-wc-city-select'),
		_x('Concepcion Quezaltepeque', 'DECH', 'ry-wc-city-select'),
		_x('Distrito de Chalatenango', 'DECH', 'ry-wc-city-select'),
		_x('Distrito de Dulce Nombre de Maria', 'DECH', 'ry-wc-city-select'),
		_x('Distrito de Tejutla', 'DECH', 'ry-wc-city-select'),
		_x('El Carrizal', 'DECH', 'ry-wc-city-select'),
		_x('El Paraiso', 'DECH', 'ry-wc-city-select'),
		_x('La Laguna', 'DECH', 'ry-wc-city-select'),
		_x('La Palma', 'DECH', 'ry-wc-city-select'),
		_x('La Reina', 'DECH', 'ry-wc-city-select'),
		_x('Las Flores', 'DECH', 'ry-wc-city-select'),
		_x('Las Vueltas', 'DECH', 'ry-wc-city-select'),
		_x('Mercedes', 'DECH', 'ry-wc-city-select'),
		_x('Nombre de Jesus', 'DECH', 'ry-wc-city-select'),
		_x('Nueva Concepcion', 'DECH', 'ry-wc-city-select'),
		_x('Nueva Trinidad', 'DECH', 'ry-wc-city-select'),
		_x('Ojos de Agua', 'DECH', 'ry-wc-city-select'),
		_x('Potonico', 'DECH', 'ry-wc-city-select'),
		_x('San Antonio de la Cruz', 'DECH', 'ry-wc-city-select'),
		_x('San Antonio los Ranchos', 'DECH', 'ry-wc-city-select'),
		_x('San Fernando', 'DECH', 'ry-wc-city-select'),
		_x('San Francisco Lempa', 'DECH', 'ry-wc-city-select'),
		_x('San Francisco Morazan', 'DECH', 'ry-wc-city-select'),
		_x('San Ignacio', 'DECH', 'ry-wc-city-select'),
		_x('San Isidro Labrador', 'DECH', 'ry-wc-city-select'),
		_x('San Luis del Carmen', 'DECH', 'ry-wc-city-select'),
		_x('San Miguel de Mercedes', 'DECH', 'ry-wc-city-select'),
		_x('San Rafael', 'DECH', 'ry-wc-city-select'),
		_x('Santa Rita', 'DECH', 'ry-wc-city-select'),
	],
	'DECU' => [
		_x('Candelaria', 'DECU', 'ry-wc-city-select'),
		_x('Distrito de Cojutepeque', 'DECU', 'ry-wc-city-select'),
		_x('Distrito de Suchitoto', 'DECU', 'ry-wc-city-select'),
		_x('El Carmen', 'DECU', 'ry-wc-city-select'),
		_x('El Rosario', 'DECU', 'ry-wc-city-select'),
		_x('Monte San Juan', 'DECU', 'ry-wc-city-select'),
		_x('Oratorio de Concepcion', 'DECU', 'ry-wc-city-select'),
		_x('San Bartolome Perulapia', 'DECU', 'ry-wc-city-select'),
		_x('San Jose Guayabal', 'DECU', 'ry-wc-city-select'),
		_x('San Luis la  Herradura', 'DECU', 'ry-wc-city-select'),
		_x('San Pedro Perulapan', 'DECU', 'ry-wc-city-select'),
		_x('San Rafael Cedros', 'DECU', 'ry-wc-city-select'),
		_x('San Ramon', 'DECU', 'ry-wc-city-select'),
		_x('Santa Cruz Analquito', 'DECU', 'ry-wc-city-select'),
		_x('Santa Cruz Michapa', 'DECU', 'ry-wc-city-select'),
		_x('Tenancingo', 'DECU', 'ry-wc-city-select'),
	],
	'DELI' => [
		_x('Antiguo Cuscatlan', 'DELI', 'ry-wc-city-select'),
		_x('Chiltiupan', 'DELI', 'ry-wc-city-select'),
		_x('Ciudad Arce', 'DELI', 'ry-wc-city-select'),
		_x('Colon', 'DELI', 'ry-wc-city-select'),
		_x('Comasagua', 'DELI', 'ry-wc-city-select'),
		_x('Distrito de Quezaltepeque', 'DELI', 'ry-wc-city-select'),
		_x('Distrito de San Juan Opico', 'DELI', 'ry-wc-city-select'),
		_x('Distrito de Santa Tecla', 'DELI', 'ry-wc-city-select'),
		_x('Huizucar', 'DELI', 'ry-wc-city-select'),
		_x('Jayaque', 'DELI', 'ry-wc-city-select'),
		_x('Jicalapa', 'DELI', 'ry-wc-city-select'),
		_x('Nuevo Cuscatlan', 'DELI', 'ry-wc-city-select'),
		_x('Sacacoyo', 'DELI', 'ry-wc-city-select'),
		_x('San Jose Villanueva', 'DELI', 'ry-wc-city-select'),
		_x('San Matias', 'DELI', 'ry-wc-city-select'),
		_x('San Pablo Tacachico', 'DELI', 'ry-wc-city-select'),
		_x('Talnique', 'DELI', 'ry-wc-city-select'),
		_x('Tamanique', 'DELI', 'ry-wc-city-select'),
		_x('Teotepeque', 'DELI', 'ry-wc-city-select'),
		_x('Tepecoyo', 'DELI', 'ry-wc-city-select'),
		_x('Zaragoza', 'DELI', 'ry-wc-city-select'),
	],
	'DEPA' => [
		_x('Cuyultitan', 'DEPA', 'ry-wc-city-select'),
		_x('Distrito de Olocuilta', 'DEPA', 'ry-wc-city-select'),
		_x('Distrito de San Pedro Masahuat', 'DEPA', 'ry-wc-city-select'),
		_x('Distrito de San Pedro Nonualco', 'DEPA', 'ry-wc-city-select'),
		_x('Distrito de Zacatecoluca', 'DEPA', 'ry-wc-city-select'),
		_x('El Rosario', 'DEPA', 'ry-wc-city-select'),
		_x('Guadalupe', 'DEPA', 'ry-wc-city-select'),
		_x('Jerusalen', 'DEPA', 'ry-wc-city-select'),
		_x('Mercedes la Ceiba', 'DEPA', 'ry-wc-city-select'),
		_x('Paraiso de Osorio', 'DEPA', 'ry-wc-city-select'),
		_x('San Antonio Masahuat', 'DEPA', 'ry-wc-city-select'),
		_x('San Emigdio', 'DEPA', 'ry-wc-city-select'),
		_x('San Francisco Chinameca', 'DEPA', 'ry-wc-city-select'),
		_x('San Juan Nonualco', 'DEPA', 'ry-wc-city-select'),
		_x('San Juan Talpa', 'DEPA', 'ry-wc-city-select'),
		_x('San Juan Tepezontes', 'DEPA', 'ry-wc-city-select'),
		_x('San Luis Talpa', 'DEPA', 'ry-wc-city-select'),
		_x('San Miguel Tepezontes', 'DEPA', 'ry-wc-city-select'),
		_x('San Rafael Obrajuelo', 'DEPA', 'ry-wc-city-select'),
		_x('Santa Maria Ostuma', 'DEPA', 'ry-wc-city-select'),
		_x('Santiago Nonualco', 'DEPA', 'ry-wc-city-select'),
		_x('Tapalhuaca', 'DEPA', 'ry-wc-city-select'),
	],
	'DEUN' => [
		_x('Anamoros', 'DEUN', 'ry-wc-city-select'),
		_x('Bolivar', 'DEUN', 'ry-wc-city-select'),
		_x('Concepcion de Oriente', 'DEUN', 'ry-wc-city-select'),
		_x('Conchagua', 'DEUN', 'ry-wc-city-select'),
		_x('Distrito de La Union', 'DEUN', 'ry-wc-city-select'),
		_x('Distrito de Santa Rosa de Lima', 'DEUN', 'ry-wc-city-select'),
		_x('El Carmen', 'DEUN', 'ry-wc-city-select'),
		_x('El Sauce', 'DEUN', 'ry-wc-city-select'),
		_x('Intipuca', 'DEUN', 'ry-wc-city-select'),
		_x('Lislique', 'DEUN', 'ry-wc-city-select'),
		_x('Meanguera del Golfo', 'DEUN', 'ry-wc-city-select'),
		_x('Nueva Esparta', 'DEUN', 'ry-wc-city-select'),
		_x('Pasaquina', 'DEUN', 'ry-wc-city-select'),
		_x('Poloros', 'DEUN', 'ry-wc-city-select'),
		_x('San Alejo', 'DEUN', 'ry-wc-city-select'),
		_x('San Jose', 'DEUN', 'ry-wc-city-select'),
		_x('Yayantique', 'DEUN', 'ry-wc-city-select'),
		_x('Yucuaiquin', 'DEUN', 'ry-wc-city-select'),
	],
	'DEMO' => [
		_x('Arambala', 'DEMO', 'ry-wc-city-select'),
		_x('Cacaopera', 'DEMO', 'ry-wc-city-select'),
		_x('Chilanga', 'DEMO', 'ry-wc-city-select'),
		_x('Corinto', 'DEMO', 'ry-wc-city-select'),
		_x('Delicias de Concepcion', 'DEMO', 'ry-wc-city-select'),
		_x('Distrito de Jocoaitique', 'DEMO', 'ry-wc-city-select'),
		_x('Distrito de Osicala', 'DEMO', 'ry-wc-city-select'),
		_x('Distrito de San Francisco', 'DEMO', 'ry-wc-city-select'),
		_x('El Divisadero', 'DEMO', 'ry-wc-city-select'),
		_x('El Rosario', 'DEMO', 'ry-wc-city-select'),
		_x('Gualococti', 'DEMO', 'ry-wc-city-select'),
		_x('Guatajiagua', 'DEMO', 'ry-wc-city-select'),
		_x('Joateca', 'DEMO', 'ry-wc-city-select'),
		_x('Jocoro', 'DEMO', 'ry-wc-city-select'),
		_x('Lolotiquillo', 'DEMO', 'ry-wc-city-select'),
		_x('Meanguera', 'DEMO', 'ry-wc-city-select'),
		_x('Perquin', 'DEMO', 'ry-wc-city-select'),
		_x('San Carlos', 'DEMO', 'ry-wc-city-select'),
		_x('San Fernando', 'DEMO', 'ry-wc-city-select'),
		_x('San Francisco Gotera', 'DEMO', 'ry-wc-city-select'),
		_x('San Isidro', 'DEMO', 'ry-wc-city-select'),
		_x('San Simon', 'DEMO', 'ry-wc-city-select'),
		_x('Sensembra', 'DEMO', 'ry-wc-city-select'),
		_x('Sociedad', 'DEMO', 'ry-wc-city-select'),
		_x('Torola', 'DEMO', 'ry-wc-city-select'),
		_x('Yamabal', 'DEMO', 'ry-wc-city-select'),
		_x('Yoloaiquin', 'DEMO', 'ry-wc-city-select'),
	],
	'DESAMI' => [
		_x('Carolina', 'DESAMI', 'ry-wc-city-select'),
		_x('Chapeltique', 'DESAMI', 'ry-wc-city-select'),
		_x('Chirilagua', 'DESAMI', 'ry-wc-city-select'),
		_x('Ciudad Barrios', 'DESAMI', 'ry-wc-city-select'),
		_x('Comacaran', 'DESAMI', 'ry-wc-city-select'),
		_x('Distrito de Chinameca', 'DESAMI', 'ry-wc-city-select'),
		_x('Distrito de San Miguel', 'DESAMI', 'ry-wc-city-select'),
		_x('Distrito de Sesori', 'DESAMI', 'ry-wc-city-select'),
		_x('El Transito', 'DESAMI', 'ry-wc-city-select'),
		_x('Lolotique', 'DESAMI', 'ry-wc-city-select'),
		_x('Moncagua', 'DESAMI', 'ry-wc-city-select'),
		_x('Nueva Guadalupe', 'DESAMI', 'ry-wc-city-select'),
		_x('Nuevo Eden de San Juan', 'DESAMI', 'ry-wc-city-select'),
		_x('Quelepa', 'DESAMI', 'ry-wc-city-select'),
		_x('San Gerardo', 'DESAMI', 'ry-wc-city-select'),
		_x('San Jorge', 'DESAMI', 'ry-wc-city-select'),
		_x('San Luis de la Reina', 'DESAMI', 'ry-wc-city-select'),
		_x('San Rafael Oriente', 'DESAMI', 'ry-wc-city-select'),
		_x('Uluazapa', 'DESAMI', 'ry-wc-city-select'),
	],
	'DESASA' => [
		_x('Aguilares', 'DESASA', 'ry-wc-city-select'),
		_x('Apopa', 'DESASA', 'ry-wc-city-select'),
		_x('Ayutuxtepeque', 'DESASA', 'ry-wc-city-select'),
		_x('Ciudad Delgado', 'DESASA', 'ry-wc-city-select'),
		_x('Cuscatancingo', 'DESASA', 'ry-wc-city-select'),
		_x('Distrito de San Salvador', 'DESASA', 'ry-wc-city-select'),
		_x('Distrito de Santo Tomas', 'DESASA', 'ry-wc-city-select'),
		_x('Distrito de Tonacatepeque', 'DESASA', 'ry-wc-city-select'),
		_x('Guazapa', 'DESASA', 'ry-wc-city-select'),
		_x('Ilopango', 'DESASA', 'ry-wc-city-select'),
		_x('Mejicanos', 'DESASA', 'ry-wc-city-select'),
		_x('Municipio de El Paisnal', 'DESASA', 'ry-wc-city-select'),
		_x('Nejapa', 'DESASA', 'ry-wc-city-select'),
		_x('Panchimalco', 'DESASA', 'ry-wc-city-select'),
		_x('Rosario de Mora', 'DESASA', 'ry-wc-city-select'),
		_x('San Marcos', 'DESASA', 'ry-wc-city-select'),
		_x('San Martin', 'DESASA', 'ry-wc-city-select'),
		_x('Santiago Texacuangos', 'DESASA', 'ry-wc-city-select'),
		_x('Soyapango', 'DESASA', 'ry-wc-city-select'),
	],
	'DESAVI' => [
		_x('Apastepeque', 'DESAVI', 'ry-wc-city-select'),
		_x('Distrito de San Sebastian', 'DESAVI', 'ry-wc-city-select'),
		_x('Distrito de San Vicente', 'DESAVI', 'ry-wc-city-select'),
		_x('San Cayetano Istepeque', 'DESAVI', 'ry-wc-city-select'),
		_x('San Esteban Catarina', 'DESAVI', 'ry-wc-city-select'),
		_x('San Ildefonso', 'DESAVI', 'ry-wc-city-select'),
		_x('San Lorenzo', 'DESAVI', 'ry-wc-city-select'),
		_x('Santa Clara', 'DESAVI', 'ry-wc-city-select'),
		_x('Santo Domingo', 'DESAVI', 'ry-wc-city-select'),
		_x('Tecoluca', 'DESAVI', 'ry-wc-city-select'),
		_x('Tepetitan', 'DESAVI', 'ry-wc-city-select'),
		_x('Verapaz', 'DESAVI', 'ry-wc-city-select'),
	],
	'DESAAN' => [
		_x('Candelaria de la Frontera', 'DESAAN', 'ry-wc-city-select'),
		_x('Coatepeque', 'DESAAN', 'ry-wc-city-select'),
		_x('Distrito de Chalchuapa', 'DESAAN', 'ry-wc-city-select'),
		_x('Distrito de Metapan', 'DESAAN', 'ry-wc-city-select'),
		_x('Distrito de Santa Ana', 'DESAAN', 'ry-wc-city-select'),
		_x('El Congo', 'DESAAN', 'ry-wc-city-select'),
		_x('El Porvenir', 'DESAAN', 'ry-wc-city-select'),
		_x('San Antonio Pajonal', 'DESAAN', 'ry-wc-city-select'),
		_x('San Sebastian Salitrillo', 'DESAAN', 'ry-wc-city-select'),
		_x('Santa Rosa Guachipilin', 'DESAAN', 'ry-wc-city-select'),
		_x('Santiago de la Frontera', 'DESAAN', 'ry-wc-city-select'),
		_x('Texistepeque', 'DESAAN', 'ry-wc-city-select'),
	],
	'DESO' => [
		_x('Acajutla', 'DESO', 'ry-wc-city-select'),
		_x('Armenia', 'DESO', 'ry-wc-city-select'),
		_x('Caluco', 'DESO', 'ry-wc-city-select'),
		_x('Cuisnahuat', 'DESO', 'ry-wc-city-select'),
		_x('Distrito de Izalco', 'DESO', 'ry-wc-city-select'),
		_x('Distrito de Juayua', 'DESO', 'ry-wc-city-select'),
		_x('Distrito de Sonsonate', 'DESO', 'ry-wc-city-select'),
		_x('Nahuizalco', 'DESO', 'ry-wc-city-select'),
		_x('Nahulingo', 'DESO', 'ry-wc-city-select'),
		_x('Salcoatitan', 'DESO', 'ry-wc-city-select'),
		_x('San Antonio del Monte', 'DESO', 'ry-wc-city-select'),
		_x('San Julian', 'DESO', 'ry-wc-city-select'),
		_x('Santa Catarina Masahuat', 'DESO', 'ry-wc-city-select'),
		_x('Santa Isabel Ishuatan', 'DESO', 'ry-wc-city-select'),
		_x('Santo Domingo de Guzman', 'DESO', 'ry-wc-city-select'),
		_x('Sonzacate', 'DESO', 'ry-wc-city-select'),
	],
	'DEUS' => [
		_x('Alegria', 'DEUS', 'ry-wc-city-select'),
		_x('California', 'DEUS', 'ry-wc-city-select'),
		_x('Concepcion Batres', 'DEUS', 'ry-wc-city-select'),
		_x('Distrito de Berlin', 'DEUS', 'ry-wc-city-select'),
		_x('Distrito de Jucuapa', 'DEUS', 'ry-wc-city-select'),
		_x('Distrito de Santiago de Maria', 'DEUS', 'ry-wc-city-select'),
		_x('Distrito de Usulutan', 'DEUS', 'ry-wc-city-select'),
		_x('El Triunfo', 'DEUS', 'ry-wc-city-select'),
		_x('Ereguayquin', 'DEUS', 'ry-wc-city-select'),
		_x('Estanzuelas', 'DEUS', 'ry-wc-city-select'),
		_x('Jiquilisco', 'DEUS', 'ry-wc-city-select'),
		_x('Jucuaran', 'DEUS', 'ry-wc-city-select'),
		_x('Mercedes Umana', 'DEUS', 'ry-wc-city-select'),
		_x('Nueva Granada', 'DEUS', 'ry-wc-city-select'),
		_x('Ozatlan', 'DEUS', 'ry-wc-city-select'),
		_x('Puerto El Triunfo', 'DEUS', 'ry-wc-city-select'),
		_x('San Agustin', 'DEUS', 'ry-wc-city-select'),
		_x('San Buenaventura', 'DEUS', 'ry-wc-city-select'),
		_x('San Dionisio', 'DEUS', 'ry-wc-city-select'),
		_x('San Francisco Javier', 'DEUS', 'ry-wc-city-select'),
		_x('Santa Elena', 'DEUS', 'ry-wc-city-select'),
		_x('Santa Maria', 'DEUS', 'ry-wc-city-select'),
		_x('Tecapan', 'DEUS', 'ry-wc-city-select'),
	],
	]
];