<?php
/**
 * Kingdom of Thailand places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'TH' => [
	'AMBAKR' => [
		_x('Sala Klang', 'AMBAKR', 'ry-wc-city-select'),
		_x('Tambon Plai Bang', 'AMBAKR', 'ry-wc-city-select'),
	],
	'AMBAYA' => [
		_x('Tambon Bang Yai', 'AMBAYA', 'ry-wc-city-select'),
	],
	'AMMASA' => [
		_x('Pa Pae', 'AMMASA', 'ry-wc-city-select'),
	],
	'AMMUNO' => [
		_x('Tambon Bang Khen', 'AMMUNO', 'ry-wc-city-select'),
	],
	'AMPA' => [
		_x('Tambon Mae Hi', 'AMPA', 'ry-wc-city-select'),
		_x('Tambon Wiang Nuea', 'AMPA', 'ry-wc-city-select'),
	],
	'AMPAKR' => [
		_x('Tambon Bang Talat', 'AMPAKR', 'ry-wc-city-select'),
	],
	'AMTH' => [
		_x('Tambon Rangsit', 'AMTH', 'ry-wc-city-select'),
	],
	'BAPH' => [
		_x('Khwaeng Bang O', 'BAPH', 'ry-wc-city-select'),
	],
	'DOMU' => [
		_x('Khwaeng Si Kan', 'DOMU', 'ry-wc-city-select'),
	],
	'KHSA' => [
		_x('Khwaeng Sam Wa Tawan Ok', 'KHSA', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Khwaeng Thung Song Hong', 'LA', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Bang Bon', 'BA', 'ry-wc-city-select'),
		_x('Bang Kapi', 'BA', 'ry-wc-city-select'),
		_x('Bang Khae', 'BA', 'ry-wc-city-select'),
		_x('Bang Khen', 'BA', 'ry-wc-city-select'),
		_x('Bang Kho laen', 'BA', 'ry-wc-city-select'),
		_x('Bang Khun thain', 'BA', 'ry-wc-city-select'),
		_x('Bang Na', 'BA', 'ry-wc-city-select'),
		_x('Bang Rak', 'BA', 'ry-wc-city-select'),
		_x('Bang Sue', 'BA', 'ry-wc-city-select'),
		_x('Bangkok Noi', 'BA', 'ry-wc-city-select'),
		_x('Bangkok Yai', 'BA', 'ry-wc-city-select'),
		_x('Bueng Kum', 'BA', 'ry-wc-city-select'),
		_x('Chatu Chak', 'BA', 'ry-wc-city-select'),
		_x('Chom Thong', 'BA', 'ry-wc-city-select'),
		_x('Din Daeng', 'BA', 'ry-wc-city-select'),
		_x('Dusit', 'BA', 'ry-wc-city-select'),
		_x('Huai Khwang', 'BA', 'ry-wc-city-select'),
		_x('Khan Na Yao', 'BA', 'ry-wc-city-select'),
		_x('Khlong San', 'BA', 'ry-wc-city-select'),
		_x('Khlong Toei', 'BA', 'ry-wc-city-select'),
		_x('Lat Krabang', 'BA', 'ry-wc-city-select'),
		_x('Lat Phrao', 'BA', 'ry-wc-city-select'),
		_x('Min Buri', 'BA', 'ry-wc-city-select'),
		_x('Nong Chok', 'BA', 'ry-wc-city-select'),
		_x('Nong Khaem', 'BA', 'ry-wc-city-select'),
		_x('Parthum Wan', 'BA', 'ry-wc-city-select'),
		_x('Phasi Charoen', 'BA', 'ry-wc-city-select'),
		_x('Phaya Thai', 'BA', 'ry-wc-city-select'),
		_x('Phra Khanong', 'BA', 'ry-wc-city-select'),
		_x('Phra Nakhon', 'BA', 'ry-wc-city-select'),
		_x('Pom Prap Sattru Phai', 'BA', 'ry-wc-city-select'),
		_x('Pra Wet', 'BA', 'ry-wc-city-select'),
		_x('Rat Burana', 'BA', 'ry-wc-city-select'),
		_x('Ratchathewi', 'BA', 'ry-wc-city-select'),
		_x('Sai Mai', 'BA', 'ry-wc-city-select'),
		_x('Samphanthawong', 'BA', 'ry-wc-city-select'),
		_x('Saphan Sung', 'BA', 'ry-wc-city-select'),
		_x('Sathon', 'BA', 'ry-wc-city-select'),
		_x('Suanluang', 'BA', 'ry-wc-city-select'),
		_x('Taling Chan', 'BA', 'ry-wc-city-select'),
		_x('Thawi Watthana', 'BA', 'ry-wc-city-select'),
		_x('Thon buri', 'BA', 'ry-wc-city-select'),
		_x('Thung khru', 'BA', 'ry-wc-city-select'),
		_x('Vadhana', 'BA', 'ry-wc-city-select'),
		_x('Wang Thong Lang', 'BA', 'ry-wc-city-select'),
		_x('Yan na wa', 'BA', 'ry-wc-city-select'),
	],
	'CHAMCH' => [
		_x('Amphoe Chanuman', 'CHAMCH', 'ry-wc-city-select'),
		_x('Amphoe Hua Taphan', 'CHAMCH', 'ry-wc-city-select'),
		_x('Amphoe Lue Amnat', 'CHAMCH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Amnat Charoen', 'CHAMCH', 'ry-wc-city-select'),
		_x('Amphoe Pathum Ratchawongsa', 'CHAMCH', 'ry-wc-city-select'),
		_x('Amphoe Phana', 'CHAMCH', 'ry-wc-city-select'),
		_x('Amphoe Senangkhanikhom', 'CHAMCH', 'ry-wc-city-select'),
	],
	'CHANTH' => [
		_x('Amphoe Chaiyo', 'CHANTH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Ang Thong', 'CHANTH', 'ry-wc-city-select'),
		_x('Amphoe Pa Mok', 'CHANTH', 'ry-wc-city-select'),
		_x('Amphoe Pho Thong', 'CHANTH', 'ry-wc-city-select'),
		_x('Amphoe Sam Ko', 'CHANTH', 'ry-wc-city-select'),
		_x('Amphoe Sawaeng Ha', 'CHANTH', 'ry-wc-city-select'),
		_x('Amphoe Wiset Chai Chan', 'CHANTH', 'ry-wc-city-select'),
	],
	'CHBUKA' => [
		_x('Amphoe Bueng Khong Long', 'CHBUKA', 'ry-wc-city-select'),
		_x('Amphoe Bung Khla', 'CHBUKA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Bueng Kan', 'CHBUKA', 'ry-wc-city-select'),
		_x('Amphoe Pak Khat', 'CHBUKA', 'ry-wc-city-select'),
		_x('Amphoe Phon Charoen', 'CHBUKA', 'ry-wc-city-select'),
		_x('Amphoe Seka', 'CHBUKA', 'ry-wc-city-select'),
		_x('Amphoe Si Wilai', 'CHBUKA', 'ry-wc-city-select'),
		_x('Amphoe So Phisai', 'CHBUKA', 'ry-wc-city-select'),
	],
	'CHBURA' => [
		_x('Amphoe Ban Dan', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Ban Kruat', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Ban Mai Chaiyaphot', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Chaloem Phra Kiat', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Chamni', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Huai Rat', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Khaen Dong', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Khu Mueang', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Krasang', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Lahan Sai', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Lam Plai Mat', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Buriram', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Na Pho', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Nang Rong', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Non Din Daeng', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Non Suwan', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Nong Hong', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Nong Ki', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Pa Kham', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Phlapphla Chai', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Phutthaisong', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Prakhon Chai', 'CHBURA', 'ry-wc-city-select'),
		_x('Amphoe Satuek', 'CHBURA', 'ry-wc-city-select'),
	],
	'CHCH' => [
		_x('Amphoe Ban Pho', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Bang Khla', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Bang Nam Priao', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Bang Pakong', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Khlong Khuean', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Chachoengsao', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Phanom Sarakham', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Plaeng Yao', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Ratchasan', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Sanam Chai Khet', 'CHCH', 'ry-wc-city-select'),
		_x('Amphoe Tha Takiap', 'CHCH', 'ry-wc-city-select'),
	],
	'CHCHNA' => [
		_x('Amphoe Hankha', 'CHCHNA', 'ry-wc-city-select'),
		_x('Amphoe Manorom', 'CHCHNA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Chainat', 'CHCHNA', 'ry-wc-city-select'),
		_x('Amphoe Noen Kham', 'CHCHNA', 'ry-wc-city-select'),
		_x('Amphoe Nong Mamong', 'CHCHNA', 'ry-wc-city-select'),
		_x('Amphoe Sankhaburi', 'CHCHNA', 'ry-wc-city-select'),
		_x('Amphoe Sapphaya', 'CHCHNA', 'ry-wc-city-select'),
		_x('Amphoe Wat Sing', 'CHCHNA', 'ry-wc-city-select'),
	],
	'CHCH2' => [
		_x('Amphoe Bamnet Narong', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Ban Khwao', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Ban Thaen', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Chatturat', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Kaeng Khro', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Kaset Sombun', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Khon San', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Khon Sawan', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Chaiyaphum', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Noen Sa-nga', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Nong Bua Daeng', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Nong Bua Rawe', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Phakdi Chumphon', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Phu Khiao', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Sap Yai', 'CHCH2', 'ry-wc-city-select'),
		_x('Amphoe Thep Sathit', 'CHCH2', 'ry-wc-city-select'),
	],
	'CHCH3' => [
		_x('Amphoe Kaeng Hang Maeo', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Khao Khitchakut', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Khlung', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Laem Sing', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Makham', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Mueang Chanthaburi', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Na Yai Am', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Pong Nam Ron', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Soi Dao', 'CHCH3', 'ry-wc-city-select'),
		_x('Amphoe Tha Mai', 'CHCH3', 'ry-wc-city-select'),
	],
	'CHCHRA' => [
		_x('Amphoe Chiang Khong', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Chiang Saen', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Doi Luang', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Khun Tan', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Mae Chan', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Mae Fa Luang', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Mae Lao', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Mae Sai', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Mae Suai', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Chiang Rai', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Pa Daet', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Phan', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Phaya Mengrai', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Thoeng', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Wiang Chai', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Wiang Chiang Rung', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Wiang Kaen', 'CHCHRA', 'ry-wc-city-select'),
		_x('Amphoe Wiang Pa Pao', 'CHCHRA', 'ry-wc-city-select'),
	],
	'CHCHBU' => [
		_x('Amphoe Ban Bueng', 'CHCHBU', 'ry-wc-city-select'),
		_x('Amphoe Bo Thong', 'CHCHBU', 'ry-wc-city-select'),
		_x('Amphoe Ko Chan', 'CHCHBU', 'ry-wc-city-select'),
		_x('Amphoe Ko Si Chang', 'CHCHBU', 'ry-wc-city-select'),
		_x('Amphoe Nong Yai', 'CHCHBU', 'ry-wc-city-select'),
		_x('Amphoe Phan Thong', 'CHCHBU', 'ry-wc-city-select'),
		_x('Amphoe Phanat Nikhom', 'CHCHBU', 'ry-wc-city-select'),
		_x('Amphoe Sattahip', 'CHCHBU', 'ry-wc-city-select'),
		_x('Amphoe Si Racha', 'CHCHBU', 'ry-wc-city-select'),
		_x('Bang Lamung District', 'CHCHBU', 'ry-wc-city-select'),
		_x('Mueang Chonburi District', 'CHCHBU', 'ry-wc-city-select'),
	],
	'CHCH4' => [
		_x('Amphoe Lamae', 'CHCH4', 'ry-wc-city-select'),
		_x('Amphoe Lang Suan', 'CHCH4', 'ry-wc-city-select'),
		_x('Amphoe Mueang Chumphon', 'CHCH4', 'ry-wc-city-select'),
		_x('Amphoe Pathio', 'CHCH4', 'ry-wc-city-select'),
		_x('Amphoe Phato', 'CHCH4', 'ry-wc-city-select'),
		_x('Amphoe Sawi', 'CHCH4', 'ry-wc-city-select'),
		_x('Amphoe Tha Sae', 'CHCH4', 'ry-wc-city-select'),
		_x('Amphoe Thung Tako', 'CHCH4', 'ry-wc-city-select'),
	],
	'CHKA' => [
		_x('Amphoe Don Chan', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Huai Mek', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Huai Phueng', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Kamalasai', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Kham Muang', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Khao Wong', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Khong Chai', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Kuchinarai', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Kalasin', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Na Khu', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Na Mon', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Nong Kung Si', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Rong Kham', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Sahatsakhan', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Sam Chai', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Somdet', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Tha Khantho', 'CHKA', 'ry-wc-city-select'),
		_x('Amphoe Yang Talat', 'CHKA', 'ry-wc-city-select'),
	],
	'CHKAPH' => [
		_x('Amphoe Bueng Samakkhi', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Khanu Woralaksaburi', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Khlong Khlung', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Khlong Lan', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Kosamphi Nakhon', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Lan Krabue', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Kamphaeng Phet', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Pang Sila Thong', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Phran Kratai', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Sai Ngam', 'CHKAPH', 'ry-wc-city-select'),
		_x('Amphoe Sai Thong Watthana', 'CHKAPH', 'ry-wc-city-select'),
	],
	'CHKA2' => [
		_x('Amphoe Bo Phloi', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Dan Makham Tia', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Huai Krachao', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Lao Khwan', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Kanchanaburi', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Nong Prue', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Phanom Thuan', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Sai Yok', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Sangkhla Buri', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Si Sawat', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Tha Maka', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Tha Muang', 'CHKA2', 'ry-wc-city-select'),
		_x('Amphoe Thong Pha Phum', 'CHKA2', 'ry-wc-city-select'),
	],
	'CHKHKA' => [
		_x('Amphoe Ban Fang', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Ban Haet', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Ban Phai', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Chonnabot', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Chum Phae', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Khao Suan Kwang', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Khok Pho Chai', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Kranuan', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Mancha Khiri', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Khon Kaen', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Nam Phong', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Non Sila', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Nong Na Kham', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Nong Ruea', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Nong Song Hong', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Phon', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Phra Yuen', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Phu Pha Man', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Phu Wiang', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Pueai Noi', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Sam Sung', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Si Chom Phu', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Ubolratana', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Waeng Noi', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Waeng Yai', 'CHKHKA', 'ry-wc-city-select'),
		_x('Amphoe Wiang Kao', 'CHKHKA', 'ry-wc-city-select'),
	],
	'CHKR' => [
		_x('Amphoe Ao Luek', 'CHKR', 'ry-wc-city-select'),
		_x('Amphoe Khao Phanom', 'CHKR', 'ry-wc-city-select'),
		_x('Amphoe Khlong Thom', 'CHKR', 'ry-wc-city-select'),
		_x('Amphoe Ko Lanta', 'CHKR', 'ry-wc-city-select'),
		_x('Amphoe Lam Thap', 'CHKR', 'ry-wc-city-select'),
		_x('Amphoe Mueang Krabi', 'CHKR', 'ry-wc-city-select'),
		_x('Amphoe Nuea Khlong', 'CHKR', 'ry-wc-city-select'),
		_x('Amphoe Plai Phraya', 'CHKR', 'ry-wc-city-select'),
	],
	'CHLA' => [
		_x('Amphoe Chae Hom', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Hang Chat', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Ko Kha', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Mae Mo', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Mae Phrik', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Mae Tha', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Lampang', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Pan', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Ngao', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Soem Ngam', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Sop Prap', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Thoen', 'CHLA', 'ry-wc-city-select'),
		_x('Amphoe Wang Nuea', 'CHLA', 'ry-wc-city-select'),
	],
	'CHLA2' => [
		_x('Amphoe Ban Hong', 'CHLA2', 'ry-wc-city-select'),
		_x('Amphoe Ban Thi', 'CHLA2', 'ry-wc-city-select'),
		_x('Amphoe Li', 'CHLA2', 'ry-wc-city-select'),
		_x('Amphoe Mae Tha', 'CHLA2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Lamphun', 'CHLA2', 'ry-wc-city-select'),
		_x('Amphoe Pa Sang', 'CHLA2', 'ry-wc-city-select'),
		_x('Amphoe Thung Hua Chang', 'CHLA2', 'ry-wc-city-select'),
		_x('Amphoe Wiang Nong Long', 'CHLA2', 'ry-wc-city-select'),
	],
	'CHLO' => [
		_x('Amphoe Chiang Khan', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Dan Sai', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Erawan', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Mueang Loei', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Na Duang', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Na Haeo', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Nong Hin', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Pak Chom', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Pha Khao', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Phu Kradueng', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Phu Luang', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Phu Ruea', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Tha Li', 'CHLO', 'ry-wc-city-select'),
		_x('Amphoe Wang Saphung', 'CHLO', 'ry-wc-city-select'),
	],
	'CHLOBU' => [
		_x('Amphoe Ban Mi', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Chai Badan', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Khok Charoen', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Khok Samrong', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Lam Sonthi', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Nong Muang', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Phatthana Nikhom', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Sa Bot', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Tha Luang', 'CHLOBU', 'ry-wc-city-select'),
		_x('Amphoe Tha Wung', 'CHLOBU', 'ry-wc-city-select'),
		_x('Muang Lop Buri District', 'CHLOBU', 'ry-wc-city-select'),
	],
	'CHMAHOSO' => [
		_x('Amphoe Khun Yuam', 'CHMAHOSO', 'ry-wc-city-select'),
		_x('Amphoe Mae La Noi', 'CHMAHOSO', 'ry-wc-city-select'),
		_x('Amphoe Mueang Mae Hong Son', 'CHMAHOSO', 'ry-wc-city-select'),
		_x('Amphoe Pang Mapha', 'CHMAHOSO', 'ry-wc-city-select'),
		_x('Amphoe Sop Moei', 'CHMAHOSO', 'ry-wc-city-select'),
	],
	'CHMASA' => [
		_x('Amphoe Borabue', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Chiang Yuen', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Chuen Chom', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Kae Dam', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Kantharawichai', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Kosum Phisai', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Kut Rang', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Maha Sarakham', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Na Chueak', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Na Dun', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Phayakkhaphum Phisai', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Wapi Pathum', 'CHMASA', 'ry-wc-city-select'),
		_x('Amphoe Yang Si Surat', 'CHMASA', 'ry-wc-city-select'),
	],
	'CHMU' => [
		_x('Amphoe Don Tan', 'CHMU', 'ry-wc-city-select'),
		_x('Amphoe Dong Luang', 'CHMU', 'ry-wc-city-select'),
		_x('Amphoe Khamcha-i', 'CHMU', 'ry-wc-city-select'),
		_x('Amphoe Mueang Mukdahan', 'CHMU', 'ry-wc-city-select'),
		_x('Amphoe Nikhom Kham Soi', 'CHMU', 'ry-wc-city-select'),
		_x('Amphoe Nong Sung', 'CHMU', 'ry-wc-city-select'),
		_x('Amphoe Wan Yai', 'CHMU', 'ry-wc-city-select'),
	],
	'CHNANA' => [
		_x('Amphoe Ban Na', 'CHNANA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Nakhon Nayok', 'CHNANA', 'ry-wc-city-select'),
		_x('Amphoe Ongkharak', 'CHNANA', 'ry-wc-city-select'),
		_x('Amphoe Pak Phli', 'CHNANA', 'ry-wc-city-select'),
	],
	'CHNAPA' => [
		_x('Amphoe Bang Len', 'CHNAPA', 'ry-wc-city-select'),
		_x('Amphoe Don Tum', 'CHNAPA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Nakhon Pathom', 'CHNAPA', 'ry-wc-city-select'),
		_x('Amphoe Nakhon Chai Si', 'CHNAPA', 'ry-wc-city-select'),
		_x('Amphoe Phutthamonthon', 'CHNAPA', 'ry-wc-city-select'),
		_x('Amphoe Sam Phran', 'CHNAPA', 'ry-wc-city-select'),
		_x('Kamphaeng Saen District', 'CHNAPA', 'ry-wc-city-select'),
	],
	'CHNAPH' => [
		_x('Amphoe Ban Phaeng', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Nakhon Phanom', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Na Kae', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Na Thom', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Na Wa', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Phon Sawan', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Pla Pak', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Renu Nakhon', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Si Songkhram', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Tha Uthen', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe That Phanom', 'CHNAPH', 'ry-wc-city-select'),
		_x('Amphoe Wangyang', 'CHNAPH', 'ry-wc-city-select'),
	],
	'CHNARA' => [
		_x('Amphoe Ban Lueam', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Bua Lai', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Bua Yai', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Chakkarat', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Chaloem Phra Kiat', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Chok Chai', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Chum Phuang', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Dan Khun Thot', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Huai Thalaeng', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Kaeng Sanam Nang', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Kham Sakae Saeng', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Kham Thale So', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Khon Buri', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Khong', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Lam Thamen Chai', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Nakhon Ratchasima', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Yang', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Non Daeng', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Non Sung', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Non Thai', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Nong Bun Mak', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Pak Chong', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Pak Thong Chai', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Phimai', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Phra Thong Kham', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Prathai', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Sida', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Sikhio', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Soeng Sang', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Sung Noen', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Thepharak', 'CHNARA', 'ry-wc-city-select'),
		_x('Amphoe Wang Nam Khiao', 'CHNARA', 'ry-wc-city-select'),
	],
	'CHNASA' => [
		_x('Amphoe Banphot Phisai', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Chum Ta Bong', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Chumsaeng', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Kao Liao', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Krok Phra', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Lat Yao', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Mae Poen', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Mae Wong', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Nakhon Sawan', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Nong Bua', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Phai Sali', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Phayuha Khiri', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Tak Fa', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Takhli', 'CHNASA', 'ry-wc-city-select'),
		_x('Amphoe Tha Tako', 'CHNASA', 'ry-wc-city-select'),
	],
	'CHNATH' => [
		_x('Amphoe Bang Khan', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Cha-uat', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Chaloem Phra Kiat', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Chang Klang', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Chawang', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Chian Yai', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Chulabhorn', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Hua Sai', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Khanom', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Lan Saka', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Nakhon Si Thammarat', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Na Bon', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Nopphitam', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Pak Phanang', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Phipun', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Phra Phrom', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Phrom Khiri', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Ron Phibun', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Sichon', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Tha Sala', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Tham Phannara', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Thung Song', 'CHNATH', 'ry-wc-city-select'),
		_x('Amphoe Thung Yai', 'CHNATH', 'ry-wc-city-select'),
	],
	'CHNA' => [
		_x('Amphoe Ban Luang', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Bo Kluea', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Chaloem Phra Kiat', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Chiang Klang', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Mae Charim', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Nan', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Na Muen', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Na Noi', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Phu Phiang', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Pua', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Santi Suk', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Song Khwae', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Tha Wang Pha', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Thung Chang', 'CHNA', 'ry-wc-city-select'),
		_x('Amphoe Wiang Sa', 'CHNA', 'ry-wc-city-select'),
	],
	'CHNA2' => [
		_x('Amphoe Ba Cho', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Chanae', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Cho-airong', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Narathiwat', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Ra-ngae', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Rueso', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Si Sakhon', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Su-ngai Kolok', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Su-ngai Padi', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Sukhirin', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Tak Bai', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Waeng', 'CHNA2', 'ry-wc-city-select'),
		_x('Amphoe Yi-ngo', 'CHNA2', 'ry-wc-city-select'),
	],
	'CHNOBULA' => [
		_x('Amphoe Mueang Nong Bua Lamphu', 'CHNOBULA', 'ry-wc-city-select'),
		_x('Amphoe Na Klang', 'CHNOBULA', 'ry-wc-city-select'),
		_x('Amphoe Na Wang', 'CHNOBULA', 'ry-wc-city-select'),
		_x('Amphoe Non Sang', 'CHNOBULA', 'ry-wc-city-select'),
		_x('Amphoe Si Bun Rueang', 'CHNOBULA', 'ry-wc-city-select'),
		_x('Amphoe Suwannakhuha', 'CHNOBULA', 'ry-wc-city-select'),
	],
	'CHNOKH' => [
		_x('Amphoe Fao Rai', 'CHNOKH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Nong Khai', 'CHNOKH', 'ry-wc-city-select'),
		_x('Amphoe Pho Tak', 'CHNOKH', 'ry-wc-city-select'),
		_x('Amphoe Phonphisai', 'CHNOKH', 'ry-wc-city-select'),
		_x('Amphoe Rattanawapi', 'CHNOKH', 'ry-wc-city-select'),
		_x('Amphoe Sa Khrai', 'CHNOKH', 'ry-wc-city-select'),
		_x('Amphoe Sangkhom', 'CHNOKH', 'ry-wc-city-select'),
		_x('Amphoe Si Chiang Mai', 'CHNOKH', 'ry-wc-city-select'),
		_x('Amphoe Tha Bo', 'CHNOKH', 'ry-wc-city-select'),
	],
	'CHNO' => [
		_x('Amphoe Bang Bua Thong', 'CHNO', 'ry-wc-city-select'),
		_x('Amphoe Sai Noi', 'CHNO', 'ry-wc-city-select'),
	],
	'CHPATH' => [
		_x('Amphoe Khlong Luang', 'CHPATH', 'ry-wc-city-select'),
		_x('Amphoe Lam Luk Ka', 'CHPATH', 'ry-wc-city-select'),
		_x('Amphoe Lat Lum Kaeo', 'CHPATH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Pathum Thani', 'CHPATH', 'ry-wc-city-select'),
		_x('Amphoe Nong Suea', 'CHPATH', 'ry-wc-city-select'),
		_x('Amphoe Sam Khok', 'CHPATH', 'ry-wc-city-select'),
	],
	'CHPA' => [
		_x('Amphoe Kapho', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Khok Pho', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Mae Lan', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Mai Kaen', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Mayo', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Pattani', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Nong Chik', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Panare', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Sai Buri', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Thung Yang Daeng', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Yarang', 'CHPA', 'ry-wc-city-select'),
		_x('Amphoe Yaring', 'CHPA', 'ry-wc-city-select'),
	],
	'CHPH' => [
		_x('Amphoe Kapong', 'CHPH', 'ry-wc-city-select'),
		_x('Amphoe Khura Buri', 'CHPH', 'ry-wc-city-select'),
		_x('Amphoe Ko Yao', 'CHPH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phangnga', 'CHPH', 'ry-wc-city-select'),
		_x('Amphoe Takua Pa', 'CHPH', 'ry-wc-city-select'),
		_x('Amphoe Takua Thung', 'CHPH', 'ry-wc-city-select'),
		_x('Amphoe Thai Mueang', 'CHPH', 'ry-wc-city-select'),
		_x('Amphoe Thap Put', 'CHPH', 'ry-wc-city-select'),
	],
	'CHPH2' => [
		_x('Amphoe Bang Kaeo', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Khao Chaison', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Khuan Khanun', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Kong Ra', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phatthalung', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Pa Bon', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Pa Phayom', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Pak Phayun', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Si Banphot', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Srinagarindra', 'CHPH2', 'ry-wc-city-select'),
		_x('Amphoe Tamot', 'CHPH2', 'ry-wc-city-select'),
	],
	'CHPH3' => [
		_x('Amphoe Chiang Kham', 'CHPH3', 'ry-wc-city-select'),
		_x('Amphoe Chiang Muan', 'CHPH3', 'ry-wc-city-select'),
		_x('Amphoe Chun', 'CHPH3', 'ry-wc-city-select'),
		_x('Amphoe Dok Kham Tai', 'CHPH3', 'ry-wc-city-select'),
		_x('Amphoe Mae Chai', 'CHPH3', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phayao', 'CHPH3', 'ry-wc-city-select'),
		_x('Amphoe Phu Kam Yao', 'CHPH3', 'ry-wc-city-select'),
		_x('Amphoe Phu Sang', 'CHPH3', 'ry-wc-city-select'),
		_x('Amphoe Pong', 'CHPH3', 'ry-wc-city-select'),
	],
	'CHPH4' => [
		_x('Amphoe Bueng Sam Phan', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Chon Daen', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Khao Kho', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Lom Kao', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Lom Sak', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phetchabun', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Nam Nao', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Nong Phai', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Si Thep', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Wang Pong', 'CHPH4', 'ry-wc-city-select'),
		_x('Amphoe Wichian Buri', 'CHPH4', 'ry-wc-city-select'),
	],
	'CHPH5' => [
		_x('Amphoe Ban Laem', 'CHPH5', 'ry-wc-city-select'),
		_x('Amphoe Ban Lat', 'CHPH5', 'ry-wc-city-select'),
		_x('Amphoe Cha-am', 'CHPH5', 'ry-wc-city-select'),
		_x('Amphoe Kaeng Krachan', 'CHPH5', 'ry-wc-city-select'),
		_x('Amphoe Khao Yoi', 'CHPH5', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phetchaburi', 'CHPH5', 'ry-wc-city-select'),
		_x('Amphoe Nong Ya Plong', 'CHPH5', 'ry-wc-city-select'),
		_x('Amphoe Tha Yang', 'CHPH5', 'ry-wc-city-select'),
	],
	'CHPH6' => [
		_x('Amphoe Bang Mun Nak', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Bueng Na Rang', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Dong Charoen', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phichit', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Pho Prathap Chang', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Pho Thale', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Sak Lek', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Sam Ngam', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Taphan Hin', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Thap Khlo', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Wachira Barami', 'CHPH6', 'ry-wc-city-select'),
		_x('Amphoe Wang Sai Phun', 'CHPH6', 'ry-wc-city-select'),
	],
	'CHPH7' => [
		_x('Amphoe Bang Krathum', 'CHPH7', 'ry-wc-city-select'),
		_x('Amphoe Bang Rakam', 'CHPH7', 'ry-wc-city-select'),
		_x('Amphoe Chat Trakan', 'CHPH7', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phitsanulok', 'CHPH7', 'ry-wc-city-select'),
		_x('Amphoe Nakhon Thai', 'CHPH7', 'ry-wc-city-select'),
		_x('Amphoe Noen Maprang', 'CHPH7', 'ry-wc-city-select'),
		_x('Amphoe Phrom Phiram', 'CHPH7', 'ry-wc-city-select'),
		_x('Amphoe Wang Thong', 'CHPH7', 'ry-wc-city-select'),
		_x('Amphoe Wat Bot', 'CHPH7', 'ry-wc-city-select'),
	],
	'CHPH8' => [
		_x('Amphoe Den Chai', 'CHPH8', 'ry-wc-city-select'),
		_x('Amphoe Long', 'CHPH8', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phrae', 'CHPH8', 'ry-wc-city-select'),
		_x('Amphoe Nong Muang Khai', 'CHPH8', 'ry-wc-city-select'),
		_x('Amphoe Rong Kwang', 'CHPH8', 'ry-wc-city-select'),
		_x('Amphoe Song', 'CHPH8', 'ry-wc-city-select'),
		_x('Amphoe Sung Men', 'CHPH8', 'ry-wc-city-select'),
		_x('Amphoe Wang Chin', 'CHPH8', 'ry-wc-city-select'),
	],
	'CHPRBU' => [
		_x('Amphoe Ban Sang', 'CHPRBU', 'ry-wc-city-select'),
		_x('Amphoe Kabin Buri', 'CHPRBU', 'ry-wc-city-select'),
		_x('Amphoe Mueang Prachin Buri', 'CHPRBU', 'ry-wc-city-select'),
		_x('Amphoe Na Di', 'CHPRBU', 'ry-wc-city-select'),
		_x('Amphoe Prachantakham', 'CHPRBU', 'ry-wc-city-select'),
		_x('Amphoe Si Maha Phot', 'CHPRBU', 'ry-wc-city-select'),
		_x('Amphoe Si Mahosot', 'CHPRBU', 'ry-wc-city-select'),
	],
	'CHPRKHKH' => [
		_x('Amphoe Bang Saphan', 'CHPRKHKH', 'ry-wc-city-select'),
		_x('Amphoe Bang Saphan Noi', 'CHPRKHKH', 'ry-wc-city-select'),
		_x('Amphoe Hua Hin', 'CHPRKHKH', 'ry-wc-city-select'),
		_x('Amphoe Kui Buri', 'CHPRKHKH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Prachuap Khiri Khan', 'CHPRKHKH', 'ry-wc-city-select'),
		_x('Amphoe Pran Buri', 'CHPRKHKH', 'ry-wc-city-select'),
		_x('Amphoe Sam Roi Yot', 'CHPRKHKH', 'ry-wc-city-select'),
		_x('Amphoe Thap Sakae', 'CHPRKHKH', 'ry-wc-city-select'),
	],
	'CHRA' => [
		_x('Amphoe Kapoe', 'CHRA', 'ry-wc-city-select'),
		_x('Amphoe Kra Buri', 'CHRA', 'ry-wc-city-select'),
		_x('Amphoe La-un', 'CHRA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Ranong', 'CHRA', 'ry-wc-city-select'),
		_x('Amphoe Suk Samran', 'CHRA', 'ry-wc-city-select'),
	],
	'CHRA2' => [
		_x('Amphoe Ban Kha', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Ban Pong', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Bang Phae', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Chom Bueng', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Damnoen Saduak', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Ratchaburi', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Pak Tho', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Photharam', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Suan Phueng', 'CHRA2', 'ry-wc-city-select'),
		_x('Amphoe Wat Phleng', 'CHRA2', 'ry-wc-city-select'),
	],
	'CHRA3' => [
		_x('Amphoe Ban Chang', 'CHRA3', 'ry-wc-city-select'),
		_x('Amphoe Ban Khai', 'CHRA3', 'ry-wc-city-select'),
		_x('Amphoe Khao Chamao', 'CHRA3', 'ry-wc-city-select'),
		_x('Amphoe Klaeng', 'CHRA3', 'ry-wc-city-select'),
		_x('Amphoe Mueang Rayong', 'CHRA3', 'ry-wc-city-select'),
		_x('Amphoe Nikhom Phattana', 'CHRA3', 'ry-wc-city-select'),
		_x('Amphoe Pluak Daeng', 'CHRA3', 'ry-wc-city-select'),
		_x('Amphoe Wang Chan', 'CHRA3', 'ry-wc-city-select'),
	],
	'CHRO' => [
		_x('Amphoe At Samat', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Changhan', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Chaturaphak Phiman', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Chiang Khwan', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Kaset Wisai', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Moeiwadi', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Mueang Roi Et', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Mueang Suang', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Nong Hi', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Nong Phok', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Pathum Rat', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Phanom Phrai', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Pho Chai', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Phon Sai', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Phon Thong', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Selaphum', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Si Somdet', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Suwannaphum', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Thawatchaburi', 'CHRO', 'ry-wc-city-select'),
		_x('Amphoe Thung Khao Luang', 'CHRO', 'ry-wc-city-select'),
	],
	'CHKA3' => [
		_x('Amphoe Aranyaprathet', 'CHKA3', 'ry-wc-city-select'),
		_x('Amphoe Khao Chakan', 'CHKA3', 'ry-wc-city-select'),
		_x('Amphoe Khlong Hat', 'CHKA3', 'ry-wc-city-select'),
		_x('Amphoe Khok Sung', 'CHKA3', 'ry-wc-city-select'),
		_x('Amphoe Mueang Sa Kaeo', 'CHKA3', 'ry-wc-city-select'),
		_x('Amphoe Ta Phraya', 'CHKA3', 'ry-wc-city-select'),
		_x('Amphoe Wang Nam Yen', 'CHKA3', 'ry-wc-city-select'),
		_x('Amphoe Wang Sombun', 'CHKA3', 'ry-wc-city-select'),
		_x('Amphoe Watthana Nakhon', 'CHKA3', 'ry-wc-city-select'),
	],
	'CHSANA' => [
		_x('Amphoe Akat Amnuai', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Ban Muang', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Charoen Sin', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Kham Ta Kla', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Khok Si Suphan', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Kusuman', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Kut Bak', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Sakon Nakhon', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Nikhom Nam Un', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Phang Khon', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Phanna Nikhom', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Phon Na Kaeo', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Phu Phan', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Sawang Daen Din', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Song Dao', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Tao Ngoi', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Wanon Niwat', 'CHSANA', 'ry-wc-city-select'),
		_x('Amphoe Waritchaphum', 'CHSANA', 'ry-wc-city-select'),
	],
	'CHSAPR' => [
		_x('Amphoe Bang Bo', 'CHSAPR', 'ry-wc-city-select'),
		_x('Amphoe Bang Phli', 'CHSAPR', 'ry-wc-city-select'),
		_x('Amphoe Bang Sao Thong', 'CHSAPR', 'ry-wc-city-select'),
		_x('Amphoe Mueang Samut Prakan', 'CHSAPR', 'ry-wc-city-select'),
		_x('Amphoe Phra Pradaeng', 'CHSAPR', 'ry-wc-city-select'),
		_x('Amphoe Phra Samut Chedi', 'CHSAPR', 'ry-wc-city-select'),
	],
	'CHSASA' => [
		_x('Amphoe Ban Phaeo', 'CHSASA', 'ry-wc-city-select'),
		_x('Amphoe Krathum Baen', 'CHSASA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Samut Sakhon', 'CHSASA', 'ry-wc-city-select'),
	],
	'CHSASO' => [
		_x('Amphoe Amphawa', 'CHSASO', 'ry-wc-city-select'),
		_x('Amphoe Bang Khonthi', 'CHSASO', 'ry-wc-city-select'),
		_x('Amphoe Mueang Samut Songkhram', 'CHSASO', 'ry-wc-city-select'),
	],
	'CHSA' => [
		_x('Amphoe Ban Mo', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Chaloem Phra Kiat', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Don Phut', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Kaeng Khoi', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Muak Lek', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Sara Buri', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Nong Don', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Nong Khae', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Nong Saeng', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Phra Phutthabat', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Sao Hai', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Wang Muang', 'CHSA', 'ry-wc-city-select'),
		_x('Amphoe Wihan Daeng', 'CHSA', 'ry-wc-city-select'),
	],
	'CHSA2' => [
		_x('Amphoe Khuan Don', 'CHSA2', 'ry-wc-city-select'),
		_x('Amphoe Khuan Kalong', 'CHSA2', 'ry-wc-city-select'),
		_x('Amphoe La-Ngu', 'CHSA2', 'ry-wc-city-select'),
		_x('Amphoe Manang', 'CHSA2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Satun', 'CHSA2', 'ry-wc-city-select'),
		_x('Amphoe Tha Phae', 'CHSA2', 'ry-wc-city-select'),
		_x('Amphoe Thung Wa', 'CHSA2', 'ry-wc-city-select'),
	],
	'CHKE' => [
		_x('Amphoe Benchalak', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Bueng Bun', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Huai Thap Than', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Kantharalak', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Kanthararom', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Khukhan', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Khun Han', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Mueang Chan', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Mueang Sisaket', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Nam Kliang', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Non Khun', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Phayu', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Pho Si Suwan', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Phrai Bueng', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Phu Sing', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Prang Ku', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Rasi Salai', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Si Rattana', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Sila Lat', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Uthumphon Phisai', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Wang Hin', 'CHKE', 'ry-wc-city-select'),
		_x('Amphoe Yang Chum Noi', 'CHKE', 'ry-wc-city-select'),
	],
	'CHSIBU' => [
		_x('Amphoe Bang Rachan', 'CHSIBU', 'ry-wc-city-select'),
		_x('Amphoe In Buri', 'CHSIBU', 'ry-wc-city-select'),
		_x('Amphoe Khai Bang Rachan', 'CHSIBU', 'ry-wc-city-select'),
		_x('Amphoe Mueang Sing Buri', 'CHSIBU', 'ry-wc-city-select'),
		_x('Amphoe Phrom Buri', 'CHSIBU', 'ry-wc-city-select'),
		_x('Amphoe Tha Chang', 'CHSIBU', 'ry-wc-city-select'),
	],
	'CHSO' => [
		_x('Amphoe Bang Klam', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Chana', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Hat Yai', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Khlong Hoi Khong', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Khuan Niang', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Krasae Sin', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Mueang Songkhla', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Na Mom', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Na Thawi', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Ranot', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Rattaphum', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Saba Yoi', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Sadao', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Sathing Phra', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Singhanakhon', 'CHSO', 'ry-wc-city-select'),
		_x('Amphoe Thepha', 'CHSO', 'ry-wc-city-select'),
	],
	'CHSU' => [
		_x('Amphoe Ban Dan Lan Hoi', 'CHSU', 'ry-wc-city-select'),
		_x('Amphoe Khiri Mat', 'CHSU', 'ry-wc-city-select'),
		_x('Amphoe Kong Krailat', 'CHSU', 'ry-wc-city-select'),
		_x('Amphoe Mueang Sukhothai', 'CHSU', 'ry-wc-city-select'),
		_x('Amphoe Sawankhalok', 'CHSU', 'ry-wc-city-select'),
		_x('Amphoe Si Nakhon', 'CHSU', 'ry-wc-city-select'),
		_x('Amphoe Si Samrong', 'CHSU', 'ry-wc-city-select'),
		_x('Amphoe Si Satchanalai', 'CHSU', 'ry-wc-city-select'),
		_x('Amphoe Thung Saliam', 'CHSU', 'ry-wc-city-select'),
	],
	'CHSUBU' => [
		_x('Amphoe Bang Pla Ma', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe Dan Chang', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe Doembang Nangbuat', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe Don Chedi', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe Mueang Suphan Buri', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe Nong Yasai', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe Sam Chuk', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe Si Prachan', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe Song Phi Nong', 'CHSUBU', 'ry-wc-city-select'),
		_x('Amphoe U Thong', 'CHSUBU', 'ry-wc-city-select'),
	],
	'CHSUTH' => [
		_x('Amphoe Ban Na Doem', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Ban Na San', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Ban Takhun', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Chai Buri', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Chaiya', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Don Sak', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Kanchanadit', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Khian Sa', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Khiri Rat Nikhom', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Ko Pha-ngan', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Ko Samui', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Surat Thani', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Phanom', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Phrasaeng', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Phunphin', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Tha Chana', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Tha Chang', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Wiang Sa', 'CHSUTH', 'ry-wc-city-select'),
		_x('Amphoe Wiphawadi', 'CHSUTH', 'ry-wc-city-select'),
	],
	'CHSU2' => [
		_x('Amphoe Bua Chet', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Chom Phra', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Chumphon Buri', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Kap Choeng', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Khwao Sinarin', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Lamduan', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Surin', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Non Narai', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Phanom Dong Rak', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Prasat', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Rattanaburi', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Samrong Thap', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Sangkha', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Sanom', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Si Khoraphum', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Si Narong', 'CHSU2', 'ry-wc-city-select'),
		_x('Amphoe Tha Tum', 'CHSU2', 'ry-wc-city-select'),
	],
	'CHTA' => [
		_x('Amphoe Ban Tak', 'CHTA', 'ry-wc-city-select'),
		_x('Amphoe Mae Ramat', 'CHTA', 'ry-wc-city-select'),
		_x('Amphoe Mae Sot', 'CHTA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Tak', 'CHTA', 'ry-wc-city-select'),
		_x('Amphoe Phop Phra', 'CHTA', 'ry-wc-city-select'),
		_x('Amphoe Sam Ngao', 'CHTA', 'ry-wc-city-select'),
		_x('Amphoe Tha Song Yang', 'CHTA', 'ry-wc-city-select'),
		_x('Amphoe Umphang', 'CHTA', 'ry-wc-city-select'),
		_x('Amphoe Wang Chao', 'CHTA', 'ry-wc-city-select'),
	],
	'CHTR' => [
		_x('Amphoe Hat Samran', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Huai Yot', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Kantang', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Mueang Trang', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Na Yong', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Palian', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Ratsada', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Sikao', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Wang Wiset', 'CHTR', 'ry-wc-city-select'),
		_x('Amphoe Yan Ta Khao', 'CHTR', 'ry-wc-city-select'),
	],
	'CHTR2' => [
		_x('Amphoe Bo Rai', 'CHTR2', 'ry-wc-city-select'),
		_x('Amphoe Khao Saming', 'CHTR2', 'ry-wc-city-select'),
		_x('Amphoe Khlong Yai', 'CHTR2', 'ry-wc-city-select'),
		_x('Amphoe Ko Chang', 'CHTR2', 'ry-wc-city-select'),
		_x('Amphoe Ko Kut', 'CHTR2', 'ry-wc-city-select'),
		_x('Amphoe Laem Ngop', 'CHTR2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Trat', 'CHTR2', 'ry-wc-city-select'),
	],
	'CHUBRA' => [
		_x('Amphoe Buntharik', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Det Udom', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Don Mot Daeng', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Khemmarat', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Khong Chiam', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Khueang Nai', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Kut Khaopun', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Lao Suea Kok', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Muang Sam Sip', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Ubon Ratchathani', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Na Chaluai', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Na Tan', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Na Yia', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Nam Khun', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Nam Yuen', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Phibun Mangsahan', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Pho Sai', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Samrong', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Sawang Wirawong', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Si Mueang Mai', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Sirindhorn', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Tan Sum', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Thung Si Udom', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Trakan Phuet Phon', 'CHUBRA', 'ry-wc-city-select'),
		_x('Amphoe Warin Chamrap', 'CHUBRA', 'ry-wc-city-select'),
	],
	'CHUDTH' => [
		_x('Amphoe Ban Dung', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Ban Phue', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Chai Wan', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Ku Kaeo', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Kumphawapi', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Kut Chap', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Udon Thani', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Na Yung', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Nam Som', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Non Sa-at', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Nong Han', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Nong Saeng', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Nong Wua So', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Phen', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Phibun Rak', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Prachak Sinlapakhom', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Sang Khom', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Si That', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Thung Fon', 'CHUDTH', 'ry-wc-city-select'),
		_x('Amphoe Wang Sam Mo', 'CHUDTH', 'ry-wc-city-select'),
	],
	'CHUTTH' => [
		_x('Amphoe Ban Rai', 'CHUTTH', 'ry-wc-city-select'),
		_x('Amphoe Huai Khot', 'CHUTTH', 'ry-wc-city-select'),
		_x('Amphoe Lan Sak', 'CHUTTH', 'ry-wc-city-select'),
		_x('Amphoe Mueang Uthai Thani', 'CHUTTH', 'ry-wc-city-select'),
		_x('Amphoe Nong Chang', 'CHUTTH', 'ry-wc-city-select'),
		_x('Amphoe Nong Khayang', 'CHUTTH', 'ry-wc-city-select'),
		_x('Amphoe Sawang Arom', 'CHUTTH', 'ry-wc-city-select'),
		_x('Amphoe Thap Than', 'CHUTTH', 'ry-wc-city-select'),
	],
	'CHUT' => [
		_x('Amphoe Ban Khok', 'CHUT', 'ry-wc-city-select'),
		_x('Amphoe Fak Tha', 'CHUT', 'ry-wc-city-select'),
		_x('Amphoe Lap Lae', 'CHUT', 'ry-wc-city-select'),
		_x('Amphoe Mueang Uttaradit', 'CHUT', 'ry-wc-city-select'),
		_x('Amphoe Nam Pat', 'CHUT', 'ry-wc-city-select'),
		_x('Amphoe Phichai', 'CHUT', 'ry-wc-city-select'),
		_x('Amphoe Tha Pla', 'CHUT', 'ry-wc-city-select'),
		_x('Amphoe Thong Saen Khan', 'CHUT', 'ry-wc-city-select'),
		_x('Amphoe Tron', 'CHUT', 'ry-wc-city-select'),
	],
	'CHYA' => [
		_x('Amphoe Bannang Sata', 'CHYA', 'ry-wc-city-select'),
		_x('Amphoe Betong', 'CHYA', 'ry-wc-city-select'),
		_x('Amphoe Kabang', 'CHYA', 'ry-wc-city-select'),
		_x('Amphoe Krong Pinang', 'CHYA', 'ry-wc-city-select'),
		_x('Amphoe Mueang Yala', 'CHYA', 'ry-wc-city-select'),
		_x('Amphoe Raman', 'CHYA', 'ry-wc-city-select'),
		_x('Amphoe Than To', 'CHYA', 'ry-wc-city-select'),
		_x('Amphoe Yaha', 'CHYA', 'ry-wc-city-select'),
	],
	'CHYA2' => [
		_x('Amphoe Kham Khuan Kaeo', 'CHYA2', 'ry-wc-city-select'),
		_x('Amphoe Kho Wang', 'CHYA2', 'ry-wc-city-select'),
		_x('Amphoe Kut Chum', 'CHYA2', 'ry-wc-city-select'),
		_x('Amphoe Loeng Nok Tha', 'CHYA2', 'ry-wc-city-select'),
		_x('Amphoe Maha Chana Chai', 'CHYA2', 'ry-wc-city-select'),
		_x('Amphoe Mueang Yasothon', 'CHYA2', 'ry-wc-city-select'),
		_x('Amphoe Pa Tio', 'CHYA2', 'ry-wc-city-select'),
		_x('Amphoe Sai Mun', 'CHYA2', 'ry-wc-city-select'),
		_x('Amphoe Thai Charoen', 'CHYA2', 'ry-wc-city-select'),
	],
	'CHMAPR' => [
		_x('Amphoe Chai Prakan', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Chiang Dao', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Chom Thong', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Doi Lo', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Doi Saket', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Doi Tao', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Fang', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Galyani Vadhana', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Hang Dong', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Hot', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Mae Ai', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Mae Chaem', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Mae On', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Mae Rim', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Mae Taeng', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Mae Wang', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Mueang Chiang Mai', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Om Koi', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Phrao', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Samoeng', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe San Kamphaeng', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe San Pa Tong', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe San Sai', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Saraphi', 'CHMAPR', 'ry-wc-city-select'),
		_x('Amphoe Wiang Haeng', 'CHMAPR', 'ry-wc-city-select'),
	],
	'PHNAAY' => [
		_x('Amphoe Ban Phraek', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Bang Ban', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Bang Pa-in', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Bang Pahan', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Bang Sai', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Bang Sai', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Lat Bua Luang', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Maha Rat', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Nakhon Luang', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Phachi', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Phak Hai', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Phra Nakhon Si Ayutthaya', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Sena', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Tha Ruea', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Uthai', 'PHNAAY', 'ry-wc-city-select'),
		_x('Amphoe Wang Noi', 'PHNAAY', 'ry-wc-city-select'),
	],
	'PHPR' => [
		_x('Amphoe Kathu', 'PHPR', 'ry-wc-city-select'),
		_x('Amphoe Mueang Phuket', 'PHPR', 'ry-wc-city-select'),
		_x('Amphoe Thalang', 'PHPR', 'ry-wc-city-select'),
	],
	]
];