<?php
/**
 * Democratic Republic of Timor-Leste places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'TL' => [
	'AIVI' => [
		_x('Aisirimou', 'AIVI', 'ry-wc-city-select'),
		_x('Bandudato', 'AIVI', 'ry-wc-city-select'),
		_x('Fahiria', 'AIVI', 'ry-wc-city-select'),
		_x('Fatubosa', 'AIVI', 'ry-wc-city-select'),
		_x('Hoholau', 'AIVI', 'ry-wc-city-select'),
		_x('Lahae', 'AIVI', 'ry-wc-city-select'),
		_x('Lausi', 'AIVI', 'ry-wc-city-select'),
		_x('Saboria', 'AIVI', 'ry-wc-city-select'),
		_x('Seloi Craic', 'AIVI', 'ry-wc-city-select'),
		_x('Seloi Malere', 'AIVI', 'ry-wc-city-select'),
		_x('Suco Liurai', 'AIVI', 'ry-wc-city-select'),
	],
	'AL' => [
		_x('Aituha', 'AL', 'ry-wc-city-select'),
		_x('Dotic', 'AL', 'ry-wc-city-select'),
		_x('Mahaquidan', 'AL', 'ry-wc-city-select'),
		_x('Taitudac', 'AL', 'ry-wc-city-select'),
		_x('Uma Berloic', 'AL', 'ry-wc-city-select'),
	],
	'AT' => [
		_x('Aidabaleten', 'AT', 'ry-wc-city-select'),
		_x('Atabae', 'AT', 'ry-wc-city-select'),
		_x('Hataz', 'AT', 'ry-wc-city-select'),
		_x('Rairobo', 'AT', 'ry-wc-city-select'),
	],
	'ATIS' => [
		_x('Atauro Vila/Maumeta', 'ATIS', 'ry-wc-city-select'),
		_x('Beloi', 'ATIS', 'ry-wc-city-select'),
		_x('Biceli', 'ATIS', 'ry-wc-city-select'),
		_x('Macadade', 'ATIS', 'ry-wc-city-select'),
		_x('Maquili', 'ATIS', 'ry-wc-city-select'),
	],
	'AT2' => [
		_x('Atadame/Malabe', 'AT2', 'ry-wc-city-select'),
		_x('Atara', 'AT2', 'ry-wc-city-select'),
		_x('Baboi Craic', 'AT2', 'ry-wc-city-select'),
		_x('Batumanu', 'AT2', 'ry-wc-city-select'),
		_x('Beboi Leten', 'AT2', 'ry-wc-city-select'),
		_x('Laclo', 'AT2', 'ry-wc-city-select'),
		_x('Lasaun', 'AT2', 'ry-wc-city-select'),
		_x('Laubono', 'AT2', 'ry-wc-city-select'),
		_x('Leimea Leten', 'AT2', 'ry-wc-city-select'),
		_x('Obulo', 'AT2', 'ry-wc-city-select'),
		_x('Paramin', 'AT2', 'ry-wc-city-select'),
		_x('Tiarlelo', 'AT2', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Afaloicai', 'BA', 'ry-wc-city-select'),
		_x('Alaua Craic', 'BA', 'ry-wc-city-select'),
		_x('Alaua Leten', 'BA', 'ry-wc-city-select'),
		_x('Defa Uassi', 'BA', 'ry-wc-city-select'),
		_x('Haeconi', 'BA', 'ry-wc-city-select'),
		_x('Lari Sula', 'BA', 'ry-wc-city-select'),
		_x('Lavateri', 'BA', 'ry-wc-city-select'),
		_x('Ossu-Huna', 'BA', 'ry-wc-city-select'),
		_x('Samalari', 'BA', 'ry-wc-city-select'),
		_x('Uacala', 'BA', 'ry-wc-city-select'),
	],
	'BA2' => [
		_x('Balibo Vila', 'BA2', 'ry-wc-city-select'),
		_x('Batugade', 'BA2', 'ry-wc-city-select'),
		_x('Cowa', 'BA2', 'ry-wc-city-select'),
		_x('Leohito', 'BA2', 'ry-wc-city-select'),
		_x('Leolima', 'BA2', 'ry-wc-city-select'),
		_x('Sanirin', 'BA2', 'ry-wc-city-select'),
	],
	'BA3' => [
		_x('Abat Oan', 'BA3', 'ry-wc-city-select'),
		_x('Aubeon', 'BA3', 'ry-wc-city-select'),
		_x('Barique', 'BA3', 'ry-wc-city-select'),
		_x('Manehat', 'BA3', 'ry-wc-city-select'),
		_x('Uma Boco', 'BA3', 'ry-wc-city-select'),
	],
	'BA5' => [
		_x('Fahilebo', 'BA5', 'ry-wc-city-select'),
		_x('Fatumasi', 'BA5', 'ry-wc-city-select'),
		_x('Lauhata', 'BA5', 'ry-wc-city-select'),
		_x('Leorema', 'BA5', 'ry-wc-city-select'),
		_x('Maumeta', 'BA5', 'ry-wc-city-select'),
		_x('Metagou', 'BA5', 'ry-wc-city-select'),
		_x('Motaulun', 'BA5', 'ry-wc-city-select'),
		_x('Tibar', 'BA5', 'ry-wc-city-select'),
		_x('Ulmera', 'BA5', 'ry-wc-city-select'),
	],
	'CA' => [
		_x('Atudara', 'CA', 'ry-wc-city-select'),
		_x('Dau Udo', 'CA', 'ry-wc-city-select'),
		_x('Goulolo', 'CA', 'ry-wc-city-select'),
		_x('Guenu Lai', 'CA', 'ry-wc-city-select'),
		_x('Manapa', 'CA', 'ry-wc-city-select'),
		_x('Meligo', 'CA', 'ry-wc-city-select'),
		_x('Purugoa', 'CA', 'ry-wc-city-select'),
		_x('Raiheu', 'CA', 'ry-wc-city-select'),
	],
	'CRRE' => [
		_x('Balibar', 'CRRE', 'ry-wc-city-select'),
		_x('Becora', 'CRRE', 'ry-wc-city-select'),
		_x('Bidau Santana', 'CRRE', 'ry-wc-city-select'),
		_x('Camea', 'CRRE', 'ry-wc-city-select'),
		_x('Culu Hun', 'CRRE', 'ry-wc-city-select'),
		_x('Hera', 'CRRE', 'ry-wc-city-select'),
		_x('Meti Aut', 'CRRE', 'ry-wc-city-select'),
	],
	'DOAL' => [
		_x('Bairro Pite', 'DOAL', 'ry-wc-city-select'),
		_x('Comoro', 'DOAL', 'ry-wc-city-select'),
		_x('Fatuhada', 'DOAL', 'ry-wc-city-select'),
		_x('Kampung Alor', 'DOAL', 'ry-wc-city-select'),
	],
	'ERVI' => [
		_x('Estado', 'ERVI', 'ry-wc-city-select'),
		_x('Humboe', 'ERVI', 'ry-wc-city-select'),
		_x('Lauala', 'ERVI', 'ry-wc-city-select'),
		_x('Leguimea', 'ERVI', 'ry-wc-city-select'),
		_x('Mirtutu', 'ERVI', 'ry-wc-city-select'),
		_x('Poetete', 'ERVI', 'ry-wc-city-select'),
		_x('Ponilala', 'ERVI', 'ry-wc-city-select'),
		_x('Raimerhei', 'ERVI', 'ry-wc-city-select'),
		_x('Riheu', 'ERVI', 'ry-wc-city-select'),
		_x('Talimoro', 'ERVI', 'ry-wc-city-select'),
	],
	'FA' => [
		_x('Bubususo', 'FA', 'ry-wc-city-select'),
		_x('Caicasa', 'FA', 'ry-wc-city-select'),
		_x('Clacuc', 'FA', 'ry-wc-city-select'),
		_x('Fahinehan', 'FA', 'ry-wc-city-select'),
		_x('Fatucahi', 'FA', 'ry-wc-city-select'),
	],
	'FA2' => [
		_x('Fatululic', 'FA2', 'ry-wc-city-select'),
		_x('Taroman', 'FA2', 'ry-wc-city-select'),
	],
	'FA3' => [
		_x('Belulik Leten', 'FA3', 'ry-wc-city-select'),
		_x('Fatumea', 'FA3', 'ry-wc-city-select'),
		_x('Nanu', 'FA3', 'ry-wc-city-select'),
	],
	'FO' => [
		_x('Dato Rua', 'FO', 'ry-wc-city-select'),
		_x('Dato Tolu', 'FO', 'ry-wc-city-select'),
		_x('Fohoren', 'FO', 'ry-wc-city-select'),
		_x('Lactos', 'FO', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Foho-Ai-Lico', 'HA', 'ry-wc-city-select'),
		_x('Leolima', 'HA', 'ry-wc-city-select'),
	],
	'HA2' => [
		_x('Mau-Chiga', 'HA2', 'ry-wc-city-select'),
		_x('Mulo', 'HA2', 'ry-wc-city-select'),
		_x('Nuno-Mogue', 'HA2', 'ry-wc-city-select'),
	],
	'HA3' => [
		_x('Ailelo', 'HA3', 'ry-wc-city-select'),
		_x('Asulau', 'HA3', 'ry-wc-city-select'),
		_x('Coliate-Leotelo', 'HA3', 'ry-wc-city-select'),
		_x('Fatubolu', 'HA3', 'ry-wc-city-select'),
		_x('Fatuessi', 'HA3', 'ry-wc-city-select'),
		_x('Hatolia', 'HA3', 'ry-wc-city-select'),
		_x('Leimeacraic', 'HA3', 'ry-wc-city-select'),
		_x('Lemia Sorimbalu', 'HA3', 'ry-wc-city-select'),
		_x('Lissapat', 'HA3', 'ry-wc-city-select'),
		_x('Manusae', 'HA3', 'ry-wc-city-select'),
		_x('Mau-Ubu', 'HA3', 'ry-wc-city-select'),
		_x('Samara', 'HA3', 'ry-wc-city-select'),
		_x('Urahou', 'HA3', 'ry-wc-city-select'),
	],
	'IL' => [
		_x('Ailebere', 'IL', 'ry-wc-city-select'),
		_x('Cainliu', 'IL', 'ry-wc-city-select'),
		_x('Fuat', 'IL', 'ry-wc-city-select'),
		_x('Iliomar I', 'IL', 'ry-wc-city-select'),
		_x('Iliomar Ii', 'IL', 'ry-wc-city-select'),
		_x('Tirilolo', 'IL', 'ry-wc-city-select'),
	],
	'LA' => [
		_x('Hohorai', 'LA', 'ry-wc-city-select'),
		_x('Lacumesac', 'LA', 'ry-wc-city-select'),
		_x('Uma Naruc', 'LA', 'ry-wc-city-select'),
		_x('Umacaduac', 'LA', 'ry-wc-city-select'),
	],
	'LA2' => [
		_x('Batara', 'LA2', 'ry-wc-city-select'),
		_x('Fatumaquerec', 'LA2', 'ry-wc-city-select'),
		_x('Funar', 'LA2', 'ry-wc-city-select'),
		_x('Manelima', 'LA2', 'ry-wc-city-select'),
		_x('Orlalan', 'LA2', 'ry-wc-city-select'),
		_x('SananaIn', 'LA2', 'ry-wc-city-select'),
	],
	'LA3' => [
		_x('Ahic', 'LA3', 'ry-wc-city-select'),
		_x('Dilor', 'LA3', 'ry-wc-city-select'),
		_x('Laline', 'LA3', 'ry-wc-city-select'),
		_x('Uma Tolu', 'LA3', 'ry-wc-city-select'),
	],
	'LA4' => [
		_x('Atelari', 'LA4', 'ry-wc-city-select'),
		_x('Libagua', 'LA4', 'ry-wc-city-select'),
		_x('Nunira', 'LA4', 'ry-wc-city-select'),
		_x('Saelari', 'LA4', 'ry-wc-city-select'),
		_x('Sagadati', 'LA4', 'ry-wc-city-select'),
		_x('Samalari', 'LA4', 'ry-wc-city-select'),
		_x('Soba', 'LA4', 'ry-wc-city-select'),
		_x('Tequino Mata', 'LA4', 'ry-wc-city-select'),
	],
	'LA5' => [
		_x('Cairui', 'LA5', 'ry-wc-city-select'),
		_x('Haturalan', 'LA5', 'ry-wc-city-select'),
		_x('Lifau', 'LA5', 'ry-wc-city-select'),
	],
	'LA6' => [
		_x('Cotolau', 'LA6', 'ry-wc-city-select'),
		_x('Fatisi', 'LA6', 'ry-wc-city-select'),
		_x('Madabeno', 'LA6', 'ry-wc-city-select'),
		_x('Talitu', 'LA6', 'ry-wc-city-select'),
		_x('Tohumeta', 'LA6', 'ry-wc-city-select'),
	],
	'LA7' => [
		_x('Baduro', 'LA7', 'ry-wc-city-select'),
		_x('Com', 'LA7', 'ry-wc-city-select'),
		_x('Daudare', 'LA7', 'ry-wc-city-select'),
		_x('Euquisi', 'LA7', 'ry-wc-city-select'),
		_x('Ililai', 'LA7', 'ry-wc-city-select'),
		_x('Maina I', 'LA7', 'ry-wc-city-select'),
		_x('Maina Ii', 'LA7', 'ry-wc-city-select'),
		_x('Pairara', 'LA7', 'ry-wc-city-select'),
		_x('Parlamento', 'LA7', 'ry-wc-city-select'),
		_x('Serelau', 'LA7', 'ry-wc-city-select'),
	],
	'LE' => [
		_x('Acubilitoho', 'LE', 'ry-wc-city-select'),
		_x('Bereleu', 'LE', 'ry-wc-city-select'),
		_x('Betulau', 'LE', 'ry-wc-city-select'),
		_x('Fahisoi', 'LE', 'ry-wc-city-select'),
		_x('Faturilau', 'LE', 'ry-wc-city-select'),
		_x('Manucasa', 'LE', 'ry-wc-city-select'),
		_x('Namoleso', 'LE', 'ry-wc-city-select'),
	],
	'LE2' => [
		_x('Catrai Leten', 'LE2', 'ry-wc-city-select'),
		_x('Catrai-Craic', 'LE2', 'ry-wc-city-select'),
		_x('Ducurai', 'LE2', 'ry-wc-city-select'),
		_x('Eraulo', 'LE2', 'ry-wc-city-select'),
		_x('Goulolo', 'LE2', 'ry-wc-city-select'),
		_x('Hatugau', 'LE2', 'ry-wc-city-select'),
		_x('Haupu', 'LE2', 'ry-wc-city-select'),
		_x('Lauana', 'LE2', 'ry-wc-city-select'),
	],
	'LO' => [
		_x('Deudet', 'LO', 'ry-wc-city-select'),
		_x('Gildapil', 'LO', 'ry-wc-city-select'),
		_x('Guda', 'LO', 'ry-wc-city-select'),
		_x('Lebos', 'LO', 'ry-wc-city-select'),
		_x('Lontas', 'LO', 'ry-wc-city-select'),
		_x('Lupal', 'LO', 'ry-wc-city-select'),
		_x('Opa', 'LO', 'ry-wc-city-select'),
	],
	'LO2' => [
		_x('Bauro', 'LO2', 'ry-wc-city-select'),
		_x('Cacavem', 'LO2', 'ry-wc-city-select'),
		_x('Fuiloro', 'LO2', 'ry-wc-city-select'),
		_x('Home', 'LO2', 'ry-wc-city-select'),
		_x('Leuro', 'LO2', 'ry-wc-city-select'),
		_x('Lore I', 'LO2', 'ry-wc-city-select'),
		_x('Lore Ii', 'LO2', 'ry-wc-city-select'),
		_x('Muapitine', 'LO2', 'ry-wc-city-select'),
		_x('Raca', 'LO2', 'ry-wc-city-select'),
		_x('Souro', 'LO2', 'ry-wc-city-select'),
	],
	'LU' => [
		_x('Afabubu', 'LU', 'ry-wc-city-select'),
		_x('Baricafa', 'LU', 'ry-wc-city-select'),
		_x('Cotamutu', 'LU', 'ry-wc-city-select'),
		_x('Lacawa', 'LU', 'ry-wc-city-select'),
		_x('Luro', 'LU', 'ry-wc-city-select'),
		_x('Wairoce', 'LU', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Holsa', 'MA', 'ry-wc-city-select'),
		_x('Lahomea', 'MA', 'ry-wc-city-select'),
		_x('Odomau', 'MA', 'ry-wc-city-select'),
		_x('Raifun', 'MA', 'ry-wc-city-select'),
		_x('Ritabou', 'MA', 'ry-wc-city-select'),
		_x('Saburai', 'MA', 'ry-wc-city-select'),
		_x('Tapo/Memo', 'MA', 'ry-wc-city-select'),
	],
	'MA3' => [
		_x('Gugleur', 'MA3', 'ry-wc-city-select'),
		_x('Guico', 'MA3', 'ry-wc-city-select'),
		_x('Lissadila', 'MA3', 'ry-wc-city-select'),
		_x('Maubaralissa', 'MA3', 'ry-wc-city-select'),
		_x('Vatuboro', 'MA3', 'ry-wc-city-select'),
		_x('Vatuvou', 'MA3', 'ry-wc-city-select'),
		_x('Vaviquinia', 'MA3', 'ry-wc-city-select'),
	],
	'MA4' => [
		_x('Aitutu', 'MA4', 'ry-wc-city-select'),
		_x('Edi', 'MA4', 'ry-wc-city-select'),
		_x('Fatu-Besi', 'MA4', 'ry-wc-city-select'),
		_x('Horai-Quic', 'MA4', 'ry-wc-city-select'),
		_x('Manelobas', 'MA4', 'ry-wc-city-select'),
		_x('Manetu', 'MA4', 'ry-wc-city-select'),
		_x('Maubisse', 'MA4', 'ry-wc-city-select'),
		_x('Maulau', 'MA4', 'ry-wc-city-select'),
		_x('Suco Liurai', 'MA4', 'ry-wc-city-select'),
	],
	'MA5' => [
		_x('Belecasac', 'MA5', 'ry-wc-city-select'),
		_x('Holpilat', 'MA5', 'ry-wc-city-select'),
		_x('Matai', 'MA5', 'ry-wc-city-select'),
		_x('Ogues', 'MA5', 'ry-wc-city-select'),
	],
	'ME' => [
		_x('Duyung (Sereia)', 'ME', 'ry-wc-city-select'),
		_x('Sabuli', 'ME', 'ry-wc-city-select'),
	],
	'NAFE' => [
		_x('Acadiru Hun', 'NAFE', 'ry-wc-city-select'),
		_x('Bemori', 'NAFE', 'ry-wc-city-select'),
		_x('Bidau Lecidere', 'NAFE', 'ry-wc-city-select'),
		_x('Gricenfor', 'NAFE', 'ry-wc-city-select'),
		_x('Lahane Oriental', 'NAFE', 'ry-wc-city-select'),
		_x('Santa Cruz', 'NAFE', 'ry-wc-city-select'),
	],
	'NI' => [
		_x('Banafi', 'NI', 'ry-wc-city-select'),
		_x('Bene-Ufe', 'NI', 'ry-wc-city-select'),
		_x('Lela-Ufe', 'NI', 'ry-wc-city-select'),
		_x('Suni-Ufe', 'NI', 'ry-wc-city-select'),
		_x('Usi-Taco', 'NI', 'ry-wc-city-select'),
	],
	'OE' => [
		_x('Bobometo', 'OE', 'ry-wc-city-select'),
		_x('Usi-Tacae', 'OE', 'ry-wc-city-select'),
		_x('Usi-Taqueno', 'OE', 'ry-wc-city-select'),
	],
	'OS' => [
		_x('Builale', 'OS', 'ry-wc-city-select'),
		_x('Liaruca', 'OS', 'ry-wc-city-select'),
		_x('Loi-Huno', 'OS', 'ry-wc-city-select'),
		_x('Nahareca', 'OS', 'ry-wc-city-select'),
		_x('Ossorua', 'OS', 'ry-wc-city-select'),
		_x('Ossu De Cima', 'OS', 'ry-wc-city-select'),
		_x('Uabubo', 'OS', 'ry-wc-city-select'),
		_x('Uaibobo', 'OS', 'ry-wc-city-select'),
		_x('Uaigia', 'OS', 'ry-wc-city-select'),
	],
	'PAMA' => [
		_x('Bobocase', 'PAMA', 'ry-wc-city-select'),
		_x('Costa', 'PAMA', 'ry-wc-city-select'),
		_x('Cunha', 'PAMA', 'ry-wc-city-select'),
		_x('Lalisuc', 'PAMA', 'ry-wc-city-select'),
		_x('Lifau', 'PAMA', 'ry-wc-city-select'),
		_x('Naimeco', 'PAMA', 'ry-wc-city-select'),
		_x('Nipani', 'PAMA', 'ry-wc-city-select'),
		_x('Taiboco', 'PAMA', 'ry-wc-city-select'),
	],
	'PA' => [
		_x('Abani', 'PA', 'ry-wc-city-select'),
		_x('Malelat', 'PA', 'ry-wc-city-select'),
	],
	'QU' => [
		_x('Abafala', 'QU', 'ry-wc-city-select'),
		_x('Abo', 'QU', 'ry-wc-city-select'),
		_x('Afaca', 'QU', 'ry-wc-city-select'),
		_x('Baguia', 'QU', 'ry-wc-city-select'),
		_x('Bualale', 'QU', 'ry-wc-city-select'),
		_x('Guruca', 'QU', 'ry-wc-city-select'),
		_x('Laisorolai De Baixo', 'QU', 'ry-wc-city-select'),
		_x('Laisorolai De Cima', 'QU', 'ry-wc-city-select'),
		_x('Lelalai', 'QU', 'ry-wc-city-select'),
		_x('Letemuno', 'QU', 'ry-wc-city-select'),
		_x('Locoliu', 'QU', 'ry-wc-city-select'),
		_x('Macalaco', 'QU', 'ry-wc-city-select'),
		_x('Maluro', 'QU', 'ry-wc-city-select'),
		_x('Namanei', 'QU', 'ry-wc-city-select'),
		_x('Waitame', 'QU', 'ry-wc-city-select'),
	],
	'RA' => [
		_x('Deleco', 'RA', 'ry-wc-city-select'),
		_x('Fatuquero', 'RA', 'ry-wc-city-select'),
		_x('Lihu', 'RA', 'ry-wc-city-select'),
		_x('Matata', 'RA', 'ry-wc-city-select'),
		_x('Railaco Craic', 'RA', 'ry-wc-city-select'),
		_x('Railaco Leten', 'RA', 'ry-wc-city-select'),
		_x('Samalete', 'RA', 'ry-wc-city-select'),
		_x('Taraco', 'RA', 'ry-wc-city-select'),
		_x('Tocoluli', 'RA', 'ry-wc-city-select'),
	],
	'RE' => [
		_x('Acumau', 'RE', 'ry-wc-city-select'),
		_x('Fadabloco', 'RE', 'ry-wc-city-select'),
		_x('Fahisoi', 'RE', 'ry-wc-city-select'),
		_x('Faturasa', 'RE', 'ry-wc-city-select'),
		_x('Hautoho', 'RE', 'ry-wc-city-select'),
		_x('Maumeta', 'RE', 'ry-wc-city-select'),
		_x('Suco-Liurai', 'RE', 'ry-wc-city-select'),
		_x('Tulataqueo', 'RE', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Babulu', 'SA', 'ry-wc-city-select'),
		_x('Betano', 'SA', 'ry-wc-city-select'),
		_x('Daisua', 'SA', 'ry-wc-city-select'),
		_x('Grotu', 'SA', 'ry-wc-city-select'),
		_x('Holarua', 'SA', 'ry-wc-city-select'),
		_x('Letefoho', 'SA', 'ry-wc-city-select'),
		_x('Rotuto', 'SA', 'ry-wc-city-select'),
		_x('Tutuluro', 'SA', 'ry-wc-city-select'),
	],
	'SO' => [
		_x('Fatumacerec', 'SO', 'ry-wc-city-select'),
		_x('Leo Hat', 'SO', 'ry-wc-city-select'),
		_x('Manlala', 'SO', 'ry-wc-city-select'),
		_x('Manufahi', 'SO', 'ry-wc-city-select'),
		_x('Samoro', 'SO', 'ry-wc-city-select'),
	],
	'SU' => [
		_x('Beco', 'SU', 'ry-wc-city-select'),
		_x('Camenaca', 'SU', 'ry-wc-city-select'),
		_x('Debos', 'SU', 'ry-wc-city-select'),
		_x('Labarai', 'SU', 'ry-wc-city-select'),
		_x('Suai Loro', 'SU', 'ry-wc-city-select'),
	],
	'TI' => [
		_x('Casabauc', 'TI', 'ry-wc-city-select'),
		_x('Foholulic', 'TI', 'ry-wc-city-select'),
		_x('Lalawa', 'TI', 'ry-wc-city-select'),
		_x('Maudemo', 'TI', 'ry-wc-city-select'),
	],
	'TU' => [
		_x('Aitemua', 'TU', 'ry-wc-city-select'),
		_x('Beremana', 'TU', 'ry-wc-city-select'),
		_x('Caimauc', 'TU', 'ry-wc-city-select'),
		_x('Fatucalo', 'TU', 'ry-wc-city-select'),
		_x('Foholau', 'TU', 'ry-wc-city-select'),
		_x('Lesuata', 'TU', 'ry-wc-city-select'),
		_x('Liurai', 'TU', 'ry-wc-city-select'),
		_x('Manumera', 'TU', 'ry-wc-city-select'),
		_x('Matorec', 'TU', 'ry-wc-city-select'),
		_x('Mindelo', 'TU', 'ry-wc-city-select'),
		_x('Orana', 'TU', 'ry-wc-city-select'),
	],
	'TU2' => [
		_x('Mehara', 'TU2', 'ry-wc-city-select'),
		_x('Tutuala', 'TU2', 'ry-wc-city-select'),
	],
	'UA' => [
		_x('Afaloicai', 'UA', 'ry-wc-city-select'),
		_x('Bahatata', 'UA', 'ry-wc-city-select'),
		_x('Irabin De Baixo', 'UA', 'ry-wc-city-select'),
		_x('Irabin De Cima', 'UA', 'ry-wc-city-select'),
		_x('Loi Ulu', 'UA', 'ry-wc-city-select'),
		_x('Uani Uma', 'UA', 'ry-wc-city-select'),
	],
	'UA2' => [
		_x('Afaloicai', 'UA2', 'ry-wc-city-select'),
		_x('Babulo', 'UA2', 'ry-wc-city-select'),
		_x('Macadique', 'UA2', 'ry-wc-city-select'),
		_x('Matahoi', 'UA2', 'ry-wc-city-select'),
		_x('Uaitame', 'UA2', 'ry-wc-city-select'),
		_x('Vessoru', 'UA2', 'ry-wc-city-select'),
	],
	'VE' => [
		_x('Caicua', 'VE', 'ry-wc-city-select'),
		_x('Loilubo', 'VE', 'ry-wc-city-select'),
		_x('Ossoala', 'VE', 'ry-wc-city-select'),
		_x('Ostico', 'VE', 'ry-wc-city-select'),
		_x('Uaigae', 'VE', 'ry-wc-city-select'),
		_x('Uatu-Lari', 'VE', 'ry-wc-city-select'),
		_x('Vemase', 'VE', 'ry-wc-city-select'),
	],
	'VE2' => [
		_x('Bado HoO', 'VE2', 'ry-wc-city-select'),
		_x('Baha Mori', 'VE2', 'ry-wc-city-select'),
		_x('Fatulia', 'VE2', 'ry-wc-city-select'),
		_x('Uailaha', 'VE2', 'ry-wc-city-select'),
		_x('Uaiolo', 'VE2', 'ry-wc-city-select'),
		_x('Uataco', 'VE2', 'ry-wc-city-select'),
		_x('Uma Ana Ico', 'VE2', 'ry-wc-city-select'),
		_x('Uma Ana Ulu', 'VE2', 'ry-wc-city-select'),
	],
	'VECR' => [
		_x('Caicoli', 'VECR', 'ry-wc-city-select'),
		_x('Colmera', 'VECR', 'ry-wc-city-select'),
		_x('Dare', 'VECR', 'ry-wc-city-select'),
		_x('Lahane Ocidental', 'VECR', 'ry-wc-city-select'),
		_x('Macarenhas', 'VECR', 'ry-wc-city-select'),
		_x('Motael', 'VECR', 'ry-wc-city-select'),
		_x('Vila Verde', 'VECR', 'ry-wc-city-select'),
	],
	'ZU' => [
		_x('Fatuleto', 'ZU', 'ry-wc-city-select'),
		_x('Lepo', 'ZU', 'ry-wc-city-select'),
		_x('Lour', 'ZU', 'ry-wc-city-select'),
		_x('Mape', 'ZU', 'ry-wc-city-select'),
		_x('Raimea', 'ZU', 'ry-wc-city-select'),
		_x('Tashilin', 'ZU', 'ry-wc-city-select'),
		_x('Ucecai', 'ZU', 'ry-wc-city-select'),
		_x('Zulo', 'ZU', 'ry-wc-city-select'),
	],
	]
];