<?php
/**
 * Republic of Turkey places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'TR' => [
	'MIIL' => [
		_x('Gulluk Bucagi', 'MIIL', 'ry-wc-city-select'),
	],
	'SUIL' => [
		_x('Atca', 'SUIL', 'ry-wc-city-select'),
	],
	'AD' => [
		_x('Aladag', 'AD', 'ry-wc-city-select'),
		_x('Ceyhan', 'AD', 'ry-wc-city-select'),
		_x('Cukurova', 'AD', 'ry-wc-city-select'),
		_x('Feke', 'AD', 'ry-wc-city-select'),
		_x('Imamoglu', 'AD', 'ry-wc-city-select'),
		_x('Karaisali', 'AD', 'ry-wc-city-select'),
		_x('Karatas', 'AD', 'ry-wc-city-select'),
		_x('Kozan', 'AD', 'ry-wc-city-select'),
		_x('Pozanti', 'AD', 'ry-wc-city-select'),
		_x('Saimbeyli', 'AD', 'ry-wc-city-select'),
		_x('Saricam', 'AD', 'ry-wc-city-select'),
		_x('Seyhan', 'AD', 'ry-wc-city-select'),
		_x('Tufanbeyli', 'AD', 'ry-wc-city-select'),
		_x('Yueregir', 'AD', 'ry-wc-city-select'),
		_x('Yumurtalik', 'AD', 'ry-wc-city-select'),
	],
	'AD2' => [
		_x('Aralik Ilcesi', 'AD2', 'ry-wc-city-select'),
		_x('Besni Ilcesi', 'AD2', 'ry-wc-city-select'),
		_x('Celikhan Ilcesi', 'AD2', 'ry-wc-city-select'),
		_x('Gerger Ilcesi', 'AD2', 'ry-wc-city-select'),
		_x('Goelbasi Ilcesi', 'AD2', 'ry-wc-city-select'),
		_x('Kahta Ilcesi', 'AD2', 'ry-wc-city-select'),
		_x('Merkez', 'AD2', 'ry-wc-city-select'),
		_x('Samsat Ilcesi', 'AD2', 'ry-wc-city-select'),
		_x('Sincik Ilcesi', 'AD2', 'ry-wc-city-select'),
		_x('Tut Ilcesi', 'AD2', 'ry-wc-city-select'),
	],
	'AF' => [
		_x('Basmakci Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Bayat Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Bolvadin Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Cay Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Cobanlar Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Dazkiri Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Dinar Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Emirdag Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Evciler Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Hocalar Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Ihsaniye Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Iscehisar', 'AF', 'ry-wc-city-select'),
		_x('Kiziloeren Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Merkez', 'AF', 'ry-wc-city-select'),
		_x('Sandikli Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Sinanpasa Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Suhut Ilcesi', 'AF', 'ry-wc-city-select'),
		_x('Sultandagi Ilcesi', 'AF', 'ry-wc-city-select'),
	],
	'AG' => [
		_x('Agri', 'AG', 'ry-wc-city-select'),
		_x('Diyadin Ilcesi', 'AG', 'ry-wc-city-select'),
		_x('Dogubayazit Ilcesi', 'AG', 'ry-wc-city-select'),
		_x('Eleskirt Ilcesi', 'AG', 'ry-wc-city-select'),
		_x('Hamur Ilcesi', 'AG', 'ry-wc-city-select'),
		_x('Patnos Ilcesi', 'AG', 'ry-wc-city-select'),
		_x('Taslicay Ilcesi', 'AG', 'ry-wc-city-select'),
		_x('Tutak Ilcesi', 'AG', 'ry-wc-city-select'),
	],
	'AK' => [
		_x('Agacoeren Ilcesi', 'AK', 'ry-wc-city-select'),
		_x('Eskil Ilcesi', 'AK', 'ry-wc-city-select'),
		_x('Guelagac Ilcesi', 'AK', 'ry-wc-city-select'),
		_x('Guezelyurt Ilcesi', 'AK', 'ry-wc-city-select'),
		_x('Merkez', 'AK', 'ry-wc-city-select'),
		_x('Ortakoey Ilcesi', 'AK', 'ry-wc-city-select'),
		_x('Sariyahsi Ilcesi', 'AK', 'ry-wc-city-select'),
		_x('Sultanhani', 'AK', 'ry-wc-city-select'),
	],
	'AM' => [
		_x('Goeynuecek Ilcesi', 'AM', 'ry-wc-city-select'),
		_x('Guemueshacikoey Ilcesi', 'AM', 'ry-wc-city-select'),
		_x('Hamamoezue Ilcesi', 'AM', 'ry-wc-city-select'),
		_x('Merkez', 'AM', 'ry-wc-city-select'),
		_x('Merzifon Ilcesi', 'AM', 'ry-wc-city-select'),
		_x('Suluova Ilcesi', 'AM', 'ry-wc-city-select'),
		_x('Tasova Ilcesi', 'AM', 'ry-wc-city-select'),
	],
	'AN' => [
		_x('Akyurt Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Altindag', 'AN', 'ry-wc-city-select'),
		_x('Ayas Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Bala Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Beypazari', 'AN', 'ry-wc-city-select'),
		_x('Camlidere Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Cankaya', 'AN', 'ry-wc-city-select'),
		_x('Cubuk Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Elmadag Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Etimesgut Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Evren Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Goelbasi', 'AN', 'ry-wc-city-select'),
		_x('Gueduel Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Haymana Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Kahramankazan', 'AN', 'ry-wc-city-select'),
		_x('Kalecik Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Kazan Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Kecioeren', 'AN', 'ry-wc-city-select'),
		_x('Kizilcahamam Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Mamak Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Nallihan Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Polatli', 'AN', 'ry-wc-city-select'),
		_x('Pursaklar', 'AN', 'ry-wc-city-select'),
		_x('Sereflikochisar Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Sincan Ilcesi', 'AN', 'ry-wc-city-select'),
		_x('Yenimahalle', 'AN', 'ry-wc-city-select'),
	],
	'AN2' => [
		_x('Akseki Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Aksu', 'AN2', 'ry-wc-city-select'),
		_x('Alanya', 'AN2', 'ry-wc-city-select'),
		_x('Demre Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Doesemealti Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Elmali Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Finike', 'AN2', 'ry-wc-city-select'),
		_x('Gazipasa Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Guendogmus Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Ibradi Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Kas Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Kemer Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Kepez Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Konyaalti', 'AN2', 'ry-wc-city-select'),
		_x('Korkuteli Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Kumluca', 'AN2', 'ry-wc-city-select'),
		_x('Manavgat Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Merkez', 'AN2', 'ry-wc-city-select'),
		_x('Muratpasa Ilcesi', 'AN2', 'ry-wc-city-select'),
		_x('Serik', 'AN2', 'ry-wc-city-select'),
	],
	'AR' => [
		_x('Cildir Ilcesi', 'AR', 'ry-wc-city-select'),
		_x('Damal Ilcesi', 'AR', 'ry-wc-city-select'),
		_x('Goele Ilcesi', 'AR', 'ry-wc-city-select'),
		_x('Hanak Ilcesi', 'AR', 'ry-wc-city-select'),
		_x('Posof Ilcesi', 'AR', 'ry-wc-city-select'),
	],
	'AR2' => [
		_x('Ardanuc Ilcesi', 'AR2', 'ry-wc-city-select'),
		_x('Arhavi Ilcesi', 'AR2', 'ry-wc-city-select'),
		_x('Borcka Ilcesi', 'AR2', 'ry-wc-city-select'),
		_x('Hopa Ilcesi', 'AR2', 'ry-wc-city-select'),
		_x('Kemalpasa', 'AR2', 'ry-wc-city-select'),
		_x('Murgul Ilcesi', 'AR2', 'ry-wc-city-select'),
		_x('Savsat Ilcesi', 'AR2', 'ry-wc-city-select'),
		_x('Yusufeli Ilcesi', 'AR2', 'ry-wc-city-select'),
	],
	'AY' => [
		_x('Bozdogan Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Buharkent Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Cine Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Didim', 'AY', 'ry-wc-city-select'),
		_x('Efeler', 'AY', 'ry-wc-city-select'),
		_x('Germencik Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Incirliova Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Karacasu', 'AY', 'ry-wc-city-select'),
		_x('Karpuzlu Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Kocarli Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Koesk Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Kusadasi Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Kuyucak Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Nazilli', 'AY', 'ry-wc-city-select'),
		_x('Soeke Ilcesi', 'AY', 'ry-wc-city-select'),
		_x('Yenipazar Ilcesi', 'AY', 'ry-wc-city-select'),
	],
	'BA' => [
		_x('Altieyluel Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Ayvalik Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Balya Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Bandirma Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Bigadic Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Burhaniye Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Dursunbey Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Edremit Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Erdek Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Goenen Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Gomec Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Havran Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Ivrindi Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Karesi Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Kepsut Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Manyas Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Marmara Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Merkez', 'BA', 'ry-wc-city-select'),
		_x('Savastepe Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Sindirgi Ilcesi', 'BA', 'ry-wc-city-select'),
		_x('Susurluk Ilcesi', 'BA', 'ry-wc-city-select'),
	],
	'BA2' => [
		_x('Amasra Ilcesi', 'BA2', 'ry-wc-city-select'),
		_x('Kurucasile Ilcesi', 'BA2', 'ry-wc-city-select'),
		_x('Ulus Ilcesi', 'BA2', 'ry-wc-city-select'),
	],
	'BA3' => [
		_x('Besiri Ilcesi', 'BA3', 'ry-wc-city-select'),
		_x('Gercues Ilcesi', 'BA3', 'ry-wc-city-select'),
		_x('Hasankeyf Ilcesi', 'BA3', 'ry-wc-city-select'),
		_x('Kozluk Ilcesi', 'BA3', 'ry-wc-city-select'),
		_x('Merkez', 'BA3', 'ry-wc-city-select'),
		_x('Sason Ilcesi', 'BA3', 'ry-wc-city-select'),
	],
	'BA4' => [
		_x('Aydintepe Ilcesi', 'BA4', 'ry-wc-city-select'),
		_x('Demiroezue Ilcesi', 'BA4', 'ry-wc-city-select'),
	],
	'BI' => [
		_x('Bozueyuek Ilcesi', 'BI', 'ry-wc-city-select'),
		_x('Goelpazari Ilcesi', 'BI', 'ry-wc-city-select'),
		_x('Inhisar Ilcesi', 'BI', 'ry-wc-city-select'),
		_x('Osmaneli Ilcesi', 'BI', 'ry-wc-city-select'),
		_x('Pazaryeri Ilcesi', 'BI', 'ry-wc-city-select'),
		_x('Soeguet Ilcesi', 'BI', 'ry-wc-city-select'),
		_x('Yenipazar Ilcesi', 'BI', 'ry-wc-city-select'),
	],
	'BI2' => [
		_x('Adakli Ilcesi', 'BI2', 'ry-wc-city-select'),
		_x('Genc Ilcesi', 'BI2', 'ry-wc-city-select'),
		_x('Karliova Ilcesi', 'BI2', 'ry-wc-city-select'),
		_x('Kigi Ilcesi', 'BI2', 'ry-wc-city-select'),
		_x('Merkez', 'BI2', 'ry-wc-city-select'),
		_x('Solhan Ilcesi', 'BI2', 'ry-wc-city-select'),
		_x('Yayladere Ilcesi', 'BI2', 'ry-wc-city-select'),
		_x('Yedisu Ilcesi', 'BI2', 'ry-wc-city-select'),
	],
	'BI3' => [
		_x('Adilcevaz Ilcesi', 'BI3', 'ry-wc-city-select'),
		_x('Ahlat Ilcesi', 'BI3', 'ry-wc-city-select'),
		_x('Gueroymak Ilcesi', 'BI3', 'ry-wc-city-select'),
		_x('Hizan Ilcesi', 'BI3', 'ry-wc-city-select'),
		_x('Merkez', 'BI3', 'ry-wc-city-select'),
		_x('Mutki Ilcesi', 'BI3', 'ry-wc-city-select'),
		_x('Tatvan Ilcesi', 'BI3', 'ry-wc-city-select'),
	],
	'BO' => [
		_x('Doertdivan Ilcesi', 'BO', 'ry-wc-city-select'),
		_x('Gerede', 'BO', 'ry-wc-city-select'),
		_x('Goeynuek Ilcesi', 'BO', 'ry-wc-city-select'),
		_x('Kibriscik Ilcesi', 'BO', 'ry-wc-city-select'),
		_x('Mengen Ilcesi', 'BO', 'ry-wc-city-select'),
		_x('Mudurnu Ilcesi', 'BO', 'ry-wc-city-select'),
		_x('Seben Ilcesi', 'BO', 'ry-wc-city-select'),
		_x('Yenicaga Ilcesi', 'BO', 'ry-wc-city-select'),
	],
	'BU' => [
		_x('Aglasun Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Altinyayla Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Bucak Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Cavdir Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Celtikci Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Goelhisar Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Karamanli Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Kemer Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Merkez', 'BU', 'ry-wc-city-select'),
		_x('Tefenni Ilcesi', 'BU', 'ry-wc-city-select'),
		_x('Yesilova Ilcesi', 'BU', 'ry-wc-city-select'),
	],
	'BU2' => [
		_x('Bueyuekorhan Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Gemlik', 'BU2', 'ry-wc-city-select'),
		_x('Guersu', 'BU2', 'ry-wc-city-select'),
		_x('Harmancik Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Inegoel', 'BU2', 'ry-wc-city-select'),
		_x('Iznik Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Karacabey Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Keles Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Kestel Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Mudanya', 'BU2', 'ry-wc-city-select'),
		_x('Mustafakemalpasa Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Niluefer', 'BU2', 'ry-wc-city-select'),
		_x('Orhaneli Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Orhangazi Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Osmangazi', 'BU2', 'ry-wc-city-select'),
		_x('Yenisehir Ilcesi', 'BU2', 'ry-wc-city-select'),
		_x('Yildirim Ilcesi', 'BU2', 'ry-wc-city-select'),
	],
	'CA' => [
		_x('Ayvacik Ilcesi', 'CA', 'ry-wc-city-select'),
		_x('Bayramic Ilcesi', 'CA', 'ry-wc-city-select'),
		_x('Biga', 'CA', 'ry-wc-city-select'),
		_x('Bozcaada', 'CA', 'ry-wc-city-select'),
		_x('Can Ilcesi', 'CA', 'ry-wc-city-select'),
		_x('Eceabat', 'CA', 'ry-wc-city-select'),
		_x('Ezine Ilcesi', 'CA', 'ry-wc-city-select'),
		_x('Gelibolu Ilcesi', 'CA', 'ry-wc-city-select'),
		_x('Goekceada', 'CA', 'ry-wc-city-select'),
		_x('Lapseki Ilcesi', 'CA', 'ry-wc-city-select'),
		_x('Merkez', 'CA', 'ry-wc-city-select'),
		_x('Yenice Ilcesi', 'CA', 'ry-wc-city-select'),
	],
	'CA2' => [
		_x('Atkaracalar Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Bayramoeren Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Cerkes Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Eldivan Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Ilgaz Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Kizilirmak Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Korgun Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Kursunlu Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Orta Ilcesi', 'CA2', 'ry-wc-city-select'),
		_x('Sabanoezue', 'CA2', 'ry-wc-city-select'),
		_x('Yaprakli Ilcesi', 'CA2', 'ry-wc-city-select'),
	],
	'CO' => [
		_x('Alaca Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Bayat Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Bogazkale Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Dodurga Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Iskilip Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Kargi Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Lacin Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Mecitoezue Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Merkez', 'CO', 'ry-wc-city-select'),
		_x('Oguzlar Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Ortakoey Ilcesi', 'CO', 'ry-wc-city-select'),
		_x('Osmancik', 'CO', 'ry-wc-city-select'),
		_x('Sungurlu', 'CO', 'ry-wc-city-select'),
		_x('Ugurludag Ilcesi', 'CO', 'ry-wc-city-select'),
	],
	'DE' => [
		_x('Acipayam Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Babadag Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Baklan Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Bekilli', 'DE', 'ry-wc-city-select'),
		_x('Beyagac Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Bozkurt', 'DE', 'ry-wc-city-select'),
		_x('Buldan Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Cal Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Cameli Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Cardak', 'DE', 'ry-wc-city-select'),
		_x('Civril Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Gueney Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Honaz', 'DE', 'ry-wc-city-select'),
		_x('Kale Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Merkez', 'DE', 'ry-wc-city-select'),
		_x('Merkezefendi Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Pamukkale Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Saraykoey', 'DE', 'ry-wc-city-select'),
		_x('Serinhisar Ilcesi', 'DE', 'ry-wc-city-select'),
		_x('Tavas Ilcesi', 'DE', 'ry-wc-city-select'),
	],
	'DI' => [
		_x('Alacakaya Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Baglar', 'DI', 'ry-wc-city-select'),
		_x('Bismil Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Cermik Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Cinar Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Cuengues Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Dicle Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Egil Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Ergani Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Hani Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Hazro Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Kayapinar', 'DI', 'ry-wc-city-select'),
		_x('Kocakoey Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Kulp Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Lice Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Merkez', 'DI', 'ry-wc-city-select'),
		_x('Silvan Ilcesi', 'DI', 'ry-wc-city-select'),
		_x('Sur', 'DI', 'ry-wc-city-select'),
		_x('Yenisehir', 'DI', 'ry-wc-city-select'),
	],
	'DU' => [
		_x('Akcakoca Ilcesi', 'DU', 'ry-wc-city-select'),
		_x('Cilimli Ilcesi', 'DU', 'ry-wc-city-select'),
		_x('Cumayeri Ilcesi', 'DU', 'ry-wc-city-select'),
		_x('Goelyaka Ilcesi', 'DU', 'ry-wc-city-select'),
		_x('Guemuesova Ilcesi', 'DU', 'ry-wc-city-select'),
		_x('Kaynasli Ilcesi', 'DU', 'ry-wc-city-select'),
		_x('Yigilca Ilcesi', 'DU', 'ry-wc-city-select'),
	],
	'ED' => [
		_x('Enez Ilcesi', 'ED', 'ry-wc-city-select'),
		_x('Havsa Ilcesi', 'ED', 'ry-wc-city-select'),
		_x('Ipsala Ilcesi', 'ED', 'ry-wc-city-select'),
		_x('Kesan Ilcesi', 'ED', 'ry-wc-city-select'),
		_x('Lalapasa Ilcesi', 'ED', 'ry-wc-city-select'),
		_x('Meric Ilcesi', 'ED', 'ry-wc-city-select'),
		_x('Sueloglu Ilcesi', 'ED', 'ry-wc-city-select'),
		_x('Uzunkoeprue Ilcesi', 'ED', 'ry-wc-city-select'),
	],
	'EL' => [
		_x('Agin', 'EL', 'ry-wc-city-select'),
		_x('Aricak Ilcesi', 'EL', 'ry-wc-city-select'),
		_x('Baskil Ilcesi', 'EL', 'ry-wc-city-select'),
		_x('Karakocan / Elazig', 'EL', 'ry-wc-city-select'),
		_x('Keban Ilcesi', 'EL', 'ry-wc-city-select'),
		_x('Kovancilar Ilcesi', 'EL', 'ry-wc-city-select'),
		_x('Maden Ilcesi', 'EL', 'ry-wc-city-select'),
		_x('Merkez', 'EL', 'ry-wc-city-select'),
		_x('Palu Ilcesi', 'EL', 'ry-wc-city-select'),
		_x('Sivrice Ilcesi', 'EL', 'ry-wc-city-select'),
	],
	'ER' => [
		_x('Cayirli Ilcesi', 'ER', 'ry-wc-city-select'),
		_x('Ilic Ilcesi', 'ER', 'ry-wc-city-select'),
		_x('Kemah Ilcesi', 'ER', 'ry-wc-city-select'),
		_x('Kemaliye Ilcesi', 'ER', 'ry-wc-city-select'),
		_x('Otlukbeli Ilcesi', 'ER', 'ry-wc-city-select'),
		_x('Refahiye Ilcesi', 'ER', 'ry-wc-city-select'),
		_x('Tercan Ilcesi', 'ER', 'ry-wc-city-select'),
		_x('UEzuemlue Ilcesi', 'ER', 'ry-wc-city-select'),
	],
	'ER2' => [
		_x('Askale Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Aziziye', 'ER2', 'ry-wc-city-select'),
		_x('Cat Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Hinis Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Horasan Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Ispir Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Karacoban Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Karayazi Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Koepruekoey Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Narman Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Oltu Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Olur Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Palandoeken', 'ER2', 'ry-wc-city-select'),
		_x('Pasinler Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Pazaryolu Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Senkaya Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Tekman Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Tortum Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Uzundere Ilcesi', 'ER2', 'ry-wc-city-select'),
		_x('Yakutiye', 'ER2', 'ry-wc-city-select'),
	],
	'ES' => [
		_x('Alpu Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Beylikova Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Cifteler Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Guenyuezue Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Han Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Inoenuei Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Mahmudiye Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Merkez', 'ES', 'ry-wc-city-select'),
		_x('Mihalgazi Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Mihaliccik Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Odunpazari', 'ES', 'ry-wc-city-select'),
		_x('Saricakaya Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Seyitgazi Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Sivrihisar Ilcesi', 'ES', 'ry-wc-city-select'),
		_x('Tepebasi', 'ES', 'ry-wc-city-select'),
	],
	'GA' => [
		_x('Araban', 'GA', 'ry-wc-city-select'),
		_x('Islahiye Ilcesi', 'GA', 'ry-wc-city-select'),
		_x('Karkamis Ilcesi', 'GA', 'ry-wc-city-select'),
		_x('Nizip Ilcesi', 'GA', 'ry-wc-city-select'),
		_x('Nurdagi Ilcesi', 'GA', 'ry-wc-city-select'),
		_x('Oguzeli Ilcesi', 'GA', 'ry-wc-city-select'),
		_x('Sahinbey Ilcesi', 'GA', 'ry-wc-city-select'),
		_x('Sehitkamil', 'GA', 'ry-wc-city-select'),
		_x('Yavuzeli Ilcesi', 'GA', 'ry-wc-city-select'),
	],
	'GI' => [
		_x('Alucra Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Bulancak Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Camoluk Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Canakci', 'GI', 'ry-wc-city-select'),
		_x('Dereli', 'GI', 'ry-wc-city-select'),
		_x('Dogankent Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Espiye Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Eynesil Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Goerele Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Guece Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Kesap', 'GI', 'ry-wc-city-select'),
		_x('Merkez', 'GI', 'ry-wc-city-select'),
		_x('Sebin Karahisar Ilcesi', 'GI', 'ry-wc-city-select'),
		_x('Tirebolu', 'GI', 'ry-wc-city-select'),
		_x('Yaglidere Ilcesi', 'GI', 'ry-wc-city-select'),
	],
	'GU' => [
		_x('Kelkit Ilcesi', 'GU', 'ry-wc-city-select'),
		_x('Koese Ilcesi', 'GU', 'ry-wc-city-select'),
		_x('Kuertuen Ilcesi', 'GU', 'ry-wc-city-select'),
		_x('Merkez', 'GU', 'ry-wc-city-select'),
		_x('Siran Ilcesi', 'GU', 'ry-wc-city-select'),
		_x('Torul Ilcesi', 'GU', 'ry-wc-city-select'),
	],
	'HA' => [
		_x('Cukurca Ilcesi', 'HA', 'ry-wc-city-select'),
		_x('Semdinni Ilcesi', 'HA', 'ry-wc-city-select'),
		_x('Yueksekova', 'HA', 'ry-wc-city-select'),
	],
	'HA2' => [
		_x('Altinoezue Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Antakya Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Arsuz', 'HA2', 'ry-wc-city-select'),
		_x('Belen Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Defne', 'HA2', 'ry-wc-city-select'),
		_x('Doertyol Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Erzin Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Hassa Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Iskenderun Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Kirikhan Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Kumlu Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Payas', 'HA2', 'ry-wc-city-select'),
		_x('Reyhanli Ilcesi', 'HA2', 'ry-wc-city-select'),
		_x('Samandag', 'HA2', 'ry-wc-city-select'),
		_x('Yayladagi Ilcesi', 'HA2', 'ry-wc-city-select'),
	],
	'IG' => [
		_x('Karakoyunlu Ilcesi', 'IG', 'ry-wc-city-select'),
		_x('Tuzluca Ilcesi', 'IG', 'ry-wc-city-select'),
	],
	'IS' => [
		_x('Aksu Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Atabey Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Egirdir Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Gelendost Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Goenen Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Keciborlu Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Sarkikaraagac Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Senirkent Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Suetcueler Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Uluborlu Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Yalvac Ilcesi', 'IS', 'ry-wc-city-select'),
		_x('Yenisarbademli Ilcesi', 'IS', 'ry-wc-city-select'),
	],
	'IS2' => [
		_x('Adalar', 'IS2', 'ry-wc-city-select'),
		_x('Arnavutkoey', 'IS2', 'ry-wc-city-select'),
		_x('Atasehir', 'IS2', 'ry-wc-city-select'),
		_x('Avcilar', 'IS2', 'ry-wc-city-select'),
		_x('Bagcilar', 'IS2', 'ry-wc-city-select'),
		_x('Bahcelievler', 'IS2', 'ry-wc-city-select'),
		_x('Bakirkoey', 'IS2', 'ry-wc-city-select'),
		_x('Basaksehir', 'IS2', 'ry-wc-city-select'),
		_x('Bayrampasa', 'IS2', 'ry-wc-city-select'),
		_x('Besiktas', 'IS2', 'ry-wc-city-select'),
		_x('Beykoz', 'IS2', 'ry-wc-city-select'),
		_x('Beylikduezue', 'IS2', 'ry-wc-city-select'),
		_x('Beyoglu', 'IS2', 'ry-wc-city-select'),
		_x('Bueyuekcekmece', 'IS2', 'ry-wc-city-select'),
		_x('Catalca', 'IS2', 'ry-wc-city-select'),
		_x('Cekmekoey', 'IS2', 'ry-wc-city-select'),
		_x('Esenler', 'IS2', 'ry-wc-city-select'),
		_x('Esenyurt', 'IS2', 'ry-wc-city-select'),
		_x('Eyuepsultan', 'IS2', 'ry-wc-city-select'),
		_x('Fatih', 'IS2', 'ry-wc-city-select'),
		_x('Gaziosmanpasa', 'IS2', 'ry-wc-city-select'),
		_x('Guengoeren', 'IS2', 'ry-wc-city-select'),
		_x('Kadikoey', 'IS2', 'ry-wc-city-select'),
		_x('Kagithane', 'IS2', 'ry-wc-city-select'),
		_x('Kartal', 'IS2', 'ry-wc-city-select'),
		_x('Kuecuekcekmece', 'IS2', 'ry-wc-city-select'),
		_x('Maltepe', 'IS2', 'ry-wc-city-select'),
		_x('Pendik', 'IS2', 'ry-wc-city-select'),
		_x('Sancaktepe', 'IS2', 'ry-wc-city-select'),
		_x('Sariyer', 'IS2', 'ry-wc-city-select'),
		_x('Sile', 'IS2', 'ry-wc-city-select'),
		_x('Silivri', 'IS2', 'ry-wc-city-select'),
		_x('Sisli', 'IS2', 'ry-wc-city-select'),
		_x('Sultanbeyli', 'IS2', 'ry-wc-city-select'),
		_x('Sultangazi', 'IS2', 'ry-wc-city-select'),
		_x('Tuzla', 'IS2', 'ry-wc-city-select'),
		_x('UEmraniye', 'IS2', 'ry-wc-city-select'),
		_x('UEskuedar', 'IS2', 'ry-wc-city-select'),
		_x('Zeytinburnu', 'IS2', 'ry-wc-city-select'),
	],
	'IZ' => [
		_x('Aliaga', 'IZ', 'ry-wc-city-select'),
		_x('Balcova', 'IZ', 'ry-wc-city-select'),
		_x('Bayindir Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Bayrakli', 'IZ', 'ry-wc-city-select'),
		_x('Bergama', 'IZ', 'ry-wc-city-select'),
		_x('Beydag', 'IZ', 'ry-wc-city-select'),
		_x('Bornova', 'IZ', 'ry-wc-city-select'),
		_x('Buca', 'IZ', 'ry-wc-city-select'),
		_x('Cesme Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Cigli', 'IZ', 'ry-wc-city-select'),
		_x('Dikili Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Foca Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Gaziemir', 'IZ', 'ry-wc-city-select'),
		_x('Guezelbahce', 'IZ', 'ry-wc-city-select'),
		_x('Karabaglar', 'IZ', 'ry-wc-city-select'),
		_x('Karaburun Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Karsiyaka Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Kemalpasa', 'IZ', 'ry-wc-city-select'),
		_x('Kinik Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Kiraz Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Konak', 'IZ', 'ry-wc-city-select'),
		_x('Menderes', 'IZ', 'ry-wc-city-select'),
		_x('Menemen', 'IZ', 'ry-wc-city-select'),
		_x('Narlidere', 'IZ', 'ry-wc-city-select'),
		_x('OEdemis Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Seferihisar', 'IZ', 'ry-wc-city-select'),
		_x('Selcuk Ilcesi', 'IZ', 'ry-wc-city-select'),
		_x('Tire', 'IZ', 'ry-wc-city-select'),
		_x('Torbali', 'IZ', 'ry-wc-city-select'),
		_x('Urla Ilcesi', 'IZ', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Afsin Ilcesi', 'KA', 'ry-wc-city-select'),
		_x('Andirin Ilcesi', 'KA', 'ry-wc-city-select'),
		_x('Caglayancerit Ilcesi', 'KA', 'ry-wc-city-select'),
		_x('Dulkadiroglu', 'KA', 'ry-wc-city-select'),
		_x('Ekinoezue Ilcesi', 'KA', 'ry-wc-city-select'),
		_x('Elbistan Ilcesi', 'KA', 'ry-wc-city-select'),
		_x('Goeksun Ilcesi', 'KA', 'ry-wc-city-select'),
		_x('Merkez', 'KA', 'ry-wc-city-select'),
		_x('Nurhak Ilcesi', 'KA', 'ry-wc-city-select'),
		_x('Onikisubat', 'KA', 'ry-wc-city-select'),
		_x('Pazarcik Ilcesi', 'KA', 'ry-wc-city-select'),
		_x('Tuerkoglu Ilcesi', 'KA', 'ry-wc-city-select'),
	],
	'KA2' => [
		_x('Eflani Ilcesi', 'KA2', 'ry-wc-city-select'),
		_x('Eskipazar Ilcesi', 'KA2', 'ry-wc-city-select'),
		_x('Ovacik Ilcesi', 'KA2', 'ry-wc-city-select'),
		_x('Safranbolu Ilcesi', 'KA2', 'ry-wc-city-select'),
		_x('Yenice Ilcesi', 'KA2', 'ry-wc-city-select'),
	],
	'KA3' => [
		_x('Ayranci Ilcesi', 'KA3', 'ry-wc-city-select'),
		_x('Basyayla Ilcesi', 'KA3', 'ry-wc-city-select'),
		_x('Ermenek Ilcesi', 'KA3', 'ry-wc-city-select'),
		_x('Kazimkarabekir Ilcesi', 'KA3', 'ry-wc-city-select'),
		_x('Sariveliler Ilcesi', 'KA3', 'ry-wc-city-select'),
	],
	'KA4' => [
		_x('Akyaka Ilcesi', 'KA4', 'ry-wc-city-select'),
		_x('Arpacay Ilcesi', 'KA4', 'ry-wc-city-select'),
		_x('Digor Ilcesi', 'KA4', 'ry-wc-city-select'),
		_x('Kagizman Ilcesi', 'KA4', 'ry-wc-city-select'),
		_x('Sarikamis Ilcesi', 'KA4', 'ry-wc-city-select'),
		_x('Selim Ilcesi', 'KA4', 'ry-wc-city-select'),
		_x('Susuz Ilcesi', 'KA4', 'ry-wc-city-select'),
	],
	'KA5' => [
		_x('Abana Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Agli Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Arac Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Azdavay Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Bozkurt Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Catalzeytin Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Cide', 'KA5', 'ry-wc-city-select'),
		_x('Daday Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Devrekani Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Doganyurt Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Hanoenue Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Ihsangazi Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Inebolu Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Kuere Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Pinarbasi Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Senpazar Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Seydiler Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Taskoeprue Ilcesi', 'KA5', 'ry-wc-city-select'),
		_x('Tosya Ilcesi', 'KA5', 'ry-wc-city-select'),
	],
	'KA6' => [
		_x('Akkisla Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Buenyan Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Develi', 'KA6', 'ry-wc-city-select'),
		_x('Felahiye Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Hacilar Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Incesu', 'KA6', 'ry-wc-city-select'),
		_x('Kocasinan', 'KA6', 'ry-wc-city-select'),
		_x('Melikgazi', 'KA6', 'ry-wc-city-select'),
		_x('OEzvatan Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Pinarbasi Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Sarioglan Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Sariz Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Talas Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Tomarza Ilcesi', 'KA6', 'ry-wc-city-select'),
		_x('Yahyali', 'KA6', 'ry-wc-city-select'),
		_x('Yesilhisar', 'KA6', 'ry-wc-city-select'),
	],
	'KI' => [
		_x('Elbeyli Ilcesi', 'KI', 'ry-wc-city-select'),
		_x('Kilis Merkez', 'KI', 'ry-wc-city-select'),
		_x('Musabeyli Ilcesi', 'KI', 'ry-wc-city-select'),
		_x('Polateli Ilcesi', 'KI', 'ry-wc-city-select'),
	],
	'KI2' => [
		_x('Bahsili Ilcesi', 'KI2', 'ry-wc-city-select'),
		_x('Baliseyh Ilcesi', 'KI2', 'ry-wc-city-select'),
		_x('Celebi Ilcesi', 'KI2', 'ry-wc-city-select'),
		_x('Delice Ilcesi', 'KI2', 'ry-wc-city-select'),
		_x('Karakecili Ilcesi', 'KI2', 'ry-wc-city-select'),
		_x('Keskin Ilcesi', 'KI2', 'ry-wc-city-select'),
		_x('Sulakyurt Ilcesi', 'KI2', 'ry-wc-city-select'),
		_x('Yahsihan Ilcesi', 'KI2', 'ry-wc-city-select'),
	],
	'KI3' => [
		_x('Babaeski Ilcesi', 'KI3', 'ry-wc-city-select'),
		_x('Demirkoey Ilcesi', 'KI3', 'ry-wc-city-select'),
		_x('Kofcaz Ilcesi', 'KI3', 'ry-wc-city-select'),
		_x('Luleburgaz Ilcesi', 'KI3', 'ry-wc-city-select'),
		_x('Pehlivankoey Ilcesi', 'KI3', 'ry-wc-city-select'),
		_x('Pinarhisar Ilcesi', 'KI3', 'ry-wc-city-select'),
		_x('Vize Ilcesi', 'KI3', 'ry-wc-city-select'),
	],
	'KI4' => [
		_x('Akcakent Ilcesi', 'KI4', 'ry-wc-city-select'),
		_x('Akpinar Ilcesi', 'KI4', 'ry-wc-city-select'),
		_x('Boztepe Ilcesi', 'KI4', 'ry-wc-city-select'),
		_x('Cicekdagi Ilcesi', 'KI4', 'ry-wc-city-select'),
		_x('Kaman Ilcesi', 'KI4', 'ry-wc-city-select'),
		_x('Mucur Ilcesi', 'KI4', 'ry-wc-city-select'),
	],
	'KO' => [
		_x('Basiskele', 'KO', 'ry-wc-city-select'),
		_x('Cayirova', 'KO', 'ry-wc-city-select'),
		_x('Darica', 'KO', 'ry-wc-city-select'),
		_x('Derince Ilcesi', 'KO', 'ry-wc-city-select'),
		_x('Dilovasi', 'KO', 'ry-wc-city-select'),
		_x('Gebze', 'KO', 'ry-wc-city-select'),
		_x('Goelcuek Ilcesi', 'KO', 'ry-wc-city-select'),
		_x('Izmit', 'KO', 'ry-wc-city-select'),
		_x('Kandira Ilcesi', 'KO', 'ry-wc-city-select'),
		_x('Karamuersel Ilcesi', 'KO', 'ry-wc-city-select'),
		_x('Kartepe', 'KO', 'ry-wc-city-select'),
		_x('Koerfez Ilcesi', 'KO', 'ry-wc-city-select'),
		_x('Merkez', 'KO', 'ry-wc-city-select'),
	],
	'KO2' => [
		_x('Ahirli Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Akoeren Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Aksehir Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Altinekin Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Beysehir Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Bozkir Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Celtik Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Cihanbeyli District', 'KO2', 'ry-wc-city-select'),
		_x('Cumra Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Derbent Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Derebucak Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Doganhisar Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Emirgazi Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Eregli Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Gueneysinir Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Hadim Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Halkapinar Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Hueyuek Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Ilgin Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Kadinhani Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Karapinar Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Karatay', 'KO2', 'ry-wc-city-select'),
		_x('Kulu Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Meram Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Sarayoenue Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Selcuklu', 'KO2', 'ry-wc-city-select'),
		_x('Seydisehir Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Taskent Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Tuzlukcu Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Yalihueyuek Ilcesi', 'KO2', 'ry-wc-city-select'),
		_x('Yunak Ilcesi', 'KO2', 'ry-wc-city-select'),
	],
	'KU' => [
		_x('Altintas Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Aslanapa Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Cavdarhisar Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Domanic Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Dumlupinar Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Emet Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Gediz Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Hisarcik Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Pazarlar Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Saphane Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Simav Ilcesi', 'KU', 'ry-wc-city-select'),
		_x('Tavsanli Ilcesi', 'KU', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Akcadag Ilcesi', 'MA', 'ry-wc-city-select'),
		_x('Arapgir Ilcesi', 'MA', 'ry-wc-city-select'),
		_x('Arguvan', 'MA', 'ry-wc-city-select'),
		_x('Battalgazi', 'MA', 'ry-wc-city-select'),
		_x('Darende Ilcesi', 'MA', 'ry-wc-city-select'),
		_x('Dogansehir Ilcesi', 'MA', 'ry-wc-city-select'),
		_x('Doganyol', 'MA', 'ry-wc-city-select'),
		_x('Hekimhan Ilcesi', 'MA', 'ry-wc-city-select'),
		_x('Kale Ilcesi', 'MA', 'ry-wc-city-select'),
		_x('Kuluncak Ilcesi', 'MA', 'ry-wc-city-select'),
		_x('Merkez', 'MA', 'ry-wc-city-select'),
		_x('Puetuerge', 'MA', 'ry-wc-city-select'),
		_x('Yazihan Ilcesi', 'MA', 'ry-wc-city-select'),
		_x('Yesilyurt Ilcesi', 'MA', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('Ahmetli Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Akhisar Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Alasehir Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Demirci Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Goelmarmara Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Goerdes Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Kirkagac Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Koepruebasi Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Kula', 'MA2', 'ry-wc-city-select'),
		_x('Merkez', 'MA2', 'ry-wc-city-select'),
		_x('Salihli Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Sarigoel Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Saruhanli', 'MA2', 'ry-wc-city-select'),
		_x('Sehzadeler', 'MA2', 'ry-wc-city-select'),
		_x('Selendi Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Soma Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Turgutlu Ilcesi', 'MA2', 'ry-wc-city-select'),
		_x('Yunusemre', 'MA2', 'ry-wc-city-select'),
	],
	'MA3' => [
		_x('Artuklu', 'MA3', 'ry-wc-city-select'),
		_x('Dargecit Ilcesi', 'MA3', 'ry-wc-city-select'),
		_x('Derik Ilcesi', 'MA3', 'ry-wc-city-select'),
		_x('Kiziltepe Ilcesi', 'MA3', 'ry-wc-city-select'),
		_x('Mardin Merkez', 'MA3', 'ry-wc-city-select'),
		_x('Mazidagi Ilcesi', 'MA3', 'ry-wc-city-select'),
		_x('Midyat Ilcesi', 'MA3', 'ry-wc-city-select'),
		_x('Nusaybin Ilcesi', 'MA3', 'ry-wc-city-select'),
		_x('OEmerli Ilcesi', 'MA3', 'ry-wc-city-select'),
		_x('Savur Ilcesi', 'MA3', 'ry-wc-city-select'),
		_x('Yesilli Ilcesi', 'MA3', 'ry-wc-city-select'),
	],
	'ME' => [
		_x('Akdeniz', 'ME', 'ry-wc-city-select'),
		_x('Anamur Ilcesi', 'ME', 'ry-wc-city-select'),
		_x('Aydincik Ilcesi', 'ME', 'ry-wc-city-select'),
		_x('Bozyazi Ilcesi', 'ME', 'ry-wc-city-select'),
		_x('Camliyayla Ilcesi', 'ME', 'ry-wc-city-select'),
		_x('Erdemli Ilcesi', 'ME', 'ry-wc-city-select'),
		_x('Guelnar Ilcesi', 'ME', 'ry-wc-city-select'),
		_x('Mezitli Ilcesi', 'ME', 'ry-wc-city-select'),
		_x('Mut', 'ME', 'ry-wc-city-select'),
		_x('Silifke Ilcesi', 'ME', 'ry-wc-city-select'),
		_x('Tarsus', 'ME', 'ry-wc-city-select'),
		_x('Toroslar', 'ME', 'ry-wc-city-select'),
		_x('Yenisehir', 'ME', 'ry-wc-city-select'),
	],
	'MU' => [
		_x('Bodrum', 'MU', 'ry-wc-city-select'),
		_x('Dalaman', 'MU', 'ry-wc-city-select'),
		_x('Datca Ilcesi', 'MU', 'ry-wc-city-select'),
		_x('Fethiye', 'MU', 'ry-wc-city-select'),
		_x('Kavaklidere', 'MU', 'ry-wc-city-select'),
		_x('Koeycegiz Ilcesi', 'MU', 'ry-wc-city-select'),
		_x('Marmaris', 'MU', 'ry-wc-city-select'),
		_x('Mentese', 'MU', 'ry-wc-city-select'),
		_x('Ortaca Ilcesi', 'MU', 'ry-wc-city-select'),
		_x('Seydikemer', 'MU', 'ry-wc-city-select'),
		_x('Ula Ilcesi', 'MU', 'ry-wc-city-select'),
		_x('Yatagan', 'MU', 'ry-wc-city-select'),
	],
	'MU2' => [
		_x('Bulanik Ilcesi', 'MU2', 'ry-wc-city-select'),
		_x('Haskoey Ilcesi', 'MU2', 'ry-wc-city-select'),
		_x('Korkut Ilcesi', 'MU2', 'ry-wc-city-select'),
		_x('Malazgirt Ilcesi', 'MU2', 'ry-wc-city-select'),
		_x('Merkez', 'MU2', 'ry-wc-city-select'),
		_x('Varto Ilcesi', 'MU2', 'ry-wc-city-select'),
	],
	'NE' => [
		_x('Acigoel Ilcesi', 'NE', 'ry-wc-city-select'),
		_x('Avanos Ilcesi', 'NE', 'ry-wc-city-select'),
		_x('Derinkuyu Ilcesi', 'NE', 'ry-wc-city-select'),
		_x('Guelsehir Ilcesi', 'NE', 'ry-wc-city-select'),
		_x('Hacibektas Ilcesi', 'NE', 'ry-wc-city-select'),
		_x('Kozakli Ilcesi', 'NE', 'ry-wc-city-select'),
		_x('Merkez', 'NE', 'ry-wc-city-select'),
		_x('UErguep', 'NE', 'ry-wc-city-select'),
	],
	'NI' => [
		_x('Altunhisar Ilcesi', 'NI', 'ry-wc-city-select'),
		_x('Bor', 'NI', 'ry-wc-city-select'),
		_x('Camardi Ilcesi', 'NI', 'ry-wc-city-select'),
		_x('Ciftlik Ilcesi', 'NI', 'ry-wc-city-select'),
		_x('Merkez', 'NI', 'ry-wc-city-select'),
		_x('Ulukisla', 'NI', 'ry-wc-city-select'),
	],
	'OR' => [
		_x('Akkus', 'OR', 'ry-wc-city-select'),
		_x('Altinordu', 'OR', 'ry-wc-city-select'),
		_x('Aybasti Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Camas Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Catalpinar Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Caybasi Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Fatsa Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Goelkoey Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Guelyali Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Guergentepe Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Ikizce Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Kabaduez Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Kabatas Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Korgan Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Kumru Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Merkez', 'OR', 'ry-wc-city-select'),
		_x('Mesudiye Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Persembe Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Piraziz Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('UEnye Ilcesi', 'OR', 'ry-wc-city-select'),
		_x('Ulubey Ilcesi', 'OR', 'ry-wc-city-select'),
	],
	'OS' => [
		_x('Bahce Ilcesi', 'OS', 'ry-wc-city-select'),
		_x('Duezici Ilcesi', 'OS', 'ry-wc-city-select'),
		_x('Hasanbeyli Ilcesi', 'OS', 'ry-wc-city-select'),
		_x('Kadirli Ilcesi', 'OS', 'ry-wc-city-select'),
		_x('Sumbas Ilcesi', 'OS', 'ry-wc-city-select'),
		_x('Toprakkale', 'OS', 'ry-wc-city-select'),
	],
	'RI' => [
		_x('Ardesen', 'RI', 'ry-wc-city-select'),
		_x('Camlihemsin Ilcesi', 'RI', 'ry-wc-city-select'),
		_x('Cayeli', 'RI', 'ry-wc-city-select'),
		_x('Derepazari Ilcesi', 'RI', 'ry-wc-city-select'),
		_x('Findikli', 'RI', 'ry-wc-city-select'),
		_x('Gueneysu Ilcesi', 'RI', 'ry-wc-city-select'),
		_x('Hemsin Ilcesi', 'RI', 'ry-wc-city-select'),
		_x('Ikizdere Ilcesi', 'RI', 'ry-wc-city-select'),
		_x('Iyidere', 'RI', 'ry-wc-city-select'),
		_x('Kalkandere', 'RI', 'ry-wc-city-select'),
		_x('Pazar Ilcesi', 'RI', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Adapazari', 'SA', 'ry-wc-city-select'),
		_x('Akyazi Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Arifiye', 'SA', 'ry-wc-city-select'),
		_x('Erenler', 'SA', 'ry-wc-city-select'),
		_x('Ferizli Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Geyve Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Hendek Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Karapuercek Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Karasu Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Kaynarca Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Kocaali Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Merkez', 'SA', 'ry-wc-city-select'),
		_x('Pamukova Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Sapanca Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Serdivan', 'SA', 'ry-wc-city-select'),
		_x('Soeguetlue Ilcesi', 'SA', 'ry-wc-city-select'),
		_x('Tarakli Ilcesi', 'SA', 'ry-wc-city-select'),
	],
	'SA2' => [
		_x('Alacam Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Asarcik Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Atakum', 'SA2', 'ry-wc-city-select'),
		_x('Ayvacik Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Bafra', 'SA2', 'ry-wc-city-select'),
		_x('Canik', 'SA2', 'ry-wc-city-select'),
		_x('Carsamba Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Havza Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Ilkadim', 'SA2', 'ry-wc-city-select'),
		_x('Kavak Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Ladik Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Merkez', 'SA2', 'ry-wc-city-select'),
		_x('Ondokuzmayis Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Salipazari Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Tekkekoey', 'SA2', 'ry-wc-city-select'),
		_x('Terme Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Vezirkoeprue Ilcesi', 'SA2', 'ry-wc-city-select'),
		_x('Yakakent Ilcesi', 'SA2', 'ry-wc-city-select'),
	],
	'SA3' => [
		_x('Akcakale Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Birecik Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Bozova Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Ceylanpinar Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Eyyuebiye', 'SA3', 'ry-wc-city-select'),
		_x('Halfeti Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Haliliye', 'SA3', 'ry-wc-city-select'),
		_x('Harran Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Hilvan Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Karakoeprue', 'SA3', 'ry-wc-city-select'),
		_x('Merkez', 'SA3', 'ry-wc-city-select'),
		_x('Siverek Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Suruc Ilcesi', 'SA3', 'ry-wc-city-select'),
		_x('Viransehir Ilcesi', 'SA3', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Baykan Ilcesi', 'SI', 'ry-wc-city-select'),
		_x('Eruh Ilcesi', 'SI', 'ry-wc-city-select'),
		_x('Kurtalan Ilcesi', 'SI', 'ry-wc-city-select'),
		_x('Pervari Ilcesi', 'SI', 'ry-wc-city-select'),
		_x('Siirt Merkez', 'SI', 'ry-wc-city-select'),
		_x('Sirvan Ilcesi', 'SI', 'ry-wc-city-select'),
		_x('Tillo Ilcesi', 'SI', 'ry-wc-city-select'),
	],
	'SI2' => [
		_x('Ayancik', 'SI2', 'ry-wc-city-select'),
		_x('Boyabat Ilcesi', 'SI2', 'ry-wc-city-select'),
		_x('Dikmen Ilcesi', 'SI2', 'ry-wc-city-select'),
		_x('Duragan Ilcesi', 'SI2', 'ry-wc-city-select'),
		_x('Erfelek Ilcesi', 'SI2', 'ry-wc-city-select'),
		_x('Gerze Ilcesi', 'SI2', 'ry-wc-city-select'),
		_x('Merkez', 'SI2', 'ry-wc-city-select'),
		_x('Sarayduezue Ilcesi', 'SI2', 'ry-wc-city-select'),
		_x('Tuerkeli Ilcesi', 'SI2', 'ry-wc-city-select'),
	],
	'SI3' => [
		_x('Beytussebap', 'SI3', 'ry-wc-city-select'),
		_x('Cizre Ilcesi', 'SI3', 'ry-wc-city-select'),
		_x('Guecluekonak Ilcesi', 'SI3', 'ry-wc-city-select'),
		_x('Idil Ilcesi', 'SI3', 'ry-wc-city-select'),
		_x('Silopi Ilcesi', 'SI3', 'ry-wc-city-select'),
		_x('Sirnak Ilcesi', 'SI3', 'ry-wc-city-select'),
		_x('Uludere Ilcesi', 'SI3', 'ry-wc-city-select'),
	],
	'SI4' => [
		_x('Akincilar Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Altinyayla Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Divrigi Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Dogansar Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Gemerek Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Goelova Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Gueruen Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Hafik Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Imranli Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Kangal Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Koyulhisar Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Merkez', 'SI4', 'ry-wc-city-select'),
		_x('Sarkisla Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Susehri Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Ulas Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Yildizeli Ilcesi', 'SI4', 'ry-wc-city-select'),
		_x('Zara', 'SI4', 'ry-wc-city-select'),
	],
	'TE' => [
		_x('Cerkezkoey', 'TE', 'ry-wc-city-select'),
		_x('Corlu', 'TE', 'ry-wc-city-select'),
		_x('Ergene', 'TE', 'ry-wc-city-select'),
		_x('Hayrabolu Ilcesi', 'TE', 'ry-wc-city-select'),
		_x('Kapakli', 'TE', 'ry-wc-city-select'),
		_x('Malkara Ilcesi', 'TE', 'ry-wc-city-select'),
		_x('Marmara Ereglisi Ilcesi', 'TE', 'ry-wc-city-select'),
		_x('Muratli Ilcesi', 'TE', 'ry-wc-city-select'),
		_x('Saray Ilcesi', 'TE', 'ry-wc-city-select'),
		_x('Sarkoey Ilcesi', 'TE', 'ry-wc-city-select'),
		_x('Sueleymanpasa', 'TE', 'ry-wc-city-select'),
	],
	'TO' => [
		_x('Almus Ilcesi', 'TO', 'ry-wc-city-select'),
		_x('Artova Ilcesi', 'TO', 'ry-wc-city-select'),
		_x('Basciftlik Ilcesi', 'TO', 'ry-wc-city-select'),
		_x('Erbaa', 'TO', 'ry-wc-city-select'),
		_x('Niksar', 'TO', 'ry-wc-city-select'),
		_x('Pazar Ilcesi', 'TO', 'ry-wc-city-select'),
		_x('Resadiye', 'TO', 'ry-wc-city-select'),
		_x('Sulusaray Ilcesi', 'TO', 'ry-wc-city-select'),
		_x('Turhal Ilcesi', 'TO', 'ry-wc-city-select'),
		_x('Yesilyurt Ilcesi', 'TO', 'ry-wc-city-select'),
		_x('Zile Ilcesi', 'TO', 'ry-wc-city-select'),
	],
	'TR' => [
		_x('Akcaabat', 'TR', 'ry-wc-city-select'),
		_x('Arakli', 'TR', 'ry-wc-city-select'),
		_x('Arsin', 'TR', 'ry-wc-city-select'),
		_x('Besikduezue', 'TR', 'ry-wc-city-select'),
		_x('Carsibasi', 'TR', 'ry-wc-city-select'),
		_x('Caykara Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Dernekpazari Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Duezkoey Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Hayrat Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Koepruebasi Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Macka', 'TR', 'ry-wc-city-select'),
		_x('Merkez', 'TR', 'ry-wc-city-select'),
		_x('Of Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Ortahisar', 'TR', 'ry-wc-city-select'),
		_x('Salpazari Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Suermene Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Tonya Ilcesi', 'TR', 'ry-wc-city-select'),
		_x('Vakfikebir', 'TR', 'ry-wc-city-select'),
		_x('Yomra Ilcesi', 'TR', 'ry-wc-city-select'),
	],
	'TU' => [
		_x('Cemisgezek Ilcesi', 'TU', 'ry-wc-city-select'),
		_x('Hozat Ilcesi', 'TU', 'ry-wc-city-select'),
		_x('Mazgirt Ilcesi', 'TU', 'ry-wc-city-select'),
		_x('Merkez', 'TU', 'ry-wc-city-select'),
		_x('Nazimiye Ilcesi', 'TU', 'ry-wc-city-select'),
		_x('Ovacik Ilcesi', 'TU', 'ry-wc-city-select'),
		_x('Pertek Ilcesi', 'TU', 'ry-wc-city-select'),
		_x('Pueluemuer Ilcesi', 'TU', 'ry-wc-city-select'),
	],
	'US' => [
		_x('Banaz Ilcesi', 'US', 'ry-wc-city-select'),
		_x('Esme Ilcesi', 'US', 'ry-wc-city-select'),
		_x('Karahalli Ilcesi', 'US', 'ry-wc-city-select'),
		_x('Merkez', 'US', 'ry-wc-city-select'),
		_x('Sivasli Ilcesi', 'US', 'ry-wc-city-select'),
		_x('Ulubey', 'US', 'ry-wc-city-select'),
	],
	'VA' => [
		_x('Bahcesaray Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('Baskale Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('Caldiran Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('Catak Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('Edremit', 'VA', 'ry-wc-city-select'),
		_x('Ercis', 'VA', 'ry-wc-city-select'),
		_x('Gevas Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('Guerpinar Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('Ipekyolu', 'VA', 'ry-wc-city-select'),
		_x('Merkez', 'VA', 'ry-wc-city-select'),
		_x('Muradiye / Berkri', 'VA', 'ry-wc-city-select'),
		_x('Muradiye Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('OEzalp Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('Saray Ilcesi', 'VA', 'ry-wc-city-select'),
		_x('Tuspa', 'VA', 'ry-wc-city-select'),
	],
	'YA' => [
		_x('Altinova Ilcesi', 'YA', 'ry-wc-city-select'),
		_x('Armutlu Ilcesi', 'YA', 'ry-wc-city-select'),
		_x('Ciftlikkoey Ilcesi', 'YA', 'ry-wc-city-select'),
		_x('Cinarcik Ilcesi', 'YA', 'ry-wc-city-select'),
		_x('Merkez', 'YA', 'ry-wc-city-select'),
		_x('Termal Ilcesi', 'YA', 'ry-wc-city-select'),
	],
	'YO' => [
		_x('Akdagmadeni Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Aydincik Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Bogazliyan Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Candir Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Cayiralan Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Cekerek Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Kadisehri Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Saraykent Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Sarikaya', 'YO', 'ry-wc-city-select'),
		_x('Sefaatli Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Sorgun Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Yenifakili Ilcesi', 'YO', 'ry-wc-city-select'),
		_x('Yerkoey Ilcesi', 'YO', 'ry-wc-city-select'),
	],
	'ZO' => [
		_x('Alapli Ilcesi', 'ZO', 'ry-wc-city-select'),
		_x('Caycuma Ilcesi', 'ZO', 'ry-wc-city-select'),
		_x('Devrek Ilcesi', 'ZO', 'ry-wc-city-select'),
		_x('Eregli', 'ZO', 'ry-wc-city-select'),
		_x('Goekcebey Ilcesi', 'ZO', 'ry-wc-city-select'),
		_x('Kilimli', 'ZO', 'ry-wc-city-select'),
		_x('Kozlu', 'ZO', 'ry-wc-city-select'),
	],
	]
];