<?php
/**
 * Taiwan places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'TW' => [
	'CH' => [
		_x('Beidou Township', 'CH', 'ry-wc-city-select'),
		_x('Bitou Township', 'CH', 'ry-wc-city-select'),
		_x('Dacheng Township', 'CH', 'ry-wc-city-select'),
		_x('Dacun Township', 'CH', 'ry-wc-city-select'),
		_x('Erlin Township', 'CH', 'ry-wc-city-select'),
		_x('Ershui Township', 'CH', 'ry-wc-city-select'),
		_x('Fangyuan Township', 'CH', 'ry-wc-city-select'),
		_x('Fenyuan Township', 'CH', 'ry-wc-city-select'),
		_x('Fuxing Township', 'CH', 'ry-wc-city-select'),
		_x('Hemei Township', 'CH', 'ry-wc-city-select'),
		_x('Huatan Township', 'CH', 'ry-wc-city-select'),
		_x('Lugang Township', 'CH', 'ry-wc-city-select'),
		_x('Puxin Township', 'CH', 'ry-wc-city-select'),
		_x('Puyan Township', 'CH', 'ry-wc-city-select'),
		_x('Shengang Township', 'CH', 'ry-wc-city-select'),
		_x('Shetou Township', 'CH', 'ry-wc-city-select'),
		_x('Tianwei Township', 'CH', 'ry-wc-city-select'),
		_x('Tianzhong Township', 'CH', 'ry-wc-city-select'),
		_x('Xianxi Township', 'CH', 'ry-wc-city-select'),
		_x('Xihu Township', 'CH', 'ry-wc-city-select'),
		_x('Xiushui Township', 'CH', 'ry-wc-city-select'),
		_x('Xizhou Township', 'CH', 'ry-wc-city-select'),
		_x('Yongjing Township', 'CH', 'ry-wc-city-select'),
		_x('Yuanlin City', 'CH', 'ry-wc-city-select'),
		_x('Zhanghua City', 'CH', 'ry-wc-city-select'),
		_x('Zhutang Township', 'CH', 'ry-wc-city-select'),
	],
	'CH2' => [
		_x('E. District', 'CH2', 'ry-wc-city-select'),
		_x('W. District', 'CH2', 'ry-wc-city-select'),
	],
	'CHCO' => [
		_x('Alishan Township', 'CHCO', 'ry-wc-city-select'),
		_x('Budai Township', 'CHCO', 'ry-wc-city-select'),
		_x('Dalin Township', 'CHCO', 'ry-wc-city-select'),
		_x('Dapu Township', 'CHCO', 'ry-wc-city-select'),
		_x('Dongshi Township', 'CHCO', 'ry-wc-city-select'),
		_x('Fanlu Township', 'CHCO', 'ry-wc-city-select'),
		_x('Liujiao Township', 'CHCO', 'ry-wc-city-select'),
		_x('Lucao Township', 'CHCO', 'ry-wc-city-select'),
		_x('Meishan Township', 'CHCO', 'ry-wc-city-select'),
		_x('Minxueng Township', 'CHCO', 'ry-wc-city-select'),
		_x('Puzi City', 'CHCO', 'ry-wc-city-select'),
		_x('Shuishang Township', 'CHCO', 'ry-wc-city-select'),
		_x('Taibao City', 'CHCO', 'ry-wc-city-select'),
		_x('Xikou Township', 'CHCO', 'ry-wc-city-select'),
		_x('Xingang Township', 'CHCO', 'ry-wc-city-select'),
		_x('Yizhu Township', 'CHCO', 'ry-wc-city-select'),
		_x('Zhongpu Township', 'CHCO', 'ry-wc-city-select'),
		_x('Zhuqi Township', 'CHCO', 'ry-wc-city-select'),
	],
	'HS' => [
		_x('E. District', 'HS', 'ry-wc-city-select'),
		_x('N. District', 'HS', 'ry-wc-city-select'),
		_x('Xiangshan District', 'HS', 'ry-wc-city-select'),
	],
	'HSCO' => [
		_x('Baoshan Township', 'HSCO', 'ry-wc-city-select'),
		_x('Beipu Township', 'HSCO', 'ry-wc-city-select'),
		_x('Emei Township', 'HSCO', 'ry-wc-city-select'),
		_x('Guanxi Township', 'HSCO', 'ry-wc-city-select'),
		_x('Hengshan Township', 'HSCO', 'ry-wc-city-select'),
		_x('Hukou Township', 'HSCO', 'ry-wc-city-select'),
		_x('Jianshi Township', 'HSCO', 'ry-wc-city-select'),
		_x('Qionglin Township', 'HSCO', 'ry-wc-city-select'),
		_x('Wufeng Township', 'HSCO', 'ry-wc-city-select'),
		_x('Xinfeng Township', 'HSCO', 'ry-wc-city-select'),
		_x('Xinpu Township', 'HSCO', 'ry-wc-city-select'),
		_x('Zhubei City', 'HSCO', 'ry-wc-city-select'),
		_x('Zhudong Township', 'HSCO', 'ry-wc-city-select'),
	],
	'HU' => [
		_x('Fengbin Township', 'HU', 'ry-wc-city-select'),
		_x('Fenglin Township', 'HU', 'ry-wc-city-select'),
		_x('Fuli Township', 'HU', 'ry-wc-city-select'),
		_x('Guangfu Township', 'HU', 'ry-wc-city-select'),
		_x('Hualien City', 'HU', 'ry-wc-city-select'),
		_x('Jian Township', 'HU', 'ry-wc-city-select'),
		_x('Ruisui Township', 'HU', 'ry-wc-city-select'),
		_x('Shoufeng Township', 'HU', 'ry-wc-city-select'),
		_x('Wanrong Township', 'HU', 'ry-wc-city-select'),
		_x('Xincheng Township', 'HU', 'ry-wc-city-select'),
		_x('Xiulin Township', 'HU', 'ry-wc-city-select'),
		_x('Yuli Township', 'HU', 'ry-wc-city-select'),
		_x('Zhuoxi Township', 'HU', 'ry-wc-city-select'),
	],
	'KE' => [
		_x('Anle District', 'KE', 'ry-wc-city-select'),
		_x('Nuannuan District', 'KE', 'ry-wc-city-select'),
		_x('Qidu District', 'KE', 'ry-wc-city-select'),
		_x('Renai District', 'KE', 'ry-wc-city-select'),
		_x('Xinyi District', 'KE', 'ry-wc-city-select'),
		_x('Zhongshan District', 'KE', 'ry-wc-city-select'),
		_x('Zhongzheng District', 'KE', 'ry-wc-city-select'),
	],
	'KICO' => [
		_x('Jincheng Township', 'KICO', 'ry-wc-city-select'),
		_x('Jinhu Township', 'KICO', 'ry-wc-city-select'),
		_x('Jinning Township', 'KICO', 'ry-wc-city-select'),
		_x('Jinsha Township', 'KICO', 'ry-wc-city-select'),
		_x('Lieyu Township', 'KICO', 'ry-wc-city-select'),
		_x('Wuchiou Township', 'KICO', 'ry-wc-city-select'),
	],
	'LI' => [
		_x('Beigan Township', 'LI', 'ry-wc-city-select'),
		_x('Dongyin Township', 'LI', 'ry-wc-city-select'),
		_x('Juguang Township', 'LI', 'ry-wc-city-select'),
		_x('Nangan Township', 'LI', 'ry-wc-city-select'),
	],
	'MI' => [
		_x('Dahu Township', 'MI', 'ry-wc-city-select'),
		_x('Gongguan Township', 'MI', 'ry-wc-city-select'),
		_x('Houlong Township', 'MI', 'ry-wc-city-select'),
		_x('Miaoli City', 'MI', 'ry-wc-city-select'),
		_x('Nanzhuang Township', 'MI', 'ry-wc-city-select'),
		_x('Sanwan Township', 'MI', 'ry-wc-city-select'),
		_x('Sanyi Township', 'MI', 'ry-wc-city-select'),
		_x('Shitan Township', 'MI', 'ry-wc-city-select'),
		_x('Taian Township', 'MI', 'ry-wc-city-select'),
		_x('Tongluo Township', 'MI', 'ry-wc-city-select'),
		_x('Tongxiao Township', 'MI', 'ry-wc-city-select'),
		_x('Toufen City', 'MI', 'ry-wc-city-select'),
		_x('Touwu Township', 'MI', 'ry-wc-city-select'),
		_x('Xihu Township', 'MI', 'ry-wc-city-select'),
		_x('Yuanli Township', 'MI', 'ry-wc-city-select'),
		_x('Zaoqiao Township', 'MI', 'ry-wc-city-select'),
		_x('Zhunan Township', 'MI', 'ry-wc-city-select'),
		_x('Zhuolan Township', 'MI', 'ry-wc-city-select'),
	],
	'NA' => [
		_x('Caotun Township', 'NA', 'ry-wc-city-select'),
		_x('Guoxing Township', 'NA', 'ry-wc-city-select'),
		_x('Jiji Township', 'NA', 'ry-wc-city-select'),
		_x('Lugu Township', 'NA', 'ry-wc-city-select'),
		_x('Mingjian Township', 'NA', 'ry-wc-city-select'),
		_x('Nantou City', 'NA', 'ry-wc-city-select'),
		_x('Puli Township', 'NA', 'ry-wc-city-select'),
		_x('Renai Township', 'NA', 'ry-wc-city-select'),
		_x('Shuili Township', 'NA', 'ry-wc-city-select'),
		_x('Xinyi Township', 'NA', 'ry-wc-city-select'),
		_x('Yuchi Township', 'NA', 'ry-wc-city-select'),
		_x('Zhongliao Township', 'NA', 'ry-wc-city-select'),
		_x('Zhushan Township', 'NA', 'ry-wc-city-select'),
	],
	'PECO' => [
		_x('Baisha Township', 'PECO', 'ry-wc-city-select'),
		_x('Huxi Township', 'PECO', 'ry-wc-city-select'),
		_x('Magong City', 'PECO', 'ry-wc-city-select'),
		_x('Qimei Township', 'PECO', 'ry-wc-city-select'),
		_x('Wangan Township', 'PECO', 'ry-wc-city-select'),
		_x('Xiyu Township', 'PECO', 'ry-wc-city-select'),
	],
	'PI' => [
		_x('Changzhi Township', 'PI', 'ry-wc-city-select'),
		_x('Chaozhou Township', 'PI', 'ry-wc-city-select'),
		_x('Checheng Township', 'PI', 'ry-wc-city-select'),
		_x('Chunri Township', 'PI', 'ry-wc-city-select'),
		_x('Donggang Township', 'PI', 'ry-wc-city-select'),
		_x('Fangliao Township', 'PI', 'ry-wc-city-select'),
		_x('Fangshan Township', 'PI', 'ry-wc-city-select'),
		_x('Gaoshu Township', 'PI', 'ry-wc-city-select'),
		_x('Hengchun Township', 'PI', 'ry-wc-city-select'),
		_x('Jiadong Township', 'PI', 'ry-wc-city-select'),
		_x('Jiuru Township', 'PI', 'ry-wc-city-select'),
		_x('Kanding Township', 'PI', 'ry-wc-city-select'),
		_x('Laiyi Township', 'PI', 'ry-wc-city-select'),
		_x('Ligang Township', 'PI', 'ry-wc-city-select'),
		_x('Linbian Township', 'PI', 'ry-wc-city-select'),
		_x('Linluo Township', 'PI', 'ry-wc-city-select'),
		_x('Liuqiu Township', 'PI', 'ry-wc-city-select'),
		_x('Majia Township', 'PI', 'ry-wc-city-select'),
		_x('Manzhou Township', 'PI', 'ry-wc-city-select'),
		_x('Mudan Township', 'PI', 'ry-wc-city-select'),
		_x('Nanzhou Township', 'PI', 'ry-wc-city-select'),
		_x('Neipu Township', 'PI', 'ry-wc-city-select'),
		_x('Pingtung City', 'PI', 'ry-wc-city-select'),
		_x('Sandimen Township', 'PI', 'ry-wc-city-select'),
		_x('Shizi Township', 'PI', 'ry-wc-city-select'),
		_x('Taiwu Township', 'PI', 'ry-wc-city-select'),
		_x('Wandan Township', 'PI', 'ry-wc-city-select'),
		_x('Wanluan Township', 'PI', 'ry-wc-city-select'),
		_x('Wutai Township', 'PI', 'ry-wc-city-select'),
		_x('Xinbi Township', 'PI', 'ry-wc-city-select'),
		_x('Xinyuan Township', 'PI', 'ry-wc-city-select'),
		_x('Yanpu Township', 'PI', 'ry-wc-city-select'),
		_x('Zhutian Township', 'PI', 'ry-wc-city-select'),
	],
	'TACI' => [
		_x('Beitun District', 'TACI', 'ry-wc-city-select'),
		_x('Daan District', 'TACI', 'ry-wc-city-select'),
		_x('Dadu District', 'TACI', 'ry-wc-city-select'),
		_x('Dajia District', 'TACI', 'ry-wc-city-select'),
		_x('Dali District', 'TACI', 'ry-wc-city-select'),
		_x('Daya District', 'TACI', 'ry-wc-city-select'),
		_x('Dongshi District', 'TACI', 'ry-wc-city-select'),
		_x('E. District', 'TACI', 'ry-wc-city-select'),
		_x('Fengyuan District', 'TACI', 'ry-wc-city-select'),
		_x('Heping District', 'TACI', 'ry-wc-city-select'),
		_x('Houli District', 'TACI', 'ry-wc-city-select'),
		_x('Longjing District', 'TACI', 'ry-wc-city-select'),
		_x('N. District', 'TACI', 'ry-wc-city-select'),
		_x('Nantun District', 'TACI', 'ry-wc-city-select'),
		_x('Qingshui District', 'TACI', 'ry-wc-city-select'),
		_x('S. District', 'TACI', 'ry-wc-city-select'),
		_x('Shalu District', 'TACI', 'ry-wc-city-select'),
		_x('Shengang District', 'TACI', 'ry-wc-city-select'),
		_x('Shigang District', 'TACI', 'ry-wc-city-select'),
		_x('Taiping District', 'TACI', 'ry-wc-city-select'),
		_x('Tanzi District', 'TACI', 'ry-wc-city-select'),
		_x('W. District', 'TACI', 'ry-wc-city-select'),
		_x('Waipu District', 'TACI', 'ry-wc-city-select'),
		_x('Wufeng District', 'TACI', 'ry-wc-city-select'),
		_x('Wuqi District', 'TACI', 'ry-wc-city-select'),
		_x('Wuri District', 'TACI', 'ry-wc-city-select'),
		_x('Xinshe District', 'TACI', 'ry-wc-city-select'),
		_x('Xitun District', 'TACI', 'ry-wc-city-select'),
		_x('Zhong District', 'TACI', 'ry-wc-city-select'),
	],
	'TA' => [
		_x('Anding District', 'TA', 'ry-wc-city-select'),
		_x('Annan District', 'TA', 'ry-wc-city-select'),
		_x('Anping District', 'TA', 'ry-wc-city-select'),
		_x('Baihe District', 'TA', 'ry-wc-city-select'),
		_x('Beimen District', 'TA', 'ry-wc-city-select'),
		_x('Danei District', 'TA', 'ry-wc-city-select'),
		_x('Dongshan District', 'TA', 'ry-wc-city-select'),
		_x('E. District', 'TA', 'ry-wc-city-select'),
		_x('Guanmiao District', 'TA', 'ry-wc-city-select'),
		_x('Guantian District', 'TA', 'ry-wc-city-select'),
		_x('Guiren District', 'TA', 'ry-wc-city-select'),
		_x('Houbi District', 'TA', 'ry-wc-city-select'),
		_x('Jiali District', 'TA', 'ry-wc-city-select'),
		_x('Jiangjun District', 'TA', 'ry-wc-city-select'),
		_x('Liujia District', 'TA', 'ry-wc-city-select'),
		_x('Liuying District', 'TA', 'ry-wc-city-select'),
		_x('Longqi District', 'TA', 'ry-wc-city-select'),
		_x('Madou District', 'TA', 'ry-wc-city-select'),
		_x('N. District', 'TA', 'ry-wc-city-select'),
		_x('Nanhua District', 'TA', 'ry-wc-city-select'),
		_x('Nanxi District', 'TA', 'ry-wc-city-select'),
		_x('Qigu District', 'TA', 'ry-wc-city-select'),
		_x('Rende District', 'TA', 'ry-wc-city-select'),
		_x('S. District', 'TA', 'ry-wc-city-select'),
		_x('Shanhua District', 'TA', 'ry-wc-city-select'),
		_x('Shanshang District', 'TA', 'ry-wc-city-select'),
		_x('Xiaying District', 'TA', 'ry-wc-city-select'),
		_x('Xigang District', 'TA', 'ry-wc-city-select'),
		_x('Xinhua District', 'TA', 'ry-wc-city-select'),
		_x('Xinshi District', 'TA', 'ry-wc-city-select'),
		_x('Xinying District', 'TA', 'ry-wc-city-select'),
		_x('Xuejia District', 'TA', 'ry-wc-city-select'),
		_x('Yanshui District', 'TA', 'ry-wc-city-select'),
		_x('Yongkang District', 'TA', 'ry-wc-city-select'),
		_x('Yujing District', 'TA', 'ry-wc-city-select'),
		_x('Zhongxi District', 'TA', 'ry-wc-city-select'),
		_x('Zuozhen District', 'TA', 'ry-wc-city-select'),
	],
	'TACI2' => [
		_x('Beitou District', 'TACI2', 'ry-wc-city-select'),
		_x('Daan District', 'TACI2', 'ry-wc-city-select'),
		_x('Datong District', 'TACI2', 'ry-wc-city-select'),
		_x('Nangang District', 'TACI2', 'ry-wc-city-select'),
		_x('Neihu District', 'TACI2', 'ry-wc-city-select'),
		_x('Shilin District', 'TACI2', 'ry-wc-city-select'),
		_x('Songshan District', 'TACI2', 'ry-wc-city-select'),
		_x('Wanhua District', 'TACI2', 'ry-wc-city-select'),
		_x('Wenshan District', 'TACI2', 'ry-wc-city-select'),
		_x('Xinyi District', 'TACI2', 'ry-wc-city-select'),
		_x('Zhongshan District', 'TACI2', 'ry-wc-city-select'),
		_x('Zhongzheng District', 'TACI2', 'ry-wc-city-select'),
	],
	'TA3' => [
		_x('Beinan Township', 'TA3', 'ry-wc-city-select'),
		_x('Changbin Township', 'TA3', 'ry-wc-city-select'),
		_x('Chenggong Township', 'TA3', 'ry-wc-city-select'),
		_x('Chishang Township', 'TA3', 'ry-wc-city-select'),
		_x('Daren Township', 'TA3', 'ry-wc-city-select'),
		_x('Dawu Township', 'TA3', 'ry-wc-city-select'),
		_x('Donghe Township', 'TA3', 'ry-wc-city-select'),
		_x('Guanshan Township', 'TA3', 'ry-wc-city-select'),
		_x('Haiduan Township', 'TA3', 'ry-wc-city-select'),
		_x('Jinfeng Township', 'TA3', 'ry-wc-city-select'),
		_x('Lanyu Township', 'TA3', 'ry-wc-city-select'),
		_x('Luye Township', 'TA3', 'ry-wc-city-select'),
		_x('Lvdao Township', 'TA3', 'ry-wc-city-select'),
		_x('Taimali Township', 'TA3', 'ry-wc-city-select'),
		_x('Taitung City', 'TA3', 'ry-wc-city-select'),
		_x('Yanping Township', 'TA3', 'ry-wc-city-select'),
	],
	'TA4' => [
		_x('Bade District', 'TA4', 'ry-wc-city-select'),
		_x('Daxi District', 'TA4', 'ry-wc-city-select'),
		_x('Dayuan District', 'TA4', 'ry-wc-city-select'),
		_x('Fuxing District', 'TA4', 'ry-wc-city-select'),
		_x('Guanyin District', 'TA4', 'ry-wc-city-select'),
		_x('Guishan District', 'TA4', 'ry-wc-city-select'),
		_x('Longtan District', 'TA4', 'ry-wc-city-select'),
		_x('Luzhu District', 'TA4', 'ry-wc-city-select'),
		_x('Pingzhen District', 'TA4', 'ry-wc-city-select'),
		_x('Taoyuan District', 'TA4', 'ry-wc-city-select'),
		_x('Xinwu District', 'TA4', 'ry-wc-city-select'),
		_x('Yangmei District', 'TA4', 'ry-wc-city-select'),
		_x('Zhongli District', 'TA4', 'ry-wc-city-select'),
	],
	'YI' => [
		_x('Datong Township', 'YI', 'ry-wc-city-select'),
		_x('Dongshan Township', 'YI', 'ry-wc-city-select'),
		_x('Jiaoxi Township', 'YI', 'ry-wc-city-select'),
		_x('Luodong Township', 'YI', 'ry-wc-city-select'),
		_x('Nanao Township', 'YI', 'ry-wc-city-select'),
		_x('Sanxing Township', 'YI', 'ry-wc-city-select'),
		_x('Suao Township', 'YI', 'ry-wc-city-select'),
		_x('Toucheng Township', 'YI', 'ry-wc-city-select'),
		_x('Wujie Township', 'YI', 'ry-wc-city-select'),
		_x('Yilan City', 'YI', 'ry-wc-city-select'),
		_x('Yuanshan Township', 'YI', 'ry-wc-city-select'),
		_x('Zhuangwei Township', 'YI', 'ry-wc-city-select'),
	],
	'YU' => [
		_x('Baozhong Township', 'YU', 'ry-wc-city-select'),
		_x('Beigang Township', 'YU', 'ry-wc-city-select'),
		_x('Citong Township', 'YU', 'ry-wc-city-select'),
		_x('Dabi Township', 'YU', 'ry-wc-city-select'),
		_x('Dongshi Township', 'YU', 'ry-wc-city-select'),
		_x('Douliu City', 'YU', 'ry-wc-city-select'),
		_x('Dounan Township', 'YU', 'ry-wc-city-select'),
		_x('Erlun Township', 'YU', 'ry-wc-city-select'),
		_x('Gukeng Township', 'YU', 'ry-wc-city-select'),
		_x('Huwei Township', 'YU', 'ry-wc-city-select'),
		_x('Kouhu Township', 'YU', 'ry-wc-city-select'),
		_x('Linnei Township', 'YU', 'ry-wc-city-select'),
		_x('Lunbei Township', 'YU', 'ry-wc-city-select'),
		_x('Mailiao Township', 'YU', 'ry-wc-city-select'),
		_x('Shuilin Township', 'YU', 'ry-wc-city-select'),
		_x('Sihu Township', 'YU', 'ry-wc-city-select'),
		_x('Taixi Township', 'YU', 'ry-wc-city-select'),
		_x('Tuku Township', 'YU', 'ry-wc-city-select'),
		_x('Xiluo Township', 'YU', 'ry-wc-city-select'),
		_x('Yuanchang Township', 'YU', 'ry-wc-city-select'),
	],
	]
];