<?php
/**
 * Ukraine places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'UA' => [
	'BARA' => [
		_x('Aromatnenskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Dolinnenskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Golubinskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Gorodskoye poselenye Bakhchisaray', 'BARA', 'ry-wc-city-select'),
		_x('Kashtanovskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Krasnomakskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Kuibyshevskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Peschanovskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Plodovskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Pochtovskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Skalistovskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Tabachnenskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Tenistovskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Uglovskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Verkhorechenskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Vilinskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Zelenovskoye selskoye poselenye', 'BARA', 'ry-wc-city-select'),
		_x('Zheleznodorozhnenskoye selskoye poselen', 'BARA', 'ry-wc-city-select'),
	],
	'BADI' => [
		_x('Balaklavskiy munitsipalniy okrug', 'BADI', 'ry-wc-city-select'),
		_x('Gorod Inkerman', 'BADI', 'ry-wc-city-select'),
		_x('Orlinovskiy munitsipalniy okrug', 'BADI', 'ry-wc-city-select'),
		_x('Ternovskiy munitsipalniy okrug', 'BADI', 'ry-wc-city-select'),
	],
	'BARA2' => [
		_x('Baranivka Town United Territorial Commun', 'BARA2', 'ry-wc-city-select'),
	],
	'BERA' => [
		_x('Aromatnovskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Bogatovskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Chernopolskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Gorodskoye poselenye Belogorsk', 'BERA', 'ry-wc-city-select'),
		_x('Krinichnenskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Krymskorozovskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Kurskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Melnichnoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Michurinskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Muromskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Novozhilovskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Rusakovskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Tsvetochnenskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Vasilyevskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Vishenskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Zelenogorskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Zemlyanichnenskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Zuyskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
		_x('Zybinskoye selskoye poselenye', 'BERA', 'ry-wc-city-select'),
	],
	'BIRA' => [
		_x('Bilhorod-Dnistrovskyy City Raion', 'BIRA', 'ry-wc-city-select'),
	],
	'CHRA' => [
		_x('Chernihivka United Territorial Community', 'CHRA', 'ry-wc-city-select'),
	],
	'CHMU' => [
		_x('Sadhirskyy Rayon', 'CHMU', 'ry-wc-city-select'),
	],
	'CHRA2' => [
		_x('Chernomorskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Dalekovskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Kirovskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Krasnopolyanskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Krasnoyarskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Medvedevskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Mezhvodnenskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Novoivanovskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Novoselskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Okunevskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
		_x('Olenevskoye selskoye poselenye', 'CHRA2', 'ry-wc-city-select'),
	],
	'CHRA3' => [
		_x('Krasnopil Amalgamated Territorial Commu', 'CHRA3', 'ry-wc-city-select'),
	],
	'DNMIRA' => [
		_x('Chechelivskyi District', 'DNMIRA', 'ry-wc-city-select'),
		_x('Sobornyi District', 'DNMIRA', 'ry-wc-city-select'),
		_x('Zavodskyi District', 'DNMIRA', 'ry-wc-city-select'),
	],
	'DOMI' => [
		_x('Budennovskiy Rayon', 'DOMI', 'ry-wc-city-select'),
		_x('Kalininskiy Rayon', 'DOMI', 'ry-wc-city-select'),
		_x('Kirovskiy Rayon', 'DOMI', 'ry-wc-city-select'),
		_x('Kuibyshevskyi District', 'DOMI', 'ry-wc-city-select'),
		_x('Kyivskyi District', 'DOMI', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'DOMI', 'ry-wc-city-select'),
		_x('Petrovsky District', 'DOMI', 'ry-wc-city-select'),
		_x('Proletarskiy Rayon', 'DOMI', 'ry-wc-city-select'),
		_x('Voroshylovskyi District', 'DOMI', 'ry-wc-city-select'),
	],
	'DZRA' => [
		_x('Azovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Chaykinskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Izumrudnovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Kondratyevskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Krymkovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Lobanovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Luganskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Maslovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Mayskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Medvedevskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Mirnovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Novokrymskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Pakharevskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Pobednenskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Prostornenskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Roshchinskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Roskoshnenskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Stalnenskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Svetlovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Tabachnenskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Tselinnoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Volnovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Yarkopolenskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Yarkovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Yasnopolyanskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Yermakovskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Zarechenskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
		_x('Zavet-Leninskoye selskoye poselenye', 'DZRA', 'ry-wc-city-select'),
	],
	'HADI' => [
		_x('Gagarinskiy munitsipalnyi okrug', 'HADI', 'ry-wc-city-select'),
	],
	'HORA' => [
		_x('Holosiiv', 'HORA', 'ry-wc-city-select'),
		_x('Teremki', 'HORA', 'ry-wc-city-select'),
	],
	'KAMU' => [
		_x('Pivdennyi District', 'KAMU', 'ry-wc-city-select'),
	],
	'KHMI' => [
		_x('Suvorovskyy Rayon', 'KHMI', 'ry-wc-city-select'),
	],
	'KHRA' => [
		_x('Khoroshiv Amalgamated Territorial Commun', 'KHRA', 'ry-wc-city-select'),
	],
	'KIRA' => [
		_x('Abrikosovskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Gorodskoye poselenye Stary Krym', 'KIRA', 'ry-wc-city-select'),
		_x('Kirovskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Lgovskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Partizanskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Pervomayskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Privetnenskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Sinitsynskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Tokarevskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Vladislavovskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Yarkopolenskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Zhuravskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
		_x('Zolotopolenskoye selskoye poselenye', 'KIRA', 'ry-wc-city-select'),
	],
	'KRRA' => [
		_x('Aleksandrovskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Amurskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Kalininskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Klepininskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Kolodezyanskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Kotelnikovskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Krasnogvardeyskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Krasnoznamenskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Leninskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Maryanovskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Naydenovskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Novopokrovskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Oktyabrskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Petrovskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Poltavskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Pyatikhatskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Rovnovskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Voskhodnenskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Yantarnenskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
		_x('Zernovskoye selskoye poselenye', 'KRRA', 'ry-wc-city-select'),
	],
	'KRRA2' => [
		_x('Bratskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Filatovskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Ilyinskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Ishunskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Krasnoarmeyskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Magazinskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Novopavlovskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Orlovskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Pochetnenskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Sovkhoznenskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Vishnyovskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
		_x('Voinskoye selskoye poselenye', 'KRRA2', 'ry-wc-city-select'),
	],
	'LEDI' => [
		_x('Leninskiy munitsipalniy okrug', 'LEDI', 'ry-wc-city-select'),
	],
	'LERA' => [
		_x('Bagerovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Batalnenskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Belinskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Chelyadinovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Chistopolskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Glazovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Gornostaevskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Gorodskoye poselenye Shchyolkino', 'LERA', 'ry-wc-city-select'),
		_x('Ilychyovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Kalinovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Kirovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Krasnogorskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Leninovo selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Leninskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Lugovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Marfovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Maryevskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Mysovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Novonikolaevskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Oktyabrskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Ostaninskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Priozyornovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Semisotskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Uvarovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Vinogradnenskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Voykovskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
		_x('Zavetnenskoye selskoye poselenye', 'LERA', 'ry-wc-city-select'),
	],
	'LURA' => [
		_x('Luhyny United Territorial Community', 'LURA', 'ry-wc-city-select'),
	],
	'LYAMTECO' => [
		_x('Drobysheve Starostynskyi Okruh', 'LYAMTECO', 'ry-wc-city-select'),
		_x('Kryva Luka Starostynskyi Okruh', 'LYAMTECO', 'ry-wc-city-select'),
		_x('Lyman Municipality', 'LYAMTECO', 'ry-wc-city-select'),
		_x('Novoselivka Starostynskyi Okruh', 'LYAMTECO', 'ry-wc-city-select'),
		_x('Terny Starostynskyi Okruh', 'LYAMTECO', 'ry-wc-city-select'),
		_x('Yampil Starostynskyi Okruh', 'LYAMTECO', 'ry-wc-city-select'),
		_x('Yatskivka Starostynskyi Okruh', 'LYAMTECO', 'ry-wc-city-select'),
		_x('Zarichne Starostynskyi Okruh', 'LYAMTECO', 'ry-wc-city-select'),
	],
	'MAMI' => [
		_x('Hirnyk District', 'MAMI', 'ry-wc-city-select'),
	],
	'MARA' => [
		_x('Chopovychi United Territorial Community', 'MARA', 'ry-wc-city-select'),
	],
	'NARA' => [
		_x('Andreevskiy munitsipalniy okrug', 'NARA', 'ry-wc-city-select'),
		_x('Kachinskiy munitsipalniy okrug', 'NARA', 'ry-wc-city-select'),
		_x('Nakhimovskiy munitsipalniy okrug', 'NARA', 'ry-wc-city-select'),
		_x('Verkhnesadovskiy munitsipalniy okrug', 'NARA', 'ry-wc-city-select'),
	],
	'NARA2' => [
		_x('Narodychi Amalgamated Territorial Commun', 'NARA2', 'ry-wc-city-select'),
	],
	'NIRA' => [
		_x('Akimovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Chkalovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Drofinskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Ivanovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Izobilnenskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Kostochkovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Listvenskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Mikhaylovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Mitrofanovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Nizhnegorskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Novogrigoryevskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Okhotskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Pshenichnenskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Sadovoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Uvarovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Yemelyanovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Zhelyabovskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Zhemchuzhenskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
		_x('Zorkinskoye selskoye poselenye', 'NIRA', 'ry-wc-city-select'),
	],
	'PERA' => [
		_x('Abrikosovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Alekseyevskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Chernovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Grishinskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Gvardeyskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Kalininskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Kormovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Krestyanovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Oktyabrskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Ostrovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Pervomayskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Pravdovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Sarybashskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Stakhanovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Stepnovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Susaninskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
		_x('Voykovskoye selskoye poselenye', 'PERA', 'ry-wc-city-select'),
	],
	'PORA' => [
		_x('Ahndrushky United Territorial Community', 'PORA', 'ry-wc-city-select'),
		_x('Kornyn United Territorial Community', 'PORA', 'ry-wc-city-select'),
		_x('Popilnya United Territorial Community', 'PORA', 'ry-wc-city-select'),
	],
	'PRRA' => [
		_x('Botiyeve United Territorial Community', 'PRRA', 'ry-wc-city-select'),
		_x('Hirsivka United Territorial Community', 'PRRA', 'ry-wc-city-select'),
		_x('Oleksandrivka United Territorial Communi', 'PRRA', 'ry-wc-city-select'),
		_x('Pryazovske United Territorial Community', 'PRRA', 'ry-wc-city-select'),
	],
	'PRRA2' => [
		_x('Novooleksiyivka United Territorial Commu', 'PRRA2', 'ry-wc-city-select'),
		_x('Prymorsk Urban United Territorial Commun', 'PRRA2', 'ry-wc-city-select'),
	],
	'RARA' => [
		_x('Horodok Settlement Council', 'RARA', 'ry-wc-city-select'),
		_x('Irshansk United Territorial Community', 'RARA', 'ry-wc-city-select'),
		_x('Korostyshiv Urban AmalgametedTerritorial', 'RARA', 'ry-wc-city-select'),
		_x('Potiyivska Silska Obyednana Terytoria', 'RARA', 'ry-wc-city-select'),
		_x('Radomyshl Town United Territorial Commu', 'RARA', 'ry-wc-city-select'),
	],
	'RARA2' => [
		_x('Berezovskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Botanicheskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Chernyshevskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Kovylnovskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Kukushkinskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Novoselovskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Razdolnenskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Ruchyevskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Serebryanskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Slavnovskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Slavyanskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
		_x('Ziminskoye selskoye poselenye', 'RARA2', 'ry-wc-city-select'),
	],
	'SARA' => [
		_x('Dobrushinskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Frunzenskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Geroyskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Ivanovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Koltsovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Kraynenskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Krymskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Lesnovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Mityaevskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Molochnenskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Novofedorovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Okhotnikovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Orekhovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Romashkinskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Shtormovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Sizovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Stolbovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Suvorovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Uyutnenskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Veresaevskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Veselovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Vinogradovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Vorobyovskoye selskoye poselenye', 'SARA', 'ry-wc-city-select'),
		_x('Zernovskoe selskoe poselenie', 'SARA', 'ry-wc-city-select'),
	],
	'SIRA' => [
		_x('Chistenskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Dobrovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Donskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Gvardeyskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Kolchuginskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Mazanskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Mirnovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Molodezhnenskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Nikolaevskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Novoandreevskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Novoselovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Perovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Pervomayskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Pozharskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Rodnikovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Shirokovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Shkolnenskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Skvortsovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Trudovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Ukromnovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Urozhaynovskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
		_x('Zhuravlevskoye selskoye poselenye', 'SIRA', 'ry-wc-city-select'),
	],
	'SORA' => [
		_x('Chokolivka', 'SORA', 'ry-wc-city-select'),
		_x('Zhuliany', 'SORA', 'ry-wc-city-select'),
	],
	'SORA2' => [
		_x('Chapayevskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Chernozemnenskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Dmitrovskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Ilyichovskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Krasnoflotskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Krasnogvardeyskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Nekrasovskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Prudovskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Pushkinskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Sovetskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Urozhaynovskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
		_x('Zavetnenskoye selskoye poselenye', 'SORA2', 'ry-wc-city-select'),
	],
	'TORA' => [
		_x('Ostrykiv United Territorial Community', 'TORA', 'ry-wc-city-select'),
	],
	'VIMI' => [
		_x('Zamostyanskyy Rayon', 'VIMI', 'ry-wc-city-select'),
	],
	'VORA' => [
		_x('Volochysk Town United Territorial Commun', 'VORA', 'ry-wc-city-select'),
	],
	'YARA' => [
		_x('Yakymivka United Territorial Community', 'YARA', 'ry-wc-city-select'),
	],
	'AURECR' => [
		_x('Gorodskoy okrug Alushta', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Armyansk', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Dzhankoy', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Feodosiya', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Krasnoperekopsk', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Saki', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Simferopol', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Sudak', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Yalta', 'AURECR', 'ry-wc-city-select'),
		_x('Gorodskoy okrug Yevpatoriya', 'AURECR', 'ry-wc-city-select'),
		_x('Kerchenska Miska Rada', 'AURECR', 'ry-wc-city-select'),
	],
	'CHOB' => [
		_x('Cherkaska Miskrada', 'CHOB', 'ry-wc-city-select'),
		_x('Chornobayivskyy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Drabiv Raion', 'CHOB', 'ry-wc-city-select'),
		_x('Horodyshchenskyy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Kanivska Miskrada', 'CHOB', 'ry-wc-city-select'),
		_x('Mankivskyy Rayon', 'CHOB', 'ry-wc-city-select'),
		_x('Smilyanska Miskrada', 'CHOB', 'ry-wc-city-select'),
		_x('Umanska Miskrada', 'CHOB', 'ry-wc-city-select'),
		_x('Vatutinska Miskrada', 'CHOB', 'ry-wc-city-select'),
		_x('Zolotoniska Miskrada', 'CHOB', 'ry-wc-city-select'),
	],
	'CHOB2' => [
		_x('Chernihiv Raion', 'CHOB2', 'ry-wc-city-select'),
		_x('Chernihivska Miskrada', 'CHOB2', 'ry-wc-city-select'),
		_x('Menskyy Rayon', 'CHOB2', 'ry-wc-city-select'),
		_x('Nizhynska Miskrada', 'CHOB2', 'ry-wc-city-select'),
		_x('Novhorod-Siverska Miskrada', 'CHOB2', 'ry-wc-city-select'),
		_x('Prylutska Miskrada', 'CHOB2', 'ry-wc-city-select'),
		_x('Prylutskyy Rayon', 'CHOB2', 'ry-wc-city-select'),
		_x('Snovskyy Rayon', 'CHOB2', 'ry-wc-city-select'),
		_x('Varvynskyy Rayon', 'CHOB2', 'ry-wc-city-select'),
	],
	'CHOB3' => [
		_x('Hertsayivskyy Rayon', 'CHOB3', 'ry-wc-city-select'),
		_x('Novodnistrovska Miskrada', 'CHOB3', 'ry-wc-city-select'),
		_x('Putyla Raion', 'CHOB3', 'ry-wc-city-select'),
		_x('Sokyryanskyy Rayon', 'CHOB3', 'ry-wc-city-select'),
	],
	'DNOB' => [
		_x('Amur-Nyzhnodniprovskyi District', 'DNOB', 'ry-wc-city-select'),
		_x('Babushkinskiy Rayon', 'DNOB', 'ry-wc-city-select'),
		_x('Dnipro Raion', 'DNOB', 'ry-wc-city-select'),
		_x('Industrialnyy Rayon', 'DNOB', 'ry-wc-city-select'),
		_x('Krynychky Raion', 'DNOB', 'ry-wc-city-select'),
		_x('Kryvorizka Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Kryvyi Rih Raion', 'DNOB', 'ry-wc-city-select'),
		_x('Leninskiy Rayon', 'DNOB', 'ry-wc-city-select'),
		_x('Mahdalynivskyy Rayon', 'DNOB', 'ry-wc-city-select'),
		_x('Marhanetska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Nikopolska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Novomoskovska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Novomoskovsk Raion', 'DNOB', 'ry-wc-city-select'),
		_x('Ordzhonikidzevska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Pavlohradska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Pershotravenska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Petrykivskyy Rayon', 'DNOB', 'ry-wc-city-select'),
		_x('Samarskiy Rayon', 'DNOB', 'ry-wc-city-select'),
		_x('Shyroke Raion', 'DNOB', 'ry-wc-city-select'),
		_x('Solone Raion', 'DNOB', 'ry-wc-city-select'),
		_x('Synelnykivska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Ternivska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Tsarychanskyy Rayon', 'DNOB', 'ry-wc-city-select'),
		_x('Vilnohirska Miskrada', 'DNOB', 'ry-wc-city-select'),
		_x('Yuryivskyy Rayon', 'DNOB', 'ry-wc-city-select'),
		_x('Zhovtovodska Miskrada', 'DNOB', 'ry-wc-city-select'),
	],
	'DOOB' => [
		_x('Amvrosiivka Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Avdiyivska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Bakhmut Municipality', 'DOOB', 'ry-wc-city-select'),
		_x('Bakhmut Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Boykivske Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Debaltsivska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Dobropilska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Dobropillia Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Dokuchayevska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Druzhkivska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Horlivska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Khartsyzka Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Kirovska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Kostiantynivka Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Kostyantynivska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Kramatorska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Krasnoarmiyska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Lyman Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Manhush Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Marinskiy Rayon', 'DOOB', 'ry-wc-city-select'),
		_x('Mariupolska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Myrnohrad Municipality', 'DOOB', 'ry-wc-city-select'),
		_x('Nikolske Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Novoazovsk Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Novohrodivska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Pokrovsk Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Selydivska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Shakhtarska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Shakhtarsk Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Slovyanska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Sloviansk Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Snizhnyanska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Starobesheve Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Toretsk Municipality', 'DOOB', 'ry-wc-city-select'),
		_x('Torezka Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Velyka Novosilka Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Volnovakha Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Vuhledarska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Yasynuvata Raion', 'DOOB', 'ry-wc-city-select'),
		_x('Yasynuvatska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Yenakiyevska Miskrada', 'DOOB', 'ry-wc-city-select'),
		_x('Zhdanivska Miskrada', 'DOOB', 'ry-wc-city-select'),
	],
	'IVOB' => [
		_x('Bohorodchanskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Bolekhivska Miskrada', 'IVOB', 'ry-wc-city-select'),
		_x('Borshchevskiy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Burshtynska Miskrada', 'IVOB', 'ry-wc-city-select'),
		_x('Dolynskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Halytskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Horodenkivskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Ivano-Frankivska Miskrada', 'IVOB', 'ry-wc-city-select'),
		_x('Kaluska Miskrada', 'IVOB', 'ry-wc-city-select'),
		_x('Kaluskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Kolomyyskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Kosivskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Nadvirnyanskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Rohatynskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Rozhnyativskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Snyatynskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Tlumatskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Tysmenytskyy Rayon', 'IVOB', 'ry-wc-city-select'),
		_x('Yaremchansks Miskrada', 'IVOB', 'ry-wc-city-select'),
	],
	'KHOB' => [
		_x('Chuhuyivska Miskrada', 'KHOB', 'ry-wc-city-select'),
		_x('Izyumska Miskrada', 'KHOB', 'ry-wc-city-select'),
		_x('Kharkivska Miskrada', 'KHOB', 'ry-wc-city-select'),
		_x('Kolomatskyy Rayon', 'KHOB', 'ry-wc-city-select'),
		_x('Kupyanska Miskrada', 'KHOB', 'ry-wc-city-select'),
		_x('Lozivska Miskrada', 'KHOB', 'ry-wc-city-select'),
		_x('Lyubotynska Miskrada', 'KHOB', 'ry-wc-city-select'),
		_x('Pechenizkyy Rayon', 'KHOB', 'ry-wc-city-select'),
		_x('Pervomaiskyi Raion', 'KHOB', 'ry-wc-city-select'),
		_x('Pervomayska Miskrada', 'KHOB', 'ry-wc-city-select'),
		_x('Zolochivskyy Rayon', 'KHOB', 'ry-wc-city-select'),
	],
	'KHOB2' => [
		_x('Bilozerskyy Rayon', 'KHOB2', 'ry-wc-city-select'),
		_x('Henicheskyy Rayon', 'KHOB2', 'ry-wc-city-select'),
		_x('Holoprystanska Miskrada', 'KHOB2', 'ry-wc-city-select'),
		_x('Kakhovska Miskrada', 'KHOB2', 'ry-wc-city-select'),
		_x('Novokakhovska Miskrada', 'KHOB2', 'ry-wc-city-select'),
		_x('Novotroyitskyy Rayon', 'KHOB2', 'ry-wc-city-select'),
		_x('Nyzhnosirohozkyy Rayon', 'KHOB2', 'ry-wc-city-select'),
	],
	'KHOB3' => [
		_x('Bilohirskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Chemerovetskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Derazhnyanskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Dunayevetskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Horodotskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Izyaslavskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Kamyanets-Podilska Miskrada', 'KHOB3', 'ry-wc-city-select'),
		_x('Khmelnytska Miskrada', 'KHOB3', 'ry-wc-city-select'),
		_x('Khmelnytskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Krasylivskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Letychivskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
		_x('Netishynska Miskrada', 'KHOB3', 'ry-wc-city-select'),
		_x('Shepetivska Miskrada', 'KHOB3', 'ry-wc-city-select'),
		_x('Slavutska Miskrada', 'KHOB3', 'ry-wc-city-select'),
		_x('Starokostyantynivska Miskrada', 'KHOB3', 'ry-wc-city-select'),
		_x('Teofipolskyy Rayon', 'KHOB3', 'ry-wc-city-select'),
	],
	'KIOB' => [
		_x('Blahovishchenske Raion', 'KIOB', 'ry-wc-city-select'),
		_x('Dobrovelychkivskyy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Dolynskyy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Kirovohradska Miskrada', 'KIOB', 'ry-wc-city-select'),
		_x('Malovyskivskyy Rayon', 'KIOB', 'ry-wc-city-select'),
		_x('Oleksandriyska Miskrada', 'KIOB', 'ry-wc-city-select'),
		_x('Svitlovodska Miskrada', 'KIOB', 'ry-wc-city-select'),
		_x('Znamyanska Miskrada', 'KIOB', 'ry-wc-city-select'),
	],
	'KYOB' => [
		_x('Baryshivskyy Rayon', 'KYOB', 'ry-wc-city-select'),
		_x('Berezanska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Bila Tserkva Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Bilotserkivska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Borispolskiy Rayon', 'KYOB', 'ry-wc-city-select'),
		_x('Borodyanskyy Rayon', 'KYOB', 'ry-wc-city-select'),
		_x('Boryspilska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Brovarska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Brovary Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Fastiv Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Fastivska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Irpinska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Ivankiv Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Kaharlyk Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Kyyevo-Svyatoshynskyy Rayon', 'KYOB', 'ry-wc-city-select'),
		_x('Makariv Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Obukhiv Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Obukhivska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Pereiaslav-Khmelnytskyi Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Pereyaslav-Khmelnytska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Rokytne Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Rzhyshchivska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Skvyrskyy Rayon', 'KYOB', 'ry-wc-city-select'),
		_x('Slavutytska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Vasylkivska Miskrada', 'KYOB', 'ry-wc-city-select'),
		_x('Vasylkiv Raion', 'KYOB', 'ry-wc-city-select'),
		_x('Vyshgorodskiy Rayon', 'KYOB', 'ry-wc-city-select'),
		_x('Yahotynskyy Rayon', 'KYOB', 'ry-wc-city-select'),
		_x('Z.hurivskyy Rayon', 'KYOB', 'ry-wc-city-select'),
	],
	'LVOB' => [
		_x('Boryslavska Miskrada', 'LVOB', 'ry-wc-city-select'),
		_x('Chervonohradska Miskrada', 'LVOB', 'ry-wc-city-select'),
		_x('Drohobytska Miskrada', 'LVOB', 'ry-wc-city-select'),
		_x('Lvivska Miskrada', 'LVOB', 'ry-wc-city-select'),
		_x('Morshynska Miskrada', 'LVOB', 'ry-wc-city-select'),
		_x('Novorozdilska Miskrada', 'LVOB', 'ry-wc-city-select'),
		_x('Sambirska Miskrada', 'LVOB', 'ry-wc-city-select'),
		_x('Stryyska Miskrada', 'LVOB', 'ry-wc-city-select'),
		_x('Truskavetska Miskrada', 'LVOB', 'ry-wc-city-select'),
	],
	'LUOB' => [
		_x('Alchevska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Antratsytivska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Antratsytivskyy Rayon', 'LUOB', 'ry-wc-city-select'),
		_x('Bryankivska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Dovzhanskyy Rayon', 'LUOB', 'ry-wc-city-select'),
		_x('Kadiyivka', 'LUOB', 'ry-wc-city-select'),
		_x('Kirovska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Krasnodonska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Krasnolutska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Luhanska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Lutuhynskyy Rayon', 'LUOB', 'ry-wc-city-select'),
		_x('Lysychanska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Pervomayska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Rovenkivska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Rubizhanska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Sorokynskyi Rayon', 'LUOB', 'ry-wc-city-select'),
		_x('Sverdlovska Miskrada', 'LUOB', 'ry-wc-city-select'),
		_x('Syevyerodonetska Miskrada', 'LUOB', 'ry-wc-city-select'),
	],
	'MIKY' => [
		_x('Darnytsia Raion', 'MIKY', 'ry-wc-city-select'),
		_x('Desnyanskyy Rayon', 'MIKY', 'ry-wc-city-select'),
		_x('Dnipro Raion', 'MIKY', 'ry-wc-city-select'),
		_x('Obolonskyy Rayon', 'MIKY', 'ry-wc-city-select'),
		_x('Pechersk Raion', 'MIKY', 'ry-wc-city-select'),
		_x('Podilskyy Rayon', 'MIKY', 'ry-wc-city-select'),
		_x('Shevchenkivskyy Rayon', 'MIKY', 'ry-wc-city-select'),
		_x('Svyatoshynskyy Rayon', 'MIKY', 'ry-wc-city-select'),
	],
	'MYOB' => [
		_x('Domanivskyy Rayon', 'MYOB', 'ry-wc-city-select'),
		_x('Mykolayivska Miskrada', 'MYOB', 'ry-wc-city-select'),
		_x('Novoodeskyy Rayon', 'MYOB', 'ry-wc-city-select'),
		_x('Ochakivska Miskrada', 'MYOB', 'ry-wc-city-select'),
		_x('Pervomayska Miskrada', 'MYOB', 'ry-wc-city-select'),
		_x('Pervomayskyy Rayon', 'MYOB', 'ry-wc-city-select'),
		_x('Veselynivskyy Rayon', 'MYOB', 'ry-wc-city-select'),
		_x('Vitovka Raion', 'MYOB', 'ry-wc-city-select'),
		_x('Voznesenska Miskrada', 'MYOB', 'ry-wc-city-select'),
		_x('Vradiyivskyy Rayon', 'MYOB', 'ry-wc-city-select'),
		_x('Yuzhnoukrayinska Miskrada', 'MYOB', 'ry-wc-city-select'),
	],
	'ODOB' => [
		_x('Ananyivskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Artsyz Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Baltskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Berezivskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Bilyayivka Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Bolhrad Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Chornomorsk Municipality', 'ODOB', 'ry-wc-city-select'),
		_x('Ivanivskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Izmail Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Kiliya Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Kodyma Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Kotovska Miskrada', 'ODOB', 'ry-wc-city-select'),
		_x('Lyman Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Lyubashivskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Mykolayivskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Odeska Miskrada', 'ODOB', 'ry-wc-city-select'),
		_x('Okny Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Ovidiopolskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Podilsk Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Reni District', 'ODOB', 'ry-wc-city-select'),
		_x('Rozdilnyanskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Sarata Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Savranskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Shyryayivskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Tarutyne Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Tatarbunary Raion', 'ODOB', 'ry-wc-city-select'),
		_x('Velykomykhaylivskyy Rayon', 'ODOB', 'ry-wc-city-select'),
		_x('Yuznenska Miskrada', 'ODOB', 'ry-wc-city-select'),
		_x('Zakharivka Raion', 'ODOB', 'ry-wc-city-select'),
	],
	'POOB' => [
		_x('Avtozavodskiy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Chornukhynskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Chutivskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Dykanskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Hlobynskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Hrebinkivskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Karlivskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Khorolskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Kobelyatskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Komsomolska Miskrada', 'POOB', 'ry-wc-city-select'),
		_x('Komsomolskiy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Kotelevskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Kozelshchyna Raion', 'POOB', 'ry-wc-city-select'),
		_x('Kremenchugskiy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Kremenchutska Miskrada', 'POOB', 'ry-wc-city-select'),
		_x('Kryukovskiy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Lokhvytskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Lubenska Miskrada', 'POOB', 'ry-wc-city-select'),
		_x('Lubenskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Mashivskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Myrhorodska Miskrada', 'POOB', 'ry-wc-city-select'),
		_x('Myrhorodskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Novosanzharskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Novosanzharskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Orzhytskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Poltavska Miskrada', 'POOB', 'ry-wc-city-select'),
		_x('Poltavskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Pyryatynskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Reshetylivskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Semenivskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Shyshatskyy Rayon', 'POOB', 'ry-wc-city-select'),
		_x('Velykobahachanskyy Rayon', 'POOB', 'ry-wc-city-select'),
	],
	'RIOB' => [
		_x('Demydivskyy Rayon', 'RIOB', 'ry-wc-city-select'),
		_x('Dubenska Miskrada', 'RIOB', 'ry-wc-city-select'),
		_x('Kuznetsovska Miskrada', 'RIOB', 'ry-wc-city-select'),
		_x('Mlinovskiy Rayon', 'RIOB', 'ry-wc-city-select'),
		_x('Mlynivskyy Rayon', 'RIOB', 'ry-wc-city-select'),
		_x('Ostrozka Miskrada', 'RIOB', 'ry-wc-city-select'),
		_x('Rivnenska Miskrada', 'RIOB', 'ry-wc-city-select'),
		_x('Sarnenskyy Rayon', 'RIOB', 'ry-wc-city-select'),
	],
	'SUOB' => [
		_x('Hlukhivska Miskrada', 'SUOB', 'ry-wc-city-select'),
		_x('Konotopska Miskrada', 'SUOB', 'ry-wc-city-select'),
		_x('Lebedynska Miskrada', 'SUOB', 'ry-wc-city-select'),
		_x('Okhtyrska Miskrada', 'SUOB', 'ry-wc-city-select'),
		_x('Romenska Miskrada', 'SUOB', 'ry-wc-city-select'),
		_x('Shostkynska Miskrada', 'SUOB', 'ry-wc-city-select'),
		_x('Sumska Miskrada', 'SUOB', 'ry-wc-city-select'),
	],
	'TEOB' => [
		_x('Chortkivska Miskrada', 'TEOB', 'ry-wc-city-select'),
		_x('Kremenets Municipality', 'TEOB', 'ry-wc-city-select'),
		_x('Pidhayetskyy Rayon', 'TEOB', 'ry-wc-city-select'),
		_x('Ternopilska Miskrada', 'TEOB', 'ry-wc-city-select'),
		_x('Zalishchytskyy Rayon', 'TEOB', 'ry-wc-city-select'),
	],
	'VIOB' => [
		_x('Barskiy Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Chechelnytskyy Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Chernivetskyy Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Khmilnytska Miskrada', 'VIOB', 'ry-wc-city-select'),
		_x('Kozyatynska Miskrada', 'VIOB', 'ry-wc-city-select'),
		_x('Ladyzhynska Miskrada', 'VIOB', 'ry-wc-city-select'),
		_x('Litynskyy Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Lypovetskyy Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Mohyliv-Podilska Miskrada', 'VIOB', 'ry-wc-city-select'),
		_x('Pohrebyshchenskyy Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Vinnitskiy Rayon', 'VIOB', 'ry-wc-city-select'),
		_x('Zhmerynska Miskrada', 'VIOB', 'ry-wc-city-select'),
	],
	'VOOB' => [
		_x('Kovelska Miskrada', 'VOOB', 'ry-wc-city-select'),
		_x('Lutska Miskrada', 'VOOB', 'ry-wc-city-select'),
		_x('Lyubeshivskyy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Lyubomlskyy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Manevytskyy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Novovolynska Miskrada', 'VOOB', 'ry-wc-city-select'),
		_x('Ratnivskyy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Shatskyy Rayon', 'VOOB', 'ry-wc-city-select'),
		_x('Volodymyr-Volynska Miskrada', 'VOOB', 'ry-wc-city-select'),
	],
	'ZAOB' => [
		_x('Berehivska Miskrada', 'ZAOB', 'ry-wc-city-select'),
		_x('Berehove Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Chopska Miskrada', 'ZAOB', 'ry-wc-city-select'),
		_x('Irshava Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Khust Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Khustska Miskrada', 'ZAOB', 'ry-wc-city-select'),
		_x('Mizhhirya Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Mukachevo Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Mukachivska Miskrada', 'ZAOB', 'ry-wc-city-select'),
		_x('Perechyn Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Rakhiv Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Svaliava Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Tiachiv Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Uzhhorod Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Uzhhorodska Miskrada', 'ZAOB', 'ry-wc-city-select'),
		_x('Velykyi Bereznyi Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Volovets Raion', 'ZAOB', 'ry-wc-city-select'),
		_x('Vynohradiv Raion', 'ZAOB', 'ry-wc-city-select'),
	],
	'ZAOB2' => [
		_x('Berdiansk Raion', 'ZAOB2', 'ry-wc-city-select'),
		_x('Berdyanska Miskrada', 'ZAOB2', 'ry-wc-city-select'),
		_x('Enerhodarska Miskrada', 'ZAOB2', 'ry-wc-city-select'),
		_x('Melitopolska Miskrada', 'ZAOB2', 'ry-wc-city-select'),
		_x('Melitopolskyy Rayon', 'ZAOB2', 'ry-wc-city-select'),
		_x('Mykhaylivskyy Rayon', 'ZAOB2', 'ry-wc-city-select'),
		_x('Rozivskyy Rayon', 'ZAOB2', 'ry-wc-city-select'),
		_x('Tokmatska Miskrada', 'ZAOB2', 'ry-wc-city-select'),
		_x('Velykobilozerskyy Rayon', 'ZAOB2', 'ry-wc-city-select'),
		_x('Vilniansk Raion', 'ZAOB2', 'ry-wc-city-select'),
		_x('Zaporizka Miskrada', 'ZAOB2', 'ry-wc-city-select'),
		_x('Zaporizhzhia Raion', 'ZAOB2', 'ry-wc-city-select'),
	],
	'ZHOB' => [
		_x('Andrushivskyy Rayon', 'ZHOB', 'ry-wc-city-select'),
		_x('Berdychivska Miskrada', 'ZHOB', 'ry-wc-city-select'),
		_x('Berdychivskyy Rayon', 'ZHOB', 'ry-wc-city-select'),
		_x('Brusylivskyy Rayon', 'ZHOB', 'ry-wc-city-select'),
		_x('Chernyakhivskyy Rayon', 'ZHOB', 'ry-wc-city-select'),
		_x('Korosten Raion', 'ZHOB', 'ry-wc-city-select'),
		_x('Korostenska Miskrada', 'ZHOB', 'ry-wc-city-select'),
		_x('Korostyshiv Raion', 'ZHOB', 'ry-wc-city-select'),
		_x('Liubar Raion', 'ZHOB', 'ry-wc-city-select'),
		_x('Malynska Miskrada', 'ZHOB', 'ry-wc-city-select'),
		_x('Novohrad-Volynska Miskrada', 'ZHOB', 'ry-wc-city-select'),
		_x('Ovruch Raion', 'ZHOB', 'ry-wc-city-select'),
		_x('Pulyny Raion', 'ZHOB', 'ry-wc-city-select'),
		_x('Zhytomyr City Amalgamated Territorial Co', 'ZHOB', 'ry-wc-city-select'),
		_x('Zhytomyr Raion', 'ZHOB', 'ry-wc-city-select'),
		_x('Zhytomyrska Miskrada', 'ZHOB', 'ry-wc-city-select'),
	],
	]
];