<?php
/**
 * Republic of Uzbekistan places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'UZ' => [
	'AN' => [
		_x('Andijon Shahri', 'AN', 'ry-wc-city-select'),
		_x('Andijon Tumani', 'AN', 'ry-wc-city-select'),
		_x('Asaka Shahri', 'AN', 'ry-wc-city-select'),
		_x('Asaka Tumani', 'AN', 'ry-wc-city-select'),
		_x('Baliqchi Tumani', 'AN', 'ry-wc-city-select'),
		_x('Bo`z Tumani', 'AN', 'ry-wc-city-select'),
		_x('Buloqboshi Tumani', 'AN', 'ry-wc-city-select'),
		_x('Izboskan Tumani', 'AN', 'ry-wc-city-select'),
		_x('Jalolkuduk Tumani', 'AN', 'ry-wc-city-select'),
		_x('Khonobod Shahri', 'AN', 'ry-wc-city-select'),
		_x('Khujaobod Tumani', 'AN', 'ry-wc-city-select'),
		_x('Marhamat Tumani', 'AN', 'ry-wc-city-select'),
		_x('Oltinkul Tumani', 'AN', 'ry-wc-city-select'),
		_x('Pakhtaobod Tumani', 'AN', 'ry-wc-city-select'),
		_x('Qorasuw Shahri', 'AN', 'ry-wc-city-select'),
		_x('Qurghontepa Tumani', 'AN', 'ry-wc-city-select'),
		_x('Shahrikhon Shahri', 'AN', 'ry-wc-city-select'),
		_x('Shahrikhon Tumani', 'AN', 'ry-wc-city-select'),
		_x('Ulug`nor Tumani', 'AN', 'ry-wc-city-select'),
		_x('Ulugnar', 'AN', 'ry-wc-city-select'),
	],
	'BUPR' => [
		_x('Alat', 'BUPR', 'ry-wc-city-select'),
		_x('Bukhoro Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Gijduvon Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Ghijduwon Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Jondor Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Kogon Shahri', 'BUPR', 'ry-wc-city-select'),
		_x('Kogon Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Olot Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Peshku Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Qorakul Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Qorovulbozor Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Romiton Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Shofirkon Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Termiz Tumani', 'BUPR', 'ry-wc-city-select'),
		_x('Vobkent Tumani', 'BUPR', 'ry-wc-city-select'),
	],
	'FE' => [
		_x('Altyarik', 'FE', 'ry-wc-city-select'),
		_x('Bag`dod Tumani', 'FE', 'ry-wc-city-select'),
		_x('Bagdad', 'FE', 'ry-wc-city-select'),
		_x('Beshariq Tumani', 'FE', 'ry-wc-city-select'),
		_x('Buvayda Tumani', 'FE', 'ry-wc-city-select'),
		_x('Dang`ara Tumani', 'FE', 'ry-wc-city-select'),
		_x('Farg`ona Shahri', 'FE', 'ry-wc-city-select'),
		_x('Farg`ona Tumani', 'FE', 'ry-wc-city-select'),
		_x('Furqat Tumani', 'FE', 'ry-wc-city-select'),
		_x('Marg`ilon Shahri', 'FE', 'ry-wc-city-select'),
		_x('O`zbekiston Tumani', 'FE', 'ry-wc-city-select'),
		_x('Oltiariq Tumani', 'FE', 'ry-wc-city-select'),
		_x('Oxunboboyev Tumani', 'FE', 'ry-wc-city-select'),
		_x('Qo`qon Shahri', 'FE', 'ry-wc-city-select'),
		_x('Quva Shahri', 'FE', 'ry-wc-city-select'),
		_x('Quva Tumani', 'FE', 'ry-wc-city-select'),
		_x('Quvasoy Shahri', 'FE', 'ry-wc-city-select'),
		_x('Rishtan', 'FE', 'ry-wc-city-select'),
		_x('Rishton Tumani', 'FE', 'ry-wc-city-select'),
		_x('So`x Tumani', 'FE', 'ry-wc-city-select'),
		_x('Toshloq Tumani', 'FE', 'ry-wc-city-select'),
		_x('Uchko`prik Tumani', 'FE', 'ry-wc-city-select'),
		_x('Yazyavan', 'FE', 'ry-wc-city-select'),
		_x('Yozyovon Tumani', 'FE', 'ry-wc-city-select'),
	],
	'JIPR' => [
		_x('Arnasoy Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Baxmal Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Dustlik Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Forish Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('G`allaorol Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Jizzax Shahri', 'JIPR', 'ry-wc-city-select'),
		_x('Jizzax Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Mirzachul Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Paxtakor Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Zafarobod Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Zarbdor Tumani', 'JIPR', 'ry-wc-city-select'),
		_x('Zomin Tumani', 'JIPR', 'ry-wc-city-select'),
	],
	'KA' => [
		_x('Amudaryo Tumani', 'KA', 'ry-wc-city-select'),
		_x('Beruniy Tumani', 'KA', 'ry-wc-city-select'),
		_x('Bo`zatov Tumani', 'KA', 'ry-wc-city-select'),
		_x('Chimboy Tumani', 'KA', 'ry-wc-city-select'),
		_x('Ellikqala Tumani', 'KA', 'ry-wc-city-select'),
		_x('Kegeyli Tumani', 'KA', 'ry-wc-city-select'),
		_x('Moynoq Tumani', 'KA', 'ry-wc-city-select'),
		_x('Nukus Tumani', 'KA', 'ry-wc-city-select'),
		_x('Qanliko`l Tumani', 'KA', 'ry-wc-city-select'),
		_x('Qo`ng`irot Tumani', 'KA', 'ry-wc-city-select'),
		_x('Qorao`zak Tumani', 'KA', 'ry-wc-city-select'),
		_x('Shumanay Tumani', 'KA', 'ry-wc-city-select'),
		_x('Taxtako`pir Tumani', 'KA', 'ry-wc-city-select'),
		_x('To`rtko`l Tumani', 'KA', 'ry-wc-city-select'),
		_x('Xo`jayli Tumani', 'KA', 'ry-wc-city-select'),
	],
	'NAPR' => [
		_x('Chortoq Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Chust Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Chust Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Kosonsoy Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Mingbuloq Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Namangan Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Norin Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Pap District', 'NAPR', 'ry-wc-city-select'),
		_x('Pop Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Turaqurghon Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Uchqurghon Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Uychi Tumani', 'NAPR', 'ry-wc-city-select'),
		_x('Yangiqo`rg`on Tumani', 'NAPR', 'ry-wc-city-select'),
	],
	'NAPR2' => [
		_x('Konimex Tumani', 'NAPR2', 'ry-wc-city-select'),
		_x('Navbahor Tumani', 'NAPR2', 'ry-wc-city-select'),
		_x('Navbakhor Tumani', 'NAPR2', 'ry-wc-city-select'),
		_x('Navoiy Tumani', 'NAPR2', 'ry-wc-city-select'),
		_x('Nurota Tumani', 'NAPR2', 'ry-wc-city-select'),
		_x('Qiziltepa Tumani', 'NAPR2', 'ry-wc-city-select'),
		_x('Tomdi Tumani', 'NAPR2', 'ry-wc-city-select'),
		_x('Uchkuduk District', 'NAPR2', 'ry-wc-city-select'),
		_x('Xatirchi Tumani', 'NAPR2', 'ry-wc-city-select'),
	],
	'QAPR' => [
		_x('Chiroqchi Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Dehqonobod Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('G`uzor Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Guzar District', 'QAPR', 'ry-wc-city-select'),
		_x('Kamashi District', 'QAPR', 'ry-wc-city-select'),
		_x('Kasbi Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Kitob Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Koson Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Mirishkar', 'QAPR', 'ry-wc-city-select'),
		_x('Mirishkor Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Muborak Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Nishon Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Qamashi Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Qarshi Shahri', 'QAPR', 'ry-wc-city-select'),
		_x('Qarshi Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Shahrisabz Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Usmon Yusupov Tumani', 'QAPR', 'ry-wc-city-select'),
		_x('Yakkabog` Tumani', 'QAPR', 'ry-wc-city-select'),
	],
	'SAVI' => [
		_x('Bulung`ur Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Chelak Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Go`zalkent Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Ishtixon Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Jomboy Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Kattaqo`rg`on Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Narpay Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Nurobod Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Oqdaryo Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Oqtosh Shahri', 'SAVI', 'ry-wc-city-select'),
		_x('Pastdarg`om Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Pastdargom', 'SAVI', 'ry-wc-city-select'),
		_x('Paxtachi Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Payariq Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Qo`shrabot Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Samarqand Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Toyloq District', 'SAVI', 'ry-wc-city-select'),
		_x('Toyloq Tumani', 'SAVI', 'ry-wc-city-select'),
		_x('Urgut Shahri', 'SAVI', 'ry-wc-city-select'),
		_x('Urgut Tumani', 'SAVI', 'ry-wc-city-select'),
	],
	'SI' => [
		_x('Bakht Shahri', 'SI', 'ry-wc-city-select'),
		_x('Bayaut', 'SI', 'ry-wc-city-select'),
		_x('Boyowut Tumani', 'SI', 'ry-wc-city-select'),
		_x('Guliston Shahri', 'SI', 'ry-wc-city-select'),
		_x('Guliston Tumani', 'SI', 'ry-wc-city-select'),
		_x('Khovos Tumani', 'SI', 'ry-wc-city-select'),
		_x('Mehnatobod Tumani', 'SI', 'ry-wc-city-select'),
		_x('Mirzaobod Tumani', 'SI', 'ry-wc-city-select'),
		_x('Oqoltin Tumani', 'SI', 'ry-wc-city-select'),
		_x('Sayhunobod Tumani', 'SI', 'ry-wc-city-select'),
		_x('Sharof-Rashidow Tumani', 'SI', 'ry-wc-city-select'),
		_x('Shirin Shahri', 'SI', 'ry-wc-city-select'),
		_x('Sirdaryo Shahri', 'SI', 'ry-wc-city-select'),
		_x('Sirdaryo Tumani', 'SI', 'ry-wc-city-select'),
		_x('Yangiyer Shahri', 'SI', 'ry-wc-city-select'),
	],
	'SUVI' => [
		_x('Angor Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Bandikhon Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Boysun Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Denov Shahri', 'SUVI', 'ry-wc-city-select'),
		_x('Denov Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Jarqo`rg`on Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Muzrabod Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Oltinsoy Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Qiziriq Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Qumqurghon Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Sariosiyo Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Sherobod Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Sho`rchi Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Termiz Shahri', 'SUVI', 'ry-wc-city-select'),
		_x('Uzun Tumani', 'SUVI', 'ry-wc-city-select'),
		_x('Yangiyul Tumani', 'SUVI', 'ry-wc-city-select'),
	],
	'TOSH' => [
		_x('Akmal Ikromow Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Bektemir Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Chilonzor Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Hamza Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Mirobod Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Mirzo Ulug`bek Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Shaykhontohur Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Sirgali Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Sobir Rahimov Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Yakkasaroy Tumani', 'TOSH', 'ry-wc-city-select'),
		_x('Yunusobod Tumani', 'TOSH', 'ry-wc-city-select'),
	],
	'TOVI' => [
		_x('Angren Shahri', 'TOVI', 'ry-wc-city-select'),
		_x('Bekobod Shahri', 'TOVI', 'ry-wc-city-select'),
		_x('Bekobod Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Buka Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Bustonliq Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Chinoz Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Chirchiq Shahri', 'TOVI', 'ry-wc-city-select'),
		_x('Ohangaron Shahri', 'TOVI', 'ry-wc-city-select'),
		_x('Ohangaron Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Olmaliq Shahri', 'TOVI', 'ry-wc-city-select'),
		_x('Oqqurghon Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Parkent Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Piskent Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Qibray Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Quyi Chirchiq Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Toshkent Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Urta Chirchiq Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Yangiobod Shahri', 'TOVI', 'ry-wc-city-select'),
		_x('Yuqori Chirchiq Tumani', 'TOVI', 'ry-wc-city-select'),
		_x('Zangiota Tumani', 'TOVI', 'ry-wc-city-select'),
	],
	'XOVI' => [
		_x('Boghot Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Gurlan Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Hazorasp Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Khiwa Shahri', 'XOVI', 'ry-wc-city-select'),
		_x('Khiwa Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Khonqa Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Pitnak Shahri', 'XOVI', 'ry-wc-city-select'),
		_x('Qushkupir Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Showot Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Urganch Shahri', 'XOVI', 'ry-wc-city-select'),
		_x('Urganch Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Yangiariq Tumani', 'XOVI', 'ry-wc-city-select'),
		_x('Yangibozor Tumani', 'XOVI', 'ry-wc-city-select'),
	],
	]
];