<?php
/**
 * Bolivarian Republic of Venezuela places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'VE' => [
	'MUALARTO' => [
		_x('Parroquia Rodriguez Dominguez', 'MUALARTO', 'ry-wc-city-select'),
		_x('Parroquia Sabaneta', 'MUALARTO', 'ry-wc-city-select'),
	],
	'MUANELBL' => [
		_x('Parroquia El Canton', 'MUANELBL', 'ry-wc-city-select'),
		_x('Parroquia Puerto Vivas', 'MUANELBL', 'ry-wc-city-select'),
		_x('Parroquia Santa Cruz de Guacas', 'MUANELBL', 'ry-wc-city-select'),
	],
	'MUANJOSU' => [
		_x('Parroquia Andres Bello', 'MUANJOSU', 'ry-wc-city-select'),
		_x('Parroquia Nicolas Pulido', 'MUANJOSU', 'ry-wc-city-select'),
		_x('Parroquia Ticoporo', 'MUANJOSU', 'ry-wc-city-select'),
	],
	'MUAR' => [
		_x('Parroquia Arismendi', 'MUAR', 'ry-wc-city-select'),
		_x('Parroquia Guadarrama', 'MUAR', 'ry-wc-city-select'),
		_x('Parroquia La Union', 'MUAR', 'ry-wc-city-select'),
		_x('Parroquia San Antonio', 'MUAR', 'ry-wc-city-select'),
	],
	'MUBA' => [
		_x('Parroquia Alfredo Arvelo Larriva', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Alto Barinas', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Barinas', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Corazon de Jesus', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Dominga Ortiz de Paez', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia El Carmen', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Juan Antonio Rodriguez Domingu', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Manuel Palacio Fajardo', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Ramon Ignacio Mendez', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Romulo Betancourt', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia San Silvestre', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Santa Ines', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Santa Lucia', 'MUBA', 'ry-wc-city-select'),
		_x('Parroquia Torunos', 'MUBA', 'ry-wc-city-select'),
	],
	'MUBO' => [
		_x('Parroquia Altamira', 'MUBO', 'ry-wc-city-select'),
		_x('Parroquia Barinitas', 'MUBO', 'ry-wc-city-select'),
		_x('Parroquia Calderas', 'MUBO', 'ry-wc-city-select'),
	],
	'MUCRPA' => [
		_x('Parroquia Barrancas', 'MUCRPA', 'ry-wc-city-select'),
		_x('Parroquia El Socorro', 'MUCRPA', 'ry-wc-city-select'),
		_x('Parroquia Masparrito', 'MUCRPA', 'ry-wc-city-select'),
	],
	'MUEZZA' => [
		_x('Parroquia Jose Ignacio del Pumar', 'MUEZZA', 'ry-wc-city-select'),
		_x('Parroquia Pedro Briceno Mendez', 'MUEZZA', 'ry-wc-city-select'),
		_x('Parroquia Ramon Ignacio Mendez', 'MUEZZA', 'ry-wc-city-select'),
		_x('Parroquia Santa Barbara', 'MUEZZA', 'ry-wc-city-select'),
	],
	'MULI' => [
		_x('Parroquia 23 de Enero', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Altagracia', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Antimano', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Candelaria', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Caricuao', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Catedral', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Coche', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia El Junquito', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia El Paraiso', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia El Recreo', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia El Valle', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia La Pastora', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia La Vega', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Macarao', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia San Agustin', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia San Bernardino', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia San Jose', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia San Juan', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia San Pedro', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Santa Rosalia', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Santa Teresa', 'MULI', 'ry-wc-city-select'),
		_x('Parroquia Sucre', 'MULI', 'ry-wc-city-select'),
	],
	'MUOB' => [
		_x('Parroquia El Real', 'MUOB', 'ry-wc-city-select'),
		_x('Parroquia La Luz', 'MUOB', 'ry-wc-city-select'),
		_x('Parroquia Los Guasimitos', 'MUOB', 'ry-wc-city-select'),
		_x('Parroquia Obispos', 'MUOB', 'ry-wc-city-select'),
	],
	'MUPE' => [
		_x('Parroquia Ciudad Bolivia', 'MUPE', 'ry-wc-city-select'),
		_x('Parroquia Ignacio Briceno', 'MUPE', 'ry-wc-city-select'),
		_x('Parroquia Jose Felix Ribas', 'MUPE', 'ry-wc-city-select'),
		_x('Parroquia Paez', 'MUPE', 'ry-wc-city-select'),
	],
	'MURO' => [
		_x('Parroquia Dolores', 'MURO', 'ry-wc-city-select'),
		_x('Parroquia Libertad', 'MURO', 'ry-wc-city-select'),
		_x('Parroquia Palacios Fajardo', 'MURO', 'ry-wc-city-select'),
		_x('Parroquia Santa Rosa', 'MURO', 'ry-wc-city-select'),
		_x('Parroquia Simon Rodriguez', 'MURO', 'ry-wc-city-select'),
	],
	'MUSIBO' => [
		_x('Parroquia Rafael Urdaneta', 'MUSIBO', 'ry-wc-city-select'),
	],
	'MUSO' => [
		_x('Parroquia Ciudad de Nutrias', 'MUSO', 'ry-wc-city-select'),
		_x('Parroquia El Regalo', 'MUSO', 'ry-wc-city-select'),
		_x('Parroquia Puerto de Nutrias', 'MUSO', 'ry-wc-city-select'),
		_x('Parroquia Santa Catalina', 'MUSO', 'ry-wc-city-select'),
		_x('Parroquia Simon Bolivar', 'MUSO', 'ry-wc-city-select'),
	],
	'MUVA' => [
		_x('Miguel Pena', 'MUVA', 'ry-wc-city-select'),
	],
	'MUVARO' => [
		_x('Parroquia La Victoria', 'MUVARO', 'ry-wc-city-select'),
		_x('Parroquia Raul Cuenca', 'MUVARO', 'ry-wc-city-select'),
	],
	'MUVA2' => [
		_x('Caraballeda', 'MUVA2', 'ry-wc-city-select'),
		_x('Carayaca', 'MUVA2', 'ry-wc-city-select'),
		_x('Carlos Soublette', 'MUVA2', 'ry-wc-city-select'),
		_x('Caruao', 'MUVA2', 'ry-wc-city-select'),
		_x('Catia La Mar', 'MUVA2', 'ry-wc-city-select'),
		_x('El Junko', 'MUVA2', 'ry-wc-city-select'),
		_x('La Guaira', 'MUVA2', 'ry-wc-city-select'),
		_x('Macuto', 'MUVA2', 'ry-wc-city-select'),
		_x('Maiquetia', 'MUVA2', 'ry-wc-city-select'),
		_x('Naiguata', 'MUVA2', 'ry-wc-city-select'),
		_x('Urimare', 'MUVA2', 'ry-wc-city-select'),
	],
	'DEAM' => [
		_x('Municipio Antonio Diaz', 'DEAM', 'ry-wc-city-select'),
		_x('Municipio Casacoima', 'DEAM', 'ry-wc-city-select'),
		_x('Municipio Pedernales', 'DEAM', 'ry-wc-city-select'),
		_x('Municipio Tucupita', 'DEAM', 'ry-wc-city-select'),
	],
	'ESAM' => [
		_x('Municipio Autonomo Alto Orinoco', 'ESAM', 'ry-wc-city-select'),
		_x('Municipio Autonomo Atabapo', 'ESAM', 'ry-wc-city-select'),
		_x('Municipio Autonomo Atures', 'ESAM', 'ry-wc-city-select'),
		_x('Municipio Autonomo Autana', 'ESAM', 'ry-wc-city-select'),
		_x('Municipio Autonomo Manapiare', 'ESAM', 'ry-wc-city-select'),
		_x('Municipio Autonomo Maroa', 'ESAM', 'ry-wc-city-select'),
		_x('Municipio Autonomo Rio Negro', 'ESAM', 'ry-wc-city-select'),
	],
	'ESAN' => [
		_x('Municipio Anaco', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Aragua', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Fernando de Penalver', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Francisco de Miranda', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Francisco del Carmen Carvajal', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Guanta', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Independencia', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Jose Gregorio Monagas', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Juan Antonio Sotillo', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Juan Manuel Cajigal', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Libertad', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Manuel Ezequiel Bruzual', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Pedro Maria Freites', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Piritu', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio San Jose de Guanipa', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio San Juan de Capistrano', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Santa Ana', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Simon Bolivar', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Simon Rodriguez', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Sir Arthur Mc Gregor', 'ESAN', 'ry-wc-city-select'),
		_x('Municipio Turistico Diego Bautista Urban', 'ESAN', 'ry-wc-city-select'),
	],
	'ESAP' => [
		_x('Municipio Achaguas', 'ESAP', 'ry-wc-city-select'),
		_x('Municipio Biruaca', 'ESAP', 'ry-wc-city-select'),
		_x('Municipio Munoz', 'ESAP', 'ry-wc-city-select'),
		_x('Municipio Paez', 'ESAP', 'ry-wc-city-select'),
		_x('Municipio Pedro Camejo', 'ESAP', 'ry-wc-city-select'),
		_x('Municipio Romulo Gallegos', 'ESAP', 'ry-wc-city-select'),
		_x('Municipio San Fernando', 'ESAP', 'ry-wc-city-select'),
	],
	'ESAR' => [
		_x('Municipio Bolivar', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Camatagua', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Francisco Linares Alcantara', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Girardot', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Jose Angel Lamas', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Jose Felix Ribas', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Jose Rafael Revenga', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Libertador', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Mario Briceno Iragorry', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Ocumare de La Costa de Oro', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio San Casimiro', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio San Sebastian', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Santiago Marino', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Santos Michelena', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Tovar', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Urdaneta', 'ESAR', 'ry-wc-city-select'),
		_x('Municipio Zamora', 'ESAR', 'ry-wc-city-select'),
	],
	'ESBO' => [
		_x('Bolivariano Angostura', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Caroni', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Cedeno', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio El Callao', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Gran Sabana', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Heres', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Padre Pedro Chien', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Piar', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Roscio', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Sifontes', 'ESBO', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESBO', 'ry-wc-city-select'),
	],
	'ESCA' => [
		_x('Municipio Bejuma', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Carlos Arvelo', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Diego Ibarra', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Guacara', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Juan Jose Mora', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Libertador', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Los Guayos', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Miranda', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Montalban', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Naguanagua', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio Puerto Cabello', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio San Diego', 'ESCA', 'ry-wc-city-select'),
		_x('Municipio San Joaquin', 'ESCA', 'ry-wc-city-select'),
	],
	'ESCO' => [
		_x('Municipio Anzoategui', 'ESCO', 'ry-wc-city-select'),
		_x('Municipio Falcon', 'ESCO', 'ry-wc-city-select'),
		_x('Municipio Girardot', 'ESCO', 'ry-wc-city-select'),
		_x('Municipio Lima Blanco', 'ESCO', 'ry-wc-city-select'),
		_x('Municipio Pao de San Juan Bautista', 'ESCO', 'ry-wc-city-select'),
		_x('Municipio Ricaurte', 'ESCO', 'ry-wc-city-select'),
		_x('Municipio Romulo Gallegos', 'ESCO', 'ry-wc-city-select'),
		_x('Municipio San Carlos', 'ESCO', 'ry-wc-city-select'),
		_x('Municipio Tinaco', 'ESCO', 'ry-wc-city-select'),
	],
	'ESFA' => [
		_x('Municipio Acosta', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Bolivar', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Buchivacoa', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Cacique Manaure', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Carirubana', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Colina', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Dabajuro', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Democracia', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Falcon', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Federacion', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Jacura', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Los Taques', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Mauroa', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Miranda', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Monsenor Iturriza', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Palmasola', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Petit', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Piritu', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio San Francisco', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Silva', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Tocopero', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Union', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Urumaco', 'ESFA', 'ry-wc-city-select'),
		_x('Municipio Zamora', 'ESFA', 'ry-wc-city-select'),
	],
	'ESGU' => [
		_x('Municipio Camaguan', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Chaguaramas', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio El Socorro', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Francisco de Miranda', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Jose Felix Ribas', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Jose Tadeo Monagas', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Juan German Roscio', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Julian Mellado', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Las Mercedes', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Leonardo Infante', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Ortiz', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Pedro Zaraza', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio San Geronimo de Guayabal', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio San Jose de Guaribe', 'ESGU', 'ry-wc-city-select'),
		_x('Municipio Santa Maria de Ipire', 'ESGU', 'ry-wc-city-select'),
	],
	'ESLA' => [
		_x('Municipio Andres Eloy Blanco', 'ESLA', 'ry-wc-city-select'),
		_x('Municipio Crespo', 'ESLA', 'ry-wc-city-select'),
		_x('Municipio Iribarren', 'ESLA', 'ry-wc-city-select'),
		_x('Municipio Jimenez', 'ESLA', 'ry-wc-city-select'),
		_x('Municipio Moran', 'ESLA', 'ry-wc-city-select'),
		_x('Municipio Palavecino', 'ESLA', 'ry-wc-city-select'),
		_x('Municipio Simon Planas', 'ESLA', 'ry-wc-city-select'),
		_x('Municipio Torres', 'ESLA', 'ry-wc-city-select'),
		_x('Municipio Urdaneta', 'ESLA', 'ry-wc-city-select'),
	],
	'ESME' => [
		_x('Municipio Alberto Adriani', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Andres Bello', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Antonio Pinto Salinas', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Aricagua', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Arzobispo Chacon', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Campo Elias', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Caracciolo Parra Olmedo', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Cardenal Quintero', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Guaraque', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Julio Cesar Salas', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Justo Briceno', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Libertador', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Miranda', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Obispo Ramos de Lora', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Padre Noguera', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Pueblo Llano', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Rangel', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Rivas Davila', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Santos Marquina', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Tovar', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Tulio Febres Cordero', 'ESME', 'ry-wc-city-select'),
		_x('Municipio Zea', 'ESME', 'ry-wc-city-select'),
	],
	'ESMO' => [
		_x('Municipio Acosta', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Aguasay', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Bolivar', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Caripe', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Cedeno', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Ezequiel Zamora', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Libertador', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Maturin', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Piar', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Punceres', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Santa Barbara', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Sotillo', 'ESMO', 'ry-wc-city-select'),
		_x('Municipio Uracoa', 'ESMO', 'ry-wc-city-select'),
	],
	'ESNUES' => [
		_x('Municipio Antolin del Campo', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Arismendi', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Diaz', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Garcia', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Gomez', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Maneiro', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Marcano', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Marino', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Peninsula de Macanao', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Tubores', 'ESNUES', 'ry-wc-city-select'),
		_x('Municipio Villalba', 'ESNUES', 'ry-wc-city-select'),
	],
	'ESPO' => [
		_x('Municipio Agua Blanca', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Araure', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Esteller', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Guanare', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Guanarito', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Monsenor Jose Vicente de Unda', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Ospino', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Paez', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Papelon', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio San Genaro de Boconoito', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio San Rafael de Onoto', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Santa Rosalia', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESPO', 'ry-wc-city-select'),
		_x('Municipio Turen', 'ESPO', 'ry-wc-city-select'),
	],
	'ESSU' => [
		_x('Municipio Andres Eloy Blanco', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Andres Mata', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Arismendi', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Benitez', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Bermudez', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Bolivar', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Cajigal', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Cruz Salmeron Acosta', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Libertador', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Marino', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Mejia', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Montes', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Ribero', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESSU', 'ry-wc-city-select'),
		_x('Municipio Valdez', 'ESSU', 'ry-wc-city-select'),
	],
	'ESTA' => [
		_x('Municipio Andres Bello', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Antonio Romulo Costa', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Ayacucho', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Bolivar', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Cardenas', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Cordoba', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Fernandez Feo', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Francisco de Miranda', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Garcia de Hevia', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Guasimos', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Independencia', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Jauregui', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Jose Maria Vargas', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Junin', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Libertad', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Libertador', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Lobatera', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Michelena', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Panamericano', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Pedro Maria Urena', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Rafael Urdaneta', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Samuel Dario Maldonado', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio San Cristobal', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio San Judas Tadeo', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Seboruco', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Simon Rodriguez', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Torbes', 'ESTA', 'ry-wc-city-select'),
		_x('Municipio Uribante', 'ESTA', 'ry-wc-city-select'),
	],
	'ESTR' => [
		_x('Municipio Andres Bello', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Bocono', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Bolivar', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Candelaria', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Carache', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Escuque', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Jose Felipe Marquez Canizales', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Juan Vicente Campo Elias', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio La Ceiba', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Miranda', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Monte Carmelo', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Motatan', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Pampan', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Pampanito', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Rafael Rangel', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio San Rafael de Carvajal', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Trujillo', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Urdaneta', 'ESTR', 'ry-wc-city-select'),
		_x('Municipio Valera', 'ESTR', 'ry-wc-city-select'),
	],
	'ESYA' => [
		_x('Municipio Aristides Bastidas', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Bolivar', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Bruzual', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Cocorote', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Independencia', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Jose Antonio Paez', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio La Trinidad', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Manuel Monge', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Nirgua', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Pena', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio San Felipe', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Urachiche', 'ESYA', 'ry-wc-city-select'),
		_x('Municipio Veroes', 'ESYA', 'ry-wc-city-select'),
	],
	'ESZU' => [
		_x('Municipio Almirante Padilla', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Baralt', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Cabimas', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Catatumbo', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Colon', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Francisco Javier Pulgar', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Jesus Enrique Lossada', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Jesus Maria Semprun', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio La Canada de Urdaneta', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Lagunillas', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Machiques de Perija', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Mara', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Maracaibo', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Miranda', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Paez', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Rosario de Perija', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio San Francisco', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Santa Rita', 'ESZU', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'ESZU', 'ry-wc-city-select'),
	],
	'MI' => [
		_x('Municipio Acevedo', 'MI', 'ry-wc-city-select'),
		_x('Municipio Andres Bello', 'MI', 'ry-wc-city-select'),
		_x('Municipio Baruta', 'MI', 'ry-wc-city-select'),
		_x('Municipio Brion', 'MI', 'ry-wc-city-select'),
		_x('Municipio Buroz', 'MI', 'ry-wc-city-select'),
		_x('Municipio Carrizal', 'MI', 'ry-wc-city-select'),
		_x('Municipio Chacao', 'MI', 'ry-wc-city-select'),
		_x('Municipio Cristobal Rojas', 'MI', 'ry-wc-city-select'),
		_x('Municipio El Hatillo', 'MI', 'ry-wc-city-select'),
		_x('Municipio Guaicaipuro', 'MI', 'ry-wc-city-select'),
		_x('Municipio Independencia', 'MI', 'ry-wc-city-select'),
		_x('Municipio Lander', 'MI', 'ry-wc-city-select'),
		_x('Municipio Los Salias', 'MI', 'ry-wc-city-select'),
		_x('Municipio Paez', 'MI', 'ry-wc-city-select'),
		_x('Municipio Paz Castillo', 'MI', 'ry-wc-city-select'),
		_x('Municipio Pedro Gual', 'MI', 'ry-wc-city-select'),
		_x('Municipio Plaza', 'MI', 'ry-wc-city-select'),
		_x('Municipio Simon Bolivar', 'MI', 'ry-wc-city-select'),
		_x('Municipio Sucre', 'MI', 'ry-wc-city-select'),
		_x('Municipio Urdaneta', 'MI', 'ry-wc-city-select'),
		_x('Municipio Zamora', 'MI', 'ry-wc-city-select'),
	],
	]
];