<?php
/**
 * Republic of Yemen places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'YE' => [
	'JA' => [
		_x('Bani Waqid', 'JA', 'ry-wc-city-select'),
	],
	'AL' => [
		_x('Rab` al Hadrami', 'AL', 'ry-wc-city-select'),
	],
	'BAGO' => [
		_x('Al Arsh', 'BAGO', 'ry-wc-city-select'),
		_x('Al Bayda City', 'BAGO', 'ry-wc-city-select'),
		_x('Al Bayda', 'BAGO', 'ry-wc-city-select'),
		_x('Al Malagim', 'BAGO', 'ry-wc-city-select'),
		_x('Al Quraishyah', 'BAGO', 'ry-wc-city-select'),
		_x('Ar Ryashyyah', 'BAGO', 'ry-wc-city-select'),
		_x('As Sawadiyah', 'BAGO', 'ry-wc-city-select'),
		_x('As Sawmaah', 'BAGO', 'ry-wc-city-select'),
		_x('Ash Sharafayn', 'BAGO', 'ry-wc-city-select'),
		_x('At Taffah', 'BAGO', 'ry-wc-city-select'),
		_x('Az Zahir', 'BAGO', 'ry-wc-city-select'),
		_x('Dhi Naim', 'BAGO', 'ry-wc-city-select'),
		_x('Maswarah', 'BAGO', 'ry-wc-city-select'),
		_x('Mukayras', 'BAGO', 'ry-wc-city-select'),
		_x('Naman', 'BAGO', 'ry-wc-city-select'),
		_x('Nati', 'BAGO', 'ry-wc-city-select'),
		_x('Rada', 'BAGO', 'ry-wc-city-select'),
		_x('Radman Al Awad', 'BAGO', 'ry-wc-city-select'),
		_x('Sabah', 'BAGO', 'ry-wc-city-select'),
		_x('Wald Rabi', 'BAGO', 'ry-wc-city-select'),
	],
	'MA' => [
		_x('Al Ghaydah', 'MA', 'ry-wc-city-select'),
		_x('Al Masilah', 'MA', 'ry-wc-city-select'),
		_x('Hat', 'MA', 'ry-wc-city-select'),
		_x('Hawf', 'MA', 'ry-wc-city-select'),
		_x('Huswain', 'MA', 'ry-wc-city-select'),
		_x('Manar', 'MA', 'ry-wc-city-select'),
		_x('Qishn', 'MA', 'ry-wc-city-select'),
		_x('Sayhut', 'MA', 'ry-wc-city-select'),
		_x('Shahan', 'MA', 'ry-wc-city-select'),
	],
	'MA2' => [
		_x('Al Khabt', 'MA2', 'ry-wc-city-select'),
		_x('Al Mahwait', 'MA2', 'ry-wc-city-select'),
		_x('Al Mahwait City', 'MA2', 'ry-wc-city-select'),
		_x('Ar Rujum', 'MA2', 'ry-wc-city-select'),
		_x('At Tawilah', 'MA2', 'ry-wc-city-select'),
		_x('Bani Sad', 'MA2', 'ry-wc-city-select'),
		_x('Hufash', 'MA2', 'ry-wc-city-select'),
		_x('Milhan', 'MA2', 'ry-wc-city-select'),
		_x('Shibam Kawkaban', 'MA2', 'ry-wc-city-select'),
	],
	'AMAS' => [
		_x('Al Wahdah', 'AMAS', 'ry-wc-city-select'),
		_x('As Sabain', 'AMAS', 'ry-wc-city-select'),
		_x('Assafiyah', 'AMAS', 'ry-wc-city-select'),
		_x('At Tahrir', 'AMAS', 'ry-wc-city-select'),
		_x('Aththaorah', 'AMAS', 'ry-wc-city-select'),
		_x('Azzal', 'AMAS', 'ry-wc-city-select'),
		_x('Bani Al Harith', 'AMAS', 'ry-wc-city-select'),
		_x('Maain', 'AMAS', 'ry-wc-city-select'),
		_x('Old City', 'AMAS', 'ry-wc-city-select'),
		_x('Shuaub', 'AMAS', 'ry-wc-city-select'),
	],
	'IB' => [
		_x('Al Udayn', 'IB', 'ry-wc-city-select'),
		_x('Al Dhihar', 'IB', 'ry-wc-city-select'),
		_x('Al Makhadir', 'IB', 'ry-wc-city-select'),
		_x('Al Mashannah', 'IB', 'ry-wc-city-select'),
		_x('Al Qafr', 'IB', 'ry-wc-city-select'),
		_x('An Nadirah', 'IB', 'ry-wc-city-select'),
		_x('Ar Radmah', 'IB', 'ry-wc-city-select'),
		_x('As Sabrah', 'IB', 'ry-wc-city-select'),
		_x('As Saddah', 'IB', 'ry-wc-city-select'),
		_x('As Sayyani', 'IB', 'ry-wc-city-select'),
		_x('Ash Shair', 'IB', 'ry-wc-city-select'),
		_x('Badan', 'IB', 'ry-wc-city-select'),
		_x('Dhi as Sufal', 'IB', 'ry-wc-city-select'),
		_x('Far Al Udayn', 'IB', 'ry-wc-city-select'),
		_x('Hazm Al Udayn', 'IB', 'ry-wc-city-select'),
		_x('Hubaysh', 'IB', 'ry-wc-city-select'),
		_x('Ibb', 'IB', 'ry-wc-city-select'),
		_x('Jiblah', 'IB', 'ry-wc-city-select'),
		_x('Mudhaykhirah', 'IB', 'ry-wc-city-select'),
		_x('Yarim', 'IB', 'ry-wc-city-select'),
	],
	'MUAD' => [
		_x('Al Buraiqeh', 'MUAD', 'ry-wc-city-select'),
		_x('Al Mansura', 'MUAD', 'ry-wc-city-select'),
		_x('Al Mualla', 'MUAD', 'ry-wc-city-select'),
		_x('Ash Shaikh Outhman', 'MUAD', 'ry-wc-city-select'),
		_x('Attawahi', 'MUAD', 'ry-wc-city-select'),
		_x('Craiter', 'MUAD', 'ry-wc-city-select'),
		_x('Dar Sad', 'MUAD', 'ry-wc-city-select'),
		_x('Khur Maksar', 'MUAD', 'ry-wc-city-select'),
	],
	'MUAM' => [
		_x('Al Ashah', 'MUAM', 'ry-wc-city-select'),
		_x('Al Madan', 'MUAM', 'ry-wc-city-select'),
		_x('Al Qaflah', 'MUAM', 'ry-wc-city-select'),
		_x('As Sawd', 'MUAM', 'ry-wc-city-select'),
		_x('As Sudah', 'MUAM', 'ry-wc-city-select'),
		_x('Bani Suraim', 'MUAM', 'ry-wc-city-select'),
		_x('Dhi Bin', 'MUAM', 'ry-wc-city-select'),
		_x('Habur Zulaymah', 'MUAM', 'ry-wc-city-select'),
		_x('Harf Sufyan', 'MUAM', 'ry-wc-city-select'),
		_x('Hooth', 'MUAM', 'ry-wc-city-select'),
		_x('Iyal Surayh', 'MUAM', 'ry-wc-city-select'),
		_x('Jabal Iyal Yazid', 'MUAM', 'ry-wc-city-select'),
		_x('Khamir', 'MUAM', 'ry-wc-city-select'),
		_x('Kharif', 'MUAM', 'ry-wc-city-select'),
		_x('Maswar', 'MUAM', 'ry-wc-city-select'),
		_x('Raydah', 'MUAM', 'ry-wc-city-select'),
		_x('Shaharah', 'MUAM', 'ry-wc-city-select'),
		_x('Suwayr', 'MUAM', 'ry-wc-city-select'),
		_x('Thula', 'MUAM', 'ry-wc-city-select'),
		_x('`Amran', 'MUAM', 'ry-wc-city-select'),
	],
	'MUAB' => [
		_x('Ahwar', 'MUAB', 'ry-wc-city-select'),
		_x('Al Mahfad', 'MUAB', 'ry-wc-city-select'),
		_x('Al Wadea', 'MUAB', 'ry-wc-city-select'),
		_x('Jayshan', 'MUAB', 'ry-wc-city-select'),
		_x('Khanfir', 'MUAB', 'ry-wc-city-select'),
		_x('Lawdar', 'MUAB', 'ry-wc-city-select'),
		_x('Mudiyah', 'MUAB', 'ry-wc-city-select'),
		_x('Rasad', 'MUAB', 'ry-wc-city-select'),
		_x('Sarar', 'MUAB', 'ry-wc-city-select'),
		_x('Sibah', 'MUAB', 'ry-wc-city-select'),
		_x('Zingibar', 'MUAB', 'ry-wc-city-select'),
	],
	'MUDH' => [
		_x('Al Hada', 'MUDH', 'ry-wc-city-select'),
		_x('Al Manar', 'MUDH', 'ry-wc-city-select'),
		_x('Dawran Aness', 'MUDH', 'ry-wc-city-select'),
		_x('Jabal Ash sharq', 'MUDH', 'ry-wc-city-select'),
		_x('Jahran', 'MUDH', 'ry-wc-city-select'),
		_x('Madinat Dhamar', 'MUDH', 'ry-wc-city-select'),
		_x('Maghirib Ans', 'MUDH', 'ry-wc-city-select'),
		_x('Mayfaat Anss', 'MUDH', 'ry-wc-city-select'),
		_x('Utmah', 'MUDH', 'ry-wc-city-select'),
		_x('Wusab Al Ali', 'MUDH', 'ry-wc-city-select'),
		_x('Wusab As Safil', 'MUDH', 'ry-wc-city-select'),
		_x('`Ans', 'MUDH', 'ry-wc-city-select'),
	],
	'MUHA' => [
		_x('Ad Dis', 'MUHA', 'ry-wc-city-select'),
		_x('Adh Dhliaah', 'MUHA', 'ry-wc-city-select'),
		_x('Al Abr', 'MUHA', 'ry-wc-city-select'),
		_x('Al Mukalla', 'MUHA', 'ry-wc-city-select'),
		_x('Al Mukalla City', 'MUHA', 'ry-wc-city-select'),
		_x('Al Qaf', 'MUHA', 'ry-wc-city-select'),
		_x('Al Qatn', 'MUHA', 'ry-wc-city-select'),
		_x('Amd', 'MUHA', 'ry-wc-city-select'),
		_x('Ar Raydah Wa Qusayar', 'MUHA', 'ry-wc-city-select'),
		_x('As Sawm', 'MUHA', 'ry-wc-city-select'),
		_x('Ash Shihr', 'MUHA', 'ry-wc-city-select'),
		_x('Brom Mayfa', 'MUHA', 'ry-wc-city-select'),
		_x('Dawan', 'MUHA', 'ry-wc-city-select'),
		_x('Ghayl Ba Wazir', 'MUHA', 'ry-wc-city-select'),
		_x('Ghayl Bin Yamin', 'MUHA', 'ry-wc-city-select'),
		_x('Hagr As Saiar', 'MUHA', 'ry-wc-city-select'),
		_x('Hajr', 'MUHA', 'ry-wc-city-select'),
		_x('Huraidhah', 'MUHA', 'ry-wc-city-select'),
		_x('Rakhyah', 'MUHA', 'ry-wc-city-select'),
		_x('Rumah', 'MUHA', 'ry-wc-city-select'),
		_x('Sah', 'MUHA', 'ry-wc-city-select'),
		_x('Sayun', 'MUHA', 'ry-wc-city-select'),
		_x('Shibam', 'MUHA', 'ry-wc-city-select'),
		_x('Tarim', 'MUHA', 'ry-wc-city-select'),
		_x('Thamud', 'MUHA', 'ry-wc-city-select'),
		_x('Wadi Al Ayn', 'MUHA', 'ry-wc-city-select'),
		_x('Yabuth', 'MUHA', 'ry-wc-city-select'),
		_x('Zamakh wa Manwakh', 'MUHA', 'ry-wc-city-select'),
	],
	'MUHA2' => [
		_x('Abs', 'MUHA2', 'ry-wc-city-select'),
		_x('Aflah Al Yaman', 'MUHA2', 'ry-wc-city-select'),
		_x('Aflah Ash Shawm', 'MUHA2', 'ry-wc-city-select'),
		_x('Al Jamimah', 'MUHA2', 'ry-wc-city-select'),
		_x('Al Maghrabah', 'MUHA2', 'ry-wc-city-select'),
		_x('Al Mahabishah', 'MUHA2', 'ry-wc-city-select'),
		_x('Al Miftah', 'MUHA2', 'ry-wc-city-select'),
		_x('Ash Shaghadirah', 'MUHA2', 'ry-wc-city-select'),
		_x('Ash Shahil', 'MUHA2', 'ry-wc-city-select'),
		_x('Aslem', 'MUHA2', 'ry-wc-city-select'),
		_x('Bakil Al Mir', 'MUHA2', 'ry-wc-city-select'),
		_x('Bani Al Awam', 'MUHA2', 'ry-wc-city-select'),
		_x('Bani Qais', 'MUHA2', 'ry-wc-city-select'),
		_x('Hajjah', 'MUHA2', 'ry-wc-city-select'),
		_x('Hajjah', 'MUHA2', 'ry-wc-city-select'),
		_x('Harad District', 'MUHA2', 'ry-wc-city-select'),
		_x('Hayran', 'MUHA2', 'ry-wc-city-select'),
		_x('Khayran Al Muharraq', 'MUHA2', 'ry-wc-city-select'),
		_x('Kuaydinah', 'MUHA2', 'ry-wc-city-select'),
		_x('Kuhlan Affar', 'MUHA2', 'ry-wc-city-select'),
		_x('Kuhlan Ash Sharaf', 'MUHA2', 'ry-wc-city-select'),
		_x('Kushar', 'MUHA2', 'ry-wc-city-select'),
		_x('Mabyan', 'MUHA2', 'ry-wc-city-select'),
		_x('Midi', 'MUHA2', 'ry-wc-city-select'),
		_x('Mustaba', 'MUHA2', 'ry-wc-city-select'),
		_x('Najrah', 'MUHA2', 'ry-wc-city-select'),
		_x('Qafl Shamer', 'MUHA2', 'ry-wc-city-select'),
		_x('Qarah', 'MUHA2', 'ry-wc-city-select'),
		_x('Sharas', 'MUHA2', 'ry-wc-city-select'),
		_x('Wadhrah', 'MUHA2', 'ry-wc-city-select'),
		_x('Washhah', 'MUHA2', 'ry-wc-city-select'),
	],
	'MULA' => [
		_x('Al  Hawtah', 'MULA', 'ry-wc-city-select'),
		_x('Al Had', 'MULA', 'ry-wc-city-select'),
		_x('Al Madaribah Wa Al Arah', 'MULA', 'ry-wc-city-select'),
		_x('Al Maflahy', 'MULA', 'ry-wc-city-select'),
		_x('Al Maqatirah', 'MULA', 'ry-wc-city-select'),
		_x('Al Milah', 'MULA', 'ry-wc-city-select'),
		_x('Al Musaymir', 'MULA', 'ry-wc-city-select'),
		_x('Al Qabbaytah', 'MULA', 'ry-wc-city-select'),
		_x('Habil Jabr', 'MULA', 'ry-wc-city-select'),
		_x('Halimayn', 'MULA', 'ry-wc-city-select'),
		_x('Radfan', 'MULA', 'ry-wc-city-select'),
		_x('Tuban', 'MULA', 'ry-wc-city-select'),
		_x('Tur Al Bahah', 'MULA', 'ry-wc-city-select'),
		_x('Yafaa', 'MULA', 'ry-wc-city-select'),
		_x('Yahr', 'MULA', 'ry-wc-city-select'),
	],
	'MUMA' => [
		_x('Al Abdiyah', 'MUMA', 'ry-wc-city-select'),
		_x('Al Jubah', 'MUMA', 'ry-wc-city-select'),
		_x('Bidbadah', 'MUMA', 'ry-wc-city-select'),
		_x('Harib', 'MUMA', 'ry-wc-city-select'),
		_x('Harib Al Qaramish', 'MUMA', 'ry-wc-city-select'),
		_x('Jabal Murad', 'MUMA', 'ry-wc-city-select'),
		_x('Mahliyah', 'MUMA', 'ry-wc-city-select'),
		_x('Majzar', 'MUMA', 'ry-wc-city-select'),
		_x('Marib', 'MUMA', 'ry-wc-city-select'),
		_x('Marib City', 'MUMA', 'ry-wc-city-select'),
		_x('Medghal', 'MUMA', 'ry-wc-city-select'),
		_x('Raghwan', 'MUMA', 'ry-wc-city-select'),
		_x('Rahabah', 'MUMA', 'ry-wc-city-select'),
		_x('Sirwah', 'MUMA', 'ry-wc-city-select'),
	],
	'MURA' => [
		_x('Al Jabin', 'MURA', 'ry-wc-city-select'),
		_x('As Salafiyah', 'MURA', 'ry-wc-city-select'),
		_x('Bilad At Taam', 'MURA', 'ry-wc-city-select'),
		_x('Kusmah', 'MURA', 'ry-wc-city-select'),
		_x('Mazhar', 'MURA', 'ry-wc-city-select'),
	],
	'MUSA' => [
		_x('Al Dhaher', 'MUSA', 'ry-wc-city-select'),
		_x('Al Hashwah', 'MUSA', 'ry-wc-city-select'),
		_x('As Safra', 'MUSA', 'ry-wc-city-select'),
		_x('Baqim', 'MUSA', 'ry-wc-city-select'),
		_x('Ghamr', 'MUSA', 'ry-wc-city-select'),
		_x('Haydan', 'MUSA', 'ry-wc-city-select'),
		_x('Kitaf wa Al Boqee', 'MUSA', 'ry-wc-city-select'),
		_x('Majz', 'MUSA', 'ry-wc-city-select'),
		_x('Monabbih', 'MUSA', 'ry-wc-city-select'),
		_x('Qatabir', 'MUSA', 'ry-wc-city-select'),
		_x('Razih', 'MUSA', 'ry-wc-city-select'),
		_x('Sadah', 'MUSA', 'ry-wc-city-select'),
		_x('Sahar', 'MUSA', 'ry-wc-city-select'),
		_x('Saqayn', 'MUSA', 'ry-wc-city-select'),
		_x('Shadaa', 'MUSA', 'ry-wc-city-select'),
	],
	'MUTA' => [
		_x('Al Maafer', 'MUTA', 'ry-wc-city-select'),
		_x('Al Mawasit', 'MUTA', 'ry-wc-city-select'),
		_x('Al Misrakh', 'MUTA', 'ry-wc-city-select'),
		_x('Al Mudhaffar', 'MUTA', 'ry-wc-city-select'),
		_x('Al Mukha', 'MUTA', 'ry-wc-city-select'),
		_x('Al Qahirah', 'MUTA', 'ry-wc-city-select'),
		_x('Al Waziiyah', 'MUTA', 'ry-wc-city-select'),
		_x('As Silw', 'MUTA', 'ry-wc-city-select'),
		_x('Ash Shamayatayn', 'MUTA', 'ry-wc-city-select'),
		_x('At Taizziyah', 'MUTA', 'ry-wc-city-select'),
		_x('Dhubab', 'MUTA', 'ry-wc-city-select'),
		_x('Dimnat Khadir', 'MUTA', 'ry-wc-city-select'),
		_x('Hayfan', 'MUTA', 'ry-wc-city-select'),
		_x('Jabal Habashy', 'MUTA', 'ry-wc-city-select'),
		_x('Maqbanah', 'MUTA', 'ry-wc-city-select'),
		_x('Mashraa Wa Hadnan', 'MUTA', 'ry-wc-city-select'),
		_x('Mawiyah', 'MUTA', 'ry-wc-city-select'),
		_x('Mawza', 'MUTA', 'ry-wc-city-select'),
		_x('Sabir Al Mawadim', 'MUTA', 'ry-wc-city-select'),
		_x('Salh', 'MUTA', 'ry-wc-city-select'),
		_x('Sama', 'MUTA', 'ry-wc-city-select'),
		_x('Sharab Ar Rawnah', 'MUTA', 'ry-wc-city-select'),
		_x('Sharab As Salam', 'MUTA', 'ry-wc-city-select'),
	],
	'MUDA' => [
		_x('Ad Dhalee', 'MUDA', 'ry-wc-city-select'),
		_x('Al Azariq', 'MUDA', 'ry-wc-city-select'),
		_x('Al Husha', 'MUDA', 'ry-wc-city-select'),
		_x('Al Hussein', 'MUDA', 'ry-wc-city-select'),
		_x('Ash Shuayb', 'MUDA', 'ry-wc-city-select'),
		_x('Damt', 'MUDA', 'ry-wc-city-select'),
		_x('Jahaf', 'MUDA', 'ry-wc-city-select'),
		_x('Juban', 'MUDA', 'ry-wc-city-select'),
		_x('Qaatabah', 'MUDA', 'ry-wc-city-select'),
	],
	'MUHU' => [
		_x('Ad Dahi', 'MUHU', 'ry-wc-city-select'),
		_x('Ad Durayhimi', 'MUHU', 'ry-wc-city-select'),
		_x('Al Garrahi', 'MUHU', 'ry-wc-city-select'),
		_x('Al Hajjaylah', 'MUHU', 'ry-wc-city-select'),
		_x('Al Hali', 'MUHU', 'ry-wc-city-select'),
		_x('Al Hawak', 'MUHU', 'ry-wc-city-select'),
		_x('Al Mansuriyah', 'MUHU', 'ry-wc-city-select'),
		_x('Al Marawiah', 'MUHU', 'ry-wc-city-select'),
		_x('Al Mighlaf', 'MUHU', 'ry-wc-city-select'),
		_x('Al Mina', 'MUHU', 'ry-wc-city-select'),
		_x('Al Munirah', 'MUHU', 'ry-wc-city-select'),
		_x('Al Qanawis', 'MUHU', 'ry-wc-city-select'),
		_x('As Salif', 'MUHU', 'ry-wc-city-select'),
		_x('As Sukhnah', 'MUHU', 'ry-wc-city-select'),
		_x('At Tuhayat', 'MUHU', 'ry-wc-city-select'),
		_x('Az Zaydiyah', 'MUHU', 'ry-wc-city-select'),
		_x('Az Zuhrah', 'MUHU', 'ry-wc-city-select'),
		_x('Bajil', 'MUHU', 'ry-wc-city-select'),
		_x('Bayt al Faqih', 'MUHU', 'ry-wc-city-select'),
		_x('Bura', 'MUHU', 'ry-wc-city-select'),
		_x('Hays', 'MUHU', 'ry-wc-city-select'),
		_x('Jabal Ras', 'MUHU', 'ry-wc-city-select'),
		_x('Kamaran', 'MUHU', 'ry-wc-city-select'),
		_x('Khawlan', 'MUHU', 'ry-wc-city-select'),
		_x('Zabid', 'MUHU', 'ry-wc-city-select'),
	],
	'MUJA' => [
		_x('Al Ghayl', 'MUJA', 'ry-wc-city-select'),
		_x('Al Hazm', 'MUJA', 'ry-wc-city-select'),
		_x('Al Humaydat', 'MUJA', 'ry-wc-city-select'),
		_x('Al Khalq', 'MUJA', 'ry-wc-city-select'),
		_x('Al Maslub', 'MUJA', 'ry-wc-city-select'),
		_x('Al Matammah', 'MUJA', 'ry-wc-city-select'),
		_x('Al Maton', 'MUJA', 'ry-wc-city-select'),
		_x('Az Zahir', 'MUJA', 'ry-wc-city-select'),
		_x('Bart al `Anan', 'MUJA', 'ry-wc-city-select'),
		_x('Khabb wa ash Shaaf', 'MUJA', 'ry-wc-city-select'),
		_x('Kharab Al Marashi', 'MUJA', 'ry-wc-city-select'),
		_x('Rajuzah', 'MUJA', 'ry-wc-city-select'),
	],
	'SA' => [
		_x('Al Haymah Ad Dakhiliyah', 'SA', 'ry-wc-city-select'),
		_x('Al Haymah Al Kharijiyah', 'SA', 'ry-wc-city-select'),
		_x('Al Husn', 'SA', 'ry-wc-city-select'),
		_x('Arhab', 'SA', 'ry-wc-city-select'),
		_x('Attyal', 'SA', 'ry-wc-city-select'),
		_x('Bani Dhabyan', 'SA', 'ry-wc-city-select'),
		_x('Bani Hushaysh', 'SA', 'ry-wc-city-select'),
		_x('Bani Matar', 'SA', 'ry-wc-city-select'),
		_x('Bilad Ar Rus', 'SA', 'ry-wc-city-select'),
		_x('Hamdan', 'SA', 'ry-wc-city-select'),
		_x('Jihanah', 'SA', 'ry-wc-city-select'),
		_x('Khwlan', 'SA', 'ry-wc-city-select'),
		_x('Manakhah', 'SA', 'ry-wc-city-select'),
		_x('Nihm', 'SA', 'ry-wc-city-select'),
		_x('Safan', 'SA', 'ry-wc-city-select'),
		_x('Sanhan', 'SA', 'ry-wc-city-select'),
	],
	'SH' => [
		_x('Ain', 'SH', 'ry-wc-city-select'),
		_x('Al Talh', 'SH', 'ry-wc-city-select'),
		_x('Ar Rawdah', 'SH', 'ry-wc-city-select'),
		_x('Arma', 'SH', 'ry-wc-city-select'),
		_x('As Said', 'SH', 'ry-wc-city-select'),
		_x('Ataq', 'SH', 'ry-wc-city-select'),
		_x('Bayhan', 'SH', 'ry-wc-city-select'),
		_x('Dhar', 'SH', 'ry-wc-city-select'),
		_x('Habban', 'SH', 'ry-wc-city-select'),
		_x('Hatib', 'SH', 'ry-wc-city-select'),
		_x('Jardan', 'SH', 'ry-wc-city-select'),
		_x('Mayfaa', 'SH', 'ry-wc-city-select'),
		_x('Merkhah Al Ulya', 'SH', 'ry-wc-city-select'),
		_x('Merkhah As Sufla', 'SH', 'ry-wc-city-select'),
		_x('Nisab', 'SH', 'ry-wc-city-select'),
		_x('Rudum', 'SH', 'ry-wc-city-select'),
		_x('Usaylan', 'SH', 'ry-wc-city-select'),
	],
	'SO' => [
		_x('Hidaybu', 'SO', 'ry-wc-city-select'),
		_x('Qulensya Wa Abd Al Kuri', 'SO', 'ry-wc-city-select'),
	],
	]
];