<?php
/**
 * Republic of South Africa places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'ZA' => [
	'ALNZDIMU' => [
		_x('Matatiele', 'ALNZDIMU', 'ry-wc-city-select'),
		_x('Mbizana', 'ALNZDIMU', 'ry-wc-city-select'),
		_x('Ntabankulu', 'ALNZDIMU', 'ry-wc-city-select'),
		_x('Umzimvubu', 'ALNZDIMU', 'ry-wc-city-select'),
	],
	'AMDIMU' => [
		_x('Dannhauser', 'AMDIMU', 'ry-wc-city-select'),
		_x('Emadlangeni', 'AMDIMU', 'ry-wc-city-select'),
		_x('Newcastle', 'AMDIMU', 'ry-wc-city-select'),
	],
	'AMDIMU2' => [
		_x('Amahlathi', 'AMDIMU2', 'ry-wc-city-select'),
		_x('Great Kei', 'AMDIMU2', 'ry-wc-city-select'),
		_x('Mbhashe', 'AMDIMU2', 'ry-wc-city-select'),
		_x('Mnquma', 'AMDIMU2', 'ry-wc-city-select'),
		_x('Ngqushwa', 'AMDIMU2', 'ry-wc-city-select'),
		_x('Nkonkobe', 'AMDIMU2', 'ry-wc-city-select'),
		_x('Nxuba', 'AMDIMU2', 'ry-wc-city-select'),
	],
	'BOPLDIMU' => [
		_x('Kgetlengrivier', 'BOPLDIMU', 'ry-wc-city-select'),
		_x('Local Municipality of Madibeng', 'BOPLDIMU', 'ry-wc-city-select'),
		_x('Moretele', 'BOPLDIMU', 'ry-wc-city-select'),
		_x('Moses Kotane', 'BOPLDIMU', 'ry-wc-city-select'),
		_x('Rustenburg', 'BOPLDIMU', 'ry-wc-city-select'),
	],
	'BUCIMEMU' => [
		_x('Buffalo City', 'BUCIMEMU', 'ry-wc-city-select'),
	],
	'CAWIDIMU' => [
		_x('Breede Valley', 'CAWIDIMU', 'ry-wc-city-select'),
		_x('Drakenstein', 'CAWIDIMU', 'ry-wc-city-select'),
		_x('Langeberg', 'CAWIDIMU', 'ry-wc-city-select'),
		_x('Stellenbosch', 'CAWIDIMU', 'ry-wc-city-select'),
		_x('Witzenberg', 'CAWIDIMU', 'ry-wc-city-select'),
	],
	'CADIMU' => [
		_x('Aganang', 'CADIMU', 'ry-wc-city-select'),
		_x('Blouberg', 'CADIMU', 'ry-wc-city-select'),
		_x('Lepele-Nkumpi', 'CADIMU', 'ry-wc-city-select'),
		_x('Molemole', 'CADIMU', 'ry-wc-city-select'),
		_x('Polokwane', 'CADIMU', 'ry-wc-city-select'),
	],
	'CEKADIMU' => [
		_x('Beaufort West', 'CEKADIMU', 'ry-wc-city-select'),
		_x('Laingsburg', 'CEKADIMU', 'ry-wc-city-select'),
		_x('Prince Albert', 'CEKADIMU', 'ry-wc-city-select'),
	],
	'CHHADIMU' => [
		_x('Emalahleni', 'CHHADIMU', 'ry-wc-city-select'),
		_x('Engcobo', 'CHHADIMU', 'ry-wc-city-select'),
		_x('Inkwanca', 'CHHADIMU', 'ry-wc-city-select'),
		_x('Intsika Yethu', 'CHHADIMU', 'ry-wc-city-select'),
		_x('Inxuba Yethemba', 'CHHADIMU', 'ry-wc-city-select'),
		_x('Lukanji', 'CHHADIMU', 'ry-wc-city-select'),
		_x('Sakhisizwe', 'CHHADIMU', 'ry-wc-city-select'),
		_x('Tsolwana', 'CHHADIMU', 'ry-wc-city-select'),
	],
	'CICATO' => [
		_x('City of Cape Town', 'CICATO', 'ry-wc-city-select'),
	],
	'CIJOMEMU' => [
		_x('City of Johannesburg', 'CIJOMEMU', 'ry-wc-city-select'),
	],
	'CITSMEMU' => [
		_x('City of Tshwane', 'CITSMEMU', 'ry-wc-city-select'),
	],
	'KEKADIMU' => [
		_x('City of Matlosana', 'KEKADIMU', 'ry-wc-city-select'),
		_x('Maquassi Hills', 'KEKADIMU', 'ry-wc-city-select'),
		_x('Tlokwe City Council', 'KEKADIMU', 'ry-wc-city-select'),
		_x('Ventersdorp', 'KEKADIMU', 'ry-wc-city-select'),
	],
	'RUSEMODIMU' => [
		_x('Greater Taung', 'RUSEMODIMU', 'ry-wc-city-select'),
		_x('Kagisano/Molopo', 'RUSEMODIMU', 'ry-wc-city-select'),
		_x('Lekwa-Teemane', 'RUSEMODIMU', 'ry-wc-city-select'),
		_x('Mamusa', 'RUSEMODIMU', 'ry-wc-city-select'),
		_x('Naledi', 'RUSEMODIMU', 'ry-wc-city-select'),
	],
	'EDDIMU' => [
		_x('Bitou', 'EDDIMU', 'ry-wc-city-select'),
		_x('George', 'EDDIMU', 'ry-wc-city-select'),
		_x('Hessequa', 'EDDIMU', 'ry-wc-city-select'),
		_x('Kannaland', 'EDDIMU', 'ry-wc-city-select'),
		_x('Knysna', 'EDDIMU', 'ry-wc-city-select'),
		_x('Mossel Bay', 'EDDIMU', 'ry-wc-city-select'),
		_x('Oudtshoorn', 'EDDIMU', 'ry-wc-city-select'),
	],
	'EHDI' => [
		_x('Bushbuckridge', 'EHDI', 'ry-wc-city-select'),
		_x('Mbombela', 'EHDI', 'ry-wc-city-select'),
		_x('Nkomazi', 'EHDI', 'ry-wc-city-select'),
		_x('Thaba Chweu', 'EHDI', 'ry-wc-city-select'),
		_x('Umjindi', 'EHDI', 'ry-wc-city-select'),
	],
	'EKMEMU' => [
		_x('Ekurhuleni', 'EKMEMU', 'ry-wc-city-select'),
	],
	'FEDADIMU' => [
		_x('Mafube', 'FEDADIMU', 'ry-wc-city-select'),
		_x('Metsimaholo', 'FEDADIMU', 'ry-wc-city-select'),
		_x('Moqhaka', 'FEDADIMU', 'ry-wc-city-select'),
		_x('Ngwathe', 'FEDADIMU', 'ry-wc-city-select'),
	],
	'FRBADIMU' => [
		_x('Dikgatlong', 'FRBADIMU', 'ry-wc-city-select'),
		_x('Magareng', 'FRBADIMU', 'ry-wc-city-select'),
		_x('Phokwane', 'FRBADIMU', 'ry-wc-city-select'),
		_x('Sol Plaatjie', 'FRBADIMU', 'ry-wc-city-select'),
	],
	'GESIDIMU' => [
		_x('Albert Luthuli', 'GESIDIMU', 'ry-wc-city-select'),
		_x('Dipaleseng', 'GESIDIMU', 'ry-wc-city-select'),
		_x('Govan Mbeki', 'GESIDIMU', 'ry-wc-city-select'),
		_x('Lekwa', 'GESIDIMU', 'ry-wc-city-select'),
		_x('Mkhondo', 'GESIDIMU', 'ry-wc-city-select'),
		_x('Msukaligwa', 'GESIDIMU', 'ry-wc-city-select'),
		_x('Pixley Ka Seme', 'GESIDIMU', 'ry-wc-city-select'),
	],
	'JOGQDIMU' => [
		_x('Elundini', 'JOGQDIMU', 'ry-wc-city-select'),
		_x('Gariep', 'JOGQDIMU', 'ry-wc-city-select'),
		_x('Maletswai', 'JOGQDIMU', 'ry-wc-city-select'),
		_x('Senqu', 'JOGQDIMU', 'ry-wc-city-select'),
	],
	'JOTAGADIMU' => [
		_x('Ga-Segonyana', 'JOTAGADIMU', 'ry-wc-city-select'),
		_x('Gamagara', 'JOTAGADIMU', 'ry-wc-city-select'),
		_x('Joe Morolong', 'JOTAGADIMU', 'ry-wc-city-select'),
	],
	'LEDIMU' => [
		_x('Masilonyana', 'LEDIMU', 'ry-wc-city-select'),
		_x('Matjhabeng', 'LEDIMU', 'ry-wc-city-select'),
		_x('Nala', 'LEDIMU', 'ry-wc-city-select'),
		_x('Tokologo', 'LEDIMU', 'ry-wc-city-select'),
		_x('Tswelopele', 'LEDIMU', 'ry-wc-city-select'),
	],
	'MAMEMU' => [
		_x('Mangaung', 'MAMEMU', 'ry-wc-city-select'),
	],
	'MODIMU' => [
		_x('Ba-Phalaborwa', 'MODIMU', 'ry-wc-city-select'),
		_x('Greater Giyani', 'MODIMU', 'ry-wc-city-select'),
		_x('Greater Letaba', 'MODIMU', 'ry-wc-city-select'),
		_x('Greater Tzaneen', 'MODIMU', 'ry-wc-city-select'),
		_x('Maruleng', 'MODIMU', 'ry-wc-city-select'),
	],
	'NADIMU' => [
		_x('Hantam', 'NADIMU', 'ry-wc-city-select'),
		_x('Kamiesberg', 'NADIMU', 'ry-wc-city-select'),
		_x('Karoo Hoogland', 'NADIMU', 'ry-wc-city-select'),
		_x('Khai-Ma', 'NADIMU', 'ry-wc-city-select'),
		_x('Nama Khoi', 'NADIMU', 'ry-wc-city-select'),
		_x('Richtersveld', 'NADIMU', 'ry-wc-city-select'),
	],
	'NEMABAMEMU' => [
		_x('Nelson Mandela Bay', 'NEMABAMEMU', 'ry-wc-city-select'),
	],
	'NGMOMODIMU' => [
		_x('Ditsobotla', 'NGMOMODIMU', 'ry-wc-city-select'),
		_x('Mafikeng', 'NGMOMODIMU', 'ry-wc-city-select'),
		_x('Ramotshere Moiloa', 'NGMOMODIMU', 'ry-wc-city-select'),
		_x('Ratlou', 'NGMOMODIMU', 'ry-wc-city-select'),
		_x('Tswaing', 'NGMOMODIMU', 'ry-wc-city-select'),
	],
	'NKDIMU' => [
		_x('Dr JS Moroka', 'NKDIMU', 'ry-wc-city-select'),
		_x('Emakhazeni', 'NKDIMU', 'ry-wc-city-select'),
		_x('Emalahleni', 'NKDIMU', 'ry-wc-city-select'),
		_x('Steve Tshwete', 'NKDIMU', 'ry-wc-city-select'),
		_x('Thembisile', 'NKDIMU', 'ry-wc-city-select'),
		_x('Victor Khanye', 'NKDIMU', 'ry-wc-city-select'),
	],
	'TADIMU' => [
		_x('King Sabata Dalindyebo', 'TADIMU', 'ry-wc-city-select'),
		_x('Mhlontlo', 'TADIMU', 'ry-wc-city-select'),
		_x('Ngquza Hill', 'TADIMU', 'ry-wc-city-select'),
		_x('Nyandeni', 'TADIMU', 'ry-wc-city-select'),
		_x('Port St Johns', 'TADIMU', 'ry-wc-city-select'),
	],
	'OVDIMU' => [
		_x('Cape Agulhas', 'OVDIMU', 'ry-wc-city-select'),
		_x('Overstrand', 'OVDIMU', 'ry-wc-city-select'),
		_x('Swellendam', 'OVDIMU', 'ry-wc-city-select'),
		_x('Theewaterskloof', 'OVDIMU', 'ry-wc-city-select'),
	],
	'PISEDIMU' => [
		_x('Emthanjeni', 'PISEDIMU', 'ry-wc-city-select'),
		_x('Kareeberg', 'PISEDIMU', 'ry-wc-city-select'),
		_x('Renosterberg', 'PISEDIMU', 'ry-wc-city-select'),
		_x('Siyancuma', 'PISEDIMU', 'ry-wc-city-select'),
		_x('Siyathemba', 'PISEDIMU', 'ry-wc-city-select'),
		_x('Thembelihle', 'PISEDIMU', 'ry-wc-city-select'),
		_x('Ubuntu', 'PISEDIMU', 'ry-wc-city-select'),
		_x('Umsobomvu', 'PISEDIMU', 'ry-wc-city-select'),
	],
	'SABADIMU' => [
		_x('Baviaans', 'SABADIMU', 'ry-wc-city-select'),
		_x('Blue Crane Route', 'SABADIMU', 'ry-wc-city-select'),
		_x('Camdeboo', 'SABADIMU', 'ry-wc-city-select'),
		_x('Ikwezi', 'SABADIMU', 'ry-wc-city-select'),
		_x('Kou-Kamma', 'SABADIMU', 'ry-wc-city-select'),
		_x('Kouga', 'SABADIMU', 'ry-wc-city-select'),
		_x('Makana', 'SABADIMU', 'ry-wc-city-select'),
		_x('Ndlambe', 'SABADIMU', 'ry-wc-city-select'),
		_x('Sundays River Valley', 'SABADIMU', 'ry-wc-city-select'),
	],
	'SEDIMU' => [
		_x('Emfuleni', 'SEDIMU', 'ry-wc-city-select'),
		_x('Lesedi', 'SEDIMU', 'ry-wc-city-select'),
		_x('Midvaal', 'SEDIMU', 'ry-wc-city-select'),
	],
	'SEDIMU2' => [
		_x('Elias Motsoaledi', 'SEDIMU2', 'ry-wc-city-select'),
		_x('Ephraim Mogale', 'SEDIMU2', 'ry-wc-city-select'),
		_x('Fetakgomo', 'SEDIMU2', 'ry-wc-city-select'),
		_x('Greater Tubatse', 'SEDIMU2', 'ry-wc-city-select'),
		_x('Makhuduthamaga', 'SEDIMU2', 'ry-wc-city-select'),
	],
	'SIDIMU' => [
		_x('Greater Kokstad', 'SIDIMU', 'ry-wc-city-select'),
		_x('Ingwe', 'SIDIMU', 'ry-wc-city-select'),
		_x('Kwa Sani', 'SIDIMU', 'ry-wc-city-select'),
		_x('Ubuhlebezwe', 'SIDIMU', 'ry-wc-city-select'),
		_x('Umzimkhulu', 'SIDIMU', 'ry-wc-city-select'),
	],
	'SIDIMU2' => [
		_x('!Kheis', 'SIDIMU2', 'ry-wc-city-select'),
		_x('//Khara Hais', 'SIDIMU2', 'ry-wc-city-select'),
		_x('Kai !Garib', 'SIDIMU2', 'ry-wc-city-select'),
		_x('Kgatelopele', 'SIDIMU2', 'ry-wc-city-select'),
		_x('Mier', 'SIDIMU2', 'ry-wc-city-select'),
		_x('Tsantsabane', 'SIDIMU2', 'ry-wc-city-select'),
	],
	'THMODIMU' => [
		_x('Dihlabeng', 'THMODIMU', 'ry-wc-city-select'),
		_x('Maluti a Phofung', 'THMODIMU', 'ry-wc-city-select'),
		_x('Mantsopa', 'THMODIMU', 'ry-wc-city-select'),
		_x('Nketoana', 'THMODIMU', 'ry-wc-city-select'),
		_x('Phumelela', 'THMODIMU', 'ry-wc-city-select'),
		_x('Setsoto', 'THMODIMU', 'ry-wc-city-select'),
	],
	'UGDIMU' => [
		_x('Ezingoleni', 'UGDIMU', 'ry-wc-city-select'),
		_x('Hibiscus Coast', 'UGDIMU', 'ry-wc-city-select'),
		_x('UMuziwabantu', 'UGDIMU', 'ry-wc-city-select'),
		_x('Umdoni', 'UGDIMU', 'ry-wc-city-select'),
		_x('Umzumbe', 'UGDIMU', 'ry-wc-city-select'),
		_x('Vulamehlo', 'UGDIMU', 'ry-wc-city-select'),
	],
	'VHDIMU' => [
		_x('Makhado', 'VHDIMU', 'ry-wc-city-select'),
		_x('Musina', 'VHDIMU', 'ry-wc-city-select'),
		_x('Mutale', 'VHDIMU', 'ry-wc-city-select'),
		_x('Thulamela', 'VHDIMU', 'ry-wc-city-select'),
	],
	'WADIMU' => [
		_x('Bela-Bela', 'WADIMU', 'ry-wc-city-select'),
		_x('Lephalale', 'WADIMU', 'ry-wc-city-select'),
		_x('Modimolle', 'WADIMU', 'ry-wc-city-select'),
		_x('Mogalakwena', 'WADIMU', 'ry-wc-city-select'),
		_x('Mookgopong', 'WADIMU', 'ry-wc-city-select'),
		_x('Thabazimbi', 'WADIMU', 'ry-wc-city-select'),
	],
	'WECODIMU' => [
		_x('Bergrivier', 'WECODIMU', 'ry-wc-city-select'),
		_x('Cederberg', 'WECODIMU', 'ry-wc-city-select'),
		_x('Matzikama', 'WECODIMU', 'ry-wc-city-select'),
		_x('Saldanha Bay', 'WECODIMU', 'ry-wc-city-select'),
		_x('Swartland', 'WECODIMU', 'ry-wc-city-select'),
	],
	'WERADIMU' => [
		_x('Merafong City', 'WERADIMU', 'ry-wc-city-select'),
		_x('Mogale City', 'WERADIMU', 'ry-wc-city-select'),
		_x('Randfontein', 'WERADIMU', 'ry-wc-city-select'),
		_x('Westonaria', 'WERADIMU', 'ry-wc-city-select'),
	],
	'XHDIMU' => [
		_x('Kopanong', 'XHDIMU', 'ry-wc-city-select'),
		_x('Letsemeng', 'XHDIMU', 'ry-wc-city-select'),
		_x('Mohokare', 'XHDIMU', 'ry-wc-city-select'),
		_x('Naledi', 'XHDIMU', 'ry-wc-city-select'),
	],
	'ZUDIMU' => [
		_x('Abaqulusi', 'ZUDIMU', 'ry-wc-city-select'),
		_x('Nongoma', 'ZUDIMU', 'ry-wc-city-select'),
		_x('UPhongolo', 'ZUDIMU', 'ry-wc-city-select'),
		_x('Ulundi', 'ZUDIMU', 'ry-wc-city-select'),
		_x('eDumbe', 'ZUDIMU', 'ry-wc-city-select'),
	],
	'ETMEMU' => [
		_x('Ethekwini', 'ETMEMU', 'ry-wc-city-select'),
	],
	'ILDIMU' => [
		_x('KwaDukuza', 'ILDIMU', 'ry-wc-city-select'),
		_x('Mandeni', 'ILDIMU', 'ry-wc-city-select'),
		_x('Maphumulo', 'ILDIMU', 'ry-wc-city-select'),
		_x('Ndwedwe', 'ILDIMU', 'ry-wc-city-select'),
	],
	'UMDIMU' => [
		_x('Impendle', 'UMDIMU', 'ry-wc-city-select'),
		_x('Mkhambathini', 'UMDIMU', 'ry-wc-city-select'),
		_x('Mooi Mpofana', 'UMDIMU', 'ry-wc-city-select'),
		_x('Richmond', 'UMDIMU', 'ry-wc-city-select'),
		_x('The Msunduzi', 'UMDIMU', 'ry-wc-city-select'),
		_x('uMngeni', 'UMDIMU', 'ry-wc-city-select'),
		_x('uMshwathi', 'UMDIMU', 'ry-wc-city-select'),
	],
	'UMDIMU2' => [
		_x('Hlabisa', 'UMDIMU2', 'ry-wc-city-select'),
		_x('Jozini', 'UMDIMU2', 'ry-wc-city-select'),
		_x('Mtubatuba', 'UMDIMU2', 'ry-wc-city-select'),
		_x('The Big 5 False Bay', 'UMDIMU2', 'ry-wc-city-select'),
		_x('Umhlabuyalingana', 'UMDIMU2', 'ry-wc-city-select'),
	],
	'UMDIMU3' => [
		_x('Endumeni', 'UMDIMU3', 'ry-wc-city-select'),
		_x('Msinga', 'UMDIMU3', 'ry-wc-city-select'),
		_x('Nqutu', 'UMDIMU3', 'ry-wc-city-select'),
		_x('Umvoti', 'UMDIMU3', 'ry-wc-city-select'),
	],
	'UTDIMU' => [
		_x('Emnambithi/Ladysmith', 'UTDIMU', 'ry-wc-city-select'),
		_x('Imbabazane', 'UTDIMU', 'ry-wc-city-select'),
		_x('Indaka', 'UTDIMU', 'ry-wc-city-select'),
		_x('Okhahlamba', 'UTDIMU', 'ry-wc-city-select'),
		_x('Umtshezi', 'UTDIMU', 'ry-wc-city-select'),
	],
	'UTDIMU2' => [
		_x('Mfolozi', 'UTDIMU2', 'ry-wc-city-select'),
		_x('Mthonjaneni', 'UTDIMU2', 'ry-wc-city-select'),
		_x('Nkandla', 'UTDIMU2', 'ry-wc-city-select'),
		_x('Ntambanana', 'UTDIMU2', 'ry-wc-city-select'),
		_x('uMhlathuze', 'UTDIMU2', 'ry-wc-city-select'),
		_x('uMlalazi', 'UTDIMU2', 'ry-wc-city-select'),
	],
	]
];