<?php
/**
 * Republic of Zambia places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'ZM' => [
	'CEPR' => [
		_x('Chibombo District', 'CEPR', 'ry-wc-city-select'),
		_x('Chisamba District', 'CEPR', 'ry-wc-city-select'),
		_x('Chitambo District', 'CEPR', 'ry-wc-city-select'),
		_x('Kabwe District', 'CEPR', 'ry-wc-city-select'),
		_x('Kapiri Mposhi', 'CEPR', 'ry-wc-city-select'),
		_x('Kapiri-Mposhi District', 'CEPR', 'ry-wc-city-select'),
		_x('Luano District', 'CEPR', 'ry-wc-city-select'),
		_x('Mkushi District', 'CEPR', 'ry-wc-city-select'),
		_x('Mumbwa District', 'CEPR', 'ry-wc-city-select'),
		_x('Ngabwe District', 'CEPR', 'ry-wc-city-select'),
		_x('Serenje District', 'CEPR', 'ry-wc-city-select'),
	],
	'COPR' => [
		_x('Chililabombwe District', 'COPR', 'ry-wc-city-select'),
		_x('Chingola District', 'COPR', 'ry-wc-city-select'),
		_x('Kalulushi District', 'COPR', 'ry-wc-city-select'),
		_x('Kitwe District', 'COPR', 'ry-wc-city-select'),
		_x('Luanshya District', 'COPR', 'ry-wc-city-select'),
		_x('Lufwanyama', 'COPR', 'ry-wc-city-select'),
		_x('Masaiti District', 'COPR', 'ry-wc-city-select'),
		_x('Mpongwe District', 'COPR', 'ry-wc-city-select'),
		_x('Mufulira District', 'COPR', 'ry-wc-city-select'),
		_x('Ndola District', 'COPR', 'ry-wc-city-select'),
		_x('Ndola Rural District', 'COPR', 'ry-wc-city-select'),
	],
	'EAPR' => [
		_x('Chadiza District', 'EAPR', 'ry-wc-city-select'),
		_x('Chipata District', 'EAPR', 'ry-wc-city-select'),
		_x('Katete District', 'EAPR', 'ry-wc-city-select'),
		_x('Lundazi District', 'EAPR', 'ry-wc-city-select'),
		_x('Mambwe', 'EAPR', 'ry-wc-city-select'),
		_x('Nyimba District', 'EAPR', 'ry-wc-city-select'),
		_x('Petauke District', 'EAPR', 'ry-wc-city-select'),
		_x('Sinda District', 'EAPR', 'ry-wc-city-select'),
		_x('Vubwi District', 'EAPR', 'ry-wc-city-select'),
	],
	'LUPR' => [
		_x('Chembe District', 'LUPR', 'ry-wc-city-select'),
		_x('Chienge', 'LUPR', 'ry-wc-city-select'),
		_x('Chipili District', 'LUPR', 'ry-wc-city-select'),
		_x('Kawambwa District', 'LUPR', 'ry-wc-city-select'),
		_x('Lunga District', 'LUPR', 'ry-wc-city-select'),
		_x('Mansa District', 'LUPR', 'ry-wc-city-select'),
		_x('Milenge', 'LUPR', 'ry-wc-city-select'),
		_x('Mwansabombwe District', 'LUPR', 'ry-wc-city-select'),
		_x('Mwense District', 'LUPR', 'ry-wc-city-select'),
		_x('Nchelenge District', 'LUPR', 'ry-wc-city-select'),
		_x('Samfya District', 'LUPR', 'ry-wc-city-select'),
	],
	'LUPR2' => [
		_x('Chilanga District', 'LUPR2', 'ry-wc-city-select'),
		_x('Chirundu District', 'LUPR2', 'ry-wc-city-select'),
		_x('Chongwe District', 'LUPR2', 'ry-wc-city-select'),
		_x('Kafue district', 'LUPR2', 'ry-wc-city-select'),
		_x('Luangwa District', 'LUPR2', 'ry-wc-city-select'),
		_x('Lusaka District', 'LUPR2', 'ry-wc-city-select'),
		_x('Rufunsa District', 'LUPR2', 'ry-wc-city-select'),
		_x('Shibuyunji District', 'LUPR2', 'ry-wc-city-select'),
	],
	'MUPR' => [
		_x('Chama District', 'MUPR', 'ry-wc-city-select'),
		_x('Chinsali District', 'MUPR', 'ry-wc-city-select'),
		_x('Isoka District', 'MUPR', 'ry-wc-city-select'),
		_x('Mafinga', 'MUPR', 'ry-wc-city-select'),
		_x('Mpika District', 'MUPR', 'ry-wc-city-select'),
		_x('Nakonde', 'MUPR', 'ry-wc-city-select'),
		_x('Shiwangandu District', 'MUPR', 'ry-wc-city-select'),
	],
	'NOPR' => [
		_x('Chavuma', 'NOPR', 'ry-wc-city-select'),
		_x('Ikelenge', 'NOPR', 'ry-wc-city-select'),
		_x('Kabompo District', 'NOPR', 'ry-wc-city-select'),
		_x('Kasempa District', 'NOPR', 'ry-wc-city-select'),
		_x('Manyinga District', 'NOPR', 'ry-wc-city-select'),
		_x('Mufumbwe', 'NOPR', 'ry-wc-city-select'),
		_x('Mwinilunga District', 'NOPR', 'ry-wc-city-select'),
		_x('Solwezi District', 'NOPR', 'ry-wc-city-select'),
		_x('Zambezi District', 'NOPR', 'ry-wc-city-select'),
	],
	'NOPR2' => [
		_x('Chilubi', 'NOPR2', 'ry-wc-city-select'),
		_x('Kaputa District', 'NOPR2', 'ry-wc-city-select'),
		_x('Kasama District', 'NOPR2', 'ry-wc-city-select'),
		_x('Luwingu District', 'NOPR2', 'ry-wc-city-select'),
		_x('Mbala District', 'NOPR2', 'ry-wc-city-select'),
		_x('Mporokoso District', 'NOPR2', 'ry-wc-city-select'),
		_x('Mpulungu District', 'NOPR2', 'ry-wc-city-select'),
		_x('Mungwi District', 'NOPR2', 'ry-wc-city-select'),
		_x('Nsama District', 'NOPR2', 'ry-wc-city-select'),
	],
	'SOPR' => [
		_x('Chikankata District', 'SOPR', 'ry-wc-city-select'),
		_x('Choma District', 'SOPR', 'ry-wc-city-select'),
		_x('Gwembe District', 'SOPR', 'ry-wc-city-select'),
		_x('Itezhi-Tezhi District', 'SOPR', 'ry-wc-city-select'),
		_x('Kalomo District', 'SOPR', 'ry-wc-city-select'),
		_x('Kazungula District', 'SOPR', 'ry-wc-city-select'),
		_x('Livingstone District', 'SOPR', 'ry-wc-city-select'),
		_x('Mazabuka District', 'SOPR', 'ry-wc-city-select'),
		_x('Monze District', 'SOPR', 'ry-wc-city-select'),
		_x('Namwala District', 'SOPR', 'ry-wc-city-select'),
		_x('Pemba District', 'SOPR', 'ry-wc-city-select'),
		_x('Siavonga District', 'SOPR', 'ry-wc-city-select'),
		_x('Sinazongwe District', 'SOPR', 'ry-wc-city-select'),
		_x('Zimba District', 'SOPR', 'ry-wc-city-select'),
	],
	'WEPR' => [
		_x('Kalabo District', 'WEPR', 'ry-wc-city-select'),
		_x('Kaoma District', 'WEPR', 'ry-wc-city-select'),
		_x('Limulunga District', 'WEPR', 'ry-wc-city-select'),
		_x('Luampa District', 'WEPR', 'ry-wc-city-select'),
		_x('Lukulu District', 'WEPR', 'ry-wc-city-select'),
		_x('Mitete District', 'WEPR', 'ry-wc-city-select'),
		_x('Mongu District', 'WEPR', 'ry-wc-city-select'),
		_x('Mulobezi District', 'WEPR', 'ry-wc-city-select'),
		_x('Mwandi District', 'WEPR', 'ry-wc-city-select'),
		_x('Nalolo District', 'WEPR', 'ry-wc-city-select'),
		_x('Nkeyema District', 'WEPR', 'ry-wc-city-select'),
		_x('Senanga District', 'WEPR', 'ry-wc-city-select'),
		_x('Sesheke District', 'WEPR', 'ry-wc-city-select'),
		_x('Shangombo', 'WEPR', 'ry-wc-city-select'),
		_x('Sikongo District', 'WEPR', 'ry-wc-city-select'),
		_x('Sioma District', 'WEPR', 'ry-wc-city-select'),
	],
	]
];