<?php

return [
    'TW' => [
        'TAIPEI CITY' => [
            [_x('Zhongzheng Dist', 'TW Taipei City', 'ry-wc-city-select'), '100'],
            [_x('Datong Dist', 'TW Taipei City', 'ry-wc-city-select'), '103'],
            [_x('Zhongshan Dist', 'TW Taipei City', 'ry-wc-city-select'), '104'],
            [_x('Songshan Dist', 'TW Taipei City', 'ry-wc-city-select'), '105'],
            [_x('Daan Dist', 'TW Taipei City', 'ry-wc-city-select'), '106'],
            [_x('Wanhua Dist', 'TW Taipei City', 'ry-wc-city-select'), '108'],
            [_x('Xinyi Dist', 'TW Taipei City', 'ry-wc-city-select'), '110'],
            [_x('Shilin Dist', 'TW Taipei City', 'ry-wc-city-select'), '111'],
            [_x('Beitou Dist', 'TW Taipei City', 'ry-wc-city-select'), '112'],
            [_x('Neihu Dist', 'TW Taipei City', 'ry-wc-city-select'), '114'],
            [_x('Nangang Dist', 'TW Taipei City', 'ry-wc-city-select'), '115'],
            [_x('Wenshan Dist', 'TW Taipei City', 'ry-wc-city-select'), '116']
        ],
        'KEELUNG CITY' => [
            [_x('Renai Dist', 'TW Keelung City', 'ry-wc-city-select'), '200'],
            [_x('Xinyi Dist', 'TW Keelung City', 'ry-wc-city-select'), '201'],
            [_x('Zhongzheng Dist', 'TW Keelung City', 'ry-wc-city-select'), '202'],
            [_x('Zhongshan Dist', 'TW Keelung City', 'ry-wc-city-select'), '203'],
            [_x('Anle Dist', 'TW Keelung City', 'ry-wc-city-select'), '204'],
            [_x('Nuannuan Dist', 'TW Keelung City', 'ry-wc-city-select'), '205'],
            [_x('Qidu Dist', 'TW Keelung City', 'ry-wc-city-select'), '206']
        ],
        'NEW TAIPEI CITY' => [
            [_x('Wanli Dist', 'TW New Taipei City', 'ry-wc-city-select'), '207'],
            [_x('Jinshan Dist', 'TW New Taipei City', 'ry-wc-city-select'), '208'],
            [_x('Banqiao Dist', 'TW New Taipei City', 'ry-wc-city-select'), '220'],
            [_x('Xizhi Dist', 'TW New Taipei City', 'ry-wc-city-select'), '221'],
            [_x('Shenkeng Dist', 'TW New Taipei City', 'ry-wc-city-select'), '222'],
            [_x('Shiding Dist', 'TW New Taipei City', 'ry-wc-city-select'), '223'],
            [_x('Ruifang Dist', 'TW New Taipei City', 'ry-wc-city-select'), '224'],
            [_x('Pingxi Dist', 'TW New Taipei City', 'ry-wc-city-select'), '226'],
            [_x('Shuangxi Dist', 'TW New Taipei City', 'ry-wc-city-select'), '227'],
            [_x('Gongliao Dist', 'TW New Taipei City', 'ry-wc-city-select'), '228'],
            [_x('Xindian Dist', 'TW New Taipei City', 'ry-wc-city-select'), '231'],
            [_x('Pinglin Dist', 'TW New Taipei City', 'ry-wc-city-select'), '232'],
            [_x('Wulai Dist', 'TW New Taipei City', 'ry-wc-city-select'), '233'],
            [_x('Yonghe Dist', 'TW New Taipei City', 'ry-wc-city-select'), '234'],
            [_x('Zhonghe Dist', 'TW New Taipei City', 'ry-wc-city-select'), '235'],
            [_x('Tucheng Dist', 'TW New Taipei City', 'ry-wc-city-select'), '236'],
            [_x('Sanxia Dist', 'TW New Taipei City', 'ry-wc-city-select'), '237'],
            [_x('Shulin Dist', 'TW New Taipei City', 'ry-wc-city-select'), '238'],
            [_x('Yingge Dist', 'TW New Taipei City', 'ry-wc-city-select'), '239'],
            [_x('Sanchong Dist', 'TW New Taipei City', 'ry-wc-city-select'), '241'],
            [_x('Xinzhuang Dist', 'TW New Taipei City', 'ry-wc-city-select'), '242'],
            [_x('Taishan Dist', 'TW New Taipei City', 'ry-wc-city-select'), '243'],
            [_x('Linkou Dist', 'TW New Taipei City', 'ry-wc-city-select'), '244'],
            [_x('Luzhou Dist', 'TW New Taipei City', 'ry-wc-city-select'), '247'],
            [_x('Wugu Dist', 'TW New Taipei City', 'ry-wc-city-select'), '248'],
            [_x('Bali Dist', 'TW New Taipei City', 'ry-wc-city-select'), '249'],
            [_x('Tamsui Dist', 'TW New Taipei City', 'ry-wc-city-select'), '251'],
            [_x('Sanzhi Dist', 'TW New Taipei City', 'ry-wc-city-select'), '252'],
            [_x('Shimen Dist', 'TW New Taipei City', 'ry-wc-city-select'), '253']
        ],
        'LIENCHIANG COUNTY' => [
            [_x('Nangan Township', 'TW Lienchiang County', 'ry-wc-city-select'), '209'],
            [_x('Beigan Township', 'TW Lienchiang County', 'ry-wc-city-select'), '210'],
            [_x('Juguang Township', 'TW Lienchiang County', 'ry-wc-city-select'), '211'],
            [_x('Dongyin Township', 'TW Lienchiang County', 'ry-wc-city-select'), '212']
        ],
        'YILAN COUNTY' => [
            [_x('Yilan City', 'TW Yilan County', 'ry-wc-city-select'), '260'],
            [_x('Toucheng Township', 'TW Yilan County', 'ry-wc-city-select'), '261'],
            [_x('Jiaoxi Township', 'TW Yilan County', 'ry-wc-city-select'), '262'],
            [_x('Zhuangwei Township', 'TW Yilan County', 'ry-wc-city-select'), '263'],
            [_x('Yuanshan Township', 'TW Yilan County', 'ry-wc-city-select'), '264'],
            [_x('Luodong Township', 'TW Yilan County', 'ry-wc-city-select'), '265'],
            [_x('Sanxing Township', 'TW Yilan County', 'ry-wc-city-select'), '266'],
            [_x('Datong Township', 'TW Yilan County', 'ry-wc-city-select'), '267'],
            [_x('Wujie Township', 'TW Yilan County', 'ry-wc-city-select'), '268'],
            [_x('Dongshan Township', 'TW Yilan County', 'ry-wc-city-select'), '269'],
            [_x('Suao Township', 'TW Yilan County', 'ry-wc-city-select'), '270'],
            [_x('Nanao Township', 'TW Yilan County', 'ry-wc-city-select'), '272']
        ],
        'HSINCHU CITY' => [
            [_x('East Dist', 'TW Hsinchu City', 'ry-wc-city-select'), '300'],
            [_x('North Dist', 'TW Hsinchu City', 'ry-wc-city-select'), '300'],
            [_x('Xiangshan Dist', 'TW Hsinchu City', 'ry-wc-city-select'), '300']
        ],
        'HSINCHU COUNTY' => [
            [_x('Zhubei City', 'TW Hsinchu County', 'ry-wc-city-select'), '302'],
            [_x('Hukou Township', 'TW Hsinchu County', 'ry-wc-city-select'), '303'],
            [_x('Xinfeng Township', 'TW Hsinchu County', 'ry-wc-city-select'), '304'],
            [_x('Xinpu Township', 'TW Hsinchu County', 'ry-wc-city-select'), '305'],
            [_x('Guanxi Township', 'TW Hsinchu County', 'ry-wc-city-select'), '306'],
            [_x('Qionglin Township', 'TW Hsinchu County', 'ry-wc-city-select'), '307'],
            [_x('Baoshan Township', 'TW Hsinchu County', 'ry-wc-city-select'), '308'],
            [_x('Zhudong Township', 'TW Hsinchu County', 'ry-wc-city-select'), '310'],
            [_x('Wufeng Township', 'TW Hsinchu County', 'ry-wc-city-select'), '311'],
            [_x('Hengshan Township', 'TW Hsinchu County', 'ry-wc-city-select'), '312'],
            [_x('Jianshi Township', 'TW Hsinchu County', 'ry-wc-city-select'), '313'],
            [_x('Beipu Township', 'TW Hsinchu County', 'ry-wc-city-select'), '314'],
            [_x('Emei Township', 'TW Hsinchu County', 'ry-wc-city-select'), '315']
        ],
        'TAOYUAN CITY' => [
            [_x('Zhongli Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '320'],
            [_x('Pingzhen Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '324'],
            [_x('Longtan Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '325'],
            [_x('Yangmei Dist', 'TW Taoyuan City City', 'ry-wc-city-select'), '326'],
            [_x('Xinwu Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '327'],
            [_x('Guanyin Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '328'],
            [_x('Taoyuan Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '330'],
            [_x('Guishan Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '333'],
            [_x('Bade Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '334'],
            [_x('Daxi Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '335'],
            [_x('Fuxing Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '336'],
            [_x('Dayuan Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '337'],
            [_x('Luzhu Dist', 'TW Taoyuan City', 'ry-wc-city-select'), '338']
        ],
        'MIAOLI COUNTY' => [
            [_x('Zhunan Township', 'TW Miaoli County', 'ry-wc-city-select'), '350'],
            [_x('Toufen City', 'TW Miaoli County', 'ry-wc-city-select'), '351'],
            [_x('Sanwan Township', 'TW Miaoli County', 'ry-wc-city-select'), '352'],
            [_x('Nanzhuang Township', 'TW Miaoli County', 'ry-wc-city-select'), '353'],
            [_x('Shitan Township', 'TW Miaoli County', 'ry-wc-city-select'), '354'],
            [_x('Houlong Township', 'TW Miaoli County', 'ry-wc-city-select'), '356'],
            [_x('Tongxiao Township', 'TW Miaoli County', 'ry-wc-city-select'), '357'],
            [_x('Yuanli Township', 'TW Miaoli County', 'ry-wc-city-select'), '358'],
            [_x('Miaoli City', 'TW Miaoli County', 'ry-wc-city-select'), '360'],
            [_x('Zaoqiao Township', 'TW Miaoli County', 'ry-wc-city-select'), '361'],
            [_x('Touwu Township', 'TW Miaoli County', 'ry-wc-city-select'), '362'],
            [_x('Gongguan Township', 'TW Miaoli County', 'ry-wc-city-select'), '363'],
            [_x('Dahu Township', 'TW Miaoli County', 'ry-wc-city-select'), '364'],
            [_x('Taian Township', 'TW Miaoli County', 'ry-wc-city-select'), '365'],
            [_x('Tongluo Township', 'TW Miaoli County', 'ry-wc-city-select'), '366'],
            [_x('Sanyi Township', 'TW Miaoli County', 'ry-wc-city-select'), '367'],
            [_x('Xihu Township', 'TW Miaoli County', 'ry-wc-city-select'), '368'],
            [_x('Zhuolan Township', 'TW Miaoli County', 'ry-wc-city-select'), '369']
        ],
        'TAICHUNG CITY' => [
            [_x('Central Dist', 'TW Taichung City', 'ry-wc-city-select'), '400'],
            [_x('East Dist', 'TW Taichung City', 'ry-wc-city-select'), '401'],
            [_x('South Dist', 'TW Taichung City', 'ry-wc-city-select'), '402'],
            [_x('West Dist', 'TW Taichung City', 'ry-wc-city-select'), '403'],
            [_x('North Dist', 'TW Taichung City', 'ry-wc-city-select'), '404'],
            [_x('Beitun Dist', 'TW Taichung City', 'ry-wc-city-select'), '406'],
            [_x('Xitun Dist', 'TW Taichung City', 'ry-wc-city-select'), '407'],
            [_x('Nantun Dist', 'TW Taichung City', 'ry-wc-city-select'), '408'],
            [_x('Taiping Dist', 'TW Taichung City', 'ry-wc-city-select'), '411'],
            [_x('Dali Dist', 'TW Taichung City', 'ry-wc-city-select'), '412'],
            [_x('Wufeng Dist', 'TW Taichung City', 'ry-wc-city-select'), '413'],
            [_x('Wuri Dist', 'TW Taichung City', 'ry-wc-city-select'), '414'],
            [_x('Fengyuan Dist', 'TW Taichung City', 'ry-wc-city-select'), '420'],
            [_x('Houli Dist', 'TW Taichung City', 'ry-wc-city-select'), '421'],
            [_x('Shigang Dist', 'TW Taichung City', 'ry-wc-city-select'), '422'],
            [_x('Dongshi Dist', 'TW Taichung City', 'ry-wc-city-select'), '423'],
            [_x('Heping Dist', 'TW Taichung City', 'ry-wc-city-select'), '424'],
            [_x('Xinshe Dist', 'TW Taichung City', 'ry-wc-city-select'), '426'],
            [_x('Tanzi Dist', 'TW Taichung City', 'ry-wc-city-select'), '427'],
            [_x('Daya Dist', 'TW Taichung City', 'ry-wc-city-select'), '428'],
            [_x('Shengang Dist', 'TW Taichung City', 'ry-wc-city-select'), '429'],
            [_x('Dadu Dist', 'TW Taichung City', 'ry-wc-city-select'), '432'],
            [_x('Shalu Dist', 'TW Taichung City', 'ry-wc-city-select'), '433'],
            [_x('Longjing Dist', 'TW Taichung City', 'ry-wc-city-select'), '434'],
            [_x('Wuqi Dist', 'TW Taichung City', 'ry-wc-city-select'), '435'],
            [_x('Qingshui Dist', 'TW Taichung City', 'ry-wc-city-select'), '436'],
            [_x('Dajia Dist', 'TW Taichung City', 'ry-wc-city-select'), '437'],
            [_x('Waipu Dist', 'TW Taichung City', 'ry-wc-city-select'), '438'],
            [_x('Daan Dist', 'TW Taichung City', 'ry-wc-city-select'), '439']
        ],
        'CHANGHUA COUNTY' => [
            [_x('Changhua City', 'TW Changhua County', 'ry-wc-city-select'), '500'],
            [_x('Fenyuan Township', 'TW Changhua County', 'ry-wc-city-select'), '502'],
            [_x('Huatan Township', 'TW Changhua County', 'ry-wc-city-select'), '503'],
            [_x('Xiushui Township', 'TW Changhua County', 'ry-wc-city-select'), '504'],
            [_x('Lukang Township', 'TW Changhua County', 'ry-wc-city-select'), '505'],
            [_x('Fuxing Township', 'TW Changhua County', 'ry-wc-city-select'), '506'],
            [_x('Xianxi Township', 'TW Changhua County', 'ry-wc-city-select'), '507'],
            [_x('Hemei Township', 'TW Changhua County', 'ry-wc-city-select'), '508'],
            [_x('Shengang Township', 'TW Changhua County', 'ry-wc-city-select'), '509'],
            [_x('Yuanlin City', 'TW Changhua County', 'ry-wc-city-select'), '510'],
            [_x('Shetou Township', 'TW Changhua County', 'ry-wc-city-select'), '511'],
            [_x('Yongjing Township', 'TW Changhua County', 'ry-wc-city-select'), '512'],
            [_x('Puxin Township', 'TW Changhua County', 'ry-wc-city-select'), '513'],
            [_x('Xihu Township', 'TW Changhua County', 'ry-wc-city-select'), '514'],
            [_x('Dacun Township', 'TW Changhua County', 'ry-wc-city-select'), '515'],
            [_x('Puyan Township', 'TW Changhua County', 'ry-wc-city-select'), '516'],
            [_x('Tianzhong Township', 'TW Changhua County', 'ry-wc-city-select'), '520'],
            [_x('Beidou Township', 'TW Changhua County', 'ry-wc-city-select'), '521'],
            [_x('Tianwei Township', 'TW Changhua County', 'ry-wc-city-select'), '522'],
            [_x('Pitou Township', 'TW Changhua County', 'ry-wc-city-select'), '523'],
            [_x('Xizhou Township', 'TW Changhua County', 'ry-wc-city-select'), '524'],
            [_x('Zhutang Township', 'TW Changhua County', 'ry-wc-city-select'), '525'],
            [_x('Erlin Township', 'TW Changhua County', 'ry-wc-city-select'), '526'],
            [_x('Dacheng Township', 'TW Changhua County', 'ry-wc-city-select'), '527'],
            [_x('Fangyuan Township', 'TW Changhua County', 'ry-wc-city-select'), '528'],
            [_x('Ershui Township', 'TW Changhua County', 'ry-wc-city-select'), '530']
        ],
        'NANTOU COUNTY' => [
            [_x('Nantou City', 'TW Nantou County', 'ry-wc-city-select'), '540'],
            [_x('Zhongliao Township', 'TW Nantou County', 'ry-wc-city-select'), '541'],
            [_x('Caotun Township', 'TW Nantou County', 'ry-wc-city-select'), '542'],
            [_x('Guoxing Township', 'TW Nantou County', 'ry-wc-city-select'), '544'],
            [_x('Puli Township', 'TW Nantou County', 'ry-wc-city-select'), '545'],
            [_x('Renai Township', 'TW Nantou County', 'ry-wc-city-select'), '546'],
            [_x('Mingjian Township', 'TW Nantou County', 'ry-wc-city-select'), '551'],
            [_x('Jiji Township', 'TW Nantou County', 'ry-wc-city-select'), '552'],
            [_x('Shuili Township', 'TW Nantou County', 'ry-wc-city-select'), '553'],
            [_x('Yuchi Township', 'TW Nantou County', 'ry-wc-city-select'), '555'],
            [_x('Xinyi Township', 'TW Nantou County', 'ry-wc-city-select'), '556'],
            [_x('Zhushan Township', 'TW Nantou County', 'ry-wc-city-select'), '557'],
            [_x('Lugu Township', 'TW Nantou County', 'ry-wc-city-select'), '558']
        ],
        'CHIAYI CITY' => [
            [_x('East Dist', 'TW Chiayi City', 'ry-wc-city-select'), '600'],
            [_x('West Dist', 'TW Chiayi City', 'ry-wc-city-select'), '600']
        ],
        'CHIAYI COUNTY' => [
            [_x('Fanlu Township', 'TW Chiayi County', 'ry-wc-city-select'), '602'],
            [_x('Meishan Township', 'TW Chiayi County', 'ry-wc-city-select'), '603'],
            [_x('Zhuqi Township', 'TW Chiayi County', 'ry-wc-city-select'), '604'],
            [_x('Alishan Township', 'TW Chiayi County', 'ry-wc-city-select'), '605'],
            [_x('Zhongpu Township', 'TW Chiayi County', 'ry-wc-city-select'), '606'],
            [_x('Dapu Township', 'TW Chiayi County', 'ry-wc-city-select'), '607'],
            [_x('Shuishang Township', 'TW Chiayi County', 'ry-wc-city-select'), '608'],
            [_x('Lucao Township', 'TW Chiayi County', 'ry-wc-city-select'), '611'],
            [_x('Taibao City', 'TW Chiayi County', 'ry-wc-city-select'), '612'],
            [_x('Puzi City', 'TW Chiayi County', 'ry-wc-city-select'), '613'],
            [_x('Dongshi Township', 'TW Chiayi County', 'ry-wc-city-select'), '614'],
            [_x('Liujiao Township', 'TW Chiayi County', 'ry-wc-city-select'), '615'],
            [_x('Xingang Township', 'TW Chiayi County', 'ry-wc-city-select'), '616'],
            [_x('Minxiong Township', 'TW Chiayi County', 'ry-wc-city-select'), '621'],
            [_x('Dalin Township', 'TW Chiayi County', 'ry-wc-city-select'), '622'],
            [_x('Xikou Township', 'TW Chiayi County', 'ry-wc-city-select'), '623'],
            [_x('Yizhu Township', 'TW Chiayi County', 'ry-wc-city-select'), '624'],
            [_x('Budai Township', 'TW Chiayi County', 'ry-wc-city-select'), '625']
        ],
        'YUNLIN COUNTY' => [
            [_x('Dounan Township', 'TW Yunlin County', 'ry-wc-city-select'), '630'],
            [_x('Dapi Township', 'TW Yunlin County', 'ry-wc-city-select'), '631'],
            [_x('Huwei Township', 'TW Yunlin County', 'ry-wc-city-select'), '632'],
            [_x('Tuku Township', 'TW Yunlin County', 'ry-wc-city-select'), '633'],
            [_x('Baozhong Township', 'TW Yunlin County', 'ry-wc-city-select'), '634'],
            [_x('Dongshi Township', 'TW Yunlin County', 'ry-wc-city-select'), '635'],
            [_x('Taixi Township', 'TW Yunlin County', 'ry-wc-city-select'), '636'],
            [_x('Lunbei Township', 'TW Yunlin County', 'ry-wc-city-select'), '637'],
            [_x('Mailiao Township', 'TW Yunlin County', 'ry-wc-city-select'), '638'],
            [_x('Douliu City', 'TW Yunlin County', 'ry-wc-city-select'), '640'],
            [_x('Linnei Township', 'TW Yunlin County', 'ry-wc-city-select'), '643'],
            [_x('Gukeng Township', 'TW Yunlin County', 'ry-wc-city-select'), '646'],
            [_x('Citong Township', 'TW Yunlin County', 'ry-wc-city-select'), '647'],
            [_x('Xiluo Township', 'TW Yunlin County', 'ry-wc-city-select'), '648'],
            [_x('Erlun Township', 'TW Yunlin County', 'ry-wc-city-select'), '649'],
            [_x('Beigang Township', 'TW Yunlin County', 'ry-wc-city-select'), '651'],
            [_x('Shuilin Township', 'TW Yunlin County', 'ry-wc-city-select'), '652'],
            [_x('Kouhu Township', 'TW Yunlin County', 'ry-wc-city-select'), '653'],
            [_x('Sihu Township', 'TW Yunlin County', 'ry-wc-city-select'), '654'],
            [_x('Yuanzhang Township', 'TW Yunlin County', 'ry-wc-city-select'), '655']
        ],
        'TAINAN CITY' => [
            [_x('West Central Dist', 'TW Tainan City', 'ry-wc-city-select'), '700'],
            [_x('East Dist', 'TW Tainan City', 'ry-wc-city-select'), '701'],
            [_x('South Dist', 'TW Tainan City', 'ry-wc-city-select'), '702'],
            [_x('North Dist', 'TW Tainan City', 'ry-wc-city-select'), '704'],
            [_x('Anping Dist', 'TW Tainan City', 'ry-wc-city-select'), '708'],
            [_x('Annan Dist', 'TW Tainan City', 'ry-wc-city-select'), '709'],
            [_x('Yongkang Dist', 'TW Tainan City', 'ry-wc-city-select'), '710'],
            [_x('Guiren Dist', 'TW Tainan City', 'ry-wc-city-select'), '711'],
            [_x('Xinhua Dist', 'TW Tainan City', 'ry-wc-city-select'), '712'],
            [_x('Zuozhen Dist', 'TW Tainan City', 'ry-wc-city-select'), '713'],
            [_x('Yujing Dist', 'TW Tainan City', 'ry-wc-city-select'), '714'],
            [_x('Nanxi Dist', 'TW Tainan City', 'ry-wc-city-select'), '715'],
            [_x('Nanhua Dist', 'TW Tainan City', 'ry-wc-city-select'), '716'],
            [_x('Rende Dist', 'TW Tainan City', 'ry-wc-city-select'), '717'],
            [_x('Guanmiao Dist', 'TW Tainan City', 'ry-wc-city-select'), '718'],
            [_x('Longqi Dist', 'TW Tainan City', 'ry-wc-city-select'), '719'],
            [_x('Guantian Dist', 'TW Tainan City', 'ry-wc-city-select'), '720'],
            [_x('Madou Dist', 'TW Tainan City', 'ry-wc-city-select'), '721'],
            [_x('Jiali Dist', 'TW Tainan City', 'ry-wc-city-select'), '722'],
            [_x('Xigang Dist', 'TW Tainan City', 'ry-wc-city-select'), '723'],
            [_x('Qigu Dist', 'TW Tainan City', 'ry-wc-city-select'), '724'],
            [_x('Jiangjun Dist', 'TW Tainan City', 'ry-wc-city-select'), '725'],
            [_x('Xuejia Dist', 'TW Tainan City', 'ry-wc-city-select'), '726'],
            [_x('Beimen Dist', 'TW Tainan City', 'ry-wc-city-select'), '727'],
            [_x('Xinying Dist', 'TW Tainan City', 'ry-wc-city-select'), '730'],
            [_x('Houbi Dist', 'TW Tainan City', 'ry-wc-city-select'), '731'],
            [_x('Baihe Dist', 'TW Tainan City', 'ry-wc-city-select'), '732'],
            [_x('Dongshan Dist', 'TW Tainan City', 'ry-wc-city-select'), '733'],
            [_x('Liujia Dist', 'TW Tainan City', 'ry-wc-city-select'), '734'],
            [_x('Xiaying Dist', 'TW Tainan City', 'ry-wc-city-select'), '735'],
            [_x('Liuying Dist', 'TW Tainan City', 'ry-wc-city-select'), '736'],
            [_x('Yanshui Dist', 'TW Tainan City', 'ry-wc-city-select'), '737'],
            [_x('Shanhua Dist', 'TW Tainan City', 'ry-wc-city-select'), '741'],
            [_x('Danei Dist', 'TW Tainan City', 'ry-wc-city-select'), '742'],
            [_x('Shanshang Dist', 'TW Tainan City', 'ry-wc-city-select'), '743'],
            [_x('Xinshi Dist', 'TW Tainan City', 'ry-wc-city-select'), '744'],
            [_x('Anding Dist', 'TW Tainan City', 'ry-wc-city-select'), '745']
        ],
        'KAOHSIUNG CITY' => [
            [_x('Xinxing Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '800'],
            [_x('Qianjin Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '801'],
            [_x('Lingya Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '802'],
            [_x('Yancheng Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '803'],
            [_x('Gushan Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '804'],
            [_x('Qijin Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '805'],
            [_x('Qianzhen Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '806'],
            [_x('Sanmin Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '807'],
            [_x('Nanzi Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '811'],
            [_x('Xiaogang Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '812'],
            [_x('Zuoying Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '813'],
            [_x('Renwu Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '814'],
            [_x('Dashe Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '815'],
            [_x('Dongsha Islands', 'TW Nanhai Islands', 'ry-wc-city-select'), '817'],
            [_x('Nansha Islands', 'TW Nanhai Islands', 'ry-wc-city-select'), '819'],
            [_x('Gangshan Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '820'],
            [_x('Luzhu Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '821'],
            [_x('Alian Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '822'],
            [_x('Tianliao Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '823'],
            [_x('Yanchao Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '824'],
            [_x('Qiaotou Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '825'],
            [_x('Ziguan Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '826'],
            [_x('Mituo Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '827'],
            [_x('Yongan Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '828'],
            [_x('Hunei Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '829'],
            [_x('Fengshan Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '830'],
            [_x('Daliao Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '831'],
            [_x('Linyuan Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '832'],
            [_x('Niaosong Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '833'],
            [_x('Dashu Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '840'],
            [_x('Qishan Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '842'],
            [_x('Meinong Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '843'],
            [_x('Liugui Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '844'],
            [_x('Neimen Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '845'],
            [_x('Shanlin Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '846'],
            [_x('Jiaxian Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '847'],
            [_x('Taoyuan Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '848'],
            [_x('Namaxia Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '849'],
            [_x('Maolin Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '851'],
            [_x('Qieding Dist', 'TW Kaohsiung City', 'ry-wc-city-select'), '852']
        ],
        'PENGHU COUNTY' => [
            [_x('Magong City', 'TW Penghu County', 'ry-wc-city-select'), '880'],
            [_x('Xiyu Township', 'TW Penghu County', 'ry-wc-city-select'), '881'],
            [_x('Wangan Township', 'TW Penghu County', 'ry-wc-city-select'), '882'],
            [_x('Qimei Township', 'TW Penghu County', 'ry-wc-city-select'), '883'],
            [_x('Baisha Township', 'TW Penghu County', 'ry-wc-city-select'), '884'],
            [_x('Huxi Township', 'TW Penghu County', 'ry-wc-city-select'), '885']
        ],
        'KINMEN COUNTY' => [
            [_x('Jinsha Township', 'TW Kinmen County', 'ry-wc-city-select'), '890'],
            [_x('Jinhu Township', 'TW Kinmen County', 'ry-wc-city-select'), '891'],
            [_x('Jinning Township', 'TW Kinmen County', 'ry-wc-city-select'), '892'],
            [_x('Jincheng Township', 'TW Kinmen County', 'ry-wc-city-select'), '893'],
            [_x('Lieyu Township', 'TW Kinmen County', 'ry-wc-city-select'), '894'],
            [_x('Wuqiu Township', 'TW Kinmen County', 'ry-wc-city-select'), '896']
        ],
        'PINGTUNG COUNTY' => [
            [_x('Pingtung City', 'TW Pingtung County', 'ry-wc-city-select'), '900'],
            [_x('Sandimen Township', 'TW Pingtung County', 'ry-wc-city-select'), '901'],
            [_x('Wutai Township', 'TW Pingtung County', 'ry-wc-city-select'), '902'],
            [_x('Majia Township', 'TW Pingtung County', 'ry-wc-city-select'), '903'],
            [_x('Jiuru Township', 'TW Pingtung County', 'ry-wc-city-select'), '904'],
            [_x('Ligang Township', 'TW Pingtung County', 'ry-wc-city-select'), '905'],
            [_x('Gaoshu Township', 'TW Pingtung County', 'ry-wc-city-select'), '906'],
            [_x('Yanpu Township', 'TW Pingtung County', 'ry-wc-city-select'), '907'],
            [_x('Changzhi Township', 'TW Pingtung County', 'ry-wc-city-select'), '908'],
            [_x('Linluo Township', 'TW Pingtung County', 'ry-wc-city-select'), '909'],
            [_x('Zhutian Township', 'TW Pingtung County', 'ry-wc-city-select'), '911'],
            [_x('Neipu Township', 'TW Pingtung County', 'ry-wc-city-select'), '912'],
            [_x('Wandan Township', 'TW Pingtung County', 'ry-wc-city-select'), '913'],
            [_x('Chaozhou Township', 'TW Pingtung County', 'ry-wc-city-select'), '920'],
            [_x('Taiwu Township', 'TW Pingtung County', 'ry-wc-city-select'), '921'],
            [_x('Laiyi Township', 'TW Pingtung County', 'ry-wc-city-select'), '922'],
            [_x('Wanluan Township', 'TW Pingtung County', 'ry-wc-city-select'), '923'],
            [_x('Kanding Township', 'TW Pingtung County', 'ry-wc-city-select'), '924'],
            [_x('Xinpi Township', 'TW Pingtung County', 'ry-wc-city-select'), '925'],
            [_x('Nanzhou Township', 'TW Pingtung County', 'ry-wc-city-select'), '926'],
            [_x('Linbian Township', 'TW Pingtung County', 'ry-wc-city-select'), '927'],
            [_x('Donggang Township', 'TW Pingtung County', 'ry-wc-city-select'), '928'],
            [_x('Liuqiu Township', 'TW Pingtung County', 'ry-wc-city-select'), '929'],
            [_x('Jiadong Township', 'TW Pingtung County', 'ry-wc-city-select'), '931'],
            [_x('Xinyuan Township', 'TW Pingtung County', 'ry-wc-city-select'), '932'],
            [_x('Fangliao Township', 'TW Pingtung County', 'ry-wc-city-select'), '940'],
            [_x('Fangshan Township', 'TW Pingtung County', 'ry-wc-city-select'), '941'],
            [_x('Chunri Township', 'TW Pingtung County', 'ry-wc-city-select'), '942'],
            [_x('Shizi Township', 'TW Pingtung County', 'ry-wc-city-select'), '943'],
            [_x('Checheng Township', 'TW Pingtung County', 'ry-wc-city-select'), '944'],
            [_x('Mudan Township', 'TW Pingtung County', 'ry-wc-city-select'), '945'],
            [_x('Hengchun Township', 'TW Pingtung County', 'ry-wc-city-select'), '946'],
            [_x('Manzhou Township', 'TW Pingtung County', 'ry-wc-city-select'), '947']
        ],
        'TAITUNG COUNTY' => [
            [_x('Taitung City', 'TW Taitung County', 'ry-wc-city-select'), '950'],
            [_x('Ludao Township', 'TW Taitung County', 'ry-wc-city-select'), '951'],
            [_x('Lanyu Township', 'TW Taitung County', 'ry-wc-city-select'), '952'],
            [_x('Yanping Township', 'TW Taitung County', 'ry-wc-city-select'), '953'],
            [_x('Beinan Township', 'TW Taitung County', 'ry-wc-city-select'), '954'],
            [_x('Luye Township', 'TW Taitung County', 'ry-wc-city-select'), '955'],
            [_x('Guanshan Township', 'TW Taitung County', 'ry-wc-city-select'), '956'],
            [_x('Haiduan Township', 'TW Taitung County', 'ry-wc-city-select'), '957'],
            [_x('Chishang Township', 'TW Taitung County', 'ry-wc-city-select'), '958'],
            [_x('Donghe Township', 'TW Taitung County', 'ry-wc-city-select'), '959'],
            [_x('Chenggong Township', 'TW Taitung County', 'ry-wc-city-select'), '961'],
            [_x('Changbin Township', 'TW Taitung County', 'ry-wc-city-select'), '962'],
            [_x('Taimali Township', 'TW Taitung County', 'ry-wc-city-select'), '963'],
            [_x('Jinfeng Township', 'TW Taitung County', 'ry-wc-city-select'), '964'],
            [_x('Dawu Township', 'TW Taitung County', 'ry-wc-city-select'), '965'],
            [_x('Daren Township', 'TW Taitung County', 'ry-wc-city-select'), '966']
        ],
        'HUALIEN COUNTY' => [
            [_x('Hualien City', 'TW Hualien County', 'ry-wc-city-select'), '970'],
            [_x('Xincheng Township', 'TW Hualien County', 'ry-wc-city-select'), '971'],
            [_x('Xiulin Township', 'TW Hualien County', 'ry-wc-city-select'), '972'],
            [_x('Jian Township', 'TW Hualien County', 'ry-wc-city-select'), '973'],
            [_x('Shoufeng Township', 'TW Hualien County', 'ry-wc-city-select'), '974'],
            [_x('Fenglin Township', 'TW Hualien County', 'ry-wc-city-select'), '975'],
            [_x('Guangfu Township', 'TW Hualien County', 'ry-wc-city-select'), '976'],
            [_x('Fengbin Township', 'TW Hualien County', 'ry-wc-city-select'), '977'],
            [_x('Ruisui Township', 'TW Hualien County', 'ry-wc-city-select'), '978'],
            [_x('Wanrong Township', 'TW Hualien County', 'ry-wc-city-select'), '979'],
            [_x('Yuli Township', 'TW Hualien County', 'ry-wc-city-select'), '981'],
            [_x('Zhuoxi Township', 'TW Hualien County', 'ry-wc-city-select'), '982'],
            [_x('Fuli Township', 'TW Hualien County', 'ry-wc-city-select'), '983']
        ]
    ]
];
