<?php

return [
    'KW' => [
        'AHMADI' => [
            _x('Abdulla Port', 'Ahmadi', 'ry-wc-city-select'),
            _x('Abu Halifa', 'Ahmadi', 'ry-wc-city-select'),
            _x('Ahmadi', 'Ahmadi', 'ry-wc-city-select'),
            _x('Al Khiran Pearl City', 'Ahmadi', 'ry-wc-city-select'),
            _x('Al Zour', 'Ahmadi', 'ry-wc-city-select'),
            _x('Ali Sabah Al Salem', 'Ahmadi', 'ry-wc-city-select'),
            _x('Aqeela', 'Ahmadi', 'ry-wc-city-select'),
            _x('Bnaider', 'Ahmadi', 'ry-wc-city-select'),
            _x('Fahad Al Ahmed Area', 'Ahmadi', 'ry-wc-city-select'),
            _x('Fahaheel', 'Ahmadi', 'ry-wc-city-select'),
            _x('Fahaheel Industrial', 'Ahmadi', 'ry-wc-city-select'),
            _x('Fintas', 'Ahmadi', 'ry-wc-city-select'),
            _x('Hadiya', 'Ahmadi', 'ry-wc-city-select'),
            _x('Hijil', 'Ahmadi', 'ry-wc-city-select'),
            _x('Jaber Al Ali', 'Ahmadi', 'ry-wc-city-select'),
            _x('Julaiya', 'Ahmadi', 'ry-wc-city-select'),
            _x('Khiran City', 'Ahmadi', 'ry-wc-city-select'),
            _x('Mahboula', 'Ahmadi', 'ry-wc-city-select'),
            _x('Manqaf', 'Ahmadi', 'ry-wc-city-select'),
            _x('Minaa Abdulla', 'Ahmadi', 'ry-wc-city-select'),
            _x('Nuwaiseeb', 'Ahmadi', 'ry-wc-city-select'),
            _x('Riqqa', 'Ahmadi', 'ry-wc-city-select'),
            _x('Sabah Al Ahmad', 'Ahmadi', 'ry-wc-city-select'),
            _x('Sabahiya', 'Ahmadi', 'ry-wc-city-select'),
            _x('Shuaiba Industrial Area', 'Ahmadi', 'ry-wc-city-select'),
            _x('South Sabahiyah', 'Ahmadi', 'ry-wc-city-select'),
            _x('Wafra', 'Ahmadi', 'ry-wc-city-select'),
            _x('Khairan', 'Ahmadi', 'ry-wc-city-select'),
            _x('Dhaher', 'Ahmadi', 'ry-wc-city-select'),
            _x('Abu Hasaniya', 'Ahmadi', 'ry-wc-city-select')
        ],
        'FARWANIYAH' => [
            _x('Abdulla Al Mubarak Al Sabah', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Abraq Khaitan', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Al Rabiah', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Al Shadadiya', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Andalous', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Ardiya', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Ardiya Industrial', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Dhajeej', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Farwaniyah', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Firdous', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Ishbilya', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Jeleeb Shoyoukh', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Khaitan', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Kuwait International Airport', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Omariyah', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Qurtuba', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Rai', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Regiee', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Rehab', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Sabah Al Naser', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Jaleeb Al-Shyoukh', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Dajeej', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Al Hasawi', 'Farwaniyah', 'ry-wc-city-select'),
            _x('Abbasiyah', 'Farwaniyah', 'ry-wc-city-select')
        ],
        'HAWALLY' => [
            _x('Al Bidaa', 'Hawally', 'ry-wc-city-select'),
            _x('Al Salam', 'Hawally', 'ry-wc-city-select'),
            _x('Al Shuhada', 'Hawally', 'ry-wc-city-select'),
            _x('Bayan', 'Hawally', 'ry-wc-city-select'),
            _x('Hateen', 'Hawally', 'ry-wc-city-select'),
            _x('Hawally', 'Hawally', 'ry-wc-city-select'),
            _x('Jabriya', 'Hawally', 'ry-wc-city-select'),
            _x('Mishref', 'Hawally', 'ry-wc-city-select'),
            _x('Mubarak Al Abdulla Al Jaber Area', 'Hawally', 'ry-wc-city-select'),
            _x('Rumaithiya', 'Hawally', 'ry-wc-city-select'),
            _x('Salmiya', 'Hawally', 'ry-wc-city-select'),
            _x('Salwa', 'Hawally', 'ry-wc-city-select'),
            _x('Sha\'ab', 'Hawally', 'ry-wc-city-select'),
            _x('Sideeq', 'Hawally', 'ry-wc-city-select'),
            _x('Zahra', 'Hawally', 'ry-wc-city-select')
        ],
        'JAHRA' => [
            _x('A\'youn', 'Jahra', 'ry-wc-city-select'),
            _x('Abdali', 'Jahra', 'ry-wc-city-select'),
            _x('Al Jahra', 'Jahra', 'ry-wc-city-select'),
            _x('Amghara Industrial Area', 'Jahra', 'ry-wc-city-select'),
            _x('Jahra Industrial Area', 'Jahra', 'ry-wc-city-select'),
            _x('Naeem', 'Jahra', 'ry-wc-city-select'),
            _x('Nahda', 'Jahra', 'ry-wc-city-select'),
            _x('Nassem', 'Jahra', 'ry-wc-city-select'),
            _x('Qasr', 'Jahra', 'ry-wc-city-select'),
            _x('Qeirawan', 'Jahra', 'ry-wc-city-select'),
            _x('Saad Abdullah City', 'Jahra', 'ry-wc-city-select'),
            _x('Sabriya', 'Jahra', 'ry-wc-city-select'),
            _x('Sulaibiyah', 'Jahra', 'ry-wc-city-select'),
            _x('Sulaibiyah Industrial Area', 'Jahra', 'ry-wc-city-select'),
            _x('Taima', 'Jahra', 'ry-wc-city-select'),
            _x('Umm Al Aish', 'Jahra', 'ry-wc-city-select'),
            _x('Waha', 'Jahra', 'ry-wc-city-select'),
            _x('Doha', 'Jahra', 'ry-wc-city-select'),
            _x('Granada', 'Jahra', 'ry-wc-city-select'),
            _x('Jabir Al Ahmad', 'Jahra', 'ry-wc-city-select'),
            _x('Qairawan', 'Jahra', 'ry-wc-city-select'),
            _x('Kabd', 'Jahra', 'ry-wc-city-select'),
            _x('Jabir Al Ahmad', 'Jahra', 'ry-wc-city-select'),
            _x('Jaber Al Ahmad', 'Jahra', 'ry-wc-city-select'),
            _x('Granada', 'Jahra', 'ry-wc-city-select'),
            _x('Doha', 'Jahra', 'ry-wc-city-select'),
            _x('Amghara', 'Jahra', 'ry-wc-city-select'),
            _x('Al Salmi', 'Jahra', 'ry-wc-city-select'),
            _x('Al Qaysariya', 'Jahra', 'ry-wc-city-select'),
            _x('Al Metlaa', 'Jahra', 'ry-wc-city-select'),
            _x('Al Jahra', 'Jahra', 'ry-wc-city-select')
        ],
        'KUWAIT CITY' => [
            _x('Abdulla Al Salem', 'Kuwait City', 'ry-wc-city-select'),
            _x('Adailiya', 'Kuwait City', 'ry-wc-city-select'),
            _x('Al Soor', 'Kuwait City', 'ry-wc-city-select'),
            _x('Beneid Al Gar', 'Kuwait City', 'ry-wc-city-select'),
            _x('Daiya', 'Kuwait City', 'ry-wc-city-select'),
            _x('Dasma', 'Kuwait City', 'ry-wc-city-select'),
            _x('Dasman', 'Kuwait City', 'ry-wc-city-select'),
            _x('Faiha', 'Kuwait City', 'ry-wc-city-select'),
            _x('Kaifan', 'Kuwait City', 'ry-wc-city-select'),
            _x('Khaldiya', 'Kuwait City', 'ry-wc-city-select'),
            _x('Kuwait City', 'Kuwait City', 'ry-wc-city-select'),
            _x('Mansouriya', 'Kuwait City', 'ry-wc-city-select'),
            _x('Mirqab', 'Kuwait City', 'ry-wc-city-select'),
            _x('North West Sulaibikhat', 'Kuwait City', 'ry-wc-city-select'),
            _x('Nuzha', 'Kuwait City', 'ry-wc-city-select'),
            _x('Qadsiya', 'Kuwait City', 'ry-wc-city-select'),
            _x('Qiblah', 'Kuwait City', 'ry-wc-city-select'),
            _x('Qurtuba', 'Kuwait City', 'ry-wc-city-select'),
            _x('Rawda', 'Kuwait City', 'ry-wc-city-select'),
            _x('Shamiyah', 'Kuwait City', 'ry-wc-city-select'),
            _x('Sharq', 'Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh', 'Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh Education Area', 'Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh Health Area', 'Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh Industrial Area', 'Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh Port', 'Kuwait City', 'ry-wc-city-select'),
            _x('Sulaibikhat', 'Kuwait City', 'ry-wc-city-select'),
            _x('Surra', 'Kuwait City', 'ry-wc-city-select'),
            _x('Um Seddah', 'Kuwait City', 'ry-wc-city-select'),
            _x('Yarmouk', 'Kuwait City', 'ry-wc-city-select'),
            _x('Al Mubarakyia', 'Kuwait City', 'ry-wc-city-select'),
            _x('Al Wetiyah', 'Kuwait City', 'ry-wc-city-select'),
            _x('Safat', 'Kuwait City', 'ry-wc-city-select'),
            _x('Salhiya', 'Kuwait City', 'ry-wc-city-select'),
            _x('Sawaber', 'Kuwait City', 'ry-wc-city-select')
        ],
        'MUBARAK AL KABEER' => [
            _x('Abu Fateera', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Abu Hasaniya', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Al Adan', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Dhaher', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Funaitees', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Messila', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Mubarak Al Kabeer', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Qurain', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Qusor', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Sabah Al Salem', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Sabhan', 'Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Masayel', 'Mubarak Al Kabeer', 'ry-wc-city-select')
        ]
    ]
];
