<?php

return [
    'KW' => [
        'AHMADI' => [
            _x('Abdulla Port', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Abu Halifa', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Ahmadi', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Al Khiran Pearl City', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Al Zour', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Ali Sabah Al Salem', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Aqeela', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Bnaider', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Fahad Al Ahmed Area', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Fahaheel', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Fahaheel Industrial', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Fintas', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Hadiya', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Hijil', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Jaber Al Ali', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Julaiya', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Khiran City', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Mahboula', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Manqaf', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Minaa Abdulla', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Nuwaiseeb', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Riqqa', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Sabah Al Ahmad', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Sabahiya', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Shuaiba Industrial Area', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('South Sabahiyah', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Wafra', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Khairan', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Dhaher', 'KW Ahmadi', 'ry-wc-city-select'),
            _x('Abu Hasaniya', 'KW Ahmadi', 'ry-wc-city-select'),
        ],
        'FARWANIYAH' => [
            _x('Abdulla Al Mubarak Al Sabah', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Abraq Khaitan', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Al Rabiah', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Al Shadadiya', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Andalous', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Ardiya', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Ardiya Industrial', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Dhajeej', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Farwaniyah', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Firdous', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Ishbilya', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Jeleeb Shoyoukh', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Khaitan', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Kuwait International Airport', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Omariyah', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Qurtuba', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Rai', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Regiee', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Rehab', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Sabah Al Naser', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Jaleeb Al-Shyoukh', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Dajeej', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Al Hasawi', 'KW Farwaniyah', 'ry-wc-city-select'),
            _x('Abbasiyah', 'KW Farwaniyah', 'ry-wc-city-select'),
        ],
        'HAWALLY' => [
            _x('Al Bidaa', 'KW Hawally', 'ry-wc-city-select'),
            _x('Al Salam', 'KW Hawally', 'ry-wc-city-select'),
            _x('Al Shuhada', 'KW Hawally', 'ry-wc-city-select'),
            _x('Bayan', 'KW Hawally', 'ry-wc-city-select'),
            _x('Hateen', 'KW Hawally', 'ry-wc-city-select'),
            _x('Hawally', 'KW Hawally', 'ry-wc-city-select'),
            _x('Jabriya', 'KW Hawally', 'ry-wc-city-select'),
            _x('Mishref', 'KW Hawally', 'ry-wc-city-select'),
            _x('Mubarak Al Abdulla Al Jaber Area', 'KW Hawally', 'ry-wc-city-select'),
            _x('Rumaithiya', 'KW Hawally', 'ry-wc-city-select'),
            _x('Salmiya', 'KW Hawally', 'ry-wc-city-select'),
            _x('Salwa', 'KW Hawally', 'ry-wc-city-select'),
            _x('Sha\'ab', 'KW Hawally', 'ry-wc-city-select'),
            _x('Sideeq', 'KW Hawally', 'ry-wc-city-select'),
            _x('Zahra', 'KW Hawally', 'ry-wc-city-select'),
        ],
        'JAHRA' => [
            _x('A\'youn', 'KW Jahra', 'ry-wc-city-select'),
            _x('Abdali', 'KW Jahra', 'ry-wc-city-select'),
            _x('Al Jahra', 'KW Jahra', 'ry-wc-city-select'),
            _x('Amghara Industrial Area', 'KW Jahra', 'ry-wc-city-select'),
            _x('Jahra Industrial Area', 'KW Jahra', 'ry-wc-city-select'),
            _x('Naeem', 'KW Jahra', 'ry-wc-city-select'),
            _x('Nahda', 'KW Jahra', 'ry-wc-city-select'),
            _x('Nassem', 'KW Jahra', 'ry-wc-city-select'),
            _x('Qasr', 'KW Jahra', 'ry-wc-city-select'),
            _x('Qeirawan', 'KW Jahra', 'ry-wc-city-select'),
            _x('Saad Abdullah City', 'KW Jahra', 'ry-wc-city-select'),
            _x('Sabriya', 'KW Jahra', 'ry-wc-city-select'),
            _x('Sulaibiyah', 'KW Jahra', 'ry-wc-city-select'),
            _x('Sulaibiyah Industrial Area', 'KW Jahra', 'ry-wc-city-select'),
            _x('Taima', 'KW Jahra', 'ry-wc-city-select'),
            _x('Umm Al Aish', 'KW Jahra', 'ry-wc-city-select'),
            _x('Waha', 'KW Jahra', 'ry-wc-city-select'),
            _x('Doha', 'KW Jahra', 'ry-wc-city-select'),
            _x('Granada', 'KW Jahra', 'ry-wc-city-select'),
            _x('Jabir Al Ahmad', 'KW Jahra', 'ry-wc-city-select'),
            _x('Qairawan', 'KW Jahra', 'ry-wc-city-select'),
            _x('Kabd', 'KW Jahra', 'ry-wc-city-select'),
            _x('Jabir Al Ahmad', 'KW Jahra', 'ry-wc-city-select'),
            _x('Jaber Al Ahmad', 'KW Jahra', 'ry-wc-city-select'),
            _x('Granada', 'KW Jahra', 'ry-wc-city-select'),
            _x('Doha', 'KW Jahra', 'ry-wc-city-select'),
            _x('Amghara', 'KW Jahra', 'ry-wc-city-select'),
            _x('Al Salmi', 'KW Jahra', 'ry-wc-city-select'),
            _x('Al Qaysariya', 'KW Jahra', 'ry-wc-city-select'),
            _x('Al Metlaa', 'KW Jahra', 'ry-wc-city-select'),
        ],
        'KUWAIT CITY' => [
            _x('Abdulla Al Salem', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Adailiya', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Al Soor', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Beneid Al Gar', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Daiya', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Dasma', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Dasman', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Faiha', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Kaifan', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Khaldiya', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Kuwait City', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Mansouriya', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Mirqab', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('North West Sulaibikhat', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Nuzha', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Qadsiya', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Qiblah', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Qurtuba', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Rawda', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Shamiyah', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Sharq', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh Education Area', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh Health Area', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh Industrial Area', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Shuwaikh Port', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Sulaibikhat', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Surra', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Um Seddah', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Yarmouk', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Al Mubarakyia', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Al Wetiyah', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Safat', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Salhiya', 'KW Kuwait City', 'ry-wc-city-select'),
            _x('Sawaber', 'KW Kuwait City', 'ry-wc-city-select'),
        ],
        'MUBARAK AL KABEER' => [
            _x('Abu Fateera', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Abu Hasaniya', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Al Adan', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Dhaher', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Funaitees', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Messila', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Mubarak Al Kabeer', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Qurain', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Qusor', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Sabah Al Salem', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Sabhan', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
            _x('Masayel', 'KW Mubarak Al Kabeer', 'ry-wc-city-select'),
        ],
    ],
];
